-- O provedor git das organizações (site 1.4.0 e app 0.64.0), nos dez idiomas.
--   org.git*                os erros novos de conectar, listar e associar
--   site.org.git.*          o provedor conectado na aba Repositórios do site
--   site.org.repos.*        a lista da organização e a escolha no provedor
--   repos.site.*, repos.*   a lista do app, que agora só lê o que o site associou
--   repos.compare.*         "Procurar clones" em qualquer profundidade, comparado com o site
--   whatsNew.item.*         as novidades da 0.64.0
--   docs.orgRepositories.*  a página nova da documentação; docs.organizations.usage
--                           passa a dizer que os repositórios são associados no site
insert into public.translations (locale, key, value) values
  ('pt-BR', 'org.gitNotConnected', $json$"Conecte o provedor git antes de adicionar os repositórios dele."$json$::jsonb),
  ('pt-BR', 'org.gitExpired', $json$"A sessão do provedor git neste site expirou. Conecte de novo."$json$::jsonb),
  ('pt-BR', 'org.gitUnavailable', $json$"O provedor git não respondeu. Tente de novo em instantes."$json$::jsonb),
  ('pt-BR', 'site.org.git.title', $json$"Provedor git"$json$::jsonb),
  ('pt-BR', 'site.org.git.description', $json$"O owner entra no GitHub, no GitLab ou no Bitbucket por aqui e escolhe os repositórios da organização. O token de acesso fica neste site por uma hora e nunca é gravado."$json$::jsonb),
  ('pt-BR', 'site.org.git.connected', $json$"Conectado como {account}"$json$::jsonb),
  ('pt-BR', 'site.org.git.since', $json$"desde {date}"$json$::jsonb),
  ('pt-BR', 'site.org.git.notConnected', $json$"Não conectado"$json$::jsonb),
  ('pt-BR', 'site.org.git.unavailable', $json$"Ainda não disponível neste site"$json$::jsonb),
  ('pt-BR', 'site.org.git.connect', $json$"Conectar"$json$::jsonb),
  ('pt-BR', 'site.org.git.reconnect', $json$"Conectar de novo"$json$::jsonb),
  ('pt-BR', 'site.org.git.disconnect', $json$"Desconectar"$json$::jsonb),
  ('pt-BR', 'site.org.git.disconnect.title', $json$"Desconectar o {provider}"$json$::jsonb),
  ('pt-BR', 'site.org.git.disconnect.description', $json$"Os repositórios da organização continuam. Para adicionar outros do {provider}, conecte de novo."$json$::jsonb),
  ('pt-BR', 'site.org.git.disconnected', $json$"{provider} desconectado."$json$::jsonb),
  ('pt-BR', 'site.org.git.ownerOnly', $json$"Só owners conectam provedores e escolhem os repositórios."$json$::jsonb),
  ('pt-BR', 'site.org.git.done', $json$"{provider} conectado."$json$::jsonb),
  ('pt-BR', 'site.org.git.denied', $json$"A conexão com o {provider} foi cancelada."$json$::jsonb),
  ('pt-BR', 'site.org.git.failed', $json$"Não foi possível conectar o {provider}. Tente de novo."$json$::jsonb),
  ('pt-BR', 'site.org.repos.description', $json$"Os membros veem estes repositórios na página da organização no app do JayV e os clonam na pasta da organização, com o próprio acesso git."$json$::jsonb),
  ('pt-BR', 'site.org.repos.add', $json$"Adicionar repositórios"$json$::jsonb),
  ('pt-BR', 'site.org.repos.connectFirst', $json$"Conecte um provedor acima para adicionar repositórios."$json$::jsonb),
  ('pt-BR', 'site.org.repos.private', $json$"Privado"$json$::jsonb),
  ('pt-BR', 'site.org.repos.public', $json$"Público"$json$::jsonb),
  ('pt-BR', 'site.org.repos.manual', $json$"Adicionado por URL"$json$::jsonb),
  ('pt-BR', 'site.org.repos.open', $json$"Abrir no {provider}"$json$::jsonb),
  ('pt-BR', 'site.org.repos.removed', $json$"Repositório removido."$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.title', $json$"Adicionar repositórios"$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.description', $json$"O que {account} alcança no {provider}. Marque os que são da organização."$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.search', $json$"Buscar repositórios"$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.placeholder', $json$"Filtrar por nome ou descrição…"$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.loading', $json$"Carregando repositórios…"$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.empty', $json$"Nenhum repositório encontrado."$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.added', $json$"Na organização"$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.truncated', $json$"Mostrando os atualizados mais recentemente. Busque para achar os outros."$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.expired', $json$"A sessão do {provider} neste site expirou. Conecte de novo para listar os repositórios."$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.submit', $json$"Adicionar selecionados ({count})"$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.linked', $json${"one": "{count} repositório adicionado.", "other": "{count} repositórios adicionados."}$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.missing', $json$"O {provider} não mostrou estes com a conta conectada: {paths}."$json$::jsonb),
  ('pt-BR', 'repos.site.owner', $json$"Você associa os repositórios no site do JayV, entrando no GitHub, no GitLab ou no Bitbucket. Esta lista se atualiza sozinha."$json$::jsonb),
  ('pt-BR', 'repos.site.member', $json$"O owner associa os repositórios no site do JayV. Esta lista se atualiza sozinha; você clona com o seu próprio acesso git."$json$::jsonb),
  ('pt-BR', 'repos.site.none', $json$"Nenhum provedor git conectado ainda."$json$::jsonb),
  ('pt-BR', 'repos.private', $json$"Privado"$json$::jsonb),
  ('pt-BR', 'repos.public', $json$"Público"$json$::jsonb),
  ('pt-BR', 'repos.openWeb', $json$"Abrir no {provider}"$json$::jsonb),
  ('pt-BR', 'repos.compare.title', $json$"Pasta comparada com a organização"$json$::jsonb),
  ('pt-BR', 'repos.compare.description', $json$"{path}, procurada em qualquer profundidade: {found} dos {total} repositórios de {org} estão nela."$json$::jsonb),
  ('pt-BR', 'repos.compare.truncated', $json$"A busca parou antes do fim: a pasta é funda ou grande demais. Escolha uma pasta mais específica para ver tudo."$json$::jsonb),
  ('pt-BR', 'repos.compare.empty', $json$"Nada a comparar: a organização não tem repositórios e a pasta não tem clones."$json$::jsonb),
  ('pt-BR', 'repos.compare.allSet', $json$"Todos os repositórios da organização estão nesta pasta."$json$::jsonb),
  ('pt-BR', 'repos.compare.found', $json$"Na pasta"$json$::jsonb),
  ('pt-BR', 'repos.compare.project', $json$"Projeto"$json$::jsonb),
  ('pt-BR', 'repos.compare.elsewhere', $json$"Já é projeto em {path}"$json$::jsonb),
  ('pt-BR', 'repos.compare.missing', $json$"Fora da pasta"$json$::jsonb),
  ('pt-BR', 'repos.compare.localElsewhere', $json$"Neste computador em {path}"$json$::jsonb),
  ('pt-BR', 'repos.compare.cloneAll', $json$"Clonar todos"$json$::jsonb),
  ('pt-BR', 'repos.compare.outside', $json$"Fora da organização"$json$::jsonb),
  ('pt-BR', 'repos.compare.outside.hint', $json$"Clones desta pasta que a organização não tem no site. Se forem dela, o owner os associa lá."$json$::jsonb),
  ('pt-BR', 'repos.compare.noRemote', $json$"Sem remote do GitHub, do GitLab ou do Bitbucket"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.repositoriesFromSite.title', $json$"Os repositórios vêm do site"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.repositoriesFromSite.detail', $json$"O owner agora associa os repositórios da organização no site do JayV, entrando no GitHub, no GitLab ou no Bitbucket, e eles aparecem no app sozinhos. O campo para colar a URL do repositório saiu do app."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.folderCompare.title', $json$"Procurar clones olha a pasta inteira"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.folderCompare.detail', $json$"Procurar clones agora busca na pasta da organização em qualquer profundidade e compara com os repositórios do site: o que já está lá, o que falta (clone um ou todos de uma vez) e os clones que não são da organização."$json$::jsonb),
  ('pt-BR', 'docs.organizations.usage', $json$"Crie uma organização, convide membros e associe os repositórios dela no painel do site do JayV. No app, Ctrl+2 (⌘2 no Mac) abre as suas organizações e os repositórios delas."$json$::jsonb),
  ('pt-BR', 'docs.orgRepositories.title', $json$"Repositórios da organização"$json$::jsonb),
  ('pt-BR', 'docs.orgRepositories.summary', $json$"O owner associa os repositórios da organização no site do JayV, entrando no GitHub, no GitLab ou no Bitbucket. O app os lista sozinho, e cada membro os clona com o próprio acesso git."$json$::jsonb),
  ('pt-BR', 'docs.orgRepositories.usage', $json$"No site, abra a organização, vá em Repositórios, conecte um provedor e adicione os repositórios. No app, a página da organização os lista conforme mudam: escolha a pasta da organização, clone o que falta e use Procurar clones para comparar a pasta inteira, em qualquer profundidade, com a lista do site."$json$::jsonb),
  ('en', 'org.gitNotConnected', $json$"Connect the git provider before adding its repositories."$json$::jsonb),
  ('en', 'org.gitExpired', $json$"The git provider session on this site has expired. Connect it again."$json$::jsonb),
  ('en', 'org.gitUnavailable', $json$"The git provider did not respond. Try again in a moment."$json$::jsonb),
  ('en', 'site.org.git.title', $json$"Git provider"$json$::jsonb),
  ('en', 'site.org.git.description', $json$"The owner signs in to GitHub, GitLab or Bitbucket here and picks the organization's repositories. The access token stays on this site for one hour and is never saved."$json$::jsonb),
  ('en', 'site.org.git.connected', $json$"Connected as {account}"$json$::jsonb),
  ('en', 'site.org.git.since', $json$"since {date}"$json$::jsonb),
  ('en', 'site.org.git.notConnected', $json$"Not connected"$json$::jsonb),
  ('en', 'site.org.git.unavailable', $json$"Not available on this site yet"$json$::jsonb),
  ('en', 'site.org.git.connect', $json$"Connect"$json$::jsonb),
  ('en', 'site.org.git.reconnect', $json$"Connect again"$json$::jsonb),
  ('en', 'site.org.git.disconnect', $json$"Disconnect"$json$::jsonb),
  ('en', 'site.org.git.disconnect.title', $json$"Disconnect {provider}"$json$::jsonb),
  ('en', 'site.org.git.disconnect.description', $json$"The organization's repositories stay. To add more from {provider}, connect it again."$json$::jsonb),
  ('en', 'site.org.git.disconnected', $json$"{provider} disconnected."$json$::jsonb),
  ('en', 'site.org.git.ownerOnly', $json$"Only owners connect providers and choose the repositories."$json$::jsonb),
  ('en', 'site.org.git.done', $json$"{provider} connected."$json$::jsonb),
  ('en', 'site.org.git.denied', $json$"The connection with {provider} was cancelled."$json$::jsonb),
  ('en', 'site.org.git.failed', $json$"Could not connect {provider}. Try again."$json$::jsonb),
  ('en', 'site.org.repos.description', $json$"Members see these repositories on the organization page of the JayV app and clone them into their organization folder, with their own git access."$json$::jsonb),
  ('en', 'site.org.repos.add', $json$"Add repositories"$json$::jsonb),
  ('en', 'site.org.repos.connectFirst', $json$"Connect a provider above to add repositories."$json$::jsonb),
  ('en', 'site.org.repos.private', $json$"Private"$json$::jsonb),
  ('en', 'site.org.repos.public', $json$"Public"$json$::jsonb),
  ('en', 'site.org.repos.manual', $json$"Added by URL"$json$::jsonb),
  ('en', 'site.org.repos.open', $json$"Open on {provider}"$json$::jsonb),
  ('en', 'site.org.repos.removed', $json$"Repository removed."$json$::jsonb),
  ('en', 'site.org.repos.pick.title', $json$"Add repositories"$json$::jsonb),
  ('en', 'site.org.repos.pick.description', $json$"What {account} can reach on {provider}. Check the ones that belong to the organization."$json$::jsonb),
  ('en', 'site.org.repos.pick.search', $json$"Search repositories"$json$::jsonb),
  ('en', 'site.org.repos.pick.placeholder', $json$"Filter by name or description…"$json$::jsonb),
  ('en', 'site.org.repos.pick.loading', $json$"Loading repositories…"$json$::jsonb),
  ('en', 'site.org.repos.pick.empty', $json$"No repositories found."$json$::jsonb),
  ('en', 'site.org.repos.pick.added', $json$"In the organization"$json$::jsonb),
  ('en', 'site.org.repos.pick.truncated', $json$"Showing the most recently updated. Search to find the others."$json$::jsonb),
  ('en', 'site.org.repos.pick.expired', $json$"The {provider} session on this site has expired. Connect again to list the repositories."$json$::jsonb),
  ('en', 'site.org.repos.pick.submit', $json$"Add selected ({count})"$json$::jsonb),
  ('en', 'site.org.repos.pick.linked', $json${"one": "{count} repository added.", "other": "{count} repositories added."}$json$::jsonb),
  ('en', 'site.org.repos.pick.missing', $json$"{provider} did not show these with the connected account: {paths}."$json$::jsonb),
  ('en', 'repos.site.owner', $json$"You link the repositories on the JayV site, by signing in to GitHub, GitLab or Bitbucket. This list updates by itself."$json$::jsonb),
  ('en', 'repos.site.member', $json$"The owner links the repositories on the JayV site. This list updates by itself; you clone with your own git access."$json$::jsonb),
  ('en', 'repos.site.none', $json$"No git provider connected yet."$json$::jsonb),
  ('en', 'repos.private', $json$"Private"$json$::jsonb),
  ('en', 'repos.public', $json$"Public"$json$::jsonb),
  ('en', 'repos.openWeb', $json$"Open on {provider}"$json$::jsonb),
  ('en', 'repos.compare.title', $json$"Folder compared with the organization"$json$::jsonb),
  ('en', 'repos.compare.description', $json$"{path}, searched at any depth: {found} of the {total} repositories of {org} are in it."$json$::jsonb),
  ('en', 'repos.compare.truncated', $json$"The search stopped before the end: the folder is too deep or too big. Choose a narrower folder to see everything."$json$::jsonb),
  ('en', 'repos.compare.empty', $json$"Nothing to compare: the organization has no repositories and the folder has no clones."$json$::jsonb),
  ('en', 'repos.compare.allSet', $json$"Every repository of the organization is in this folder."$json$::jsonb),
  ('en', 'repos.compare.found', $json$"In the folder"$json$::jsonb),
  ('en', 'repos.compare.project', $json$"Project"$json$::jsonb),
  ('en', 'repos.compare.elsewhere', $json$"Already a project in {path}"$json$::jsonb),
  ('en', 'repos.compare.missing', $json$"Not in the folder"$json$::jsonb),
  ('en', 'repos.compare.localElsewhere', $json$"On this computer in {path}"$json$::jsonb),
  ('en', 'repos.compare.cloneAll', $json$"Clone all"$json$::jsonb),
  ('en', 'repos.compare.outside', $json$"Not in the organization"$json$::jsonb),
  ('en', 'repos.compare.outside.hint', $json$"Clones in this folder that the organization does not have on the site. If they belong to it, the owner links them there."$json$::jsonb),
  ('en', 'repos.compare.noRemote', $json$"No GitHub, GitLab or Bitbucket remote"$json$::jsonb),
  ('en', 'whatsNew.item.repositoriesFromSite.title', $json$"Repositories come from the site"$json$::jsonb),
  ('en', 'whatsNew.item.repositoriesFromSite.detail', $json$"The owner now links the organization's repositories on the JayV site, by signing in to GitHub, GitLab or Bitbucket, and they show up in the app by themselves. The field to paste a repository URL left the app."$json$::jsonb),
  ('en', 'whatsNew.item.folderCompare.title', $json$"Find clones looks at the whole folder"$json$::jsonb),
  ('en', 'whatsNew.item.folderCompare.detail', $json$"Find clones now searches the organization folder at any depth and compares it with the repositories on the site: what is already there, what is missing (clone one or all at once) and the clones that are not in the organization."$json$::jsonb),
  ('en', 'docs.organizations.usage', $json$"Create an organization, invite members and link its repositories on the JayV site dashboard. In the app, Ctrl+2 (⌘2 on Mac) opens your organizations and their repositories."$json$::jsonb),
  ('en', 'docs.orgRepositories.title', $json$"Organization repositories"$json$::jsonb),
  ('en', 'docs.orgRepositories.summary', $json$"The owner links the organization's repositories on the JayV site by signing in to GitHub, GitLab or Bitbucket. The app lists them by itself, and each member clones them with their own git access."$json$::jsonb),
  ('en', 'docs.orgRepositories.usage', $json$"On the site, open the organization, go to Repositories, connect a provider and add the repositories. In the app, the organization page lists them as they change: choose the organization folder, clone what is missing, and use Find clones to compare the whole folder, at any depth, with the list from the site."$json$::jsonb),
  ('es', 'org.gitNotConnected', $json$"Conecta el proveedor git antes de añadir sus repositorios."$json$::jsonb),
  ('es', 'org.gitExpired', $json$"La sesión del proveedor git en este sitio caducó. Vuelve a conectarlo."$json$::jsonb),
  ('es', 'org.gitUnavailable', $json$"El proveedor git no respondió. Inténtalo de nuevo en un momento."$json$::jsonb),
  ('es', 'site.org.git.title', $json$"Proveedor git"$json$::jsonb),
  ('es', 'site.org.git.description', $json$"El owner inicia sesión aquí en GitHub, GitLab o Bitbucket y elige los repositorios de la organización. El token de acceso se queda en este sitio una hora y nunca se guarda."$json$::jsonb),
  ('es', 'site.org.git.connected', $json$"Conectado como {account}"$json$::jsonb),
  ('es', 'site.org.git.since', $json$"desde {date}"$json$::jsonb),
  ('es', 'site.org.git.notConnected', $json$"No conectado"$json$::jsonb),
  ('es', 'site.org.git.unavailable', $json$"Aún no disponible en este sitio"$json$::jsonb),
  ('es', 'site.org.git.connect', $json$"Conectar"$json$::jsonb),
  ('es', 'site.org.git.reconnect', $json$"Volver a conectar"$json$::jsonb),
  ('es', 'site.org.git.disconnect', $json$"Desconectar"$json$::jsonb),
  ('es', 'site.org.git.disconnect.title', $json$"Desconectar {provider}"$json$::jsonb),
  ('es', 'site.org.git.disconnect.description', $json$"Los repositorios de la organización se mantienen. Para añadir más de {provider}, vuelve a conectarlo."$json$::jsonb),
  ('es', 'site.org.git.disconnected', $json$"{provider} desconectado."$json$::jsonb),
  ('es', 'site.org.git.ownerOnly', $json$"Solo los owners conectan proveedores y eligen los repositorios."$json$::jsonb),
  ('es', 'site.org.git.done', $json$"{provider} conectado."$json$::jsonb),
  ('es', 'site.org.git.denied', $json$"Se canceló la conexión con {provider}."$json$::jsonb),
  ('es', 'site.org.git.failed', $json$"No se pudo conectar {provider}. Inténtalo de nuevo."$json$::jsonb),
  ('es', 'site.org.repos.description', $json$"Los miembros ven estos repositorios en la página de la organización de la app de JayV y los clonan en su carpeta de la organización, con su propio acceso git."$json$::jsonb),
  ('es', 'site.org.repos.add', $json$"Añadir repositorios"$json$::jsonb),
  ('es', 'site.org.repos.connectFirst', $json$"Conecta un proveedor arriba para añadir repositorios."$json$::jsonb),
  ('es', 'site.org.repos.private', $json$"Privado"$json$::jsonb),
  ('es', 'site.org.repos.public', $json$"Público"$json$::jsonb),
  ('es', 'site.org.repos.manual', $json$"Añadido por URL"$json$::jsonb),
  ('es', 'site.org.repos.open', $json$"Abrir en {provider}"$json$::jsonb),
  ('es', 'site.org.repos.removed', $json$"Repositorio eliminado."$json$::jsonb),
  ('es', 'site.org.repos.pick.title', $json$"Añadir repositorios"$json$::jsonb),
  ('es', 'site.org.repos.pick.description', $json$"Lo que {account} puede ver en {provider}. Marca los que pertenecen a la organización."$json$::jsonb),
  ('es', 'site.org.repos.pick.search', $json$"Buscar repositorios"$json$::jsonb),
  ('es', 'site.org.repos.pick.placeholder', $json$"Filtrar por nombre o descripción…"$json$::jsonb),
  ('es', 'site.org.repos.pick.loading', $json$"Cargando repositorios…"$json$::jsonb),
  ('es', 'site.org.repos.pick.empty', $json$"No se encontraron repositorios."$json$::jsonb),
  ('es', 'site.org.repos.pick.added', $json$"En la organización"$json$::jsonb),
  ('es', 'site.org.repos.pick.truncated', $json$"Se muestran los actualizados más recientemente. Busca para encontrar los demás."$json$::jsonb),
  ('es', 'site.org.repos.pick.expired', $json$"La sesión de {provider} en este sitio caducó. Vuelve a conectar para ver los repositorios."$json$::jsonb),
  ('es', 'site.org.repos.pick.submit', $json$"Añadir seleccionados ({count})"$json$::jsonb),
  ('es', 'site.org.repos.pick.linked', $json${"one": "{count} repositorio añadido.", "other": "{count} repositorios añadidos."}$json$::jsonb),
  ('es', 'site.org.repos.pick.missing', $json$"{provider} no mostró estos con la cuenta conectada: {paths}."$json$::jsonb),
  ('es', 'repos.site.owner', $json$"Tú asocias los repositorios en el sitio de JayV, iniciando sesión en GitHub, GitLab o Bitbucket. Esta lista se actualiza sola."$json$::jsonb),
  ('es', 'repos.site.member', $json$"El owner asocia los repositorios en el sitio de JayV. Esta lista se actualiza sola; tú clonas con tu propio acceso git."$json$::jsonb),
  ('es', 'repos.site.none', $json$"Aún no hay ningún proveedor git conectado."$json$::jsonb),
  ('es', 'repos.private', $json$"Privado"$json$::jsonb),
  ('es', 'repos.public', $json$"Público"$json$::jsonb),
  ('es', 'repos.openWeb', $json$"Abrir en {provider}"$json$::jsonb),
  ('es', 'repos.compare.title', $json$"Carpeta comparada con la organización"$json$::jsonb),
  ('es', 'repos.compare.description', $json$"{path}, buscada a cualquier profundidad: {found} de los {total} repositorios de {org} están en ella."$json$::jsonb),
  ('es', 'repos.compare.truncated', $json$"La búsqueda se detuvo antes del final: la carpeta es demasiado profunda o grande. Elige una carpeta más concreta para verlo todo."$json$::jsonb),
  ('es', 'repos.compare.empty', $json$"Nada que comparar: la organización no tiene repositorios y la carpeta no tiene clones."$json$::jsonb),
  ('es', 'repos.compare.allSet', $json$"Todos los repositorios de la organización están en esta carpeta."$json$::jsonb),
  ('es', 'repos.compare.found', $json$"En la carpeta"$json$::jsonb),
  ('es', 'repos.compare.project', $json$"Proyecto"$json$::jsonb),
  ('es', 'repos.compare.elsewhere', $json$"Ya es un proyecto en {path}"$json$::jsonb),
  ('es', 'repos.compare.missing', $json$"Fuera de la carpeta"$json$::jsonb),
  ('es', 'repos.compare.localElsewhere', $json$"En este equipo en {path}"$json$::jsonb),
  ('es', 'repos.compare.cloneAll', $json$"Clonar todos"$json$::jsonb),
  ('es', 'repos.compare.outside', $json$"Fuera de la organización"$json$::jsonb),
  ('es', 'repos.compare.outside.hint', $json$"Clones de esta carpeta que la organización no tiene en el sitio. Si le pertenecen, el owner los asocia allí."$json$::jsonb),
  ('es', 'repos.compare.noRemote', $json$"Sin remote de GitHub, GitLab o Bitbucket"$json$::jsonb),
  ('es', 'whatsNew.item.repositoriesFromSite.title', $json$"Los repositorios vienen del sitio"$json$::jsonb),
  ('es', 'whatsNew.item.repositoriesFromSite.detail', $json$"El owner ahora asocia los repositorios de la organización en el sitio de JayV, iniciando sesión en GitHub, GitLab o Bitbucket, y aparecen solos en la app. El campo para pegar la URL del repositorio salió de la app."$json$::jsonb),
  ('es', 'whatsNew.item.folderCompare.title', $json$"Buscar clones revisa toda la carpeta"$json$::jsonb),
  ('es', 'whatsNew.item.folderCompare.detail', $json$"Buscar clones ahora revisa la carpeta de la organización a cualquier profundidad y la compara con los repositorios del sitio: lo que ya está, lo que falta (clona uno o todos a la vez) y los clones que no son de la organización."$json$::jsonb),
  ('es', 'docs.organizations.usage', $json$"Crea una organización, invita a miembros y asocia sus repositorios en el panel del sitio de JayV. En la app, Ctrl+2 (⌘2 en Mac) abre tus organizaciones y sus repositorios."$json$::jsonb),
  ('es', 'docs.orgRepositories.title', $json$"Repositorios de la organización"$json$::jsonb),
  ('es', 'docs.orgRepositories.summary', $json$"El owner asocia los repositorios de la organización en el sitio de JayV iniciando sesión en GitHub, GitLab o Bitbucket. La app los lista sola y cada miembro los clona con su propio acceso git."$json$::jsonb),
  ('es', 'docs.orgRepositories.usage', $json$"En el sitio, abre la organización, ve a Repositorios, conecta un proveedor y añade los repositorios. En la app, la página de la organización los lista a medida que cambian: elige la carpeta de la organización, clona lo que falta y usa Buscar clones para comparar toda la carpeta, a cualquier profundidad, con la lista del sitio."$json$::jsonb),
  ('zh-CN', 'org.gitNotConnected', $json$"请先连接 Git 提供方，再添加其中的仓库。"$json$::jsonb),
  ('zh-CN', 'org.gitExpired', $json$"本网站上的 Git 提供方会话已过期，请重新连接。"$json$::jsonb),
  ('zh-CN', 'org.gitUnavailable', $json$"Git 提供方没有响应，请稍后再试。"$json$::jsonb),
  ('zh-CN', 'site.org.git.title', $json$"Git 提供方"$json$::jsonb),
  ('zh-CN', 'site.org.git.description', $json$"所有者在这里登录 GitHub、GitLab 或 Bitbucket，并选择组织的仓库。访问令牌只在本网站停留一小时，从不保存。"$json$::jsonb),
  ('zh-CN', 'site.org.git.connected', $json$"已以 {account} 连接"$json$::jsonb),
  ('zh-CN', 'site.org.git.since', $json$"自 {date} 起"$json$::jsonb),
  ('zh-CN', 'site.org.git.notConnected', $json$"未连接"$json$::jsonb),
  ('zh-CN', 'site.org.git.unavailable', $json$"本网站暂不支持"$json$::jsonb),
  ('zh-CN', 'site.org.git.connect', $json$"连接"$json$::jsonb),
  ('zh-CN', 'site.org.git.reconnect', $json$"重新连接"$json$::jsonb),
  ('zh-CN', 'site.org.git.disconnect', $json$"断开连接"$json$::jsonb),
  ('zh-CN', 'site.org.git.disconnect.title', $json$"断开 {provider}"$json$::jsonb),
  ('zh-CN', 'site.org.git.disconnect.description', $json$"组织的仓库会保留。要从 {provider} 添加更多仓库，请重新连接。"$json$::jsonb),
  ('zh-CN', 'site.org.git.disconnected', $json$"已断开 {provider}。"$json$::jsonb),
  ('zh-CN', 'site.org.git.ownerOnly', $json$"只有所有者可以连接提供方并选择仓库。"$json$::jsonb),
  ('zh-CN', 'site.org.git.done', $json$"已连接 {provider}。"$json$::jsonb),
  ('zh-CN', 'site.org.git.denied', $json$"与 {provider} 的连接已取消。"$json$::jsonb),
  ('zh-CN', 'site.org.git.failed', $json$"无法连接 {provider}，请重试。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.description', $json$"成员会在 JayV 应用的组织页面看到这些仓库，并用自己的 git 权限把它们克隆到组织文件夹中。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.add', $json$"添加仓库"$json$::jsonb),
  ('zh-CN', 'site.org.repos.connectFirst', $json$"请先在上方连接提供方，再添加仓库。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.private', $json$"私有"$json$::jsonb),
  ('zh-CN', 'site.org.repos.public', $json$"公开"$json$::jsonb),
  ('zh-CN', 'site.org.repos.manual', $json$"通过 URL 添加"$json$::jsonb),
  ('zh-CN', 'site.org.repos.open', $json$"在 {provider} 上打开"$json$::jsonb),
  ('zh-CN', 'site.org.repos.removed', $json$"仓库已移除。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.title', $json$"添加仓库"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.description', $json$"{account} 在 {provider} 上可访问的仓库。勾选属于该组织的仓库。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.search', $json$"搜索仓库"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.placeholder', $json$"按名称或描述筛选…"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.loading', $json$"正在加载仓库…"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.empty', $json$"没有找到仓库。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.added', $json$"已在组织中"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.truncated', $json$"仅显示最近更新的仓库。搜索以查找其他仓库。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.expired', $json$"本网站上的 {provider} 会话已过期。重新连接后即可列出仓库。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.submit', $json$"添加所选（{count}）"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.linked', $json${"other": "已添加 {count} 个仓库。"}$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.missing', $json$"{provider} 未通过已连接的账号显示以下仓库：{paths}。"$json$::jsonb),
  ('zh-CN', 'repos.site.owner', $json$"你在 JayV 网站上登录 GitHub、GitLab 或 Bitbucket 来关联仓库。此列表会自动更新。"$json$::jsonb),
  ('zh-CN', 'repos.site.member', $json$"所有者在 JayV 网站上关联仓库。此列表会自动更新；你用自己的 git 权限克隆。"$json$::jsonb),
  ('zh-CN', 'repos.site.none', $json$"尚未连接任何 Git 提供方。"$json$::jsonb),
  ('zh-CN', 'repos.private', $json$"私有"$json$::jsonb),
  ('zh-CN', 'repos.public', $json$"公开"$json$::jsonb),
  ('zh-CN', 'repos.openWeb', $json$"在 {provider} 上打开"$json$::jsonb),
  ('zh-CN', 'repos.compare.title', $json$"文件夹与组织的对比"$json$::jsonb),
  ('zh-CN', 'repos.compare.description', $json$"已在 {path} 的所有层级中查找：{org} 的 {total} 个仓库中有 {found} 个在其中。"$json$::jsonb),
  ('zh-CN', 'repos.compare.truncated', $json$"搜索未完成就停止了：文件夹层级太深或内容太多。请选择范围更小的文件夹以查看全部。"$json$::jsonb),
  ('zh-CN', 'repos.compare.empty', $json$"没有可比较的内容：组织没有仓库，文件夹中也没有克隆。"$json$::jsonb),
  ('zh-CN', 'repos.compare.allSet', $json$"组织的所有仓库都在此文件夹中。"$json$::jsonb),
  ('zh-CN', 'repos.compare.found', $json$"在文件夹中"$json$::jsonb),
  ('zh-CN', 'repos.compare.project', $json$"项目"$json$::jsonb),
  ('zh-CN', 'repos.compare.elsewhere', $json$"已是 {path} 中的项目"$json$::jsonb),
  ('zh-CN', 'repos.compare.missing', $json$"不在文件夹中"$json$::jsonb),
  ('zh-CN', 'repos.compare.localElsewhere', $json$"在本机的 {path} 中"$json$::jsonb),
  ('zh-CN', 'repos.compare.cloneAll', $json$"全部克隆"$json$::jsonb),
  ('zh-CN', 'repos.compare.outside', $json$"不属于该组织"$json$::jsonb),
  ('zh-CN', 'repos.compare.outside.hint', $json$"此文件夹中有些克隆不在组织的网站列表里。如果它们属于该组织，请所有者在网站上关联。"$json$::jsonb),
  ('zh-CN', 'repos.compare.noRemote', $json$"没有 GitHub、GitLab 或 Bitbucket 的 remote"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.repositoriesFromSite.title', $json$"仓库来自网站"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.repositoriesFromSite.detail', $json$"所有者现在在 JayV 网站上登录 GitHub、GitLab 或 Bitbucket 来关联组织的仓库，它们会自动出现在应用中。应用里粘贴仓库 URL 的输入框已移除。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.folderCompare.title', $json$"“查找克隆”会检查整个文件夹"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.folderCompare.detail', $json$"“查找克隆”现在会在组织文件夹的所有层级中查找，并与网站上的仓库对比：哪些已在其中、哪些缺失（可单个或全部一次克隆），以及哪些克隆不属于该组织。"$json$::jsonb),
  ('zh-CN', 'docs.organizations.usage', $json$"在 JayV 网站的控制台中创建组织、邀请成员并关联其仓库。在应用中，Ctrl+2（Mac 上为 ⌘2）打开你的组织及其仓库。"$json$::jsonb),
  ('zh-CN', 'docs.orgRepositories.title', $json$"组织仓库"$json$::jsonb),
  ('zh-CN', 'docs.orgRepositories.summary', $json$"所有者在 JayV 网站上登录 GitHub、GitLab 或 Bitbucket 来关联组织的仓库。应用会自动列出它们，每位成员用自己的 git 权限克隆。"$json$::jsonb),
  ('zh-CN', 'docs.orgRepositories.usage', $json$"在网站上打开组织，进入“仓库”，连接提供方并添加仓库。在应用中，组织页面会随变化实时列出它们：选择组织文件夹，克隆缺少的仓库，并用“查找克隆”在所有层级中将整个文件夹与网站上的列表进行对比。"$json$::jsonb),
  ('hi', 'org.gitNotConnected', $json$"इसकी रिपॉज़िटरी जोड़ने से पहले git प्रदाता कनेक्ट करें।"$json$::jsonb),
  ('hi', 'org.gitExpired', $json$"इस साइट पर git प्रदाता का सत्र समाप्त हो गया है। इसे फिर से कनेक्ट करें।"$json$::jsonb),
  ('hi', 'org.gitUnavailable', $json$"git प्रदाता ने जवाब नहीं दिया। थोड़ी देर में फिर से कोशिश करें।"$json$::jsonb),
  ('hi', 'site.org.git.title', $json$"git प्रदाता"$json$::jsonb),
  ('hi', 'site.org.git.description', $json$"ओनर यहाँ GitHub, GitLab या Bitbucket में साइन इन करता है और संगठन की रिपॉज़िटरी चुनता है। ऐक्सेस टोकन इस साइट पर सिर्फ़ एक घंटे रहता है और कभी सहेजा नहीं जाता।"$json$::jsonb),
  ('hi', 'site.org.git.connected', $json$"{account} के रूप में कनेक्टेड"$json$::jsonb),
  ('hi', 'site.org.git.since', $json$"{date} से"$json$::jsonb),
  ('hi', 'site.org.git.notConnected', $json$"कनेक्ट नहीं है"$json$::jsonb),
  ('hi', 'site.org.git.unavailable', $json$"इस साइट पर अभी उपलब्ध नहीं"$json$::jsonb),
  ('hi', 'site.org.git.connect', $json$"कनेक्ट करें"$json$::jsonb),
  ('hi', 'site.org.git.reconnect', $json$"फिर से कनेक्ट करें"$json$::jsonb),
  ('hi', 'site.org.git.disconnect', $json$"डिस्कनेक्ट करें"$json$::jsonb),
  ('hi', 'site.org.git.disconnect.title', $json$"{provider} डिस्कनेक्ट करें"$json$::jsonb),
  ('hi', 'site.org.git.disconnect.description', $json$"संगठन की रिपॉज़िटरी बनी रहेंगी। {provider} से और जोड़ने के लिए इसे फिर से कनेक्ट करें।"$json$::jsonb),
  ('hi', 'site.org.git.disconnected', $json$"{provider} डिस्कनेक्ट हो गया।"$json$::jsonb),
  ('hi', 'site.org.git.ownerOnly', $json$"सिर्फ़ ओनर ही प्रदाता कनेक्ट करते हैं और रिपॉज़िटरी चुनते हैं।"$json$::jsonb),
  ('hi', 'site.org.git.done', $json$"{provider} कनेक्ट हो गया।"$json$::jsonb),
  ('hi', 'site.org.git.denied', $json$"{provider} से कनेक्शन रद्द कर दिया गया।"$json$::jsonb),
  ('hi', 'site.org.git.failed', $json$"{provider} कनेक्ट नहीं हो सका। फिर से कोशिश करें।"$json$::jsonb),
  ('hi', 'site.org.repos.description', $json$"सदस्य JayV ऐप के संगठन पेज पर ये रिपॉज़िटरी देखते हैं और अपनी git ऐक्सेस से इन्हें संगठन के फ़ोल्डर में क्लोन करते हैं।"$json$::jsonb),
  ('hi', 'site.org.repos.add', $json$"रिपॉज़िटरी जोड़ें"$json$::jsonb),
  ('hi', 'site.org.repos.connectFirst', $json$"रिपॉज़िटरी जोड़ने के लिए ऊपर कोई प्रदाता कनेक्ट करें।"$json$::jsonb),
  ('hi', 'site.org.repos.private', $json$"निजी"$json$::jsonb),
  ('hi', 'site.org.repos.public', $json$"सार्वजनिक"$json$::jsonb),
  ('hi', 'site.org.repos.manual', $json$"URL से जोड़ा गया"$json$::jsonb),
  ('hi', 'site.org.repos.open', $json$"{provider} पर खोलें"$json$::jsonb),
  ('hi', 'site.org.repos.removed', $json$"रिपॉज़िटरी हटा दी गई।"$json$::jsonb),
  ('hi', 'site.org.repos.pick.title', $json$"रिपॉज़िटरी जोड़ें"$json$::jsonb),
  ('hi', 'site.org.repos.pick.description', $json$"{provider} पर {account} जिन तक पहुँच सकता है। संगठन की रिपॉज़िटरी चुनें।"$json$::jsonb),
  ('hi', 'site.org.repos.pick.search', $json$"रिपॉज़िटरी खोजें"$json$::jsonb),
  ('hi', 'site.org.repos.pick.placeholder', $json$"नाम या विवरण से फ़िल्टर करें…"$json$::jsonb),
  ('hi', 'site.org.repos.pick.loading', $json$"रिपॉज़िटरी लोड हो रही हैं…"$json$::jsonb),
  ('hi', 'site.org.repos.pick.empty', $json$"कोई रिपॉज़िटरी नहीं मिली।"$json$::jsonb),
  ('hi', 'site.org.repos.pick.added', $json$"संगठन में है"$json$::jsonb),
  ('hi', 'site.org.repos.pick.truncated', $json$"हाल में अपडेट हुई रिपॉज़िटरी दिख रही हैं। बाकी के लिए खोजें।"$json$::jsonb),
  ('hi', 'site.org.repos.pick.expired', $json$"इस साइट पर {provider} का सत्र समाप्त हो गया है। रिपॉज़िटरी देखने के लिए फिर से कनेक्ट करें।"$json$::jsonb),
  ('hi', 'site.org.repos.pick.submit', $json$"चुनी हुई जोड़ें ({count})"$json$::jsonb),
  ('hi', 'site.org.repos.pick.linked', $json${"one": "{count} रिपॉज़िटरी जोड़ी गई।", "other": "{count} रिपॉज़िटरी जोड़ी गईं।"}$json$::jsonb),
  ('hi', 'site.org.repos.pick.missing', $json$"जुड़े हुए खाते से {provider} ने ये नहीं दिखाईं: {paths}।"$json$::jsonb),
  ('hi', 'repos.site.owner', $json$"आप JayV साइट पर GitHub, GitLab या Bitbucket में साइन इन करके रिपॉज़िटरी जोड़ते हैं। यह सूची अपने-आप अपडेट होती है।"$json$::jsonb),
  ('hi', 'repos.site.member', $json$"ओनर JayV साइट पर रिपॉज़िटरी जोड़ता है। यह सूची अपने-आप अपडेट होती है; आप अपनी git ऐक्सेस से क्लोन करते हैं।"$json$::jsonb),
  ('hi', 'repos.site.none', $json$"अभी कोई git प्रदाता कनेक्ट नहीं है।"$json$::jsonb),
  ('hi', 'repos.private', $json$"निजी"$json$::jsonb),
  ('hi', 'repos.public', $json$"सार्वजनिक"$json$::jsonb),
  ('hi', 'repos.openWeb', $json$"{provider} पर खोलें"$json$::jsonb),
  ('hi', 'repos.compare.title', $json$"संगठन से तुलना किया गया फ़ोल्डर"$json$::jsonb),
  ('hi', 'repos.compare.description', $json$"{path} को हर गहराई तक खोजा गया: {org} की {total} में से {found} रिपॉज़िटरी इसमें हैं।"$json$::jsonb),
  ('hi', 'repos.compare.truncated', $json$"खोज पूरी होने से पहले रुक गई: फ़ोल्डर बहुत गहरा या बहुत बड़ा है। सब कुछ देखने के लिए छोटा फ़ोल्डर चुनें।"$json$::jsonb),
  ('hi', 'repos.compare.empty', $json$"तुलना के लिए कुछ नहीं: संगठन में कोई रिपॉज़िटरी नहीं है और फ़ोल्डर में कोई क्लोन नहीं है।"$json$::jsonb),
  ('hi', 'repos.compare.allSet', $json$"संगठन की सभी रिपॉज़िटरी इस फ़ोल्डर में हैं।"$json$::jsonb),
  ('hi', 'repos.compare.found', $json$"फ़ोल्डर में"$json$::jsonb),
  ('hi', 'repos.compare.project', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'repos.compare.elsewhere', $json$"{path} में पहले से प्रोजेक्ट है"$json$::jsonb),
  ('hi', 'repos.compare.missing', $json$"फ़ोल्डर में नहीं"$json$::jsonb),
  ('hi', 'repos.compare.localElsewhere', $json$"इस कंप्यूटर पर {path} में"$json$::jsonb),
  ('hi', 'repos.compare.cloneAll', $json$"सभी क्लोन करें"$json$::jsonb),
  ('hi', 'repos.compare.outside', $json$"संगठन में नहीं"$json$::jsonb),
  ('hi', 'repos.compare.outside.hint', $json$"इस फ़ोल्डर के वे क्लोन जो संगठन के पास साइट पर नहीं हैं। अगर ये उसी के हैं, तो ओनर इन्हें वहाँ जोड़ता है।"$json$::jsonb),
  ('hi', 'repos.compare.noRemote', $json$"GitHub, GitLab या Bitbucket का कोई remote नहीं"$json$::jsonb),
  ('hi', 'whatsNew.item.repositoriesFromSite.title', $json$"रिपॉज़िटरी अब साइट से आती हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.repositoriesFromSite.detail', $json$"ओनर अब JayV साइट पर GitHub, GitLab या Bitbucket में साइन इन करके संगठन की रिपॉज़िटरी जोड़ता है, और वे ऐप में अपने-आप दिखती हैं। रिपॉज़िटरी URL चिपकाने वाला फ़ील्ड ऐप से हटा दिया गया है।"$json$::jsonb),
  ('hi', 'whatsNew.item.folderCompare.title', $json$"क्लोन खोजें अब पूरा फ़ोल्डर देखता है"$json$::jsonb),
  ('hi', 'whatsNew.item.folderCompare.detail', $json$"क्लोन खोजें अब संगठन के फ़ोल्डर को हर गहराई तक खोजता है और साइट की रिपॉज़िटरी से तुलना करता है: क्या पहले से है, क्या नहीं है (एक-एक या सभी एक साथ क्लोन करें) और कौन से क्लोन संगठन के नहीं हैं।"$json$::jsonb),
  ('hi', 'docs.organizations.usage', $json$"JayV साइट के डैशबोर्ड में संगठन बनाएँ, सदस्यों को आमंत्रित करें और उसकी रिपॉज़िटरी जोड़ें। ऐप में Ctrl+2 (Mac पर ⌘2) आपके संगठन और उनकी रिपॉज़िटरी खोलता है।"$json$::jsonb),
  ('hi', 'docs.orgRepositories.title', $json$"संगठन की रिपॉज़िटरी"$json$::jsonb),
  ('hi', 'docs.orgRepositories.summary', $json$"ओनर JayV साइट पर GitHub, GitLab या Bitbucket में साइन इन करके संगठन की रिपॉज़िटरी जोड़ता है। ऐप इन्हें अपने-आप दिखाता है, और हर सदस्य अपनी git ऐक्सेस से इन्हें क्लोन करता है।"$json$::jsonb),
  ('hi', 'docs.orgRepositories.usage', $json$"साइट पर संगठन खोलें, रिपॉज़िटरी में जाएँ, कोई प्रदाता कनेक्ट करें और रिपॉज़िटरी जोड़ें। ऐप में संगठन का पेज बदलाव होते ही इन्हें दिखाता है: संगठन का फ़ोल्डर चुनें, जो नहीं है उसे क्लोन करें और क्लोन खोजें से पूरे फ़ोल्डर की, हर गहराई तक, साइट की सूची से तुलना करें।"$json$::jsonb),
  ('ar', 'org.gitNotConnected', $json$"اربط مزوّد git قبل إضافة مستودعاته."$json$::jsonb),
  ('ar', 'org.gitExpired', $json$"انتهت جلسة مزوّد git على هذا الموقع. اربطه مرة أخرى."$json$::jsonb),
  ('ar', 'org.gitUnavailable', $json$"لم يستجب مزوّد git. حاول مرة أخرى بعد قليل."$json$::jsonb),
  ('ar', 'site.org.git.title', $json$"مزوّد git"$json$::jsonb),
  ('ar', 'site.org.git.description', $json$"يسجّل المالك الدخول هنا إلى GitHub أو GitLab أو Bitbucket ويختار مستودعات المؤسسة. يبقى رمز الوصول على هذا الموقع ساعة واحدة ولا يُحفظ أبدًا."$json$::jsonb),
  ('ar', 'site.org.git.connected', $json$"متصل باسم {account}"$json$::jsonb),
  ('ar', 'site.org.git.since', $json$"منذ {date}"$json$::jsonb),
  ('ar', 'site.org.git.notConnected', $json$"غير متصل"$json$::jsonb),
  ('ar', 'site.org.git.unavailable', $json$"غير متاح على هذا الموقع بعد"$json$::jsonb),
  ('ar', 'site.org.git.connect', $json$"ربط"$json$::jsonb),
  ('ar', 'site.org.git.reconnect', $json$"الربط مرة أخرى"$json$::jsonb),
  ('ar', 'site.org.git.disconnect', $json$"فصل"$json$::jsonb),
  ('ar', 'site.org.git.disconnect.title', $json$"فصل {provider}"$json$::jsonb),
  ('ar', 'site.org.git.disconnect.description', $json$"تبقى مستودعات المؤسسة كما هي. لإضافة المزيد من {provider}، اربطه مرة أخرى."$json$::jsonb),
  ('ar', 'site.org.git.disconnected', $json$"تم فصل {provider}."$json$::jsonb),
  ('ar', 'site.org.git.ownerOnly', $json$"المالكون وحدهم يربطون المزوّدين ويختارون المستودعات."$json$::jsonb),
  ('ar', 'site.org.git.done', $json$"تم ربط {provider}."$json$::jsonb),
  ('ar', 'site.org.git.denied', $json$"أُلغي الربط مع {provider}."$json$::jsonb),
  ('ar', 'site.org.git.failed', $json$"تعذّر ربط {provider}. حاول مرة أخرى."$json$::jsonb),
  ('ar', 'site.org.repos.description', $json$"يرى الأعضاء هذه المستودعات في صفحة المؤسسة في تطبيق JayV ويستنسخونها في مجلد المؤسسة لديهم بصلاحيات git الخاصة بهم."$json$::jsonb),
  ('ar', 'site.org.repos.add', $json$"إضافة مستودعات"$json$::jsonb),
  ('ar', 'site.org.repos.connectFirst', $json$"اربط مزوّدًا في الأعلى لإضافة مستودعات."$json$::jsonb),
  ('ar', 'site.org.repos.private', $json$"خاص"$json$::jsonb),
  ('ar', 'site.org.repos.public', $json$"عام"$json$::jsonb),
  ('ar', 'site.org.repos.manual', $json$"أُضيف عبر URL"$json$::jsonb),
  ('ar', 'site.org.repos.open', $json$"فتح في {provider}"$json$::jsonb),
  ('ar', 'site.org.repos.removed', $json$"أُزيل المستودع."$json$::jsonb),
  ('ar', 'site.org.repos.pick.title', $json$"إضافة مستودعات"$json$::jsonb),
  ('ar', 'site.org.repos.pick.description', $json$"ما يستطيع {account} الوصول إليه على {provider}. حدّد ما يخص المؤسسة."$json$::jsonb),
  ('ar', 'site.org.repos.pick.search', $json$"البحث في المستودعات"$json$::jsonb),
  ('ar', 'site.org.repos.pick.placeholder', $json$"التصفية بالاسم أو الوصف…"$json$::jsonb),
  ('ar', 'site.org.repos.pick.loading', $json$"جارٍ تحميل المستودعات…"$json$::jsonb),
  ('ar', 'site.org.repos.pick.empty', $json$"لم يُعثر على مستودعات."$json$::jsonb),
  ('ar', 'site.org.repos.pick.added', $json$"ضمن المؤسسة"$json$::jsonb),
  ('ar', 'site.org.repos.pick.truncated', $json$"تُعرض المستودعات المحدّثة مؤخرًا. ابحث للعثور على البقية."$json$::jsonb),
  ('ar', 'site.org.repos.pick.expired', $json$"انتهت جلسة {provider} على هذا الموقع. اربطه مرة أخرى لعرض المستودعات."$json$::jsonb),
  ('ar', 'site.org.repos.pick.submit', $json$"إضافة المحدد ({count})"$json$::jsonb),
  ('ar', 'site.org.repos.pick.linked', $json${"zero": "لم يُضف أي مستودع.", "one": "أُضيف مستودع واحد.", "two": "أُضيف مستودعان.", "few": "أُضيفت {count} مستودعات.", "many": "أُضيف {count} مستودعًا.", "other": "أُضيف {count} مستودع."}$json$::jsonb),
  ('ar', 'site.org.repos.pick.missing', $json$"لم يُظهر {provider} هذه المستودعات بالحساب المرتبط: {paths}."$json$::jsonb),
  ('ar', 'repos.site.owner', $json$"أنت من يربط المستودعات في موقع JayV بتسجيل الدخول إلى GitHub أو GitLab أو Bitbucket. تتحدّث هذه القائمة تلقائيًا."$json$::jsonb),
  ('ar', 'repos.site.member', $json$"يربط المالك المستودعات في موقع JayV. تتحدّث هذه القائمة تلقائيًا، وتستنسخ أنت بصلاحيات git الخاصة بك."$json$::jsonb),
  ('ar', 'repos.site.none', $json$"لم يُربط أي مزوّد git بعد."$json$::jsonb),
  ('ar', 'repos.private', $json$"خاص"$json$::jsonb),
  ('ar', 'repos.public', $json$"عام"$json$::jsonb),
  ('ar', 'repos.openWeb', $json$"فتح في {provider}"$json$::jsonb),
  ('ar', 'repos.compare.title', $json$"مقارنة المجلد بالمؤسسة"$json$::jsonb),
  ('ar', 'repos.compare.description', $json$"بُحث في {path} على كل المستويات: {found} من أصل {total} من مستودعات {org} موجودة فيه."$json$::jsonb),
  ('ar', 'repos.compare.truncated', $json$"توقّف البحث قبل النهاية: المجلد عميق أو كبير جدًا. اختر مجلدًا أضيق لرؤية كل شيء."$json$::jsonb),
  ('ar', 'repos.compare.empty', $json$"لا شيء للمقارنة: لا تملك المؤسسة مستودعات ولا يحوي المجلد أي نسخ."$json$::jsonb),
  ('ar', 'repos.compare.allSet', $json$"كل مستودعات المؤسسة موجودة في هذا المجلد."$json$::jsonb),
  ('ar', 'repos.compare.found', $json$"في المجلد"$json$::jsonb),
  ('ar', 'repos.compare.project', $json$"مشروع"$json$::jsonb),
  ('ar', 'repos.compare.elsewhere', $json$"مشروع بالفعل في {path}"$json$::jsonb),
  ('ar', 'repos.compare.missing', $json$"ليست في المجلد"$json$::jsonb),
  ('ar', 'repos.compare.localElsewhere', $json$"على هذا الحاسوب في {path}"$json$::jsonb),
  ('ar', 'repos.compare.cloneAll', $json$"استنساخ الكل"$json$::jsonb),
  ('ar', 'repos.compare.outside', $json$"خارج المؤسسة"$json$::jsonb),
  ('ar', 'repos.compare.outside.hint', $json$"نسخ في هذا المجلد لا تملكها المؤسسة في الموقع. إن كانت تخصها، فالمالك يربطها هناك."$json$::jsonb),
  ('ar', 'repos.compare.noRemote', $json$"لا يوجد remote من GitHub أو GitLab أو Bitbucket"$json$::jsonb),
  ('ar', 'whatsNew.item.repositoriesFromSite.title', $json$"المستودعات تأتي من الموقع"$json$::jsonb),
  ('ar', 'whatsNew.item.repositoriesFromSite.detail', $json$"أصبح المالك يربط مستودعات المؤسسة في موقع JayV بتسجيل الدخول إلى GitHub أو GitLab أو Bitbucket، فتظهر في التطبيق تلقائيًا. أُزيل من التطبيق حقل لصق رابط المستودع."$json$::jsonb),
  ('ar', 'whatsNew.item.folderCompare.title', $json$"البحث عن النسخ يشمل المجلد كله"$json$::jsonb),
  ('ar', 'whatsNew.item.folderCompare.detail', $json$"أصبح البحث عن النسخ يفحص مجلد المؤسسة على كل المستويات ويقارنه بمستودعات الموقع: ما هو موجود بالفعل، وما ينقص (استنسخ واحدًا أو الكل دفعة واحدة)، والنسخ التي لا تخص المؤسسة."$json$::jsonb),
  ('ar', 'docs.organizations.usage', $json$"أنشئ مؤسسة وادعُ الأعضاء واربط مستودعاتها من لوحة تحكم موقع JayV. في التطبيق، يفتح Ctrl+2 (⌘2 على Mac) مؤسساتك ومستودعاتها."$json$::jsonb),
  ('ar', 'docs.orgRepositories.title', $json$"مستودعات المؤسسة"$json$::jsonb),
  ('ar', 'docs.orgRepositories.summary', $json$"يربط المالك مستودعات المؤسسة في موقع JayV بتسجيل الدخول إلى GitHub أو GitLab أو Bitbucket. يعرضها التطبيق تلقائيًا، ويستنسخها كل عضو بصلاحيات git الخاصة به."$json$::jsonb),
  ('ar', 'docs.orgRepositories.usage', $json$"في الموقع، افتح المؤسسة واذهب إلى المستودعات واربط مزوّدًا وأضف المستودعات. في التطبيق، تعرضها صفحة المؤسسة كلما تغيّرت: اختر مجلد المؤسسة، واستنسخ ما ينقص، واستخدم البحث عن النسخ لمقارنة المجلد كله، على كل المستويات، بقائمة الموقع."$json$::jsonb),
  ('fr', 'org.gitNotConnected', $json$"Connectez le fournisseur git avant d'ajouter ses dépôts."$json$::jsonb),
  ('fr', 'org.gitExpired', $json$"La session du fournisseur git sur ce site a expiré. Reconnectez-le."$json$::jsonb),
  ('fr', 'org.gitUnavailable', $json$"Le fournisseur git n'a pas répondu. Réessayez dans un instant."$json$::jsonb),
  ('fr', 'site.org.git.title', $json$"Fournisseur git"$json$::jsonb),
  ('fr', 'site.org.git.description', $json$"L'owner se connecte ici à GitHub, GitLab ou Bitbucket et choisit les dépôts de l'organisation. Le jeton d'accès reste sur ce site une heure et n'est jamais enregistré."$json$::jsonb),
  ('fr', 'site.org.git.connected', $json$"Connecté en tant que {account}"$json$::jsonb),
  ('fr', 'site.org.git.since', $json$"depuis le {date}"$json$::jsonb),
  ('fr', 'site.org.git.notConnected', $json$"Non connecté"$json$::jsonb),
  ('fr', 'site.org.git.unavailable', $json$"Pas encore disponible sur ce site"$json$::jsonb),
  ('fr', 'site.org.git.connect', $json$"Connecter"$json$::jsonb),
  ('fr', 'site.org.git.reconnect', $json$"Reconnecter"$json$::jsonb),
  ('fr', 'site.org.git.disconnect', $json$"Déconnecter"$json$::jsonb),
  ('fr', 'site.org.git.disconnect.title', $json$"Déconnecter {provider}"$json$::jsonb),
  ('fr', 'site.org.git.disconnect.description', $json$"Les dépôts de l'organisation restent. Pour en ajouter d'autres depuis {provider}, reconnectez-le."$json$::jsonb),
  ('fr', 'site.org.git.disconnected', $json$"{provider} déconnecté."$json$::jsonb),
  ('fr', 'site.org.git.ownerOnly', $json$"Seuls les owners connectent les fournisseurs et choisissent les dépôts."$json$::jsonb),
  ('fr', 'site.org.git.done', $json$"{provider} connecté."$json$::jsonb),
  ('fr', 'site.org.git.denied', $json$"La connexion avec {provider} a été annulée."$json$::jsonb),
  ('fr', 'site.org.git.failed', $json$"Impossible de connecter {provider}. Réessayez."$json$::jsonb),
  ('fr', 'site.org.repos.description', $json$"Les membres voient ces dépôts sur la page de l'organisation dans l'application JayV et les clonent dans leur dossier de l'organisation, avec leur propre accès git."$json$::jsonb),
  ('fr', 'site.org.repos.add', $json$"Ajouter des dépôts"$json$::jsonb),
  ('fr', 'site.org.repos.connectFirst', $json$"Connectez un fournisseur ci-dessus pour ajouter des dépôts."$json$::jsonb),
  ('fr', 'site.org.repos.private', $json$"Privé"$json$::jsonb),
  ('fr', 'site.org.repos.public', $json$"Public"$json$::jsonb),
  ('fr', 'site.org.repos.manual', $json$"Ajouté par URL"$json$::jsonb),
  ('fr', 'site.org.repos.open', $json$"Ouvrir sur {provider}"$json$::jsonb),
  ('fr', 'site.org.repos.removed', $json$"Dépôt retiré."$json$::jsonb),
  ('fr', 'site.org.repos.pick.title', $json$"Ajouter des dépôts"$json$::jsonb),
  ('fr', 'site.org.repos.pick.description', $json$"Ce à quoi {account} a accès sur {provider}. Cochez ceux qui appartiennent à l'organisation."$json$::jsonb),
  ('fr', 'site.org.repos.pick.search', $json$"Rechercher des dépôts"$json$::jsonb),
  ('fr', 'site.org.repos.pick.placeholder', $json$"Filtrer par nom ou description…"$json$::jsonb),
  ('fr', 'site.org.repos.pick.loading', $json$"Chargement des dépôts…"$json$::jsonb),
  ('fr', 'site.org.repos.pick.empty', $json$"Aucun dépôt trouvé."$json$::jsonb),
  ('fr', 'site.org.repos.pick.added', $json$"Dans l'organisation"$json$::jsonb),
  ('fr', 'site.org.repos.pick.truncated', $json$"Affichage des plus récemment mis à jour. Recherchez pour trouver les autres."$json$::jsonb),
  ('fr', 'site.org.repos.pick.expired', $json$"La session {provider} sur ce site a expiré. Reconnectez-vous pour lister les dépôts."$json$::jsonb),
  ('fr', 'site.org.repos.pick.submit', $json$"Ajouter la sélection ({count})"$json$::jsonb),
  ('fr', 'site.org.repos.pick.linked', $json${"one": "{count} dépôt ajouté.", "other": "{count} dépôts ajoutés."}$json$::jsonb),
  ('fr', 'site.org.repos.pick.missing', $json$"{provider} n'a pas montré ceux-ci avec le compte connecté : {paths}."$json$::jsonb),
  ('fr', 'repos.site.owner', $json$"Vous associez les dépôts sur le site de JayV, en vous connectant à GitHub, GitLab ou Bitbucket. Cette liste se met à jour toute seule."$json$::jsonb),
  ('fr', 'repos.site.member', $json$"L'owner associe les dépôts sur le site de JayV. Cette liste se met à jour toute seule ; vous clonez avec votre propre accès git."$json$::jsonb),
  ('fr', 'repos.site.none', $json$"Aucun fournisseur git connecté pour l'instant."$json$::jsonb),
  ('fr', 'repos.private', $json$"Privé"$json$::jsonb),
  ('fr', 'repos.public', $json$"Public"$json$::jsonb),
  ('fr', 'repos.openWeb', $json$"Ouvrir sur {provider}"$json$::jsonb),
  ('fr', 'repos.compare.title', $json$"Dossier comparé à l'organisation"$json$::jsonb),
  ('fr', 'repos.compare.description', $json$"{path}, parcouru à toute profondeur : {found} des {total} dépôts de {org} s'y trouvent."$json$::jsonb),
  ('fr', 'repos.compare.truncated', $json$"La recherche s'est arrêtée avant la fin : le dossier est trop profond ou trop grand. Choisissez un dossier plus précis pour tout voir."$json$::jsonb),
  ('fr', 'repos.compare.empty', $json$"Rien à comparer : l'organisation n'a aucun dépôt et le dossier aucun clone."$json$::jsonb),
  ('fr', 'repos.compare.allSet', $json$"Tous les dépôts de l'organisation sont dans ce dossier."$json$::jsonb),
  ('fr', 'repos.compare.found', $json$"Dans le dossier"$json$::jsonb),
  ('fr', 'repos.compare.project', $json$"Projet"$json$::jsonb),
  ('fr', 'repos.compare.elsewhere', $json$"Déjà un projet dans {path}"$json$::jsonb),
  ('fr', 'repos.compare.missing', $json$"Absents du dossier"$json$::jsonb),
  ('fr', 'repos.compare.localElsewhere', $json$"Sur cet ordinateur dans {path}"$json$::jsonb),
  ('fr', 'repos.compare.cloneAll', $json$"Tout cloner"$json$::jsonb),
  ('fr', 'repos.compare.outside', $json$"Hors de l'organisation"$json$::jsonb),
  ('fr', 'repos.compare.outside.hint', $json$"Des clones de ce dossier que l'organisation n'a pas sur le site. S'ils lui appartiennent, l'owner les y associe."$json$::jsonb),
  ('fr', 'repos.compare.noRemote', $json$"Aucun remote GitHub, GitLab ou Bitbucket"$json$::jsonb),
  ('fr', 'whatsNew.item.repositoriesFromSite.title', $json$"Les dépôts viennent du site"$json$::jsonb),
  ('fr', 'whatsNew.item.repositoriesFromSite.detail', $json$"L'owner associe désormais les dépôts de l'organisation sur le site de JayV, en se connectant à GitHub, GitLab ou Bitbucket, et ils apparaissent tout seuls dans l'application. Le champ pour coller l'URL d'un dépôt a quitté l'application."$json$::jsonb),
  ('fr', 'whatsNew.item.folderCompare.title', $json$"Chercher des clones parcourt tout le dossier"$json$::jsonb),
  ('fr', 'whatsNew.item.folderCompare.detail', $json$"Chercher des clones parcourt désormais le dossier de l'organisation à toute profondeur et le compare aux dépôts du site : ce qui y est déjà, ce qui manque (clonez-en un ou tous d'un coup) et les clones qui ne sont pas de l'organisation."$json$::jsonb),
  ('fr', 'docs.organizations.usage', $json$"Créez une organisation, invitez des membres et associez ses dépôts dans le tableau de bord du site de JayV. Dans l'application, Ctrl+2 (⌘2 sur Mac) ouvre vos organisations et leurs dépôts."$json$::jsonb),
  ('fr', 'docs.orgRepositories.title', $json$"Dépôts de l'organisation"$json$::jsonb),
  ('fr', 'docs.orgRepositories.summary', $json$"L'owner associe les dépôts de l'organisation sur le site de JayV en se connectant à GitHub, GitLab ou Bitbucket. L'application les liste toute seule, et chaque membre les clone avec son propre accès git."$json$::jsonb),
  ('fr', 'docs.orgRepositories.usage', $json$"Sur le site, ouvrez l'organisation, allez dans Dépôts, connectez un fournisseur et ajoutez les dépôts. Dans l'application, la page de l'organisation les liste au fil des changements : choisissez le dossier de l'organisation, clonez ce qui manque et utilisez Chercher des clones pour comparer tout le dossier, à toute profondeur, à la liste du site."$json$::jsonb),
  ('ru', 'org.gitNotConnected', $json$"Подключите git-провайдер, прежде чем добавлять его репозитории."$json$::jsonb),
  ('ru', 'org.gitExpired', $json$"Сеанс git-провайдера на этом сайте истёк. Подключите его снова."$json$::jsonb),
  ('ru', 'org.gitUnavailable', $json$"Git-провайдер не ответил. Попробуйте ещё раз чуть позже."$json$::jsonb),
  ('ru', 'site.org.git.title', $json$"Git-провайдер"$json$::jsonb),
  ('ru', 'site.org.git.description', $json$"Владелец входит здесь в GitHub, GitLab или Bitbucket и выбирает репозитории организации. Токен доступа живёт на этом сайте один час и нигде не записывается."$json$::jsonb),
  ('ru', 'site.org.git.connected', $json$"Подключено как {account}"$json$::jsonb),
  ('ru', 'site.org.git.since', $json$"с {date}"$json$::jsonb),
  ('ru', 'site.org.git.notConnected', $json$"Не подключено"$json$::jsonb),
  ('ru', 'site.org.git.unavailable', $json$"Пока недоступно на этом сайте"$json$::jsonb),
  ('ru', 'site.org.git.connect', $json$"Подключить"$json$::jsonb),
  ('ru', 'site.org.git.reconnect', $json$"Подключить снова"$json$::jsonb),
  ('ru', 'site.org.git.disconnect', $json$"Отключить"$json$::jsonb),
  ('ru', 'site.org.git.disconnect.title', $json$"Отключить {provider}"$json$::jsonb),
  ('ru', 'site.org.git.disconnect.description', $json$"Репозитории организации останутся. Чтобы добавить ещё из {provider}, подключите его снова."$json$::jsonb),
  ('ru', 'site.org.git.disconnected', $json$"{provider} отключён."$json$::jsonb),
  ('ru', 'site.org.git.ownerOnly', $json$"Только владельцы подключают провайдеров и выбирают репозитории."$json$::jsonb),
  ('ru', 'site.org.git.done', $json$"{provider} подключён."$json$::jsonb),
  ('ru', 'site.org.git.denied', $json$"Подключение к {provider} отменено."$json$::jsonb),
  ('ru', 'site.org.git.failed', $json$"Не удалось подключить {provider}. Попробуйте ещё раз."$json$::jsonb),
  ('ru', 'site.org.repos.description', $json$"Участники видят эти репозитории на странице организации в приложении JayV и клонируют их в папку организации со своим доступом к git."$json$::jsonb),
  ('ru', 'site.org.repos.add', $json$"Добавить репозитории"$json$::jsonb),
  ('ru', 'site.org.repos.connectFirst', $json$"Подключите провайдера выше, чтобы добавить репозитории."$json$::jsonb),
  ('ru', 'site.org.repos.private', $json$"Приватный"$json$::jsonb),
  ('ru', 'site.org.repos.public', $json$"Публичный"$json$::jsonb),
  ('ru', 'site.org.repos.manual', $json$"Добавлен по URL"$json$::jsonb),
  ('ru', 'site.org.repos.open', $json$"Открыть в {provider}"$json$::jsonb),
  ('ru', 'site.org.repos.removed', $json$"Репозиторий удалён."$json$::jsonb),
  ('ru', 'site.org.repos.pick.title', $json$"Добавить репозитории"$json$::jsonb),
  ('ru', 'site.org.repos.pick.description', $json$"Что доступно {account} в {provider}. Отметьте репозитории, которые относятся к организации."$json$::jsonb),
  ('ru', 'site.org.repos.pick.search', $json$"Поиск репозиториев"$json$::jsonb),
  ('ru', 'site.org.repos.pick.placeholder', $json$"Фильтр по имени или описанию…"$json$::jsonb),
  ('ru', 'site.org.repos.pick.loading', $json$"Загрузка репозиториев…"$json$::jsonb),
  ('ru', 'site.org.repos.pick.empty', $json$"Репозитории не найдены."$json$::jsonb),
  ('ru', 'site.org.repos.pick.added', $json$"Уже в организации"$json$::jsonb),
  ('ru', 'site.org.repos.pick.truncated', $json$"Показаны недавно обновлённые. Чтобы найти остальные, воспользуйтесь поиском."$json$::jsonb),
  ('ru', 'site.org.repos.pick.expired', $json$"Сеанс {provider} на этом сайте истёк. Подключитесь снова, чтобы увидеть репозитории."$json$::jsonb),
  ('ru', 'site.org.repos.pick.submit', $json$"Добавить выбранные ({count})"$json$::jsonb),
  ('ru', 'site.org.repos.pick.linked', $json${"one": "Добавлен {count} репозиторий.", "few": "Добавлено {count} репозитория.", "many": "Добавлено {count} репозиториев.", "other": "Добавлено {count} репозитория."}$json$::jsonb),
  ('ru', 'site.org.repos.pick.missing', $json$"{provider} не показал эти репозитории для подключённой учётной записи: {paths}."$json$::jsonb),
  ('ru', 'repos.site.owner', $json$"Вы привязываете репозитории на сайте JayV, войдя в GitHub, GitLab или Bitbucket. Этот список обновляется сам."$json$::jsonb),
  ('ru', 'repos.site.member', $json$"Владелец привязывает репозитории на сайте JayV. Этот список обновляется сам; вы клонируете со своим доступом к git."$json$::jsonb),
  ('ru', 'repos.site.none', $json$"Git-провайдер ещё не подключён."$json$::jsonb),
  ('ru', 'repos.private', $json$"Приватный"$json$::jsonb),
  ('ru', 'repos.public', $json$"Публичный"$json$::jsonb),
  ('ru', 'repos.openWeb', $json$"Открыть в {provider}"$json$::jsonb),
  ('ru', 'repos.compare.title', $json$"Сравнение папки с организацией"$json$::jsonb),
  ('ru', 'repos.compare.description', $json$"{path}, поиск на любой глубине: в ней {found} из {total} репозиториев {org}."$json$::jsonb),
  ('ru', 'repos.compare.truncated', $json$"Поиск остановился раньше времени: папка слишком глубокая или большая. Выберите папку поуже, чтобы увидеть всё."$json$::jsonb),
  ('ru', 'repos.compare.empty', $json$"Сравнивать нечего: у организации нет репозиториев, а в папке нет клонов."$json$::jsonb),
  ('ru', 'repos.compare.allSet', $json$"Все репозитории организации есть в этой папке."$json$::jsonb),
  ('ru', 'repos.compare.found', $json$"В папке"$json$::jsonb),
  ('ru', 'repos.compare.project', $json$"Проект"$json$::jsonb),
  ('ru', 'repos.compare.elsewhere', $json$"Уже проект в {path}"$json$::jsonb),
  ('ru', 'repos.compare.missing', $json$"Нет в папке"$json$::jsonb),
  ('ru', 'repos.compare.localElsewhere', $json$"На этом компьютере в {path}"$json$::jsonb),
  ('ru', 'repos.compare.cloneAll', $json$"Клонировать все"$json$::jsonb),
  ('ru', 'repos.compare.outside', $json$"Не из организации"$json$::jsonb),
  ('ru', 'repos.compare.outside.hint', $json$"Клоны в этой папке, которых нет у организации на сайте. Если они её, владелец привяжет их там."$json$::jsonb),
  ('ru', 'repos.compare.noRemote', $json$"Нет remote GitHub, GitLab или Bitbucket"$json$::jsonb),
  ('ru', 'whatsNew.item.repositoriesFromSite.title', $json$"Репозитории приходят с сайта"$json$::jsonb),
  ('ru', 'whatsNew.item.repositoriesFromSite.detail', $json$"Теперь владелец привязывает репозитории организации на сайте JayV, войдя в GitHub, GitLab или Bitbucket, и они сами появляются в приложении. Поле для вставки URL репозитория из приложения убрано."$json$::jsonb),
  ('ru', 'whatsNew.item.folderCompare.title', $json$"«Найти клоны» смотрит всю папку"$json$::jsonb),
  ('ru', 'whatsNew.item.folderCompare.detail', $json$"«Найти клоны» теперь ищет в папке организации на любой глубине и сравнивает её с репозиториями на сайте: что уже есть, чего не хватает (клонируйте по одному или все сразу) и какие клоны не относятся к организации."$json$::jsonb),
  ('ru', 'docs.organizations.usage', $json$"Создайте организацию, пригласите участников и привяжите её репозитории в панели сайта JayV. В приложении Ctrl+2 (⌘2 на Mac) открывает ваши организации и их репозитории."$json$::jsonb),
  ('ru', 'docs.orgRepositories.title', $json$"Репозитории организации"$json$::jsonb),
  ('ru', 'docs.orgRepositories.summary', $json$"Владелец привязывает репозитории организации на сайте JayV, войдя в GitHub, GitLab или Bitbucket. Приложение показывает их само, а каждый участник клонирует их со своим доступом к git."$json$::jsonb),
  ('ru', 'docs.orgRepositories.usage', $json$"На сайте откройте организацию, перейдите в «Репозитории», подключите провайдера и добавьте репозитории. В приложении страница организации показывает их по мере изменений: выберите папку организации, клонируйте недостающие и с помощью «Найти клоны» сравните всю папку, на любой глубине, со списком с сайта."$json$::jsonb),
  ('ja', 'org.gitNotConnected', $json$"リポジトリを追加する前に Git プロバイダーを接続してください。"$json$::jsonb),
  ('ja', 'org.gitExpired', $json$"このサイトでの Git プロバイダーのセッションが期限切れです。もう一度接続してください。"$json$::jsonb),
  ('ja', 'org.gitUnavailable', $json$"Git プロバイダーが応答しませんでした。しばらくしてからもう一度お試しください。"$json$::jsonb),
  ('ja', 'site.org.git.title', $json$"Git プロバイダー"$json$::jsonb),
  ('ja', 'site.org.git.description', $json$"オーナーがここで GitHub・GitLab・Bitbucket にサインインし、組織のリポジトリを選びます。アクセストークンはこのサイトに 1 時間だけ置かれ、保存されることはありません。"$json$::jsonb),
  ('ja', 'site.org.git.connected', $json$"{account} として接続済み"$json$::jsonb),
  ('ja', 'site.org.git.since', $json$"{date} から"$json$::jsonb),
  ('ja', 'site.org.git.notConnected', $json$"未接続"$json$::jsonb),
  ('ja', 'site.org.git.unavailable', $json$"このサイトではまだ利用できません"$json$::jsonb),
  ('ja', 'site.org.git.connect', $json$"接続"$json$::jsonb),
  ('ja', 'site.org.git.reconnect', $json$"再接続"$json$::jsonb),
  ('ja', 'site.org.git.disconnect', $json$"接続を解除"$json$::jsonb),
  ('ja', 'site.org.git.disconnect.title', $json$"{provider} の接続を解除"$json$::jsonb),
  ('ja', 'site.org.git.disconnect.description', $json$"組織のリポジトリはそのまま残ります。{provider} からさらに追加するには、もう一度接続してください。"$json$::jsonb),
  ('ja', 'site.org.git.disconnected', $json$"{provider} の接続を解除しました。"$json$::jsonb),
  ('ja', 'site.org.git.ownerOnly', $json$"プロバイダーの接続とリポジトリの選択ができるのはオーナーだけです。"$json$::jsonb),
  ('ja', 'site.org.git.done', $json$"{provider} を接続しました。"$json$::jsonb),
  ('ja', 'site.org.git.denied', $json$"{provider} との接続はキャンセルされました。"$json$::jsonb),
  ('ja', 'site.org.git.failed', $json$"{provider} を接続できませんでした。もう一度お試しください。"$json$::jsonb),
  ('ja', 'site.org.repos.description', $json$"メンバーは JayV アプリの組織ページでこれらのリポジトリを確認し、自分の Git アクセスで組織フォルダーにクローンします。"$json$::jsonb),
  ('ja', 'site.org.repos.add', $json$"リポジトリを追加"$json$::jsonb),
  ('ja', 'site.org.repos.connectFirst', $json$"リポジトリを追加するには、上でプロバイダーを接続してください。"$json$::jsonb),
  ('ja', 'site.org.repos.private', $json$"非公開"$json$::jsonb),
  ('ja', 'site.org.repos.public', $json$"公開"$json$::jsonb),
  ('ja', 'site.org.repos.manual', $json$"URL で追加"$json$::jsonb),
  ('ja', 'site.org.repos.open', $json$"{provider} で開く"$json$::jsonb),
  ('ja', 'site.org.repos.removed', $json$"リポジトリを削除しました。"$json$::jsonb),
  ('ja', 'site.org.repos.pick.title', $json$"リポジトリを追加"$json$::jsonb),
  ('ja', 'site.org.repos.pick.description', $json$"{provider} で {account} がアクセスできるリポジトリです。組織のものにチェックを入れてください。"$json$::jsonb),
  ('ja', 'site.org.repos.pick.search', $json$"リポジトリを検索"$json$::jsonb),
  ('ja', 'site.org.repos.pick.placeholder', $json$"名前や説明で絞り込み…"$json$::jsonb),
  ('ja', 'site.org.repos.pick.loading', $json$"リポジトリを読み込んでいます…"$json$::jsonb),
  ('ja', 'site.org.repos.pick.empty', $json$"リポジトリが見つかりません。"$json$::jsonb),
  ('ja', 'site.org.repos.pick.added', $json$"組織に追加済み"$json$::jsonb),
  ('ja', 'site.org.repos.pick.truncated', $json$"最近更新されたものを表示しています。ほかのリポジトリは検索してください。"$json$::jsonb),
  ('ja', 'site.org.repos.pick.expired', $json$"このサイトでの {provider} のセッションが期限切れです。リポジトリを表示するには再接続してください。"$json$::jsonb),
  ('ja', 'site.org.repos.pick.submit', $json$"選択したものを追加（{count}）"$json$::jsonb),
  ('ja', 'site.org.repos.pick.linked', $json${"other": "{count} 件のリポジトリを追加しました。"}$json$::jsonb),
  ('ja', 'site.org.repos.pick.missing', $json$"接続中のアカウントでは {provider} に次のリポジトリが表示されませんでした: {paths}。"$json$::jsonb),
  ('ja', 'repos.site.owner', $json$"リポジトリは JayV サイトで GitHub・GitLab・Bitbucket にサインインして関連付けます。この一覧は自動で更新されます。"$json$::jsonb),
  ('ja', 'repos.site.member', $json$"リポジトリはオーナーが JayV サイトで関連付けます。この一覧は自動で更新され、クローンはあなた自身の Git アクセスで行います。"$json$::jsonb),
  ('ja', 'repos.site.none', $json$"Git プロバイダーはまだ接続されていません。"$json$::jsonb),
  ('ja', 'repos.private', $json$"非公開"$json$::jsonb),
  ('ja', 'repos.public', $json$"公開"$json$::jsonb),
  ('ja', 'repos.openWeb', $json$"{provider} で開く"$json$::jsonb),
  ('ja', 'repos.compare.title', $json$"フォルダーと組織の比較"$json$::jsonb),
  ('ja', 'repos.compare.description', $json$"{path} をすべての階層で検索しました: {org} の {total} 件のリポジトリのうち {found} 件があります。"$json$::jsonb),
  ('ja', 'repos.compare.truncated', $json$"検索は途中で止まりました。フォルダーが深すぎるか大きすぎます。すべてを見るには、より狭いフォルダーを選んでください。"$json$::jsonb),
  ('ja', 'repos.compare.empty', $json$"比較するものがありません。組織にリポジトリがなく、フォルダーにもクローンがありません。"$json$::jsonb),
  ('ja', 'repos.compare.allSet', $json$"組織のリポジトリはすべてこのフォルダーにあります。"$json$::jsonb),
  ('ja', 'repos.compare.found', $json$"フォルダー内"$json$::jsonb),
  ('ja', 'repos.compare.project', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'repos.compare.elsewhere', $json$"{path} ですでにプロジェクトです"$json$::jsonb),
  ('ja', 'repos.compare.missing', $json$"フォルダーにない"$json$::jsonb),
  ('ja', 'repos.compare.localElsewhere', $json$"このコンピューターの {path} にあります"$json$::jsonb),
  ('ja', 'repos.compare.cloneAll', $json$"すべてクローン"$json$::jsonb),
  ('ja', 'repos.compare.outside', $json$"組織にないもの"$json$::jsonb),
  ('ja', 'repos.compare.outside.hint', $json$"このフォルダーにあるクローンのうち、組織がサイトに登録していないものです。組織のものなら、オーナーがサイトで関連付けます。"$json$::jsonb),
  ('ja', 'repos.compare.noRemote', $json$"GitHub・GitLab・Bitbucket の remote がありません"$json$::jsonb),
  ('ja', 'whatsNew.item.repositoriesFromSite.title', $json$"リポジトリはサイトから"$json$::jsonb),
  ('ja', 'whatsNew.item.repositoriesFromSite.detail', $json$"オーナーは JayV サイトで GitHub・GitLab・Bitbucket にサインインして組織のリポジトリを関連付けるようになり、アプリには自動で表示されます。アプリからリポジトリ URL の入力欄はなくなりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.folderCompare.title', $json$"「クローンを探す」がフォルダー全体を確認"$json$::jsonb),
  ('ja', 'whatsNew.item.folderCompare.detail', $json$"「クローンを探す」は組織フォルダーをすべての階層で検索し、サイトのリポジトリと比較するようになりました。すでにあるもの、足りないもの（1 件ずつでもまとめてでもクローン可能）、組織に属さないクローンがわかります。"$json$::jsonb),
  ('ja', 'docs.organizations.usage', $json$"JayV サイトのダッシュボードで組織を作成し、メンバーを招待して、リポジトリを関連付けます。アプリでは Ctrl+2（Mac では ⌘2）で組織とそのリポジトリを開けます。"$json$::jsonb),
  ('ja', 'docs.orgRepositories.title', $json$"組織のリポジトリ"$json$::jsonb),
  ('ja', 'docs.orgRepositories.summary', $json$"オーナーが JayV サイトで GitHub・GitLab・Bitbucket にサインインして組織のリポジトリを関連付けます。アプリは自動で一覧を表示し、各メンバーは自分の Git アクセスでクローンします。"$json$::jsonb),
  ('ja', 'docs.orgRepositories.usage', $json$"サイトで組織を開き、「リポジトリ」でプロバイダーを接続してリポジトリを追加します。アプリの組織ページには変更がすぐに反映されます。組織フォルダーを選び、足りないものをクローンし、「クローンを探す」でフォルダー全体をすべての階層でサイトの一覧と比較します。"$json$::jsonb),
  ('de', 'org.gitNotConnected', $json$"Verbinde den Git-Anbieter, bevor du seine Repositorys hinzufügst."$json$::jsonb),
  ('de', 'org.gitExpired', $json$"Die Sitzung des Git-Anbieters auf dieser Website ist abgelaufen. Verbinde ihn erneut."$json$::jsonb),
  ('de', 'org.gitUnavailable', $json$"Der Git-Anbieter hat nicht geantwortet. Versuche es gleich noch einmal."$json$::jsonb),
  ('de', 'site.org.git.title', $json$"Git-Anbieter"$json$::jsonb),
  ('de', 'site.org.git.description', $json$"Der Owner meldet sich hier bei GitHub, GitLab oder Bitbucket an und wählt die Repositorys der Organisation. Das Zugriffstoken bleibt eine Stunde auf dieser Website und wird nie gespeichert."$json$::jsonb),
  ('de', 'site.org.git.connected', $json$"Verbunden als {account}"$json$::jsonb),
  ('de', 'site.org.git.since', $json$"seit {date}"$json$::jsonb),
  ('de', 'site.org.git.notConnected', $json$"Nicht verbunden"$json$::jsonb),
  ('de', 'site.org.git.unavailable', $json$"Auf dieser Website noch nicht verfügbar"$json$::jsonb),
  ('de', 'site.org.git.connect', $json$"Verbinden"$json$::jsonb),
  ('de', 'site.org.git.reconnect', $json$"Erneut verbinden"$json$::jsonb),
  ('de', 'site.org.git.disconnect', $json$"Trennen"$json$::jsonb),
  ('de', 'site.org.git.disconnect.title', $json$"{provider} trennen"$json$::jsonb),
  ('de', 'site.org.git.disconnect.description', $json$"Die Repositorys der Organisation bleiben. Um weitere aus {provider} hinzuzufügen, verbinde ihn erneut."$json$::jsonb),
  ('de', 'site.org.git.disconnected', $json$"{provider} getrennt."$json$::jsonb),
  ('de', 'site.org.git.ownerOnly', $json$"Nur Owner verbinden Anbieter und wählen die Repositorys."$json$::jsonb),
  ('de', 'site.org.git.done', $json$"{provider} verbunden."$json$::jsonb),
  ('de', 'site.org.git.denied', $json$"Die Verbindung mit {provider} wurde abgebrochen."$json$::jsonb),
  ('de', 'site.org.git.failed', $json$"{provider} konnte nicht verbunden werden. Versuche es erneut."$json$::jsonb),
  ('de', 'site.org.repos.description', $json$"Mitglieder sehen diese Repositorys auf der Organisationsseite der JayV-App und klonen sie mit ihrem eigenen Git-Zugang in ihren Organisationsordner."$json$::jsonb),
  ('de', 'site.org.repos.add', $json$"Repositorys hinzufügen"$json$::jsonb),
  ('de', 'site.org.repos.connectFirst', $json$"Verbinde oben einen Anbieter, um Repositorys hinzuzufügen."$json$::jsonb),
  ('de', 'site.org.repos.private', $json$"Privat"$json$::jsonb),
  ('de', 'site.org.repos.public', $json$"Öffentlich"$json$::jsonb),
  ('de', 'site.org.repos.manual', $json$"Per URL hinzugefügt"$json$::jsonb),
  ('de', 'site.org.repos.open', $json$"Auf {provider} öffnen"$json$::jsonb),
  ('de', 'site.org.repos.removed', $json$"Repository entfernt."$json$::jsonb),
  ('de', 'site.org.repos.pick.title', $json$"Repositorys hinzufügen"$json$::jsonb),
  ('de', 'site.org.repos.pick.description', $json$"Worauf {account} auf {provider} Zugriff hat. Markiere die, die zur Organisation gehören."$json$::jsonb),
  ('de', 'site.org.repos.pick.search', $json$"Repositorys durchsuchen"$json$::jsonb),
  ('de', 'site.org.repos.pick.placeholder', $json$"Nach Name oder Beschreibung filtern…"$json$::jsonb),
  ('de', 'site.org.repos.pick.loading', $json$"Repositorys werden geladen…"$json$::jsonb),
  ('de', 'site.org.repos.pick.empty', $json$"Keine Repositorys gefunden."$json$::jsonb),
  ('de', 'site.org.repos.pick.added', $json$"In der Organisation"$json$::jsonb),
  ('de', 'site.org.repos.pick.truncated', $json$"Es werden die zuletzt aktualisierten angezeigt. Suche, um die anderen zu finden."$json$::jsonb),
  ('de', 'site.org.repos.pick.expired', $json$"Die {provider}-Sitzung auf dieser Website ist abgelaufen. Verbinde dich erneut, um die Repositorys aufzulisten."$json$::jsonb),
  ('de', 'site.org.repos.pick.submit', $json$"Auswahl hinzufügen ({count})"$json$::jsonb),
  ('de', 'site.org.repos.pick.linked', $json${"one": "{count} Repository hinzugefügt.", "other": "{count} Repositorys hinzugefügt."}$json$::jsonb),
  ('de', 'site.org.repos.pick.missing', $json$"{provider} hat diese mit dem verbundenen Konto nicht angezeigt: {paths}."$json$::jsonb),
  ('de', 'repos.site.owner', $json$"Du verknüpfst die Repositorys auf der JayV-Website, indem du dich bei GitHub, GitLab oder Bitbucket anmeldest. Diese Liste aktualisiert sich von selbst."$json$::jsonb),
  ('de', 'repos.site.member', $json$"Der Owner verknüpft die Repositorys auf der JayV-Website. Diese Liste aktualisiert sich von selbst; du klonst mit deinem eigenen Git-Zugang."$json$::jsonb),
  ('de', 'repos.site.none', $json$"Noch kein Git-Anbieter verbunden."$json$::jsonb),
  ('de', 'repos.private', $json$"Privat"$json$::jsonb),
  ('de', 'repos.public', $json$"Öffentlich"$json$::jsonb),
  ('de', 'repos.openWeb', $json$"Auf {provider} öffnen"$json$::jsonb),
  ('de', 'repos.compare.title', $json$"Ordner im Vergleich zur Organisation"$json$::jsonb),
  ('de', 'repos.compare.description', $json$"{path}, in jeder Tiefe durchsucht: {found} der {total} Repositorys von {org} liegen darin."$json$::jsonb),
  ('de', 'repos.compare.truncated', $json$"Die Suche hat vor dem Ende angehalten: Der Ordner ist zu tief oder zu groß. Wähle einen engeren Ordner, um alles zu sehen."$json$::jsonb),
  ('de', 'repos.compare.empty', $json$"Nichts zu vergleichen: Die Organisation hat keine Repositorys und der Ordner keine Klone."$json$::jsonb),
  ('de', 'repos.compare.allSet', $json$"Alle Repositorys der Organisation liegen in diesem Ordner."$json$::jsonb),
  ('de', 'repos.compare.found', $json$"Im Ordner"$json$::jsonb),
  ('de', 'repos.compare.project', $json$"Projekt"$json$::jsonb),
  ('de', 'repos.compare.elsewhere', $json$"Bereits ein Projekt in {path}"$json$::jsonb),
  ('de', 'repos.compare.missing', $json$"Nicht im Ordner"$json$::jsonb),
  ('de', 'repos.compare.localElsewhere', $json$"Auf diesem Computer in {path}"$json$::jsonb),
  ('de', 'repos.compare.cloneAll', $json$"Alle klonen"$json$::jsonb),
  ('de', 'repos.compare.outside', $json$"Nicht in der Organisation"$json$::jsonb),
  ('de', 'repos.compare.outside.hint', $json$"Klone in diesem Ordner, die die Organisation auf der Website nicht hat. Wenn sie zu ihr gehören, verknüpft der Owner sie dort."$json$::jsonb),
  ('de', 'repos.compare.noRemote', $json$"Kein Remote von GitHub, GitLab oder Bitbucket"$json$::jsonb),
  ('de', 'whatsNew.item.repositoriesFromSite.title', $json$"Die Repositorys kommen von der Website"$json$::jsonb),
  ('de', 'whatsNew.item.repositoriesFromSite.detail', $json$"Der Owner verknüpft die Repositorys der Organisation jetzt auf der JayV-Website, indem er sich bei GitHub, GitLab oder Bitbucket anmeldet, und sie erscheinen von selbst in der App. Das Feld zum Einfügen einer Repository-URL ist aus der App verschwunden."$json$::jsonb),
  ('de', 'whatsNew.item.folderCompare.title', $json$"Klone suchen durchsucht den ganzen Ordner"$json$::jsonb),
  ('de', 'whatsNew.item.folderCompare.detail', $json$"Klone suchen durchsucht den Organisationsordner jetzt in jeder Tiefe und vergleicht ihn mit den Repositorys auf der Website: was schon da ist, was fehlt (einzeln oder alle auf einmal klonen) und welche Klone nicht zur Organisation gehören."$json$::jsonb),
  ('de', 'docs.organizations.usage', $json$"Erstelle eine Organisation, lade Mitglieder ein und verknüpfe ihre Repositorys im Dashboard der JayV-Website. In der App öffnet Strg+2 (⌘2 auf dem Mac) deine Organisationen und ihre Repositorys."$json$::jsonb),
  ('de', 'docs.orgRepositories.title', $json$"Repositorys der Organisation"$json$::jsonb),
  ('de', 'docs.orgRepositories.summary', $json$"Der Owner verknüpft die Repositorys der Organisation auf der JayV-Website, indem er sich bei GitHub, GitLab oder Bitbucket anmeldet. Die App listet sie von selbst auf, und jedes Mitglied klont sie mit seinem eigenen Git-Zugang."$json$::jsonb),
  ('de', 'docs.orgRepositories.usage', $json$"Öffne auf der Website die Organisation, gehe zu Repositories, verbinde einen Anbieter und füge die Repositorys hinzu. In der App listet die Organisationsseite sie auf, sobald sie sich ändern: Wähle den Organisationsordner, klone, was fehlt, und vergleiche mit Klone suchen den ganzen Ordner in jeder Tiefe mit der Liste der Website."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
