-- v0.37.0: cara de terminal, no estilo do Warp.
--
-- Só textos: o app ganha uma paleta de comandos (Ctrl+K / ⌘K), uma barra de
-- status no pé da janela, os atalhos à vista na caixa de mensagem e os itens
-- da janela "Novidades" desta versão. As cores do app não mudaram.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'composer.key.send', $json$"enviar"$json$::jsonb),
  ('pt-BR', 'composer.key.answer', $json$"enviar a resposta"$json$::jsonb),
  ('pt-BR', 'composer.key.newline', $json$"nova linha"$json$::jsonb),
  ('pt-BR', 'palette.title', $json$"Comandos"$json$::jsonb),
  ('pt-BR', 'palette.placeholder', $json$"Digite um comando, projeto ou chat…"$json$::jsonb),
  ('pt-BR', 'palette.empty', $json$"Nenhum comando combina com o que você digitou."$json$::jsonb),
  ('pt-BR', 'palette.group.project', $json$"Este projeto"$json$::jsonb),
  ('pt-BR', 'palette.group.chats', $json$"Chats recentes"$json$::jsonb),
  ('pt-BR', 'palette.group.navigate', $json$"Ir para"$json$::jsonb),
  ('pt-BR', 'palette.group.projects', $json$"Projetos"$json$::jsonb),
  ('pt-BR', 'palette.group.organizations', $json$"Organizações"$json$::jsonb),
  ('pt-BR', 'palette.group.appearance', $json$"Aparência"$json$::jsonb),
  ('pt-BR', 'palette.group.help', $json$"Ajuda"$json$::jsonb),
  ('pt-BR', 'palette.theme', $json$"Tema: {name}"$json$::jsonb),
  ('pt-BR', 'palette.whatsNew', $json$"Novidades do JayV"$json$::jsonb),
  ('pt-BR', 'palette.hint.move', $json$"mover"$json$::jsonb),
  ('pt-BR', 'palette.hint.run', $json$"rodar"$json$::jsonb),
  ('pt-BR', 'palette.hint.close', $json$"fechar"$json$::jsonb),
  ('pt-BR', 'status.synced', $json$"sincronizado"$json$::jsonb),
  ('pt-BR', 'status.gate', $json$"Abrir a portaria deste projeto"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.terminalLook.title', $json$"Cara de terminal"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.terminalLook.detail', $json$"O JayV agora parece um terminal moderno, no estilo do Warp, com as mesmas cores de antes. O app inteiro usa uma fonte monoespaçada. Cada pedido e sua resposta formam um bloco, e a margem esquerda do bloco fica âmbar ou vermelha quando a portaria fez uma pergunta ou o barrou. A caixa de mensagem é um prompt com os atalhos à vista, e o código mostra o número das linhas."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.commandPalette.title', $json$"Paleta de comandos (Ctrl+K / ⌘K)"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.commandPalette.detail', $json$"Aperte Ctrl+K (⌘K no Mac) em qualquer tela para buscar tudo que tem botão: ir a uma página, abrir um projeto, chat ou organização, começar um chat novo ou trocar o tema. Ctrl+1 a Ctrl+4 abrem Projetos, Organizações, Estatísticas e Sistema, Ctrl+N começa um chat novo, Ctrl+G abre a portaria e Ctrl+, abre as configurações."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.statusBar.title', $json$"Barra de status"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.statusBar.detail', $json$"Uma barra no pé da janela mostra se suas alterações estão sincronizadas, a pasta do projeto aberto, a contagem da portaria dele e a versão instalada. Clique na contagem para abrir a portaria, ou na versão para ver as novidades."$json$::jsonb),
  ('en', 'composer.key.send', $json$"send"$json$::jsonb),
  ('en', 'composer.key.answer', $json$"send the answer"$json$::jsonb),
  ('en', 'composer.key.newline', $json$"new line"$json$::jsonb),
  ('en', 'palette.title', $json$"Commands"$json$::jsonb),
  ('en', 'palette.placeholder', $json$"Type a command, project or chat…"$json$::jsonb),
  ('en', 'palette.empty', $json$"No command matches what you typed."$json$::jsonb),
  ('en', 'palette.group.project', $json$"This project"$json$::jsonb),
  ('en', 'palette.group.chats', $json$"Recent chats"$json$::jsonb),
  ('en', 'palette.group.navigate', $json$"Go to"$json$::jsonb),
  ('en', 'palette.group.projects', $json$"Projects"$json$::jsonb),
  ('en', 'palette.group.organizations', $json$"Organizations"$json$::jsonb),
  ('en', 'palette.group.appearance', $json$"Appearance"$json$::jsonb),
  ('en', 'palette.group.help', $json$"Help"$json$::jsonb),
  ('en', 'palette.theme', $json$"Theme: {name}"$json$::jsonb),
  ('en', 'palette.whatsNew', $json$"What's new in JayV"$json$::jsonb),
  ('en', 'palette.hint.move', $json$"move"$json$::jsonb),
  ('en', 'palette.hint.run', $json$"run"$json$::jsonb),
  ('en', 'palette.hint.close', $json$"close"$json$::jsonb),
  ('en', 'status.synced', $json$"synced"$json$::jsonb),
  ('en', 'status.gate', $json$"Open the gatehouse of this project"$json$::jsonb),
  ('en', 'whatsNew.item.terminalLook.title', $json$"A terminal look"$json$::jsonb),
  ('en', 'whatsNew.item.terminalLook.detail', $json$"JayV now looks like a modern terminal, in the style of Warp, with the same colors as before. The whole app uses a monospaced font. Each request and its answer form one block, and the block's left edge turns amber or red when the gatehouse asked a question or blocked it. The message box is a prompt with its shortcuts in view, and code shows line numbers."$json$::jsonb),
  ('en', 'whatsNew.item.commandPalette.title', $json$"Command palette (Ctrl+K / ⌘K)"$json$::jsonb),
  ('en', 'whatsNew.item.commandPalette.detail', $json$"Press Ctrl+K (⌘K on Mac) on any screen to search everything that has a button: go to a page, open a project, chat or organization, start a new chat or change the theme. Ctrl+1 to Ctrl+4 open Projects, Organizations, Statistics and System, Ctrl+N starts a new chat, Ctrl+G opens the gatehouse and Ctrl+, opens the settings."$json$::jsonb),
  ('en', 'whatsNew.item.statusBar.title', $json$"Status bar"$json$::jsonb),
  ('en', 'whatsNew.item.statusBar.detail', $json$"A bar at the bottom of the window shows whether your changes are synced, the folder of the open project, its gatehouse count and the installed version. Click the count to open the gatehouse, or the version to see what's new."$json$::jsonb),
  ('es', 'composer.key.send', $json$"enviar"$json$::jsonb),
  ('es', 'composer.key.answer', $json$"enviar la respuesta"$json$::jsonb),
  ('es', 'composer.key.newline', $json$"nueva línea"$json$::jsonb),
  ('es', 'palette.title', $json$"Comandos"$json$::jsonb),
  ('es', 'palette.placeholder', $json$"Escribe un comando, proyecto o chat…"$json$::jsonb),
  ('es', 'palette.empty', $json$"Ningún comando coincide con lo que escribiste."$json$::jsonb),
  ('es', 'palette.group.project', $json$"Este proyecto"$json$::jsonb),
  ('es', 'palette.group.chats', $json$"Chats recientes"$json$::jsonb),
  ('es', 'palette.group.navigate', $json$"Ir a"$json$::jsonb),
  ('es', 'palette.group.projects', $json$"Proyectos"$json$::jsonb),
  ('es', 'palette.group.organizations', $json$"Organizaciones"$json$::jsonb),
  ('es', 'palette.group.appearance', $json$"Apariencia"$json$::jsonb),
  ('es', 'palette.group.help', $json$"Ayuda"$json$::jsonb),
  ('es', 'palette.theme', $json$"Tema: {name}"$json$::jsonb),
  ('es', 'palette.whatsNew', $json$"Novedades de JayV"$json$::jsonb),
  ('es', 'palette.hint.move', $json$"mover"$json$::jsonb),
  ('es', 'palette.hint.run', $json$"ejecutar"$json$::jsonb),
  ('es', 'palette.hint.close', $json$"cerrar"$json$::jsonb),
  ('es', 'status.synced', $json$"sincronizado"$json$::jsonb),
  ('es', 'status.gate', $json$"Abrir la portería de este proyecto"$json$::jsonb),
  ('es', 'whatsNew.item.terminalLook.title', $json$"Aspecto de terminal"$json$::jsonb),
  ('es', 'whatsNew.item.terminalLook.detail', $json$"JayV ahora parece una terminal moderna, al estilo de Warp, con los mismos colores de antes. Toda la app usa una fuente monoespaciada. Cada solicitud y su respuesta forman un bloque, y el borde izquierdo del bloque se vuelve ámbar o rojo cuando la portería hizo una pregunta o la bloqueó. La caja de mensajes es un prompt con sus atajos a la vista, y el código muestra números de línea."$json$::jsonb),
  ('es', 'whatsNew.item.commandPalette.title', $json$"Paleta de comandos (Ctrl+K / ⌘K)"$json$::jsonb),
  ('es', 'whatsNew.item.commandPalette.detail', $json$"Pulsa Ctrl+K (⌘K en Mac) en cualquier pantalla para buscar todo lo que tiene un botón: ir a una página, abrir un proyecto, chat u organización, empezar un chat nuevo o cambiar el tema. Ctrl+1 a Ctrl+4 abren Proyectos, Organizaciones, Estadísticas y Sistema, Ctrl+N empieza un chat nuevo, Ctrl+G abre la portería y Ctrl+, abre la configuración."$json$::jsonb),
  ('es', 'whatsNew.item.statusBar.title', $json$"Barra de estado"$json$::jsonb),
  ('es', 'whatsNew.item.statusBar.detail', $json$"Una barra al pie de la ventana muestra si tus cambios están sincronizados, la carpeta del proyecto abierto, el conteo de su portería y la versión instalada. Haz clic en el conteo para abrir la portería, o en la versión para ver las novedades."$json$::jsonb),
  ('zh-CN', 'composer.key.send', $json$"发送"$json$::jsonb),
  ('zh-CN', 'composer.key.answer', $json$"发送回答"$json$::jsonb),
  ('zh-CN', 'composer.key.newline', $json$"换行"$json$::jsonb),
  ('zh-CN', 'palette.title', $json$"命令"$json$::jsonb),
  ('zh-CN', 'palette.placeholder', $json$"输入命令、项目或聊天…"$json$::jsonb),
  ('zh-CN', 'palette.empty', $json$"没有与输入匹配的命令。"$json$::jsonb),
  ('zh-CN', 'palette.group.project', $json$"此项目"$json$::jsonb),
  ('zh-CN', 'palette.group.chats', $json$"最近的聊天"$json$::jsonb),
  ('zh-CN', 'palette.group.navigate', $json$"前往"$json$::jsonb),
  ('zh-CN', 'palette.group.projects', $json$"项目"$json$::jsonb),
  ('zh-CN', 'palette.group.organizations', $json$"组织"$json$::jsonb),
  ('zh-CN', 'palette.group.appearance', $json$"外观"$json$::jsonb),
  ('zh-CN', 'palette.group.help', $json$"帮助"$json$::jsonb),
  ('zh-CN', 'palette.theme', $json$"主题：{name}"$json$::jsonb),
  ('zh-CN', 'palette.whatsNew', $json$"JayV 新功能"$json$::jsonb),
  ('zh-CN', 'palette.hint.move', $json$"移动"$json$::jsonb),
  ('zh-CN', 'palette.hint.run', $json$"运行"$json$::jsonb),
  ('zh-CN', 'palette.hint.close', $json$"关闭"$json$::jsonb),
  ('zh-CN', 'status.synced', $json$"已同步"$json$::jsonb),
  ('zh-CN', 'status.gate', $json$"打开此项目的门卫"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.terminalLook.title', $json$"终端风格外观"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.terminalLook.detail', $json$"JayV 现在看起来像一个现代终端，风格类似 Warp，颜色与之前相同。整个应用使用等宽字体。每个请求及其回答组成一个块，当门卫提出问题或拦截请求时，块的左边缘会变为琥珀色或红色。消息框是一个可以看到快捷键的提示符，代码会显示行号。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.commandPalette.title', $json$"命令面板 (Ctrl+K / ⌘K)"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.commandPalette.detail', $json$"在任意界面按 Ctrl+K（Mac 上为 ⌘K），即可搜索所有带按钮的操作：前往某个页面、打开项目、聊天或组织、开始新聊天或切换主题。Ctrl+1 到 Ctrl+4 分别打开项目、组织、统计和系统，Ctrl+N 开始新聊天，Ctrl+G 打开门卫，Ctrl+, 打开设置。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.statusBar.title', $json$"状态栏"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.statusBar.detail', $json$"窗口底部的状态栏显示你的更改是否已同步、当前项目的文件夹、它的门卫计数以及已安装的版本。点击计数可打开门卫，点击版本可查看新功能。"$json$::jsonb),
  ('hi', 'composer.key.send', $json$"भेजें"$json$::jsonb),
  ('hi', 'composer.key.answer', $json$"जवाब भेजें"$json$::jsonb),
  ('hi', 'composer.key.newline', $json$"नई पंक्ति"$json$::jsonb),
  ('hi', 'palette.title', $json$"कमांड"$json$::jsonb),
  ('hi', 'palette.placeholder', $json$"कमांड, प्रोजेक्ट या चैट लिखें…"$json$::jsonb),
  ('hi', 'palette.empty', $json$"आपने जो लिखा उससे कोई कमांड मेल नहीं खाता।"$json$::jsonb),
  ('hi', 'palette.group.project', $json$"यह प्रोजेक्ट"$json$::jsonb),
  ('hi', 'palette.group.chats', $json$"हाल की चैट"$json$::jsonb),
  ('hi', 'palette.group.navigate', $json$"यहाँ जाएँ"$json$::jsonb),
  ('hi', 'palette.group.projects', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'palette.group.organizations', $json$"संगठन"$json$::jsonb),
  ('hi', 'palette.group.appearance', $json$"रूप-रंग"$json$::jsonb),
  ('hi', 'palette.group.help', $json$"सहायता"$json$::jsonb),
  ('hi', 'palette.theme', $json$"थीम: {name}"$json$::jsonb),
  ('hi', 'palette.whatsNew', $json$"JayV में नया क्या है"$json$::jsonb),
  ('hi', 'palette.hint.move', $json$"चलें"$json$::jsonb),
  ('hi', 'palette.hint.run', $json$"चलाएँ"$json$::jsonb),
  ('hi', 'palette.hint.close', $json$"बंद करें"$json$::jsonb),
  ('hi', 'status.synced', $json$"सिंक हो गया"$json$::jsonb),
  ('hi', 'status.gate', $json$"इस प्रोजेक्ट का गेटहाउस खोलें"$json$::jsonb),
  ('hi', 'whatsNew.item.terminalLook.title', $json$"टर्मिनल जैसा रूप"$json$::jsonb),
  ('hi', 'whatsNew.item.terminalLook.detail', $json$"JayV अब Warp की शैली में एक आधुनिक टर्मिनल जैसा दिखता है, रंग पहले जैसे ही हैं। पूरा ऐप मोनोस्पेस फ़ॉन्ट इस्तेमाल करता है। हर अनुरोध और उसका जवाब एक ब्लॉक बनाते हैं, और जब गेटहाउस ने सवाल पूछा या उसे रोका, तो ब्लॉक का बायाँ किनारा एम्बर या लाल हो जाता है। संदेश बॉक्स एक प्रॉम्प्ट है जिसमें शॉर्टकट दिखते हैं, और कोड में पंक्ति संख्याएँ दिखती हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.commandPalette.title', $json$"कमांड पैलेट (Ctrl+K / ⌘K)"$json$::jsonb),
  ('hi', 'whatsNew.item.commandPalette.detail', $json$"किसी भी स्क्रीन पर Ctrl+K (Mac पर ⌘K) दबाकर बटन वाली हर चीज़ खोजें: किसी पेज पर जाएँ, प्रोजेक्ट, चैट या संगठन खोलें, नई चैट शुरू करें या थीम बदलें। Ctrl+1 से Ctrl+4 प्रोजेक्ट, संगठन, आँकड़े और सिस्टम खोलते हैं, Ctrl+N नई चैट शुरू करता है, Ctrl+G गेटहाउस और Ctrl+, सेटिंग्स खोलता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.statusBar.title', $json$"स्टेटस बार"$json$::jsonb),
  ('hi', 'whatsNew.item.statusBar.detail', $json$"विंडो के नीचे एक बार दिखाता है कि आपके बदलाव सिंक हुए या नहीं, खुले प्रोजेक्ट का फ़ोल्डर, उसके गेटहाउस की गिनती और इंस्टॉल किया गया वर्ज़न। गेटहाउस खोलने के लिए गिनती पर, या नया क्या है देखने के लिए वर्ज़न पर क्लिक करें।"$json$::jsonb),
  ('ar', 'composer.key.send', $json$"إرسال"$json$::jsonb),
  ('ar', 'composer.key.answer', $json$"إرسال الإجابة"$json$::jsonb),
  ('ar', 'composer.key.newline', $json$"سطر جديد"$json$::jsonb),
  ('ar', 'palette.title', $json$"الأوامر"$json$::jsonb),
  ('ar', 'palette.placeholder', $json$"اكتب أمرًا أو مشروعًا أو محادثة…"$json$::jsonb),
  ('ar', 'palette.empty', $json$"لا يوجد أمر يطابق ما كتبته."$json$::jsonb),
  ('ar', 'palette.group.project', $json$"هذا المشروع"$json$::jsonb),
  ('ar', 'palette.group.chats', $json$"المحادثات الأخيرة"$json$::jsonb),
  ('ar', 'palette.group.navigate', $json$"انتقل إلى"$json$::jsonb),
  ('ar', 'palette.group.projects', $json$"المشاريع"$json$::jsonb),
  ('ar', 'palette.group.organizations', $json$"المؤسسات"$json$::jsonb),
  ('ar', 'palette.group.appearance', $json$"المظهر"$json$::jsonb),
  ('ar', 'palette.group.help', $json$"المساعدة"$json$::jsonb),
  ('ar', 'palette.theme', $json$"السمة: {name}"$json$::jsonb),
  ('ar', 'palette.whatsNew', $json$"الجديد في JayV"$json$::jsonb),
  ('ar', 'palette.hint.move', $json$"تنقّل"$json$::jsonb),
  ('ar', 'palette.hint.run', $json$"تشغيل"$json$::jsonb),
  ('ar', 'palette.hint.close', $json$"إغلاق"$json$::jsonb),
  ('ar', 'status.synced', $json$"متزامن"$json$::jsonb),
  ('ar', 'status.gate', $json$"افتح البوابة الخاصة بهذا المشروع"$json$::jsonb),
  ('ar', 'whatsNew.item.terminalLook.title', $json$"مظهر الطرفية"$json$::jsonb),
  ('ar', 'whatsNew.item.terminalLook.detail', $json$"أصبح JayV يشبه طرفية حديثة على طراز Warp، بالألوان نفسها كما كان. يستخدم التطبيق كله خطًا أحادي المسافة. يشكّل كل طلب وإجابته كتلة واحدة، ويتحوّل الحد الأيسر للكتلة إلى الكهرماني أو الأحمر عندما تطرح البوابة سؤالًا أو تحظر الطلب. صندوق الرسائل موجّه تظهر فيه الاختصارات، ويعرض الكود أرقام الأسطر."$json$::jsonb),
  ('ar', 'whatsNew.item.commandPalette.title', $json$"لوحة الأوامر (Ctrl+K / ⌘K)"$json$::jsonb),
  ('ar', 'whatsNew.item.commandPalette.detail', $json$"اضغط Ctrl+K (أو ⌘K على Mac) في أي شاشة للبحث في كل ما له زر: الانتقال إلى صفحة، أو فتح مشروع أو محادثة أو مؤسسة، أو بدء محادثة جديدة، أو تغيير السمة. تفتح Ctrl+1 إلى Ctrl+4 المشاريع والمؤسسات والإحصاءات والنظام، وتبدأ Ctrl+N محادثة جديدة، وتفتح Ctrl+G البوابة وCtrl+, الإعدادات."$json$::jsonb),
  ('ar', 'whatsNew.item.statusBar.title', $json$"شريط الحالة"$json$::jsonb),
  ('ar', 'whatsNew.item.statusBar.detail', $json$"يعرض شريط أسفل النافذة ما إذا كانت تغييراتك متزامنة، ومجلد المشروع المفتوح، وعدّاد بوابته، والإصدار المثبّت. انقر على العدّاد لفتح البوابة، أو على الإصدار لرؤية الجديد."$json$::jsonb),
  ('fr', 'composer.key.send', $json$"envoyer"$json$::jsonb),
  ('fr', 'composer.key.answer', $json$"envoyer la réponse"$json$::jsonb),
  ('fr', 'composer.key.newline', $json$"nouvelle ligne"$json$::jsonb),
  ('fr', 'palette.title', $json$"Commandes"$json$::jsonb),
  ('fr', 'palette.placeholder', $json$"Tapez une commande, un projet ou un chat…"$json$::jsonb),
  ('fr', 'palette.empty', $json$"Aucune commande ne correspond à votre saisie."$json$::jsonb),
  ('fr', 'palette.group.project', $json$"Ce projet"$json$::jsonb),
  ('fr', 'palette.group.chats', $json$"Chats récents"$json$::jsonb),
  ('fr', 'palette.group.navigate', $json$"Aller à"$json$::jsonb),
  ('fr', 'palette.group.projects', $json$"Projets"$json$::jsonb),
  ('fr', 'palette.group.organizations', $json$"Organisations"$json$::jsonb),
  ('fr', 'palette.group.appearance', $json$"Apparence"$json$::jsonb),
  ('fr', 'palette.group.help', $json$"Aide"$json$::jsonb),
  ('fr', 'palette.theme', $json$"Thème : {name}"$json$::jsonb),
  ('fr', 'palette.whatsNew', $json$"Nouveautés de JayV"$json$::jsonb),
  ('fr', 'palette.hint.move', $json$"déplacer"$json$::jsonb),
  ('fr', 'palette.hint.run', $json$"exécuter"$json$::jsonb),
  ('fr', 'palette.hint.close', $json$"fermer"$json$::jsonb),
  ('fr', 'status.synced', $json$"synchronisé"$json$::jsonb),
  ('fr', 'status.gate', $json$"Ouvrir la loge de ce projet"$json$::jsonb),
  ('fr', 'whatsNew.item.terminalLook.title', $json$"Un air de terminal"$json$::jsonb),
  ('fr', 'whatsNew.item.terminalLook.detail', $json$"JayV ressemble maintenant à un terminal moderne, dans le style de Warp, avec les mêmes couleurs qu'avant. Toute l'application utilise une police à chasse fixe. Chaque demande et sa réponse forment un bloc, et le bord gauche du bloc devient ambre ou rouge quand la loge a posé une question ou l'a bloquée. La zone de message est une invite avec ses raccourcis visibles, et le code affiche les numéros de ligne."$json$::jsonb),
  ('fr', 'whatsNew.item.commandPalette.title', $json$"Palette de commandes (Ctrl+K / ⌘K)"$json$::jsonb),
  ('fr', 'whatsNew.item.commandPalette.detail', $json$"Appuyez sur Ctrl+K (⌘K sur Mac) sur n'importe quel écran pour chercher tout ce qui a un bouton : aller à une page, ouvrir un projet, un chat ou une organisation, démarrer un nouveau chat ou changer de thème. Ctrl+1 à Ctrl+4 ouvrent Projets, Organisations, Statistiques et Système, Ctrl+N démarre un nouveau chat, Ctrl+G ouvre la loge et Ctrl+, ouvre les réglages."$json$::jsonb),
  ('fr', 'whatsNew.item.statusBar.title', $json$"Barre d'état"$json$::jsonb),
  ('fr', 'whatsNew.item.statusBar.detail', $json$"Une barre en bas de la fenêtre indique si vos modifications sont synchronisées, le dossier du projet ouvert, le décompte de sa loge et la version installée. Cliquez sur le décompte pour ouvrir la loge, ou sur la version pour voir les nouveautés."$json$::jsonb),
  ('ru', 'composer.key.send', $json$"отправить"$json$::jsonb),
  ('ru', 'composer.key.answer', $json$"отправить ответ"$json$::jsonb),
  ('ru', 'composer.key.newline', $json$"новая строка"$json$::jsonb),
  ('ru', 'palette.title', $json$"Команды"$json$::jsonb),
  ('ru', 'palette.placeholder', $json$"Введите команду, проект или чат…"$json$::jsonb),
  ('ru', 'palette.empty', $json$"Нет команд, подходящих под ваш запрос."$json$::jsonb),
  ('ru', 'palette.group.project', $json$"Этот проект"$json$::jsonb),
  ('ru', 'palette.group.chats', $json$"Недавние чаты"$json$::jsonb),
  ('ru', 'palette.group.navigate', $json$"Перейти"$json$::jsonb),
  ('ru', 'palette.group.projects', $json$"Проекты"$json$::jsonb),
  ('ru', 'palette.group.organizations', $json$"Организации"$json$::jsonb),
  ('ru', 'palette.group.appearance', $json$"Оформление"$json$::jsonb),
  ('ru', 'palette.group.help', $json$"Справка"$json$::jsonb),
  ('ru', 'palette.theme', $json$"Тема: {name}"$json$::jsonb),
  ('ru', 'palette.whatsNew', $json$"Что нового в JayV"$json$::jsonb),
  ('ru', 'palette.hint.move', $json$"перейти"$json$::jsonb),
  ('ru', 'palette.hint.run', $json$"выполнить"$json$::jsonb),
  ('ru', 'palette.hint.close', $json$"закрыть"$json$::jsonb),
  ('ru', 'status.synced', $json$"синхронизировано"$json$::jsonb),
  ('ru', 'status.gate', $json$"Открыть проходную этого проекта"$json$::jsonb),
  ('ru', 'whatsNew.item.terminalLook.title', $json$"Вид терминала"$json$::jsonb),
  ('ru', 'whatsNew.item.terminalLook.detail', $json$"Теперь JayV выглядит как современный терминал в стиле Warp, с теми же цветами, что и раньше. Всё приложение использует моноширинный шрифт. Каждый запрос и ответ на него образуют один блок, а левый край блока становится янтарным или красным, когда проходная задала вопрос или заблокировала запрос. Поле сообщения — это строка ввода с видимыми сочетаниями клавиш, а в коде показаны номера строк."$json$::jsonb),
  ('ru', 'whatsNew.item.commandPalette.title', $json$"Палитра команд (Ctrl+K / ⌘K)"$json$::jsonb),
  ('ru', 'whatsNew.item.commandPalette.detail', $json$"Нажмите Ctrl+K (⌘K на Mac) на любом экране, чтобы найти всё, у чего есть кнопка: перейти на страницу, открыть проект, чат или организацию, начать новый чат или сменить тему. Ctrl+1–Ctrl+4 открывают Проекты, Организации, Статистику и Систему, Ctrl+N начинает новый чат, Ctrl+G открывает проходную, а Ctrl+, — настройки."$json$::jsonb),
  ('ru', 'whatsNew.item.statusBar.title', $json$"Строка состояния"$json$::jsonb),
  ('ru', 'whatsNew.item.statusBar.detail', $json$"Строка внизу окна показывает, синхронизированы ли ваши изменения, папку открытого проекта, счётчик его проходной и установленную версию. Нажмите на счётчик, чтобы открыть проходную, или на версию, чтобы посмотреть, что нового."$json$::jsonb),
  ('ja', 'composer.key.send', $json$"送信"$json$::jsonb),
  ('ja', 'composer.key.answer', $json$"回答を送信"$json$::jsonb),
  ('ja', 'composer.key.newline', $json$"改行"$json$::jsonb),
  ('ja', 'palette.title', $json$"コマンド"$json$::jsonb),
  ('ja', 'palette.placeholder', $json$"コマンド、プロジェクト、チャットを入力…"$json$::jsonb),
  ('ja', 'palette.empty', $json$"入力に一致するコマンドはありません。"$json$::jsonb),
  ('ja', 'palette.group.project', $json$"このプロジェクト"$json$::jsonb),
  ('ja', 'palette.group.chats', $json$"最近のチャット"$json$::jsonb),
  ('ja', 'palette.group.navigate', $json$"移動"$json$::jsonb),
  ('ja', 'palette.group.projects', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'palette.group.organizations', $json$"組織"$json$::jsonb),
  ('ja', 'palette.group.appearance', $json$"外観"$json$::jsonb),
  ('ja', 'palette.group.help', $json$"ヘルプ"$json$::jsonb),
  ('ja', 'palette.theme', $json$"テーマ: {name}"$json$::jsonb),
  ('ja', 'palette.whatsNew', $json$"JayV の新機能"$json$::jsonb),
  ('ja', 'palette.hint.move', $json$"移動"$json$::jsonb),
  ('ja', 'palette.hint.run', $json$"実行"$json$::jsonb),
  ('ja', 'palette.hint.close', $json$"閉じる"$json$::jsonb),
  ('ja', 'status.synced', $json$"同期済み"$json$::jsonb),
  ('ja', 'status.gate', $json$"このプロジェクトのゲートハウスを開く"$json$::jsonb),
  ('ja', 'whatsNew.item.terminalLook.title', $json$"ターミナル風の見た目"$json$::jsonb),
  ('ja', 'whatsNew.item.terminalLook.detail', $json$"JayV は Warp 風のモダンなターミナルの見た目になりました。色はこれまでと同じです。アプリ全体で等幅フォントを使います。各リクエストと回答は 1 つのブロックになり、ゲートハウスが質問したりブロックしたりすると、ブロックの左端が琥珀色または赤になります。メッセージ欄はショートカットが見えるプロンプトになり、コードには行番号が付きます。"$json$::jsonb),
  ('ja', 'whatsNew.item.commandPalette.title', $json$"コマンドパレット (Ctrl+K / ⌘K)"$json$::jsonb),
  ('ja', 'whatsNew.item.commandPalette.detail', $json$"どの画面でも Ctrl+K (Mac では ⌘K) を押すと、ボタンのある操作をすべて検索できます。ページへの移動、プロジェクト・チャット・組織を開く、新しいチャットの開始、テーマの変更などです。Ctrl+1〜Ctrl+4 でプロジェクト、組織、統計、システムを開き、Ctrl+N で新しいチャット、Ctrl+G でゲートハウス、Ctrl+, で設定を開きます。"$json$::jsonb),
  ('ja', 'whatsNew.item.statusBar.title', $json$"ステータスバー"$json$::jsonb),
  ('ja', 'whatsNew.item.statusBar.detail', $json$"ウィンドウ下部のバーに、変更が同期済みかどうか、開いているプロジェクトのフォルダー、そのゲートハウスの件数、インストール済みのバージョンが表示されます。件数をクリックするとゲートハウスが、バージョンをクリックすると新機能が開きます。"$json$::jsonb),
  ('de', 'composer.key.send', $json$"senden"$json$::jsonb),
  ('de', 'composer.key.answer', $json$"Antwort senden"$json$::jsonb),
  ('de', 'composer.key.newline', $json$"neue Zeile"$json$::jsonb),
  ('de', 'palette.title', $json$"Befehle"$json$::jsonb),
  ('de', 'palette.placeholder', $json$"Befehl, Projekt oder Chat eingeben…"$json$::jsonb),
  ('de', 'palette.empty', $json$"Kein Befehl passt zu deiner Eingabe."$json$::jsonb),
  ('de', 'palette.group.project', $json$"Dieses Projekt"$json$::jsonb),
  ('de', 'palette.group.chats', $json$"Letzte Chats"$json$::jsonb),
  ('de', 'palette.group.navigate', $json$"Gehe zu"$json$::jsonb),
  ('de', 'palette.group.projects', $json$"Projekte"$json$::jsonb),
  ('de', 'palette.group.organizations', $json$"Organisationen"$json$::jsonb),
  ('de', 'palette.group.appearance', $json$"Darstellung"$json$::jsonb),
  ('de', 'palette.group.help', $json$"Hilfe"$json$::jsonb),
  ('de', 'palette.theme', $json$"Design: {name}"$json$::jsonb),
  ('de', 'palette.whatsNew', $json$"Neu in JayV"$json$::jsonb),
  ('de', 'palette.hint.move', $json$"bewegen"$json$::jsonb),
  ('de', 'palette.hint.run', $json$"ausführen"$json$::jsonb),
  ('de', 'palette.hint.close', $json$"schließen"$json$::jsonb),
  ('de', 'status.synced', $json$"synchronisiert"$json$::jsonb),
  ('de', 'status.gate', $json$"Pforte dieses Projekts öffnen"$json$::jsonb),
  ('de', 'whatsNew.item.terminalLook.title', $json$"Ein Terminal-Look"$json$::jsonb),
  ('de', 'whatsNew.item.terminalLook.detail', $json$"JayV sieht jetzt aus wie ein modernes Terminal im Stil von Warp, mit denselben Farben wie bisher. Die ganze App nutzt eine Festbreitenschrift. Jede Anfrage bildet mit ihrer Antwort einen Block, und der linke Rand des Blocks wird bernsteinfarben oder rot, wenn die Pforte eine Frage gestellt oder sie blockiert hat. Das Nachrichtenfeld ist ein Prompt mit sichtbaren Tastenkürzeln, und Code zeigt Zeilennummern."$json$::jsonb),
  ('de', 'whatsNew.item.commandPalette.title', $json$"Befehlspalette (Strg+K / ⌘K)"$json$::jsonb),
  ('de', 'whatsNew.item.commandPalette.detail', $json$"Drücke Strg+K (⌘K auf dem Mac) auf jedem Bildschirm, um alles zu suchen, was einen Knopf hat: zu einer Seite wechseln, ein Projekt, einen Chat oder eine Organisation öffnen, einen neuen Chat beginnen oder das Design wechseln. Strg+1 bis Strg+4 öffnen Projekte, Organisationen, Statistiken und System, Strg+N beginnt einen neuen Chat, Strg+G öffnet die Pforte und Strg+, die Einstellungen."$json$::jsonb),
  ('de', 'whatsNew.item.statusBar.title', $json$"Statusleiste"$json$::jsonb),
  ('de', 'whatsNew.item.statusBar.detail', $json$"Eine Leiste am unteren Fensterrand zeigt, ob deine Änderungen synchronisiert sind, den Ordner des offenen Projekts, den Zähler seiner Pforte und die installierte Version. Klicke auf den Zähler, um die Pforte zu öffnen, oder auf die Version, um die Neuerungen zu sehen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
