-- App v0.65.1 e site 2.0.0: o GitHub é só por GitHub App, no login (o
-- provedor GitHub do Supabase Auth recebe as credenciais do GitHub App) e no
-- provedor git das organizações (sem o fluxo de OAuth App). A novidade da
-- versão e o uso da página orgRepositories da Documentação, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.item.githubApp.title', $json$"GitHub pelo GitHub App do JayV"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.githubApp.detail', $json$"Entrar com o GitHub, no app e no site, e conectar o GitHub aos repositórios de uma organização agora passam pelo GitHub App do JayV, e não mais por um OAuth App. Ao conectar, o GitHub pergunta em qual conta ou organização e quais repositórios o JayV pode ler, e nada além disso fica ao alcance. Uma organização conectada antes precisa conectar o GitHub de novo."$json$::jsonb),
  ('pt-BR', 'docs.orgRepositories.usage', $json$"No site, abra a organização, vá em Repositórios, conecte um provedor e adicione os repositórios. No app, a página da organização os lista conforme mudam: escolha a pasta da organização, clone o que falta e use Procurar clones para comparar a pasta inteira, em qualquer profundidade, com a lista do site. No GitHub, conectar instala o GitHub App do JayV na conta ou na organização que você escolher, e ele alcança só os repositórios que você marcar lá; para adicionar outros, clique em GitHub de novo."$json$::jsonb),
  ('en', 'whatsNew.item.githubApp.title', $json$"GitHub through the JayV GitHub App"$json$::jsonb),
  ('en', 'whatsNew.item.githubApp.detail', $json$"Signing in with GitHub, in the app and on the site, and connecting GitHub to an organization's repositories now go through the JayV GitHub App instead of an OAuth App. When connecting, GitHub asks which account or organization and which repositories JayV may read, and nothing else is reachable. An organization connected before has to connect GitHub again."$json$::jsonb),
  ('en', 'docs.orgRepositories.usage', $json$"On the site, open the organization, go to Repositories, connect a provider and add the repositories. In the app, the organization page lists them as they change: choose the organization folder, clone what is missing, and use Find clones to compare the whole folder, at any depth, with the list from the site. On GitHub, connecting installs the JayV GitHub App on the account or organization you choose, and it reaches only the repositories you pick there; to add more, click GitHub again."$json$::jsonb),
  ('es', 'whatsNew.item.githubApp.title', $json$"GitHub a través de la GitHub App de JayV"$json$::jsonb),
  ('es', 'whatsNew.item.githubApp.detail', $json$"Iniciar sesión con GitHub, en la app y en el sitio, y conectar GitHub a los repositorios de una organización ahora pasan por la GitHub App de JayV en lugar de una OAuth App. Al conectar, GitHub pregunta en qué cuenta u organización y qué repositorios puede leer JayV, y nada más queda a su alcance. Una organización conectada antes tiene que volver a conectar GitHub."$json$::jsonb),
  ('es', 'docs.orgRepositories.usage', $json$"En el sitio, abre la organización, ve a Repositorios, conecta un proveedor y añade los repositorios. En la app, la página de la organización los lista a medida que cambian: elige la carpeta de la organización, clona lo que falta y usa Buscar clones para comparar toda la carpeta, a cualquier profundidad, con la lista del sitio. En GitHub, conectar instala la GitHub App de JayV en la cuenta o la organización que elijas, y solo alcanza los repositorios que marques allí; para añadir otros, vuelve a hacer clic en GitHub."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.githubApp.title', $json$"通过 JayV 的 GitHub App 使用 GitHub"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.githubApp.detail', $json$"在应用和网站上使用 GitHub 登录，以及将 GitHub 连接到组织的仓库，现在都通过 JayV 的 GitHub App，而不再通过 OAuth App。连接时，GitHub 会询问 JayV 可以读取哪个账户或组织以及哪些仓库，除此之外无法访问任何内容。之前已连接的组织需要重新连接 GitHub。"$json$::jsonb),
  ('zh-CN', 'docs.orgRepositories.usage', $json$"在网站上打开组织，进入“仓库”，连接提供方并添加仓库。在应用中，组织页面会随变化实时列出它们：选择组织文件夹，克隆缺少的仓库，并用“查找克隆”在所有层级中将整个文件夹与网站上的列表进行对比。在 GitHub 上，连接会把 JayV 的 GitHub App 安装到你选择的账户或组织，它只能访问你在那里勾选的仓库；要添加更多，请再次点击 GitHub。"$json$::jsonb),
  ('hi', 'whatsNew.item.githubApp.title', $json$"JayV के GitHub App के ज़रिए GitHub"$json$::jsonb),
  ('hi', 'whatsNew.item.githubApp.detail', $json$"ऐप और साइट पर GitHub से साइन इन करना, और किसी संगठन की रिपॉज़िटरी से GitHub को कनेक्ट करना, अब OAuth App के बजाय JayV के GitHub App से होता है। कनेक्ट करते समय GitHub पूछता है कि JayV किस खाते या संगठन और किन रिपॉज़िटरी को पढ़ सकता है, और इसके अलावा कुछ भी पहुँच में नहीं रहता। पहले से कनेक्ट संगठन को GitHub फिर से कनेक्ट करना होगा।"$json$::jsonb),
  ('hi', 'docs.orgRepositories.usage', $json$"साइट पर संगठन खोलें, रिपॉज़िटरी में जाएँ, कोई प्रदाता कनेक्ट करें और रिपॉज़िटरी जोड़ें। ऐप में संगठन का पेज बदलाव होते ही इन्हें दिखाता है: संगठन का फ़ोल्डर चुनें, जो नहीं है उसे क्लोन करें और क्लोन खोजें से पूरे फ़ोल्डर की, हर गहराई तक, साइट की सूची से तुलना करें। GitHub पर कनेक्ट करने से JayV का GitHub App आपके चुने हुए खाते या संगठन में इंस्टॉल होता है, और वह सिर्फ़ उन्हीं रिपॉज़िटरी तक पहुँचता है जो आप वहाँ चुनते हैं; और जोड़ने के लिए GitHub पर फिर क्लिक करें।"$json$::jsonb),
  ('ar', 'whatsNew.item.githubApp.title', $json$"GitHub عبر تطبيق GitHub الخاص بـ JayV"$json$::jsonb),
  ('ar', 'whatsNew.item.githubApp.detail', $json$"أصبح تسجيل الدخول باستخدام GitHub، في التطبيق وفي الموقع، وربط GitHub بمستودعات المؤسسة يمرّان عبر تطبيق GitHub الخاص بـ JayV بدلًا من تطبيق OAuth. عند الربط، يسأل GitHub عن الحساب أو المؤسسة والمستودعات التي يمكن لـ JayV قراءتها، ولا يكون أي شيء آخر في متناوله. على المؤسسة التي رُبطت من قبل أن تربط GitHub من جديد."$json$::jsonb),
  ('ar', 'docs.orgRepositories.usage', $json$"في الموقع، افتح المؤسسة واذهب إلى المستودعات واربط مزوّدًا وأضف المستودعات. في التطبيق، تعرضها صفحة المؤسسة كلما تغيّرت: اختر مجلد المؤسسة، واستنسخ ما ينقص، واستخدم البحث عن النسخ لمقارنة المجلد كله، على كل المستويات، بقائمة الموقع. في GitHub، يؤدي الربط إلى تثبيت تطبيق GitHub الخاص بـ JayV في الحساب أو المؤسسة التي تختارها، ولا يصل إلا إلى المستودعات التي تحددها هناك؛ لإضافة المزيد، انقر على GitHub مرة أخرى."$json$::jsonb),
  ('fr', 'whatsNew.item.githubApp.title', $json$"GitHub via la GitHub App de JayV"$json$::jsonb),
  ('fr', 'whatsNew.item.githubApp.detail', $json$"La connexion avec GitHub, dans l'application et sur le site, et le raccordement de GitHub aux dépôts d'une organisation passent désormais par la GitHub App de JayV au lieu d'une OAuth App. Lors du raccordement, GitHub demande quel compte ou quelle organisation et quels dépôts JayV peut lire, et rien d'autre n'est accessible. Une organisation raccordée auparavant doit reconnecter GitHub."$json$::jsonb),
  ('fr', 'docs.orgRepositories.usage', $json$"Sur le site, ouvrez l'organisation, allez dans Dépôts, connectez un fournisseur et ajoutez les dépôts. Dans l'application, la page de l'organisation les liste au fil des changements : choisissez le dossier de l'organisation, clonez ce qui manque et utilisez Chercher des clones pour comparer tout le dossier, à toute profondeur, à la liste du site. Sur GitHub, la connexion installe la GitHub App de JayV sur le compte ou l'organisation de votre choix, et elle n'atteint que les dépôts que vous y cochez ; pour en ajouter d'autres, cliquez à nouveau sur GitHub."$json$::jsonb),
  ('ru', 'whatsNew.item.githubApp.title', $json$"GitHub через GitHub App JayV"$json$::jsonb),
  ('ru', 'whatsNew.item.githubApp.detail', $json$"Вход через GitHub в приложении и на сайте, а также подключение GitHub к репозиториям организации теперь идут через GitHub App JayV, а не через OAuth App. При подключении GitHub спрашивает, какой аккаунт или организацию и какие репозитории JayV может читать, и больше ничего не доступно. Организации, подключённой раньше, нужно подключить GitHub заново."$json$::jsonb),
  ('ru', 'docs.orgRepositories.usage', $json$"На сайте откройте организацию, перейдите в «Репозитории», подключите провайдера и добавьте репозитории. В приложении страница организации показывает их по мере изменений: выберите папку организации, клонируйте недостающие и с помощью «Найти клоны» сравните всю папку, на любой глубине, со списком с сайта. В GitHub подключение устанавливает GitHub App JayV в выбранный вами аккаунт или организацию, и оно получает доступ только к отмеченным там репозиториям; чтобы добавить другие, нажмите GitHub ещё раз."$json$::jsonb),
  ('ja', 'whatsNew.item.githubApp.title', $json$"JayV の GitHub App 経由の GitHub"$json$::jsonb),
  ('ja', 'whatsNew.item.githubApp.detail', $json$"アプリとサイトでの GitHub によるサインイン、および組織のリポジトリへの GitHub の接続は、OAuth App ではなく JayV の GitHub App を経由するようになりました。接続時に、JayV が読み取れるアカウントまたは組織とリポジトリを GitHub が確認し、それ以外にはアクセスできません。以前に接続した組織は、GitHub を接続し直す必要があります。"$json$::jsonb),
  ('ja', 'docs.orgRepositories.usage', $json$"サイトで組織を開き、「リポジトリ」でプロバイダーを接続してリポジトリを追加します。アプリの組織ページには変更がすぐに反映されます。組織フォルダーを選び、足りないものをクローンし、「クローンを探す」でフォルダー全体をすべての階層でサイトの一覧と比較します。GitHub では、接続すると JayV の GitHub App が選んだアカウントまたは組織にインストールされ、そこで選んだリポジトリにだけアクセスします。追加するには、もう一度 GitHub をクリックしてください。"$json$::jsonb),
  ('de', 'whatsNew.item.githubApp.title', $json$"GitHub über die GitHub App von JayV"$json$::jsonb),
  ('de', 'whatsNew.item.githubApp.detail', $json$"Die Anmeldung mit GitHub in der App und auf der Website sowie das Verbinden von GitHub mit den Repositorys einer Organisation laufen jetzt über die GitHub App von JayV statt über eine OAuth App. Beim Verbinden fragt GitHub, welches Konto oder welche Organisation und welche Repositorys JayV lesen darf, und nichts anderes ist erreichbar. Eine zuvor verbundene Organisation muss GitHub erneut verbinden."$json$::jsonb),
  ('de', 'docs.orgRepositories.usage', $json$"Öffne auf der Website die Organisation, gehe zu Repositories, verbinde einen Anbieter und füge die Repositorys hinzu. In der App listet die Organisationsseite sie auf, sobald sie sich ändern: Wähle den Organisationsordner, klone, was fehlt, und vergleiche mit Klone suchen den ganzen Ordner in jeder Tiefe mit der Liste der Website. Bei GitHub installiert das Verbinden die GitHub App von JayV im gewählten Konto oder in der gewählten Organisation, und sie erreicht nur die Repositorys, die du dort auswählst; um weitere hinzuzufügen, klicke erneut auf GitHub."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
