-- v0.34.0: economia de tokens com os agentes.
--
-- O pedido seguinte do mesmo chat retoma a sessão do agente; os agentes que
-- exploram o repositório recebem o mapa dos arquivos, não os arquivos; a
-- portaria e o roteamento do Jev rodam juntos; cache de prompt na API da
-- Anthropic; o comando `jayv bench`. O painel de desempenho do Jev deixa de
-- somar o "contexto enxugado" à economia e passa a contar as sessões
-- retomadas (`usage.jev.work.sessionResumed`); a dica da economia
-- (`usage.jev.saved.hint`) muda de texto, com os mesmos parâmetros. E os
-- itens da janela "Novidades" desta versão (`whatsNew.item.<id>.*`).
--
-- Só traduções: nenhuma tabela, coluna ou regra muda.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'usage.jev.work.sessionResumed', $json$"Sessões do agente retomadas"$json$::jsonb),
  ('pt-BR', 'usage.jev.saved.hint', $json$"Estimativa, nunca somada aos números reais: um pedido barrado conta o próprio tamanho mais uma resposta média. Para medir a economia no seu projeto, rode jayv bench."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentSessionResume.title', $json$"Agentes continuam de onde pararam"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentSessionResume.detail', $json$"No mesmo chat, o pedido seguinte retoma a sessão do Claude Code do anterior em vez de abrir outra. O agente não relê o projeto e a conversa inteira a cada mensagem, que era o maior gasto de tokens de um chat longo. Uma sessão nova começa depois de 10 pedidos, ou quando o agente, o modelo ou a pasta mudam."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentFileMap.title', $json$"Um mapa de arquivos em vez de arquivos inteiros"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentFileMap.detail', $json$"Os agentes que leem o projeto por conta própria agora recebem a lista dos arquivos mais relevantes com as definições encontradas neles, e abrem só o que precisam. Antes, o JayV colava esses arquivos inteiros no pedido e o agente os lia de novo mesmo assim. Modelos usados por API, que não enxergam o disco, continuam recebendo os arquivos."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.parallelJev.title', $json$"Início mais rápido de cada pedido"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.parallelJev.detail', $json$"A portaria de entrada e a leitura de roteamento do Jev agora rodam ao mesmo tempo, e o pedido não espera uma chamada de rede depois da outra antes de ir ao modelo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.promptCache.title', $json$"Cache de prompt para modelos da Anthropic"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.promptCache.detail', $json$"Quando você usa um modelo da Anthropic pela API, as instruções e o começo da conversa vão marcados para o cache de prompt e, na mensagem seguinte, são cobrados pela tarifa do cache. Os tokens do cache agora também entram no uso dos modelos usados por API."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.benchCommand.title', $json$"Meça a economia você mesmo"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.benchCommand.detail', $json$"O novo comando jayv bench roda uma lista de pedidos pelo JayV e direto no mesmo agente, e mostra os tokens cobrados de cada lado, com o cache incluído. É o jeito honesto de ver quanto o JayV economiza no seu próprio projeto."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.honestSavings.title', $json$"O painel de economia mostra só economia real"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.honestSavings.detail', $json$"A linha \"Contexto enxugado\" saiu de O que ele poupou: ela contava texto que o próprio JayV tinha escolhido e depois cortado, não tokens que o modelo gastaria. As sessões do agente retomadas agora entram em O que ele fez."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.titleWithoutAgent.title', $json$"O título do chat não abre mais uma sessão de agente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.titleWithoutAgent.detail', $json$"Dar nome ao chat abria uma sessão inteira de agente só para conseguir seis palavras. Agora só um modelo usado por API dá o nome; com apenas agentes de linha de comando, o chat fica com o resumo do seu primeiro pedido."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.betterRetrieval.title', $json$"Escolha melhor dos arquivos relevantes"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.betterRetrieval.detail', $json$"A busca de arquivos agora dá mais peso às palavras raras do que às que todo arquivo tem, separa identificadores como fetchUserName em palavras, ignora palavras de ligação, coloca a documentação abaixo do código e, de um arquivo grande, manda o trecho que casa com o pedido em vez do começo dele."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.shortHistory.title', $json$"Histórico mais curto em cada pedido"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.shortHistory.detail', $json$"Quando o pedido não consegue retomar a sessão do agente, as respostas anteriores do modelo voltam no histórico encurtadas às primeiras linhas, porque o pedido novo precisa do assunto, não de todo o código já entregue."$json$::jsonb),
  ('en', 'usage.jev.work.sessionResumed', $json$"Agent sessions resumed"$json$::jsonb),
  ('en', 'usage.jev.saved.hint', $json$"An estimate, never added to the real numbers: a blocked request is its own size plus an average answer. To measure the savings on your project, run jayv bench."$json$::jsonb),
  ('en', 'whatsNew.item.agentSessionResume.title', $json$"Agents pick up where they left off"$json$::jsonb),
  ('en', 'whatsNew.item.agentSessionResume.detail', $json$"In the same chat, the next request resumes the Claude Code session of the previous one instead of opening a new one. The agent no longer rereads the project and the whole conversation on every message, which was the largest token cost of a long chat. A new session starts after 10 requests, or when the agent, model or folder changes."$json$::jsonb),
  ('en', 'whatsNew.item.agentFileMap.title', $json$"A file map instead of whole files"$json$::jsonb),
  ('en', 'whatsNew.item.agentFileMap.detail', $json$"Agents that read the project on their own now get the list of the most relevant files with the definitions found in them, and open only what they need. Before, JayV pasted those files whole into the request and the agent read them again anyway. Models used through an API, which cannot see the disk, still get the files."$json$::jsonb),
  ('en', 'whatsNew.item.parallelJev.title', $json$"Faster start for every request"$json$::jsonb),
  ('en', 'whatsNew.item.parallelJev.detail', $json$"The entry gate and the routing read from Jev now run at the same time, so a request no longer waits for one network call after the other before going to the model."$json$::jsonb),
  ('en', 'whatsNew.item.promptCache.title', $json$"Prompt cache for Anthropic models"$json$::jsonb),
  ('en', 'whatsNew.item.promptCache.detail', $json$"When you use an Anthropic model through the API, the instructions and the earlier part of the conversation are marked for the prompt cache, so they are billed at the cached rate on the next message. Cached tokens are now counted in usage for models used through an API too."$json$::jsonb),
  ('en', 'whatsNew.item.benchCommand.title', $json$"Measure the savings yourself"$json$::jsonb),
  ('en', 'whatsNew.item.benchCommand.detail', $json$"The new jayv bench command runs a list of requests through JayV and straight to the same agent, and prints the tokens each side was charged, cache included. It is the honest way to see what JayV saves on your own project."$json$::jsonb),
  ('en', 'whatsNew.item.honestSavings.title', $json$"Savings panel shows only real savings"$json$::jsonb),
  ('en', 'whatsNew.item.honestSavings.detail', $json$"The \"Trimmed context\" line was removed from What it saved: it counted text JayV itself had picked and then cut, not tokens the model would have spent. Agent sessions resumed are now counted in What it did."$json$::jsonb),
  ('en', 'whatsNew.item.titleWithoutAgent.title', $json$"Chat titles no longer open an agent session"$json$::jsonb),
  ('en', 'whatsNew.item.titleWithoutAgent.detail', $json$"Naming a chat used to start a full agent session just to get six words. Now only a model used through an API names the chat; with command line agents only, the chat keeps the summary of your first request."$json$::jsonb),
  ('en', 'whatsNew.item.betterRetrieval.title', $json$"Better choice of relevant files"$json$::jsonb),
  ('en', 'whatsNew.item.betterRetrieval.detail', $json$"The file search now weighs rare words over the ones every file has, splits identifiers like fetchUserName into words, ignores filler words, ranks documentation below code and, from a large file, sends the part that matches the request instead of its beginning."$json$::jsonb),
  ('en', 'whatsNew.item.shortHistory.title', $json$"Shorter history in each request"$json$::jsonb),
  ('en', 'whatsNew.item.shortHistory.detail', $json$"When a request cannot resume the agent session, earlier answers from the model come back in the history shortened to their first lines, since the new request needs the subject, not all the code already delivered."$json$::jsonb),
  ('es', 'usage.jev.work.sessionResumed', $json$"Sesiones del agente retomadas"$json$::jsonb),
  ('es', 'usage.jev.saved.hint', $json$"Una estimación, nunca sumada a los números reales: una solicitud bloqueada cuenta su propio tamaño más una respuesta media. Para medir el ahorro en tu proyecto, ejecuta jayv bench."$json$::jsonb),
  ('es', 'whatsNew.item.agentSessionResume.title', $json$"Los agentes siguen donde lo dejaron"$json$::jsonb),
  ('es', 'whatsNew.item.agentSessionResume.detail', $json$"En el mismo chat, la siguiente solicitud retoma la sesión de Claude Code de la anterior en lugar de abrir otra. El agente ya no vuelve a leer el proyecto y toda la conversación en cada mensaje, que era el mayor gasto de tokens de un chat largo. Una sesión nueva empieza después de 10 solicitudes, o cuando cambian el agente, el modelo o la carpeta."$json$::jsonb),
  ('es', 'whatsNew.item.agentFileMap.title', $json$"Un mapa de archivos en lugar de archivos completos"$json$::jsonb),
  ('es', 'whatsNew.item.agentFileMap.detail', $json$"Los agentes que leen el proyecto por su cuenta ahora reciben la lista de los archivos más relevantes con las definiciones encontradas en ellos, y abren solo lo que necesitan. Antes, JayV pegaba esos archivos completos en la solicitud y el agente los volvía a leer de todos modos. Los modelos usados por API, que no ven el disco, siguen recibiendo los archivos."$json$::jsonb),
  ('es', 'whatsNew.item.parallelJev.title', $json$"Inicio más rápido de cada solicitud"$json$::jsonb),
  ('es', 'whatsNew.item.parallelJev.detail', $json$"La puerta de entrada y la lectura de enrutamiento de Jev ahora se ejecutan al mismo tiempo, así que la solicitud ya no espera una llamada de red tras otra antes de ir al modelo."$json$::jsonb),
  ('es', 'whatsNew.item.promptCache.title', $json$"Caché de prompt para modelos de Anthropic"$json$::jsonb),
  ('es', 'whatsNew.item.promptCache.detail', $json$"Cuando usas un modelo de Anthropic por la API, las instrucciones y la parte anterior de la conversación se marcan para la caché de prompt, y en el siguiente mensaje se cobran a la tarifa de caché. Los tokens en caché ahora también se cuentan en el uso de los modelos usados por API."$json$::jsonb),
  ('es', 'whatsNew.item.benchCommand.title', $json$"Mide el ahorro tú mismo"$json$::jsonb),
  ('es', 'whatsNew.item.benchCommand.detail', $json$"El nuevo comando jayv bench ejecuta una lista de solicitudes a través de JayV y directamente en el mismo agente, y muestra los tokens cobrados a cada lado, caché incluida. Es la forma honesta de ver cuánto ahorra JayV en tu propio proyecto."$json$::jsonb),
  ('es', 'whatsNew.item.honestSavings.title', $json$"El panel de ahorro muestra solo ahorro real"$json$::jsonb),
  ('es', 'whatsNew.item.honestSavings.detail', $json$"La línea \"Contexto recortado\" salió de Lo que ahorró: contaba texto que el propio JayV había elegido y después recortado, no tokens que el modelo habría gastado. Las sesiones del agente retomadas ahora se cuentan en Lo que hizo."$json$::jsonb),
  ('es', 'whatsNew.item.titleWithoutAgent.title', $json$"El título del chat ya no abre una sesión de agente"$json$::jsonb),
  ('es', 'whatsNew.item.titleWithoutAgent.detail', $json$"Poner nombre al chat abría una sesión completa de agente solo para obtener seis palabras. Ahora solo un modelo usado por API pone el nombre; con solo agentes de línea de comandos, el chat conserva el resumen de tu primera solicitud."$json$::jsonb),
  ('es', 'whatsNew.item.betterRetrieval.title', $json$"Mejor elección de los archivos relevantes"$json$::jsonb),
  ('es', 'whatsNew.item.betterRetrieval.detail', $json$"La búsqueda de archivos ahora da más peso a las palabras raras que a las que tiene cualquier archivo, separa identificadores como fetchUserName en palabras, ignora palabras de relleno, coloca la documentación por debajo del código y, de un archivo grande, envía la parte que coincide con la solicitud en lugar de su comienzo."$json$::jsonb),
  ('es', 'whatsNew.item.shortHistory.title', $json$"Historial más corto en cada solicitud"$json$::jsonb),
  ('es', 'whatsNew.item.shortHistory.detail', $json$"Cuando la solicitud no puede retomar la sesión del agente, las respuestas anteriores del modelo vuelven al historial acortadas a sus primeras líneas, porque la nueva solicitud necesita el tema, no todo el código ya entregado."$json$::jsonb),
  ('zh-CN', 'usage.jev.work.sessionResumed', $json$"恢复的智能体会话"$json$::jsonb),
  ('zh-CN', 'usage.jev.saved.hint', $json$"估算值，从不计入真实数字：被拦截的请求按其自身大小加一次平均回答计算。要在你的项目中衡量节省量，请运行 jayv bench。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentSessionResume.title', $json$"智能体从上次中断处继续"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentSessionResume.detail', $json$"在同一个聊天中，下一个请求会恢复上一个请求的 Claude Code 会话，而不是新开一个。智能体不再在每条消息时重新读取项目和整段对话，而这正是长聊天中最大的 token 开销。10 个请求之后，或者智能体、模型或文件夹发生变化时，会开始新的会话。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentFileMap.title', $json$"用文件地图代替完整文件"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentFileMap.detail', $json$"会自行读取项目的智能体，现在收到的是最相关文件的列表以及其中找到的定义，只打开需要的部分。以前 JayV 会把这些文件整段贴进请求，而智能体无论如何还会再读一遍。通过 API 使用的模型看不到磁盘，仍然会收到文件内容。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.parallelJev.title', $json$"每个请求启动更快"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.parallelJev.detail', $json$"入口关卡和 Jev 的路由判断现在同时进行，请求在发送给模型之前不再需要依次等待两次网络调用。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.promptCache.title', $json$"Anthropic 模型的提示缓存"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.promptCache.detail', $json$"通过 API 使用 Anthropic 模型时，指令和对话前面的部分会被标记进入提示缓存，下一条消息时按缓存费率计费。通过 API 使用的模型的缓存 token 现在也会计入用量。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.benchCommand.title', $json$"亲自衡量节省量"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.benchCommand.detail', $json$"新的 jayv bench 命令会把一组请求分别通过 JayV 和直接发送给同一个智能体，并输出两边实际计费的 token（含缓存）。这是在你自己的项目中如实查看 JayV 节省了多少的方法。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.honestSavings.title', $json$"节省面板只显示真实的节省"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.honestSavings.detail', $json$"“精简的上下文”一行已从“它节省了什么”中移除：它统计的是 JayV 自己选出又删掉的文本，而不是模型本会消耗的 token。恢复的智能体会话现在计入“它做了什么”。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.titleWithoutAgent.title', $json$"聊天标题不再开启智能体会话"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.titleWithoutAgent.detail', $json$"以前给聊天命名会为了六个词启动一整个智能体会话。现在只有通过 API 使用的模型才会命名聊天；如果只有命令行智能体，聊天会保留你第一个请求的摘要。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.betterRetrieval.title', $json$"更准确地挑选相关文件"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.betterRetrieval.detail', $json$"文件搜索现在更看重少见的词而不是每个文件都有的词，会把 fetchUserName 这样的标识符拆成单词，忽略虚词，把文档排在代码之后；对于大文件，发送与请求匹配的那一段，而不是文件开头。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.shortHistory.title', $json$"每个请求的历史更短"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.shortHistory.detail', $json$"当请求无法恢复智能体会话时，模型之前的回答会以缩短到开头几行的形式出现在历史中，因为新请求需要的是主题，而不是已经交付的全部代码。"$json$::jsonb),
  ('hi', 'usage.jev.work.sessionResumed', $json$"फिर से शुरू किए गए एजेंट सत्र"$json$::jsonb),
  ('hi', 'usage.jev.saved.hint', $json$"यह अनुमान है, असली आँकड़ों में कभी नहीं जोड़ा जाता: रोका गया अनुरोध अपना आकार और एक औसत उत्तर गिना जाता है। अपने प्रोजेक्ट में बचत मापने के लिए jayv bench चलाएँ।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentSessionResume.title', $json$"एजेंट वहीं से आगे बढ़ते हैं जहाँ रुके थे"$json$::jsonb),
  ('hi', 'whatsNew.item.agentSessionResume.detail', $json$"उसी चैट में, अगला अनुरोध नया सत्र खोलने के बजाय पिछले अनुरोध का Claude Code सत्र फिर से शुरू करता है। एजेंट अब हर संदेश पर प्रोजेक्ट और पूरी बातचीत दोबारा नहीं पढ़ता, जो लंबी चैट में टोकन का सबसे बड़ा खर्च था। 10 अनुरोधों के बाद, या जब एजेंट, मॉडल या फ़ोल्डर बदलता है, तो नया सत्र शुरू होता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentFileMap.title', $json$"पूरी फ़ाइलों की जगह फ़ाइलों का नक्शा"$json$::jsonb),
  ('hi', 'whatsNew.item.agentFileMap.detail', $json$"जो एजेंट प्रोजेक्ट खुद पढ़ते हैं, उन्हें अब सबसे प्रासंगिक फ़ाइलों की सूची उनमें मिली परिभाषाओं के साथ मिलती है, और वे सिर्फ़ ज़रूरी फ़ाइलें खोलते हैं। पहले JayV ये फ़ाइलें पूरी की पूरी अनुरोध में चिपका देता था और एजेंट फिर भी उन्हें दोबारा पढ़ता था। API से इस्तेमाल होने वाले मॉडल, जो डिस्क नहीं देख सकते, अब भी फ़ाइलें पाते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.parallelJev.title', $json$"हर अनुरोध की तेज़ शुरुआत"$json$::jsonb),
  ('hi', 'whatsNew.item.parallelJev.detail', $json$"प्रवेश द्वार और Jev की रूटिंग जाँच अब एक साथ चलती हैं, इसलिए अनुरोध मॉडल तक जाने से पहले एक के बाद एक नेटवर्क कॉल का इंतज़ार नहीं करता।"$json$::jsonb),
  ('hi', 'whatsNew.item.promptCache.title', $json$"Anthropic मॉडलों के लिए प्रॉम्प्ट कैश"$json$::jsonb),
  ('hi', 'whatsNew.item.promptCache.detail', $json$"जब आप API से Anthropic मॉडल इस्तेमाल करते हैं, तो निर्देश और बातचीत का पिछला हिस्सा प्रॉम्प्ट कैश के लिए चिह्नित होते हैं, और अगले संदेश पर उनका शुल्क कैश दर से लगता है। API से इस्तेमाल होने वाले मॉडलों के कैश टोकन भी अब उपयोग में गिने जाते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.benchCommand.title', $json$"बचत खुद मापें"$json$::jsonb),
  ('hi', 'whatsNew.item.benchCommand.detail', $json$"नया jayv bench कमांड अनुरोधों की एक सूची JayV के ज़रिए और सीधे उसी एजेंट पर चलाता है, और दोनों तरफ़ लगे टोकन, कैश सहित, दिखाता है। अपने प्रोजेक्ट में JayV कितना बचाता है, यह देखने का यही ईमानदार तरीका है।"$json$::jsonb),
  ('hi', 'whatsNew.item.honestSavings.title', $json$"बचत पैनल अब सिर्फ़ असली बचत दिखाता है"$json$::jsonb),
  ('hi', 'whatsNew.item.honestSavings.detail', $json$"\"छोटा किया गया संदर्भ\" पंक्ति \"उसने क्या बचाया\" से हटा दी गई: यह वह टेक्स्ट गिनती थी जिसे JayV ने खुद चुना और फिर काटा, न कि वे टोकन जो मॉडल खर्च करता। फिर से शुरू किए गए एजेंट सत्र अब \"उसने क्या किया\" में गिने जाते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.titleWithoutAgent.title', $json$"चैट का शीर्षक अब एजेंट सत्र नहीं खोलता"$json$::jsonb),
  ('hi', 'whatsNew.item.titleWithoutAgent.detail', $json$"चैट का नाम रखने के लिए पहले सिर्फ़ छह शब्दों के लिए पूरा एजेंट सत्र शुरू होता था। अब सिर्फ़ API से इस्तेमाल होने वाला मॉडल चैट का नाम रखता है; केवल कमांड लाइन एजेंट होने पर चैट आपके पहले अनुरोध का सारांश रखती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.betterRetrieval.title', $json$"प्रासंगिक फ़ाइलों का बेहतर चुनाव"$json$::jsonb),
  ('hi', 'whatsNew.item.betterRetrieval.detail', $json$"फ़ाइल खोज अब हर फ़ाइल में मिलने वाले शब्दों के बजाय दुर्लभ शब्दों को ज़्यादा महत्व देती है, fetchUserName जैसे पहचानकर्ताओं को शब्दों में बाँटती है, भराव वाले शब्दों को अनदेखा करती है, दस्तावेज़ को कोड से नीचे रखती है और बड़ी फ़ाइल से उसकी शुरुआत के बजाय अनुरोध से मेल खाने वाला हिस्सा भेजती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.shortHistory.title', $json$"हर अनुरोध में छोटा इतिहास"$json$::jsonb),
  ('hi', 'whatsNew.item.shortHistory.detail', $json$"जब अनुरोध एजेंट सत्र फिर से शुरू नहीं कर पाता, तो मॉडल के पिछले उत्तर इतिहास में अपनी शुरुआती पंक्तियों तक छोटे होकर आते हैं, क्योंकि नए अनुरोध को विषय चाहिए, पहले से दिया गया पूरा कोड नहीं।"$json$::jsonb),
  ('ar', 'usage.jev.work.sessionResumed', $json$"جلسات الوكيل المستأنفة"$json$::jsonb),
  ('ar', 'usage.jev.saved.hint', $json$"تقدير لا يُضاف أبدًا إلى الأرقام الفعلية: الطلب المحظور يُحسب بحجمه مع إجابة متوسطة. لقياس التوفير في مشروعك، شغّل jayv bench."$json$::jsonb),
  ('ar', 'whatsNew.item.agentSessionResume.title', $json$"الوكلاء يكملون من حيث توقفوا"$json$::jsonb),
  ('ar', 'whatsNew.item.agentSessionResume.detail', $json$"في المحادثة نفسها، يستأنف الطلب التالي جلسة Claude Code الخاصة بالطلب السابق بدلًا من فتح جلسة جديدة. لم يعد الوكيل يعيد قراءة المشروع والمحادثة كاملة مع كل رسالة، وكان ذلك أكبر استهلاك للرموز في المحادثات الطويلة. تبدأ جلسة جديدة بعد 10 طلبات، أو عند تغيّر الوكيل أو النموذج أو المجلد."$json$::jsonb),
  ('ar', 'whatsNew.item.agentFileMap.title', $json$"خريطة ملفات بدلًا من الملفات كاملة"$json$::jsonb),
  ('ar', 'whatsNew.item.agentFileMap.detail', $json$"الوكلاء الذين يقرؤون المشروع بأنفسهم يتلقون الآن قائمة بأهم الملفات مع التعريفات الموجودة فيها، ويفتحون فقط ما يحتاجونه. في السابق كان JayV يلصق هذه الملفات كاملة في الطلب، ثم يقرؤها الوكيل مرة أخرى على أي حال. أما النماذج المستخدمة عبر API، التي لا ترى القرص، فما زالت تتلقى الملفات."$json$::jsonb),
  ('ar', 'whatsNew.item.parallelJev.title', $json$"بدء أسرع لكل طلب"$json$::jsonb),
  ('ar', 'whatsNew.item.parallelJev.detail', $json$"بوابة الدخول وقراءة التوجيه من Jev تعملان الآن في الوقت نفسه، فلم يعد الطلب ينتظر اتصالًا شبكيًا تلو الآخر قبل أن يصل إلى النموذج."$json$::jsonb),
  ('ar', 'whatsNew.item.promptCache.title', $json$"ذاكرة تخزين مؤقت للمطالبات لنماذج Anthropic"$json$::jsonb),
  ('ar', 'whatsNew.item.promptCache.detail', $json$"عند استخدام نموذج من Anthropic عبر API، تُعلَّم التعليمات والجزء السابق من المحادثة لذاكرة التخزين المؤقت للمطالبات، فتُحتسب في الرسالة التالية بسعر التخزين المؤقت. وأصبحت الرموز المخزنة مؤقتًا تُحتسب الآن في الاستخدام للنماذج المستخدمة عبر API أيضًا."$json$::jsonb),
  ('ar', 'whatsNew.item.benchCommand.title', $json$"قِس التوفير بنفسك"$json$::jsonb),
  ('ar', 'whatsNew.item.benchCommand.detail', $json$"يشغّل الأمر الجديد jayv bench قائمة طلبات عبر JayV ومباشرة على الوكيل نفسه، ويعرض الرموز المحتسبة على كل جانب بما فيها التخزين المؤقت. إنها الطريقة الصادقة لمعرفة ما يوفّره JayV في مشروعك."$json$::jsonb),
  ('ar', 'whatsNew.item.honestSavings.title', $json$"لوحة التوفير تعرض التوفير الحقيقي فقط"$json$::jsonb),
  ('ar', 'whatsNew.item.honestSavings.detail', $json$"أُزيل سطر \"سياق مختصر\" من \"ما وفّره\": كان يحسب نصًا اختاره JayV بنفسه ثم قصّه، لا رموزًا كان النموذج سيستهلكها. وتُحتسب جلسات الوكيل المستأنفة الآن في \"ما فعله\"."$json$::jsonb),
  ('ar', 'whatsNew.item.titleWithoutAgent.title', $json$"عناوين المحادثات لم تعد تفتح جلسة وكيل"$json$::jsonb),
  ('ar', 'whatsNew.item.titleWithoutAgent.detail', $json$"كانت تسمية المحادثة تبدأ جلسة وكيل كاملة للحصول على ست كلمات فقط. الآن لا يسمّي المحادثة إلا نموذج مستخدم عبر API؛ ومع وكلاء سطر الأوامر فقط، تحتفظ المحادثة بملخص طلبك الأول."$json$::jsonb),
  ('ar', 'whatsNew.item.betterRetrieval.title', $json$"اختيار أفضل للملفات ذات الصلة"$json$::jsonb),
  ('ar', 'whatsNew.item.betterRetrieval.detail', $json$"يعطي البحث عن الملفات الآن وزنًا أكبر للكلمات النادرة من الكلمات الموجودة في كل ملف، ويقسّم المعرّفات مثل fetchUserName إلى كلمات، ويتجاهل كلمات الحشو، ويضع التوثيق بعد الشيفرة، ومن الملف الكبير يرسل الجزء المطابق للطلب بدلًا من بدايته."$json$::jsonb),
  ('ar', 'whatsNew.item.shortHistory.title', $json$"سجل أقصر في كل طلب"$json$::jsonb),
  ('ar', 'whatsNew.item.shortHistory.detail', $json$"عندما يتعذّر على الطلب استئناف جلسة الوكيل، تعود إجابات النموذج السابقة في السجل مختصرة إلى أسطرها الأولى، لأن الطلب الجديد يحتاج إلى الموضوع لا إلى كل الشيفرة التي سُلّمت."$json$::jsonb),
  ('fr', 'usage.jev.work.sessionResumed', $json$"Sessions d’agent reprises"$json$::jsonb),
  ('fr', 'usage.jev.saved.hint', $json$"Une estimation, jamais ajoutée aux chiffres réels : une demande bloquée compte sa propre taille plus une réponse moyenne. Pour mesurer l’économie sur votre projet, lancez jayv bench."$json$::jsonb),
  ('fr', 'whatsNew.item.agentSessionResume.title', $json$"Les agents reprennent là où ils s’étaient arrêtés"$json$::jsonb),
  ('fr', 'whatsNew.item.agentSessionResume.detail', $json$"Dans le même chat, la demande suivante reprend la session Claude Code de la précédente au lieu d’en ouvrir une nouvelle. L’agent ne relit plus le projet et toute la conversation à chaque message, ce qui était la plus grosse dépense de tokens d’un long chat. Une nouvelle session démarre après 10 demandes, ou quand l’agent, le modèle ou le dossier change."$json$::jsonb),
  ('fr', 'whatsNew.item.agentFileMap.title', $json$"Une carte des fichiers au lieu des fichiers entiers"$json$::jsonb),
  ('fr', 'whatsNew.item.agentFileMap.detail', $json$"Les agents qui lisent le projet par eux-mêmes reçoivent désormais la liste des fichiers les plus pertinents avec les définitions qui s’y trouvent, et n’ouvrent que ce dont ils ont besoin. Avant, JayV collait ces fichiers entiers dans la demande et l’agent les relisait quand même. Les modèles utilisés via une API, qui ne voient pas le disque, reçoivent toujours les fichiers."$json$::jsonb),
  ('fr', 'whatsNew.item.parallelJev.title', $json$"Démarrage plus rapide de chaque demande"$json$::jsonb),
  ('fr', 'whatsNew.item.parallelJev.detail', $json$"Le contrôle d’entrée et la lecture de routage de Jev s’exécutent désormais en même temps : la demande n’attend plus un appel réseau après l’autre avant d’aller au modèle."$json$::jsonb),
  ('fr', 'whatsNew.item.promptCache.title', $json$"Cache de prompt pour les modèles Anthropic"$json$::jsonb),
  ('fr', 'whatsNew.item.promptCache.detail', $json$"Quand vous utilisez un modèle Anthropic via l’API, les instructions et le début de la conversation sont marqués pour le cache de prompt, et sont facturés au tarif du cache au message suivant. Les tokens en cache sont désormais comptés dans l’utilisation des modèles utilisés via une API aussi."$json$::jsonb),
  ('fr', 'whatsNew.item.benchCommand.title', $json$"Mesurez l’économie vous-même"$json$::jsonb),
  ('fr', 'whatsNew.item.benchCommand.detail', $json$"La nouvelle commande jayv bench exécute une liste de demandes via JayV et directement sur le même agent, et affiche les tokens facturés de chaque côté, cache compris. C’est la façon honnête de voir ce que JayV économise sur votre propre projet."$json$::jsonb),
  ('fr', 'whatsNew.item.honestSavings.title', $json$"Le panneau d’économies ne montre que les économies réelles"$json$::jsonb),
  ('fr', 'whatsNew.item.honestSavings.detail', $json$"La ligne « Contexte réduit » a été retirée de Ce qu’il a économisé : elle comptait du texte que JayV avait lui-même choisi puis coupé, pas des tokens que le modèle aurait dépensés. Les sessions d’agent reprises sont désormais comptées dans Ce qu’il a fait."$json$::jsonb),
  ('fr', 'whatsNew.item.titleWithoutAgent.title', $json$"Le titre du chat n’ouvre plus de session d’agent"$json$::jsonb),
  ('fr', 'whatsNew.item.titleWithoutAgent.detail', $json$"Nommer un chat démarrait une session d’agent complète juste pour obtenir six mots. Désormais, seul un modèle utilisé via une API nomme le chat ; avec uniquement des agents en ligne de commande, le chat garde le résumé de votre première demande."$json$::jsonb),
  ('fr', 'whatsNew.item.betterRetrieval.title', $json$"Meilleur choix des fichiers pertinents"$json$::jsonb),
  ('fr', 'whatsNew.item.betterRetrieval.detail', $json$"La recherche de fichiers donne désormais plus de poids aux mots rares qu’à ceux que tous les fichiers contiennent, découpe les identifiants comme fetchUserName en mots, ignore les mots de liaison, classe la documentation après le code et, pour un gros fichier, envoie la partie qui correspond à la demande plutôt que son début."$json$::jsonb),
  ('fr', 'whatsNew.item.shortHistory.title', $json$"Historique plus court dans chaque demande"$json$::jsonb),
  ('fr', 'whatsNew.item.shortHistory.detail', $json$"Quand une demande ne peut pas reprendre la session de l’agent, les réponses précédentes du modèle reviennent dans l’historique raccourcies à leurs premières lignes, car la nouvelle demande a besoin du sujet, pas de tout le code déjà livré."$json$::jsonb),
  ('ru', 'usage.jev.work.sessionResumed', $json$"Возобновлённые сессии агента"$json$::jsonb),
  ('ru', 'usage.jev.saved.hint', $json$"Оценка, которая никогда не прибавляется к реальным цифрам: заблокированный запрос считается как его собственный размер плюс средний ответ. Чтобы измерить экономию в своём проекте, запустите jayv bench."$json$::jsonb),
  ('ru', 'whatsNew.item.agentSessionResume.title', $json$"Агенты продолжают с того места, где остановились"$json$::jsonb),
  ('ru', 'whatsNew.item.agentSessionResume.detail', $json$"В том же чате следующий запрос возобновляет сессию Claude Code предыдущего, а не открывает новую. Агент больше не перечитывает проект и весь разговор при каждом сообщении, а это была самая большая статья расхода токенов в длинном чате. Новая сессия начинается после 10 запросов или при смене агента, модели или папки."$json$::jsonb),
  ('ru', 'whatsNew.item.agentFileMap.title', $json$"Карта файлов вместо целых файлов"$json$::jsonb),
  ('ru', 'whatsNew.item.agentFileMap.detail', $json$"Агенты, которые сами читают проект, теперь получают список самых подходящих файлов с найденными в них определениями и открывают только нужное. Раньше JayV вставлял эти файлы целиком в запрос, а агент всё равно читал их заново. Модели, используемые через API, которые не видят диск, по-прежнему получают файлы."$json$::jsonb),
  ('ru', 'whatsNew.item.parallelJev.title', $json$"Каждый запрос стартует быстрее"$json$::jsonb),
  ('ru', 'whatsNew.item.parallelJev.detail', $json$"Входной контроль и маршрутизация Jev теперь выполняются одновременно, и запрос больше не ждёт сетевые вызовы один за другим, прежде чем уйти к модели."$json$::jsonb),
  ('ru', 'whatsNew.item.promptCache.title', $json$"Кэш промптов для моделей Anthropic"$json$::jsonb),
  ('ru', 'whatsNew.item.promptCache.detail', $json$"Когда вы используете модель Anthropic через API, инструкции и начало разговора помечаются для кэша промптов и в следующем сообщении оплачиваются по тарифу кэша. Кэшированные токены теперь учитываются в расходе и для моделей, используемых через API."$json$::jsonb),
  ('ru', 'whatsNew.item.benchCommand.title', $json$"Измерьте экономию сами"$json$::jsonb),
  ('ru', 'whatsNew.item.benchCommand.detail', $json$"Новая команда jayv bench прогоняет список запросов через JayV и напрямую через того же агента и выводит токены, списанные с каждой стороны, включая кэш. Это честный способ увидеть, сколько JayV экономит в вашем собственном проекте."$json$::jsonb),
  ('ru', 'whatsNew.item.honestSavings.title', $json$"Панель экономии показывает только реальную экономию"$json$::jsonb),
  ('ru', 'whatsNew.item.honestSavings.detail', $json$"Строка «Сокращённый контекст» убрана из блока «Что он сэкономил»: она считала текст, который JayV сам выбрал и потом урезал, а не токены, которые потратила бы модель. Возобновлённые сессии агента теперь учитываются в блоке «Что он сделал»."$json$::jsonb),
  ('ru', 'whatsNew.item.titleWithoutAgent.title', $json$"Название чата больше не открывает сессию агента"$json$::jsonb),
  ('ru', 'whatsNew.item.titleWithoutAgent.detail', $json$"Чтобы назвать чат, раньше запускалась целая сессия агента ради шести слов. Теперь название даёт только модель, используемая через API; если есть только агенты командной строки, чат сохраняет краткое содержание вашего первого запроса."$json$::jsonb),
  ('ru', 'whatsNew.item.betterRetrieval.title', $json$"Более точный выбор нужных файлов"$json$::jsonb),
  ('ru', 'whatsNew.item.betterRetrieval.detail', $json$"Поиск файлов теперь придаёт больший вес редким словам, чем тем, что есть в каждом файле, разбивает идентификаторы вроде fetchUserName на слова, пропускает служебные слова, ставит документацию ниже кода и из большого файла отправляет фрагмент, совпадающий с запросом, а не его начало."$json$::jsonb),
  ('ru', 'whatsNew.item.shortHistory.title', $json$"Более короткая история в каждом запросе"$json$::jsonb),
  ('ru', 'whatsNew.item.shortHistory.detail', $json$"Когда запрос не может возобновить сессию агента, прежние ответы модели попадают в историю сокращёнными до первых строк: новому запросу нужна тема, а не весь уже выданный код."$json$::jsonb),
  ('ja', 'usage.jev.work.sessionResumed', $json$"再開したエージェントのセッション"$json$::jsonb),
  ('ja', 'usage.jev.saved.hint', $json$"推定値で、実際の数値には加算されません。ブロックされたリクエストは、その大きさと平均的な回答 1 回分で数えます。プロジェクトでの節約量を測るには jayv bench を実行してください。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentSessionResume.title', $json$"エージェントが前回の続きから再開"$json$::jsonb),
  ('ja', 'whatsNew.item.agentSessionResume.detail', $json$"同じチャットでは、次のリクエストが新しいセッションを開かずに、前回の Claude Code セッションを再開します。エージェントはメッセージのたびにプロジェクトと会話全体を読み直さなくなりました。これは長いチャットで最も大きなトークン消費でした。10 件のリクエストの後、またはエージェント、モデル、フォルダーが変わったときに新しいセッションが始まります。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentFileMap.title', $json$"ファイル全体の代わりにファイルマップ"$json$::jsonb),
  ('ja', 'whatsNew.item.agentFileMap.detail', $json$"プロジェクトを自分で読むエージェントには、関連性の高いファイルの一覧とそこで見つかった定義が渡され、必要なものだけを開くようになりました。以前は JayV がそれらのファイルを丸ごとリクエストに貼り付け、エージェントはそれでも読み直していました。ディスクを見られない API 経由のモデルには、引き続きファイルが渡されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.parallelJev.title', $json$"すべてのリクエストの開始が高速に"$json$::jsonb),
  ('ja', 'whatsNew.item.parallelJev.detail', $json$"入口ゲートと Jev のルーティング判定が同時に実行されるようになり、リクエストがモデルに届く前にネットワーク呼び出しを順番に待つことがなくなりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.promptCache.title', $json$"Anthropic モデルのプロンプトキャッシュ"$json$::jsonb),
  ('ja', 'whatsNew.item.promptCache.detail', $json$"API 経由で Anthropic のモデルを使うと、指示と会話の前半がプロンプトキャッシュの対象として指定され、次のメッセージではキャッシュ料金で課金されます。API 経由のモデルでも、キャッシュされたトークンが使用量に計上されるようになりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.benchCommand.title', $json$"節約量を自分で測る"$json$::jsonb),
  ('ja', 'whatsNew.item.benchCommand.detail', $json$"新しい jayv bench コマンドは、リクエストの一覧を JayV 経由と同じエージェントへの直接の両方で実行し、それぞれで課金されたトークン（キャッシュを含む）を表示します。自分のプロジェクトで JayV がどれだけ節約するかを正直に確かめる方法です。"$json$::jsonb),
  ('ja', 'whatsNew.item.honestSavings.title', $json$"節約パネルは実際の節約だけを表示"$json$::jsonb),
  ('ja', 'whatsNew.item.honestSavings.detail', $json$"「節約した量」から「削ったコンテキスト」の行を削除しました。これは JayV 自身が選んでから削ったテキストを数えていただけで、モデルが消費するはずだったトークンではありませんでした。再開したエージェントのセッションは「行ったこと」に数えられるようになりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.titleWithoutAgent.title', $json$"チャットのタイトル付けでエージェントのセッションを開かなくなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.titleWithoutAgent.detail', $json$"以前はチャットに名前を付けるためだけに、6 語のためにエージェントのセッションを丸ごと開いていました。今は API 経由のモデルだけが名前を付けます。コマンドラインのエージェントしかない場合、チャットは最初のリクエストの要約をそのまま使います。"$json$::jsonb),
  ('ja', 'whatsNew.item.betterRetrieval.title', $json$"関連ファイルの選び方を改善"$json$::jsonb),
  ('ja', 'whatsNew.item.betterRetrieval.detail', $json$"ファイル検索は、どのファイルにもある語より珍しい語を重視し、fetchUserName のような識別子を単語に分け、つなぎの語を無視し、ドキュメントをコードより下に並べるようになりました。大きなファイルからは、先頭ではなくリクエストに合う部分を送ります。"$json$::jsonb),
  ('ja', 'whatsNew.item.shortHistory.title', $json$"各リクエストの履歴を短く"$json$::jsonb),
  ('ja', 'whatsNew.item.shortHistory.detail', $json$"リクエストがエージェントのセッションを再開できないときは、モデルの以前の回答を冒頭の数行に縮めて履歴に入れます。新しいリクエストに必要なのは話題であり、すでに渡したコード全体ではないからです。"$json$::jsonb),
  ('de', 'usage.jev.work.sessionResumed', $json$"Fortgesetzte Agent-Sitzungen"$json$::jsonb),
  ('de', 'usage.jev.saved.hint', $json$"Eine Schätzung, die nie zu den echten Zahlen addiert wird: Eine blockierte Anfrage zählt ihre eigene Größe plus eine durchschnittliche Antwort. Um die Einsparung in deinem Projekt zu messen, führe jayv bench aus."$json$::jsonb),
  ('de', 'whatsNew.item.agentSessionResume.title', $json$"Agenten machen dort weiter, wo sie aufgehört haben"$json$::jsonb),
  ('de', 'whatsNew.item.agentSessionResume.detail', $json$"Im selben Chat setzt die nächste Anfrage die Claude-Code-Sitzung der vorherigen fort, statt eine neue zu öffnen. Der Agent liest das Projekt und das ganze Gespräch nicht mehr bei jeder Nachricht neu ein, was der größte Tokenverbrauch eines langen Chats war. Nach 10 Anfragen oder wenn sich Agent, Modell oder Ordner ändern, beginnt eine neue Sitzung."$json$::jsonb),
  ('de', 'whatsNew.item.agentFileMap.title', $json$"Eine Dateiübersicht statt ganzer Dateien"$json$::jsonb),
  ('de', 'whatsNew.item.agentFileMap.detail', $json$"Agenten, die das Projekt selbst lesen, bekommen jetzt die Liste der relevantesten Dateien mit den darin gefundenen Definitionen und öffnen nur, was sie brauchen. Vorher hat JayV diese Dateien vollständig in die Anfrage kopiert, und der Agent hat sie trotzdem noch einmal gelesen. Modelle, die über eine API genutzt werden und die Festplatte nicht sehen, bekommen weiterhin die Dateien."$json$::jsonb),
  ('de', 'whatsNew.item.parallelJev.title', $json$"Schnellerer Start jeder Anfrage"$json$::jsonb),
  ('de', 'whatsNew.item.parallelJev.detail', $json$"Die Eingangskontrolle und die Routing-Einschätzung von Jev laufen jetzt gleichzeitig, sodass eine Anfrage nicht mehr einen Netzwerkaufruf nach dem anderen abwartet, bevor sie zum Modell geht."$json$::jsonb),
  ('de', 'whatsNew.item.promptCache.title', $json$"Prompt-Cache für Anthropic-Modelle"$json$::jsonb),
  ('de', 'whatsNew.item.promptCache.detail', $json$"Wenn du ein Anthropic-Modell über die API nutzt, werden die Anweisungen und der frühere Teil des Gesprächs für den Prompt-Cache markiert und bei der nächsten Nachricht zum Cache-Tarif berechnet. Zwischengespeicherte Tokens werden jetzt auch bei Modellen, die über eine API genutzt werden, im Verbrauch gezählt."$json$::jsonb),
  ('de', 'whatsNew.item.benchCommand.title', $json$"Miss die Einsparung selbst"$json$::jsonb),
  ('de', 'whatsNew.item.benchCommand.detail', $json$"Der neue Befehl jayv bench schickt eine Liste von Anfragen über JayV und direkt an denselben Agenten und gibt die auf beiden Seiten berechneten Tokens aus, Cache eingeschlossen. So siehst du ehrlich, was JayV in deinem eigenen Projekt einspart."$json$::jsonb),
  ('de', 'whatsNew.item.honestSavings.title', $json$"Das Einsparungsfeld zeigt nur echte Einsparungen"$json$::jsonb),
  ('de', 'whatsNew.item.honestSavings.detail', $json$"Die Zeile „Gekürzter Kontext“ wurde aus „Was er eingespart hat“ entfernt: Sie zählte Text, den JayV selbst ausgewählt und dann gekürzt hatte, nicht Tokens, die das Modell verbraucht hätte. Fortgesetzte Agent-Sitzungen werden jetzt unter „Was er getan hat“ gezählt."$json$::jsonb),
  ('de', 'whatsNew.item.titleWithoutAgent.title', $json$"Chat-Titel öffnen keine Agent-Sitzung mehr"$json$::jsonb),
  ('de', 'whatsNew.item.titleWithoutAgent.detail', $json$"Einen Chat zu benennen hat früher eine vollständige Agent-Sitzung gestartet, nur um sechs Wörter zu bekommen. Jetzt benennt nur noch ein über eine API genutztes Modell den Chat; gibt es nur Kommandozeilen-Agenten, behält der Chat die Zusammenfassung deiner ersten Anfrage."$json$::jsonb),
  ('de', 'whatsNew.item.betterRetrieval.title', $json$"Bessere Auswahl der relevanten Dateien"$json$::jsonb),
  ('de', 'whatsNew.item.betterRetrieval.detail', $json$"Die Dateisuche gewichtet jetzt seltene Wörter stärker als solche, die jede Datei enthält, zerlegt Bezeichner wie fetchUserName in Wörter, ignoriert Füllwörter, stuft Dokumentation unter Code ein und schickt aus einer großen Datei den Teil, der zur Anfrage passt, statt ihres Anfangs."$json$::jsonb),
  ('de', 'whatsNew.item.shortHistory.title', $json$"Kürzerer Verlauf in jeder Anfrage"$json$::jsonb),
  ('de', 'whatsNew.item.shortHistory.detail', $json$"Wenn eine Anfrage die Agent-Sitzung nicht fortsetzen kann, kommen frühere Antworten des Modells auf ihre ersten Zeilen gekürzt in den Verlauf, denn die neue Anfrage braucht das Thema, nicht den ganzen bereits gelieferten Code."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
