-- Versão nova do JayV: aviso no topo de qualquer tela e notificação no sino.
--
-- Até a v0.24 o app achava a versão nova ao abrir e já instalava, com a janela
-- de progresso na frente. Agora a consulta (ao abrir e a cada 30 minutos) só
-- avisa: uma faixa no topo de qualquer tela, com "O que muda" e "Atualizar
-- agora", e a notificação do aparelho `update.available` no sino. A
-- notificação é do aparelho (vive na memória do app), não da conta: nada muda
-- em `public.notifications`.
--
-- Só traduções: as chaves novas da janela, da faixa e da notificação, e o
-- texto novo de `app.updates.hint`, que dizia que o app só procura ao abrir.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'update.available.title', $json$"JayV {version} está disponível"$json$::jsonb),
  ('pt-BR', 'update.available.fromTo', $json$"Da versão {current} para a {next}. Atualizar baixa, instala e reinicia o JayV; seus pedidos continuam de onde pararam."$json$::jsonb),
  ('pt-BR', 'update.install', $json$"Atualizar agora"$json$::jsonb),
  ('pt-BR', 'update.later', $json$"Depois"$json$::jsonb),
  ('pt-BR', 'update.banner.title', $json$"JayV {version} está disponível"$json$::jsonb),
  ('pt-BR', 'update.banner.description', $json$"Atualize para receber as correções e novidades mais recentes."$json$::jsonb),
  ('pt-BR', 'update.banner.details', $json$"O que muda"$json$::jsonb),
  ('pt-BR', 'update.banner.dismiss', $json$"Esconder este aviso"$json$::jsonb),
  ('pt-BR', 'notifications.update.available', $json$"JayV {version} está disponível para instalar"$json$::jsonb),
  ('pt-BR', 'app.updates.hint', $json$"O app procura versões novas ao abrir e a cada 30 minutos, e mostra um aviso no topo quando há uma; o botão procura e atualiza agora."$json$::jsonb),
  ('en', 'update.available.title', $json$"JayV {version} is available"$json$::jsonb),
  ('en', 'update.available.fromTo', $json$"From version {current} to {next}. Updating downloads it, installs it and restarts JayV; your requests continue where they left off."$json$::jsonb),
  ('en', 'update.install', $json$"Update now"$json$::jsonb),
  ('en', 'update.later', $json$"Later"$json$::jsonb),
  ('en', 'update.banner.title', $json$"JayV {version} is available"$json$::jsonb),
  ('en', 'update.banner.description', $json$"Update to get the latest fixes and features."$json$::jsonb),
  ('en', 'update.banner.details', $json$"What changes"$json$::jsonb),
  ('en', 'update.banner.dismiss', $json$"Hide this notice"$json$::jsonb),
  ('en', 'notifications.update.available', $json$"JayV {version} is available to install"$json$::jsonb),
  ('en', 'app.updates.hint', $json$"The app looks for new versions when it opens and every 30 minutes, and shows a notice at the top when one is available; the button looks and updates now."$json$::jsonb),
  ('es', 'update.available.title', $json$"JayV {version} está disponible"$json$::jsonb),
  ('es', 'update.available.fromTo', $json$"De la versión {current} a la {next}. Actualizar la descarga, la instala y reinicia JayV; tus solicitudes siguen donde quedaron."$json$::jsonb),
  ('es', 'update.install', $json$"Actualizar ahora"$json$::jsonb),
  ('es', 'update.later', $json$"Más tarde"$json$::jsonb),
  ('es', 'update.banner.title', $json$"JayV {version} está disponible"$json$::jsonb),
  ('es', 'update.banner.description', $json$"Actualiza para recibir las correcciones y novedades más recientes."$json$::jsonb),
  ('es', 'update.banner.details', $json$"Qué cambia"$json$::jsonb),
  ('es', 'update.banner.dismiss', $json$"Ocultar este aviso"$json$::jsonb),
  ('es', 'notifications.update.available', $json$"JayV {version} está disponible para instalar"$json$::jsonb),
  ('es', 'app.updates.hint', $json$"La aplicación busca versiones nuevas al abrirse y cada 30 minutos, y muestra un aviso arriba cuando hay una; el botón busca y actualiza ahora."$json$::jsonb),
  ('zh-CN', 'update.available.title', $json$"JayV {version} 已可用"$json$::jsonb),
  ('zh-CN', 'update.available.fromTo', $json$"从版本 {current} 到 {next}。更新会下载、安装并重启 JayV；你的请求会从中断处继续。"$json$::jsonb),
  ('zh-CN', 'update.install', $json$"立即更新"$json$::jsonb),
  ('zh-CN', 'update.later', $json$"稍后"$json$::jsonb),
  ('zh-CN', 'update.banner.title', $json$"JayV {version} 已可用"$json$::jsonb),
  ('zh-CN', 'update.banner.description', $json$"更新以获取最新的修复和功能。"$json$::jsonb),
  ('zh-CN', 'update.banner.details', $json$"更新内容"$json$::jsonb),
  ('zh-CN', 'update.banner.dismiss', $json$"隐藏此提示"$json$::jsonb),
  ('zh-CN', 'notifications.update.available', $json$"JayV {version} 可以安装了"$json$::jsonb),
  ('zh-CN', 'app.updates.hint', $json$"应用会在打开时以及每 30 分钟检查一次新版本，有新版本时在顶部显示提示；按钮会立即检查并更新。"$json$::jsonb),
  ('hi', 'update.available.title', $json$"JayV {version} उपलब्ध है"$json$::jsonb),
  ('hi', 'update.available.fromTo', $json$"संस्करण {current} से {next} तक। अपडेट करने पर यह डाउनलोड होगा, इंस्टॉल होगा और JayV फिर से शुरू होगा; आपके अनुरोध वहीं से जारी रहेंगे।"$json$::jsonb),
  ('hi', 'update.install', $json$"अभी अपडेट करें"$json$::jsonb),
  ('hi', 'update.later', $json$"बाद में"$json$::jsonb),
  ('hi', 'update.banner.title', $json$"JayV {version} उपलब्ध है"$json$::jsonb),
  ('hi', 'update.banner.description', $json$"नवीनतम सुधार और सुविधाएँ पाने के लिए अपडेट करें।"$json$::jsonb),
  ('hi', 'update.banner.details', $json$"क्या बदला है"$json$::jsonb),
  ('hi', 'update.banner.dismiss', $json$"यह सूचना छिपाएँ"$json$::jsonb),
  ('hi', 'notifications.update.available', $json$"JayV {version} इंस्टॉल करने के लिए उपलब्ध है"$json$::jsonb),
  ('hi', 'app.updates.hint', $json$"ऐप खुलते समय और हर 30 मिनट में नए संस्करण खोजता है, और नया संस्करण मिलने पर ऊपर सूचना दिखाता है; बटन अभी खोजता और अपडेट करता है।"$json$::jsonb),
  ('ar', 'update.available.title', $json$"JayV {version} متاح"$json$::jsonb),
  ('ar', 'update.available.fromTo', $json$"من الإصدار {current} إلى {next}. التحديث ينزّله ويثبّته ويعيد تشغيل JayV؛ وتستمر طلباتك من حيث توقفت."$json$::jsonb),
  ('ar', 'update.install', $json$"حدّث الآن"$json$::jsonb),
  ('ar', 'update.later', $json$"لاحقًا"$json$::jsonb),
  ('ar', 'update.banner.title', $json$"JayV {version} متاح"$json$::jsonb),
  ('ar', 'update.banner.description', $json$"حدّث للحصول على أحدث الإصلاحات والميزات."$json$::jsonb),
  ('ar', 'update.banner.details', $json$"ما الذي تغيّر"$json$::jsonb),
  ('ar', 'update.banner.dismiss', $json$"إخفاء هذا التنبيه"$json$::jsonb),
  ('ar', 'notifications.update.available', $json$"JayV {version} متاح للتثبيت"$json$::jsonb),
  ('ar', 'app.updates.hint', $json$"يبحث التطبيق عن إصدارات جديدة عند فتحه وكل 30 دقيقة، ويعرض تنبيهًا في الأعلى عند توفر إصدار؛ والزر يبحث ويحدّث الآن."$json$::jsonb),
  ('fr', 'update.available.title', $json$"JayV {version} est disponible"$json$::jsonb),
  ('fr', 'update.available.fromTo', $json$"De la version {current} à la {next}. La mise à jour la télécharge, l’installe et redémarre JayV ; vos demandes reprennent là où elles s’étaient arrêtées."$json$::jsonb),
  ('fr', 'update.install', $json$"Mettre à jour"$json$::jsonb),
  ('fr', 'update.later', $json$"Plus tard"$json$::jsonb),
  ('fr', 'update.banner.title', $json$"JayV {version} est disponible"$json$::jsonb),
  ('fr', 'update.banner.description', $json$"Mettez à jour pour obtenir les derniers correctifs et nouveautés."$json$::jsonb),
  ('fr', 'update.banner.details', $json$"Nouveautés"$json$::jsonb),
  ('fr', 'update.banner.dismiss', $json$"Masquer cet avis"$json$::jsonb),
  ('fr', 'notifications.update.available', $json$"JayV {version} est prêt à être installé"$json$::jsonb),
  ('fr', 'app.updates.hint', $json$"L’application cherche les nouvelles versions à l’ouverture et toutes les 30 minutes, et affiche un avis en haut quand il y en a une ; le bouton cherche et met à jour maintenant."$json$::jsonb),
  ('ru', 'update.available.title', $json$"Доступна версия JayV {version}"$json$::jsonb),
  ('ru', 'update.available.fromTo', $json$"С версии {current} на {next}. Обновление скачает её, установит и перезапустит JayV; ваши запросы продолжатся с того же места."$json$::jsonb),
  ('ru', 'update.install', $json$"Обновить сейчас"$json$::jsonb),
  ('ru', 'update.later', $json$"Позже"$json$::jsonb),
  ('ru', 'update.banner.title', $json$"Доступна версия JayV {version}"$json$::jsonb),
  ('ru', 'update.banner.description', $json$"Обновитесь, чтобы получить последние исправления и новые возможности."$json$::jsonb),
  ('ru', 'update.banner.details', $json$"Что нового"$json$::jsonb),
  ('ru', 'update.banner.dismiss', $json$"Скрыть уведомление"$json$::jsonb),
  ('ru', 'notifications.update.available', $json$"JayV {version} готова к установке"$json$::jsonb),
  ('ru', 'app.updates.hint', $json$"Приложение ищет новые версии при запуске и каждые 30 минут и показывает уведомление вверху, когда версия доступна; кнопка проверяет и обновляет сейчас."$json$::jsonb),
  ('ja', 'update.available.title', $json$"JayV {version} が利用可能です"$json$::jsonb),
  ('ja', 'update.available.fromTo', $json$"バージョン {current} から {next} へ。更新するとダウンロード、インストールして JayV を再起動します。リクエストは中断したところから続きます。"$json$::jsonb),
  ('ja', 'update.install', $json$"今すぐ更新"$json$::jsonb),
  ('ja', 'update.later', $json$"後で"$json$::jsonb),
  ('ja', 'update.banner.title', $json$"JayV {version} が利用可能です"$json$::jsonb),
  ('ja', 'update.banner.description', $json$"最新の修正と新機能を入手するには更新してください。"$json$::jsonb),
  ('ja', 'update.banner.details', $json$"変更内容"$json$::jsonb),
  ('ja', 'update.banner.dismiss', $json$"この通知を隠す"$json$::jsonb),
  ('ja', 'notifications.update.available', $json$"JayV {version} をインストールできます"$json$::jsonb),
  ('ja', 'app.updates.hint', $json$"アプリは起動時と 30 分ごとに新しいバージョンを確認し、見つかると上部に通知を表示します。ボタンは今すぐ確認して更新します。"$json$::jsonb),
  ('de', 'update.available.title', $json$"JayV {version} ist verfügbar"$json$::jsonb),
  ('de', 'update.available.fromTo', $json$"Von Version {current} auf {next}. Das Update wird heruntergeladen, installiert und JayV neu gestartet; deine Anfragen laufen dort weiter, wo sie aufgehört haben."$json$::jsonb),
  ('de', 'update.install', $json$"Jetzt aktualisieren"$json$::jsonb),
  ('de', 'update.later', $json$"Später"$json$::jsonb),
  ('de', 'update.banner.title', $json$"JayV {version} ist verfügbar"$json$::jsonb),
  ('de', 'update.banner.description', $json$"Aktualisiere, um die neuesten Fehlerbehebungen und Funktionen zu erhalten."$json$::jsonb),
  ('de', 'update.banner.details', $json$"Was sich ändert"$json$::jsonb),
  ('de', 'update.banner.dismiss', $json$"Hinweis ausblenden"$json$::jsonb),
  ('de', 'notifications.update.available', $json$"JayV {version} kann installiert werden"$json$::jsonb),
  ('de', 'app.updates.hint', $json$"Die App sucht beim Öffnen und alle 30 Minuten nach neuen Versionen und zeigt oben einen Hinweis, wenn eine verfügbar ist; die Schaltfläche sucht und aktualisiert sofort."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
