-- v0.85.0 (app): página da organização no app igual à do site. Só textos:
-- as abas MCP e Skills da organização e o item do Novidades.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'org.extensions.mcp.description', $json$"Servidores MCP que esta organização dá aos membros. Nos projetos e chats dela eles se somam aos seus; aqui você não os edita."$json$::jsonb),
  ('en', 'org.extensions.mcp.description', $json$"MCP servers this organization gives its members. They are added to yours in the organization’s projects and chats; you can’t edit them here."$json$::jsonb),
  ('es', 'org.extensions.mcp.description', $json$"Servidores MCP que esta organización da a sus miembros. En sus proyectos y chats se suman a los tuyos; aquí no puedes editarlos."$json$::jsonb),
  ('zh-CN', 'org.extensions.mcp.description', $json$"本组织提供给成员的 MCP 服务器。在该组织的项目和聊天中，它们会与你自己的服务器一起生效；在这里无法编辑。"$json$::jsonb),
  ('hi', 'org.extensions.mcp.description', $json$"इस संगठन द्वारा सदस्यों को दिए गए MCP सर्वर। संगठन के प्रोजेक्ट और चैट में ये आपके सर्वरों के साथ जुड़ जाते हैं; यहाँ आप इन्हें संपादित नहीं कर सकते।"$json$::jsonb),
  ('ar', 'org.extensions.mcp.description', $json$"خوادم MCP التي تمنحها هذه المؤسسة لأعضائها. تُضاف إلى خوادمك في مشاريع المؤسسة ومحادثاتها، ولا يمكنك تعديلها هنا."$json$::jsonb),
  ('fr', 'org.extensions.mcp.description', $json$"Serveurs MCP que cette organisation met à disposition de ses membres. Dans ses projets et chats, ils s’ajoutent aux vôtres ; vous ne pouvez pas les modifier ici."$json$::jsonb),
  ('ru', 'org.extensions.mcp.description', $json$"MCP-серверы, которые эта организация предоставляет участникам. В её проектах и чатах они добавляются к вашим; изменить их здесь нельзя."$json$::jsonb),
  ('ja', 'org.extensions.mcp.description', $json$"この組織がメンバーに提供する MCP サーバーです。組織のプロジェクトとチャットでは自分のサーバーに加えて使われます。ここでは編集できません。"$json$::jsonb),
  ('de', 'org.extensions.mcp.description', $json$"MCP-Server, die diese Organisation ihren Mitgliedern bereitstellt. In ihren Projekten und Chats kommen sie zu Ihren eigenen hinzu; hier können Sie sie nicht bearbeiten."$json$::jsonb),
  ('pt-BR', 'org.extensions.skills.description', $json$"Skills que esta organização dá aos membros. Nos projetos e chats dela o Jev as considera junto com as suas; aqui você não as edita."$json$::jsonb),
  ('en', 'org.extensions.skills.description', $json$"Skills this organization gives its members. Jev considers them along with yours in the organization’s projects and chats; you can’t edit them here."$json$::jsonb),
  ('es', 'org.extensions.skills.description', $json$"Skills que esta organización da a sus miembros. En sus proyectos y chats Jev las considera junto con las tuyas; aquí no puedes editarlas."$json$::jsonb),
  ('zh-CN', 'org.extensions.skills.description', $json$"本组织提供给成员的技能。在该组织的项目和聊天中，Jev 会把它们与你自己的技能一并考虑；在这里无法编辑。"$json$::jsonb),
  ('hi', 'org.extensions.skills.description', $json$"इस संगठन द्वारा सदस्यों को दिए गए स्किल। संगठन के प्रोजेक्ट और चैट में Jev इन्हें आपके स्किल के साथ गिनता है; यहाँ आप इन्हें संपादित नहीं कर सकते।"$json$::jsonb),
  ('ar', 'org.extensions.skills.description', $json$"المهارات التي تمنحها هذه المؤسسة لأعضائها. في مشاريع المؤسسة ومحادثاتها ينظر Jev فيها مع مهاراتك، ولا يمكنك تعديلها هنا."$json$::jsonb),
  ('fr', 'org.extensions.skills.description', $json$"Skills que cette organisation met à disposition de ses membres. Dans ses projets et chats, Jev les considère avec les vôtres ; vous ne pouvez pas les modifier ici."$json$::jsonb),
  ('ru', 'org.extensions.skills.description', $json$"Навыки, которые эта организация предоставляет участникам. В её проектах и чатах Jev учитывает их вместе с вашими; изменить их здесь нельзя."$json$::jsonb),
  ('ja', 'org.extensions.skills.description', $json$"この組織がメンバーに提供するスキルです。組織のプロジェクトとチャットでは Jev が自分のスキルと合わせて検討します。ここでは編集できません。"$json$::jsonb),
  ('de', 'org.extensions.skills.description', $json$"Skills, die diese Organisation ihren Mitgliedern bereitstellt. In ihren Projekten und Chats berücksichtigt Jev sie zusammen mit Ihren eigenen; hier können Sie sie nicht bearbeiten."$json$::jsonb),
  ('pt-BR', 'org.extensions.mcp.empty', $json$"Esta organização ainda não tem servidores MCP."$json$::jsonb),
  ('en', 'org.extensions.mcp.empty', $json$"This organization has no MCP servers yet."$json$::jsonb),
  ('es', 'org.extensions.mcp.empty', $json$"Esta organización aún no tiene servidores MCP."$json$::jsonb),
  ('zh-CN', 'org.extensions.mcp.empty', $json$"本组织还没有 MCP 服务器。"$json$::jsonb),
  ('hi', 'org.extensions.mcp.empty', $json$"इस संगठन में अभी कोई MCP सर्वर नहीं है।"$json$::jsonb),
  ('ar', 'org.extensions.mcp.empty', $json$"لا تملك هذه المؤسسة خوادم MCP بعد."$json$::jsonb),
  ('fr', 'org.extensions.mcp.empty', $json$"Cette organisation n’a pas encore de serveurs MCP."$json$::jsonb),
  ('ru', 'org.extensions.mcp.empty', $json$"В этой организации пока нет MCP-серверов."$json$::jsonb),
  ('ja', 'org.extensions.mcp.empty', $json$"この組織にはまだ MCP サーバーがありません。"$json$::jsonb),
  ('de', 'org.extensions.mcp.empty', $json$"Diese Organisation hat noch keine MCP-Server."$json$::jsonb),
  ('pt-BR', 'org.extensions.skills.empty', $json$"Esta organização ainda não tem skills."$json$::jsonb),
  ('en', 'org.extensions.skills.empty', $json$"This organization has no skills yet."$json$::jsonb),
  ('es', 'org.extensions.skills.empty', $json$"Esta organización aún no tiene skills."$json$::jsonb),
  ('zh-CN', 'org.extensions.skills.empty', $json$"本组织还没有技能。"$json$::jsonb),
  ('hi', 'org.extensions.skills.empty', $json$"इस संगठन में अभी कोई स्किल नहीं है।"$json$::jsonb),
  ('ar', 'org.extensions.skills.empty', $json$"لا تملك هذه المؤسسة مهارات بعد."$json$::jsonb),
  ('fr', 'org.extensions.skills.empty', $json$"Cette organisation n’a pas encore de skills."$json$::jsonb),
  ('ru', 'org.extensions.skills.empty', $json$"В этой организации пока нет навыков."$json$::jsonb),
  ('ja', 'org.extensions.skills.empty', $json$"この組織にはまだスキルがありません。"$json$::jsonb),
  ('de', 'org.extensions.skills.empty', $json$"Diese Organisation hat noch keine Skills."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgTabs.title', $json$"Página da organização igual à do site"$json$::jsonb),
  ('en', 'whatsNew.item.orgTabs.title', $json$"Organization page like the site"$json$::jsonb),
  ('es', 'whatsNew.item.orgTabs.title', $json$"Página de la organización como la del sitio"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgTabs.title', $json$"组织页面与网站一致"$json$::jsonb),
  ('hi', 'whatsNew.item.orgTabs.title', $json$"संगठन का पेज साइट जैसा"$json$::jsonb),
  ('ar', 'whatsNew.item.orgTabs.title', $json$"صفحة المؤسسة مثل الموقع"$json$::jsonb),
  ('fr', 'whatsNew.item.orgTabs.title', $json$"Page de l’organisation comme sur le site"$json$::jsonb),
  ('ru', 'whatsNew.item.orgTabs.title', $json$"Страница организации как на сайте"$json$::jsonb),
  ('ja', 'whatsNew.item.orgTabs.title', $json$"組織ページをサイトと同じに"$json$::jsonb),
  ('de', 'whatsNew.item.orgTabs.title', $json$"Organisationsseite wie auf der Website"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgTabs.detail', $json$"As abas da organização agora ficam numa coluna na vertical, como no site, com as novas abas MCP e Skills que listam o que a organização dá aos membros. O botão de voltar é o do site: o ❯ verde virado para a esquerda com “Voltar às organizações” ao lado."$json$::jsonb),
  ('en', 'whatsNew.item.orgTabs.detail', $json$"The organization’s tabs now sit in a vertical column, as on the site, with new MCP and Skills tabs that list what the organization gives its members. The back button is the site’s: the green ❯ pointing left with “Back to organizations” beside it."$json$::jsonb),
  ('es', 'whatsNew.item.orgTabs.detail', $json$"Las pestañas de la organización ahora van en una columna vertical, como en el sitio, con nuevas pestañas MCP y Skills que listan lo que la organización da a sus miembros. El botón de volver es el del sitio: el ❯ verde apuntando a la izquierda con “Volver a las organizaciones” al lado."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgTabs.detail', $json$"组织的标签页现在像网站一样竖向排列，并新增 MCP 和技能两个标签页，列出组织提供给成员的内容。返回按钮与网站一致：向左的绿色 ❯，旁边是“返回组织列表”。"$json$::jsonb),
  ('hi', 'whatsNew.item.orgTabs.detail', $json$"संगठन के टैब अब साइट की तरह लंबवत कॉलम में हैं, और नए MCP और स्किल टैब संगठन द्वारा सदस्यों को दी गई चीज़ें दिखाते हैं। वापस बटन साइट जैसा है: बाईं ओर इशारा करता हरा ❯ और उसके साथ “संगठनों पर वापस”।"$json$::jsonb),
  ('ar', 'whatsNew.item.orgTabs.detail', $json$"أصبحت تبويبات المؤسسة في عمود عمودي كما في الموقع، مع تبويبين جديدين MCP والمهارات يعرضان ما تمنحه المؤسسة لأعضائها. زر الرجوع هو نفسه في الموقع: ❯ أخضر متجه لليسار وبجانبه «العودة إلى المؤسسات»."$json$::jsonb),
  ('fr', 'whatsNew.item.orgTabs.detail', $json$"Les onglets de l’organisation sont maintenant dans une colonne verticale, comme sur le site, avec de nouveaux onglets MCP et Skills qui listent ce que l’organisation donne à ses membres. Le bouton retour est celui du site : le ❯ vert tourné vers la gauche avec « Retour aux organisations » à côté."$json$::jsonb),
  ('ru', 'whatsNew.item.orgTabs.detail', $json$"Вкладки организации теперь расположены вертикальной колонкой, как на сайте, а новые вкладки MCP и Skills показывают, что организация даёт участникам. Кнопка «назад» как на сайте: зелёный ❯, повёрнутый влево, и рядом «Назад к организациям»."$json$::jsonb),
  ('ja', 'whatsNew.item.orgTabs.detail', $json$"組織のタブがサイトと同じ縦の列になり、組織がメンバーに提供するものを一覧する MCP と Skills のタブが加わりました。戻るボタンもサイトと同じで、左向きの緑の ❯ の横に「組織一覧に戻る」と表示されます。"$json$::jsonb),
  ('de', 'whatsNew.item.orgTabs.detail', $json$"Die Tabs der Organisation stehen jetzt wie auf der Website in einer vertikalen Spalte, mit neuen Tabs MCP und Skills, die auflisten, was die Organisation ihren Mitgliedern gibt. Der Zurück-Button ist der der Website: das grüne ❯ nach links mit „Zurück zu den Organisationen“ daneben."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
