-- v0.73.0: atualizar ao abrir o app — tela de abertura, opção em Configurações › App, Novidades e documentação, nos dez idiomas.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'update.launch.checking', $json$"Procurando atualizações…"$json$::jsonb),
  ('en', 'update.launch.checking', $json$"Checking for updates…"$json$::jsonb),
  ('es', 'update.launch.checking', $json$"Buscando actualizaciones…"$json$::jsonb),
  ('zh-CN', 'update.launch.checking', $json$"正在检查更新…"$json$::jsonb),
  ('hi', 'update.launch.checking', $json$"अपडेट खोजे जा रहे हैं…"$json$::jsonb),
  ('ar', 'update.launch.checking', $json$"جارٍ البحث عن تحديثات…"$json$::jsonb),
  ('fr', 'update.launch.checking', $json$"Recherche de mises à jour…"$json$::jsonb),
  ('ru', 'update.launch.checking', $json$"Проверка обновлений…"$json$::jsonb),
  ('ja', 'update.launch.checking', $json$"アップデートを確認中…"$json$::jsonb),
  ('de', 'update.launch.checking', $json$"Suche nach Updates …"$json$::jsonb),
  ('pt-BR', 'update.launch.note', $json$"Se houver versão nova, o JayV instala e reinicia sozinho."$json$::jsonb),
  ('en', 'update.launch.note', $json$"If there is a new version, JayV installs it and restarts on its own."$json$::jsonb),
  ('es', 'update.launch.note', $json$"Si hay una versión nueva, JayV la instala y se reinicia solo."$json$::jsonb),
  ('zh-CN', 'update.launch.note', $json$"如有新版本，JayV 会自动安装并重启。"$json$::jsonb),
  ('hi', 'update.launch.note', $json$"नया संस्करण होने पर JayV उसे खुद इंस्टॉल करके रीस्टार्ट हो जाएगा।"$json$::jsonb),
  ('ar', 'update.launch.note', $json$"إذا وُجد إصدار جديد فسيثبّته JayV ويعيد التشغيل تلقائيًا."$json$::jsonb),
  ('fr', 'update.launch.note', $json$"S’il y a une nouvelle version, JayV l’installe et redémarre tout seul."$json$::jsonb),
  ('ru', 'update.launch.note', $json$"Если есть новая версия, JayV сам установит её и перезапустится."$json$::jsonb),
  ('ja', 'update.launch.note', $json$"新しいバージョンがあれば、JayV が自動でインストールして再起動します。"$json$::jsonb),
  ('de', 'update.launch.note', $json$"Gibt es eine neue Version, installiert JayV sie und startet selbst neu."$json$::jsonb),
  ('pt-BR', 'update.launch.skip', $json$"Pular"$json$::jsonb),
  ('en', 'update.launch.skip', $json$"Skip"$json$::jsonb),
  ('es', 'update.launch.skip', $json$"Omitir"$json$::jsonb),
  ('zh-CN', 'update.launch.skip', $json$"跳过"$json$::jsonb),
  ('hi', 'update.launch.skip', $json$"छोड़ें"$json$::jsonb),
  ('ar', 'update.launch.skip', $json$"تخطي"$json$::jsonb),
  ('fr', 'update.launch.skip', $json$"Passer"$json$::jsonb),
  ('ru', 'update.launch.skip', $json$"Пропустить"$json$::jsonb),
  ('ja', 'update.launch.skip', $json$"スキップ"$json$::jsonb),
  ('de', 'update.launch.skip', $json$"Überspringen"$json$::jsonb),
  ('pt-BR', 'app.updates.launch', $json$"Atualizar ao abrir o JayV"$json$::jsonb),
  ('en', 'app.updates.launch', $json$"Update when JayV opens"$json$::jsonb),
  ('es', 'app.updates.launch', $json$"Actualizar al abrir JayV"$json$::jsonb),
  ('zh-CN', 'app.updates.launch', $json$"打开 JayV 时更新"$json$::jsonb),
  ('hi', 'app.updates.launch', $json$"JayV खुलते समय अपडेट करें"$json$::jsonb),
  ('ar', 'app.updates.launch', $json$"التحديث عند فتح JayV"$json$::jsonb),
  ('fr', 'app.updates.launch', $json$"Mettre à jour à l’ouverture de JayV"$json$::jsonb),
  ('ru', 'app.updates.launch', $json$"Обновлять при запуске JayV"$json$::jsonb),
  ('ja', 'app.updates.launch', $json$"JayV を開くときに更新"$json$::jsonb),
  ('de', 'app.updates.launch', $json$"Beim Start von JayV aktualisieren"$json$::jsonb),
  ('pt-BR', 'app.updates.launch.hint', $json$"Ao abrir, o JayV procura uma versão nova e, se houver, baixa, instala e reinicia sozinho. Desligado, só aparece o aviso no topo e você escolhe quando atualizar."$json$::jsonb),
  ('en', 'app.updates.launch.hint', $json$"On open, JayV looks for a new version and, if there is one, downloads it, installs it and restarts on its own. Off: only the notice at the top appears and you choose when to update."$json$::jsonb),
  ('es', 'app.updates.launch.hint', $json$"Al abrir, JayV busca una versión nueva y, si la hay, la descarga, la instala y se reinicia solo. Desactivado: solo aparece el aviso superior y tú eliges cuándo actualizar."$json$::jsonb),
  ('zh-CN', 'app.updates.launch.hint', $json$"打开时，JayV 会检查新版本，如有则自动下载、安装并重启。关闭后只显示顶部提示，由你决定何时更新。"$json$::jsonb),
  ('hi', 'app.updates.launch.hint', $json$"खुलते समय JayV नया संस्करण खोजता है और मिलने पर उसे डाउनलोड, इंस्टॉल करके खुद रीस्टार्ट होता है। बंद होने पर केवल ऊपर की सूचना दिखती है और अपडेट का समय आप चुनते हैं।"$json$::jsonb),
  ('ar', 'app.updates.launch.hint', $json$"عند الفتح يبحث JayV عن إصدار جديد، وإن وُجد ينزّله ويثبّته ويعيد التشغيل تلقائيًا. عند الإيقاف يظهر التنبيه العلوي فقط وتختار أنت وقت التحديث."$json$::jsonb),
  ('fr', 'app.updates.launch.hint', $json$"À l’ouverture, JayV cherche une nouvelle version et, s’il y en a une, la télécharge, l’installe et redémarre tout seul. Désactivé : seul l’avis en haut s’affiche et vous choisissez quand mettre à jour."$json$::jsonb),
  ('ru', 'app.updates.launch.hint', $json$"При запуске JayV ищет новую версию и, если она есть, сам скачивает, устанавливает её и перезапускается. Если выключено, появляется только уведомление сверху, а время обновления вы выбираете сами."$json$::jsonb),
  ('ja', 'app.updates.launch.hint', $json$"起動時に JayV が新しいバージョンを確認し、あればダウンロード・インストールして自動で再起動します。オフの場合は上部の通知だけが表示され、更新のタイミングは自分で選べます。"$json$::jsonb),
  ('de', 'app.updates.launch.hint', $json$"Beim Start sucht JayV nach einer neuen Version und lädt sie, falls vorhanden, herunter, installiert sie und startet selbst neu. Aus: Es erscheint nur der Hinweis oben, und du wählst, wann du aktualisierst."$json$::jsonb),
  ('pt-BR', 'app.updates.auto', $json$"O JayV procura versão nova ao abrir e a cada 15 segundos. Com “Atualizar ao abrir” ligado, a versão achada ao abrir é instalada na hora; as achadas depois aparecem num aviso no topo de todas as telas."$json$::jsonb),
  ('en', 'app.updates.auto', $json$"JayV looks for a new version when it opens and every 15 seconds. With “Update when JayV opens” on, a version found at startup is installed right away; later ones appear in a notice at the top of every screen."$json$::jsonb),
  ('es', 'app.updates.auto', $json$"JayV busca una versión nueva al abrir y cada 15 segundos. Con “Actualizar al abrir JayV” activado, la versión encontrada al abrir se instala de inmediato; las posteriores aparecen en un aviso en la parte superior de todas las pantallas."$json$::jsonb),
  ('zh-CN', 'app.updates.auto', $json$"JayV 会在打开时以及每 15 秒检查一次新版本。开启“打开 JayV 时更新”后，启动时发现的版本会立即安装；之后发现的版本会显示在所有界面顶部的提示中。"$json$::jsonb),
  ('hi', 'app.updates.auto', $json$"JayV खुलते समय और हर 15 सेकंड में नया संस्करण खोजता है। “JayV खुलते समय अपडेट करें” चालू होने पर शुरू में मिला संस्करण तुरंत इंस्टॉल हो जाता है; बाद में मिले संस्करण हर स्क्रीन के ऊपर सूचना में दिखते हैं।"$json$::jsonb),
  ('ar', 'app.updates.auto', $json$"يبحث JayV عن إصدار جديد عند الفتح وكل 15 ثانية. مع تفعيل «التحديث عند فتح JayV» يُثبَّت الإصدار الذي يُعثر عليه عند البدء فورًا، أما اللاحقة فتظهر في تنبيه أعلى كل الشاشات."$json$::jsonb),
  ('fr', 'app.updates.auto', $json$"JayV cherche une nouvelle version à l’ouverture puis toutes les 15 secondes. Avec « Mettre à jour à l’ouverture de JayV » activé, la version trouvée au démarrage est installée aussitôt ; les suivantes apparaissent dans un avis en haut de chaque écran."$json$::jsonb),
  ('ru', 'app.updates.auto', $json$"JayV ищет новую версию при запуске и каждые 15 секунд. Если включено «Обновлять при запуске JayV», найденная при старте версия устанавливается сразу; найденные позже появляются в уведомлении вверху каждого экрана."$json$::jsonb),
  ('ja', 'app.updates.auto', $json$"JayV は起動時と 15 秒ごとに新しいバージョンを確認します。「JayV を開くときに更新」がオンなら、起動時に見つかったバージョンはすぐにインストールされ、その後に見つかったものはすべての画面上部の通知に表示されます。"$json$::jsonb),
  ('de', 'app.updates.auto', $json$"JayV sucht beim Start und danach alle 15 Sekunden nach einer neuen Version. Ist „Beim Start von JayV aktualisieren“ an, wird eine beim Start gefundene Version sofort installiert; spätere erscheinen in einem Hinweis oben auf jedem Bildschirm."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateOnLaunch.title', $json$"Atualiza sozinho ao abrir"$json$::jsonb),
  ('en', 'whatsNew.item.updateOnLaunch.title', $json$"Updates itself when it opens"$json$::jsonb),
  ('es', 'whatsNew.item.updateOnLaunch.title', $json$"Se actualiza solo al abrir"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateOnLaunch.title', $json$"打开时自动更新"$json$::jsonb),
  ('hi', 'whatsNew.item.updateOnLaunch.title', $json$"खुलते समय खुद अपडेट"$json$::jsonb),
  ('ar', 'whatsNew.item.updateOnLaunch.title', $json$"يتحدّث تلقائيًا عند الفتح"$json$::jsonb),
  ('fr', 'whatsNew.item.updateOnLaunch.title', $json$"Se met à jour à l’ouverture"$json$::jsonb),
  ('ru', 'whatsNew.item.updateOnLaunch.title', $json$"Обновляется при запуске"$json$::jsonb),
  ('ja', 'whatsNew.item.updateOnLaunch.title', $json$"起動時に自動で更新"$json$::jsonb),
  ('de', 'whatsNew.item.updateOnLaunch.title', $json$"Aktualisiert sich beim Start"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateOnLaunch.detail', $json$"Ao abrir, o JayV procura uma versão nova antes de mostrar a tela e, se houver, baixa, instala e reinicia sozinho, com a janela de progresso na frente. Sem rede (passados 10 segundos) ou clicando em Pular, o app abre normalmente. Dá para desligar em Configurações › App › Versão, ou pela paleta (Ctrl+K)."$json$::jsonb),
  ('en', 'whatsNew.item.updateOnLaunch.detail', $json$"On open, JayV looks for a new version before showing the screen and, if there is one, downloads it, installs it and restarts on its own, with the progress window in front. Without a network (after 10 seconds) or by clicking Skip, the app opens normally. You can turn it off in Settings › App › Version, or from the command palette (Ctrl+K)."$json$::jsonb),
  ('es', 'whatsNew.item.updateOnLaunch.detail', $json$"Al abrir, JayV busca una versión nueva antes de mostrar la pantalla y, si la hay, la descarga, la instala y se reinicia solo, con la ventana de progreso al frente. Sin red (pasados 10 segundos) o al pulsar Omitir, la app abre con normalidad. Puedes desactivarlo en Ajustes › App › Versión o desde la paleta (Ctrl+K)."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateOnLaunch.detail', $json$"打开时，JayV 会先检查新版本再显示界面，如有则自动下载、安装并重启，并在前台显示进度窗口。没有网络（超过 10 秒）或点击“跳过”时，应用正常打开。可在 设置 › 应用 › 版本 或命令面板（Ctrl+K）中关闭。"$json$::jsonb),
  ('hi', 'whatsNew.item.updateOnLaunch.detail', $json$"खुलते समय JayV स्क्रीन दिखाने से पहले नया संस्करण खोजता है और मिलने पर उसे डाउनलोड, इंस्टॉल करके खुद रीस्टार्ट होता है, प्रगति विंडो सामने रहती है। नेटवर्क न होने पर (10 सेकंड बाद) या छोड़ें दबाने पर ऐप सामान्य रूप से खुलता है। इसे सेटिंग › ऐप › संस्करण या कमांड पैलेट (Ctrl+K) से बंद कर सकते हैं।"$json$::jsonb),
  ('ar', 'whatsNew.item.updateOnLaunch.detail', $json$"عند الفتح يبحث JayV عن إصدار جديد قبل عرض الشاشة، وإن وُجد ينزّله ويثبّته ويعيد التشغيل تلقائيًا مع نافذة التقدّم في المقدمة. دون شبكة (بعد 10 ثوانٍ) أو بالنقر على «تخطي» يفتح التطبيق بشكل عادي. يمكنك إيقافه من الإعدادات › التطبيق › الإصدار أو من لوحة الأوامر (Ctrl+K)."$json$::jsonb),
  ('fr', 'whatsNew.item.updateOnLaunch.detail', $json$"À l’ouverture, JayV cherche une nouvelle version avant d’afficher l’écran et, s’il y en a une, la télécharge, l’installe et redémarre tout seul, avec la fenêtre de progression au premier plan. Sans réseau (après 10 secondes) ou en cliquant sur Passer, l’app s’ouvre normalement. Désactivable dans Réglages › App › Version ou depuis la palette (Ctrl+K)."$json$::jsonb),
  ('ru', 'whatsNew.item.updateOnLaunch.detail', $json$"При запуске JayV до показа экрана ищет новую версию и, если она есть, сам скачивает, устанавливает и перезапускается, показывая окно прогресса. Без сети (через 10 секунд) или по кнопке «Пропустить» приложение открывается как обычно. Отключить можно в Настройки › Приложение › Версия или в палитре команд (Ctrl+K)."$json$::jsonb),
  ('ja', 'whatsNew.item.updateOnLaunch.detail', $json$"起動時、画面を表示する前に JayV が新しいバージョンを確認し、あればダウンロード・インストールして自動で再起動します（進捗ウィンドウが前面に表示されます）。ネットワークがない場合（10 秒後）や「スキップ」を押した場合は、通常どおり起動します。設定 › アプリ › バージョン、またはコマンドパレット（Ctrl+K）でオフにできます。"$json$::jsonb),
  ('de', 'whatsNew.item.updateOnLaunch.detail', $json$"Beim Start sucht JayV nach einer neuen Version, bevor die Oberfläche erscheint, und lädt sie, falls vorhanden, herunter, installiert sie und startet selbst neu – mit dem Fortschrittsfenster im Vordergrund. Ohne Netzwerk (nach 10 Sekunden) oder mit „Überspringen“ öffnet sich die App normal. Abschaltbar unter Einstellungen › App › Version oder in der Befehlspalette (Strg+K)."$json$::jsonb),
  ('pt-BR', 'docs.updates.summary', $json$"O JayV procura uma versão nova ao abrir e em segundo plano, instala sozinho a que achar ao abrir e, depois de cada atualização, mostra o que mudou desde a última versão que você viu."$json$::jsonb),
  ('en', 'docs.updates.summary', $json$"JayV checks for a new version when it opens and in the background, installs the one it finds at startup by itself, and after each update shows what changed since the last version you saw."$json$::jsonb),
  ('es', 'docs.updates.summary', $json$"JayV busca una versión nueva al abrir y en segundo plano, instala sola la que encuentra al abrir y, tras cada actualización, muestra qué cambió desde la última versión que viste."$json$::jsonb),
  ('zh-CN', 'docs.updates.summary', $json$"JayV 会在打开时和后台检查新版本，自动安装启动时发现的版本，并在每次更新后显示自你上次查看以来的变化。"$json$::jsonb),
  ('hi', 'docs.updates.summary', $json$"JayV खुलते समय और बैकग्राउंड में नया संस्करण खोजता है, शुरू में मिले संस्करण को खुद इंस्टॉल करता है और हर अपडेट के बाद दिखाता है कि आपके आखिरी देखे संस्करण के बाद क्या बदला।"$json$::jsonb),
  ('ar', 'docs.updates.summary', $json$"يبحث JayV عن إصدار جديد عند الفتح وفي الخلفية، ويثبّت تلقائيًا ما يجده عند البدء، وبعد كل تحديث يعرض ما تغيّر منذ آخر إصدار رأيته."$json$::jsonb),
  ('fr', 'docs.updates.summary', $json$"JayV cherche une nouvelle version à l’ouverture et en arrière-plan, installe seul celle trouvée au démarrage et, après chaque mise à jour, affiche ce qui a changé depuis la dernière version que vous avez vue."$json$::jsonb),
  ('ru', 'docs.updates.summary', $json$"JayV ищет новую версию при запуске и в фоне, сам устанавливает найденную при старте и после каждого обновления показывает, что изменилось с последней увиденной вами версии."$json$::jsonb),
  ('ja', 'docs.updates.summary', $json$"JayV は起動時とバックグラウンドで新しいバージョンを確認し、起動時に見つかったものは自動でインストールし、更新のたびに前回見たバージョンからの変更点を表示します。"$json$::jsonb),
  ('de', 'docs.updates.summary', $json$"JayV sucht beim Start und im Hintergrund nach einer neuen Version, installiert die beim Start gefundene selbst und zeigt nach jedem Update, was sich seit der zuletzt gesehenen Version geändert hat."$json$::jsonb),
  ('pt-BR', 'docs.updates.usage', $json$"Ao abrir, uma tela rápida procura a versão nova e, havendo, atualiza e reinicia (Pular abre o app na hora). Achada depois, uma barra oferece O que muda e Atualizar agora. Para desligar a atualização ao abrir: Configurações › App › Versão. O histórico completo está em Novidades do JayV, na paleta de comandos, e na página Notas da versão do site."$json$::jsonb),
  ('en', 'docs.updates.usage', $json$"On open, a short screen looks for the new version and, if there is one, updates and restarts (Skip opens the app right away). Found later, a bar offers What changes and Update now. To turn off updating on open: Settings › App › Version. The full history is in What's new, in the command palette, and on the Release notes page of the site."$json$::jsonb),
  ('es', 'docs.updates.usage', $json$"Al abrir, una pantalla breve busca la versión nueva y, si la hay, actualiza y reinicia (Omitir abre la app de inmediato). Si se encuentra después, una barra ofrece Qué cambia y Actualizar ahora. Para desactivar la actualización al abrir: Ajustes › App › Versión. El historial completo está en Novedades, en la paleta de comandos y en la página Notas de la versión del sitio."$json$::jsonb),
  ('zh-CN', 'docs.updates.usage', $json$"打开时，一个简短的界面会检查新版本，如有则更新并重启（点“跳过”可立即进入应用）。之后发现的版本会由顶部栏提供“变化内容”和“立即更新”。要关闭启动时更新：设置 › 应用 › 版本。完整历史在“新功能”、命令面板和网站的“版本说明”页面中。"$json$::jsonb),
  ('hi', 'docs.updates.usage', $json$"खुलते समय एक छोटी स्क्रीन नया संस्करण खोजती है और मिलने पर अपडेट करके रीस्टार्ट करती है (छोड़ें दबाने पर ऐप तुरंत खुलता है)। बाद में मिलने पर ऊपर की पट्टी में क्या बदलता है और अभी अपडेट करें के विकल्प आते हैं। खुलते समय अपडेट बंद करने के लिए: सेटिंग › ऐप › संस्करण। पूरा इतिहास नया क्या है, कमांड पैलेट और साइट के रिलीज़ नोट्स पेज पर है।"$json$::jsonb),
  ('ar', 'docs.updates.usage', $json$"عند الفتح تبحث شاشة قصيرة عن الإصدار الجديد، وإن وُجد تحدّث وتعيد التشغيل (تخطي يفتح التطبيق فورًا). وإن وُجد لاحقًا يعرض الشريط العلوي «ما الذي يتغير» و«التحديث الآن». لإيقاف التحديث عند الفتح: الإعدادات › التطبيق › الإصدار. السجل الكامل في «الجديد» ولوحة الأوامر وصفحة ملاحظات الإصدار في الموقع."$json$::jsonb),
  ('fr', 'docs.updates.usage', $json$"À l’ouverture, un court écran cherche la nouvelle version et, s’il y en a une, met à jour et redémarre (Passer ouvre l’app aussitôt). Trouvée plus tard, une barre propose Ce qui change et Mettre à jour maintenant. Pour désactiver la mise à jour à l’ouverture : Réglages › App › Version. L’historique complet est dans Nouveautés, dans la palette de commandes et sur la page Notes de version du site."$json$::jsonb),
  ('ru', 'docs.updates.usage', $json$"При запуске короткий экран ищет новую версию и, если она есть, обновляет и перезапускает приложение («Пропустить» открывает его сразу). Если версия найдена позже, панель сверху предлагает «Что изменится» и «Обновить сейчас». Чтобы отключить обновление при запуске: Настройки › Приложение › Версия. Полная история — в «Новом», в палитре команд и на странице заметок о выпуске на сайте."$json$::jsonb),
  ('ja', 'docs.updates.usage', $json$"起動時に短い画面が新しいバージョンを確認し、あれば更新して再起動します（「スキップ」で即座にアプリを開けます）。その後に見つかった場合は、上部のバーに「変更内容」と「今すぐ更新」が表示されます。起動時の更新をオフにするには 設定 › アプリ › バージョン。全履歴は「新機能」、コマンドパレット、サイトのリリースノートページにあります。"$json$::jsonb),
  ('de', 'docs.updates.usage', $json$"Beim Start sucht ein kurzer Bildschirm nach der neuen Version und aktualisiert und startet gegebenenfalls neu („Überspringen“ öffnet die App sofort). Wird sie später gefunden, bietet eine Leiste Was ändert sich und Jetzt aktualisieren an. Zum Abschalten des Updates beim Start: Einstellungen › App › Version. Der gesamte Verlauf steht unter Neuigkeiten, in der Befehlspalette und auf der Seite Release Notes der Website."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
