-- v0.56.0: a continuação curta herda o veredito do pedido que ela continua, e
-- a portaria pergunta ela mesma (enviar como está, enviar reescrito ou completar)
-- antes de chamar qualquer agente. `entry.note.ask` muda de texto. Só textos.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'entry.note.ask', $json$"Liberado com ressalva: a portaria pergunta a você antes de chamar um agente."$json$::jsonb),
  ('pt-BR', 'entry.note.confirmed', $json$"Liberado por você: enviado depois de a portaria perguntar."$json$::jsonb),
  ('pt-BR', 'gate.confirm', $json$"A portaria segurou este pedido antes de chamar qualquer agente: {score} de 100 (um {scope} pede {demand})."$json$::jsonb),
  ('pt-BR', 'gate.confirm.choose', $json$"Envie como está, envie a versão que o JayV reescreveu com instruções para o que falta, ou complete o pedido."$json$::jsonb),
  ('pt-BR', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('pt-BR', 'gate.confirm.option.send_as_is', $json$"Enviar como está"$json$::jsonb),
  ('pt-BR', 'gate.confirm.option.send_rewritten', $json$"Enviar reescrito"$json$::jsonb),
  ('pt-BR', 'gate.confirm.complete', $json$"Completar o pedido"$json$::jsonb),
  ('pt-BR', 'gate.confirm.completeHint', $json$"Escreva o que faltou; a portaria lê junto com o seu pedido."$json$::jsonb),
  ('pt-BR', 'source.gate', $json$"a portaria"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.followUps.title', $json$"A continuação mantém a passagem do pedido que ela continua"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.followUps.detail', $json$"Uma mensagem curta logo depois de uma resposta, como \"pode implementar\", \"segue\" ou \"ainda dá erro\", agora é lida como parte da conversa: ela mantém o veredito da portaria do pedido que continua e pode ir para o modo build, em vez de virar mais uma pergunta. Com o Jev ligado, a portaria também lê as últimas mensagens do chat."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.gateAsks.title', $json$"A portaria pergunta ela mesma, antes de qualquer agente rodar"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.gateAsks.detail', $json$"Quando um pedido é liberado com ressalva, a portaria não paga mais uma sessão de agente só para fazer uma pergunta. Ela mostra o que falta e oferece três saídas: enviar como está, enviar a versão que o JayV reescreveu com instruções para as lacunas, ou completar o pedido. As duas primeiras vão direto ao agente, e podem construir."$json$::jsonb),
  ('en', 'entry.note.ask', $json$"Cleared with reservations: the gatehouse asks you before calling an agent."$json$::jsonb),
  ('en', 'entry.note.confirmed', $json$"Cleared by you: sent after the gatehouse asked."$json$::jsonb),
  ('en', 'gate.confirm', $json$"The gatehouse held this request before calling any agent: {score} out of 100 (a {scope} asks for {demand})."$json$::jsonb),
  ('en', 'gate.confirm.choose', $json$"Send it as written, send the version JayV rewrote with instructions for what is missing, or complete the request."$json$::jsonb),
  ('en', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('en', 'gate.confirm.option.send_as_is', $json$"Send as written"$json$::jsonb),
  ('en', 'gate.confirm.option.send_rewritten', $json$"Send rewritten"$json$::jsonb),
  ('en', 'gate.confirm.complete', $json$"Complete the request"$json$::jsonb),
  ('en', 'gate.confirm.completeHint', $json$"Write what was missing; the gatehouse reads it together with your request."$json$::jsonb),
  ('en', 'source.gate', $json$"the gatehouse"$json$::jsonb),
  ('en', 'whatsNew.item.followUps.title', $json$"Follow-ups keep the pass of the request they continue"$json$::jsonb),
  ('en', 'whatsNew.item.followUps.detail', $json$"A short message right after an answer, such as \"go ahead\", \"implement it\" or \"it still fails\", is now read as part of the conversation: it keeps the gatehouse verdict of the request it continues, so it can go to build mode instead of turning into another question. With the Jev on, the gatehouse also reads the last messages of the chat."$json$::jsonb),
  ('en', 'whatsNew.item.gateAsks.title', $json$"The gatehouse asks you itself, before any agent runs"$json$::jsonb),
  ('en', 'whatsNew.item.gateAsks.detail', $json$"When a request is cleared with reservations, the gatehouse no longer pays an agent session just to ask a question. It shows what is missing and offers three ways out: send as written, send the version JayV rewrote with instructions for the gaps, or complete the request. The first two go straight to the agent, and can build."$json$::jsonb),
  ('es', 'entry.note.ask', $json$"Liberado con reservas: la portería te pregunta antes de llamar a un agente."$json$::jsonb),
  ('es', 'entry.note.confirmed', $json$"Liberado por ti: enviado después de que la portería preguntara."$json$::jsonb),
  ('es', 'gate.confirm', $json$"La portería retuvo esta solicitud antes de llamar a cualquier agente: {score} de 100 (un {scope} pide {demand})."$json$::jsonb),
  ('es', 'gate.confirm.choose', $json$"Envíala tal cual, envía la versión que JayV reescribió con instrucciones para lo que falta, o completa la solicitud."$json$::jsonb),
  ('es', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('es', 'gate.confirm.option.send_as_is', $json$"Enviar tal cual"$json$::jsonb),
  ('es', 'gate.confirm.option.send_rewritten', $json$"Enviar reescrito"$json$::jsonb),
  ('es', 'gate.confirm.complete', $json$"Completar la solicitud"$json$::jsonb),
  ('es', 'gate.confirm.completeHint', $json$"Escribe lo que faltó; la portería lo lee junto con tu solicitud."$json$::jsonb),
  ('es', 'source.gate', $json$"la portería"$json$::jsonb),
  ('es', 'whatsNew.item.followUps.title', $json$"La continuación conserva el pase de la solicitud que continúa"$json$::jsonb),
  ('es', 'whatsNew.item.followUps.detail', $json$"Un mensaje corto justo después de una respuesta, como \"adelante\", \"impleméntalo\" o \"sigue dando error\", ahora se lee como parte de la conversación: conserva el veredicto de la portería de la solicitud que continúa y puede ir al modo build en lugar de convertirse en otra pregunta. Con el Jev activado, la portería también lee los últimos mensajes del chat."$json$::jsonb),
  ('es', 'whatsNew.item.gateAsks.title', $json$"La portería te pregunta ella misma, antes de que corra cualquier agente"$json$::jsonb),
  ('es', 'whatsNew.item.gateAsks.detail', $json$"Cuando una solicitud se libera con reservas, la portería ya no paga una sesión de agente solo para hacer una pregunta. Muestra lo que falta y ofrece tres salidas: enviar tal cual, enviar la versión que JayV reescribió con instrucciones para los huecos, o completar la solicitud. Las dos primeras van directo al agente y pueden construir."$json$::jsonb),
  ('zh-CN', 'entry.note.ask', $json$"有保留地放行：门房会在调用智能体之前先问你。"$json$::jsonb),
  ('zh-CN', 'entry.note.confirmed', $json$"由你放行：在门房询问后发送。"$json$::jsonb),
  ('zh-CN', 'gate.confirm', $json$"门房在调用任何智能体之前拦住了这个请求：{score}/100（{scope} 需要 {demand}）。"$json$::jsonb),
  ('zh-CN', 'gate.confirm.choose', $json$"原样发送，发送 JayV 为缺失部分补充了指示的改写版本，或补全这个请求。"$json$::jsonb),
  ('zh-CN', 'gate.confirm.picked', $json$"{choice}。"$json$::jsonb),
  ('zh-CN', 'gate.confirm.option.send_as_is', $json$"原样发送"$json$::jsonb),
  ('zh-CN', 'gate.confirm.option.send_rewritten', $json$"发送改写版"$json$::jsonb),
  ('zh-CN', 'gate.confirm.complete', $json$"补全请求"$json$::jsonb),
  ('zh-CN', 'gate.confirm.completeHint', $json$"写下缺少的内容；门房会把它和你的请求一起阅读。"$json$::jsonb),
  ('zh-CN', 'source.gate', $json$"门房"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.followUps.title', $json$"后续消息沿用它所延续的请求的放行结果"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.followUps.detail', $json$"回答之后紧接着的简短消息，例如“继续”“实现吧”或“还是报错”，现在会被当作对话的一部分：它沿用所延续请求的门房判定，可以进入构建模式，而不是又变成一个问题。开启 Jev 时，门房也会读取聊天的最近几条消息。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.gateAsks.title', $json$"门房亲自询问你，在任何智能体运行之前"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.gateAsks.detail', $json$"当请求被有保留地放行时，门房不再为了提一个问题而花费一次智能体会话。它会显示缺少什么，并提供三个选择：原样发送、发送 JayV 为缺口补充了指示的改写版，或补全请求。前两个会直接交给智能体，并且可以构建。"$json$::jsonb),
  ('hi', 'entry.note.ask', $json$"शर्त के साथ अनुमति: गेटहाउस किसी एजेंट को बुलाने से पहले आपसे पूछता है।"$json$::jsonb),
  ('hi', 'entry.note.confirmed', $json$"आपने अनुमति दी: गेटहाउस के पूछने के बाद भेजा गया।"$json$::jsonb),
  ('hi', 'gate.confirm', $json$"गेटहाउस ने किसी भी एजेंट को बुलाने से पहले इस अनुरोध को रोका: 100 में से {score} ({scope} के लिए {demand} चाहिए)।"$json$::jsonb),
  ('hi', 'gate.confirm.choose', $json$"जैसा लिखा है वैसा भेजें, JayV का वह संस्करण भेजें जिसमें कमी वाली बातों के निर्देश जोड़े गए हैं, या अनुरोध पूरा करें।"$json$::jsonb),
  ('hi', 'gate.confirm.picked', $json$"{choice}।"$json$::jsonb),
  ('hi', 'gate.confirm.option.send_as_is', $json$"जैसा है वैसा भेजें"$json$::jsonb),
  ('hi', 'gate.confirm.option.send_rewritten', $json$"दोबारा लिखा हुआ भेजें"$json$::jsonb),
  ('hi', 'gate.confirm.complete', $json$"अनुरोध पूरा करें"$json$::jsonb),
  ('hi', 'gate.confirm.completeHint', $json$"जो कमी थी वह लिखें; गेटहाउस उसे आपके अनुरोध के साथ पढ़ेगा।"$json$::jsonb),
  ('hi', 'source.gate', $json$"गेटहाउस"$json$::jsonb),
  ('hi', 'whatsNew.item.followUps.title', $json$"आगे का संदेश उसी अनुरोध की अनुमति रखता है जिसे वह आगे बढ़ाता है"$json$::jsonb),
  ('hi', 'whatsNew.item.followUps.detail', $json$"किसी जवाब के तुरंत बाद आने वाला छोटा संदेश, जैसे \"आगे बढ़ो\", \"इसे लागू करो\" या \"अब भी त्रुटि है\", अब बातचीत का हिस्सा माना जाता है: वह जिस अनुरोध को आगे बढ़ाता है उसका गेटहाउस फ़ैसला बनाए रखता है और एक और सवाल बनने के बजाय बिल्ड मोड में जा सकता है। Jev चालू होने पर गेटहाउस चैट के आख़िरी संदेश भी पढ़ता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.gateAsks.title', $json$"गेटहाउस ख़ुद आपसे पूछता है, किसी भी एजेंट के चलने से पहले"$json$::jsonb),
  ('hi', 'whatsNew.item.gateAsks.detail', $json$"जब कोई अनुरोध शर्त के साथ पास होता है, तो गेटहाउस अब सिर्फ़ एक सवाल पूछने के लिए एजेंट सत्र का ख़र्च नहीं करता। वह बताता है कि क्या कमी है और तीन रास्ते देता है: जैसा लिखा है वैसा भेजें, JayV का वह संस्करण भेजें जिसमें कमियों के निर्देश जोड़े गए हैं, या अनुरोध पूरा करें। पहले दो सीधे एजेंट के पास जाते हैं और बिल्ड कर सकते हैं।"$json$::jsonb),
  ('ar', 'entry.note.ask', $json$"مسموح بتحفظ: تسألك البوابة قبل استدعاء أي وكيل."$json$::jsonb),
  ('ar', 'entry.note.confirmed', $json$"سمحت به أنت: أُرسل بعد أن سألت البوابة."$json$::jsonb),
  ('ar', 'gate.confirm', $json$"أوقفت البوابة هذا الطلب قبل استدعاء أي وكيل: {score} من 100 (يتطلب {scope} الدرجة {demand})."$json$::jsonb),
  ('ar', 'gate.confirm.choose', $json$"أرسله كما هو، أو أرسل النسخة التي أعاد JayV كتابتها مع تعليمات لما ينقص، أو أكمل الطلب."$json$::jsonb),
  ('ar', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('ar', 'gate.confirm.option.send_as_is', $json$"إرسال كما هو"$json$::jsonb),
  ('ar', 'gate.confirm.option.send_rewritten', $json$"إرسال النسخة المعاد كتابتها"$json$::jsonb),
  ('ar', 'gate.confirm.complete', $json$"إكمال الطلب"$json$::jsonb),
  ('ar', 'gate.confirm.completeHint', $json$"اكتب ما كان ناقصًا؛ ستقرؤه البوابة مع طلبك."$json$::jsonb),
  ('ar', 'source.gate', $json$"البوابة"$json$::jsonb),
  ('ar', 'whatsNew.item.followUps.title', $json$"الرسالة اللاحقة تحتفظ بإذن الطلب الذي تتابعه"$json$::jsonb),
  ('ar', 'whatsNew.item.followUps.detail', $json$"الرسالة القصيرة التي تأتي مباشرة بعد إجابة، مثل \"تابع\" أو \"نفّذه\" أو \"ما زال الخطأ قائمًا\"، تُقرأ الآن كجزء من المحادثة: تحتفظ بحكم البوابة للطلب الذي تتابعه، ويمكن أن تنتقل إلى وضع البناء بدل أن تتحول إلى سؤال آخر. عند تفعيل Jev، تقرأ البوابة أيضًا آخر رسائل المحادثة."$json$::jsonb),
  ('ar', 'whatsNew.item.gateAsks.title', $json$"البوابة تسألك بنفسها قبل تشغيل أي وكيل"$json$::jsonb),
  ('ar', 'whatsNew.item.gateAsks.detail', $json$"عندما يُسمح بطلب مع تحفظ، لم تعد البوابة تدفع جلسة وكيل لمجرد طرح سؤال. تعرض ما ينقص وتقدّم ثلاثة خيارات: الإرسال كما هو، أو إرسال النسخة التي أعاد JayV كتابتها مع تعليمات للفجوات، أو إكمال الطلب. الخياران الأولان يذهبان مباشرة إلى الوكيل ويمكنهما البناء."$json$::jsonb),
  ('fr', 'entry.note.ask', $json$"Autorisé avec réserve : le poste de garde vous pose la question avant d’appeler un agent."$json$::jsonb),
  ('fr', 'entry.note.confirmed', $json$"Autorisé par vous : envoyé après la question du poste de garde."$json$::jsonb),
  ('fr', 'gate.confirm', $json$"Le poste de garde a retenu cette demande avant d’appeler un agent : {score} sur 100 ({scope} demande {demand})."$json$::jsonb),
  ('fr', 'gate.confirm.choose', $json$"Envoyez-la telle quelle, envoyez la version réécrite par JayV avec des consignes pour ce qui manque, ou complétez la demande."$json$::jsonb),
  ('fr', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('fr', 'gate.confirm.option.send_as_is', $json$"Envoyer tel quel"$json$::jsonb),
  ('fr', 'gate.confirm.option.send_rewritten', $json$"Envoyer réécrit"$json$::jsonb),
  ('fr', 'gate.confirm.complete', $json$"Compléter la demande"$json$::jsonb),
  ('fr', 'gate.confirm.completeHint', $json$"Écrivez ce qui manquait ; le poste de garde le lit avec votre demande."$json$::jsonb),
  ('fr', 'source.gate', $json$"le poste de garde"$json$::jsonb),
  ('fr', 'whatsNew.item.followUps.title', $json$"Une relance garde l’autorisation de la demande qu’elle prolonge"$json$::jsonb),
  ('fr', 'whatsNew.item.followUps.detail', $json$"Un message court juste après une réponse, comme « vas-y », « implémente-le » ou « ça plante toujours », est désormais lu comme faisant partie de la conversation : il garde le verdict du poste de garde de la demande qu’il prolonge et peut passer en mode build au lieu de devenir une nouvelle question. Avec le Jev activé, le poste de garde lit aussi les derniers messages du chat."$json$::jsonb),
  ('fr', 'whatsNew.item.gateAsks.title', $json$"Le poste de garde vous pose lui-même la question, avant qu’un agent ne tourne"$json$::jsonb),
  ('fr', 'whatsNew.item.gateAsks.detail', $json$"Quand une demande est autorisée avec réserve, le poste de garde ne paie plus une session d’agent juste pour poser une question. Il montre ce qui manque et propose trois issues : envoyer tel quel, envoyer la version réécrite par JayV avec des consignes pour les lacunes, ou compléter la demande. Les deux premières vont directement à l’agent, et peuvent construire."$json$::jsonb),
  ('ru', 'entry.note.ask', $json$"Пропущено с оговоркой: проходная спросит вас, прежде чем вызвать агента."$json$::jsonb),
  ('ru', 'entry.note.confirmed', $json$"Пропущено вами: отправлено после вопроса проходной."$json$::jsonb),
  ('ru', 'gate.confirm', $json$"Проходная задержала этот запрос до вызова агента: {score} из 100 (для «{scope}» нужно {demand})."$json$::jsonb),
  ('ru', 'gate.confirm.choose', $json$"Отправьте как есть, отправьте версию, переписанную JayV с указаниями по недостающему, или дополните запрос."$json$::jsonb),
  ('ru', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('ru', 'gate.confirm.option.send_as_is', $json$"Отправить как есть"$json$::jsonb),
  ('ru', 'gate.confirm.option.send_rewritten', $json$"Отправить переписанное"$json$::jsonb),
  ('ru', 'gate.confirm.complete', $json$"Дополнить запрос"$json$::jsonb),
  ('ru', 'gate.confirm.completeHint', $json$"Напишите, чего не хватало; проходная прочитает это вместе с вашим запросом."$json$::jsonb),
  ('ru', 'source.gate', $json$"проходная"$json$::jsonb),
  ('ru', 'whatsNew.item.followUps.title', $json$"Продолжение сохраняет пропуск запроса, который оно продолжает"$json$::jsonb),
  ('ru', 'whatsNew.item.followUps.detail', $json$"Короткое сообщение сразу после ответа, например «давай», «реализуй» или «всё ещё ошибка», теперь читается как часть разговора: оно сохраняет вердикт проходной для запроса, который продолжает, и может уйти в режим сборки, а не превратиться в ещё один вопрос. С включённым Jev проходная также читает последние сообщения чата."$json$::jsonb),
  ('ru', 'whatsNew.item.gateAsks.title', $json$"Проходная сама задаёт вопрос, ещё до запуска агента"$json$::jsonb),
  ('ru', 'whatsNew.item.gateAsks.detail', $json$"Когда запрос пропущен с оговоркой, проходная больше не тратит сессию агента только на то, чтобы задать вопрос. Она показывает, чего не хватает, и предлагает три варианта: отправить как есть, отправить версию, переписанную JayV с указаниями по пробелам, или дополнить запрос. Первые два сразу уходят агенту и могут собирать."$json$::jsonb),
  ('ja', 'entry.note.ask', $json$"条件付きで許可：エージェントを呼ぶ前にゲートがあなたに確認します。"$json$::jsonb),
  ('ja', 'entry.note.confirmed', $json$"あなたが許可：ゲートの確認後に送信されました。"$json$::jsonb),
  ('ja', 'gate.confirm', $json$"ゲートはエージェントを呼ぶ前にこのリクエストを止めました：100点中{score}点（{scope}には{demand}点が必要です）。"$json$::jsonb),
  ('ja', 'gate.confirm.choose', $json$"そのまま送るか、足りない点への指示を JayV が加えて書き直した版を送るか、リクエストを補ってください。"$json$::jsonb),
  ('ja', 'gate.confirm.picked', $json$"{choice}。"$json$::jsonb),
  ('ja', 'gate.confirm.option.send_as_is', $json$"そのまま送る"$json$::jsonb),
  ('ja', 'gate.confirm.option.send_rewritten', $json$"書き直した版を送る"$json$::jsonb),
  ('ja', 'gate.confirm.complete', $json$"リクエストを補う"$json$::jsonb),
  ('ja', 'gate.confirm.completeHint', $json$"足りなかった点を書いてください。ゲートはリクエストと合わせて読みます。"$json$::jsonb),
  ('ja', 'source.gate', $json$"ゲート"$json$::jsonb),
  ('ja', 'whatsNew.item.followUps.title', $json$"続きのメッセージは元のリクエストの通過判定を引き継ぎます"$json$::jsonb),
  ('ja', 'whatsNew.item.followUps.detail', $json$"回答の直後の短いメッセージ（「進めて」「実装して」「まだエラーが出る」など）は、会話の一部として読まれるようになりました。続きとなるリクエストのゲート判定を引き継ぐので、また質問になる代わりにビルドモードへ進めます。Jev が有効なときは、ゲートはチャットの直近のメッセージも読みます。"$json$::jsonb),
  ('ja', 'whatsNew.item.gateAsks.title', $json$"エージェントが動く前に、ゲート自身が確認します"$json$::jsonb),
  ('ja', 'whatsNew.item.gateAsks.detail', $json$"条件付きで許可されたリクエストのために、ゲートが質問するだけのエージェントセッションを使うことはなくなりました。足りない点を示し、3つの選択肢を出します。そのまま送る、JayV が不足点への指示を加えて書き直した版を送る、またはリクエストを補う。最初の2つはそのままエージェントに渡り、ビルドもできます。"$json$::jsonb),
  ('de', 'entry.note.ask', $json$"Mit Vorbehalt freigegeben: Das Pförtnerhaus fragt dich, bevor es einen Agenten aufruft."$json$::jsonb),
  ('de', 'entry.note.confirmed', $json$"Von dir freigegeben: gesendet, nachdem das Pförtnerhaus gefragt hat."$json$::jsonb),
  ('de', 'gate.confirm', $json$"Das Pförtnerhaus hat diese Anfrage angehalten, bevor ein Agent aufgerufen wurde: {score} von 100 ({scope} verlangt {demand})."$json$::jsonb),
  ('de', 'gate.confirm.choose', $json$"Sende sie so, wie sie ist, sende die von JayV umgeschriebene Fassung mit Anweisungen für das Fehlende, oder ergänze die Anfrage."$json$::jsonb),
  ('de', 'gate.confirm.picked', $json$"{choice}."$json$::jsonb),
  ('de', 'gate.confirm.option.send_as_is', $json$"So senden"$json$::jsonb),
  ('de', 'gate.confirm.option.send_rewritten', $json$"Umgeschrieben senden"$json$::jsonb),
  ('de', 'gate.confirm.complete', $json$"Anfrage ergänzen"$json$::jsonb),
  ('de', 'gate.confirm.completeHint', $json$"Schreib, was gefehlt hat; das Pförtnerhaus liest es zusammen mit deiner Anfrage."$json$::jsonb),
  ('de', 'source.gate', $json$"das Pförtnerhaus"$json$::jsonb),
  ('de', 'whatsNew.item.followUps.title', $json$"Folgenachrichten behalten die Freigabe der Anfrage, die sie fortsetzen"$json$::jsonb),
  ('de', 'whatsNew.item.followUps.detail', $json$"Eine kurze Nachricht direkt nach einer Antwort, etwa „mach weiter“, „setz es um“ oder „geht immer noch nicht“, wird jetzt als Teil des Gesprächs gelesen: Sie behält das Urteil des Pförtnerhauses für die Anfrage, die sie fortsetzt, und kann in den Build-Modus gehen, statt zur nächsten Frage zu werden. Mit eingeschaltetem Jev liest das Pförtnerhaus auch die letzten Nachrichten des Chats."$json$::jsonb),
  ('de', 'whatsNew.item.gateAsks.title', $json$"Das Pförtnerhaus fragt selbst, bevor ein Agent läuft"$json$::jsonb),
  ('de', 'whatsNew.item.gateAsks.detail', $json$"Wird eine Anfrage mit Vorbehalt freigegeben, bezahlt das Pförtnerhaus keine Agentensitzung mehr nur für eine Rückfrage. Es zeigt, was fehlt, und bietet drei Wege: so senden, die von JayV umgeschriebene Fassung mit Anweisungen für die Lücken senden oder die Anfrage ergänzen. Die ersten beiden gehen direkt an den Agenten und können bauen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
