-- v0.36.0: código enxuto, índice de símbolos, mapa do projeto e ferramentas
-- de símbolos para o Claude Code.
--
-- O interruptor "Código enxuto no modo build" no painel do nível
-- (`expertise.lean*`), a opção do Claude que liga o servidor `jayv mcp`
-- (`claude.symbols*`) e os itens da janela "Novidades" desta versão
-- (`whatsNew.item.<id>.*`). A escolha do código enxuto é gravada como a chave
-- `lean_code` de `account_settings`, que já sincroniza chave e valor.
--
-- Só traduções: nenhuma tabela, coluna ou regra muda.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'expertise.lean', $json$"Código enxuto no modo build"$json$::jsonb),
  ('pt-BR', 'expertise.lean.hint', $json$"Pede ao agente o mínimo de código que resolve o pedido, reaproveitando o que a linguagem, a plataforma ou uma biblioteca já instalada fazem. Validação, tratamento de erro, segurança e acessibilidade nunca são cortados. Starter e Júnior recebem a versão leve, que só aponta o caminho mais simples."$json$::jsonb),
  ('pt-BR', 'expertise.lean.on', $json$"Código enxuto ligado. Vale a partir do próximo pedido."$json$::jsonb),
  ('pt-BR', 'expertise.lean.off', $json$"Código enxuto desligado. Vale a partir do próximo pedido."$json$::jsonb),
  ('pt-BR', 'claude.symbols', $json$"Ferramentas de símbolos do JayV"$json$::jsonb),
  ('pt-BR', 'claude.symbols.hint', $json$"Deixa o Claude perguntar ao índice de símbolos local do JayV onde algo é definido, quem usa e o que uma mudança afeta, em vez de vasculhar a pasta. As descrições das ferramentas custam algumas centenas de tokens por sessão: rode jayv bench para ver se compensa no seu projeto."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.leanCode.title', $json$"Menos código no modo build"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.leanCode.detail', $json$"No modo build, o agente agora confere se o código precisa existir e reaproveita o que a linguagem, a plataforma ou uma biblioteca instalada já fazem antes de escrever algo novo. Validação, tratamento de erro, segurança e acessibilidade nunca são cortados. Starter e Júnior recebem uma versão mais leve, e dá para desligar em Seu nível."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.symbolIndex.title', $json$"Um índice de símbolos do seu projeto"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.symbolIndex.detail', $json$"O JayV agora lê onde cada função, tipo e classe é definido nos arquivos Rust, TypeScript, JavaScript, Python e Go, no seu computador e sem gastar tokens. O mapa de arquivos que vai aos agentes traz as definições do arquivo inteiro com a linha de cada uma e quais arquivos cada um usa ou o usam, e a busca de arquivos dá mais peso aos nomes que um arquivo define."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectMap.title', $json$"Um mapa do projeto no começo de cada sessão do agente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectMap.detail', $json$"Em projetos com 80 arquivos ou mais, o agente que começa uma sessão nova recebe um mapa curto montado a partir do índice de símbolos: as pastas principais, os arquivos de que mais outros dependem e os pontos de entrada. Uma sessão retomada já o tem e não o recebe de novo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.symbolTools.title', $json$"Ferramentas de símbolos para o Claude Code (opcional)"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.symbolTools.detail', $json$"Uma opção nova nas configurações do Claude Code deixa o Claude perguntar ao índice de símbolos do JayV onde algo é definido, quem usa e o que uma mudança afeta, em vez de vasculhar a pasta. Ela vem desligada porque as descrições das ferramentas custam tokens em toda sessão; rode jayv bench para ver se compensa no seu projeto."$json$::jsonb),
  ('en', 'expertise.lean', $json$"Lean code in build mode"$json$::jsonb),
  ('en', 'expertise.lean.hint', $json$"Asks the agent to write the least code that solves the request, reusing what the language, the platform or an installed library already does. Validation, error handling, security and accessibility are never cut. Starter and Junior get the lighter version, which only points out the simpler path."$json$::jsonb),
  ('en', 'expertise.lean.on', $json$"Lean code turned on. It applies from the next request."$json$::jsonb),
  ('en', 'expertise.lean.off', $json$"Lean code turned off. It applies from the next request."$json$::jsonb),
  ('en', 'claude.symbols', $json$"JayV symbol tools"$json$::jsonb),
  ('en', 'claude.symbols.hint', $json$"Lets Claude ask JayV's local symbol index where something is defined, who uses it and what a change affects, instead of searching the folder. The tool descriptions cost a few hundred tokens per session: run jayv bench to see whether they pay off in your project."$json$::jsonb),
  ('en', 'whatsNew.item.leanCode.title', $json$"Less code in build mode"$json$::jsonb),
  ('en', 'whatsNew.item.leanCode.detail', $json$"In build mode the agent now checks whether the code needs to exist and reuses what the language, the platform or an installed library already does before writing anything new. Validation, error handling, security and accessibility are never cut. Starter and Junior get a lighter version, and you can turn it off under Your level."$json$::jsonb),
  ('en', 'whatsNew.item.symbolIndex.title', $json$"A symbol index of your project"$json$::jsonb),
  ('en', 'whatsNew.item.symbolIndex.detail', $json$"JayV now reads where each function, type and class is defined in Rust, TypeScript, JavaScript, Python and Go files, on your computer and without spending tokens. The file map sent to agents lists the definitions of the whole file with their line, and which files each one uses or is used by, and file search gives more weight to names a file defines."$json$::jsonb),
  ('en', 'whatsNew.item.projectMap.title', $json$"A project map at the start of each agent session"$json$::jsonb),
  ('en', 'whatsNew.item.projectMap.detail', $json$"In projects with 80 files or more, an agent that starts a new session gets a short map built from the symbol index: the main folders, the files most others depend on and the entry points. A resumed session already has it and does not get it again."$json$::jsonb),
  ('en', 'whatsNew.item.symbolTools.title', $json$"Symbol tools for Claude Code (optional)"$json$::jsonb),
  ('en', 'whatsNew.item.symbolTools.detail', $json$"A new option in the Claude Code settings lets Claude ask JayV's symbol index where something is defined, who uses it and what a change affects, instead of searching the folder. It is off by default because the tool descriptions cost tokens in every session; run jayv bench to see whether it pays off in your project."$json$::jsonb),
  ('es', 'expertise.lean', $json$"Código mínimo en modo build"$json$::jsonb),
  ('es', 'expertise.lean.hint', $json$"Pide al agente el mínimo de código que resuelve la solicitud, reutilizando lo que el lenguaje, la plataforma o una biblioteca ya instalada hacen. La validación, el manejo de errores, la seguridad y la accesibilidad nunca se recortan. Starter y Junior reciben la versión ligera, que solo señala el camino más simple."$json$::jsonb),
  ('es', 'expertise.lean.on', $json$"Código mínimo activado. Se aplica desde la próxima solicitud."$json$::jsonb),
  ('es', 'expertise.lean.off', $json$"Código mínimo desactivado. Se aplica desde la próxima solicitud."$json$::jsonb),
  ('es', 'claude.symbols', $json$"Herramientas de símbolos de JayV"$json$::jsonb),
  ('es', 'claude.symbols.hint', $json$"Permite a Claude preguntar al índice de símbolos local de JayV dónde se define algo, quién lo usa y qué afecta un cambio, en lugar de buscar en la carpeta. Las descripciones de las herramientas cuestan unos cientos de tokens por sesión: ejecuta jayv bench para ver si compensa en tu proyecto."$json$::jsonb),
  ('es', 'whatsNew.item.leanCode.title', $json$"Menos código en modo build"$json$::jsonb),
  ('es', 'whatsNew.item.leanCode.detail', $json$"En modo build, el agente ahora comprueba si el código necesita existir y reutiliza lo que el lenguaje, la plataforma o una biblioteca instalada ya hacen antes de escribir algo nuevo. La validación, el manejo de errores, la seguridad y la accesibilidad nunca se recortan. Starter y Junior reciben una versión más ligera, y puedes desactivarlo en Tu nivel."$json$::jsonb),
  ('es', 'whatsNew.item.symbolIndex.title', $json$"Un índice de símbolos de tu proyecto"$json$::jsonb),
  ('es', 'whatsNew.item.symbolIndex.detail', $json$"JayV ahora lee dónde se define cada función, tipo y clase en los archivos Rust, TypeScript, JavaScript, Python y Go, en tu computadora y sin gastar tokens. El mapa de archivos que va a los agentes trae las definiciones de todo el archivo con su línea y qué archivos usa cada uno o lo usan, y la búsqueda de archivos da más peso a los nombres que define un archivo."$json$::jsonb),
  ('es', 'whatsNew.item.projectMap.title', $json$"Un mapa del proyecto al inicio de cada sesión del agente"$json$::jsonb),
  ('es', 'whatsNew.item.projectMap.detail', $json$"En proyectos con 80 archivos o más, el agente que inicia una sesión nueva recibe un mapa breve construido a partir del índice de símbolos: las carpetas principales, los archivos de los que más dependen los demás y los puntos de entrada. Una sesión reanudada ya lo tiene y no lo recibe de nuevo."$json$::jsonb),
  ('es', 'whatsNew.item.symbolTools.title', $json$"Herramientas de símbolos para Claude Code (opcional)"$json$::jsonb),
  ('es', 'whatsNew.item.symbolTools.detail', $json$"Una opción nueva en la configuración de Claude Code permite a Claude preguntar al índice de símbolos de JayV dónde se define algo, quién lo usa y qué afecta un cambio, en lugar de buscar en la carpeta. Viene desactivada porque las descripciones de las herramientas cuestan tokens en cada sesión; ejecuta jayv bench para ver si compensa en tu proyecto."$json$::jsonb),
  ('zh-CN', 'expertise.lean', $json$"构建模式下精简代码"$json$::jsonb),
  ('zh-CN', 'expertise.lean.hint', $json$"要求代理用最少的代码完成请求，优先复用语言、平台或已安装库已有的功能。输入校验、错误处理、安全和无障碍永远不会被删减。Starter 和 Junior 使用轻量版本，只会指出更简单的做法。"$json$::jsonb),
  ('zh-CN', 'expertise.lean.on', $json$"已开启精简代码。从下一个请求开始生效。"$json$::jsonb),
  ('zh-CN', 'expertise.lean.off', $json$"已关闭精简代码。从下一个请求开始生效。"$json$::jsonb),
  ('zh-CN', 'claude.symbols', $json$"JayV 符号工具"$json$::jsonb),
  ('zh-CN', 'claude.symbols.hint', $json$"让 Claude 向 JayV 的本地符号索引查询某个东西在哪里定义、谁在使用它、修改会影响什么，而不是搜索整个文件夹。工具描述每个会话会消耗几百个 token：运行 jayv bench 看看在你的项目中是否划算。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.leanCode.title', $json$"构建模式下写更少的代码"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.leanCode.detail', $json$"在构建模式下，代理现在会先确认代码是否有必要存在，并在编写新代码之前复用语言、平台或已安装库已有的功能。输入校验、错误处理、安全和无障碍永远不会被删减。Starter 和 Junior 使用更轻的版本，你也可以在“你的级别”中关闭它。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.symbolIndex.title', $json$"项目的符号索引"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.symbolIndex.detail', $json$"JayV 现在会在你的电脑上读取 Rust、TypeScript、JavaScript、Python 和 Go 文件中每个函数、类型和类的定义位置，不消耗 token。发送给代理的文件地图会列出整个文件的定义及其行号，以及每个文件使用了哪些文件、被哪些文件使用；文件搜索也会更重视文件中定义的名称。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectMap.title', $json$"每次代理会话开始时的项目地图"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectMap.detail', $json$"在 80 个文件及以上的项目中，开始新会话的代理会收到一份根据符号索引生成的简短地图：主要文件夹、被最多文件依赖的文件以及入口文件。恢复的会话已经有这份地图，不会再次收到。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.symbolTools.title', $json$"Claude Code 的符号工具（可选）"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.symbolTools.detail', $json$"Claude Code 设置中的新选项让 Claude 向 JayV 的符号索引查询某个东西在哪里定义、谁在使用它、修改会影响什么，而不是搜索整个文件夹。它默认关闭，因为工具描述在每个会话中都会消耗 token；运行 jayv bench 看看在你的项目中是否划算。"$json$::jsonb),
  ('hi', 'expertise.lean', $json$"बिल्ड मोड में कम कोड"$json$::jsonb),
  ('hi', 'expertise.lean.hint', $json$"एजेंट से अनुरोध हल करने के लिए कम से कम कोड लिखने को कहता है, और वही दोबारा इस्तेमाल करता है जो भाषा, प्लेटफ़ॉर्म या पहले से इंस्टॉल लाइब्रेरी करती है। वैलिडेशन, एरर हैंडलिंग, सुरक्षा और सुलभता कभी नहीं हटाए जाते। Starter और Junior को हल्का संस्करण मिलता है, जो सिर्फ़ आसान रास्ता बताता है।"$json$::jsonb),
  ('hi', 'expertise.lean.on', $json$"कम कोड चालू किया गया। यह अगले अनुरोध से लागू होगा।"$json$::jsonb),
  ('hi', 'expertise.lean.off', $json$"कम कोड बंद किया गया। यह अगले अनुरोध से लागू होगा।"$json$::jsonb),
  ('hi', 'claude.symbols', $json$"JayV सिंबल टूल"$json$::jsonb),
  ('hi', 'claude.symbols.hint', $json$"Claude को फ़ोल्डर खोजने के बजाय JayV के लोकल सिंबल इंडेक्स से पूछने देता है कि कोई चीज़ कहाँ परिभाषित है, उसे कौन इस्तेमाल करता है और किसी बदलाव का क्या असर होगा। टूल के विवरण हर सेशन में कुछ सौ टोकन लेते हैं: अपने प्रोजेक्ट में फ़ायदा देखने के लिए jayv bench चलाएँ।"$json$::jsonb),
  ('hi', 'whatsNew.item.leanCode.title', $json$"बिल्ड मोड में कम कोड"$json$::jsonb),
  ('hi', 'whatsNew.item.leanCode.detail', $json$"बिल्ड मोड में एजेंट अब कुछ नया लिखने से पहले जाँचता है कि कोड की ज़रूरत है या नहीं, और वही दोबारा इस्तेमाल करता है जो भाषा, प्लेटफ़ॉर्म या इंस्टॉल लाइब्रेरी पहले से करती है। वैलिडेशन, एरर हैंडलिंग, सुरक्षा और सुलभता कभी नहीं हटाए जाते। Starter और Junior को हल्का संस्करण मिलता है, और आप इसे आपका स्तर में बंद कर सकते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.symbolIndex.title', $json$"आपके प्रोजेक्ट का सिंबल इंडेक्स"$json$::jsonb),
  ('hi', 'whatsNew.item.symbolIndex.detail', $json$"JayV अब आपके कंप्यूटर पर, बिना टोकन खर्च किए, पढ़ता है कि Rust, TypeScript, JavaScript, Python और Go फ़ाइलों में हर फ़ंक्शन, टाइप और क्लास कहाँ परिभाषित है। एजेंटों को भेजे जाने वाले फ़ाइल मैप में पूरी फ़ाइल की परिभाषाएँ उनकी लाइन के साथ होती हैं, और यह भी कि हर फ़ाइल किन फ़ाइलों को इस्तेमाल करती है या कौन उसे इस्तेमाल करता है; फ़ाइल खोज किसी फ़ाइल में परिभाषित नामों को ज़्यादा महत्व देती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.projectMap.title', $json$"हर एजेंट सेशन की शुरुआत में प्रोजेक्ट मैप"$json$::jsonb),
  ('hi', 'whatsNew.item.projectMap.detail', $json$"80 या उससे ज़्यादा फ़ाइलों वाले प्रोजेक्ट में नया सेशन शुरू करने वाले एजेंट को सिंबल इंडेक्स से बना एक छोटा मैप मिलता है: मुख्य फ़ोल्डर, वे फ़ाइलें जिन पर सबसे ज़्यादा दूसरी फ़ाइलें निर्भर हैं, और एंट्री पॉइंट। फिर से शुरू किए गए सेशन के पास यह पहले से होता है और उसे दोबारा नहीं मिलता।"$json$::jsonb),
  ('hi', 'whatsNew.item.symbolTools.title', $json$"Claude Code के लिए सिंबल टूल (वैकल्पिक)"$json$::jsonb),
  ('hi', 'whatsNew.item.symbolTools.detail', $json$"Claude Code की सेटिंग में एक नया विकल्प Claude को फ़ोल्डर खोजने के बजाय JayV के सिंबल इंडेक्स से पूछने देता है कि कोई चीज़ कहाँ परिभाषित है, उसे कौन इस्तेमाल करता है और किसी बदलाव का क्या असर होगा। यह डिफ़ॉल्ट रूप से बंद है, क्योंकि टूल के विवरण हर सेशन में टोकन लेते हैं; अपने प्रोजेक्ट में फ़ायदा देखने के लिए jayv bench चलाएँ।"$json$::jsonb),
  ('ar', 'expertise.lean', $json$"كود مختصر في وضع البناء"$json$::jsonb),
  ('ar', 'expertise.lean.hint', $json$"يطلب من الوكيل أقل قدر من الكود يحل الطلب، مع إعادة استخدام ما تقدمه اللغة أو المنصة أو مكتبة مثبتة بالفعل. لا يتم أبدًا حذف التحقق من المدخلات أو معالجة الأخطاء أو الأمان أو إمكانية الوصول. يحصل Starter وJunior على النسخة الخفيفة التي تكتفي بالإشارة إلى الطريق الأبسط."$json$::jsonb),
  ('ar', 'expertise.lean.on', $json$"تم تشغيل الكود المختصر. يسري من الطلب التالي."$json$::jsonb),
  ('ar', 'expertise.lean.off', $json$"تم إيقاف الكود المختصر. يسري من الطلب التالي."$json$::jsonb),
  ('ar', 'claude.symbols', $json$"أدوات الرموز في JayV"$json$::jsonb),
  ('ar', 'claude.symbols.hint', $json$"يتيح لـ Claude أن يسأل فهرس الرموز المحلي في JayV أين يُعرَّف شيء ما ومن يستخدمه وما الذي يتأثر بالتغيير، بدلًا من البحث في المجلد. أوصاف الأدوات تكلف بضع مئات من الرموز في كل جلسة: شغّل jayv bench لترى إن كانت مجدية في مشروعك."$json$::jsonb),
  ('ar', 'whatsNew.item.leanCode.title', $json$"كود أقل في وضع البناء"$json$::jsonb),
  ('ar', 'whatsNew.item.leanCode.detail', $json$"في وضع البناء، يتحقق الوكيل الآن مما إذا كان الكود ضروريًا، ويعيد استخدام ما تقدمه اللغة أو المنصة أو مكتبة مثبتة قبل كتابة أي شيء جديد. لا يتم أبدًا حذف التحقق من المدخلات أو معالجة الأخطاء أو الأمان أو إمكانية الوصول. يحصل Starter وJunior على نسخة أخف، ويمكنك إيقافه من مستواك."$json$::jsonb),
  ('ar', 'whatsNew.item.symbolIndex.title', $json$"فهرس رموز لمشروعك"$json$::jsonb),
  ('ar', 'whatsNew.item.symbolIndex.detail', $json$"يقرأ JayV الآن أين تُعرَّف كل دالة ونوع وصنف في ملفات Rust وTypeScript وJavaScript وPython وGo، على جهازك ودون إنفاق رموز. خريطة الملفات المرسلة إلى الوكلاء تعرض تعريفات الملف كاملًا مع سطر كل منها، والملفات التي يستخدمها كل ملف أو تستخدمه، ويعطي البحث في الملفات وزنًا أكبر للأسماء التي يعرّفها الملف."$json$::jsonb),
  ('ar', 'whatsNew.item.projectMap.title', $json$"خريطة للمشروع في بداية كل جلسة للوكيل"$json$::jsonb),
  ('ar', 'whatsNew.item.projectMap.detail', $json$"في المشاريع التي تضم 80 ملفًا أو أكثر، يتلقى الوكيل الذي يبدأ جلسة جديدة خريطة قصيرة مبنية من فهرس الرموز: المجلدات الرئيسية، والملفات التي تعتمد عليها أغلب الملفات الأخرى، ونقاط الدخول. الجلسة المستأنفة لديها الخريطة بالفعل ولا تتلقاها مرة أخرى."$json$::jsonb),
  ('ar', 'whatsNew.item.symbolTools.title', $json$"أدوات الرموز لـ Claude Code (اختيارية)"$json$::jsonb),
  ('ar', 'whatsNew.item.symbolTools.detail', $json$"خيار جديد في إعدادات Claude Code يتيح لـ Claude أن يسأل فهرس الرموز في JayV أين يُعرَّف شيء ما ومن يستخدمه وما الذي يتأثر بالتغيير، بدلًا من البحث في المجلد. يأتي معطلًا افتراضيًا لأن أوصاف الأدوات تكلف رموزًا في كل جلسة؛ شغّل jayv bench لترى إن كان مجديًا في مشروعك."$json$::jsonb),
  ('fr', 'expertise.lean', $json$"Code minimal en mode build"$json$::jsonb),
  ('fr', 'expertise.lean.hint', $json$"Demande à l'agent le minimum de code qui résout la demande, en réutilisant ce que le langage, la plateforme ou une bibliothèque déjà installée font. La validation, la gestion des erreurs, la sécurité et l'accessibilité ne sont jamais supprimées. Starter et Junior reçoivent la version légère, qui se contente d'indiquer la voie la plus simple."$json$::jsonb),
  ('fr', 'expertise.lean.on', $json$"Code minimal activé. Il s'applique dès la prochaine demande."$json$::jsonb),
  ('fr', 'expertise.lean.off', $json$"Code minimal désactivé. Il s'applique dès la prochaine demande."$json$::jsonb),
  ('fr', 'claude.symbols', $json$"Outils de symboles de JayV"$json$::jsonb),
  ('fr', 'claude.symbols.hint', $json$"Permet à Claude de demander à l'index de symboles local de JayV où quelque chose est défini, qui l'utilise et ce qu'un changement affecte, au lieu de fouiller le dossier. Les descriptions des outils coûtent quelques centaines de tokens par session : lancez jayv bench pour voir si cela vaut la peine dans votre projet."$json$::jsonb),
  ('fr', 'whatsNew.item.leanCode.title', $json$"Moins de code en mode build"$json$::jsonb),
  ('fr', 'whatsNew.item.leanCode.detail', $json$"En mode build, l'agent vérifie désormais si le code doit exister et réutilise ce que le langage, la plateforme ou une bibliothèque installée font déjà avant d'écrire quoi que ce soit de nouveau. La validation, la gestion des erreurs, la sécurité et l'accessibilité ne sont jamais supprimées. Starter et Junior reçoivent une version plus légère, et vous pouvez la désactiver dans Votre niveau."$json$::jsonb),
  ('fr', 'whatsNew.item.symbolIndex.title', $json$"Un index des symboles de votre projet"$json$::jsonb),
  ('fr', 'whatsNew.item.symbolIndex.detail', $json$"JayV lit désormais où chaque fonction, type et classe est défini dans les fichiers Rust, TypeScript, JavaScript, Python et Go, sur votre ordinateur et sans dépenser de tokens. La carte des fichiers envoyée aux agents liste les définitions du fichier entier avec leur ligne, ainsi que les fichiers que chacun utilise ou qui l'utilisent, et la recherche de fichiers donne plus de poids aux noms qu'un fichier définit."$json$::jsonb),
  ('fr', 'whatsNew.item.projectMap.title', $json$"Une carte du projet au début de chaque session de l'agent"$json$::jsonb),
  ('fr', 'whatsNew.item.projectMap.detail', $json$"Dans les projets de 80 fichiers ou plus, l'agent qui démarre une nouvelle session reçoit une courte carte construite à partir de l'index de symboles : les dossiers principaux, les fichiers dont dépendent le plus d'autres fichiers et les points d'entrée. Une session reprise l'a déjà et ne la reçoit pas de nouveau."$json$::jsonb),
  ('fr', 'whatsNew.item.symbolTools.title', $json$"Outils de symboles pour Claude Code (facultatif)"$json$::jsonb),
  ('fr', 'whatsNew.item.symbolTools.detail', $json$"Une nouvelle option dans les réglages de Claude Code permet à Claude de demander à l'index de symboles de JayV où quelque chose est défini, qui l'utilise et ce qu'un changement affecte, au lieu de fouiller le dossier. Elle est désactivée par défaut car les descriptions des outils coûtent des tokens à chaque session ; lancez jayv bench pour voir si cela vaut la peine dans votre projet."$json$::jsonb),
  ('ru', 'expertise.lean', $json$"Минимум кода в режиме сборки"$json$::jsonb),
  ('ru', 'expertise.lean.hint', $json$"Просит агента написать минимум кода, который решает запрос, и переиспользовать то, что уже умеют язык, платформа или установленная библиотека. Валидация, обработка ошибок, безопасность и доступность никогда не вырезаются. Starter и Junior получают облегчённую версию, которая лишь подсказывает более простой путь."$json$::jsonb),
  ('ru', 'expertise.lean.on', $json$"Минимум кода включён. Действует со следующего запроса."$json$::jsonb),
  ('ru', 'expertise.lean.off', $json$"Минимум кода выключен. Действует со следующего запроса."$json$::jsonb),
  ('ru', 'claude.symbols', $json$"Инструменты символов JayV"$json$::jsonb),
  ('ru', 'claude.symbols.hint', $json$"Позволяет Claude спрашивать у локального индекса символов JayV, где что-то определено, кто это использует и на что повлияет изменение, вместо поиска по папке. Описания инструментов стоят несколько сотен токенов за сессию: запустите jayv bench, чтобы понять, окупается ли это в вашем проекте."$json$::jsonb),
  ('ru', 'whatsNew.item.leanCode.title', $json$"Меньше кода в режиме сборки"$json$::jsonb),
  ('ru', 'whatsNew.item.leanCode.detail', $json$"В режиме сборки агент теперь проверяет, нужен ли код вообще, и переиспользует то, что уже умеют язык, платформа или установленная библиотека, прежде чем писать что-то новое. Валидация, обработка ошибок, безопасность и доступность никогда не вырезаются. Starter и Junior получают облегчённую версию, а выключить её можно в разделе Ваш уровень."$json$::jsonb),
  ('ru', 'whatsNew.item.symbolIndex.title', $json$"Индекс символов вашего проекта"$json$::jsonb),
  ('ru', 'whatsNew.item.symbolIndex.detail', $json$"JayV теперь определяет, где объявлена каждая функция, тип и класс в файлах Rust, TypeScript, JavaScript, Python и Go, прямо на вашем компьютере и без расхода токенов. Карта файлов, которую получают агенты, перечисляет определения всего файла с номерами строк и показывает, какие файлы он использует и какие используют его, а поиск файлов придаёт больший вес именам, которые файл определяет."$json$::jsonb),
  ('ru', 'whatsNew.item.projectMap.title', $json$"Карта проекта в начале каждой сессии агента"$json$::jsonb),
  ('ru', 'whatsNew.item.projectMap.detail', $json$"В проектах от 80 файлов агент, начинающий новую сессию, получает короткую карту, построенную по индексу символов: основные папки, файлы, от которых зависит больше всего других, и точки входа. Возобновлённая сессия уже её имеет и не получает повторно."$json$::jsonb),
  ('ru', 'whatsNew.item.symbolTools.title', $json$"Инструменты символов для Claude Code (необязательно)"$json$::jsonb),
  ('ru', 'whatsNew.item.symbolTools.detail', $json$"Новая опция в настройках Claude Code позволяет Claude спрашивать у индекса символов JayV, где что-то определено, кто это использует и на что повлияет изменение, вместо поиска по папке. По умолчанию она выключена, потому что описания инструментов стоят токенов в каждой сессии; запустите jayv bench, чтобы понять, окупается ли это в вашем проекте."$json$::jsonb),
  ('ja', 'expertise.lean', $json$"ビルドモードで最小限のコード"$json$::jsonb),
  ('ja', 'expertise.lean.hint', $json$"エージェントに、リクエストを解決する最小限のコードを書くよう求め、言語・プラットフォーム・インストール済みのライブラリがすでに提供している機能を再利用させます。入力検証、エラー処理、セキュリティ、アクセシビリティは決して削られません。Starter と Junior には、より簡単な方法を指摘するだけの軽いバージョンが使われます。"$json$::jsonb),
  ('ja', 'expertise.lean.on', $json$"最小限のコードをオンにしました。次のリクエストから適用されます。"$json$::jsonb),
  ('ja', 'expertise.lean.off', $json$"最小限のコードをオフにしました。次のリクエストから適用されます。"$json$::jsonb),
  ('ja', 'claude.symbols', $json$"JayV シンボルツール"$json$::jsonb),
  ('ja', 'claude.symbols.hint', $json$"フォルダーを検索する代わりに、JayV のローカルなシンボルインデックスに、何がどこで定義されているか、誰が使っているか、変更が何に影響するかを Claude が問い合わせられるようにします。ツールの説明はセッションごとに数百トークンかかります。プロジェクトで元が取れるか jayv bench で確認してください。"$json$::jsonb),
  ('ja', 'whatsNew.item.leanCode.title', $json$"ビルドモードでコードを減らす"$json$::jsonb),
  ('ja', 'whatsNew.item.leanCode.detail', $json$"ビルドモードのエージェントは、新しいコードを書く前に、そのコードが本当に必要かを確認し、言語・プラットフォーム・インストール済みのライブラリがすでに提供している機能を再利用するようになりました。入力検証、エラー処理、セキュリティ、アクセシビリティは決して削られません。Starter と Junior には軽いバージョンが使われ、「あなたのレベル」でオフにできます。"$json$::jsonb),
  ('ja', 'whatsNew.item.symbolIndex.title', $json$"プロジェクトのシンボルインデックス"$json$::jsonb),
  ('ja', 'whatsNew.item.symbolIndex.detail', $json$"JayV は、Rust、TypeScript、JavaScript、Python、Go のファイルで各関数・型・クラスがどこで定義されているかを、トークンを使わずにあなたのコンピューター上で読み取るようになりました。エージェントに送るファイルマップには、ファイル全体の定義と行番号、各ファイルが使うファイルとそのファイルを使うファイルが載り、ファイル検索ではファイルが定義する名前がより重視されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.projectMap.title', $json$"エージェントの各セッション開始時にプロジェクトマップ"$json$::jsonb),
  ('ja', 'whatsNew.item.projectMap.detail', $json$"ファイルが 80 個以上のプロジェクトでは、新しいセッションを始めるエージェントに、シンボルインデックスから作った短いマップが渡されます。主要なフォルダー、他の多くのファイルが依存しているファイル、エントリーポイントです。再開したセッションはすでに持っているので、再度は渡されません。"$json$::jsonb),
  ('ja', 'whatsNew.item.symbolTools.title', $json$"Claude Code 用シンボルツール（任意）"$json$::jsonb),
  ('ja', 'whatsNew.item.symbolTools.detail', $json$"Claude Code の設定に新しいオプションが加わり、フォルダーを検索する代わりに、何がどこで定義されているか、誰が使っているか、変更が何に影響するかを Claude が JayV のシンボルインデックスに問い合わせられます。ツールの説明はセッションごとにトークンがかかるため、デフォルトではオフです。プロジェクトで元が取れるか jayv bench で確認してください。"$json$::jsonb),
  ('de', 'expertise.lean', $json$"Schlanker Code im Build-Modus"$json$::jsonb),
  ('de', 'expertise.lean.hint', $json$"Bittet den Agenten um möglichst wenig Code, der die Anfrage löst, und nutzt wieder, was die Sprache, die Plattform oder eine bereits installierte Bibliothek schon kann. Validierung, Fehlerbehandlung, Sicherheit und Barrierefreiheit werden nie gestrichen. Starter und Junior erhalten die leichte Version, die nur auf den einfacheren Weg hinweist."$json$::jsonb),
  ('de', 'expertise.lean.on', $json$"Schlanker Code eingeschaltet. Gilt ab der nächsten Anfrage."$json$::jsonb),
  ('de', 'expertise.lean.off', $json$"Schlanker Code ausgeschaltet. Gilt ab der nächsten Anfrage."$json$::jsonb),
  ('de', 'claude.symbols', $json$"JayV-Symbolwerkzeuge"$json$::jsonb),
  ('de', 'claude.symbols.hint', $json$"Lässt Claude den lokalen Symbolindex von JayV fragen, wo etwas definiert ist, wer es nutzt und was eine Änderung betrifft, statt den Ordner zu durchsuchen. Die Werkzeugbeschreibungen kosten pro Sitzung einige hundert Tokens: Führen Sie jayv bench aus, um zu sehen, ob es sich in Ihrem Projekt lohnt."$json$::jsonb),
  ('de', 'whatsNew.item.leanCode.title', $json$"Weniger Code im Build-Modus"$json$::jsonb),
  ('de', 'whatsNew.item.leanCode.detail', $json$"Im Build-Modus prüft der Agent jetzt, ob der Code überhaupt nötig ist, und nutzt wieder, was die Sprache, die Plattform oder eine installierte Bibliothek schon kann, bevor er etwas Neues schreibt. Validierung, Fehlerbehandlung, Sicherheit und Barrierefreiheit werden nie gestrichen. Starter und Junior bekommen eine leichtere Version, und du kannst es unter Ihr Level ausschalten."$json$::jsonb),
  ('de', 'whatsNew.item.symbolIndex.title', $json$"Ein Symbolindex deines Projekts"$json$::jsonb),
  ('de', 'whatsNew.item.symbolIndex.detail', $json$"JayV liest jetzt, wo jede Funktion, jeder Typ und jede Klasse in Rust-, TypeScript-, JavaScript-, Python- und Go-Dateien definiert ist, auf deinem Computer und ohne Tokens zu verbrauchen. Die Dateikarte für die Agenten listet die Definitionen der ganzen Datei mit ihrer Zeile und welche Dateien jede nutzt oder von welchen sie genutzt wird, und die Dateisuche gewichtet Namen stärker, die eine Datei definiert."$json$::jsonb),
  ('de', 'whatsNew.item.projectMap.title', $json$"Eine Projektkarte zu Beginn jeder Agentensitzung"$json$::jsonb),
  ('de', 'whatsNew.item.projectMap.detail', $json$"In Projekten mit 80 oder mehr Dateien bekommt ein Agent, der eine neue Sitzung beginnt, eine kurze Karte aus dem Symbolindex: die wichtigsten Ordner, die Dateien, von denen die meisten anderen abhängen, und die Einstiegspunkte. Eine fortgesetzte Sitzung hat sie schon und bekommt sie nicht erneut."$json$::jsonb),
  ('de', 'whatsNew.item.symbolTools.title', $json$"Symbolwerkzeuge für Claude Code (optional)"$json$::jsonb),
  ('de', 'whatsNew.item.symbolTools.detail', $json$"Eine neue Option in den Einstellungen von Claude Code lässt Claude den Symbolindex von JayV fragen, wo etwas definiert ist, wer es nutzt und was eine Änderung betrifft, statt den Ordner zu durchsuchen. Sie ist standardmäßig aus, weil die Werkzeugbeschreibungen in jeder Sitzung Tokens kosten; führe jayv bench aus, um zu sehen, ob es sich in deinem Projekt lohnt."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
