-- App 0.87.0: o manual dos ambientes diz que a política da organização vale só no ambiente dela.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'docs.environments.summary', $json$"Seus projetos pessoais e cada organização vivem em ambientes separados. Cada um guarda seus próprios projetos, chats, notas, uso e configurações (agentes, modelos, servidores MCP, skills e permissões), então nada de um vaza para o outro. Seu perfil, idioma, tema, plano e login em duas etapas são os mesmos em todo lugar, assim como o limite do plano de cada agente. A política de uma organização (agentes permitidos, comandos bloqueados, arquivos protegidos) vale só dentro do ambiente dela."$json$::jsonb),
  ('en', 'docs.environments.summary', $json$"Your personal projects and each organization live in separate environments. Each one keeps its own projects, chats, notes, usage and settings (agents, models, MCP servers, skills and permissions), so nothing from one leaks into another. Your profile, language, theme, plan and two-factor sign-in are the same everywhere, and so is the limit of each agent's plan. An organization's policy (allowed agents, blocked commands, protected files) applies only inside its own environment."$json$::jsonb),
  ('es', 'docs.environments.summary', $json$"Tus proyectos personales y cada organización viven en entornos separados. Cada uno guarda sus propios proyectos, chats, notas, uso y ajustes (agentes, modelos, servidores MCP, skills y permisos), así que nada de uno pasa al otro. Tu perfil, idioma, tema, plan e inicio de sesión en dos pasos son los mismos en todas partes, igual que el límite del plan de cada agente. La política de una organización (agentes permitidos, comandos bloqueados, archivos protegidos) vale solo dentro de su propio entorno."$json$::jsonb),
  ('fr', 'docs.environments.summary', $json$"Vos projets personnels et chaque organisation vivent dans des environnements séparés. Chacun garde ses propres projets, chats, notes, usage et réglages (agents, modèles, serveurs MCP, skills et autorisations), donc rien de l'un ne passe dans l'autre. Votre profil, langue, thème, forfait et connexion en deux étapes sont les mêmes partout, tout comme la limite du forfait de chaque agent. La politique d'une organisation (agents autorisés, commandes bloquées, fichiers protégés) ne s'applique qu'à l'intérieur de son propre environnement."$json$::jsonb),
  ('de', 'docs.environments.summary', $json$"Deine persönlichen Projekte und jede Organisation leben in getrennten Umgebungen. Jede hält ihre eigenen Projekte, Chats, Notizen, Nutzung und Einstellungen (Agenten, Modelle, MCP-Server, Skills und Berechtigungen), sodass nichts von einer in die andere gelangt. Dein Profil, deine Sprache, dein Design, dein Tarif und die Zwei-Faktor-Anmeldung sind überall gleich, ebenso das Limit des Tarifs jedes Agenten. Die Richtlinie einer Organisation (erlaubte Agenten, gesperrte Befehle, geschützte Dateien) gilt nur innerhalb ihrer eigenen Umgebung."$json$::jsonb),
  ('ru', 'docs.environments.summary', $json$"Ваши личные проекты и каждая организация живут в отдельных средах. В каждой свои проекты, чаты, заметки, расход и настройки (агенты, модели, серверы MCP, skills и разрешения), поэтому ничто из одной не попадает в другую. Профиль, язык, тема, тариф и двухфакторный вход одинаковы везде, как и лимит тарифа каждого агента. Политика организации (разрешённые агенты, заблокированные команды, защищённые файлы) действует только внутри её собственной среды."$json$::jsonb),
  ('zh-CN', 'docs.environments.summary', $json$"你的个人项目和每个组织都在各自独立的环境中。每个环境保存自己的项目、聊天、笔记、用量和设置（代理、模型、MCP 服务器、skills 和权限），因此互不泄漏。你的资料、语言、主题、套餐和两步验证在所有环境中相同，各代理套餐的额度也是共享的。组织的策略（允许的代理、被阻止的命令、受保护的文件）只在它自己的环境中生效。"$json$::jsonb),
  ('ja', 'docs.environments.summary', $json$"個人のプロジェクトと各組織は別々の環境にあります。それぞれが自分のプロジェクト、チャット、ノート、使用量、設定（エージェント、モデル、MCP サーバー、スキル、権限）を持つため、互いに混ざりません。プロフィール、言語、テーマ、プラン、2 段階認証はどこでも共通で、各エージェントのプランの上限も共有されます。組織のポリシー（許可されたエージェント、ブロックされたコマンド、保護されたファイル）は、その組織自身の環境の中でのみ適用されます。"$json$::jsonb),
  ('hi', 'docs.environments.summary', $json$"आपके व्यक्तिगत प्रोजेक्ट और हर संगठन अलग-अलग परिवेश में रहते हैं। हर परिवेश के अपने प्रोजेक्ट, चैट, नोट्स, उपयोग और सेटिंग (एजेंट, मॉडल, MCP सर्वर, स्किल और अनुमतियाँ) होते हैं, इसलिए एक की चीज़ें दूसरे में नहीं जातीं। आपकी प्रोफ़ाइल, भाषा, थीम, प्लान और दो-चरण साइन-इन हर जगह समान हैं, और हर एजेंट के प्लान की सीमा भी साझा है। किसी संगठन की नीति (अनुमत एजेंट, अवरुद्ध कमांड, सुरक्षित फ़ाइलें) केवल उसके अपने परिवेश के भीतर लागू होती है।"$json$::jsonb),
  ('ar', 'docs.environments.summary', $json$"مشاريعك الشخصية وكل مؤسسة تعيش في بيئات منفصلة. تحتفظ كل بيئة بمشاريعها ومحادثاتها وملاحظاتها واستخدامها وإعداداتها (الوكلاء والنماذج وخوادم MCP والمهارات والأذونات)، فلا يتسرب شيء من إحداها إلى الأخرى. ملفك الشخصي ولغتك والمظهر والخطة وتسجيل الدخول بخطوتين واحدة في كل مكان، وكذلك حد خطة كل وكيل. تسري سياسة المؤسسة (الوكلاء المسموح بهم والأوامر المحظورة والملفات المحمية) داخل بيئتها فقط."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
