-- v0.45.0: fechar a janela deixa o JayV na bandeja.
--
-- Só textos: o menu do ícone na bandeja (os itens que não reaproveitam chaves
-- que já existiam) e os itens da janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'tray.open', $json$"Abrir o JayV"$json$::jsonb),
  ('pt-BR', 'tray.quit', $json$"Sair do JayV"$json$::jsonb),
  ('pt-BR', 'tray.updateTo', $json$"Atualizar para o JayV {version}"$json$::jsonb),
  ('pt-BR', 'tray.tooltip.update', $json$"JayV · versão {version} disponível"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.trayBackground.title', $json$"Fechar a janela deixa o JayV rodando na bandeja"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.trayBackground.detail', $json$"No Windows, no macOS e no Linux, o botão fechar agora esconde a janela em vez de sair. Os pedidos na fila, a sincronização, o painel Ao vivo e a busca de atualizações continuam rodando. O menu do ícone na bandeja abre o JayV direto em Projetos, Organizações, Estatísticas, Sistema ou Configurações, começa um chat novo e procura atualizações; Sair do JayV é o caminho para fechar de verdade. Abrir o JayV de novo pelo menu do sistema ou pelo Dock também traz a janela de volta."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updatesInBackground.title', $json$"Versão nova aparece mesmo com a janela escondida"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updatesInBackground.detail', $json$"A busca de versão nova agora roda no núcleo do app a cada 15 segundos, então continua funcionando com a janela na bandeja, e também roda quando você volta para a janela. Uma versão nova ainda leva alguns minutos para aparecer depois do merge: é o tempo de gerar os instaladores de todos os sistemas."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveFixes.title', $json$"O painel Ao vivo acompanha o agente com mais precisão"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveFixes.detail', $json$"Um projeto aberto numa subpasta de um repositório agora usa o git, e o diff compara com o arquivo como estava antes do pedido, em vez de mostrar tudo como novo. Arquivos temporários que o agente cria e apaga ao salvar não ficam mais na lista como removidos. Uma segunda gravação rápida com o mesmo tamanho não passa mais despercebida, e o que o agente grava nos primeiros segundos não é mais confundido com alterações que já existiam."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatFilterWidth.title', $json$"O filtro de chat nas Estatísticas não estica mais pela tela"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatFilterWidth.detail', $json$"Os filtros de projeto e de chat nas Estatísticas e no painel da organização têm largura fixa, e títulos de chat longos são cortados com reticências na lista; passe o mouse sobre um deles para ler inteiro."$json$::jsonb),
  ('en', 'tray.open', $json$"Open JayV"$json$::jsonb),
  ('en', 'tray.quit', $json$"Quit JayV"$json$::jsonb),
  ('en', 'tray.updateTo', $json$"Update to JayV {version}"$json$::jsonb),
  ('en', 'tray.tooltip.update', $json$"JayV · version {version} available"$json$::jsonb),
  ('en', 'whatsNew.item.trayBackground.title', $json$"Closing the window keeps JayV running in the tray"$json$::jsonb),
  ('en', 'whatsNew.item.trayBackground.detail', $json$"On Windows, macOS and Linux the close button now hides the window instead of quitting. Requests in the queue, sync, the Live panel and the update check keep running. The tray icon menu opens JayV straight on Projects, Organizations, Statistics, System or Settings, starts a new chat and checks for updates; Quit JayV is the way to close it for real. Opening JayV again from the menu or the Dock also brings the window back."$json$::jsonb),
  ('en', 'whatsNew.item.updatesInBackground.title', $json$"New versions show up even with the window hidden"$json$::jsonb),
  ('en', 'whatsNew.item.updatesInBackground.detail', $json$"The check for a new version now runs in the app core every 15 seconds, so it keeps working with the window in the tray, and it also runs when you come back to the window. A new version still takes a few minutes to appear after it is merged: that is the time to build the installers for every system."$json$::jsonb),
  ('en', 'whatsNew.item.liveFixes.title', $json$"Live panel follows the agent more reliably"$json$::jsonb),
  ('en', 'whatsNew.item.liveFixes.detail', $json$"A project opened in a subfolder of a repository now uses git, so the diff compares with how the file was before the request instead of showing everything as new. Temporary files that the agent creates and removes while saving no longer stay in the list as removed. A quick second save with the same size is no longer missed, and the files the agent writes in its first seconds are no longer mistaken for changes that already existed."$json$::jsonb),
  ('en', 'whatsNew.item.chatFilterWidth.title', $json$"The chat filter in Statistics no longer stretches across the screen"$json$::jsonb),
  ('en', 'whatsNew.item.chatFilterWidth.detail', $json$"The project and chat filters in Statistics and in the organization dashboard have a fixed width, and long chat titles are cut with an ellipsis in the list; hover over one to read it in full."$json$::jsonb),
  ('es', 'tray.open', $json$"Abrir JayV"$json$::jsonb),
  ('es', 'tray.quit', $json$"Salir de JayV"$json$::jsonb),
  ('es', 'tray.updateTo', $json$"Actualizar a JayV {version}"$json$::jsonb),
  ('es', 'tray.tooltip.update', $json$"JayV · versión {version} disponible"$json$::jsonb),
  ('es', 'whatsNew.item.trayBackground.title', $json$"Cerrar la ventana deja JayV funcionando en la bandeja"$json$::jsonb),
  ('es', 'whatsNew.item.trayBackground.detail', $json$"En Windows, macOS y Linux, el botón cerrar ahora oculta la ventana en lugar de salir. Las solicitudes en cola, la sincronización, el panel En vivo y la búsqueda de actualizaciones siguen funcionando. El menú del icono de la bandeja abre JayV directamente en Proyectos, Organizaciones, Estadísticas, Sistema o Configuración, inicia un chat nuevo y busca actualizaciones; Salir de JayV es la forma de cerrarlo de verdad. Abrir JayV de nuevo desde el menú del sistema o el Dock también trae la ventana de vuelta."$json$::jsonb),
  ('es', 'whatsNew.item.updatesInBackground.title', $json$"Las versiones nuevas aparecen aunque la ventana esté oculta"$json$::jsonb),
  ('es', 'whatsNew.item.updatesInBackground.detail', $json$"La búsqueda de una versión nueva ahora se ejecuta en el núcleo de la app cada 15 segundos, así que sigue funcionando con la ventana en la bandeja, y también se ejecuta cuando vuelves a la ventana. Una versión nueva aún tarda unos minutos en aparecer después del merge: es el tiempo de generar los instaladores de todos los sistemas."$json$::jsonb),
  ('es', 'whatsNew.item.liveFixes.title', $json$"El panel En vivo sigue al agente con más precisión"$json$::jsonb),
  ('es', 'whatsNew.item.liveFixes.detail', $json$"Un proyecto abierto en una subcarpeta de un repositorio ahora usa git, y el diff compara con el archivo tal como estaba antes de la solicitud en lugar de mostrar todo como nuevo. Los archivos temporales que el agente crea y borra al guardar ya no quedan en la lista como eliminados. Un segundo guardado rápido con el mismo tamaño ya no pasa desapercibido, y lo que el agente escribe en sus primeros segundos ya no se confunde con cambios que ya existían."$json$::jsonb),
  ('es', 'whatsNew.item.chatFilterWidth.title', $json$"El filtro de chat en Estadísticas ya no se estira por la pantalla"$json$::jsonb),
  ('es', 'whatsNew.item.chatFilterWidth.detail', $json$"Los filtros de proyecto y de chat en Estadísticas y en el panel de la organización tienen ancho fijo, y los títulos de chat largos se cortan con puntos suspensivos en la lista; pasa el ratón sobre uno para leerlo completo."$json$::jsonb),
  ('zh-CN', 'tray.open', $json$"打开 JayV"$json$::jsonb),
  ('zh-CN', 'tray.quit', $json$"退出 JayV"$json$::jsonb),
  ('zh-CN', 'tray.updateTo', $json$"更新到 JayV {version}"$json$::jsonb),
  ('zh-CN', 'tray.tooltip.update', $json$"JayV · 版本 {version} 可用"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.trayBackground.title', $json$"关闭窗口后 JayV 会在托盘中继续运行"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.trayBackground.detail', $json$"在 Windows、macOS 和 Linux 上，关闭按钮现在会隐藏窗口而不是退出。队列中的请求、同步、实时面板和更新检查都会继续运行。托盘图标菜单可直接打开项目、组织、统计、系统或设置，新建聊天并检查更新；要真正关闭，请使用“退出 JayV”。从系统菜单或程序坞再次打开 JayV 也会让窗口回来。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updatesInBackground.title', $json$"即使窗口隐藏也能发现新版本"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updatesInBackground.detail', $json$"检查新版本现在每 15 秒在应用核心中运行一次，因此窗口在托盘中时也能工作，回到窗口时也会检查。合并后新版本仍需几分钟才会出现：这是为所有系统生成安装包的时间。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveFixes.title', $json$"实时面板更准确地跟随代理"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveFixes.detail', $json$"在仓库子文件夹中打开的项目现在也使用 git，差异会与请求开始前的文件比较，而不是把所有内容显示为新增。代理保存时创建又删除的临时文件不再以“已删除”留在列表中。相同大小的快速二次保存不再被遗漏，代理在最初几秒写入的内容也不再被误认为已有的修改。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatFilterWidth.title', $json$"统计中的聊天筛选器不再撑满屏幕"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatFilterWidth.detail', $json$"统计和组织仪表板中的项目与聊天筛选器宽度固定，较长的聊天标题在列表中会以省略号截断；将鼠标悬停在上面即可查看完整标题。"$json$::jsonb),
  ('hi', 'tray.open', $json$"JayV खोलें"$json$::jsonb),
  ('hi', 'tray.quit', $json$"JayV बंद करें"$json$::jsonb),
  ('hi', 'tray.updateTo', $json$"JayV {version} पर अपडेट करें"$json$::jsonb),
  ('hi', 'tray.tooltip.update', $json$"JayV · संस्करण {version} उपलब्ध"$json$::jsonb),
  ('hi', 'whatsNew.item.trayBackground.title', $json$"विंडो बंद करने पर JayV ट्रे में चलता रहता है"$json$::jsonb),
  ('hi', 'whatsNew.item.trayBackground.detail', $json$"Windows, macOS और Linux पर बंद करने का बटन अब ऐप से बाहर निकलने के बजाय विंडो छिपा देता है। कतार के अनुरोध, सिंक, लाइव पैनल और अपडेट की जाँच चलते रहते हैं। ट्रे आइकन का मेनू JayV को सीधे प्रोजेक्ट, संगठन, आँकड़े, सिस्टम या सेटिंग्स पर खोलता है, नई चैट शुरू करता है और अपडेट खोजता है; सचमुच बंद करने के लिए JayV बंद करें चुनें। सिस्टम मेनू या Dock से JayV फिर खोलने पर भी विंडो वापस आ जाती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updatesInBackground.title', $json$"विंडो छिपी होने पर भी नया संस्करण दिखता है"$json$::jsonb),
  ('hi', 'whatsNew.item.updatesInBackground.detail', $json$"नए संस्करण की जाँच अब ऐप के कोर में हर 15 सेकंड चलती है, इसलिए विंडो ट्रे में होने पर भी काम करती है, और विंडो पर लौटने पर भी चलती है। मर्ज के बाद नया संस्करण दिखने में अब भी कुछ मिनट लगते हैं: इतना समय सभी सिस्टम के इंस्टॉलर बनाने में लगता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.liveFixes.title', $json$"लाइव पैनल एजेंट को ज़्यादा सटीकता से दिखाता है"$json$::jsonb),
  ('hi', 'whatsNew.item.liveFixes.detail', $json$"किसी रिपॉज़िटरी के सबफ़ोल्डर में खोला गया प्रोजेक्ट अब git का उपयोग करता है, और diff सब कुछ नया दिखाने के बजाय अनुरोध से पहले वाली फ़ाइल से तुलना करता है। सहेजते समय एजेंट जो अस्थायी फ़ाइलें बनाता और मिटाता है, वे अब सूची में हटाई गई के रूप में नहीं रहतीं। उसी आकार वाली तेज़ दूसरी सेव अब नहीं छूटती, और एजेंट पहले कुछ सेकंड में जो लिखता है उसे पहले से मौजूद बदलाव नहीं समझा जाता।"$json$::jsonb),
  ('hi', 'whatsNew.item.chatFilterWidth.title', $json$"आँकड़ों में चैट फ़िल्टर अब पूरी स्क्रीन पर नहीं फैलता"$json$::jsonb),
  ('hi', 'whatsNew.item.chatFilterWidth.detail', $json$"आँकड़ों और संगठन डैशबोर्ड में प्रोजेक्ट और चैट फ़िल्टर की चौड़ाई तय है, और लंबे चैट शीर्षक सूची में तीन बिंदुओं के साथ काटे जाते हैं; पूरा पढ़ने के लिए उस पर माउस ले जाएँ।"$json$::jsonb),
  ('ar', 'tray.open', $json$"فتح JayV"$json$::jsonb),
  ('ar', 'tray.quit', $json$"إنهاء JayV"$json$::jsonb),
  ('ar', 'tray.updateTo', $json$"التحديث إلى JayV {version}"$json$::jsonb),
  ('ar', 'tray.tooltip.update', $json$"JayV · الإصدار {version} متاح"$json$::jsonb),
  ('ar', 'whatsNew.item.trayBackground.title', $json$"إغلاق النافذة يُبقي JayV يعمل في شريط النظام"$json$::jsonb),
  ('ar', 'whatsNew.item.trayBackground.detail', $json$"في Windows وmacOS وLinux، أصبح زر الإغلاق يُخفي النافذة بدلًا من إنهاء التطبيق. تستمر الطلبات في قائمة الانتظار والمزامنة ولوحة «مباشر» والبحث عن التحديثات في العمل. تفتح قائمة الأيقونة JayV مباشرة على المشاريع أو المؤسسات أو الإحصاءات أو النظام أو الإعدادات، وتبدأ محادثة جديدة وتبحث عن التحديثات؛ أما إنهاء JayV فهو طريقة إغلاقه فعلًا. فتح JayV مجددًا من قائمة النظام أو من Dock يعيد النافذة أيضًا."$json$::jsonb),
  ('ar', 'whatsNew.item.updatesInBackground.title', $json$"تظهر الإصدارات الجديدة حتى مع إخفاء النافذة"$json$::jsonb),
  ('ar', 'whatsNew.item.updatesInBackground.detail', $json$"أصبح البحث عن إصدار جديد يعمل في نواة التطبيق كل 15 ثانية، فيستمر مع وجود النافذة في شريط النظام، ويعمل أيضًا عند عودتك إلى النافذة. لا يزال الإصدار الجديد يحتاج بضع دقائق ليظهر بعد الدمج: وهو وقت بناء المثبتات لكل الأنظمة."$json$::jsonb),
  ('ar', 'whatsNew.item.liveFixes.title', $json$"لوحة «مباشر» تتابع الوكيل بدقة أكبر"$json$::jsonb),
  ('ar', 'whatsNew.item.liveFixes.detail', $json$"المشروع المفتوح في مجلد فرعي من مستودع يستخدم git الآن، فيقارن الفرق بالملف كما كان قبل الطلب بدلًا من عرض كل شيء كجديد. لم تعد الملفات المؤقتة التي ينشئها الوكيل ويحذفها أثناء الحفظ تبقى في القائمة كمحذوفة. لم يعد الحفظ الثاني السريع بالحجم نفسه يفوت، ولم يعد ما يكتبه الوكيل في ثوانيه الأولى يُحسب تغييرات كانت موجودة من قبل."$json$::jsonb),
  ('ar', 'whatsNew.item.chatFilterWidth.title', $json$"لم يعد فلتر المحادثة في الإحصاءات يمتد عبر الشاشة"$json$::jsonb),
  ('ar', 'whatsNew.item.chatFilterWidth.detail', $json$"لفلاتر المشروع والمحادثة في الإحصاءات ولوحة المؤسسة عرض ثابت، وتُقص عناوين المحادثات الطويلة بعلامة حذف في القائمة؛ مرّر المؤشر فوق أحدها لقراءته كاملًا."$json$::jsonb),
  ('fr', 'tray.open', $json$"Ouvrir JayV"$json$::jsonb),
  ('fr', 'tray.quit', $json$"Quitter JayV"$json$::jsonb),
  ('fr', 'tray.updateTo', $json$"Mettre à jour vers JayV {version}"$json$::jsonb),
  ('fr', 'tray.tooltip.update', $json$"JayV · version {version} disponible"$json$::jsonb),
  ('fr', 'whatsNew.item.trayBackground.title', $json$"Fermer la fenêtre laisse JayV tourner dans la barre système"$json$::jsonb),
  ('fr', 'whatsNew.item.trayBackground.detail', $json$"Sous Windows, macOS et Linux, le bouton fermer masque désormais la fenêtre au lieu de quitter. Les demandes en file, la synchronisation, le panneau En direct et la recherche de mises à jour continuent de tourner. Le menu de l'icône ouvre JayV directement sur Projets, Organisations, Statistiques, Système ou Paramètres, démarre une nouvelle discussion et cherche des mises à jour ; Quitter JayV est le moyen de le fermer vraiment. Rouvrir JayV depuis le menu du système ou le Dock ramène aussi la fenêtre."$json$::jsonb),
  ('fr', 'whatsNew.item.updatesInBackground.title', $json$"Les nouvelles versions apparaissent même fenêtre masquée"$json$::jsonb),
  ('fr', 'whatsNew.item.updatesInBackground.detail', $json$"La recherche d'une nouvelle version tourne désormais dans le cœur de l'app toutes les 15 secondes : elle continue avec la fenêtre dans la barre système et se lance aussi quand vous revenez à la fenêtre. Une nouvelle version met encore quelques minutes à apparaître après le merge : c'est le temps de générer les installateurs pour chaque système."$json$::jsonb),
  ('fr', 'whatsNew.item.liveFixes.title', $json$"Le panneau En direct suit l'agent plus fidèlement"$json$::jsonb),
  ('fr', 'whatsNew.item.liveFixes.detail', $json$"Un projet ouvert dans un sous-dossier d'un dépôt utilise maintenant git, et le diff compare avec le fichier tel qu'il était avant la demande au lieu de tout montrer comme nouveau. Les fichiers temporaires que l'agent crée et supprime en enregistrant ne restent plus dans la liste comme supprimés. Un second enregistrement rapide de même taille n'est plus manqué, et ce que l'agent écrit dans ses premières secondes n'est plus confondu avec des modifications déjà présentes."$json$::jsonb),
  ('fr', 'whatsNew.item.chatFilterWidth.title', $json$"Le filtre de discussion des Statistiques ne s'étire plus sur tout l'écran"$json$::jsonb),
  ('fr', 'whatsNew.item.chatFilterWidth.detail', $json$"Les filtres de projet et de discussion dans les Statistiques et le tableau de bord de l'organisation ont une largeur fixe, et les titres de discussion longs sont coupés par des points de suspension dans la liste ; survolez-en un pour le lire en entier."$json$::jsonb),
  ('de', 'tray.open', $json$"JayV öffnen"$json$::jsonb),
  ('de', 'tray.quit', $json$"JayV beenden"$json$::jsonb),
  ('de', 'tray.updateTo', $json$"Auf JayV {version} aktualisieren"$json$::jsonb),
  ('de', 'tray.tooltip.update', $json$"JayV · Version {version} verfügbar"$json$::jsonb),
  ('de', 'whatsNew.item.trayBackground.title', $json$"Das Schließen des Fensters lässt JayV im Infobereich weiterlaufen"$json$::jsonb),
  ('de', 'whatsNew.item.trayBackground.detail', $json$"Unter Windows, macOS und Linux blendet die Schließen-Schaltfläche das Fenster jetzt aus, statt die App zu beenden. Anfragen in der Warteschlange, die Synchronisierung, das Live-Panel und die Update-Suche laufen weiter. Das Menü des Symbols öffnet JayV direkt in Projekte, Organisationen, Statistiken, System oder Einstellungen, startet einen neuen Chat und sucht nach Updates; JayV beenden schließt die App wirklich. JayV erneut über das Systemmenü oder das Dock zu öffnen, holt das Fenster ebenfalls zurück."$json$::jsonb),
  ('de', 'whatsNew.item.updatesInBackground.title', $json$"Neue Versionen erscheinen auch bei ausgeblendetem Fenster"$json$::jsonb),
  ('de', 'whatsNew.item.updatesInBackground.detail', $json$"Die Suche nach einer neuen Version läuft jetzt alle 15 Sekunden im Kern der App, funktioniert also auch mit dem Fenster im Infobereich, und sie läuft auch, wenn du zum Fenster zurückkehrst. Eine neue Version braucht nach dem Merge trotzdem einige Minuten: so lange dauert es, die Installer für alle Systeme zu bauen."$json$::jsonb),
  ('de', 'whatsNew.item.liveFixes.title', $json$"Das Live-Panel folgt dem Agenten zuverlässiger"$json$::jsonb),
  ('de', 'whatsNew.item.liveFixes.detail', $json$"Ein Projekt, das in einem Unterordner eines Repositorys geöffnet ist, nutzt jetzt git, und der Diff vergleicht mit dem Stand vor der Anfrage, statt alles als neu anzuzeigen. Temporäre Dateien, die der Agent beim Speichern anlegt und löscht, bleiben nicht mehr als entfernt in der Liste. Ein schnelles zweites Speichern mit gleicher Größe wird nicht mehr übersehen, und was der Agent in den ersten Sekunden schreibt, wird nicht mehr mit bereits vorhandenen Änderungen verwechselt."$json$::jsonb),
  ('de', 'whatsNew.item.chatFilterWidth.title', $json$"Der Chat-Filter in den Statistiken zieht sich nicht mehr über den Bildschirm"$json$::jsonb),
  ('de', 'whatsNew.item.chatFilterWidth.detail', $json$"Die Projekt- und Chat-Filter in den Statistiken und im Organisations-Dashboard haben eine feste Breite, und lange Chat-Titel werden in der Liste mit Auslassungspunkten gekürzt; fahre mit der Maus darüber, um sie vollständig zu lesen."$json$::jsonb),
  ('ja', 'tray.open', $json$"JayV を開く"$json$::jsonb),
  ('ja', 'tray.quit', $json$"JayV を終了"$json$::jsonb),
  ('ja', 'tray.updateTo', $json$"JayV {version} に更新"$json$::jsonb),
  ('ja', 'tray.tooltip.update', $json$"JayV · バージョン {version} が利用可能"$json$::jsonb),
  ('ja', 'whatsNew.item.trayBackground.title', $json$"ウィンドウを閉じても JayV はトレイで動き続けます"$json$::jsonb),
  ('ja', 'whatsNew.item.trayBackground.detail', $json$"Windows、macOS、Linux で、閉じるボタンはアプリを終了せずにウィンドウを隠すようになりました。キュー内のリクエスト、同期、ライブパネル、更新の確認は動き続けます。トレイアイコンのメニューから、プロジェクト、組織、統計、システム、設定を直接開いたり、新しいチャットを始めたり、更新を確認したりできます。本当に閉じるには「JayV を終了」を使います。システムのメニューや Dock から JayV を開き直してもウィンドウが戻ります。"$json$::jsonb),
  ('ja', 'whatsNew.item.updatesInBackground.title', $json$"ウィンドウを隠していても新しいバージョンが表示されます"$json$::jsonb),
  ('ja', 'whatsNew.item.updatesInBackground.detail', $json$"新しいバージョンの確認はアプリのコアで 15 秒ごとに行われるようになり、ウィンドウがトレイにあっても動作し、ウィンドウに戻ったときにも実行されます。マージ後に新しいバージョンが表示されるまでには数分かかります。すべてのシステム向けのインストーラーを作る時間です。"$json$::jsonb),
  ('ja', 'whatsNew.item.liveFixes.title', $json$"ライブパネルがエージェントをより正確に追います"$json$::jsonb),
  ('ja', 'whatsNew.item.liveFixes.detail', $json$"リポジトリのサブフォルダーで開いたプロジェクトでも git を使うようになり、すべてを新規として表示する代わりに、リクエスト前のファイルと比較します。保存時にエージェントが作成して削除する一時ファイルが、削除済みとして一覧に残らなくなりました。同じサイズのすばやい再保存も見逃さず、エージェントが最初の数秒に書いた内容を既存の変更と取り違えることもなくなりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.chatFilterWidth.title', $json$"統計のチャットフィルターが画面いっぱいに広がらなくなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.chatFilterWidth.detail', $json$"統計と組織ダッシュボードのプロジェクトとチャットのフィルターは幅が固定になり、長いチャットのタイトルは一覧で省略記号付きで切り詰められます。マウスを重ねると全文を読めます。"$json$::jsonb),
  ('ru', 'tray.open', $json$"Открыть JayV"$json$::jsonb),
  ('ru', 'tray.quit', $json$"Выйти из JayV"$json$::jsonb),
  ('ru', 'tray.updateTo', $json$"Обновить до JayV {version}"$json$::jsonb),
  ('ru', 'tray.tooltip.update', $json$"JayV · доступна версия {version}"$json$::jsonb),
  ('ru', 'whatsNew.item.trayBackground.title', $json$"После закрытия окна JayV продолжает работать в трее"$json$::jsonb),
  ('ru', 'whatsNew.item.trayBackground.detail', $json$"В Windows, macOS и Linux кнопка закрытия теперь скрывает окно, а не завершает приложение. Запросы в очереди, синхронизация, панель «В реальном времени» и проверка обновлений продолжают работать. Меню значка в трее открывает JayV сразу на разделах «Проекты», «Организации», «Статистика», «Система» или «Настройки», создаёт новый чат и проверяет обновления; чтобы закрыть приложение по-настоящему, выберите «Выйти из JayV». Повторный запуск JayV из меню системы или из Dock тоже возвращает окно."$json$::jsonb),
  ('ru', 'whatsNew.item.updatesInBackground.title', $json$"Новые версии появляются, даже когда окно скрыто"$json$::jsonb),
  ('ru', 'whatsNew.item.updatesInBackground.detail', $json$"Проверка новой версии теперь выполняется в ядре приложения каждые 15 секунд, поэтому работает и с окном в трее, а также запускается, когда вы возвращаетесь к окну. После слияния новой версии всё ещё нужно несколько минут, чтобы появиться: столько занимает сборка установщиков для всех систем."$json$::jsonb),
  ('ru', 'whatsNew.item.liveFixes.title', $json$"Панель «В реальном времени» точнее следит за агентом"$json$::jsonb),
  ('ru', 'whatsNew.item.liveFixes.detail', $json$"Проект, открытый в подпапке репозитория, теперь использует git, и diff сравнивает файл с тем, каким он был до запроса, а не показывает всё как новое. Временные файлы, которые агент создаёт и удаляет при сохранении, больше не остаются в списке как удалённые. Быстрое повторное сохранение того же размера больше не пропускается, а то, что агент пишет в первые секунды, больше не принимается за уже существовавшие изменения."$json$::jsonb),
  ('ru', 'whatsNew.item.chatFilterWidth.title', $json$"Фильтр чатов в статистике больше не растягивается на весь экран"$json$::jsonb),
  ('ru', 'whatsNew.item.chatFilterWidth.detail', $json$"Фильтры проектов и чатов в статистике и на панели организации теперь фиксированной ширины, а длинные названия чатов в списке обрезаются многоточием; наведите на название, чтобы прочитать его полностью."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
