-- As abas Estatísticas e Portaria da organização: a conta e os dois portões
-- dos projetos dela neste computador, filtrados por projeto e por chat.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'org.tab.stats', $json$"Estatísticas"$json$::jsonb),
  ('pt-BR', 'org.tab.gate', $json$"Portaria"$json$::jsonb),
  ('pt-BR', 'org.dashboard.description', $json$"Contado a partir dos seus projetos neste computador que pertencem a esta organização. Filtre por projeto e por chat."$json$::jsonb),
  ('pt-BR', 'org.dashboard.allProjects', $json$"Todos os projetos da organização"$json$::jsonb),
  ('pt-BR', 'org.gate.entry.empty', $json$"Nenhum pedido passou pelo portão de entrada neste recorte ainda."$json$::jsonb),
  ('pt-BR', 'org.gate.exit.empty', $json$"Nada saiu pelo portão de saída neste recorte ainda."$json$::jsonb),
  ('en', 'org.tab.stats', $json$"Statistics"$json$::jsonb),
  ('en', 'org.tab.gate', $json$"Gatehouse"$json$::jsonb),
  ('en', 'org.dashboard.description', $json$"Counted from your projects on this computer that belong to this organization. Filter by project and by chat."$json$::jsonb),
  ('en', 'org.dashboard.allProjects', $json$"All projects in the organization"$json$::jsonb),
  ('en', 'org.gate.entry.empty', $json$"No request has passed the entry gate in this selection yet."$json$::jsonb),
  ('en', 'org.gate.exit.empty', $json$"Nothing has left through the exit gate in this selection yet."$json$::jsonb),
  ('es', 'org.tab.stats', $json$"Estadísticas"$json$::jsonb),
  ('es', 'org.tab.gate', $json$"Portería"$json$::jsonb),
  ('es', 'org.dashboard.description', $json$"Calculado a partir de tus proyectos en este equipo que pertenecen a esta organización. Filtra por proyecto y por chat."$json$::jsonb),
  ('es', 'org.dashboard.allProjects', $json$"Todos los proyectos de la organización"$json$::jsonb),
  ('es', 'org.gate.entry.empty', $json$"Ninguna solicitud ha pasado por la puerta de entrada en esta selección todavía."$json$::jsonb),
  ('es', 'org.gate.exit.empty', $json$"Nada ha salido por la puerta de salida en esta selección todavía."$json$::jsonb),
  ('zh-CN', 'org.tab.stats', $json$"统计"$json$::jsonb),
  ('zh-CN', 'org.tab.gate', $json$"门岗"$json$::jsonb),
  ('zh-CN', 'org.dashboard.description', $json$"根据你在本机上属于此组织的项目统计。可按项目和对话筛选。"$json$::jsonb),
  ('zh-CN', 'org.dashboard.allProjects', $json$"组织的所有项目"$json$::jsonb),
  ('zh-CN', 'org.gate.entry.empty', $json$"此筛选范围内还没有请求经过入口。"$json$::jsonb),
  ('zh-CN', 'org.gate.exit.empty', $json$"此筛选范围内还没有内容经过出口。"$json$::jsonb),
  ('hi', 'org.tab.stats', $json$"आँकड़े"$json$::jsonb),
  ('hi', 'org.tab.gate', $json$"गेट"$json$::jsonb),
  ('hi', 'org.dashboard.description', $json$"इस कंप्यूटर पर इस संगठन से जुड़े आपके प्रोजेक्ट से गिना गया। प्रोजेक्ट और चैट के अनुसार फ़िल्टर करें।"$json$::jsonb),
  ('hi', 'org.dashboard.allProjects', $json$"संगठन के सभी प्रोजेक्ट"$json$::jsonb),
  ('hi', 'org.gate.entry.empty', $json$"इस चयन में अभी तक कोई अनुरोध प्रवेश द्वार से नहीं गुज़रा।"$json$::jsonb),
  ('hi', 'org.gate.exit.empty', $json$"इस चयन में अभी तक निकास द्वार से कुछ नहीं निकला।"$json$::jsonb),
  ('ar', 'org.tab.stats', $json$"الإحصاءات"$json$::jsonb),
  ('ar', 'org.tab.gate', $json$"البوابة"$json$::jsonb),
  ('ar', 'org.dashboard.description', $json$"محسوبة من مشاريعك على هذا الجهاز التابعة لهذه المؤسسة. صفِّ حسب المشروع وحسب المحادثة."$json$::jsonb),
  ('ar', 'org.dashboard.allProjects', $json$"كل مشاريع المؤسسة"$json$::jsonb),
  ('ar', 'org.gate.entry.empty', $json$"لم يمر أي طلب عبر بوابة الدخول في هذا التحديد بعد."$json$::jsonb),
  ('ar', 'org.gate.exit.empty', $json$"لم يخرج شيء عبر بوابة الخروج في هذا التحديد بعد."$json$::jsonb),
  ('fr', 'org.tab.stats', $json$"Statistiques"$json$::jsonb),
  ('fr', 'org.tab.gate', $json$"Loge"$json$::jsonb),
  ('fr', 'org.dashboard.description', $json$"Calculé à partir de vos projets sur cet ordinateur qui appartiennent à cette organisation. Filtrez par projet et par chat."$json$::jsonb),
  ('fr', 'org.dashboard.allProjects', $json$"Tous les projets de l'organisation"$json$::jsonb),
  ('fr', 'org.gate.entry.empty', $json$"Aucune demande n'a encore franchi la porte d'entrée dans cette sélection."$json$::jsonb),
  ('fr', 'org.gate.exit.empty', $json$"Rien n'est encore sorti par la porte de sortie dans cette sélection."$json$::jsonb),
  ('ru', 'org.tab.stats', $json$"Статистика"$json$::jsonb),
  ('ru', 'org.tab.gate', $json$"Проходная"$json$::jsonb),
  ('ru', 'org.dashboard.description', $json$"Подсчитано по вашим проектам на этом компьютере, которые входят в эту организацию. Фильтруйте по проекту и по чату."$json$::jsonb),
  ('ru', 'org.dashboard.allProjects', $json$"Все проекты организации"$json$::jsonb),
  ('ru', 'org.gate.entry.empty', $json$"В этой выборке через вход ещё не прошёл ни один запрос."$json$::jsonb),
  ('ru', 'org.gate.exit.empty', $json$"В этой выборке через выход ещё ничего не прошло."$json$::jsonb),
  ('ja', 'org.tab.stats', $json$"統計"$json$::jsonb),
  ('ja', 'org.tab.gate', $json$"ゲート"$json$::jsonb),
  ('ja', 'org.dashboard.description', $json$"このコンピューター上の、この組織に属するあなたのプロジェクトから集計しています。プロジェクトとチャットで絞り込めます。"$json$::jsonb),
  ('ja', 'org.dashboard.allProjects', $json$"組織のすべてのプロジェクト"$json$::jsonb),
  ('ja', 'org.gate.entry.empty', $json$"この絞り込みでは、まだ入口ゲートを通ったリクエストはありません。"$json$::jsonb),
  ('ja', 'org.gate.exit.empty', $json$"この絞り込みでは、まだ出口ゲートを通ったものはありません。"$json$::jsonb),
  ('de', 'org.tab.stats', $json$"Statistiken"$json$::jsonb),
  ('de', 'org.tab.gate', $json$"Pforte"$json$::jsonb),
  ('de', 'org.dashboard.description', $json$"Gezählt aus deinen Projekten auf diesem Computer, die zu dieser Organisation gehören. Nach Projekt und Chat filtern."$json$::jsonb),
  ('de', 'org.dashboard.allProjects', $json$"Alle Projekte der Organisation"$json$::jsonb),
  ('de', 'org.gate.entry.empty', $json$"In dieser Auswahl hat noch keine Anfrage das Eingangstor passiert."$json$::jsonb),
  ('de', 'org.gate.exit.empty', $json$"In dieser Auswahl hat noch nichts das Ausgangstor verlassen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
