-- Site 1.4.1: a demonstração e o "como funciona" deixam de prometer "saída
-- verificada". A portaria de saída confere as regras da casa; o que o JayV
-- não rodou aparece como não verificado, e o JayV não garante que a mudança
-- está correta. As chaves antigas mudam só de texto (sem parâmetro novo), e
-- site.trace.unverified é nova.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'site.hero.copy', $json$"O JayV coordena Codex, Claude Code, GitHub Copilot e Cursor Agent no contexto de cada projeto. O Jev entende o pedido, escolhe a rota e confere a resposta com as regras do projeto, e diz com clareza o que não foi verificado."$json$::jsonb),
  ('pt-BR', 'site.trace.exit', $json$"portaria de saída: nenhuma regra da casa tocada"$json$::jsonb),
  ('pt-BR', 'site.trace.unverified', $json$"não verificada: nenhum teste rodou neste turno"$json$::jsonb),
  ('pt-BR', 'site.how.step4.title', $json$"Diz o que foi conferido"$json$::jsonb),
  ('pt-BR', 'site.how.step4.detail', $json$"Os comandos e arquivos da resposta passam pela portaria de saída, e o que o JayV não conferiu aparece como não verificado: o JayV não garante que uma mudança está correta."$json$::jsonb),
  ('en', 'site.hero.copy', $json$"JayV coordinates Codex, Claude Code, GitHub Copilot and Cursor Agent in the context of each project. Jev understands the request, picks the route and checks the answer against the project's rules, and says plainly what was not verified."$json$::jsonb),
  ('en', 'site.trace.exit', $json$"exit gate: no house rule touched"$json$::jsonb),
  ('en', 'site.trace.unverified', $json$"not verified: no test ran in this turn"$json$::jsonb),
  ('en', 'site.how.step4.title', $json$"Says what was checked"$json$::jsonb),
  ('en', 'site.how.step4.detail', $json$"The commands and files in the answer go through the exit gate, and what JayV did not check shows as not verified: JayV does not guarantee that a change is correct."$json$::jsonb),
  ('es', 'site.hero.copy', $json$"JayV coordina Codex, Claude Code, GitHub Copilot y Cursor Agent en el contexto de cada proyecto. Jev entiende la petición, elige la ruta y comprueba la respuesta con las reglas del proyecto, y dice con claridad lo que no se verificó."$json$::jsonb),
  ('es', 'site.trace.exit', $json$"portería de salida: ninguna regla de la casa tocada"$json$::jsonb),
  ('es', 'site.trace.unverified', $json$"no verificada: no se ejecutó ninguna prueba en este turno"$json$::jsonb),
  ('es', 'site.how.step4.title', $json$"Dice qué se comprobó"$json$::jsonb),
  ('es', 'site.how.step4.detail', $json$"Los comandos y archivos de la respuesta pasan por la portería de salida, y lo que JayV no comprobó aparece como no verificado: JayV no garantiza que un cambio sea correcto."$json$::jsonb),
  ('zh-CN', 'site.hero.copy', $json$"JayV 在每个项目的上下文中协调 Codex、Claude Code、GitHub Copilot 和 Cursor Agent。Jev 理解请求、选择路线，按项目规则核查回答，并清楚说明哪些内容未经验证。"$json$::jsonb),
  ('zh-CN', 'site.trace.exit', $json$"出口门岗：未触及任何内部规则"$json$::jsonb),
  ('zh-CN', 'site.trace.unverified', $json$"未验证：本轮没有运行任何测试"$json$::jsonb),
  ('zh-CN', 'site.how.step4.title', $json$"说明核查了什么"$json$::jsonb),
  ('zh-CN', 'site.how.step4.detail', $json$"回答中的命令和文件会经过出口门岗，JayV 没有核查的内容会显示为未验证：JayV 不保证更改是正确的。"$json$::jsonb),
  ('hi', 'site.hero.copy', $json$"JayV हर प्रोजेक्ट के संदर्भ में Codex, Claude Code, GitHub Copilot और Cursor Agent को समन्वित करता है। Jev अनुरोध समझता है, रास्ता चुनता है, जवाब को प्रोजेक्ट के नियमों से जाँचता है और साफ़ बताता है कि क्या सत्यापित नहीं हुआ।"$json$::jsonb),
  ('hi', 'site.trace.exit', $json$"निकास गेट: घर का कोई नियम नहीं छुआ गया"$json$::jsonb),
  ('hi', 'site.trace.unverified', $json$"सत्यापित नहीं: इस टर्न में कोई टेस्ट नहीं चला"$json$::jsonb),
  ('hi', 'site.how.step4.title', $json$"बताता है कि क्या जाँचा गया"$json$::jsonb),
  ('hi', 'site.how.step4.detail', $json$"जवाब के कमांड और फ़ाइलें निकास गेट से गुज़रते हैं, और जो JayV ने नहीं जाँचा वह सत्यापित नहीं के रूप में दिखता है: JayV यह गारंटी नहीं देता कि बदलाव सही है।"$json$::jsonb),
  ('ar', 'site.hero.copy', $json$"ينسّق JayV بين Codex وClaude Code وGitHub Copilot وCursor Agent في سياق كل مشروع. يفهم Jev الطلب ويختار المسار ويفحص الإجابة وفق قواعد المشروع، ويقول بوضوح ما الذي لم يُتحقق منه."$json$::jsonb),
  ('ar', 'site.trace.exit', $json$"بوابة الخروج: لم تُمَس أي قاعدة من قواعد الدار"$json$::jsonb),
  ('ar', 'site.trace.unverified', $json$"غير متحقق منها: لم يُشغَّل أي اختبار في هذه الجولة"$json$::jsonb),
  ('ar', 'site.how.step4.title', $json$"يقول ما الذي فُحص"$json$::jsonb),
  ('ar', 'site.how.step4.detail', $json$"تمر أوامر الإجابة وملفاتها عبر بوابة الخروج، ويظهر ما لم يفحصه JayV على أنه غير متحقق منه: لا يضمن JayV أن التغيير صحيح."$json$::jsonb),
  ('fr', 'site.hero.copy', $json$"JayV coordonne Codex, Claude Code, GitHub Copilot et Cursor Agent dans le contexte de chaque projet. Jev comprend la demande, choisit la route, contrôle la réponse selon les règles du projet et dit clairement ce qui n’a pas été vérifié."$json$::jsonb),
  ('fr', 'site.trace.exit', $json$"loge de sortie : aucune règle de la maison touchée"$json$::jsonb),
  ('fr', 'site.trace.unverified', $json$"non vérifiée : aucun test lancé dans ce tour"$json$::jsonb),
  ('fr', 'site.how.step4.title', $json$"Dit ce qui a été vérifié"$json$::jsonb),
  ('fr', 'site.how.step4.detail', $json$"Les commandes et fichiers de la réponse passent par la loge de sortie, et ce que JayV n’a pas vérifié apparaît comme non vérifié : JayV ne garantit pas qu’une modification est correcte."$json$::jsonb),
  ('ru', 'site.hero.copy', $json$"JayV координирует Codex, Claude Code, GitHub Copilot и Cursor Agent в контексте каждого проекта. Jev понимает запрос, выбирает маршрут, сверяет ответ с правилами проекта и прямо говорит, что не было проверено."$json$::jsonb),
  ('ru', 'site.trace.exit', $json$"выходная проходная: правила дома не затронуты"$json$::jsonb),
  ('ru', 'site.trace.unverified', $json$"не проверено: в этом ходе не запускалось ни одного теста"$json$::jsonb),
  ('ru', 'site.how.step4.title', $json$"Говорит, что проверено"$json$::jsonb),
  ('ru', 'site.how.step4.detail', $json$"Команды и файлы из ответа проходят через выходную проходную, а то, что JayV не проверял, помечается как не проверенное: JayV не гарантирует, что изменение верно."$json$::jsonb),
  ('ja', 'site.hero.copy', $json$"JayV は Codex、Claude Code、GitHub Copilot、Cursor Agent をプロジェクトごとのコンテキストで連携させます。Jev が依頼を理解してルートを選び、回答をプロジェクトのルールと照合し、検証していないことをはっきり伝えます。"$json$::jsonb),
  ('ja', 'site.trace.exit', $json$"出口ゲート：ハウスルールへの抵触なし"$json$::jsonb),
  ('ja', 'site.trace.unverified', $json$"未検証：このターンではテストを実行していません"$json$::jsonb),
  ('ja', 'site.how.step4.title', $json$"確認した内容を示す"$json$::jsonb),
  ('ja', 'site.how.step4.detail', $json$"回答内のコマンドとファイルは出口ゲートを通り、JayV が確認していないものは未検証と表示されます。JayV は変更が正しいことを保証しません。"$json$::jsonb),
  ('de', 'site.hero.copy', $json$"JayV koordiniert Codex, Claude Code, GitHub Copilot und Cursor Agent im Kontext jedes Projekts. Jev versteht die Anfrage, wählt die Route, gleicht die Antwort mit den Regeln des Projekts ab und sagt klar, was nicht geprüft wurde."$json$::jsonb),
  ('de', 'site.trace.exit', $json$"Ausgangspforte: keine Hausregel berührt"$json$::jsonb),
  ('de', 'site.trace.unverified', $json$"nicht geprüft: in diesem Durchgang lief kein Test"$json$::jsonb),
  ('de', 'site.how.step4.title', $json$"Sagt, was geprüft wurde"$json$::jsonb),
  ('de', 'site.how.step4.detail', $json$"Die Befehle und Dateien der Antwort gehen durch die Ausgangspforte, und was JayV nicht geprüft hat, wird als nicht geprüft angezeigt: JayV garantiert nicht, dass eine Änderung korrekt ist."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
