-- v0.42.0: balões do chat, etapas recentes e botões de resposta legíveis.
--
-- Só textos: o botão que abre ou recolhe as etapas anteriores na faixa de em
-- andamento (pending.steps.*) e os itens da janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'pending.steps.all', $json${"one":"+ {count} etapa anterior","other":"+ {count} etapas anteriores"}$json$::jsonb),
  ('pt-BR', 'pending.steps.less', $json$"mostrar só as últimas"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatBubbles.title', $json$"Quem disse o quê, de relance"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatBubbles.detail', $json$"No chat, os seus pedidos agora ficam num balão cheio à direita, e as respostas do JayV numa janela com borda e uma barra 🤖 jayv no topo, com o agente, o modelo e o veredito da portaria."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.recentSteps.title', $json$"Só as últimas etapas enquanto o pedido roda"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.recentSteps.detail', $json$"A faixa de em andamento acima da caixa de escrita mostra as 3 etapas mais recentes. Um botão abre a lista inteira, e o próximo pedido começa recolhido de novo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.readableButtons.title', $json$"Botões de resposta legíveis"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.readableButtons.detail', $json$"Enviar respostas, Enviar escolha e Sim, numa pergunta do agente, tinham o texto da mesma cor do botão. Agora dá para ler nos temas claro e escuro."$json$::jsonb),
  ('en', 'pending.steps.all', $json${"one":"+ {count} earlier step","other":"+ {count} earlier steps"}$json$::jsonb),
  ('en', 'pending.steps.less', $json$"show only the latest"$json$::jsonb),
  ('en', 'whatsNew.item.chatBubbles.title', $json$"Who said what, at a glance"$json$::jsonb),
  ('en', 'whatsNew.item.chatBubbles.detail', $json$"In the chat, your requests now sit in a filled bubble on the right, and JayV's answers in a framed window with a 🤖 jayv bar on top showing the agent, the model and the gate's verdict."$json$::jsonb),
  ('en', 'whatsNew.item.recentSteps.title', $json$"Only the latest steps while a request runs"$json$::jsonb),
  ('en', 'whatsNew.item.recentSteps.detail', $json$"The in-progress strip above the message box shows the 3 most recent steps. A button opens the full list, and the next request starts collapsed again."$json$::jsonb),
  ('en', 'whatsNew.item.readableButtons.title', $json$"Readable answer buttons"$json$::jsonb),
  ('en', 'whatsNew.item.readableButtons.detail', $json$"Send answers, Send choice and Yes, in a question from the agent, had text the same color as the button. They are readable again in light and dark themes."$json$::jsonb),
  ('es', 'pending.steps.all', $json${"one":"+ {count} paso anterior","other":"+ {count} pasos anteriores"}$json$::jsonb),
  ('es', 'pending.steps.less', $json$"mostrar solo los últimos"$json$::jsonb),
  ('es', 'whatsNew.item.chatBubbles.title', $json$"Quién dijo qué, de un vistazo"$json$::jsonb),
  ('es', 'whatsNew.item.chatBubbles.detail', $json$"En el chat, tus solicitudes ahora aparecen en un globo relleno a la derecha, y las respuestas de JayV en una ventana con borde y una barra 🤖 jayv arriba que muestra el agente, el modelo y el veredicto de la portería."$json$::jsonb),
  ('es', 'whatsNew.item.recentSteps.title', $json$"Solo los últimos pasos mientras se ejecuta una solicitud"$json$::jsonb),
  ('es', 'whatsNew.item.recentSteps.detail', $json$"La franja de en curso sobre el cuadro de mensaje muestra los 3 pasos más recientes. Un botón abre la lista completa, y la siguiente solicitud empieza contraída otra vez."$json$::jsonb),
  ('es', 'whatsNew.item.readableButtons.title', $json$"Botones de respuesta legibles"$json$::jsonb),
  ('es', 'whatsNew.item.readableButtons.detail', $json$"Enviar respuestas, Enviar elección y Sí, en una pregunta del agente, tenían el texto del mismo color que el botón. Ahora se leen en los temas claro y oscuro."$json$::jsonb),
  ('zh-CN', 'pending.steps.all', $json${"other":"+ 之前的 {count} 个步骤"}$json$::jsonb),
  ('zh-CN', 'pending.steps.less', $json$"只显示最新的"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatBubbles.title', $json$"谁说了什么，一目了然"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatBubbles.detail', $json$"在聊天中，你的请求现在显示在右侧的填充气泡里，JayV 的回答显示在带边框的窗口中，顶部的 🤖 jayv 栏显示代理、模型和门卫的判定。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.recentSteps.title', $json$"请求运行时只显示最新步骤"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.recentSteps.detail', $json$"输入框上方的进行中栏显示最近的 3 个步骤。一个按钮可以打开完整列表，下一个请求开始时会重新折叠。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.readableButtons.title', $json$"回答按钮清晰可读"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.readableButtons.detail', $json$"在代理提出的问题中，“发送回答”“发送选择”和“是”按钮的文字与按钮颜色相同。现在在浅色和深色主题下都能看清。"$json$::jsonb),
  ('hi', 'pending.steps.all', $json${"one":"+ {count} पिछला चरण","other":"+ {count} पिछले चरण"}$json$::jsonb),
  ('hi', 'pending.steps.less', $json$"सिर्फ़ नवीनतम दिखाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.chatBubbles.title', $json$"किसने क्या कहा, एक नज़र में"$json$::jsonb),
  ('hi', 'whatsNew.item.chatBubbles.detail', $json$"चैट में आपके अनुरोध अब दाईं ओर भरे हुए बबल में दिखते हैं, और JayV के जवाब एक बॉर्डर वाली विंडो में, जिसके ऊपर 🤖 jayv पट्टी एजेंट, मॉडल और गेट का फ़ैसला दिखाती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.recentSteps.title', $json$"अनुरोध चलते समय सिर्फ़ नवीनतम चरण"$json$::jsonb),
  ('hi', 'whatsNew.item.recentSteps.detail', $json$"संदेश बॉक्स के ऊपर प्रगति वाली पट्टी 3 सबसे हाल के चरण दिखाती है। एक बटन पूरी सूची खोलता है, और अगला अनुरोध फिर से सिमटा हुआ शुरू होता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.readableButtons.title', $json$"पढ़ने योग्य जवाब बटन"$json$::jsonb),
  ('hi', 'whatsNew.item.readableButtons.detail', $json$"एजेंट के प्रश्न में जवाब भेजें, चुनाव भेजें और हाँ बटन का टेक्स्ट बटन के ही रंग का था। अब ये हल्की और गहरी दोनों थीम में पढ़े जा सकते हैं।"$json$::jsonb),
  ('ar', 'pending.steps.all', $json${"zero":"+ {count} خطوة سابقة","one":"+ خطوة سابقة واحدة","two":"+ خطوتان سابقتان","few":"+ {count} خطوات سابقة","many":"+ {count} خطوة سابقة","other":"+ {count} خطوة سابقة"}$json$::jsonb),
  ('ar', 'pending.steps.less', $json$"عرض الأحدث فقط"$json$::jsonb),
  ('ar', 'whatsNew.item.chatBubbles.title', $json$"من قال ماذا، بنظرة واحدة"$json$::jsonb),
  ('ar', 'whatsNew.item.chatBubbles.detail', $json$"في الدردشة، تظهر طلباتك الآن في فقاعة ممتلئة على الجانب، وتظهر إجابات JayV في نافذة بإطار وفي أعلاها شريط 🤖 jayv يعرض الوكيل والنموذج وحكم البوابة."$json$::jsonb),
  ('ar', 'whatsNew.item.recentSteps.title', $json$"أحدث الخطوات فقط أثناء تنفيذ الطلب"$json$::jsonb),
  ('ar', 'whatsNew.item.recentSteps.detail', $json$"يعرض شريط قيد التنفيذ فوق مربع الرسالة أحدث 3 خطوات. يفتح زر القائمة الكاملة، ويبدأ الطلب التالي مطويًا من جديد."$json$::jsonb),
  ('ar', 'whatsNew.item.readableButtons.title', $json$"أزرار إجابة مقروءة"$json$::jsonb),
  ('ar', 'whatsNew.item.readableButtons.detail', $json$"في سؤال من الوكيل، كان نص أزرار إرسال الإجابات وإرسال الاختيار ونعم بلون الزر نفسه. أصبحت مقروءة الآن في المظهرين الفاتح والداكن."$json$::jsonb),
  ('fr', 'pending.steps.all', $json${"one":"+ {count} étape précédente","other":"+ {count} étapes précédentes"}$json$::jsonb),
  ('fr', 'pending.steps.less', $json$"n'afficher que les dernières"$json$::jsonb),
  ('fr', 'whatsNew.item.chatBubbles.title', $json$"Qui a dit quoi, en un coup d'œil"$json$::jsonb),
  ('fr', 'whatsNew.item.chatBubbles.detail', $json$"Dans le chat, vos demandes apparaissent désormais dans une bulle pleine à droite, et les réponses de JayV dans une fenêtre encadrée, avec en haut une barre 🤖 jayv qui indique l'agent, le modèle et le verdict du poste de garde."$json$::jsonb),
  ('fr', 'whatsNew.item.recentSteps.title', $json$"Seulement les dernières étapes pendant une demande"$json$::jsonb),
  ('fr', 'whatsNew.item.recentSteps.detail', $json$"Le bandeau en cours au-dessus de la zone de saisie affiche les 3 étapes les plus récentes. Un bouton ouvre la liste complète, et la demande suivante repart repliée."$json$::jsonb),
  ('fr', 'whatsNew.item.readableButtons.title', $json$"Boutons de réponse lisibles"$json$::jsonb),
  ('fr', 'whatsNew.item.readableButtons.detail', $json$"Dans une question de l'agent, les boutons Envoyer les réponses, Envoyer le choix et Oui avaient un texte de la même couleur que le bouton. Ils sont de nouveau lisibles en thème clair et sombre."$json$::jsonb),
  ('ru', 'pending.steps.all', $json${"one":"+ {count} предыдущий шаг","few":"+ {count} предыдущих шага","many":"+ {count} предыдущих шагов","other":"+ {count} предыдущего шага"}$json$::jsonb),
  ('ru', 'pending.steps.less', $json$"показать только последние"$json$::jsonb),
  ('ru', 'whatsNew.item.chatBubbles.title', $json$"Кто что сказал — с первого взгляда"$json$::jsonb),
  ('ru', 'whatsNew.item.chatBubbles.detail', $json$"В чате ваши запросы теперь показываются в заполненном пузыре справа, а ответы JayV — в окне с рамкой и полосой 🤖 jayv сверху, где видны агент, модель и вердикт проходной."$json$::jsonb),
  ('ru', 'whatsNew.item.recentSteps.title', $json$"Только последние шаги во время запроса"$json$::jsonb),
  ('ru', 'whatsNew.item.recentSteps.detail', $json$"Полоса «в процессе» над полем ввода показывает 3 последних шага. Кнопка открывает полный список, а следующий запрос снова начинается в свёрнутом виде."$json$::jsonb),
  ('ru', 'whatsNew.item.readableButtons.title', $json$"Читаемые кнопки ответа"$json$::jsonb),
  ('ru', 'whatsNew.item.readableButtons.detail', $json$"В вопросе агента у кнопок «Отправить ответы», «Отправить выбор» и «Да» текст был того же цвета, что и кнопка. Теперь они читаются в светлой и тёмной темах."$json$::jsonb),
  ('ja', 'pending.steps.all', $json${"other":"+ 以前のステップ {count} 件"}$json$::jsonb),
  ('ja', 'pending.steps.less', $json$"最新のみ表示"$json$::jsonb),
  ('ja', 'whatsNew.item.chatBubbles.title', $json$"誰が何を言ったか一目で"$json$::jsonb),
  ('ja', 'whatsNew.item.chatBubbles.detail', $json$"チャットでは、あなたのリクエストが右側の塗りつぶされた吹き出しに、JayV の回答が枠付きのウィンドウに表示されるようになりました。上部の 🤖 jayv バーにはエージェント、モデル、ゲートの判定が表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.recentSteps.title', $json$"リクエスト実行中は最新のステップだけ"$json$::jsonb),
  ('ja', 'whatsNew.item.recentSteps.detail', $json$"入力欄の上にある進行中バーには、直近 3 件のステップが表示されます。ボタンで全件を開けて、次のリクエストはまた折りたたまれた状態で始まります。"$json$::jsonb),
  ('ja', 'whatsNew.item.readableButtons.title', $json$"読みやすい回答ボタン"$json$::jsonb),
  ('ja', 'whatsNew.item.readableButtons.detail', $json$"エージェントからの質問で、「回答を送信」「選択を送信」「はい」ボタンの文字がボタンと同じ色になっていました。ライトとダークの両方のテーマで読めるようになりました。"$json$::jsonb),
  ('de', 'pending.steps.all', $json${"one":"+ {count} früherer Schritt","other":"+ {count} frühere Schritte"}$json$::jsonb),
  ('de', 'pending.steps.less', $json$"nur die neuesten zeigen"$json$::jsonb),
  ('de', 'whatsNew.item.chatBubbles.title', $json$"Wer was gesagt hat, auf einen Blick"$json$::jsonb),
  ('de', 'whatsNew.item.chatBubbles.detail', $json$"Im Chat stehen Ihre Anfragen jetzt in einer gefüllten Blase rechts, und die Antworten von JayV in einem umrandeten Fenster mit einer 🤖-jayv-Leiste oben, die Agent, Modell und das Urteil der Pforte zeigt."$json$::jsonb),
  ('de', 'whatsNew.item.recentSteps.title', $json$"Nur die neuesten Schritte während einer Anfrage"$json$::jsonb),
  ('de', 'whatsNew.item.recentSteps.detail', $json$"Die Leiste „in Arbeit“ über dem Eingabefeld zeigt die 3 neuesten Schritte. Ein Knopf öffnet die ganze Liste, und die nächste Anfrage beginnt wieder eingeklappt."$json$::jsonb),
  ('de', 'whatsNew.item.readableButtons.title', $json$"Lesbare Antwortknöpfe"$json$::jsonb),
  ('de', 'whatsNew.item.readableButtons.detail', $json$"In einer Frage des Agenten hatten die Knöpfe Antworten senden, Auswahl senden und Ja Text in der Farbe des Knopfes. Jetzt sind sie im hellen und dunklen Design lesbar."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
