-- Site v1.1.0: o painel (`/dashboard`). Quem entrou ganha o botão Painel no
-- topo; dentro dele ficam as organizações — criar, convidar membros e a
-- política de LLM, renomear, sair e excluir, que saíram do app (jayv-coder) —
-- e, para o admin do
-- sistema, a Administração que já estava no site. As chaves que o painel
-- divide com o app (`org.*`, `policy.*`, `mechanism.*`, `permission.*`,
-- `jev.exit.*`, `app.*`) já estão aqui e não mudam; as `site.*` são novas.
--
-- App v0.53.0: no lugar dessas telas, o app ganha o botão que abre o painel
-- (`org.site.*`) e a entrada das Novidades (`whatsNew.item.orgAdminOnSite.*`).

insert into public.translations (locale, key, value) values
  ('pt-BR', 'site.nav.dashboard', $json$"Painel"$json$::jsonb),
  ('pt-BR', 'site.dashboard.title', $json$"Painel"$json$::jsonb),
  ('pt-BR', 'site.dashboard.label', $json$"Seções do painel"$json$::jsonb),
  ('pt-BR', 'site.dashboard.signIn', $json$"Entre para abrir o seu painel."$json$::jsonb),
  ('pt-BR', 'site.dashboard.locked', $json$"Organizações não fazem parte do seu plano. Veja os planos no app do JayV."$json$::jsonb),
  ('pt-BR', 'site.dashboard.organizations', $json$"Crie, renomeie e exclua organizações, convide pessoas e defina a política de LLM. Repositórios, papéis dos membros e os projetos da organização continuam no app do JayV."$json$::jsonb),
  ('pt-BR', 'site.org.notFound', $json$"Esta organização não existe ou você não faz mais parte dela."$json$::jsonb),
  ('pt-BR', 'site.org.invites.none', $json$"Nenhum convite pendente."$json$::jsonb),
  ('pt-BR', 'site.org.invites.readOnly', $json$"Só owners e maintainers convidam pessoas."$json$::jsonb),
  ('pt-BR', 'site.org.created', $json$"Organização {name} criada."$json$::jsonb),
  ('pt-BR', 'site.org.revoked', $json$"Convite revogado."$json$::jsonb),
  ('en', 'site.nav.dashboard', $json$"Dashboard"$json$::jsonb),
  ('en', 'site.dashboard.title', $json$"Dashboard"$json$::jsonb),
  ('en', 'site.dashboard.label', $json$"Dashboard sections"$json$::jsonb),
  ('en', 'site.dashboard.signIn', $json$"Sign in to open your dashboard."$json$::jsonb),
  ('en', 'site.dashboard.locked', $json$"Organizations aren't part of your plan. See the plans in the JayV app."$json$::jsonb),
  ('en', 'site.dashboard.organizations', $json$"Create, rename and delete organizations, invite people and set the LLM policy. Repositories, members' roles and the organization's projects stay in the JayV app."$json$::jsonb),
  ('en', 'site.org.notFound', $json$"This organization doesn't exist or you are no longer in it."$json$::jsonb),
  ('en', 'site.org.invites.none', $json$"No pending invites."$json$::jsonb),
  ('en', 'site.org.invites.readOnly', $json$"Only owners and maintainers invite people."$json$::jsonb),
  ('en', 'site.org.created', $json$"Organization {name} created."$json$::jsonb),
  ('en', 'site.org.revoked', $json$"Invite revoked."$json$::jsonb),
  ('es', 'site.nav.dashboard', $json$"Panel"$json$::jsonb),
  ('es', 'site.dashboard.title', $json$"Panel"$json$::jsonb),
  ('es', 'site.dashboard.label', $json$"Secciones del panel"$json$::jsonb),
  ('es', 'site.dashboard.signIn', $json$"Inicia sesión para abrir tu panel."$json$::jsonb),
  ('es', 'site.dashboard.locked', $json$"Las organizaciones no forman parte de tu plan. Mira los planes en la app de JayV."$json$::jsonb),
  ('es', 'site.dashboard.organizations', $json$"Crea, renombra y elimina organizaciones, invita a personas y define la política de LLM. Los repositorios, los roles de los miembros y los proyectos de la organización siguen en la app de JayV."$json$::jsonb),
  ('es', 'site.org.notFound', $json$"Esta organización no existe o ya no formas parte de ella."$json$::jsonb),
  ('es', 'site.org.invites.none', $json$"No hay invitaciones pendientes."$json$::jsonb),
  ('es', 'site.org.invites.readOnly', $json$"Solo los owners y maintainers invitan a personas."$json$::jsonb),
  ('es', 'site.org.created', $json$"Organización {name} creada."$json$::jsonb),
  ('es', 'site.org.revoked', $json$"Invitación revocada."$json$::jsonb),
  ('zh-CN', 'site.nav.dashboard', $json$"控制台"$json$::jsonb),
  ('zh-CN', 'site.dashboard.title', $json$"控制台"$json$::jsonb),
  ('zh-CN', 'site.dashboard.label', $json$"控制台栏目"$json$::jsonb),
  ('zh-CN', 'site.dashboard.signIn', $json$"登录以打开你的控制台。"$json$::jsonb),
  ('zh-CN', 'site.dashboard.locked', $json$"你的套餐不包含组织功能。请在 JayV 应用中查看套餐。"$json$::jsonb),
  ('zh-CN', 'site.dashboard.organizations', $json$"创建、重命名和删除组织，邀请成员并设置 LLM 策略。仓库、成员角色和组织的项目仍在 JayV 应用中管理。"$json$::jsonb),
  ('zh-CN', 'site.org.notFound', $json$"该组织不存在，或你已不在其中。"$json$::jsonb),
  ('zh-CN', 'site.org.invites.none', $json$"没有待处理的邀请。"$json$::jsonb),
  ('zh-CN', 'site.org.invites.readOnly', $json$"只有 owner 和 maintainer 可以邀请成员。"$json$::jsonb),
  ('zh-CN', 'site.org.created', $json$"已创建组织 {name}。"$json$::jsonb),
  ('zh-CN', 'site.org.revoked', $json$"邀请已撤销。"$json$::jsonb),
  ('hi', 'site.nav.dashboard', $json$"डैशबोर्ड"$json$::jsonb),
  ('hi', 'site.dashboard.title', $json$"डैशबोर्ड"$json$::jsonb),
  ('hi', 'site.dashboard.label', $json$"डैशबोर्ड के अनुभाग"$json$::jsonb),
  ('hi', 'site.dashboard.signIn', $json$"अपना डैशबोर्ड खोलने के लिए साइन इन करें।"$json$::jsonb),
  ('hi', 'site.dashboard.locked', $json$"संगठन आपके प्लान का हिस्सा नहीं हैं। JayV ऐप में प्लान देखें।"$json$::jsonb),
  ('hi', 'site.dashboard.organizations', $json$"संगठन बनाएँ, उनका नाम बदलें और उन्हें हटाएँ, लोगों को आमंत्रित करें और LLM नीति तय करें। रिपॉज़िटरी, सदस्यों की भूमिकाएँ और संगठन के प्रोजेक्ट JayV ऐप में ही रहते हैं।"$json$::jsonb),
  ('hi', 'site.org.notFound', $json$"यह संगठन मौजूद नहीं है या अब आप इसमें नहीं हैं।"$json$::jsonb),
  ('hi', 'site.org.invites.none', $json$"कोई लंबित आमंत्रण नहीं।"$json$::jsonb),
  ('hi', 'site.org.invites.readOnly', $json$"केवल owner और maintainer ही लोगों को आमंत्रित करते हैं।"$json$::jsonb),
  ('hi', 'site.org.created', $json$"संगठन {name} बनाया गया।"$json$::jsonb),
  ('hi', 'site.org.revoked', $json$"आमंत्रण रद्द किया गया।"$json$::jsonb),
  ('ar', 'site.nav.dashboard', $json$"لوحة التحكم"$json$::jsonb),
  ('ar', 'site.dashboard.title', $json$"لوحة التحكم"$json$::jsonb),
  ('ar', 'site.dashboard.label', $json$"أقسام لوحة التحكم"$json$::jsonb),
  ('ar', 'site.dashboard.signIn', $json$"سجّل الدخول لفتح لوحة التحكم الخاصة بك."$json$::jsonb),
  ('ar', 'site.dashboard.locked', $json$"المؤسسات ليست ضمن خطتك. اطّلع على الخطط في تطبيق JayV."$json$::jsonb),
  ('ar', 'site.dashboard.organizations', $json$"أنشئ المؤسسات وأعد تسميتها واحذفها، وادعُ أشخاصًا وحدّد سياسة LLM. تبقى المستودعات وأدوار الأعضاء ومشاريع المؤسسة في تطبيق JayV."$json$::jsonb),
  ('ar', 'site.org.notFound', $json$"هذه المؤسسة غير موجودة أو لم تعد عضوًا فيها."$json$::jsonb),
  ('ar', 'site.org.invites.none', $json$"لا توجد دعوات معلّقة."$json$::jsonb),
  ('ar', 'site.org.invites.readOnly', $json$"يدعو الأشخاصَ مالكو المؤسسة والمشرفون عليها فقط."$json$::jsonb),
  ('ar', 'site.org.created', $json$"تم إنشاء المؤسسة {name}."$json$::jsonb),
  ('ar', 'site.org.revoked', $json$"تم إلغاء الدعوة."$json$::jsonb),
  ('fr', 'site.nav.dashboard', $json$"Tableau de bord"$json$::jsonb),
  ('fr', 'site.dashboard.title', $json$"Tableau de bord"$json$::jsonb),
  ('fr', 'site.dashboard.label', $json$"Sections du tableau de bord"$json$::jsonb),
  ('fr', 'site.dashboard.signIn', $json$"Connectez-vous pour ouvrir votre tableau de bord."$json$::jsonb),
  ('fr', 'site.dashboard.locked', $json$"Les organisations ne font pas partie de votre offre. Consultez les offres dans l'app JayV."$json$::jsonb),
  ('fr', 'site.dashboard.organizations', $json$"Créez, renommez et supprimez des organisations, invitez des personnes et définissez la politique LLM. Les dépôts, les rôles des membres et les projets de l'organisation restent dans l'app JayV."$json$::jsonb),
  ('fr', 'site.org.notFound', $json$"Cette organisation n'existe pas ou vous n'en faites plus partie."$json$::jsonb),
  ('fr', 'site.org.invites.none', $json$"Aucune invitation en attente."$json$::jsonb),
  ('fr', 'site.org.invites.readOnly', $json$"Seuls les owners et les maintainers invitent des personnes."$json$::jsonb),
  ('fr', 'site.org.created', $json$"Organisation {name} créée."$json$::jsonb),
  ('fr', 'site.org.revoked', $json$"Invitation révoquée."$json$::jsonb),
  ('ru', 'site.nav.dashboard', $json$"Панель"$json$::jsonb),
  ('ru', 'site.dashboard.title', $json$"Панель"$json$::jsonb),
  ('ru', 'site.dashboard.label', $json$"Разделы панели"$json$::jsonb),
  ('ru', 'site.dashboard.signIn', $json$"Войдите, чтобы открыть свою панель."$json$::jsonb),
  ('ru', 'site.dashboard.locked', $json$"Организации не входят в ваш тариф. Посмотрите тарифы в приложении JayV."$json$::jsonb),
  ('ru', 'site.dashboard.organizations', $json$"Создавайте, переименовывайте и удаляйте организации, приглашайте людей и задавайте политику LLM. Репозитории, роли участников и проекты организации остаются в приложении JayV."$json$::jsonb),
  ('ru', 'site.org.notFound', $json$"Эта организация не существует или вы больше в ней не состоите."$json$::jsonb),
  ('ru', 'site.org.invites.none', $json$"Нет ожидающих приглашений."$json$::jsonb),
  ('ru', 'site.org.invites.readOnly', $json$"Приглашать людей могут только owner и maintainer."$json$::jsonb),
  ('ru', 'site.org.created', $json$"Организация {name} создана."$json$::jsonb),
  ('ru', 'site.org.revoked', $json$"Приглашение отозвано."$json$::jsonb),
  ('ja', 'site.nav.dashboard', $json$"ダッシュボード"$json$::jsonb),
  ('ja', 'site.dashboard.title', $json$"ダッシュボード"$json$::jsonb),
  ('ja', 'site.dashboard.label', $json$"ダッシュボードのセクション"$json$::jsonb),
  ('ja', 'site.dashboard.signIn', $json$"ダッシュボードを開くにはサインインしてください。"$json$::jsonb),
  ('ja', 'site.dashboard.locked', $json$"組織はご利用のプランに含まれていません。JayV アプリでプランをご確認ください。"$json$::jsonb),
  ('ja', 'site.dashboard.organizations', $json$"組織の作成・名前変更・削除、メンバーの招待、LLM ポリシーの設定ができます。リポジトリ、メンバーの役割、組織のプロジェクトは引き続き JayV アプリで管理します。"$json$::jsonb),
  ('ja', 'site.org.notFound', $json$"この組織は存在しないか、あなたはもう参加していません。"$json$::jsonb),
  ('ja', 'site.org.invites.none', $json$"保留中の招待はありません。"$json$::jsonb),
  ('ja', 'site.org.invites.readOnly', $json$"メンバーを招待できるのは owner と maintainer だけです。"$json$::jsonb),
  ('ja', 'site.org.created', $json$"組織 {name} を作成しました。"$json$::jsonb),
  ('ja', 'site.org.revoked', $json$"招待を取り消しました。"$json$::jsonb),
  ('de', 'site.nav.dashboard', $json$"Dashboard"$json$::jsonb),
  ('de', 'site.dashboard.title', $json$"Dashboard"$json$::jsonb),
  ('de', 'site.dashboard.label', $json$"Bereiche des Dashboards"$json$::jsonb),
  ('de', 'site.dashboard.signIn', $json$"Melde dich an, um dein Dashboard zu öffnen."$json$::jsonb),
  ('de', 'site.dashboard.locked', $json$"Organisationen sind nicht Teil deines Tarifs. Sieh dir die Tarife in der JayV-App an."$json$::jsonb),
  ('de', 'site.dashboard.organizations', $json$"Erstelle, benenne um und lösche Organisationen, lade Personen ein und lege die LLM-Richtlinie fest. Repositories, Rollen der Mitglieder und die Projekte der Organisation bleiben in der JayV-App."$json$::jsonb),
  ('de', 'site.org.notFound', $json$"Diese Organisation gibt es nicht oder du bist nicht mehr Mitglied."$json$::jsonb),
  ('de', 'site.org.invites.none', $json$"Keine offenen Einladungen."$json$::jsonb),
  ('de', 'site.org.invites.readOnly', $json$"Nur Owner und Maintainer laden Personen ein."$json$::jsonb),
  ('de', 'site.org.created', $json$"Organisation {name} erstellt."$json$::jsonb),
  ('de', 'site.org.revoked', $json$"Einladung zurückgezogen."$json$::jsonb),
  ('pt-BR', 'org.site.manage', $json$"Abrir no site"$json$::jsonb),
  ('pt-BR', 'org.site.hint', $json$"Criar organizações, convidar membros e a política de LLM mudaram para o painel do site do JayV."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgAdminOnSite.title', $json$"Organizações geridas no site"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgAdminOnSite.detail', $json$"Criar organizações, convidar membros e a política de LLM mudaram para o painel do site do JayV. O app continua com membros, repositórios, projetos e a política em vigor."$json$::jsonb),
  ('en', 'org.site.manage', $json$"Open on the site"$json$::jsonb),
  ('en', 'org.site.hint', $json$"Creating organizations, inviting members and the LLM policy moved to the dashboard on the JayV site."$json$::jsonb),
  ('en', 'whatsNew.item.orgAdminOnSite.title', $json$"Organizations managed on the site"$json$::jsonb),
  ('en', 'whatsNew.item.orgAdminOnSite.detail', $json$"Creating organizations, inviting members and the LLM policy moved to the dashboard on the JayV site. The app keeps members, repositories, projects and the policy in force."$json$::jsonb),
  ('es', 'org.site.manage', $json$"Abrir en el sitio"$json$::jsonb),
  ('es', 'org.site.hint', $json$"Crear organizaciones, invitar miembros y la política de LLM se trasladaron al panel del sitio de JayV."$json$::jsonb),
  ('es', 'whatsNew.item.orgAdminOnSite.title', $json$"Organizaciones gestionadas en el sitio"$json$::jsonb),
  ('es', 'whatsNew.item.orgAdminOnSite.detail', $json$"Crear organizaciones, invitar miembros y la política de LLM se trasladaron al panel del sitio de JayV. La app conserva los miembros, los repositorios, los proyectos y la política vigente."$json$::jsonb),
  ('zh-CN', 'org.site.manage', $json$"在网站上打开"$json$::jsonb),
  ('zh-CN', 'org.site.hint', $json$"创建组织、邀请成员和 LLM 策略已移至 JayV 网站的控制台。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgAdminOnSite.title', $json$"在网站上管理组织"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgAdminOnSite.detail', $json$"创建组织、邀请成员和 LLM 策略已移至 JayV 网站的控制台。应用中仍保留成员、仓库、项目以及生效中的策略。"$json$::jsonb),
  ('hi', 'org.site.manage', $json$"साइट पर खोलें"$json$::jsonb),
  ('hi', 'org.site.hint', $json$"संगठन बनाना, सदस्यों को आमंत्रित करना और LLM नीति अब JayV साइट के डैशबोर्ड में हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgAdminOnSite.title', $json$"संगठनों का प्रबंधन साइट पर"$json$::jsonb),
  ('hi', 'whatsNew.item.orgAdminOnSite.detail', $json$"संगठन बनाना, सदस्यों को आमंत्रित करना और LLM नीति अब JayV साइट के डैशबोर्ड में हैं। ऐप में सदस्य, रिपॉज़िटरी, प्रोजेक्ट और लागू नीति बने रहते हैं।"$json$::jsonb),
  ('ar', 'org.site.manage', $json$"فتح في الموقع"$json$::jsonb),
  ('ar', 'org.site.hint', $json$"انتقل إنشاء المؤسسات ودعوة الأعضاء وسياسة LLM إلى لوحة التحكم في موقع JayV."$json$::jsonb),
  ('ar', 'whatsNew.item.orgAdminOnSite.title', $json$"إدارة المؤسسات من الموقع"$json$::jsonb),
  ('ar', 'whatsNew.item.orgAdminOnSite.detail', $json$"انتقل إنشاء المؤسسات ودعوة الأعضاء وسياسة LLM إلى لوحة التحكم في موقع JayV. يحتفظ التطبيق بالأعضاء والمستودعات والمشاريع والسياسة السارية."$json$::jsonb),
  ('fr', 'org.site.manage', $json$"Ouvrir sur le site"$json$::jsonb),
  ('fr', 'org.site.hint', $json$"La création d'organisations, l'invitation de membres et la politique LLM sont passées au tableau de bord du site JayV."$json$::jsonb),
  ('fr', 'whatsNew.item.orgAdminOnSite.title', $json$"Organisations gérées sur le site"$json$::jsonb),
  ('fr', 'whatsNew.item.orgAdminOnSite.detail', $json$"La création d'organisations, l'invitation de membres et la politique LLM sont passées au tableau de bord du site JayV. L'app garde les membres, les dépôts, les projets et la politique en vigueur."$json$::jsonb),
  ('ru', 'org.site.manage', $json$"Открыть на сайте"$json$::jsonb),
  ('ru', 'org.site.hint', $json$"Создание организаций, приглашение участников и политика LLM переехали в панель на сайте JayV."$json$::jsonb),
  ('ru', 'whatsNew.item.orgAdminOnSite.title', $json$"Организации управляются на сайте"$json$::jsonb),
  ('ru', 'whatsNew.item.orgAdminOnSite.detail', $json$"Создание организаций, приглашение участников и политика LLM переехали в панель на сайте JayV. В приложении остаются участники, репозитории, проекты и действующая политика."$json$::jsonb),
  ('ja', 'org.site.manage', $json$"サイトで開く"$json$::jsonb),
  ('ja', 'org.site.hint', $json$"組織の作成、メンバーの招待、LLM ポリシーは JayV サイトのダッシュボードに移りました。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgAdminOnSite.title', $json$"組織の管理はサイトで"$json$::jsonb),
  ('ja', 'whatsNew.item.orgAdminOnSite.detail', $json$"組織の作成、メンバーの招待、LLM ポリシーは JayV サイトのダッシュボードに移りました。メンバー、リポジトリ、プロジェクト、適用中のポリシーは引き続きアプリにあります。"$json$::jsonb),
  ('de', 'org.site.manage', $json$"Auf der Website öffnen"$json$::jsonb),
  ('de', 'org.site.hint', $json$"Organisationen erstellen, Mitglieder einladen und die LLM-Richtlinie sind ins Dashboard der JayV-Website umgezogen."$json$::jsonb),
  ('de', 'whatsNew.item.orgAdminOnSite.title', $json$"Organisationen auf der Website verwalten"$json$::jsonb),
  ('de', 'whatsNew.item.orgAdminOnSite.detail', $json$"Organisationen erstellen, Mitglieder einladen und die LLM-Richtlinie sind ins Dashboard der JayV-Website umgezogen. Die App behält Mitglieder, Repositories, Projekte und die geltende Richtlinie."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
