-- Site 1.4.4: cada organização do JayV presa a uma organização do provedor
-- git (migração org_git_namespace), nos dez idiomas.
--   org.gitNamespaceMissing, org.repoOutsideNamespace   os erros novos
--   site.org.git.namespace*                              a escolha da organização do provedor
--   site.org.repos.pick.scope                            a lista, só dessa organização
insert into public.translations (locale, key, value) values
  ('pt-BR', 'org.gitNamespaceMissing', $json$"Escolha antes a organização do provedor git desta organização."$json$::jsonb),
  ('pt-BR', 'org.repoOutsideNamespace', $json$"Este repositório é de outra organização no provedor git."$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace', $json$"Organização: {namespace}"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.none', $json$"Escolha qual organização do {provider} é desta"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.choose', $json$"Escolher organização"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.change', $json$"Trocar organização"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.back', $json$"Voltar aos repositórios"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.title', $json$"Organização no {provider}"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.description', $json$"Esta organização do JayV fica presa a uma organização do {provider}: só os repositórios dela entram aqui, e as outras organizações do JayV escolhem a sua. Conta conectada: {account}."$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.personal', $json$"Conta pessoal"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.loading', $json$"Carregando organizações…"$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.empty', $json$"Esta conta não tem organização para escolher."$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.githubHint', $json$"A organização não aparece, ou os repositórios privados dela não vêm? No GitHub, abra Settings › Applications › Authorized OAuth Apps, selecione o JayV e conceda acesso à organização."$json$::jsonb),
  ('pt-BR', 'site.org.git.namespace.saved', $json$"Esta organização agora usa {namespace} no {provider}."$json$::jsonb),
  ('pt-BR', 'site.org.repos.pick.scope', $json$"Repositórios de {namespace} no {provider}, como {account} os vê. Marque os que são desta organização."$json$::jsonb),
  ('en', 'org.gitNamespaceMissing', $json$"Choose this organization's organization in the git provider first."$json$::jsonb),
  ('en', 'org.repoOutsideNamespace', $json$"This repository belongs to another organization in the git provider."$json$::jsonb),
  ('en', 'site.org.git.namespace', $json$"Organization: {namespace}"$json$::jsonb),
  ('en', 'site.org.git.namespace.none', $json$"Choose which {provider} organization belongs to this one"$json$::jsonb),
  ('en', 'site.org.git.namespace.choose', $json$"Choose organization"$json$::jsonb),
  ('en', 'site.org.git.namespace.change', $json$"Change organization"$json$::jsonb),
  ('en', 'site.org.git.namespace.back', $json$"Back to repositories"$json$::jsonb),
  ('en', 'site.org.git.namespace.title', $json$"{provider} organization"$json$::jsonb),
  ('en', 'site.org.git.namespace.description', $json$"This JayV organization is tied to one organization of {provider}: only its repositories can be added here, and other JayV organizations choose their own. Connected account: {account}."$json$::jsonb),
  ('en', 'site.org.git.namespace.personal', $json$"Personal account"$json$::jsonb),
  ('en', 'site.org.git.namespace.loading', $json$"Loading organizations…"$json$::jsonb),
  ('en', 'site.org.git.namespace.empty', $json$"This account has no organization to choose."$json$::jsonb),
  ('en', 'site.org.git.namespace.githubHint', $json$"Organization missing, or its private repositories not showing? On GitHub, open Settings › Applications › Authorized OAuth Apps, select JayV and grant access to the organization."$json$::jsonb),
  ('en', 'site.org.git.namespace.saved', $json$"This organization now uses {namespace} on {provider}."$json$::jsonb),
  ('en', 'site.org.repos.pick.scope', $json$"Repositories of {namespace} on {provider}, as {account} sees them. Check the ones that belong to this organization."$json$::jsonb),
  ('es', 'org.gitNamespaceMissing', $json$"Elige primero la organización del proveedor git de esta organización."$json$::jsonb),
  ('es', 'org.repoOutsideNamespace', $json$"Este repositorio pertenece a otra organización del proveedor git."$json$::jsonb),
  ('es', 'site.org.git.namespace', $json$"Organización: {namespace}"$json$::jsonb),
  ('es', 'site.org.git.namespace.none', $json$"Elige qué organización de {provider} corresponde a esta"$json$::jsonb),
  ('es', 'site.org.git.namespace.choose', $json$"Elegir organización"$json$::jsonb),
  ('es', 'site.org.git.namespace.change', $json$"Cambiar organización"$json$::jsonb),
  ('es', 'site.org.git.namespace.back', $json$"Volver a los repositorios"$json$::jsonb),
  ('es', 'site.org.git.namespace.title', $json$"Organización en {provider}"$json$::jsonb),
  ('es', 'site.org.git.namespace.description', $json$"Esta organización de JayV queda vinculada a una organización de {provider}: solo sus repositorios se pueden añadir aquí, y las otras organizaciones de JayV eligen la suya. Cuenta conectada: {account}."$json$::jsonb),
  ('es', 'site.org.git.namespace.personal', $json$"Cuenta personal"$json$::jsonb),
  ('es', 'site.org.git.namespace.loading', $json$"Cargando organizaciones…"$json$::jsonb),
  ('es', 'site.org.git.namespace.empty', $json$"Esta cuenta no tiene organizaciones para elegir."$json$::jsonb),
  ('es', 'site.org.git.namespace.githubHint', $json$"¿No aparece la organización o no se ven sus repositorios privados? En GitHub, abre Settings › Applications › Authorized OAuth Apps, selecciona JayV y concede acceso a la organización."$json$::jsonb),
  ('es', 'site.org.git.namespace.saved', $json$"Esta organización ahora usa {namespace} en {provider}."$json$::jsonb),
  ('es', 'site.org.repos.pick.scope', $json$"Repositorios de {namespace} en {provider}, tal como los ve {account}. Marca los que pertenecen a esta organización."$json$::jsonb),
  ('zh-CN', 'org.gitNamespaceMissing', $json$"请先为该组织选择 Git 提供方中的组织。"$json$::jsonb),
  ('zh-CN', 'org.repoOutsideNamespace', $json$"该仓库属于 Git 提供方中的另一个组织。"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace', $json$"组织：{namespace}"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.none', $json$"选择与此组织对应的 {provider} 组织"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.choose', $json$"选择组织"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.change', $json$"更换组织"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.back', $json$"返回仓库"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.title', $json$"{provider} 组织"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.description', $json$"此 JayV 组织绑定到 {provider} 中的一个组织：这里只能添加该组织的仓库，其他 JayV 组织各自选择自己的组织。已连接账号：{account}。"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.personal', $json$"个人账号"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.loading', $json$"正在加载组织…"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.empty', $json$"此账号没有可选择的组织。"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.githubHint', $json$"找不到组织，或看不到它的私有仓库？在 GitHub 中打开 Settings › Applications › Authorized OAuth Apps，选择 JayV 并授予对该组织的访问权限。"$json$::jsonb),
  ('zh-CN', 'site.org.git.namespace.saved', $json$"此组织现在使用 {provider} 上的 {namespace}。"$json$::jsonb),
  ('zh-CN', 'site.org.repos.pick.scope', $json$"{provider} 上 {namespace} 的仓库（以 {account} 的视角）。勾选属于此组织的仓库。"$json$::jsonb),
  ('hi', 'org.gitNamespaceMissing', $json$"पहले इस संगठन के लिए git प्रदाता में संगठन चुनें।"$json$::jsonb),
  ('hi', 'org.repoOutsideNamespace', $json$"यह रिपॉज़िटरी git प्रदाता में किसी दूसरे संगठन की है।"$json$::jsonb),
  ('hi', 'site.org.git.namespace', $json$"संगठन: {namespace}"$json$::jsonb),
  ('hi', 'site.org.git.namespace.none', $json$"चुनें कि {provider} का कौन-सा संगठन इसका है"$json$::jsonb),
  ('hi', 'site.org.git.namespace.choose', $json$"संगठन चुनें"$json$::jsonb),
  ('hi', 'site.org.git.namespace.change', $json$"संगठन बदलें"$json$::jsonb),
  ('hi', 'site.org.git.namespace.back', $json$"रिपॉज़िटरी पर लौटें"$json$::jsonb),
  ('hi', 'site.org.git.namespace.title', $json$"{provider} संगठन"$json$::jsonb),
  ('hi', 'site.org.git.namespace.description', $json$"यह JayV संगठन {provider} के एक संगठन से जुड़ा रहता है: यहाँ सिर्फ़ उसी की रिपॉज़िटरी जोड़ी जा सकती हैं, और JayV के बाकी संगठन अपना-अपना चुनते हैं। कनेक्ट किया गया खाता: {account}।"$json$::jsonb),
  ('hi', 'site.org.git.namespace.personal', $json$"निजी खाता"$json$::jsonb),
  ('hi', 'site.org.git.namespace.loading', $json$"संगठन लोड हो रहे हैं…"$json$::jsonb),
  ('hi', 'site.org.git.namespace.empty', $json$"इस खाते में चुनने के लिए कोई संगठन नहीं है।"$json$::jsonb),
  ('hi', 'site.org.git.namespace.githubHint', $json$"संगठन नहीं दिख रहा, या उसकी निजी रिपॉज़िटरी नहीं आ रहीं? GitHub पर Settings › Applications › Authorized OAuth Apps खोलें, JayV चुनें और संगठन को ऐक्सेस दें।"$json$::jsonb),
  ('hi', 'site.org.git.namespace.saved', $json$"यह संगठन अब {provider} पर {namespace} इस्तेमाल करता है।"$json$::jsonb),
  ('hi', 'site.org.repos.pick.scope', $json$"{provider} पर {namespace} की रिपॉज़िटरी, जैसा {account} उन्हें देखता है। इस संगठन की रिपॉज़िटरी चुनें।"$json$::jsonb),
  ('ar', 'org.gitNamespaceMissing', $json$"اختر أولًا مؤسسة هذه المؤسسة لدى مزوّد git."$json$::jsonb),
  ('ar', 'org.repoOutsideNamespace', $json$"هذا المستودع تابع لمؤسسة أخرى لدى مزوّد git."$json$::jsonb),
  ('ar', 'site.org.git.namespace', $json$"المؤسسة: {namespace}"$json$::jsonb),
  ('ar', 'site.org.git.namespace.none', $json$"اختر مؤسسة {provider} التابعة لهذه المؤسسة"$json$::jsonb),
  ('ar', 'site.org.git.namespace.choose', $json$"اختيار المؤسسة"$json$::jsonb),
  ('ar', 'site.org.git.namespace.change', $json$"تغيير المؤسسة"$json$::jsonb),
  ('ar', 'site.org.git.namespace.back', $json$"العودة إلى المستودعات"$json$::jsonb),
  ('ar', 'site.org.git.namespace.title', $json$"المؤسسة في {provider}"$json$::jsonb),
  ('ar', 'site.org.git.namespace.description', $json$"ترتبط مؤسسة JayV هذه بمؤسسة واحدة في {provider}: لا يمكن إضافة إلا مستودعاتها هنا، وتختار مؤسسات JayV الأخرى مؤسساتها. الحساب المرتبط: {account}."$json$::jsonb),
  ('ar', 'site.org.git.namespace.personal', $json$"حساب شخصي"$json$::jsonb),
  ('ar', 'site.org.git.namespace.loading', $json$"جارٍ تحميل المؤسسات…"$json$::jsonb),
  ('ar', 'site.org.git.namespace.empty', $json$"لا توجد مؤسسة لاختيارها في هذا الحساب."$json$::jsonb),
  ('ar', 'site.org.git.namespace.githubHint', $json$"لا تظهر المؤسسة أو لا تظهر مستودعاتها الخاصة؟ في GitHub افتح Settings › Applications › Authorized OAuth Apps واختر JayV وامنح الوصول إلى المؤسسة."$json$::jsonb),
  ('ar', 'site.org.git.namespace.saved', $json$"تستخدم هذه المؤسسة الآن {namespace} في {provider}."$json$::jsonb),
  ('ar', 'site.org.repos.pick.scope', $json$"مستودعات {namespace} في {provider} كما يراها {account}. حدّد ما يخص هذه المؤسسة."$json$::jsonb),
  ('fr', 'org.gitNamespaceMissing', $json$"Choisissez d'abord l'organisation de cette organisation chez le fournisseur git."$json$::jsonb),
  ('fr', 'org.repoOutsideNamespace', $json$"Ce dépôt appartient à une autre organisation chez le fournisseur git."$json$::jsonb),
  ('fr', 'site.org.git.namespace', $json$"Organisation : {namespace}"$json$::jsonb),
  ('fr', 'site.org.git.namespace.none', $json$"Choisissez l'organisation {provider} qui correspond à celle-ci"$json$::jsonb),
  ('fr', 'site.org.git.namespace.choose', $json$"Choisir l'organisation"$json$::jsonb),
  ('fr', 'site.org.git.namespace.change', $json$"Changer d'organisation"$json$::jsonb),
  ('fr', 'site.org.git.namespace.back', $json$"Retour aux dépôts"$json$::jsonb),
  ('fr', 'site.org.git.namespace.title', $json$"Organisation {provider}"$json$::jsonb),
  ('fr', 'site.org.git.namespace.description', $json$"Cette organisation JayV est liée à une seule organisation {provider} : seuls ses dépôts peuvent être ajoutés ici, et les autres organisations JayV choisissent la leur. Compte connecté : {account}."$json$::jsonb),
  ('fr', 'site.org.git.namespace.personal', $json$"Compte personnel"$json$::jsonb),
  ('fr', 'site.org.git.namespace.loading', $json$"Chargement des organisations…"$json$::jsonb),
  ('fr', 'site.org.git.namespace.empty', $json$"Ce compte n'a aucune organisation à choisir."$json$::jsonb),
  ('fr', 'site.org.git.namespace.githubHint', $json$"L'organisation n'apparaît pas, ou ses dépôts privés manquent ? Sur GitHub, ouvrez Settings › Applications › Authorized OAuth Apps, sélectionnez JayV et accordez l'accès à l'organisation."$json$::jsonb),
  ('fr', 'site.org.git.namespace.saved', $json$"Cette organisation utilise désormais {namespace} sur {provider}."$json$::jsonb),
  ('fr', 'site.org.repos.pick.scope', $json$"Dépôts de {namespace} sur {provider}, tels que {account} les voit. Cochez ceux qui appartiennent à cette organisation."$json$::jsonb),
  ('ru', 'org.gitNamespaceMissing', $json$"Сначала выберите организацию этой организации в git-провайдере."$json$::jsonb),
  ('ru', 'org.repoOutsideNamespace', $json$"Этот репозиторий принадлежит другой организации в git-провайдере."$json$::jsonb),
  ('ru', 'site.org.git.namespace', $json$"Организация: {namespace}"$json$::jsonb),
  ('ru', 'site.org.git.namespace.none', $json$"Выберите, какая организация {provider} относится к этой"$json$::jsonb),
  ('ru', 'site.org.git.namespace.choose', $json$"Выбрать организацию"$json$::jsonb),
  ('ru', 'site.org.git.namespace.change', $json$"Сменить организацию"$json$::jsonb),
  ('ru', 'site.org.git.namespace.back', $json$"Назад к репозиториям"$json$::jsonb),
  ('ru', 'site.org.git.namespace.title', $json$"Организация в {provider}"$json$::jsonb),
  ('ru', 'site.org.git.namespace.description', $json$"Эта организация JayV привязана к одной организации {provider}: сюда можно добавить только её репозитории, а другие организации JayV выбирают свою. Подключённая учётная запись: {account}."$json$::jsonb),
  ('ru', 'site.org.git.namespace.personal', $json$"Личная учётная запись"$json$::jsonb),
  ('ru', 'site.org.git.namespace.loading', $json$"Загрузка организаций…"$json$::jsonb),
  ('ru', 'site.org.git.namespace.empty', $json$"У этой учётной записи нет организаций для выбора."$json$::jsonb),
  ('ru', 'site.org.git.namespace.githubHint', $json$"Организации нет в списке или не видны её приватные репозитории? В GitHub откройте Settings › Applications › Authorized OAuth Apps, выберите JayV и предоставьте доступ к организации."$json$::jsonb),
  ('ru', 'site.org.git.namespace.saved', $json$"Теперь эта организация использует {namespace} в {provider}."$json$::jsonb),
  ('ru', 'site.org.repos.pick.scope', $json$"Репозитории {namespace} в {provider}, как их видит {account}. Отметьте те, что относятся к этой организации."$json$::jsonb),
  ('ja', 'org.gitNamespaceMissing', $json$"先に、この組織に対応する Git プロバイダーの組織を選んでください。"$json$::jsonb),
  ('ja', 'org.repoOutsideNamespace', $json$"このリポジトリは Git プロバイダーの別の組織のものです。"$json$::jsonb),
  ('ja', 'site.org.git.namespace', $json$"組織: {namespace}"$json$::jsonb),
  ('ja', 'site.org.git.namespace.none', $json$"この組織に対応する {provider} の組織を選んでください"$json$::jsonb),
  ('ja', 'site.org.git.namespace.choose', $json$"組織を選ぶ"$json$::jsonb),
  ('ja', 'site.org.git.namespace.change', $json$"組織を変更"$json$::jsonb),
  ('ja', 'site.org.git.namespace.back', $json$"リポジトリに戻る"$json$::jsonb),
  ('ja', 'site.org.git.namespace.title', $json$"{provider} の組織"$json$::jsonb),
  ('ja', 'site.org.git.namespace.description', $json$"この JayV の組織は {provider} の 1 つの組織に結び付きます。ここに追加できるのはその組織のリポジトリだけで、ほかの JayV の組織はそれぞれ自分の組織を選びます。接続中のアカウント: {account}。"$json$::jsonb),
  ('ja', 'site.org.git.namespace.personal', $json$"個人アカウント"$json$::jsonb),
  ('ja', 'site.org.git.namespace.loading', $json$"組織を読み込んでいます…"$json$::jsonb),
  ('ja', 'site.org.git.namespace.empty', $json$"このアカウントには選べる組織がありません。"$json$::jsonb),
  ('ja', 'site.org.git.namespace.githubHint', $json$"組織が表示されない、または非公開リポジトリが出てこない場合は、GitHub の Settings › Applications › Authorized OAuth Apps で JayV を選び、組織へのアクセスを許可してください。"$json$::jsonb),
  ('ja', 'site.org.git.namespace.saved', $json$"この組織は {provider} の {namespace} を使うようになりました。"$json$::jsonb),
  ('ja', 'site.org.repos.pick.scope', $json$"{account} から見た {provider} の {namespace} のリポジトリです。この組織のものにチェックを入れてください。"$json$::jsonb),
  ('de', 'org.gitNamespaceMissing', $json$"Wähle zuerst die Organisation dieser Organisation beim Git-Anbieter."$json$::jsonb),
  ('de', 'org.repoOutsideNamespace', $json$"Dieses Repository gehört zu einer anderen Organisation beim Git-Anbieter."$json$::jsonb),
  ('de', 'site.org.git.namespace', $json$"Organisation: {namespace}"$json$::jsonb),
  ('de', 'site.org.git.namespace.none', $json$"Wähle, welche {provider}-Organisation zu dieser gehört"$json$::jsonb),
  ('de', 'site.org.git.namespace.choose', $json$"Organisation wählen"$json$::jsonb),
  ('de', 'site.org.git.namespace.change', $json$"Organisation ändern"$json$::jsonb),
  ('de', 'site.org.git.namespace.back', $json$"Zurück zu den Repositorys"$json$::jsonb),
  ('de', 'site.org.git.namespace.title', $json$"{provider}-Organisation"$json$::jsonb),
  ('de', 'site.org.git.namespace.description', $json$"Diese JayV-Organisation ist an eine Organisation von {provider} gebunden: Nur deren Repositorys können hier hinzugefügt werden, und andere JayV-Organisationen wählen ihre eigene. Verbundenes Konto: {account}."$json$::jsonb),
  ('de', 'site.org.git.namespace.personal', $json$"Persönliches Konto"$json$::jsonb),
  ('de', 'site.org.git.namespace.loading', $json$"Organisationen werden geladen…"$json$::jsonb),
  ('de', 'site.org.git.namespace.empty', $json$"Dieses Konto hat keine Organisation zur Auswahl."$json$::jsonb),
  ('de', 'site.org.git.namespace.githubHint', $json$"Organisation fehlt oder ihre privaten Repositorys erscheinen nicht? Öffne auf GitHub Settings › Applications › Authorized OAuth Apps, wähle JayV und gewähre Zugriff auf die Organisation."$json$::jsonb),
  ('de', 'site.org.git.namespace.saved', $json$"Diese Organisation nutzt jetzt {namespace} auf {provider}."$json$::jsonb),
  ('de', 'site.org.repos.pick.scope', $json$"Repositorys von {namespace} auf {provider}, wie {account} sie sieht. Markiere die, die zu dieser Organisation gehören."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
