-- v0.47.0: ordem de preferência dos agentes no desempate e capacidades por
-- família nos modelos novos.
--
-- Só textos: o campo novo em Configuração › Jev › Roteamento, o erro de
-- validação e os itens da janela "Novidades".

insert into public.translations (locale, key, value) values
  ('pt-BR', 'core.agentOrder', $json$"Agente desconhecido na ordem de preferência: “{agent}”."$json$::jsonb),
  ('pt-BR', 'jev.agentOrder', $json$"Preferência de agente"$json$::jsonb),
  ('pt-BR', 'jev.agentOrder.hint', $json$"Quem ganha quando dois agentes têm a mesma nota para um pedido. O porte certo do modelo sempre vem primeiro."$json$::jsonb),
  ('pt-BR', 'jev.agentOrder.spread', $json$"Espalhar entre os chats"$json$::jsonb),
  ('pt-BR', 'jev.agentOrder.order', $json$"Seguir esta ordem"$json$::jsonb),
  ('pt-BR', 'jev.agentOrder.up', $json$"Subir {agent}"$json$::jsonb),
  ('pt-BR', 'jev.agentOrder.down', $json$"Descer {agent}"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentOrder.title', $json$"Escolha qual agente ganha o empate"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentOrder.detail', $json$"Em Configuração › Jev › Roteamento, a Preferência de agente define quem responde quando dois agentes têm a mesma nota para um pedido. Espalhar entre os chats mantém o comportamento atual, e Seguir esta ordem põe o seu favorito na frente. O porte de modelo que o pedido pede continua vindo primeiro."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.modelFamilies.title', $json$"Modelos pequenos não contam mais como modelos de raciocínio"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.modelFamilies.detail', $json$"Um modelo pequeno recém-descoberto (haiku, mini, flash…) chega sem a capacidade de raciocínio, então não disputa mais pedidos de análise e complexos, e os modelos da série o da OpenAI são reconhecidos como modelos grandes de raciocínio. Os modelos que você já tem mantêm as capacidades que você definiu."$json$::jsonb),
  ('en', 'core.agentOrder', $json$"Unknown agent in the preference order: “{agent}”."$json$::jsonb),
  ('en', 'jev.agentOrder', $json$"Agent preference"$json$::jsonb),
  ('en', 'jev.agentOrder.hint', $json$"Who wins when two agents score the same for a request. The right model size always comes first."$json$::jsonb),
  ('en', 'jev.agentOrder.spread', $json$"Spread across chats"$json$::jsonb),
  ('en', 'jev.agentOrder.order', $json$"Follow this order"$json$::jsonb),
  ('en', 'jev.agentOrder.up', $json$"Move {agent} up"$json$::jsonb),
  ('en', 'jev.agentOrder.down', $json$"Move {agent} down"$json$::jsonb),
  ('en', 'whatsNew.item.agentOrder.title', $json$"Choose which agent wins a tie"$json$::jsonb),
  ('en', 'whatsNew.item.agentOrder.detail', $json$"In Settings › Jev › Routing, Agent preference sets who answers when two agents score the same for a request. Spread across chats keeps the current behavior, and Follow this order puts your favorite first. The model size the request needs still comes first."$json$::jsonb),
  ('en', 'whatsNew.item.modelFamilies.title', $json$"Small models no longer count as reasoning models"$json$::jsonb),
  ('en', 'whatsNew.item.modelFamilies.detail', $json$"A newly found small model (haiku, mini, flash…) comes without the reasoning capability, so it no longer competes for analysis and complex requests, and OpenAI's o-series models are recognized as large reasoning models. Models you already have keep the capabilities you set."$json$::jsonb),
  ('es', 'core.agentOrder', $json$"Agente desconocido en el orden de preferencia: “{agent}”."$json$::jsonb),
  ('es', 'jev.agentOrder', $json$"Preferencia de agente"$json$::jsonb),
  ('es', 'jev.agentOrder.hint', $json$"Quién gana cuando dos agentes obtienen la misma nota para una solicitud. El tamaño de modelo adecuado siempre va primero."$json$::jsonb),
  ('es', 'jev.agentOrder.spread', $json$"Repartir entre los chats"$json$::jsonb),
  ('es', 'jev.agentOrder.order', $json$"Seguir este orden"$json$::jsonb),
  ('es', 'jev.agentOrder.up', $json$"Subir {agent}"$json$::jsonb),
  ('es', 'jev.agentOrder.down', $json$"Bajar {agent}"$json$::jsonb),
  ('es', 'whatsNew.item.agentOrder.title', $json$"Elige qué agente gana un empate"$json$::jsonb),
  ('es', 'whatsNew.item.agentOrder.detail', $json$"En Configuración › Jev › Enrutamiento, Preferencia de agente define quién responde cuando dos agentes obtienen la misma nota para una solicitud. Repartir entre los chats mantiene el comportamiento actual, y Seguir este orden pone a tu favorito primero. El tamaño de modelo que pide la solicitud sigue yendo primero."$json$::jsonb),
  ('es', 'whatsNew.item.modelFamilies.title', $json$"Los modelos pequeños ya no cuentan como modelos de razonamiento"$json$::jsonb),
  ('es', 'whatsNew.item.modelFamilies.detail', $json$"Un modelo pequeño recién encontrado (haiku, mini, flash…) llega sin la capacidad de razonamiento, así que ya no compite por solicitudes de análisis y complejas, y los modelos de la serie o de OpenAI se reconocen como modelos grandes de razonamiento. Los modelos que ya tienes conservan las capacidades que definiste."$json$::jsonb),
  ('zh-CN', 'core.agentOrder', $json$"优先顺序中有未知的代理:“{agent}”。"$json$::jsonb),
  ('zh-CN', 'jev.agentOrder', $json$"代理优先级"$json$::jsonb),
  ('zh-CN', 'jev.agentOrder.hint', $json$"当两个代理对某个请求得分相同时由谁来处理。合适的模型规模始终优先。"$json$::jsonb),
  ('zh-CN', 'jev.agentOrder.spread', $json$"在各对话间分配"$json$::jsonb),
  ('zh-CN', 'jev.agentOrder.order', $json$"按此顺序"$json$::jsonb),
  ('zh-CN', 'jev.agentOrder.up', $json$"上移 {agent}"$json$::jsonb),
  ('zh-CN', 'jev.agentOrder.down', $json$"下移 {agent}"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentOrder.title', $json$"选择平局时由哪个代理胜出"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentOrder.detail', $json$"在 设置 › Jev › 路由 中,“代理优先级”决定两个代理对某个请求得分相同时由谁回答。“在各对话间分配”保持现有行为,“按此顺序”让你偏爱的代理排在前面。请求所需的模型规模仍然优先。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.modelFamilies.title', $json$"小模型不再算作推理模型"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.modelFamilies.detail', $json$"新发现的小模型(haiku、mini、flash…)不再带有推理能力,因此不再争夺分析类和复杂请求;OpenAI 的 o 系列会被识别为大型推理模型。你已有的模型保留你设置的能力。"$json$::jsonb),
  ('hi', 'core.agentOrder', $json$"पसंद के क्रम में अज्ञात एजेंट: “{agent}”।"$json$::jsonb),
  ('hi', 'jev.agentOrder', $json$"एजेंट की पसंद"$json$::jsonb),
  ('hi', 'jev.agentOrder.hint', $json$"जब किसी अनुरोध के लिए दो एजेंटों का स्कोर बराबर हो तो कौन जीतता है। सही आकार का मॉडल हमेशा पहले आता है।"$json$::jsonb),
  ('hi', 'jev.agentOrder.spread', $json$"चैट्स में बाँटें"$json$::jsonb),
  ('hi', 'jev.agentOrder.order', $json$"इस क्रम का पालन करें"$json$::jsonb),
  ('hi', 'jev.agentOrder.up', $json$"{agent} को ऊपर ले जाएँ"$json$::jsonb),
  ('hi', 'jev.agentOrder.down', $json$"{agent} को नीचे ले जाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.agentOrder.title', $json$"चुनें कि बराबरी पर कौन-सा एजेंट जीते"$json$::jsonb),
  ('hi', 'whatsNew.item.agentOrder.detail', $json$"सेटिंग्स › Jev › रूटिंग में, एजेंट की पसंद तय करती है कि किसी अनुरोध के लिए दो एजेंटों का स्कोर बराबर होने पर कौन जवाब दे। चैट्स में बाँटें मौजूदा व्यवहार रखता है, और इस क्रम का पालन करें आपके पसंदीदा को सबसे आगे रखता है। अनुरोध को जिस आकार का मॉडल चाहिए, वह अब भी पहले आता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.modelFamilies.title', $json$"छोटे मॉडल अब रीज़निंग मॉडल नहीं गिने जाते"$json$::jsonb),
  ('hi', 'whatsNew.item.modelFamilies.detail', $json$"नया मिला छोटा मॉडल (haiku, mini, flash…) रीज़निंग क्षमता के बिना आता है, इसलिए वह अब विश्लेषण और जटिल अनुरोधों के लिए होड़ नहीं करता, और OpenAI की o-सीरीज़ को बड़े रीज़निंग मॉडल के रूप में पहचाना जाता है। आपके पहले से मौजूद मॉडल आपकी तय की गई क्षमताएँ रखते हैं।"$json$::jsonb),
  ('ar', 'core.agentOrder', $json$"وكيل غير معروف في ترتيب التفضيل: «{agent}»."$json$::jsonb),
  ('ar', 'jev.agentOrder', $json$"تفضيل الوكيل"$json$::jsonb),
  ('ar', 'jev.agentOrder.hint', $json$"من يفوز عندما يحصل وكيلان على الدرجة نفسها لطلب ما. حجم النموذج المناسب يأتي أولًا دائمًا."$json$::jsonb),
  ('ar', 'jev.agentOrder.spread', $json$"التوزيع على المحادثات"$json$::jsonb),
  ('ar', 'jev.agentOrder.order', $json$"اتباع هذا الترتيب"$json$::jsonb),
  ('ar', 'jev.agentOrder.up', $json$"نقل {agent} إلى الأعلى"$json$::jsonb),
  ('ar', 'jev.agentOrder.down', $json$"نقل {agent} إلى الأسفل"$json$::jsonb),
  ('ar', 'whatsNew.item.agentOrder.title', $json$"اختر الوكيل الذي يفوز عند التعادل"$json$::jsonb),
  ('ar', 'whatsNew.item.agentOrder.detail', $json$"في الإعدادات › Jev › التوجيه، يحدد «تفضيل الوكيل» من يجيب عندما يحصل وكيلان على الدرجة نفسها لطلب ما. «التوزيع على المحادثات» يُبقي السلوك الحالي، و«اتباع هذا الترتيب» يضع وكيلك المفضل أولًا. ويظل حجم النموذج الذي يحتاجه الطلب هو الأول."$json$::jsonb),
  ('ar', 'whatsNew.item.modelFamilies.title', $json$"النماذج الصغيرة لم تعد تُحسب نماذج استدلال"$json$::jsonb),
  ('ar', 'whatsNew.item.modelFamilies.detail', $json$"النموذج الصغير المكتشف حديثًا (haiku وmini وflash…) يأتي دون قدرة الاستدلال، فلا ينافس بعد الآن على طلبات التحليل والطلبات المعقدة، وتُعرَف نماذج سلسلة o من OpenAI كنماذج استدلال كبيرة. وتحتفظ النماذج الموجودة لديك بالقدرات التي حددتها."$json$::jsonb),
  ('fr', 'core.agentOrder', $json$"Agent inconnu dans l’ordre de préférence : « {agent} »."$json$::jsonb),
  ('fr', 'jev.agentOrder', $json$"Préférence d’agent"$json$::jsonb),
  ('fr', 'jev.agentOrder.hint', $json$"Qui l’emporte quand deux agents obtiennent la même note pour une demande. La bonne taille de modèle passe toujours en premier."$json$::jsonb),
  ('fr', 'jev.agentOrder.spread', $json$"Répartir entre les discussions"$json$::jsonb),
  ('fr', 'jev.agentOrder.order', $json$"Suivre cet ordre"$json$::jsonb),
  ('fr', 'jev.agentOrder.up', $json$"Monter {agent}"$json$::jsonb),
  ('fr', 'jev.agentOrder.down', $json$"Descendre {agent}"$json$::jsonb),
  ('fr', 'whatsNew.item.agentOrder.title', $json$"Choisissez l’agent qui l’emporte en cas d’égalité"$json$::jsonb),
  ('fr', 'whatsNew.item.agentOrder.detail', $json$"Dans Configuration › Jev › Routage, Préférence d’agent définit qui répond quand deux agents obtiennent la même note pour une demande. Répartir entre les discussions garde le comportement actuel, et Suivre cet ordre place votre favori en premier. La taille de modèle demandée passe toujours en premier."$json$::jsonb),
  ('fr', 'whatsNew.item.modelFamilies.title', $json$"Les petits modèles ne comptent plus comme modèles de raisonnement"$json$::jsonb),
  ('fr', 'whatsNew.item.modelFamilies.detail', $json$"Un petit modèle nouvellement trouvé (haiku, mini, flash…) arrive sans la capacité de raisonnement : il ne concourt plus pour les demandes d’analyse et complexes, et les modèles de la série o d’OpenAI sont reconnus comme de grands modèles de raisonnement. Les modèles que vous avez déjà gardent les capacités que vous avez définies."$json$::jsonb),
  ('ru', 'core.agentOrder', $json$"Неизвестный агент в порядке предпочтения: «{agent}»."$json$::jsonb),
  ('ru', 'jev.agentOrder', $json$"Предпочтение агента"$json$::jsonb),
  ('ru', 'jev.agentOrder.hint', $json$"Кто побеждает, когда два агента получают одинаковую оценку для запроса. Подходящий размер модели всегда важнее."$json$::jsonb),
  ('ru', 'jev.agentOrder.spread', $json$"Распределять между чатами"$json$::jsonb),
  ('ru', 'jev.agentOrder.order', $json$"Следовать этому порядку"$json$::jsonb),
  ('ru', 'jev.agentOrder.up', $json$"Поднять {agent}"$json$::jsonb),
  ('ru', 'jev.agentOrder.down', $json$"Опустить {agent}"$json$::jsonb),
  ('ru', 'whatsNew.item.agentOrder.title', $json$"Выберите, какой агент побеждает при равенстве"$json$::jsonb),
  ('ru', 'whatsNew.item.agentOrder.detail', $json$"В Настройки › Jev › Маршрутизация параметр «Предпочтение агента» задаёт, кто отвечает, когда два агента получают одинаковую оценку для запроса. «Распределять между чатами» сохраняет прежнее поведение, а «Следовать этому порядку» ставит вашего любимца первым. Размер модели, нужный запросу, по-прежнему важнее."$json$::jsonb),
  ('ru', 'whatsNew.item.modelFamilies.title', $json$"Маленькие модели больше не считаются моделями рассуждения"$json$::jsonb),
  ('ru', 'whatsNew.item.modelFamilies.detail', $json$"Новая найденная маленькая модель (haiku, mini, flash…) приходит без способности рассуждения, поэтому больше не претендует на аналитические и сложные запросы, а модели серии o от OpenAI распознаются как большие модели рассуждения. Уже добавленные модели сохраняют заданные вами способности."$json$::jsonb),
  ('ja', 'core.agentOrder', $json$"優先順位に不明なエージェントがあります:「{agent}」。"$json$::jsonb),
  ('ja', 'jev.agentOrder', $json$"エージェントの優先順位"$json$::jsonb),
  ('ja', 'jev.agentOrder.hint', $json$"ある依頼で2つのエージェントが同点になったとき、どちらが担当するか。適切なモデルの規模が常に優先されます。"$json$::jsonb),
  ('ja', 'jev.agentOrder.spread', $json$"チャットごとに分散"$json$::jsonb),
  ('ja', 'jev.agentOrder.order', $json$"この順番に従う"$json$::jsonb),
  ('ja', 'jev.agentOrder.up', $json$"{agent} を上へ"$json$::jsonb),
  ('ja', 'jev.agentOrder.down', $json$"{agent} を下へ"$json$::jsonb),
  ('ja', 'whatsNew.item.agentOrder.title', $json$"同点のときに選ばれるエージェントを指定"$json$::jsonb),
  ('ja', 'whatsNew.item.agentOrder.detail', $json$"設定 › Jev › ルーティングの「エージェントの優先順位」で、依頼に対して2つのエージェントが同点になったときに誰が答えるかを決められます。「チャットごとに分散」はこれまでの動作のまま、「この順番に従う」はお気に入りを先頭にします。依頼に必要なモデルの規模は引き続き最優先です。"$json$::jsonb),
  ('ja', 'whatsNew.item.modelFamilies.title', $json$"小さなモデルは推論モデルとして扱われなくなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.modelFamilies.detail', $json$"新しく見つかった小さなモデル(haiku、mini、flash…)は推論の能力なしで登録されるため、分析や複雑な依頼を取り合わなくなります。OpenAI の o シリーズは大型の推論モデルとして認識されます。既存のモデルは設定済みの能力をそのまま保ちます。"$json$::jsonb),
  ('de', 'core.agentOrder', $json$"Unbekannter Agent in der Reihenfolge: „{agent}“."$json$::jsonb),
  ('de', 'jev.agentOrder', $json$"Agent-Vorrang"$json$::jsonb),
  ('de', 'jev.agentOrder.hint', $json$"Wer gewinnt, wenn zwei Agenten für eine Anfrage gleich bewertet werden. Die passende Modellgröße kommt immer zuerst."$json$::jsonb),
  ('de', 'jev.agentOrder.spread', $json$"Auf die Chats verteilen"$json$::jsonb),
  ('de', 'jev.agentOrder.order', $json$"Dieser Reihenfolge folgen"$json$::jsonb),
  ('de', 'jev.agentOrder.up', $json$"{agent} nach oben"$json$::jsonb),
  ('de', 'jev.agentOrder.down', $json$"{agent} nach unten"$json$::jsonb),
  ('de', 'whatsNew.item.agentOrder.title', $json$"Wähle, welcher Agent bei Gleichstand gewinnt"$json$::jsonb),
  ('de', 'whatsNew.item.agentOrder.detail', $json$"Unter Einstellungen › Jev › Routing legt Agent-Vorrang fest, wer antwortet, wenn zwei Agenten für eine Anfrage gleich bewertet werden. Auf die Chats verteilen behält das bisherige Verhalten, und Dieser Reihenfolge folgen setzt deinen Favoriten nach vorn. Die Modellgröße, die die Anfrage braucht, kommt weiterhin zuerst."$json$::jsonb),
  ('de', 'whatsNew.item.modelFamilies.title', $json$"Kleine Modelle zählen nicht mehr als Reasoning-Modelle"$json$::jsonb),
  ('de', 'whatsNew.item.modelFamilies.detail', $json$"Ein neu gefundenes kleines Modell (haiku, mini, flash…) kommt ohne die Reasoning-Fähigkeit, konkurriert also nicht mehr um Analyse- und komplexe Anfragen, und die o-Serie von OpenAI wird als großes Reasoning-Modell erkannt. Vorhandene Modelle behalten die Fähigkeiten, die du festgelegt hast."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
