-- v0.70.0: todas as telas acessíveis pela paleta de comandos (Ctrl+K): grupos,
-- comandos novos, novidades e a página da documentação.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'palette.group.settings', $json$"Configurações"$json$::jsonb),
  ('en', 'palette.group.settings', $json$"Settings"$json$::jsonb),
  ('es', 'palette.group.settings', $json$"Configuración"$json$::jsonb),
  ('zh-CN', 'palette.group.settings', $json$"设置"$json$::jsonb),
  ('hi', 'palette.group.settings', $json$"सेटिंग्स"$json$::jsonb),
  ('ar', 'palette.group.settings', $json$"الإعدادات"$json$::jsonb),
  ('fr', 'palette.group.settings', $json$"Paramètres"$json$::jsonb),
  ('ru', 'palette.group.settings', $json$"Настройки"$json$::jsonb),
  ('ja', 'palette.group.settings', $json$"設定"$json$::jsonb),
  ('de', 'palette.group.settings', $json$"Einstellungen"$json$::jsonb),
  ('pt-BR', 'palette.group.stats', $json$"Estatísticas"$json$::jsonb),
  ('en', 'palette.group.stats', $json$"Statistics"$json$::jsonb),
  ('es', 'palette.group.stats', $json$"Estadísticas"$json$::jsonb),
  ('zh-CN', 'palette.group.stats', $json$"统计"$json$::jsonb),
  ('hi', 'palette.group.stats', $json$"आँकड़े"$json$::jsonb),
  ('ar', 'palette.group.stats', $json$"الإحصائيات"$json$::jsonb),
  ('fr', 'palette.group.stats', $json$"Statistiques"$json$::jsonb),
  ('ru', 'palette.group.stats', $json$"Статистика"$json$::jsonb),
  ('ja', 'palette.group.stats', $json$"統計"$json$::jsonb),
  ('de', 'palette.group.stats', $json$"Statistiken"$json$::jsonb),
  ('pt-BR', 'palette.group.organization', $json$"Esta organização"$json$::jsonb),
  ('en', 'palette.group.organization', $json$"This organization"$json$::jsonb),
  ('es', 'palette.group.organization', $json$"Esta organización"$json$::jsonb),
  ('zh-CN', 'palette.group.organization', $json$"此组织"$json$::jsonb),
  ('hi', 'palette.group.organization', $json$"यह संगठन"$json$::jsonb),
  ('ar', 'palette.group.organization', $json$"هذه المؤسسة"$json$::jsonb),
  ('fr', 'palette.group.organization', $json$"Cette organisation"$json$::jsonb),
  ('ru', 'palette.group.organization', $json$"Эта организация"$json$::jsonb),
  ('ja', 'palette.group.organization', $json$"この組織"$json$::jsonb),
  ('de', 'palette.group.organization', $json$"Diese Organisation"$json$::jsonb),
  ('pt-BR', 'palette.group.language', $json$"Idioma"$json$::jsonb),
  ('en', 'palette.group.language', $json$"Language"$json$::jsonb),
  ('es', 'palette.group.language', $json$"Idioma"$json$::jsonb),
  ('zh-CN', 'palette.group.language', $json$"语言"$json$::jsonb),
  ('hi', 'palette.group.language', $json$"भाषा"$json$::jsonb),
  ('ar', 'palette.group.language', $json$"اللغة"$json$::jsonb),
  ('fr', 'palette.group.language', $json$"Langue"$json$::jsonb),
  ('ru', 'palette.group.language', $json$"Язык"$json$::jsonb),
  ('ja', 'palette.group.language', $json$"言語"$json$::jsonb),
  ('de', 'palette.group.language', $json$"Sprache"$json$::jsonb),
  ('pt-BR', 'palette.group.account', $json$"Conta"$json$::jsonb),
  ('en', 'palette.group.account', $json$"Account"$json$::jsonb),
  ('es', 'palette.group.account', $json$"Cuenta"$json$::jsonb),
  ('zh-CN', 'palette.group.account', $json$"账户"$json$::jsonb),
  ('hi', 'palette.group.account', $json$"खाता"$json$::jsonb),
  ('ar', 'palette.group.account', $json$"الحساب"$json$::jsonb),
  ('fr', 'palette.group.account', $json$"Compte"$json$::jsonb),
  ('ru', 'palette.group.account', $json$"Аккаунт"$json$::jsonb),
  ('ja', 'palette.group.account', $json$"アカウント"$json$::jsonb),
  ('de', 'palette.group.account', $json$"Konto"$json$::jsonb),
  ('pt-BR', 'palette.language', $json$"Idioma: {name}"$json$::jsonb),
  ('en', 'palette.language', $json$"Language: {name}"$json$::jsonb),
  ('es', 'palette.language', $json$"Idioma: {name}"$json$::jsonb),
  ('zh-CN', 'palette.language', $json$"语言：{name}"$json$::jsonb),
  ('hi', 'palette.language', $json$"भाषा: {name}"$json$::jsonb),
  ('ar', 'palette.language', $json$"اللغة: {name}"$json$::jsonb),
  ('fr', 'palette.language', $json$"Langue : {name}"$json$::jsonb),
  ('ru', 'palette.language', $json$"Язык: {name}"$json$::jsonb),
  ('ja', 'palette.language', $json$"言語: {name}"$json$::jsonb),
  ('de', 'palette.language', $json$"Sprache: {name}"$json$::jsonb),
  ('pt-BR', 'palette.live', $json$"Mostrar ou ocultar os arquivos ao vivo"$json$::jsonb),
  ('en', 'palette.live', $json$"Show or hide live files"$json$::jsonb),
  ('es', 'palette.live', $json$"Mostrar u ocultar los archivos en vivo"$json$::jsonb),
  ('zh-CN', 'palette.live', $json$"显示或隐藏实时文件"$json$::jsonb),
  ('hi', 'palette.live', $json$"लाइव फ़ाइलें दिखाएँ या छिपाएँ"$json$::jsonb),
  ('ar', 'palette.live', $json$"إظهار الملفات المباشرة أو إخفاؤها"$json$::jsonb),
  ('fr', 'palette.live', $json$"Afficher ou masquer les fichiers en direct"$json$::jsonb),
  ('ru', 'palette.live', $json$"Показать или скрыть файлы в реальном времени"$json$::jsonb),
  ('ja', 'palette.live', $json$"ライブファイルを表示/非表示"$json$::jsonb),
  ('de', 'palette.live', $json$"Live-Dateien ein- oder ausblenden"$json$::jsonb),
  ('pt-BR', 'palette.stop', $json$"Parar o pedido em andamento"$json$::jsonb),
  ('en', 'palette.stop', $json$"Stop the running request"$json$::jsonb),
  ('es', 'palette.stop', $json$"Detener la solicitud en curso"$json$::jsonb),
  ('zh-CN', 'palette.stop', $json$"停止正在运行的请求"$json$::jsonb),
  ('hi', 'palette.stop', $json$"चल रहे अनुरोध को रोकें"$json$::jsonb),
  ('ar', 'palette.stop', $json$"إيقاف الطلب الجاري"$json$::jsonb),
  ('fr', 'palette.stop', $json$"Arrêter la requête en cours"$json$::jsonb),
  ('ru', 'palette.stop', $json$"Остановить выполняемый запрос"$json$::jsonb),
  ('ja', 'palette.stop', $json$"実行中のリクエストを停止"$json$::jsonb),
  ('de', 'palette.stop', $json$"Laufende Anfrage stoppen"$json$::jsonb),
  ('pt-BR', 'palette.docs', $json$"Documentação (site)"$json$::jsonb),
  ('en', 'palette.docs', $json$"Documentation (site)"$json$::jsonb),
  ('es', 'palette.docs', $json$"Documentación (sitio)"$json$::jsonb),
  ('zh-CN', 'palette.docs', $json$"文档（网站）"$json$::jsonb),
  ('hi', 'palette.docs', $json$"दस्तावेज़ (साइट)"$json$::jsonb),
  ('ar', 'palette.docs', $json$"التوثيق (الموقع)"$json$::jsonb),
  ('fr', 'palette.docs', $json$"Documentation (site)"$json$::jsonb),
  ('ru', 'palette.docs', $json$"Документация (сайт)"$json$::jsonb),
  ('ja', 'palette.docs', $json$"ドキュメント（サイト）"$json$::jsonb),
  ('de', 'palette.docs', $json$"Dokumentation (Website)"$json$::jsonb),
  ('pt-BR', 'palette.releases', $json$"Versões (site)"$json$::jsonb),
  ('en', 'palette.releases', $json$"Releases (site)"$json$::jsonb),
  ('es', 'palette.releases', $json$"Versiones (sitio)"$json$::jsonb),
  ('zh-CN', 'palette.releases', $json$"版本（网站）"$json$::jsonb),
  ('hi', 'palette.releases', $json$"रिलीज़ (साइट)"$json$::jsonb),
  ('ar', 'palette.releases', $json$"الإصدارات (الموقع)"$json$::jsonb),
  ('fr', 'palette.releases', $json$"Versions (site)"$json$::jsonb),
  ('ru', 'palette.releases', $json$"Релизы (сайт)"$json$::jsonb),
  ('ja', 'palette.releases', $json$"リリース（サイト）"$json$::jsonb),
  ('de', 'palette.releases', $json$"Releases (Website)"$json$::jsonb),
  ('pt-BR', 'palette.siteAccount', $json$"Conta no site"$json$::jsonb),
  ('en', 'palette.siteAccount', $json$"Account on the site"$json$::jsonb),
  ('es', 'palette.siteAccount', $json$"Cuenta en el sitio"$json$::jsonb),
  ('zh-CN', 'palette.siteAccount', $json$"网站上的账户"$json$::jsonb),
  ('hi', 'palette.siteAccount', $json$"साइट पर खाता"$json$::jsonb),
  ('ar', 'palette.siteAccount', $json$"الحساب على الموقع"$json$::jsonb),
  ('fr', 'palette.siteAccount', $json$"Compte sur le site"$json$::jsonb),
  ('ru', 'palette.siteAccount', $json$"Аккаунт на сайте"$json$::jsonb),
  ('ja', 'palette.siteAccount', $json$"サイトのアカウント"$json$::jsonb),
  ('de', 'palette.siteAccount', $json$"Konto auf der Website"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.paletteEverything.title', $json$"Todas as telas acessíveis pelo Ctrl+K"$json$::jsonb),
  ('en', 'whatsNew.item.paletteEverything.title', $json$"Every screen is reachable from Ctrl+K"$json$::jsonb),
  ('es', 'whatsNew.item.paletteEverything.title', $json$"Todas las pantallas accesibles con Ctrl+K"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.paletteEverything.title', $json$"所有界面都可通过 Ctrl+K 打开"$json$::jsonb),
  ('hi', 'whatsNew.item.paletteEverything.title', $json$"हर स्क्रीन Ctrl+K से पहुँच में"$json$::jsonb),
  ('ar', 'whatsNew.item.paletteEverything.title', $json$"كل الشاشات متاحة عبر Ctrl+K"$json$::jsonb),
  ('fr', 'whatsNew.item.paletteEverything.title', $json$"Tous les écrans accessibles avec Ctrl+K"$json$::jsonb),
  ('ru', 'whatsNew.item.paletteEverything.title', $json$"Все экраны доступны через Ctrl+K"$json$::jsonb),
  ('ja', 'whatsNew.item.paletteEverything.title', $json$"すべての画面を Ctrl+K から開けます"$json$::jsonb),
  ('de', 'whatsNew.item.paletteEverything.title', $json$"Jeder Bildschirm ist per Strg+K erreichbar"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.paletteEverything.detail', $json$"A paleta de comandos agora lista o que cada tela faz: projeto novo e layout, notas do projeto e busca de chats, o painel de arquivos ao vivo, parar um pedido, cada aba das Configurações com seus botões de salvar, descartar e restaurar padrões, as abas da organização, aceitar convites, idioma, tema, notificações, sair, buscar atualizações, o diagnóstico do sistema e a documentação no site."$json$::jsonb),
  ('en', 'whatsNew.item.paletteEverything.detail', $json$"The command palette now lists what each screen does: new project and layout, project notes and chat search, the live files panel, stopping a request, every Settings tab and its save, discard and defaults buttons, the organization tabs, accepting invites, language, theme, notifications, sign out, checking for updates, the system diagnostics and the documentation on the site."$json$::jsonb),
  ('es', 'whatsNew.item.paletteEverything.detail', $json$"La paleta de comandos ahora lista lo que hace cada pantalla: proyecto nuevo y diseño, notas del proyecto y búsqueda de chats, el panel de archivos en vivo, detener una solicitud, cada pestaña de Configuración con sus botones de guardar, descartar y restaurar valores, las pestañas de la organización, aceptar invitaciones, idioma, tema, notificaciones, cerrar sesión, buscar actualizaciones, el diagnóstico del sistema y la documentación del sitio."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.paletteEverything.detail', $json$"命令面板现在列出每个界面能做的事：新建项目与布局、项目笔记与聊天搜索、实时文件面板、停止请求、设置的每个标签页及其保存、放弃和恢复默认按钮、组织的各个标签页、接受邀请、语言、主题、通知、退出登录、检查更新、系统诊断以及网站上的文档。"$json$::jsonb),
  ('hi', 'whatsNew.item.paletteEverything.detail', $json$"कमांड पैलेट अब बताता है कि हर स्क्रीन क्या करती है: नया प्रोजेक्ट और लेआउट, प्रोजेक्ट नोट्स और चैट खोज, लाइव फ़ाइलें पैनल, अनुरोध रोकना, सेटिंग्स का हर टैब और उसके सहेजें, छोड़ें व डिफ़ॉल्ट बटन, संगठन के टैब, निमंत्रण स्वीकार करना, भाषा, थीम, सूचनाएँ, साइन आउट, अपडेट जाँचना, सिस्टम डायग्नोस्टिक और साइट पर दस्तावेज़।"$json$::jsonb),
  ('ar', 'whatsNew.item.paletteEverything.detail', $json$"تعرض لوحة الأوامر الآن ما تفعله كل شاشة: مشروع جديد والتخطيط، ملاحظات المشروع والبحث في المحادثات، لوحة الملفات المباشرة، إيقاف طلب، كل تبويب في الإعدادات مع أزرار الحفظ والتجاهل واستعادة الافتراضيات، تبويبات المؤسسة، قبول الدعوات، اللغة، السمة، الإشعارات، تسجيل الخروج، البحث عن تحديثات، تشخيص النظام والتوثيق على الموقع."$json$::jsonb),
  ('fr', 'whatsNew.item.paletteEverything.detail', $json$"La palette de commandes liste désormais ce que fait chaque écran : nouveau projet et disposition, notes du projet et recherche de chats, le panneau des fichiers en direct, arrêter une requête, chaque onglet des Paramètres avec ses boutons enregistrer, annuler et valeurs par défaut, les onglets de l’organisation, accepter les invitations, langue, thème, notifications, déconnexion, recherche de mises à jour, le diagnostic du système et la documentation du site."$json$::jsonb),
  ('ru', 'whatsNew.item.paletteEverything.detail', $json$"Палитра команд теперь показывает, что умеет каждый экран: новый проект и вид списка, заметки проекта и поиск по чатам, панель файлов в реальном времени, остановка запроса, каждая вкладка настроек с кнопками сохранения, отмены и значений по умолчанию, вкладки организации, принятие приглашений, язык, тема, уведомления, выход, проверка обновлений, диагностика системы и документация на сайте."$json$::jsonb),
  ('ja', 'whatsNew.item.paletteEverything.detail', $json$"コマンドパレットに各画面でできることが並ぶようになりました。新規プロジェクトとレイアウト、プロジェクトのメモとチャット検索、ライブファイルのパネル、リクエストの停止、設定の各タブと保存・破棄・初期値に戻すボタン、組織のタブ、招待の承諾、言語、テーマ、通知、サインアウト、アップデートの確認、システム診断、サイト上のドキュメントです。"$json$::jsonb),
  ('de', 'whatsNew.item.paletteEverything.detail', $json$"Die Befehlspalette listet jetzt, was jeder Bildschirm kann: neues Projekt und Layout, Projektnotizen und Chat-Suche, das Live-Dateien-Panel, eine Anfrage stoppen, jeden Einstellungs-Tab mit Speichern, Verwerfen und Standardwerten, die Tabs der Organisation, Einladungen annehmen, Sprache, Design, Benachrichtigungen, Abmelden, Updates suchen, die Systemdiagnose und die Dokumentation auf der Website."$json$::jsonb),
  ('pt-BR', 'docs.commandPalette.title', $json$"Paleta de comandos e atalhos"$json$::jsonb),
  ('en', 'docs.commandPalette.title', $json$"Command palette and shortcuts"$json$::jsonb),
  ('es', 'docs.commandPalette.title', $json$"Paleta de comandos y atajos"$json$::jsonb),
  ('zh-CN', 'docs.commandPalette.title', $json$"命令面板和快捷键"$json$::jsonb),
  ('hi', 'docs.commandPalette.title', $json$"कमांड पैलेट और शॉर्टकट"$json$::jsonb),
  ('ar', 'docs.commandPalette.title', $json$"لوحة الأوامر والاختصارات"$json$::jsonb),
  ('fr', 'docs.commandPalette.title', $json$"Palette de commandes et raccourcis"$json$::jsonb),
  ('ru', 'docs.commandPalette.title', $json$"Палитра команд и горячие клавиши"$json$::jsonb),
  ('ja', 'docs.commandPalette.title', $json$"コマンドパレットとショートカット"$json$::jsonb),
  ('de', 'docs.commandPalette.title', $json$"Befehlspalette und Tastenkürzel"$json$::jsonb),
  ('pt-BR', 'docs.commandPalette.summary', $json$"Tudo que tem botão também tem nome na paleta de comandos, e as telas principais têm atalhos de teclado."$json$::jsonb),
  ('en', 'docs.commandPalette.summary', $json$"Everything that has a button also has a name in the command palette, and the main screens have keyboard shortcuts."$json$::jsonb),
  ('es', 'docs.commandPalette.summary', $json$"Todo lo que tiene botón también tiene nombre en la paleta de comandos, y las pantallas principales tienen atajos de teclado."$json$::jsonb),
  ('zh-CN', 'docs.commandPalette.summary', $json$"所有带按钮的功能在命令面板中也有对应名称，主要界面还有键盘快捷键。"$json$::jsonb),
  ('hi', 'docs.commandPalette.summary', $json$"जिस भी चीज़ का बटन है उसका नाम कमांड पैलेट में भी है, और मुख्य स्क्रीन के कीबोर्ड शॉर्टकट हैं।"$json$::jsonb),
  ('ar', 'docs.commandPalette.summary', $json$"كل ما له زر له اسم أيضًا في لوحة الأوامر، وللشاشات الرئيسية اختصارات لوحة المفاتيح."$json$::jsonb),
  ('fr', 'docs.commandPalette.summary', $json$"Tout ce qui a un bouton a aussi un nom dans la palette de commandes, et les écrans principaux ont des raccourcis clavier."$json$::jsonb),
  ('ru', 'docs.commandPalette.summary', $json$"У всего, что есть на кнопках, есть название и в палитре команд, а у основных экранов есть горячие клавиши."$json$::jsonb),
  ('ja', 'docs.commandPalette.summary', $json$"ボタンのあるものはすべてコマンドパレットにも名前があり、主な画面にはキーボードショートカットがあります。"$json$::jsonb),
  ('de', 'docs.commandPalette.summary', $json$"Alles, was eine Schaltfläche hat, hat auch einen Namen in der Befehlspalette, und die wichtigsten Bildschirme haben Tastenkürzel."$json$::jsonb),
  ('pt-BR', 'docs.commandPalette.usage', $json$"Pressione Ctrl+K (⌘K no Mac) em qualquer tela e digite: ir para uma página ou aba das Configurações, abrir um projeto, chat ou organização (e suas abas), começar um projeto ou chat, buscar chats, abrir as notas do projeto, mostrar os arquivos ao vivo, parar um pedido, trocar o modo de trabalho, o tema ou o idioma, abrir as notificações, buscar atualizações, copiar o diagnóstico, abrir a documentação ou sair."$json$::jsonb),
  ('en', 'docs.commandPalette.usage', $json$"Press Ctrl+K (⌘K on Mac) on any screen and type: go to a page or Settings tab, open a project, chat or organization (and its tabs), start a project or chat, search chats, open project notes, show live files, stop a request, change the work mode, theme or language, open notifications, check for updates, copy the diagnostics, open the documentation or sign out."$json$::jsonb),
  ('es', 'docs.commandPalette.usage', $json$"Pulsa Ctrl+K (⌘K en Mac) en cualquier pantalla y escribe: ir a una página o pestaña de Configuración, abrir un proyecto, chat u organización (y sus pestañas), crear un proyecto o chat, buscar chats, abrir las notas del proyecto, mostrar los archivos en vivo, detener una solicitud, cambiar el modo de trabajo, el tema o el idioma, abrir las notificaciones, buscar actualizaciones, copiar el diagnóstico, abrir la documentación o cerrar sesión."$json$::jsonb),
  ('zh-CN', 'docs.commandPalette.usage', $json$"在任意界面按 Ctrl+K（Mac 上为 ⌘K）并输入：前往某个页面或设置标签页、打开项目、聊天或组织（及其标签页）、新建项目或聊天、搜索聊天、打开项目笔记、显示实时文件、停止请求、切换工作模式、主题或语言、打开通知、检查更新、复制诊断信息、打开文档或退出登录。"$json$::jsonb),
  ('hi', 'docs.commandPalette.usage', $json$"किसी भी स्क्रीन पर Ctrl+K (Mac पर ⌘K) दबाएँ और लिखें: किसी पेज या सेटिंग्स टैब पर जाएँ, प्रोजेक्ट, चैट या संगठन (और उसके टैब) खोलें, प्रोजेक्ट या चैट शुरू करें, चैट खोजें, प्रोजेक्ट नोट्स खोलें, लाइव फ़ाइलें दिखाएँ, अनुरोध रोकें, कार्य मोड, थीम या भाषा बदलें, सूचनाएँ खोलें, अपडेट जाँचें, डायग्नोस्टिक कॉपी करें, दस्तावेज़ खोलें या साइन आउट करें।"$json$::jsonb),
  ('ar', 'docs.commandPalette.usage', $json$"اضغط Ctrl+K (⌘K على Mac) في أي شاشة واكتب: الانتقال إلى صفحة أو تبويب في الإعدادات، فتح مشروع أو محادثة أو مؤسسة (وتبويباتها)، بدء مشروع أو محادثة، البحث في المحادثات، فتح ملاحظات المشروع، إظهار الملفات المباشرة، إيقاف طلب، تغيير وضع العمل أو السمة أو اللغة، فتح الإشعارات، البحث عن تحديثات، نسخ التشخيص، فتح التوثيق أو تسجيل الخروج."$json$::jsonb),
  ('fr', 'docs.commandPalette.usage', $json$"Appuyez sur Ctrl+K (⌘K sur Mac) sur n’importe quel écran et tapez : aller à une page ou à un onglet des Paramètres, ouvrir un projet, un chat ou une organisation (et ses onglets), démarrer un projet ou un chat, chercher dans les chats, ouvrir les notes du projet, afficher les fichiers en direct, arrêter une requête, changer le mode de travail, le thème ou la langue, ouvrir les notifications, rechercher des mises à jour, copier le diagnostic, ouvrir la documentation ou se déconnecter."$json$::jsonb),
  ('ru', 'docs.commandPalette.usage', $json$"Нажмите Ctrl+K (⌘K на Mac) на любом экране и введите: перейти на страницу или вкладку настроек, открыть проект, чат или организацию (и её вкладки), начать проект или чат, искать по чатам, открыть заметки проекта, показать файлы в реальном времени, остановить запрос, сменить режим работы, тему или язык, открыть уведомления, проверить обновления, скопировать диагностику, открыть документацию или выйти."$json$::jsonb),
  ('ja', 'docs.commandPalette.usage', $json$"どの画面でも Ctrl+K（Mac は ⌘K）を押して入力します。ページや設定のタブへの移動、プロジェクト・チャット・組織（とそのタブ）を開く、プロジェクトやチャットの開始、チャット検索、プロジェクトのメモを開く、ライブファイルの表示、リクエストの停止、作業モード・テーマ・言語の変更、通知を開く、アップデートの確認、診断のコピー、ドキュメントを開く、サインアウトができます。"$json$::jsonb),
  ('de', 'docs.commandPalette.usage', $json$"Drücke auf jedem Bildschirm Strg+K (⌘K auf dem Mac) und tippe: zu einer Seite oder einem Einstellungs-Tab wechseln, ein Projekt, einen Chat oder eine Organisation (und deren Tabs) öffnen, ein Projekt oder einen Chat starten, Chats durchsuchen, Projektnotizen öffnen, Live-Dateien anzeigen, eine Anfrage stoppen, Arbeitsmodus, Design oder Sprache ändern, Benachrichtigungen öffnen, nach Updates suchen, die Diagnose kopieren, die Dokumentation öffnen oder abmelden."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
