-- Os repositórios da organização neste computador: a aba Repositórios mostra
-- se cada um já está clonado, clona o que falta (com o git e as credenciais
-- de quem usa o app), liga uma pasta que já existe e procura os clones dentro
-- da pasta da organização. A página Projetos ganha o atalho "Trazer
-- repositórios" no grupo de uma organização sem projetos. Só traduções: a
-- pasta fica no computador, e o vínculo continua pela chave do remote.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'projects.org.bring', $json$"Trazer repositórios"$json$::jsonb),
  ('pt-BR', 'repos.folder.title', $json$"Pasta da organização neste computador"$json$::jsonb),
  ('pt-BR', 'repos.folder.none', $json$"Ainda não escolhida. Os clones vão para a pasta que você escolher, e este computador a guarda."$json$::jsonb),
  ('pt-BR', 'repos.folder.choose', $json$"Escolher pasta"$json$::jsonb),
  ('pt-BR', 'repos.folder.change', $json$"Trocar"$json$::jsonb),
  ('pt-BR', 'repos.folder.scan', $json$"Procurar clones"$json$::jsonb),
  ('pt-BR', 'repos.folder.pick', $json$"Onde ficam os repositórios de {org} neste computador?"$json$::jsonb),
  ('pt-BR', 'repos.folder.missing', $json$"A pasta {path} não existe."$json$::jsonb),
  ('pt-BR', 'repos.local', $json$"Neste computador"$json$::jsonb),
  ('pt-BR', 'repos.remote', $json$"Não está neste computador"$json$::jsonb),
  ('pt-BR', 'repos.open', $json$"Abrir"$json$::jsonb),
  ('pt-BR', 'repos.clone', $json$"Clonar"$json$::jsonb),
  ('pt-BR', 'repos.cloning', $json$"Clonando…"$json$::jsonb),
  ('pt-BR', 'repos.link', $json$"Já tenho"$json$::jsonb),
  ('pt-BR', 'repos.link.pick', $json$"Escolha a pasta onde {repo} está clonado"$json$::jsonb),
  ('pt-BR', 'repos.link.mismatch', $json$"Essa pasta não é um clone de {repo}: nenhum git remote dela aponta para ele."$json$::jsonb),
  ('pt-BR', 'repos.link.done', $json$"{repo} agora é um projeto"$json$::jsonb),
  ('pt-BR', 'repos.clone.done', $json$"{repo} clonado em {path}"$json$::jsonb),
  ('pt-BR', 'repos.clone.invalid', $json$"{repo} não é um repositório que dá para clonar."$json$::jsonb),
  ('pt-BR', 'repos.clone.exists', $json$"{path} já existe e não está vazia. Se for o clone, use “Já tenho”."$json$::jsonb),
  ('pt-BR', 'repos.clone.noGit', $json$"O git não está instalado neste computador. Instale e tente de novo."$json$::jsonb),
  ('pt-BR', 'repos.clone.denied', $json$"Suas credenciais do git não leem {repo}. Confira se sua conta tem acesso e se o git está logado (HTTPS) ou tem uma chave SSH. O git disse: {reason}"$json$::jsonb),
  ('pt-BR', 'repos.clone.failed', $json$"O clone falhou: {reason}"$json$::jsonb),
  ('pt-BR', 'repos.import.title', $json$"Clones encontrados"$json$::jsonb),
  ('pt-BR', 'repos.import.description', $json$"Repositórios de {org} clonados dentro de {path}. Cada um que ficar marcado vira um projeto."$json$::jsonb),
  ('pt-BR', 'repos.import.empty', $json$"Nenhum clone novo dos repositórios desta organização nesta pasta."$json$::jsonb),
  ('pt-BR', 'repos.import.add', $json${"one": "Adicionar {count} projeto", "other": "Adicionar {count} projetos"}$json$::jsonb),
  ('pt-BR', 'repos.import.done', $json${"one": "{count} projeto adicionado", "other": "{count} projetos adicionados"}$json$::jsonb),
  ('en', 'projects.org.bring', $json$"Bring repositories"$json$::jsonb),
  ('en', 'repos.folder.title', $json$"Organization folder on this computer"$json$::jsonb),
  ('en', 'repos.folder.none', $json$"Not chosen yet. Clones go into the folder you pick, and this computer remembers it."$json$::jsonb),
  ('en', 'repos.folder.choose', $json$"Choose folder"$json$::jsonb),
  ('en', 'repos.folder.change', $json$"Change"$json$::jsonb),
  ('en', 'repos.folder.scan', $json$"Find clones"$json$::jsonb),
  ('en', 'repos.folder.pick', $json$"Where do the repositories of {org} live on this computer?"$json$::jsonb),
  ('en', 'repos.folder.missing', $json$"The folder {path} does not exist."$json$::jsonb),
  ('en', 'repos.local', $json$"On this computer"$json$::jsonb),
  ('en', 'repos.remote', $json$"Not on this computer"$json$::jsonb),
  ('en', 'repos.open', $json$"Open"$json$::jsonb),
  ('en', 'repos.clone', $json$"Clone"$json$::jsonb),
  ('en', 'repos.cloning', $json$"Cloning…"$json$::jsonb),
  ('en', 'repos.link', $json$"I already have it"$json$::jsonb),
  ('en', 'repos.link.pick', $json$"Pick the folder where {repo} is cloned"$json$::jsonb),
  ('en', 'repos.link.mismatch', $json$"That folder is not a clone of {repo}: none of its git remotes points to it."$json$::jsonb),
  ('en', 'repos.link.done', $json$"{repo} is now a project"$json$::jsonb),
  ('en', 'repos.clone.done', $json$"{repo} cloned into {path}"$json$::jsonb),
  ('en', 'repos.clone.invalid', $json$"{repo} is not a repository that can be cloned."$json$::jsonb),
  ('en', 'repos.clone.exists', $json$"{path} already exists and is not empty. If it is the clone, use “I already have it”."$json$::jsonb),
  ('en', 'repos.clone.noGit', $json$"Git is not installed on this computer. Install it and try again."$json$::jsonb),
  ('en', 'repos.clone.denied', $json$"Your git credentials cannot read {repo}. Check that your account has access and that git is signed in (HTTPS) or has an SSH key. Git said: {reason}"$json$::jsonb),
  ('en', 'repos.clone.failed', $json$"The clone failed: {reason}"$json$::jsonb),
  ('en', 'repos.import.title', $json$"Clones found"$json$::jsonb),
  ('en', 'repos.import.description', $json$"Repositories of {org} cloned inside {path}. Each one you keep checked becomes a project."$json$::jsonb),
  ('en', 'repos.import.empty', $json$"No new clone of this organization's repositories in this folder."$json$::jsonb),
  ('en', 'repos.import.add', $json${"one": "Add {count} project", "other": "Add {count} projects"}$json$::jsonb),
  ('en', 'repos.import.done', $json${"one": "{count} project added", "other": "{count} projects added"}$json$::jsonb),
  ('es', 'projects.org.bring', $json$"Traer repositorios"$json$::jsonb),
  ('es', 'repos.folder.title', $json$"Carpeta de la organización en este equipo"$json$::jsonb),
  ('es', 'repos.folder.none', $json$"Aún no elegida. Los clones van a la carpeta que elijas, y este equipo la recuerda."$json$::jsonb),
  ('es', 'repos.folder.choose', $json$"Elegir carpeta"$json$::jsonb),
  ('es', 'repos.folder.change', $json$"Cambiar"$json$::jsonb),
  ('es', 'repos.folder.scan', $json$"Buscar clones"$json$::jsonb),
  ('es', 'repos.folder.pick', $json$"¿Dónde están los repositorios de {org} en este equipo?"$json$::jsonb),
  ('es', 'repos.folder.missing', $json$"La carpeta {path} no existe."$json$::jsonb),
  ('es', 'repos.local', $json$"En este equipo"$json$::jsonb),
  ('es', 'repos.remote', $json$"No está en este equipo"$json$::jsonb),
  ('es', 'repos.open', $json$"Abrir"$json$::jsonb),
  ('es', 'repos.clone', $json$"Clonar"$json$::jsonb),
  ('es', 'repos.cloning', $json$"Clonando…"$json$::jsonb),
  ('es', 'repos.link', $json$"Ya lo tengo"$json$::jsonb),
  ('es', 'repos.link.pick', $json$"Elige la carpeta donde está clonado {repo}"$json$::jsonb),
  ('es', 'repos.link.mismatch', $json$"Esa carpeta no es un clon de {repo}: ninguno de sus git remotes apunta a él."$json$::jsonb),
  ('es', 'repos.link.done', $json$"{repo} ahora es un proyecto"$json$::jsonb),
  ('es', 'repos.clone.done', $json$"{repo} clonado en {path}"$json$::jsonb),
  ('es', 'repos.clone.invalid', $json$"{repo} no es un repositorio que se pueda clonar."$json$::jsonb),
  ('es', 'repos.clone.exists', $json$"{path} ya existe y no está vacía. Si es el clon, usa “Ya lo tengo”."$json$::jsonb),
  ('es', 'repos.clone.noGit', $json$"Git no está instalado en este equipo. Instálalo e inténtalo de nuevo."$json$::jsonb),
  ('es', 'repos.clone.denied', $json$"Tus credenciales de git no pueden leer {repo}. Comprueba que tu cuenta tiene acceso y que git tiene sesión iniciada (HTTPS) o una clave SSH. Git dijo: {reason}"$json$::jsonb),
  ('es', 'repos.clone.failed', $json$"El clon falló: {reason}"$json$::jsonb),
  ('es', 'repos.import.title', $json$"Clones encontrados"$json$::jsonb),
  ('es', 'repos.import.description', $json$"Repositorios de {org} clonados dentro de {path}. Cada uno que dejes marcado se convierte en un proyecto."$json$::jsonb),
  ('es', 'repos.import.empty', $json$"No hay clones nuevos de los repositorios de esta organización en esta carpeta."$json$::jsonb),
  ('es', 'repos.import.add', $json${"one": "Añadir {count} proyecto", "other": "Añadir {count} proyectos"}$json$::jsonb),
  ('es', 'repos.import.done', $json${"one": "{count} proyecto añadido", "other": "{count} proyectos añadidos"}$json$::jsonb),
  ('zh-CN', 'projects.org.bring', $json$"导入仓库"$json$::jsonb),
  ('zh-CN', 'repos.folder.title', $json$"本机上的组织文件夹"$json$::jsonb),
  ('zh-CN', 'repos.folder.none', $json$"尚未选择。克隆会放到你选择的文件夹，本机会记住它。"$json$::jsonb),
  ('zh-CN', 'repos.folder.choose', $json$"选择文件夹"$json$::jsonb),
  ('zh-CN', 'repos.folder.change', $json$"更换"$json$::jsonb),
  ('zh-CN', 'repos.folder.scan', $json$"查找克隆"$json$::jsonb),
  ('zh-CN', 'repos.folder.pick', $json$"{org} 的仓库在本机的哪个文件夹？"$json$::jsonb),
  ('zh-CN', 'repos.folder.missing', $json$"文件夹 {path} 不存在。"$json$::jsonb),
  ('zh-CN', 'repos.local', $json$"在本机"$json$::jsonb),
  ('zh-CN', 'repos.remote', $json$"不在本机"$json$::jsonb),
  ('zh-CN', 'repos.open', $json$"打开"$json$::jsonb),
  ('zh-CN', 'repos.clone', $json$"克隆"$json$::jsonb),
  ('zh-CN', 'repos.cloning', $json$"正在克隆…"$json$::jsonb),
  ('zh-CN', 'repos.link', $json$"我已经有了"$json$::jsonb),
  ('zh-CN', 'repos.link.pick', $json$"选择 {repo} 克隆所在的文件夹"$json$::jsonb),
  ('zh-CN', 'repos.link.mismatch', $json$"该文件夹不是 {repo} 的克隆：它的 git remote 都没有指向它。"$json$::jsonb),
  ('zh-CN', 'repos.link.done', $json$"{repo} 现在是一个项目"$json$::jsonb),
  ('zh-CN', 'repos.clone.done', $json$"{repo} 已克隆到 {path}"$json$::jsonb),
  ('zh-CN', 'repos.clone.invalid', $json$"{repo} 不是可以克隆的仓库。"$json$::jsonb),
  ('zh-CN', 'repos.clone.exists', $json$"{path} 已存在且不为空。如果它就是克隆，请使用“我已经有了”。"$json$::jsonb),
  ('zh-CN', 'repos.clone.noGit', $json$"本机未安装 Git。请安装后重试。"$json$::jsonb),
  ('zh-CN', 'repos.clone.denied', $json$"你的 git 凭据无法读取 {repo}。请确认你的账号有访问权限，并且 git 已登录（HTTPS）或配置了 SSH 密钥。Git 输出：{reason}"$json$::jsonb),
  ('zh-CN', 'repos.clone.failed', $json$"克隆失败：{reason}"$json$::jsonb),
  ('zh-CN', 'repos.import.title', $json$"找到的克隆"$json$::jsonb),
  ('zh-CN', 'repos.import.description', $json$"{path} 中克隆的 {org} 仓库。保持勾选的每一个都会成为项目。"$json$::jsonb),
  ('zh-CN', 'repos.import.empty', $json$"此文件夹中没有该组织仓库的新克隆。"$json$::jsonb),
  ('zh-CN', 'repos.import.add', $json${"other": "添加 {count} 个项目"}$json$::jsonb),
  ('zh-CN', 'repos.import.done', $json${"other": "已添加 {count} 个项目"}$json$::jsonb),
  ('hi', 'projects.org.bring', $json$"रिपॉज़िटरी लाएँ"$json$::jsonb),
  ('hi', 'repos.folder.title', $json$"इस कंप्यूटर पर संगठन का फ़ोल्डर"$json$::jsonb),
  ('hi', 'repos.folder.none', $json$"अभी चुना नहीं गया। क्लोन आपके चुने फ़ोल्डर में जाते हैं, और यह कंप्यूटर उसे याद रखता है।"$json$::jsonb),
  ('hi', 'repos.folder.choose', $json$"फ़ोल्डर चुनें"$json$::jsonb),
  ('hi', 'repos.folder.change', $json$"बदलें"$json$::jsonb),
  ('hi', 'repos.folder.scan', $json$"क्लोन खोजें"$json$::jsonb),
  ('hi', 'repos.folder.pick', $json$"इस कंप्यूटर पर {org} की रिपॉज़िटरी कहाँ हैं?"$json$::jsonb),
  ('hi', 'repos.folder.missing', $json$"फ़ोल्डर {path} मौजूद नहीं है।"$json$::jsonb),
  ('hi', 'repos.local', $json$"इस कंप्यूटर पर"$json$::jsonb),
  ('hi', 'repos.remote', $json$"इस कंप्यूटर पर नहीं"$json$::jsonb),
  ('hi', 'repos.open', $json$"खोलें"$json$::jsonb),
  ('hi', 'repos.clone', $json$"क्लोन करें"$json$::jsonb),
  ('hi', 'repos.cloning', $json$"क्लोन हो रहा है…"$json$::jsonb),
  ('hi', 'repos.link', $json$"मेरे पास पहले से है"$json$::jsonb),
  ('hi', 'repos.link.pick', $json$"वह फ़ोल्डर चुनें जहाँ {repo} क्लोन है"$json$::jsonb),
  ('hi', 'repos.link.mismatch', $json$"यह फ़ोल्डर {repo} का क्लोन नहीं है: इसका कोई git remote उसकी ओर इशारा नहीं करता।"$json$::jsonb),
  ('hi', 'repos.link.done', $json$"{repo} अब एक प्रोजेक्ट है"$json$::jsonb),
  ('hi', 'repos.clone.done', $json$"{repo} को {path} में क्लोन किया गया"$json$::jsonb),
  ('hi', 'repos.clone.invalid', $json$"{repo} ऐसी रिपॉज़िटरी नहीं है जिसे क्लोन किया जा सके।"$json$::jsonb),
  ('hi', 'repos.clone.exists', $json$"{path} पहले से मौजूद है और खाली नहीं है। अगर यही क्लोन है, तो “मेरे पास पहले से है” इस्तेमाल करें।"$json$::jsonb),
  ('hi', 'repos.clone.noGit', $json$"इस कंप्यूटर पर Git इंस्टॉल नहीं है। इसे इंस्टॉल करके फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'repos.clone.denied', $json$"आपके git क्रेडेंशियल {repo} नहीं पढ़ सकते। जाँचें कि आपके खाते को एक्सेस है और git साइन इन है (HTTPS) या उसके पास SSH कुंजी है। Git ने कहा: {reason}"$json$::jsonb),
  ('hi', 'repos.clone.failed', $json$"क्लोन विफल रहा: {reason}"$json$::jsonb),
  ('hi', 'repos.import.title', $json$"मिले क्लोन"$json$::jsonb),
  ('hi', 'repos.import.description', $json$"{path} में क्लोन की गई {org} की रिपॉज़िटरी। हर चुनी हुई रिपॉज़िटरी एक प्रोजेक्ट बन जाती है।"$json$::jsonb),
  ('hi', 'repos.import.empty', $json$"इस फ़ोल्डर में इस संगठन की रिपॉज़िटरी का कोई नया क्लोन नहीं है।"$json$::jsonb),
  ('hi', 'repos.import.add', $json${"one": "{count} प्रोजेक्ट जोड़ें", "other": "{count} प्रोजेक्ट जोड़ें"}$json$::jsonb),
  ('hi', 'repos.import.done', $json${"one": "{count} प्रोजेक्ट जोड़ा गया", "other": "{count} प्रोजेक्ट जोड़े गए"}$json$::jsonb),
  ('ar', 'projects.org.bring', $json$"إحضار المستودعات"$json$::jsonb),
  ('ar', 'repos.folder.title', $json$"مجلد المؤسسة على هذا الحاسوب"$json$::jsonb),
  ('ar', 'repos.folder.none', $json$"لم يُختر بعد. تذهب النسخ إلى المجلد الذي تختاره، ويتذكره هذا الحاسوب."$json$::jsonb),
  ('ar', 'repos.folder.choose', $json$"اختيار مجلد"$json$::jsonb),
  ('ar', 'repos.folder.change', $json$"تغيير"$json$::jsonb),
  ('ar', 'repos.folder.scan', $json$"البحث عن النسخ"$json$::jsonb),
  ('ar', 'repos.folder.pick', $json$"أين توجد مستودعات {org} على هذا الحاسوب؟"$json$::jsonb),
  ('ar', 'repos.folder.missing', $json$"المجلد {path} غير موجود."$json$::jsonb),
  ('ar', 'repos.local', $json$"على هذا الحاسوب"$json$::jsonb),
  ('ar', 'repos.remote', $json$"ليس على هذا الحاسوب"$json$::jsonb),
  ('ar', 'repos.open', $json$"فتح"$json$::jsonb),
  ('ar', 'repos.clone', $json$"استنساخ"$json$::jsonb),
  ('ar', 'repos.cloning', $json$"جارٍ الاستنساخ…"$json$::jsonb),
  ('ar', 'repos.link', $json$"لدي نسخة بالفعل"$json$::jsonb),
  ('ar', 'repos.link.pick', $json$"اختر المجلد الذي استُنسخ فيه {repo}"$json$::jsonb),
  ('ar', 'repos.link.mismatch', $json$"هذا المجلد ليس نسخة من {repo}: لا يشير إليه أي git remote فيه."$json$::jsonb),
  ('ar', 'repos.link.done', $json$"أصبح {repo} مشروعًا"$json$::jsonb),
  ('ar', 'repos.clone.done', $json$"استُنسخ {repo} في {path}"$json$::jsonb),
  ('ar', 'repos.clone.invalid', $json$"{repo} ليس مستودعًا يمكن استنساخه."$json$::jsonb),
  ('ar', 'repos.clone.exists', $json$"{path} موجود بالفعل وليس فارغًا. إن كان هو النسخة، فاستخدم “لدي نسخة بالفعل”."$json$::jsonb),
  ('ar', 'repos.clone.noGit', $json$"Git غير مثبت على هذا الحاسوب. ثبّته وحاول مجددًا."$json$::jsonb),
  ('ar', 'repos.clone.denied', $json$"بيانات اعتماد git لديك لا تستطيع قراءة {repo}. تحقق من أن حسابك يملك صلاحية الوصول وأن git مسجّل الدخول (HTTPS) أو لديه مفتاح SSH. قال git: {reason}"$json$::jsonb),
  ('ar', 'repos.clone.failed', $json$"فشل الاستنساخ: {reason}"$json$::jsonb),
  ('ar', 'repos.import.title', $json$"النسخ التي عُثر عليها"$json$::jsonb),
  ('ar', 'repos.import.description', $json$"مستودعات {org} المستنسخة داخل {path}. كل ما يبقى محددًا يصبح مشروعًا."$json$::jsonb),
  ('ar', 'repos.import.empty', $json$"لا توجد نسخ جديدة من مستودعات هذه المؤسسة في هذا المجلد."$json$::jsonb),
  ('ar', 'repos.import.add', $json${"zero": "إضافة {count} مشروع", "one": "إضافة مشروع واحد", "two": "إضافة مشروعين", "few": "إضافة {count} مشاريع", "many": "إضافة {count} مشروعًا", "other": "إضافة {count} مشروع"}$json$::jsonb),
  ('ar', 'repos.import.done', $json${"zero": "لم يُضف أي مشروع", "one": "أُضيف مشروع واحد", "two": "أُضيف مشروعان", "few": "أُضيفت {count} مشاريع", "many": "أُضيف {count} مشروعًا", "other": "أُضيف {count} مشروع"}$json$::jsonb),
  ('fr', 'projects.org.bring', $json$"Récupérer les dépôts"$json$::jsonb),
  ('fr', 'repos.folder.title', $json$"Dossier de l'organisation sur cet ordinateur"$json$::jsonb),
  ('fr', 'repos.folder.none', $json$"Pas encore choisi. Les clones vont dans le dossier que vous choisissez, et cet ordinateur s'en souvient."$json$::jsonb),
  ('fr', 'repos.folder.choose', $json$"Choisir un dossier"$json$::jsonb),
  ('fr', 'repos.folder.change', $json$"Changer"$json$::jsonb),
  ('fr', 'repos.folder.scan', $json$"Chercher des clones"$json$::jsonb),
  ('fr', 'repos.folder.pick', $json$"Où se trouvent les dépôts de {org} sur cet ordinateur ?"$json$::jsonb),
  ('fr', 'repos.folder.missing', $json$"Le dossier {path} n'existe pas."$json$::jsonb),
  ('fr', 'repos.local', $json$"Sur cet ordinateur"$json$::jsonb),
  ('fr', 'repos.remote', $json$"Pas sur cet ordinateur"$json$::jsonb),
  ('fr', 'repos.open', $json$"Ouvrir"$json$::jsonb),
  ('fr', 'repos.clone', $json$"Cloner"$json$::jsonb),
  ('fr', 'repos.cloning', $json$"Clonage…"$json$::jsonb),
  ('fr', 'repos.link', $json$"Je l'ai déjà"$json$::jsonb),
  ('fr', 'repos.link.pick', $json$"Choisissez le dossier où {repo} est cloné"$json$::jsonb),
  ('fr', 'repos.link.mismatch', $json$"Ce dossier n'est pas un clone de {repo} : aucun de ses git remotes ne pointe vers lui."$json$::jsonb),
  ('fr', 'repos.link.done', $json$"{repo} est maintenant un projet"$json$::jsonb),
  ('fr', 'repos.clone.done', $json$"{repo} cloné dans {path}"$json$::jsonb),
  ('fr', 'repos.clone.invalid', $json$"{repo} n'est pas un dépôt qui peut être cloné."$json$::jsonb),
  ('fr', 'repos.clone.exists', $json$"{path} existe déjà et n'est pas vide. Si c'est le clone, utilisez « Je l'ai déjà »."$json$::jsonb),
  ('fr', 'repos.clone.noGit', $json$"Git n'est pas installé sur cet ordinateur. Installez-le et réessayez."$json$::jsonb),
  ('fr', 'repos.clone.denied', $json$"Vos identifiants git ne peuvent pas lire {repo}. Vérifiez que votre compte y a accès et que git est connecté (HTTPS) ou dispose d'une clé SSH. Git a dit : {reason}"$json$::jsonb),
  ('fr', 'repos.clone.failed', $json$"Le clonage a échoué : {reason}"$json$::jsonb),
  ('fr', 'repos.import.title', $json$"Clones trouvés"$json$::jsonb),
  ('fr', 'repos.import.description', $json$"Dépôts de {org} clonés dans {path}. Chaque dépôt coché devient un projet."$json$::jsonb),
  ('fr', 'repos.import.empty', $json$"Aucun nouveau clone des dépôts de cette organisation dans ce dossier."$json$::jsonb),
  ('fr', 'repos.import.add', $json${"one": "Ajouter {count} projet", "other": "Ajouter {count} projets"}$json$::jsonb),
  ('fr', 'repos.import.done', $json${"one": "{count} projet ajouté", "other": "{count} projets ajoutés"}$json$::jsonb),
  ('ru', 'projects.org.bring', $json$"Добавить репозитории"$json$::jsonb),
  ('ru', 'repos.folder.title', $json$"Папка организации на этом компьютере"$json$::jsonb),
  ('ru', 'repos.folder.none', $json$"Ещё не выбрана. Клоны попадают в выбранную вами папку, и этот компьютер её запоминает."$json$::jsonb),
  ('ru', 'repos.folder.choose', $json$"Выбрать папку"$json$::jsonb),
  ('ru', 'repos.folder.change', $json$"Изменить"$json$::jsonb),
  ('ru', 'repos.folder.scan', $json$"Найти клоны"$json$::jsonb),
  ('ru', 'repos.folder.pick', $json$"Где на этом компьютере лежат репозитории {org}?"$json$::jsonb),
  ('ru', 'repos.folder.missing', $json$"Папка {path} не существует."$json$::jsonb),
  ('ru', 'repos.local', $json$"На этом компьютере"$json$::jsonb),
  ('ru', 'repos.remote', $json$"Нет на этом компьютере"$json$::jsonb),
  ('ru', 'repos.open', $json$"Открыть"$json$::jsonb),
  ('ru', 'repos.clone', $json$"Клонировать"$json$::jsonb),
  ('ru', 'repos.cloning', $json$"Клонирование…"$json$::jsonb),
  ('ru', 'repos.link', $json$"Уже есть"$json$::jsonb),
  ('ru', 'repos.link.pick', $json$"Выберите папку, куда клонирован {repo}"$json$::jsonb),
  ('ru', 'repos.link.mismatch', $json$"Эта папка не клон {repo}: ни один её git remote не указывает на него."$json$::jsonb),
  ('ru', 'repos.link.done', $json$"{repo} теперь проект"$json$::jsonb),
  ('ru', 'repos.clone.done', $json$"{repo} клонирован в {path}"$json$::jsonb),
  ('ru', 'repos.clone.invalid', $json$"{repo} нельзя клонировать."$json$::jsonb),
  ('ru', 'repos.clone.exists', $json$"{path} уже существует и не пуста. Если это клон, нажмите «Уже есть»."$json$::jsonb),
  ('ru', 'repos.clone.noGit', $json$"Git не установлен на этом компьютере. Установите его и попробуйте снова."$json$::jsonb),
  ('ru', 'repos.clone.denied', $json$"Ваши учётные данные git не дают прочитать {repo}. Проверьте, что у аккаунта есть доступ и что git авторизован (HTTPS) или у него есть SSH-ключ. Git ответил: {reason}"$json$::jsonb),
  ('ru', 'repos.clone.failed', $json$"Клонирование не удалось: {reason}"$json$::jsonb),
  ('ru', 'repos.import.title', $json$"Найденные клоны"$json$::jsonb),
  ('ru', 'repos.import.description', $json$"Репозитории {org}, клонированные в {path}. Каждый отмеченный станет проектом."$json$::jsonb),
  ('ru', 'repos.import.empty', $json$"В этой папке нет новых клонов репозиториев этой организации."$json$::jsonb),
  ('ru', 'repos.import.add', $json${"one": "Добавить {count} проект", "few": "Добавить {count} проекта", "many": "Добавить {count} проектов", "other": "Добавить {count} проекта"}$json$::jsonb),
  ('ru', 'repos.import.done', $json${"one": "Добавлен {count} проект", "few": "Добавлено {count} проекта", "many": "Добавлено {count} проектов", "other": "Добавлено {count} проекта"}$json$::jsonb),
  ('ja', 'projects.org.bring', $json$"リポジトリを取り込む"$json$::jsonb),
  ('ja', 'repos.folder.title', $json$"このコンピューター上の組織フォルダー"$json$::jsonb),
  ('ja', 'repos.folder.none', $json$"まだ選択されていません。クローンは選んだフォルダーに作られ、このコンピューターが記憶します。"$json$::jsonb),
  ('ja', 'repos.folder.choose', $json$"フォルダーを選択"$json$::jsonb),
  ('ja', 'repos.folder.change', $json$"変更"$json$::jsonb),
  ('ja', 'repos.folder.scan', $json$"クローンを探す"$json$::jsonb),
  ('ja', 'repos.folder.pick', $json$"このコンピューターで {org} のリポジトリはどこにありますか？"$json$::jsonb),
  ('ja', 'repos.folder.missing', $json$"フォルダー {path} は存在しません。"$json$::jsonb),
  ('ja', 'repos.local', $json$"このコンピューターにあります"$json$::jsonb),
  ('ja', 'repos.remote', $json$"このコンピューターにはありません"$json$::jsonb),
  ('ja', 'repos.open', $json$"開く"$json$::jsonb),
  ('ja', 'repos.clone', $json$"クローン"$json$::jsonb),
  ('ja', 'repos.cloning', $json$"クローン中…"$json$::jsonb),
  ('ja', 'repos.link', $json$"すでにあります"$json$::jsonb),
  ('ja', 'repos.link.pick', $json$"{repo} がクローンされているフォルダーを選択"$json$::jsonb),
  ('ja', 'repos.link.mismatch', $json$"このフォルダーは {repo} のクローンではありません。どの git remote もそれを指していません。"$json$::jsonb),
  ('ja', 'repos.link.done', $json$"{repo} がプロジェクトになりました"$json$::jsonb),
  ('ja', 'repos.clone.done', $json$"{repo} を {path} にクローンしました"$json$::jsonb),
  ('ja', 'repos.clone.invalid', $json$"{repo} はクローンできるリポジトリではありません。"$json$::jsonb),
  ('ja', 'repos.clone.exists', $json$"{path} はすでに存在し、空ではありません。それがクローンなら「すでにあります」を使ってください。"$json$::jsonb),
  ('ja', 'repos.clone.noGit', $json$"このコンピューターに Git がインストールされていません。インストールしてもう一度お試しください。"$json$::jsonb),
  ('ja', 'repos.clone.denied', $json$"git の認証情報では {repo} を読み取れません。アカウントにアクセス権があり、git がサインイン済み（HTTPS）または SSH キーを持っているか確認してください。Git の出力: {reason}"$json$::jsonb),
  ('ja', 'repos.clone.failed', $json$"クローンに失敗しました: {reason}"$json$::jsonb),
  ('ja', 'repos.import.title', $json$"見つかったクローン"$json$::jsonb),
  ('ja', 'repos.import.description', $json$"{path} 内にクローンされた {org} のリポジトリです。チェックしたものがそれぞれプロジェクトになります。"$json$::jsonb),
  ('ja', 'repos.import.empty', $json$"このフォルダーにこの組織のリポジトリの新しいクローンはありません。"$json$::jsonb),
  ('ja', 'repos.import.add', $json${"other": "{count} 件のプロジェクトを追加"}$json$::jsonb),
  ('ja', 'repos.import.done', $json${"other": "{count} 件のプロジェクトを追加しました"}$json$::jsonb),
  ('de', 'projects.org.bring', $json$"Repositorys holen"$json$::jsonb),
  ('de', 'repos.folder.title', $json$"Organisationsordner auf diesem Computer"$json$::jsonb),
  ('de', 'repos.folder.none', $json$"Noch nicht gewählt. Klone landen im Ordner, den du wählst, und dieser Computer merkt ihn sich."$json$::jsonb),
  ('de', 'repos.folder.choose', $json$"Ordner wählen"$json$::jsonb),
  ('de', 'repos.folder.change', $json$"Ändern"$json$::jsonb),
  ('de', 'repos.folder.scan', $json$"Klone suchen"$json$::jsonb),
  ('de', 'repos.folder.pick', $json$"Wo liegen die Repositorys von {org} auf diesem Computer?"$json$::jsonb),
  ('de', 'repos.folder.missing', $json$"Der Ordner {path} existiert nicht."$json$::jsonb),
  ('de', 'repos.local', $json$"Auf diesem Computer"$json$::jsonb),
  ('de', 'repos.remote', $json$"Nicht auf diesem Computer"$json$::jsonb),
  ('de', 'repos.open', $json$"Öffnen"$json$::jsonb),
  ('de', 'repos.clone', $json$"Klonen"$json$::jsonb),
  ('de', 'repos.cloning', $json$"Wird geklont…"$json$::jsonb),
  ('de', 'repos.link', $json$"Habe ich schon"$json$::jsonb),
  ('de', 'repos.link.pick', $json$"Wähle den Ordner, in dem {repo} geklont ist"$json$::jsonb),
  ('de', 'repos.link.mismatch', $json$"Dieser Ordner ist kein Klon von {repo}: keines seiner git remotes zeigt darauf."$json$::jsonb),
  ('de', 'repos.link.done', $json$"{repo} ist jetzt ein Projekt"$json$::jsonb),
  ('de', 'repos.clone.done', $json$"{repo} nach {path} geklont"$json$::jsonb),
  ('de', 'repos.clone.invalid', $json$"{repo} ist kein Repository, das sich klonen lässt."$json$::jsonb),
  ('de', 'repos.clone.exists', $json$"{path} existiert bereits und ist nicht leer. Wenn es der Klon ist, nutze „Habe ich schon“."$json$::jsonb),
  ('de', 'repos.clone.noGit', $json$"Git ist auf diesem Computer nicht installiert. Installiere es und versuche es erneut."$json$::jsonb),
  ('de', 'repos.clone.denied', $json$"Deine git-Zugangsdaten können {repo} nicht lesen. Prüfe, ob dein Konto Zugriff hat und git angemeldet ist (HTTPS) oder einen SSH-Schlüssel hat. Git meldete: {reason}"$json$::jsonb),
  ('de', 'repos.clone.failed', $json$"Das Klonen ist fehlgeschlagen: {reason}"$json$::jsonb),
  ('de', 'repos.import.title', $json$"Gefundene Klone"$json$::jsonb),
  ('de', 'repos.import.description', $json$"Repositorys von {org}, geklont in {path}. Jedes markierte wird ein Projekt."$json$::jsonb),
  ('de', 'repos.import.empty', $json$"Kein neuer Klon der Repositorys dieser Organisation in diesem Ordner."$json$::jsonb),
  ('de', 'repos.import.add', $json${"one": "{count} Projekt hinzufügen", "other": "{count} Projekte hinzufügen"}$json$::jsonb),
  ('de', 'repos.import.done', $json${"one": "{count} Projekt hinzugefügt", "other": "{count} Projekte hinzugefügt"}$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
