-- O agente que não está instalado, o que não inicia e o que é achado mas não
-- responde; e o aviso de que a tela confere os agentes sozinha.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'provider.notInstalled', $json$"O agente “{provider}” não foi encontrado (comando `{command}`). Instale o CLI ou informe o caminho completo em Configurações."$json$::jsonb),
  ('pt-BR', 'provider.start', $json$"Não foi possível iniciar o agente “{provider}” em {path}: {reason}"$json$::jsonb),
  ('pt-BR', 'agent.silent', $json$"Encontrado em {path}, mas não respondeu a `--version`. Confira a instalação (os CLIs do npm precisam do Node 22 ou mais novo)."$json$::jsonb),
  ('pt-BR', 'agent.watching', $json$"conferido a cada {seconds}s"$json$::jsonb),
  ('en', 'provider.notInstalled', $json$"The agent “{provider}” was not found (command `{command}`). Install the CLI or enter its full path in Settings."$json$::jsonb),
  ('en', 'provider.start', $json$"Could not start the agent “{provider}” at {path}: {reason}"$json$::jsonb),
  ('en', 'agent.silent', $json$"Found at {path}, but it did not answer `--version`. Check the installation (npm CLIs need Node 22 or later)."$json$::jsonb),
  ('en', 'agent.watching', $json$"checked every {seconds}s"$json$::jsonb),
  ('es', 'provider.notInstalled', $json$"No se encontró el agente “{provider}” (comando `{command}`). Instala la CLI o indica la ruta completa en Configuración."$json$::jsonb),
  ('es', 'provider.start', $json$"No se pudo iniciar el agente “{provider}” en {path}: {reason}"$json$::jsonb),
  ('es', 'agent.silent', $json$"Encontrado en {path}, pero no respondió a `--version`. Revisa la instalación (las CLI de npm necesitan Node 22 o posterior)."$json$::jsonb),
  ('es', 'agent.watching', $json$"verificado cada {seconds}s"$json$::jsonb),
  ('zh-CN', 'provider.notInstalled', $json$"找不到代理“{provider}”（命令 `{command}`）。请安装该 CLI，或在设置中填写完整路径。"$json$::jsonb),
  ('zh-CN', 'provider.start', $json$"无法启动位于 {path} 的代理“{provider}”：{reason}"$json$::jsonb),
  ('zh-CN', 'agent.silent', $json$"已在 {path} 找到，但它没有响应 `--version`。请检查安装（npm 安装的 CLI 需要 Node 22 或更高版本）。"$json$::jsonb),
  ('zh-CN', 'agent.watching', $json$"每 {seconds} 秒检查一次"$json$::jsonb),
  ('hi', 'provider.notInstalled', $json$"एजेंट “{provider}” नहीं मिला (कमांड `{command}`)। CLI इंस्टॉल करें या सेटिंग्स में पूरा पथ दर्ज करें।"$json$::jsonb),
  ('hi', 'provider.start', $json$"{path} पर एजेंट “{provider}” शुरू नहीं हो सका: {reason}"$json$::jsonb),
  ('hi', 'agent.silent', $json$"{path} पर मिला, लेकिन इसने `--version` का जवाब नहीं दिया। इंस्टॉलेशन जाँचें (npm वाले CLI को Node 22 या नया चाहिए)।"$json$::jsonb),
  ('hi', 'agent.watching', $json$"हर {seconds} सेकंड में जाँचा जाता है"$json$::jsonb),
  ('ar', 'provider.notInstalled', $json$"لم يتم العثور على الوكيل «{provider}» (الأمر `{command}`). ثبّت واجهة CLI أو أدخل مسارها الكامل في الإعدادات."$json$::jsonb),
  ('ar', 'provider.start', $json$"تعذّر تشغيل الوكيل «{provider}» في {path}: {reason}"$json$::jsonb),
  ('ar', 'agent.silent', $json$"موجود في {path} لكنه لم يستجب لـ `--version`. تحقّق من التثبيت (تحتاج واجهات CLI من npm إلى Node 22 أو أحدث)."$json$::jsonb),
  ('ar', 'agent.watching', $json$"يُفحص كل {seconds} ث"$json$::jsonb),
  ('fr', 'provider.notInstalled', $json$"L'agent « {provider} » est introuvable (commande `{command}`). Installez la CLI ou indiquez son chemin complet dans les réglages."$json$::jsonb),
  ('fr', 'provider.start', $json$"Impossible de démarrer l'agent « {provider} » à {path} : {reason}"$json$::jsonb),
  ('fr', 'agent.silent', $json$"Trouvé à {path}, mais il n'a pas répondu à `--version`. Vérifiez l'installation (les CLI npm demandent Node 22 ou plus récent)."$json$::jsonb),
  ('fr', 'agent.watching', $json$"vérifié toutes les {seconds} s"$json$::jsonb),
  ('ru', 'provider.notInstalled', $json$"Агент «{provider}» не найден (команда `{command}`). Установите CLI или укажите полный путь в настройках."$json$::jsonb),
  ('ru', 'provider.start', $json$"Не удалось запустить агента «{provider}» по пути {path}: {reason}"$json$::jsonb),
  ('ru', 'agent.silent', $json$"Найден по пути {path}, но не ответил на `--version`. Проверьте установку (CLI из npm нужен Node 22 или новее)."$json$::jsonb),
  ('ru', 'agent.watching', $json$"проверяется каждые {seconds} с"$json$::jsonb),
  ('ja', 'provider.notInstalled', $json$"エージェント「{provider}」が見つかりません（コマンド `{command}`）。CLI をインストールするか、設定でフルパスを入力してください。"$json$::jsonb),
  ('ja', 'provider.start', $json$"{path} のエージェント「{provider}」を起動できませんでした: {reason}"$json$::jsonb),
  ('ja', 'agent.silent', $json$"{path} で見つかりましたが、`--version` に応答しませんでした。インストールを確認してください（npm の CLI には Node 22 以降が必要です）。"$json$::jsonb),
  ('ja', 'agent.watching', $json$"{seconds} 秒ごとに確認"$json$::jsonb),
  ('de', 'provider.notInstalled', $json$"Der Agent „{provider}“ wurde nicht gefunden (Befehl `{command}`). Installiere die CLI oder gib in den Einstellungen den vollständigen Pfad an."$json$::jsonb),
  ('de', 'provider.start', $json$"Der Agent „{provider}“ unter {path} konnte nicht gestartet werden: {reason}"$json$::jsonb),
  ('de', 'agent.silent', $json$"Gefunden unter {path}, aber es hat nicht auf `--version` geantwortet. Prüfe die Installation (npm-CLIs brauchen Node 22 oder neuer)."$json$::jsonb),
  ('de', 'agent.watching', $json$"alle {seconds} s geprüft"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
