-- v0.48.0: segunda opinião. Depois de uma mudança no modo build, um agente
-- de outro provedor lê o diff em somente leitura e aponta problemas.
--
-- Só textos: a etapa da revisão no chat, a opção em Configuração › Jev ›
-- Roteamento e o item da janela "Novidades".

insert into public.translations (locale, key, value) values
  ('pt-BR', 'beat.review', $json$"{agent} · {model} está revisando o(s) {count} arquivo(s) alterado(s)"$json$::jsonb),
  ('pt-BR', 'jev.review', $json$"Segunda opinião de outro agente"$json$::jsonb),
  ('pt-BR', 'jev.review.hint', $json$"Depois de uma mudança no modo build, um agente de outro provedor lê o diff em somente leitura e lista os problemas no fim da resposta. Custa uma chamada a mais de agente por mudança."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.secondOpinion.title', $json$"Outro agente revisa o que o primeiro mudou"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.secondOpinion.detail', $json$"Ligue Segunda opinião de outro agente em Configuração › Jev › Roteamento. Depois que um pedido muda o projeto no modo build, um agente de outro provedor lê o diff sem editar nada e lista no fim da resposta os problemas que encontrar. Arquivos privados vão só pelo nome, e com um único agente ligado nada muda."$json$::jsonb),
  ('en', 'beat.review', $json$"{agent} · {model} is reviewing the {count} changed file(s)"$json$::jsonb),
  ('en', 'jev.review', $json$"Second opinion from another agent"$json$::jsonb),
  ('en', 'jev.review.hint', $json$"After a change in build mode, an agent from another provider reads the diff in read-only mode and lists problems at the end of the answer. It costs one more agent call per change."$json$::jsonb),
  ('en', 'whatsNew.item.secondOpinion.title', $json$"Another agent reviews what the first one changed"$json$::jsonb),
  ('en', 'whatsNew.item.secondOpinion.detail', $json$"Turn on Second opinion from another agent in Settings › Jev › Routing. After a request changes the project in build mode, an agent from another provider reads the diff without editing anything and lists the problems it finds at the end of the answer. Private files go by name only, and with a single agent enabled nothing changes."$json$::jsonb),
  ('es', 'beat.review', $json$"{agent} · {model} está revisando {count} archivo(s) modificado(s)"$json$::jsonb),
  ('es', 'jev.review', $json$"Segunda opinión de otro agente"$json$::jsonb),
  ('es', 'jev.review.hint', $json$"Después de un cambio en modo build, un agente de otro proveedor lee el diff en solo lectura y enumera los problemas al final de la respuesta. Cuesta una llamada de agente más por cambio."$json$::jsonb),
  ('es', 'whatsNew.item.secondOpinion.title', $json$"Otro agente revisa lo que cambió el primero"$json$::jsonb),
  ('es', 'whatsNew.item.secondOpinion.detail', $json$"Activa Segunda opinión de otro agente en Configuración › Jev › Enrutamiento. Cuando una solicitud cambia el proyecto en modo build, un agente de otro proveedor lee el diff sin editar nada y enumera al final de la respuesta los problemas que encuentre. Los archivos privados van solo por nombre, y con un solo agente activado nada cambia."$json$::jsonb),
  ('zh-CN', 'beat.review', $json$"{agent} · {model} 正在审查 {count} 个已更改的文件"$json$::jsonb),
  ('zh-CN', 'jev.review', $json$"由另一个代理提供第二意见"$json$::jsonb),
  ('zh-CN', 'jev.review.hint', $json$"在 build 模式下修改后,另一个提供方的代理以只读方式阅读 diff,并在回答末尾列出问题。每次修改会多一次代理调用。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.secondOpinion.title', $json$"另一个代理审查第一个代理所做的修改"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.secondOpinion.detail', $json$"在 设置 › Jev › 路由 中打开“由另一个代理提供第二意见”。当请求在 build 模式下修改项目后,另一个提供方的代理会在不编辑任何内容的情况下阅读 diff,并在回答末尾列出发现的问题。私有文件只传文件名,只启用一个代理时不会有任何变化。"$json$::jsonb),
  ('hi', 'beat.review', $json$"{agent} · {model} बदली गई {count} फ़ाइल(ों) की समीक्षा कर रहा है"$json$::jsonb),
  ('hi', 'jev.review', $json$"दूसरे एजेंट की दूसरी राय"$json$::jsonb),
  ('hi', 'jev.review.hint', $json$"बिल्ड मोड में बदलाव के बाद, दूसरे प्रदाता का एजेंट केवल-पढ़ने के मोड में diff पढ़ता है और जवाब के अंत में समस्याएँ बताता है। हर बदलाव पर एक एजेंट कॉल ज़्यादा लगती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.secondOpinion.title', $json$"पहले एजेंट के बदलावों की समीक्षा दूसरा एजेंट करता है"$json$::jsonb),
  ('hi', 'whatsNew.item.secondOpinion.detail', $json$"सेटिंग्स › Jev › रूटिंग में दूसरे एजेंट की दूसरी राय चालू करें। जब कोई अनुरोध बिल्ड मोड में प्रोजेक्ट बदलता है, तो दूसरे प्रदाता का एजेंट कुछ भी संपादित किए बिना diff पढ़ता है और जो समस्याएँ मिलती हैं उन्हें जवाब के अंत में बताता है। निजी फ़ाइलें केवल नाम से जाती हैं, और केवल एक एजेंट चालू होने पर कुछ नहीं बदलता।"$json$::jsonb),
  ('ar', 'beat.review', $json$"{agent} · {model} يراجع {count} ملفًا معدّلًا"$json$::jsonb),
  ('ar', 'jev.review', $json$"رأي ثانٍ من وكيل آخر"$json$::jsonb),
  ('ar', 'jev.review.hint', $json$"بعد أي تعديل في وضع البناء، يقرأ وكيل من مزوّد آخر الفروقات في وضع القراءة فقط ويسرد المشكلات في نهاية الرد. يكلّف ذلك استدعاءً إضافيًا لوكيل في كل تعديل."$json$::jsonb),
  ('ar', 'whatsNew.item.secondOpinion.title', $json$"وكيل آخر يراجع ما عدّله الأول"$json$::jsonb),
  ('ar', 'whatsNew.item.secondOpinion.detail', $json$"فعّل «رأي ثانٍ من وكيل آخر» في الإعدادات › Jev › التوجيه. بعد أن يعدّل طلبٌ المشروع في وضع البناء، يقرأ وكيل من مزوّد آخر الفروقات دون تعديل أي شيء ويسرد المشكلات التي يجدها في نهاية الرد. تُرسَل الملفات الخاصة بأسمائها فقط، ومع وكيل واحد مفعّل لا يتغير شيء."$json$::jsonb),
  ('fr', 'beat.review', $json$"{agent} · {model} relit le(s) {count} fichier(s) modifié(s)"$json$::jsonb),
  ('fr', 'jev.review', $json$"Deuxième avis d’un autre agent"$json$::jsonb),
  ('fr', 'jev.review.hint', $json$"Après une modification en mode build, un agent d’un autre fournisseur lit le diff en lecture seule et liste les problèmes à la fin de la réponse. Cela coûte un appel d’agent de plus par modification."$json$::jsonb),
  ('fr', 'whatsNew.item.secondOpinion.title', $json$"Un autre agent relit ce que le premier a modifié"$json$::jsonb),
  ('fr', 'whatsNew.item.secondOpinion.detail', $json$"Activez Deuxième avis d’un autre agent dans Configuration › Jev › Routage. Quand une demande modifie le projet en mode build, un agent d’un autre fournisseur lit le diff sans rien modifier et liste à la fin de la réponse les problèmes qu’il trouve. Les fichiers privés ne sont transmis que par leur nom, et avec un seul agent activé rien ne change."$json$::jsonb),
  ('ru', 'beat.review', $json$"{agent} · {model} проверяет изменённые файлы: {count}"$json$::jsonb),
  ('ru', 'jev.review', $json$"Второе мнение другого агента"$json$::jsonb),
  ('ru', 'jev.review.hint', $json$"После изменения в режиме build агент другого провайдера читает diff в режиме только чтения и перечисляет проблемы в конце ответа. Это ещё один вызов агента на каждое изменение."$json$::jsonb),
  ('ru', 'whatsNew.item.secondOpinion.title', $json$"Другой агент проверяет то, что изменил первый"$json$::jsonb),
  ('ru', 'whatsNew.item.secondOpinion.detail', $json$"Включите «Второе мнение другого агента» в Настройки › Jev › Маршрутизация. Когда запрос меняет проект в режиме build, агент другого провайдера читает diff, ничего не редактируя, и перечисляет найденные проблемы в конце ответа. Приватные файлы передаются только по имени, а при одном включённом агенте ничего не меняется."$json$::jsonb),
  ('ja', 'beat.review', $json$"{agent} · {model} が変更された {count} 個のファイルをレビュー中"$json$::jsonb),
  ('ja', 'jev.review', $json$"別のエージェントによるセカンドオピニオン"$json$::jsonb),
  ('ja', 'jev.review.hint', $json$"build モードで変更したあと、別のプロバイダーのエージェントが読み取り専用で diff を読み、問題点を回答の最後に挙げます。変更ごとにエージェントの呼び出しが1回増えます。"$json$::jsonb),
  ('ja', 'whatsNew.item.secondOpinion.title', $json$"最初のエージェントの変更を別のエージェントがレビュー"$json$::jsonb),
  ('ja', 'whatsNew.item.secondOpinion.detail', $json$"設定 › Jev › ルーティングで「別のエージェントによるセカンドオピニオン」をオンにしてください。依頼が build モードでプロジェクトを変更すると、別のプロバイダーのエージェントが何も編集せずに diff を読み、見つけた問題を回答の最後に挙げます。非公開ファイルは名前だけが渡され、エージェントが1つだけのときは何も変わりません。"$json$::jsonb),
  ('de', 'beat.review', $json$"{agent} · {model} prüft {count} geänderte Datei(en)"$json$::jsonb),
  ('de', 'jev.review', $json$"Zweite Meinung von einem anderen Agenten"$json$::jsonb),
  ('de', 'jev.review.hint', $json$"Nach einer Änderung im Build-Modus liest ein Agent eines anderen Anbieters den Diff schreibgeschützt und listet Probleme am Ende der Antwort auf. Das kostet einen Agentenaufruf mehr pro Änderung."$json$::jsonb),
  ('de', 'whatsNew.item.secondOpinion.title', $json$"Ein anderer Agent prüft, was der erste geändert hat"$json$::jsonb),
  ('de', 'whatsNew.item.secondOpinion.detail', $json$"Schalte Zweite Meinung von einem anderen Agenten unter Einstellungen › Jev › Routing ein. Wenn eine Anfrage das Projekt im Build-Modus ändert, liest ein Agent eines anderen Anbieters den Diff, ohne etwas zu bearbeiten, und listet gefundene Probleme am Ende der Antwort auf. Private Dateien gehen nur mit ihrem Namen mit, und mit nur einem aktiven Agenten ändert sich nichts."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
