-- v0.68.0: servidores MCP (Configurações › MCP e /mcp no chat) e as novidades
-- da versão.

insert into public.translations (locale, key, value) values
  ('en', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('en', 'mcp.title', $json$"MCP servers"$json$::jsonb),
  ('en', 'mcp.description', $json$"Servers JayV hands to Claude Code, Codex and Copilot on every request. Their tools run without asking, because nobody can approve them while the agent works."$json$::jsonb),
  ('en', 'mcp.add', $json$"Add server"$json$::jsonb),
  ('en', 'mcp.empty', $json$"No server yet. Add one, paste a configuration below, or type /mcp in a chat followed by the configuration or a description."$json$::jsonb),
  ('en', 'mcp.notes', $json$"Cursor reads its own .cursor/mcp.json and is left out. Planning mode and organization policies with safe agents run without these servers. Environment variables stay on this computer."$json$::jsonb),
  ('en', 'mcp.agents.all', $json$"All agents"$json$::jsonb),
  ('en', 'mcp.edit', $json$"Edit {name}"$json$::jsonb),
  ('en', 'mcp.delete', $json$"Remove {name}"$json$::jsonb),
  ('en', 'mcp.remove', $json$"Leave this one out"$json$::jsonb),
  ('en', 'mcp.save', $json$"Save"$json$::jsonb),
  ('en', 'mcp.paste.title', $json$"Paste a configuration"$json$::jsonb),
  ('en', 'mcp.paste.description', $json$"The mcpServers block from Claude Desktop or Cursor, the servers block from VS Code, a claude mcp add line, the npx command, or a description such as “the GitHub MCP”. A description goes to your cheapest agent, which drafts the configuration."$json$::jsonb),
  ('en', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('en', 'mcp.paste.read', $json$"Read"$json$::jsonb),
  ('en', 'mcp.paste.reading', $json$"Reading…"$json$::jsonb),
  ('en', 'mcp.draft.title', $json${"one":"Check the MCP server","other":"Check the {count} MCP servers"}$json$::jsonb),
  ('en', 'mcp.draft.description', $json$"Read from what you pasted. Nothing is saved until you click Save."$json$::jsonb),
  ('en', 'mcp.draft.fromModel', $json$"An agent drafted this from your description. Check the command and fill in the secrets before saving."$json$::jsonb),
  ('en', 'mcp.chat.empty', $json$"Type the configuration or a description after /mcp."$json$::jsonb),
  ('en', 'mcp.field.name', $json$"Name"$json$::jsonb),
  ('en', 'mcp.field.name.hint', $json$"Letters, digits, - and _. The agent sees the tools as mcp__name."$json$::jsonb),
  ('en', 'mcp.field.transport', $json$"Transport"$json$::jsonb),
  ('en', 'mcp.transport.stdio', $json$"Local"$json$::jsonb),
  ('en', 'mcp.transport.stdio.hint', $json$"Starts a command on this computer"$json$::jsonb),
  ('en', 'mcp.transport.http', $json$"Remote"$json$::jsonb),
  ('en', 'mcp.transport.http.hint', $json$"Talks to a URL"$json$::jsonb),
  ('en', 'mcp.field.command', $json$"Command"$json$::jsonb),
  ('en', 'mcp.field.args', $json$"Arguments"$json$::jsonb),
  ('en', 'mcp.field.args.hint', $json$"One per line."$json$::jsonb),
  ('en', 'mcp.field.env', $json$"Environment variables"$json$::jsonb),
  ('en', 'mcp.field.env.hint', $json$"KEY=value, one per line."$json$::jsonb),
  ('en', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('en', 'mcp.field.headers', $json$"Headers"$json$::jsonb),
  ('en', 'mcp.field.headers.hint', $json$"Name: value, one per line."$json$::jsonb),
  ('en', 'mcp.field.agents', $json$"Agents"$json$::jsonb),
  ('en', 'mcp.field.agents.hint', $json$"Who receives this server."$json$::jsonb),
  ('en', 'mcp.field.enabled', $json$"On"$json$::jsonb),
  ('en', 'mcp.field.enabled.hint', $json$"Off keeps it here without handing it to the agents."$json$::jsonb),
  ('en', 'mcp.invalid.name', $json$"The MCP server name takes letters, digits, - and _, up to 40 characters."$json$::jsonb),
  ('en', 'mcp.invalid.reserved', $json$"The name jayv belongs to JayV's own symbol server."$json$::jsonb),
  ('en', 'mcp.invalid.command', $json$"A local MCP server needs the command that starts it."$json$::jsonb),
  ('en', 'mcp.invalid.url', $json$"A remote MCP server needs an http:// or https:// URL."$json$::jsonb),
  ('en', 'mcp.invalid.env', $json$"Environment variable names take letters, digits and _."$json$::jsonb),
  ('en', 'mcp.invalid.transport', $json$"Pick Local or Remote."$json$::jsonb),
  ('en', 'mcp.invalid.duplicate', $json$"There are two MCP servers named {name}."$json$::jsonb),
  ('en', 'mcp.draft.noAgent', $json$"No agent is on to read the description. Paste the configuration instead."$json$::jsonb),
  ('en', 'mcp.draft.failed', $json$"The agent did not answer. Try again or paste the configuration."$json$::jsonb),
  ('en', 'mcp.draft.unknown', $json$"Neither JayV nor the agent found an MCP server in that text. Paste the configuration from the server's documentation."$json$::jsonb),
  ('en', 'whatsNew.item.mcpServers.title', $json$"MCP servers for your agents"$json$::jsonb),
  ('en', 'whatsNew.item.mcpServers.detail', $json$"Settings › MCP lists the servers JayV hands to Claude Code, Codex and Copilot on every request. Add one by hand, paste a configuration, or type /mcp in a chat followed by the configuration or a description; an agent drafts it, and nothing is saved until you check it."$json$::jsonb),
  ('pt-BR', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('pt-BR', 'mcp.title', $json$"Servidores MCP"$json$::jsonb),
  ('pt-BR', 'mcp.description', $json$"Servidores que o JayV entrega ao Claude Code, ao Codex e ao Copilot em cada pedido. As ferramentas deles rodam sem perguntar, porque ninguém consegue aprovar enquanto o agente trabalha."$json$::jsonb),
  ('pt-BR', 'mcp.add', $json$"Adicionar servidor"$json$::jsonb),
  ('pt-BR', 'mcp.empty', $json$"Nenhum servidor ainda. Adicione um, cole uma configuração abaixo ou digite /mcp num chat seguido da configuração ou de uma descrição."$json$::jsonb),
  ('pt-BR', 'mcp.notes', $json$"O Cursor lê o próprio .cursor/mcp.json e fica de fora. O modo planejamento e as políticas de organização com agentes seguros rodam sem estes servidores. As variáveis de ambiente ficam neste computador."$json$::jsonb),
  ('pt-BR', 'mcp.agents.all', $json$"Todos os agentes"$json$::jsonb),
  ('pt-BR', 'mcp.edit', $json$"Editar {name}"$json$::jsonb),
  ('pt-BR', 'mcp.delete', $json$"Remover {name}"$json$::jsonb),
  ('pt-BR', 'mcp.remove', $json$"Deixar este de fora"$json$::jsonb),
  ('pt-BR', 'mcp.save', $json$"Salvar"$json$::jsonb),
  ('pt-BR', 'mcp.paste.title', $json$"Colar uma configuração"$json$::jsonb),
  ('pt-BR', 'mcp.paste.description', $json$"O bloco mcpServers do Claude Desktop ou do Cursor, o bloco servers do VS Code, uma linha claude mcp add, o comando npx, ou uma descrição como “o MCP do GitHub”. A descrição vai ao seu agente mais barato, que monta a configuração."$json$::jsonb),
  ('pt-BR', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('pt-BR', 'mcp.paste.read', $json$"Ler"$json$::jsonb),
  ('pt-BR', 'mcp.paste.reading', $json$"Lendo…"$json$::jsonb),
  ('pt-BR', 'mcp.draft.title', $json${"one":"Confira o servidor MCP","other":"Confira os {count} servidores MCP"}$json$::jsonb),
  ('pt-BR', 'mcp.draft.description', $json$"Lido do que você colou. Nada é gravado até você clicar em Salvar."$json$::jsonb),
  ('pt-BR', 'mcp.draft.fromModel', $json$"Um agente montou isto a partir da sua descrição. Confira o comando e preencha os segredos antes de salvar."$json$::jsonb),
  ('pt-BR', 'mcp.chat.empty', $json$"Escreva a configuração ou uma descrição depois de /mcp."$json$::jsonb),
  ('pt-BR', 'mcp.field.name', $json$"Nome"$json$::jsonb),
  ('pt-BR', 'mcp.field.name.hint', $json$"Letras, dígitos, - e _. O agente vê as ferramentas como mcp__nome."$json$::jsonb),
  ('pt-BR', 'mcp.field.transport', $json$"Transporte"$json$::jsonb),
  ('pt-BR', 'mcp.transport.stdio', $json$"Local"$json$::jsonb),
  ('pt-BR', 'mcp.transport.stdio.hint', $json$"Sobe um comando neste computador"$json$::jsonb),
  ('pt-BR', 'mcp.transport.http', $json$"Remoto"$json$::jsonb),
  ('pt-BR', 'mcp.transport.http.hint', $json$"Fala com uma URL"$json$::jsonb),
  ('pt-BR', 'mcp.field.command', $json$"Comando"$json$::jsonb),
  ('pt-BR', 'mcp.field.args', $json$"Argumentos"$json$::jsonb),
  ('pt-BR', 'mcp.field.args.hint', $json$"Um por linha."$json$::jsonb),
  ('pt-BR', 'mcp.field.env', $json$"Variáveis de ambiente"$json$::jsonb),
  ('pt-BR', 'mcp.field.env.hint', $json$"CHAVE=valor, uma por linha."$json$::jsonb),
  ('pt-BR', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('pt-BR', 'mcp.field.headers', $json$"Cabeçalhos"$json$::jsonb),
  ('pt-BR', 'mcp.field.headers.hint', $json$"Nome: valor, um por linha."$json$::jsonb),
  ('pt-BR', 'mcp.field.agents', $json$"Agentes"$json$::jsonb),
  ('pt-BR', 'mcp.field.agents.hint', $json$"Quem recebe este servidor."$json$::jsonb),
  ('pt-BR', 'mcp.field.enabled', $json$"Ligado"$json$::jsonb),
  ('pt-BR', 'mcp.field.enabled.hint', $json$"Desligado, ele fica aqui sem ir para os agentes."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.name', $json$"O nome do servidor MCP aceita letras, dígitos, - e _, até 40 caracteres."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.reserved', $json$"O nome jayv é do servidor de símbolos do próprio JayV."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.command', $json$"Um servidor MCP local precisa do comando que o sobe."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.url', $json$"Um servidor MCP remoto precisa de uma URL http:// ou https://."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.env', $json$"Nomes de variáveis de ambiente aceitam letras, dígitos e _."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.transport', $json$"Escolha Local ou Remoto."$json$::jsonb),
  ('pt-BR', 'mcp.invalid.duplicate', $json$"Há dois servidores MCP com o nome {name}."$json$::jsonb),
  ('pt-BR', 'mcp.draft.noAgent', $json$"Nenhum agente ligado para ler a descrição. Cole a configuração."$json$::jsonb),
  ('pt-BR', 'mcp.draft.failed', $json$"O agente não respondeu. Tente de novo ou cole a configuração."$json$::jsonb),
  ('pt-BR', 'mcp.draft.unknown', $json$"Nem o JayV nem o agente acharam um servidor MCP nesse texto. Cole a configuração da documentação do servidor."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.mcpServers.title', $json$"Servidores MCP para os seus agentes"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.mcpServers.detail', $json$"Configurações › MCP lista os servidores que o JayV entrega ao Claude Code, ao Codex e ao Copilot em cada pedido. Adicione à mão, cole uma configuração ou digite /mcp num chat seguido da configuração ou de uma descrição; um agente monta o rascunho, e nada é gravado antes de você conferir."$json$::jsonb),
  ('es', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('es', 'mcp.title', $json$"Servidores MCP"$json$::jsonb),
  ('es', 'mcp.description', $json$"Servidores que JayV entrega a Claude Code, Codex y Copilot en cada solicitud. Sus herramientas se ejecutan sin preguntar, porque nadie puede aprobarlas mientras el agente trabaja."$json$::jsonb),
  ('es', 'mcp.add', $json$"Añadir servidor"$json$::jsonb),
  ('es', 'mcp.empty', $json$"Aún no hay servidores. Añade uno, pega una configuración abajo o escribe /mcp en un chat seguido de la configuración o de una descripción."$json$::jsonb),
  ('es', 'mcp.notes', $json$"Cursor lee su propio .cursor/mcp.json y queda fuera. El modo planificación y las políticas de organización con agentes seguros se ejecutan sin estos servidores. Las variables de entorno se quedan en este equipo."$json$::jsonb),
  ('es', 'mcp.agents.all', $json$"Todos los agentes"$json$::jsonb),
  ('es', 'mcp.edit', $json$"Editar {name}"$json$::jsonb),
  ('es', 'mcp.delete', $json$"Quitar {name}"$json$::jsonb),
  ('es', 'mcp.remove', $json$"Dejar este fuera"$json$::jsonb),
  ('es', 'mcp.save', $json$"Guardar"$json$::jsonb),
  ('es', 'mcp.paste.title', $json$"Pegar una configuración"$json$::jsonb),
  ('es', 'mcp.paste.description', $json$"El bloque mcpServers de Claude Desktop o Cursor, el bloque servers de VS Code, una línea claude mcp add, el comando npx o una descripción como «el MCP de GitHub». La descripción va a tu agente más barato, que redacta la configuración."$json$::jsonb),
  ('es', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('es', 'mcp.paste.read', $json$"Leer"$json$::jsonb),
  ('es', 'mcp.paste.reading', $json$"Leyendo…"$json$::jsonb),
  ('es', 'mcp.draft.title', $json${"one":"Revisa el servidor MCP","other":"Revisa los {count} servidores MCP"}$json$::jsonb),
  ('es', 'mcp.draft.description', $json$"Leído de lo que pegaste. Nada se guarda hasta que hagas clic en Guardar."$json$::jsonb),
  ('es', 'mcp.draft.fromModel', $json$"Un agente redactó esto a partir de tu descripción. Revisa el comando y completa los secretos antes de guardar."$json$::jsonb),
  ('es', 'mcp.chat.empty', $json$"Escribe la configuración o una descripción después de /mcp."$json$::jsonb),
  ('es', 'mcp.field.name', $json$"Nombre"$json$::jsonb),
  ('es', 'mcp.field.name.hint', $json$"Letras, dígitos, - y _. El agente ve las herramientas como mcp__nombre."$json$::jsonb),
  ('es', 'mcp.field.transport', $json$"Transporte"$json$::jsonb),
  ('es', 'mcp.transport.stdio', $json$"Local"$json$::jsonb),
  ('es', 'mcp.transport.stdio.hint', $json$"Inicia un comando en este equipo"$json$::jsonb),
  ('es', 'mcp.transport.http', $json$"Remoto"$json$::jsonb),
  ('es', 'mcp.transport.http.hint', $json$"Habla con una URL"$json$::jsonb),
  ('es', 'mcp.field.command', $json$"Comando"$json$::jsonb),
  ('es', 'mcp.field.args', $json$"Argumentos"$json$::jsonb),
  ('es', 'mcp.field.args.hint', $json$"Uno por línea."$json$::jsonb),
  ('es', 'mcp.field.env', $json$"Variables de entorno"$json$::jsonb),
  ('es', 'mcp.field.env.hint', $json$"CLAVE=valor, una por línea."$json$::jsonb),
  ('es', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('es', 'mcp.field.headers', $json$"Encabezados"$json$::jsonb),
  ('es', 'mcp.field.headers.hint', $json$"Nombre: valor, uno por línea."$json$::jsonb),
  ('es', 'mcp.field.agents', $json$"Agentes"$json$::jsonb),
  ('es', 'mcp.field.agents.hint', $json$"Quién recibe este servidor."$json$::jsonb),
  ('es', 'mcp.field.enabled', $json$"Activado"$json$::jsonb),
  ('es', 'mcp.field.enabled.hint', $json$"Desactivado, se queda aquí sin pasar a los agentes."$json$::jsonb),
  ('es', 'mcp.invalid.name', $json$"El nombre del servidor MCP admite letras, dígitos, - y _, hasta 40 caracteres."$json$::jsonb),
  ('es', 'mcp.invalid.reserved', $json$"El nombre jayv pertenece al servidor de símbolos de JayV."$json$::jsonb),
  ('es', 'mcp.invalid.command', $json$"Un servidor MCP local necesita el comando que lo inicia."$json$::jsonb),
  ('es', 'mcp.invalid.url', $json$"Un servidor MCP remoto necesita una URL http:// o https://."$json$::jsonb),
  ('es', 'mcp.invalid.env', $json$"Los nombres de variables de entorno admiten letras, dígitos y _."$json$::jsonb),
  ('es', 'mcp.invalid.transport', $json$"Elige Local o Remoto."$json$::jsonb),
  ('es', 'mcp.invalid.duplicate', $json$"Hay dos servidores MCP llamados {name}."$json$::jsonb),
  ('es', 'mcp.draft.noAgent', $json$"No hay ningún agente activado para leer la descripción. Pega la configuración."$json$::jsonb),
  ('es', 'mcp.draft.failed', $json$"El agente no respondió. Inténtalo de nuevo o pega la configuración."$json$::jsonb),
  ('es', 'mcp.draft.unknown', $json$"Ni JayV ni el agente encontraron un servidor MCP en ese texto. Pega la configuración de la documentación del servidor."$json$::jsonb),
  ('es', 'whatsNew.item.mcpServers.title', $json$"Servidores MCP para tus agentes"$json$::jsonb),
  ('es', 'whatsNew.item.mcpServers.detail', $json$"Configuración › MCP lista los servidores que JayV entrega a Claude Code, Codex y Copilot en cada solicitud. Añade uno a mano, pega una configuración o escribe /mcp en un chat seguido de la configuración o de una descripción; un agente redacta el borrador y nada se guarda antes de que lo revises."$json$::jsonb),
  ('fr', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('fr', 'mcp.title', $json$"Serveurs MCP"$json$::jsonb),
  ('fr', 'mcp.description', $json$"Les serveurs que JayV transmet à Claude Code, Codex et Copilot à chaque demande. Leurs outils s'exécutent sans demander, car personne ne peut les approuver pendant que l'agent travaille."$json$::jsonb),
  ('fr', 'mcp.add', $json$"Ajouter un serveur"$json$::jsonb),
  ('fr', 'mcp.empty', $json$"Aucun serveur pour l'instant. Ajoutez-en un, collez une configuration ci-dessous ou tapez /mcp dans un chat suivi de la configuration ou d'une description."$json$::jsonb),
  ('fr', 'mcp.notes', $json$"Cursor lit son propre .cursor/mcp.json et reste à l'écart. Le mode planification et les politiques d'organisation avec agents sûrs s'exécutent sans ces serveurs. Les variables d'environnement restent sur cet ordinateur."$json$::jsonb),
  ('fr', 'mcp.agents.all', $json$"Tous les agents"$json$::jsonb),
  ('fr', 'mcp.edit', $json$"Modifier {name}"$json$::jsonb),
  ('fr', 'mcp.delete', $json$"Supprimer {name}"$json$::jsonb),
  ('fr', 'mcp.remove', $json$"Laisser celui-ci de côté"$json$::jsonb),
  ('fr', 'mcp.save', $json$"Enregistrer"$json$::jsonb),
  ('fr', 'mcp.paste.title', $json$"Coller une configuration"$json$::jsonb),
  ('fr', 'mcp.paste.description', $json$"Le bloc mcpServers de Claude Desktop ou de Cursor, le bloc servers de VS Code, une ligne claude mcp add, la commande npx ou une description comme « le MCP GitHub ». Une description part à votre agent le moins cher, qui rédige la configuration."$json$::jsonb),
  ('fr', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('fr', 'mcp.paste.read', $json$"Lire"$json$::jsonb),
  ('fr', 'mcp.paste.reading', $json$"Lecture…"$json$::jsonb),
  ('fr', 'mcp.draft.title', $json${"one":"Vérifiez le serveur MCP","other":"Vérifiez les {count} serveurs MCP"}$json$::jsonb),
  ('fr', 'mcp.draft.description', $json$"Lu à partir de ce que vous avez collé. Rien n'est enregistré avant de cliquer sur Enregistrer."$json$::jsonb),
  ('fr', 'mcp.draft.fromModel', $json$"Un agent a rédigé ceci à partir de votre description. Vérifiez la commande et renseignez les secrets avant d'enregistrer."$json$::jsonb),
  ('fr', 'mcp.chat.empty', $json$"Tapez la configuration ou une description après /mcp."$json$::jsonb),
  ('fr', 'mcp.field.name', $json$"Nom"$json$::jsonb),
  ('fr', 'mcp.field.name.hint', $json$"Lettres, chiffres, - et _. L'agent voit les outils comme mcp__nom."$json$::jsonb),
  ('fr', 'mcp.field.transport', $json$"Transport"$json$::jsonb),
  ('fr', 'mcp.transport.stdio', $json$"Local"$json$::jsonb),
  ('fr', 'mcp.transport.stdio.hint', $json$"Lance une commande sur cet ordinateur"$json$::jsonb),
  ('fr', 'mcp.transport.http', $json$"Distant"$json$::jsonb),
  ('fr', 'mcp.transport.http.hint', $json$"Parle à une URL"$json$::jsonb),
  ('fr', 'mcp.field.command', $json$"Commande"$json$::jsonb),
  ('fr', 'mcp.field.args', $json$"Arguments"$json$::jsonb),
  ('fr', 'mcp.field.args.hint', $json$"Un par ligne."$json$::jsonb),
  ('fr', 'mcp.field.env', $json$"Variables d'environnement"$json$::jsonb),
  ('fr', 'mcp.field.env.hint', $json$"CLÉ=valeur, une par ligne."$json$::jsonb),
  ('fr', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('fr', 'mcp.field.headers', $json$"En-têtes"$json$::jsonb),
  ('fr', 'mcp.field.headers.hint', $json$"Nom : valeur, un par ligne."$json$::jsonb),
  ('fr', 'mcp.field.agents', $json$"Agents"$json$::jsonb),
  ('fr', 'mcp.field.agents.hint', $json$"Qui reçoit ce serveur."$json$::jsonb),
  ('fr', 'mcp.field.enabled', $json$"Activé"$json$::jsonb),
  ('fr', 'mcp.field.enabled.hint', $json$"Désactivé, il reste ici sans être transmis aux agents."$json$::jsonb),
  ('fr', 'mcp.invalid.name', $json$"Le nom du serveur MCP accepte lettres, chiffres, - et _, jusqu'à 40 caractères."$json$::jsonb),
  ('fr', 'mcp.invalid.reserved', $json$"Le nom jayv appartient au serveur de symboles de JayV."$json$::jsonb),
  ('fr', 'mcp.invalid.command', $json$"Un serveur MCP local a besoin de la commande qui le lance."$json$::jsonb),
  ('fr', 'mcp.invalid.url', $json$"Un serveur MCP distant a besoin d'une URL http:// ou https://."$json$::jsonb),
  ('fr', 'mcp.invalid.env', $json$"Les noms de variables d'environnement acceptent lettres, chiffres et _."$json$::jsonb),
  ('fr', 'mcp.invalid.transport', $json$"Choisissez Local ou Distant."$json$::jsonb),
  ('fr', 'mcp.invalid.duplicate', $json$"Il y a deux serveurs MCP nommés {name}."$json$::jsonb),
  ('fr', 'mcp.draft.noAgent', $json$"Aucun agent n'est activé pour lire la description. Collez plutôt la configuration."$json$::jsonb),
  ('fr', 'mcp.draft.failed', $json$"L'agent n'a pas répondu. Réessayez ou collez la configuration."$json$::jsonb),
  ('fr', 'mcp.draft.unknown', $json$"Ni JayV ni l'agent n'ont trouvé de serveur MCP dans ce texte. Collez la configuration de la documentation du serveur."$json$::jsonb),
  ('fr', 'whatsNew.item.mcpServers.title', $json$"Des serveurs MCP pour vos agents"$json$::jsonb),
  ('fr', 'whatsNew.item.mcpServers.detail', $json$"Paramètres › MCP liste les serveurs que JayV transmet à Claude Code, Codex et Copilot à chaque demande. Ajoutez-en un à la main, collez une configuration ou tapez /mcp dans un chat suivi de la configuration ou d'une description ; un agent rédige le brouillon, et rien n'est enregistré avant votre vérification."$json$::jsonb),
  ('de', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('de', 'mcp.title', $json$"MCP-Server"$json$::jsonb),
  ('de', 'mcp.description', $json$"Server, die JayV bei jeder Anfrage an Claude Code, Codex und Copilot übergibt. Ihre Werkzeuge laufen ohne Nachfrage, weil niemand sie genehmigen kann, während der Agent arbeitet."$json$::jsonb),
  ('de', 'mcp.add', $json$"Server hinzufügen"$json$::jsonb),
  ('de', 'mcp.empty', $json$"Noch kein Server. Fügen Sie einen hinzu, fügen Sie unten eine Konfiguration ein oder tippen Sie in einem Chat /mcp gefolgt von der Konfiguration oder einer Beschreibung."$json$::jsonb),
  ('de', 'mcp.notes', $json$"Cursor liest seine eigene .cursor/mcp.json und bleibt außen vor. Der Planungsmodus und Organisationsrichtlinien mit sicheren Agenten laufen ohne diese Server. Umgebungsvariablen bleiben auf diesem Computer."$json$::jsonb),
  ('de', 'mcp.agents.all', $json$"Alle Agenten"$json$::jsonb),
  ('de', 'mcp.edit', $json$"{name} bearbeiten"$json$::jsonb),
  ('de', 'mcp.delete', $json$"{name} entfernen"$json$::jsonb),
  ('de', 'mcp.remove', $json$"Diesen weglassen"$json$::jsonb),
  ('de', 'mcp.save', $json$"Speichern"$json$::jsonb),
  ('de', 'mcp.paste.title', $json$"Konfiguration einfügen"$json$::jsonb),
  ('de', 'mcp.paste.description', $json$"Den mcpServers-Block aus Claude Desktop oder Cursor, den servers-Block aus VS Code, eine claude mcp add-Zeile, den npx-Befehl oder eine Beschreibung wie „das GitHub-MCP“. Eine Beschreibung geht an Ihren günstigsten Agenten, der die Konfiguration entwirft."$json$::jsonb),
  ('de', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('de', 'mcp.paste.read', $json$"Lesen"$json$::jsonb),
  ('de', 'mcp.paste.reading', $json$"Wird gelesen…"$json$::jsonb),
  ('de', 'mcp.draft.title', $json${"one":"MCP-Server prüfen","other":"{count} MCP-Server prüfen"}$json$::jsonb),
  ('de', 'mcp.draft.description', $json$"Aus Ihrem eingefügten Text gelesen. Nichts wird gespeichert, bevor Sie auf Speichern klicken."$json$::jsonb),
  ('de', 'mcp.draft.fromModel', $json$"Ein Agent hat dies aus Ihrer Beschreibung entworfen. Prüfen Sie den Befehl und tragen Sie die Geheimnisse ein, bevor Sie speichern."$json$::jsonb),
  ('de', 'mcp.chat.empty', $json$"Schreiben Sie die Konfiguration oder eine Beschreibung nach /mcp."$json$::jsonb),
  ('de', 'mcp.field.name', $json$"Name"$json$::jsonb),
  ('de', 'mcp.field.name.hint', $json$"Buchstaben, Ziffern, - und _. Der Agent sieht die Werkzeuge als mcp__name."$json$::jsonb),
  ('de', 'mcp.field.transport', $json$"Transport"$json$::jsonb),
  ('de', 'mcp.transport.stdio', $json$"Lokal"$json$::jsonb),
  ('de', 'mcp.transport.stdio.hint', $json$"Startet einen Befehl auf diesem Computer"$json$::jsonb),
  ('de', 'mcp.transport.http', $json$"Entfernt"$json$::jsonb),
  ('de', 'mcp.transport.http.hint', $json$"Spricht mit einer URL"$json$::jsonb),
  ('de', 'mcp.field.command', $json$"Befehl"$json$::jsonb),
  ('de', 'mcp.field.args', $json$"Argumente"$json$::jsonb),
  ('de', 'mcp.field.args.hint', $json$"Eines pro Zeile."$json$::jsonb),
  ('de', 'mcp.field.env', $json$"Umgebungsvariablen"$json$::jsonb),
  ('de', 'mcp.field.env.hint', $json$"SCHLÜSSEL=Wert, eine pro Zeile."$json$::jsonb),
  ('de', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('de', 'mcp.field.headers', $json$"Header"$json$::jsonb),
  ('de', 'mcp.field.headers.hint', $json$"Name: Wert, einer pro Zeile."$json$::jsonb),
  ('de', 'mcp.field.agents', $json$"Agenten"$json$::jsonb),
  ('de', 'mcp.field.agents.hint', $json$"Wer diesen Server erhält."$json$::jsonb),
  ('de', 'mcp.field.enabled', $json$"An"$json$::jsonb),
  ('de', 'mcp.field.enabled.hint', $json$"Aus: bleibt hier, ohne an die Agenten zu gehen."$json$::jsonb),
  ('de', 'mcp.invalid.name', $json$"Der MCP-Servername erlaubt Buchstaben, Ziffern, - und _, bis zu 40 Zeichen."$json$::jsonb),
  ('de', 'mcp.invalid.reserved', $json$"Der Name jayv gehört JayVs eigenem Symbolserver."$json$::jsonb),
  ('de', 'mcp.invalid.command', $json$"Ein lokaler MCP-Server braucht den Befehl, der ihn startet."$json$::jsonb),
  ('de', 'mcp.invalid.url', $json$"Ein entfernter MCP-Server braucht eine http://- oder https://-URL."$json$::jsonb),
  ('de', 'mcp.invalid.env', $json$"Namen von Umgebungsvariablen erlauben Buchstaben, Ziffern und _."$json$::jsonb),
  ('de', 'mcp.invalid.transport', $json$"Wählen Sie Lokal oder Entfernt."$json$::jsonb),
  ('de', 'mcp.invalid.duplicate', $json$"Es gibt zwei MCP-Server namens {name}."$json$::jsonb),
  ('de', 'mcp.draft.noAgent', $json$"Kein Agent ist aktiv, um die Beschreibung zu lesen. Fügen Sie stattdessen die Konfiguration ein."$json$::jsonb),
  ('de', 'mcp.draft.failed', $json$"Der Agent hat nicht geantwortet. Versuchen Sie es erneut oder fügen Sie die Konfiguration ein."$json$::jsonb),
  ('de', 'mcp.draft.unknown', $json$"Weder JayV noch der Agent haben in diesem Text einen MCP-Server gefunden. Fügen Sie die Konfiguration aus der Dokumentation des Servers ein."$json$::jsonb),
  ('de', 'whatsNew.item.mcpServers.title', $json$"MCP-Server für Ihre Agenten"$json$::jsonb),
  ('de', 'whatsNew.item.mcpServers.detail', $json$"Einstellungen › MCP listet die Server, die JayV bei jeder Anfrage an Claude Code, Codex und Copilot übergibt. Fügen Sie einen von Hand hinzu, fügen Sie eine Konfiguration ein oder tippen Sie in einem Chat /mcp gefolgt von der Konfiguration oder einer Beschreibung; ein Agent entwirft ihn, und nichts wird gespeichert, bevor Sie es prüfen."$json$::jsonb),
  ('ru', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('ru', 'mcp.title', $json$"Серверы MCP"$json$::jsonb),
  ('ru', 'mcp.description', $json$"Серверы, которые JayV передаёт Claude Code, Codex и Copilot в каждом запросе. Их инструменты работают без вопросов, потому что одобрить их, пока агент работает, некому."$json$::jsonb),
  ('ru', 'mcp.add', $json$"Добавить сервер"$json$::jsonb),
  ('ru', 'mcp.empty', $json$"Серверов пока нет. Добавьте сервер, вставьте конфигурацию ниже или введите в чате /mcp и после него конфигурацию или описание."$json$::jsonb),
  ('ru', 'mcp.notes', $json$"Cursor читает свой .cursor/mcp.json и не участвует. Режим планирования и политики организации с безопасными агентами работают без этих серверов. Переменные окружения остаются на этом компьютере."$json$::jsonb),
  ('ru', 'mcp.agents.all', $json$"Все агенты"$json$::jsonb),
  ('ru', 'mcp.edit', $json$"Изменить {name}"$json$::jsonb),
  ('ru', 'mcp.delete', $json$"Удалить {name}"$json$::jsonb),
  ('ru', 'mcp.remove', $json$"Не добавлять этот"$json$::jsonb),
  ('ru', 'mcp.save', $json$"Сохранить"$json$::jsonb),
  ('ru', 'mcp.paste.title', $json$"Вставить конфигурацию"$json$::jsonb),
  ('ru', 'mcp.paste.description', $json$"Блок mcpServers из Claude Desktop или Cursor, блок servers из VS Code, строку claude mcp add, команду npx или описание вроде «MCP для GitHub». Описание уходит самому дешёвому агенту, который составит конфигурацию."$json$::jsonb),
  ('ru', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('ru', 'mcp.paste.read', $json$"Прочитать"$json$::jsonb),
  ('ru', 'mcp.paste.reading', $json$"Чтение…"$json$::jsonb),
  ('ru', 'mcp.draft.title', $json${"one":"Проверьте сервер MCP","other":"Проверьте серверы MCP ({count})"}$json$::jsonb),
  ('ru', 'mcp.draft.description', $json$"Прочитано из вставленного текста. Ничего не сохраняется, пока вы не нажмёте «Сохранить»."$json$::jsonb),
  ('ru', 'mcp.draft.fromModel', $json$"Агент составил это по вашему описанию. Проверьте команду и заполните секреты перед сохранением."$json$::jsonb),
  ('ru', 'mcp.chat.empty', $json$"Напишите конфигурацию или описание после /mcp."$json$::jsonb),
  ('ru', 'mcp.field.name', $json$"Имя"$json$::jsonb),
  ('ru', 'mcp.field.name.hint', $json$"Буквы, цифры, - и _. Агент видит инструменты как mcp__имя."$json$::jsonb),
  ('ru', 'mcp.field.transport', $json$"Транспорт"$json$::jsonb),
  ('ru', 'mcp.transport.stdio', $json$"Локальный"$json$::jsonb),
  ('ru', 'mcp.transport.stdio.hint', $json$"Запускает команду на этом компьютере"$json$::jsonb),
  ('ru', 'mcp.transport.http', $json$"Удалённый"$json$::jsonb),
  ('ru', 'mcp.transport.http.hint', $json$"Обращается к URL"$json$::jsonb),
  ('ru', 'mcp.field.command', $json$"Команда"$json$::jsonb),
  ('ru', 'mcp.field.args', $json$"Аргументы"$json$::jsonb),
  ('ru', 'mcp.field.args.hint', $json$"По одному в строке."$json$::jsonb),
  ('ru', 'mcp.field.env', $json$"Переменные окружения"$json$::jsonb),
  ('ru', 'mcp.field.env.hint', $json$"КЛЮЧ=значение, по одной в строке."$json$::jsonb),
  ('ru', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('ru', 'mcp.field.headers', $json$"Заголовки"$json$::jsonb),
  ('ru', 'mcp.field.headers.hint', $json$"Имя: значение, по одному в строке."$json$::jsonb),
  ('ru', 'mcp.field.agents', $json$"Агенты"$json$::jsonb),
  ('ru', 'mcp.field.agents.hint', $json$"Кто получает этот сервер."$json$::jsonb),
  ('ru', 'mcp.field.enabled', $json$"Включён"$json$::jsonb),
  ('ru', 'mcp.field.enabled.hint', $json$"Выключенный остаётся здесь, но не передаётся агентам."$json$::jsonb),
  ('ru', 'mcp.invalid.name', $json$"Имя сервера MCP: буквы, цифры, - и _, до 40 символов."$json$::jsonb),
  ('ru', 'mcp.invalid.reserved', $json$"Имя jayv занято собственным сервером символов JayV."$json$::jsonb),
  ('ru', 'mcp.invalid.command', $json$"Локальному серверу MCP нужна команда запуска."$json$::jsonb),
  ('ru', 'mcp.invalid.url', $json$"Удалённому серверу MCP нужен URL http:// или https://."$json$::jsonb),
  ('ru', 'mcp.invalid.env', $json$"Имена переменных окружения: буквы, цифры и _."$json$::jsonb),
  ('ru', 'mcp.invalid.transport', $json$"Выберите «Локальный» или «Удалённый»."$json$::jsonb),
  ('ru', 'mcp.invalid.duplicate', $json$"Есть два сервера MCP с именем {name}."$json$::jsonb),
  ('ru', 'mcp.draft.noAgent', $json$"Нет включённого агента, чтобы прочитать описание. Вставьте конфигурацию."$json$::jsonb),
  ('ru', 'mcp.draft.failed', $json$"Агент не ответил. Попробуйте ещё раз или вставьте конфигурацию."$json$::jsonb),
  ('ru', 'mcp.draft.unknown', $json$"Ни JayV, ни агент не нашли сервер MCP в этом тексте. Вставьте конфигурацию из документации сервера."$json$::jsonb),
  ('ru', 'whatsNew.item.mcpServers.title', $json$"Серверы MCP для ваших агентов"$json$::jsonb),
  ('ru', 'whatsNew.item.mcpServers.detail', $json$"Настройки › MCP показывают серверы, которые JayV передаёт Claude Code, Codex и Copilot в каждом запросе. Добавьте сервер вручную, вставьте конфигурацию или введите в чате /mcp с конфигурацией или описанием; агент составит черновик, и ничего не сохранится без вашей проверки."$json$::jsonb),
  ('zh-CN', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('zh-CN', 'mcp.title', $json$"MCP 服务器"$json$::jsonb),
  ('zh-CN', 'mcp.description', $json$"JayV 在每次请求时交给 Claude Code、Codex 和 Copilot 的服务器。它们的工具无需询问即可运行，因为代理工作时无人能批准。"$json$::jsonb),
  ('zh-CN', 'mcp.add', $json$"添加服务器"$json$::jsonb),
  ('zh-CN', 'mcp.empty', $json$"还没有服务器。添加一个、在下方粘贴配置，或在聊天中输入 /mcp 后接配置或描述。"$json$::jsonb),
  ('zh-CN', 'mcp.notes', $json$"Cursor 读取自己的 .cursor/mcp.json，不在此列。规划模式和启用安全代理的组织策略不带这些服务器运行。环境变量只留在这台电脑上。"$json$::jsonb),
  ('zh-CN', 'mcp.agents.all', $json$"所有代理"$json$::jsonb),
  ('zh-CN', 'mcp.edit', $json$"编辑 {name}"$json$::jsonb),
  ('zh-CN', 'mcp.delete', $json$"移除 {name}"$json$::jsonb),
  ('zh-CN', 'mcp.remove', $json$"不添加这个"$json$::jsonb),
  ('zh-CN', 'mcp.save', $json$"保存"$json$::jsonb),
  ('zh-CN', 'mcp.paste.title', $json$"粘贴配置"$json$::jsonb),
  ('zh-CN', 'mcp.paste.description', $json$"Claude Desktop 或 Cursor 的 mcpServers 块、VS Code 的 servers 块、一行 claude mcp add、npx 命令，或像“GitHub 的 MCP”这样的描述。描述会交给你最便宜的代理来起草配置。"$json$::jsonb),
  ('zh-CN', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('zh-CN', 'mcp.paste.read', $json$"读取"$json$::jsonb),
  ('zh-CN', 'mcp.paste.reading', $json$"读取中…"$json$::jsonb),
  ('zh-CN', 'mcp.draft.title', $json${"one":"检查 MCP 服务器","other":"检查 {count} 个 MCP 服务器"}$json$::jsonb),
  ('zh-CN', 'mcp.draft.description', $json$"从你粘贴的内容读取。点击“保存”之前不会保存任何内容。"$json$::jsonb),
  ('zh-CN', 'mcp.draft.fromModel', $json$"这是代理根据你的描述起草的。保存前请检查命令并填写密钥。"$json$::jsonb),
  ('zh-CN', 'mcp.chat.empty', $json$"请在 /mcp 后输入配置或描述。"$json$::jsonb),
  ('zh-CN', 'mcp.field.name', $json$"名称"$json$::jsonb),
  ('zh-CN', 'mcp.field.name.hint', $json$"字母、数字、- 和 _。代理看到的工具名为 mcp__名称。"$json$::jsonb),
  ('zh-CN', 'mcp.field.transport', $json$"传输方式"$json$::jsonb),
  ('zh-CN', 'mcp.transport.stdio', $json$"本地"$json$::jsonb),
  ('zh-CN', 'mcp.transport.stdio.hint', $json$"在这台电脑上启动命令"$json$::jsonb),
  ('zh-CN', 'mcp.transport.http', $json$"远程"$json$::jsonb),
  ('zh-CN', 'mcp.transport.http.hint', $json$"连接到一个 URL"$json$::jsonb),
  ('zh-CN', 'mcp.field.command', $json$"命令"$json$::jsonb),
  ('zh-CN', 'mcp.field.args', $json$"参数"$json$::jsonb),
  ('zh-CN', 'mcp.field.args.hint', $json$"每行一个。"$json$::jsonb),
  ('zh-CN', 'mcp.field.env', $json$"环境变量"$json$::jsonb),
  ('zh-CN', 'mcp.field.env.hint', $json$"KEY=value，每行一个。"$json$::jsonb),
  ('zh-CN', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('zh-CN', 'mcp.field.headers', $json$"请求头"$json$::jsonb),
  ('zh-CN', 'mcp.field.headers.hint', $json$"名称: 值，每行一个。"$json$::jsonb),
  ('zh-CN', 'mcp.field.agents', $json$"代理"$json$::jsonb),
  ('zh-CN', 'mcp.field.agents.hint', $json$"哪些代理接收此服务器。"$json$::jsonb),
  ('zh-CN', 'mcp.field.enabled', $json$"开启"$json$::jsonb),
  ('zh-CN', 'mcp.field.enabled.hint', $json$"关闭后保留在这里，但不交给代理。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.name', $json$"MCP 服务器名称只能包含字母、数字、- 和 _，最多 40 个字符。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.reserved', $json$"名称 jayv 属于 JayV 自己的符号服务器。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.command', $json$"本地 MCP 服务器需要启动它的命令。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.url', $json$"远程 MCP 服务器需要 http:// 或 https:// 的 URL。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.env', $json$"环境变量名只能包含字母、数字和 _。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.transport', $json$"请选择本地或远程。"$json$::jsonb),
  ('zh-CN', 'mcp.invalid.duplicate', $json$"有两个名为 {name} 的 MCP 服务器。"$json$::jsonb),
  ('zh-CN', 'mcp.draft.noAgent', $json$"没有开启的代理来读取描述。请直接粘贴配置。"$json$::jsonb),
  ('zh-CN', 'mcp.draft.failed', $json$"代理没有回应。请重试或粘贴配置。"$json$::jsonb),
  ('zh-CN', 'mcp.draft.unknown', $json$"JayV 和代理都没有在该文本中找到 MCP 服务器。请粘贴服务器文档中的配置。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.mcpServers.title', $json$"为你的代理配置 MCP 服务器"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.mcpServers.detail', $json$"设置 › MCP 列出 JayV 在每次请求时交给 Claude Code、Codex 和 Copilot 的服务器。可以手动添加、粘贴配置，或在聊天中输入 /mcp 后接配置或描述；代理会起草，检查之前不会保存。"$json$::jsonb),
  ('ja', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('ja', 'mcp.title', $json$"MCP サーバー"$json$::jsonb),
  ('ja', 'mcp.description', $json$"JayV がリクエストごとに Claude Code、Codex、Copilot に渡すサーバーです。エージェントの作業中は誰も承認できないため、ツールは確認なしで実行されます。"$json$::jsonb),
  ('ja', 'mcp.add', $json$"サーバーを追加"$json$::jsonb),
  ('ja', 'mcp.empty', $json$"サーバーはまだありません。追加するか、下に設定を貼り付けるか、チャットで /mcp に続けて設定や説明を入力してください。"$json$::jsonb),
  ('ja', 'mcp.notes', $json$"Cursor は独自の .cursor/mcp.json を読むため対象外です。計画モードと、安全なエージェントを求める組織ポリシーではこれらのサーバーなしで実行します。環境変数はこのコンピューターに残ります。"$json$::jsonb),
  ('ja', 'mcp.agents.all', $json$"すべてのエージェント"$json$::jsonb),
  ('ja', 'mcp.edit', $json$"{name} を編集"$json$::jsonb),
  ('ja', 'mcp.delete', $json$"{name} を削除"$json$::jsonb),
  ('ja', 'mcp.remove', $json$"これは追加しない"$json$::jsonb),
  ('ja', 'mcp.save', $json$"保存"$json$::jsonb),
  ('ja', 'mcp.paste.title', $json$"設定を貼り付け"$json$::jsonb),
  ('ja', 'mcp.paste.description', $json$"Claude Desktop や Cursor の mcpServers ブロック、VS Code の servers ブロック、claude mcp add の行、npx コマンド、または「GitHub の MCP」のような説明。説明は最も安価なエージェントに渡され、設定が下書きされます。"$json$::jsonb),
  ('ja', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('ja', 'mcp.paste.read', $json$"読み取る"$json$::jsonb),
  ('ja', 'mcp.paste.reading', $json$"読み取り中…"$json$::jsonb),
  ('ja', 'mcp.draft.title', $json${"one":"MCP サーバーを確認","other":"{count} 個の MCP サーバーを確認"}$json$::jsonb),
  ('ja', 'mcp.draft.description', $json$"貼り付けた内容から読み取りました。「保存」を押すまで何も保存されません。"$json$::jsonb),
  ('ja', 'mcp.draft.fromModel', $json$"エージェントが説明から下書きしました。保存する前にコマンドを確認し、シークレットを入力してください。"$json$::jsonb),
  ('ja', 'mcp.chat.empty', $json$"/mcp の後に設定か説明を入力してください。"$json$::jsonb),
  ('ja', 'mcp.field.name', $json$"名前"$json$::jsonb),
  ('ja', 'mcp.field.name.hint', $json$"英数字、- と _。エージェントにはツールが mcp__名前 として見えます。"$json$::jsonb),
  ('ja', 'mcp.field.transport', $json$"通信方式"$json$::jsonb),
  ('ja', 'mcp.transport.stdio', $json$"ローカル"$json$::jsonb),
  ('ja', 'mcp.transport.stdio.hint', $json$"このコンピューターでコマンドを起動"$json$::jsonb),
  ('ja', 'mcp.transport.http', $json$"リモート"$json$::jsonb),
  ('ja', 'mcp.transport.http.hint', $json$"URL に接続"$json$::jsonb),
  ('ja', 'mcp.field.command', $json$"コマンド"$json$::jsonb),
  ('ja', 'mcp.field.args', $json$"引数"$json$::jsonb),
  ('ja', 'mcp.field.args.hint', $json$"1 行に 1 つ。"$json$::jsonb),
  ('ja', 'mcp.field.env', $json$"環境変数"$json$::jsonb),
  ('ja', 'mcp.field.env.hint', $json$"KEY=value を 1 行に 1 つ。"$json$::jsonb),
  ('ja', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('ja', 'mcp.field.headers', $json$"ヘッダー"$json$::jsonb),
  ('ja', 'mcp.field.headers.hint', $json$"名前: 値 を 1 行に 1 つ。"$json$::jsonb),
  ('ja', 'mcp.field.agents', $json$"エージェント"$json$::jsonb),
  ('ja', 'mcp.field.agents.hint', $json$"このサーバーを受け取るエージェント。"$json$::jsonb),
  ('ja', 'mcp.field.enabled', $json$"オン"$json$::jsonb),
  ('ja', 'mcp.field.enabled.hint', $json$"オフにするとここに残りますが、エージェントには渡しません。"$json$::jsonb),
  ('ja', 'mcp.invalid.name', $json$"MCP サーバー名には英数字、- と _ を 40 文字まで使えます。"$json$::jsonb),
  ('ja', 'mcp.invalid.reserved', $json$"jayv という名前は JayV 自身のシンボルサーバーが使っています。"$json$::jsonb),
  ('ja', 'mcp.invalid.command', $json$"ローカルの MCP サーバーには起動するコマンドが必要です。"$json$::jsonb),
  ('ja', 'mcp.invalid.url', $json$"リモートの MCP サーバーには http:// または https:// の URL が必要です。"$json$::jsonb),
  ('ja', 'mcp.invalid.env', $json$"環境変数名には英数字と _ を使えます。"$json$::jsonb),
  ('ja', 'mcp.invalid.transport', $json$"ローカルかリモートを選んでください。"$json$::jsonb),
  ('ja', 'mcp.invalid.duplicate', $json$"{name} という名前の MCP サーバーが 2 つあります。"$json$::jsonb),
  ('ja', 'mcp.draft.noAgent', $json$"説明を読むエージェントがオンになっていません。設定を貼り付けてください。"$json$::jsonb),
  ('ja', 'mcp.draft.failed', $json$"エージェントが応答しませんでした。もう一度試すか、設定を貼り付けてください。"$json$::jsonb),
  ('ja', 'mcp.draft.unknown', $json$"JayV もエージェントもそのテキストから MCP サーバーを見つけられませんでした。サーバーのドキュメントにある設定を貼り付けてください。"$json$::jsonb),
  ('ja', 'whatsNew.item.mcpServers.title', $json$"エージェント用の MCP サーバー"$json$::jsonb),
  ('ja', 'whatsNew.item.mcpServers.detail', $json$"設定 › MCP に、JayV がリクエストごとに Claude Code、Codex、Copilot に渡すサーバーが並びます。手動で追加、設定を貼り付け、またはチャットで /mcp に続けて設定や説明を入力すると、エージェントが下書きします。確認するまで何も保存されません。"$json$::jsonb),
  ('ar', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('ar', 'mcp.title', $json$"خوادم MCP"$json$::jsonb),
  ('ar', 'mcp.description', $json$"الخوادم التي يسلّمها JayV إلى Claude Code وCodex وCopilot في كل طلب. تعمل أدواتها دون سؤال، لأن لا أحد يستطيع الموافقة بينما يعمل الوكيل."$json$::jsonb),
  ('ar', 'mcp.add', $json$"إضافة خادم"$json$::jsonb),
  ('ar', 'mcp.empty', $json$"لا يوجد خادم بعد. أضف واحدًا، أو الصق إعدادًا بالأسفل، أو اكتب /mcp في محادثة متبوعًا بالإعداد أو بوصف."$json$::jsonb),
  ('ar', 'mcp.notes', $json$"يقرأ Cursor ملفه .cursor/mcp.json ويبقى خارج ذلك. وضع التخطيط وسياسات المؤسسة ذات الوكلاء الآمنين تعمل دون هذه الخوادم. متغيرات البيئة تبقى على هذا الحاسوب."$json$::jsonb),
  ('ar', 'mcp.agents.all', $json$"كل الوكلاء"$json$::jsonb),
  ('ar', 'mcp.edit', $json$"تعديل {name}"$json$::jsonb),
  ('ar', 'mcp.delete', $json$"إزالة {name}"$json$::jsonb),
  ('ar', 'mcp.remove', $json$"استبعاد هذا"$json$::jsonb),
  ('ar', 'mcp.save', $json$"حفظ"$json$::jsonb),
  ('ar', 'mcp.paste.title', $json$"لصق إعداد"$json$::jsonb),
  ('ar', 'mcp.paste.description', $json$"كتلة mcpServers من Claude Desktop أو Cursor، أو كتلة servers من VS Code، أو سطر claude mcp add، أو أمر npx، أو وصف مثل «MCP الخاص بـ GitHub». يذهب الوصف إلى أرخص وكلائك ليصوغ الإعداد."$json$::jsonb),
  ('ar', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('ar', 'mcp.paste.read', $json$"قراءة"$json$::jsonb),
  ('ar', 'mcp.paste.reading', $json$"جارٍ القراءة…"$json$::jsonb),
  ('ar', 'mcp.draft.title', $json${"one":"راجع خادم MCP","other":"راجع خوادم MCP ({count})"}$json$::jsonb),
  ('ar', 'mcp.draft.description', $json$"مقروء مما لصقته. لا يُحفظ شيء حتى تنقر «حفظ»."$json$::jsonb),
  ('ar', 'mcp.draft.fromModel', $json$"صاغ وكيلٌ هذا من وصفك. راجع الأمر واملأ الأسرار قبل الحفظ."$json$::jsonb),
  ('ar', 'mcp.chat.empty', $json$"اكتب الإعداد أو وصفًا بعد /mcp."$json$::jsonb),
  ('ar', 'mcp.field.name', $json$"الاسم"$json$::jsonb),
  ('ar', 'mcp.field.name.hint', $json$"أحرف وأرقام و- و_. يرى الوكيل الأدوات باسم mcp__الاسم."$json$::jsonb),
  ('ar', 'mcp.field.transport', $json$"النقل"$json$::jsonb),
  ('ar', 'mcp.transport.stdio', $json$"محلي"$json$::jsonb),
  ('ar', 'mcp.transport.stdio.hint', $json$"يشغّل أمرًا على هذا الحاسوب"$json$::jsonb),
  ('ar', 'mcp.transport.http', $json$"بعيد"$json$::jsonb),
  ('ar', 'mcp.transport.http.hint', $json$"يتصل بعنوان URL"$json$::jsonb),
  ('ar', 'mcp.field.command', $json$"الأمر"$json$::jsonb),
  ('ar', 'mcp.field.args', $json$"الوسائط"$json$::jsonb),
  ('ar', 'mcp.field.args.hint', $json$"واحد في كل سطر."$json$::jsonb),
  ('ar', 'mcp.field.env', $json$"متغيرات البيئة"$json$::jsonb),
  ('ar', 'mcp.field.env.hint', $json$"المفتاح=القيمة، واحد في كل سطر."$json$::jsonb),
  ('ar', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('ar', 'mcp.field.headers', $json$"الترويسات"$json$::jsonb),
  ('ar', 'mcp.field.headers.hint', $json$"الاسم: القيمة، واحدة في كل سطر."$json$::jsonb),
  ('ar', 'mcp.field.agents', $json$"الوكلاء"$json$::jsonb),
  ('ar', 'mcp.field.agents.hint', $json$"من يستقبل هذا الخادم."$json$::jsonb),
  ('ar', 'mcp.field.enabled', $json$"مفعّل"$json$::jsonb),
  ('ar', 'mcp.field.enabled.hint', $json$"عند الإيقاف يبقى هنا دون أن يُسلَّم للوكلاء."$json$::jsonb),
  ('ar', 'mcp.invalid.name', $json$"اسم خادم MCP يقبل الأحرف والأرقام و- و_ حتى 40 حرفًا."$json$::jsonb),
  ('ar', 'mcp.invalid.reserved', $json$"الاسم jayv محجوز لخادم الرموز الخاص بـ JayV."$json$::jsonb),
  ('ar', 'mcp.invalid.command', $json$"خادم MCP المحلي يحتاج إلى الأمر الذي يشغّله."$json$::jsonb),
  ('ar', 'mcp.invalid.url', $json$"خادم MCP البعيد يحتاج إلى عنوان http:// أو https://."$json$::jsonb),
  ('ar', 'mcp.invalid.env', $json$"أسماء متغيرات البيئة تقبل الأحرف والأرقام و_."$json$::jsonb),
  ('ar', 'mcp.invalid.transport', $json$"اختر محلي أو بعيد."$json$::jsonb),
  ('ar', 'mcp.invalid.duplicate', $json$"يوجد خادما MCP باسم {name}."$json$::jsonb),
  ('ar', 'mcp.draft.noAgent', $json$"لا يوجد وكيل مفعّل لقراءة الوصف. الصق الإعداد بدلًا من ذلك."$json$::jsonb),
  ('ar', 'mcp.draft.failed', $json$"لم يُجب الوكيل. حاول مجددًا أو الصق الإعداد."$json$::jsonb),
  ('ar', 'mcp.draft.unknown', $json$"لم يجد JayV ولا الوكيل خادم MCP في هذا النص. الصق الإعداد من توثيق الخادم."$json$::jsonb),
  ('ar', 'whatsNew.item.mcpServers.title', $json$"خوادم MCP لوكلائك"$json$::jsonb),
  ('ar', 'whatsNew.item.mcpServers.detail', $json$"تعرض الإعدادات › MCP الخوادم التي يسلّمها JayV إلى Claude Code وCodex وCopilot في كل طلب. أضف واحدًا يدويًا، أو الصق إعدادًا، أو اكتب /mcp في محادثة متبوعًا بالإعداد أو بوصف؛ يصوغ وكيلٌ المسودة، ولا يُحفظ شيء قبل أن تراجعه."$json$::jsonb),
  ('hi', 'settings.tab.mcp', $json$"MCP"$json$::jsonb),
  ('hi', 'mcp.title', $json$"MCP सर्वर"$json$::jsonb),
  ('hi', 'mcp.description', $json$"वे सर्वर जिन्हें JayV हर अनुरोध में Claude Code, Codex और Copilot को देता है। इनके टूल बिना पूछे चलते हैं, क्योंकि एजेंट के काम करते समय कोई मंज़ूरी नहीं दे सकता।"$json$::jsonb),
  ('hi', 'mcp.add', $json$"सर्वर जोड़ें"$json$::jsonb),
  ('hi', 'mcp.empty', $json$"अभी कोई सर्वर नहीं। एक जोड़ें, नीचे कॉन्फ़िगरेशन चिपकाएँ, या किसी चैट में /mcp के बाद कॉन्फ़िगरेशन या विवरण लिखें।"$json$::jsonb),
  ('hi', 'mcp.notes', $json$"Cursor अपना .cursor/mcp.json पढ़ता है और इससे बाहर रहता है। प्लानिंग मोड और सुरक्षित एजेंट वाली संगठन नीतियाँ इन सर्वरों के बिना चलती हैं। एनवायरनमेंट वेरिएबल इसी कंप्यूटर पर रहते हैं।"$json$::jsonb),
  ('hi', 'mcp.agents.all', $json$"सभी एजेंट"$json$::jsonb),
  ('hi', 'mcp.edit', $json$"{name} संपादित करें"$json$::jsonb),
  ('hi', 'mcp.delete', $json$"{name} हटाएँ"$json$::jsonb),
  ('hi', 'mcp.remove', $json$"इसे न जोड़ें"$json$::jsonb),
  ('hi', 'mcp.save', $json$"सहेजें"$json$::jsonb),
  ('hi', 'mcp.paste.title', $json$"कॉन्फ़िगरेशन चिपकाएँ"$json$::jsonb),
  ('hi', 'mcp.paste.description', $json$"Claude Desktop या Cursor का mcpServers ब्लॉक, VS Code का servers ब्लॉक, claude mcp add की लाइन, npx कमांड, या “GitHub का MCP” जैसा विवरण। विवरण आपके सबसे सस्ते एजेंट को जाता है, जो कॉन्फ़िगरेशन का मसौदा बनाता है।"$json$::jsonb),
  ('hi', 'mcp.paste.placeholder', $json$"{\"mcpServers\": {\"github\": {\"command\": \"npx\", \"args\": [\"-y\", \"@modelcontextprotocol/server-github\"]}}}"$json$::jsonb),
  ('hi', 'mcp.paste.read', $json$"पढ़ें"$json$::jsonb),
  ('hi', 'mcp.paste.reading', $json$"पढ़ा जा रहा है…"$json$::jsonb),
  ('hi', 'mcp.draft.title', $json${"one":"MCP सर्वर जाँचें","other":"{count} MCP सर्वर जाँचें"}$json$::jsonb),
  ('hi', 'mcp.draft.description', $json$"आपके चिपकाए टेक्स्ट से पढ़ा गया। सहेजें पर क्लिक करने तक कुछ भी सहेजा नहीं जाता।"$json$::jsonb),
  ('hi', 'mcp.draft.fromModel', $json$"एक एजेंट ने आपके विवरण से यह मसौदा बनाया। सहेजने से पहले कमांड जाँचें और सीक्रेट भरें।"$json$::jsonb),
  ('hi', 'mcp.chat.empty', $json$"/mcp के बाद कॉन्फ़िगरेशन या विवरण लिखें।"$json$::jsonb),
  ('hi', 'mcp.field.name', $json$"नाम"$json$::jsonb),
  ('hi', 'mcp.field.name.hint', $json$"अक्षर, अंक, - और _। एजेंट टूल को mcp__नाम के रूप में देखता है।"$json$::jsonb),
  ('hi', 'mcp.field.transport', $json$"ट्रांसपोर्ट"$json$::jsonb),
  ('hi', 'mcp.transport.stdio', $json$"लोकल"$json$::jsonb),
  ('hi', 'mcp.transport.stdio.hint', $json$"इस कंप्यूटर पर एक कमांड चलाता है"$json$::jsonb),
  ('hi', 'mcp.transport.http', $json$"रिमोट"$json$::jsonb),
  ('hi', 'mcp.transport.http.hint', $json$"एक URL से बात करता है"$json$::jsonb),
  ('hi', 'mcp.field.command', $json$"कमांड"$json$::jsonb),
  ('hi', 'mcp.field.args', $json$"आर्ग्युमेंट"$json$::jsonb),
  ('hi', 'mcp.field.args.hint', $json$"हर लाइन में एक।"$json$::jsonb),
  ('hi', 'mcp.field.env', $json$"एनवायरनमेंट वेरिएबल"$json$::jsonb),
  ('hi', 'mcp.field.env.hint', $json$"KEY=value, हर लाइन में एक।"$json$::jsonb),
  ('hi', 'mcp.field.url', $json$"URL"$json$::jsonb),
  ('hi', 'mcp.field.headers', $json$"हेडर"$json$::jsonb),
  ('hi', 'mcp.field.headers.hint', $json$"नाम: मान, हर लाइन में एक।"$json$::jsonb),
  ('hi', 'mcp.field.agents', $json$"एजेंट"$json$::jsonb),
  ('hi', 'mcp.field.agents.hint', $json$"यह सर्वर किसे मिलेगा।"$json$::jsonb),
  ('hi', 'mcp.field.enabled', $json$"चालू"$json$::jsonb),
  ('hi', 'mcp.field.enabled.hint', $json$"बंद होने पर यहाँ रहता है, पर एजेंटों को नहीं दिया जाता।"$json$::jsonb),
  ('hi', 'mcp.invalid.name', $json$"MCP सर्वर के नाम में अक्षर, अंक, - और _ हो सकते हैं, 40 वर्णों तक।"$json$::jsonb),
  ('hi', 'mcp.invalid.reserved', $json$"jayv नाम JayV के अपने सिंबल सर्वर का है।"$json$::jsonb),
  ('hi', 'mcp.invalid.command', $json$"लोकल MCP सर्वर को उसे चलाने वाली कमांड चाहिए।"$json$::jsonb),
  ('hi', 'mcp.invalid.url', $json$"रिमोट MCP सर्वर को http:// या https:// URL चाहिए।"$json$::jsonb),
  ('hi', 'mcp.invalid.env', $json$"एनवायरनमेंट वेरिएबल के नाम में अक्षर, अंक और _ हो सकते हैं।"$json$::jsonb),
  ('hi', 'mcp.invalid.transport', $json$"लोकल या रिमोट चुनें।"$json$::jsonb),
  ('hi', 'mcp.invalid.duplicate', $json$"{name} नाम के दो MCP सर्वर हैं।"$json$::jsonb),
  ('hi', 'mcp.draft.noAgent', $json$"विवरण पढ़ने के लिए कोई एजेंट चालू नहीं है। कॉन्फ़िगरेशन चिपकाएँ।"$json$::jsonb),
  ('hi', 'mcp.draft.failed', $json$"एजेंट ने जवाब नहीं दिया। फिर से कोशिश करें या कॉन्फ़िगरेशन चिपकाएँ।"$json$::jsonb),
  ('hi', 'mcp.draft.unknown', $json$"न JayV को और न एजेंट को उस टेक्स्ट में कोई MCP सर्वर मिला। सर्वर के दस्तावेज़ से कॉन्फ़िगरेशन चिपकाएँ।"$json$::jsonb),
  ('hi', 'whatsNew.item.mcpServers.title', $json$"आपके एजेंटों के लिए MCP सर्वर"$json$::jsonb),
  ('hi', 'whatsNew.item.mcpServers.detail', $json$"सेटिंग्स › MCP में वे सर्वर हैं जिन्हें JayV हर अनुरोध में Claude Code, Codex और Copilot को देता है। हाथ से जोड़ें, कॉन्फ़िगरेशन चिपकाएँ, या चैट में /mcp के बाद कॉन्फ़िगरेशन या विवरण लिखें; एजेंट मसौदा बनाता है, और आपके जाँचने से पहले कुछ भी सहेजा नहीं जाता।"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
