-- As mensagens do login e da conexão. Os idiomas sem tradução aqui mostram o
-- inglês embutido no app até alguém traduzi-las pelo painel.

insert into public.translations (locale, key, value) values
  ('en', 'auth.title', $json$"Sign in to JayV"$json$::jsonb),
  ('en', 'auth.subtitle', $json$"Your projects, chats and agents follow you to any machine."$json$::jsonb),
  ('en', 'auth.email', $json$"Email"$json$::jsonb),
  ('en', 'auth.password', $json$"Password"$json$::jsonb),
  ('en', 'auth.signIn', $json$"Sign in"$json$::jsonb),
  ('en', 'auth.signUp', $json$"Create account"$json$::jsonb),
  ('en', 'auth.github', $json$"Continue with GitHub"$json$::jsonb),
  ('en', 'auth.toSignUp', $json$"No account yet? Create one"$json$::jsonb),
  ('en', 'auth.toSignIn', $json$"Already have an account? Sign in"$json$::jsonb),
  ('en', 'auth.checkEmail', $json$"Check your email to confirm the account, then sign in."$json$::jsonb),
  ('en', 'auth.waitingBrowser', $json$"Finish signing in in your browser…"$json$::jsonb),
  ('en', 'auth.signOut', $json$"Sign out"$json$::jsonb),
  ('en', 'auth.loading', $json$"Opening your session…"$json$::jsonb),
  ('en', 'connection.offline', $json$"Offline — changes wait to sync"$json$::jsonb),
  ('en', 'connection.expired', $json$"Session expired — renewing…"$json$::jsonb),
  ('en', 'connection.pending', $json${"one":"{count} change not synced","other":"{count} changes not synced"}$json$::jsonb),
  ('en', 'connection.failed', $json${"one":"{count} change refused by the server","other":"{count} changes refused by the server"}$json$::jsonb),
  ('pt-BR', 'auth.title', $json$"Entrar no JayV"$json$::jsonb),
  ('pt-BR', 'auth.subtitle', $json$"Seus projetos, chats e agentes acompanham você em qualquer máquina."$json$::jsonb),
  ('pt-BR', 'auth.email', $json$"E-mail"$json$::jsonb),
  ('pt-BR', 'auth.password', $json$"Senha"$json$::jsonb),
  ('pt-BR', 'auth.signIn', $json$"Entrar"$json$::jsonb),
  ('pt-BR', 'auth.signUp', $json$"Criar conta"$json$::jsonb),
  ('pt-BR', 'auth.github', $json$"Continuar com o GitHub"$json$::jsonb),
  ('pt-BR', 'auth.toSignUp', $json$"Ainda não tem conta? Crie uma"$json$::jsonb),
  ('pt-BR', 'auth.toSignIn', $json$"Já tem conta? Entre"$json$::jsonb),
  ('pt-BR', 'auth.checkEmail', $json$"Confirme a conta pelo e-mail que enviamos e depois entre."$json$::jsonb),
  ('pt-BR', 'auth.waitingBrowser', $json$"Termine o login no navegador…"$json$::jsonb),
  ('pt-BR', 'auth.signOut', $json$"Sair"$json$::jsonb),
  ('pt-BR', 'auth.loading', $json$"Abrindo sua sessão…"$json$::jsonb),
  ('pt-BR', 'connection.offline', $json$"Sem conexão — as alterações esperam para sincronizar"$json$::jsonb),
  ('pt-BR', 'connection.expired', $json$"Sessão expirada — renovando…"$json$::jsonb),
  ('pt-BR', 'connection.pending', $json${"one":"{count} alteração não sincronizada","other":"{count} alterações não sincronizadas"}$json$::jsonb),
  ('pt-BR', 'connection.failed', $json${"one":"{count} alteração recusada pelo servidor","other":"{count} alterações recusadas pelo servidor"}$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
