-- v0.62.0: as novidades da onda 3 — pedidos de projetos diferentes ao mesmo
-- tempo, o plano ao vivo na faixa e o retrato leve dos chats.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.item.parallelRequests.title', $json$"Pedidos de projetos diferentes rodam ao mesmo tempo"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.parallelRequests.detail', $json$"Quando o seu plano permite mais de um pedido ao mesmo tempo, chats de projetos diferentes não esperam mais um pelo outro: cada um roda com os seus agentes e o seu índice. Pedidos do mesmo projeto continuam um de cada vez, para dois agentes nunca escreverem na mesma pasta juntos."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planLive.title', $json$"O plano aparece enquanto é escrito"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planLive.detail', $json$"Quando um modelo de raciocínio planeja antes um build complexo, cada linha do plano aparece no painel de andamento assim que é escrita."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.lightWorkspace.title', $json$"Os chats carregam mais leve"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.lightWorkspace.detail', $json$"O app agora carrega a lista de chats sem as conversas e lê cada conversa só quando você a abre."$json$::jsonb),
  ('en', 'whatsNew.item.parallelRequests.title', $json$"Requests from different projects run at the same time"$json$::jsonb),
  ('en', 'whatsNew.item.parallelRequests.detail', $json$"When your plan allows more than one request at a time, chats from different projects no longer wait for each other: each runs with its own agents and its own index. Requests in the same project still go one at a time, so two agents never write to the same folder at once."$json$::jsonb),
  ('en', 'whatsNew.item.planLive.title', $json$"The plan appears while it is written"$json$::jsonb),
  ('en', 'whatsNew.item.planLive.detail', $json$"When a reasoning model plans a complex build first, each line of the plan shows up in the progress panel as soon as it is written."$json$::jsonb),
  ('en', 'whatsNew.item.lightWorkspace.title', $json$"Lighter loading of your chats"$json$::jsonb),
  ('en', 'whatsNew.item.lightWorkspace.detail', $json$"The app now loads the list of chats without their conversations and reads each conversation only when you open it."$json$::jsonb),
  ('es', 'whatsNew.item.parallelRequests.title', $json$"Las solicitudes de proyectos distintos se ejecutan a la vez"$json$::jsonb),
  ('es', 'whatsNew.item.parallelRequests.detail', $json$"Cuando tu plan permite más de una solicitud a la vez, los chats de proyectos distintos ya no se esperan entre sí: cada uno se ejecuta con sus propios agentes y su propio índice. Las solicitudes del mismo proyecto siguen yendo de una en una, para que dos agentes nunca escriban en la misma carpeta a la vez."$json$::jsonb),
  ('es', 'whatsNew.item.planLive.title', $json$"El plan aparece mientras se escribe"$json$::jsonb),
  ('es', 'whatsNew.item.planLive.detail', $json$"Cuando un modelo de razonamiento planifica primero una compilación compleja, cada línea del plan aparece en el panel de progreso en cuanto se escribe."$json$::jsonb),
  ('es', 'whatsNew.item.lightWorkspace.title', $json$"Los chats se cargan de forma más ligera"$json$::jsonb),
  ('es', 'whatsNew.item.lightWorkspace.detail', $json$"La app ahora carga la lista de chats sin sus conversaciones y lee cada conversación solo cuando la abres."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.parallelRequests.title', $json$"不同项目的请求可同时运行"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.parallelRequests.detail', $json$"当你的套餐允许同时运行多个请求时，不同项目的聊天不再相互等待：每个都使用自己的代理和索引运行。同一项目的请求仍逐个进行，因此两个代理绝不会同时写入同一个文件夹。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planLive.title', $json$"计划在编写时即可看到"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planLive.detail', $json$"当推理模型先为复杂的构建制定计划时，计划的每一行一写出就会显示在进度面板中。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.lightWorkspace.title', $json$"聊天加载更轻快"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.lightWorkspace.detail', $json$"应用现在加载聊天列表时不包含对话内容，只有在你打开某个对话时才读取它。"$json$::jsonb),
  ('hi', 'whatsNew.item.parallelRequests.title', $json$"अलग-अलग प्रोजेक्टों के अनुरोध एक साथ चलते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.parallelRequests.detail', $json$"जब आपका प्लान एक साथ एक से ज़्यादा अनुरोध की अनुमति देता है, तो अलग-अलग प्रोजेक्टों की चैट अब एक-दूसरे का इंतज़ार नहीं करतीं: हर एक अपने एजेंटों और अपने इंडेक्स के साथ चलती है। एक ही प्रोजेक्ट के अनुरोध अब भी एक-एक करके चलते हैं, ताकि दो एजेंट कभी एक ही फ़ोल्डर में एक साथ न लिखें।"$json$::jsonb),
  ('hi', 'whatsNew.item.planLive.title', $json$"योजना लिखे जाते समय ही दिखती है"$json$::jsonb),
  ('hi', 'whatsNew.item.planLive.detail', $json$"जब कोई रीज़निंग मॉडल किसी जटिल बिल्ड की पहले योजना बनाता है, तो योजना की हर पंक्ति लिखे जाते ही प्रगति पैनल में दिखती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.lightWorkspace.title', $json$"चैट हल्के ढंग से लोड होती हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.lightWorkspace.detail', $json$"ऐप अब चैट की सूची उनकी बातचीत के बिना लोड करता है और हर बातचीत तभी पढ़ता है जब आप उसे खोलते हैं।"$json$::jsonb),
  ('ar', 'whatsNew.item.parallelRequests.title', $json$"طلبات المشاريع المختلفة تعمل في الوقت نفسه"$json$::jsonb),
  ('ar', 'whatsNew.item.parallelRequests.detail', $json$"عندما يسمح اشتراكك بأكثر من طلب في الوقت نفسه، لم تعد محادثات المشاريع المختلفة تنتظر بعضها: يعمل كل منها بوكلائه وفهرسه الخاصين. وتبقى طلبات المشروع الواحد تُنفَّذ واحدًا تلو الآخر، كي لا يكتب وكيلان في المجلد نفسه معًا أبدًا."$json$::jsonb),
  ('ar', 'whatsNew.item.planLive.title', $json$"تظهر الخطة أثناء كتابتها"$json$::jsonb),
  ('ar', 'whatsNew.item.planLive.detail', $json$"عندما يخطط نموذج استدلال أولًا لعملية بناء معقدة، يظهر كل سطر من الخطة في لوحة التقدم فور كتابته."$json$::jsonb),
  ('ar', 'whatsNew.item.lightWorkspace.title', $json$"تحميل أخف للمحادثات"$json$::jsonb),
  ('ar', 'whatsNew.item.lightWorkspace.detail', $json$"أصبح التطبيق يحمّل قائمة المحادثات من دون محتواها، ولا يقرأ كل محادثة إلا عند فتحها."$json$::jsonb),
  ('fr', 'whatsNew.item.parallelRequests.title', $json$"Les demandes de projets différents s'exécutent en même temps"$json$::jsonb),
  ('fr', 'whatsNew.item.parallelRequests.detail', $json$"Quand votre forfait autorise plusieurs demandes à la fois, les conversations de projets différents ne s'attendent plus : chacune s'exécute avec ses propres agents et son propre index. Les demandes d'un même projet passent toujours une par une, pour que deux agents n'écrivent jamais dans le même dossier en même temps."$json$::jsonb),
  ('fr', 'whatsNew.item.planLive.title', $json$"Le plan s'affiche pendant qu'il s'écrit"$json$::jsonb),
  ('fr', 'whatsNew.item.planLive.detail', $json$"Quand un modèle de raisonnement planifie d'abord une construction complexe, chaque ligne du plan apparaît dans le panneau d'avancement dès qu'elle est écrite."$json$::jsonb),
  ('fr', 'whatsNew.item.lightWorkspace.title', $json$"Un chargement plus léger des conversations"$json$::jsonb),
  ('fr', 'whatsNew.item.lightWorkspace.detail', $json$"L'application charge désormais la liste des conversations sans leur contenu et ne lit chaque conversation que lorsque vous l'ouvrez."$json$::jsonb),
  ('ru', 'whatsNew.item.parallelRequests.title', $json$"Запросы из разных проектов выполняются одновременно"$json$::jsonb),
  ('ru', 'whatsNew.item.parallelRequests.detail', $json$"Если тариф допускает несколько запросов одновременно, чаты разных проектов больше не ждут друг друга: каждый работает со своими агентами и своим индексом. Запросы одного проекта по-прежнему идут по одному, чтобы два агента никогда не писали в одну папку одновременно."$json$::jsonb),
  ('ru', 'whatsNew.item.planLive.title', $json$"План виден по мере написания"$json$::jsonb),
  ('ru', 'whatsNew.item.planLive.detail', $json$"Когда модель рассуждений сначала планирует сложную сборку, каждая строка плана появляется на панели хода работы сразу после написания."$json$::jsonb),
  ('ru', 'whatsNew.item.lightWorkspace.title', $json$"Более лёгкая загрузка чатов"$json$::jsonb),
  ('ru', 'whatsNew.item.lightWorkspace.detail', $json$"Теперь приложение загружает список чатов без переписки и читает каждый разговор, только когда вы его открываете."$json$::jsonb),
  ('ja', 'whatsNew.item.parallelRequests.title', $json$"別々のプロジェクトのリクエストが同時に実行されます"$json$::jsonb),
  ('ja', 'whatsNew.item.parallelRequests.detail', $json$"プランで同時に複数のリクエストが許可されている場合、別々のプロジェクトのチャットはお互いを待たなくなり、それぞれが専用のエージェントとインデックスで実行されます。同じプロジェクトのリクエストは引き続き 1 件ずつ処理されるため、2 つのエージェントが同じフォルダーに同時に書き込むことはありません。"$json$::jsonb),
  ('ja', 'whatsNew.item.planLive.title', $json$"計画が書かれている途中から表示されます"$json$::jsonb),
  ('ja', 'whatsNew.item.planLive.detail', $json$"推論モデルが複雑なビルドを先に計画するとき、計画の各行は書かれるとすぐに進行状況パネルに表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.lightWorkspace.title', $json$"チャットの読み込みが軽くなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.lightWorkspace.detail', $json$"アプリはチャットの一覧を会話なしで読み込み、各会話は開いたときにだけ読み込むようになりました。"$json$::jsonb),
  ('de', 'whatsNew.item.parallelRequests.title', $json$"Anfragen aus verschiedenen Projekten laufen gleichzeitig"$json$::jsonb),
  ('de', 'whatsNew.item.parallelRequests.detail', $json$"Wenn dein Tarif mehr als eine Anfrage gleichzeitig erlaubt, warten Chats aus verschiedenen Projekten nicht mehr aufeinander: Jeder läuft mit eigenen Agenten und eigenem Index. Anfragen aus demselben Projekt laufen weiterhin nacheinander, damit nie zwei Agenten gleichzeitig in denselben Ordner schreiben."$json$::jsonb),
  ('de', 'whatsNew.item.planLive.title', $json$"Der Plan erscheint, während er geschrieben wird"$json$::jsonb),
  ('de', 'whatsNew.item.planLive.detail', $json$"Wenn ein Reasoning-Modell einen komplexen Build zuerst plant, erscheint jede Zeile des Plans im Fortschrittsbereich, sobald sie geschrieben ist."$json$::jsonb),
  ('de', 'whatsNew.item.lightWorkspace.title', $json$"Chats laden schlanker"$json$::jsonb),
  ('de', 'whatsNew.item.lightWorkspace.detail', $json$"Die App lädt die Chatliste jetzt ohne die Unterhaltungen und liest jede Unterhaltung erst, wenn du sie öffnest."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
