-- O perfil de quem usa o JayV. Uma linha por conta, criada pelo trigger em
-- `auth.users`; o cliente só lê e muda a própria. Os valores fechados são
-- identificadores em inglês: a tela traduz.

create table public.profiles (
  user_id uuid primary key references auth.users on delete cascade,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 60),
  full_name text check (char_length(full_name) <= 120),
  sex text check (sex in ('female', 'male', 'intersex', 'undisclosed')),
  gender text check (gender in ('woman', 'man', 'non_binary', 'other', 'undisclosed')),
  gender_custom text check (char_length(gender_custom) <= 40),
  pronouns text check (pronouns in ('she', 'he', 'they', 'custom', 'undisclosed')),
  pronouns_custom text check (char_length(pronouns_custom) <= 40),
  birth_date date check (birth_date between date '1900-01-01' and current_date),
  country text check (country ~ '^[A-Z]{2}$'),
  timezone text check (char_length(timezone) <= 64),
  role text check (role in ('developer', 'tech_lead', 'qa', 'devops', 'designer', 'manager', 'data', 'other')),
  company text check (char_length(company) <= 120),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (gender_custom is null or gender = 'other'),
  check (pronouns_custom is null or pronouns = 'custom')
);

alter table public.profiles enable row level security;
create policy "dono lê" on public.profiles for select to authenticated using (user_id = (select auth.uid()));
create policy "dono muda" on public.profiles for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
revoke insert, delete, truncate on public.profiles from anon, authenticated;
revoke all on public.profiles from anon;

-- `user_id` e `created_at` não mudam; `updated_at` anda a cada escrita.
create function public.profiles_touch() returns trigger language plpgsql set search_path = '' as $$
begin
  new.user_id := old.user_id;
  new.created_at := old.created_at;
  new.updated_at := now();
  return new;
end;
$$;
create trigger touch before update on public.profiles for each row execute function public.profiles_touch();

-- O nome inicial: o do registro, o do provedor ou o começo do e-mail.
create function public.profile_name(meta jsonb, email text) returns text language sql immutable set search_path = '' as $$
  select left(coalesce(
    nullif(btrim(meta->>'display_name'), ''),
    nullif(btrim(meta->>'full_name'), ''),
    nullif(btrim(meta->>'name'), ''),
    nullif(btrim(meta->>'user_name'), ''),
    nullif(btrim(meta->>'preferred_username'), ''),
    nullif(split_part(coalesce(email, ''), '@', 1), ''),
    'user'), 60);
$$;

create function public.profiles_create() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (user_id, display_name)
  values (new.id, public.profile_name(new.raw_user_meta_data, new.email))
  on conflict (user_id) do nothing;
  return new;
end;
$$;
create trigger profiles_create after insert on auth.users for each row execute function public.profiles_create();

insert into public.profiles (user_id, display_name)
select id, public.profile_name(raw_user_meta_data, email) from auth.users
on conflict (user_id) do nothing;

-- A conta OAuth que define senha não ganha identidade `email`: só o banco sabe.
create function public.account_has_password() returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce((select encrypted_password <> '' from auth.users where id = auth.uid()), false);
$$;
revoke execute on function public.account_has_password() from public, anon;
grant execute on function public.account_has_password() to authenticated;
revoke execute on function public.profiles_create(), public.profiles_touch(), public.profile_name(jsonb, text) from public, anon, authenticated;

-- Registro, perfil, senha e contas vinculadas, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'auth.displayName', $json$"Nome de exibição"$json$::jsonb),
  ('pt-BR', 'auth.confirmPassword', $json$"Confirme a senha"$json$::jsonb),
  ('pt-BR', 'auth.mismatch', $json$"As senhas não coincidem."$json$::jsonb),
  ('pt-BR', 'auth.forgot', $json$"Esqueceu a senha?"$json$::jsonb),
  ('pt-BR', 'auth.reset.title', $json$"Redefina sua senha"$json$::jsonb),
  ('pt-BR', 'auth.reset.description', $json$"Enviaremos por e-mail um link para você escolher uma nova senha."$json$::jsonb),
  ('pt-BR', 'auth.reset.send', $json$"Enviar link de redefinição"$json$::jsonb),
  ('pt-BR', 'auth.resetSent', $json$"Se existir uma conta com este e-mail, o link de redefinição está a caminho."$json$::jsonb),
  ('pt-BR', 'auth.backToSignIn', $json$"Voltar para entrar"$json$::jsonb),
  ('pt-BR', 'auth.continueWith', $json$"Continuar com {provider}"$json$::jsonb),
  ('pt-BR', 'auth.or', $json$"ou"$json$::jsonb),
  ('pt-BR', 'auth.rule.length', $json$"Pelo menos {min} caracteres"$json$::jsonb),
  ('pt-BR', 'auth.rule.lower', $json$"Uma letra minúscula"$json$::jsonb),
  ('pt-BR', 'auth.rule.upper', $json$"Uma letra maiúscula"$json$::jsonb),
  ('pt-BR', 'auth.rule.digit', $json$"Um dígito"$json$::jsonb),
  ('pt-BR', 'auth.rule.symbol', $json$"Um caractere especial"$json$::jsonb),
  ('pt-BR', 'auth.identityTaken', $json$"Esta conta já está vinculada a outro usuário do JayV."$json$::jsonb),
  ('pt-BR', 'auth.weakPassword', $json$"O servidor recusou esta senha: ela é fraca demais ou apareceu em um vazamento de dados."$json$::jsonb),
  ('pt-BR', 'auth.invalidCredentials', $json$"E-mail ou senha incorretos."$json$::jsonb),
  ('pt-BR', 'auth.wrongPassword', $json$"A senha atual está incorreta."$json$::jsonb),
  ('pt-BR', 'auth.samePassword', $json$"A nova senha precisa ser diferente da atual."$json$::jsonb),
  ('pt-BR', 'auth.badCode', $json$"O código é inválido ou expirou. Peça um novo."$json$::jsonb),
  ('pt-BR', 'auth.lastIdentity', $json$"Esta é sua única forma de entrar. Defina uma senha ou vincule outra conta antes."$json$::jsonb),
  ('pt-BR', 'auth.linkingDisabled', $json$"A vinculação de contas está desativada no servidor."$json$::jsonb),
  ('pt-BR', 'auth.emailNotConfirmed', $json$"Confirme seu e-mail antes de entrar."$json$::jsonb),
  ('pt-BR', 'auth.newPassword.title', $json$"Escolha uma nova senha"$json$::jsonb),
  ('pt-BR', 'auth.newPassword.description', $json$"Você abriu o link de redefinição. Escolha a senha que vai usar daqui em diante."$json$::jsonb),
  ('pt-BR', 'auth.newPassword.save', $json$"Salvar senha"$json$::jsonb),
  ('pt-BR', 'auth.newPassword.saved', $json$"Senha salva."$json$::jsonb),
  ('pt-BR', 'profile.password', $json$"Senha"$json$::jsonb),
  ('pt-BR', 'profile.unset', $json$"Não informado"$json$::jsonb),
  ('pt-BR', 'profile.save', $json$"Salvar"$json$::jsonb),
  ('pt-BR', 'profile.skip', $json$"Pular por agora"$json$::jsonb),
  ('pt-BR', 'profile.saved', $json$"Perfil salvo."$json$::jsonb),
  ('pt-BR', 'profile.invalid', $json$"Algum campo tem um valor que o servidor não aceita. Confira e tente de novo."$json$::jsonb),
  ('pt-BR', 'profile.setup.title', $json$"Complete seu perfil"$json$::jsonb),
  ('pt-BR', 'profile.setup.description', $json$"Só o nome de exibição é obrigatório. Você pode mudar tudo depois na página de Perfil."$json$::jsonb),
  ('pt-BR', 'profile.data.title', $json$"Dados pessoais"$json$::jsonb),
  ('pt-BR', 'profile.data.description', $json$"Só o nome de exibição é obrigatório. Nada de documentos, endereço ou telefone."$json$::jsonb),
  ('pt-BR', 'profile.field.displayName', $json$"Nome de exibição"$json$::jsonb),
  ('pt-BR', 'profile.field.displayName.hint', $json$"Como você aparece no JayV."$json$::jsonb),
  ('pt-BR', 'profile.field.fullName', $json$"Nome completo"$json$::jsonb),
  ('pt-BR', 'profile.field.sex', $json$"Sexo"$json$::jsonb),
  ('pt-BR', 'profile.field.gender', $json$"Gênero"$json$::jsonb),
  ('pt-BR', 'profile.field.genderCustom', $json$"Seu gênero"$json$::jsonb),
  ('pt-BR', 'profile.field.pronouns', $json$"Pronomes"$json$::jsonb),
  ('pt-BR', 'profile.field.pronounsCustom', $json$"Seus pronomes"$json$::jsonb),
  ('pt-BR', 'profile.field.birthDate', $json$"Data de nascimento"$json$::jsonb),
  ('pt-BR', 'profile.field.country', $json$"País"$json$::jsonb),
  ('pt-BR', 'profile.field.timezone', $json$"Fuso horário"$json$::jsonb),
  ('pt-BR', 'profile.field.role', $json$"Função"$json$::jsonb),
  ('pt-BR', 'profile.field.company', $json$"Empresa"$json$::jsonb),
  ('pt-BR', 'profile.sex.female', $json$"Feminino"$json$::jsonb),
  ('pt-BR', 'profile.sex.male', $json$"Masculino"$json$::jsonb),
  ('pt-BR', 'profile.sex.intersex', $json$"Intersexo"$json$::jsonb),
  ('pt-BR', 'profile.sex.undisclosed', $json$"Prefiro não informar"$json$::jsonb),
  ('pt-BR', 'profile.gender.woman', $json$"Mulher"$json$::jsonb),
  ('pt-BR', 'profile.gender.man', $json$"Homem"$json$::jsonb),
  ('pt-BR', 'profile.gender.non_binary', $json$"Não binário"$json$::jsonb),
  ('pt-BR', 'profile.gender.other', $json$"Outro"$json$::jsonb),
  ('pt-BR', 'profile.gender.undisclosed', $json$"Prefiro não informar"$json$::jsonb),
  ('pt-BR', 'profile.pronouns.she', $json$"ela/dela"$json$::jsonb),
  ('pt-BR', 'profile.pronouns.he', $json$"ele/dele"$json$::jsonb),
  ('pt-BR', 'profile.pronouns.they', $json$"elu/delu"$json$::jsonb),
  ('pt-BR', 'profile.pronouns.custom', $json$"Personalizado"$json$::jsonb),
  ('pt-BR', 'profile.pronouns.undisclosed', $json$"Prefiro não informar"$json$::jsonb),
  ('pt-BR', 'profile.role.developer', $json$"Desenvolvimento"$json$::jsonb),
  ('pt-BR', 'profile.role.tech_lead', $json$"Tech lead"$json$::jsonb),
  ('pt-BR', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('pt-BR', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('pt-BR', 'profile.role.designer', $json$"Design"$json$::jsonb),
  ('pt-BR', 'profile.role.manager', $json$"Gestão"$json$::jsonb),
  ('pt-BR', 'profile.role.data', $json$"Dados"$json$::jsonb),
  ('pt-BR', 'profile.role.other', $json$"Outro"$json$::jsonb),
  ('pt-BR', 'security.title', $json$"Segurança"$json$::jsonb),
  ('pt-BR', 'security.description', $json$"A senha para entrar com seu e-mail."$json$::jsonb),
  ('pt-BR', 'security.current', $json$"Senha atual"$json$::jsonb),
  ('pt-BR', 'security.new', $json$"Nova senha"$json$::jsonb),
  ('pt-BR', 'security.confirm', $json$"Confirme a nova senha"$json$::jsonb),
  ('pt-BR', 'security.change', $json$"Trocar senha"$json$::jsonb),
  ('pt-BR', 'security.changed', $json$"Senha trocada."$json$::jsonb),
  ('pt-BR', 'security.noPassword', $json$"Sua conta ainda não tem senha: você entra só por uma conta vinculada. Defina uma para entrar também com seu e-mail."$json$::jsonb),
  ('pt-BR', 'security.sendCode', $json$"Enviar código por e-mail"$json$::jsonb),
  ('pt-BR', 'security.codeSent', $json$"Enviamos um código de 6 dígitos para {email}."$json$::jsonb),
  ('pt-BR', 'security.code', $json$"Código do e-mail"$json$::jsonb),
  ('pt-BR', 'security.setPassword', $json$"Definir senha"$json$::jsonb),
  ('pt-BR', 'security.set', $json$"Senha definida. Agora você também pode entrar com seu e-mail."$json$::jsonb),
  ('pt-BR', 'linked.title', $json$"Contas vinculadas"$json$::jsonb),
  ('pt-BR', 'linked.description', $json$"Entre com qualquer uma delas. Desvincular fica bloqueado enquanto for sua única forma de entrar."$json$::jsonb),
  ('pt-BR', 'linked.on', $json$"Vinculada"$json$::jsonb),
  ('pt-BR', 'linked.off', $json$"Não vinculada"$json$::jsonb),
  ('pt-BR', 'linked.link', $json$"Vincular"$json$::jsonb),
  ('pt-BR', 'linked.unlink', $json$"Desvincular"$json$::jsonb),
  ('pt-BR', 'linked.unlink.title', $json$"Desvincular {provider}"$json$::jsonb),
  ('pt-BR', 'linked.unlink.description', $json$"Você não poderá mais entrar com o {provider}."$json$::jsonb),
  ('en', 'auth.displayName', $json$"Display name"$json$::jsonb),
  ('en', 'auth.confirmPassword', $json$"Confirm password"$json$::jsonb),
  ('en', 'auth.mismatch', $json$"The passwords don't match."$json$::jsonb),
  ('en', 'auth.forgot', $json$"Forgot your password?"$json$::jsonb),
  ('en', 'auth.reset.title', $json$"Reset your password"$json$::jsonb),
  ('en', 'auth.reset.description', $json$"We'll email you a link to choose a new password."$json$::jsonb),
  ('en', 'auth.reset.send', $json$"Send reset link"$json$::jsonb),
  ('en', 'auth.resetSent', $json$"If an account exists for this email, the reset link is on its way."$json$::jsonb),
  ('en', 'auth.backToSignIn', $json$"Back to sign in"$json$::jsonb),
  ('en', 'auth.continueWith', $json$"Continue with {provider}"$json$::jsonb),
  ('en', 'auth.or', $json$"or"$json$::jsonb),
  ('en', 'auth.rule.length', $json$"At least {min} characters"$json$::jsonb),
  ('en', 'auth.rule.lower', $json$"A lowercase letter"$json$::jsonb),
  ('en', 'auth.rule.upper', $json$"An uppercase letter"$json$::jsonb),
  ('en', 'auth.rule.digit', $json$"A digit"$json$::jsonb),
  ('en', 'auth.rule.symbol', $json$"A special character"$json$::jsonb),
  ('en', 'auth.identityTaken', $json$"This account is already linked to another JayV user."$json$::jsonb),
  ('en', 'auth.weakPassword', $json$"The server refused this password: it is too weak or has appeared in a data leak."$json$::jsonb),
  ('en', 'auth.invalidCredentials', $json$"Wrong email or password."$json$::jsonb),
  ('en', 'auth.wrongPassword', $json$"The current password is wrong."$json$::jsonb),
  ('en', 'auth.samePassword', $json$"The new password must be different from the current one."$json$::jsonb),
  ('en', 'auth.badCode', $json$"The code is invalid or has expired. Request a new one."$json$::jsonb),
  ('en', 'auth.lastIdentity', $json$"This is your only way to sign in. Set a password or link another account first."$json$::jsonb),
  ('en', 'auth.linkingDisabled', $json$"Linking accounts is turned off on the server."$json$::jsonb),
  ('en', 'auth.emailNotConfirmed', $json$"Confirm your email before signing in."$json$::jsonb),
  ('en', 'auth.newPassword.title', $json$"Choose a new password"$json$::jsonb),
  ('en', 'auth.newPassword.description', $json$"You opened the reset link. Pick the password you will use from now on."$json$::jsonb),
  ('en', 'auth.newPassword.save', $json$"Save password"$json$::jsonb),
  ('en', 'auth.newPassword.saved', $json$"Password saved."$json$::jsonb),
  ('en', 'profile.password', $json$"Password"$json$::jsonb),
  ('en', 'profile.unset', $json$"Not informed"$json$::jsonb),
  ('en', 'profile.save', $json$"Save"$json$::jsonb),
  ('en', 'profile.skip', $json$"Skip for now"$json$::jsonb),
  ('en', 'profile.saved', $json$"Profile saved."$json$::jsonb),
  ('en', 'profile.invalid', $json$"Some field has a value the server does not accept. Check it and try again."$json$::jsonb),
  ('en', 'profile.setup.title', $json$"Complete your profile"$json$::jsonb),
  ('en', 'profile.setup.description', $json$"Only the display name is required. You can change everything later on the Profile page."$json$::jsonb),
  ('en', 'profile.data.title', $json$"Personal data"$json$::jsonb),
  ('en', 'profile.data.description', $json$"Only the display name is required. No documents, address or phone number."$json$::jsonb),
  ('en', 'profile.field.displayName', $json$"Display name"$json$::jsonb),
  ('en', 'profile.field.displayName.hint', $json$"How you appear in JayV."$json$::jsonb),
  ('en', 'profile.field.fullName', $json$"Full name"$json$::jsonb),
  ('en', 'profile.field.sex', $json$"Sex"$json$::jsonb),
  ('en', 'profile.field.gender', $json$"Gender"$json$::jsonb),
  ('en', 'profile.field.genderCustom', $json$"Your gender"$json$::jsonb),
  ('en', 'profile.field.pronouns', $json$"Pronouns"$json$::jsonb),
  ('en', 'profile.field.pronounsCustom', $json$"Your pronouns"$json$::jsonb),
  ('en', 'profile.field.birthDate', $json$"Date of birth"$json$::jsonb),
  ('en', 'profile.field.country', $json$"Country"$json$::jsonb),
  ('en', 'profile.field.timezone', $json$"Time zone"$json$::jsonb),
  ('en', 'profile.field.role', $json$"Role"$json$::jsonb),
  ('en', 'profile.field.company', $json$"Company"$json$::jsonb),
  ('en', 'profile.sex.female', $json$"Female"$json$::jsonb),
  ('en', 'profile.sex.male', $json$"Male"$json$::jsonb),
  ('en', 'profile.sex.intersex', $json$"Intersex"$json$::jsonb),
  ('en', 'profile.sex.undisclosed', $json$"Prefer not to say"$json$::jsonb),
  ('en', 'profile.gender.woman', $json$"Woman"$json$::jsonb),
  ('en', 'profile.gender.man', $json$"Man"$json$::jsonb),
  ('en', 'profile.gender.non_binary', $json$"Non-binary"$json$::jsonb),
  ('en', 'profile.gender.other', $json$"Other"$json$::jsonb),
  ('en', 'profile.gender.undisclosed', $json$"Prefer not to say"$json$::jsonb),
  ('en', 'profile.pronouns.she', $json$"she/her"$json$::jsonb),
  ('en', 'profile.pronouns.he', $json$"he/him"$json$::jsonb),
  ('en', 'profile.pronouns.they', $json$"they/them"$json$::jsonb),
  ('en', 'profile.pronouns.custom', $json$"Custom"$json$::jsonb),
  ('en', 'profile.pronouns.undisclosed', $json$"Prefer not to say"$json$::jsonb),
  ('en', 'profile.role.developer', $json$"Developer"$json$::jsonb),
  ('en', 'profile.role.tech_lead', $json$"Tech lead"$json$::jsonb),
  ('en', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('en', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('en', 'profile.role.designer', $json$"Designer"$json$::jsonb),
  ('en', 'profile.role.manager', $json$"Manager"$json$::jsonb),
  ('en', 'profile.role.data', $json$"Data"$json$::jsonb),
  ('en', 'profile.role.other', $json$"Other"$json$::jsonb),
  ('en', 'security.title', $json$"Security"$json$::jsonb),
  ('en', 'security.description', $json$"The password for signing in with your email."$json$::jsonb),
  ('en', 'security.current', $json$"Current password"$json$::jsonb),
  ('en', 'security.new', $json$"New password"$json$::jsonb),
  ('en', 'security.confirm', $json$"Confirm the new password"$json$::jsonb),
  ('en', 'security.change', $json$"Change password"$json$::jsonb),
  ('en', 'security.changed', $json$"Password changed."$json$::jsonb),
  ('en', 'security.noPassword', $json$"Your account has no password yet: you sign in only through a linked account. Set one to also sign in with your email."$json$::jsonb),
  ('en', 'security.sendCode', $json$"Email me a code"$json$::jsonb),
  ('en', 'security.codeSent', $json$"We sent a 6-digit code to {email}."$json$::jsonb),
  ('en', 'security.code', $json$"Code from the email"$json$::jsonb),
  ('en', 'security.setPassword', $json$"Set password"$json$::jsonb),
  ('en', 'security.set', $json$"Password set. You can now sign in with your email."$json$::jsonb),
  ('en', 'linked.title', $json$"Linked accounts"$json$::jsonb),
  ('en', 'linked.description', $json$"Sign in with any of them. Unlinking is blocked while it is your only way in."$json$::jsonb),
  ('en', 'linked.on', $json$"Linked"$json$::jsonb),
  ('en', 'linked.off', $json$"Not linked"$json$::jsonb),
  ('en', 'linked.link', $json$"Link"$json$::jsonb),
  ('en', 'linked.unlink', $json$"Unlink"$json$::jsonb),
  ('en', 'linked.unlink.title', $json$"Unlink {provider}"$json$::jsonb),
  ('en', 'linked.unlink.description', $json$"You will no longer be able to sign in with {provider}."$json$::jsonb),
  ('es', 'auth.displayName', $json$"Nombre visible"$json$::jsonb),
  ('es', 'auth.confirmPassword', $json$"Confirma la contraseña"$json$::jsonb),
  ('es', 'auth.mismatch', $json$"Las contraseñas no coinciden."$json$::jsonb),
  ('es', 'auth.forgot', $json$"¿Olvidaste tu contraseña?"$json$::jsonb),
  ('es', 'auth.reset.title', $json$"Restablece tu contraseña"$json$::jsonb),
  ('es', 'auth.reset.description', $json$"Te enviaremos un enlace por correo para elegir una nueva contraseña."$json$::jsonb),
  ('es', 'auth.reset.send', $json$"Enviar enlace"$json$::jsonb),
  ('es', 'auth.resetSent', $json$"Si existe una cuenta con este correo, el enlace está en camino."$json$::jsonb),
  ('es', 'auth.backToSignIn', $json$"Volver a iniciar sesión"$json$::jsonb),
  ('es', 'auth.continueWith', $json$"Continuar con {provider}"$json$::jsonb),
  ('es', 'auth.or', $json$"o"$json$::jsonb),
  ('es', 'auth.rule.length', $json$"Al menos {min} caracteres"$json$::jsonb),
  ('es', 'auth.rule.lower', $json$"Una letra minúscula"$json$::jsonb),
  ('es', 'auth.rule.upper', $json$"Una letra mayúscula"$json$::jsonb),
  ('es', 'auth.rule.digit', $json$"Un dígito"$json$::jsonb),
  ('es', 'auth.rule.symbol', $json$"Un carácter especial"$json$::jsonb),
  ('es', 'auth.identityTaken', $json$"Esta cuenta ya está vinculada a otro usuario de JayV."$json$::jsonb),
  ('es', 'auth.weakPassword', $json$"El servidor rechazó esta contraseña: es demasiado débil o apareció en una filtración de datos."$json$::jsonb),
  ('es', 'auth.invalidCredentials', $json$"Correo o contraseña incorrectos."$json$::jsonb),
  ('es', 'auth.wrongPassword', $json$"La contraseña actual es incorrecta."$json$::jsonb),
  ('es', 'auth.samePassword', $json$"La nueva contraseña debe ser distinta de la actual."$json$::jsonb),
  ('es', 'auth.badCode', $json$"El código no es válido o caducó. Pide uno nuevo."$json$::jsonb),
  ('es', 'auth.lastIdentity', $json$"Es tu única forma de entrar. Define una contraseña o vincula otra cuenta primero."$json$::jsonb),
  ('es', 'auth.linkingDisabled', $json$"La vinculación de cuentas está desactivada en el servidor."$json$::jsonb),
  ('es', 'auth.emailNotConfirmed', $json$"Confirma tu correo antes de iniciar sesión."$json$::jsonb),
  ('es', 'auth.newPassword.title', $json$"Elige una nueva contraseña"$json$::jsonb),
  ('es', 'auth.newPassword.description', $json$"Abriste el enlace de restablecimiento. Elige la contraseña que usarás a partir de ahora."$json$::jsonb),
  ('es', 'auth.newPassword.save', $json$"Guardar contraseña"$json$::jsonb),
  ('es', 'auth.newPassword.saved', $json$"Contraseña guardada."$json$::jsonb),
  ('es', 'profile.password', $json$"Contraseña"$json$::jsonb),
  ('es', 'profile.unset', $json$"Sin indicar"$json$::jsonb),
  ('es', 'profile.save', $json$"Guardar"$json$::jsonb),
  ('es', 'profile.skip', $json$"Omitir por ahora"$json$::jsonb),
  ('es', 'profile.saved', $json$"Perfil guardado."$json$::jsonb),
  ('es', 'profile.invalid', $json$"Algún campo tiene un valor que el servidor no acepta. Revísalo e inténtalo de nuevo."$json$::jsonb),
  ('es', 'profile.setup.title', $json$"Completa tu perfil"$json$::jsonb),
  ('es', 'profile.setup.description', $json$"Solo el nombre visible es obligatorio. Puedes cambiarlo todo después en la página de Perfil."$json$::jsonb),
  ('es', 'profile.data.title', $json$"Datos personales"$json$::jsonb),
  ('es', 'profile.data.description', $json$"Solo el nombre visible es obligatorio. Sin documentos, dirección ni teléfono."$json$::jsonb),
  ('es', 'profile.field.displayName', $json$"Nombre visible"$json$::jsonb),
  ('es', 'profile.field.displayName.hint', $json$"Cómo apareces en JayV."$json$::jsonb),
  ('es', 'profile.field.fullName', $json$"Nombre completo"$json$::jsonb),
  ('es', 'profile.field.sex', $json$"Sexo"$json$::jsonb),
  ('es', 'profile.field.gender', $json$"Género"$json$::jsonb),
  ('es', 'profile.field.genderCustom', $json$"Tu género"$json$::jsonb),
  ('es', 'profile.field.pronouns', $json$"Pronombres"$json$::jsonb),
  ('es', 'profile.field.pronounsCustom', $json$"Tus pronombres"$json$::jsonb),
  ('es', 'profile.field.birthDate', $json$"Fecha de nacimiento"$json$::jsonb),
  ('es', 'profile.field.country', $json$"País"$json$::jsonb),
  ('es', 'profile.field.timezone', $json$"Zona horaria"$json$::jsonb),
  ('es', 'profile.field.role', $json$"Puesto"$json$::jsonb),
  ('es', 'profile.field.company', $json$"Empresa"$json$::jsonb),
  ('es', 'profile.sex.female', $json$"Femenino"$json$::jsonb),
  ('es', 'profile.sex.male', $json$"Masculino"$json$::jsonb),
  ('es', 'profile.sex.intersex', $json$"Intersexual"$json$::jsonb),
  ('es', 'profile.sex.undisclosed', $json$"Prefiero no decirlo"$json$::jsonb),
  ('es', 'profile.gender.woman', $json$"Mujer"$json$::jsonb),
  ('es', 'profile.gender.man', $json$"Hombre"$json$::jsonb),
  ('es', 'profile.gender.non_binary', $json$"No binario"$json$::jsonb),
  ('es', 'profile.gender.other', $json$"Otro"$json$::jsonb),
  ('es', 'profile.gender.undisclosed', $json$"Prefiero no decirlo"$json$::jsonb),
  ('es', 'profile.pronouns.she', $json$"ella"$json$::jsonb),
  ('es', 'profile.pronouns.he', $json$"él"$json$::jsonb),
  ('es', 'profile.pronouns.they', $json$"elle"$json$::jsonb),
  ('es', 'profile.pronouns.custom', $json$"Personalizado"$json$::jsonb),
  ('es', 'profile.pronouns.undisclosed', $json$"Prefiero no decirlo"$json$::jsonb),
  ('es', 'profile.role.developer', $json$"Desarrollo"$json$::jsonb),
  ('es', 'profile.role.tech_lead', $json$"Líder técnico"$json$::jsonb),
  ('es', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('es', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('es', 'profile.role.designer', $json$"Diseño"$json$::jsonb),
  ('es', 'profile.role.manager', $json$"Gestión"$json$::jsonb),
  ('es', 'profile.role.data', $json$"Datos"$json$::jsonb),
  ('es', 'profile.role.other', $json$"Otro"$json$::jsonb),
  ('es', 'security.title', $json$"Seguridad"$json$::jsonb),
  ('es', 'security.description', $json$"La contraseña para iniciar sesión con tu correo."$json$::jsonb),
  ('es', 'security.current', $json$"Contraseña actual"$json$::jsonb),
  ('es', 'security.new', $json$"Nueva contraseña"$json$::jsonb),
  ('es', 'security.confirm', $json$"Confirma la nueva contraseña"$json$::jsonb),
  ('es', 'security.change', $json$"Cambiar contraseña"$json$::jsonb),
  ('es', 'security.changed', $json$"Contraseña cambiada."$json$::jsonb),
  ('es', 'security.noPassword', $json$"Tu cuenta aún no tiene contraseña: solo entras con una cuenta vinculada. Define una para entrar también con tu correo."$json$::jsonb),
  ('es', 'security.sendCode', $json$"Enviarme un código"$json$::jsonb),
  ('es', 'security.codeSent', $json$"Enviamos un código de 6 dígitos a {email}."$json$::jsonb),
  ('es', 'security.code', $json$"Código del correo"$json$::jsonb),
  ('es', 'security.setPassword', $json$"Definir contraseña"$json$::jsonb),
  ('es', 'security.set', $json$"Contraseña definida. Ahora también puedes entrar con tu correo."$json$::jsonb),
  ('es', 'linked.title', $json$"Cuentas vinculadas"$json$::jsonb),
  ('es', 'linked.description', $json$"Entra con cualquiera de ellas. Desvincular queda bloqueado mientras sea tu única forma de entrar."$json$::jsonb),
  ('es', 'linked.on', $json$"Vinculada"$json$::jsonb),
  ('es', 'linked.off', $json$"No vinculada"$json$::jsonb),
  ('es', 'linked.link', $json$"Vincular"$json$::jsonb),
  ('es', 'linked.unlink', $json$"Desvincular"$json$::jsonb),
  ('es', 'linked.unlink.title', $json$"Desvincular {provider}"$json$::jsonb),
  ('es', 'linked.unlink.description', $json$"Ya no podrás entrar con {provider}."$json$::jsonb),
  ('zh-CN', 'auth.displayName', $json$"显示名称"$json$::jsonb),
  ('zh-CN', 'auth.confirmPassword', $json$"确认密码"$json$::jsonb),
  ('zh-CN', 'auth.mismatch', $json$"两次输入的密码不一致。"$json$::jsonb),
  ('zh-CN', 'auth.forgot', $json$"忘记密码？"$json$::jsonb),
  ('zh-CN', 'auth.reset.title', $json$"重置密码"$json$::jsonb),
  ('zh-CN', 'auth.reset.description', $json$"我们会通过邮件发送一个链接，供你设置新密码。"$json$::jsonb),
  ('zh-CN', 'auth.reset.send', $json$"发送重置链接"$json$::jsonb),
  ('zh-CN', 'auth.resetSent', $json$"如果该邮箱存在账户，重置链接已发出。"$json$::jsonb),
  ('zh-CN', 'auth.backToSignIn', $json$"返回登录"$json$::jsonb),
  ('zh-CN', 'auth.continueWith', $json$"使用 {provider} 继续"$json$::jsonb),
  ('zh-CN', 'auth.or', $json$"或"$json$::jsonb),
  ('zh-CN', 'auth.rule.length', $json$"至少 {min} 个字符"$json$::jsonb),
  ('zh-CN', 'auth.rule.lower', $json$"一个小写字母"$json$::jsonb),
  ('zh-CN', 'auth.rule.upper', $json$"一个大写字母"$json$::jsonb),
  ('zh-CN', 'auth.rule.digit', $json$"一个数字"$json$::jsonb),
  ('zh-CN', 'auth.rule.symbol', $json$"一个特殊字符"$json$::jsonb),
  ('zh-CN', 'auth.identityTaken', $json$"该账户已关联到另一个 JayV 用户。"$json$::jsonb),
  ('zh-CN', 'auth.weakPassword', $json$"服务器拒绝了此密码：强度太弱或曾出现在数据泄露中。"$json$::jsonb),
  ('zh-CN', 'auth.invalidCredentials', $json$"邮箱或密码错误。"$json$::jsonb),
  ('zh-CN', 'auth.wrongPassword', $json$"当前密码错误。"$json$::jsonb),
  ('zh-CN', 'auth.samePassword', $json$"新密码必须与当前密码不同。"$json$::jsonb),
  ('zh-CN', 'auth.badCode', $json$"验证码无效或已过期，请重新获取。"$json$::jsonb),
  ('zh-CN', 'auth.lastIdentity', $json$"这是你唯一的登录方式。请先设置密码或关联其他账户。"$json$::jsonb),
  ('zh-CN', 'auth.linkingDisabled', $json$"服务器已关闭账户关联。"$json$::jsonb),
  ('zh-CN', 'auth.emailNotConfirmed', $json$"请先验证邮箱再登录。"$json$::jsonb),
  ('zh-CN', 'auth.newPassword.title', $json$"设置新密码"$json$::jsonb),
  ('zh-CN', 'auth.newPassword.description', $json$"你已打开重置链接。请设置今后使用的密码。"$json$::jsonb),
  ('zh-CN', 'auth.newPassword.save', $json$"保存密码"$json$::jsonb),
  ('zh-CN', 'auth.newPassword.saved', $json$"密码已保存。"$json$::jsonb),
  ('zh-CN', 'profile.password', $json$"密码"$json$::jsonb),
  ('zh-CN', 'profile.unset', $json$"未填写"$json$::jsonb),
  ('zh-CN', 'profile.save', $json$"保存"$json$::jsonb),
  ('zh-CN', 'profile.skip', $json$"暂时跳过"$json$::jsonb),
  ('zh-CN', 'profile.saved', $json$"个人资料已保存。"$json$::jsonb),
  ('zh-CN', 'profile.invalid', $json$"某个字段的值服务器不接受，请检查后重试。"$json$::jsonb),
  ('zh-CN', 'profile.setup.title', $json$"完善你的个人资料"$json$::jsonb),
  ('zh-CN', 'profile.setup.description', $json$"只有显示名称是必填的。之后可以在个人资料页修改全部内容。"$json$::jsonb),
  ('zh-CN', 'profile.data.title', $json$"个人信息"$json$::jsonb),
  ('zh-CN', 'profile.data.description', $json$"只有显示名称是必填的。不收集证件、地址或电话。"$json$::jsonb),
  ('zh-CN', 'profile.field.displayName', $json$"显示名称"$json$::jsonb),
  ('zh-CN', 'profile.field.displayName.hint', $json$"你在 JayV 中显示的名字。"$json$::jsonb),
  ('zh-CN', 'profile.field.fullName', $json$"全名"$json$::jsonb),
  ('zh-CN', 'profile.field.sex', $json$"性别"$json$::jsonb),
  ('zh-CN', 'profile.field.gender', $json$"性别认同"$json$::jsonb),
  ('zh-CN', 'profile.field.genderCustom', $json$"你的性别认同"$json$::jsonb),
  ('zh-CN', 'profile.field.pronouns', $json$"代词"$json$::jsonb),
  ('zh-CN', 'profile.field.pronounsCustom', $json$"你的代词"$json$::jsonb),
  ('zh-CN', 'profile.field.birthDate', $json$"出生日期"$json$::jsonb),
  ('zh-CN', 'profile.field.country', $json$"国家/地区"$json$::jsonb),
  ('zh-CN', 'profile.field.timezone', $json$"时区"$json$::jsonb),
  ('zh-CN', 'profile.field.role', $json$"角色"$json$::jsonb),
  ('zh-CN', 'profile.field.company', $json$"公司"$json$::jsonb),
  ('zh-CN', 'profile.sex.female', $json$"女"$json$::jsonb),
  ('zh-CN', 'profile.sex.male', $json$"男"$json$::jsonb),
  ('zh-CN', 'profile.sex.intersex', $json$"间性"$json$::jsonb),
  ('zh-CN', 'profile.sex.undisclosed', $json$"不愿透露"$json$::jsonb),
  ('zh-CN', 'profile.gender.woman', $json$"女性"$json$::jsonb),
  ('zh-CN', 'profile.gender.man', $json$"男性"$json$::jsonb),
  ('zh-CN', 'profile.gender.non_binary', $json$"非二元"$json$::jsonb),
  ('zh-CN', 'profile.gender.other', $json$"其他"$json$::jsonb),
  ('zh-CN', 'profile.gender.undisclosed', $json$"不愿透露"$json$::jsonb),
  ('zh-CN', 'profile.pronouns.she', $json$"她"$json$::jsonb),
  ('zh-CN', 'profile.pronouns.he', $json$"他"$json$::jsonb),
  ('zh-CN', 'profile.pronouns.they', $json$"TA"$json$::jsonb),
  ('zh-CN', 'profile.pronouns.custom', $json$"自定义"$json$::jsonb),
  ('zh-CN', 'profile.pronouns.undisclosed', $json$"不愿透露"$json$::jsonb),
  ('zh-CN', 'profile.role.developer', $json$"开发"$json$::jsonb),
  ('zh-CN', 'profile.role.tech_lead', $json$"技术负责人"$json$::jsonb),
  ('zh-CN', 'profile.role.qa', $json$"测试"$json$::jsonb),
  ('zh-CN', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('zh-CN', 'profile.role.designer', $json$"设计"$json$::jsonb),
  ('zh-CN', 'profile.role.manager', $json$"管理"$json$::jsonb),
  ('zh-CN', 'profile.role.data', $json$"数据"$json$::jsonb),
  ('zh-CN', 'profile.role.other', $json$"其他"$json$::jsonb),
  ('zh-CN', 'security.title', $json$"安全"$json$::jsonb),
  ('zh-CN', 'security.description', $json$"使用邮箱登录的密码。"$json$::jsonb),
  ('zh-CN', 'security.current', $json$"当前密码"$json$::jsonb),
  ('zh-CN', 'security.new', $json$"新密码"$json$::jsonb),
  ('zh-CN', 'security.confirm', $json$"确认新密码"$json$::jsonb),
  ('zh-CN', 'security.change', $json$"修改密码"$json$::jsonb),
  ('zh-CN', 'security.changed', $json$"密码已修改。"$json$::jsonb),
  ('zh-CN', 'security.noPassword', $json$"你的账户还没有密码，只能通过关联账户登录。设置密码后也可以用邮箱登录。"$json$::jsonb),
  ('zh-CN', 'security.sendCode', $json$"通过邮件发送验证码"$json$::jsonb),
  ('zh-CN', 'security.codeSent', $json$"我们已向 {email} 发送了 6 位验证码。"$json$::jsonb),
  ('zh-CN', 'security.code', $json$"邮件中的验证码"$json$::jsonb),
  ('zh-CN', 'security.setPassword', $json$"设置密码"$json$::jsonb),
  ('zh-CN', 'security.set', $json$"密码已设置。现在也可以用邮箱登录了。"$json$::jsonb),
  ('zh-CN', 'linked.title', $json$"已关联账户"$json$::jsonb),
  ('zh-CN', 'linked.description', $json$"可用其中任意一个登录。若它是唯一的登录方式，则无法解除关联。"$json$::jsonb),
  ('zh-CN', 'linked.on', $json$"已关联"$json$::jsonb),
  ('zh-CN', 'linked.off', $json$"未关联"$json$::jsonb),
  ('zh-CN', 'linked.link', $json$"关联"$json$::jsonb),
  ('zh-CN', 'linked.unlink', $json$"解除关联"$json$::jsonb),
  ('zh-CN', 'linked.unlink.title', $json$"解除关联 {provider}"$json$::jsonb),
  ('zh-CN', 'linked.unlink.description', $json$"你将无法再使用 {provider} 登录。"$json$::jsonb),
  ('hi', 'auth.displayName', $json$"प्रदर्शित नाम"$json$::jsonb),
  ('hi', 'auth.confirmPassword', $json$"पासवर्ड की पुष्टि करें"$json$::jsonb),
  ('hi', 'auth.mismatch', $json$"पासवर्ड मेल नहीं खाते।"$json$::jsonb),
  ('hi', 'auth.forgot', $json$"पासवर्ड भूल गए?"$json$::jsonb),
  ('hi', 'auth.reset.title', $json$"अपना पासवर्ड रीसेट करें"$json$::jsonb),
  ('hi', 'auth.reset.description', $json$"हम आपको नया पासवर्ड चुनने के लिए ईमेल पर एक लिंक भेजेंगे।"$json$::jsonb),
  ('hi', 'auth.reset.send', $json$"रीसेट लिंक भेजें"$json$::jsonb),
  ('hi', 'auth.resetSent', $json$"अगर इस ईमेल से कोई खाता है, तो रीसेट लिंक भेज दिया गया है।"$json$::jsonb),
  ('hi', 'auth.backToSignIn', $json$"साइन इन पर वापस जाएँ"$json$::jsonb),
  ('hi', 'auth.continueWith', $json$"{provider} से जारी रखें"$json$::jsonb),
  ('hi', 'auth.or', $json$"या"$json$::jsonb),
  ('hi', 'auth.rule.length', $json$"कम से कम {min} अक्षर"$json$::jsonb),
  ('hi', 'auth.rule.lower', $json$"एक छोटा अक्षर"$json$::jsonb),
  ('hi', 'auth.rule.upper', $json$"एक बड़ा अक्षर"$json$::jsonb),
  ('hi', 'auth.rule.digit', $json$"एक अंक"$json$::jsonb),
  ('hi', 'auth.rule.symbol', $json$"एक विशेष वर्ण"$json$::jsonb),
  ('hi', 'auth.identityTaken', $json$"यह खाता पहले से किसी दूसरे JayV उपयोगकर्ता से जुड़ा है।"$json$::jsonb),
  ('hi', 'auth.weakPassword', $json$"सर्वर ने यह पासवर्ड अस्वीकार कर दिया: यह बहुत कमज़ोर है या किसी डेटा लीक में आ चुका है।"$json$::jsonb),
  ('hi', 'auth.invalidCredentials', $json$"ईमेल या पासवर्ड गलत है।"$json$::jsonb),
  ('hi', 'auth.wrongPassword', $json$"मौजूदा पासवर्ड गलत है।"$json$::jsonb),
  ('hi', 'auth.samePassword', $json$"नया पासवर्ड मौजूदा पासवर्ड से अलग होना चाहिए।"$json$::jsonb),
  ('hi', 'auth.badCode', $json$"कोड अमान्य है या उसकी समय-सीमा खत्म हो गई है। नया कोड मँगाएँ।"$json$::jsonb),
  ('hi', 'auth.lastIdentity', $json$"यह आपके साइन इन का इकलौता तरीका है। पहले पासवर्ड सेट करें या कोई दूसरा खाता जोड़ें।"$json$::jsonb),
  ('hi', 'auth.linkingDisabled', $json$"सर्वर पर खाते जोड़ना बंद है।"$json$::jsonb),
  ('hi', 'auth.emailNotConfirmed', $json$"साइन इन करने से पहले अपना ईमेल पुष्टि करें।"$json$::jsonb),
  ('hi', 'auth.newPassword.title', $json$"नया पासवर्ड चुनें"$json$::jsonb),
  ('hi', 'auth.newPassword.description', $json$"आपने रीसेट लिंक खोला है। अब से इस्तेमाल होने वाला पासवर्ड चुनें।"$json$::jsonb),
  ('hi', 'auth.newPassword.save', $json$"पासवर्ड सहेजें"$json$::jsonb),
  ('hi', 'auth.newPassword.saved', $json$"पासवर्ड सहेजा गया।"$json$::jsonb),
  ('hi', 'profile.password', $json$"पासवर्ड"$json$::jsonb),
  ('hi', 'profile.unset', $json$"नहीं बताया"$json$::jsonb),
  ('hi', 'profile.save', $json$"सहेजें"$json$::jsonb),
  ('hi', 'profile.skip', $json$"अभी छोड़ें"$json$::jsonb),
  ('hi', 'profile.saved', $json$"प्रोफ़ाइल सहेजी गई।"$json$::jsonb),
  ('hi', 'profile.invalid', $json$"किसी फ़ील्ड में ऐसा मान है जिसे सर्वर स्वीकार नहीं करता। जाँचकर फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'profile.setup.title', $json$"अपनी प्रोफ़ाइल पूरी करें"$json$::jsonb),
  ('hi', 'profile.setup.description', $json$"केवल प्रदर्शित नाम ज़रूरी है। बाकी सब बाद में प्रोफ़ाइल पेज पर बदल सकते हैं।"$json$::jsonb),
  ('hi', 'profile.data.title', $json$"व्यक्तिगत जानकारी"$json$::jsonb),
  ('hi', 'profile.data.description', $json$"केवल प्रदर्शित नाम ज़रूरी है। कोई दस्तावेज़, पता या फ़ोन नहीं।"$json$::jsonb),
  ('hi', 'profile.field.displayName', $json$"प्रदर्शित नाम"$json$::jsonb),
  ('hi', 'profile.field.displayName.hint', $json$"JayV में आप इसी नाम से दिखेंगे।"$json$::jsonb),
  ('hi', 'profile.field.fullName', $json$"पूरा नाम"$json$::jsonb),
  ('hi', 'profile.field.sex', $json$"लिंग"$json$::jsonb),
  ('hi', 'profile.field.gender', $json$"जेंडर"$json$::jsonb),
  ('hi', 'profile.field.genderCustom', $json$"आपका जेंडर"$json$::jsonb),
  ('hi', 'profile.field.pronouns', $json$"सर्वनाम"$json$::jsonb),
  ('hi', 'profile.field.pronounsCustom', $json$"आपके सर्वनाम"$json$::jsonb),
  ('hi', 'profile.field.birthDate', $json$"जन्म तिथि"$json$::jsonb),
  ('hi', 'profile.field.country', $json$"देश"$json$::jsonb),
  ('hi', 'profile.field.timezone', $json$"समय क्षेत्र"$json$::jsonb),
  ('hi', 'profile.field.role', $json$"भूमिका"$json$::jsonb),
  ('hi', 'profile.field.company', $json$"कंपनी"$json$::jsonb),
  ('hi', 'profile.sex.female', $json$"महिला"$json$::jsonb),
  ('hi', 'profile.sex.male', $json$"पुरुष"$json$::jsonb),
  ('hi', 'profile.sex.intersex', $json$"इंटरसेक्स"$json$::jsonb),
  ('hi', 'profile.sex.undisclosed', $json$"बताना नहीं चाहते"$json$::jsonb),
  ('hi', 'profile.gender.woman', $json$"महिला"$json$::jsonb),
  ('hi', 'profile.gender.man', $json$"पुरुष"$json$::jsonb),
  ('hi', 'profile.gender.non_binary', $json$"नॉन-बाइनरी"$json$::jsonb),
  ('hi', 'profile.gender.other', $json$"अन्य"$json$::jsonb),
  ('hi', 'profile.gender.undisclosed', $json$"बताना नहीं चाहते"$json$::jsonb),
  ('hi', 'profile.pronouns.she', $json$"वह (स्त्री)"$json$::jsonb),
  ('hi', 'profile.pronouns.he', $json$"वह (पुरुष)"$json$::jsonb),
  ('hi', 'profile.pronouns.they', $json$"वे"$json$::jsonb),
  ('hi', 'profile.pronouns.custom', $json$"अपने अनुसार"$json$::jsonb),
  ('hi', 'profile.pronouns.undisclosed', $json$"बताना नहीं चाहते"$json$::jsonb),
  ('hi', 'profile.role.developer', $json$"डेवलपर"$json$::jsonb),
  ('hi', 'profile.role.tech_lead', $json$"टेक लीड"$json$::jsonb),
  ('hi', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('hi', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('hi', 'profile.role.designer', $json$"डिज़ाइनर"$json$::jsonb),
  ('hi', 'profile.role.manager', $json$"मैनेजर"$json$::jsonb),
  ('hi', 'profile.role.data', $json$"डेटा"$json$::jsonb),
  ('hi', 'profile.role.other', $json$"अन्य"$json$::jsonb),
  ('hi', 'security.title', $json$"सुरक्षा"$json$::jsonb),
  ('hi', 'security.description', $json$"अपने ईमेल से साइन इन करने का पासवर्ड।"$json$::jsonb),
  ('hi', 'security.current', $json$"मौजूदा पासवर्ड"$json$::jsonb),
  ('hi', 'security.new', $json$"नया पासवर्ड"$json$::jsonb),
  ('hi', 'security.confirm', $json$"नए पासवर्ड की पुष्टि करें"$json$::jsonb),
  ('hi', 'security.change', $json$"पासवर्ड बदलें"$json$::jsonb),
  ('hi', 'security.changed', $json$"पासवर्ड बदल दिया गया।"$json$::jsonb),
  ('hi', 'security.noPassword', $json$"आपके खाते में अभी पासवर्ड नहीं है: आप केवल जुड़े हुए खाते से साइन इन करते हैं। ईमेल से भी साइन इन करने के लिए पासवर्ड सेट करें।"$json$::jsonb),
  ('hi', 'security.sendCode', $json$"ईमेल पर कोड भेजें"$json$::jsonb),
  ('hi', 'security.codeSent', $json$"हमने {email} पर 6 अंकों का कोड भेजा है।"$json$::jsonb),
  ('hi', 'security.code', $json$"ईमेल वाला कोड"$json$::jsonb),
  ('hi', 'security.setPassword', $json$"पासवर्ड सेट करें"$json$::jsonb),
  ('hi', 'security.set', $json$"पासवर्ड सेट हो गया। अब आप अपने ईमेल से भी साइन इन कर सकते हैं।"$json$::jsonb),
  ('hi', 'linked.title', $json$"जुड़े हुए खाते"$json$::jsonb),
  ('hi', 'linked.description', $json$"इनमें से किसी से भी साइन इन करें। जब तक यह इकलौता तरीका है, हटाना बंद रहेगा।"$json$::jsonb),
  ('hi', 'linked.on', $json$"जुड़ा हुआ"$json$::jsonb),
  ('hi', 'linked.off', $json$"नहीं जुड़ा"$json$::jsonb),
  ('hi', 'linked.link', $json$"जोड़ें"$json$::jsonb),
  ('hi', 'linked.unlink', $json$"हटाएँ"$json$::jsonb),
  ('hi', 'linked.unlink.title', $json$"{provider} हटाएँ"$json$::jsonb),
  ('hi', 'linked.unlink.description', $json$"आप फिर {provider} से साइन इन नहीं कर पाएँगे।"$json$::jsonb),
  ('ar', 'auth.displayName', $json$"الاسم المعروض"$json$::jsonb),
  ('ar', 'auth.confirmPassword', $json$"تأكيد كلمة المرور"$json$::jsonb),
  ('ar', 'auth.mismatch', $json$"كلمتا المرور غير متطابقتين."$json$::jsonb),
  ('ar', 'auth.forgot', $json$"هل نسيت كلمة المرور؟"$json$::jsonb),
  ('ar', 'auth.reset.title', $json$"إعادة تعيين كلمة المرور"$json$::jsonb),
  ('ar', 'auth.reset.description', $json$"سنرسل إليك رابطًا عبر البريد الإلكتروني لاختيار كلمة مرور جديدة."$json$::jsonb),
  ('ar', 'auth.reset.send', $json$"إرسال رابط إعادة التعيين"$json$::jsonb),
  ('ar', 'auth.resetSent', $json$"إذا كان هناك حساب بهذا البريد، فرابط إعادة التعيين في الطريق."$json$::jsonb),
  ('ar', 'auth.backToSignIn', $json$"العودة إلى تسجيل الدخول"$json$::jsonb),
  ('ar', 'auth.continueWith', $json$"المتابعة باستخدام {provider}"$json$::jsonb),
  ('ar', 'auth.or', $json$"أو"$json$::jsonb),
  ('ar', 'auth.rule.length', $json$"{min} أحرف على الأقل"$json$::jsonb),
  ('ar', 'auth.rule.lower', $json$"حرف صغير"$json$::jsonb),
  ('ar', 'auth.rule.upper', $json$"حرف كبير"$json$::jsonb),
  ('ar', 'auth.rule.digit', $json$"رقم"$json$::jsonb),
  ('ar', 'auth.rule.symbol', $json$"رمز خاص"$json$::jsonb),
  ('ar', 'auth.identityTaken', $json$"هذا الحساب مرتبط بالفعل بمستخدم آخر في JayV."$json$::jsonb),
  ('ar', 'auth.weakPassword', $json$"رفض الخادم كلمة المرور هذه: إنها ضعيفة جدًا أو ظهرت في تسريب بيانات."$json$::jsonb),
  ('ar', 'auth.invalidCredentials', $json$"البريد الإلكتروني أو كلمة المرور غير صحيحة."$json$::jsonb),
  ('ar', 'auth.wrongPassword', $json$"كلمة المرور الحالية غير صحيحة."$json$::jsonb),
  ('ar', 'auth.samePassword', $json$"يجب أن تختلف كلمة المرور الجديدة عن الحالية."$json$::jsonb),
  ('ar', 'auth.badCode', $json$"الرمز غير صالح أو منتهي الصلاحية. اطلب رمزًا جديدًا."$json$::jsonb),
  ('ar', 'auth.lastIdentity', $json$"هذه طريقتك الوحيدة لتسجيل الدخول. عيّن كلمة مرور أو اربط حسابًا آخر أولًا."$json$::jsonb),
  ('ar', 'auth.linkingDisabled', $json$"ربط الحسابات معطّل على الخادم."$json$::jsonb),
  ('ar', 'auth.emailNotConfirmed', $json$"أكّد بريدك الإلكتروني قبل تسجيل الدخول."$json$::jsonb),
  ('ar', 'auth.newPassword.title', $json$"اختر كلمة مرور جديدة"$json$::jsonb),
  ('ar', 'auth.newPassword.description', $json$"لقد فتحت رابط إعادة التعيين. اختر كلمة المرور التي ستستخدمها من الآن."$json$::jsonb),
  ('ar', 'auth.newPassword.save', $json$"حفظ كلمة المرور"$json$::jsonb),
  ('ar', 'auth.newPassword.saved', $json$"تم حفظ كلمة المرور."$json$::jsonb),
  ('ar', 'profile.password', $json$"كلمة المرور"$json$::jsonb),
  ('ar', 'profile.unset', $json$"غير محدد"$json$::jsonb),
  ('ar', 'profile.save', $json$"حفظ"$json$::jsonb),
  ('ar', 'profile.skip', $json$"تخطَّ الآن"$json$::jsonb),
  ('ar', 'profile.saved', $json$"تم حفظ الملف الشخصي."$json$::jsonb),
  ('ar', 'profile.invalid', $json$"يحتوي أحد الحقول على قيمة لا يقبلها الخادم. تحقق منها وحاول مرة أخرى."$json$::jsonb),
  ('ar', 'profile.setup.title', $json$"أكمل ملفك الشخصي"$json$::jsonb),
  ('ar', 'profile.setup.description', $json$"الاسم المعروض وحده إلزامي. يمكنك تغيير كل شيء لاحقًا في صفحة الملف الشخصي."$json$::jsonb),
  ('ar', 'profile.data.title', $json$"البيانات الشخصية"$json$::jsonb),
  ('ar', 'profile.data.description', $json$"الاسم المعروض وحده إلزامي. لا وثائق ولا عنوان ولا هاتف."$json$::jsonb),
  ('ar', 'profile.field.displayName', $json$"الاسم المعروض"$json$::jsonb),
  ('ar', 'profile.field.displayName.hint', $json$"كيف تظهر في JayV."$json$::jsonb),
  ('ar', 'profile.field.fullName', $json$"الاسم الكامل"$json$::jsonb),
  ('ar', 'profile.field.sex', $json$"الجنس"$json$::jsonb),
  ('ar', 'profile.field.gender', $json$"الهوية الجندرية"$json$::jsonb),
  ('ar', 'profile.field.genderCustom', $json$"هويتك الجندرية"$json$::jsonb),
  ('ar', 'profile.field.pronouns', $json$"الضمائر"$json$::jsonb),
  ('ar', 'profile.field.pronounsCustom', $json$"ضمائرك"$json$::jsonb),
  ('ar', 'profile.field.birthDate', $json$"تاريخ الميلاد"$json$::jsonb),
  ('ar', 'profile.field.country', $json$"الدولة"$json$::jsonb),
  ('ar', 'profile.field.timezone', $json$"المنطقة الزمنية"$json$::jsonb),
  ('ar', 'profile.field.role', $json$"الدور"$json$::jsonb),
  ('ar', 'profile.field.company', $json$"الشركة"$json$::jsonb),
  ('ar', 'profile.sex.female', $json$"أنثى"$json$::jsonb),
  ('ar', 'profile.sex.male', $json$"ذكر"$json$::jsonb),
  ('ar', 'profile.sex.intersex', $json$"ثنائي الجنس"$json$::jsonb),
  ('ar', 'profile.sex.undisclosed', $json$"أفضّل عدم الإفصاح"$json$::jsonb),
  ('ar', 'profile.gender.woman', $json$"امرأة"$json$::jsonb),
  ('ar', 'profile.gender.man', $json$"رجل"$json$::jsonb),
  ('ar', 'profile.gender.non_binary', $json$"غير ثنائي"$json$::jsonb),
  ('ar', 'profile.gender.other', $json$"آخر"$json$::jsonb),
  ('ar', 'profile.gender.undisclosed', $json$"أفضّل عدم الإفصاح"$json$::jsonb),
  ('ar', 'profile.pronouns.she', $json$"هي"$json$::jsonb),
  ('ar', 'profile.pronouns.he', $json$"هو"$json$::jsonb),
  ('ar', 'profile.pronouns.they', $json$"هم"$json$::jsonb),
  ('ar', 'profile.pronouns.custom', $json$"مخصص"$json$::jsonb),
  ('ar', 'profile.pronouns.undisclosed', $json$"أفضّل عدم الإفصاح"$json$::jsonb),
  ('ar', 'profile.role.developer', $json$"مطوّر"$json$::jsonb),
  ('ar', 'profile.role.tech_lead', $json$"قائد تقني"$json$::jsonb),
  ('ar', 'profile.role.qa', $json$"ضمان الجودة"$json$::jsonb),
  ('ar', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('ar', 'profile.role.designer', $json$"مصمم"$json$::jsonb),
  ('ar', 'profile.role.manager', $json$"مدير"$json$::jsonb),
  ('ar', 'profile.role.data', $json$"البيانات"$json$::jsonb),
  ('ar', 'profile.role.other', $json$"أخرى"$json$::jsonb),
  ('ar', 'security.title', $json$"الأمان"$json$::jsonb),
  ('ar', 'security.description', $json$"كلمة المرور لتسجيل الدخول ببريدك الإلكتروني."$json$::jsonb),
  ('ar', 'security.current', $json$"كلمة المرور الحالية"$json$::jsonb),
  ('ar', 'security.new', $json$"كلمة المرور الجديدة"$json$::jsonb),
  ('ar', 'security.confirm', $json$"تأكيد كلمة المرور الجديدة"$json$::jsonb),
  ('ar', 'security.change', $json$"تغيير كلمة المرور"$json$::jsonb),
  ('ar', 'security.changed', $json$"تم تغيير كلمة المرور."$json$::jsonb),
  ('ar', 'security.noPassword', $json$"لا يملك حسابك كلمة مرور بعد: تسجّل الدخول عبر حساب مرتبط فقط. عيّن واحدة لتسجّل الدخول ببريدك أيضًا."$json$::jsonb),
  ('ar', 'security.sendCode', $json$"أرسل لي رمزًا"$json$::jsonb),
  ('ar', 'security.codeSent', $json$"أرسلنا رمزًا من 6 أرقام إلى {email}."$json$::jsonb),
  ('ar', 'security.code', $json$"الرمز من البريد"$json$::jsonb),
  ('ar', 'security.setPassword', $json$"تعيين كلمة المرور"$json$::jsonb),
  ('ar', 'security.set', $json$"تم تعيين كلمة المرور. يمكنك الآن تسجيل الدخول ببريدك أيضًا."$json$::jsonb),
  ('ar', 'linked.title', $json$"الحسابات المرتبطة"$json$::jsonb),
  ('ar', 'linked.description', $json$"سجّل الدخول بأيٍّ منها. فكّ الربط محظور ما دام طريقتك الوحيدة للدخول."$json$::jsonb),
  ('ar', 'linked.on', $json$"مرتبط"$json$::jsonb),
  ('ar', 'linked.off', $json$"غير مرتبط"$json$::jsonb),
  ('ar', 'linked.link', $json$"ربط"$json$::jsonb),
  ('ar', 'linked.unlink', $json$"فكّ الربط"$json$::jsonb),
  ('ar', 'linked.unlink.title', $json$"فكّ ربط {provider}"$json$::jsonb),
  ('ar', 'linked.unlink.description', $json$"لن تتمكن بعد الآن من تسجيل الدخول باستخدام {provider}."$json$::jsonb),
  ('fr', 'auth.displayName', $json$"Nom d'affichage"$json$::jsonb),
  ('fr', 'auth.confirmPassword', $json$"Confirmez le mot de passe"$json$::jsonb),
  ('fr', 'auth.mismatch', $json$"Les mots de passe ne correspondent pas."$json$::jsonb),
  ('fr', 'auth.forgot', $json$"Mot de passe oublié ?"$json$::jsonb),
  ('fr', 'auth.reset.title', $json$"Réinitialisez votre mot de passe"$json$::jsonb),
  ('fr', 'auth.reset.description', $json$"Nous vous enverrons par e-mail un lien pour choisir un nouveau mot de passe."$json$::jsonb),
  ('fr', 'auth.reset.send', $json$"Envoyer le lien"$json$::jsonb),
  ('fr', 'auth.resetSent', $json$"Si un compte existe pour cet e-mail, le lien est en route."$json$::jsonb),
  ('fr', 'auth.backToSignIn', $json$"Retour à la connexion"$json$::jsonb),
  ('fr', 'auth.continueWith', $json$"Continuer avec {provider}"$json$::jsonb),
  ('fr', 'auth.or', $json$"ou"$json$::jsonb),
  ('fr', 'auth.rule.length', $json$"Au moins {min} caractères"$json$::jsonb),
  ('fr', 'auth.rule.lower', $json$"Une lettre minuscule"$json$::jsonb),
  ('fr', 'auth.rule.upper', $json$"Une lettre majuscule"$json$::jsonb),
  ('fr', 'auth.rule.digit', $json$"Un chiffre"$json$::jsonb),
  ('fr', 'auth.rule.symbol', $json$"Un caractère spécial"$json$::jsonb),
  ('fr', 'auth.identityTaken', $json$"Ce compte est déjà lié à un autre utilisateur JayV."$json$::jsonb),
  ('fr', 'auth.weakPassword', $json$"Le serveur a refusé ce mot de passe : il est trop faible ou figure dans une fuite de données."$json$::jsonb),
  ('fr', 'auth.invalidCredentials', $json$"E-mail ou mot de passe incorrect."$json$::jsonb),
  ('fr', 'auth.wrongPassword', $json$"Le mot de passe actuel est incorrect."$json$::jsonb),
  ('fr', 'auth.samePassword', $json$"Le nouveau mot de passe doit être différent de l'actuel."$json$::jsonb),
  ('fr', 'auth.badCode', $json$"Le code est invalide ou a expiré. Demandez-en un nouveau."$json$::jsonb),
  ('fr', 'auth.lastIdentity', $json$"C'est votre seul moyen de connexion. Définissez un mot de passe ou liez un autre compte d'abord."$json$::jsonb),
  ('fr', 'auth.linkingDisabled', $json$"La liaison de comptes est désactivée sur le serveur."$json$::jsonb),
  ('fr', 'auth.emailNotConfirmed', $json$"Confirmez votre e-mail avant de vous connecter."$json$::jsonb),
  ('fr', 'auth.newPassword.title', $json$"Choisissez un nouveau mot de passe"$json$::jsonb),
  ('fr', 'auth.newPassword.description', $json$"Vous avez ouvert le lien de réinitialisation. Choisissez le mot de passe que vous utiliserez désormais."$json$::jsonb),
  ('fr', 'auth.newPassword.save', $json$"Enregistrer le mot de passe"$json$::jsonb),
  ('fr', 'auth.newPassword.saved', $json$"Mot de passe enregistré."$json$::jsonb),
  ('fr', 'profile.password', $json$"Mot de passe"$json$::jsonb),
  ('fr', 'profile.unset', $json$"Non renseigné"$json$::jsonb),
  ('fr', 'profile.save', $json$"Enregistrer"$json$::jsonb),
  ('fr', 'profile.skip', $json$"Passer pour l'instant"$json$::jsonb),
  ('fr', 'profile.saved', $json$"Profil enregistré."$json$::jsonb),
  ('fr', 'profile.invalid', $json$"Un champ contient une valeur refusée par le serveur. Vérifiez et réessayez."$json$::jsonb),
  ('fr', 'profile.setup.title', $json$"Complétez votre profil"$json$::jsonb),
  ('fr', 'profile.setup.description', $json$"Seul le nom d'affichage est obligatoire. Vous pourrez tout modifier plus tard dans la page Profil."$json$::jsonb),
  ('fr', 'profile.data.title', $json$"Données personnelles"$json$::jsonb),
  ('fr', 'profile.data.description', $json$"Seul le nom d'affichage est obligatoire. Ni pièce d'identité, ni adresse, ni téléphone."$json$::jsonb),
  ('fr', 'profile.field.displayName', $json$"Nom d'affichage"$json$::jsonb),
  ('fr', 'profile.field.displayName.hint', $json$"Comment vous apparaissez dans JayV."$json$::jsonb),
  ('fr', 'profile.field.fullName', $json$"Nom complet"$json$::jsonb),
  ('fr', 'profile.field.sex', $json$"Sexe"$json$::jsonb),
  ('fr', 'profile.field.gender', $json$"Genre"$json$::jsonb),
  ('fr', 'profile.field.genderCustom', $json$"Votre genre"$json$::jsonb),
  ('fr', 'profile.field.pronouns', $json$"Pronoms"$json$::jsonb),
  ('fr', 'profile.field.pronounsCustom', $json$"Vos pronoms"$json$::jsonb),
  ('fr', 'profile.field.birthDate', $json$"Date de naissance"$json$::jsonb),
  ('fr', 'profile.field.country', $json$"Pays"$json$::jsonb),
  ('fr', 'profile.field.timezone', $json$"Fuseau horaire"$json$::jsonb),
  ('fr', 'profile.field.role', $json$"Rôle"$json$::jsonb),
  ('fr', 'profile.field.company', $json$"Entreprise"$json$::jsonb),
  ('fr', 'profile.sex.female', $json$"Féminin"$json$::jsonb),
  ('fr', 'profile.sex.male', $json$"Masculin"$json$::jsonb),
  ('fr', 'profile.sex.intersex', $json$"Intersexe"$json$::jsonb),
  ('fr', 'profile.sex.undisclosed', $json$"Je préfère ne pas répondre"$json$::jsonb),
  ('fr', 'profile.gender.woman', $json$"Femme"$json$::jsonb),
  ('fr', 'profile.gender.man', $json$"Homme"$json$::jsonb),
  ('fr', 'profile.gender.non_binary', $json$"Non binaire"$json$::jsonb),
  ('fr', 'profile.gender.other', $json$"Autre"$json$::jsonb),
  ('fr', 'profile.gender.undisclosed', $json$"Je préfère ne pas répondre"$json$::jsonb),
  ('fr', 'profile.pronouns.she', $json$"elle"$json$::jsonb),
  ('fr', 'profile.pronouns.he', $json$"il"$json$::jsonb),
  ('fr', 'profile.pronouns.they', $json$"iel"$json$::jsonb),
  ('fr', 'profile.pronouns.custom', $json$"Personnalisé"$json$::jsonb),
  ('fr', 'profile.pronouns.undisclosed', $json$"Je préfère ne pas répondre"$json$::jsonb),
  ('fr', 'profile.role.developer', $json$"Développement"$json$::jsonb),
  ('fr', 'profile.role.tech_lead', $json$"Tech lead"$json$::jsonb),
  ('fr', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('fr', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('fr', 'profile.role.designer', $json$"Design"$json$::jsonb),
  ('fr', 'profile.role.manager', $json$"Management"$json$::jsonb),
  ('fr', 'profile.role.data', $json$"Data"$json$::jsonb),
  ('fr', 'profile.role.other', $json$"Autre"$json$::jsonb),
  ('fr', 'security.title', $json$"Sécurité"$json$::jsonb),
  ('fr', 'security.description', $json$"Le mot de passe pour vous connecter avec votre e-mail."$json$::jsonb),
  ('fr', 'security.current', $json$"Mot de passe actuel"$json$::jsonb),
  ('fr', 'security.new', $json$"Nouveau mot de passe"$json$::jsonb),
  ('fr', 'security.confirm', $json$"Confirmez le nouveau mot de passe"$json$::jsonb),
  ('fr', 'security.change', $json$"Changer le mot de passe"$json$::jsonb),
  ('fr', 'security.changed', $json$"Mot de passe modifié."$json$::jsonb),
  ('fr', 'security.noPassword', $json$"Votre compte n'a pas encore de mot de passe : vous vous connectez uniquement via un compte lié. Définissez-en un pour vous connecter aussi avec votre e-mail."$json$::jsonb),
  ('fr', 'security.sendCode', $json$"M'envoyer un code"$json$::jsonb),
  ('fr', 'security.codeSent', $json$"Nous avons envoyé un code à 6 chiffres à {email}."$json$::jsonb),
  ('fr', 'security.code', $json$"Code reçu par e-mail"$json$::jsonb),
  ('fr', 'security.setPassword', $json$"Définir le mot de passe"$json$::jsonb),
  ('fr', 'security.set', $json$"Mot de passe défini. Vous pouvez désormais vous connecter aussi avec votre e-mail."$json$::jsonb),
  ('fr', 'linked.title', $json$"Comptes liés"$json$::jsonb),
  ('fr', 'linked.description', $json$"Connectez-vous avec n'importe lequel. La dissociation est bloquée tant que c'est votre seul moyen de connexion."$json$::jsonb),
  ('fr', 'linked.on', $json$"Lié"$json$::jsonb),
  ('fr', 'linked.off', $json$"Non lié"$json$::jsonb),
  ('fr', 'linked.link', $json$"Lier"$json$::jsonb),
  ('fr', 'linked.unlink', $json$"Dissocier"$json$::jsonb),
  ('fr', 'linked.unlink.title', $json$"Dissocier {provider}"$json$::jsonb),
  ('fr', 'linked.unlink.description', $json$"Vous ne pourrez plus vous connecter avec {provider}."$json$::jsonb),
  ('ru', 'auth.displayName', $json$"Отображаемое имя"$json$::jsonb),
  ('ru', 'auth.confirmPassword', $json$"Подтвердите пароль"$json$::jsonb),
  ('ru', 'auth.mismatch', $json$"Пароли не совпадают."$json$::jsonb),
  ('ru', 'auth.forgot', $json$"Забыли пароль?"$json$::jsonb),
  ('ru', 'auth.reset.title', $json$"Сброс пароля"$json$::jsonb),
  ('ru', 'auth.reset.description', $json$"Мы отправим на почту ссылку для выбора нового пароля."$json$::jsonb),
  ('ru', 'auth.reset.send', $json$"Отправить ссылку"$json$::jsonb),
  ('ru', 'auth.resetSent', $json$"Если аккаунт с этой почтой существует, ссылка уже в пути."$json$::jsonb),
  ('ru', 'auth.backToSignIn', $json$"Вернуться ко входу"$json$::jsonb),
  ('ru', 'auth.continueWith', $json$"Продолжить через {provider}"$json$::jsonb),
  ('ru', 'auth.or', $json$"или"$json$::jsonb),
  ('ru', 'auth.rule.length', $json$"Не менее {min} символов"$json$::jsonb),
  ('ru', 'auth.rule.lower', $json$"Строчная буква"$json$::jsonb),
  ('ru', 'auth.rule.upper', $json$"Заглавная буква"$json$::jsonb),
  ('ru', 'auth.rule.digit', $json$"Цифра"$json$::jsonb),
  ('ru', 'auth.rule.symbol', $json$"Специальный символ"$json$::jsonb),
  ('ru', 'auth.identityTaken', $json$"Этот аккаунт уже привязан к другому пользователю JayV."$json$::jsonb),
  ('ru', 'auth.weakPassword', $json$"Сервер отклонил пароль: он слишком слабый или встречался в утечке данных."$json$::jsonb),
  ('ru', 'auth.invalidCredentials', $json$"Неверная почта или пароль."$json$::jsonb),
  ('ru', 'auth.wrongPassword', $json$"Текущий пароль неверен."$json$::jsonb),
  ('ru', 'auth.samePassword', $json$"Новый пароль должен отличаться от текущего."$json$::jsonb),
  ('ru', 'auth.badCode', $json$"Код неверен или истёк. Запросите новый."$json$::jsonb),
  ('ru', 'auth.lastIdentity', $json$"Это ваш единственный способ входа. Сначала задайте пароль или привяжите другой аккаунт."$json$::jsonb),
  ('ru', 'auth.linkingDisabled', $json$"Привязка аккаунтов отключена на сервере."$json$::jsonb),
  ('ru', 'auth.emailNotConfirmed', $json$"Подтвердите почту перед входом."$json$::jsonb),
  ('ru', 'auth.newPassword.title', $json$"Выберите новый пароль"$json$::jsonb),
  ('ru', 'auth.newPassword.description', $json$"Вы открыли ссылку для сброса. Выберите пароль, который будете использовать дальше."$json$::jsonb),
  ('ru', 'auth.newPassword.save', $json$"Сохранить пароль"$json$::jsonb),
  ('ru', 'auth.newPassword.saved', $json$"Пароль сохранён."$json$::jsonb),
  ('ru', 'profile.password', $json$"Пароль"$json$::jsonb),
  ('ru', 'profile.unset', $json$"Не указано"$json$::jsonb),
  ('ru', 'profile.save', $json$"Сохранить"$json$::jsonb),
  ('ru', 'profile.skip', $json$"Пропустить пока"$json$::jsonb),
  ('ru', 'profile.saved', $json$"Профиль сохранён."$json$::jsonb),
  ('ru', 'profile.invalid', $json$"В одном из полей значение, которое сервер не принимает. Проверьте и попробуйте снова."$json$::jsonb),
  ('ru', 'profile.setup.title', $json$"Заполните профиль"$json$::jsonb),
  ('ru', 'profile.setup.description', $json$"Обязательно только отображаемое имя. Всё можно изменить позже на странице профиля."$json$::jsonb),
  ('ru', 'profile.data.title', $json$"Личные данные"$json$::jsonb),
  ('ru', 'profile.data.description', $json$"Обязательно только отображаемое имя. Никаких документов, адреса или телефона."$json$::jsonb),
  ('ru', 'profile.field.displayName', $json$"Отображаемое имя"$json$::jsonb),
  ('ru', 'profile.field.displayName.hint', $json$"Как вас видят в JayV."$json$::jsonb),
  ('ru', 'profile.field.fullName', $json$"Полное имя"$json$::jsonb),
  ('ru', 'profile.field.sex', $json$"Пол"$json$::jsonb),
  ('ru', 'profile.field.gender', $json$"Гендер"$json$::jsonb),
  ('ru', 'profile.field.genderCustom', $json$"Ваш гендер"$json$::jsonb),
  ('ru', 'profile.field.pronouns', $json$"Местоимения"$json$::jsonb),
  ('ru', 'profile.field.pronounsCustom', $json$"Ваши местоимения"$json$::jsonb),
  ('ru', 'profile.field.birthDate', $json$"Дата рождения"$json$::jsonb),
  ('ru', 'profile.field.country', $json$"Страна"$json$::jsonb),
  ('ru', 'profile.field.timezone', $json$"Часовой пояс"$json$::jsonb),
  ('ru', 'profile.field.role', $json$"Роль"$json$::jsonb),
  ('ru', 'profile.field.company', $json$"Компания"$json$::jsonb),
  ('ru', 'profile.sex.female', $json$"Женский"$json$::jsonb),
  ('ru', 'profile.sex.male', $json$"Мужской"$json$::jsonb),
  ('ru', 'profile.sex.intersex', $json$"Интерсекс"$json$::jsonb),
  ('ru', 'profile.sex.undisclosed', $json$"Предпочитаю не указывать"$json$::jsonb),
  ('ru', 'profile.gender.woman', $json$"Женщина"$json$::jsonb),
  ('ru', 'profile.gender.man', $json$"Мужчина"$json$::jsonb),
  ('ru', 'profile.gender.non_binary', $json$"Небинарный"$json$::jsonb),
  ('ru', 'profile.gender.other', $json$"Другое"$json$::jsonb),
  ('ru', 'profile.gender.undisclosed', $json$"Предпочитаю не указывать"$json$::jsonb),
  ('ru', 'profile.pronouns.she', $json$"она/её"$json$::jsonb),
  ('ru', 'profile.pronouns.he', $json$"он/его"$json$::jsonb),
  ('ru', 'profile.pronouns.they', $json$"они/их"$json$::jsonb),
  ('ru', 'profile.pronouns.custom', $json$"Свои"$json$::jsonb),
  ('ru', 'profile.pronouns.undisclosed', $json$"Предпочитаю не указывать"$json$::jsonb),
  ('ru', 'profile.role.developer', $json$"Разработка"$json$::jsonb),
  ('ru', 'profile.role.tech_lead', $json$"Техлид"$json$::jsonb),
  ('ru', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('ru', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('ru', 'profile.role.designer', $json$"Дизайн"$json$::jsonb),
  ('ru', 'profile.role.manager', $json$"Менеджмент"$json$::jsonb),
  ('ru', 'profile.role.data', $json$"Данные"$json$::jsonb),
  ('ru', 'profile.role.other', $json$"Другое"$json$::jsonb),
  ('ru', 'security.title', $json$"Безопасность"$json$::jsonb),
  ('ru', 'security.description', $json$"Пароль для входа по почте."$json$::jsonb),
  ('ru', 'security.current', $json$"Текущий пароль"$json$::jsonb),
  ('ru', 'security.new', $json$"Новый пароль"$json$::jsonb),
  ('ru', 'security.confirm', $json$"Подтвердите новый пароль"$json$::jsonb),
  ('ru', 'security.change', $json$"Сменить пароль"$json$::jsonb),
  ('ru', 'security.changed', $json$"Пароль изменён."$json$::jsonb),
  ('ru', 'security.noPassword', $json$"У аккаунта пока нет пароля: вы входите только через привязанный аккаунт. Задайте пароль, чтобы входить и по почте."$json$::jsonb),
  ('ru', 'security.sendCode', $json$"Прислать код на почту"$json$::jsonb),
  ('ru', 'security.codeSent', $json$"Мы отправили 6-значный код на {email}."$json$::jsonb),
  ('ru', 'security.code', $json$"Код из письма"$json$::jsonb),
  ('ru', 'security.setPassword', $json$"Задать пароль"$json$::jsonb),
  ('ru', 'security.set', $json$"Пароль задан. Теперь можно входить и по почте."$json$::jsonb),
  ('ru', 'linked.title', $json$"Привязанные аккаунты"$json$::jsonb),
  ('ru', 'linked.description', $json$"Входите через любой из них. Отвязать нельзя, пока это единственный способ входа."$json$::jsonb),
  ('ru', 'linked.on', $json$"Привязан"$json$::jsonb),
  ('ru', 'linked.off', $json$"Не привязан"$json$::jsonb),
  ('ru', 'linked.link', $json$"Привязать"$json$::jsonb),
  ('ru', 'linked.unlink', $json$"Отвязать"$json$::jsonb),
  ('ru', 'linked.unlink.title', $json$"Отвязать {provider}"$json$::jsonb),
  ('ru', 'linked.unlink.description', $json$"Вы больше не сможете входить через {provider}."$json$::jsonb),
  ('ja', 'auth.displayName', $json$"表示名"$json$::jsonb),
  ('ja', 'auth.confirmPassword', $json$"パスワードの確認"$json$::jsonb),
  ('ja', 'auth.mismatch', $json$"パスワードが一致しません。"$json$::jsonb),
  ('ja', 'auth.forgot', $json$"パスワードをお忘れですか？"$json$::jsonb),
  ('ja', 'auth.reset.title', $json$"パスワードの再設定"$json$::jsonb),
  ('ja', 'auth.reset.description', $json$"新しいパスワードを設定するためのリンクをメールで送ります。"$json$::jsonb),
  ('ja', 'auth.reset.send', $json$"リンクを送信"$json$::jsonb),
  ('ja', 'auth.resetSent', $json$"このメールのアカウントが存在する場合、再設定リンクを送信しました。"$json$::jsonb),
  ('ja', 'auth.backToSignIn', $json$"サインインに戻る"$json$::jsonb),
  ('ja', 'auth.continueWith', $json$"{provider} で続行"$json$::jsonb),
  ('ja', 'auth.or', $json$"または"$json$::jsonb),
  ('ja', 'auth.rule.length', $json$"{min} 文字以上"$json$::jsonb),
  ('ja', 'auth.rule.lower', $json$"小文字"$json$::jsonb),
  ('ja', 'auth.rule.upper', $json$"大文字"$json$::jsonb),
  ('ja', 'auth.rule.digit', $json$"数字"$json$::jsonb),
  ('ja', 'auth.rule.symbol', $json$"記号"$json$::jsonb),
  ('ja', 'auth.identityTaken', $json$"このアカウントは既に別の JayV ユーザーに連携されています。"$json$::jsonb),
  ('ja', 'auth.weakPassword', $json$"サーバーがこのパスワードを拒否しました。弱すぎるか、データ漏えいで確認されています。"$json$::jsonb),
  ('ja', 'auth.invalidCredentials', $json$"メールアドレスまたはパスワードが違います。"$json$::jsonb),
  ('ja', 'auth.wrongPassword', $json$"現在のパスワードが違います。"$json$::jsonb),
  ('ja', 'auth.samePassword', $json$"新しいパスワードは現在のものと異なる必要があります。"$json$::jsonb),
  ('ja', 'auth.badCode', $json$"コードが無効か期限切れです。新しいコードを請求してください。"$json$::jsonb),
  ('ja', 'auth.lastIdentity', $json$"これが唯一のサインイン方法です。先にパスワードを設定するか、別のアカウントを連携してください。"$json$::jsonb),
  ('ja', 'auth.linkingDisabled', $json$"サーバーでアカウント連携が無効になっています。"$json$::jsonb),
  ('ja', 'auth.emailNotConfirmed', $json$"サインインする前にメールアドレスを確認してください。"$json$::jsonb),
  ('ja', 'auth.newPassword.title', $json$"新しいパスワードを設定"$json$::jsonb),
  ('ja', 'auth.newPassword.description', $json$"再設定リンクを開きました。今後使うパスワードを決めてください。"$json$::jsonb),
  ('ja', 'auth.newPassword.save', $json$"パスワードを保存"$json$::jsonb),
  ('ja', 'auth.newPassword.saved', $json$"パスワードを保存しました。"$json$::jsonb),
  ('ja', 'profile.password', $json$"パスワード"$json$::jsonb),
  ('ja', 'profile.unset', $json$"未設定"$json$::jsonb),
  ('ja', 'profile.save', $json$"保存"$json$::jsonb),
  ('ja', 'profile.skip', $json$"今はスキップ"$json$::jsonb),
  ('ja', 'profile.saved', $json$"プロフィールを保存しました。"$json$::jsonb),
  ('ja', 'profile.invalid', $json$"サーバーが受け付けない値の項目があります。確認してもう一度お試しください。"$json$::jsonb),
  ('ja', 'profile.setup.title', $json$"プロフィールを完成させましょう"$json$::jsonb),
  ('ja', 'profile.setup.description', $json$"必須なのは表示名だけです。あとからプロフィールページですべて変更できます。"$json$::jsonb),
  ('ja', 'profile.data.title', $json$"個人情報"$json$::jsonb),
  ('ja', 'profile.data.description', $json$"必須なのは表示名だけです。身分証、住所、電話番号は扱いません。"$json$::jsonb),
  ('ja', 'profile.field.displayName', $json$"表示名"$json$::jsonb),
  ('ja', 'profile.field.displayName.hint', $json$"JayV での表示名です。"$json$::jsonb),
  ('ja', 'profile.field.fullName', $json$"氏名"$json$::jsonb),
  ('ja', 'profile.field.sex', $json$"性別"$json$::jsonb),
  ('ja', 'profile.field.gender', $json$"ジェンダー"$json$::jsonb),
  ('ja', 'profile.field.genderCustom', $json$"あなたのジェンダー"$json$::jsonb),
  ('ja', 'profile.field.pronouns', $json$"代名詞"$json$::jsonb),
  ('ja', 'profile.field.pronounsCustom', $json$"あなたの代名詞"$json$::jsonb),
  ('ja', 'profile.field.birthDate', $json$"生年月日"$json$::jsonb),
  ('ja', 'profile.field.country', $json$"国・地域"$json$::jsonb),
  ('ja', 'profile.field.timezone', $json$"タイムゾーン"$json$::jsonb),
  ('ja', 'profile.field.role', $json$"役割"$json$::jsonb),
  ('ja', 'profile.field.company', $json$"会社"$json$::jsonb),
  ('ja', 'profile.sex.female', $json$"女性"$json$::jsonb),
  ('ja', 'profile.sex.male', $json$"男性"$json$::jsonb),
  ('ja', 'profile.sex.intersex', $json$"インターセックス"$json$::jsonb),
  ('ja', 'profile.sex.undisclosed', $json$"回答しない"$json$::jsonb),
  ('ja', 'profile.gender.woman', $json$"女性"$json$::jsonb),
  ('ja', 'profile.gender.man', $json$"男性"$json$::jsonb),
  ('ja', 'profile.gender.non_binary', $json$"ノンバイナリー"$json$::jsonb),
  ('ja', 'profile.gender.other', $json$"その他"$json$::jsonb),
  ('ja', 'profile.gender.undisclosed', $json$"回答しない"$json$::jsonb),
  ('ja', 'profile.pronouns.she', $json$"she/her"$json$::jsonb),
  ('ja', 'profile.pronouns.he', $json$"he/him"$json$::jsonb),
  ('ja', 'profile.pronouns.they', $json$"they/them"$json$::jsonb),
  ('ja', 'profile.pronouns.custom', $json$"カスタム"$json$::jsonb),
  ('ja', 'profile.pronouns.undisclosed', $json$"回答しない"$json$::jsonb),
  ('ja', 'profile.role.developer', $json$"開発者"$json$::jsonb),
  ('ja', 'profile.role.tech_lead', $json$"テックリード"$json$::jsonb),
  ('ja', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('ja', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('ja', 'profile.role.designer', $json$"デザイナー"$json$::jsonb),
  ('ja', 'profile.role.manager', $json$"マネージャー"$json$::jsonb),
  ('ja', 'profile.role.data', $json$"データ"$json$::jsonb),
  ('ja', 'profile.role.other', $json$"その他"$json$::jsonb),
  ('ja', 'security.title', $json$"セキュリティ"$json$::jsonb),
  ('ja', 'security.description', $json$"メールアドレスでサインインするためのパスワードです。"$json$::jsonb),
  ('ja', 'security.current', $json$"現在のパスワード"$json$::jsonb),
  ('ja', 'security.new', $json$"新しいパスワード"$json$::jsonb),
  ('ja', 'security.confirm', $json$"新しいパスワードの確認"$json$::jsonb),
  ('ja', 'security.change', $json$"パスワードを変更"$json$::jsonb),
  ('ja', 'security.changed', $json$"パスワードを変更しました。"$json$::jsonb),
  ('ja', 'security.noPassword', $json$"このアカウントにはまだパスワードがなく、連携アカウントからのみサインインできます。メールでもサインインするにはパスワードを設定してください。"$json$::jsonb),
  ('ja', 'security.sendCode', $json$"コードをメールで送信"$json$::jsonb),
  ('ja', 'security.codeSent', $json$"{email} に 6 桁のコードを送信しました。"$json$::jsonb),
  ('ja', 'security.code', $json$"メールのコード"$json$::jsonb),
  ('ja', 'security.setPassword', $json$"パスワードを設定"$json$::jsonb),
  ('ja', 'security.set', $json$"パスワードを設定しました。メールでもサインインできます。"$json$::jsonb),
  ('ja', 'linked.title', $json$"連携アカウント"$json$::jsonb),
  ('ja', 'linked.description', $json$"どれでもサインインできます。唯一のサインイン方法の間は連携を解除できません。"$json$::jsonb),
  ('ja', 'linked.on', $json$"連携済み"$json$::jsonb),
  ('ja', 'linked.off', $json$"未連携"$json$::jsonb),
  ('ja', 'linked.link', $json$"連携する"$json$::jsonb),
  ('ja', 'linked.unlink', $json$"連携を解除"$json$::jsonb),
  ('ja', 'linked.unlink.title', $json$"{provider} の連携を解除"$json$::jsonb),
  ('ja', 'linked.unlink.description', $json$"{provider} でサインインできなくなります。"$json$::jsonb),
  ('de', 'auth.displayName', $json$"Anzeigename"$json$::jsonb),
  ('de', 'auth.confirmPassword', $json$"Passwort bestätigen"$json$::jsonb),
  ('de', 'auth.mismatch', $json$"Die Passwörter stimmen nicht überein."$json$::jsonb),
  ('de', 'auth.forgot', $json$"Passwort vergessen?"$json$::jsonb),
  ('de', 'auth.reset.title', $json$"Passwort zurücksetzen"$json$::jsonb),
  ('de', 'auth.reset.description', $json$"Wir senden dir per E-Mail einen Link, um ein neues Passwort zu wählen."$json$::jsonb),
  ('de', 'auth.reset.send', $json$"Link senden"$json$::jsonb),
  ('de', 'auth.resetSent', $json$"Falls ein Konto mit dieser E-Mail existiert, ist der Link unterwegs."$json$::jsonb),
  ('de', 'auth.backToSignIn', $json$"Zurück zur Anmeldung"$json$::jsonb),
  ('de', 'auth.continueWith', $json$"Weiter mit {provider}"$json$::jsonb),
  ('de', 'auth.or', $json$"oder"$json$::jsonb),
  ('de', 'auth.rule.length', $json$"Mindestens {min} Zeichen"$json$::jsonb),
  ('de', 'auth.rule.lower', $json$"Ein Kleinbuchstabe"$json$::jsonb),
  ('de', 'auth.rule.upper', $json$"Ein Großbuchstabe"$json$::jsonb),
  ('de', 'auth.rule.digit', $json$"Eine Ziffer"$json$::jsonb),
  ('de', 'auth.rule.symbol', $json$"Ein Sonderzeichen"$json$::jsonb),
  ('de', 'auth.identityTaken', $json$"Dieses Konto ist bereits mit einem anderen JayV-Nutzer verknüpft."$json$::jsonb),
  ('de', 'auth.weakPassword', $json$"Der Server hat dieses Passwort abgelehnt: Es ist zu schwach oder tauchte in einem Datenleck auf."$json$::jsonb),
  ('de', 'auth.invalidCredentials', $json$"E-Mail oder Passwort falsch."$json$::jsonb),
  ('de', 'auth.wrongPassword', $json$"Das aktuelle Passwort ist falsch."$json$::jsonb),
  ('de', 'auth.samePassword', $json$"Das neue Passwort muss sich vom aktuellen unterscheiden."$json$::jsonb),
  ('de', 'auth.badCode', $json$"Der Code ist ungültig oder abgelaufen. Fordere einen neuen an."$json$::jsonb),
  ('de', 'auth.lastIdentity', $json$"Das ist deine einzige Anmeldemöglichkeit. Lege zuerst ein Passwort fest oder verknüpfe ein anderes Konto."$json$::jsonb),
  ('de', 'auth.linkingDisabled', $json$"Das Verknüpfen von Konten ist auf dem Server deaktiviert."$json$::jsonb),
  ('de', 'auth.emailNotConfirmed', $json$"Bestätige deine E-Mail, bevor du dich anmeldest."$json$::jsonb),
  ('de', 'auth.newPassword.title', $json$"Wähle ein neues Passwort"$json$::jsonb),
  ('de', 'auth.newPassword.description', $json$"Du hast den Link geöffnet. Wähle das Passwort, das du ab jetzt verwendest."$json$::jsonb),
  ('de', 'auth.newPassword.save', $json$"Passwort speichern"$json$::jsonb),
  ('de', 'auth.newPassword.saved', $json$"Passwort gespeichert."$json$::jsonb),
  ('de', 'profile.password', $json$"Passwort"$json$::jsonb),
  ('de', 'profile.unset', $json$"Keine Angabe"$json$::jsonb),
  ('de', 'profile.save', $json$"Speichern"$json$::jsonb),
  ('de', 'profile.skip', $json$"Vorerst überspringen"$json$::jsonb),
  ('de', 'profile.saved', $json$"Profil gespeichert."$json$::jsonb),
  ('de', 'profile.invalid', $json$"Ein Feld hat einen Wert, den der Server nicht akzeptiert. Prüfe ihn und versuche es erneut."$json$::jsonb),
  ('de', 'profile.setup.title', $json$"Vervollständige dein Profil"$json$::jsonb),
  ('de', 'profile.setup.description', $json$"Nur der Anzeigename ist Pflicht. Alles lässt sich später auf der Profilseite ändern."$json$::jsonb),
  ('de', 'profile.data.title', $json$"Persönliche Daten"$json$::jsonb),
  ('de', 'profile.data.description', $json$"Nur der Anzeigename ist Pflicht. Keine Ausweise, keine Adresse, keine Telefonnummer."$json$::jsonb),
  ('de', 'profile.field.displayName', $json$"Anzeigename"$json$::jsonb),
  ('de', 'profile.field.displayName.hint', $json$"So erscheinst du in JayV."$json$::jsonb),
  ('de', 'profile.field.fullName', $json$"Vollständiger Name"$json$::jsonb),
  ('de', 'profile.field.sex', $json$"Geschlecht (biologisch)"$json$::jsonb),
  ('de', 'profile.field.gender', $json$"Geschlechtsidentität"$json$::jsonb),
  ('de', 'profile.field.genderCustom', $json$"Deine Geschlechtsidentität"$json$::jsonb),
  ('de', 'profile.field.pronouns', $json$"Pronomen"$json$::jsonb),
  ('de', 'profile.field.pronounsCustom', $json$"Deine Pronomen"$json$::jsonb),
  ('de', 'profile.field.birthDate', $json$"Geburtsdatum"$json$::jsonb),
  ('de', 'profile.field.country', $json$"Land"$json$::jsonb),
  ('de', 'profile.field.timezone', $json$"Zeitzone"$json$::jsonb),
  ('de', 'profile.field.role', $json$"Rolle"$json$::jsonb),
  ('de', 'profile.field.company', $json$"Unternehmen"$json$::jsonb),
  ('de', 'profile.sex.female', $json$"Weiblich"$json$::jsonb),
  ('de', 'profile.sex.male', $json$"Männlich"$json$::jsonb),
  ('de', 'profile.sex.intersex', $json$"Intergeschlechtlich"$json$::jsonb),
  ('de', 'profile.sex.undisclosed', $json$"Keine Angabe"$json$::jsonb),
  ('de', 'profile.gender.woman', $json$"Frau"$json$::jsonb),
  ('de', 'profile.gender.man', $json$"Mann"$json$::jsonb),
  ('de', 'profile.gender.non_binary', $json$"Nichtbinär"$json$::jsonb),
  ('de', 'profile.gender.other', $json$"Anderes"$json$::jsonb),
  ('de', 'profile.gender.undisclosed', $json$"Keine Angabe"$json$::jsonb),
  ('de', 'profile.pronouns.she', $json$"sie/ihr"$json$::jsonb),
  ('de', 'profile.pronouns.he', $json$"er/ihm"$json$::jsonb),
  ('de', 'profile.pronouns.they', $json$"they/them"$json$::jsonb),
  ('de', 'profile.pronouns.custom', $json$"Eigene"$json$::jsonb),
  ('de', 'profile.pronouns.undisclosed', $json$"Keine Angabe"$json$::jsonb),
  ('de', 'profile.role.developer', $json$"Entwicklung"$json$::jsonb),
  ('de', 'profile.role.tech_lead', $json$"Tech Lead"$json$::jsonb),
  ('de', 'profile.role.qa', $json$"QA"$json$::jsonb),
  ('de', 'profile.role.devops', $json$"DevOps"$json$::jsonb),
  ('de', 'profile.role.designer', $json$"Design"$json$::jsonb),
  ('de', 'profile.role.manager', $json$"Management"$json$::jsonb),
  ('de', 'profile.role.data', $json$"Daten"$json$::jsonb),
  ('de', 'profile.role.other', $json$"Andere"$json$::jsonb),
  ('de', 'security.title', $json$"Sicherheit"$json$::jsonb),
  ('de', 'security.description', $json$"Das Passwort für die Anmeldung mit deiner E-Mail."$json$::jsonb),
  ('de', 'security.current', $json$"Aktuelles Passwort"$json$::jsonb),
  ('de', 'security.new', $json$"Neues Passwort"$json$::jsonb),
  ('de', 'security.confirm', $json$"Neues Passwort bestätigen"$json$::jsonb),
  ('de', 'security.change', $json$"Passwort ändern"$json$::jsonb),
  ('de', 'security.changed', $json$"Passwort geändert."$json$::jsonb),
  ('de', 'security.noPassword', $json$"Dein Konto hat noch kein Passwort: Du meldest dich nur über ein verknüpftes Konto an. Lege eins fest, um dich auch mit deiner E-Mail anzumelden."$json$::jsonb),
  ('de', 'security.sendCode', $json$"Code per E-Mail senden"$json$::jsonb),
  ('de', 'security.codeSent', $json$"Wir haben einen 6-stelligen Code an {email} gesendet."$json$::jsonb),
  ('de', 'security.code', $json$"Code aus der E-Mail"$json$::jsonb),
  ('de', 'security.setPassword', $json$"Passwort festlegen"$json$::jsonb),
  ('de', 'security.set', $json$"Passwort festgelegt. Du kannst dich jetzt auch mit deiner E-Mail anmelden."$json$::jsonb),
  ('de', 'linked.title', $json$"Verknüpfte Konten"$json$::jsonb),
  ('de', 'linked.description', $json$"Melde dich mit jedem davon an. Trennen ist gesperrt, solange es dein einziger Zugang ist."$json$::jsonb),
  ('de', 'linked.on', $json$"Verknüpft"$json$::jsonb),
  ('de', 'linked.off', $json$"Nicht verknüpft"$json$::jsonb),
  ('de', 'linked.link', $json$"Verknüpfen"$json$::jsonb),
  ('de', 'linked.unlink', $json$"Trennen"$json$::jsonb),
  ('de', 'linked.unlink.title', $json$"{provider} trennen"$json$::jsonb),
  ('de', 'linked.unlink.description', $json$"Du kannst dich dann nicht mehr mit {provider} anmelden."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
