-- v0.74.0: tutoriais de cada funcionalidade — textos do tutorial, Configurações › App, paleta, Novidades e documentação, nos dez idiomas.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'tutorial.tour.projects', $json$"Primeiros passos"$json$::jsonb),
  ('en', 'tutorial.tour.projects', $json$"Getting started"$json$::jsonb),
  ('es', 'tutorial.tour.projects', $json$"Primeros pasos"$json$::jsonb),
  ('zh-CN', 'tutorial.tour.projects', $json$"快速上手"$json$::jsonb),
  ('hi', 'tutorial.tour.projects', $json$"शुरुआत"$json$::jsonb),
  ('ar', 'tutorial.tour.projects', $json$"البدء"$json$::jsonb),
  ('fr', 'tutorial.tour.projects', $json$"Premiers pas"$json$::jsonb),
  ('ru', 'tutorial.tour.projects', $json$"Первые шаги"$json$::jsonb),
  ('ja', 'tutorial.tour.projects', $json$"はじめに"$json$::jsonb),
  ('de', 'tutorial.tour.projects', $json$"Erste Schritte"$json$::jsonb),
  ('pt-BR', 'tutorial.tour.chat', $json$"O chat"$json$::jsonb),
  ('en', 'tutorial.tour.chat', $json$"The chat"$json$::jsonb),
  ('es', 'tutorial.tour.chat', $json$"El chat"$json$::jsonb),
  ('zh-CN', 'tutorial.tour.chat', $json$"聊天"$json$::jsonb),
  ('hi', 'tutorial.tour.chat', $json$"चैट"$json$::jsonb),
  ('ar', 'tutorial.tour.chat', $json$"المحادثة"$json$::jsonb),
  ('fr', 'tutorial.tour.chat', $json$"Le chat"$json$::jsonb),
  ('ru', 'tutorial.tour.chat', $json$"Чат"$json$::jsonb),
  ('ja', 'tutorial.tour.chat', $json$"チャット"$json$::jsonb),
  ('de', 'tutorial.tour.chat', $json$"Der Chat"$json$::jsonb),
  ('pt-BR', 'tutorial.tour.gate', $json$"A portaria"$json$::jsonb),
  ('en', 'tutorial.tour.gate', $json$"The gate"$json$::jsonb),
  ('es', 'tutorial.tour.gate', $json$"La portería"$json$::jsonb),
  ('zh-CN', 'tutorial.tour.gate', $json$"门禁"$json$::jsonb),
  ('hi', 'tutorial.tour.gate', $json$"गेट"$json$::jsonb),
  ('ar', 'tutorial.tour.gate', $json$"البوابة"$json$::jsonb),
  ('fr', 'tutorial.tour.gate', $json$"La porte"$json$::jsonb),
  ('ru', 'tutorial.tour.gate', $json$"Шлюз"$json$::jsonb),
  ('ja', 'tutorial.tour.gate', $json$"ゲート"$json$::jsonb),
  ('de', 'tutorial.tour.gate', $json$"Das Gate"$json$::jsonb),
  ('pt-BR', 'tutorial.tour.settings', $json$"Configurações e agentes"$json$::jsonb),
  ('en', 'tutorial.tour.settings', $json$"Settings and agents"$json$::jsonb),
  ('es', 'tutorial.tour.settings', $json$"Ajustes y agentes"$json$::jsonb),
  ('zh-CN', 'tutorial.tour.settings', $json$"设置与智能体"$json$::jsonb),
  ('hi', 'tutorial.tour.settings', $json$"सेटिंग और एजेंट"$json$::jsonb),
  ('ar', 'tutorial.tour.settings', $json$"الإعدادات والوكلاء"$json$::jsonb),
  ('fr', 'tutorial.tour.settings', $json$"Réglages et agents"$json$::jsonb),
  ('ru', 'tutorial.tour.settings', $json$"Настройки и агенты"$json$::jsonb),
  ('ja', 'tutorial.tour.settings', $json$"設定とエージェント"$json$::jsonb),
  ('de', 'tutorial.tour.settings', $json$"Einstellungen und Agenten"$json$::jsonb),
  ('pt-BR', 'tutorial.tour.organizations', $json$"Organizações"$json$::jsonb),
  ('en', 'tutorial.tour.organizations', $json$"Organizations"$json$::jsonb),
  ('es', 'tutorial.tour.organizations', $json$"Organizaciones"$json$::jsonb),
  ('zh-CN', 'tutorial.tour.organizations', $json$"组织"$json$::jsonb),
  ('hi', 'tutorial.tour.organizations', $json$"संगठन"$json$::jsonb),
  ('ar', 'tutorial.tour.organizations', $json$"المؤسسات"$json$::jsonb),
  ('fr', 'tutorial.tour.organizations', $json$"Organisations"$json$::jsonb),
  ('ru', 'tutorial.tour.organizations', $json$"Организации"$json$::jsonb),
  ('ja', 'tutorial.tour.organizations', $json$"組織"$json$::jsonb),
  ('de', 'tutorial.tour.organizations', $json$"Organisationen"$json$::jsonb),
  ('pt-BR', 'tutorial.tour.profile', $json$"Sua conta"$json$::jsonb),
  ('en', 'tutorial.tour.profile', $json$"Your account"$json$::jsonb),
  ('es', 'tutorial.tour.profile', $json$"Tu cuenta"$json$::jsonb),
  ('zh-CN', 'tutorial.tour.profile', $json$"你的账户"$json$::jsonb),
  ('hi', 'tutorial.tour.profile', $json$"आपका खाता"$json$::jsonb),
  ('ar', 'tutorial.tour.profile', $json$"حسابك"$json$::jsonb),
  ('fr', 'tutorial.tour.profile', $json$"Votre compte"$json$::jsonb),
  ('ru', 'tutorial.tour.profile', $json$"Ваш аккаунт"$json$::jsonb),
  ('ja', 'tutorial.tour.profile', $json$"アカウント"$json$::jsonb),
  ('de', 'tutorial.tour.profile', $json$"Dein Konto"$json$::jsonb),
  ('pt-BR', 'tutorial.step', $json$"{current} de {total}"$json$::jsonb),
  ('en', 'tutorial.step', $json$"{current} of {total}"$json$::jsonb),
  ('es', 'tutorial.step', $json$"{current} de {total}"$json$::jsonb),
  ('zh-CN', 'tutorial.step', $json$"第 {current} 步，共 {total} 步"$json$::jsonb),
  ('hi', 'tutorial.step', $json$"{total} में से {current}"$json$::jsonb),
  ('ar', 'tutorial.step', $json$"{current} من {total}"$json$::jsonb),
  ('fr', 'tutorial.step', $json$"{current} sur {total}"$json$::jsonb),
  ('ru', 'tutorial.step', $json$"{current} из {total}"$json$::jsonb),
  ('ja', 'tutorial.step', $json$"{current} / {total}"$json$::jsonb),
  ('de', 'tutorial.step', $json$"{current} von {total}"$json$::jsonb),
  ('pt-BR', 'tutorial.next', $json$"Próximo"$json$::jsonb),
  ('en', 'tutorial.next', $json$"Next"$json$::jsonb),
  ('es', 'tutorial.next', $json$"Siguiente"$json$::jsonb),
  ('zh-CN', 'tutorial.next', $json$"下一步"$json$::jsonb),
  ('hi', 'tutorial.next', $json$"आगे"$json$::jsonb),
  ('ar', 'tutorial.next', $json$"التالي"$json$::jsonb),
  ('fr', 'tutorial.next', $json$"Suivant"$json$::jsonb),
  ('ru', 'tutorial.next', $json$"Далее"$json$::jsonb),
  ('ja', 'tutorial.next', $json$"次へ"$json$::jsonb),
  ('de', 'tutorial.next', $json$"Weiter"$json$::jsonb),
  ('pt-BR', 'tutorial.back', $json$"Voltar"$json$::jsonb),
  ('en', 'tutorial.back', $json$"Back"$json$::jsonb),
  ('es', 'tutorial.back', $json$"Atrás"$json$::jsonb),
  ('zh-CN', 'tutorial.back', $json$"上一步"$json$::jsonb),
  ('hi', 'tutorial.back', $json$"पीछे"$json$::jsonb),
  ('ar', 'tutorial.back', $json$"السابق"$json$::jsonb),
  ('fr', 'tutorial.back', $json$"Précédent"$json$::jsonb),
  ('ru', 'tutorial.back', $json$"Назад"$json$::jsonb),
  ('ja', 'tutorial.back', $json$"戻る"$json$::jsonb),
  ('de', 'tutorial.back', $json$"Zurück"$json$::jsonb),
  ('pt-BR', 'tutorial.done', $json$"Concluir"$json$::jsonb),
  ('en', 'tutorial.done', $json$"Done"$json$::jsonb),
  ('es', 'tutorial.done', $json$"Terminar"$json$::jsonb),
  ('zh-CN', 'tutorial.done', $json$"完成"$json$::jsonb),
  ('hi', 'tutorial.done', $json$"पूरा करें"$json$::jsonb),
  ('ar', 'tutorial.done', $json$"إنهاء"$json$::jsonb),
  ('fr', 'tutorial.done', $json$"Terminer"$json$::jsonb),
  ('ru', 'tutorial.done', $json$"Готово"$json$::jsonb),
  ('ja', 'tutorial.done', $json$"完了"$json$::jsonb),
  ('de', 'tutorial.done', $json$"Fertig"$json$::jsonb),
  ('pt-BR', 'tutorial.skip', $json$"Fechar tutorial"$json$::jsonb),
  ('en', 'tutorial.skip', $json$"Close tutorial"$json$::jsonb),
  ('es', 'tutorial.skip', $json$"Cerrar tutorial"$json$::jsonb),
  ('zh-CN', 'tutorial.skip', $json$"关闭教程"$json$::jsonb),
  ('hi', 'tutorial.skip', $json$"ट्यूटोरियल बंद करें"$json$::jsonb),
  ('ar', 'tutorial.skip', $json$"إغلاق الدليل"$json$::jsonb),
  ('fr', 'tutorial.skip', $json$"Fermer le tutoriel"$json$::jsonb),
  ('ru', 'tutorial.skip', $json$"Закрыть обучение"$json$::jsonb),
  ('ja', 'tutorial.skip', $json$"チュートリアルを閉じる"$json$::jsonb),
  ('de', 'tutorial.skip', $json$"Tutorial schließen"$json$::jsonb),
  ('pt-BR', 'tutorial.skipAll', $json$"Não mostrar mais"$json$::jsonb),
  ('en', 'tutorial.skipAll', $json$"Don’t show again"$json$::jsonb),
  ('es', 'tutorial.skipAll', $json$"No mostrar más"$json$::jsonb),
  ('zh-CN', 'tutorial.skipAll', $json$"不再显示"$json$::jsonb),
  ('hi', 'tutorial.skipAll', $json$"फिर न दिखाएँ"$json$::jsonb),
  ('ar', 'tutorial.skipAll', $json$"عدم العرض مجددًا"$json$::jsonb),
  ('fr', 'tutorial.skipAll', $json$"Ne plus afficher"$json$::jsonb),
  ('ru', 'tutorial.skipAll', $json$"Больше не показывать"$json$::jsonb),
  ('ja', 'tutorial.skipAll', $json$"今後表示しない"$json$::jsonb),
  ('de', 'tutorial.skipAll', $json$"Nicht mehr anzeigen"$json$::jsonb),
  ('pt-BR', 'tutorial.help', $json$"Tutorial"$json$::jsonb),
  ('en', 'tutorial.help', $json$"Tutorial"$json$::jsonb),
  ('es', 'tutorial.help', $json$"Tutorial"$json$::jsonb),
  ('zh-CN', 'tutorial.help', $json$"教程"$json$::jsonb),
  ('hi', 'tutorial.help', $json$"ट्यूटोरियल"$json$::jsonb),
  ('ar', 'tutorial.help', $json$"دليل الاستخدام"$json$::jsonb),
  ('fr', 'tutorial.help', $json$"Tutoriel"$json$::jsonb),
  ('ru', 'tutorial.help', $json$"Обучение"$json$::jsonb),
  ('ja', 'tutorial.help', $json$"チュートリアル"$json$::jsonb),
  ('de', 'tutorial.help', $json$"Tutorial"$json$::jsonb),
  ('pt-BR', 'tutorial.here', $json$"Tutorial desta tela"$json$::jsonb),
  ('en', 'tutorial.here', $json$"Tutorial for this screen"$json$::jsonb),
  ('es', 'tutorial.here', $json$"Tutorial de esta pantalla"$json$::jsonb),
  ('zh-CN', 'tutorial.here', $json$"本页教程"$json$::jsonb),
  ('hi', 'tutorial.here', $json$"इस स्क्रीन का ट्यूटोरियल"$json$::jsonb),
  ('ar', 'tutorial.here', $json$"دليل هذه الشاشة"$json$::jsonb),
  ('fr', 'tutorial.here', $json$"Tutoriel de cet écran"$json$::jsonb),
  ('ru', 'tutorial.here', $json$"Обучение для этого экрана"$json$::jsonb),
  ('ja', 'tutorial.here', $json$"この画面のチュートリアル"$json$::jsonb),
  ('de', 'tutorial.here', $json$"Tutorial für diesen Bildschirm"$json$::jsonb),
  ('pt-BR', 'tutorial.palette', $json$"Tutorial: {name}"$json$::jsonb),
  ('en', 'tutorial.palette', $json$"Tutorial: {name}"$json$::jsonb),
  ('es', 'tutorial.palette', $json$"Tutorial: {name}"$json$::jsonb),
  ('zh-CN', 'tutorial.palette', $json$"教程：{name}"$json$::jsonb),
  ('hi', 'tutorial.palette', $json$"ट्यूटोरियल: {name}"$json$::jsonb),
  ('ar', 'tutorial.palette', $json$"دليل: {name}"$json$::jsonb),
  ('fr', 'tutorial.palette', $json$"Tutoriel : {name}"$json$::jsonb),
  ('ru', 'tutorial.palette', $json$"Обучение: {name}"$json$::jsonb),
  ('ja', 'tutorial.palette', $json$"チュートリアル: {name}"$json$::jsonb),
  ('de', 'tutorial.palette', $json$"Tutorial: {name}"$json$::jsonb),
  ('pt-BR', 'tutorial.section.title', $json$"Tutoriais"$json$::jsonb),
  ('en', 'tutorial.section.title', $json$"Tutorials"$json$::jsonb),
  ('es', 'tutorial.section.title', $json$"Tutoriales"$json$::jsonb),
  ('zh-CN', 'tutorial.section.title', $json$"教程"$json$::jsonb),
  ('hi', 'tutorial.section.title', $json$"ट्यूटोरियल"$json$::jsonb),
  ('ar', 'tutorial.section.title', $json$"الأدلة التعليمية"$json$::jsonb),
  ('fr', 'tutorial.section.title', $json$"Tutoriels"$json$::jsonb),
  ('ru', 'tutorial.section.title', $json$"Обучение"$json$::jsonb),
  ('ja', 'tutorial.section.title', $json$"チュートリアル"$json$::jsonb),
  ('de', 'tutorial.section.title', $json$"Tutorials"$json$::jsonb),
  ('pt-BR', 'tutorial.section.description', $json$"Passeios guiados e curtos por cada tela e funcionalidade. Cada um abre sozinho na primeira vez que você entra na tela."$json$::jsonb),
  ('en', 'tutorial.section.description', $json$"Short guided tours of each screen and feature. Each one opens by itself the first time you visit its screen."$json$::jsonb),
  ('es', 'tutorial.section.description', $json$"Recorridos guiados y breves por cada pantalla y función. Cada uno se abre solo la primera vez que entras en su pantalla."$json$::jsonb),
  ('zh-CN', 'tutorial.section.description', $json$"对每个界面和功能的简短引导。每个教程会在你第一次进入对应界面时自动打开。"$json$::jsonb),
  ('hi', 'tutorial.section.description', $json$"हर स्क्रीन और सुविधा के छोटे गाइडेड टूर। हर टूर स्क्रीन पर पहली बार जाने पर अपने आप खुलता है।"$json$::jsonb),
  ('ar', 'tutorial.section.description', $json$"جولات إرشادية قصيرة لكل شاشة وميزة. تُفتح كل جولة تلقائيًا أول مرة تزور فيها شاشتها."$json$::jsonb),
  ('fr', 'tutorial.section.description', $json$"De courtes visites guidées de chaque écran et fonctionnalité. Chacune s’ouvre toute seule la première fois que vous visitez son écran."$json$::jsonb),
  ('ru', 'tutorial.section.description', $json$"Короткие обучающие туры по каждому экрану и функции. Каждый открывается сам при первом посещении своего экрана."$json$::jsonb),
  ('ja', 'tutorial.section.description', $json$"各画面と機能の短いガイドツアーです。それぞれ、その画面を初めて開いたときに自動で表示されます。"$json$::jsonb),
  ('de', 'tutorial.section.description', $json$"Kurze geführte Touren durch jeden Bildschirm und jede Funktion. Jede öffnet sich beim ersten Besuch des jeweiligen Bildschirms von selbst."$json$::jsonb),
  ('pt-BR', 'tutorial.auto', $json$"Mostrar tutoriais na primeira visita de cada tela"$json$::jsonb),
  ('en', 'tutorial.auto', $json$"Show tutorials on the first visit to each screen"$json$::jsonb),
  ('es', 'tutorial.auto', $json$"Mostrar tutoriales en la primera visita a cada pantalla"$json$::jsonb),
  ('zh-CN', 'tutorial.auto', $json$"首次访问每个界面时显示教程"$json$::jsonb),
  ('hi', 'tutorial.auto', $json$"हर स्क्रीन पर पहली बार जाने पर ट्यूटोरियल दिखाएँ"$json$::jsonb),
  ('ar', 'tutorial.auto', $json$"عرض الأدلة عند أول زيارة لكل شاشة"$json$::jsonb),
  ('fr', 'tutorial.auto', $json$"Afficher les tutoriels à la première visite de chaque écran"$json$::jsonb),
  ('ru', 'tutorial.auto', $json$"Показывать обучение при первом посещении каждого экрана"$json$::jsonb),
  ('ja', 'tutorial.auto', $json$"各画面を初めて開いたときにチュートリアルを表示"$json$::jsonb),
  ('de', 'tutorial.auto', $json$"Tutorials beim ersten Besuch jedes Bildschirms anzeigen"$json$::jsonb),
  ('pt-BR', 'tutorial.auto.hint', $json$"Desligado, os tutoriais só abrem quando você pedir (botão de ajuda, Ctrl+K ou aqui)."$json$::jsonb),
  ('en', 'tutorial.auto.hint', $json$"Off: tutorials only open when you ask (Help button, Ctrl+K or here)."$json$::jsonb),
  ('es', 'tutorial.auto.hint', $json$"Desactivado, los tutoriales solo se abren cuando los pides (botón de ayuda, Ctrl+K o aquí)."$json$::jsonb),
  ('zh-CN', 'tutorial.auto.hint', $json$"关闭后，教程仅在你需要时打开（帮助按钮、Ctrl+K 或此处）。"$json$::jsonb),
  ('hi', 'tutorial.auto.hint', $json$"बंद होने पर ट्यूटोरियल केवल आपके कहने पर खुलते हैं (सहायता बटन, Ctrl+K या यहाँ)।"$json$::jsonb),
  ('ar', 'tutorial.auto.hint', $json$"عند الإيقاف لا تُفتح الأدلة إلا عند طلبك (زر المساعدة أو Ctrl+K أو هنا)."$json$::jsonb),
  ('fr', 'tutorial.auto.hint', $json$"Désactivé, les tutoriels ne s’ouvrent que sur demande (bouton d’aide, Ctrl+K ou ici)."$json$::jsonb),
  ('ru', 'tutorial.auto.hint', $json$"Если выключено, обучение открывается только по вашему запросу (кнопка помощи, Ctrl+K или здесь)."$json$::jsonb),
  ('ja', 'tutorial.auto.hint', $json$"オフの場合、チュートリアルは操作したときだけ開きます（ヘルプボタン、Ctrl+K、またはここ）。"$json$::jsonb),
  ('de', 'tutorial.auto.hint', $json$"Aus: Tutorials öffnen sich nur auf Wunsch (Hilfe-Button, Strg+K oder hier)."$json$::jsonb),
  ('pt-BR', 'tutorial.reset', $json$"Mostrar todos os tutoriais de novo"$json$::jsonb),
  ('en', 'tutorial.reset', $json$"Show all tutorials again"$json$::jsonb),
  ('es', 'tutorial.reset', $json$"Mostrar todos los tutoriales de nuevo"$json$::jsonb),
  ('zh-CN', 'tutorial.reset', $json$"重新显示所有教程"$json$::jsonb),
  ('hi', 'tutorial.reset', $json$"सभी ट्यूटोरियल फिर से दिखाएँ"$json$::jsonb),
  ('ar', 'tutorial.reset', $json$"عرض كل الأدلة مرة أخرى"$json$::jsonb),
  ('fr', 'tutorial.reset', $json$"Réafficher tous les tutoriels"$json$::jsonb),
  ('ru', 'tutorial.reset', $json$"Показать всё обучение снова"$json$::jsonb),
  ('ja', 'tutorial.reset', $json$"すべてのチュートリアルを再表示"$json$::jsonb),
  ('de', 'tutorial.reset', $json$"Alle Tutorials erneut anzeigen"$json$::jsonb),
  ('pt-BR', 'tutorial.start', $json$"Iniciar"$json$::jsonb),
  ('en', 'tutorial.start', $json$"Start"$json$::jsonb),
  ('es', 'tutorial.start', $json$"Iniciar"$json$::jsonb),
  ('zh-CN', 'tutorial.start', $json$"开始"$json$::jsonb),
  ('hi', 'tutorial.start', $json$"शुरू करें"$json$::jsonb),
  ('ar', 'tutorial.start', $json$"ابدأ"$json$::jsonb),
  ('fr', 'tutorial.start', $json$"Démarrer"$json$::jsonb),
  ('ru', 'tutorial.start', $json$"Начать"$json$::jsonb),
  ('ja', 'tutorial.start', $json$"開始"$json$::jsonb),
  ('de', 'tutorial.start', $json$"Starten"$json$::jsonb),
  ('pt-BR', 'tutorial.steps', $json$"{count} passos"$json$::jsonb),
  ('en', 'tutorial.steps', $json$"{count} steps"$json$::jsonb),
  ('es', 'tutorial.steps', $json$"{count} pasos"$json$::jsonb),
  ('zh-CN', 'tutorial.steps', $json$"{count} 步"$json$::jsonb),
  ('hi', 'tutorial.steps', $json$"{count} चरण"$json$::jsonb),
  ('ar', 'tutorial.steps', $json$"{count} خطوات"$json$::jsonb),
  ('fr', 'tutorial.steps', $json$"{count} étapes"$json$::jsonb),
  ('ru', 'tutorial.steps', $json$"шагов: {count}"$json$::jsonb),
  ('ja', 'tutorial.steps', $json$"{count} ステップ"$json$::jsonb),
  ('de', 'tutorial.steps', $json$"{count} Schritte"$json$::jsonb),
  ('pt-BR', 'tutorial.seen', $json$"visto"$json$::jsonb),
  ('en', 'tutorial.seen', $json$"seen"$json$::jsonb),
  ('es', 'tutorial.seen', $json$"visto"$json$::jsonb),
  ('zh-CN', 'tutorial.seen', $json$"已看过"$json$::jsonb),
  ('hi', 'tutorial.seen', $json$"देखा गया"$json$::jsonb),
  ('ar', 'tutorial.seen', $json$"تمت المشاهدة"$json$::jsonb),
  ('fr', 'tutorial.seen', $json$"vu"$json$::jsonb),
  ('ru', 'tutorial.seen', $json$"просмотрено"$json$::jsonb),
  ('ja', 'tutorial.seen', $json$"表示済み"$json$::jsonb),
  ('de', 'tutorial.seen', $json$"gesehen"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.tutorials.title', $json$"Tutoriais para cada funcionalidade"$json$::jsonb),
  ('en', 'whatsNew.item.tutorials.title', $json$"Tutorials for every feature"$json$::jsonb),
  ('es', 'whatsNew.item.tutorials.title', $json$"Tutoriales para cada función"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.tutorials.title', $json$"每个功能都有教程"$json$::jsonb),
  ('hi', 'whatsNew.item.tutorials.title', $json$"हर सुविधा के लिए ट्यूटोरियल"$json$::jsonb),
  ('ar', 'whatsNew.item.tutorials.title', $json$"أدلة تعليمية لكل ميزة"$json$::jsonb),
  ('fr', 'whatsNew.item.tutorials.title', $json$"Des tutoriels pour chaque fonctionnalité"$json$::jsonb),
  ('ru', 'whatsNew.item.tutorials.title', $json$"Обучение для каждой функции"$json$::jsonb),
  ('ja', 'whatsNew.item.tutorials.title', $json$"すべての機能にチュートリアル"$json$::jsonb),
  ('de', 'whatsNew.item.tutorials.title', $json$"Tutorials für jede Funktion"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.tutorials.detail', $json$"Cada tela tem um passeio guiado que apresenta as funcionalidades dela, com o elemento destacado na tela. Abre sozinho na primeira visita; depois, pelo botão de ajuda (?) na lateral, pela paleta (Ctrl+K) ou em Configurações › App › Tutoriais, onde também dá para desligar a abertura automática. Funcionalidade nova entra no tutorial junto com a documentação."$json$::jsonb),
  ('en', 'whatsNew.item.tutorials.detail', $json$"Each screen has a guided tour that introduces its features, highlighting the element on screen. It opens by itself on your first visit; afterwards, use the help button (?) in the sidebar, the command palette (Ctrl+K) or Settings › App › Tutorials, where you can also turn off the automatic opening. New features join the tutorial together with the documentation."$json$::jsonb),
  ('es', 'whatsNew.item.tutorials.detail', $json$"Cada pantalla tiene un recorrido guiado que presenta sus funciones, resaltando el elemento en pantalla. Se abre solo en la primera visita; después, con el botón de ayuda (?) de la barra lateral, la paleta (Ctrl+K) o Ajustes › App › Tutoriales, donde también puedes desactivar la apertura automática. Las funciones nuevas entran en el tutorial junto con la documentación."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.tutorials.detail', $json$"每个界面都有一个引导教程，介绍该界面的功能并在屏幕上高亮对应元素。首次访问时自动打开；之后可通过侧边栏的帮助按钮 (?)、命令面板 (Ctrl+K) 或 设置 › 应用 › 教程 打开，也可在那里关闭自动打开。新功能会与文档一同加入教程。"$json$::jsonb),
  ('hi', 'whatsNew.item.tutorials.detail', $json$"हर स्क्रीन का एक गाइडेड टूर है जो उसकी सुविधाओं का परिचय देता है और स्क्रीन पर संबंधित तत्व को हाइलाइट करता है। पहली बार जाने पर यह अपने आप खुलता है; बाद में साइडबार के सहायता बटन (?), कमांड पैलेट (Ctrl+K) या सेटिंग › ऐप › ट्यूटोरियल से खोलें, जहाँ स्वतः खुलना बंद भी किया जा सकता है। नई सुविधाएँ दस्तावेज़ के साथ ट्यूटोरियल में जुड़ती हैं।"$json$::jsonb),
  ('ar', 'whatsNew.item.tutorials.detail', $json$"لكل شاشة جولة إرشادية تعرّف بميزاتها وتُبرز العنصر المعني على الشاشة. تُفتح تلقائيًا في أول زيارة؛ وبعدها عبر زر المساعدة (؟) في الشريط الجانبي أو لوحة الأوامر (Ctrl+K) أو الإعدادات › التطبيق › الأدلة، حيث يمكنك أيضًا إيقاف الفتح التلقائي. تنضم الميزات الجديدة إلى الدليل مع التوثيق."$json$::jsonb),
  ('fr', 'whatsNew.item.tutorials.detail', $json$"Chaque écran a une visite guidée qui présente ses fonctionnalités en mettant l’élément en évidence. Elle s’ouvre toute seule à la première visite ; ensuite, via le bouton d’aide (?) de la barre latérale, la palette (Ctrl+K) ou Réglages › App › Tutoriels, où vous pouvez aussi désactiver l’ouverture automatique. Les nouvelles fonctionnalités rejoignent le tutoriel avec la documentation."$json$::jsonb),
  ('ru', 'whatsNew.item.tutorials.detail', $json$"У каждого экрана есть обучающий тур, который знакомит с его функциями и подсвечивает нужный элемент. При первом посещении он открывается сам; позже — кнопкой помощи (?) в боковой панели, палитрой команд (Ctrl+K) или в Настройки › Приложение › Обучение, где можно отключить и автоматическое открытие. Новые функции попадают в обучение вместе с документацией."$json$::jsonb),
  ('ja', 'whatsNew.item.tutorials.detail', $json$"各画面に、その機能を紹介し画面上の要素をハイライトするガイドツアーがあります。初回の訪問時に自動で開き、その後はサイドバーのヘルプボタン (?)、コマンドパレット (Ctrl+K)、または 設定 › アプリ › チュートリアル から開けます（自動表示のオフもここで可能）。新機能はドキュメントと一緒にチュートリアルに追加されます。"$json$::jsonb),
  ('de', 'whatsNew.item.tutorials.detail', $json$"Jeder Bildschirm hat eine geführte Tour, die seine Funktionen vorstellt und das Element auf dem Bildschirm hervorhebt. Sie öffnet sich beim ersten Besuch von selbst; danach über den Hilfe-Button (?) in der Seitenleiste, die Befehlspalette (Strg+K) oder Einstellungen › App › Tutorials, wo sich das automatische Öffnen auch abschalten lässt. Neue Funktionen kommen zusammen mit der Dokumentation ins Tutorial."$json$::jsonb),
  ('pt-BR', 'docs.tutorials.title', $json$"Tutoriais"$json$::jsonb),
  ('en', 'docs.tutorials.title', $json$"Tutorials"$json$::jsonb),
  ('es', 'docs.tutorials.title', $json$"Tutoriales"$json$::jsonb),
  ('zh-CN', 'docs.tutorials.title', $json$"教程"$json$::jsonb),
  ('hi', 'docs.tutorials.title', $json$"ट्यूटोरियल"$json$::jsonb),
  ('ar', 'docs.tutorials.title', $json$"الأدلة التعليمية"$json$::jsonb),
  ('fr', 'docs.tutorials.title', $json$"Tutoriels"$json$::jsonb),
  ('ru', 'docs.tutorials.title', $json$"Обучение"$json$::jsonb),
  ('ja', 'docs.tutorials.title', $json$"チュートリアル"$json$::jsonb),
  ('de', 'docs.tutorials.title', $json$"Tutorials"$json$::jsonb),
  ('pt-BR', 'docs.tutorials.summary', $json$"Cada tela tem um passeio guiado que explica as funcionalidades dela, com o elemento destacado, usando o mesmo texto desta documentação."$json$::jsonb),
  ('en', 'docs.tutorials.summary', $json$"Each screen has a guided tour that explains its features, highlighting the element, using the same text as this documentation."$json$::jsonb),
  ('es', 'docs.tutorials.summary', $json$"Cada pantalla tiene un recorrido guiado que explica sus funciones, resaltando el elemento, con el mismo texto de esta documentación."$json$::jsonb),
  ('zh-CN', 'docs.tutorials.summary', $json$"每个界面都有一个引导教程，使用与本文档相同的文字讲解其功能并高亮对应元素。"$json$::jsonb),
  ('hi', 'docs.tutorials.summary', $json$"हर स्क्रीन का एक गाइडेड टूर है जो इसी दस्तावेज़ के पाठ से उसकी सुविधाएँ समझाता है और तत्व को हाइलाइट करता है।"$json$::jsonb),
  ('ar', 'docs.tutorials.summary', $json$"لكل شاشة جولة إرشادية تشرح ميزاتها وتُبرز العنصر، بنفس نص هذا التوثيق."$json$::jsonb),
  ('fr', 'docs.tutorials.summary', $json$"Chaque écran a une visite guidée qui explique ses fonctionnalités en mettant l’élément en évidence, avec le même texte que cette documentation."$json$::jsonb),
  ('ru', 'docs.tutorials.summary', $json$"У каждого экрана есть обучающий тур, который объясняет его функции и подсвечивает элемент, с тем же текстом, что и в этой документации."$json$::jsonb),
  ('ja', 'docs.tutorials.summary', $json$"各画面に、このドキュメントと同じ文章で機能を説明し、要素をハイライトするガイドツアーがあります。"$json$::jsonb),
  ('de', 'docs.tutorials.summary', $json$"Jeder Bildschirm hat eine geführte Tour, die seine Funktionen mit demselben Text wie diese Dokumentation erklärt und das Element hervorhebt."$json$::jsonb),
  ('pt-BR', 'docs.tutorials.usage', $json$"O tutorial abre sozinho na primeira visita a cada tela. Para rever: botão de ajuda (?) na lateral, Tutorial desta tela na paleta de comandos (Ctrl+K) ou Configurações › App › Tutoriais, onde também se desliga a abertura automática."$json$::jsonb),
  ('en', 'docs.tutorials.usage', $json$"The tutorial opens by itself on the first visit to each screen. To see it again: the help button (?) in the sidebar, Tutorial for this screen in the command palette (Ctrl+K), or Settings › App › Tutorials, where you can also turn off the automatic opening."$json$::jsonb),
  ('es', 'docs.tutorials.usage', $json$"El tutorial se abre solo en la primera visita a cada pantalla. Para verlo de nuevo: el botón de ayuda (?) de la barra lateral, Tutorial de esta pantalla en la paleta de comandos (Ctrl+K) o Ajustes › App › Tutoriales, donde también se desactiva la apertura automática."$json$::jsonb),
  ('zh-CN', 'docs.tutorials.usage', $json$"教程会在首次访问每个界面时自动打开。再次查看：侧边栏的帮助按钮 (?)、命令面板 (Ctrl+K) 中的“本页教程”，或 设置 › 应用 › 教程（也可在此关闭自动打开）。"$json$::jsonb),
  ('hi', 'docs.tutorials.usage', $json$"ट्यूटोरियल हर स्क्रीन पर पहली बार जाने पर अपने आप खुलता है। दोबारा देखने के लिए: साइडबार का सहायता बटन (?), कमांड पैलेट (Ctrl+K) में इस स्क्रीन का ट्यूटोरियल, या सेटिंग › ऐप › ट्यूटोरियल, जहाँ स्वतः खुलना बंद भी किया जा सकता है।"$json$::jsonb),
  ('ar', 'docs.tutorials.usage', $json$"يُفتح الدليل تلقائيًا عند أول زيارة لكل شاشة. لمشاهدته مجددًا: زر المساعدة (؟) في الشريط الجانبي، أو «دليل هذه الشاشة» في لوحة الأوامر (Ctrl+K)، أو الإعدادات › التطبيق › الأدلة حيث يمكن أيضًا إيقاف الفتح التلقائي."$json$::jsonb),
  ('fr', 'docs.tutorials.usage', $json$"Le tutoriel s’ouvre tout seul à la première visite de chaque écran. Pour le revoir : le bouton d’aide (?) de la barre latérale, Tutoriel de cet écran dans la palette de commandes (Ctrl+K), ou Réglages › App › Tutoriels, où l’on peut aussi désactiver l’ouverture automatique."$json$::jsonb),
  ('ru', 'docs.tutorials.usage', $json$"Обучение открывается само при первом посещении каждого экрана. Чтобы увидеть его снова: кнопка помощи (?) в боковой панели, «Обучение для этого экрана» в палитре команд (Ctrl+K) или Настройки › Приложение › Обучение, где можно отключить автоматическое открытие."$json$::jsonb),
  ('ja', 'docs.tutorials.usage', $json$"チュートリアルは各画面を初めて開いたときに自動で表示されます。もう一度見るには、サイドバーのヘルプボタン (?)、コマンドパレット (Ctrl+K) の「この画面のチュートリアル」、または 設定 › アプリ › チュートリアル（自動表示のオフもここで可能）を使います。"$json$::jsonb),
  ('de', 'docs.tutorials.usage', $json$"Das Tutorial öffnet sich beim ersten Besuch jedes Bildschirms von selbst. Erneut ansehen: Hilfe-Button (?) in der Seitenleiste, Tutorial für diesen Bildschirm in der Befehlspalette (Strg+K) oder Einstellungen › App › Tutorials, wo sich das automatische Öffnen auch abschalten lässt."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
