-- O layout novo do chat: copiar a resposta, voltar ao fim da conversa
-- quando se subiu para reler e confirmar antes de limpar o histórico.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'chat.copy', $json$"Copiar resposta"$json$::jsonb),
  ('pt-BR', 'chat.copied', $json$"Resposta copiada"$json$::jsonb),
  ('pt-BR', 'chat.jumpToLatest', $json$"Ir para o fim"$json$::jsonb),
  ('pt-BR', 'chat.clear.title', $json$"Limpar chat"$json$::jsonb),
  ('pt-BR', 'chat.clear.description', $json$"Limpar todas as mensagens de “{title}”? O chat continua no projeto, mas o histórico não pode ser recuperado."$json$::jsonb),
  ('en', 'chat.copy', $json$"Copy answer"$json$::jsonb),
  ('en', 'chat.copied', $json$"Answer copied"$json$::jsonb),
  ('en', 'chat.jumpToLatest', $json$"Jump to latest"$json$::jsonb),
  ('en', 'chat.clear.title', $json$"Clear chat"$json$::jsonb),
  ('en', 'chat.clear.description', $json$"Clear every message in “{title}”? The chat stays in the project, but its history can't be recovered."$json$::jsonb),
  ('es', 'chat.copy', $json$"Copiar respuesta"$json$::jsonb),
  ('es', 'chat.copied', $json$"Respuesta copiada"$json$::jsonb),
  ('es', 'chat.jumpToLatest', $json$"Ir al final"$json$::jsonb),
  ('es', 'chat.clear.title', $json$"Vaciar chat"$json$::jsonb),
  ('es', 'chat.clear.description', $json$"¿Borrar todos los mensajes de “{title}”? El chat sigue en el proyecto, pero su historial no se puede recuperar."$json$::jsonb),
  ('zh-CN', 'chat.copy', $json$"复制回答"$json$::jsonb),
  ('zh-CN', 'chat.copied', $json$"已复制回答"$json$::jsonb),
  ('zh-CN', 'chat.jumpToLatest', $json$"跳到最新"$json$::jsonb),
  ('zh-CN', 'chat.clear.title', $json$"清空聊天"$json$::jsonb),
  ('zh-CN', 'chat.clear.description', $json$"要清空“{title}”中的所有消息吗？聊天仍保留在项目中，但历史记录无法恢复。"$json$::jsonb),
  ('hi', 'chat.copy', $json$"उत्तर कॉपी करें"$json$::jsonb),
  ('hi', 'chat.copied', $json$"उत्तर कॉपी हो गया"$json$::jsonb),
  ('hi', 'chat.jumpToLatest', $json$"नवीनतम पर जाएँ"$json$::jsonb),
  ('hi', 'chat.clear.title', $json$"चैट साफ़ करें"$json$::jsonb),
  ('hi', 'chat.clear.description', $json$"“{title}” के सभी संदेश साफ़ करें? चैट प्रोजेक्ट में बनी रहेगी, लेकिन उसका इतिहास वापस नहीं मिलेगा।"$json$::jsonb),
  ('ar', 'chat.copy', $json$"نسخ الإجابة"$json$::jsonb),
  ('ar', 'chat.copied', $json$"تم نسخ الإجابة"$json$::jsonb),
  ('ar', 'chat.jumpToLatest', $json$"الانتقال إلى الأحدث"$json$::jsonb),
  ('ar', 'chat.clear.title', $json$"مسح المحادثة"$json$::jsonb),
  ('ar', 'chat.clear.description', $json$"مسح كل الرسائل في “{title}”؟ تبقى المحادثة في المشروع، لكن لا يمكن استعادة سجلها."$json$::jsonb),
  ('fr', 'chat.copy', $json$"Copier la réponse"$json$::jsonb),
  ('fr', 'chat.copied', $json$"Réponse copiée"$json$::jsonb),
  ('fr', 'chat.jumpToLatest', $json$"Aller au plus récent"$json$::jsonb),
  ('fr', 'chat.clear.title', $json$"Vider le chat"$json$::jsonb),
  ('fr', 'chat.clear.description', $json$"Effacer tous les messages de « {title} » ? Le chat reste dans le projet, mais son historique ne pourra pas être récupéré."$json$::jsonb),
  ('ru', 'chat.copy', $json$"Копировать ответ"$json$::jsonb),
  ('ru', 'chat.copied', $json$"Ответ скопирован"$json$::jsonb),
  ('ru', 'chat.jumpToLatest', $json$"К последним"$json$::jsonb),
  ('ru', 'chat.clear.title', $json$"Очистить чат"$json$::jsonb),
  ('ru', 'chat.clear.description', $json$"Удалить все сообщения в «{title}»? Чат останется в проекте, но его историю нельзя будет восстановить."$json$::jsonb),
  ('ja', 'chat.copy', $json$"回答をコピー"$json$::jsonb),
  ('ja', 'chat.copied', $json$"回答をコピーしました"$json$::jsonb),
  ('ja', 'chat.jumpToLatest', $json$"最新へ移動"$json$::jsonb),
  ('ja', 'chat.clear.title', $json$"チャットを消去"$json$::jsonb),
  ('ja', 'chat.clear.description', $json$"「{title}」のすべてのメッセージを消去しますか？チャットはプロジェクトに残りますが、履歴は元に戻せません。"$json$::jsonb),
  ('de', 'chat.copy', $json$"Antwort kopieren"$json$::jsonb),
  ('de', 'chat.copied', $json$"Antwort kopiert"$json$::jsonb),
  ('de', 'chat.jumpToLatest', $json$"Zum Neuesten"$json$::jsonb),
  ('de', 'chat.clear.title', $json$"Chat leeren"$json$::jsonb),
  ('de', 'chat.clear.description', $json$"Alle Nachrichten in „{title}“ löschen? Der Chat bleibt im Projekt, aber sein Verlauf kann nicht wiederhergestellt werden."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
