-- v0.84.0: os recursos que o app já tinha e a lista de Recursos da
-- Administração não: servidores MCP, skills, busca no skills.sh, agente Kilo
-- Code, OpenRouter e LiteLLM, e a busca na conversa. Entram em todo plano
-- opcionais e ligados, como o usuário já os tem hoje; o admin tira dos planos
-- que quiser.

insert into public.features (key, position, core) values
  ('mcp', 120, false),
  ('skills', 125, false),
  ('skillsHub', 126, false),
  ('kiloCode', 127, false),
  ('gatewayProviders', 128, false),
  ('conversationFind', 62, false)
on conflict (key) do nothing;

insert into public.plan_features (plan_key, feature_key, mode, default_on)
select p.key, f.key, 'optional', true from public.plans p cross join public.features f
where f.key in ('mcp', 'skills', 'skillsHub', 'kiloCode', 'gatewayProviders', 'conversationFind')
on conflict (plan_key, feature_key) do nothing;

insert into public.translations (locale, key, value) values
  ('pt-BR', 'feature.mcp.title', $json$"Servidores MCP"$json$::jsonb),
  ('en', 'feature.mcp.title', $json$"MCP servers"$json$::jsonb),
  ('es', 'feature.mcp.title', $json$"Servidores MCP"$json$::jsonb),
  ('zh-CN', 'feature.mcp.title', $json$"MCP 服务器"$json$::jsonb),
  ('hi', 'feature.mcp.title', $json$"MCP सर्वर"$json$::jsonb),
  ('ar', 'feature.mcp.title', $json$"خوادم MCP"$json$::jsonb),
  ('fr', 'feature.mcp.title', $json$"Serveurs MCP"$json$::jsonb),
  ('ru', 'feature.mcp.title', $json$"MCP-серверы"$json$::jsonb),
  ('ja', 'feature.mcp.title', $json$"MCPサーバー"$json$::jsonb),
  ('de', 'feature.mcp.title', $json$"MCP-Server"$json$::jsonb),
  ('pt-BR', 'feature.mcp.detail', $json$"Ligar servidores MCP aos agentes: ferramentas externas, a aba MCP e os servidores da organização."$json$::jsonb),
  ('en', 'feature.mcp.detail', $json$"Connect MCP servers to the agents: external tools, the MCP tab and the organization servers."$json$::jsonb),
  ('es', 'feature.mcp.detail', $json$"Conectar servidores MCP a los agentes: herramientas externas, la pestaña MCP y los servidores de la organización."$json$::jsonb),
  ('zh-CN', 'feature.mcp.detail', $json$"为代理连接 MCP 服务器：外部工具、MCP 标签页和组织的服务器。"$json$::jsonb),
  ('hi', 'feature.mcp.detail', $json$"एजेंट से MCP सर्वर जोड़ें: बाहरी टूल, MCP टैब और संगठन के सर्वर।"$json$::jsonb),
  ('ar', 'feature.mcp.detail', $json$"ربط خوادم MCP بالوكلاء: أدوات خارجية وتبويب MCP وخوادم المؤسسة."$json$::jsonb),
  ('fr', 'feature.mcp.detail', $json$"Connecter des serveurs MCP aux agents : outils externes, l'onglet MCP et les serveurs de l'organisation."$json$::jsonb),
  ('ru', 'feature.mcp.detail', $json$"Подключение MCP-серверов к агентам: внешние инструменты, вкладка MCP и серверы организации."$json$::jsonb),
  ('ja', 'feature.mcp.detail', $json$"エージェントにMCPサーバーを接続：外部ツール、MCPタブ、組織のサーバー。"$json$::jsonb),
  ('de', 'feature.mcp.detail', $json$"MCP-Server an die Agenten anbinden: externe Werkzeuge, der MCP-Tab und die Server der Organisation."$json$::jsonb),
  ('pt-BR', 'feature.skills.title', $json$"Skills"$json$::jsonb),
  ('en', 'feature.skills.title', $json$"Skills"$json$::jsonb),
  ('es', 'feature.skills.title', $json$"Skills"$json$::jsonb),
  ('zh-CN', 'feature.skills.title', $json$"技能"$json$::jsonb),
  ('hi', 'feature.skills.title', $json$"स्किल्स"$json$::jsonb),
  ('ar', 'feature.skills.title', $json$"المهارات"$json$::jsonb),
  ('fr', 'feature.skills.title', $json$"Skills"$json$::jsonb),
  ('ru', 'feature.skills.title', $json$"Навыки"$json$::jsonb),
  ('ja', 'feature.skills.title', $json$"スキル"$json$::jsonb),
  ('de', 'feature.skills.title', $json$"Skills"$json$::jsonb),
  ('pt-BR', 'feature.skills.detail', $json$"Pastas SKILL.md que o Jev escolhe por pedido, a aba Skills e as skills da organização."$json$::jsonb),
  ('en', 'feature.skills.detail', $json$"SKILL.md folders that Jev picks per request, the Skills tab and the organization skills."$json$::jsonb),
  ('es', 'feature.skills.detail', $json$"Carpetas SKILL.md que Jev elige por solicitud, la pestaña Skills y las skills de la organización."$json$::jsonb),
  ('zh-CN', 'feature.skills.detail', $json$"Jev 按请求选择的 SKILL.md 文件夹、技能标签页和组织的技能。"$json$::jsonb),
  ('hi', 'feature.skills.detail', $json$"SKILL.md फ़ोल्डर जिन्हें Jev हर अनुरोध पर चुनता है, स्किल्स टैब और संगठन की स्किल्स।"$json$::jsonb),
  ('ar', 'feature.skills.detail', $json$"مجلدات SKILL.md التي يختار منها Jev لكل طلب، وتبويب المهارات ومهارات المؤسسة."$json$::jsonb),
  ('fr', 'feature.skills.detail', $json$"Dossiers SKILL.md que Jev choisit à chaque demande, l'onglet Skills et les skills de l'organisation."$json$::jsonb),
  ('ru', 'feature.skills.detail', $json$"Папки SKILL.md, из которых Jev выбирает под запрос, вкладка «Навыки» и навыки организации."$json$::jsonb),
  ('ja', 'feature.skills.detail', $json$"Jevがリクエストごとに選ぶSKILL.mdフォルダ、スキルタブ、組織のスキル。"$json$::jsonb),
  ('de', 'feature.skills.detail', $json$"SKILL.md-Ordner, aus denen Jev pro Anfrage wählt, der Skills-Tab und die Skills der Organisation."$json$::jsonb),
  ('pt-BR', 'feature.skillsHub.title', $json$"Busca no skills.sh"$json$::jsonb),
  ('en', 'feature.skillsHub.title', $json$"skills.sh search"$json$::jsonb),
  ('es', 'feature.skillsHub.title', $json$"Búsqueda en skills.sh"$json$::jsonb),
  ('zh-CN', 'feature.skillsHub.title', $json$"skills.sh 搜索"$json$::jsonb),
  ('hi', 'feature.skillsHub.title', $json$"skills.sh खोज"$json$::jsonb),
  ('ar', 'feature.skillsHub.title', $json$"البحث في skills.sh"$json$::jsonb),
  ('fr', 'feature.skillsHub.title', $json$"Recherche sur skills.sh"$json$::jsonb),
  ('ru', 'feature.skillsHub.title', $json$"Поиск на skills.sh"$json$::jsonb),
  ('ja', 'feature.skillsHub.title', $json$"skills.sh検索"$json$::jsonb),
  ('de', 'feature.skillsHub.title', $json$"skills.sh-Suche"$json$::jsonb),
  ('pt-BR', 'feature.skillsHub.detail', $json$"Pesquisar e instalar skills do skills.sh direto em Configurações › Skills."$json$::jsonb),
  ('en', 'feature.skillsHub.detail', $json$"Search and install skills from skills.sh right in Settings › Skills."$json$::jsonb),
  ('es', 'feature.skillsHub.detail', $json$"Buscar e instalar skills de skills.sh en Configuración › Skills."$json$::jsonb),
  ('zh-CN', 'feature.skillsHub.detail', $json$"直接在“设置 › 技能”中搜索并安装 skills.sh 的技能。"$json$::jsonb),
  ('hi', 'feature.skillsHub.detail', $json$"सेटिंग्स › स्किल्स में ही skills.sh से स्किल्स खोजें और इंस्टॉल करें।"$json$::jsonb),
  ('ar', 'feature.skillsHub.detail', $json$"ابحث عن مهارات skills.sh وثبّتها مباشرة من الإعدادات › المهارات."$json$::jsonb),
  ('fr', 'feature.skillsHub.detail', $json$"Rechercher et installer des skills de skills.sh dans Réglages › Skills."$json$::jsonb),
  ('ru', 'feature.skillsHub.detail', $json$"Поиск и установка навыков с skills.sh прямо в Настройки › Навыки."$json$::jsonb),
  ('ja', 'feature.skillsHub.detail', $json$"設定 › スキルからskills.shのスキルを検索してインストール。"$json$::jsonb),
  ('de', 'feature.skillsHub.detail', $json$"Skills von skills.sh direkt in Einstellungen › Skills suchen und installieren."$json$::jsonb),
  ('pt-BR', 'feature.kiloCode.title', $json$"Agente Kilo Code"$json$::jsonb),
  ('en', 'feature.kiloCode.title', $json$"Kilo Code agent"$json$::jsonb),
  ('es', 'feature.kiloCode.title', $json$"Agente Kilo Code"$json$::jsonb),
  ('zh-CN', 'feature.kiloCode.title', $json$"Kilo Code 代理"$json$::jsonb),
  ('hi', 'feature.kiloCode.title', $json$"Kilo Code एजेंट"$json$::jsonb),
  ('ar', 'feature.kiloCode.title', $json$"وكيل Kilo Code"$json$::jsonb),
  ('fr', 'feature.kiloCode.title', $json$"Agent Kilo Code"$json$::jsonb),
  ('ru', 'feature.kiloCode.title', $json$"Агент Kilo Code"$json$::jsonb),
  ('ja', 'feature.kiloCode.title', $json$"Kilo Codeエージェント"$json$::jsonb),
  ('de', 'feature.kiloCode.title', $json$"Kilo-Code-Agent"$json$::jsonb),
  ('pt-BR', 'feature.kiloCode.detail', $json$"Usar o Kilo Code como agente de CLI do Jev, com a aba própria nas Configurações."$json$::jsonb),
  ('en', 'feature.kiloCode.detail', $json$"Use Kilo Code as one of Jev's CLI agents, with its own tab in Settings."$json$::jsonb),
  ('es', 'feature.kiloCode.detail', $json$"Usar Kilo Code como agente de CLI de Jev, con su pestaña en Configuración."$json$::jsonb),
  ('zh-CN', 'feature.kiloCode.detail', $json$"将 Kilo Code 用作 Jev 的 CLI 代理，并在设置中有专属标签页。"$json$::jsonb),
  ('hi', 'feature.kiloCode.detail', $json$"Kilo Code को Jev के CLI एजेंट के रूप में उपयोग करें, सेटिंग्स में अपने टैब के साथ।"$json$::jsonb),
  ('ar', 'feature.kiloCode.detail', $json$"استخدام Kilo Code كأحد وكلاء CLI لدى Jev مع تبويب خاص في الإعدادات."$json$::jsonb),
  ('fr', 'feature.kiloCode.detail', $json$"Utiliser Kilo Code comme agent CLI de Jev, avec son propre onglet dans Réglages."$json$::jsonb),
  ('ru', 'feature.kiloCode.detail', $json$"Использовать Kilo Code как один из CLI-агентов Jev с отдельной вкладкой в настройках."$json$::jsonb),
  ('ja', 'feature.kiloCode.detail', $json$"Kilo CodeをJevのCLIエージェントとして使用。設定に専用タブがあります。"$json$::jsonb),
  ('de', 'feature.kiloCode.detail', $json$"Kilo Code als einen der CLI-Agenten von Jev nutzen, mit eigenem Tab in den Einstellungen."$json$::jsonb),
  ('pt-BR', 'feature.gatewayProviders.title', $json$"OpenRouter e LiteLLM"$json$::jsonb),
  ('en', 'feature.gatewayProviders.title', $json$"OpenRouter and LiteLLM"$json$::jsonb),
  ('es', 'feature.gatewayProviders.title', $json$"OpenRouter y LiteLLM"$json$::jsonb),
  ('zh-CN', 'feature.gatewayProviders.title', $json$"OpenRouter 与 LiteLLM"$json$::jsonb),
  ('hi', 'feature.gatewayProviders.title', $json$"OpenRouter और LiteLLM"$json$::jsonb),
  ('ar', 'feature.gatewayProviders.title', $json$"OpenRouter وLiteLLM"$json$::jsonb),
  ('fr', 'feature.gatewayProviders.title', $json$"OpenRouter et LiteLLM"$json$::jsonb),
  ('ru', 'feature.gatewayProviders.title', $json$"OpenRouter и LiteLLM"$json$::jsonb),
  ('ja', 'feature.gatewayProviders.title', $json$"OpenRouterとLiteLLM"$json$::jsonb),
  ('de', 'feature.gatewayProviders.title', $json$"OpenRouter und LiteLLM"$json$::jsonb),
  ('pt-BR', 'feature.gatewayProviders.detail', $json$"Modelos por API (OpenRouter e LiteLLM) como agentes de texto, com as chaves guardadas só no computador."$json$::jsonb),
  ('en', 'feature.gatewayProviders.detail', $json$"Models through an API (OpenRouter and LiteLLM) as text agents, with keys stored only on the computer."$json$::jsonb),
  ('es', 'feature.gatewayProviders.detail', $json$"Modelos por API (OpenRouter y LiteLLM) como agentes de texto, con las claves guardadas solo en el equipo."$json$::jsonb),
  ('zh-CN', 'feature.gatewayProviders.detail', $json$"通过 API（OpenRouter 和 LiteLLM）使用模型作为文本代理，密钥仅保存在本机。"$json$::jsonb),
  ('hi', 'feature.gatewayProviders.detail', $json$"API के ज़रिए मॉडल (OpenRouter और LiteLLM) टेक्स्ट एजेंट के रूप में, कुंजियाँ केवल कंप्यूटर पर सहेजी जाती हैं।"$json$::jsonb),
  ('ar', 'feature.gatewayProviders.detail', $json$"نماذج عبر واجهة API (OpenRouter وLiteLLM) كوكلاء نصيين مع حفظ المفاتيح على الحاسوب فقط."$json$::jsonb),
  ('fr', 'feature.gatewayProviders.detail', $json$"Modèles via API (OpenRouter et LiteLLM) comme agents texte, clés stockées uniquement sur l'ordinateur."$json$::jsonb),
  ('ru', 'feature.gatewayProviders.detail', $json$"Модели через API (OpenRouter и LiteLLM) как текстовые агенты, ключи хранятся только на компьютере."$json$::jsonb),
  ('ja', 'feature.gatewayProviders.detail', $json$"API経由のモデル（OpenRouterとLiteLLM）をテキストエージェントとして使用。キーはこのコンピューターにのみ保存されます。"$json$::jsonb),
  ('de', 'feature.gatewayProviders.detail', $json$"Modelle über API (OpenRouter und LiteLLM) als Textagenten, Schlüssel nur auf dem Rechner gespeichert."$json$::jsonb),
  ('pt-BR', 'feature.conversationFind.title', $json$"Busca na conversa"$json$::jsonb),
  ('en', 'feature.conversationFind.title', $json$"Find in conversation"$json$::jsonb),
  ('es', 'feature.conversationFind.title', $json$"Buscar en la conversación"$json$::jsonb),
  ('zh-CN', 'feature.conversationFind.title', $json$"对话内查找"$json$::jsonb),
  ('hi', 'feature.conversationFind.title', $json$"बातचीत में खोजें"$json$::jsonb),
  ('ar', 'feature.conversationFind.title', $json$"البحث في المحادثة"$json$::jsonb),
  ('fr', 'feature.conversationFind.title', $json$"Recherche dans la conversation"$json$::jsonb),
  ('ru', 'feature.conversationFind.title', $json$"Поиск в беседе"$json$::jsonb),
  ('ja', 'feature.conversationFind.title', $json$"会話内検索"$json$::jsonb),
  ('de', 'feature.conversationFind.title', $json$"Suche im Gespräch"$json$::jsonb),
  ('pt-BR', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F procura texto no chat aberto e destaca cada ocorrência."$json$::jsonb),
  ('en', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F searches the open chat and highlights every match."$json$::jsonb),
  ('es', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F busca texto en el chat abierto y resalta cada coincidencia."$json$::jsonb),
  ('zh-CN', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F 在当前聊天中搜索文本并高亮每个匹配项。"$json$::jsonb),
  ('hi', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F खुली चैट में टेक्स्ट खोजता है और हर मिलान को हाइलाइट करता है।"$json$::jsonb),
  ('ar', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F يبحث في المحادثة المفتوحة ويميّز كل نتيجة."$json$::jsonb),
  ('fr', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F cherche du texte dans le chat ouvert et surligne chaque occurrence."$json$::jsonb),
  ('ru', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F ищет текст в открытом чате и подсвечивает каждое совпадение."$json$::jsonb),
  ('ja', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+Fで開いているチャット内を検索し、一致をハイライト。"$json$::jsonb),
  ('de', 'feature.conversationFind.detail', $json$"Ctrl/Cmd+F durchsucht den offenen Chat und markiert jeden Treffer."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planFeatures.title', $json$"Todos os recursos na lista da Administração"$json$::jsonb),
  ('en', 'whatsNew.item.planFeatures.title', $json$"Every feature in the admin list"$json$::jsonb),
  ('es', 'whatsNew.item.planFeatures.title', $json$"Todas las funciones en la lista de Administración"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planFeatures.title', $json$"管理列表中的全部功能"$json$::jsonb),
  ('hi', 'whatsNew.item.planFeatures.title', $json$"एडमिन सूची में हर सुविधा"$json$::jsonb),
  ('ar', 'whatsNew.item.planFeatures.title', $json$"كل الميزات في قائمة الإدارة"$json$::jsonb),
  ('fr', 'whatsNew.item.planFeatures.title', $json$"Toutes les fonctionnalités dans la liste d'administration"$json$::jsonb),
  ('ru', 'whatsNew.item.planFeatures.title', $json$"Все функции в списке администрирования"$json$::jsonb),
  ('ja', 'whatsNew.item.planFeatures.title', $json$"管理リストにすべての機能"$json$::jsonb),
  ('de', 'whatsNew.item.planFeatures.title', $json$"Alle Funktionen in der Admin-Liste"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planFeatures.detail', $json$"Servidores MCP, skills, busca no skills.sh, o agente Kilo Code, OpenRouter e LiteLLM e a busca na conversa agora se ligam e desligam por plano na Administração do site. Os planos que já existem continuam com todos ligados."$json$::jsonb),
  ('en', 'whatsNew.item.planFeatures.detail', $json$"MCP servers, skills, skills.sh search, the Kilo Code agent, OpenRouter and LiteLLM, and find in conversation can now be switched per plan from the site's Administration. Plans that already exist keep all of them on."$json$::jsonb),
  ('es', 'whatsNew.item.planFeatures.detail', $json$"Los servidores MCP, las skills, la búsqueda en skills.sh, el agente Kilo Code, OpenRouter y LiteLLM y la búsqueda en la conversación ahora se activan por plan desde la Administración del sitio. Los planes existentes los conservan todos activados."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planFeatures.detail', $json$"MCP 服务器、技能、skills.sh 搜索、Kilo Code 代理、OpenRouter 与 LiteLLM 以及对话内查找，现在可在网站管理页按套餐开关。已有套餐保持全部开启。"$json$::jsonb),
  ('hi', 'whatsNew.item.planFeatures.detail', $json$"MCP सर्वर, स्किल्स, skills.sh खोज, Kilo Code एजेंट, OpenRouter और LiteLLM, और बातचीत में खोज अब साइट के एडमिन से प्लान के अनुसार चालू-बंद की जा सकती हैं। मौजूदा प्लान में सब चालू रहते हैं।"$json$::jsonb),
  ('ar', 'whatsNew.item.planFeatures.detail', $json$"يمكن الآن تشغيل خوادم MCP والمهارات والبحث في skills.sh ووكيل Kilo Code وOpenRouter وLiteLLM والبحث في المحادثة أو إيقافها لكل خطة من إدارة الموقع. تبقى كلها مفعّلة في الخطط الحالية."$json$::jsonb),
  ('fr', 'whatsNew.item.planFeatures.detail', $json$"Les serveurs MCP, les skills, la recherche sur skills.sh, l'agent Kilo Code, OpenRouter et LiteLLM, et la recherche dans la conversation s'activent désormais par plan depuis l'administration du site. Les plans existants gardent tout activé."$json$::jsonb),
  ('ru', 'whatsNew.item.planFeatures.detail', $json$"Серверы MCP, навыки, поиск на skills.sh, агент Kilo Code, OpenRouter и LiteLLM и поиск в беседе теперь включаются по тарифам в администрировании сайта. В существующих тарифах всё остаётся включённым."$json$::jsonb),
  ('ja', 'whatsNew.item.planFeatures.detail', $json$"MCPサーバー、スキル、skills.sh検索、Kilo Codeエージェント、OpenRouterとLiteLLM、会話内検索を、サイトの管理画面からプランごとに切り替えられます。既存のプランはすべて有効のままです。"$json$::jsonb),
  ('de', 'whatsNew.item.planFeatures.detail', $json$"MCP-Server, Skills, die skills.sh-Suche, der Kilo-Code-Agent, OpenRouter und LiteLLM sowie die Suche im Gespräch lassen sich jetzt pro Plan in der Administration der Website schalten. Bestehende Pläne behalten alles eingeschaltet."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
