-- v0.49.0: planejar com um, construir com outro. Num pedido complexo do
-- modo build, um modelo de raciocínio escreve o plano antes do agente.
--
-- Só textos: a etapa do plano no chat, a opção em Configuração › Jev ›
-- Roteamento e o item da janela "Novidades".

insert into public.translations (locale, key, value) values
  ('pt-BR', 'beat.plan', $json$"{agent} · {model} está escrevendo o plano da construção"$json$::jsonb),
  ('pt-BR', 'jev.planFirst', $json$"Planejar com um modelo, construir com outro"$json$::jsonb),
  ('pt-BR', 'jev.planFirst.hint', $json$"Num pedido complexo do modo build, um modelo forte de raciocínio lê o projeto em somente leitura e escreve o plano antes; o agente que constrói recebe o plano junto com o pedido. Custa uma chamada a mais de agente por pedido complexo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planFirst.title', $json$"Um modelo de raciocínio planeja, um agente de código constrói"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planFirst.detail', $json$"Ligue Planejar com um modelo, construir com outro em Configuração › Jev › Roteamento. Num pedido complexo do modo build, o seu modelo de raciocínio mais forte escreve o plano antes, sem editar nada, e o agente escolhido para construir, que pode ser de outro provedor, recebe o plano junto com o pedido. Se o plano falhar, a construção segue como antes."$json$::jsonb),
  ('en', 'beat.plan', $json$"{agent} · {model} is writing the plan for the build"$json$::jsonb),
  ('en', 'jev.planFirst', $json$"Plan with one model, build with another"$json$::jsonb),
  ('en', 'jev.planFirst.hint', $json$"In a complex build request, a strong reasoning model reads the project in read-only mode and writes the plan first; the agent that builds gets the plan with the request. It costs one more agent call per complex request."$json$::jsonb),
  ('en', 'whatsNew.item.planFirst.title', $json$"A reasoning model plans, a coding agent builds"$json$::jsonb),
  ('en', 'whatsNew.item.planFirst.detail', $json$"Turn on Plan with one model, build with another in Settings › Jev › Routing. In a complex request in build mode, the strongest reasoning model you have writes the plan first without editing anything, and the agent picked to build, possibly from another provider, gets the plan with the request. If the plan fails, the build goes ahead as before."$json$::jsonb),
  ('es', 'beat.plan', $json$"{agent} · {model} está escribiendo el plan de la construcción"$json$::jsonb),
  ('es', 'jev.planFirst', $json$"Planificar con un modelo, construir con otro"$json$::jsonb),
  ('es', 'jev.planFirst.hint', $json$"En una solicitud compleja en modo build, un modelo de razonamiento potente lee el proyecto en solo lectura y escribe primero el plan; el agente que construye recibe el plan junto con la solicitud. Cuesta una llamada de agente más por solicitud compleja."$json$::jsonb),
  ('es', 'whatsNew.item.planFirst.title', $json$"Un modelo de razonamiento planifica, un agente de código construye"$json$::jsonb),
  ('es', 'whatsNew.item.planFirst.detail', $json$"Activa Planificar con un modelo, construir con otro en Configuración › Jev › Enrutamiento. En una solicitud compleja en modo build, tu modelo de razonamiento más potente escribe primero el plan sin editar nada, y el agente elegido para construir, que puede ser de otro proveedor, recibe el plan junto con la solicitud. Si el plan falla, la construcción sigue como antes."$json$::jsonb),
  ('zh-CN', 'beat.plan', $json$"{agent} · {model} 正在编写构建计划"$json$::jsonb),
  ('zh-CN', 'jev.planFirst', $json$"用一个模型规划,用另一个模型构建"$json$::jsonb),
  ('zh-CN', 'jev.planFirst.hint', $json$"在 build 模式的复杂请求中,一个强推理模型以只读方式阅读项目并先写出计划;负责构建的代理会随请求一起收到该计划。每个复杂请求会多一次代理调用。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planFirst.title', $json$"推理模型规划,编码代理构建"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planFirst.detail', $json$"在 设置 › Jev › 路由 中打开“用一个模型规划,用另一个模型构建”。在 build 模式的复杂请求中,你最强的推理模型会在不编辑任何内容的情况下先写出计划,被选中负责构建的代理(可能来自另一个提供方)会随请求一起收到计划。如果计划失败,构建照常进行。"$json$::jsonb),
  ('hi', 'beat.plan', $json$"{agent} · {model} बिल्ड की योजना लिख रहा है"$json$::jsonb),
  ('hi', 'jev.planFirst', $json$"एक मॉडल से योजना, दूसरे से निर्माण"$json$::jsonb),
  ('hi', 'jev.planFirst.hint', $json$"बिल्ड मोड के जटिल अनुरोध में, एक मज़बूत रीज़निंग मॉडल केवल-पढ़ने के मोड में प्रोजेक्ट पढ़कर पहले योजना लिखता है; निर्माण करने वाले एजेंट को अनुरोध के साथ योजना मिलती है। हर जटिल अनुरोध पर एक एजेंट कॉल ज़्यादा लगती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.planFirst.title', $json$"रीज़निंग मॉडल योजना बनाता है, कोडिंग एजेंट निर्माण करता है"$json$::jsonb),
  ('hi', 'whatsNew.item.planFirst.detail', $json$"सेटिंग्स › Jev › रूटिंग में एक मॉडल से योजना, दूसरे से निर्माण चालू करें। बिल्ड मोड के जटिल अनुरोध में, आपका सबसे मज़बूत रीज़निंग मॉडल कुछ भी संपादित किए बिना पहले योजना लिखता है, और निर्माण के लिए चुने गए एजेंट को, जो दूसरे प्रदाता का भी हो सकता है, अनुरोध के साथ योजना मिलती है। योजना विफल होने पर निर्माण पहले की तरह चलता है।"$json$::jsonb),
  ('ar', 'beat.plan', $json$"{agent} · {model} يكتب خطة البناء"$json$::jsonb),
  ('ar', 'jev.planFirst', $json$"التخطيط بنموذج والبناء بآخر"$json$::jsonb),
  ('ar', 'jev.planFirst.hint', $json$"في الطلب المعقّد في وضع البناء، يقرأ نموذج استدلال قوي المشروع في وضع القراءة فقط ويكتب الخطة أولًا، ويتلقى الوكيل الذي يبني الخطة مع الطلب. يكلّف ذلك استدعاءً إضافيًا لوكيل في كل طلب معقّد."$json$::jsonb),
  ('ar', 'whatsNew.item.planFirst.title', $json$"نموذج استدلال يخطط ووكيل برمجة يبني"$json$::jsonb),
  ('ar', 'whatsNew.item.planFirst.detail', $json$"فعّل «التخطيط بنموذج والبناء بآخر» في الإعدادات › Jev › التوجيه. في الطلب المعقّد في وضع البناء، يكتب أقوى نموذج استدلال لديك الخطة أولًا دون تعديل أي شيء، ويتلقى الوكيل المختار للبناء، وقد يكون من مزوّد آخر، الخطة مع الطلب. وإذا فشلت الخطة يستمر البناء كما كان."$json$::jsonb),
  ('fr', 'beat.plan', $json$"{agent} · {model} rédige le plan de la construction"$json$::jsonb),
  ('fr', 'jev.planFirst', $json$"Planifier avec un modèle, construire avec un autre"$json$::jsonb),
  ('fr', 'jev.planFirst.hint', $json$"Pour une demande complexe en mode build, un modèle de raisonnement puissant lit le projet en lecture seule et rédige d’abord le plan ; l’agent qui construit reçoit le plan avec la demande. Cela coûte un appel d’agent de plus par demande complexe."$json$::jsonb),
  ('fr', 'whatsNew.item.planFirst.title', $json$"Un modèle de raisonnement planifie, un agent de code construit"$json$::jsonb),
  ('fr', 'whatsNew.item.planFirst.detail', $json$"Activez Planifier avec un modèle, construire avec un autre dans Configuration › Jev › Routage. Pour une demande complexe en mode build, votre modèle de raisonnement le plus puissant rédige d’abord le plan sans rien modifier, et l’agent choisi pour construire, éventuellement d’un autre fournisseur, reçoit le plan avec la demande. Si le plan échoue, la construction continue comme avant."$json$::jsonb),
  ('ru', 'beat.plan', $json$"{agent} · {model} пишет план сборки"$json$::jsonb),
  ('ru', 'jev.planFirst', $json$"Планировать одной моделью, строить другой"$json$::jsonb),
  ('ru', 'jev.planFirst.hint', $json$"В сложном запросе в режиме build сильная модель рассуждения читает проект в режиме только чтения и сначала пишет план; агент, который строит, получает план вместе с запросом. Это ещё один вызов агента на каждый сложный запрос."$json$::jsonb),
  ('ru', 'whatsNew.item.planFirst.title', $json$"Модель рассуждения планирует, агент кода строит"$json$::jsonb),
  ('ru', 'whatsNew.item.planFirst.detail', $json$"Включите «Планировать одной моделью, строить другой» в Настройки › Jev › Маршрутизация. В сложном запросе в режиме build ваша самая сильная модель рассуждения сначала пишет план, ничего не редактируя, а агент, выбранный для сборки, возможно другого провайдера, получает план вместе с запросом. Если план не удался, сборка идёт как раньше."$json$::jsonb),
  ('ja', 'beat.plan', $json$"{agent} · {model} がビルドの計画を書いています"$json$::jsonb),
  ('ja', 'jev.planFirst', $json$"あるモデルで計画し、別のモデルで構築"$json$::jsonb),
  ('ja', 'jev.planFirst.hint', $json$"build モードの複雑な依頼では、強力な推論モデルが読み取り専用でプロジェクトを読み、先に計画を書きます。構築するエージェントは依頼と一緒に計画を受け取ります。複雑な依頼ごとにエージェントの呼び出しが1回増えます。"$json$::jsonb),
  ('ja', 'whatsNew.item.planFirst.title', $json$"推論モデルが計画し、コーディングエージェントが構築"$json$::jsonb),
  ('ja', 'whatsNew.item.planFirst.detail', $json$"設定 › Jev › ルーティングで「あるモデルで計画し、別のモデルで構築」をオンにしてください。build モードの複雑な依頼では、手持ちで最も強力な推論モデルが何も編集せずに先に計画を書き、構築に選ばれたエージェント(別のプロバイダーの場合もあります)が依頼と一緒に計画を受け取ります。計画に失敗した場合は、これまでどおり構築が進みます。"$json$::jsonb),
  ('de', 'beat.plan', $json$"{agent} · {model} schreibt den Plan für den Build"$json$::jsonb),
  ('de', 'jev.planFirst', $json$"Mit einem Modell planen, mit einem anderen bauen"$json$::jsonb),
  ('de', 'jev.planFirst.hint', $json$"Bei einer komplexen Anfrage im Build-Modus liest ein starkes Reasoning-Modell das Projekt schreibgeschützt und schreibt zuerst den Plan; der Agent, der baut, bekommt den Plan mit der Anfrage. Das kostet einen Agentenaufruf mehr pro komplexer Anfrage."$json$::jsonb),
  ('de', 'whatsNew.item.planFirst.title', $json$"Ein Reasoning-Modell plant, ein Coding-Agent baut"$json$::jsonb),
  ('de', 'whatsNew.item.planFirst.detail', $json$"Schalte Mit einem Modell planen, mit einem anderen bauen unter Einstellungen › Jev › Routing ein. Bei einer komplexen Anfrage im Build-Modus schreibt dein stärkstes Reasoning-Modell zuerst den Plan, ohne etwas zu bearbeiten, und der zum Bauen gewählte Agent, auch von einem anderen Anbieter, bekommt den Plan mit der Anfrage. Scheitert der Plan, läuft der Build wie bisher."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
