-- Site 2.10.0: a página Dashboard do painel (o uso da conta e, para o admin, o
-- do sistema), nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'site.overview.description.me', $json$"Como você tem usado o JayV: pedidos, tokens, custo e para onde foram."$json$::jsonb),
  ('pt-BR', 'site.overview.description.system', $json$"Como o JayV está sendo usado em todas as contas: quem entra, o que pede e quanto custa."$json$::jsonb),
  ('pt-BR', 'site.overview.view', $json$"Visão"$json$::jsonb),
  ('pt-BR', 'site.overview.view.me', $json$"Meu uso"$json$::jsonb),
  ('pt-BR', 'site.overview.view.system', $json$"Sistema"$json$::jsonb),
  ('pt-BR', 'site.overview.period', $json$"Período"$json$::jsonb),
  ('pt-BR', 'site.overview.period.days', $json${"one": "{count} dia", "other": "{count} dias"}$json$::jsonb),
  ('pt-BR', 'site.overview.since', $json$"Desde {date} · dias em {zone}"$json$::jsonb),
  ('pt-BR', 'site.overview.failed', $json$"Não foi possível carregar o painel. Tente de novo daqui a pouco."$json$::jsonb),
  ('pt-BR', 'site.overview.requests', $json$"Pedidos"$json$::jsonb),
  ('pt-BR', 'site.overview.requests.hint', $json$"{answered} respondidos · {failed} com falha · {blocked} barrados na portaria"$json$::jsonb),
  ('pt-BR', 'site.overview.tokens', $json$"Tokens"$json$::jsonb),
  ('pt-BR', 'site.overview.tokens.hint', $json$"{input} de entrada · {output} de saída · {cache} do cache"$json$::jsonb),
  ('pt-BR', 'site.overview.tokens.cache', $json$"mais {cache} do cache"$json$::jsonb),
  ('pt-BR', 'site.overview.cost', $json$"Custo"$json$::jsonb),
  ('pt-BR', 'site.overview.cost.hint', $json$"{calls} chamadas a modelos, {jev} do Jev"$json$::jsonb),
  ('pt-BR', 'site.overview.jev', $json$"Jev hoje"$json$::jsonb),
  ('pt-BR', 'site.overview.jev.limit', $json$"de {limit} chamadas por dia no seu plano"$json$::jsonb),
  ('pt-BR', 'site.overview.jev.unlimited', $json$"Sem limite diário no seu plano"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.requests', $json$"Pedidos por dia"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.tokens', $json$"Tokens por dia"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.sessions', $json$"Acessos por dia"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.active', $json$"Contas usando o app por dia"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.signups', $json$"Contas novas por dia"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.total', $json$"{total} no período"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.peak', $json$"Pico {value}"$json$::jsonb),
  ('pt-BR', 'site.overview.chart.table', $json$"Ver como tabela"$json$::jsonb),
  ('pt-BR', 'site.overview.column.day', $json$"Dia"$json$::jsonb),
  ('pt-BR', 'site.overview.column.model', $json$"Modelo"$json$::jsonb),
  ('pt-BR', 'site.overview.column.calls', $json$"Chamadas"$json$::jsonb),
  ('pt-BR', 'site.overview.column.tokens', $json$"Tokens"$json$::jsonb),
  ('pt-BR', 'site.overview.column.cost', $json$"Custo"$json$::jsonb),
  ('pt-BR', 'site.overview.column.requests', $json$"Pedidos"$json$::jsonb),
  ('pt-BR', 'site.overview.column.account', $json$"Conta"$json$::jsonb),
  ('pt-BR', 'site.overview.column.lastSignIn', $json$"Último acesso"$json$::jsonb),
  ('pt-BR', 'site.overview.column.environment', $json$"Ambiente"$json$::jsonb),
  ('pt-BR', 'site.overview.label.projects', $json$"Projetos"$json$::jsonb),
  ('pt-BR', 'site.overview.label.chats', $json$"Chats"$json$::jsonb),
  ('pt-BR', 'site.overview.label.requests', $json$"Pedidos"$json$::jsonb),
  ('pt-BR', 'site.overview.label.organizations', $json$"Organizações"$json$::jsonb),
  ('pt-BR', 'site.overview.label.devices', $json$"Computadores no período"$json$::jsonb),
  ('pt-BR', 'site.overview.label.avgCall', $json$"Chamada média a modelo"$json$::jsonb),
  ('pt-BR', 'site.overview.seconds', $json$"{value} s"$json$::jsonb),
  ('pt-BR', 'site.overview.totals', $json$"Desde o início"$json$::jsonb),
  ('pt-BR', 'site.overview.models', $json$"Modelos"$json$::jsonb),
  ('pt-BR', 'site.overview.models.empty', $json$"Nenhuma chamada a modelo neste período."$json$::jsonb),
  ('pt-BR', 'site.overview.environments', $json$"Por ambiente"$json$::jsonb),
  ('pt-BR', 'site.overview.environments.description', $json$"Seus projetos pessoais e cada organização da qual você participa, no período."$json$::jsonb),
  ('pt-BR', 'site.overview.chats', $json$"Chats recentes"$json$::jsonb),
  ('pt-BR', 'site.overview.chats.empty', $json$"Nenhum chat ainda. Comece um no app JayV."$json$::jsonb),
  ('pt-BR', 'site.overview.chats.untitled', $json$"Chat sem título"$json$::jsonb),
  ('pt-BR', 'site.overview.system.accounts', $json$"Contas"$json$::jsonb),
  ('pt-BR', 'site.overview.system.accounts.hint', $json$"{count} novas no período"$json$::jsonb),
  ('pt-BR', 'site.overview.system.active', $json$"Usando o app"$json$::jsonb),
  ('pt-BR', 'site.overview.system.active.hint', $json$"{day} hoje · {week} nos últimos 7 dias"$json$::jsonb),
  ('pt-BR', 'site.overview.system.signIns', $json$"Acessos"$json$::jsonb),
  ('pt-BR', 'site.overview.system.signIns.hint', $json$"{users} contas entraram · {open} sessões abertas"$json$::jsonb),
  ('pt-BR', 'site.overview.system.sessionsNote', $json$"Os acessos contam as sessões que ainda estão registradas: sair da conta apaga a sessão."$json$::jsonb),
  ('pt-BR', 'site.overview.system.access', $json$"Contas e acesso"$json$::jsonb),
  ('pt-BR', 'site.overview.system.confirmed', $json$"E-mail confirmado"$json$::jsonb),
  ('pt-BR', 'site.overview.system.mfa', $json$"Com duas etapas"$json$::jsonb),
  ('pt-BR', 'site.overview.system.banned', $json$"Bloqueadas"$json$::jsonb),
  ('pt-BR', 'site.overview.system.admins', $json$"Admins"$json$::jsonb),
  ('pt-BR', 'site.overview.system.signedInDay', $json$"Entraram hoje"$json$::jsonb),
  ('pt-BR', 'site.overview.system.signedInWeek', $json$"Entraram nos últimos 7 dias"$json$::jsonb),
  ('pt-BR', 'site.overview.system.activity', $json$"Projetos e chats"$json$::jsonb),
  ('pt-BR', 'site.overview.system.chatsNew', $json$"Chats novos no período"$json$::jsonb),
  ('pt-BR', 'site.overview.system.messages', $json$"Mensagens no período"$json$::jsonb),
  ('pt-BR', 'site.overview.system.orgRequests', $json$"Pedidos em organizações"$json$::jsonb),
  ('pt-BR', 'site.overview.system.failures', $json$"Chamadas a modelos com falha"$json$::jsonb),
  ('pt-BR', 'site.overview.system.topUsers', $json$"Quem mais usou"$json$::jsonb),
  ('pt-BR', 'site.overview.system.topUsers.empty', $json$"Ninguém usou o app neste período."$json$::jsonb),
  ('pt-BR', 'site.overview.system.plans', $json$"Planos"$json$::jsonb),
  ('pt-BR', 'site.overview.system.plans.users', $json${"one": "{count} conta", "other": "{count} contas"}$json$::jsonb),
  ('pt-BR', 'site.overview.system.organizations', $json$"Organizações e Jev"$json$::jsonb),
  ('pt-BR', 'site.overview.system.members', $json$"Membros"$json$::jsonb),
  ('pt-BR', 'site.overview.system.repositories', $json$"Repositórios"$json$::jsonb),
  ('pt-BR', 'site.overview.system.jevCalls', $json$"Chamadas ao Jev no período"$json$::jsonb),
  ('pt-BR', 'site.overview.system.jevUsers', $json$"Contas que usaram o Jev"$json$::jsonb),
  ('pt-BR', 'site.overview.system.recent', $json$"Contas mais novas"$json$::jsonb),
  ('pt-BR', 'site.overview.system.joined', $json$"Entrou em {date}"$json$::jsonb),
  ('pt-BR', 'site.overview.system.never', $json$"Nunca entrou"$json$::jsonb),
  ('pt-BR', 'site.overview.system.seen', $json$"Último acesso em {date}"$json$::jsonb),
  ('en', 'site.overview.description.me', $json$"How you have been using JayV: requests, tokens, cost and where they went."$json$::jsonb),
  ('en', 'site.overview.description.system', $json$"How JayV is being used across every account: who signs in, what they ask and what it costs."$json$::jsonb),
  ('en', 'site.overview.view', $json$"View"$json$::jsonb),
  ('en', 'site.overview.view.me', $json$"My usage"$json$::jsonb),
  ('en', 'site.overview.view.system', $json$"System"$json$::jsonb),
  ('en', 'site.overview.period', $json$"Period"$json$::jsonb),
  ('en', 'site.overview.period.days', $json${"one": "{count} day", "other": "{count} days"}$json$::jsonb),
  ('en', 'site.overview.since', $json$"Since {date} · days in {zone}"$json$::jsonb),
  ('en', 'site.overview.failed', $json$"Could not load the dashboard. Try again in a moment."$json$::jsonb),
  ('en', 'site.overview.requests', $json$"Requests"$json$::jsonb),
  ('en', 'site.overview.requests.hint', $json$"{answered} answered · {failed} failed · {blocked} blocked at the gatehouse"$json$::jsonb),
  ('en', 'site.overview.tokens', $json$"Tokens"$json$::jsonb),
  ('en', 'site.overview.tokens.hint', $json$"{input} in · {output} out · {cache} from cache"$json$::jsonb),
  ('en', 'site.overview.tokens.cache', $json$"{cache} more from cache"$json$::jsonb),
  ('en', 'site.overview.cost', $json$"Cost"$json$::jsonb),
  ('en', 'site.overview.cost.hint', $json$"{calls} model calls, {jev} by Jev"$json$::jsonb),
  ('en', 'site.overview.jev', $json$"Jev today"$json$::jsonb),
  ('en', 'site.overview.jev.limit', $json$"of {limit} calls a day in your plan"$json$::jsonb),
  ('en', 'site.overview.jev.unlimited', $json$"No daily limit in your plan"$json$::jsonb),
  ('en', 'site.overview.chart.requests', $json$"Requests per day"$json$::jsonb),
  ('en', 'site.overview.chart.tokens', $json$"Tokens per day"$json$::jsonb),
  ('en', 'site.overview.chart.sessions', $json$"Sign-ins per day"$json$::jsonb),
  ('en', 'site.overview.chart.active', $json$"Accounts using the app per day"$json$::jsonb),
  ('en', 'site.overview.chart.signups', $json$"New accounts per day"$json$::jsonb),
  ('en', 'site.overview.chart.total', $json$"{total} in the period"$json$::jsonb),
  ('en', 'site.overview.chart.peak', $json$"Peak {value}"$json$::jsonb),
  ('en', 'site.overview.chart.table', $json$"Show as a table"$json$::jsonb),
  ('en', 'site.overview.column.day', $json$"Day"$json$::jsonb),
  ('en', 'site.overview.column.model', $json$"Model"$json$::jsonb),
  ('en', 'site.overview.column.calls', $json$"Calls"$json$::jsonb),
  ('en', 'site.overview.column.tokens', $json$"Tokens"$json$::jsonb),
  ('en', 'site.overview.column.cost', $json$"Cost"$json$::jsonb),
  ('en', 'site.overview.column.requests', $json$"Requests"$json$::jsonb),
  ('en', 'site.overview.column.account', $json$"Account"$json$::jsonb),
  ('en', 'site.overview.column.lastSignIn', $json$"Last sign-in"$json$::jsonb),
  ('en', 'site.overview.column.environment', $json$"Environment"$json$::jsonb),
  ('en', 'site.overview.label.projects', $json$"Projects"$json$::jsonb),
  ('en', 'site.overview.label.chats', $json$"Chats"$json$::jsonb),
  ('en', 'site.overview.label.requests', $json$"Requests"$json$::jsonb),
  ('en', 'site.overview.label.organizations', $json$"Organizations"$json$::jsonb),
  ('en', 'site.overview.label.devices', $json$"Computers in the period"$json$::jsonb),
  ('en', 'site.overview.label.avgCall', $json$"Average model call"$json$::jsonb),
  ('en', 'site.overview.seconds', $json$"{value} s"$json$::jsonb),
  ('en', 'site.overview.totals', $json$"Since the start"$json$::jsonb),
  ('en', 'site.overview.models', $json$"Models"$json$::jsonb),
  ('en', 'site.overview.models.empty', $json$"No model calls in this period."$json$::jsonb),
  ('en', 'site.overview.environments', $json$"By environment"$json$::jsonb),
  ('en', 'site.overview.environments.description', $json$"Your personal projects and each organization you belong to, in the period."$json$::jsonb),
  ('en', 'site.overview.chats', $json$"Recent chats"$json$::jsonb),
  ('en', 'site.overview.chats.empty', $json$"No chats yet. Start one in the JayV app."$json$::jsonb),
  ('en', 'site.overview.chats.untitled', $json$"Untitled chat"$json$::jsonb),
  ('en', 'site.overview.system.accounts', $json$"Accounts"$json$::jsonb),
  ('en', 'site.overview.system.accounts.hint', $json$"{count} new in the period"$json$::jsonb),
  ('en', 'site.overview.system.active', $json$"Using the app"$json$::jsonb),
  ('en', 'site.overview.system.active.hint', $json$"{day} today · {week} in the last 7 days"$json$::jsonb),
  ('en', 'site.overview.system.signIns', $json$"Sign-ins"$json$::jsonb),
  ('en', 'site.overview.system.signIns.hint', $json$"{users} accounts signed in · {open} open sessions"$json$::jsonb),
  ('en', 'site.overview.system.sessionsNote', $json$"Sign-ins count the sessions still on record: signing out removes a session."$json$::jsonb),
  ('en', 'site.overview.system.access', $json$"Accounts and access"$json$::jsonb),
  ('en', 'site.overview.system.confirmed', $json$"E-mail confirmed"$json$::jsonb),
  ('en', 'site.overview.system.mfa', $json$"Two-factor on"$json$::jsonb),
  ('en', 'site.overview.system.banned', $json$"Blocked"$json$::jsonb),
  ('en', 'site.overview.system.admins', $json$"Admins"$json$::jsonb),
  ('en', 'site.overview.system.signedInDay', $json$"Signed in today"$json$::jsonb),
  ('en', 'site.overview.system.signedInWeek', $json$"Signed in in the last 7 days"$json$::jsonb),
  ('en', 'site.overview.system.activity', $json$"Projects and chats"$json$::jsonb),
  ('en', 'site.overview.system.chatsNew', $json$"New chats in the period"$json$::jsonb),
  ('en', 'site.overview.system.messages', $json$"Messages in the period"$json$::jsonb),
  ('en', 'site.overview.system.orgRequests', $json$"Requests in organizations"$json$::jsonb),
  ('en', 'site.overview.system.failures', $json$"Failed model calls"$json$::jsonb),
  ('en', 'site.overview.system.topUsers', $json$"Who used it most"$json$::jsonb),
  ('en', 'site.overview.system.topUsers.empty', $json$"Nobody used the app in this period."$json$::jsonb),
  ('en', 'site.overview.system.plans', $json$"Plans"$json$::jsonb),
  ('en', 'site.overview.system.plans.users', $json${"one": "{count} account", "other": "{count} accounts"}$json$::jsonb),
  ('en', 'site.overview.system.organizations', $json$"Organizations and Jev"$json$::jsonb),
  ('en', 'site.overview.system.members', $json$"Members"$json$::jsonb),
  ('en', 'site.overview.system.repositories', $json$"Repositories"$json$::jsonb),
  ('en', 'site.overview.system.jevCalls', $json$"Jev calls in the period"$json$::jsonb),
  ('en', 'site.overview.system.jevUsers', $json$"Accounts that used Jev"$json$::jsonb),
  ('en', 'site.overview.system.recent', $json$"Newest accounts"$json$::jsonb),
  ('en', 'site.overview.system.joined', $json$"Joined {date}"$json$::jsonb),
  ('en', 'site.overview.system.never', $json$"Never signed in"$json$::jsonb),
  ('en', 'site.overview.system.seen', $json$"Last sign-in {date}"$json$::jsonb),
  ('es', 'site.overview.description.me', $json$"Cómo has estado usando JayV: solicitudes, tokens, costo y adónde fueron."$json$::jsonb),
  ('es', 'site.overview.description.system', $json$"Cómo se está usando JayV en todas las cuentas: quién entra, qué pide y cuánto cuesta."$json$::jsonb),
  ('es', 'site.overview.view', $json$"Vista"$json$::jsonb),
  ('es', 'site.overview.view.me', $json$"Mi uso"$json$::jsonb),
  ('es', 'site.overview.view.system', $json$"Sistema"$json$::jsonb),
  ('es', 'site.overview.period', $json$"Período"$json$::jsonb),
  ('es', 'site.overview.period.days', $json${"one": "{count} día", "other": "{count} días"}$json$::jsonb),
  ('es', 'site.overview.since', $json$"Desde el {date} · días en {zone}"$json$::jsonb),
  ('es', 'site.overview.failed', $json$"No se pudo cargar el panel. Vuelve a intentarlo en un momento."$json$::jsonb),
  ('es', 'site.overview.requests', $json$"Solicitudes"$json$::jsonb),
  ('es', 'site.overview.requests.hint', $json$"{answered} respondidas · {failed} fallidas · {blocked} detenidas en la portería"$json$::jsonb),
  ('es', 'site.overview.tokens', $json$"Tokens"$json$::jsonb),
  ('es', 'site.overview.tokens.hint', $json$"{input} de entrada · {output} de salida · {cache} de la caché"$json$::jsonb),
  ('es', 'site.overview.tokens.cache', $json$"{cache} más de la caché"$json$::jsonb),
  ('es', 'site.overview.cost', $json$"Costo"$json$::jsonb),
  ('es', 'site.overview.cost.hint', $json$"{calls} llamadas a modelos, {jev} de Jev"$json$::jsonb),
  ('es', 'site.overview.jev', $json$"Jev hoy"$json$::jsonb),
  ('es', 'site.overview.jev.limit', $json$"de {limit} llamadas al día en tu plan"$json$::jsonb),
  ('es', 'site.overview.jev.unlimited', $json$"Sin límite diario en tu plan"$json$::jsonb),
  ('es', 'site.overview.chart.requests', $json$"Solicitudes por día"$json$::jsonb),
  ('es', 'site.overview.chart.tokens', $json$"Tokens por día"$json$::jsonb),
  ('es', 'site.overview.chart.sessions', $json$"Accesos por día"$json$::jsonb),
  ('es', 'site.overview.chart.active', $json$"Cuentas que usan la app por día"$json$::jsonb),
  ('es', 'site.overview.chart.signups', $json$"Cuentas nuevas por día"$json$::jsonb),
  ('es', 'site.overview.chart.total', $json$"{total} en el período"$json$::jsonb),
  ('es', 'site.overview.chart.peak', $json$"Máximo {value}"$json$::jsonb),
  ('es', 'site.overview.chart.table', $json$"Ver como tabla"$json$::jsonb),
  ('es', 'site.overview.column.day', $json$"Día"$json$::jsonb),
  ('es', 'site.overview.column.model', $json$"Modelo"$json$::jsonb),
  ('es', 'site.overview.column.calls', $json$"Llamadas"$json$::jsonb),
  ('es', 'site.overview.column.tokens', $json$"Tokens"$json$::jsonb),
  ('es', 'site.overview.column.cost', $json$"Costo"$json$::jsonb),
  ('es', 'site.overview.column.requests', $json$"Solicitudes"$json$::jsonb),
  ('es', 'site.overview.column.account', $json$"Cuenta"$json$::jsonb),
  ('es', 'site.overview.column.lastSignIn', $json$"Último acceso"$json$::jsonb),
  ('es', 'site.overview.column.environment', $json$"Entorno"$json$::jsonb),
  ('es', 'site.overview.label.projects', $json$"Proyectos"$json$::jsonb),
  ('es', 'site.overview.label.chats', $json$"Chats"$json$::jsonb),
  ('es', 'site.overview.label.requests', $json$"Solicitudes"$json$::jsonb),
  ('es', 'site.overview.label.organizations', $json$"Organizaciones"$json$::jsonb),
  ('es', 'site.overview.label.devices', $json$"Computadoras en el período"$json$::jsonb),
  ('es', 'site.overview.label.avgCall', $json$"Llamada media a un modelo"$json$::jsonb),
  ('es', 'site.overview.seconds', $json$"{value} s"$json$::jsonb),
  ('es', 'site.overview.totals', $json$"Desde el inicio"$json$::jsonb),
  ('es', 'site.overview.models', $json$"Modelos"$json$::jsonb),
  ('es', 'site.overview.models.empty', $json$"No hay llamadas a modelos en este período."$json$::jsonb),
  ('es', 'site.overview.environments', $json$"Por entorno"$json$::jsonb),
  ('es', 'site.overview.environments.description', $json$"Tus proyectos personales y cada organización a la que perteneces, en el período."$json$::jsonb),
  ('es', 'site.overview.chats', $json$"Chats recientes"$json$::jsonb),
  ('es', 'site.overview.chats.empty', $json$"Todavía no hay chats. Empieza uno en la app JayV."$json$::jsonb),
  ('es', 'site.overview.chats.untitled', $json$"Chat sin título"$json$::jsonb),
  ('es', 'site.overview.system.accounts', $json$"Cuentas"$json$::jsonb),
  ('es', 'site.overview.system.accounts.hint', $json$"{count} nuevas en el período"$json$::jsonb),
  ('es', 'site.overview.system.active', $json$"Usando la app"$json$::jsonb),
  ('es', 'site.overview.system.active.hint', $json$"{day} hoy · {week} en los últimos 7 días"$json$::jsonb),
  ('es', 'site.overview.system.signIns', $json$"Accesos"$json$::jsonb),
  ('es', 'site.overview.system.signIns.hint', $json$"{users} cuentas entraron · {open} sesiones abiertas"$json$::jsonb),
  ('es', 'site.overview.system.sessionsNote', $json$"Los accesos cuentan las sesiones que siguen registradas: cerrar sesión la borra."$json$::jsonb),
  ('es', 'site.overview.system.access', $json$"Cuentas y acceso"$json$::jsonb),
  ('es', 'site.overview.system.confirmed', $json$"Correo confirmado"$json$::jsonb),
  ('es', 'site.overview.system.mfa', $json$"Con dos pasos"$json$::jsonb),
  ('es', 'site.overview.system.banned', $json$"Bloqueadas"$json$::jsonb),
  ('es', 'site.overview.system.admins', $json$"Administradores"$json$::jsonb),
  ('es', 'site.overview.system.signedInDay', $json$"Entraron hoy"$json$::jsonb),
  ('es', 'site.overview.system.signedInWeek', $json$"Entraron en los últimos 7 días"$json$::jsonb),
  ('es', 'site.overview.system.activity', $json$"Proyectos y chats"$json$::jsonb),
  ('es', 'site.overview.system.chatsNew', $json$"Chats nuevos en el período"$json$::jsonb),
  ('es', 'site.overview.system.messages', $json$"Mensajes en el período"$json$::jsonb),
  ('es', 'site.overview.system.orgRequests', $json$"Solicitudes en organizaciones"$json$::jsonb),
  ('es', 'site.overview.system.failures', $json$"Llamadas a modelos fallidas"$json$::jsonb),
  ('es', 'site.overview.system.topUsers', $json$"Quién más lo usó"$json$::jsonb),
  ('es', 'site.overview.system.topUsers.empty', $json$"Nadie usó la app en este período."$json$::jsonb),
  ('es', 'site.overview.system.plans', $json$"Planes"$json$::jsonb),
  ('es', 'site.overview.system.plans.users', $json${"one": "{count} cuenta", "other": "{count} cuentas"}$json$::jsonb),
  ('es', 'site.overview.system.organizations', $json$"Organizaciones y Jev"$json$::jsonb),
  ('es', 'site.overview.system.members', $json$"Miembros"$json$::jsonb),
  ('es', 'site.overview.system.repositories', $json$"Repositorios"$json$::jsonb),
  ('es', 'site.overview.system.jevCalls', $json$"Llamadas a Jev en el período"$json$::jsonb),
  ('es', 'site.overview.system.jevUsers', $json$"Cuentas que usaron Jev"$json$::jsonb),
  ('es', 'site.overview.system.recent', $json$"Cuentas más recientes"$json$::jsonb),
  ('es', 'site.overview.system.joined', $json$"Se unió el {date}"$json$::jsonb),
  ('es', 'site.overview.system.never', $json$"Nunca entró"$json$::jsonb),
  ('es', 'site.overview.system.seen', $json$"Último acceso el {date}"$json$::jsonb),
  ('zh-CN', 'site.overview.description.me', $json$"你使用 JayV 的情况：请求、令牌、费用以及它们的去向。"$json$::jsonb),
  ('zh-CN', 'site.overview.description.system', $json$"所有账户使用 JayV 的情况：谁在登录、提出了什么请求、花费多少。"$json$::jsonb),
  ('zh-CN', 'site.overview.view', $json$"视图"$json$::jsonb),
  ('zh-CN', 'site.overview.view.me', $json$"我的使用"$json$::jsonb),
  ('zh-CN', 'site.overview.view.system', $json$"系统"$json$::jsonb),
  ('zh-CN', 'site.overview.period', $json$"时间段"$json$::jsonb),
  ('zh-CN', 'site.overview.period.days', $json${"other": "{count} 天"}$json$::jsonb),
  ('zh-CN', 'site.overview.since', $json$"自 {date} 起 · 按 {zone} 划分日期"$json$::jsonb),
  ('zh-CN', 'site.overview.failed', $json$"无法加载控制台。请稍后再试。"$json$::jsonb),
  ('zh-CN', 'site.overview.requests', $json$"请求"$json$::jsonb),
  ('zh-CN', 'site.overview.requests.hint', $json$"{answered} 已回答 · {failed} 失败 · {blocked} 被门岗拦下"$json$::jsonb),
  ('zh-CN', 'site.overview.tokens', $json$"令牌"$json$::jsonb),
  ('zh-CN', 'site.overview.tokens.hint', $json$"输入 {input} · 输出 {output} · 缓存 {cache}"$json$::jsonb),
  ('zh-CN', 'site.overview.tokens.cache', $json$"另有 {cache} 来自缓存"$json$::jsonb),
  ('zh-CN', 'site.overview.cost', $json$"费用"$json$::jsonb),
  ('zh-CN', 'site.overview.cost.hint', $json$"{calls} 次模型调用，其中 {jev} 次来自 Jev"$json$::jsonb),
  ('zh-CN', 'site.overview.jev', $json$"今日的 Jev"$json$::jsonb),
  ('zh-CN', 'site.overview.jev.limit', $json$"套餐每天上限 {limit} 次"$json$::jsonb),
  ('zh-CN', 'site.overview.jev.unlimited', $json$"你的套餐没有每日上限"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.requests', $json$"每日请求"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.tokens', $json$"每日令牌"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.sessions', $json$"每日登录"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.active', $json$"每日使用应用的账户"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.signups', $json$"每日新账户"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.total', $json$"期间内共 {total}"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.peak', $json$"峰值 {value}"$json$::jsonb),
  ('zh-CN', 'site.overview.chart.table', $json$"以表格显示"$json$::jsonb),
  ('zh-CN', 'site.overview.column.day', $json$"日期"$json$::jsonb),
  ('zh-CN', 'site.overview.column.model', $json$"模型"$json$::jsonb),
  ('zh-CN', 'site.overview.column.calls', $json$"调用"$json$::jsonb),
  ('zh-CN', 'site.overview.column.tokens', $json$"令牌"$json$::jsonb),
  ('zh-CN', 'site.overview.column.cost', $json$"费用"$json$::jsonb),
  ('zh-CN', 'site.overview.column.requests', $json$"请求"$json$::jsonb),
  ('zh-CN', 'site.overview.column.account', $json$"账户"$json$::jsonb),
  ('zh-CN', 'site.overview.column.lastSignIn', $json$"最近登录"$json$::jsonb),
  ('zh-CN', 'site.overview.column.environment', $json$"环境"$json$::jsonb),
  ('zh-CN', 'site.overview.label.projects', $json$"项目"$json$::jsonb),
  ('zh-CN', 'site.overview.label.chats', $json$"聊天"$json$::jsonb),
  ('zh-CN', 'site.overview.label.requests', $json$"请求"$json$::jsonb),
  ('zh-CN', 'site.overview.label.organizations', $json$"组织"$json$::jsonb),
  ('zh-CN', 'site.overview.label.devices', $json$"期间内的电脑"$json$::jsonb),
  ('zh-CN', 'site.overview.label.avgCall', $json$"模型调用平均耗时"$json$::jsonb),
  ('zh-CN', 'site.overview.seconds', $json$"{value} 秒"$json$::jsonb),
  ('zh-CN', 'site.overview.totals', $json$"自开始以来"$json$::jsonb),
  ('zh-CN', 'site.overview.models', $json$"模型"$json$::jsonb),
  ('zh-CN', 'site.overview.models.empty', $json$"此期间没有模型调用。"$json$::jsonb),
  ('zh-CN', 'site.overview.environments', $json$"按环境"$json$::jsonb),
  ('zh-CN', 'site.overview.environments.description', $json$"期间内你的个人项目以及你所属的每个组织。"$json$::jsonb),
  ('zh-CN', 'site.overview.chats', $json$"最近的聊天"$json$::jsonb),
  ('zh-CN', 'site.overview.chats.empty', $json$"还没有聊天。在 JayV 应用中开始一个吧。"$json$::jsonb),
  ('zh-CN', 'site.overview.chats.untitled', $json$"未命名聊天"$json$::jsonb),
  ('zh-CN', 'site.overview.system.accounts', $json$"账户"$json$::jsonb),
  ('zh-CN', 'site.overview.system.accounts.hint', $json$"期间内新增 {count} 个"$json$::jsonb),
  ('zh-CN', 'site.overview.system.active', $json$"使用应用中"$json$::jsonb),
  ('zh-CN', 'site.overview.system.active.hint', $json$"今天 {day} · 最近 7 天 {week}"$json$::jsonb),
  ('zh-CN', 'site.overview.system.signIns', $json$"登录"$json$::jsonb),
  ('zh-CN', 'site.overview.system.signIns.hint', $json$"{users} 个账户登录过 · {open} 个活动会话"$json$::jsonb),
  ('zh-CN', 'site.overview.system.sessionsNote', $json$"登录次数统计的是仍有记录的会话：退出登录会删除会话。"$json$::jsonb),
  ('zh-CN', 'site.overview.system.access', $json$"账户与访问"$json$::jsonb),
  ('zh-CN', 'site.overview.system.confirmed', $json$"邮箱已确认"$json$::jsonb),
  ('zh-CN', 'site.overview.system.mfa', $json$"已开启两步验证"$json$::jsonb),
  ('zh-CN', 'site.overview.system.banned', $json$"已封禁"$json$::jsonb),
  ('zh-CN', 'site.overview.system.admins', $json$"管理员"$json$::jsonb),
  ('zh-CN', 'site.overview.system.signedInDay', $json$"今天登录过"$json$::jsonb),
  ('zh-CN', 'site.overview.system.signedInWeek', $json$"最近 7 天登录过"$json$::jsonb),
  ('zh-CN', 'site.overview.system.activity', $json$"项目与聊天"$json$::jsonb),
  ('zh-CN', 'site.overview.system.chatsNew', $json$"期间内新建的聊天"$json$::jsonb),
  ('zh-CN', 'site.overview.system.messages', $json$"期间内的消息"$json$::jsonb),
  ('zh-CN', 'site.overview.system.orgRequests', $json$"组织中的请求"$json$::jsonb),
  ('zh-CN', 'site.overview.system.failures', $json$"失败的模型调用"$json$::jsonb),
  ('zh-CN', 'site.overview.system.topUsers', $json$"使用最多的人"$json$::jsonb),
  ('zh-CN', 'site.overview.system.topUsers.empty', $json$"此期间没有人使用应用。"$json$::jsonb),
  ('zh-CN', 'site.overview.system.plans', $json$"套餐"$json$::jsonb),
  ('zh-CN', 'site.overview.system.plans.users', $json${"other": "{count} 个账户"}$json$::jsonb),
  ('zh-CN', 'site.overview.system.organizations', $json$"组织与 Jev"$json$::jsonb),
  ('zh-CN', 'site.overview.system.members', $json$"成员"$json$::jsonb),
  ('zh-CN', 'site.overview.system.repositories', $json$"仓库"$json$::jsonb),
  ('zh-CN', 'site.overview.system.jevCalls', $json$"期间内的 Jev 调用"$json$::jsonb),
  ('zh-CN', 'site.overview.system.jevUsers', $json$"使用过 Jev 的账户"$json$::jsonb),
  ('zh-CN', 'site.overview.system.recent', $json$"最新账户"$json$::jsonb),
  ('zh-CN', 'site.overview.system.joined', $json$"{date} 加入"$json$::jsonb),
  ('zh-CN', 'site.overview.system.never', $json$"从未登录"$json$::jsonb),
  ('zh-CN', 'site.overview.system.seen', $json$"最近登录于 {date}"$json$::jsonb),
  ('hi', 'site.overview.description.me', $json$"आप JayV का कैसे उपयोग कर रहे हैं: अनुरोध, टोकन, लागत और वे कहाँ गए।"$json$::jsonb),
  ('hi', 'site.overview.description.system', $json$"सभी खातों में JayV का उपयोग कैसे हो रहा है: कौन साइन इन करता है, क्या अनुरोध करता है और कितना खर्च होता है।"$json$::jsonb),
  ('hi', 'site.overview.view', $json$"दृश्य"$json$::jsonb),
  ('hi', 'site.overview.view.me', $json$"मेरा उपयोग"$json$::jsonb),
  ('hi', 'site.overview.view.system', $json$"सिस्टम"$json$::jsonb),
  ('hi', 'site.overview.period', $json$"अवधि"$json$::jsonb),
  ('hi', 'site.overview.period.days', $json${"one": "{count} दिन", "other": "{count} दिन"}$json$::jsonb),
  ('hi', 'site.overview.since', $json$"{date} से · दिन {zone} के अनुसार"$json$::jsonb),
  ('hi', 'site.overview.failed', $json$"डैशबोर्ड लोड नहीं हो सका। थोड़ी देर में फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'site.overview.requests', $json$"अनुरोध"$json$::jsonb),
  ('hi', 'site.overview.requests.hint', $json$"{answered} उत्तरित · {failed} विफल · {blocked} गेट पर रोके गए"$json$::jsonb),
  ('hi', 'site.overview.tokens', $json$"टोकन"$json$::jsonb),
  ('hi', 'site.overview.tokens.hint', $json$"{input} इनपुट · {output} आउटपुट · {cache} कैश से"$json$::jsonb),
  ('hi', 'site.overview.tokens.cache', $json$"{cache} और कैश से"$json$::jsonb),
  ('hi', 'site.overview.cost', $json$"लागत"$json$::jsonb),
  ('hi', 'site.overview.cost.hint', $json$"{calls} मॉडल कॉल, जिनमें {jev} Jev के"$json$::jsonb),
  ('hi', 'site.overview.jev', $json$"आज Jev"$json$::jsonb),
  ('hi', 'site.overview.jev.limit', $json$"आपके प्लान में प्रतिदिन {limit} कॉल में से"$json$::jsonb),
  ('hi', 'site.overview.jev.unlimited', $json$"आपके प्लान में कोई दैनिक सीमा नहीं"$json$::jsonb),
  ('hi', 'site.overview.chart.requests', $json$"प्रतिदिन अनुरोध"$json$::jsonb),
  ('hi', 'site.overview.chart.tokens', $json$"प्रतिदिन टोकन"$json$::jsonb),
  ('hi', 'site.overview.chart.sessions', $json$"प्रतिदिन साइन-इन"$json$::jsonb),
  ('hi', 'site.overview.chart.active', $json$"प्रतिदिन ऐप उपयोग करने वाले खाते"$json$::jsonb),
  ('hi', 'site.overview.chart.signups', $json$"प्रतिदिन नए खाते"$json$::jsonb),
  ('hi', 'site.overview.chart.total', $json$"अवधि में {total}"$json$::jsonb),
  ('hi', 'site.overview.chart.peak', $json$"शिखर {value}"$json$::jsonb),
  ('hi', 'site.overview.chart.table', $json$"तालिका के रूप में दिखाएँ"$json$::jsonb),
  ('hi', 'site.overview.column.day', $json$"दिन"$json$::jsonb),
  ('hi', 'site.overview.column.model', $json$"मॉडल"$json$::jsonb),
  ('hi', 'site.overview.column.calls', $json$"कॉल"$json$::jsonb),
  ('hi', 'site.overview.column.tokens', $json$"टोकन"$json$::jsonb),
  ('hi', 'site.overview.column.cost', $json$"लागत"$json$::jsonb),
  ('hi', 'site.overview.column.requests', $json$"अनुरोध"$json$::jsonb),
  ('hi', 'site.overview.column.account', $json$"खाता"$json$::jsonb),
  ('hi', 'site.overview.column.lastSignIn', $json$"अंतिम साइन-इन"$json$::jsonb),
  ('hi', 'site.overview.column.environment', $json$"परिवेश"$json$::jsonb),
  ('hi', 'site.overview.label.projects', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'site.overview.label.chats', $json$"चैट"$json$::jsonb),
  ('hi', 'site.overview.label.requests', $json$"अनुरोध"$json$::jsonb),
  ('hi', 'site.overview.label.organizations', $json$"संगठन"$json$::jsonb),
  ('hi', 'site.overview.label.devices', $json$"अवधि में कंप्यूटर"$json$::jsonb),
  ('hi', 'site.overview.label.avgCall', $json$"औसत मॉडल कॉल"$json$::jsonb),
  ('hi', 'site.overview.seconds', $json$"{value} से."$json$::jsonb),
  ('hi', 'site.overview.totals', $json$"शुरुआत से"$json$::jsonb),
  ('hi', 'site.overview.models', $json$"मॉडल"$json$::jsonb),
  ('hi', 'site.overview.models.empty', $json$"इस अवधि में कोई मॉडल कॉल नहीं।"$json$::jsonb),
  ('hi', 'site.overview.environments', $json$"परिवेश के अनुसार"$json$::jsonb),
  ('hi', 'site.overview.environments.description', $json$"अवधि में आपके व्यक्तिगत प्रोजेक्ट और हर वह संगठन जिसके आप सदस्य हैं।"$json$::jsonb),
  ('hi', 'site.overview.chats', $json$"हाल की चैट"$json$::jsonb),
  ('hi', 'site.overview.chats.empty', $json$"अभी कोई चैट नहीं। JayV ऐप में एक शुरू करें।"$json$::jsonb),
  ('hi', 'site.overview.chats.untitled', $json$"बिना शीर्षक की चैट"$json$::jsonb),
  ('hi', 'site.overview.system.accounts', $json$"खाते"$json$::jsonb),
  ('hi', 'site.overview.system.accounts.hint', $json$"अवधि में {count} नए"$json$::jsonb),
  ('hi', 'site.overview.system.active', $json$"ऐप का उपयोग कर रहे"$json$::jsonb),
  ('hi', 'site.overview.system.active.hint', $json$"आज {day} · पिछले 7 दिनों में {week}"$json$::jsonb),
  ('hi', 'site.overview.system.signIns', $json$"साइन-इन"$json$::jsonb),
  ('hi', 'site.overview.system.signIns.hint', $json$"{users} खातों ने साइन इन किया · {open} खुले सत्र"$json$::jsonb),
  ('hi', 'site.overview.system.sessionsNote', $json$"साइन-इन में वे सत्र गिने जाते हैं जो अब भी दर्ज हैं: साइन आउट करने पर सत्र हट जाता है।"$json$::jsonb),
  ('hi', 'site.overview.system.access', $json$"खाते और पहुँच"$json$::jsonb),
  ('hi', 'site.overview.system.confirmed', $json$"ईमेल की पुष्टि हुई"$json$::jsonb),
  ('hi', 'site.overview.system.mfa', $json$"दो-चरणीय चालू"$json$::jsonb),
  ('hi', 'site.overview.system.banned', $json$"अवरुद्ध"$json$::jsonb),
  ('hi', 'site.overview.system.admins', $json$"एडमिन"$json$::jsonb),
  ('hi', 'site.overview.system.signedInDay', $json$"आज साइन इन किया"$json$::jsonb),
  ('hi', 'site.overview.system.signedInWeek', $json$"पिछले 7 दिनों में साइन इन किया"$json$::jsonb),
  ('hi', 'site.overview.system.activity', $json$"प्रोजेक्ट और चैट"$json$::jsonb),
  ('hi', 'site.overview.system.chatsNew', $json$"अवधि में नई चैट"$json$::jsonb),
  ('hi', 'site.overview.system.messages', $json$"अवधि में संदेश"$json$::jsonb),
  ('hi', 'site.overview.system.orgRequests', $json$"संगठनों में अनुरोध"$json$::jsonb),
  ('hi', 'site.overview.system.failures', $json$"विफल मॉडल कॉल"$json$::jsonb),
  ('hi', 'site.overview.system.topUsers', $json$"सबसे ज़्यादा किसने उपयोग किया"$json$::jsonb),
  ('hi', 'site.overview.system.topUsers.empty', $json$"इस अवधि में किसी ने ऐप का उपयोग नहीं किया।"$json$::jsonb),
  ('hi', 'site.overview.system.plans', $json$"प्लान"$json$::jsonb),
  ('hi', 'site.overview.system.plans.users', $json${"one": "{count} खाता", "other": "{count} खाते"}$json$::jsonb),
  ('hi', 'site.overview.system.organizations', $json$"संगठन और Jev"$json$::jsonb),
  ('hi', 'site.overview.system.members', $json$"सदस्य"$json$::jsonb),
  ('hi', 'site.overview.system.repositories', $json$"रिपॉज़िटरी"$json$::jsonb),
  ('hi', 'site.overview.system.jevCalls', $json$"अवधि में Jev कॉल"$json$::jsonb),
  ('hi', 'site.overview.system.jevUsers', $json$"Jev का उपयोग करने वाले खाते"$json$::jsonb),
  ('hi', 'site.overview.system.recent', $json$"सबसे नए खाते"$json$::jsonb),
  ('hi', 'site.overview.system.joined', $json$"{date} को जुड़े"$json$::jsonb),
  ('hi', 'site.overview.system.never', $json$"कभी साइन इन नहीं किया"$json$::jsonb),
  ('hi', 'site.overview.system.seen', $json$"अंतिम साइन-इन {date}"$json$::jsonb),
  ('ar', 'site.overview.description.me', $json$"كيف تستخدم JayV: الطلبات والرموز والتكلفة وأين ذهبت."$json$::jsonb),
  ('ar', 'site.overview.description.system', $json$"كيف يُستخدم JayV في كل الحسابات: من يسجّل الدخول، وماذا يطلب، وكم يكلّف."$json$::jsonb),
  ('ar', 'site.overview.view', $json$"العرض"$json$::jsonb),
  ('ar', 'site.overview.view.me', $json$"استخدامي"$json$::jsonb),
  ('ar', 'site.overview.view.system', $json$"النظام"$json$::jsonb),
  ('ar', 'site.overview.period', $json$"الفترة"$json$::jsonb),
  ('ar', 'site.overview.period.days', $json${"zero": "{count} يوم", "one": "يوم واحد", "two": "يومان", "few": "{count} أيام", "many": "{count} يومًا", "other": "{count} يوم"}$json$::jsonb),
  ('ar', 'site.overview.since', $json$"منذ {date} · الأيام بتوقيت {zone}"$json$::jsonb),
  ('ar', 'site.overview.failed', $json$"تعذّر تحميل لوحة التحكم. حاول مرة أخرى بعد قليل."$json$::jsonb),
  ('ar', 'site.overview.requests', $json$"الطلبات"$json$::jsonb),
  ('ar', 'site.overview.requests.hint', $json$"{answered} أُجيب عنها · {failed} فشلت · {blocked} أُوقفت عند البوابة"$json$::jsonb),
  ('ar', 'site.overview.tokens', $json$"الرموز"$json$::jsonb),
  ('ar', 'site.overview.tokens.hint', $json$"{input} إدخال · {output} إخراج · {cache} من الذاكرة المؤقتة"$json$::jsonb),
  ('ar', 'site.overview.tokens.cache', $json$"و{cache} إضافية من الذاكرة المؤقتة"$json$::jsonb),
  ('ar', 'site.overview.cost', $json$"التكلفة"$json$::jsonb),
  ('ar', 'site.overview.cost.hint', $json$"{calls} استدعاء للنماذج، منها {jev} من Jev"$json$::jsonb),
  ('ar', 'site.overview.jev', $json$"Jev اليوم"$json$::jsonb),
  ('ar', 'site.overview.jev.limit', $json$"من {limit} استدعاء يوميًا في خطتك"$json$::jsonb),
  ('ar', 'site.overview.jev.unlimited', $json$"لا حد يومي في خطتك"$json$::jsonb),
  ('ar', 'site.overview.chart.requests', $json$"الطلبات يوميًا"$json$::jsonb),
  ('ar', 'site.overview.chart.tokens', $json$"الرموز يوميًا"$json$::jsonb),
  ('ar', 'site.overview.chart.sessions', $json$"تسجيلات الدخول يوميًا"$json$::jsonb),
  ('ar', 'site.overview.chart.active', $json$"الحسابات التي تستخدم التطبيق يوميًا"$json$::jsonb),
  ('ar', 'site.overview.chart.signups', $json$"الحسابات الجديدة يوميًا"$json$::jsonb),
  ('ar', 'site.overview.chart.total', $json$"{total} خلال الفترة"$json$::jsonb),
  ('ar', 'site.overview.chart.peak', $json$"الذروة {value}"$json$::jsonb),
  ('ar', 'site.overview.chart.table', $json$"العرض كجدول"$json$::jsonb),
  ('ar', 'site.overview.column.day', $json$"اليوم"$json$::jsonb),
  ('ar', 'site.overview.column.model', $json$"النموذج"$json$::jsonb),
  ('ar', 'site.overview.column.calls', $json$"الاستدعاءات"$json$::jsonb),
  ('ar', 'site.overview.column.tokens', $json$"الرموز"$json$::jsonb),
  ('ar', 'site.overview.column.cost', $json$"التكلفة"$json$::jsonb),
  ('ar', 'site.overview.column.requests', $json$"الطلبات"$json$::jsonb),
  ('ar', 'site.overview.column.account', $json$"الحساب"$json$::jsonb),
  ('ar', 'site.overview.column.lastSignIn', $json$"آخر تسجيل دخول"$json$::jsonb),
  ('ar', 'site.overview.column.environment', $json$"البيئة"$json$::jsonb),
  ('ar', 'site.overview.label.projects', $json$"المشاريع"$json$::jsonb),
  ('ar', 'site.overview.label.chats', $json$"المحادثات"$json$::jsonb),
  ('ar', 'site.overview.label.requests', $json$"الطلبات"$json$::jsonb),
  ('ar', 'site.overview.label.organizations', $json$"المؤسسات"$json$::jsonb),
  ('ar', 'site.overview.label.devices', $json$"الحواسيب خلال الفترة"$json$::jsonb),
  ('ar', 'site.overview.label.avgCall', $json$"متوسط استدعاء النموذج"$json$::jsonb),
  ('ar', 'site.overview.seconds', $json$"{value} ث"$json$::jsonb),
  ('ar', 'site.overview.totals', $json$"منذ البداية"$json$::jsonb),
  ('ar', 'site.overview.models', $json$"النماذج"$json$::jsonb),
  ('ar', 'site.overview.models.empty', $json$"لا توجد استدعاءات للنماذج في هذه الفترة."$json$::jsonb),
  ('ar', 'site.overview.environments', $json$"حسب البيئة"$json$::jsonb),
  ('ar', 'site.overview.environments.description', $json$"مشاريعك الشخصية وكل مؤسسة تنتمي إليها، خلال الفترة."$json$::jsonb),
  ('ar', 'site.overview.chats', $json$"المحادثات الأخيرة"$json$::jsonb),
  ('ar', 'site.overview.chats.empty', $json$"لا توجد محادثات بعد. ابدأ واحدة في تطبيق JayV."$json$::jsonb),
  ('ar', 'site.overview.chats.untitled', $json$"محادثة بلا عنوان"$json$::jsonb),
  ('ar', 'site.overview.system.accounts', $json$"الحسابات"$json$::jsonb),
  ('ar', 'site.overview.system.accounts.hint', $json$"{count} جديدة خلال الفترة"$json$::jsonb),
  ('ar', 'site.overview.system.active', $json$"يستخدمون التطبيق"$json$::jsonb),
  ('ar', 'site.overview.system.active.hint', $json$"{day} اليوم · {week} خلال آخر 7 أيام"$json$::jsonb),
  ('ar', 'site.overview.system.signIns', $json$"تسجيلات الدخول"$json$::jsonb),
  ('ar', 'site.overview.system.signIns.hint', $json$"{users} حسابات سجّلت الدخول · {open} جلسات مفتوحة"$json$::jsonb),
  ('ar', 'site.overview.system.sessionsNote', $json$"تحسب تسجيلات الدخول الجلسات التي ما زالت مسجّلة: تسجيل الخروج يحذف الجلسة."$json$::jsonb),
  ('ar', 'site.overview.system.access', $json$"الحسابات والوصول"$json$::jsonb),
  ('ar', 'site.overview.system.confirmed', $json$"البريد مؤكَّد"$json$::jsonb),
  ('ar', 'site.overview.system.mfa', $json$"التحقق بخطوتين مفعّل"$json$::jsonb),
  ('ar', 'site.overview.system.banned', $json$"محظورة"$json$::jsonb),
  ('ar', 'site.overview.system.admins', $json$"المشرفون"$json$::jsonb),
  ('ar', 'site.overview.system.signedInDay', $json$"سجّلوا الدخول اليوم"$json$::jsonb),
  ('ar', 'site.overview.system.signedInWeek', $json$"سجّلوا الدخول خلال آخر 7 أيام"$json$::jsonb),
  ('ar', 'site.overview.system.activity', $json$"المشاريع والمحادثات"$json$::jsonb),
  ('ar', 'site.overview.system.chatsNew', $json$"محادثات جديدة خلال الفترة"$json$::jsonb),
  ('ar', 'site.overview.system.messages', $json$"الرسائل خلال الفترة"$json$::jsonb),
  ('ar', 'site.overview.system.orgRequests', $json$"الطلبات في المؤسسات"$json$::jsonb),
  ('ar', 'site.overview.system.failures', $json$"استدعاءات النماذج الفاشلة"$json$::jsonb),
  ('ar', 'site.overview.system.topUsers', $json$"الأكثر استخدامًا"$json$::jsonb),
  ('ar', 'site.overview.system.topUsers.empty', $json$"لم يستخدم أحد التطبيق في هذه الفترة."$json$::jsonb),
  ('ar', 'site.overview.system.plans', $json$"الخطط"$json$::jsonb),
  ('ar', 'site.overview.system.plans.users', $json${"zero": "لا حسابات", "one": "حساب واحد", "two": "حسابان", "few": "{count} حسابات", "many": "{count} حسابًا", "other": "{count} حساب"}$json$::jsonb),
  ('ar', 'site.overview.system.organizations', $json$"المؤسسات وJev"$json$::jsonb),
  ('ar', 'site.overview.system.members', $json$"الأعضاء"$json$::jsonb),
  ('ar', 'site.overview.system.repositories', $json$"المستودعات"$json$::jsonb),
  ('ar', 'site.overview.system.jevCalls', $json$"استدعاءات Jev خلال الفترة"$json$::jsonb),
  ('ar', 'site.overview.system.jevUsers', $json$"الحسابات التي استخدمت Jev"$json$::jsonb),
  ('ar', 'site.overview.system.recent', $json$"أحدث الحسابات"$json$::jsonb),
  ('ar', 'site.overview.system.joined', $json$"انضم في {date}"$json$::jsonb),
  ('ar', 'site.overview.system.never', $json$"لم يسجّل الدخول قط"$json$::jsonb),
  ('ar', 'site.overview.system.seen', $json$"آخر تسجيل دخول {date}"$json$::jsonb),
  ('fr', 'site.overview.description.me', $json$"Comment vous utilisez JayV : demandes, jetons, coût et où ils sont allés."$json$::jsonb),
  ('fr', 'site.overview.description.system', $json$"Comment JayV est utilisé sur tous les comptes : qui se connecte, ce qui est demandé et ce que cela coûte."$json$::jsonb),
  ('fr', 'site.overview.view', $json$"Vue"$json$::jsonb),
  ('fr', 'site.overview.view.me', $json$"Mon utilisation"$json$::jsonb),
  ('fr', 'site.overview.view.system', $json$"Système"$json$::jsonb),
  ('fr', 'site.overview.period', $json$"Période"$json$::jsonb),
  ('fr', 'site.overview.period.days', $json${"one": "{count} jour", "other": "{count} jours"}$json$::jsonb),
  ('fr', 'site.overview.since', $json$"Depuis le {date} · jours en {zone}"$json$::jsonb),
  ('fr', 'site.overview.failed', $json$"Impossible de charger le tableau de bord. Réessayez dans un instant."$json$::jsonb),
  ('fr', 'site.overview.requests', $json$"Demandes"$json$::jsonb),
  ('fr', 'site.overview.requests.hint', $json$"{answered} répondues · {failed} en échec · {blocked} arrêtées à la loge"$json$::jsonb),
  ('fr', 'site.overview.tokens', $json$"Jetons"$json$::jsonb),
  ('fr', 'site.overview.tokens.hint', $json$"{input} en entrée · {output} en sortie · {cache} depuis le cache"$json$::jsonb),
  ('fr', 'site.overview.tokens.cache', $json$"{cache} de plus depuis le cache"$json$::jsonb),
  ('fr', 'site.overview.cost', $json$"Coût"$json$::jsonb),
  ('fr', 'site.overview.cost.hint', $json$"{calls} appels aux modèles, dont {jev} par Jev"$json$::jsonb),
  ('fr', 'site.overview.jev', $json$"Jev aujourd'hui"$json$::jsonb),
  ('fr', 'site.overview.jev.limit', $json$"sur {limit} appels par jour dans votre forfait"$json$::jsonb),
  ('fr', 'site.overview.jev.unlimited', $json$"Pas de limite quotidienne dans votre forfait"$json$::jsonb),
  ('fr', 'site.overview.chart.requests', $json$"Demandes par jour"$json$::jsonb),
  ('fr', 'site.overview.chart.tokens', $json$"Jetons par jour"$json$::jsonb),
  ('fr', 'site.overview.chart.sessions', $json$"Connexions par jour"$json$::jsonb),
  ('fr', 'site.overview.chart.active', $json$"Comptes utilisant l'application par jour"$json$::jsonb),
  ('fr', 'site.overview.chart.signups', $json$"Nouveaux comptes par jour"$json$::jsonb),
  ('fr', 'site.overview.chart.total', $json$"{total} sur la période"$json$::jsonb),
  ('fr', 'site.overview.chart.peak', $json$"Pic {value}"$json$::jsonb),
  ('fr', 'site.overview.chart.table', $json$"Afficher en tableau"$json$::jsonb),
  ('fr', 'site.overview.column.day', $json$"Jour"$json$::jsonb),
  ('fr', 'site.overview.column.model', $json$"Modèle"$json$::jsonb),
  ('fr', 'site.overview.column.calls', $json$"Appels"$json$::jsonb),
  ('fr', 'site.overview.column.tokens', $json$"Jetons"$json$::jsonb),
  ('fr', 'site.overview.column.cost', $json$"Coût"$json$::jsonb),
  ('fr', 'site.overview.column.requests', $json$"Demandes"$json$::jsonb),
  ('fr', 'site.overview.column.account', $json$"Compte"$json$::jsonb),
  ('fr', 'site.overview.column.lastSignIn', $json$"Dernière connexion"$json$::jsonb),
  ('fr', 'site.overview.column.environment', $json$"Environnement"$json$::jsonb),
  ('fr', 'site.overview.label.projects', $json$"Projets"$json$::jsonb),
  ('fr', 'site.overview.label.chats', $json$"Chats"$json$::jsonb),
  ('fr', 'site.overview.label.requests', $json$"Demandes"$json$::jsonb),
  ('fr', 'site.overview.label.organizations', $json$"Organisations"$json$::jsonb),
  ('fr', 'site.overview.label.devices', $json$"Ordinateurs sur la période"$json$::jsonb),
  ('fr', 'site.overview.label.avgCall', $json$"Appel moyen à un modèle"$json$::jsonb),
  ('fr', 'site.overview.seconds', $json$"{value} s"$json$::jsonb),
  ('fr', 'site.overview.totals', $json$"Depuis le début"$json$::jsonb),
  ('fr', 'site.overview.models', $json$"Modèles"$json$::jsonb),
  ('fr', 'site.overview.models.empty', $json$"Aucun appel aux modèles sur cette période."$json$::jsonb),
  ('fr', 'site.overview.environments', $json$"Par environnement"$json$::jsonb),
  ('fr', 'site.overview.environments.description', $json$"Vos projets personnels et chaque organisation dont vous êtes membre, sur la période."$json$::jsonb),
  ('fr', 'site.overview.chats', $json$"Chats récents"$json$::jsonb),
  ('fr', 'site.overview.chats.empty', $json$"Aucun chat pour l'instant. Lancez-en un dans l'application JayV."$json$::jsonb),
  ('fr', 'site.overview.chats.untitled', $json$"Chat sans titre"$json$::jsonb),
  ('fr', 'site.overview.system.accounts', $json$"Comptes"$json$::jsonb),
  ('fr', 'site.overview.system.accounts.hint', $json$"{count} nouveaux sur la période"$json$::jsonb),
  ('fr', 'site.overview.system.active', $json$"Utilisent l'application"$json$::jsonb),
  ('fr', 'site.overview.system.active.hint', $json$"{day} aujourd'hui · {week} sur les 7 derniers jours"$json$::jsonb),
  ('fr', 'site.overview.system.signIns', $json$"Connexions"$json$::jsonb),
  ('fr', 'site.overview.system.signIns.hint', $json$"{users} comptes se sont connectés · {open} sessions ouvertes"$json$::jsonb),
  ('fr', 'site.overview.system.sessionsNote', $json$"Les connexions comptent les sessions encore enregistrées : se déconnecter supprime la session."$json$::jsonb),
  ('fr', 'site.overview.system.access', $json$"Comptes et accès"$json$::jsonb),
  ('fr', 'site.overview.system.confirmed', $json$"E-mail confirmé"$json$::jsonb),
  ('fr', 'site.overview.system.mfa', $json$"Deux étapes activées"$json$::jsonb),
  ('fr', 'site.overview.system.banned', $json$"Bloqués"$json$::jsonb),
  ('fr', 'site.overview.system.admins', $json$"Admins"$json$::jsonb),
  ('fr', 'site.overview.system.signedInDay', $json$"Connectés aujourd'hui"$json$::jsonb),
  ('fr', 'site.overview.system.signedInWeek', $json$"Connectés sur les 7 derniers jours"$json$::jsonb),
  ('fr', 'site.overview.system.activity', $json$"Projets et chats"$json$::jsonb),
  ('fr', 'site.overview.system.chatsNew', $json$"Nouveaux chats sur la période"$json$::jsonb),
  ('fr', 'site.overview.system.messages', $json$"Messages sur la période"$json$::jsonb),
  ('fr', 'site.overview.system.orgRequests', $json$"Demandes dans les organisations"$json$::jsonb),
  ('fr', 'site.overview.system.failures', $json$"Appels aux modèles en échec"$json$::jsonb),
  ('fr', 'site.overview.system.topUsers', $json$"Qui l'a le plus utilisé"$json$::jsonb),
  ('fr', 'site.overview.system.topUsers.empty', $json$"Personne n'a utilisé l'application sur cette période."$json$::jsonb),
  ('fr', 'site.overview.system.plans', $json$"Forfaits"$json$::jsonb),
  ('fr', 'site.overview.system.plans.users', $json${"one": "{count} compte", "other": "{count} comptes"}$json$::jsonb),
  ('fr', 'site.overview.system.organizations', $json$"Organisations et Jev"$json$::jsonb),
  ('fr', 'site.overview.system.members', $json$"Membres"$json$::jsonb),
  ('fr', 'site.overview.system.repositories', $json$"Dépôts"$json$::jsonb),
  ('fr', 'site.overview.system.jevCalls', $json$"Appels à Jev sur la période"$json$::jsonb),
  ('fr', 'site.overview.system.jevUsers', $json$"Comptes ayant utilisé Jev"$json$::jsonb),
  ('fr', 'site.overview.system.recent', $json$"Comptes les plus récents"$json$::jsonb),
  ('fr', 'site.overview.system.joined', $json$"Inscrit le {date}"$json$::jsonb),
  ('fr', 'site.overview.system.never', $json$"Jamais connecté"$json$::jsonb),
  ('fr', 'site.overview.system.seen', $json$"Dernière connexion le {date}"$json$::jsonb),
  ('ru', 'site.overview.description.me', $json$"Как вы пользуетесь JayV: запросы, токены, стоимость и на что они ушли."$json$::jsonb),
  ('ru', 'site.overview.description.system', $json$"Как JayV используется во всех аккаунтах: кто входит, что спрашивает и сколько это стоит."$json$::jsonb),
  ('ru', 'site.overview.view', $json$"Вид"$json$::jsonb),
  ('ru', 'site.overview.view.me', $json$"Моё использование"$json$::jsonb),
  ('ru', 'site.overview.view.system', $json$"Система"$json$::jsonb),
  ('ru', 'site.overview.period', $json$"Период"$json$::jsonb),
  ('ru', 'site.overview.period.days', $json${"one": "{count} день", "few": "{count} дня", "many": "{count} дней", "other": "{count} дня"}$json$::jsonb),
  ('ru', 'site.overview.since', $json$"С {date} · дни по {zone}"$json$::jsonb),
  ('ru', 'site.overview.failed', $json$"Не удалось загрузить панель. Попробуйте ещё раз чуть позже."$json$::jsonb),
  ('ru', 'site.overview.requests', $json$"Запросы"$json$::jsonb),
  ('ru', 'site.overview.requests.hint', $json$"{answered} с ответом · {failed} с ошибкой · {blocked} остановлены на проходной"$json$::jsonb),
  ('ru', 'site.overview.tokens', $json$"Токены"$json$::jsonb),
  ('ru', 'site.overview.tokens.hint', $json$"{input} на входе · {output} на выходе · {cache} из кэша"$json$::jsonb),
  ('ru', 'site.overview.tokens.cache', $json$"ещё {cache} из кэша"$json$::jsonb),
  ('ru', 'site.overview.cost', $json$"Стоимость"$json$::jsonb),
  ('ru', 'site.overview.cost.hint', $json$"{calls} вызовов моделей, из них {jev} от Jev"$json$::jsonb),
  ('ru', 'site.overview.jev', $json$"Jev сегодня"$json$::jsonb),
  ('ru', 'site.overview.jev.limit', $json$"из {limit} вызовов в день по вашему тарифу"$json$::jsonb),
  ('ru', 'site.overview.jev.unlimited', $json$"Без дневного лимита по вашему тарифу"$json$::jsonb),
  ('ru', 'site.overview.chart.requests', $json$"Запросы по дням"$json$::jsonb),
  ('ru', 'site.overview.chart.tokens', $json$"Токены по дням"$json$::jsonb),
  ('ru', 'site.overview.chart.sessions', $json$"Входы по дням"$json$::jsonb),
  ('ru', 'site.overview.chart.active', $json$"Аккаунты, пользующиеся приложением, по дням"$json$::jsonb),
  ('ru', 'site.overview.chart.signups', $json$"Новые аккаунты по дням"$json$::jsonb),
  ('ru', 'site.overview.chart.total', $json$"{total} за период"$json$::jsonb),
  ('ru', 'site.overview.chart.peak', $json$"Пик {value}"$json$::jsonb),
  ('ru', 'site.overview.chart.table', $json$"Показать таблицей"$json$::jsonb),
  ('ru', 'site.overview.column.day', $json$"День"$json$::jsonb),
  ('ru', 'site.overview.column.model', $json$"Модель"$json$::jsonb),
  ('ru', 'site.overview.column.calls', $json$"Вызовы"$json$::jsonb),
  ('ru', 'site.overview.column.tokens', $json$"Токены"$json$::jsonb),
  ('ru', 'site.overview.column.cost', $json$"Стоимость"$json$::jsonb),
  ('ru', 'site.overview.column.requests', $json$"Запросы"$json$::jsonb),
  ('ru', 'site.overview.column.account', $json$"Аккаунт"$json$::jsonb),
  ('ru', 'site.overview.column.lastSignIn', $json$"Последний вход"$json$::jsonb),
  ('ru', 'site.overview.column.environment', $json$"Среда"$json$::jsonb),
  ('ru', 'site.overview.label.projects', $json$"Проекты"$json$::jsonb),
  ('ru', 'site.overview.label.chats', $json$"Чаты"$json$::jsonb),
  ('ru', 'site.overview.label.requests', $json$"Запросы"$json$::jsonb),
  ('ru', 'site.overview.label.organizations', $json$"Организации"$json$::jsonb),
  ('ru', 'site.overview.label.devices', $json$"Компьютеры за период"$json$::jsonb),
  ('ru', 'site.overview.label.avgCall', $json$"Средний вызов модели"$json$::jsonb),
  ('ru', 'site.overview.seconds', $json$"{value} с"$json$::jsonb),
  ('ru', 'site.overview.totals', $json$"С самого начала"$json$::jsonb),
  ('ru', 'site.overview.models', $json$"Модели"$json$::jsonb),
  ('ru', 'site.overview.models.empty', $json$"За этот период вызовов моделей нет."$json$::jsonb),
  ('ru', 'site.overview.environments', $json$"По средам"$json$::jsonb),
  ('ru', 'site.overview.environments.description', $json$"Ваши личные проекты и каждая организация, в которой вы состоите, за период."$json$::jsonb),
  ('ru', 'site.overview.chats', $json$"Недавние чаты"$json$::jsonb),
  ('ru', 'site.overview.chats.empty', $json$"Чатов пока нет. Начните чат в приложении JayV."$json$::jsonb),
  ('ru', 'site.overview.chats.untitled', $json$"Чат без названия"$json$::jsonb),
  ('ru', 'site.overview.system.accounts', $json$"Аккаунты"$json$::jsonb),
  ('ru', 'site.overview.system.accounts.hint', $json$"{count} новых за период"$json$::jsonb),
  ('ru', 'site.overview.system.active', $json$"Пользуются приложением"$json$::jsonb),
  ('ru', 'site.overview.system.active.hint', $json$"{day} сегодня · {week} за последние 7 дней"$json$::jsonb),
  ('ru', 'site.overview.system.signIns', $json$"Входы"$json$::jsonb),
  ('ru', 'site.overview.system.signIns.hint', $json$"Вошли {users} аккаунтов · {open} открытых сессий"$json$::jsonb),
  ('ru', 'site.overview.system.sessionsNote', $json$"Входы считают сессии, которые ещё хранятся: выход из аккаунта удаляет сессию."$json$::jsonb),
  ('ru', 'site.overview.system.access', $json$"Аккаунты и доступ"$json$::jsonb),
  ('ru', 'site.overview.system.confirmed', $json$"Почта подтверждена"$json$::jsonb),
  ('ru', 'site.overview.system.mfa', $json$"Двухэтапная проверка"$json$::jsonb),
  ('ru', 'site.overview.system.banned', $json$"Заблокированы"$json$::jsonb),
  ('ru', 'site.overview.system.admins', $json$"Администраторы"$json$::jsonb),
  ('ru', 'site.overview.system.signedInDay', $json$"Вошли сегодня"$json$::jsonb),
  ('ru', 'site.overview.system.signedInWeek', $json$"Входили за последние 7 дней"$json$::jsonb),
  ('ru', 'site.overview.system.activity', $json$"Проекты и чаты"$json$::jsonb),
  ('ru', 'site.overview.system.chatsNew', $json$"Новые чаты за период"$json$::jsonb),
  ('ru', 'site.overview.system.messages', $json$"Сообщения за период"$json$::jsonb),
  ('ru', 'site.overview.system.orgRequests', $json$"Запросы в организациях"$json$::jsonb),
  ('ru', 'site.overview.system.failures', $json$"Неудачные вызовы моделей"$json$::jsonb),
  ('ru', 'site.overview.system.topUsers', $json$"Кто пользовался больше всех"$json$::jsonb),
  ('ru', 'site.overview.system.topUsers.empty', $json$"За этот период приложением никто не пользовался."$json$::jsonb),
  ('ru', 'site.overview.system.plans', $json$"Тарифы"$json$::jsonb),
  ('ru', 'site.overview.system.plans.users', $json${"one": "{count} аккаунт", "few": "{count} аккаунта", "many": "{count} аккаунтов", "other": "{count} аккаунта"}$json$::jsonb),
  ('ru', 'site.overview.system.organizations', $json$"Организации и Jev"$json$::jsonb),
  ('ru', 'site.overview.system.members', $json$"Участники"$json$::jsonb),
  ('ru', 'site.overview.system.repositories', $json$"Репозитории"$json$::jsonb),
  ('ru', 'site.overview.system.jevCalls', $json$"Вызовы Jev за период"$json$::jsonb),
  ('ru', 'site.overview.system.jevUsers', $json$"Аккаунты, использовавшие Jev"$json$::jsonb),
  ('ru', 'site.overview.system.recent', $json$"Новые аккаунты"$json$::jsonb),
  ('ru', 'site.overview.system.joined', $json$"Зарегистрирован {date}"$json$::jsonb),
  ('ru', 'site.overview.system.never', $json$"Ни разу не входил"$json$::jsonb),
  ('ru', 'site.overview.system.seen', $json$"Последний вход {date}"$json$::jsonb),
  ('ja', 'site.overview.description.me', $json$"JayV の使い方：リクエスト、トークン、コスト、そしてそれらの行き先。"$json$::jsonb),
  ('ja', 'site.overview.description.system', $json$"すべてのアカウントでの JayV の利用状況：誰がサインインし、何をリクエストし、いくらかかっているか。"$json$::jsonb),
  ('ja', 'site.overview.view', $json$"表示"$json$::jsonb),
  ('ja', 'site.overview.view.me', $json$"自分の利用"$json$::jsonb),
  ('ja', 'site.overview.view.system', $json$"システム"$json$::jsonb),
  ('ja', 'site.overview.period', $json$"期間"$json$::jsonb),
  ('ja', 'site.overview.period.days', $json${"other": "{count} 日間"}$json$::jsonb),
  ('ja', 'site.overview.since', $json$"{date} 以降 · 日付は {zone} 基準"$json$::jsonb),
  ('ja', 'site.overview.failed', $json$"ダッシュボードを読み込めませんでした。しばらくしてからもう一度お試しください。"$json$::jsonb),
  ('ja', 'site.overview.requests', $json$"リクエスト"$json$::jsonb),
  ('ja', 'site.overview.requests.hint', $json$"回答済み {answered} · 失敗 {failed} · ゲートで停止 {blocked}"$json$::jsonb),
  ('ja', 'site.overview.tokens', $json$"トークン"$json$::jsonb),
  ('ja', 'site.overview.tokens.hint', $json$"入力 {input} · 出力 {output} · キャッシュ {cache}"$json$::jsonb),
  ('ja', 'site.overview.tokens.cache', $json$"ほかにキャッシュから {cache}"$json$::jsonb),
  ('ja', 'site.overview.cost', $json$"コスト"$json$::jsonb),
  ('ja', 'site.overview.cost.hint', $json$"モデル呼び出し {calls} 回（うち Jev {jev} 回）"$json$::jsonb),
  ('ja', 'site.overview.jev', $json$"今日の Jev"$json$::jsonb),
  ('ja', 'site.overview.jev.limit', $json$"プランの上限は 1 日 {limit} 回"$json$::jsonb),
  ('ja', 'site.overview.jev.unlimited', $json$"プランに 1 日の上限はありません"$json$::jsonb),
  ('ja', 'site.overview.chart.requests', $json$"1 日あたりのリクエスト"$json$::jsonb),
  ('ja', 'site.overview.chart.tokens', $json$"1 日あたりのトークン"$json$::jsonb),
  ('ja', 'site.overview.chart.sessions', $json$"1 日あたりのサインイン"$json$::jsonb),
  ('ja', 'site.overview.chart.active', $json$"1 日あたりのアプリ利用アカウント"$json$::jsonb),
  ('ja', 'site.overview.chart.signups', $json$"1 日あたりの新規アカウント"$json$::jsonb),
  ('ja', 'site.overview.chart.total', $json$"期間中 {total}"$json$::jsonb),
  ('ja', 'site.overview.chart.peak', $json$"最大 {value}"$json$::jsonb),
  ('ja', 'site.overview.chart.table', $json$"表で表示"$json$::jsonb),
  ('ja', 'site.overview.column.day', $json$"日付"$json$::jsonb),
  ('ja', 'site.overview.column.model', $json$"モデル"$json$::jsonb),
  ('ja', 'site.overview.column.calls', $json$"呼び出し"$json$::jsonb),
  ('ja', 'site.overview.column.tokens', $json$"トークン"$json$::jsonb),
  ('ja', 'site.overview.column.cost', $json$"コスト"$json$::jsonb),
  ('ja', 'site.overview.column.requests', $json$"リクエスト"$json$::jsonb),
  ('ja', 'site.overview.column.account', $json$"アカウント"$json$::jsonb),
  ('ja', 'site.overview.column.lastSignIn', $json$"最終サインイン"$json$::jsonb),
  ('ja', 'site.overview.column.environment', $json$"環境"$json$::jsonb),
  ('ja', 'site.overview.label.projects', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'site.overview.label.chats', $json$"チャット"$json$::jsonb),
  ('ja', 'site.overview.label.requests', $json$"リクエスト"$json$::jsonb),
  ('ja', 'site.overview.label.organizations', $json$"組織"$json$::jsonb),
  ('ja', 'site.overview.label.devices', $json$"期間中のコンピューター"$json$::jsonb),
  ('ja', 'site.overview.label.avgCall', $json$"モデル呼び出しの平均時間"$json$::jsonb),
  ('ja', 'site.overview.seconds', $json$"{value} 秒"$json$::jsonb),
  ('ja', 'site.overview.totals', $json$"開始以来"$json$::jsonb),
  ('ja', 'site.overview.models', $json$"モデル"$json$::jsonb),
  ('ja', 'site.overview.models.empty', $json$"この期間にモデル呼び出しはありません。"$json$::jsonb),
  ('ja', 'site.overview.environments', $json$"環境別"$json$::jsonb),
  ('ja', 'site.overview.environments.description', $json$"期間中の個人プロジェクトと、所属する各組織。"$json$::jsonb),
  ('ja', 'site.overview.chats', $json$"最近のチャット"$json$::jsonb),
  ('ja', 'site.overview.chats.empty', $json$"まだチャットはありません。JayV アプリで始めましょう。"$json$::jsonb),
  ('ja', 'site.overview.chats.untitled', $json$"無題のチャット"$json$::jsonb),
  ('ja', 'site.overview.system.accounts', $json$"アカウント"$json$::jsonb),
  ('ja', 'site.overview.system.accounts.hint', $json$"期間中の新規 {count}"$json$::jsonb),
  ('ja', 'site.overview.system.active', $json$"アプリを利用中"$json$::jsonb),
  ('ja', 'site.overview.system.active.hint', $json$"今日 {day} · 過去 7 日間 {week}"$json$::jsonb),
  ('ja', 'site.overview.system.signIns', $json$"サインイン"$json$::jsonb),
  ('ja', 'site.overview.system.signIns.hint', $json$"サインインしたアカウント {users} · 開いているセッション {open}"$json$::jsonb),
  ('ja', 'site.overview.system.sessionsNote', $json$"サインイン数は記録が残っているセッションを数えます。サインアウトするとセッションは削除されます。"$json$::jsonb),
  ('ja', 'site.overview.system.access', $json$"アカウントとアクセス"$json$::jsonb),
  ('ja', 'site.overview.system.confirmed', $json$"メール確認済み"$json$::jsonb),
  ('ja', 'site.overview.system.mfa', $json$"2 段階認証オン"$json$::jsonb),
  ('ja', 'site.overview.system.banned', $json$"ブロック中"$json$::jsonb),
  ('ja', 'site.overview.system.admins', $json$"管理者"$json$::jsonb),
  ('ja', 'site.overview.system.signedInDay', $json$"今日サインイン"$json$::jsonb),
  ('ja', 'site.overview.system.signedInWeek', $json$"過去 7 日間にサインイン"$json$::jsonb),
  ('ja', 'site.overview.system.activity', $json$"プロジェクトとチャット"$json$::jsonb),
  ('ja', 'site.overview.system.chatsNew', $json$"期間中の新しいチャット"$json$::jsonb),
  ('ja', 'site.overview.system.messages', $json$"期間中のメッセージ"$json$::jsonb),
  ('ja', 'site.overview.system.orgRequests', $json$"組織でのリクエスト"$json$::jsonb),
  ('ja', 'site.overview.system.failures', $json$"失敗したモデル呼び出し"$json$::jsonb),
  ('ja', 'site.overview.system.topUsers', $json$"最もよく使ったアカウント"$json$::jsonb),
  ('ja', 'site.overview.system.topUsers.empty', $json$"この期間にアプリを使った人はいません。"$json$::jsonb),
  ('ja', 'site.overview.system.plans', $json$"プラン"$json$::jsonb),
  ('ja', 'site.overview.system.plans.users', $json${"other": "{count} アカウント"}$json$::jsonb),
  ('ja', 'site.overview.system.organizations', $json$"組織と Jev"$json$::jsonb),
  ('ja', 'site.overview.system.members', $json$"メンバー"$json$::jsonb),
  ('ja', 'site.overview.system.repositories', $json$"リポジトリ"$json$::jsonb),
  ('ja', 'site.overview.system.jevCalls', $json$"期間中の Jev 呼び出し"$json$::jsonb),
  ('ja', 'site.overview.system.jevUsers', $json$"Jev を使ったアカウント"$json$::jsonb),
  ('ja', 'site.overview.system.recent', $json$"最新のアカウント"$json$::jsonb),
  ('ja', 'site.overview.system.joined', $json$"{date} に登録"$json$::jsonb),
  ('ja', 'site.overview.system.never', $json$"サインイン履歴なし"$json$::jsonb),
  ('ja', 'site.overview.system.seen', $json$"最終サインイン {date}"$json$::jsonb),
  ('de', 'site.overview.description.me', $json$"Wie du JayV nutzt: Anfragen, Tokens, Kosten und wohin sie gegangen sind."$json$::jsonb),
  ('de', 'site.overview.description.system', $json$"Wie JayV über alle Konten hinweg genutzt wird: wer sich anmeldet, was angefragt wird und was es kostet."$json$::jsonb),
  ('de', 'site.overview.view', $json$"Ansicht"$json$::jsonb),
  ('de', 'site.overview.view.me', $json$"Meine Nutzung"$json$::jsonb),
  ('de', 'site.overview.view.system', $json$"System"$json$::jsonb),
  ('de', 'site.overview.period', $json$"Zeitraum"$json$::jsonb),
  ('de', 'site.overview.period.days', $json${"one": "{count} Tag", "other": "{count} Tage"}$json$::jsonb),
  ('de', 'site.overview.since', $json$"Seit {date} · Tage in {zone}"$json$::jsonb),
  ('de', 'site.overview.failed', $json$"Das Dashboard konnte nicht geladen werden. Versuche es gleich noch einmal."$json$::jsonb),
  ('de', 'site.overview.requests', $json$"Anfragen"$json$::jsonb),
  ('de', 'site.overview.requests.hint', $json$"{answered} beantwortet · {failed} fehlgeschlagen · {blocked} an der Pforte gestoppt"$json$::jsonb),
  ('de', 'site.overview.tokens', $json$"Tokens"$json$::jsonb),
  ('de', 'site.overview.tokens.hint', $json$"{input} Eingabe · {output} Ausgabe · {cache} aus dem Cache"$json$::jsonb),
  ('de', 'site.overview.tokens.cache', $json$"{cache} weitere aus dem Cache"$json$::jsonb),
  ('de', 'site.overview.cost', $json$"Kosten"$json$::jsonb),
  ('de', 'site.overview.cost.hint', $json$"{calls} Modellaufrufe, {jev} davon durch Jev"$json$::jsonb),
  ('de', 'site.overview.jev', $json$"Jev heute"$json$::jsonb),
  ('de', 'site.overview.jev.limit', $json$"von {limit} Aufrufen pro Tag in deinem Plan"$json$::jsonb),
  ('de', 'site.overview.jev.unlimited', $json$"Kein Tageslimit in deinem Plan"$json$::jsonb),
  ('de', 'site.overview.chart.requests', $json$"Anfragen pro Tag"$json$::jsonb),
  ('de', 'site.overview.chart.tokens', $json$"Tokens pro Tag"$json$::jsonb),
  ('de', 'site.overview.chart.sessions', $json$"Anmeldungen pro Tag"$json$::jsonb),
  ('de', 'site.overview.chart.active', $json$"Konten, die die App nutzen, pro Tag"$json$::jsonb),
  ('de', 'site.overview.chart.signups', $json$"Neue Konten pro Tag"$json$::jsonb),
  ('de', 'site.overview.chart.total', $json$"{total} im Zeitraum"$json$::jsonb),
  ('de', 'site.overview.chart.peak', $json$"Spitze {value}"$json$::jsonb),
  ('de', 'site.overview.chart.table', $json$"Als Tabelle anzeigen"$json$::jsonb),
  ('de', 'site.overview.column.day', $json$"Tag"$json$::jsonb),
  ('de', 'site.overview.column.model', $json$"Modell"$json$::jsonb),
  ('de', 'site.overview.column.calls', $json$"Aufrufe"$json$::jsonb),
  ('de', 'site.overview.column.tokens', $json$"Tokens"$json$::jsonb),
  ('de', 'site.overview.column.cost', $json$"Kosten"$json$::jsonb),
  ('de', 'site.overview.column.requests', $json$"Anfragen"$json$::jsonb),
  ('de', 'site.overview.column.account', $json$"Konto"$json$::jsonb),
  ('de', 'site.overview.column.lastSignIn', $json$"Letzte Anmeldung"$json$::jsonb),
  ('de', 'site.overview.column.environment', $json$"Umgebung"$json$::jsonb),
  ('de', 'site.overview.label.projects', $json$"Projekte"$json$::jsonb),
  ('de', 'site.overview.label.chats', $json$"Chats"$json$::jsonb),
  ('de', 'site.overview.label.requests', $json$"Anfragen"$json$::jsonb),
  ('de', 'site.overview.label.organizations', $json$"Organisationen"$json$::jsonb),
  ('de', 'site.overview.label.devices', $json$"Computer im Zeitraum"$json$::jsonb),
  ('de', 'site.overview.label.avgCall', $json$"Durchschnittlicher Modellaufruf"$json$::jsonb),
  ('de', 'site.overview.seconds', $json$"{value} s"$json$::jsonb),
  ('de', 'site.overview.totals', $json$"Seit Beginn"$json$::jsonb),
  ('de', 'site.overview.models', $json$"Modelle"$json$::jsonb),
  ('de', 'site.overview.models.empty', $json$"Keine Modellaufrufe in diesem Zeitraum."$json$::jsonb),
  ('de', 'site.overview.environments', $json$"Nach Umgebung"$json$::jsonb),
  ('de', 'site.overview.environments.description', $json$"Deine persönlichen Projekte und jede Organisation, der du angehörst, im Zeitraum."$json$::jsonb),
  ('de', 'site.overview.chats', $json$"Letzte Chats"$json$::jsonb),
  ('de', 'site.overview.chats.empty', $json$"Noch keine Chats. Starte einen in der JayV-App."$json$::jsonb),
  ('de', 'site.overview.chats.untitled', $json$"Chat ohne Titel"$json$::jsonb),
  ('de', 'site.overview.system.accounts', $json$"Konten"$json$::jsonb),
  ('de', 'site.overview.system.accounts.hint', $json$"{count} neu im Zeitraum"$json$::jsonb),
  ('de', 'site.overview.system.active', $json$"Nutzen die App"$json$::jsonb),
  ('de', 'site.overview.system.active.hint', $json$"{day} heute · {week} in den letzten 7 Tagen"$json$::jsonb),
  ('de', 'site.overview.system.signIns', $json$"Anmeldungen"$json$::jsonb),
  ('de', 'site.overview.system.signIns.hint', $json$"{users} Konten angemeldet · {open} offene Sitzungen"$json$::jsonb),
  ('de', 'site.overview.system.sessionsNote', $json$"Anmeldungen zählen die noch gespeicherten Sitzungen: Abmelden entfernt eine Sitzung."$json$::jsonb),
  ('de', 'site.overview.system.access', $json$"Konten und Zugriff"$json$::jsonb),
  ('de', 'site.overview.system.confirmed', $json$"E-Mail bestätigt"$json$::jsonb),
  ('de', 'site.overview.system.mfa', $json$"Zwei Schritte aktiv"$json$::jsonb),
  ('de', 'site.overview.system.banned', $json$"Gesperrt"$json$::jsonb),
  ('de', 'site.overview.system.admins', $json$"Admins"$json$::jsonb),
  ('de', 'site.overview.system.signedInDay', $json$"Heute angemeldet"$json$::jsonb),
  ('de', 'site.overview.system.signedInWeek', $json$"In den letzten 7 Tagen angemeldet"$json$::jsonb),
  ('de', 'site.overview.system.activity', $json$"Projekte und Chats"$json$::jsonb),
  ('de', 'site.overview.system.chatsNew', $json$"Neue Chats im Zeitraum"$json$::jsonb),
  ('de', 'site.overview.system.messages', $json$"Nachrichten im Zeitraum"$json$::jsonb),
  ('de', 'site.overview.system.orgRequests', $json$"Anfragen in Organisationen"$json$::jsonb),
  ('de', 'site.overview.system.failures', $json$"Fehlgeschlagene Modellaufrufe"$json$::jsonb),
  ('de', 'site.overview.system.topUsers', $json$"Wer es am meisten genutzt hat"$json$::jsonb),
  ('de', 'site.overview.system.topUsers.empty', $json$"In diesem Zeitraum hat niemand die App genutzt."$json$::jsonb),
  ('de', 'site.overview.system.plans', $json$"Pläne"$json$::jsonb),
  ('de', 'site.overview.system.plans.users', $json${"one": "{count} Konto", "other": "{count} Konten"}$json$::jsonb),
  ('de', 'site.overview.system.organizations', $json$"Organisationen und Jev"$json$::jsonb),
  ('de', 'site.overview.system.members', $json$"Mitglieder"$json$::jsonb),
  ('de', 'site.overview.system.repositories', $json$"Repositories"$json$::jsonb),
  ('de', 'site.overview.system.jevCalls', $json$"Jev-Aufrufe im Zeitraum"$json$::jsonb),
  ('de', 'site.overview.system.jevUsers', $json$"Konten, die Jev genutzt haben"$json$::jsonb),
  ('de', 'site.overview.system.recent', $json$"Neueste Konten"$json$::jsonb),
  ('de', 'site.overview.system.joined', $json$"Beigetreten am {date}"$json$::jsonb),
  ('de', 'site.overview.system.never', $json$"Nie angemeldet"$json$::jsonb),
  ('de', 'site.overview.system.seen', $json$"Letzte Anmeldung am {date}"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
