-- Recursos ativáveis e planos (v0.51.0). Cada funcionalidade do app que pode
-- ser ligada ou desligada tem uma linha em `features`; o admin do sistema a
-- desliga para todo mundo (`enabled`) e escolhe em quais planos ela entra
-- (`plan_features`). Quem usa recebe os recursos do plano da assinatura
-- ativa no Stripe ou, sem assinatura, os do plano padrão.
--
-- O plano padrão nasce com todos os recursos: ninguém perde o que já usa no
-- dia da migração. O admin tira dele o que quiser vender nos outros planos.
--
-- Leitura do catálogo e dos planos por RLS (todo mundo logado lê); escrita só
-- pelas RPCs `admin_*`, que conferem `is_admin()`. As assinaturas só
-- são escritas pela função `stripe-webhook`, com a service role.

-- 1. O admin do sistema é o mesmo que já edita textos e perguntas do Jev:
-- `public.admins` / `is_admin()`. Não há tela para nomear; entra pelo SQL
-- Editor do Supabase (`insert into public.admins (user_id) values
-- ('<uuid do auth.users>')`).
create function public.admin_require() returns void language plpgsql stable security definer set search_path = '' as $$
begin
  if not public.is_admin() then raise exception 'admin.forbidden'; end if;
end;
$$;
revoke execute on function public.admin_require() from public, anon, authenticated;

-- 2. O catálogo. A chave é a do app (`organizations`, `secondOpinion`...); o
-- nome e a descrição vêm do i18n (`feature.<chave>.title` / `.detail`).
create table public.features (
  key text primary key check (key ~ '^[a-z][A-Za-z0-9]{1,40}$'),
  enabled boolean not null default true,
  position integer not null default 0,
  updated_by uuid references auth.users on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.features enable row level security;
create policy "todos leem" on public.features for select to authenticated using (true);

-- 3. Os planos. Nome e descrição são dado do admin, como o nome de uma
-- organização; o preço só serve para a tela mostrar — quem cobra é o preço
-- do Stripe em `stripe_price_id`.
create table public.plans (
  key text primary key check (key ~ '^[a-z][a-z0-9_-]{1,30}$'),
  name text not null check (char_length(btrim(name)) between 1 and 60),
  description text not null default '' check (char_length(description) <= 300),
  position integer not null default 0,
  active boolean not null default true,
  is_default boolean not null default false,
  stripe_price_id text check (stripe_price_id ~ '^price_[A-Za-z0-9]{6,80}$'),
  price_cents integer check (price_cents >= 0),
  currency text check (currency ~ '^[a-z]{3}$'),
  billing_interval text check (billing_interval in ('month', 'year')),
  updated_by uuid references auth.users on delete set null,
  updated_at timestamptz not null default now(),
  -- O padrão é gratuito e sempre ativo: é o que vale para quem não assina.
  check (not is_default or (active and stripe_price_id is null))
);
create unique index plans_one_default on public.plans (is_default) where is_default;
create unique index plans_price on public.plans (stripe_price_id) where stripe_price_id is not null;
alter table public.plans enable row level security;
create policy "todos leem" on public.plans for select to authenticated using (true);

create table public.plan_features (
  plan_key text not null references public.plans on update cascade on delete cascade,
  feature_key text not null references public.features on delete cascade,
  primary key (plan_key, feature_key)
);
alter table public.plan_features enable row level security;
create policy "todos leem" on public.plan_features for select to authenticated using (true);

-- 4. Cliente e assinatura no Stripe. Uma assinatura por conta: a função
-- `billing` manda para o portal quem já assina, em vez de abrir outra.
create table public.billing_customers (
  user_id uuid primary key references auth.users on delete cascade,
  stripe_customer_id text not null unique,
  created_at timestamptz not null default now()
);
alter table public.billing_customers enable row level security;
create policy "lê a própria linha" on public.billing_customers for select to authenticated
  using (user_id = (select auth.uid()));

create table public.subscriptions (
  user_id uuid primary key references auth.users on delete cascade,
  plan_key text references public.plans on update cascade on delete set null,
  stripe_subscription_id text not null unique,
  stripe_price_id text,
  status text not null,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  updated_at timestamptz not null default now()
);
alter table public.subscriptions enable row level security;
create policy "lê a própria linha" on public.subscriptions for select to authenticated
  using (user_id = (select auth.uid()));

-- Tabelas novas depois do segundo fator ganham a mesma política restritiva.
create policy "segundo fator" on public.features as restrictive to authenticated
  using ((select public.second_factor_ok())) with check ((select public.second_factor_ok()));
create policy "segundo fator" on public.plans as restrictive to authenticated
  using ((select public.second_factor_ok())) with check ((select public.second_factor_ok()));
create policy "segundo fator" on public.plan_features as restrictive to authenticated
  using ((select public.second_factor_ok())) with check ((select public.second_factor_ok()));
create policy "segundo fator" on public.billing_customers as restrictive to authenticated
  using ((select public.second_factor_ok())) with check ((select public.second_factor_ok()));
create policy "segundo fator" on public.subscriptions as restrictive to authenticated
  using ((select public.second_factor_ok())) with check ((select public.second_factor_ok()));

-- Nenhuma destas tabelas é escrita direto pela API: o catálogo pelas RPCs do
-- admin, cliente e assinatura pelas funções do Stripe (service role).
revoke insert, update, delete, truncate on public.features, public.plans, public.plan_features, public.billing_customers, public.subscriptions from anon, authenticated;
revoke all on public.features, public.plans, public.plan_features, public.billing_customers, public.subscriptions from anon;

-- O app ouve a própria assinatura e o catálogo: o pagamento e a troca feita
-- pelo admin chegam sem reabrir a tela.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.subscriptions, public.features, public.plans, public.plan_features;
  end if;
end
$$;

-- 5. O que vale para quem chama. `past_due` ainda conta: o Stripe tenta de
-- novo por alguns dias antes de cancelar, e cortar na primeira falha do
-- cartão castiga quem só precisa trocá-lo.
create function public.my_plan() returns text language sql stable security definer set search_path = '' as $$
  select coalesce(
    (select s.plan_key from public.subscriptions s join public.plans p on p.key = s.plan_key
      where s.user_id = auth.uid() and s.status in ('active', 'trialing', 'past_due')),
    (select p.key from public.plans p where p.is_default)
  );
$$;
revoke execute on function public.my_plan() from public, anon;
grant execute on function public.my_plan() to authenticated;

-- `{ plan, features, admin }`: os recursos ligados pelo admin que estão no
-- plano de quem chama. É o que o app e o núcleo leem.
create function public.my_features() returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object(
    'plan', public.my_plan(),
    'admin', coalesce(public.is_admin(), false),
    'features', coalesce((
      select jsonb_agg(f.key order by f.position, f.key)
      from public.features f join public.plan_features pf on pf.feature_key = f.key
      where f.enabled and pf.plan_key = public.my_plan()
    ), '[]'::jsonb)
  );
$$;
revoke execute on function public.my_features() from public, anon;
grant execute on function public.my_features() to authenticated;

-- 6. Escrita do admin.
create function public.admin_set_feature(feature text, on_off boolean) returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.admin_require();
  update public.features set enabled = on_off, updated_by = auth.uid(), updated_at = now() where key = feature;
  if not found then raise exception 'admin.error.unknownFeature'; end if;
end;
$$;

-- Cria ou troca um plano inteiro: campos e recursos. `plan.features` é a
-- lista de chaves; chave fora do catálogo recusa tudo.
create function public.admin_save_plan(plan jsonb) returns void language plpgsql security definer set search_path = '' as $$
declare
  chosen text := plan->>'key';
  wanted text[];
begin
  perform public.admin_require();
  if jsonb_typeof(plan) is distinct from 'object' or jsonb_typeof(plan->'features') is distinct from 'array' then
    raise exception 'admin.error.planInvalid';
  end if;
  wanted := array(select distinct jsonb_array_elements_text(plan->'features'));
  if exists (select 1 from unnest(wanted) k where not exists (select 1 from public.features f where f.key = k)) then
    raise exception 'admin.error.unknownFeature';
  end if;
  begin
    -- Um padrão novo tira o posto do antigo antes de a linha nova entrar.
    if coalesce((plan->>'is_default')::boolean, false) then
      update public.plans set is_default = false where is_default and key <> chosen;
    end if;
    insert into public.plans (key, name, description, position, active, is_default, stripe_price_id, price_cents, currency, billing_interval, updated_by, updated_at)
    values (
      chosen, btrim(plan->>'name'), coalesce(plan->>'description', ''), coalesce((plan->>'position')::integer, 0),
      coalesce((plan->>'active')::boolean, true), coalesce((plan->>'is_default')::boolean, false),
      nullif(btrim(plan->>'stripe_price_id'), ''), (plan->>'price_cents')::integer, nullif(lower(btrim(plan->>'currency')), ''),
      nullif(plan->>'billing_interval', ''), auth.uid(), now()
    )
    on conflict (key) do update set
      name = excluded.name, description = excluded.description, position = excluded.position, active = excluded.active,
      is_default = excluded.is_default, stripe_price_id = excluded.stripe_price_id, price_cents = excluded.price_cents,
      currency = excluded.currency, billing_interval = excluded.billing_interval, updated_by = excluded.updated_by, updated_at = excluded.updated_at;
  exception
    when check_violation or not_null_violation or invalid_text_representation then raise exception 'admin.error.planInvalid';
    when unique_violation then raise exception 'admin.error.priceTaken';
  end;
  if not exists (select 1 from public.plans where is_default) then raise exception 'admin.error.default'; end if;
  delete from public.plan_features pf where pf.plan_key = chosen and not (pf.feature_key = any (wanted));
  insert into public.plan_features (plan_key, feature_key) select chosen, k from unnest(wanted) k on conflict do nothing;
end;
$$;

-- O padrão não sai, nem plano com assinatura de alguém: desative-o em vez de
-- apagar, e quem já assina segue até cancelar.
create function public.admin_delete_plan(plan text) returns void language plpgsql security definer set search_path = '' as $$
begin
  perform public.admin_require();
  if exists (select 1 from public.plans where key = plan and is_default) then raise exception 'admin.error.default'; end if;
  if exists (select 1 from public.subscriptions where plan_key = plan) then raise exception 'admin.error.inUse'; end if;
  delete from public.plans where key = plan;
end;
$$;

-- Quantas contas assinam cada plano, para o admin decidir sem abrir o Stripe.
create function public.admin_plan_counts() returns table (plan_key text, subscribers bigint) language plpgsql stable security definer set search_path = '' as $$
begin
  perform public.admin_require();
  return query select s.plan_key, count(*) from public.subscriptions s
    where s.status in ('active', 'trialing', 'past_due') group by s.plan_key;
end;
$$;

revoke execute on function public.admin_set_feature(text, boolean) from public, anon;
revoke execute on function public.admin_save_plan(jsonb) from public, anon;
revoke execute on function public.admin_delete_plan(text) from public, anon;
revoke execute on function public.admin_plan_counts() from public, anon;
grant execute on function public.admin_set_feature(text, boolean) to authenticated;
grant execute on function public.admin_save_plan(jsonb) to authenticated;
grant execute on function public.admin_delete_plan(text) to authenticated;
grant execute on function public.admin_plan_counts() to authenticated;

-- 7. O catálogo de partida e o plano gratuito com tudo dentro.
insert into public.features (key, position) values
  ('organizations', 10),
  ('orgChat', 20),
  ('stats', 30),
  ('gateBoard', 40),
  ('liveFiles', 50),
  ('chatSearch', 60),
  ('projectNotes', 70),
  ('adaptiveRouting', 80),
  ('secondOpinion', 90),
  ('planFirst', 100),
  ('parallelTasks', 110)
on conflict (key) do nothing;

insert into public.plans (key, name, description, position, is_default) values
  ('free', 'Free', '', 0, true)
on conflict (key) do nothing;

insert into public.plan_features (plan_key, feature_key)
select 'free', key from public.features
on conflict do nothing;


-- 8. Os textos dos recursos, dos planos e da administração, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'feature.organizations.title', $json$"Organizações"$json$::jsonb),
  ('pt-BR', 'feature.organizations.detail', $json$"Criar organizações, convidar membros, repositórios da equipe e política de LLM."$json$::jsonb),
  ('pt-BR', 'feature.orgChat.title', $json$"Chat da organização"$json$::jsonb),
  ('pt-BR', 'feature.orgChat.detail', $json$"Um chat com o agente que enxerga todos os repositórios da organização."$json$::jsonb),
  ('pt-BR', 'feature.stats.title', $json$"Estatísticas"$json$::jsonb),
  ('pt-BR', 'feature.stats.detail', $json$"Uso de tokens, custo, cotas dos agentes e gráficos por projeto."$json$::jsonb),
  ('pt-BR', 'feature.gateBoard.title', $json$"Painel da portaria"$json$::jsonb),
  ('pt-BR', 'feature.gateBoard.detail', $json$"A página com tudo o que o Jev deixou passar, perguntou ou barrou no projeto."$json$::jsonb),
  ('pt-BR', 'feature.liveFiles.title', $json$"Arquivos ao vivo"$json$::jsonb),
  ('pt-BR', 'feature.liveFiles.detail', $json$"O painel que mostra os arquivos que o agente está mudando, com o diff, enquanto ele trabalha."$json$::jsonb),
  ('pt-BR', 'feature.chatSearch.title', $json$"Busca nos chats"$json$::jsonb),
  ('pt-BR', 'feature.chatSearch.detail', $json$"Procurar palavras em todas as conversas do projeto."$json$::jsonb),
  ('pt-BR', 'feature.projectNotes.title', $json$"Notas do projeto"$json$::jsonb),
  ('pt-BR', 'feature.projectNotes.detail', $json$"O que o agente deve lembrar sobre o projeto em toda conversa nova."$json$::jsonb),
  ('pt-BR', 'feature.adaptiveRouting.title', $json$"Roteamento adaptativo"$json$::jsonb),
  ('pt-BR', 'feature.adaptiveRouting.detail', $json$"O histórico de acertos de cada modelo pesa na escolha de quem atende."$json$::jsonb),
  ('pt-BR', 'feature.secondOpinion.title', $json$"Segunda opinião"$json$::jsonb),
  ('pt-BR', 'feature.secondOpinion.detail', $json$"Um agente de outro provedor revisa o que o modo build mudou."$json$::jsonb),
  ('pt-BR', 'feature.planFirst.title', $json$"Planejar antes de construir"$json$::jsonb),
  ('pt-BR', 'feature.planFirst.detail', $json$"Num pedido complexo do modo build, um modelo de raciocínio planeja antes de o agente construir."$json$::jsonb),
  ('pt-BR', 'feature.parallelTasks.title', $json$"Agentes em paralelo"$json$::jsonb),
  ('pt-BR', 'feature.parallelTasks.detail', $json$"Um pedido grande é dividido entre agentes que trabalham ao mesmo tempo em git worktrees."$json$::jsonb),
  ('pt-BR', 'nav.plans', $json$"Planos"$json$::jsonb),
  ('pt-BR', 'nav.admin', $json$"Administração"$json$::jsonb),
  ('pt-BR', 'plans.description', $json$"O que cada plano traz. O pagamento abre no navegador, pelo Stripe, e o JayV atualiza sozinho quando ele termina."$json$::jsonb),
  ('pt-BR', 'plans.loading', $json$"Carregando planos…"$json$::jsonb),
  ('pt-BR', 'plans.locked', $json$"Este recurso não está no seu plano ou foi desligado pelo administrador."$json$::jsonb),
  ('pt-BR', 'plans.see', $json$"Ver planos"$json$::jsonb),
  ('pt-BR', 'plans.manage', $json$"Gerenciar assinatura"$json$::jsonb),
  ('pt-BR', 'plans.current', $json$"Seu plano"$json$::jsonb),
  ('pt-BR', 'plans.free', $json$"Grátis"$json$::jsonb),
  ('pt-BR', 'plans.interval.month', $json$"mês"$json$::jsonb),
  ('pt-BR', 'plans.interval.year', $json$"ano"$json$::jsonb),
  ('pt-BR', 'plans.included', $json$"incluído"$json$::jsonb),
  ('pt-BR', 'plans.notIncluded', $json$"não incluído"$json$::jsonb),
  ('pt-BR', 'plans.subscribe', $json$"Assinar"$json$::jsonb),
  ('pt-BR', 'plans.change', $json$"Trocar de plano"$json$::jsonb),
  ('pt-BR', 'plans.paid', $json$"Pagamento concluído. Seu plano será atualizado em instantes."$json$::jsonb),
  ('pt-BR', 'plans.canceled', $json$"Pagamento cancelado. Nada foi cobrado."$json$::jsonb),
  ('pt-BR', 'plans.renewsOn', $json$"Renova em {date}."$json$::jsonb),
  ('pt-BR', 'plans.endsOn', $json$"Termina em {date} e não será renovada."$json$::jsonb),
  ('pt-BR', 'plans.status.active', $json$"Assinatura ativa."$json$::jsonb),
  ('pt-BR', 'plans.status.trialing', $json$"Período de teste."$json$::jsonb),
  ('pt-BR', 'plans.status.past_due', $json$"O último pagamento falhou. Atualize o cartão em Gerenciar assinatura para não perder o plano."$json$::jsonb),
  ('pt-BR', 'plans.error.config', $json$"O pagamento ainda não está configurado no servidor."$json$::jsonb),
  ('pt-BR', 'plans.error.plan', $json$"Este plano não está à venda agora."$json$::jsonb),
  ('pt-BR', 'plans.error.stripe', $json$"Não foi possível falar com o Stripe. Tente de novo em instantes."$json$::jsonb),
  ('pt-BR', 'plans.jevLocked', $json$"Fora do seu plano"$json$::jsonb),
  ('pt-BR', 'admin.eyebrow', $json$"Sistema"$json$::jsonb),
  ('pt-BR', 'admin.description', $json$"Ligue e desligue cada recurso para todos e monte os planos vendidos pelo Stripe."$json$::jsonb),
  ('pt-BR', 'admin.forbidden', $json$"Só o administrador do sistema pode fazer isso."$json$::jsonb),
  ('pt-BR', 'admin.tab.features', $json$"Recursos"$json$::jsonb),
  ('pt-BR', 'admin.tab.plans', $json$"Planos"$json$::jsonb),
  ('pt-BR', 'admin.features.title', $json$"Recursos do sistema"$json$::jsonb),
  ('pt-BR', 'admin.features.description', $json$"Desligado aqui, o recurso some para todos, em qualquer plano."$json$::jsonb),
  ('pt-BR', 'admin.plans.description', $json$"Quem não assina fica no plano padrão. Cada plano pago precisa de um preço recorrente criado no Stripe."$json$::jsonb),
  ('pt-BR', 'admin.plan.new', $json$"Novo plano"$json$::jsonb),
  ('pt-BR', 'admin.plan.newHint', $json$"Preencha e salve para criar."$json$::jsonb),
  ('pt-BR', 'admin.plan.untitled', $json$"Plano sem nome"$json$::jsonb),
  ('pt-BR', 'admin.plan.subscribers', $json${"one": "{count} assinante", "other": "{count} assinantes"}$json$::jsonb),
  ('pt-BR', 'admin.plan.defaultBadge', $json$"Padrão"$json$::jsonb),
  ('pt-BR', 'admin.plan.inactiveBadge', $json$"Fora de venda"$json$::jsonb),
  ('pt-BR', 'admin.plan.key', $json$"Identificador"$json$::jsonb),
  ('pt-BR', 'admin.plan.keyHint', $json$"Letras minúsculas, números, - e _. Não muda depois."$json$::jsonb),
  ('pt-BR', 'admin.plan.name', $json$"Nome"$json$::jsonb),
  ('pt-BR', 'admin.plan.descriptionField', $json$"Descrição"$json$::jsonb),
  ('pt-BR', 'admin.plan.price', $json$"Preço exibido"$json$::jsonb),
  ('pt-BR', 'admin.plan.priceHint', $json$"Só para a página de planos: quem cobra é o preço do Stripe."$json$::jsonb),
  ('pt-BR', 'admin.plan.currency', $json$"Moeda"$json$::jsonb),
  ('pt-BR', 'admin.plan.interval', $json$"Cobrança"$json$::jsonb),
  ('pt-BR', 'admin.plan.stripePrice', $json$"ID do preço no Stripe"$json$::jsonb),
  ('pt-BR', 'admin.plan.stripePriceHint', $json$"Em Stripe › Catálogo de produtos › o produto › Preço (começa com price_)."$json$::jsonb),
  ('pt-BR', 'admin.plan.active', $json$"À venda"$json$::jsonb),
  ('pt-BR', 'admin.plan.activeHint', $json$"Desligado, some da página de planos; quem já assina continua."$json$::jsonb),
  ('pt-BR', 'admin.plan.default', $json$"Plano padrão"$json$::jsonb),
  ('pt-BR', 'admin.plan.defaultHint', $json$"Gratuito: vale para quem não tem assinatura. Só um plano é o padrão."$json$::jsonb),
  ('pt-BR', 'admin.plan.features', $json$"Recursos incluídos"$json$::jsonb),
  ('pt-BR', 'admin.plan.delete', $json$"Excluir plano"$json$::jsonb),
  ('pt-BR', 'admin.plan.deleteTitle', $json$"Excluir o plano {plan}?"$json$::jsonb),
  ('pt-BR', 'admin.plan.deleteHint', $json$"Plano com assinantes não pode ser excluído: tire-o da venda."$json$::jsonb),
  ('pt-BR', 'admin.plan.saved', $json$"Plano {plan} salvo."$json$::jsonb),
  ('pt-BR', 'admin.plan.deleted', $json$"Plano {plan} excluído."$json$::jsonb),
  ('pt-BR', 'admin.error.unknownFeature', $json$"Recurso desconhecido."$json$::jsonb),
  ('pt-BR', 'admin.error.planInvalid', $json$"Confira os campos do plano: identificador, nome, moeda (3 letras) e o ID do preço (price_…)."$json$::jsonb),
  ('pt-BR', 'admin.error.priceTaken', $json$"Este preço do Stripe já está em outro plano."$json$::jsonb),
  ('pt-BR', 'admin.error.default', $json$"Precisa haver um plano padrão, e ele não pode ser excluído."$json$::jsonb),
  ('pt-BR', 'admin.error.inUse', $json$"Este plano tem assinantes. Tire-o da venda em vez de excluir."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.plans.title', $json$"Planos e assinatura"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.plans.detail', $json$"A nova página Planos mostra o que cada plano traz e assina pelo Stripe. Quem não assina segue no plano gratuito, com tudo o que já usava."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.adminFeatures.title', $json$"Recursos ligados pelo administrador"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.adminFeatures.detail', $json$"Organizações, estatísticas, painel da portaria, arquivos ao vivo, busca, notas do projeto e as opções avançadas do Jev agora podem ser ligados ou desligados pelo administrador do sistema e entrar em cada plano."$json$::jsonb),
  ('en', 'feature.organizations.title', $json$"Organizations"$json$::jsonb),
  ('en', 'feature.organizations.detail', $json$"Create organizations, invite members, team repositories and LLM policy."$json$::jsonb),
  ('en', 'feature.orgChat.title', $json$"Organization chat"$json$::jsonb),
  ('en', 'feature.orgChat.detail', $json$"A chat with the agent that sees every repository of the organization."$json$::jsonb),
  ('en', 'feature.stats.title', $json$"Statistics"$json$::jsonb),
  ('en', 'feature.stats.detail', $json$"Token usage, cost, agent quotas and charts per project."$json$::jsonb),
  ('en', 'feature.gateBoard.title', $json$"Gatehouse board"$json$::jsonb),
  ('en', 'feature.gateBoard.detail', $json$"The page with everything Jev let through, asked about or blocked in the project."$json$::jsonb),
  ('en', 'feature.liveFiles.title', $json$"Live files"$json$::jsonb),
  ('en', 'feature.liveFiles.detail', $json$"The panel that shows the files the agent is changing, with the diff, while it works."$json$::jsonb),
  ('en', 'feature.chatSearch.title', $json$"Chat search"$json$::jsonb),
  ('en', 'feature.chatSearch.detail', $json$"Search for words across every conversation of the project."$json$::jsonb),
  ('en', 'feature.projectNotes.title', $json$"Project notes"$json$::jsonb),
  ('en', 'feature.projectNotes.detail', $json$"What the agent should remember about the project in every new conversation."$json$::jsonb),
  ('en', 'feature.adaptiveRouting.title', $json$"Adaptive routing"$json$::jsonb),
  ('en', 'feature.adaptiveRouting.detail', $json$"Each model's track record weighs in on who answers."$json$::jsonb),
  ('en', 'feature.secondOpinion.title', $json$"Second opinion"$json$::jsonb),
  ('en', 'feature.secondOpinion.detail', $json$"An agent from another provider reviews what build mode changed."$json$::jsonb),
  ('en', 'feature.planFirst.title', $json$"Plan before building"$json$::jsonb),
  ('en', 'feature.planFirst.detail', $json$"On a complex build request, a reasoning model plans before the agent builds."$json$::jsonb),
  ('en', 'feature.parallelTasks.title', $json$"Parallel agents"$json$::jsonb),
  ('en', 'feature.parallelTasks.detail', $json$"A large request is split among agents working at the same time in git worktrees."$json$::jsonb),
  ('en', 'nav.plans', $json$"Plans"$json$::jsonb),
  ('en', 'nav.admin', $json$"Administration"$json$::jsonb),
  ('en', 'plans.description', $json$"What each plan includes. Payment opens in the browser, through Stripe, and JayV updates by itself when it finishes."$json$::jsonb),
  ('en', 'plans.loading', $json$"Loading plans…"$json$::jsonb),
  ('en', 'plans.locked', $json$"This feature isn't in your plan or was turned off by the administrator."$json$::jsonb),
  ('en', 'plans.see', $json$"See plans"$json$::jsonb),
  ('en', 'plans.manage', $json$"Manage subscription"$json$::jsonb),
  ('en', 'plans.current', $json$"Your plan"$json$::jsonb),
  ('en', 'plans.free', $json$"Free"$json$::jsonb),
  ('en', 'plans.interval.month', $json$"month"$json$::jsonb),
  ('en', 'plans.interval.year', $json$"year"$json$::jsonb),
  ('en', 'plans.included', $json$"included"$json$::jsonb),
  ('en', 'plans.notIncluded', $json$"not included"$json$::jsonb),
  ('en', 'plans.subscribe', $json$"Subscribe"$json$::jsonb),
  ('en', 'plans.change', $json$"Change plan"$json$::jsonb),
  ('en', 'plans.paid', $json$"Payment complete. Your plan will update in a moment."$json$::jsonb),
  ('en', 'plans.canceled', $json$"Payment canceled. Nothing was charged."$json$::jsonb),
  ('en', 'plans.renewsOn', $json$"Renews on {date}."$json$::jsonb),
  ('en', 'plans.endsOn', $json$"Ends on {date} and won't renew."$json$::jsonb),
  ('en', 'plans.status.active', $json$"Subscription active."$json$::jsonb),
  ('en', 'plans.status.trialing', $json$"Trial period."$json$::jsonb),
  ('en', 'plans.status.past_due', $json$"The last payment failed. Update your card in Manage subscription to keep your plan."$json$::jsonb),
  ('en', 'plans.error.config', $json$"Payment isn't set up on the server yet."$json$::jsonb),
  ('en', 'plans.error.plan', $json$"This plan isn't for sale right now."$json$::jsonb),
  ('en', 'plans.error.stripe', $json$"Couldn't reach Stripe. Try again in a moment."$json$::jsonb),
  ('en', 'plans.jevLocked', $json$"Not in your plan"$json$::jsonb),
  ('en', 'admin.eyebrow', $json$"System"$json$::jsonb),
  ('en', 'admin.description', $json$"Turn each feature on or off for everyone and build the plans sold through Stripe."$json$::jsonb),
  ('en', 'admin.forbidden', $json$"Only the system administrator can do this."$json$::jsonb),
  ('en', 'admin.tab.features', $json$"Features"$json$::jsonb),
  ('en', 'admin.tab.plans', $json$"Plans"$json$::jsonb),
  ('en', 'admin.features.title', $json$"System features"$json$::jsonb),
  ('en', 'admin.features.description', $json$"Turned off here, the feature disappears for everyone, in any plan."$json$::jsonb),
  ('en', 'admin.plans.description', $json$"Anyone without a subscription stays on the default plan. Each paid plan needs a recurring price created in Stripe."$json$::jsonb),
  ('en', 'admin.plan.new', $json$"New plan"$json$::jsonb),
  ('en', 'admin.plan.newHint', $json$"Fill in and save to create it."$json$::jsonb),
  ('en', 'admin.plan.untitled', $json$"Untitled plan"$json$::jsonb),
  ('en', 'admin.plan.subscribers', $json${"one": "{count} subscriber", "other": "{count} subscribers"}$json$::jsonb),
  ('en', 'admin.plan.defaultBadge', $json$"Default"$json$::jsonb),
  ('en', 'admin.plan.inactiveBadge', $json$"Not for sale"$json$::jsonb),
  ('en', 'admin.plan.key', $json$"Identifier"$json$::jsonb),
  ('en', 'admin.plan.keyHint', $json$"Lowercase letters, digits, - and _. Can't change later."$json$::jsonb),
  ('en', 'admin.plan.name', $json$"Name"$json$::jsonb),
  ('en', 'admin.plan.descriptionField', $json$"Description"$json$::jsonb),
  ('en', 'admin.plan.price', $json$"Displayed price"$json$::jsonb),
  ('en', 'admin.plan.priceHint', $json$"Only for the plans page: Stripe's price is what gets charged."$json$::jsonb),
  ('en', 'admin.plan.currency', $json$"Currency"$json$::jsonb),
  ('en', 'admin.plan.interval', $json$"Billing"$json$::jsonb),
  ('en', 'admin.plan.stripePrice', $json$"Stripe price ID"$json$::jsonb),
  ('en', 'admin.plan.stripePriceHint', $json$"In Stripe › Product catalog › the product › Price (starts with price_)."$json$::jsonb),
  ('en', 'admin.plan.active', $json$"For sale"$json$::jsonb),
  ('en', 'admin.plan.activeHint', $json$"Off, it leaves the plans page; existing subscribers keep it."$json$::jsonb),
  ('en', 'admin.plan.default', $json$"Default plan"$json$::jsonb),
  ('en', 'admin.plan.defaultHint', $json$"Free: applies to anyone without a subscription. Only one plan is the default."$json$::jsonb),
  ('en', 'admin.plan.features', $json$"Included features"$json$::jsonb),
  ('en', 'admin.plan.delete', $json$"Delete plan"$json$::jsonb),
  ('en', 'admin.plan.deleteTitle', $json$"Delete the {plan} plan?"$json$::jsonb),
  ('en', 'admin.plan.deleteHint', $json$"A plan with subscribers can't be deleted: take it off sale instead."$json$::jsonb),
  ('en', 'admin.plan.saved', $json$"Plan {plan} saved."$json$::jsonb),
  ('en', 'admin.plan.deleted', $json$"Plan {plan} deleted."$json$::jsonb),
  ('en', 'admin.error.unknownFeature', $json$"Unknown feature."$json$::jsonb),
  ('en', 'admin.error.planInvalid', $json$"Check the plan fields: identifier, name, currency (3 letters) and price ID (price_…)."$json$::jsonb),
  ('en', 'admin.error.priceTaken', $json$"This Stripe price is already used by another plan."$json$::jsonb),
  ('en', 'admin.error.default', $json$"There must be a default plan, and it can't be deleted."$json$::jsonb),
  ('en', 'admin.error.inUse', $json$"This plan has subscribers. Take it off sale instead of deleting it."$json$::jsonb),
  ('en', 'whatsNew.item.plans.title', $json$"Plans and subscription"$json$::jsonb),
  ('en', 'whatsNew.item.plans.detail', $json$"The new Plans page shows what each plan includes and subscribes through Stripe. Anyone without a subscription stays on the free plan, with everything they already used."$json$::jsonb),
  ('en', 'whatsNew.item.adminFeatures.title', $json$"Features controlled by the administrator"$json$::jsonb),
  ('en', 'whatsNew.item.adminFeatures.detail', $json$"Organizations, statistics, gatehouse board, live files, search, project notes and Jev's advanced options can now be turned on or off by the system administrator and included in each plan."$json$::jsonb),
  ('es', 'feature.organizations.title', $json$"Organizaciones"$json$::jsonb),
  ('es', 'feature.organizations.detail', $json$"Crear organizaciones, invitar miembros, repositorios del equipo y política de LLM."$json$::jsonb),
  ('es', 'feature.orgChat.title', $json$"Chat de la organización"$json$::jsonb),
  ('es', 'feature.orgChat.detail', $json$"Un chat con el agente que ve todos los repositorios de la organización."$json$::jsonb),
  ('es', 'feature.stats.title', $json$"Estadísticas"$json$::jsonb),
  ('es', 'feature.stats.detail', $json$"Uso de tokens, coste, cuotas de los agentes y gráficos por proyecto."$json$::jsonb),
  ('es', 'feature.gateBoard.title', $json$"Panel de la portería"$json$::jsonb),
  ('es', 'feature.gateBoard.detail', $json$"La página con todo lo que Jev dejó pasar, preguntó o bloqueó en el proyecto."$json$::jsonb),
  ('es', 'feature.liveFiles.title', $json$"Archivos en vivo"$json$::jsonb),
  ('es', 'feature.liveFiles.detail', $json$"El panel que muestra los archivos que el agente está cambiando, con el diff, mientras trabaja."$json$::jsonb),
  ('es', 'feature.chatSearch.title', $json$"Búsqueda en los chats"$json$::jsonb),
  ('es', 'feature.chatSearch.detail', $json$"Buscar palabras en todas las conversaciones del proyecto."$json$::jsonb),
  ('es', 'feature.projectNotes.title', $json$"Notas del proyecto"$json$::jsonb),
  ('es', 'feature.projectNotes.detail', $json$"Lo que el agente debe recordar del proyecto en cada conversación nueva."$json$::jsonb),
  ('es', 'feature.adaptiveRouting.title', $json$"Enrutamiento adaptativo"$json$::jsonb),
  ('es', 'feature.adaptiveRouting.detail', $json$"El historial de aciertos de cada modelo pesa en la elección de quién responde."$json$::jsonb),
  ('es', 'feature.secondOpinion.title', $json$"Segunda opinión"$json$::jsonb),
  ('es', 'feature.secondOpinion.detail', $json$"Un agente de otro proveedor revisa lo que cambió el modo build."$json$::jsonb),
  ('es', 'feature.planFirst.title', $json$"Planificar antes de construir"$json$::jsonb),
  ('es', 'feature.planFirst.detail', $json$"En una petición compleja del modo build, un modelo de razonamiento planifica antes de que el agente construya."$json$::jsonb),
  ('es', 'feature.parallelTasks.title', $json$"Agentes en paralelo"$json$::jsonb),
  ('es', 'feature.parallelTasks.detail', $json$"Una petición grande se divide entre agentes que trabajan a la vez en git worktrees."$json$::jsonb),
  ('es', 'nav.plans', $json$"Planes"$json$::jsonb),
  ('es', 'nav.admin', $json$"Administración"$json$::jsonb),
  ('es', 'plans.description', $json$"Lo que incluye cada plan. El pago se abre en el navegador, mediante Stripe, y JayV se actualiza solo cuando termina."$json$::jsonb),
  ('es', 'plans.loading', $json$"Cargando planes…"$json$::jsonb),
  ('es', 'plans.locked', $json$"Esta función no está en tu plan o la desactivó el administrador."$json$::jsonb),
  ('es', 'plans.see', $json$"Ver planes"$json$::jsonb),
  ('es', 'plans.manage', $json$"Gestionar suscripción"$json$::jsonb),
  ('es', 'plans.current', $json$"Tu plan"$json$::jsonb),
  ('es', 'plans.free', $json$"Gratis"$json$::jsonb),
  ('es', 'plans.interval.month', $json$"mes"$json$::jsonb),
  ('es', 'plans.interval.year', $json$"año"$json$::jsonb),
  ('es', 'plans.included', $json$"incluido"$json$::jsonb),
  ('es', 'plans.notIncluded', $json$"no incluido"$json$::jsonb),
  ('es', 'plans.subscribe', $json$"Suscribirse"$json$::jsonb),
  ('es', 'plans.change', $json$"Cambiar de plan"$json$::jsonb),
  ('es', 'plans.paid', $json$"Pago completado. Tu plan se actualizará en unos instantes."$json$::jsonb),
  ('es', 'plans.canceled', $json$"Pago cancelado. No se cobró nada."$json$::jsonb),
  ('es', 'plans.renewsOn', $json$"Se renueva el {date}."$json$::jsonb),
  ('es', 'plans.endsOn', $json$"Termina el {date} y no se renovará."$json$::jsonb),
  ('es', 'plans.status.active', $json$"Suscripción activa."$json$::jsonb),
  ('es', 'plans.status.trialing', $json$"Período de prueba."$json$::jsonb),
  ('es', 'plans.status.past_due', $json$"El último pago falló. Actualiza la tarjeta en Gestionar suscripción para no perder el plan."$json$::jsonb),
  ('es', 'plans.error.config', $json$"El pago aún no está configurado en el servidor."$json$::jsonb),
  ('es', 'plans.error.plan', $json$"Este plan no está a la venta ahora."$json$::jsonb),
  ('es', 'plans.error.stripe', $json$"No se pudo contactar con Stripe. Inténtalo de nuevo en unos instantes."$json$::jsonb),
  ('es', 'plans.jevLocked', $json$"Fuera de tu plan"$json$::jsonb),
  ('es', 'admin.eyebrow', $json$"Sistema"$json$::jsonb),
  ('es', 'admin.description', $json$"Activa o desactiva cada función para todos y arma los planes que se venden con Stripe."$json$::jsonb),
  ('es', 'admin.forbidden', $json$"Solo el administrador del sistema puede hacerlo."$json$::jsonb),
  ('es', 'admin.tab.features', $json$"Funciones"$json$::jsonb),
  ('es', 'admin.tab.plans', $json$"Planes"$json$::jsonb),
  ('es', 'admin.features.title', $json$"Funciones del sistema"$json$::jsonb),
  ('es', 'admin.features.description', $json$"Desactivada aquí, la función desaparece para todos, en cualquier plan."$json$::jsonb),
  ('es', 'admin.plans.description', $json$"Quien no se suscribe queda en el plan predeterminado. Cada plan de pago necesita un precio recurrente creado en Stripe."$json$::jsonb),
  ('es', 'admin.plan.new', $json$"Nuevo plan"$json$::jsonb),
  ('es', 'admin.plan.newHint', $json$"Rellena y guarda para crearlo."$json$::jsonb),
  ('es', 'admin.plan.untitled', $json$"Plan sin nombre"$json$::jsonb),
  ('es', 'admin.plan.subscribers', $json${"one": "{count} suscriptor", "other": "{count} suscriptores"}$json$::jsonb),
  ('es', 'admin.plan.defaultBadge', $json$"Predeterminado"$json$::jsonb),
  ('es', 'admin.plan.inactiveBadge', $json$"Fuera de venta"$json$::jsonb),
  ('es', 'admin.plan.key', $json$"Identificador"$json$::jsonb),
  ('es', 'admin.plan.keyHint', $json$"Minúsculas, números, - y _. No se puede cambiar después."$json$::jsonb),
  ('es', 'admin.plan.name', $json$"Nombre"$json$::jsonb),
  ('es', 'admin.plan.descriptionField', $json$"Descripción"$json$::jsonb),
  ('es', 'admin.plan.price', $json$"Precio mostrado"$json$::jsonb),
  ('es', 'admin.plan.priceHint', $json$"Solo para la página de planes: lo que se cobra es el precio de Stripe."$json$::jsonb),
  ('es', 'admin.plan.currency', $json$"Moneda"$json$::jsonb),
  ('es', 'admin.plan.interval', $json$"Cobro"$json$::jsonb),
  ('es', 'admin.plan.stripePrice', $json$"ID del precio en Stripe"$json$::jsonb),
  ('es', 'admin.plan.stripePriceHint', $json$"En Stripe › Catálogo de productos › el producto › Precio (empieza por price_)."$json$::jsonb),
  ('es', 'admin.plan.active', $json$"A la venta"$json$::jsonb),
  ('es', 'admin.plan.activeHint', $json$"Desactivado, desaparece de la página de planes; quien ya está suscrito sigue."$json$::jsonb),
  ('es', 'admin.plan.default', $json$"Plan predeterminado"$json$::jsonb),
  ('es', 'admin.plan.defaultHint', $json$"Gratuito: vale para quien no tiene suscripción. Solo un plan es el predeterminado."$json$::jsonb),
  ('es', 'admin.plan.features', $json$"Funciones incluidas"$json$::jsonb),
  ('es', 'admin.plan.delete', $json$"Eliminar plan"$json$::jsonb),
  ('es', 'admin.plan.deleteTitle', $json$"¿Eliminar el plan {plan}?"$json$::jsonb),
  ('es', 'admin.plan.deleteHint', $json$"Un plan con suscriptores no se puede eliminar: retíralo de la venta."$json$::jsonb),
  ('es', 'admin.plan.saved', $json$"Plan {plan} guardado."$json$::jsonb),
  ('es', 'admin.plan.deleted', $json$"Plan {plan} eliminado."$json$::jsonb),
  ('es', 'admin.error.unknownFeature', $json$"Función desconocida."$json$::jsonb),
  ('es', 'admin.error.planInvalid', $json$"Revisa los campos del plan: identificador, nombre, moneda (3 letras) e ID del precio (price_…)."$json$::jsonb),
  ('es', 'admin.error.priceTaken', $json$"Este precio de Stripe ya está en otro plan."$json$::jsonb),
  ('es', 'admin.error.default', $json$"Debe haber un plan predeterminado, y no se puede eliminar."$json$::jsonb),
  ('es', 'admin.error.inUse', $json$"Este plan tiene suscriptores. Retíralo de la venta en lugar de eliminarlo."$json$::jsonb),
  ('es', 'whatsNew.item.plans.title', $json$"Planes y suscripción"$json$::jsonb),
  ('es', 'whatsNew.item.plans.detail', $json$"La nueva página Planes muestra lo que incluye cada plan y permite suscribirse con Stripe. Quien no se suscribe sigue en el plan gratuito, con todo lo que ya usaba."$json$::jsonb),
  ('es', 'whatsNew.item.adminFeatures.title', $json$"Funciones controladas por el administrador"$json$::jsonb),
  ('es', 'whatsNew.item.adminFeatures.detail', $json$"Organizaciones, estadísticas, panel de la portería, archivos en vivo, búsqueda, notas del proyecto y las opciones avanzadas de Jev ahora pueden activarse o desactivarse por el administrador del sistema e incluirse en cada plan."$json$::jsonb),
  ('zh-CN', 'feature.organizations.title', $json$"组织"$json$::jsonb),
  ('zh-CN', 'feature.organizations.detail', $json$"创建组织、邀请成员、团队仓库和 LLM 策略。"$json$::jsonb),
  ('zh-CN', 'feature.orgChat.title', $json$"组织聊天"$json$::jsonb),
  ('zh-CN', 'feature.orgChat.detail', $json$"与能看到组织所有仓库的智能体聊天。"$json$::jsonb),
  ('zh-CN', 'feature.stats.title', $json$"统计"$json$::jsonb),
  ('zh-CN', 'feature.stats.detail', $json$"令牌用量、成本、智能体配额和按项目的图表。"$json$::jsonb),
  ('zh-CN', 'feature.gateBoard.title', $json$"门卫面板"$json$::jsonb),
  ('zh-CN', 'feature.gateBoard.detail', $json$"显示 Jev 在项目中放行、询问或拦截的所有内容的页面。"$json$::jsonb),
  ('zh-CN', 'feature.liveFiles.title', $json$"实时文件"$json$::jsonb),
  ('zh-CN', 'feature.liveFiles.detail', $json$"在智能体工作时显示其正在修改的文件及差异的面板。"$json$::jsonb),
  ('zh-CN', 'feature.chatSearch.title', $json$"聊天搜索"$json$::jsonb),
  ('zh-CN', 'feature.chatSearch.detail', $json$"在项目的所有对话中搜索文字。"$json$::jsonb),
  ('zh-CN', 'feature.projectNotes.title', $json$"项目笔记"$json$::jsonb),
  ('zh-CN', 'feature.projectNotes.detail', $json$"智能体在每次新对话中都应记住的项目信息。"$json$::jsonb),
  ('zh-CN', 'feature.adaptiveRouting.title', $json$"自适应路由"$json$::jsonb),
  ('zh-CN', 'feature.adaptiveRouting.detail', $json$"每个模型的历史表现会影响由谁来回答。"$json$::jsonb),
  ('zh-CN', 'feature.secondOpinion.title', $json$"第二意见"$json$::jsonb),
  ('zh-CN', 'feature.secondOpinion.detail', $json$"由另一家提供商的智能体审查构建模式所做的更改。"$json$::jsonb),
  ('zh-CN', 'feature.planFirst.title', $json$"先规划后构建"$json$::jsonb),
  ('zh-CN', 'feature.planFirst.detail', $json$"对于复杂的构建请求，推理模型会在智能体构建前先做规划。"$json$::jsonb),
  ('zh-CN', 'feature.parallelTasks.title', $json$"并行智能体"$json$::jsonb),
  ('zh-CN', 'feature.parallelTasks.detail', $json$"大型请求会拆分给在 git worktree 中同时工作的多个智能体。"$json$::jsonb),
  ('zh-CN', 'nav.plans', $json$"套餐"$json$::jsonb),
  ('zh-CN', 'nav.admin', $json$"管理"$json$::jsonb),
  ('zh-CN', 'plans.description', $json$"各套餐包含的内容。付款会在浏览器中通过 Stripe 打开，完成后 JayV 会自动更新。"$json$::jsonb),
  ('zh-CN', 'plans.loading', $json$"正在加载套餐…"$json$::jsonb),
  ('zh-CN', 'plans.locked', $json$"此功能不在你的套餐中，或已被管理员关闭。"$json$::jsonb),
  ('zh-CN', 'plans.see', $json$"查看套餐"$json$::jsonb),
  ('zh-CN', 'plans.manage', $json$"管理订阅"$json$::jsonb),
  ('zh-CN', 'plans.current', $json$"当前套餐"$json$::jsonb),
  ('zh-CN', 'plans.free', $json$"免费"$json$::jsonb),
  ('zh-CN', 'plans.interval.month', $json$"月"$json$::jsonb),
  ('zh-CN', 'plans.interval.year', $json$"年"$json$::jsonb),
  ('zh-CN', 'plans.included', $json$"已包含"$json$::jsonb),
  ('zh-CN', 'plans.notIncluded', $json$"不包含"$json$::jsonb),
  ('zh-CN', 'plans.subscribe', $json$"订阅"$json$::jsonb),
  ('zh-CN', 'plans.change', $json$"更换套餐"$json$::jsonb),
  ('zh-CN', 'plans.paid', $json$"付款完成。你的套餐稍后会更新。"$json$::jsonb),
  ('zh-CN', 'plans.canceled', $json$"付款已取消，未产生任何费用。"$json$::jsonb),
  ('zh-CN', 'plans.renewsOn', $json$"将于 {date} 续订。"$json$::jsonb),
  ('zh-CN', 'plans.endsOn', $json$"将于 {date} 结束，且不会续订。"$json$::jsonb),
  ('zh-CN', 'plans.status.active', $json$"订阅有效。"$json$::jsonb),
  ('zh-CN', 'plans.status.trialing', $json$"试用期。"$json$::jsonb),
  ('zh-CN', 'plans.status.past_due', $json$"上次付款失败。请在“管理订阅”中更新银行卡，以免失去套餐。"$json$::jsonb),
  ('zh-CN', 'plans.error.config', $json$"服务器尚未配置付款。"$json$::jsonb),
  ('zh-CN', 'plans.error.plan', $json$"此套餐目前不可购买。"$json$::jsonb),
  ('zh-CN', 'plans.error.stripe', $json$"无法连接 Stripe，请稍后重试。"$json$::jsonb),
  ('zh-CN', 'plans.jevLocked', $json$"不在你的套餐中"$json$::jsonb),
  ('zh-CN', 'admin.eyebrow', $json$"系统"$json$::jsonb),
  ('zh-CN', 'admin.description', $json$"为所有人开启或关闭每项功能，并配置通过 Stripe 销售的套餐。"$json$::jsonb),
  ('zh-CN', 'admin.forbidden', $json$"只有系统管理员可以执行此操作。"$json$::jsonb),
  ('zh-CN', 'admin.tab.features', $json$"功能"$json$::jsonb),
  ('zh-CN', 'admin.tab.plans', $json$"套餐"$json$::jsonb),
  ('zh-CN', 'admin.features.title', $json$"系统功能"$json$::jsonb),
  ('zh-CN', 'admin.features.description', $json$"在此关闭后，该功能对所有人、所有套餐都不可用。"$json$::jsonb),
  ('zh-CN', 'admin.plans.description', $json$"未订阅的用户使用默认套餐。每个付费套餐都需要在 Stripe 中创建一个定期价格。"$json$::jsonb),
  ('zh-CN', 'admin.plan.new', $json$"新建套餐"$json$::jsonb),
  ('zh-CN', 'admin.plan.newHint', $json$"填写并保存即可创建。"$json$::jsonb),
  ('zh-CN', 'admin.plan.untitled', $json$"未命名套餐"$json$::jsonb),
  ('zh-CN', 'admin.plan.subscribers', $json${"other": "{count} 位订阅者"}$json$::jsonb),
  ('zh-CN', 'admin.plan.defaultBadge', $json$"默认"$json$::jsonb),
  ('zh-CN', 'admin.plan.inactiveBadge', $json$"停售"$json$::jsonb),
  ('zh-CN', 'admin.plan.key', $json$"标识符"$json$::jsonb),
  ('zh-CN', 'admin.plan.keyHint', $json$"小写字母、数字、- 和 _，之后不可更改。"$json$::jsonb),
  ('zh-CN', 'admin.plan.name', $json$"名称"$json$::jsonb),
  ('zh-CN', 'admin.plan.descriptionField', $json$"描述"$json$::jsonb),
  ('zh-CN', 'admin.plan.price', $json$"显示价格"$json$::jsonb),
  ('zh-CN', 'admin.plan.priceHint', $json$"仅用于套餐页面显示，实际扣款以 Stripe 价格为准。"$json$::jsonb),
  ('zh-CN', 'admin.plan.currency', $json$"货币"$json$::jsonb),
  ('zh-CN', 'admin.plan.interval', $json$"计费周期"$json$::jsonb),
  ('zh-CN', 'admin.plan.stripePrice', $json$"Stripe 价格 ID"$json$::jsonb),
  ('zh-CN', 'admin.plan.stripePriceHint', $json$"在 Stripe › 产品目录 › 对应产品 › 价格中（以 price_ 开头）。"$json$::jsonb),
  ('zh-CN', 'admin.plan.active', $json$"在售"$json$::jsonb),
  ('zh-CN', 'admin.plan.activeHint', $json$"关闭后不再在套餐页面显示，已订阅者不受影响。"$json$::jsonb),
  ('zh-CN', 'admin.plan.default', $json$"默认套餐"$json$::jsonb),
  ('zh-CN', 'admin.plan.defaultHint', $json$"免费：适用于所有未订阅的用户。只能有一个默认套餐。"$json$::jsonb),
  ('zh-CN', 'admin.plan.features', $json$"包含的功能"$json$::jsonb),
  ('zh-CN', 'admin.plan.delete', $json$"删除套餐"$json$::jsonb),
  ('zh-CN', 'admin.plan.deleteTitle', $json$"删除套餐 {plan}？"$json$::jsonb),
  ('zh-CN', 'admin.plan.deleteHint', $json$"有订阅者的套餐无法删除，请改为停售。"$json$::jsonb),
  ('zh-CN', 'admin.plan.saved', $json$"套餐 {plan} 已保存。"$json$::jsonb),
  ('zh-CN', 'admin.plan.deleted', $json$"套餐 {plan} 已删除。"$json$::jsonb),
  ('zh-CN', 'admin.error.unknownFeature', $json$"未知功能。"$json$::jsonb),
  ('zh-CN', 'admin.error.planInvalid', $json$"请检查套餐字段：标识符、名称、货币（3 个字母）和价格 ID（price_…）。"$json$::jsonb),
  ('zh-CN', 'admin.error.priceTaken', $json$"该 Stripe 价格已被其他套餐使用。"$json$::jsonb),
  ('zh-CN', 'admin.error.default', $json$"必须有一个默认套餐，且不能删除。"$json$::jsonb),
  ('zh-CN', 'admin.error.inUse', $json$"此套餐仍有订阅者，请停售而不是删除。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.plans.title', $json$"套餐与订阅"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.plans.detail', $json$"新的“套餐”页面展示各套餐包含的内容，并可通过 Stripe 订阅。未订阅的用户继续使用免费套餐，原有功能不受影响。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.adminFeatures.title', $json$"由管理员控制的功能"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.adminFeatures.detail', $json$"组织、统计、门卫面板、实时文件、搜索、项目笔记以及 Jev 的高级选项，现在都可由系统管理员开启或关闭，并纳入各个套餐。"$json$::jsonb),
  ('hi', 'feature.organizations.title', $json$"संगठन"$json$::jsonb),
  ('hi', 'feature.organizations.detail', $json$"संगठन बनाना, सदस्यों को आमंत्रित करना, टीम रिपॉज़िटरी और LLM नीति।"$json$::jsonb),
  ('hi', 'feature.orgChat.title', $json$"संगठन चैट"$json$::jsonb),
  ('hi', 'feature.orgChat.detail', $json$"ऐसे एजेंट से चैट जो संगठन की सभी रिपॉज़िटरी देखता है।"$json$::jsonb),
  ('hi', 'feature.stats.title', $json$"आँकड़े"$json$::jsonb),
  ('hi', 'feature.stats.detail', $json$"टोकन उपयोग, लागत, एजेंट कोटा और प्रोजेक्ट के अनुसार चार्ट।"$json$::jsonb),
  ('hi', 'feature.gateBoard.title', $json$"गेटहाउस बोर्ड"$json$::jsonb),
  ('hi', 'feature.gateBoard.detail', $json$"वह पेज जिसमें प्रोजेक्ट में Jev ने जो कुछ पास किया, पूछा या रोका, सब दिखता है।"$json$::jsonb),
  ('hi', 'feature.liveFiles.title', $json$"लाइव फ़ाइलें"$json$::jsonb),
  ('hi', 'feature.liveFiles.detail', $json$"वह पैनल जो एजेंट के काम करते समय बदली जा रही फ़ाइलें diff के साथ दिखाता है।"$json$::jsonb),
  ('hi', 'feature.chatSearch.title', $json$"चैट खोज"$json$::jsonb),
  ('hi', 'feature.chatSearch.detail', $json$"प्रोजेक्ट की सभी बातचीत में शब्द खोजें।"$json$::jsonb),
  ('hi', 'feature.projectNotes.title', $json$"प्रोजेक्ट नोट्स"$json$::jsonb),
  ('hi', 'feature.projectNotes.detail', $json$"प्रोजेक्ट के बारे में वह जानकारी जो एजेंट को हर नई बातचीत में याद रखनी चाहिए।"$json$::jsonb),
  ('hi', 'feature.adaptiveRouting.title', $json$"अनुकूली रूटिंग"$json$::jsonb),
  ('hi', 'feature.adaptiveRouting.detail', $json$"हर मॉडल का पिछला प्रदर्शन तय करने में गिना जाता है कि जवाब कौन देगा।"$json$::jsonb),
  ('hi', 'feature.secondOpinion.title', $json$"दूसरी राय"$json$::jsonb),
  ('hi', 'feature.secondOpinion.detail', $json$"दूसरे प्रदाता का एजेंट बिल्ड मोड के बदलावों की समीक्षा करता है।"$json$::jsonb),
  ('hi', 'feature.planFirst.title', $json$"बनाने से पहले योजना"$json$::jsonb),
  ('hi', 'feature.planFirst.detail', $json$"जटिल बिल्ड अनुरोध पर, एजेंट के बनाने से पहले एक तर्क मॉडल योजना बनाता है।"$json$::jsonb),
  ('hi', 'feature.parallelTasks.title', $json$"समानांतर एजेंट"$json$::jsonb),
  ('hi', 'feature.parallelTasks.detail', $json$"बड़ा अनुरोध उन एजेंटों में बाँटा जाता है जो git worktrees में एक साथ काम करते हैं।"$json$::jsonb),
  ('hi', 'nav.plans', $json$"प्लान"$json$::jsonb),
  ('hi', 'nav.admin', $json$"प्रशासन"$json$::jsonb),
  ('hi', 'plans.description', $json$"हर प्लान में क्या मिलता है। भुगतान ब्राउज़र में Stripe के ज़रिए खुलता है, और पूरा होने पर JayV अपने-आप अपडेट हो जाता है।"$json$::jsonb),
  ('hi', 'plans.loading', $json$"प्लान लोड हो रहे हैं…"$json$::jsonb),
  ('hi', 'plans.locked', $json$"यह सुविधा आपके प्लान में नहीं है या एडमिन ने इसे बंद कर दिया है।"$json$::jsonb),
  ('hi', 'plans.see', $json$"प्लान देखें"$json$::jsonb),
  ('hi', 'plans.manage', $json$"सदस्यता प्रबंधित करें"$json$::jsonb),
  ('hi', 'plans.current', $json$"आपका प्लान"$json$::jsonb),
  ('hi', 'plans.free', $json$"मुफ़्त"$json$::jsonb),
  ('hi', 'plans.interval.month', $json$"महीना"$json$::jsonb),
  ('hi', 'plans.interval.year', $json$"साल"$json$::jsonb),
  ('hi', 'plans.included', $json$"शामिल"$json$::jsonb),
  ('hi', 'plans.notIncluded', $json$"शामिल नहीं"$json$::jsonb),
  ('hi', 'plans.subscribe', $json$"सदस्यता लें"$json$::jsonb),
  ('hi', 'plans.change', $json$"प्लान बदलें"$json$::jsonb),
  ('hi', 'plans.paid', $json$"भुगतान पूरा हुआ। आपका प्लान कुछ ही पलों में अपडेट होगा।"$json$::jsonb),
  ('hi', 'plans.canceled', $json$"भुगतान रद्द हुआ। कुछ भी नहीं काटा गया।"$json$::jsonb),
  ('hi', 'plans.renewsOn', $json$"{date} को नवीनीकरण होगा।"$json$::jsonb),
  ('hi', 'plans.endsOn', $json$"{date} को समाप्त होगी और नवीनीकृत नहीं होगी।"$json$::jsonb),
  ('hi', 'plans.status.active', $json$"सदस्यता सक्रिय है।"$json$::jsonb),
  ('hi', 'plans.status.trialing', $json$"ट्रायल अवधि।"$json$::jsonb),
  ('hi', 'plans.status.past_due', $json$"पिछला भुगतान विफल रहा। प्लान बनाए रखने के लिए सदस्यता प्रबंधित करें में कार्ड अपडेट करें।"$json$::jsonb),
  ('hi', 'plans.error.config', $json$"सर्वर पर अभी भुगतान सेट नहीं है।"$json$::jsonb),
  ('hi', 'plans.error.plan', $json$"यह प्लान अभी बिक्री के लिए नहीं है।"$json$::jsonb),
  ('hi', 'plans.error.stripe', $json$"Stripe से संपर्क नहीं हो सका। थोड़ी देर में फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'plans.jevLocked', $json$"आपके प्लान में नहीं"$json$::jsonb),
  ('hi', 'admin.eyebrow', $json$"सिस्टम"$json$::jsonb),
  ('hi', 'admin.description', $json$"हर सुविधा को सबके लिए चालू या बंद करें और Stripe से बिकने वाले प्लान बनाएँ।"$json$::jsonb),
  ('hi', 'admin.forbidden', $json$"यह केवल सिस्टम एडमिन कर सकता है।"$json$::jsonb),
  ('hi', 'admin.tab.features', $json$"सुविधाएँ"$json$::jsonb),
  ('hi', 'admin.tab.plans', $json$"प्लान"$json$::jsonb),
  ('hi', 'admin.features.title', $json$"सिस्टम सुविधाएँ"$json$::jsonb),
  ('hi', 'admin.features.description', $json$"यहाँ बंद करने पर सुविधा हर प्लान में सबके लिए गायब हो जाती है।"$json$::jsonb),
  ('hi', 'admin.plans.description', $json$"जिनकी सदस्यता नहीं है वे डिफ़ॉल्ट प्लान पर रहते हैं। हर पेड प्लान के लिए Stripe में एक आवर्ती प्राइस बनाना ज़रूरी है।"$json$::jsonb),
  ('hi', 'admin.plan.new', $json$"नया प्लान"$json$::jsonb),
  ('hi', 'admin.plan.newHint', $json$"बनाने के लिए भरें और सहेजें।"$json$::jsonb),
  ('hi', 'admin.plan.untitled', $json$"बिना नाम का प्लान"$json$::jsonb),
  ('hi', 'admin.plan.subscribers', $json${"one": "{count} सब्सक्राइबर", "other": "{count} सब्सक्राइबर"}$json$::jsonb),
  ('hi', 'admin.plan.defaultBadge', $json$"डिफ़ॉल्ट"$json$::jsonb),
  ('hi', 'admin.plan.inactiveBadge', $json$"बिक्री बंद"$json$::jsonb),
  ('hi', 'admin.plan.key', $json$"पहचानकर्ता"$json$::jsonb),
  ('hi', 'admin.plan.keyHint', $json$"छोटे अक्षर, अंक, - और _। बाद में नहीं बदलता।"$json$::jsonb),
  ('hi', 'admin.plan.name', $json$"नाम"$json$::jsonb),
  ('hi', 'admin.plan.descriptionField', $json$"विवरण"$json$::jsonb),
  ('hi', 'admin.plan.price', $json$"दिखाई गई कीमत"$json$::jsonb),
  ('hi', 'admin.plan.priceHint', $json$"केवल प्लान पेज के लिए: शुल्क Stripe की कीमत से लगता है।"$json$::jsonb),
  ('hi', 'admin.plan.currency', $json$"मुद्रा"$json$::jsonb),
  ('hi', 'admin.plan.interval', $json$"बिलिंग"$json$::jsonb),
  ('hi', 'admin.plan.stripePrice', $json$"Stripe प्राइस ID"$json$::jsonb),
  ('hi', 'admin.plan.stripePriceHint', $json$"Stripe › Product catalog › उत्पाद › Price में (price_ से शुरू)।"$json$::jsonb),
  ('hi', 'admin.plan.active', $json$"बिक्री पर"$json$::jsonb),
  ('hi', 'admin.plan.activeHint', $json$"बंद करने पर प्लान पेज से हट जाता है; मौजूदा सब्सक्राइबर बने रहते हैं।"$json$::jsonb),
  ('hi', 'admin.plan.default', $json$"डिफ़ॉल्ट प्लान"$json$::jsonb),
  ('hi', 'admin.plan.defaultHint', $json$"मुफ़्त: बिना सदस्यता वाले सभी पर लागू। केवल एक प्लान डिफ़ॉल्ट होता है।"$json$::jsonb),
  ('hi', 'admin.plan.features', $json$"शामिल सुविधाएँ"$json$::jsonb),
  ('hi', 'admin.plan.delete', $json$"प्लान हटाएँ"$json$::jsonb),
  ('hi', 'admin.plan.deleteTitle', $json$"{plan} प्लान हटाएँ?"$json$::jsonb),
  ('hi', 'admin.plan.deleteHint', $json$"सब्सक्राइबर वाला प्लान हटाया नहीं जा सकता: उसे बिक्री से हटा दें।"$json$::jsonb),
  ('hi', 'admin.plan.saved', $json$"{plan} प्लान सहेजा गया।"$json$::jsonb),
  ('hi', 'admin.plan.deleted', $json$"{plan} प्लान हटाया गया।"$json$::jsonb),
  ('hi', 'admin.error.unknownFeature', $json$"अज्ञात सुविधा।"$json$::jsonb),
  ('hi', 'admin.error.planInvalid', $json$"प्लान के फ़ील्ड जाँचें: पहचानकर्ता, नाम, मुद्रा (3 अक्षर) और प्राइस ID (price_…)।"$json$::jsonb),
  ('hi', 'admin.error.priceTaken', $json$"यह Stripe प्राइस पहले से दूसरे प्लान में है।"$json$::jsonb),
  ('hi', 'admin.error.default', $json$"एक डिफ़ॉल्ट प्लान होना ज़रूरी है, और उसे हटाया नहीं जा सकता।"$json$::jsonb),
  ('hi', 'admin.error.inUse', $json$"इस प्लान के सब्सक्राइबर हैं। हटाने के बजाय बिक्री से हटाएँ।"$json$::jsonb),
  ('hi', 'whatsNew.item.plans.title', $json$"प्लान और सदस्यता"$json$::jsonb),
  ('hi', 'whatsNew.item.plans.detail', $json$"नया प्लान पेज दिखाता है कि हर प्लान में क्या है और Stripe से सदस्यता लेने देता है। बिना सदस्यता वाले मुफ़्त प्लान पर रहते हैं, जो पहले इस्तेमाल करते थे सब मिलता रहेगा।"$json$::jsonb),
  ('hi', 'whatsNew.item.adminFeatures.title', $json$"एडमिन द्वारा नियंत्रित सुविधाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.adminFeatures.detail', $json$"संगठन, आँकड़े, गेटहाउस बोर्ड, लाइव फ़ाइलें, खोज, प्रोजेक्ट नोट्स और Jev के उन्नत विकल्प अब सिस्टम एडमिन चालू या बंद कर सकता है और हर प्लान में शामिल कर सकता है।"$json$::jsonb),
  ('ar', 'feature.organizations.title', $json$"المؤسسات"$json$::jsonb),
  ('ar', 'feature.organizations.detail', $json$"إنشاء المؤسسات ودعوة الأعضاء ومستودعات الفريق وسياسة LLM."$json$::jsonb),
  ('ar', 'feature.orgChat.title', $json$"دردشة المؤسسة"$json$::jsonb),
  ('ar', 'feature.orgChat.detail', $json$"دردشة مع الوكيل الذي يرى كل مستودعات المؤسسة."$json$::jsonb),
  ('ar', 'feature.stats.title', $json$"الإحصاءات"$json$::jsonb),
  ('ar', 'feature.stats.detail', $json$"استهلاك الرموز والتكلفة وحصص الوكلاء والرسوم البيانية لكل مشروع."$json$::jsonb),
  ('ar', 'feature.gateBoard.title', $json$"لوحة البوابة"$json$::jsonb),
  ('ar', 'feature.gateBoard.detail', $json$"الصفحة التي تعرض كل ما سمح به Jev أو سأل عنه أو حظره في المشروع."$json$::jsonb),
  ('ar', 'feature.liveFiles.title', $json$"الملفات المباشرة"$json$::jsonb),
  ('ar', 'feature.liveFiles.detail', $json$"اللوحة التي تعرض الملفات التي يغيّرها الوكيل مع الفروق أثناء عمله."$json$::jsonb),
  ('ar', 'feature.chatSearch.title', $json$"البحث في الدردشات"$json$::jsonb),
  ('ar', 'feature.chatSearch.detail', $json$"البحث عن كلمات في كل محادثات المشروع."$json$::jsonb),
  ('ar', 'feature.projectNotes.title', $json$"ملاحظات المشروع"$json$::jsonb),
  ('ar', 'feature.projectNotes.detail', $json$"ما يجب أن يتذكره الوكيل عن المشروع في كل محادثة جديدة."$json$::jsonb),
  ('ar', 'feature.adaptiveRouting.title', $json$"التوجيه التكيفي"$json$::jsonb),
  ('ar', 'feature.adaptiveRouting.detail', $json$"يؤثر سجل نجاح كل نموذج في اختيار من يجيب."$json$::jsonb),
  ('ar', 'feature.secondOpinion.title', $json$"رأي ثانٍ"$json$::jsonb),
  ('ar', 'feature.secondOpinion.detail', $json$"يراجع وكيل من مزوّد آخر ما غيّره وضع البناء."$json$::jsonb),
  ('ar', 'feature.planFirst.title', $json$"التخطيط قبل البناء"$json$::jsonb),
  ('ar', 'feature.planFirst.detail', $json$"في طلب بناء معقد، يخطط نموذج استدلال قبل أن يبني الوكيل."$json$::jsonb),
  ('ar', 'feature.parallelTasks.title', $json$"وكلاء بالتوازي"$json$::jsonb),
  ('ar', 'feature.parallelTasks.detail', $json$"يُقسَّم الطلب الكبير بين وكلاء يعملون في الوقت نفسه في git worktrees."$json$::jsonb),
  ('ar', 'nav.plans', $json$"الخطط"$json$::jsonb),
  ('ar', 'nav.admin', $json$"الإدارة"$json$::jsonb),
  ('ar', 'plans.description', $json$"ما تتضمنه كل خطة. يُفتح الدفع في المتصفح عبر Stripe، ويتحدّث JayV تلقائيًا عند انتهائه."$json$::jsonb),
  ('ar', 'plans.loading', $json$"جارٍ تحميل الخطط…"$json$::jsonb),
  ('ar', 'plans.locked', $json$"هذه الميزة ليست ضمن خطتك أو أوقفها المسؤول."$json$::jsonb),
  ('ar', 'plans.see', $json$"عرض الخطط"$json$::jsonb),
  ('ar', 'plans.manage', $json$"إدارة الاشتراك"$json$::jsonb),
  ('ar', 'plans.current', $json$"خطتك"$json$::jsonb),
  ('ar', 'plans.free', $json$"مجاني"$json$::jsonb),
  ('ar', 'plans.interval.month', $json$"شهر"$json$::jsonb),
  ('ar', 'plans.interval.year', $json$"سنة"$json$::jsonb),
  ('ar', 'plans.included', $json$"مضمّن"$json$::jsonb),
  ('ar', 'plans.notIncluded', $json$"غير مضمّن"$json$::jsonb),
  ('ar', 'plans.subscribe', $json$"اشترك"$json$::jsonb),
  ('ar', 'plans.change', $json$"تغيير الخطة"$json$::jsonb),
  ('ar', 'plans.paid', $json$"اكتمل الدفع. ستُحدَّث خطتك خلال لحظات."$json$::jsonb),
  ('ar', 'plans.canceled', $json$"أُلغي الدفع. لم يُخصم أي مبلغ."$json$::jsonb),
  ('ar', 'plans.renewsOn', $json$"يتجدد في {date}."$json$::jsonb),
  ('ar', 'plans.endsOn', $json$"ينتهي في {date} ولن يتجدد."$json$::jsonb),
  ('ar', 'plans.status.active', $json$"الاشتراك نشط."$json$::jsonb),
  ('ar', 'plans.status.trialing', $json$"فترة تجريبية."$json$::jsonb),
  ('ar', 'plans.status.past_due', $json$"فشلت آخر عملية دفع. حدّث بطاقتك من إدارة الاشتراك للاحتفاظ بخطتك."$json$::jsonb),
  ('ar', 'plans.error.config', $json$"لم يُعدّ الدفع على الخادم بعد."$json$::jsonb),
  ('ar', 'plans.error.plan', $json$"هذه الخطة غير متاحة للشراء الآن."$json$::jsonb),
  ('ar', 'plans.error.stripe', $json$"تعذّر الاتصال بـ Stripe. حاول مرة أخرى بعد قليل."$json$::jsonb),
  ('ar', 'plans.jevLocked', $json$"ليست ضمن خطتك"$json$::jsonb),
  ('ar', 'admin.eyebrow', $json$"النظام"$json$::jsonb),
  ('ar', 'admin.description', $json$"شغّل كل ميزة أو أوقفها للجميع وأنشئ الخطط التي تُباع عبر Stripe."$json$::jsonb),
  ('ar', 'admin.forbidden', $json$"لا يمكن لغير مسؤول النظام القيام بذلك."$json$::jsonb),
  ('ar', 'admin.tab.features', $json$"الميزات"$json$::jsonb),
  ('ar', 'admin.tab.plans', $json$"الخطط"$json$::jsonb),
  ('ar', 'admin.features.title', $json$"ميزات النظام"$json$::jsonb),
  ('ar', 'admin.features.description', $json$"عند إيقافها هنا تختفي الميزة للجميع في أي خطة."$json$::jsonb),
  ('ar', 'admin.plans.description', $json$"من لا يشترك يبقى على الخطة الافتراضية. تحتاج كل خطة مدفوعة إلى سعر متكرر يُنشأ في Stripe."$json$::jsonb),
  ('ar', 'admin.plan.new', $json$"خطة جديدة"$json$::jsonb),
  ('ar', 'admin.plan.newHint', $json$"املأ الحقول واحفظ لإنشائها."$json$::jsonb),
  ('ar', 'admin.plan.untitled', $json$"خطة بلا اسم"$json$::jsonb),
  ('ar', 'admin.plan.subscribers', $json${"zero": "لا مشتركين", "one": "مشترك واحد", "two": "مشتركان", "few": "{count} مشتركين", "many": "{count} مشتركًا", "other": "{count} مشترك"}$json$::jsonb),
  ('ar', 'admin.plan.defaultBadge', $json$"افتراضية"$json$::jsonb),
  ('ar', 'admin.plan.inactiveBadge', $json$"غير معروضة للبيع"$json$::jsonb),
  ('ar', 'admin.plan.key', $json$"المعرّف"$json$::jsonb),
  ('ar', 'admin.plan.keyHint', $json$"حروف صغيرة وأرقام و- و_. لا يمكن تغييره لاحقًا."$json$::jsonb),
  ('ar', 'admin.plan.name', $json$"الاسم"$json$::jsonb),
  ('ar', 'admin.plan.descriptionField', $json$"الوصف"$json$::jsonb),
  ('ar', 'admin.plan.price', $json$"السعر المعروض"$json$::jsonb),
  ('ar', 'admin.plan.priceHint', $json$"للعرض في صفحة الخطط فقط: المبلغ المحصّل هو سعر Stripe."$json$::jsonb),
  ('ar', 'admin.plan.currency', $json$"العملة"$json$::jsonb),
  ('ar', 'admin.plan.interval', $json$"الفوترة"$json$::jsonb),
  ('ar', 'admin.plan.stripePrice', $json$"معرّف السعر في Stripe"$json$::jsonb),
  ('ar', 'admin.plan.stripePriceHint', $json$"في Stripe › كتالوج المنتجات › المنتج › السعر (يبدأ بـ price_)."$json$::jsonb),
  ('ar', 'admin.plan.active', $json$"معروضة للبيع"$json$::jsonb),
  ('ar', 'admin.plan.activeHint', $json$"عند الإيقاف تختفي من صفحة الخطط ويحتفظ بها المشتركون الحاليون."$json$::jsonb),
  ('ar', 'admin.plan.default', $json$"الخطة الافتراضية"$json$::jsonb),
  ('ar', 'admin.plan.defaultHint', $json$"مجانية: تنطبق على كل من ليس لديه اشتراك. خطة واحدة فقط تكون الافتراضية."$json$::jsonb),
  ('ar', 'admin.plan.features', $json$"الميزات المضمّنة"$json$::jsonb),
  ('ar', 'admin.plan.delete', $json$"حذف الخطة"$json$::jsonb),
  ('ar', 'admin.plan.deleteTitle', $json$"حذف خطة {plan}؟"$json$::jsonb),
  ('ar', 'admin.plan.deleteHint', $json$"لا يمكن حذف خطة لديها مشتركون: أوقف بيعها بدلًا من ذلك."$json$::jsonb),
  ('ar', 'admin.plan.saved', $json$"حُفظت خطة {plan}."$json$::jsonb),
  ('ar', 'admin.plan.deleted', $json$"حُذفت خطة {plan}."$json$::jsonb),
  ('ar', 'admin.error.unknownFeature', $json$"ميزة غير معروفة."$json$::jsonb),
  ('ar', 'admin.error.planInvalid', $json$"تحقق من حقول الخطة: المعرّف والاسم والعملة (3 أحرف) ومعرّف السعر (price_…)."$json$::jsonb),
  ('ar', 'admin.error.priceTaken', $json$"سعر Stripe هذا مستخدم في خطة أخرى."$json$::jsonb),
  ('ar', 'admin.error.default', $json$"يجب وجود خطة افتراضية، ولا يمكن حذفها."$json$::jsonb),
  ('ar', 'admin.error.inUse', $json$"لهذه الخطة مشتركون. أوقف بيعها بدلًا من حذفها."$json$::jsonb),
  ('ar', 'whatsNew.item.plans.title', $json$"الخطط والاشتراك"$json$::jsonb),
  ('ar', 'whatsNew.item.plans.detail', $json$"تعرض صفحة الخطط الجديدة ما تتضمنه كل خطة وتتيح الاشتراك عبر Stripe. من لا يشترك يبقى على الخطة المجانية مع كل ما كان يستخدمه."$json$::jsonb),
  ('ar', 'whatsNew.item.adminFeatures.title', $json$"ميزات يتحكم بها المسؤول"$json$::jsonb),
  ('ar', 'whatsNew.item.adminFeatures.detail', $json$"أصبح بإمكان مسؤول النظام تشغيل أو إيقاف المؤسسات والإحصاءات ولوحة البوابة والملفات المباشرة والبحث وملاحظات المشروع وخيارات Jev المتقدمة، وتضمينها في كل خطة."$json$::jsonb),
  ('fr', 'feature.organizations.title', $json$"Organisations"$json$::jsonb),
  ('fr', 'feature.organizations.detail', $json$"Créer des organisations, inviter des membres, dépôts de l'équipe et politique LLM."$json$::jsonb),
  ('fr', 'feature.orgChat.title', $json$"Chat de l'organisation"$json$::jsonb),
  ('fr', 'feature.orgChat.detail', $json$"Un chat avec l'agent qui voit tous les dépôts de l'organisation."$json$::jsonb),
  ('fr', 'feature.stats.title', $json$"Statistiques"$json$::jsonb),
  ('fr', 'feature.stats.detail', $json$"Consommation de jetons, coût, quotas des agents et graphiques par projet."$json$::jsonb),
  ('fr', 'feature.gateBoard.title', $json$"Tableau du poste de garde"$json$::jsonb),
  ('fr', 'feature.gateBoard.detail', $json$"La page avec tout ce que Jev a laissé passer, questionné ou bloqué dans le projet."$json$::jsonb),
  ('fr', 'feature.liveFiles.title', $json$"Fichiers en direct"$json$::jsonb),
  ('fr', 'feature.liveFiles.detail', $json$"Le panneau qui montre les fichiers que l'agent modifie, avec le diff, pendant qu'il travaille."$json$::jsonb),
  ('fr', 'feature.chatSearch.title', $json$"Recherche dans les chats"$json$::jsonb),
  ('fr', 'feature.chatSearch.detail', $json$"Chercher des mots dans toutes les conversations du projet."$json$::jsonb),
  ('fr', 'feature.projectNotes.title', $json$"Notes du projet"$json$::jsonb),
  ('fr', 'feature.projectNotes.detail', $json$"Ce que l'agent doit retenir du projet à chaque nouvelle conversation."$json$::jsonb),
  ('fr', 'feature.adaptiveRouting.title', $json$"Routage adaptatif"$json$::jsonb),
  ('fr', 'feature.adaptiveRouting.detail', $json$"L'historique de réussite de chaque modèle pèse dans le choix de qui répond."$json$::jsonb),
  ('fr', 'feature.secondOpinion.title', $json$"Second avis"$json$::jsonb),
  ('fr', 'feature.secondOpinion.detail', $json$"Un agent d'un autre fournisseur relit ce que le mode build a modifié."$json$::jsonb),
  ('fr', 'feature.planFirst.title', $json$"Planifier avant de construire"$json$::jsonb),
  ('fr', 'feature.planFirst.detail', $json$"Pour une demande complexe en mode build, un modèle de raisonnement planifie avant que l'agent construise."$json$::jsonb),
  ('fr', 'feature.parallelTasks.title', $json$"Agents en parallèle"$json$::jsonb),
  ('fr', 'feature.parallelTasks.detail', $json$"Une grosse demande est répartie entre des agents qui travaillent en même temps dans des git worktrees."$json$::jsonb),
  ('fr', 'nav.plans', $json$"Forfaits"$json$::jsonb),
  ('fr', 'nav.admin', $json$"Administration"$json$::jsonb),
  ('fr', 'plans.description', $json$"Ce que comprend chaque forfait. Le paiement s'ouvre dans le navigateur, via Stripe, et JayV se met à jour tout seul à la fin."$json$::jsonb),
  ('fr', 'plans.loading', $json$"Chargement des forfaits…"$json$::jsonb),
  ('fr', 'plans.locked', $json$"Cette fonctionnalité n'est pas dans votre forfait ou a été désactivée par l'administrateur."$json$::jsonb),
  ('fr', 'plans.see', $json$"Voir les forfaits"$json$::jsonb),
  ('fr', 'plans.manage', $json$"Gérer l'abonnement"$json$::jsonb),
  ('fr', 'plans.current', $json$"Votre forfait"$json$::jsonb),
  ('fr', 'plans.free', $json$"Gratuit"$json$::jsonb),
  ('fr', 'plans.interval.month', $json$"mois"$json$::jsonb),
  ('fr', 'plans.interval.year', $json$"an"$json$::jsonb),
  ('fr', 'plans.included', $json$"inclus"$json$::jsonb),
  ('fr', 'plans.notIncluded', $json$"non inclus"$json$::jsonb),
  ('fr', 'plans.subscribe', $json$"S'abonner"$json$::jsonb),
  ('fr', 'plans.change', $json$"Changer de forfait"$json$::jsonb),
  ('fr', 'plans.paid', $json$"Paiement terminé. Votre forfait sera mis à jour dans un instant."$json$::jsonb),
  ('fr', 'plans.canceled', $json$"Paiement annulé. Rien n'a été débité."$json$::jsonb),
  ('fr', 'plans.renewsOn', $json$"Renouvellement le {date}."$json$::jsonb),
  ('fr', 'plans.endsOn', $json$"Se termine le {date} et ne sera pas renouvelé."$json$::jsonb),
  ('fr', 'plans.status.active', $json$"Abonnement actif."$json$::jsonb),
  ('fr', 'plans.status.trialing', $json$"Période d'essai."$json$::jsonb),
  ('fr', 'plans.status.past_due', $json$"Le dernier paiement a échoué. Mettez à jour votre carte dans Gérer l'abonnement pour garder votre forfait."$json$::jsonb),
  ('fr', 'plans.error.config', $json$"Le paiement n'est pas encore configuré sur le serveur."$json$::jsonb),
  ('fr', 'plans.error.plan', $json$"Ce forfait n'est pas en vente pour le moment."$json$::jsonb),
  ('fr', 'plans.error.stripe', $json$"Impossible de joindre Stripe. Réessayez dans un instant."$json$::jsonb),
  ('fr', 'plans.jevLocked', $json$"Hors de votre forfait"$json$::jsonb),
  ('fr', 'admin.eyebrow', $json$"Système"$json$::jsonb),
  ('fr', 'admin.description', $json$"Activez ou désactivez chaque fonctionnalité pour tous et composez les forfaits vendus via Stripe."$json$::jsonb),
  ('fr', 'admin.forbidden', $json$"Seul l'administrateur du système peut faire cela."$json$::jsonb),
  ('fr', 'admin.tab.features', $json$"Fonctionnalités"$json$::jsonb),
  ('fr', 'admin.tab.plans', $json$"Forfaits"$json$::jsonb),
  ('fr', 'admin.features.title', $json$"Fonctionnalités du système"$json$::jsonb),
  ('fr', 'admin.features.description', $json$"Désactivée ici, la fonctionnalité disparaît pour tous, quel que soit le forfait."$json$::jsonb),
  ('fr', 'admin.plans.description', $json$"Sans abonnement, on reste sur le forfait par défaut. Chaque forfait payant a besoin d'un prix récurrent créé dans Stripe."$json$::jsonb),
  ('fr', 'admin.plan.new', $json$"Nouveau forfait"$json$::jsonb),
  ('fr', 'admin.plan.newHint', $json$"Remplissez et enregistrez pour le créer."$json$::jsonb),
  ('fr', 'admin.plan.untitled', $json$"Forfait sans nom"$json$::jsonb),
  ('fr', 'admin.plan.subscribers', $json${"one": "{count} abonné", "other": "{count} abonnés"}$json$::jsonb),
  ('fr', 'admin.plan.defaultBadge', $json$"Par défaut"$json$::jsonb),
  ('fr', 'admin.plan.inactiveBadge', $json$"Hors vente"$json$::jsonb),
  ('fr', 'admin.plan.key', $json$"Identifiant"$json$::jsonb),
  ('fr', 'admin.plan.keyHint', $json$"Minuscules, chiffres, - et _. Non modifiable ensuite."$json$::jsonb),
  ('fr', 'admin.plan.name', $json$"Nom"$json$::jsonb),
  ('fr', 'admin.plan.descriptionField', $json$"Description"$json$::jsonb),
  ('fr', 'admin.plan.price', $json$"Prix affiché"$json$::jsonb),
  ('fr', 'admin.plan.priceHint', $json$"Uniquement pour la page des forfaits : c'est le prix Stripe qui est facturé."$json$::jsonb),
  ('fr', 'admin.plan.currency', $json$"Devise"$json$::jsonb),
  ('fr', 'admin.plan.interval', $json$"Facturation"$json$::jsonb),
  ('fr', 'admin.plan.stripePrice', $json$"ID du prix Stripe"$json$::jsonb),
  ('fr', 'admin.plan.stripePriceHint', $json$"Dans Stripe › Catalogue de produits › le produit › Prix (commence par price_)."$json$::jsonb),
  ('fr', 'admin.plan.active', $json$"En vente"$json$::jsonb),
  ('fr', 'admin.plan.activeHint', $json$"Désactivé, il disparaît de la page des forfaits ; les abonnés actuels le gardent."$json$::jsonb),
  ('fr', 'admin.plan.default', $json$"Forfait par défaut"$json$::jsonb),
  ('fr', 'admin.plan.defaultHint', $json$"Gratuit : s'applique à toute personne sans abonnement. Un seul forfait est par défaut."$json$::jsonb),
  ('fr', 'admin.plan.features', $json$"Fonctionnalités incluses"$json$::jsonb),
  ('fr', 'admin.plan.delete', $json$"Supprimer le forfait"$json$::jsonb),
  ('fr', 'admin.plan.deleteTitle', $json$"Supprimer le forfait {plan} ?"$json$::jsonb),
  ('fr', 'admin.plan.deleteHint', $json$"Un forfait avec des abonnés ne peut pas être supprimé : retirez-le de la vente."$json$::jsonb),
  ('fr', 'admin.plan.saved', $json$"Forfait {plan} enregistré."$json$::jsonb),
  ('fr', 'admin.plan.deleted', $json$"Forfait {plan} supprimé."$json$::jsonb),
  ('fr', 'admin.error.unknownFeature', $json$"Fonctionnalité inconnue."$json$::jsonb),
  ('fr', 'admin.error.planInvalid', $json$"Vérifiez les champs du forfait : identifiant, nom, devise (3 lettres) et ID du prix (price_…)."$json$::jsonb),
  ('fr', 'admin.error.priceTaken', $json$"Ce prix Stripe est déjà utilisé par un autre forfait."$json$::jsonb),
  ('fr', 'admin.error.default', $json$"Il faut un forfait par défaut, et il ne peut pas être supprimé."$json$::jsonb),
  ('fr', 'admin.error.inUse', $json$"Ce forfait a des abonnés. Retirez-le de la vente au lieu de le supprimer."$json$::jsonb),
  ('fr', 'whatsNew.item.plans.title', $json$"Forfaits et abonnement"$json$::jsonb),
  ('fr', 'whatsNew.item.plans.detail', $json$"La nouvelle page Forfaits montre ce que comprend chaque forfait et permet de s'abonner via Stripe. Sans abonnement, on reste sur le forfait gratuit, avec tout ce qu'on utilisait déjà."$json$::jsonb),
  ('fr', 'whatsNew.item.adminFeatures.title', $json$"Fonctionnalités pilotées par l'administrateur"$json$::jsonb),
  ('fr', 'whatsNew.item.adminFeatures.detail', $json$"Organisations, statistiques, tableau du poste de garde, fichiers en direct, recherche, notes du projet et options avancées de Jev peuvent désormais être activés ou désactivés par l'administrateur et inclus dans chaque forfait."$json$::jsonb),
  ('ru', 'feature.organizations.title', $json$"Организации"$json$::jsonb),
  ('ru', 'feature.organizations.detail', $json$"Создание организаций, приглашение участников, репозитории команды и политика LLM."$json$::jsonb),
  ('ru', 'feature.orgChat.title', $json$"Чат организации"$json$::jsonb),
  ('ru', 'feature.orgChat.detail', $json$"Чат с агентом, который видит все репозитории организации."$json$::jsonb),
  ('ru', 'feature.stats.title', $json$"Статистика"$json$::jsonb),
  ('ru', 'feature.stats.detail', $json$"Расход токенов, стоимость, квоты агентов и графики по проектам."$json$::jsonb),
  ('ru', 'feature.gateBoard.title', $json$"Панель проходной"$json$::jsonb),
  ('ru', 'feature.gateBoard.detail', $json$"Страница со всем, что Jev пропустил, уточнил или заблокировал в проекте."$json$::jsonb),
  ('ru', 'feature.liveFiles.title', $json$"Файлы в реальном времени"$json$::jsonb),
  ('ru', 'feature.liveFiles.detail', $json$"Панель, которая показывает файлы, изменяемые агентом, с diff, пока он работает."$json$::jsonb),
  ('ru', 'feature.chatSearch.title', $json$"Поиск по чатам"$json$::jsonb),
  ('ru', 'feature.chatSearch.detail', $json$"Поиск слов во всех беседах проекта."$json$::jsonb),
  ('ru', 'feature.projectNotes.title', $json$"Заметки проекта"$json$::jsonb),
  ('ru', 'feature.projectNotes.detail', $json$"То, что агент должен помнить о проекте в каждой новой беседе."$json$::jsonb),
  ('ru', 'feature.adaptiveRouting.title', $json$"Адаптивная маршрутизация"$json$::jsonb),
  ('ru', 'feature.adaptiveRouting.detail', $json$"История успехов каждой модели влияет на выбор того, кто отвечает."$json$::jsonb),
  ('ru', 'feature.secondOpinion.title', $json$"Второе мнение"$json$::jsonb),
  ('ru', 'feature.secondOpinion.detail', $json$"Агент другого провайдера проверяет изменения режима сборки."$json$::jsonb),
  ('ru', 'feature.planFirst.title', $json$"План перед сборкой"$json$::jsonb),
  ('ru', 'feature.planFirst.detail', $json$"При сложном запросе в режиме сборки модель рассуждений составляет план до того, как агент начнёт работу."$json$::jsonb),
  ('ru', 'feature.parallelTasks.title', $json$"Параллельные агенты"$json$::jsonb),
  ('ru', 'feature.parallelTasks.detail', $json$"Большой запрос делится между агентами, которые работают одновременно в git worktree."$json$::jsonb),
  ('ru', 'nav.plans', $json$"Тарифы"$json$::jsonb),
  ('ru', 'nav.admin', $json$"Администрирование"$json$::jsonb),
  ('ru', 'plans.description', $json$"Что входит в каждый тариф. Оплата открывается в браузере через Stripe, и JayV обновится сам, когда она завершится."$json$::jsonb),
  ('ru', 'plans.loading', $json$"Загрузка тарифов…"$json$::jsonb),
  ('ru', 'plans.locked', $json$"Этой функции нет в вашем тарифе, или администратор её отключил."$json$::jsonb),
  ('ru', 'plans.see', $json$"Посмотреть тарифы"$json$::jsonb),
  ('ru', 'plans.manage', $json$"Управлять подпиской"$json$::jsonb),
  ('ru', 'plans.current', $json$"Ваш тариф"$json$::jsonb),
  ('ru', 'plans.free', $json$"Бесплатно"$json$::jsonb),
  ('ru', 'plans.interval.month', $json$"месяц"$json$::jsonb),
  ('ru', 'plans.interval.year', $json$"год"$json$::jsonb),
  ('ru', 'plans.included', $json$"включено"$json$::jsonb),
  ('ru', 'plans.notIncluded', $json$"не включено"$json$::jsonb),
  ('ru', 'plans.subscribe', $json$"Подписаться"$json$::jsonb),
  ('ru', 'plans.change', $json$"Сменить тариф"$json$::jsonb),
  ('ru', 'plans.paid', $json$"Оплата завершена. Ваш тариф скоро обновится."$json$::jsonb),
  ('ru', 'plans.canceled', $json$"Оплата отменена. Деньги не списаны."$json$::jsonb),
  ('ru', 'plans.renewsOn', $json$"Продление {date}."$json$::jsonb),
  ('ru', 'plans.endsOn', $json$"Заканчивается {date} и не будет продлена."$json$::jsonb),
  ('ru', 'plans.status.active', $json$"Подписка активна."$json$::jsonb),
  ('ru', 'plans.status.trialing', $json$"Пробный период."$json$::jsonb),
  ('ru', 'plans.status.past_due', $json$"Последний платёж не прошёл. Обновите карту в разделе «Управлять подпиской», чтобы сохранить тариф."$json$::jsonb),
  ('ru', 'plans.error.config', $json$"Оплата ещё не настроена на сервере."$json$::jsonb),
  ('ru', 'plans.error.plan', $json$"Этот тариф сейчас недоступен."$json$::jsonb),
  ('ru', 'plans.error.stripe', $json$"Не удалось связаться со Stripe. Повторите попытку чуть позже."$json$::jsonb),
  ('ru', 'plans.jevLocked', $json$"Не входит в ваш тариф"$json$::jsonb),
  ('ru', 'admin.eyebrow', $json$"Система"$json$::jsonb),
  ('ru', 'admin.description', $json$"Включайте и выключайте каждую функцию для всех и настраивайте тарифы, продаваемые через Stripe."$json$::jsonb),
  ('ru', 'admin.forbidden', $json$"Это может сделать только администратор системы."$json$::jsonb),
  ('ru', 'admin.tab.features', $json$"Функции"$json$::jsonb),
  ('ru', 'admin.tab.plans', $json$"Тарифы"$json$::jsonb),
  ('ru', 'admin.features.title', $json$"Функции системы"$json$::jsonb),
  ('ru', 'admin.features.description', $json$"Выключенная здесь функция пропадает у всех, в любом тарифе."$json$::jsonb),
  ('ru', 'admin.plans.description', $json$"Кто не подписан, остаётся на тарифе по умолчанию. Для каждого платного тарифа нужна регулярная цена, созданная в Stripe."$json$::jsonb),
  ('ru', 'admin.plan.new', $json$"Новый тариф"$json$::jsonb),
  ('ru', 'admin.plan.newHint', $json$"Заполните и сохраните, чтобы создать."$json$::jsonb),
  ('ru', 'admin.plan.untitled', $json$"Тариф без названия"$json$::jsonb),
  ('ru', 'admin.plan.subscribers', $json${"one": "{count} подписчик", "few": "{count} подписчика", "many": "{count} подписчиков", "other": "{count} подписчика"}$json$::jsonb),
  ('ru', 'admin.plan.defaultBadge', $json$"По умолчанию"$json$::jsonb),
  ('ru', 'admin.plan.inactiveBadge', $json$"Не продаётся"$json$::jsonb),
  ('ru', 'admin.plan.key', $json$"Идентификатор"$json$::jsonb),
  ('ru', 'admin.plan.keyHint', $json$"Строчные буквы, цифры, - и _. Потом не меняется."$json$::jsonb),
  ('ru', 'admin.plan.name', $json$"Название"$json$::jsonb),
  ('ru', 'admin.plan.descriptionField', $json$"Описание"$json$::jsonb),
  ('ru', 'admin.plan.price', $json$"Отображаемая цена"$json$::jsonb),
  ('ru', 'admin.plan.priceHint', $json$"Только для страницы тарифов: списывается цена из Stripe."$json$::jsonb),
  ('ru', 'admin.plan.currency', $json$"Валюта"$json$::jsonb),
  ('ru', 'admin.plan.interval', $json$"Оплата"$json$::jsonb),
  ('ru', 'admin.plan.stripePrice', $json$"ID цены в Stripe"$json$::jsonb),
  ('ru', 'admin.plan.stripePriceHint', $json$"В Stripe › Каталог товаров › товар › Цена (начинается с price_)."$json$::jsonb),
  ('ru', 'admin.plan.active', $json$"В продаже"$json$::jsonb),
  ('ru', 'admin.plan.activeHint', $json$"Выключенный тариф пропадает со страницы тарифов; текущие подписчики сохраняют его."$json$::jsonb),
  ('ru', 'admin.plan.default', $json$"Тариф по умолчанию"$json$::jsonb),
  ('ru', 'admin.plan.defaultHint', $json$"Бесплатный: действует для всех без подписки. Тариф по умолчанию только один."$json$::jsonb),
  ('ru', 'admin.plan.features', $json$"Включённые функции"$json$::jsonb),
  ('ru', 'admin.plan.delete', $json$"Удалить тариф"$json$::jsonb),
  ('ru', 'admin.plan.deleteTitle', $json$"Удалить тариф {plan}?"$json$::jsonb),
  ('ru', 'admin.plan.deleteHint', $json$"Тариф с подписчиками удалить нельзя: снимите его с продажи."$json$::jsonb),
  ('ru', 'admin.plan.saved', $json$"Тариф {plan} сохранён."$json$::jsonb),
  ('ru', 'admin.plan.deleted', $json$"Тариф {plan} удалён."$json$::jsonb),
  ('ru', 'admin.error.unknownFeature', $json$"Неизвестная функция."$json$::jsonb),
  ('ru', 'admin.error.planInvalid', $json$"Проверьте поля тарифа: идентификатор, название, валюту (3 буквы) и ID цены (price_…)."$json$::jsonb),
  ('ru', 'admin.error.priceTaken', $json$"Эта цена Stripe уже используется в другом тарифе."$json$::jsonb),
  ('ru', 'admin.error.default', $json$"Тариф по умолчанию обязателен, и его нельзя удалить."$json$::jsonb),
  ('ru', 'admin.error.inUse', $json$"У тарифа есть подписчики. Снимите его с продажи вместо удаления."$json$::jsonb),
  ('ru', 'whatsNew.item.plans.title', $json$"Тарифы и подписка"$json$::jsonb),
  ('ru', 'whatsNew.item.plans.detail', $json$"Новая страница «Тарифы» показывает, что входит в каждый тариф, и позволяет подписаться через Stripe. Без подписки вы остаётесь на бесплатном тарифе со всем, чем уже пользовались."$json$::jsonb),
  ('ru', 'whatsNew.item.adminFeatures.title', $json$"Функции под управлением администратора"$json$::jsonb),
  ('ru', 'whatsNew.item.adminFeatures.detail', $json$"Организации, статистику, панель проходной, файлы в реальном времени, поиск, заметки проекта и расширенные параметры Jev теперь может включать и выключать администратор системы и добавлять в каждый тариф."$json$::jsonb),
  ('ja', 'feature.organizations.title', $json$"組織"$json$::jsonb),
  ('ja', 'feature.organizations.detail', $json$"組織の作成、メンバーの招待、チームのリポジトリ、LLM ポリシー。"$json$::jsonb),
  ('ja', 'feature.orgChat.title', $json$"組織チャット"$json$::jsonb),
  ('ja', 'feature.orgChat.detail', $json$"組織のすべてのリポジトリを見渡せるエージェントとのチャット。"$json$::jsonb),
  ('ja', 'feature.stats.title', $json$"統計"$json$::jsonb),
  ('ja', 'feature.stats.detail', $json$"トークン使用量、コスト、エージェントのクォータ、プロジェクト別のグラフ。"$json$::jsonb),
  ('ja', 'feature.gateBoard.title', $json$"ゲートハウスのボード"$json$::jsonb),
  ('ja', 'feature.gateBoard.detail', $json$"プロジェクトで Jev が通した・確認した・止めたものをすべて表示するページ。"$json$::jsonb),
  ('ja', 'feature.liveFiles.title', $json$"ライブファイル"$json$::jsonb),
  ('ja', 'feature.liveFiles.detail', $json$"エージェントの作業中に変更中のファイルと差分を表示するパネル。"$json$::jsonb),
  ('ja', 'feature.chatSearch.title', $json$"チャット検索"$json$::jsonb),
  ('ja', 'feature.chatSearch.detail', $json$"プロジェクトのすべての会話から語句を検索します。"$json$::jsonb),
  ('ja', 'feature.projectNotes.title', $json$"プロジェクトノート"$json$::jsonb),
  ('ja', 'feature.projectNotes.detail', $json$"新しい会話のたびにエージェントが覚えておくべきプロジェクトの情報。"$json$::jsonb),
  ('ja', 'feature.adaptiveRouting.title', $json$"適応ルーティング"$json$::jsonb),
  ('ja', 'feature.adaptiveRouting.detail', $json$"各モデルの実績が、どのモデルが回答するかの選択に反映されます。"$json$::jsonb),
  ('ja', 'feature.secondOpinion.title', $json$"セカンドオピニオン"$json$::jsonb),
  ('ja', 'feature.secondOpinion.detail', $json$"別のプロバイダーのエージェントがビルドモードの変更をレビューします。"$json$::jsonb),
  ('ja', 'feature.planFirst.title', $json$"構築前に計画"$json$::jsonb),
  ('ja', 'feature.planFirst.detail', $json$"複雑なビルド依頼では、エージェントが構築する前に推論モデルが計画を立てます。"$json$::jsonb),
  ('ja', 'feature.parallelTasks.title', $json$"並列エージェント"$json$::jsonb),
  ('ja', 'feature.parallelTasks.detail', $json$"大きな依頼は、git worktree で同時に作業する複数のエージェントに分割されます。"$json$::jsonb),
  ('ja', 'nav.plans', $json$"プラン"$json$::jsonb),
  ('ja', 'nav.admin', $json$"管理"$json$::jsonb),
  ('ja', 'plans.description', $json$"各プランの内容です。支払いはブラウザーで Stripe を通じて開き、完了すると JayV が自動で更新されます。"$json$::jsonb),
  ('ja', 'plans.loading', $json$"プランを読み込み中…"$json$::jsonb),
  ('ja', 'plans.locked', $json$"この機能はご利用のプランに含まれていないか、管理者によって無効にされています。"$json$::jsonb),
  ('ja', 'plans.see', $json$"プランを見る"$json$::jsonb),
  ('ja', 'plans.manage', $json$"サブスクリプションを管理"$json$::jsonb),
  ('ja', 'plans.current', $json$"現在のプラン"$json$::jsonb),
  ('ja', 'plans.free', $json$"無料"$json$::jsonb),
  ('ja', 'plans.interval.month', $json$"月"$json$::jsonb),
  ('ja', 'plans.interval.year', $json$"年"$json$::jsonb),
  ('ja', 'plans.included', $json$"含む"$json$::jsonb),
  ('ja', 'plans.notIncluded', $json$"含まない"$json$::jsonb),
  ('ja', 'plans.subscribe', $json$"申し込む"$json$::jsonb),
  ('ja', 'plans.change', $json$"プランを変更"$json$::jsonb),
  ('ja', 'plans.paid', $json$"支払いが完了しました。まもなくプランが更新されます。"$json$::jsonb),
  ('ja', 'plans.canceled', $json$"支払いはキャンセルされました。請求はありません。"$json$::jsonb),
  ('ja', 'plans.renewsOn', $json$"{date} に更新されます。"$json$::jsonb),
  ('ja', 'plans.endsOn', $json$"{date} に終了し、更新されません。"$json$::jsonb),
  ('ja', 'plans.status.active', $json$"サブスクリプションは有効です。"$json$::jsonb),
  ('ja', 'plans.status.trialing', $json$"試用期間中です。"$json$::jsonb),
  ('ja', 'plans.status.past_due', $json$"前回の支払いに失敗しました。プランを維持するには「サブスクリプションを管理」でカードを更新してください。"$json$::jsonb),
  ('ja', 'plans.error.config', $json$"サーバーで支払いがまだ設定されていません。"$json$::jsonb),
  ('ja', 'plans.error.plan', $json$"このプランは現在販売していません。"$json$::jsonb),
  ('ja', 'plans.error.stripe', $json$"Stripe に接続できませんでした。しばらくしてからもう一度お試しください。"$json$::jsonb),
  ('ja', 'plans.jevLocked', $json$"プラン対象外"$json$::jsonb),
  ('ja', 'admin.eyebrow', $json$"システム"$json$::jsonb),
  ('ja', 'admin.description', $json$"各機能を全員に対してオン・オフし、Stripe で販売するプランを作成します。"$json$::jsonb),
  ('ja', 'admin.forbidden', $json$"これはシステム管理者のみが実行できます。"$json$::jsonb),
  ('ja', 'admin.tab.features', $json$"機能"$json$::jsonb),
  ('ja', 'admin.tab.plans', $json$"プラン"$json$::jsonb),
  ('ja', 'admin.features.title', $json$"システムの機能"$json$::jsonb),
  ('ja', 'admin.features.description', $json$"ここでオフにすると、どのプランでも全員から機能が消えます。"$json$::jsonb),
  ('ja', 'admin.plans.description', $json$"サブスクリプションのない人はデフォルトプランになります。有料プランごとに Stripe で定期価格を作成する必要があります。"$json$::jsonb),
  ('ja', 'admin.plan.new', $json$"新しいプラン"$json$::jsonb),
  ('ja', 'admin.plan.newHint', $json$"入力して保存すると作成されます。"$json$::jsonb),
  ('ja', 'admin.plan.untitled', $json$"名前のないプラン"$json$::jsonb),
  ('ja', 'admin.plan.subscribers', $json${"other": "{count} 人が購読中"}$json$::jsonb),
  ('ja', 'admin.plan.defaultBadge', $json$"デフォルト"$json$::jsonb),
  ('ja', 'admin.plan.inactiveBadge', $json$"販売停止"$json$::jsonb),
  ('ja', 'admin.plan.key', $json$"識別子"$json$::jsonb),
  ('ja', 'admin.plan.keyHint', $json$"小文字・数字・-・_。後から変更できません。"$json$::jsonb),
  ('ja', 'admin.plan.name', $json$"名前"$json$::jsonb),
  ('ja', 'admin.plan.descriptionField', $json$"説明"$json$::jsonb),
  ('ja', 'admin.plan.price', $json$"表示価格"$json$::jsonb),
  ('ja', 'admin.plan.priceHint', $json$"プランページの表示用です。請求は Stripe の価格で行われます。"$json$::jsonb),
  ('ja', 'admin.plan.currency', $json$"通貨"$json$::jsonb),
  ('ja', 'admin.plan.interval', $json$"請求周期"$json$::jsonb),
  ('ja', 'admin.plan.stripePrice', $json$"Stripe の価格 ID"$json$::jsonb),
  ('ja', 'admin.plan.stripePriceHint', $json$"Stripe › 商品カタログ › 該当商品 › 価格（price_ で始まります）。"$json$::jsonb),
  ('ja', 'admin.plan.active', $json$"販売中"$json$::jsonb),
  ('ja', 'admin.plan.activeHint', $json$"オフにするとプランページから消えますが、既存の購読者は継続します。"$json$::jsonb),
  ('ja', 'admin.plan.default', $json$"デフォルトプラン"$json$::jsonb),
  ('ja', 'admin.plan.defaultHint', $json$"無料：サブスクリプションのない全員に適用されます。デフォルトは 1 つだけです。"$json$::jsonb),
  ('ja', 'admin.plan.features', $json$"含まれる機能"$json$::jsonb),
  ('ja', 'admin.plan.delete', $json$"プランを削除"$json$::jsonb),
  ('ja', 'admin.plan.deleteTitle', $json$"プラン「{plan}」を削除しますか？"$json$::jsonb),
  ('ja', 'admin.plan.deleteHint', $json$"購読者のいるプランは削除できません。販売停止にしてください。"$json$::jsonb),
  ('ja', 'admin.plan.saved', $json$"プラン「{plan}」を保存しました。"$json$::jsonb),
  ('ja', 'admin.plan.deleted', $json$"プラン「{plan}」を削除しました。"$json$::jsonb),
  ('ja', 'admin.error.unknownFeature', $json$"不明な機能です。"$json$::jsonb),
  ('ja', 'admin.error.planInvalid', $json$"プランの項目を確認してください：識別子、名前、通貨（3 文字）、価格 ID（price_…）。"$json$::jsonb),
  ('ja', 'admin.error.priceTaken', $json$"この Stripe 価格は別のプランで使用されています。"$json$::jsonb),
  ('ja', 'admin.error.default', $json$"デフォルトプランが必要で、削除はできません。"$json$::jsonb),
  ('ja', 'admin.error.inUse', $json$"このプランには購読者がいます。削除せず販売停止にしてください。"$json$::jsonb),
  ('ja', 'whatsNew.item.plans.title', $json$"プランとサブスクリプション"$json$::jsonb),
  ('ja', 'whatsNew.item.plans.detail', $json$"新しい「プラン」ページで各プランの内容を確認し、Stripe で申し込めます。申し込まない場合は、これまでの機能がそのまま使える無料プランのままです。"$json$::jsonb),
  ('ja', 'whatsNew.item.adminFeatures.title', $json$"管理者が制御する機能"$json$::jsonb),
  ('ja', 'whatsNew.item.adminFeatures.detail', $json$"組織、統計、ゲートハウスのボード、ライブファイル、検索、プロジェクトノート、Jev の高度なオプションを、システム管理者がオン・オフし、各プランに含められるようになりました。"$json$::jsonb),
  ('de', 'feature.organizations.title', $json$"Organisationen"$json$::jsonb),
  ('de', 'feature.organizations.detail', $json$"Organisationen anlegen, Mitglieder einladen, Team-Repositorys und LLM-Richtlinie."$json$::jsonb),
  ('de', 'feature.orgChat.title', $json$"Organisations-Chat"$json$::jsonb),
  ('de', 'feature.orgChat.detail', $json$"Ein Chat mit dem Agenten, der alle Repositorys der Organisation sieht."$json$::jsonb),
  ('de', 'feature.stats.title', $json$"Statistiken"$json$::jsonb),
  ('de', 'feature.stats.detail', $json$"Token-Verbrauch, Kosten, Agenten-Kontingente und Diagramme pro Projekt."$json$::jsonb),
  ('de', 'feature.gateBoard.title', $json$"Pförtner-Übersicht"$json$::jsonb),
  ('de', 'feature.gateBoard.detail', $json$"Die Seite mit allem, was Jev im Projekt durchgelassen, nachgefragt oder blockiert hat."$json$::jsonb),
  ('de', 'feature.liveFiles.title', $json$"Live-Dateien"$json$::jsonb),
  ('de', 'feature.liveFiles.detail', $json$"Das Panel, das die Dateien, die der Agent gerade ändert, mit Diff zeigt, während er arbeitet."$json$::jsonb),
  ('de', 'feature.chatSearch.title', $json$"Chat-Suche"$json$::jsonb),
  ('de', 'feature.chatSearch.detail', $json$"Wörter in allen Unterhaltungen des Projekts suchen."$json$::jsonb),
  ('de', 'feature.projectNotes.title', $json$"Projektnotizen"$json$::jsonb),
  ('de', 'feature.projectNotes.detail', $json$"Was der Agent in jeder neuen Unterhaltung über das Projekt wissen soll."$json$::jsonb),
  ('de', 'feature.adaptiveRouting.title', $json$"Adaptives Routing"$json$::jsonb),
  ('de', 'feature.adaptiveRouting.detail', $json$"Die Erfolgsbilanz jedes Modells fließt in die Wahl ein, wer antwortet."$json$::jsonb),
  ('de', 'feature.secondOpinion.title', $json$"Zweite Meinung"$json$::jsonb),
  ('de', 'feature.secondOpinion.detail', $json$"Ein Agent eines anderen Anbieters prüft, was der Build-Modus geändert hat."$json$::jsonb),
  ('de', 'feature.planFirst.title', $json$"Erst planen, dann bauen"$json$::jsonb),
  ('de', 'feature.planFirst.detail', $json$"Bei einer komplexen Build-Anfrage plant ein Reasoning-Modell, bevor der Agent baut."$json$::jsonb),
  ('de', 'feature.parallelTasks.title', $json$"Parallele Agenten"$json$::jsonb),
  ('de', 'feature.parallelTasks.detail', $json$"Eine große Anfrage wird auf Agenten verteilt, die gleichzeitig in Git-Worktrees arbeiten."$json$::jsonb),
  ('de', 'nav.plans', $json$"Pläne"$json$::jsonb),
  ('de', 'nav.admin', $json$"Verwaltung"$json$::jsonb),
  ('de', 'plans.description', $json$"Was jeder Plan enthält. Die Zahlung öffnet sich im Browser über Stripe, und JayV aktualisiert sich danach von selbst."$json$::jsonb),
  ('de', 'plans.loading', $json$"Pläne werden geladen…"$json$::jsonb),
  ('de', 'plans.locked', $json$"Diese Funktion ist nicht in Ihrem Plan enthalten oder wurde vom Administrator deaktiviert."$json$::jsonb),
  ('de', 'plans.see', $json$"Pläne ansehen"$json$::jsonb),
  ('de', 'plans.manage', $json$"Abo verwalten"$json$::jsonb),
  ('de', 'plans.current', $json$"Ihr Plan"$json$::jsonb),
  ('de', 'plans.free', $json$"Kostenlos"$json$::jsonb),
  ('de', 'plans.interval.month', $json$"Monat"$json$::jsonb),
  ('de', 'plans.interval.year', $json$"Jahr"$json$::jsonb),
  ('de', 'plans.included', $json$"enthalten"$json$::jsonb),
  ('de', 'plans.notIncluded', $json$"nicht enthalten"$json$::jsonb),
  ('de', 'plans.subscribe', $json$"Abonnieren"$json$::jsonb),
  ('de', 'plans.change', $json$"Plan wechseln"$json$::jsonb),
  ('de', 'plans.paid', $json$"Zahlung abgeschlossen. Ihr Plan wird gleich aktualisiert."$json$::jsonb),
  ('de', 'plans.canceled', $json$"Zahlung abgebrochen. Es wurde nichts berechnet."$json$::jsonb),
  ('de', 'plans.renewsOn', $json$"Verlängert sich am {date}."$json$::jsonb),
  ('de', 'plans.endsOn', $json$"Endet am {date} und wird nicht verlängert."$json$::jsonb),
  ('de', 'plans.status.active', $json$"Abo aktiv."$json$::jsonb),
  ('de', 'plans.status.trialing', $json$"Testzeitraum."$json$::jsonb),
  ('de', 'plans.status.past_due', $json$"Die letzte Zahlung ist fehlgeschlagen. Aktualisieren Sie die Karte unter Abo verwalten, um den Plan zu behalten."$json$::jsonb),
  ('de', 'plans.error.config', $json$"Die Zahlung ist auf dem Server noch nicht eingerichtet."$json$::jsonb),
  ('de', 'plans.error.plan', $json$"Dieser Plan ist derzeit nicht erhältlich."$json$::jsonb),
  ('de', 'plans.error.stripe', $json$"Stripe ist nicht erreichbar. Versuchen Sie es gleich noch einmal."$json$::jsonb),
  ('de', 'plans.jevLocked', $json$"Nicht in Ihrem Plan"$json$::jsonb),
  ('de', 'admin.eyebrow', $json$"System"$json$::jsonb),
  ('de', 'admin.description', $json$"Schalten Sie jede Funktion für alle ein oder aus und stellen Sie die über Stripe verkauften Pläne zusammen."$json$::jsonb),
  ('de', 'admin.forbidden', $json$"Das darf nur der Systemadministrator."$json$::jsonb),
  ('de', 'admin.tab.features', $json$"Funktionen"$json$::jsonb),
  ('de', 'admin.tab.plans', $json$"Pläne"$json$::jsonb),
  ('de', 'admin.features.title', $json$"Systemfunktionen"$json$::jsonb),
  ('de', 'admin.features.description', $json$"Hier deaktiviert, verschwindet die Funktion für alle, in jedem Plan."$json$::jsonb),
  ('de', 'admin.plans.description', $json$"Wer kein Abo hat, bleibt im Standardplan. Jeder bezahlte Plan braucht einen in Stripe angelegten wiederkehrenden Preis."$json$::jsonb),
  ('de', 'admin.plan.new', $json$"Neuer Plan"$json$::jsonb),
  ('de', 'admin.plan.newHint', $json$"Ausfüllen und speichern, um ihn anzulegen."$json$::jsonb),
  ('de', 'admin.plan.untitled', $json$"Plan ohne Namen"$json$::jsonb),
  ('de', 'admin.plan.subscribers', $json${"one": "{count} Abonnent", "other": "{count} Abonnenten"}$json$::jsonb),
  ('de', 'admin.plan.defaultBadge', $json$"Standard"$json$::jsonb),
  ('de', 'admin.plan.inactiveBadge', $json$"Nicht im Verkauf"$json$::jsonb),
  ('de', 'admin.plan.key', $json$"Kennung"$json$::jsonb),
  ('de', 'admin.plan.keyHint', $json$"Kleinbuchstaben, Ziffern, - und _. Später nicht änderbar."$json$::jsonb),
  ('de', 'admin.plan.name', $json$"Name"$json$::jsonb),
  ('de', 'admin.plan.descriptionField', $json$"Beschreibung"$json$::jsonb),
  ('de', 'admin.plan.price', $json$"Angezeigter Preis"$json$::jsonb),
  ('de', 'admin.plan.priceHint', $json$"Nur für die Planseite: Berechnet wird der Stripe-Preis."$json$::jsonb),
  ('de', 'admin.plan.currency', $json$"Währung"$json$::jsonb),
  ('de', 'admin.plan.interval', $json$"Abrechnung"$json$::jsonb),
  ('de', 'admin.plan.stripePrice', $json$"Stripe-Preis-ID"$json$::jsonb),
  ('de', 'admin.plan.stripePriceHint', $json$"In Stripe › Produktkatalog › das Produkt › Preis (beginnt mit price_)."$json$::jsonb),
  ('de', 'admin.plan.active', $json$"Im Verkauf"$json$::jsonb),
  ('de', 'admin.plan.activeHint', $json$"Deaktiviert verschwindet er von der Planseite; bestehende Abonnenten behalten ihn."$json$::jsonb),
  ('de', 'admin.plan.default', $json$"Standardplan"$json$::jsonb),
  ('de', 'admin.plan.defaultHint', $json$"Kostenlos: gilt für alle ohne Abo. Nur ein Plan ist der Standard."$json$::jsonb),
  ('de', 'admin.plan.features', $json$"Enthaltene Funktionen"$json$::jsonb),
  ('de', 'admin.plan.delete', $json$"Plan löschen"$json$::jsonb),
  ('de', 'admin.plan.deleteTitle', $json$"Plan {plan} löschen?"$json$::jsonb),
  ('de', 'admin.plan.deleteHint', $json$"Ein Plan mit Abonnenten kann nicht gelöscht werden: Nehmen Sie ihn aus dem Verkauf."$json$::jsonb),
  ('de', 'admin.plan.saved', $json$"Plan {plan} gespeichert."$json$::jsonb),
  ('de', 'admin.plan.deleted', $json$"Plan {plan} gelöscht."$json$::jsonb),
  ('de', 'admin.error.unknownFeature', $json$"Unbekannte Funktion."$json$::jsonb),
  ('de', 'admin.error.planInvalid', $json$"Prüfen Sie die Planfelder: Kennung, Name, Währung (3 Buchstaben) und Preis-ID (price_…)."$json$::jsonb),
  ('de', 'admin.error.priceTaken', $json$"Dieser Stripe-Preis wird bereits von einem anderen Plan verwendet."$json$::jsonb),
  ('de', 'admin.error.default', $json$"Es muss einen Standardplan geben, und er kann nicht gelöscht werden."$json$::jsonb),
  ('de', 'admin.error.inUse', $json$"Dieser Plan hat Abonnenten. Nehmen Sie ihn aus dem Verkauf, statt ihn zu löschen."$json$::jsonb),
  ('de', 'whatsNew.item.plans.title', $json$"Pläne und Abo"$json$::jsonb),
  ('de', 'whatsNew.item.plans.detail', $json$"Die neue Seite Pläne zeigt, was jeder Plan enthält, und abonniert über Stripe. Wer kein Abo hat, bleibt im kostenlosen Plan mit allem, was er schon genutzt hat."$json$::jsonb),
  ('de', 'whatsNew.item.adminFeatures.title', $json$"Vom Administrator gesteuerte Funktionen"$json$::jsonb),
  ('de', 'whatsNew.item.adminFeatures.detail', $json$"Organisationen, Statistiken, Pförtner-Übersicht, Live-Dateien, Suche, Projektnotizen und die erweiterten Jev-Optionen können jetzt vom Systemadministrator ein- oder ausgeschaltet und in jeden Plan aufgenommen werden."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
