-- O agente Cursor (aba de configuração, sandbox, aprovação e limite do
-- plano) e a página de perfil (conta, atividade dos últimos 30 dias), nos dez
-- idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'nav.profile', $json$"Perfil"$json$::jsonb),
  ('pt-BR', 'header.account', $json$"Conta"$json$::jsonb),
  ('pt-BR', 'agent.cursor.tagline', $json$"O agente do Cursor, com sandbox e catálogo de modelos próprios."$json$::jsonb),
  ('pt-BR', 'cursor.sandbox', $json$"Sandbox"$json$::jsonb),
  ('pt-BR', 'cursor.sandbox.default', $json$"Como está no Cursor"$json$::jsonb),
  ('pt-BR', 'cursor.sandbox.default.hint', $json$"Segue a configuração de sandbox do próprio Cursor CLI."$json$::jsonb),
  ('pt-BR', 'cursor.sandbox.enabled', $json$"Ligado"$json$::jsonb),
  ('pt-BR', 'cursor.sandbox.enabled.hint', $json$"Os comandos rodam isolados do resto do computador."$json$::jsonb),
  ('pt-BR', 'cursor.sandbox.disabled', $json$"Desligado (perigoso)"$json$::jsonb),
  ('pt-BR', 'cursor.sandbox.disabled.hint', $json$"Os comandos rodam direto no computador, sem isolamento."$json$::jsonb),
  ('pt-BR', 'cursor.force', $json$"Executar sem aprovação"$json$::jsonb),
  ('pt-BR', 'cursor.force.hint', $json$"Aplica edições e roda comandos sem perguntar. O modo planejamento sempre desliga isto."$json$::jsonb),
  ('pt-BR', 'cursor.approveMcps', $json$"Aprovar servidores MCP"$json$::jsonb),
  ('pt-BR', 'cursor.approveMcps.hint', $json$"Deixa o agente usar todos os servidores MCP configurados no Cursor sem perguntar."$json$::jsonb),
  ('pt-BR', 'settings.field.cursor.sandbox', $json$"o sandbox do Cursor"$json$::jsonb),
  ('pt-BR', 'usage.quota.cursorUnreported', $json$"O Cursor CLI não informa o saldo do plano. Os tokens usados pelo JayV estão contados acima."$json$::jsonb),
  ('pt-BR', 'profile.provider', $json$"Entrou com {provider}"$json$::jsonb),
  ('pt-BR', 'profile.provider.email', $json$"e-mail"$json$::jsonb),
  ('pt-BR', 'profile.memberSince', $json$"Membro desde"$json$::jsonb),
  ('pt-BR', 'profile.lastSignIn', $json$"Último acesso"$json$::jsonb),
  ('pt-BR', 'profile.activity.title', $json$"Sua atividade"$json$::jsonb),
  ('pt-BR', 'profile.activity.description', $json$"Os últimos 30 dias, em todos os projetos."$json$::jsonb),
  ('pt-BR', 'profile.activity.open', $json$"Abrir estatísticas"$json$::jsonb),
  ('pt-BR', 'profile.activity.projects', $json$"Projetos"$json$::jsonb),
  ('pt-BR', 'profile.activity.chats', $json$"Chats"$json$::jsonb),
  ('pt-BR', 'profile.activity.tokens', $json$"Tokens"$json$::jsonb),
  ('en', 'nav.profile', $json$"Profile"$json$::jsonb),
  ('en', 'header.account', $json$"Account"$json$::jsonb),
  ('en', 'agent.cursor.tagline', $json$"Cursor's agent, with its own sandbox and model catalog."$json$::jsonb),
  ('en', 'cursor.sandbox', $json$"Sandbox"$json$::jsonb),
  ('en', 'cursor.sandbox.default', $json$"As configured in Cursor"$json$::jsonb),
  ('en', 'cursor.sandbox.default.hint', $json$"Follows the sandbox setting of the Cursor CLI itself."$json$::jsonb),
  ('en', 'cursor.sandbox.enabled', $json$"Enabled"$json$::jsonb),
  ('en', 'cursor.sandbox.enabled.hint', $json$"Commands run isolated from the rest of the computer."$json$::jsonb),
  ('en', 'cursor.sandbox.disabled', $json$"Disabled (dangerous)"$json$::jsonb),
  ('en', 'cursor.sandbox.disabled.hint', $json$"Commands run directly on the computer, with no isolation."$json$::jsonb),
  ('en', 'cursor.force', $json$"Run without approval"$json$::jsonb),
  ('en', 'cursor.force.hint', $json$"Applies edits and runs commands without asking. Plan mode always turns this off."$json$::jsonb),
  ('en', 'cursor.approveMcps', $json$"Approve MCP servers"$json$::jsonb),
  ('en', 'cursor.approveMcps.hint', $json$"Lets the agent use every MCP server configured in Cursor without asking."$json$::jsonb),
  ('en', 'settings.field.cursor.sandbox', $json$"the Cursor sandbox"$json$::jsonb),
  ('en', 'usage.quota.cursorUnreported', $json$"The Cursor CLI does not report the plan balance. Tokens used through JayV are counted above."$json$::jsonb),
  ('en', 'profile.provider', $json$"Signed in with {provider}"$json$::jsonb),
  ('en', 'profile.provider.email', $json$"email"$json$::jsonb),
  ('en', 'profile.memberSince', $json$"Member since"$json$::jsonb),
  ('en', 'profile.lastSignIn', $json$"Last sign-in"$json$::jsonb),
  ('en', 'profile.activity.title', $json$"Your activity"$json$::jsonb),
  ('en', 'profile.activity.description', $json$"The last 30 days, across all projects."$json$::jsonb),
  ('en', 'profile.activity.open', $json$"Open statistics"$json$::jsonb),
  ('en', 'profile.activity.projects', $json$"Projects"$json$::jsonb),
  ('en', 'profile.activity.chats', $json$"Chats"$json$::jsonb),
  ('en', 'profile.activity.tokens', $json$"Tokens"$json$::jsonb),
  ('es', 'nav.profile', $json$"Perfil"$json$::jsonb),
  ('es', 'header.account', $json$"Cuenta"$json$::jsonb),
  ('es', 'agent.cursor.tagline', $json$"El agente de Cursor, con sandbox y catálogo de modelos propios."$json$::jsonb),
  ('es', 'cursor.sandbox', $json$"Sandbox"$json$::jsonb),
  ('es', 'cursor.sandbox.default', $json$"Como está en Cursor"$json$::jsonb),
  ('es', 'cursor.sandbox.default.hint', $json$"Sigue la configuración de sandbox del propio Cursor CLI."$json$::jsonb),
  ('es', 'cursor.sandbox.enabled', $json$"Activado"$json$::jsonb),
  ('es', 'cursor.sandbox.enabled.hint', $json$"Los comandos se ejecutan aislados del resto del equipo."$json$::jsonb),
  ('es', 'cursor.sandbox.disabled', $json$"Desactivado (peligroso)"$json$::jsonb),
  ('es', 'cursor.sandbox.disabled.hint', $json$"Los comandos se ejecutan directamente en el equipo, sin aislamiento."$json$::jsonb),
  ('es', 'cursor.force', $json$"Ejecutar sin aprobación"$json$::jsonb),
  ('es', 'cursor.force.hint', $json$"Aplica ediciones y ejecuta comandos sin preguntar. El modo planificación siempre lo desactiva."$json$::jsonb),
  ('es', 'cursor.approveMcps', $json$"Aprobar servidores MCP"$json$::jsonb),
  ('es', 'cursor.approveMcps.hint', $json$"Permite que el agente use todos los servidores MCP configurados en Cursor sin preguntar."$json$::jsonb),
  ('es', 'settings.field.cursor.sandbox', $json$"el sandbox de Cursor"$json$::jsonb),
  ('es', 'usage.quota.cursorUnreported', $json$"Cursor CLI no informa el saldo del plan. Los tokens usados a través de JayV se cuentan arriba."$json$::jsonb),
  ('es', 'profile.provider', $json$"Sesión iniciada con {provider}"$json$::jsonb),
  ('es', 'profile.provider.email', $json$"correo electrónico"$json$::jsonb),
  ('es', 'profile.memberSince', $json$"Miembro desde"$json$::jsonb),
  ('es', 'profile.lastSignIn', $json$"Último acceso"$json$::jsonb),
  ('es', 'profile.activity.title', $json$"Tu actividad"$json$::jsonb),
  ('es', 'profile.activity.description', $json$"Los últimos 30 días, en todos los proyectos."$json$::jsonb),
  ('es', 'profile.activity.open', $json$"Abrir estadísticas"$json$::jsonb),
  ('es', 'profile.activity.projects', $json$"Proyectos"$json$::jsonb),
  ('es', 'profile.activity.chats', $json$"Chats"$json$::jsonb),
  ('es', 'profile.activity.tokens', $json$"Tokens"$json$::jsonb),
  ('zh-CN', 'nav.profile', $json$"个人资料"$json$::jsonb),
  ('zh-CN', 'header.account', $json$"账户"$json$::jsonb),
  ('zh-CN', 'agent.cursor.tagline', $json$"Cursor 的代理，拥有自己的沙箱和模型目录。"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox', $json$"沙箱"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox.default', $json$"按 Cursor 中的设置"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox.default.hint', $json$"沿用 Cursor CLI 自身的沙箱设置。"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox.enabled', $json$"启用"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox.enabled.hint', $json$"命令在与计算机其余部分隔离的环境中运行。"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox.disabled', $json$"禁用（危险）"$json$::jsonb),
  ('zh-CN', 'cursor.sandbox.disabled.hint', $json$"命令直接在计算机上运行，没有隔离。"$json$::jsonb),
  ('zh-CN', 'cursor.force', $json$"无需批准即可执行"$json$::jsonb),
  ('zh-CN', 'cursor.force.hint', $json$"无需询问即可应用编辑并执行命令。计划模式始终会关闭此项。"$json$::jsonb),
  ('zh-CN', 'cursor.approveMcps', $json$"批准 MCP 服务器"$json$::jsonb),
  ('zh-CN', 'cursor.approveMcps.hint', $json$"允许代理无需询问即可使用 Cursor 中配置的所有 MCP 服务器。"$json$::jsonb),
  ('zh-CN', 'settings.field.cursor.sandbox', $json$"Cursor 沙箱"$json$::jsonb),
  ('zh-CN', 'usage.quota.cursorUnreported', $json$"Cursor CLI 不提供套餐余额。通过 JayV 使用的令牌已计入上方。"$json$::jsonb),
  ('zh-CN', 'profile.provider', $json$"通过 {provider} 登录"$json$::jsonb),
  ('zh-CN', 'profile.provider.email', $json$"电子邮件"$json$::jsonb),
  ('zh-CN', 'profile.memberSince', $json$"注册时间"$json$::jsonb),
  ('zh-CN', 'profile.lastSignIn', $json$"上次登录"$json$::jsonb),
  ('zh-CN', 'profile.activity.title', $json$"你的活动"$json$::jsonb),
  ('zh-CN', 'profile.activity.description', $json$"最近 30 天，涵盖所有项目。"$json$::jsonb),
  ('zh-CN', 'profile.activity.open', $json$"打开统计"$json$::jsonb),
  ('zh-CN', 'profile.activity.projects', $json$"项目"$json$::jsonb),
  ('zh-CN', 'profile.activity.chats', $json$"对话"$json$::jsonb),
  ('zh-CN', 'profile.activity.tokens', $json$"令牌"$json$::jsonb),
  ('hi', 'nav.profile', $json$"प्रोफ़ाइल"$json$::jsonb),
  ('hi', 'header.account', $json$"खाता"$json$::jsonb),
  ('hi', 'agent.cursor.tagline', $json$"Cursor का एजेंट, अपने सैंडबॉक्स और मॉडल सूची के साथ।"$json$::jsonb),
  ('hi', 'cursor.sandbox', $json$"सैंडबॉक्स"$json$::jsonb),
  ('hi', 'cursor.sandbox.default', $json$"जैसा Cursor में सेट है"$json$::jsonb),
  ('hi', 'cursor.sandbox.default.hint', $json$"Cursor CLI की अपनी सैंडबॉक्स सेटिंग का पालन करता है।"$json$::jsonb),
  ('hi', 'cursor.sandbox.enabled', $json$"चालू"$json$::jsonb),
  ('hi', 'cursor.sandbox.enabled.hint', $json$"कमांड कंप्यूटर के बाकी हिस्से से अलग चलते हैं।"$json$::jsonb),
  ('hi', 'cursor.sandbox.disabled', $json$"बंद (खतरनाक)"$json$::jsonb),
  ('hi', 'cursor.sandbox.disabled.hint', $json$"कमांड बिना अलगाव के सीधे कंप्यूटर पर चलते हैं।"$json$::jsonb),
  ('hi', 'cursor.force', $json$"बिना मंज़ूरी के चलाएँ"$json$::jsonb),
  ('hi', 'cursor.force.hint', $json$"बिना पूछे संपादन लागू करता है और कमांड चलाता है। योजना मोड इसे हमेशा बंद कर देता है।"$json$::jsonb),
  ('hi', 'cursor.approveMcps', $json$"MCP सर्वर मंज़ूर करें"$json$::jsonb),
  ('hi', 'cursor.approveMcps.hint', $json$"एजेंट को Cursor में सेट सभी MCP सर्वर बिना पूछे इस्तेमाल करने देता है।"$json$::jsonb),
  ('hi', 'settings.field.cursor.sandbox', $json$"Cursor का सैंडबॉक्स"$json$::jsonb),
  ('hi', 'usage.quota.cursorUnreported', $json$"Cursor CLI प्लान का बैलेंस नहीं बताता। JayV से इस्तेमाल हुए टोकन ऊपर गिने गए हैं।"$json$::jsonb),
  ('hi', 'profile.provider', $json$"{provider} से साइन इन किया"$json$::jsonb),
  ('hi', 'profile.provider.email', $json$"ईमेल"$json$::jsonb),
  ('hi', 'profile.memberSince', $json$"सदस्य कब से"$json$::jsonb),
  ('hi', 'profile.lastSignIn', $json$"पिछला साइन-इन"$json$::jsonb),
  ('hi', 'profile.activity.title', $json$"आपकी गतिविधि"$json$::jsonb),
  ('hi', 'profile.activity.description', $json$"पिछले 30 दिन, सभी प्रोजेक्ट में।"$json$::jsonb),
  ('hi', 'profile.activity.open', $json$"आँकड़े खोलें"$json$::jsonb),
  ('hi', 'profile.activity.projects', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'profile.activity.chats', $json$"चैट"$json$::jsonb),
  ('hi', 'profile.activity.tokens', $json$"टोकन"$json$::jsonb),
  ('ar', 'nav.profile', $json$"الملف الشخصي"$json$::jsonb),
  ('ar', 'header.account', $json$"الحساب"$json$::jsonb),
  ('ar', 'agent.cursor.tagline', $json$"وكيل Cursor، مع بيئة معزولة وقائمة نماذج خاصة به."$json$::jsonb),
  ('ar', 'cursor.sandbox', $json$"البيئة المعزولة"$json$::jsonb),
  ('ar', 'cursor.sandbox.default', $json$"كما في إعدادات Cursor"$json$::jsonb),
  ('ar', 'cursor.sandbox.default.hint', $json$"يتبع إعداد البيئة المعزولة في Cursor CLI نفسه."$json$::jsonb),
  ('ar', 'cursor.sandbox.enabled', $json$"مفعّلة"$json$::jsonb),
  ('ar', 'cursor.sandbox.enabled.hint', $json$"تعمل الأوامر معزولة عن بقية الحاسوب."$json$::jsonb),
  ('ar', 'cursor.sandbox.disabled', $json$"معطّلة (خطير)"$json$::jsonb),
  ('ar', 'cursor.sandbox.disabled.hint', $json$"تعمل الأوامر مباشرة على الحاسوب دون عزل."$json$::jsonb),
  ('ar', 'cursor.force', $json$"التشغيل دون موافقة"$json$::jsonb),
  ('ar', 'cursor.force.hint', $json$"يطبّق التعديلات ويشغّل الأوامر دون سؤال. وضع التخطيط يعطّل هذا دائمًا."$json$::jsonb),
  ('ar', 'cursor.approveMcps', $json$"الموافقة على خوادم MCP"$json$::jsonb),
  ('ar', 'cursor.approveMcps.hint', $json$"يسمح للوكيل باستخدام كل خوادم MCP المضبوطة في Cursor دون سؤال."$json$::jsonb),
  ('ar', 'settings.field.cursor.sandbox', $json$"البيئة المعزولة في Cursor"$json$::jsonb),
  ('ar', 'usage.quota.cursorUnreported', $json$"لا يعرض Cursor CLI رصيد الخطة. الرموز المستخدمة عبر JayV محسوبة أعلاه."$json$::jsonb),
  ('ar', 'profile.provider', $json$"تم تسجيل الدخول عبر {provider}"$json$::jsonb),
  ('ar', 'profile.provider.email', $json$"البريد الإلكتروني"$json$::jsonb),
  ('ar', 'profile.memberSince', $json$"عضو منذ"$json$::jsonb),
  ('ar', 'profile.lastSignIn', $json$"آخر تسجيل دخول"$json$::jsonb),
  ('ar', 'profile.activity.title', $json$"نشاطك"$json$::jsonb),
  ('ar', 'profile.activity.description', $json$"آخر 30 يومًا، في كل المشاريع."$json$::jsonb),
  ('ar', 'profile.activity.open', $json$"فتح الإحصاءات"$json$::jsonb),
  ('ar', 'profile.activity.projects', $json$"المشاريع"$json$::jsonb),
  ('ar', 'profile.activity.chats', $json$"المحادثات"$json$::jsonb),
  ('ar', 'profile.activity.tokens', $json$"الرموز"$json$::jsonb),
  ('fr', 'nav.profile', $json$"Profil"$json$::jsonb),
  ('fr', 'header.account', $json$"Compte"$json$::jsonb),
  ('fr', 'agent.cursor.tagline', $json$"L'agent de Cursor, avec son propre bac à sable et son catalogue de modèles."$json$::jsonb),
  ('fr', 'cursor.sandbox', $json$"Bac à sable"$json$::jsonb),
  ('fr', 'cursor.sandbox.default', $json$"Selon la configuration de Cursor"$json$::jsonb),
  ('fr', 'cursor.sandbox.default.hint', $json$"Suit le réglage de bac à sable du Cursor CLI lui-même."$json$::jsonb),
  ('fr', 'cursor.sandbox.enabled', $json$"Activé"$json$::jsonb),
  ('fr', 'cursor.sandbox.enabled.hint', $json$"Les commandes s'exécutent isolées du reste de l'ordinateur."$json$::jsonb),
  ('fr', 'cursor.sandbox.disabled', $json$"Désactivé (dangereux)"$json$::jsonb),
  ('fr', 'cursor.sandbox.disabled.hint', $json$"Les commandes s'exécutent directement sur l'ordinateur, sans isolement."$json$::jsonb),
  ('fr', 'cursor.force', $json$"Exécuter sans approbation"$json$::jsonb),
  ('fr', 'cursor.force.hint', $json$"Applique les modifications et exécute les commandes sans demander. Le mode planification désactive toujours cette option."$json$::jsonb),
  ('fr', 'cursor.approveMcps', $json$"Approuver les serveurs MCP"$json$::jsonb),
  ('fr', 'cursor.approveMcps.hint', $json$"Permet à l'agent d'utiliser tous les serveurs MCP configurés dans Cursor sans demander."$json$::jsonb),
  ('fr', 'settings.field.cursor.sandbox', $json$"le bac à sable de Cursor"$json$::jsonb),
  ('fr', 'usage.quota.cursorUnreported', $json$"Le Cursor CLI n'indique pas le solde du forfait. Les jetons utilisés via JayV sont comptés ci-dessus."$json$::jsonb),
  ('fr', 'profile.provider', $json$"Connecté avec {provider}"$json$::jsonb),
  ('fr', 'profile.provider.email', $json$"e-mail"$json$::jsonb),
  ('fr', 'profile.memberSince', $json$"Membre depuis"$json$::jsonb),
  ('fr', 'profile.lastSignIn', $json$"Dernière connexion"$json$::jsonb),
  ('fr', 'profile.activity.title', $json$"Votre activité"$json$::jsonb),
  ('fr', 'profile.activity.description', $json$"Les 30 derniers jours, sur tous les projets."$json$::jsonb),
  ('fr', 'profile.activity.open', $json$"Ouvrir les statistiques"$json$::jsonb),
  ('fr', 'profile.activity.projects', $json$"Projets"$json$::jsonb),
  ('fr', 'profile.activity.chats', $json$"Chats"$json$::jsonb),
  ('fr', 'profile.activity.tokens', $json$"Jetons"$json$::jsonb),
  ('ru', 'nav.profile', $json$"Профиль"$json$::jsonb),
  ('ru', 'header.account', $json$"Аккаунт"$json$::jsonb),
  ('ru', 'agent.cursor.tagline', $json$"Агент Cursor с собственной песочницей и каталогом моделей."$json$::jsonb),
  ('ru', 'cursor.sandbox', $json$"Песочница"$json$::jsonb),
  ('ru', 'cursor.sandbox.default', $json$"Как настроено в Cursor"$json$::jsonb),
  ('ru', 'cursor.sandbox.default.hint', $json$"Следует настройке песочницы самого Cursor CLI."$json$::jsonb),
  ('ru', 'cursor.sandbox.enabled', $json$"Включена"$json$::jsonb),
  ('ru', 'cursor.sandbox.enabled.hint', $json$"Команды выполняются изолированно от остального компьютера."$json$::jsonb),
  ('ru', 'cursor.sandbox.disabled', $json$"Отключена (опасно)"$json$::jsonb),
  ('ru', 'cursor.sandbox.disabled.hint', $json$"Команды выполняются прямо на компьютере, без изоляции."$json$::jsonb),
  ('ru', 'cursor.force', $json$"Выполнять без подтверждения"$json$::jsonb),
  ('ru', 'cursor.force.hint', $json$"Применяет правки и выполняет команды без вопросов. Режим планирования всегда это отключает."$json$::jsonb),
  ('ru', 'cursor.approveMcps', $json$"Одобрять серверы MCP"$json$::jsonb),
  ('ru', 'cursor.approveMcps.hint', $json$"Позволяет агенту без вопросов использовать все серверы MCP, настроенные в Cursor."$json$::jsonb),
  ('ru', 'settings.field.cursor.sandbox', $json$"песочница Cursor"$json$::jsonb),
  ('ru', 'usage.quota.cursorUnreported', $json$"Cursor CLI не сообщает остаток по тарифу. Токены, использованные через JayV, учтены выше."$json$::jsonb),
  ('ru', 'profile.provider', $json$"Вход через {provider}"$json$::jsonb),
  ('ru', 'profile.provider.email', $json$"эл. почта"$json$::jsonb),
  ('ru', 'profile.memberSince', $json$"Участник с"$json$::jsonb),
  ('ru', 'profile.lastSignIn', $json$"Последний вход"$json$::jsonb),
  ('ru', 'profile.activity.title', $json$"Ваша активность"$json$::jsonb),
  ('ru', 'profile.activity.description', $json$"Последние 30 дней по всем проектам."$json$::jsonb),
  ('ru', 'profile.activity.open', $json$"Открыть статистику"$json$::jsonb),
  ('ru', 'profile.activity.projects', $json$"Проекты"$json$::jsonb),
  ('ru', 'profile.activity.chats', $json$"Чаты"$json$::jsonb),
  ('ru', 'profile.activity.tokens', $json$"Токены"$json$::jsonb),
  ('ja', 'nav.profile', $json$"プロフィール"$json$::jsonb),
  ('ja', 'header.account', $json$"アカウント"$json$::jsonb),
  ('ja', 'agent.cursor.tagline', $json$"独自のサンドボックスとモデル一覧を持つ Cursor のエージェント。"$json$::jsonb),
  ('ja', 'cursor.sandbox', $json$"サンドボックス"$json$::jsonb),
  ('ja', 'cursor.sandbox.default', $json$"Cursor の設定どおり"$json$::jsonb),
  ('ja', 'cursor.sandbox.default.hint', $json$"Cursor CLI 自体のサンドボックス設定に従います。"$json$::jsonb),
  ('ja', 'cursor.sandbox.enabled', $json$"有効"$json$::jsonb),
  ('ja', 'cursor.sandbox.enabled.hint', $json$"コマンドはコンピューターの他の部分から隔離されて実行されます。"$json$::jsonb),
  ('ja', 'cursor.sandbox.disabled', $json$"無効（危険）"$json$::jsonb),
  ('ja', 'cursor.sandbox.disabled.hint', $json$"コマンドは隔離なしでコンピューター上で直接実行されます。"$json$::jsonb),
  ('ja', 'cursor.force', $json$"承認なしで実行"$json$::jsonb),
  ('ja', 'cursor.force.hint', $json$"確認せずに編集を適用し、コマンドを実行します。プランモードでは常にオフになります。"$json$::jsonb),
  ('ja', 'cursor.approveMcps', $json$"MCP サーバーを承認"$json$::jsonb),
  ('ja', 'cursor.approveMcps.hint', $json$"Cursor で設定されたすべての MCP サーバーを確認なしでエージェントが使えるようにします。"$json$::jsonb),
  ('ja', 'settings.field.cursor.sandbox', $json$"Cursor のサンドボックス"$json$::jsonb),
  ('ja', 'usage.quota.cursorUnreported', $json$"Cursor CLI はプランの残量を報告しません。JayV 経由で使ったトークンは上に集計されています。"$json$::jsonb),
  ('ja', 'profile.provider', $json$"{provider} でサインイン"$json$::jsonb),
  ('ja', 'profile.provider.email', $json$"メール"$json$::jsonb),
  ('ja', 'profile.memberSince', $json$"登録日"$json$::jsonb),
  ('ja', 'profile.lastSignIn', $json$"最終サインイン"$json$::jsonb),
  ('ja', 'profile.activity.title', $json$"あなたのアクティビティ"$json$::jsonb),
  ('ja', 'profile.activity.description', $json$"直近 30 日間、すべてのプロジェクト。"$json$::jsonb),
  ('ja', 'profile.activity.open', $json$"統計を開く"$json$::jsonb),
  ('ja', 'profile.activity.projects', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'profile.activity.chats', $json$"チャット"$json$::jsonb),
  ('ja', 'profile.activity.tokens', $json$"トークン"$json$::jsonb),
  ('de', 'nav.profile', $json$"Profil"$json$::jsonb),
  ('de', 'header.account', $json$"Konto"$json$::jsonb),
  ('de', 'agent.cursor.tagline', $json$"Der Agent von Cursor, mit eigener Sandbox und eigenem Modellkatalog."$json$::jsonb),
  ('de', 'cursor.sandbox', $json$"Sandbox"$json$::jsonb),
  ('de', 'cursor.sandbox.default', $json$"Wie in Cursor eingestellt"$json$::jsonb),
  ('de', 'cursor.sandbox.default.hint', $json$"Folgt der Sandbox-Einstellung des Cursor CLI selbst."$json$::jsonb),
  ('de', 'cursor.sandbox.enabled', $json$"Aktiviert"$json$::jsonb),
  ('de', 'cursor.sandbox.enabled.hint', $json$"Befehle laufen isoliert vom Rest des Computers."$json$::jsonb),
  ('de', 'cursor.sandbox.disabled', $json$"Deaktiviert (gefährlich)"$json$::jsonb),
  ('de', 'cursor.sandbox.disabled.hint', $json$"Befehle laufen direkt auf dem Computer, ohne Isolation."$json$::jsonb),
  ('de', 'cursor.force', $json$"Ohne Freigabe ausführen"$json$::jsonb),
  ('de', 'cursor.force.hint', $json$"Übernimmt Änderungen und führt Befehle aus, ohne zu fragen. Der Planungsmodus schaltet das immer ab."$json$::jsonb),
  ('de', 'cursor.approveMcps', $json$"MCP-Server freigeben"$json$::jsonb),
  ('de', 'cursor.approveMcps.hint', $json$"Lässt den Agenten alle in Cursor eingerichteten MCP-Server ohne Rückfrage nutzen."$json$::jsonb),
  ('de', 'settings.field.cursor.sandbox', $json$"die Cursor-Sandbox"$json$::jsonb),
  ('de', 'usage.quota.cursorUnreported', $json$"Das Cursor CLI meldet das Planguthaben nicht. Über JayV verbrauchte Tokens sind oben gezählt."$json$::jsonb),
  ('de', 'profile.provider', $json$"Angemeldet mit {provider}"$json$::jsonb),
  ('de', 'profile.provider.email', $json$"E-Mail"$json$::jsonb),
  ('de', 'profile.memberSince', $json$"Mitglied seit"$json$::jsonb),
  ('de', 'profile.lastSignIn', $json$"Letzte Anmeldung"$json$::jsonb),
  ('de', 'profile.activity.title', $json$"Deine Aktivität"$json$::jsonb),
  ('de', 'profile.activity.description', $json$"Die letzten 30 Tage, über alle Projekte."$json$::jsonb),
  ('de', 'profile.activity.open', $json$"Statistiken öffnen"$json$::jsonb),
  ('de', 'profile.activity.projects', $json$"Projekte"$json$::jsonb),
  ('de', 'profile.activity.chats', $json$"Chats"$json$::jsonb),
  ('de', 'profile.activity.tokens', $json$"Tokens"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
