-- Paginação da lista de modelos nas abas dos agentes, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'model.problemElsewhere', $json$"Um modelo em outra página precisa de ajuste."$json$::jsonb),
  ('pt-BR', 'model.problemElsewhere.show', $json$"Mostrar"$json$::jsonb),
  ('pt-BR', 'pager.perPage', $json$"Por página"$json$::jsonb),
  ('pt-BR', 'pager.range', $json$"{from}–{to} de {total}"$json$::jsonb),
  ('pt-BR', 'pager.page', $json$"Página {page} de {pages}"$json$::jsonb),
  ('pt-BR', 'pager.previous', $json$"Página anterior"$json$::jsonb),
  ('pt-BR', 'pager.next', $json$"Próxima página"$json$::jsonb),
  ('en', 'model.problemElsewhere', $json$"A model on another page needs fixing."$json$::jsonb),
  ('en', 'model.problemElsewhere.show', $json$"Show it"$json$::jsonb),
  ('en', 'pager.perPage', $json$"Per page"$json$::jsonb),
  ('en', 'pager.range', $json$"{from}–{to} of {total}"$json$::jsonb),
  ('en', 'pager.page', $json$"Page {page} of {pages}"$json$::jsonb),
  ('en', 'pager.previous', $json$"Previous page"$json$::jsonb),
  ('en', 'pager.next', $json$"Next page"$json$::jsonb),
  ('es', 'model.problemElsewhere', $json$"Un modelo en otra página necesita corrección."$json$::jsonb),
  ('es', 'model.problemElsewhere.show', $json$"Mostrar"$json$::jsonb),
  ('es', 'pager.perPage', $json$"Por página"$json$::jsonb),
  ('es', 'pager.range', $json$"{from}–{to} de {total}"$json$::jsonb),
  ('es', 'pager.page', $json$"Página {page} de {pages}"$json$::jsonb),
  ('es', 'pager.previous', $json$"Página anterior"$json$::jsonb),
  ('es', 'pager.next', $json$"Página siguiente"$json$::jsonb),
  ('zh-CN', 'model.problemElsewhere', $json$"另一页上有模型需要修正。"$json$::jsonb),
  ('zh-CN', 'model.problemElsewhere.show', $json$"查看"$json$::jsonb),
  ('zh-CN', 'pager.perPage', $json$"每页"$json$::jsonb),
  ('zh-CN', 'pager.range', $json$"第 {from}–{to} 项，共 {total} 项"$json$::jsonb),
  ('zh-CN', 'pager.page', $json$"第 {page} 页，共 {pages} 页"$json$::jsonb),
  ('zh-CN', 'pager.previous', $json$"上一页"$json$::jsonb),
  ('zh-CN', 'pager.next', $json$"下一页"$json$::jsonb),
  ('hi', 'model.problemElsewhere', $json$"दूसरे पेज पर एक मॉडल को ठीक करना है।"$json$::jsonb),
  ('hi', 'model.problemElsewhere.show', $json$"दिखाएँ"$json$::jsonb),
  ('hi', 'pager.perPage', $json$"प्रति पेज"$json$::jsonb),
  ('hi', 'pager.range', $json$"{total} में से {from}–{to}"$json$::jsonb),
  ('hi', 'pager.page', $json$"पेज {page} / {pages}"$json$::jsonb),
  ('hi', 'pager.previous', $json$"पिछला पेज"$json$::jsonb),
  ('hi', 'pager.next', $json$"अगला पेज"$json$::jsonb),
  ('ar', 'model.problemElsewhere', $json$"يوجد نموذج في صفحة أخرى يحتاج إلى تصحيح."$json$::jsonb),
  ('ar', 'model.problemElsewhere.show', $json$"اعرضه"$json$::jsonb),
  ('ar', 'pager.perPage', $json$"لكل صفحة"$json$::jsonb),
  ('ar', 'pager.range', $json$"{from}–{to} من {total}"$json$::jsonb),
  ('ar', 'pager.page', $json$"الصفحة {page} من {pages}"$json$::jsonb),
  ('ar', 'pager.previous', $json$"الصفحة السابقة"$json$::jsonb),
  ('ar', 'pager.next', $json$"الصفحة التالية"$json$::jsonb),
  ('fr', 'model.problemElsewhere', $json$"Un modèle sur une autre page doit être corrigé."$json$::jsonb),
  ('fr', 'model.problemElsewhere.show', $json$"Afficher"$json$::jsonb),
  ('fr', 'pager.perPage', $json$"Par page"$json$::jsonb),
  ('fr', 'pager.range', $json$"{from}–{to} sur {total}"$json$::jsonb),
  ('fr', 'pager.page', $json$"Page {page} sur {pages}"$json$::jsonb),
  ('fr', 'pager.previous', $json$"Page précédente"$json$::jsonb),
  ('fr', 'pager.next', $json$"Page suivante"$json$::jsonb),
  ('ru', 'model.problemElsewhere', $json$"Модель на другой странице нужно исправить."$json$::jsonb),
  ('ru', 'model.problemElsewhere.show', $json$"Показать"$json$::jsonb),
  ('ru', 'pager.perPage', $json$"На странице"$json$::jsonb),
  ('ru', 'pager.range', $json$"{from}–{to} из {total}"$json$::jsonb),
  ('ru', 'pager.page', $json$"Страница {page} из {pages}"$json$::jsonb),
  ('ru', 'pager.previous', $json$"Предыдущая страница"$json$::jsonb),
  ('ru', 'pager.next', $json$"Следующая страница"$json$::jsonb),
  ('ja', 'model.problemElsewhere', $json$"別のページのモデルに修正が必要です。"$json$::jsonb),
  ('ja', 'model.problemElsewhere.show', $json$"表示"$json$::jsonb),
  ('ja', 'pager.perPage', $json$"1ページの件数"$json$::jsonb),
  ('ja', 'pager.range', $json$"{total} 件中 {from}–{to} 件"$json$::jsonb),
  ('ja', 'pager.page', $json$"{page} / {pages} ページ"$json$::jsonb),
  ('ja', 'pager.previous', $json$"前のページ"$json$::jsonb),
  ('ja', 'pager.next', $json$"次のページ"$json$::jsonb),
  ('de', 'model.problemElsewhere', $json$"Ein Modell auf einer anderen Seite muss korrigiert werden."$json$::jsonb),
  ('de', 'model.problemElsewhere.show', $json$"Anzeigen"$json$::jsonb),
  ('de', 'pager.perPage', $json$"Pro Seite"$json$::jsonb),
  ('de', 'pager.range', $json$"{from}–{to} von {total}"$json$::jsonb),
  ('de', 'pager.page', $json$"Seite {page} von {pages}"$json$::jsonb),
  ('de', 'pager.previous', $json$"Vorherige Seite"$json$::jsonb),
  ('de', 'pager.next', $json$"Nächste Seite"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
