-- As abas Jev e Aplicativo das configurações, as regras que o núcleo confere
-- ao salvá-las e a busca manual por atualização.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('pt-BR', 'settings.tab.app', $json$"Aplicativo"$json$::jsonb),
  ('pt-BR', 'settings.defaults', $json$"Restaurar padrões"$json$::jsonb),
  ('pt-BR', 'settings.defaults.hint', $json$"Volta as abas Jev e Aplicativo aos valores de partida. Nada é gravado até salvar."$json$::jsonb),
  ('pt-BR', 'complexity.trivial', $json$"Trivial"$json$::jsonb),
  ('pt-BR', 'complexity.simple', $json$"Simples"$json$::jsonb),
  ('pt-BR', 'complexity.medium', $json$"Média"$json$::jsonb),
  ('pt-BR', 'complexity.complex', $json$"Complexa"$json$::jsonb),
  ('pt-BR', 'jev.section.routing', $json$"Roteamento"$json$::jsonb),
  ('pt-BR', 'jev.section.routing.description', $json$"Como o Jev escolhe o agente e o modelo de cada pedido."$json$::jsonb),
  ('pt-BR', 'jev.adaptive', $json$"Roteamento adaptativo"$json$::jsonb),
  ('pt-BR', 'jev.adaptive.hint', $json$"O histórico de cada modelo (acertos e tempo) pesa na escolha."$json$::jsonb),
  ('pt-BR', 'jev.preferLocal', $json$"Preferir modelos locais"$json$::jsonb),
  ('pt-BR', 'jev.preferLocal.hint', $json$"Modelos gratuitos, que rodam na máquina, ganham pontos no roteamento."$json$::jsonb),
  ('pt-BR', 'jev.confidence', $json$"Confiança mínima"$json$::jsonb),
  ('pt-BR', 'jev.confidence.hint', $json$"Abaixo dela o Jev amplia o orçamento e pede ao modelo uma pergunta de esclarecimento."$json$::jsonb),
  ('pt-BR', 'jev.section.budgets', $json$"Orçamento de contexto"$json$::jsonb),
  ('pt-BR', 'jev.section.budgets.description', $json$"Quantos tokens de contexto cada pedido leva, conforme a complexidade que o Jev leu (de {min} a {max})."$json$::jsonb),
  ('pt-BR', 'jev.budget.invalid', $json$"Use um valor entre {min} e {max}."$json$::jsonb),
  ('pt-BR', 'jev.section.cache', $json$"Cache de contexto"$json$::jsonb),
  ('pt-BR', 'jev.section.cache.description', $json$"O contexto montado para um pedido é reaproveitado enquanto os arquivos não mudam, por este tempo."$json$::jsonb),
  ('pt-BR', 'jev.cache', $json$"Validade"$json$::jsonb),
  ('pt-BR', 'jev.cache.off', $json$"Desligado"$json$::jsonb),
  ('pt-BR', 'jev.cache.minutes', $json${"one": "{count} minuto", "other": "{count} minutos"}$json$::jsonb),
  ('pt-BR', 'jev.cache.hours', $json${"one": "{count} hora", "other": "{count} horas"}$json$::jsonb),
  ('pt-BR', 'jev.section.exit', $json$"Portaria de saída"$json$::jsonb),
  ('pt-BR', 'jev.section.exit.description', $json$"O que a portaria faz quando a resposta do modelo pede para ler, escrever um arquivo ou rodar um comando."$json$::jsonb),
  ('pt-BR', 'jev.exit.read', $json$"Ler arquivos"$json$::jsonb),
  ('pt-BR', 'jev.exit.read.hint', $json$"Arquivo só citado na resposta."$json$::jsonb),
  ('pt-BR', 'jev.exit.write', $json$"Escrever arquivos"$json$::jsonb),
  ('pt-BR', 'jev.exit.write.hint', $json$"Arquivo cujo conteúdo a resposta entrega."$json$::jsonb),
  ('pt-BR', 'jev.exit.shell', $json$"Rodar comandos"$json$::jsonb),
  ('pt-BR', 'jev.exit.shell.hint', $json$"Linhas de um bloco de shell na resposta."$json$::jsonb),
  ('pt-BR', 'permission.allow', $json$"Liberar"$json$::jsonb),
  ('pt-BR', 'permission.allow.hint', $json$"Passa sem segurar."$json$::jsonb),
  ('pt-BR', 'permission.ask', $json$"Segurar e mostrar"$json$::jsonb),
  ('pt-BR', 'permission.ask.hint', $json$"Fica na coluna de saída para você conferir."$json$::jsonb),
  ('pt-BR', 'permission.deny', $json$"Bloquear"$json$::jsonb),
  ('pt-BR', 'permission.deny.hint', $json$"Sempre segurado como proibido."$json$::jsonb),
  ('pt-BR', 'jev.section.gate', $json$"Parâmetros da portaria de entrada"$json$::jsonb),
  ('pt-BR', 'jev.section.gate.description', $json$"Vêm do Supabase e valem para todos; aqui só se leem."$json$::jsonb),
  ('pt-BR', 'jev.gate.demand', $json$"Clareza mínima · {scope}"$json$::jsonb),
  ('pt-BR', 'jev.gate.margin', $json$"Margem até barrar"$json$::jsonb),
  ('pt-BR', 'jev.gate.weight', $json$"Peso · {criterion}"$json$::jsonb),
  ('pt-BR', 'jev.gate.noulLine', $json$"Linha do sim/não"$json$::jsonb),
  ('pt-BR', 'app.section.language', $json$"Idioma"$json$::jsonb),
  ('pt-BR', 'app.section.language.description', $json$"O idioma da tela e das respostas do modelo. Sem escolha, vale o do sistema."$json$::jsonb),
  ('pt-BR', 'app.section.privacy', $json$"Privacidade"$json$::jsonb),
  ('pt-BR', 'app.section.privacy.description', $json$"O que nunca entra no contexto enviado aos modelos. Um padrão glob por linha."$json$::jsonb),
  ('pt-BR', 'app.redact', $json$"Ocultar segredos"$json$::jsonb),
  ('pt-BR', 'app.redact.hint', $json$"Chaves, tokens e senhas no contexto viram [REDACTED]."$json$::jsonb),
  ('pt-BR', 'app.deny', $json$"Nunca ler"$json$::jsonb),
  ('pt-BR', 'app.deny.hint', $json$"Arquivos que nenhum modelo vê, e que a portaria sempre segura."$json$::jsonb),
  ('pt-BR', 'app.localOnly', $json$"Só para modelos locais"$json$::jsonb),
  ('pt-BR', 'app.localOnly.hint', $json$"Arquivos que só entram quando o modelo roda na máquina."$json$::jsonb),
  ('pt-BR', 'app.section.version', $json$"Versão"$json$::jsonb),
  ('pt-BR', 'app.version', $json$"JayV {version} instalado."$json$::jsonb),
  ('pt-BR', 'app.updates.hint', $json$"O app procura versões novas sozinho ao abrir; o botão procura agora."$json$::jsonb),
  ('pt-BR', 'app.checkUpdates', $json$"Procurar atualizações"$json$::jsonb),
  ('pt-BR', 'app.checking', $json$"Procurando…"$json$::jsonb),
  ('pt-BR', 'update.latest', $json$"Você já está na versão mais nova."$json$::jsonb),
  ('pt-BR', 'update.checkFailed', $json$"Não foi possível procurar atualizações: {error}"$json$::jsonb),
  ('pt-BR', 'core.confidence', $json$"A confiança mínima precisa ficar entre {min} e {max}."$json$::jsonb),
  ('pt-BR', 'core.budget', $json$"O orçamento de “{level}” precisa ficar entre {min} e {max} tokens."$json$::jsonb),
  ('pt-BR', 'core.cacheTtl', $json$"A validade do cache vai até {max} segundos."$json$::jsonb),
  ('pt-BR', 'core.permission', $json$"Valor inválido para a regra {rule}: “{value}”."$json$::jsonb),
  ('pt-BR', 'core.patternLong', $json$"Cada padrão vai até {max} caracteres."$json$::jsonb),
  ('pt-BR', 'core.patternInvalid', $json$"O padrão “{pattern}” não é um glob válido."$json$::jsonb),
  ('en', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('en', 'settings.tab.app', $json$"App"$json$::jsonb),
  ('en', 'settings.defaults', $json$"Restore defaults"$json$::jsonb),
  ('en', 'settings.defaults.hint', $json$"Puts the Jev and App tabs back to their starting values. Nothing is stored until you save."$json$::jsonb),
  ('en', 'complexity.trivial', $json$"Trivial"$json$::jsonb),
  ('en', 'complexity.simple', $json$"Simple"$json$::jsonb),
  ('en', 'complexity.medium', $json$"Medium"$json$::jsonb),
  ('en', 'complexity.complex', $json$"Complex"$json$::jsonb),
  ('en', 'jev.section.routing', $json$"Routing"$json$::jsonb),
  ('en', 'jev.section.routing.description', $json$"How the Jev picks the agent and model for each request."$json$::jsonb),
  ('en', 'jev.adaptive', $json$"Adaptive routing"$json$::jsonb),
  ('en', 'jev.adaptive.hint', $json$"Each model's track record (successes and speed) weighs in the choice."$json$::jsonb),
  ('en', 'jev.preferLocal', $json$"Prefer local models"$json$::jsonb),
  ('en', 'jev.preferLocal.hint', $json$"Free models that run on this machine score higher in routing."$json$::jsonb),
  ('en', 'jev.confidence', $json$"Minimum confidence"$json$::jsonb),
  ('en', 'jev.confidence.hint', $json$"Below it the Jev widens the budget and asks the model for a clarifying question."$json$::jsonb),
  ('en', 'jev.section.budgets', $json$"Context budget"$json$::jsonb),
  ('en', 'jev.section.budgets.description', $json$"How many context tokens each request carries, by the complexity the Jev read ({min} to {max})."$json$::jsonb),
  ('en', 'jev.budget.invalid', $json$"Use a value between {min} and {max}."$json$::jsonb),
  ('en', 'jev.section.cache', $json$"Context cache"$json$::jsonb),
  ('en', 'jev.section.cache.description', $json$"The context built for a request is reused for this long, as long as the files do not change."$json$::jsonb),
  ('en', 'jev.cache', $json$"Lifetime"$json$::jsonb),
  ('en', 'jev.cache.off', $json$"Off"$json$::jsonb),
  ('en', 'jev.cache.minutes', $json${"one": "{count} minute", "other": "{count} minutes"}$json$::jsonb),
  ('en', 'jev.cache.hours', $json${"one": "{count} hour", "other": "{count} hours"}$json$::jsonb),
  ('en', 'jev.section.exit', $json$"Exit gate"$json$::jsonb),
  ('en', 'jev.section.exit.description', $json$"What the gate does when the model's answer asks to read, write a file or run a command."$json$::jsonb),
  ('en', 'jev.exit.read', $json$"Read files"$json$::jsonb),
  ('en', 'jev.exit.read.hint', $json$"A file the answer only mentions."$json$::jsonb),
  ('en', 'jev.exit.write', $json$"Write files"$json$::jsonb),
  ('en', 'jev.exit.write.hint', $json$"A file whose content the answer delivers."$json$::jsonb),
  ('en', 'jev.exit.shell', $json$"Run commands"$json$::jsonb),
  ('en', 'jev.exit.shell.hint', $json$"Lines of a shell block in the answer."$json$::jsonb),
  ('en', 'permission.allow', $json$"Allow"$json$::jsonb),
  ('en', 'permission.allow.hint', $json$"Passes without holding."$json$::jsonb),
  ('en', 'permission.ask', $json$"Hold and show"$json$::jsonb),
  ('en', 'permission.ask.hint', $json$"Stays in the exit column for you to check."$json$::jsonb),
  ('en', 'permission.deny', $json$"Block"$json$::jsonb),
  ('en', 'permission.deny.hint', $json$"Always held as forbidden."$json$::jsonb),
  ('en', 'jev.section.gate', $json$"Entry gate parameters"$json$::jsonb),
  ('en', 'jev.section.gate.description', $json$"They come from Supabase and apply to everyone; read-only here."$json$::jsonb),
  ('en', 'jev.gate.demand', $json$"Minimum clarity · {scope}"$json$::jsonb),
  ('en', 'jev.gate.margin', $json$"Margin before blocking"$json$::jsonb),
  ('en', 'jev.gate.weight', $json$"Weight · {criterion}"$json$::jsonb),
  ('en', 'jev.gate.noulLine', $json$"Yes/no line"$json$::jsonb),
  ('en', 'app.section.language', $json$"Language"$json$::jsonb),
  ('en', 'app.section.language.description', $json$"The language of the screen and of the model's answers. Without a choice, the system's applies."$json$::jsonb),
  ('en', 'app.section.privacy', $json$"Privacy"$json$::jsonb),
  ('en', 'app.section.privacy.description', $json$"What never enters the context sent to the models. One glob pattern per line."$json$::jsonb),
  ('en', 'app.redact', $json$"Redact secrets"$json$::jsonb),
  ('en', 'app.redact.hint', $json$"Keys, tokens and passwords in the context become [REDACTED]."$json$::jsonb),
  ('en', 'app.deny', $json$"Never read"$json$::jsonb),
  ('en', 'app.deny.hint', $json$"Files no model ever sees, which the gate always holds."$json$::jsonb),
  ('en', 'app.localOnly', $json$"Local models only"$json$::jsonb),
  ('en', 'app.localOnly.hint', $json$"Files that only go in when the model runs on this machine."$json$::jsonb),
  ('en', 'app.section.version', $json$"Version"$json$::jsonb),
  ('en', 'app.version', $json$"JayV {version} installed."$json$::jsonb),
  ('en', 'app.updates.hint', $json$"The app looks for new versions on its own when it opens; the button looks now."$json$::jsonb),
  ('en', 'app.checkUpdates', $json$"Check for updates"$json$::jsonb),
  ('en', 'app.checking', $json$"Checking…"$json$::jsonb),
  ('en', 'update.latest', $json$"You are on the latest version."$json$::jsonb),
  ('en', 'update.checkFailed', $json$"Could not check for updates: {error}"$json$::jsonb),
  ('en', 'core.confidence', $json$"The minimum confidence must be between {min} and {max}."$json$::jsonb),
  ('en', 'core.budget', $json$"The “{level}” budget must be between {min} and {max} tokens."$json$::jsonb),
  ('en', 'core.cacheTtl', $json$"The cache lifetime goes up to {max} seconds."$json$::jsonb),
  ('en', 'core.permission', $json$"Invalid value for the {rule} rule: “{value}”."$json$::jsonb),
  ('en', 'core.patternLong', $json$"Each pattern goes up to {max} characters."$json$::jsonb),
  ('en', 'core.patternInvalid', $json$"The pattern “{pattern}” is not a valid glob."$json$::jsonb),
  ('es', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('es', 'settings.tab.app', $json$"Aplicación"$json$::jsonb),
  ('es', 'settings.defaults', $json$"Restaurar valores predeterminados"$json$::jsonb),
  ('es', 'settings.defaults.hint', $json$"Devuelve las pestañas Jev y Aplicación a sus valores iniciales. No se guarda nada hasta que guardes."$json$::jsonb),
  ('es', 'complexity.trivial', $json$"Trivial"$json$::jsonb),
  ('es', 'complexity.simple', $json$"Sencilla"$json$::jsonb),
  ('es', 'complexity.medium', $json$"Media"$json$::jsonb),
  ('es', 'complexity.complex', $json$"Compleja"$json$::jsonb),
  ('es', 'jev.section.routing', $json$"Enrutamiento"$json$::jsonb),
  ('es', 'jev.section.routing.description', $json$"Cómo el Jev elige el agente y el modelo de cada solicitud."$json$::jsonb),
  ('es', 'jev.adaptive', $json$"Enrutamiento adaptativo"$json$::jsonb),
  ('es', 'jev.adaptive.hint', $json$"El historial de cada modelo (aciertos y tiempo) cuenta en la elección."$json$::jsonb),
  ('es', 'jev.preferLocal', $json$"Preferir modelos locales"$json$::jsonb),
  ('es', 'jev.preferLocal.hint', $json$"Los modelos gratuitos que se ejecutan en la máquina suman puntos en el enrutamiento."$json$::jsonb),
  ('es', 'jev.confidence', $json$"Confianza mínima"$json$::jsonb),
  ('es', 'jev.confidence.hint', $json$"Por debajo, el Jev amplía el presupuesto y pide al modelo una pregunta aclaratoria."$json$::jsonb),
  ('es', 'jev.section.budgets', $json$"Presupuesto de contexto"$json$::jsonb),
  ('es', 'jev.section.budgets.description', $json$"Cuántos tokens de contexto lleva cada solicitud, según la complejidad que leyó el Jev (de {min} a {max})."$json$::jsonb),
  ('es', 'jev.budget.invalid', $json$"Usa un valor entre {min} y {max}."$json$::jsonb),
  ('es', 'jev.section.cache', $json$"Caché de contexto"$json$::jsonb),
  ('es', 'jev.section.cache.description', $json$"El contexto armado para una solicitud se reutiliza durante este tiempo mientras los archivos no cambien."$json$::jsonb),
  ('es', 'jev.cache', $json$"Validez"$json$::jsonb),
  ('es', 'jev.cache.off', $json$"Desactivado"$json$::jsonb),
  ('es', 'jev.cache.minutes', $json${"one": "{count} minuto", "other": "{count} minutos"}$json$::jsonb),
  ('es', 'jev.cache.hours', $json${"one": "{count} hora", "other": "{count} horas"}$json$::jsonb),
  ('es', 'jev.section.exit', $json$"Portería de salida"$json$::jsonb),
  ('es', 'jev.section.exit.description', $json$"Qué hace la portería cuando la respuesta del modelo pide leer, escribir un archivo o ejecutar un comando."$json$::jsonb),
  ('es', 'jev.exit.read', $json$"Leer archivos"$json$::jsonb),
  ('es', 'jev.exit.read.hint', $json$"Archivo que la respuesta solo menciona."$json$::jsonb),
  ('es', 'jev.exit.write', $json$"Escribir archivos"$json$::jsonb),
  ('es', 'jev.exit.write.hint', $json$"Archivo cuyo contenido entrega la respuesta."$json$::jsonb),
  ('es', 'jev.exit.shell', $json$"Ejecutar comandos"$json$::jsonb),
  ('es', 'jev.exit.shell.hint', $json$"Líneas de un bloque de shell en la respuesta."$json$::jsonb),
  ('es', 'permission.allow', $json$"Permitir"$json$::jsonb),
  ('es', 'permission.allow.hint', $json$"Pasa sin retener."$json$::jsonb),
  ('es', 'permission.ask', $json$"Retener y mostrar"$json$::jsonb),
  ('es', 'permission.ask.hint', $json$"Queda en la columna de salida para que lo revises."$json$::jsonb),
  ('es', 'permission.deny', $json$"Bloquear"$json$::jsonb),
  ('es', 'permission.deny.hint', $json$"Siempre retenido como prohibido."$json$::jsonb),
  ('es', 'jev.section.gate', $json$"Parámetros de la portería de entrada"$json$::jsonb),
  ('es', 'jev.section.gate.description', $json$"Vienen de Supabase y se aplican a todos; aquí solo se leen."$json$::jsonb),
  ('es', 'jev.gate.demand', $json$"Claridad mínima · {scope}"$json$::jsonb),
  ('es', 'jev.gate.margin', $json$"Margen antes de bloquear"$json$::jsonb),
  ('es', 'jev.gate.weight', $json$"Peso · {criterion}"$json$::jsonb),
  ('es', 'jev.gate.noulLine', $json$"Umbral de sí/no"$json$::jsonb),
  ('es', 'app.section.language', $json$"Idioma"$json$::jsonb),
  ('es', 'app.section.language.description', $json$"El idioma de la pantalla y de las respuestas del modelo. Sin elección, se usa el del sistema."$json$::jsonb),
  ('es', 'app.section.privacy', $json$"Privacidad"$json$::jsonb),
  ('es', 'app.section.privacy.description', $json$"Lo que nunca entra en el contexto enviado a los modelos. Un patrón glob por línea."$json$::jsonb),
  ('es', 'app.redact', $json$"Ocultar secretos"$json$::jsonb),
  ('es', 'app.redact.hint', $json$"Claves, tokens y contraseñas del contexto se convierten en [REDACTED]."$json$::jsonb),
  ('es', 'app.deny', $json$"Nunca leer"$json$::jsonb),
  ('es', 'app.deny.hint', $json$"Archivos que ningún modelo ve y que la portería siempre retiene."$json$::jsonb),
  ('es', 'app.localOnly', $json$"Solo para modelos locales"$json$::jsonb),
  ('es', 'app.localOnly.hint', $json$"Archivos que solo entran cuando el modelo se ejecuta en la máquina."$json$::jsonb),
  ('es', 'app.section.version', $json$"Versión"$json$::jsonb),
  ('es', 'app.version', $json$"JayV {version} instalado."$json$::jsonb),
  ('es', 'app.updates.hint', $json$"La aplicación busca versiones nuevas al abrirse; el botón busca ahora."$json$::jsonb),
  ('es', 'app.checkUpdates', $json$"Buscar actualizaciones"$json$::jsonb),
  ('es', 'app.checking', $json$"Buscando…"$json$::jsonb),
  ('es', 'update.latest', $json$"Ya tienes la versión más reciente."$json$::jsonb),
  ('es', 'update.checkFailed', $json$"No se pudo buscar actualizaciones: {error}"$json$::jsonb),
  ('es', 'core.confidence', $json$"La confianza mínima debe estar entre {min} y {max}."$json$::jsonb),
  ('es', 'core.budget', $json$"El presupuesto de “{level}” debe estar entre {min} y {max} tokens."$json$::jsonb),
  ('es', 'core.cacheTtl', $json$"La validez de la caché llega hasta {max} segundos."$json$::jsonb),
  ('es', 'core.permission', $json$"Valor no válido para la regla {rule}: “{value}”."$json$::jsonb),
  ('es', 'core.patternLong', $json$"Cada patrón llega hasta {max} caracteres."$json$::jsonb),
  ('es', 'core.patternInvalid', $json$"El patrón “{pattern}” no es un glob válido."$json$::jsonb),
  ('zh-CN', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('zh-CN', 'settings.tab.app', $json$"应用"$json$::jsonb),
  ('zh-CN', 'settings.defaults', $json$"恢复默认值"$json$::jsonb),
  ('zh-CN', 'settings.defaults.hint', $json$"将 Jev 和应用选项卡恢复为初始值。保存之前不会存储任何内容。"$json$::jsonb),
  ('zh-CN', 'complexity.trivial', $json$"简单"$json$::jsonb),
  ('zh-CN', 'complexity.simple', $json$"较简单"$json$::jsonb),
  ('zh-CN', 'complexity.medium', $json$"中等"$json$::jsonb),
  ('zh-CN', 'complexity.complex', $json$"复杂"$json$::jsonb),
  ('zh-CN', 'jev.section.routing', $json$"路由"$json$::jsonb),
  ('zh-CN', 'jev.section.routing.description', $json$"Jev 如何为每个请求选择代理和模型。"$json$::jsonb),
  ('zh-CN', 'jev.adaptive', $json$"自适应路由"$json$::jsonb),
  ('zh-CN', 'jev.adaptive.hint', $json$"每个模型的历史表现（成功率和速度）会影响选择。"$json$::jsonb),
  ('zh-CN', 'jev.preferLocal', $json$"优先使用本地模型"$json$::jsonb),
  ('zh-CN', 'jev.preferLocal.hint', $json$"在本机运行的免费模型在路由中得分更高。"$json$::jsonb),
  ('zh-CN', 'jev.confidence', $json$"最低置信度"$json$::jsonb),
  ('zh-CN', 'jev.confidence.hint', $json$"低于此值时，Jev 会扩大预算并让模型先提出澄清问题。"$json$::jsonb),
  ('zh-CN', 'jev.section.budgets', $json$"上下文预算"$json$::jsonb),
  ('zh-CN', 'jev.section.budgets.description', $json$"每个请求携带的上下文 token 数，按 Jev 判断的复杂度而定（{min} 到 {max}）。"$json$::jsonb),
  ('zh-CN', 'jev.budget.invalid', $json$"请使用 {min} 到 {max} 之间的值。"$json$::jsonb),
  ('zh-CN', 'jev.section.cache', $json$"上下文缓存"$json$::jsonb),
  ('zh-CN', 'jev.section.cache.description', $json$"只要文件未变，为请求构建的上下文会在此时间内复用。"$json$::jsonb),
  ('zh-CN', 'jev.cache', $json$"有效期"$json$::jsonb),
  ('zh-CN', 'jev.cache.off', $json$"关闭"$json$::jsonb),
  ('zh-CN', 'jev.cache.minutes', $json${"other": "{count} 分钟"}$json$::jsonb),
  ('zh-CN', 'jev.cache.hours', $json${"other": "{count} 小时"}$json$::jsonb),
  ('zh-CN', 'jev.section.exit', $json$"出口门"$json$::jsonb),
  ('zh-CN', 'jev.section.exit.description', $json$"当模型的回答要求读取、写入文件或运行命令时，门房如何处理。"$json$::jsonb),
  ('zh-CN', 'jev.exit.read', $json$"读取文件"$json$::jsonb),
  ('zh-CN', 'jev.exit.read.hint', $json$"回答中仅提及的文件。"$json$::jsonb),
  ('zh-CN', 'jev.exit.write', $json$"写入文件"$json$::jsonb),
  ('zh-CN', 'jev.exit.write.hint', $json$"回答给出了其内容的文件。"$json$::jsonb),
  ('zh-CN', 'jev.exit.shell', $json$"运行命令"$json$::jsonb),
  ('zh-CN', 'jev.exit.shell.hint', $json$"回答中 shell 代码块的各行。"$json$::jsonb),
  ('zh-CN', 'permission.allow', $json$"允许"$json$::jsonb),
  ('zh-CN', 'permission.allow.hint', $json$"直接放行。"$json$::jsonb),
  ('zh-CN', 'permission.ask', $json$"拦下并显示"$json$::jsonb),
  ('zh-CN', 'permission.ask.hint', $json$"留在出口栏供你检查。"$json$::jsonb),
  ('zh-CN', 'permission.deny', $json$"阻止"$json$::jsonb),
  ('zh-CN', 'permission.deny.hint', $json$"始终作为禁止项拦下。"$json$::jsonb),
  ('zh-CN', 'jev.section.gate', $json$"入口门参数"$json$::jsonb),
  ('zh-CN', 'jev.section.gate.description', $json$"来自 Supabase，对所有人生效；此处只读。"$json$::jsonb),
  ('zh-CN', 'jev.gate.demand', $json$"最低清晰度 · {scope}"$json$::jsonb),
  ('zh-CN', 'jev.gate.margin', $json$"阻止前的余量"$json$::jsonb),
  ('zh-CN', 'jev.gate.weight', $json$"权重 · {criterion}"$json$::jsonb),
  ('zh-CN', 'jev.gate.noulLine', $json$"是/否阈值"$json$::jsonb),
  ('zh-CN', 'app.section.language', $json$"语言"$json$::jsonb),
  ('zh-CN', 'app.section.language.description', $json$"界面和模型回答所用的语言。未选择时使用系统语言。"$json$::jsonb),
  ('zh-CN', 'app.section.privacy', $json$"隐私"$json$::jsonb),
  ('zh-CN', 'app.section.privacy.description', $json$"永远不会进入发送给模型的上下文的内容。每行一个 glob 模式。"$json$::jsonb),
  ('zh-CN', 'app.redact', $json$"隐藏机密"$json$::jsonb),
  ('zh-CN', 'app.redact.hint', $json$"上下文中的密钥、令牌和密码会被替换为 [REDACTED]。"$json$::jsonb),
  ('zh-CN', 'app.deny', $json$"禁止读取"$json$::jsonb),
  ('zh-CN', 'app.deny.hint', $json$"任何模型都看不到、门房始终拦下的文件。"$json$::jsonb),
  ('zh-CN', 'app.localOnly', $json$"仅限本地模型"$json$::jsonb),
  ('zh-CN', 'app.localOnly.hint', $json$"仅当模型在本机运行时才会加入的文件。"$json$::jsonb),
  ('zh-CN', 'app.section.version', $json$"版本"$json$::jsonb),
  ('zh-CN', 'app.version', $json$"已安装 JayV {version}。"$json$::jsonb),
  ('zh-CN', 'app.updates.hint', $json$"应用打开时会自动检查新版本；此按钮会立即检查。"$json$::jsonb),
  ('zh-CN', 'app.checkUpdates', $json$"检查更新"$json$::jsonb),
  ('zh-CN', 'app.checking', $json$"正在检查…"$json$::jsonb),
  ('zh-CN', 'update.latest', $json$"你已在使用最新版本。"$json$::jsonb),
  ('zh-CN', 'update.checkFailed', $json$"无法检查更新：{error}"$json$::jsonb),
  ('zh-CN', 'core.confidence', $json$"最低置信度必须在 {min} 到 {max} 之间。"$json$::jsonb),
  ('zh-CN', 'core.budget', $json$"“{level}”的预算必须在 {min} 到 {max} 个 token 之间。"$json$::jsonb),
  ('zh-CN', 'core.cacheTtl', $json$"缓存有效期最长 {max} 秒。"$json$::jsonb),
  ('zh-CN', 'core.permission', $json$"规则 {rule} 的值无效：“{value}”。"$json$::jsonb),
  ('zh-CN', 'core.patternLong', $json$"每个模式最多 {max} 个字符。"$json$::jsonb),
  ('zh-CN', 'core.patternInvalid', $json$"模式“{pattern}”不是有效的 glob。"$json$::jsonb),
  ('hi', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('hi', 'settings.tab.app', $json$"ऐप"$json$::jsonb),
  ('hi', 'settings.defaults', $json$"डिफ़ॉल्ट बहाल करें"$json$::jsonb),
  ('hi', 'settings.defaults.hint', $json$"Jev और ऐप टैब को शुरुआती मानों पर लौटाता है। सहेजने तक कुछ भी सहेजा नहीं जाता।"$json$::jsonb),
  ('hi', 'complexity.trivial', $json$"मामूली"$json$::jsonb),
  ('hi', 'complexity.simple', $json$"सरल"$json$::jsonb),
  ('hi', 'complexity.medium', $json$"मध्यम"$json$::jsonb),
  ('hi', 'complexity.complex', $json$"जटिल"$json$::jsonb),
  ('hi', 'jev.section.routing', $json$"रूटिंग"$json$::jsonb),
  ('hi', 'jev.section.routing.description', $json$"Jev हर अनुरोध के लिए एजेंट और मॉडल कैसे चुनता है।"$json$::jsonb),
  ('hi', 'jev.adaptive', $json$"अनुकूली रूटिंग"$json$::jsonb),
  ('hi', 'jev.adaptive.hint', $json$"हर मॉडल का पिछला रिकॉर्ड (सफलता और गति) चुनाव में गिना जाता है।"$json$::jsonb),
  ('hi', 'jev.preferLocal', $json$"स्थानीय मॉडल को प्राथमिकता दें"$json$::jsonb),
  ('hi', 'jev.preferLocal.hint', $json$"इस मशीन पर चलने वाले मुफ़्त मॉडल रूटिंग में ज़्यादा अंक पाते हैं।"$json$::jsonb),
  ('hi', 'jev.confidence', $json$"न्यूनतम विश्वास"$json$::jsonb),
  ('hi', 'jev.confidence.hint', $json$"इससे नीचे Jev बजट बढ़ाता है और मॉडल से स्पष्टीकरण वाला प्रश्न पूछने को कहता है।"$json$::jsonb),
  ('hi', 'jev.section.budgets', $json$"संदर्भ बजट"$json$::jsonb),
  ('hi', 'jev.section.budgets.description', $json$"Jev द्वारा पढ़ी गई जटिलता के अनुसार हर अनुरोध कितने संदर्भ टोकन ले जाता है ({min} से {max})।"$json$::jsonb),
  ('hi', 'jev.budget.invalid', $json$"{min} और {max} के बीच का मान रखें।"$json$::jsonb),
  ('hi', 'jev.section.cache', $json$"संदर्भ कैश"$json$::jsonb),
  ('hi', 'jev.section.cache.description', $json$"किसी अनुरोध के लिए बना संदर्भ इतनी देर तक दोबारा इस्तेमाल होता है, जब तक फ़ाइलें न बदलें।"$json$::jsonb),
  ('hi', 'jev.cache', $json$"वैधता"$json$::jsonb),
  ('hi', 'jev.cache.off', $json$"बंद"$json$::jsonb),
  ('hi', 'jev.cache.minutes', $json${"one": "{count} मिनट", "other": "{count} मिनट"}$json$::jsonb),
  ('hi', 'jev.cache.hours', $json${"one": "{count} घंटा", "other": "{count} घंटे"}$json$::jsonb),
  ('hi', 'jev.section.exit', $json$"निकास द्वार"$json$::jsonb),
  ('hi', 'jev.section.exit.description', $json$"जब मॉडल का उत्तर पढ़ने, फ़ाइल लिखने या कमांड चलाने को कहे, तो द्वार क्या करता है।"$json$::jsonb),
  ('hi', 'jev.exit.read', $json$"फ़ाइलें पढ़ें"$json$::jsonb),
  ('hi', 'jev.exit.read.hint', $json$"उत्तर में केवल उल्लेखित फ़ाइल।"$json$::jsonb),
  ('hi', 'jev.exit.write', $json$"फ़ाइलें लिखें"$json$::jsonb),
  ('hi', 'jev.exit.write.hint', $json$"वह फ़ाइल जिसकी सामग्री उत्तर देता है।"$json$::jsonb),
  ('hi', 'jev.exit.shell', $json$"कमांड चलाएँ"$json$::jsonb),
  ('hi', 'jev.exit.shell.hint', $json$"उत्तर में shell ब्लॉक की पंक्तियाँ।"$json$::jsonb),
  ('hi', 'permission.allow', $json$"अनुमति दें"$json$::jsonb),
  ('hi', 'permission.allow.hint', $json$"बिना रोके जाने दें।"$json$::jsonb),
  ('hi', 'permission.ask', $json$"रोकें और दिखाएँ"$json$::jsonb),
  ('hi', 'permission.ask.hint', $json$"आपकी जाँच के लिए निकास कॉलम में रहता है।"$json$::jsonb),
  ('hi', 'permission.deny', $json$"रोकें"$json$::jsonb),
  ('hi', 'permission.deny.hint', $json$"हमेशा निषिद्ध मानकर रोका जाता है।"$json$::jsonb),
  ('hi', 'jev.section.gate', $json$"प्रवेश द्वार के पैरामीटर"$json$::jsonb),
  ('hi', 'jev.section.gate.description', $json$"ये Supabase से आते हैं और सभी पर लागू होते हैं; यहाँ केवल पढ़ने के लिए।"$json$::jsonb),
  ('hi', 'jev.gate.demand', $json$"न्यूनतम स्पष्टता · {scope}"$json$::jsonb),
  ('hi', 'jev.gate.margin', $json$"रोकने से पहले का अंतर"$json$::jsonb),
  ('hi', 'jev.gate.weight', $json$"भार · {criterion}"$json$::jsonb),
  ('hi', 'jev.gate.noulLine', $json$"हाँ/नहीं सीमा"$json$::jsonb),
  ('hi', 'app.section.language', $json$"भाषा"$json$::jsonb),
  ('hi', 'app.section.language.description', $json$"स्क्रीन और मॉडल के उत्तरों की भाषा। चयन न होने पर सिस्टम की भाषा लागू होती है।"$json$::jsonb),
  ('hi', 'app.section.privacy', $json$"गोपनीयता"$json$::jsonb),
  ('hi', 'app.section.privacy.description', $json$"जो कभी भी मॉडलों को भेजे गए संदर्भ में नहीं जाता। हर पंक्ति में एक glob पैटर्न।"$json$::jsonb),
  ('hi', 'app.redact', $json$"रहस्य छिपाएँ"$json$::jsonb),
  ('hi', 'app.redact.hint', $json$"संदर्भ में कुंजियाँ, टोकन और पासवर्ड [REDACTED] बन जाते हैं।"$json$::jsonb),
  ('hi', 'app.deny', $json$"कभी न पढ़ें"$json$::jsonb),
  ('hi', 'app.deny.hint', $json$"वे फ़ाइलें जिन्हें कोई मॉडल नहीं देखता और द्वार हमेशा रोकता है।"$json$::jsonb),
  ('hi', 'app.localOnly', $json$"केवल स्थानीय मॉडल"$json$::jsonb),
  ('hi', 'app.localOnly.hint', $json$"वे फ़ाइलें जो तभी जाती हैं जब मॉडल इसी मशीन पर चले।"$json$::jsonb),
  ('hi', 'app.section.version', $json$"संस्करण"$json$::jsonb),
  ('hi', 'app.version', $json$"JayV {version} इंस्टॉल है।"$json$::jsonb),
  ('hi', 'app.updates.hint', $json$"ऐप खुलते ही नए संस्करण खुद खोजता है; यह बटन अभी खोजता है।"$json$::jsonb),
  ('hi', 'app.checkUpdates', $json$"अपडेट खोजें"$json$::jsonb),
  ('hi', 'app.checking', $json$"खोज रहे हैं…"$json$::jsonb),
  ('hi', 'update.latest', $json$"आप नवीनतम संस्करण पर हैं।"$json$::jsonb),
  ('hi', 'update.checkFailed', $json$"अपडेट नहीं खोजे जा सके: {error}"$json$::jsonb),
  ('hi', 'core.confidence', $json$"न्यूनतम विश्वास {min} और {max} के बीच होना चाहिए।"$json$::jsonb),
  ('hi', 'core.budget', $json$"“{level}” का बजट {min} और {max} टोकन के बीच होना चाहिए।"$json$::jsonb),
  ('hi', 'core.cacheTtl', $json$"कैश की वैधता अधिकतम {max} सेकंड है।"$json$::jsonb),
  ('hi', 'core.permission', $json$"{rule} नियम के लिए अमान्य मान: “{value}”।"$json$::jsonb),
  ('hi', 'core.patternLong', $json$"हर पैटर्न अधिकतम {max} अक्षरों का हो सकता है।"$json$::jsonb),
  ('hi', 'core.patternInvalid', $json$"पैटर्न “{pattern}” मान्य glob नहीं है।"$json$::jsonb),
  ('ar', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('ar', 'settings.tab.app', $json$"التطبيق"$json$::jsonb),
  ('ar', 'settings.defaults', $json$"استعادة الإعدادات الافتراضية"$json$::jsonb),
  ('ar', 'settings.defaults.hint', $json$"يعيد علامتي Jev والتطبيق إلى قيمهما الأولية. لا يُحفظ شيء حتى تحفظ."$json$::jsonb),
  ('ar', 'complexity.trivial', $json$"بسيط جدًا"$json$::jsonb),
  ('ar', 'complexity.simple', $json$"بسيط"$json$::jsonb),
  ('ar', 'complexity.medium', $json$"متوسط"$json$::jsonb),
  ('ar', 'complexity.complex', $json$"معقّد"$json$::jsonb),
  ('ar', 'jev.section.routing', $json$"التوجيه"$json$::jsonb),
  ('ar', 'jev.section.routing.description', $json$"كيف يختار Jev الوكيل والنموذج لكل طلب."$json$::jsonb),
  ('ar', 'jev.adaptive', $json$"التوجيه التكيّفي"$json$::jsonb),
  ('ar', 'jev.adaptive.hint', $json$"يُؤخذ سجل كل نموذج (النجاحات والسرعة) في الاعتبار عند الاختيار."$json$::jsonb),
  ('ar', 'jev.preferLocal', $json$"تفضيل النماذج المحلية"$json$::jsonb),
  ('ar', 'jev.preferLocal.hint', $json$"تحصل النماذج المجانية التي تعمل على هذا الجهاز على نقاط أعلى في التوجيه."$json$::jsonb),
  ('ar', 'jev.confidence', $json$"الحد الأدنى للثقة"$json$::jsonb),
  ('ar', 'jev.confidence.hint', $json$"تحتها يوسّع Jev الميزانية ويطلب من النموذج سؤالًا توضيحيًا."$json$::jsonb),
  ('ar', 'jev.section.budgets', $json$"ميزانية السياق"$json$::jsonb),
  ('ar', 'jev.section.budgets.description', $json$"عدد رموز السياق التي يحملها كل طلب حسب التعقيد الذي قرأه Jev (من {min} إلى {max})."$json$::jsonb),
  ('ar', 'jev.budget.invalid', $json$"استخدم قيمة بين {min} و{max}."$json$::jsonb),
  ('ar', 'jev.section.cache', $json$"ذاكرة السياق المؤقتة"$json$::jsonb),
  ('ar', 'jev.section.cache.description', $json$"يُعاد استخدام السياق المبني لطلب ما طوال هذه المدة ما دامت الملفات لم تتغيّر."$json$::jsonb),
  ('ar', 'jev.cache', $json$"مدة الصلاحية"$json$::jsonb),
  ('ar', 'jev.cache.off', $json$"متوقف"$json$::jsonb),
  ('ar', 'jev.cache.minutes', $json${"zero": "{count} دقيقة", "one": "دقيقة واحدة", "two": "دقيقتان", "few": "{count} دقائق", "many": "{count} دقيقة", "other": "{count} دقيقة"}$json$::jsonb),
  ('ar', 'jev.cache.hours', $json${"zero": "{count} ساعة", "one": "ساعة واحدة", "two": "ساعتان", "few": "{count} ساعات", "many": "{count} ساعة", "other": "{count} ساعة"}$json$::jsonb),
  ('ar', 'jev.section.exit', $json$"بوابة الخروج"$json$::jsonb),
  ('ar', 'jev.section.exit.description', $json$"ما تفعله البوابة حين تطلب إجابة النموذج القراءة أو كتابة ملف أو تشغيل أمر."$json$::jsonb),
  ('ar', 'jev.exit.read', $json$"قراءة الملفات"$json$::jsonb),
  ('ar', 'jev.exit.read.hint', $json$"ملف تذكره الإجابة فقط."$json$::jsonb),
  ('ar', 'jev.exit.write', $json$"كتابة الملفات"$json$::jsonb),
  ('ar', 'jev.exit.write.hint', $json$"ملف تقدّم الإجابة محتواه."$json$::jsonb),
  ('ar', 'jev.exit.shell', $json$"تشغيل الأوامر"$json$::jsonb),
  ('ar', 'jev.exit.shell.hint', $json$"أسطر كتلة shell في الإجابة."$json$::jsonb),
  ('ar', 'permission.allow', $json$"سماح"$json$::jsonb),
  ('ar', 'permission.allow.hint', $json$"يمر دون إيقاف."$json$::jsonb),
  ('ar', 'permission.ask', $json$"إيقاف وعرض"$json$::jsonb),
  ('ar', 'permission.ask.hint', $json$"يبقى في عمود الخروج لتتحقّق منه."$json$::jsonb),
  ('ar', 'permission.deny', $json$"حظر"$json$::jsonb),
  ('ar', 'permission.deny.hint', $json$"يُوقف دائمًا كأمر محظور."$json$::jsonb),
  ('ar', 'jev.section.gate', $json$"معايير بوابة الدخول"$json$::jsonb),
  ('ar', 'jev.section.gate.description', $json$"تأتي من Supabase وتنطبق على الجميع؛ للقراءة فقط هنا."$json$::jsonb),
  ('ar', 'jev.gate.demand', $json$"الحد الأدنى للوضوح · {scope}"$json$::jsonb),
  ('ar', 'jev.gate.margin', $json$"الهامش قبل الحظر"$json$::jsonb),
  ('ar', 'jev.gate.weight', $json$"الوزن · {criterion}"$json$::jsonb),
  ('ar', 'jev.gate.noulLine', $json$"حدّ نعم/لا"$json$::jsonb),
  ('ar', 'app.section.language', $json$"اللغة"$json$::jsonb),
  ('ar', 'app.section.language.description', $json$"لغة الواجهة وإجابات النموذج. دون اختيار تُستخدم لغة النظام."$json$::jsonb),
  ('ar', 'app.section.privacy', $json$"الخصوصية"$json$::jsonb),
  ('ar', 'app.section.privacy.description', $json$"ما لا يدخل أبدًا في السياق المُرسَل إلى النماذج. نمط glob واحد في كل سطر."$json$::jsonb),
  ('ar', 'app.redact', $json$"إخفاء الأسرار"$json$::jsonb),
  ('ar', 'app.redact.hint', $json$"تتحوّل المفاتيح والرموز وكلمات المرور في السياق إلى [REDACTED]."$json$::jsonb),
  ('ar', 'app.deny', $json$"لا تُقرأ أبدًا"$json$::jsonb),
  ('ar', 'app.deny.hint', $json$"ملفات لا يراها أي نموذج وتوقفها البوابة دائمًا."$json$::jsonb),
  ('ar', 'app.localOnly', $json$"للنماذج المحلية فقط"$json$::jsonb),
  ('ar', 'app.localOnly.hint', $json$"ملفات لا تدخل إلا عندما يعمل النموذج على هذا الجهاز."$json$::jsonb),
  ('ar', 'app.section.version', $json$"الإصدار"$json$::jsonb),
  ('ar', 'app.version', $json$"تم تثبيت JayV {version}."$json$::jsonb),
  ('ar', 'app.updates.hint', $json$"يبحث التطبيق عن الإصدارات الجديدة تلقائيًا عند فتحه؛ والزر يبحث الآن."$json$::jsonb),
  ('ar', 'app.checkUpdates', $json$"البحث عن تحديثات"$json$::jsonb),
  ('ar', 'app.checking', $json$"جارٍ البحث…"$json$::jsonb),
  ('ar', 'update.latest', $json$"أنت تستخدم أحدث إصدار."$json$::jsonb),
  ('ar', 'update.checkFailed', $json$"تعذّر البحث عن تحديثات: {error}"$json$::jsonb),
  ('ar', 'core.confidence', $json$"يجب أن يكون الحد الأدنى للثقة بين {min} و{max}."$json$::jsonb),
  ('ar', 'core.budget', $json$"يجب أن تكون ميزانية «{level}» بين {min} و{max} رمزًا."$json$::jsonb),
  ('ar', 'core.cacheTtl', $json$"تصل مدة صلاحية الذاكرة المؤقتة إلى {max} ثانية."$json$::jsonb),
  ('ar', 'core.permission', $json$"قيمة غير صالحة للقاعدة {rule}: «{value}»."$json$::jsonb),
  ('ar', 'core.patternLong', $json$"يصل كل نمط إلى {max} حرفًا."$json$::jsonb),
  ('ar', 'core.patternInvalid', $json$"النمط «{pattern}» ليس glob صالحًا."$json$::jsonb),
  ('fr', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('fr', 'settings.tab.app', $json$"Application"$json$::jsonb),
  ('fr', 'settings.defaults', $json$"Rétablir les valeurs par défaut"$json$::jsonb),
  ('fr', 'settings.defaults.hint', $json$"Remet les onglets Jev et Application à leurs valeurs initiales. Rien n'est enregistré avant d'enregistrer."$json$::jsonb),
  ('fr', 'complexity.trivial', $json$"Triviale"$json$::jsonb),
  ('fr', 'complexity.simple', $json$"Simple"$json$::jsonb),
  ('fr', 'complexity.medium', $json$"Moyenne"$json$::jsonb),
  ('fr', 'complexity.complex', $json$"Complexe"$json$::jsonb),
  ('fr', 'jev.section.routing', $json$"Routage"$json$::jsonb),
  ('fr', 'jev.section.routing.description', $json$"Comment le Jev choisit l'agent et le modèle de chaque demande."$json$::jsonb),
  ('fr', 'jev.adaptive', $json$"Routage adaptatif"$json$::jsonb),
  ('fr', 'jev.adaptive.hint', $json$"L'historique de chaque modèle (réussites et rapidité) compte dans le choix."$json$::jsonb),
  ('fr', 'jev.preferLocal', $json$"Préférer les modèles locaux"$json$::jsonb),
  ('fr', 'jev.preferLocal.hint', $json$"Les modèles gratuits qui tournent sur la machine sont favorisés au routage."$json$::jsonb),
  ('fr', 'jev.confidence', $json$"Confiance minimale"$json$::jsonb),
  ('fr', 'jev.confidence.hint', $json$"En dessous, le Jev élargit le budget et demande au modèle une question de clarification."$json$::jsonb),
  ('fr', 'jev.section.budgets', $json$"Budget de contexte"$json$::jsonb),
  ('fr', 'jev.section.budgets.description', $json$"Combien de jetons de contexte chaque demande emporte, selon la complexité lue par le Jev (de {min} à {max})."$json$::jsonb),
  ('fr', 'jev.budget.invalid', $json$"Utilisez une valeur entre {min} et {max}."$json$::jsonb),
  ('fr', 'jev.section.cache', $json$"Cache de contexte"$json$::jsonb),
  ('fr', 'jev.section.cache.description', $json$"Le contexte préparé pour une demande est réutilisé pendant ce temps tant que les fichiers ne changent pas."$json$::jsonb),
  ('fr', 'jev.cache', $json$"Durée de validité"$json$::jsonb),
  ('fr', 'jev.cache.off', $json$"Désactivé"$json$::jsonb),
  ('fr', 'jev.cache.minutes', $json${"one": "{count} minute", "other": "{count} minutes"}$json$::jsonb),
  ('fr', 'jev.cache.hours', $json${"one": "{count} heure", "other": "{count} heures"}$json$::jsonb),
  ('fr', 'jev.section.exit', $json$"Contrôle de sortie"$json$::jsonb),
  ('fr', 'jev.section.exit.description', $json$"Ce que fait le contrôle quand la réponse du modèle demande de lire, d'écrire un fichier ou de lancer une commande."$json$::jsonb),
  ('fr', 'jev.exit.read', $json$"Lire des fichiers"$json$::jsonb),
  ('fr', 'jev.exit.read.hint', $json$"Fichier seulement cité dans la réponse."$json$::jsonb),
  ('fr', 'jev.exit.write', $json$"Écrire des fichiers"$json$::jsonb),
  ('fr', 'jev.exit.write.hint', $json$"Fichier dont la réponse fournit le contenu."$json$::jsonb),
  ('fr', 'jev.exit.shell', $json$"Lancer des commandes"$json$::jsonb),
  ('fr', 'jev.exit.shell.hint', $json$"Lignes d'un bloc shell dans la réponse."$json$::jsonb),
  ('fr', 'permission.allow', $json$"Autoriser"$json$::jsonb),
  ('fr', 'permission.allow.hint', $json$"Passe sans retenue."$json$::jsonb),
  ('fr', 'permission.ask', $json$"Retenir et afficher"$json$::jsonb),
  ('fr', 'permission.ask.hint', $json$"Reste dans la colonne de sortie pour vérification."$json$::jsonb),
  ('fr', 'permission.deny', $json$"Bloquer"$json$::jsonb),
  ('fr', 'permission.deny.hint', $json$"Toujours retenu comme interdit."$json$::jsonb),
  ('fr', 'jev.section.gate', $json$"Paramètres du contrôle d'entrée"$json$::jsonb),
  ('fr', 'jev.section.gate.description', $json$"Ils viennent de Supabase et s'appliquent à tous ; lecture seule ici."$json$::jsonb),
  ('fr', 'jev.gate.demand', $json$"Clarté minimale · {scope}"$json$::jsonb),
  ('fr', 'jev.gate.margin', $json$"Marge avant blocage"$json$::jsonb),
  ('fr', 'jev.gate.weight', $json$"Poids · {criterion}"$json$::jsonb),
  ('fr', 'jev.gate.noulLine', $json$"Seuil oui/non"$json$::jsonb),
  ('fr', 'app.section.language', $json$"Langue"$json$::jsonb),
  ('fr', 'app.section.language.description', $json$"La langue de l'écran et des réponses du modèle. Sans choix, celle du système s'applique."$json$::jsonb),
  ('fr', 'app.section.privacy', $json$"Confidentialité"$json$::jsonb),
  ('fr', 'app.section.privacy.description', $json$"Ce qui n'entre jamais dans le contexte envoyé aux modèles. Un motif glob par ligne."$json$::jsonb),
  ('fr', 'app.redact', $json$"Masquer les secrets"$json$::jsonb),
  ('fr', 'app.redact.hint', $json$"Clés, jetons et mots de passe du contexte deviennent [REDACTED]."$json$::jsonb),
  ('fr', 'app.deny', $json$"Ne jamais lire"$json$::jsonb),
  ('fr', 'app.deny.hint', $json$"Fichiers qu'aucun modèle ne voit et que le contrôle retient toujours."$json$::jsonb),
  ('fr', 'app.localOnly', $json$"Modèles locaux uniquement"$json$::jsonb),
  ('fr', 'app.localOnly.hint', $json$"Fichiers inclus seulement quand le modèle tourne sur la machine."$json$::jsonb),
  ('fr', 'app.section.version', $json$"Version"$json$::jsonb),
  ('fr', 'app.version', $json$"JayV {version} installé."$json$::jsonb),
  ('fr', 'app.updates.hint', $json$"L'application cherche les nouvelles versions à l'ouverture ; le bouton cherche maintenant."$json$::jsonb),
  ('fr', 'app.checkUpdates', $json$"Rechercher des mises à jour"$json$::jsonb),
  ('fr', 'app.checking', $json$"Recherche…"$json$::jsonb),
  ('fr', 'update.latest', $json$"Vous avez la dernière version."$json$::jsonb),
  ('fr', 'update.checkFailed', $json$"Impossible de rechercher des mises à jour : {error}"$json$::jsonb),
  ('fr', 'core.confidence', $json$"La confiance minimale doit être comprise entre {min} et {max}."$json$::jsonb),
  ('fr', 'core.budget', $json$"Le budget « {level} » doit être compris entre {min} et {max} jetons."$json$::jsonb),
  ('fr', 'core.cacheTtl', $json$"La durée du cache va jusqu'à {max} secondes."$json$::jsonb),
  ('fr', 'core.permission', $json$"Valeur invalide pour la règle {rule} : « {value} »."$json$::jsonb),
  ('fr', 'core.patternLong', $json$"Chaque motif va jusqu'à {max} caractères."$json$::jsonb),
  ('fr', 'core.patternInvalid', $json$"Le motif « {pattern} » n'est pas un glob valide."$json$::jsonb),
  ('ru', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('ru', 'settings.tab.app', $json$"Приложение"$json$::jsonb),
  ('ru', 'settings.defaults', $json$"Восстановить значения по умолчанию"$json$::jsonb),
  ('ru', 'settings.defaults.hint', $json$"Возвращает вкладки Jev и «Приложение» к исходным значениям. Ничего не сохраняется, пока вы не нажмёте «Сохранить»."$json$::jsonb),
  ('ru', 'complexity.trivial', $json$"Тривиальная"$json$::jsonb),
  ('ru', 'complexity.simple', $json$"Простая"$json$::jsonb),
  ('ru', 'complexity.medium', $json$"Средняя"$json$::jsonb),
  ('ru', 'complexity.complex', $json$"Сложная"$json$::jsonb),
  ('ru', 'jev.section.routing', $json$"Маршрутизация"$json$::jsonb),
  ('ru', 'jev.section.routing.description', $json$"Как Jev выбирает агента и модель для каждого запроса."$json$::jsonb),
  ('ru', 'jev.adaptive', $json$"Адаптивная маршрутизация"$json$::jsonb),
  ('ru', 'jev.adaptive.hint', $json$"История каждой модели (успехи и скорость) учитывается при выборе."$json$::jsonb),
  ('ru', 'jev.preferLocal', $json$"Предпочитать локальные модели"$json$::jsonb),
  ('ru', 'jev.preferLocal.hint', $json$"Бесплатные модели, работающие на этой машине, получают больше баллов при маршрутизации."$json$::jsonb),
  ('ru', 'jev.confidence', $json$"Минимальная уверенность"$json$::jsonb),
  ('ru', 'jev.confidence.hint', $json$"Ниже этого порога Jev увеличивает бюджет и просит модель задать уточняющий вопрос."$json$::jsonb),
  ('ru', 'jev.section.budgets', $json$"Бюджет контекста"$json$::jsonb),
  ('ru', 'jev.section.budgets.description', $json$"Сколько токенов контекста получает каждый запрос в зависимости от сложности, которую определил Jev (от {min} до {max})."$json$::jsonb),
  ('ru', 'jev.budget.invalid', $json$"Укажите значение от {min} до {max}."$json$::jsonb),
  ('ru', 'jev.section.cache', $json$"Кэш контекста"$json$::jsonb),
  ('ru', 'jev.section.cache.description', $json$"Собранный для запроса контекст используется повторно в течение этого времени, пока файлы не меняются."$json$::jsonb),
  ('ru', 'jev.cache', $json$"Срок действия"$json$::jsonb),
  ('ru', 'jev.cache.off', $json$"Выключено"$json$::jsonb),
  ('ru', 'jev.cache.minutes', $json${"one": "{count} минута", "few": "{count} минуты", "many": "{count} минут", "other": "{count} минуты"}$json$::jsonb),
  ('ru', 'jev.cache.hours', $json${"one": "{count} час", "few": "{count} часа", "many": "{count} часов", "other": "{count} часа"}$json$::jsonb),
  ('ru', 'jev.section.exit', $json$"Выходной контроль"$json$::jsonb),
  ('ru', 'jev.section.exit.description', $json$"Что делает проходная, когда ответ модели просит прочитать, записать файл или выполнить команду."$json$::jsonb),
  ('ru', 'jev.exit.read', $json$"Чтение файлов"$json$::jsonb),
  ('ru', 'jev.exit.read.hint', $json$"Файл, который ответ только упоминает."$json$::jsonb),
  ('ru', 'jev.exit.write', $json$"Запись файлов"$json$::jsonb),
  ('ru', 'jev.exit.write.hint', $json$"Файл, содержимое которого приводит ответ."$json$::jsonb),
  ('ru', 'jev.exit.shell', $json$"Выполнение команд"$json$::jsonb),
  ('ru', 'jev.exit.shell.hint', $json$"Строки shell-блока в ответе."$json$::jsonb),
  ('ru', 'permission.allow', $json$"Разрешать"$json$::jsonb),
  ('ru', 'permission.allow.hint', $json$"Пропускается без задержки."$json$::jsonb),
  ('ru', 'permission.ask', $json$"Задержать и показать"$json$::jsonb),
  ('ru', 'permission.ask.hint', $json$"Остаётся в колонке выхода для проверки."$json$::jsonb),
  ('ru', 'permission.deny', $json$"Блокировать"$json$::jsonb),
  ('ru', 'permission.deny.hint', $json$"Всегда задерживается как запрещённое."$json$::jsonb),
  ('ru', 'jev.section.gate', $json$"Параметры входного контроля"$json$::jsonb),
  ('ru', 'jev.section.gate.description', $json$"Приходят из Supabase и действуют для всех; здесь только для чтения."$json$::jsonb),
  ('ru', 'jev.gate.demand', $json$"Минимальная ясность · {scope}"$json$::jsonb),
  ('ru', 'jev.gate.margin', $json$"Запас до блокировки"$json$::jsonb),
  ('ru', 'jev.gate.weight', $json$"Вес · {criterion}"$json$::jsonb),
  ('ru', 'jev.gate.noulLine', $json$"Порог «да/нет»"$json$::jsonb),
  ('ru', 'app.section.language', $json$"Язык"$json$::jsonb),
  ('ru', 'app.section.language.description', $json$"Язык интерфейса и ответов модели. Если не выбран, используется язык системы."$json$::jsonb),
  ('ru', 'app.section.privacy', $json$"Конфиденциальность"$json$::jsonb),
  ('ru', 'app.section.privacy.description', $json$"То, что никогда не попадает в контекст, отправляемый моделям. Один glob-шаблон на строку."$json$::jsonb),
  ('ru', 'app.redact', $json$"Скрывать секреты"$json$::jsonb),
  ('ru', 'app.redact.hint', $json$"Ключи, токены и пароли в контексте заменяются на [REDACTED]."$json$::jsonb),
  ('ru', 'app.deny', $json$"Никогда не читать"$json$::jsonb),
  ('ru', 'app.deny.hint', $json$"Файлы, которые не видит ни одна модель и которые проходная всегда задерживает."$json$::jsonb),
  ('ru', 'app.localOnly', $json$"Только для локальных моделей"$json$::jsonb),
  ('ru', 'app.localOnly.hint', $json$"Файлы, которые попадают в контекст, только если модель работает на этой машине."$json$::jsonb),
  ('ru', 'app.section.version', $json$"Версия"$json$::jsonb),
  ('ru', 'app.version', $json$"Установлен JayV {version}."$json$::jsonb),
  ('ru', 'app.updates.hint', $json$"Приложение само ищет новые версии при запуске; кнопка ищет прямо сейчас."$json$::jsonb),
  ('ru', 'app.checkUpdates', $json$"Проверить обновления"$json$::jsonb),
  ('ru', 'app.checking', $json$"Проверка…"$json$::jsonb),
  ('ru', 'update.latest', $json$"У вас последняя версия."$json$::jsonb),
  ('ru', 'update.checkFailed', $json$"Не удалось проверить обновления: {error}"$json$::jsonb),
  ('ru', 'core.confidence', $json$"Минимальная уверенность должна быть от {min} до {max}."$json$::jsonb),
  ('ru', 'core.budget', $json$"Бюджет «{level}» должен быть от {min} до {max} токенов."$json$::jsonb),
  ('ru', 'core.cacheTtl', $json$"Срок действия кэша — не более {max} секунд."$json$::jsonb),
  ('ru', 'core.permission', $json$"Недопустимое значение для правила {rule}: «{value}»."$json$::jsonb),
  ('ru', 'core.patternLong', $json$"Каждый шаблон — не более {max} символов."$json$::jsonb),
  ('ru', 'core.patternInvalid', $json$"Шаблон «{pattern}» не является допустимым glob."$json$::jsonb),
  ('ja', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('ja', 'settings.tab.app', $json$"アプリ"$json$::jsonb),
  ('ja', 'settings.defaults', $json$"既定値に戻す"$json$::jsonb),
  ('ja', 'settings.defaults.hint', $json$"Jev とアプリのタブを初期値に戻します。保存するまで何も保存されません。"$json$::jsonb),
  ('ja', 'complexity.trivial', $json$"ごく簡単"$json$::jsonb),
  ('ja', 'complexity.simple', $json$"簡単"$json$::jsonb),
  ('ja', 'complexity.medium', $json$"中程度"$json$::jsonb),
  ('ja', 'complexity.complex', $json$"複雑"$json$::jsonb),
  ('ja', 'jev.section.routing', $json$"ルーティング"$json$::jsonb),
  ('ja', 'jev.section.routing.description', $json$"Jev が各リクエストのエージェントとモデルを選ぶ方法。"$json$::jsonb),
  ('ja', 'jev.adaptive', $json$"適応ルーティング"$json$::jsonb),
  ('ja', 'jev.adaptive.hint', $json$"各モデルの実績（成功率と速度）が選択に反映されます。"$json$::jsonb),
  ('ja', 'jev.preferLocal', $json$"ローカルモデルを優先"$json$::jsonb),
  ('ja', 'jev.preferLocal.hint', $json$"このマシンで動く無料モデルがルーティングで有利になります。"$json$::jsonb),
  ('ja', 'jev.confidence', $json$"最低信頼度"$json$::jsonb),
  ('ja', 'jev.confidence.hint', $json$"これを下回ると、Jev は予算を広げ、モデルに確認の質問を求めます。"$json$::jsonb),
  ('ja', 'jev.section.budgets', $json$"コンテキスト予算"$json$::jsonb),
  ('ja', 'jev.section.budgets.description', $json$"Jev が読み取った複雑さに応じて、各リクエストに渡すコンテキストのトークン数（{min}〜{max}）。"$json$::jsonb),
  ('ja', 'jev.budget.invalid', $json$"{min}〜{max} の値にしてください。"$json$::jsonb),
  ('ja', 'jev.section.cache', $json$"コンテキストキャッシュ"$json$::jsonb),
  ('ja', 'jev.section.cache.description', $json$"ファイルが変わらない限り、リクエスト用に組み立てたコンテキストをこの時間だけ再利用します。"$json$::jsonb),
  ('ja', 'jev.cache', $json$"有効期間"$json$::jsonb),
  ('ja', 'jev.cache.off', $json$"オフ"$json$::jsonb),
  ('ja', 'jev.cache.minutes', $json${"other": "{count} 分"}$json$::jsonb),
  ('ja', 'jev.cache.hours', $json${"other": "{count} 時間"}$json$::jsonb),
  ('ja', 'jev.section.exit', $json$"出口ゲート"$json$::jsonb),
  ('ja', 'jev.section.exit.description', $json$"モデルの回答が読み取り、ファイル書き込み、コマンド実行を求めたときのゲートの動作。"$json$::jsonb),
  ('ja', 'jev.exit.read', $json$"ファイルの読み取り"$json$::jsonb),
  ('ja', 'jev.exit.read.hint', $json$"回答で言及されているだけのファイル。"$json$::jsonb),
  ('ja', 'jev.exit.write', $json$"ファイルの書き込み"$json$::jsonb),
  ('ja', 'jev.exit.write.hint', $json$"回答が内容を提示しているファイル。"$json$::jsonb),
  ('ja', 'jev.exit.shell', $json$"コマンドの実行"$json$::jsonb),
  ('ja', 'jev.exit.shell.hint', $json$"回答内のシェルブロックの行。"$json$::jsonb),
  ('ja', 'permission.allow', $json$"許可"$json$::jsonb),
  ('ja', 'permission.allow.hint', $json$"止めずに通します。"$json$::jsonb),
  ('ja', 'permission.ask', $json$"止めて表示"$json$::jsonb),
  ('ja', 'permission.ask.hint', $json$"確認できるよう出口の列に残ります。"$json$::jsonb),
  ('ja', 'permission.deny', $json$"ブロック"$json$::jsonb),
  ('ja', 'permission.deny.hint', $json$"常に禁止として止めます。"$json$::jsonb),
  ('ja', 'jev.section.gate', $json$"入口ゲートのパラメーター"$json$::jsonb),
  ('ja', 'jev.section.gate.description', $json$"Supabase から取得され全員に適用されます。ここでは読み取り専用です。"$json$::jsonb),
  ('ja', 'jev.gate.demand', $json$"最低限の明確さ · {scope}"$json$::jsonb),
  ('ja', 'jev.gate.margin', $json$"ブロックまでの余裕"$json$::jsonb),
  ('ja', 'jev.gate.weight', $json$"重み · {criterion}"$json$::jsonb),
  ('ja', 'jev.gate.noulLine', $json$"はい/いいえの境界"$json$::jsonb),
  ('ja', 'app.section.language', $json$"言語"$json$::jsonb),
  ('ja', 'app.section.language.description', $json$"画面とモデルの回答の言語。選ばない場合はシステムの言語になります。"$json$::jsonb),
  ('ja', 'app.section.privacy', $json$"プライバシー"$json$::jsonb),
  ('ja', 'app.section.privacy.description', $json$"モデルに送るコンテキストに決して含めないもの。1 行に 1 つの glob パターン。"$json$::jsonb),
  ('ja', 'app.redact', $json$"シークレットを伏せる"$json$::jsonb),
  ('ja', 'app.redact.hint', $json$"コンテキスト内のキー、トークン、パスワードは [REDACTED] になります。"$json$::jsonb),
  ('ja', 'app.deny', $json$"読み取らない"$json$::jsonb),
  ('ja', 'app.deny.hint', $json$"どのモデルにも見せず、ゲートが常に止めるファイル。"$json$::jsonb),
  ('ja', 'app.localOnly', $json$"ローカルモデルのみ"$json$::jsonb),
  ('ja', 'app.localOnly.hint', $json$"モデルがこのマシンで動くときだけ含めるファイル。"$json$::jsonb),
  ('ja', 'app.section.version', $json$"バージョン"$json$::jsonb),
  ('ja', 'app.version', $json$"JayV {version} がインストールされています。"$json$::jsonb),
  ('ja', 'app.updates.hint', $json$"アプリは起動時に新しいバージョンを自動で確認します。ボタンで今すぐ確認できます。"$json$::jsonb),
  ('ja', 'app.checkUpdates', $json$"アップデートを確認"$json$::jsonb),
  ('ja', 'app.checking', $json$"確認中…"$json$::jsonb),
  ('ja', 'update.latest', $json$"最新バージョンです。"$json$::jsonb),
  ('ja', 'update.checkFailed', $json$"アップデートを確認できませんでした: {error}"$json$::jsonb),
  ('ja', 'core.confidence', $json$"最低信頼度は {min}〜{max} にしてください。"$json$::jsonb),
  ('ja', 'core.budget', $json$"「{level}」の予算は {min}〜{max} トークンにしてください。"$json$::jsonb),
  ('ja', 'core.cacheTtl', $json$"キャッシュの有効期間は最大 {max} 秒です。"$json$::jsonb),
  ('ja', 'core.permission', $json$"ルール {rule} の値が無効です: 「{value}」。"$json$::jsonb),
  ('ja', 'core.patternLong', $json$"各パターンは最大 {max} 文字です。"$json$::jsonb),
  ('ja', 'core.patternInvalid', $json$"パターン「{pattern}」は有効な glob ではありません。"$json$::jsonb),
  ('de', 'settings.tab.jev', $json$"Jev"$json$::jsonb),
  ('de', 'settings.tab.app', $json$"App"$json$::jsonb),
  ('de', 'settings.defaults', $json$"Standardwerte wiederherstellen"$json$::jsonb),
  ('de', 'settings.defaults.hint', $json$"Setzt die Tabs Jev und App auf ihre Ausgangswerte zurück. Gespeichert wird erst beim Speichern."$json$::jsonb),
  ('de', 'complexity.trivial', $json$"Trivial"$json$::jsonb),
  ('de', 'complexity.simple', $json$"Einfach"$json$::jsonb),
  ('de', 'complexity.medium', $json$"Mittel"$json$::jsonb),
  ('de', 'complexity.complex', $json$"Komplex"$json$::jsonb),
  ('de', 'jev.section.routing', $json$"Routing"$json$::jsonb),
  ('de', 'jev.section.routing.description', $json$"Wie der Jev Agent und Modell für jede Anfrage auswählt."$json$::jsonb),
  ('de', 'jev.adaptive', $json$"Adaptives Routing"$json$::jsonb),
  ('de', 'jev.adaptive.hint', $json$"Die Bilanz jedes Modells (Erfolge und Tempo) fließt in die Auswahl ein."$json$::jsonb),
  ('de', 'jev.preferLocal', $json$"Lokale Modelle bevorzugen"$json$::jsonb),
  ('de', 'jev.preferLocal.hint', $json$"Kostenlose Modelle, die auf diesem Rechner laufen, punkten beim Routing."$json$::jsonb),
  ('de', 'jev.confidence', $json$"Mindestkonfidenz"$json$::jsonb),
  ('de', 'jev.confidence.hint', $json$"Darunter erweitert der Jev das Budget und bittet das Modell um eine Rückfrage."$json$::jsonb),
  ('de', 'jev.section.budgets', $json$"Kontextbudget"$json$::jsonb),
  ('de', 'jev.section.budgets.description', $json$"Wie viele Kontext-Tokens jede Anfrage je nach vom Jev erkannter Komplexität erhält ({min} bis {max})."$json$::jsonb),
  ('de', 'jev.budget.invalid', $json$"Verwende einen Wert zwischen {min} und {max}."$json$::jsonb),
  ('de', 'jev.section.cache', $json$"Kontext-Cache"$json$::jsonb),
  ('de', 'jev.section.cache.description', $json$"Der für eine Anfrage aufgebaute Kontext wird so lange wiederverwendet, solange sich die Dateien nicht ändern."$json$::jsonb),
  ('de', 'jev.cache', $json$"Gültigkeit"$json$::jsonb),
  ('de', 'jev.cache.off', $json$"Aus"$json$::jsonb),
  ('de', 'jev.cache.minutes', $json${"one": "{count} Minute", "other": "{count} Minuten"}$json$::jsonb),
  ('de', 'jev.cache.hours', $json${"one": "{count} Stunde", "other": "{count} Stunden"}$json$::jsonb),
  ('de', 'jev.section.exit', $json$"Ausgangskontrolle"$json$::jsonb),
  ('de', 'jev.section.exit.description', $json$"Was die Kontrolle tut, wenn die Antwort des Modells lesen, eine Datei schreiben oder einen Befehl ausführen will."$json$::jsonb),
  ('de', 'jev.exit.read', $json$"Dateien lesen"$json$::jsonb),
  ('de', 'jev.exit.read.hint', $json$"Eine Datei, die die Antwort nur erwähnt."$json$::jsonb),
  ('de', 'jev.exit.write', $json$"Dateien schreiben"$json$::jsonb),
  ('de', 'jev.exit.write.hint', $json$"Eine Datei, deren Inhalt die Antwort liefert."$json$::jsonb),
  ('de', 'jev.exit.shell', $json$"Befehle ausführen"$json$::jsonb),
  ('de', 'jev.exit.shell.hint', $json$"Zeilen eines Shell-Blocks in der Antwort."$json$::jsonb),
  ('de', 'permission.allow', $json$"Erlauben"$json$::jsonb),
  ('de', 'permission.allow.hint', $json$"Geht ohne Halt durch."$json$::jsonb),
  ('de', 'permission.ask', $json$"Anhalten und zeigen"$json$::jsonb),
  ('de', 'permission.ask.hint', $json$"Bleibt zur Prüfung in der Ausgangsspalte."$json$::jsonb),
  ('de', 'permission.deny', $json$"Sperren"$json$::jsonb),
  ('de', 'permission.deny.hint', $json$"Wird immer als verboten angehalten."$json$::jsonb),
  ('de', 'jev.section.gate', $json$"Parameter der Eingangskontrolle"$json$::jsonb),
  ('de', 'jev.section.gate.description', $json$"Sie kommen aus Supabase und gelten für alle; hier nur lesbar."$json$::jsonb),
  ('de', 'jev.gate.demand', $json$"Mindestklarheit · {scope}"$json$::jsonb),
  ('de', 'jev.gate.margin', $json$"Spielraum bis zur Sperre"$json$::jsonb),
  ('de', 'jev.gate.weight', $json$"Gewicht · {criterion}"$json$::jsonb),
  ('de', 'jev.gate.noulLine', $json$"Ja/Nein-Schwelle"$json$::jsonb),
  ('de', 'app.section.language', $json$"Sprache"$json$::jsonb),
  ('de', 'app.section.language.description', $json$"Die Sprache der Oberfläche und der Antworten des Modells. Ohne Auswahl gilt die des Systems."$json$::jsonb),
  ('de', 'app.section.privacy', $json$"Datenschutz"$json$::jsonb),
  ('de', 'app.section.privacy.description', $json$"Was nie in den an die Modelle gesendeten Kontext gelangt. Ein Glob-Muster pro Zeile."$json$::jsonb),
  ('de', 'app.redact', $json$"Geheimnisse schwärzen"$json$::jsonb),
  ('de', 'app.redact.hint', $json$"Schlüssel, Tokens und Passwörter im Kontext werden zu [REDACTED]."$json$::jsonb),
  ('de', 'app.deny', $json$"Nie lesen"$json$::jsonb),
  ('de', 'app.deny.hint', $json$"Dateien, die kein Modell sieht und die die Kontrolle immer anhält."$json$::jsonb),
  ('de', 'app.localOnly', $json$"Nur lokale Modelle"$json$::jsonb),
  ('de', 'app.localOnly.hint', $json$"Dateien, die nur einfließen, wenn das Modell auf diesem Rechner läuft."$json$::jsonb),
  ('de', 'app.section.version', $json$"Version"$json$::jsonb),
  ('de', 'app.version', $json$"JayV {version} installiert."$json$::jsonb),
  ('de', 'app.updates.hint', $json$"Die App sucht beim Öffnen selbst nach neuen Versionen; die Schaltfläche sucht jetzt."$json$::jsonb),
  ('de', 'app.checkUpdates', $json$"Nach Updates suchen"$json$::jsonb),
  ('de', 'app.checking', $json$"Suche…"$json$::jsonb),
  ('de', 'update.latest', $json$"Du hast die neueste Version."$json$::jsonb),
  ('de', 'update.checkFailed', $json$"Nach Updates konnte nicht gesucht werden: {error}"$json$::jsonb),
  ('de', 'core.confidence', $json$"Die Mindestkonfidenz muss zwischen {min} und {max} liegen."$json$::jsonb),
  ('de', 'core.budget', $json$"Das Budget für „{level}“ muss zwischen {min} und {max} Tokens liegen."$json$::jsonb),
  ('de', 'core.cacheTtl', $json$"Die Cache-Gültigkeit beträgt höchstens {max} Sekunden."$json$::jsonb),
  ('de', 'core.permission', $json$"Ungültiger Wert für die Regel {rule}: „{value}“."$json$::jsonb),
  ('de', 'core.patternLong', $json$"Jedes Muster hat höchstens {max} Zeichen."$json$::jsonb),
  ('de', 'core.patternInvalid', $json$"Das Muster „{pattern}“ ist kein gültiger Glob."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
