-- v0.59.1: as correções de latência e de conversa com as CLIs — o texto do
-- Claude enquanto ele escreve, o prazo da portaria, a saída dos agentes, o
-- índice que segue o .gitignore e apagar sem esperar o agente. Só textos.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.item.liveClaudeText.title', $json$"A resposta do Claude aparece enquanto ele escreve"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveClaudeText.detail', $json$"A resposta do Claude Code agora cresce na tela token a token, em vez de aparecer só quando cada mensagem termina. A resposta gravada é a mesma de antes, e os pedaços chegam à tela em pequenos lotes para que respostas longas não deixem a janela lenta."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.gateDeadline.title', $json$"A portaria não segura mais o pedido por minutos"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.gateDeadline.detail', $json$"A portaria de entrada e o roteamento esperam o Jev por poucos segundos, com uma nova tentativa, e então decidem pelas heurísticas locais. Depois de três falhas seguidas, o app deixa de esperar o Jev por cinco minutos, e uma chamada que o app repete conta só uma vez no limite diário."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentOutput.title', $json$"Conversas mais firmes com os agentes"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentOutput.detail', $json$"Uma sessão do Codex que já não existe começa outra em vez de falhar; uma linha fora do UTF-8 não derruba mais o pedido; um pedido longo não trava mais o agente que escreve muito antes de lê-lo; o agente reserva assume mesmo depois de um plano demorado; e os eventos de estado internos do Claude não repetem mais \"agente começou\" na linha do tempo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectIndex.title', $json$"O índice do projeto segue o .gitignore"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectIndex.detail', $json$"Arquivos ignorados, ambientes virtuais e pastas de build ficam fora do contexto, e o orçamento de leitura vai primeiro para o código: uma pasta .venv ou coverage grande não tira mais o código do projeto do índice."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.instantDelete.title', $json$"Apagar ou limpar um chat responde na hora"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.instantDelete.detail', $json$"Limpar um chat, apagá-lo ou apagar um projeto não espera mais o pedido que outro chat está atendendo."$json$::jsonb),
  ('en', 'whatsNew.item.liveClaudeText.title', $json$"Claude's answer appears while it is written"$json$::jsonb),
  ('en', 'whatsNew.item.liveClaudeText.detail', $json$"Claude Code's reply now grows on the screen token by token instead of showing up only when each message ends. The saved answer is the same as before, and the pieces reach the screen in small batches so long answers do not slow the window down."$json$::jsonb),
  ('en', 'whatsNew.item.gateDeadline.title', $json$"The gatehouse no longer holds a request for minutes"$json$::jsonb),
  ('en', 'whatsNew.item.gateDeadline.detail', $json$"The entry gate and the routing wait for the Jev at most a few seconds, with one retry, and then decide with the local heuristics. After three failures in a row the app stops waiting for the Jev for five minutes, and a call the app retries counts only once in the daily limit."$json$::jsonb),
  ('en', 'whatsNew.item.agentOutput.title', $json$"Steadier conversations with the agents"$json$::jsonb),
  ('en', 'whatsNew.item.agentOutput.detail', $json$"A Codex session that no longer exists starts a new one instead of failing; a line outside UTF-8 no longer breaks the request; a long request no longer locks up an agent that writes a lot before reading it; the backup agent takes over even after a long plan; and Claude's internal status events no longer repeat \"agent started\" in the timeline."$json$::jsonb),
  ('en', 'whatsNew.item.projectIndex.title', $json$"The project index follows .gitignore"$json$::jsonb),
  ('en', 'whatsNew.item.projectIndex.detail', $json$"Ignored files, virtual environments and build folders stay out of the context, and the read budget goes to code first: a large .venv or coverage folder no longer pushes the project's source out of the index."$json$::jsonb),
  ('en', 'whatsNew.item.instantDelete.title', $json$"Deleting or clearing a chat answers at once"$json$::jsonb),
  ('en', 'whatsNew.item.instantDelete.detail', $json$"Clearing a chat, deleting it or deleting a project no longer waits for the request another chat is running."$json$::jsonb),
  ('es', 'whatsNew.item.liveClaudeText.title', $json$"La respuesta de Claude aparece mientras la escribe"$json$::jsonb),
  ('es', 'whatsNew.item.liveClaudeText.detail', $json$"La respuesta de Claude Code ahora crece en la pantalla token a token, en lugar de aparecer solo cuando termina cada mensaje. La respuesta guardada es la misma que antes, y los fragmentos llegan a la pantalla en pequeños lotes para que las respuestas largas no ralenticen la ventana."$json$::jsonb),
  ('es', 'whatsNew.item.gateDeadline.title', $json$"La portería ya no retiene la solicitud durante minutos"$json$::jsonb),
  ('es', 'whatsNew.item.gateDeadline.detail', $json$"La portería de entrada y el enrutamiento esperan al Jev como máximo unos segundos, con un reintento, y luego deciden con las heurísticas locales. Tras tres fallos seguidos, la app deja de esperar al Jev durante cinco minutos, y una llamada que la app repite cuenta solo una vez en el límite diario."$json$::jsonb),
  ('es', 'whatsNew.item.agentOutput.title', $json$"Conversaciones más estables con los agentes"$json$::jsonb),
  ('es', 'whatsNew.item.agentOutput.detail', $json$"Una sesión de Codex que ya no existe inicia otra en lugar de fallar; una línea fuera de UTF-8 ya no rompe la solicitud; una solicitud larga ya no bloquea a un agente que escribe mucho antes de leerla; el agente de respaldo toma el relevo incluso después de un plan largo; y los eventos de estado internos de Claude ya no repiten \"el agente empezó\" en la línea de tiempo."$json$::jsonb),
  ('es', 'whatsNew.item.projectIndex.title', $json$"El índice del proyecto respeta el .gitignore"$json$::jsonb),
  ('es', 'whatsNew.item.projectIndex.detail', $json$"Los archivos ignorados, los entornos virtuales y las carpetas de build quedan fuera del contexto, y el presupuesto de lectura va primero al código: una carpeta .venv o coverage grande ya no saca el código del proyecto del índice."$json$::jsonb),
  ('es', 'whatsNew.item.instantDelete.title', $json$"Borrar o vaciar un chat responde al instante"$json$::jsonb),
  ('es', 'whatsNew.item.instantDelete.detail', $json$"Vaciar un chat, borrarlo o borrar un proyecto ya no espera a la solicitud que está atendiendo otro chat."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveClaudeText.title', $json$"Claude 的回答会边写边显示"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveClaudeText.detail', $json$"Claude Code 的回复现在会逐个 token 在屏幕上增长，而不是等每条消息结束才出现。保存的回答与之前相同，片段会以小批次送到屏幕上，长回答也不会拖慢窗口。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.gateDeadline.title', $json$"门卫不再把请求卡住好几分钟"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.gateDeadline.detail', $json$"入口门卫和路由最多等待 Jev 几秒钟，并重试一次，然后改用本地启发式规则决定。连续失败三次后，应用会在五分钟内不再等待 Jev；应用重试的调用在每日限额中只计一次。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentOutput.title', $json$"与代理的对话更稳定"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentOutput.detail', $json$"已不存在的 Codex 会话会新开一个，而不是失败；不是 UTF-8 的一行不再导致请求失败；长请求不再卡住那些在读取前大量输出的代理；即使经过很长的规划，备用代理也能接手；Claude 的内部状态事件不再在时间线上重复“代理已开始”。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectIndex.title', $json$"项目索引遵循 .gitignore"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectIndex.detail', $json$"被忽略的文件、虚拟环境和构建目录不再进入上下文，读取预算优先分配给代码：庞大的 .venv 或 coverage 目录不会再把项目源码挤出索引。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.instantDelete.title', $json$"删除或清空聊天会立即响应"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.instantDelete.detail', $json$"清空聊天、删除聊天或删除项目，不再需要等待另一个聊天正在运行的请求。"$json$::jsonb),
  ('hi', 'whatsNew.item.liveClaudeText.title', $json$"Claude का जवाब लिखते समय ही दिखने लगता है"$json$::jsonb),
  ('hi', 'whatsNew.item.liveClaudeText.detail', $json$"Claude Code का जवाब अब हर संदेश के खत्म होने का इंतज़ार किए बिना, टोकन-दर-टोकन स्क्रीन पर बढ़ता है। सहेजा गया जवाब पहले जैसा ही है, और टुकड़े छोटे बैच में स्क्रीन तक पहुँचते हैं ताकि लंबे जवाब विंडो को धीमा न करें।"$json$::jsonb),
  ('hi', 'whatsNew.item.gateDeadline.title', $json$"गेटहाउस अब अनुरोध को मिनटों तक नहीं रोकता"$json$::jsonb),
  ('hi', 'whatsNew.item.gateDeadline.detail', $json$"एंट्री गेट और रूटिंग Jev का अधिकतम कुछ सेकंड, एक दोबारा कोशिश के साथ, इंतज़ार करते हैं और फिर स्थानीय ह्यूरिस्टिक्स से तय करते हैं। लगातार तीन विफलताओं के बाद ऐप पाँच मिनट तक Jev का इंतज़ार नहीं करता, और ऐप द्वारा दोहराई गई कॉल दैनिक सीमा में केवल एक बार गिनी जाती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentOutput.title', $json$"एजेंटों के साथ ज़्यादा स्थिर बातचीत"$json$::jsonb),
  ('hi', 'whatsNew.item.agentOutput.detail', $json$"जो Codex सत्र अब मौजूद नहीं है, वह विफल होने के बजाय नया शुरू करता है; UTF-8 से बाहर की पंक्ति अब अनुरोध को नहीं तोड़ती; लंबा अनुरोध अब उस एजेंट को नहीं अटकाता जो उसे पढ़ने से पहले बहुत लिखता है; लंबी योजना के बाद भी बैकअप एजेंट काम संभाल लेता है; और Claude के आंतरिक स्थिति इवेंट टाइमलाइन में \"एजेंट शुरू हुआ\" अब नहीं दोहराते।"$json$::jsonb),
  ('hi', 'whatsNew.item.projectIndex.title', $json$"प्रोजेक्ट इंडेक्स .gitignore का पालन करता है"$json$::jsonb),
  ('hi', 'whatsNew.item.projectIndex.detail', $json$"अनदेखी फ़ाइलें, वर्चुअल एनवायरनमेंट और बिल्ड फ़ोल्डर संदर्भ से बाहर रहते हैं, और पढ़ने का बजट पहले कोड को मिलता है: बड़ा .venv या coverage फ़ोल्डर अब प्रोजेक्ट के सोर्स को इंडेक्स से बाहर नहीं करता।"$json$::jsonb),
  ('hi', 'whatsNew.item.instantDelete.title', $json$"चैट हटाना या साफ़ करना तुरंत होता है"$json$::jsonb),
  ('hi', 'whatsNew.item.instantDelete.detail', $json$"चैट साफ़ करना, उसे हटाना या प्रोजेक्ट हटाना अब किसी दूसरी चैट में चल रहे अनुरोध का इंतज़ार नहीं करता।"$json$::jsonb),
  ('ar', 'whatsNew.item.liveClaudeText.title', $json$"يظهر رد Claude أثناء كتابته"$json$::jsonb),
  ('ar', 'whatsNew.item.liveClaudeText.detail', $json$"يتزايد رد Claude Code الآن على الشاشة رمزًا تلو الآخر بدلًا من أن يظهر فقط عند انتهاء كل رسالة. الرد المحفوظ هو نفسه كما كان، وتصل الأجزاء إلى الشاشة على دفعات صغيرة حتى لا تُبطئ الردود الطويلة النافذة."$json$::jsonb),
  ('ar', 'whatsNew.item.gateDeadline.title', $json$"لم تعد البوابة تحتجز الطلب لدقائق"$json$::jsonb),
  ('ar', 'whatsNew.item.gateDeadline.detail', $json$"تنتظر بوابة الدخول والتوجيه Jev بضع ثوانٍ على الأكثر، مع محاولة إضافية واحدة، ثم تقرر باستخدام الاستدلالات المحلية. بعد ثلاث إخفاقات متتالية يتوقف التطبيق عن انتظار Jev لمدة خمس دقائق، والاستدعاء الذي يكرره التطبيق يُحتسب مرة واحدة فقط في الحد اليومي."$json$::jsonb),
  ('ar', 'whatsNew.item.agentOutput.title', $json$"محادثات أكثر ثباتًا مع الوكلاء"$json$::jsonb),
  ('ar', 'whatsNew.item.agentOutput.detail', $json$"جلسة Codex التي لم تعد موجودة تبدأ جلسة جديدة بدلًا من الفشل؛ ولم يعد سطر خارج UTF-8 يُفشل الطلب؛ ولم يعد الطلب الطويل يُعلّق وكيلًا يكتب كثيرًا قبل قراءته؛ ويتولى الوكيل الاحتياطي المهمة حتى بعد خطة طويلة؛ ولم تعد أحداث الحالة الداخلية لـ Claude تكرر \"بدأ الوكيل\" في المخطط الزمني."$json$::jsonb),
  ('ar', 'whatsNew.item.projectIndex.title', $json$"فهرس المشروع يتبع .gitignore"$json$::jsonb),
  ('ar', 'whatsNew.item.projectIndex.detail', $json$"تبقى الملفات المتجاهلة والبيئات الافتراضية ومجلدات البناء خارج السياق، وتذهب ميزانية القراءة إلى الشيفرة أولًا: لم يعد مجلد .venv أو coverage كبير يُخرج شيفرة المشروع من الفهرس."$json$::jsonb),
  ('ar', 'whatsNew.item.instantDelete.title', $json$"حذف الدردشة أو مسحها يستجيب فورًا"$json$::jsonb),
  ('ar', 'whatsNew.item.instantDelete.detail', $json$"لم يعد مسح الدردشة أو حذفها أو حذف المشروع ينتظر الطلب الذي تعمل عليه دردشة أخرى."$json$::jsonb),
  ('fr', 'whatsNew.item.liveClaudeText.title', $json$"La réponse de Claude apparaît pendant qu'il l'écrit"$json$::jsonb),
  ('fr', 'whatsNew.item.liveClaudeText.detail', $json$"La réponse de Claude Code s'affiche désormais au fil des tokens au lieu d'apparaître seulement à la fin de chaque message. La réponse enregistrée reste la même, et les morceaux arrivent à l'écran par petits lots pour que les longues réponses ne ralentissent pas la fenêtre."$json$::jsonb),
  ('fr', 'whatsNew.item.gateDeadline.title', $json$"Le poste de garde ne retient plus une demande pendant des minutes"$json$::jsonb),
  ('fr', 'whatsNew.item.gateDeadline.detail', $json$"Le contrôle d'entrée et le routage attendent le Jev quelques secondes au plus, avec une nouvelle tentative, puis décident avec les heuristiques locales. Après trois échecs d'affilée, l'app cesse d'attendre le Jev pendant cinq minutes, et un appel que l'app relance ne compte qu'une fois dans la limite quotidienne."$json$::jsonb),
  ('fr', 'whatsNew.item.agentOutput.title', $json$"Des échanges plus fiables avec les agents"$json$::jsonb),
  ('fr', 'whatsNew.item.agentOutput.detail', $json$"Une session Codex qui n'existe plus en démarre une nouvelle au lieu d'échouer ; une ligne hors UTF-8 ne fait plus échouer la demande ; une longue demande ne bloque plus un agent qui écrit beaucoup avant de la lire ; l'agent de secours prend le relais même après un long plan ; et les événements d'état internes de Claude ne répètent plus « agent démarré » dans la chronologie."$json$::jsonb),
  ('fr', 'whatsNew.item.projectIndex.title', $json$"L'index du projet suit le .gitignore"$json$::jsonb),
  ('fr', 'whatsNew.item.projectIndex.detail', $json$"Les fichiers ignorés, les environnements virtuels et les dossiers de build restent hors du contexte, et le budget de lecture va d'abord au code : un gros dossier .venv ou coverage ne chasse plus le code du projet de l'index."$json$::jsonb),
  ('fr', 'whatsNew.item.instantDelete.title', $json$"Supprimer ou vider un chat répond tout de suite"$json$::jsonb),
  ('fr', 'whatsNew.item.instantDelete.detail', $json$"Vider un chat, le supprimer ou supprimer un projet n'attend plus la demande qu'un autre chat est en train d'exécuter."$json$::jsonb),
  ('ru', 'whatsNew.item.liveClaudeText.title', $json$"Ответ Claude появляется по мере написания"$json$::jsonb),
  ('ru', 'whatsNew.item.liveClaudeText.detail', $json$"Ответ Claude Code теперь растёт на экране токен за токеном, а не появляется только в конце каждого сообщения. Сохранённый ответ остаётся прежним, а фрагменты приходят на экран небольшими партиями, чтобы длинные ответы не тормозили окно."$json$::jsonb),
  ('ru', 'whatsNew.item.gateDeadline.title', $json$"Проходная больше не держит запрос минутами"$json$::jsonb),
  ('ru', 'whatsNew.item.gateDeadline.detail', $json$"Входная проверка и маршрутизация ждут Jev не дольше нескольких секунд, с одной повторной попыткой, а затем решают по локальным эвристикам. После трёх неудач подряд приложение пять минут не ждёт Jev, а вызов, который приложение повторяет, засчитывается в дневной лимит только один раз."$json$::jsonb),
  ('ru', 'whatsNew.item.agentOutput.title', $json$"Более устойчивая работа с агентами"$json$::jsonb),
  ('ru', 'whatsNew.item.agentOutput.detail', $json$"Несуществующая сессия Codex запускает новую вместо ошибки; строка вне UTF-8 больше не ломает запрос; длинный запрос больше не блокирует агента, который много пишет до того, как его прочитать; резервный агент подхватывает работу даже после долгого планирования; а внутренние события состояния Claude больше не повторяют «агент запущен» в хронологии."$json$::jsonb),
  ('ru', 'whatsNew.item.projectIndex.title', $json$"Индекс проекта учитывает .gitignore"$json$::jsonb),
  ('ru', 'whatsNew.item.projectIndex.detail', $json$"Игнорируемые файлы, виртуальные окружения и папки сборки не попадают в контекст, а бюджет чтения сначала идёт на код: большая папка .venv или coverage больше не вытесняет исходники проекта из индекса."$json$::jsonb),
  ('ru', 'whatsNew.item.instantDelete.title', $json$"Удаление и очистка чата срабатывают сразу"$json$::jsonb),
  ('ru', 'whatsNew.item.instantDelete.detail', $json$"Очистка чата, его удаление или удаление проекта больше не ждут запрос, который выполняется в другом чате."$json$::jsonb),
  ('ja', 'whatsNew.item.liveClaudeText.title', $json$"Claude の回答が書かれるそばから表示されます"$json$::jsonb),
  ('ja', 'whatsNew.item.liveClaudeText.detail', $json$"Claude Code の返信は、各メッセージの終わりを待たずにトークンごとに画面上で伸びていくようになりました。保存される回答はこれまでと同じで、断片は小さなまとまりで画面に届くため、長い回答でもウィンドウが重くなりません。"$json$::jsonb),
  ('ja', 'whatsNew.item.gateDeadline.title', $json$"ゲートがリクエストを何分も止めることはなくなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.gateDeadline.detail', $json$"入口ゲートとルーティングは Jev を最大で数秒、1 回の再試行つきで待ち、その後はローカルのヒューリスティクスで判断します。3 回続けて失敗すると、アプリは 5 分間 Jev を待たなくなり、アプリが再試行した呼び出しは 1 日の上限に 1 回だけ数えられます。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentOutput.title', $json$"エージェントとのやり取りがより安定"$json$::jsonb),
  ('ja', 'whatsNew.item.agentOutput.detail', $json$"存在しなくなった Codex セッションは失敗せずに新しいセッションを始めます。UTF-8 以外の行でリクエストが失敗することはなくなりました。読み込む前に大量に出力するエージェントが長いリクエストで固まることもなくなりました。長い計画のあとでも予備のエージェントが引き継ぎます。Claude の内部状態イベントがタイムラインで「エージェント開始」を繰り返すこともなくなりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.projectIndex.title', $json$"プロジェクトのインデックスが .gitignore に従います"$json$::jsonb),
  ('ja', 'whatsNew.item.projectIndex.detail', $json$"無視されたファイル、仮想環境、ビルドフォルダはコンテキストに入らず、読み込みの予算はまずコードに使われます。大きな .venv や coverage フォルダがプロジェクトのソースをインデックスから押し出すことはなくなりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.instantDelete.title', $json$"チャットの削除やクリアがすぐに反映されます"$json$::jsonb),
  ('ja', 'whatsNew.item.instantDelete.detail', $json$"チャットのクリア、削除、プロジェクトの削除が、別のチャットで実行中のリクエストを待たなくなりました。"$json$::jsonb),
  ('de', 'whatsNew.item.liveClaudeText.title', $json$"Claudes Antwort erscheint, während sie geschrieben wird"$json$::jsonb),
  ('de', 'whatsNew.item.liveClaudeText.detail', $json$"Die Antwort von Claude Code wächst jetzt Token für Token auf dem Bildschirm, statt erst am Ende jeder Nachricht zu erscheinen. Die gespeicherte Antwort bleibt dieselbe, und die Teile erreichen den Bildschirm in kleinen Paketen, damit lange Antworten das Fenster nicht verlangsamen."$json$::jsonb),
  ('de', 'whatsNew.item.gateDeadline.title', $json$"Die Pforte hält eine Anfrage nicht mehr minutenlang fest"$json$::jsonb),
  ('de', 'whatsNew.item.gateDeadline.detail', $json$"Die Eingangspforte und das Routing warten höchstens ein paar Sekunden mit einem Wiederholungsversuch auf den Jev und entscheiden dann mit den lokalen Heuristiken. Nach drei Fehlern in Folge wartet die App fünf Minuten lang nicht mehr auf den Jev, und ein Aufruf, den die App wiederholt, zählt im Tageslimit nur einmal."$json$::jsonb),
  ('de', 'whatsNew.item.agentOutput.title', $json$"Stabilere Gespräche mit den Agenten"$json$::jsonb),
  ('de', 'whatsNew.item.agentOutput.detail', $json$"Eine Codex-Sitzung, die es nicht mehr gibt, startet eine neue, statt zu scheitern; eine Zeile außerhalb von UTF-8 bricht die Anfrage nicht mehr ab; eine lange Anfrage blockiert keinen Agenten mehr, der viel schreibt, bevor er sie liest; der Ersatzagent übernimmt auch nach einer langen Planung; und Claudes interne Statusereignisse wiederholen in der Zeitleiste nicht mehr „Agent gestartet“."$json$::jsonb),
  ('de', 'whatsNew.item.projectIndex.title', $json$"Der Projektindex folgt der .gitignore"$json$::jsonb),
  ('de', 'whatsNew.item.projectIndex.detail', $json$"Ignorierte Dateien, virtuelle Umgebungen und Build-Ordner bleiben aus dem Kontext heraus, und das Lesebudget geht zuerst an den Code: Ein großer .venv- oder coverage-Ordner verdrängt den Quellcode des Projekts nicht mehr aus dem Index."$json$::jsonb),
  ('de', 'whatsNew.item.instantDelete.title', $json$"Einen Chat löschen oder leeren reagiert sofort"$json$::jsonb),
  ('de', 'whatsNew.item.instantDelete.detail', $json$"Einen Chat leeren, löschen oder ein Projekt löschen wartet nicht mehr auf die Anfrage, die ein anderer Chat gerade ausführt."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
