-- v0.44.0: código e caminhos de arquivo mais fáceis de ler nas respostas.
--
-- Só textos: o tamanho e o abrir/recolher dos blocos de código (code.*) e o
-- item da janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'code.lines', $json${"one":"{count} linha","other":"{count} linhas"}$json$::jsonb),
  ('pt-BR', 'code.expand', $json${"one":"Mostrar mais {count} linha","other":"Mostrar mais {count} linhas"}$json$::jsonb),
  ('pt-BR', 'code.collapse', $json$"Mostrar menos"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.readableCode.title', $json$"Código e caminhos de arquivo mais fáceis de ler"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.readableCode.detail', $json$"O código nas respostas ganhou cores por tipo (palavras reservadas, textos, números, comentários), fica sobre um fundo mais fundo com o número das linhas numa margem própria, e bloco comprido abre recolhido. Caminhos de arquivo, mesmo escritos sem crase, viram um selo com a pasta apagada e o nome do arquivo em destaque."$json$::jsonb),
  ('en', 'code.lines', $json${"one":"{count} line","other":"{count} lines"}$json$::jsonb),
  ('en', 'code.expand', $json${"one":"Show {count} more line","other":"Show {count} more lines"}$json$::jsonb),
  ('en', 'code.collapse', $json$"Show less"$json$::jsonb),
  ('en', 'whatsNew.item.readableCode.title', $json$"Easier-to-read code and file paths"$json$::jsonb),
  ('en', 'whatsNew.item.readableCode.detail', $json$"Code in answers is colored by kind (keywords, strings, numbers, comments), sits on a deeper background with line numbers in their own margin, and long blocks open collapsed. File paths, even when written without backticks, become a badge with the folder dimmed and the file name highlighted."$json$::jsonb),
  ('es', 'code.lines', $json${"one":"{count} línea","other":"{count} líneas"}$json$::jsonb),
  ('es', 'code.expand', $json${"one":"Mostrar {count} línea más","other":"Mostrar {count} líneas más"}$json$::jsonb),
  ('es', 'code.collapse', $json$"Mostrar menos"$json$::jsonb),
  ('es', 'whatsNew.item.readableCode.title', $json$"Código y rutas de archivo más fáciles de leer"$json$::jsonb),
  ('es', 'whatsNew.item.readableCode.detail', $json$"El código en las respuestas se colorea por tipo (palabras reservadas, cadenas, números, comentarios), va sobre un fondo más profundo con los números de línea en su propio margen, y los bloques largos se abren contraídos. Las rutas de archivo, incluso escritas sin comillas invertidas, se convierten en una etiqueta con la carpeta atenuada y el nombre del archivo destacado."$json$::jsonb),
  ('zh-CN', 'code.lines', $json${"other":"{count} 行"}$json$::jsonb),
  ('zh-CN', 'code.expand', $json${"other":"再显示 {count} 行"}$json$::jsonb),
  ('zh-CN', 'code.collapse', $json$"收起"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.readableCode.title', $json$"代码和文件路径更易阅读"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.readableCode.detail', $json$"回答中的代码按类型着色（关键字、字符串、数字、注释），放在更深的背景上，行号有单独的边栏，长代码块默认折叠。文件路径即使没有反引号，也会变成一个标签，文件夹变暗，文件名突出显示。"$json$::jsonb),
  ('hi', 'code.lines', $json${"one":"{count} पंक्ति","other":"{count} पंक्तियाँ"}$json$::jsonb),
  ('hi', 'code.expand', $json${"one":"{count} और पंक्ति दिखाएँ","other":"{count} और पंक्तियाँ दिखाएँ"}$json$::jsonb),
  ('hi', 'code.collapse', $json$"कम दिखाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.readableCode.title', $json$"पढ़ने में आसान कोड और फ़ाइल पथ"$json$::jsonb),
  ('hi', 'whatsNew.item.readableCode.detail', $json$"जवाबों में कोड प्रकार के अनुसार रंगीन होता है (कीवर्ड, स्ट्रिंग, संख्या, टिप्पणी), गहरी पृष्ठभूमि पर दिखता है और पंक्ति संख्याएँ अलग हाशिये में होती हैं; लंबे ब्लॉक सिमटे हुए खुलते हैं। फ़ाइल पथ, बिना बैकटिक के लिखे होने पर भी, एक बैज बन जाते हैं जिसमें फ़ोल्डर हल्का और फ़ाइल का नाम उभरा होता है।"$json$::jsonb),
  ('ar', 'code.lines', $json${"zero":"{count} سطر","one":"سطر واحد","two":"سطران","few":"{count} أسطر","many":"{count} سطرًا","other":"{count} سطر"}$json$::jsonb),
  ('ar', 'code.expand', $json${"zero":"عرض {count} سطر إضافي","one":"عرض سطر إضافي واحد","two":"عرض سطرين إضافيين","few":"عرض {count} أسطر إضافية","many":"عرض {count} سطرًا إضافيًا","other":"عرض {count} سطر إضافي"}$json$::jsonb),
  ('ar', 'code.collapse', $json$"عرض أقل"$json$::jsonb),
  ('ar', 'whatsNew.item.readableCode.title', $json$"شيفرة ومسارات ملفات أسهل في القراءة"$json$::jsonb),
  ('ar', 'whatsNew.item.readableCode.detail', $json$"أصبحت الشيفرة في الإجابات ملونة حسب النوع (الكلمات المحجوزة والنصوص والأرقام والتعليقات)، وتظهر على خلفية أعمق مع أرقام الأسطر في هامش خاص، وتُفتح الكتل الطويلة مطوية. وتتحول مسارات الملفات، حتى المكتوبة بلا علامات اقتباس خلفية، إلى شارة يظهر فيها المجلد باهتًا واسم الملف بارزًا."$json$::jsonb),
  ('fr', 'code.lines', $json${"one":"{count} ligne","other":"{count} lignes"}$json$::jsonb),
  ('fr', 'code.expand', $json${"one":"Afficher {count} ligne de plus","other":"Afficher {count} lignes de plus"}$json$::jsonb),
  ('fr', 'code.collapse', $json$"Afficher moins"$json$::jsonb),
  ('fr', 'whatsNew.item.readableCode.title', $json$"Code et chemins de fichiers plus lisibles"$json$::jsonb),
  ('fr', 'whatsNew.item.readableCode.detail', $json$"Le code des réponses est coloré par type (mots-clés, chaînes, nombres, commentaires), posé sur un fond plus profond avec les numéros de ligne dans leur propre marge, et les blocs longs s'ouvrent repliés. Les chemins de fichiers, même écrits sans accents graves, deviennent un badge avec le dossier atténué et le nom du fichier mis en avant."$json$::jsonb),
  ('ru', 'code.lines', $json${"one":"{count} строка","few":"{count} строки","many":"{count} строк","other":"{count} строки"}$json$::jsonb),
  ('ru', 'code.expand', $json${"one":"Показать ещё {count} строку","few":"Показать ещё {count} строки","many":"Показать ещё {count} строк","other":"Показать ещё {count} строки"}$json$::jsonb),
  ('ru', 'code.collapse', $json$"Свернуть"$json$::jsonb),
  ('ru', 'whatsNew.item.readableCode.title', $json$"Код и пути к файлам читаются легче"$json$::jsonb),
  ('ru', 'whatsNew.item.readableCode.detail', $json$"Код в ответах раскрашен по типу (ключевые слова, строки, числа, комментарии), лежит на более глубоком фоне, номера строк вынесены на отдельное поле, а длинные блоки открываются свёрнутыми. Пути к файлам, даже без обратных кавычек, превращаются в метку с приглушённой папкой и выделенным именем файла."$json$::jsonb),
  ('ja', 'code.lines', $json${"other":"{count} 行"}$json$::jsonb),
  ('ja', 'code.expand', $json${"other":"さらに {count} 行を表示"}$json$::jsonb),
  ('ja', 'code.collapse', $json$"折りたたむ"$json$::jsonb),
  ('ja', 'whatsNew.item.readableCode.title', $json$"読みやすくなったコードとファイルパス"$json$::jsonb),
  ('ja', 'whatsNew.item.readableCode.detail', $json$"回答内のコードは種類ごと（キーワード、文字列、数値、コメント）に色分けされ、より深い背景の上に行番号専用の余白付きで表示されます。長いブロックは折りたたまれて開きます。ファイルパスはバッククォートなしで書かれていても、フォルダを薄く、ファイル名を強調したバッジになります。"$json$::jsonb),
  ('de', 'code.lines', $json${"one":"{count} Zeile","other":"{count} Zeilen"}$json$::jsonb),
  ('de', 'code.expand', $json${"one":"{count} weitere Zeile zeigen","other":"{count} weitere Zeilen zeigen"}$json$::jsonb),
  ('de', 'code.collapse', $json$"Weniger zeigen"$json$::jsonb),
  ('de', 'whatsNew.item.readableCode.title', $json$"Leichter lesbarer Code und Dateipfade"$json$::jsonb),
  ('de', 'whatsNew.item.readableCode.detail', $json$"Code in Antworten ist nach Art eingefärbt (Schlüsselwörter, Zeichenketten, Zahlen, Kommentare), liegt auf einem tieferen Hintergrund mit Zeilennummern in einem eigenen Rand, und lange Blöcke öffnen sich eingeklappt. Dateipfade, auch ohne Backticks geschrieben, werden zu einem Abzeichen mit abgedunkeltem Ordner und hervorgehobenem Dateinamen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
