-- Os textos que o núcleo devolve como chave do i18n: erros dos comandos,
-- avisos gravados no chat (pedido barrado, falha, resposta a uma pergunta) e
-- os nomes das fontes de leitura. A tela os traduz (ver src-tauri/src/i18n.rs).
insert into public.translations (locale, key, value) values
  ('pt-BR', 'error.unexpected', $json$"Algo deu errado: {reason}"$json$::jsonb),
  ('pt-BR', 'session.required', $json$"Entre na sua conta para continuar."$json$::jsonb),
  ('pt-BR', 'session.expired', $json$"Sua sessão expirou. Entre de novo."$json$::jsonb),
  ('pt-BR', 'session.invalid', $json$"A sessão não é válida: {reason}"$json$::jsonb),
  ('pt-BR', 'session.unknownKey', $json$"A sessão foi assinada por uma chave desconhecida."$json$::jsonb),
  ('pt-BR', 'session.offlineFirst', $json$"No primeiro acesso é preciso rede para conferir a sessão: {reason}"$json$::jsonb),
  ('pt-BR', 'session.keyOffline', $json$"A chave da sessão é nova e não há rede para buscá-la: {reason}"$json$::jsonb),
  ('pt-BR', 'prompt.noChat', $json$"Selecione um chat antes de enviar."$json$::jsonb),
  ('pt-BR', 'prompt.empty', $json$"Não há o que enviar."$json$::jsonb),
  ('pt-BR', 'chat.notFound', $json$"Chat não encontrado."$json$::jsonb),
  ('pt-BR', 'project.notFound', $json$"Projeto não encontrado."$json$::jsonb),
  ('pt-BR', 'project.nameRequired', $json$"O nome do projeto é obrigatório."$json$::jsonb),
  ('pt-BR', 'project.folderMissing', $json$"A pasta do projeto não existe mais: {path}"$json$::jsonb),
  ('pt-BR', 'turn.notFound', $json$"O pedido {turn} não existe mais."$json$::jsonb),
  ('pt-BR', 'turn.otherChat', $json$"O pedido {turn} é de outro chat."$json$::jsonb),
  ('pt-BR', 'turn.noAnswer', $json$"A execução terminou sem resposta."$json$::jsonb),
  ('pt-BR', 'question.gone', $json$"Essa pergunta não existe mais."$json$::jsonb),
  ('pt-BR', 'question.closed', $json$"Essa pergunta já foi encerrada."$json$::jsonb),
  ('pt-BR', 'question.originGone', $json$"O pedido que originou essa pergunta não existe mais."$json$::jsonb),
  ('pt-BR', 'answer.noul', $json$"Responda sim ou não, ou escreva a resposta."$json$::jsonb),
  ('pt-BR', 'answer.pickOne', $json$"Escolha ao menos uma alternativa, ou escreva a resposta."$json$::jsonb),
  ('pt-BR', 'answer.single', $json$"Esta pergunta aceita uma alternativa só."$json$::jsonb),
  ('pt-BR', 'answer.unknown', $json$"“{option}” não é uma das alternativas oferecidas."$json$::jsonb),
  ('pt-BR', 'ask.answer', $json$"Resposta à pergunta «{question}»: {answer}"$json$::jsonb),
  ('pt-BR', 'gate.blocked', $json$"A portaria barrou este pedido com {score} de 100 (o mínimo para um {scope} é {demand})."$json$::jsonb),
  ('pt-BR', 'gate.missing', $json$"O que está faltando:"$json$::jsonb),
  ('pt-BR', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('pt-BR', 'gate.asks.0', $json$"Diga o que deve mudar e como você confirma que mudou."$json$::jsonb),
  ('pt-BR', 'gate.asks.1', $json$"Diga o objetivo, onde mexer e como você confirma que ficou pronto."$json$::jsonb),
  ('pt-BR', 'gate.asks.2', $json$"Um pedido desse tamanho precisa do objetivo, dos arquivos ou módulos envolvidos e do critério de pronto. Se der, quebre em partes."$json$::jsonb),
  ('pt-BR', 'source.jev', $json$"Jev"$json$::jsonb),
  ('pt-BR', 'source.local', $json$"heurísticas locais"$json$::jsonb),
  ('pt-BR', 'source.fallback', $json$"heurísticas locais (o Jev não respondeu)"$json$::jsonb),
  ('pt-BR', 'settings.invalidValue', $json$"Valor inválido para {field}: “{value}”."$json$::jsonb),
  ('pt-BR', 'settings.field.claude.permissionMode', $json$"o modo de permissão do Claude Code"$json$::jsonb),
  ('pt-BR', 'settings.field.claude.effort', $json$"o esforço do Claude Code"$json$::jsonb),
  ('pt-BR', 'settings.field.claude.blockedTools', $json$"as ferramentas bloqueadas do Claude Code"$json$::jsonb),
  ('pt-BR', 'settings.field.codex.sandbox', $json$"o sandbox do Codex"$json$::jsonb),
  ('pt-BR', 'settings.field.codex.reasoning', $json$"o raciocínio do Codex"$json$::jsonb),
  ('pt-BR', 'settings.field.copilot.toolAccess', $json$"o acesso a ferramentas do Copilot"$json$::jsonb),
  ('pt-BR', 'settings.field.copilot.blockedTools', $json$"as ferramentas bloqueadas do Copilot"$json$::jsonb),
  ('pt-BR', 'settings.field.model.capability', $json$"a capacidade"$json$::jsonb),
  ('pt-BR', 'settings.field.model.cost', $json$"o custo"$json$::jsonb),
  ('pt-BR', 'settings.field.model.speed', $json$"a velocidade"$json$::jsonb),
  ('pt-BR', 'settings.claude.fallback', $json$"O modelo reserva do Claude Code precisa ser um dos modelos cadastrados nele."$json$::jsonb),
  ('pt-BR', 'settings.claude.budget', $json$"O limite de gasto do Claude Code precisa ficar entre US$ 0,01 e US$ 1.000."$json$::jsonb),
  ('pt-BR', 'settings.claude.instructions', $json$"As instruções extras do Claude Code passam de {max} caracteres."$json$::jsonb),
  ('pt-BR', 'settings.invalidOptions', $json$"Opções inválidas: {reason}"$json$::jsonb),
  ('pt-BR', 'settings.commandRequired', $json$"Informe o comando do {agent}."$json$::jsonb),
  ('pt-BR', 'settings.commandArgs', $json$"O comando do {agent} é só o nome ou o caminho do executável, sem argumentos."$json$::jsonb),
  ('pt-BR', 'settings.timeout', $json$"O tempo de silêncio do {agent} precisa ficar entre {min} e {max} segundos."$json$::jsonb),
  ('pt-BR', 'settings.noActiveModel', $json$"O {agent} está ligado mas não tem nenhum modelo ativo."$json$::jsonb),
  ('pt-BR', 'settings.modelNoId', $json$"Há um modelo sem identificador no {agent}."$json$::jsonb),
  ('pt-BR', 'settings.modelBadId', $json$"O identificador “{name}” tem caracteres que nenhum agente aceita."$json$::jsonb),
  ('pt-BR', 'settings.modelDuplicate', $json$"O modelo “{name}” aparece duas vezes no {agent}."$json$::jsonb),
  ('pt-BR', 'settings.modelNoCapability', $json$"O modelo “{name}” precisa de ao menos uma capacidade."$json$::jsonb),
  ('pt-BR', 'settings.contextWindow', $json$"A janela de contexto de “{name}” precisa ficar entre {min} e {max} tokens."$json$::jsonb),
  ('pt-BR', 'settings.noAgent', $json$"Ligue ao menos um agente."$json$::jsonb),
  ('pt-BR', 'provider.failed', $json$"O provedor “{provider}” falhou ({exit}): {reason}"$json$::jsonb),
  ('pt-BR', 'provider.failedSilent', $json$"O provedor “{provider}” falhou ({exit}) sem escrever o motivo; rode `{command}` no terminal para ver o erro."$json$::jsonb),
  ('pt-BR', 'provider.exit.code', $json$"saiu com o código {code}"$json$::jsonb),
  ('pt-BR', 'provider.exit.signal', $json$"foi interrompido por um sinal"$json$::jsonb),
  ('pt-BR', 'provider.exit.announced', $json$"anunciou um erro"$json$::jsonb),
  ('pt-BR', 'provider.silent', $json$"O provedor “{provider}” passou {seconds}s sem dar sinal de vida e foi encerrado; se o trabalho costuma demorar mais em silêncio, aumente o tempo de silêncio dele nas configurações."$json$::jsonb),
  ('pt-BR', 'provider.timeout', $json$"O provedor “{provider}” excedeu o tempo limite; verifique o serviço e o tempo limite configurado."$json$::jsonb),
  ('pt-BR', 'provider.connect', $json$"Não foi possível conectar ao provedor “{provider}”; verifique se o serviço está em execução, a rede e a URL base."$json$::jsonb),
  ('pt-BR', 'provider.send', $json$"Falha ao enviar o pedido ao provedor “{provider}”: {reason}"$json$::jsonb),
  ('en', 'error.unexpected', $json$"Something went wrong: {reason}"$json$::jsonb),
  ('en', 'session.required', $json$"Sign in to continue."$json$::jsonb),
  ('en', 'session.expired', $json$"Your session has expired. Sign in again."$json$::jsonb),
  ('en', 'session.invalid', $json$"This session is not valid: {reason}"$json$::jsonb),
  ('en', 'session.unknownKey', $json$"The session was signed by an unknown key."$json$::jsonb),
  ('en', 'session.offlineFirst', $json$"The first sign-in needs a network connection to check the session: {reason}"$json$::jsonb),
  ('en', 'session.keyOffline', $json$"The session key is new and there is no network to fetch it: {reason}"$json$::jsonb),
  ('en', 'prompt.noChat', $json$"Select a chat before sending."$json$::jsonb),
  ('en', 'prompt.empty', $json$"There is nothing to send."$json$::jsonb),
  ('en', 'chat.notFound', $json$"Chat not found."$json$::jsonb),
  ('en', 'project.notFound', $json$"Project not found."$json$::jsonb),
  ('en', 'project.nameRequired', $json$"The project name is required."$json$::jsonb),
  ('en', 'project.folderMissing', $json$"The project folder no longer exists: {path}"$json$::jsonb),
  ('en', 'turn.notFound', $json$"Request {turn} no longer exists."$json$::jsonb),
  ('en', 'turn.otherChat', $json$"Request {turn} belongs to another chat."$json$::jsonb),
  ('en', 'turn.noAnswer', $json$"The run ended without an answer."$json$::jsonb),
  ('en', 'question.gone', $json$"This question no longer exists."$json$::jsonb),
  ('en', 'question.closed', $json$"This question has already been closed."$json$::jsonb),
  ('en', 'question.originGone', $json$"The request behind this question no longer exists."$json$::jsonb),
  ('en', 'answer.noul', $json$"Answer yes or no, or write your answer."$json$::jsonb),
  ('en', 'answer.pickOne', $json$"Pick at least one option, or write your answer."$json$::jsonb),
  ('en', 'answer.single', $json$"This question accepts only one option."$json$::jsonb),
  ('en', 'answer.unknown', $json$"“{option}” is not one of the options offered."$json$::jsonb),
  ('en', 'ask.answer', $json$"Answer to the question «{question}»: {answer}"$json$::jsonb),
  ('en', 'gate.blocked', $json$"The gatehouse blocked this request with {score} out of 100 (the minimum for a {scope} is {demand})."$json$::jsonb),
  ('en', 'gate.missing', $json$"What is missing:"$json$::jsonb),
  ('en', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('en', 'gate.asks.0', $json$"Say what should change and how you will confirm it changed."$json$::jsonb),
  ('en', 'gate.asks.1', $json$"Say the goal, where to change and how you will confirm it is done."$json$::jsonb),
  ('en', 'gate.asks.2', $json$"A request this size needs the goal, the files or modules involved and the definition of done. If you can, split it into parts."$json$::jsonb),
  ('en', 'source.jev', $json$"Jev"$json$::jsonb),
  ('en', 'source.local', $json$"local heuristics"$json$::jsonb),
  ('en', 'source.fallback', $json$"local heuristics (the Jev did not answer)"$json$::jsonb),
  ('en', 'settings.invalidValue', $json$"Invalid value for {field}: “{value}”."$json$::jsonb),
  ('en', 'settings.field.claude.permissionMode', $json$"the Claude Code permission mode"$json$::jsonb),
  ('en', 'settings.field.claude.effort', $json$"the Claude Code effort"$json$::jsonb),
  ('en', 'settings.field.claude.blockedTools', $json$"the Claude Code blocked tools"$json$::jsonb),
  ('en', 'settings.field.codex.sandbox', $json$"the Codex sandbox"$json$::jsonb),
  ('en', 'settings.field.codex.reasoning', $json$"the Codex reasoning"$json$::jsonb),
  ('en', 'settings.field.copilot.toolAccess', $json$"the Copilot tool access"$json$::jsonb),
  ('en', 'settings.field.copilot.blockedTools', $json$"the Copilot blocked tools"$json$::jsonb),
  ('en', 'settings.field.model.capability', $json$"the capability"$json$::jsonb),
  ('en', 'settings.field.model.cost', $json$"the cost"$json$::jsonb),
  ('en', 'settings.field.model.speed', $json$"the speed"$json$::jsonb),
  ('en', 'settings.claude.fallback', $json$"The Claude Code fallback model must be one of its registered models."$json$::jsonb),
  ('en', 'settings.claude.budget', $json$"The Claude Code spending limit must be between US$ 0.01 and US$ 1,000."$json$::jsonb),
  ('en', 'settings.claude.instructions', $json$"The Claude Code extra instructions exceed {max} characters."$json$::jsonb),
  ('en', 'settings.invalidOptions', $json$"Invalid options: {reason}"$json$::jsonb),
  ('en', 'settings.commandRequired', $json$"Enter the {agent} command."$json$::jsonb),
  ('en', 'settings.commandArgs', $json$"The {agent} command is only the executable name or path, without arguments."$json$::jsonb),
  ('en', 'settings.timeout', $json$"The {agent} silence timeout must be between {min} and {max} seconds."$json$::jsonb),
  ('en', 'settings.noActiveModel', $json$"{agent} is on but has no active model."$json$::jsonb),
  ('en', 'settings.modelNoId', $json$"There is a model without an identifier in {agent}."$json$::jsonb),
  ('en', 'settings.modelBadId', $json$"The identifier “{name}” has characters no agent accepts."$json$::jsonb),
  ('en', 'settings.modelDuplicate', $json$"The model “{name}” appears twice in {agent}."$json$::jsonb),
  ('en', 'settings.modelNoCapability', $json$"The model “{name}” needs at least one capability."$json$::jsonb),
  ('en', 'settings.contextWindow', $json$"The context window of “{name}” must be between {min} and {max} tokens."$json$::jsonb),
  ('en', 'settings.noAgent', $json$"Turn on at least one agent."$json$::jsonb),
  ('en', 'provider.failed', $json$"The provider “{provider}” failed ({exit}): {reason}"$json$::jsonb),
  ('en', 'provider.failedSilent', $json$"The provider “{provider}” failed ({exit}) without saying why; run `{command}` in a terminal to see the error."$json$::jsonb),
  ('en', 'provider.exit.code', $json$"exited with code {code}"$json$::jsonb),
  ('en', 'provider.exit.signal', $json$"was stopped by a signal"$json$::jsonb),
  ('en', 'provider.exit.announced', $json$"reported an error"$json$::jsonb),
  ('en', 'provider.silent', $json$"The provider “{provider}” went {seconds}s without a sign of life and was stopped; if its work usually stays silent longer, raise its silence timeout in the settings."$json$::jsonb),
  ('en', 'provider.timeout', $json$"The provider “{provider}” timed out; check the service and the configured timeout."$json$::jsonb),
  ('en', 'provider.connect', $json$"Could not connect to the provider “{provider}”; check that the service is running, the network and the base URL."$json$::jsonb),
  ('en', 'provider.send', $json$"Failed to send the request to the provider “{provider}”: {reason}"$json$::jsonb),
  ('es', 'error.unexpected', $json$"Algo salió mal: {reason}"$json$::jsonb),
  ('es', 'session.required', $json$"Inicia sesión para continuar."$json$::jsonb),
  ('es', 'session.expired', $json$"Tu sesión ha caducado. Inicia sesión de nuevo."$json$::jsonb),
  ('es', 'session.invalid', $json$"La sesión no es válida: {reason}"$json$::jsonb),
  ('es', 'session.unknownKey', $json$"La sesión fue firmada con una clave desconocida."$json$::jsonb),
  ('es', 'session.offlineFirst', $json$"El primer acceso necesita conexión para verificar la sesión: {reason}"$json$::jsonb),
  ('es', 'session.keyOffline', $json$"La clave de la sesión es nueva y no hay red para obtenerla: {reason}"$json$::jsonb),
  ('es', 'prompt.noChat', $json$"Selecciona un chat antes de enviar."$json$::jsonb),
  ('es', 'prompt.empty', $json$"No hay nada que enviar."$json$::jsonb),
  ('es', 'chat.notFound', $json$"No se encontró el chat."$json$::jsonb),
  ('es', 'project.notFound', $json$"No se encontró el proyecto."$json$::jsonb),
  ('es', 'project.nameRequired', $json$"El nombre del proyecto es obligatorio."$json$::jsonb),
  ('es', 'project.folderMissing', $json$"La carpeta del proyecto ya no existe: {path}"$json$::jsonb),
  ('es', 'turn.notFound', $json$"La solicitud {turn} ya no existe."$json$::jsonb),
  ('es', 'turn.otherChat', $json$"La solicitud {turn} pertenece a otro chat."$json$::jsonb),
  ('es', 'turn.noAnswer', $json$"La ejecución terminó sin respuesta."$json$::jsonb),
  ('es', 'question.gone', $json$"Esta pregunta ya no existe."$json$::jsonb),
  ('es', 'question.closed', $json$"Esta pregunta ya se cerró."$json$::jsonb),
  ('es', 'question.originGone', $json$"La solicitud que originó esta pregunta ya no existe."$json$::jsonb),
  ('es', 'answer.noul', $json$"Responde sí o no, o escribe tu respuesta."$json$::jsonb),
  ('es', 'answer.pickOne', $json$"Elige al menos una opción, o escribe tu respuesta."$json$::jsonb),
  ('es', 'answer.single', $json$"Esta pregunta acepta una sola opción."$json$::jsonb),
  ('es', 'answer.unknown', $json$"“{option}” no es una de las opciones ofrecidas."$json$::jsonb),
  ('es', 'ask.answer', $json$"Respuesta a la pregunta «{question}»: {answer}"$json$::jsonb),
  ('es', 'gate.blocked', $json$"La portería bloqueó esta solicitud con {score} de 100 (el mínimo para un {scope} es {demand})."$json$::jsonb),
  ('es', 'gate.missing', $json$"Lo que falta:"$json$::jsonb),
  ('es', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('es', 'gate.asks.0', $json$"Di qué debe cambiar y cómo confirmarás que cambió."$json$::jsonb),
  ('es', 'gate.asks.1', $json$"Di el objetivo, dónde cambiar y cómo confirmarás que está listo."$json$::jsonb),
  ('es', 'gate.asks.2', $json$"Una solicitud de este tamaño necesita el objetivo, los archivos o módulos involucrados y el criterio de terminado. Si puedes, divídela en partes."$json$::jsonb),
  ('es', 'source.jev', $json$"Jev"$json$::jsonb),
  ('es', 'source.local', $json$"heurísticas locales"$json$::jsonb),
  ('es', 'source.fallback', $json$"heurísticas locales (el Jev no respondió)"$json$::jsonb),
  ('es', 'settings.invalidValue', $json$"Valor no válido para {field}: “{value}”."$json$::jsonb),
  ('es', 'settings.field.claude.permissionMode', $json$"el modo de permisos de Claude Code"$json$::jsonb),
  ('es', 'settings.field.claude.effort', $json$"el esfuerzo de Claude Code"$json$::jsonb),
  ('es', 'settings.field.claude.blockedTools', $json$"las herramientas bloqueadas de Claude Code"$json$::jsonb),
  ('es', 'settings.field.codex.sandbox', $json$"el sandbox de Codex"$json$::jsonb),
  ('es', 'settings.field.codex.reasoning', $json$"el razonamiento de Codex"$json$::jsonb),
  ('es', 'settings.field.copilot.toolAccess', $json$"el acceso a herramientas de Copilot"$json$::jsonb),
  ('es', 'settings.field.copilot.blockedTools', $json$"las herramientas bloqueadas de Copilot"$json$::jsonb),
  ('es', 'settings.field.model.capability', $json$"la capacidad"$json$::jsonb),
  ('es', 'settings.field.model.cost', $json$"el costo"$json$::jsonb),
  ('es', 'settings.field.model.speed', $json$"la velocidad"$json$::jsonb),
  ('es', 'settings.claude.fallback', $json$"El modelo de respaldo de Claude Code debe ser uno de sus modelos registrados."$json$::jsonb),
  ('es', 'settings.claude.budget', $json$"El límite de gasto de Claude Code debe estar entre US$ 0,01 y US$ 1.000."$json$::jsonb),
  ('es', 'settings.claude.instructions', $json$"Las instrucciones adicionales de Claude Code superan los {max} caracteres."$json$::jsonb),
  ('es', 'settings.invalidOptions', $json$"Opciones no válidas: {reason}"$json$::jsonb),
  ('es', 'settings.commandRequired', $json$"Indica el comando de {agent}."$json$::jsonb),
  ('es', 'settings.commandArgs', $json$"El comando de {agent} es solo el nombre o la ruta del ejecutable, sin argumentos."$json$::jsonb),
  ('es', 'settings.timeout', $json$"El tiempo de silencio de {agent} debe estar entre {min} y {max} segundos."$json$::jsonb),
  ('es', 'settings.noActiveModel', $json$"{agent} está activado pero no tiene ningún modelo activo."$json$::jsonb),
  ('es', 'settings.modelNoId', $json$"Hay un modelo sin identificador en {agent}."$json$::jsonb),
  ('es', 'settings.modelBadId', $json$"El identificador “{name}” tiene caracteres que ningún agente acepta."$json$::jsonb),
  ('es', 'settings.modelDuplicate', $json$"El modelo “{name}” aparece dos veces en {agent}."$json$::jsonb),
  ('es', 'settings.modelNoCapability', $json$"El modelo “{name}” necesita al menos una capacidad."$json$::jsonb),
  ('es', 'settings.contextWindow', $json$"La ventana de contexto de “{name}” debe estar entre {min} y {max} tokens."$json$::jsonb),
  ('es', 'settings.noAgent', $json$"Activa al menos un agente."$json$::jsonb),
  ('es', 'provider.failed', $json$"El proveedor “{provider}” falló ({exit}): {reason}"$json$::jsonb),
  ('es', 'provider.failedSilent', $json$"El proveedor “{provider}” falló ({exit}) sin indicar el motivo; ejecuta `{command}` en una terminal para ver el error."$json$::jsonb),
  ('es', 'provider.exit.code', $json$"salió con el código {code}"$json$::jsonb),
  ('es', 'provider.exit.signal', $json$"fue interrumpido por una señal"$json$::jsonb),
  ('es', 'provider.exit.announced', $json$"informó un error"$json$::jsonb),
  ('es', 'provider.silent', $json$"El proveedor “{provider}” pasó {seconds}s sin dar señales de vida y se detuvo; si su trabajo suele tardar más en silencio, aumenta su tiempo de silencio en la configuración."$json$::jsonb),
  ('es', 'provider.timeout', $json$"El proveedor “{provider}” superó el tiempo límite; revisa el servicio y el tiempo límite configurado."$json$::jsonb),
  ('es', 'provider.connect', $json$"No se pudo conectar con el proveedor “{provider}”; comprueba que el servicio esté en ejecución, la red y la URL base."$json$::jsonb),
  ('es', 'provider.send', $json$"No se pudo enviar la solicitud al proveedor “{provider}”: {reason}"$json$::jsonb),
  ('zh-CN', 'error.unexpected', $json$"出了点问题：{reason}"$json$::jsonb),
  ('zh-CN', 'session.required', $json$"请登录后继续。"$json$::jsonb),
  ('zh-CN', 'session.expired', $json$"会话已过期，请重新登录。"$json$::jsonb),
  ('zh-CN', 'session.invalid', $json$"会话无效：{reason}"$json$::jsonb),
  ('zh-CN', 'session.unknownKey', $json$"会话由未知密钥签名。"$json$::jsonb),
  ('zh-CN', 'session.offlineFirst', $json$"首次登录需要网络来验证会话：{reason}"$json$::jsonb),
  ('zh-CN', 'session.keyOffline', $json$"会话密钥是新的，且没有网络可获取：{reason}"$json$::jsonb),
  ('zh-CN', 'prompt.noChat', $json$"发送前请先选择一个对话。"$json$::jsonb),
  ('zh-CN', 'prompt.empty', $json$"没有可发送的内容。"$json$::jsonb),
  ('zh-CN', 'chat.notFound', $json$"找不到该对话。"$json$::jsonb),
  ('zh-CN', 'project.notFound', $json$"找不到该项目。"$json$::jsonb),
  ('zh-CN', 'project.nameRequired', $json$"项目名称为必填项。"$json$::jsonb),
  ('zh-CN', 'project.folderMissing', $json$"项目文件夹已不存在：{path}"$json$::jsonb),
  ('zh-CN', 'turn.notFound', $json$"请求 {turn} 已不存在。"$json$::jsonb),
  ('zh-CN', 'turn.otherChat', $json$"请求 {turn} 属于另一个对话。"$json$::jsonb),
  ('zh-CN', 'turn.noAnswer', $json$"运行结束，但没有回答。"$json$::jsonb),
  ('zh-CN', 'question.gone', $json$"这个问题已不存在。"$json$::jsonb),
  ('zh-CN', 'question.closed', $json$"这个问题已关闭。"$json$::jsonb),
  ('zh-CN', 'question.originGone', $json$"引出这个问题的请求已不存在。"$json$::jsonb),
  ('zh-CN', 'answer.noul', $json$"请回答是或否，或写下你的回答。"$json$::jsonb),
  ('zh-CN', 'answer.pickOne', $json$"请至少选择一个选项，或写下你的回答。"$json$::jsonb),
  ('zh-CN', 'answer.single', $json$"这个问题只接受一个选项。"$json$::jsonb),
  ('zh-CN', 'answer.unknown', $json$"“{option}”不是给出的选项之一。"$json$::jsonb),
  ('zh-CN', 'ask.answer', $json$"对问题「{question}」的回答：{answer}"$json$::jsonb),
  ('zh-CN', 'gate.blocked', $json$"门房以 {score}/100 拦下了这个请求（{scope} 的最低分是 {demand}）。"$json$::jsonb),
  ('zh-CN', 'gate.missing', $json$"缺少的内容："$json$::jsonb),
  ('zh-CN', 'gate.missing.item', $json$"- {criterion}：{reading}"$json$::jsonb),
  ('zh-CN', 'gate.asks.0', $json$"说明要改什么，以及你如何确认已经改好。"$json$::jsonb),
  ('zh-CN', 'gate.asks.1', $json$"说明目标、要改的位置，以及你如何确认完成。"$json$::jsonb),
  ('zh-CN', 'gate.asks.2', $json$"这么大的请求需要目标、涉及的文件或模块以及完成标准。如果可以，请拆分成几部分。"$json$::jsonb),
  ('zh-CN', 'source.jev', $json$"Jev"$json$::jsonb),
  ('zh-CN', 'source.local', $json$"本地启发式规则"$json$::jsonb),
  ('zh-CN', 'source.fallback', $json$"本地启发式规则（Jev 未响应）"$json$::jsonb),
  ('zh-CN', 'settings.invalidValue', $json$"{field} 的值无效：“{value}”。"$json$::jsonb),
  ('zh-CN', 'settings.field.claude.permissionMode', $json$"Claude Code 的权限模式"$json$::jsonb),
  ('zh-CN', 'settings.field.claude.effort', $json$"Claude Code 的投入程度"$json$::jsonb),
  ('zh-CN', 'settings.field.claude.blockedTools', $json$"Claude Code 中被禁用的工具"$json$::jsonb),
  ('zh-CN', 'settings.field.codex.sandbox', $json$"Codex 的沙箱"$json$::jsonb),
  ('zh-CN', 'settings.field.codex.reasoning', $json$"Codex 的推理强度"$json$::jsonb),
  ('zh-CN', 'settings.field.copilot.toolAccess', $json$"Copilot 的工具访问权限"$json$::jsonb),
  ('zh-CN', 'settings.field.copilot.blockedTools', $json$"Copilot 中被禁用的工具"$json$::jsonb),
  ('zh-CN', 'settings.field.model.capability', $json$"能力"$json$::jsonb),
  ('zh-CN', 'settings.field.model.cost', $json$"成本"$json$::jsonb),
  ('zh-CN', 'settings.field.model.speed', $json$"速度"$json$::jsonb),
  ('zh-CN', 'settings.claude.fallback', $json$"Claude Code 的备用模型必须是已登记的模型之一。"$json$::jsonb),
  ('zh-CN', 'settings.claude.budget', $json$"Claude Code 的花费上限必须在 0.01 至 1,000 美元之间。"$json$::jsonb),
  ('zh-CN', 'settings.claude.instructions', $json$"Claude Code 的附加指令超过 {max} 个字符。"$json$::jsonb),
  ('zh-CN', 'settings.invalidOptions', $json$"选项无效：{reason}"$json$::jsonb),
  ('zh-CN', 'settings.commandRequired', $json$"请填写 {agent} 的命令。"$json$::jsonb),
  ('zh-CN', 'settings.commandArgs', $json$"{agent} 的命令只能是可执行文件的名称或路径，不带参数。"$json$::jsonb),
  ('zh-CN', 'settings.timeout', $json$"{agent} 的静默超时必须在 {min} 到 {max} 秒之间。"$json$::jsonb),
  ('zh-CN', 'settings.noActiveModel', $json$"{agent} 已开启，但没有任何启用的模型。"$json$::jsonb),
  ('zh-CN', 'settings.modelNoId', $json$"{agent} 中有一个模型没有标识符。"$json$::jsonb),
  ('zh-CN', 'settings.modelBadId', $json$"标识符“{name}”包含任何代理都不接受的字符。"$json$::jsonb),
  ('zh-CN', 'settings.modelDuplicate', $json$"模型“{name}”在 {agent} 中出现了两次。"$json$::jsonb),
  ('zh-CN', 'settings.modelNoCapability', $json$"模型“{name}”至少需要一项能力。"$json$::jsonb),
  ('zh-CN', 'settings.contextWindow', $json$"“{name}”的上下文窗口必须在 {min} 到 {max} 个 token 之间。"$json$::jsonb),
  ('zh-CN', 'settings.noAgent', $json$"请至少开启一个代理。"$json$::jsonb),
  ('zh-CN', 'provider.failed', $json$"提供方“{provider}”失败（{exit}）：{reason}"$json$::jsonb),
  ('zh-CN', 'provider.failedSilent', $json$"提供方“{provider}”失败（{exit}），但没有说明原因；请在终端运行 `{command}` 查看错误。"$json$::jsonb),
  ('zh-CN', 'provider.exit.code', $json$"以代码 {code} 退出"$json$::jsonb),
  ('zh-CN', 'provider.exit.signal', $json$"被信号中断"$json$::jsonb),
  ('zh-CN', 'provider.exit.announced', $json$"报告了一个错误"$json$::jsonb),
  ('zh-CN', 'provider.silent', $json$"提供方“{provider}”在 {seconds} 秒内没有任何响应，已被停止；如果它的工作通常静默更久，请在设置中调高静默超时。"$json$::jsonb),
  ('zh-CN', 'provider.timeout', $json$"提供方“{provider}”超时；请检查服务和所配置的超时时间。"$json$::jsonb),
  ('zh-CN', 'provider.connect', $json$"无法连接到提供方“{provider}”；请检查服务是否在运行、网络以及基础 URL。"$json$::jsonb),
  ('zh-CN', 'provider.send', $json$"向提供方“{provider}”发送请求失败：{reason}"$json$::jsonb),
  ('hi', 'error.unexpected', $json$"कुछ गलत हो गया: {reason}"$json$::jsonb),
  ('hi', 'session.required', $json$"जारी रखने के लिए साइन इन करें।"$json$::jsonb),
  ('hi', 'session.expired', $json$"आपका सत्र समाप्त हो गया है। फिर से साइन इन करें।"$json$::jsonb),
  ('hi', 'session.invalid', $json$"यह सत्र मान्य नहीं है: {reason}"$json$::jsonb),
  ('hi', 'session.unknownKey', $json$"सत्र किसी अज्ञात कुंजी से हस्ताक्षरित है।"$json$::jsonb),
  ('hi', 'session.offlineFirst', $json$"पहली बार साइन इन करने पर सत्र जाँचने के लिए नेटवर्क चाहिए: {reason}"$json$::jsonb),
  ('hi', 'session.keyOffline', $json$"सत्र कुंजी नई है और उसे लाने के लिए नेटवर्क नहीं है: {reason}"$json$::jsonb),
  ('hi', 'prompt.noChat', $json$"भेजने से पहले एक चैट चुनें।"$json$::jsonb),
  ('hi', 'prompt.empty', $json$"भेजने के लिए कुछ नहीं है।"$json$::jsonb),
  ('hi', 'chat.notFound', $json$"चैट नहीं मिली।"$json$::jsonb),
  ('hi', 'project.notFound', $json$"प्रोजेक्ट नहीं मिला।"$json$::jsonb),
  ('hi', 'project.nameRequired', $json$"प्रोजेक्ट का नाम आवश्यक है।"$json$::jsonb),
  ('hi', 'project.folderMissing', $json$"प्रोजेक्ट फ़ोल्डर अब मौजूद नहीं है: {path}"$json$::jsonb),
  ('hi', 'turn.notFound', $json$"अनुरोध {turn} अब मौजूद नहीं है।"$json$::jsonb),
  ('hi', 'turn.otherChat', $json$"अनुरोध {turn} किसी दूसरी चैट का है।"$json$::jsonb),
  ('hi', 'turn.noAnswer', $json$"रन बिना उत्तर के समाप्त हो गया।"$json$::jsonb),
  ('hi', 'question.gone', $json$"यह प्रश्न अब मौजूद नहीं है।"$json$::jsonb),
  ('hi', 'question.closed', $json$"यह प्रश्न पहले ही बंद हो चुका है।"$json$::jsonb),
  ('hi', 'question.originGone', $json$"जिस अनुरोध से यह प्रश्न आया, वह अब मौजूद नहीं है।"$json$::jsonb),
  ('hi', 'answer.noul', $json$"हाँ या नहीं में उत्तर दें, या अपना उत्तर लिखें।"$json$::jsonb),
  ('hi', 'answer.pickOne', $json$"कम से कम एक विकल्प चुनें, या अपना उत्तर लिखें।"$json$::jsonb),
  ('hi', 'answer.single', $json$"यह प्रश्न केवल एक विकल्प स्वीकार करता है।"$json$::jsonb),
  ('hi', 'answer.unknown', $json$"“{option}” दिए गए विकल्पों में से नहीं है।"$json$::jsonb),
  ('hi', 'ask.answer', $json$"प्रश्न «{question}» का उत्तर: {answer}"$json$::jsonb),
  ('hi', 'gate.blocked', $json$"गेटहाउस ने इस अनुरोध को 100 में से {score} पर रोक दिया ({scope} के लिए न्यूनतम {demand} है)।"$json$::jsonb),
  ('hi', 'gate.missing', $json$"क्या कमी है:"$json$::jsonb),
  ('hi', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('hi', 'gate.asks.0', $json$"बताएँ कि क्या बदलना है और आप कैसे पुष्टि करेंगे कि वह बदल गया।"$json$::jsonb),
  ('hi', 'gate.asks.1', $json$"लक्ष्य, कहाँ बदलना है और आप कैसे पुष्टि करेंगे कि काम पूरा हुआ, यह बताएँ।"$json$::jsonb),
  ('hi', 'gate.asks.2', $json$"इतने बड़े अनुरोध के लिए लक्ष्य, शामिल फ़ाइलें या मॉड्यूल और पूरा होने की कसौटी चाहिए। हो सके तो इसे हिस्सों में बाँटें।"$json$::jsonb),
  ('hi', 'source.jev', $json$"Jev"$json$::jsonb),
  ('hi', 'source.local', $json$"स्थानीय अनुमान-नियम"$json$::jsonb),
  ('hi', 'source.fallback', $json$"स्थानीय अनुमान-नियम (Jev ने जवाब नहीं दिया)"$json$::jsonb),
  ('hi', 'settings.invalidValue', $json$"{field} के लिए अमान्य मान: “{value}”।"$json$::jsonb),
  ('hi', 'settings.field.claude.permissionMode', $json$"Claude Code का अनुमति मोड"$json$::jsonb),
  ('hi', 'settings.field.claude.effort', $json$"Claude Code का प्रयास स्तर"$json$::jsonb),
  ('hi', 'settings.field.claude.blockedTools', $json$"Claude Code के अवरुद्ध टूल"$json$::jsonb),
  ('hi', 'settings.field.codex.sandbox', $json$"Codex का सैंडबॉक्स"$json$::jsonb),
  ('hi', 'settings.field.codex.reasoning', $json$"Codex का तर्क स्तर"$json$::jsonb),
  ('hi', 'settings.field.copilot.toolAccess', $json$"Copilot की टूल पहुँच"$json$::jsonb),
  ('hi', 'settings.field.copilot.blockedTools', $json$"Copilot के अवरुद्ध टूल"$json$::jsonb),
  ('hi', 'settings.field.model.capability', $json$"क्षमता"$json$::jsonb),
  ('hi', 'settings.field.model.cost', $json$"लागत"$json$::jsonb),
  ('hi', 'settings.field.model.speed', $json$"गति"$json$::jsonb),
  ('hi', 'settings.claude.fallback', $json$"Claude Code का बैकअप मॉडल उसके पंजीकृत मॉडलों में से एक होना चाहिए।"$json$::jsonb),
  ('hi', 'settings.claude.budget', $json$"Claude Code की खर्च सीमा US$ 0.01 और US$ 1,000 के बीच होनी चाहिए।"$json$::jsonb),
  ('hi', 'settings.claude.instructions', $json$"Claude Code के अतिरिक्त निर्देश {max} अक्षरों से अधिक हैं।"$json$::jsonb),
  ('hi', 'settings.invalidOptions', $json$"अमान्य विकल्प: {reason}"$json$::jsonb),
  ('hi', 'settings.commandRequired', $json$"{agent} का कमांड दर्ज करें।"$json$::jsonb),
  ('hi', 'settings.commandArgs', $json$"{agent} का कमांड केवल executable का नाम या पथ है, बिना arguments के।"$json$::jsonb),
  ('hi', 'settings.timeout', $json$"{agent} का मौन समय {min} और {max} सेकंड के बीच होना चाहिए।"$json$::jsonb),
  ('hi', 'settings.noActiveModel', $json$"{agent} चालू है, लेकिन कोई सक्रिय मॉडल नहीं है।"$json$::jsonb),
  ('hi', 'settings.modelNoId', $json$"{agent} में एक मॉडल बिना पहचानकर्ता के है।"$json$::jsonb),
  ('hi', 'settings.modelBadId', $json$"पहचानकर्ता “{name}” में ऐसे अक्षर हैं जिन्हें कोई एजेंट स्वीकार नहीं करता।"$json$::jsonb),
  ('hi', 'settings.modelDuplicate', $json$"मॉडल “{name}” {agent} में दो बार है।"$json$::jsonb),
  ('hi', 'settings.modelNoCapability', $json$"मॉडल “{name}” को कम से कम एक क्षमता चाहिए।"$json$::jsonb),
  ('hi', 'settings.contextWindow', $json$"“{name}” की कॉन्टेक्स्ट विंडो {min} और {max} टोकन के बीच होनी चाहिए।"$json$::jsonb),
  ('hi', 'settings.noAgent', $json$"कम से कम एक एजेंट चालू करें।"$json$::jsonb),
  ('hi', 'provider.failed', $json$"प्रदाता “{provider}” विफल हुआ ({exit}): {reason}"$json$::jsonb),
  ('hi', 'provider.failedSilent', $json$"प्रदाता “{provider}” बिना कारण बताए विफल हुआ ({exit}); त्रुटि देखने के लिए टर्मिनल में `{command}` चलाएँ।"$json$::jsonb),
  ('hi', 'provider.exit.code', $json$"कोड {code} के साथ बाहर निकला"$json$::jsonb),
  ('hi', 'provider.exit.signal', $json$"एक सिग्नल से रोका गया"$json$::jsonb),
  ('hi', 'provider.exit.announced', $json$"एक त्रुटि बताई"$json$::jsonb),
  ('hi', 'provider.silent', $json$"प्रदाता “{provider}” {seconds} सेकंड तक बिना किसी संकेत के रहा और रोक दिया गया; अगर उसका काम आमतौर पर ज़्यादा देर चुप रहता है, तो सेटिंग्स में उसका मौन समय बढ़ाएँ।"$json$::jsonb),
  ('hi', 'provider.timeout', $json$"प्रदाता “{provider}” का समय समाप्त हो गया; सेवा और सेट की गई समय-सीमा जाँचें।"$json$::jsonb),
  ('hi', 'provider.connect', $json$"प्रदाता “{provider}” से कनेक्ट नहीं हो सका; जाँचें कि सेवा चल रही है, नेटवर्क और बेस URL।"$json$::jsonb),
  ('hi', 'provider.send', $json$"प्रदाता “{provider}” को अनुरोध भेजने में विफल: {reason}"$json$::jsonb),
  ('ar', 'error.unexpected', $json$"حدث خطأ ما: {reason}"$json$::jsonb),
  ('ar', 'session.required', $json$"سجّل الدخول للمتابعة."$json$::jsonb),
  ('ar', 'session.expired', $json$"انتهت صلاحية جلستك. سجّل الدخول مرة أخرى."$json$::jsonb),
  ('ar', 'session.invalid', $json$"هذه الجلسة غير صالحة: {reason}"$json$::jsonb),
  ('ar', 'session.unknownKey', $json$"تم توقيع الجلسة بمفتاح غير معروف."$json$::jsonb),
  ('ar', 'session.offlineFirst', $json$"يتطلب أول تسجيل دخول اتصالًا بالشبكة للتحقق من الجلسة: {reason}"$json$::jsonb),
  ('ar', 'session.keyOffline', $json$"مفتاح الجلسة جديد ولا توجد شبكة لجلبه: {reason}"$json$::jsonb),
  ('ar', 'prompt.noChat', $json$"اختر محادثة قبل الإرسال."$json$::jsonb),
  ('ar', 'prompt.empty', $json$"لا يوجد ما يُرسل."$json$::jsonb),
  ('ar', 'chat.notFound', $json$"لم يتم العثور على المحادثة."$json$::jsonb),
  ('ar', 'project.notFound', $json$"لم يتم العثور على المشروع."$json$::jsonb),
  ('ar', 'project.nameRequired', $json$"اسم المشروع مطلوب."$json$::jsonb),
  ('ar', 'project.folderMissing', $json$"لم يعد مجلد المشروع موجودًا: {path}"$json$::jsonb),
  ('ar', 'turn.notFound', $json$"لم يعد الطلب {turn} موجودًا."$json$::jsonb),
  ('ar', 'turn.otherChat', $json$"الطلب {turn} يخص محادثة أخرى."$json$::jsonb),
  ('ar', 'turn.noAnswer', $json$"انتهى التشغيل دون إجابة."$json$::jsonb),
  ('ar', 'question.gone', $json$"لم يعد هذا السؤال موجودًا."$json$::jsonb),
  ('ar', 'question.closed', $json$"تم إغلاق هذا السؤال بالفعل."$json$::jsonb),
  ('ar', 'question.originGone', $json$"لم يعد الطلب الذي نشأ عنه هذا السؤال موجودًا."$json$::jsonb),
  ('ar', 'answer.noul', $json$"أجب بنعم أو لا، أو اكتب إجابتك."$json$::jsonb),
  ('ar', 'answer.pickOne', $json$"اختر خيارًا واحدًا على الأقل، أو اكتب إجابتك."$json$::jsonb),
  ('ar', 'answer.single', $json$"هذا السؤال يقبل خيارًا واحدًا فقط."$json$::jsonb),
  ('ar', 'answer.unknown', $json$"«{option}» ليس من الخيارات المعروضة."$json$::jsonb),
  ('ar', 'ask.answer', $json$"إجابة السؤال «{question}»: {answer}"$json$::jsonb),
  ('ar', 'gate.blocked', $json$"أوقفت البوابة هذا الطلب بدرجة {score} من 100 (الحد الأدنى لـ {scope} هو {demand})."$json$::jsonb),
  ('ar', 'gate.missing', $json$"ما الذي ينقص:"$json$::jsonb),
  ('ar', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('ar', 'gate.asks.0', $json$"قل ما الذي يجب تغييره وكيف ستتأكد من أنه تغيّر."$json$::jsonb),
  ('ar', 'gate.asks.1', $json$"اذكر الهدف ومكان التغيير وكيف ستتأكد من اكتماله."$json$::jsonb),
  ('ar', 'gate.asks.2', $json$"يحتاج طلب بهذا الحجم إلى الهدف والملفات أو الوحدات المعنية ومعيار الاكتمال. قسّمه إلى أجزاء إن أمكن."$json$::jsonb),
  ('ar', 'source.jev', $json$"Jev"$json$::jsonb),
  ('ar', 'source.local', $json$"الاستدلالات المحلية"$json$::jsonb),
  ('ar', 'source.fallback', $json$"الاستدلالات المحلية (لم يستجب Jev)"$json$::jsonb),
  ('ar', 'settings.invalidValue', $json$"قيمة غير صالحة لـ {field}: «{value}»."$json$::jsonb),
  ('ar', 'settings.field.claude.permissionMode', $json$"وضع أذونات Claude Code"$json$::jsonb),
  ('ar', 'settings.field.claude.effort', $json$"مستوى جهد Claude Code"$json$::jsonb),
  ('ar', 'settings.field.claude.blockedTools', $json$"الأدوات المحظورة في Claude Code"$json$::jsonb),
  ('ar', 'settings.field.codex.sandbox', $json$"بيئة Codex المعزولة"$json$::jsonb),
  ('ar', 'settings.field.codex.reasoning', $json$"مستوى استدلال Codex"$json$::jsonb),
  ('ar', 'settings.field.copilot.toolAccess', $json$"وصول Copilot إلى الأدوات"$json$::jsonb),
  ('ar', 'settings.field.copilot.blockedTools', $json$"الأدوات المحظورة في Copilot"$json$::jsonb),
  ('ar', 'settings.field.model.capability', $json$"القدرة"$json$::jsonb),
  ('ar', 'settings.field.model.cost', $json$"التكلفة"$json$::jsonb),
  ('ar', 'settings.field.model.speed', $json$"السرعة"$json$::jsonb),
  ('ar', 'settings.claude.fallback', $json$"يجب أن يكون النموذج الاحتياطي لـ Claude Code أحد نماذجه المسجلة."$json$::jsonb),
  ('ar', 'settings.claude.budget', $json$"يجب أن يكون حد إنفاق Claude Code بين 0.01 و1000 دولار أمريكي."$json$::jsonb),
  ('ar', 'settings.claude.instructions', $json$"تتجاوز التعليمات الإضافية لـ Claude Code {max} حرف."$json$::jsonb),
  ('ar', 'settings.invalidOptions', $json$"خيارات غير صالحة: {reason}"$json$::jsonb),
  ('ar', 'settings.commandRequired', $json$"أدخل أمر {agent}."$json$::jsonb),
  ('ar', 'settings.commandArgs', $json$"أمر {agent} هو اسم الملف التنفيذي أو مساره فقط، دون وسائط."$json$::jsonb),
  ('ar', 'settings.timeout', $json$"يجب أن تكون مهلة الصمت لـ {agent} بين {min} و{max} ثانية."$json$::jsonb),
  ('ar', 'settings.noActiveModel', $json$"{agent} مفعّل لكن ليس لديه أي نموذج نشط."$json$::jsonb),
  ('ar', 'settings.modelNoId', $json$"يوجد نموذج بلا معرّف في {agent}."$json$::jsonb),
  ('ar', 'settings.modelBadId', $json$"يحتوي المعرّف «{name}» على أحرف لا يقبلها أي وكيل."$json$::jsonb),
  ('ar', 'settings.modelDuplicate', $json$"يظهر النموذج «{name}» مرتين في {agent}."$json$::jsonb),
  ('ar', 'settings.modelNoCapability', $json$"يحتاج النموذج «{name}» إلى قدرة واحدة على الأقل."$json$::jsonb),
  ('ar', 'settings.contextWindow', $json$"يجب أن تكون نافذة سياق «{name}» بين {min} و{max} رمزًا."$json$::jsonb),
  ('ar', 'settings.noAgent', $json$"فعّل وكيلًا واحدًا على الأقل."$json$::jsonb),
  ('ar', 'provider.failed', $json$"فشل المزوّد «{provider}» ({exit}): {reason}"$json$::jsonb),
  ('ar', 'provider.failedSilent', $json$"فشل المزوّد «{provider}» ({exit}) دون ذكر السبب؛ شغّل `{command}` في الطرفية لرؤية الخطأ."$json$::jsonb),
  ('ar', 'provider.exit.code', $json$"خرج بالرمز {code}"$json$::jsonb),
  ('ar', 'provider.exit.signal', $json$"أُوقف بإشارة"$json$::jsonb),
  ('ar', 'provider.exit.announced', $json$"أبلغ عن خطأ"$json$::jsonb),
  ('ar', 'provider.silent', $json$"ظل المزوّد «{provider}» {seconds} ثانية دون أي استجابة فأُوقف؛ إذا كان عمله يستغرق عادةً وقتًا أطول في صمت، فزد مهلة الصمت له في الإعدادات."$json$::jsonb),
  ('ar', 'provider.timeout', $json$"انتهت مهلة المزوّد «{provider}»؛ تحقّق من الخدمة ومن المهلة المضبوطة."$json$::jsonb),
  ('ar', 'provider.connect', $json$"تعذّر الاتصال بالمزوّد «{provider}»؛ تحقّق من أن الخدمة تعمل ومن الشبكة والعنوان الأساسي."$json$::jsonb),
  ('ar', 'provider.send', $json$"تعذّر إرسال الطلب إلى المزوّد «{provider}»: {reason}"$json$::jsonb),
  ('fr', 'error.unexpected', $json$"Une erreur s'est produite : {reason}"$json$::jsonb),
  ('fr', 'session.required', $json$"Connectez-vous pour continuer."$json$::jsonb),
  ('fr', 'session.expired', $json$"Votre session a expiré. Reconnectez-vous."$json$::jsonb),
  ('fr', 'session.invalid', $json$"Cette session n'est pas valide : {reason}"$json$::jsonb),
  ('fr', 'session.unknownKey', $json$"La session a été signée par une clé inconnue."$json$::jsonb),
  ('fr', 'session.offlineFirst', $json$"La première connexion nécessite le réseau pour vérifier la session : {reason}"$json$::jsonb),
  ('fr', 'session.keyOffline', $json$"La clé de session est nouvelle et aucun réseau ne permet de la récupérer : {reason}"$json$::jsonb),
  ('fr', 'prompt.noChat', $json$"Sélectionnez une conversation avant d'envoyer."$json$::jsonb),
  ('fr', 'prompt.empty', $json$"Il n'y a rien à envoyer."$json$::jsonb),
  ('fr', 'chat.notFound', $json$"Conversation introuvable."$json$::jsonb),
  ('fr', 'project.notFound', $json$"Projet introuvable."$json$::jsonb),
  ('fr', 'project.nameRequired', $json$"Le nom du projet est obligatoire."$json$::jsonb),
  ('fr', 'project.folderMissing', $json$"Le dossier du projet n'existe plus : {path}"$json$::jsonb),
  ('fr', 'turn.notFound', $json$"La demande {turn} n'existe plus."$json$::jsonb),
  ('fr', 'turn.otherChat', $json$"La demande {turn} appartient à une autre conversation."$json$::jsonb),
  ('fr', 'turn.noAnswer', $json$"L'exécution s'est terminée sans réponse."$json$::jsonb),
  ('fr', 'question.gone', $json$"Cette question n'existe plus."$json$::jsonb),
  ('fr', 'question.closed', $json$"Cette question est déjà close."$json$::jsonb),
  ('fr', 'question.originGone', $json$"La demande à l'origine de cette question n'existe plus."$json$::jsonb),
  ('fr', 'answer.noul', $json$"Répondez oui ou non, ou écrivez votre réponse."$json$::jsonb),
  ('fr', 'answer.pickOne', $json$"Choisissez au moins une option, ou écrivez votre réponse."$json$::jsonb),
  ('fr', 'answer.single', $json$"Cette question n'accepte qu'une seule option."$json$::jsonb),
  ('fr', 'answer.unknown', $json$"« {option} » ne fait pas partie des options proposées."$json$::jsonb),
  ('fr', 'ask.answer', $json$"Réponse à la question « {question} » : {answer}"$json$::jsonb),
  ('fr', 'gate.blocked', $json$"Le poste de garde a bloqué cette demande avec {score} sur 100 (le minimum pour {scope} est {demand})."$json$::jsonb),
  ('fr', 'gate.missing', $json$"Ce qui manque :"$json$::jsonb),
  ('fr', 'gate.missing.item', $json$"- {criterion} : {reading}"$json$::jsonb),
  ('fr', 'gate.asks.0', $json$"Dites ce qui doit changer et comment vous confirmerez le changement."$json$::jsonb),
  ('fr', 'gate.asks.1', $json$"Indiquez l'objectif, où intervenir et comment vous confirmerez que c'est terminé."$json$::jsonb),
  ('fr', 'gate.asks.2', $json$"Une demande de cette taille demande l'objectif, les fichiers ou modules concernés et le critère de fin. Si possible, découpez-la en parties."$json$::jsonb),
  ('fr', 'source.jev', $json$"Jev"$json$::jsonb),
  ('fr', 'source.local', $json$"heuristiques locales"$json$::jsonb),
  ('fr', 'source.fallback', $json$"heuristiques locales (le Jev n'a pas répondu)"$json$::jsonb),
  ('fr', 'settings.invalidValue', $json$"Valeur invalide pour {field} : « {value} »."$json$::jsonb),
  ('fr', 'settings.field.claude.permissionMode', $json$"le mode d'autorisation de Claude Code"$json$::jsonb),
  ('fr', 'settings.field.claude.effort', $json$"l'effort de Claude Code"$json$::jsonb),
  ('fr', 'settings.field.claude.blockedTools', $json$"les outils bloqués de Claude Code"$json$::jsonb),
  ('fr', 'settings.field.codex.sandbox', $json$"le bac à sable de Codex"$json$::jsonb),
  ('fr', 'settings.field.codex.reasoning', $json$"le raisonnement de Codex"$json$::jsonb),
  ('fr', 'settings.field.copilot.toolAccess', $json$"l'accès aux outils de Copilot"$json$::jsonb),
  ('fr', 'settings.field.copilot.blockedTools', $json$"les outils bloqués de Copilot"$json$::jsonb),
  ('fr', 'settings.field.model.capability', $json$"la capacité"$json$::jsonb),
  ('fr', 'settings.field.model.cost', $json$"le coût"$json$::jsonb),
  ('fr', 'settings.field.model.speed', $json$"la vitesse"$json$::jsonb),
  ('fr', 'settings.claude.fallback', $json$"Le modèle de secours de Claude Code doit faire partie de ses modèles enregistrés."$json$::jsonb),
  ('fr', 'settings.claude.budget', $json$"La limite de dépense de Claude Code doit être comprise entre 0,01 $ US et 1 000 $ US."$json$::jsonb),
  ('fr', 'settings.claude.instructions', $json$"Les instructions supplémentaires de Claude Code dépassent {max} caractères."$json$::jsonb),
  ('fr', 'settings.invalidOptions', $json$"Options invalides : {reason}"$json$::jsonb),
  ('fr', 'settings.commandRequired', $json$"Indiquez la commande de {agent}."$json$::jsonb),
  ('fr', 'settings.commandArgs', $json$"La commande de {agent} est uniquement le nom ou le chemin de l'exécutable, sans arguments."$json$::jsonb),
  ('fr', 'settings.timeout', $json$"Le délai de silence de {agent} doit être compris entre {min} et {max} secondes."$json$::jsonb),
  ('fr', 'settings.noActiveModel', $json$"{agent} est activé mais n'a aucun modèle actif."$json$::jsonb),
  ('fr', 'settings.modelNoId', $json$"Il y a un modèle sans identifiant dans {agent}."$json$::jsonb),
  ('fr', 'settings.modelBadId', $json$"L'identifiant « {name} » contient des caractères qu'aucun agent n'accepte."$json$::jsonb),
  ('fr', 'settings.modelDuplicate', $json$"Le modèle « {name} » apparaît deux fois dans {agent}."$json$::jsonb),
  ('fr', 'settings.modelNoCapability', $json$"Le modèle « {name} » a besoin d'au moins une capacité."$json$::jsonb),
  ('fr', 'settings.contextWindow', $json$"La fenêtre de contexte de « {name} » doit être comprise entre {min} et {max} jetons."$json$::jsonb),
  ('fr', 'settings.noAgent', $json$"Activez au moins un agent."$json$::jsonb),
  ('fr', 'provider.failed', $json$"Le fournisseur « {provider} » a échoué ({exit}) : {reason}"$json$::jsonb),
  ('fr', 'provider.failedSilent', $json$"Le fournisseur « {provider} » a échoué ({exit}) sans dire pourquoi ; lancez `{command}` dans un terminal pour voir l'erreur."$json$::jsonb),
  ('fr', 'provider.exit.code', $json$"s'est arrêté avec le code {code}"$json$::jsonb),
  ('fr', 'provider.exit.signal', $json$"a été interrompu par un signal"$json$::jsonb),
  ('fr', 'provider.exit.announced', $json$"a signalé une erreur"$json$::jsonb),
  ('fr', 'provider.silent', $json$"Le fournisseur « {provider} » est resté {seconds} s sans signe de vie et a été arrêté ; si son travail reste souvent silencieux plus longtemps, augmentez son délai de silence dans les réglages."$json$::jsonb),
  ('fr', 'provider.timeout', $json$"Le fournisseur « {provider} » a dépassé le délai ; vérifiez le service et le délai configuré."$json$::jsonb),
  ('fr', 'provider.connect', $json$"Impossible de se connecter au fournisseur « {provider} » ; vérifiez que le service tourne, le réseau et l'URL de base."$json$::jsonb),
  ('fr', 'provider.send', $json$"Échec de l'envoi de la demande au fournisseur « {provider} » : {reason}"$json$::jsonb),
  ('ru', 'error.unexpected', $json$"Что-то пошло не так: {reason}"$json$::jsonb),
  ('ru', 'session.required', $json$"Войдите, чтобы продолжить."$json$::jsonb),
  ('ru', 'session.expired', $json$"Сеанс истёк. Войдите снова."$json$::jsonb),
  ('ru', 'session.invalid', $json$"Сеанс недействителен: {reason}"$json$::jsonb),
  ('ru', 'session.unknownKey', $json$"Сеанс подписан неизвестным ключом."$json$::jsonb),
  ('ru', 'session.offlineFirst', $json$"Для первого входа нужна сеть, чтобы проверить сеанс: {reason}"$json$::jsonb),
  ('ru', 'session.keyOffline', $json$"Ключ сеанса новый, а сети для его загрузки нет: {reason}"$json$::jsonb),
  ('ru', 'prompt.noChat', $json$"Выберите чат перед отправкой."$json$::jsonb),
  ('ru', 'prompt.empty', $json$"Нечего отправлять."$json$::jsonb),
  ('ru', 'chat.notFound', $json$"Чат не найден."$json$::jsonb),
  ('ru', 'project.notFound', $json$"Проект не найден."$json$::jsonb),
  ('ru', 'project.nameRequired', $json$"Название проекта обязательно."$json$::jsonb),
  ('ru', 'project.folderMissing', $json$"Папка проекта больше не существует: {path}"$json$::jsonb),
  ('ru', 'turn.notFound', $json$"Запрос {turn} больше не существует."$json$::jsonb),
  ('ru', 'turn.otherChat', $json$"Запрос {turn} относится к другому чату."$json$::jsonb),
  ('ru', 'turn.noAnswer', $json$"Выполнение завершилось без ответа."$json$::jsonb),
  ('ru', 'question.gone', $json$"Этого вопроса больше нет."$json$::jsonb),
  ('ru', 'question.closed', $json$"Этот вопрос уже закрыт."$json$::jsonb),
  ('ru', 'question.originGone', $json$"Запрос, из которого возник этот вопрос, больше не существует."$json$::jsonb),
  ('ru', 'answer.noul', $json$"Ответьте «да» или «нет» или напишите свой ответ."$json$::jsonb),
  ('ru', 'answer.pickOne', $json$"Выберите хотя бы один вариант или напишите свой ответ."$json$::jsonb),
  ('ru', 'answer.single', $json$"В этом вопросе можно выбрать только один вариант."$json$::jsonb),
  ('ru', 'answer.unknown', $json$"«{option}» нет среди предложенных вариантов."$json$::jsonb),
  ('ru', 'ask.answer', $json$"Ответ на вопрос «{question}»: {answer}"$json$::jsonb),
  ('ru', 'gate.blocked', $json$"Проходная остановила этот запрос с оценкой {score} из 100 (минимум для «{scope}» — {demand})."$json$::jsonb),
  ('ru', 'gate.missing', $json$"Чего не хватает:"$json$::jsonb),
  ('ru', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('ru', 'gate.asks.0', $json$"Скажите, что нужно изменить и как вы убедитесь, что изменение сделано."$json$::jsonb),
  ('ru', 'gate.asks.1', $json$"Назовите цель, где вносить изменения и как вы убедитесь, что всё готово."$json$::jsonb),
  ('ru', 'gate.asks.2', $json$"Для запроса такого размера нужны цель, затронутые файлы или модули и критерий готовности. Если можно, разбейте его на части."$json$::jsonb),
  ('ru', 'source.jev', $json$"Jev"$json$::jsonb),
  ('ru', 'source.local', $json$"локальные эвристики"$json$::jsonb),
  ('ru', 'source.fallback', $json$"локальные эвристики (Jev не ответил)"$json$::jsonb),
  ('ru', 'settings.invalidValue', $json$"Недопустимое значение для «{field}»: «{value}»."$json$::jsonb),
  ('ru', 'settings.field.claude.permissionMode', $json$"режим разрешений Claude Code"$json$::jsonb),
  ('ru', 'settings.field.claude.effort', $json$"уровень усилий Claude Code"$json$::jsonb),
  ('ru', 'settings.field.claude.blockedTools', $json$"заблокированные инструменты Claude Code"$json$::jsonb),
  ('ru', 'settings.field.codex.sandbox', $json$"песочница Codex"$json$::jsonb),
  ('ru', 'settings.field.codex.reasoning', $json$"уровень рассуждений Codex"$json$::jsonb),
  ('ru', 'settings.field.copilot.toolAccess', $json$"доступ Copilot к инструментам"$json$::jsonb),
  ('ru', 'settings.field.copilot.blockedTools', $json$"заблокированные инструменты Copilot"$json$::jsonb),
  ('ru', 'settings.field.model.capability', $json$"возможность"$json$::jsonb),
  ('ru', 'settings.field.model.cost', $json$"стоимость"$json$::jsonb),
  ('ru', 'settings.field.model.speed', $json$"скорость"$json$::jsonb),
  ('ru', 'settings.claude.fallback', $json$"Резервная модель Claude Code должна быть одной из его зарегистрированных моделей."$json$::jsonb),
  ('ru', 'settings.claude.budget', $json$"Лимит расходов Claude Code должен быть от 0,01 до 1000 долларов США."$json$::jsonb),
  ('ru', 'settings.claude.instructions', $json$"Дополнительные инструкции Claude Code длиннее {max} символов."$json$::jsonb),
  ('ru', 'settings.invalidOptions', $json$"Недопустимые параметры: {reason}"$json$::jsonb),
  ('ru', 'settings.commandRequired', $json$"Укажите команду {agent}."$json$::jsonb),
  ('ru', 'settings.commandArgs', $json$"Команда {agent} — это только имя или путь к исполняемому файлу, без аргументов."$json$::jsonb),
  ('ru', 'settings.timeout', $json$"Тайм-аут тишины {agent} должен быть от {min} до {max} секунд."$json$::jsonb),
  ('ru', 'settings.noActiveModel', $json$"{agent} включён, но у него нет активных моделей."$json$::jsonb),
  ('ru', 'settings.modelNoId', $json$"В {agent} есть модель без идентификатора."$json$::jsonb),
  ('ru', 'settings.modelBadId', $json$"Идентификатор «{name}» содержит символы, которые не принимает ни один агент."$json$::jsonb),
  ('ru', 'settings.modelDuplicate', $json$"Модель «{name}» указана в {agent} дважды."$json$::jsonb),
  ('ru', 'settings.modelNoCapability', $json$"Модели «{name}» нужна хотя бы одна возможность."$json$::jsonb),
  ('ru', 'settings.contextWindow', $json$"Окно контекста «{name}» должно быть от {min} до {max} токенов."$json$::jsonb),
  ('ru', 'settings.noAgent', $json$"Включите хотя бы одного агента."$json$::jsonb),
  ('ru', 'provider.failed', $json$"Провайдер «{provider}» завершился с ошибкой ({exit}): {reason}"$json$::jsonb),
  ('ru', 'provider.failedSilent', $json$"Провайдер «{provider}» завершился с ошибкой ({exit}) без объяснения; запустите `{command}` в терминале, чтобы увидеть ошибку."$json$::jsonb),
  ('ru', 'provider.exit.code', $json$"завершился с кодом {code}"$json$::jsonb),
  ('ru', 'provider.exit.signal', $json$"был остановлен сигналом"$json$::jsonb),
  ('ru', 'provider.exit.announced', $json$"сообщил об ошибке"$json$::jsonb),
  ('ru', 'provider.silent', $json$"Провайдер «{provider}» молчал {seconds} с и был остановлен; если его работа обычно дольше идёт без вывода, увеличьте тайм-аут тишины в настройках."$json$::jsonb),
  ('ru', 'provider.timeout', $json$"Провайдер «{provider}» превысил время ожидания; проверьте сервис и заданный тайм-аут."$json$::jsonb),
  ('ru', 'provider.connect', $json$"Не удалось подключиться к провайдеру «{provider}»; проверьте, запущен ли сервис, сеть и базовый URL."$json$::jsonb),
  ('ru', 'provider.send', $json$"Не удалось отправить запрос провайдеру «{provider}»: {reason}"$json$::jsonb),
  ('ja', 'error.unexpected', $json$"問題が発生しました: {reason}"$json$::jsonb),
  ('ja', 'session.required', $json$"続行するにはサインインしてください。"$json$::jsonb),
  ('ja', 'session.expired', $json$"セッションの有効期限が切れました。もう一度サインインしてください。"$json$::jsonb),
  ('ja', 'session.invalid', $json$"このセッションは無効です: {reason}"$json$::jsonb),
  ('ja', 'session.unknownKey', $json$"セッションは不明な鍵で署名されています。"$json$::jsonb),
  ('ja', 'session.offlineFirst', $json$"初回のサインインではセッションの確認にネットワークが必要です: {reason}"$json$::jsonb),
  ('ja', 'session.keyOffline', $json$"セッションの鍵が新しく、取得するためのネットワークがありません: {reason}"$json$::jsonb),
  ('ja', 'prompt.noChat', $json$"送信する前にチャットを選択してください。"$json$::jsonb),
  ('ja', 'prompt.empty', $json$"送信する内容がありません。"$json$::jsonb),
  ('ja', 'chat.notFound', $json$"チャットが見つかりません。"$json$::jsonb),
  ('ja', 'project.notFound', $json$"プロジェクトが見つかりません。"$json$::jsonb),
  ('ja', 'project.nameRequired', $json$"プロジェクト名は必須です。"$json$::jsonb),
  ('ja', 'project.folderMissing', $json$"プロジェクトフォルダーはもう存在しません: {path}"$json$::jsonb),
  ('ja', 'turn.notFound', $json$"リクエスト {turn} はもう存在しません。"$json$::jsonb),
  ('ja', 'turn.otherChat', $json$"リクエスト {turn} は別のチャットのものです。"$json$::jsonb),
  ('ja', 'turn.noAnswer', $json$"実行は回答なしで終了しました。"$json$::jsonb),
  ('ja', 'question.gone', $json$"この質問はもう存在しません。"$json$::jsonb),
  ('ja', 'question.closed', $json$"この質問はすでに締め切られています。"$json$::jsonb),
  ('ja', 'question.originGone', $json$"この質問の元になったリクエストはもう存在しません。"$json$::jsonb),
  ('ja', 'answer.noul', $json$"はい か いいえ で答えるか、回答を書いてください。"$json$::jsonb),
  ('ja', 'answer.pickOne', $json$"少なくとも1つ選ぶか、回答を書いてください。"$json$::jsonb),
  ('ja', 'answer.single', $json$"この質問で選べるのは1つだけです。"$json$::jsonb),
  ('ja', 'answer.unknown', $json$"「{option}」は提示された選択肢にありません。"$json$::jsonb),
  ('ja', 'ask.answer', $json$"質問「{question}」への回答: {answer}"$json$::jsonb),
  ('ja', 'gate.blocked', $json$"ゲートはこのリクエストを100点中{score}点で止めました（{scope}の最低点は{demand}です）。"$json$::jsonb),
  ('ja', 'gate.missing', $json$"不足している点:"$json$::jsonb),
  ('ja', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('ja', 'gate.asks.0', $json$"何を変えるべきか、変わったことをどう確認するかを書いてください。"$json$::jsonb),
  ('ja', 'gate.asks.1', $json$"目的、変更する場所、完了をどう確認するかを書いてください。"$json$::jsonb),
  ('ja', 'gate.asks.2', $json$"この規模のリクエストには、目的、関係するファイルやモジュール、完了の基準が必要です。できれば分割してください。"$json$::jsonb),
  ('ja', 'source.jev', $json$"Jev"$json$::jsonb),
  ('ja', 'source.local', $json$"ローカルのヒューリスティック"$json$::jsonb),
  ('ja', 'source.fallback', $json$"ローカルのヒューリスティック（Jev が応答しませんでした）"$json$::jsonb),
  ('ja', 'settings.invalidValue', $json$"{field} の値が無効です: 「{value}」。"$json$::jsonb),
  ('ja', 'settings.field.claude.permissionMode', $json$"Claude Code の権限モード"$json$::jsonb),
  ('ja', 'settings.field.claude.effort', $json$"Claude Code の推論量"$json$::jsonb),
  ('ja', 'settings.field.claude.blockedTools', $json$"Claude Code でブロックするツール"$json$::jsonb),
  ('ja', 'settings.field.codex.sandbox', $json$"Codex のサンドボックス"$json$::jsonb),
  ('ja', 'settings.field.codex.reasoning', $json$"Codex の推論"$json$::jsonb),
  ('ja', 'settings.field.copilot.toolAccess', $json$"Copilot のツールアクセス"$json$::jsonb),
  ('ja', 'settings.field.copilot.blockedTools', $json$"Copilot でブロックするツール"$json$::jsonb),
  ('ja', 'settings.field.model.capability', $json$"機能"$json$::jsonb),
  ('ja', 'settings.field.model.cost', $json$"コスト"$json$::jsonb),
  ('ja', 'settings.field.model.speed', $json$"速度"$json$::jsonb),
  ('ja', 'settings.claude.fallback', $json$"Claude Code の予備モデルは登録済みモデルのいずれかである必要があります。"$json$::jsonb),
  ('ja', 'settings.claude.budget', $json$"Claude Code の支出上限は 0.01〜1,000 米ドルの範囲にしてください。"$json$::jsonb),
  ('ja', 'settings.claude.instructions', $json$"Claude Code の追加指示が {max} 文字を超えています。"$json$::jsonb),
  ('ja', 'settings.invalidOptions', $json$"無効なオプション: {reason}"$json$::jsonb),
  ('ja', 'settings.commandRequired', $json$"{agent} のコマンドを入力してください。"$json$::jsonb),
  ('ja', 'settings.commandArgs', $json$"{agent} のコマンドは実行ファイルの名前かパスだけで、引数は付けません。"$json$::jsonb),
  ('ja', 'settings.timeout', $json$"{agent} の無応答タイムアウトは {min}〜{max} 秒にしてください。"$json$::jsonb),
  ('ja', 'settings.noActiveModel', $json$"{agent} はオンですが、有効なモデルがありません。"$json$::jsonb),
  ('ja', 'settings.modelNoId', $json$"{agent} に識別子のないモデルがあります。"$json$::jsonb),
  ('ja', 'settings.modelBadId', $json$"識別子「{name}」にはどのエージェントも受け付けない文字が含まれています。"$json$::jsonb),
  ('ja', 'settings.modelDuplicate', $json$"モデル「{name}」が {agent} に2回登録されています。"$json$::jsonb),
  ('ja', 'settings.modelNoCapability', $json$"モデル「{name}」には少なくとも1つの機能が必要です。"$json$::jsonb),
  ('ja', 'settings.contextWindow', $json$"「{name}」のコンテキストウィンドウは {min}〜{max} トークンにしてください。"$json$::jsonb),
  ('ja', 'settings.noAgent', $json$"少なくとも1つのエージェントをオンにしてください。"$json$::jsonb),
  ('ja', 'provider.failed', $json$"プロバイダー「{provider}」が失敗しました（{exit}）: {reason}"$json$::jsonb),
  ('ja', 'provider.failedSilent', $json$"プロバイダー「{provider}」が理由を示さずに失敗しました（{exit}）。ターミナルで `{command}` を実行してエラーを確認してください。"$json$::jsonb),
  ('ja', 'provider.exit.code', $json$"コード {code} で終了"$json$::jsonb),
  ('ja', 'provider.exit.signal', $json$"シグナルで停止"$json$::jsonb),
  ('ja', 'provider.exit.announced', $json$"エラーを報告"$json$::jsonb),
  ('ja', 'provider.silent', $json$"プロバイダー「{provider}」が {seconds} 秒間応答せず、停止されました。通常もっと長く無言で作業する場合は、設定で無応答タイムアウトを延ばしてください。"$json$::jsonb),
  ('ja', 'provider.timeout', $json$"プロバイダー「{provider}」がタイムアウトしました。サービスと設定したタイムアウトを確認してください。"$json$::jsonb),
  ('ja', 'provider.connect', $json$"プロバイダー「{provider}」に接続できませんでした。サービスが動いているか、ネットワーク、ベース URL を確認してください。"$json$::jsonb),
  ('ja', 'provider.send', $json$"プロバイダー「{provider}」へのリクエスト送信に失敗しました: {reason}"$json$::jsonb),
  ('de', 'error.unexpected', $json$"Etwas ist schiefgelaufen: {reason}"$json$::jsonb),
  ('de', 'session.required', $json$"Melde dich an, um fortzufahren."$json$::jsonb),
  ('de', 'session.expired', $json$"Deine Sitzung ist abgelaufen. Melde dich erneut an."$json$::jsonb),
  ('de', 'session.invalid', $json$"Diese Sitzung ist ungültig: {reason}"$json$::jsonb),
  ('de', 'session.unknownKey', $json$"Die Sitzung wurde mit einem unbekannten Schlüssel signiert."$json$::jsonb),
  ('de', 'session.offlineFirst', $json$"Die erste Anmeldung braucht eine Netzwerkverbindung, um die Sitzung zu prüfen: {reason}"$json$::jsonb),
  ('de', 'session.keyOffline', $json$"Der Sitzungsschlüssel ist neu und es gibt kein Netzwerk, um ihn abzurufen: {reason}"$json$::jsonb),
  ('de', 'prompt.noChat', $json$"Wähle vor dem Senden einen Chat aus."$json$::jsonb),
  ('de', 'prompt.empty', $json$"Es gibt nichts zu senden."$json$::jsonb),
  ('de', 'chat.notFound', $json$"Chat nicht gefunden."$json$::jsonb),
  ('de', 'project.notFound', $json$"Projekt nicht gefunden."$json$::jsonb),
  ('de', 'project.nameRequired', $json$"Der Projektname ist erforderlich."$json$::jsonb),
  ('de', 'project.folderMissing', $json$"Der Projektordner existiert nicht mehr: {path}"$json$::jsonb),
  ('de', 'turn.notFound', $json$"Die Anfrage {turn} existiert nicht mehr."$json$::jsonb),
  ('de', 'turn.otherChat', $json$"Die Anfrage {turn} gehört zu einem anderen Chat."$json$::jsonb),
  ('de', 'turn.noAnswer', $json$"Der Lauf endete ohne Antwort."$json$::jsonb),
  ('de', 'question.gone', $json$"Diese Frage existiert nicht mehr."$json$::jsonb),
  ('de', 'question.closed', $json$"Diese Frage wurde bereits geschlossen."$json$::jsonb),
  ('de', 'question.originGone', $json$"Die Anfrage hinter dieser Frage existiert nicht mehr."$json$::jsonb),
  ('de', 'answer.noul', $json$"Antworte mit Ja oder Nein oder schreibe deine Antwort."$json$::jsonb),
  ('de', 'answer.pickOne', $json$"Wähle mindestens eine Option oder schreibe deine Antwort."$json$::jsonb),
  ('de', 'answer.single', $json$"Diese Frage erlaubt nur eine Option."$json$::jsonb),
  ('de', 'answer.unknown', $json$"„{option}“ ist keine der angebotenen Optionen."$json$::jsonb),
  ('de', 'ask.answer', $json$"Antwort auf die Frage „{question}“: {answer}"$json$::jsonb),
  ('de', 'gate.blocked', $json$"Das Pförtnerhaus hat diese Anfrage mit {score} von 100 gestoppt (das Minimum für {scope} ist {demand})."$json$::jsonb),
  ('de', 'gate.missing', $json$"Was fehlt:"$json$::jsonb),
  ('de', 'gate.missing.item', $json$"- {criterion}: {reading}"$json$::jsonb),
  ('de', 'gate.asks.0', $json$"Sag, was sich ändern soll und wie du prüfst, dass es sich geändert hat."$json$::jsonb),
  ('de', 'gate.asks.1', $json$"Nenne das Ziel, wo geändert werden soll und wie du prüfst, dass es fertig ist."$json$::jsonb),
  ('de', 'gate.asks.2', $json$"Eine Anfrage dieser Größe braucht das Ziel, die betroffenen Dateien oder Module und die Definition von fertig. Teile sie wenn möglich auf."$json$::jsonb),
  ('de', 'source.jev', $json$"Jev"$json$::jsonb),
  ('de', 'source.local', $json$"lokale Heuristiken"$json$::jsonb),
  ('de', 'source.fallback', $json$"lokale Heuristiken (der Jev hat nicht geantwortet)"$json$::jsonb),
  ('de', 'settings.invalidValue', $json$"Ungültiger Wert für {field}: „{value}“."$json$::jsonb),
  ('de', 'settings.field.claude.permissionMode', $json$"den Berechtigungsmodus von Claude Code"$json$::jsonb),
  ('de', 'settings.field.claude.effort', $json$"den Aufwand von Claude Code"$json$::jsonb),
  ('de', 'settings.field.claude.blockedTools', $json$"die blockierten Werkzeuge von Claude Code"$json$::jsonb),
  ('de', 'settings.field.codex.sandbox', $json$"die Sandbox von Codex"$json$::jsonb),
  ('de', 'settings.field.codex.reasoning', $json$"das Reasoning von Codex"$json$::jsonb),
  ('de', 'settings.field.copilot.toolAccess', $json$"den Werkzeugzugriff von Copilot"$json$::jsonb),
  ('de', 'settings.field.copilot.blockedTools', $json$"die blockierten Werkzeuge von Copilot"$json$::jsonb),
  ('de', 'settings.field.model.capability', $json$"die Fähigkeit"$json$::jsonb),
  ('de', 'settings.field.model.cost', $json$"die Kosten"$json$::jsonb),
  ('de', 'settings.field.model.speed', $json$"die Geschwindigkeit"$json$::jsonb),
  ('de', 'settings.claude.fallback', $json$"Das Ersatzmodell von Claude Code muss eines seiner registrierten Modelle sein."$json$::jsonb),
  ('de', 'settings.claude.budget', $json$"Das Ausgabenlimit von Claude Code muss zwischen 0,01 US$ und 1.000 US$ liegen."$json$::jsonb),
  ('de', 'settings.claude.instructions', $json$"Die zusätzlichen Anweisungen für Claude Code überschreiten {max} Zeichen."$json$::jsonb),
  ('de', 'settings.invalidOptions', $json$"Ungültige Optionen: {reason}"$json$::jsonb),
  ('de', 'settings.commandRequired', $json$"Gib den Befehl für {agent} an."$json$::jsonb),
  ('de', 'settings.commandArgs', $json$"Der Befehl für {agent} ist nur der Name oder Pfad der ausführbaren Datei, ohne Argumente."$json$::jsonb),
  ('de', 'settings.timeout', $json$"Die Stille-Zeitüberschreitung für {agent} muss zwischen {min} und {max} Sekunden liegen."$json$::jsonb),
  ('de', 'settings.noActiveModel', $json$"{agent} ist eingeschaltet, hat aber kein aktives Modell."$json$::jsonb),
  ('de', 'settings.modelNoId', $json$"In {agent} gibt es ein Modell ohne Kennung."$json$::jsonb),
  ('de', 'settings.modelBadId', $json$"Die Kennung „{name}“ enthält Zeichen, die kein Agent akzeptiert."$json$::jsonb),
  ('de', 'settings.modelDuplicate', $json$"Das Modell „{name}“ kommt in {agent} zweimal vor."$json$::jsonb),
  ('de', 'settings.modelNoCapability', $json$"Das Modell „{name}“ braucht mindestens eine Fähigkeit."$json$::jsonb),
  ('de', 'settings.contextWindow', $json$"Das Kontextfenster von „{name}“ muss zwischen {min} und {max} Tokens liegen."$json$::jsonb),
  ('de', 'settings.noAgent', $json$"Schalte mindestens einen Agenten ein."$json$::jsonb),
  ('de', 'provider.failed', $json$"Der Anbieter „{provider}“ ist fehlgeschlagen ({exit}): {reason}"$json$::jsonb),
  ('de', 'provider.failedSilent', $json$"Der Anbieter „{provider}“ ist ohne Begründung fehlgeschlagen ({exit}); führe `{command}` im Terminal aus, um den Fehler zu sehen."$json$::jsonb),
  ('de', 'provider.exit.code', $json$"mit Code {code} beendet"$json$::jsonb),
  ('de', 'provider.exit.signal', $json$"durch ein Signal beendet"$json$::jsonb),
  ('de', 'provider.exit.announced', $json$"hat einen Fehler gemeldet"$json$::jsonb),
  ('de', 'provider.silent', $json$"Der Anbieter „{provider}“ war {seconds} s ohne Lebenszeichen und wurde beendet; wenn seine Arbeit meist länger still läuft, erhöhe die Stille-Zeitüberschreitung in den Einstellungen."$json$::jsonb),
  ('de', 'provider.timeout', $json$"Beim Anbieter „{provider}“ ist die Zeit abgelaufen; prüfe den Dienst und die eingestellte Zeitüberschreitung."$json$::jsonb),
  ('de', 'provider.connect', $json$"Keine Verbindung zum Anbieter „{provider}“; prüfe, ob der Dienst läuft, das Netzwerk und die Basis-URL."$json$::jsonb),
  ('de', 'provider.send', $json$"Die Anfrage an den Anbieter „{provider}“ konnte nicht gesendet werden: {reason}"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
