-- v0.44.2: "O que muda" abre só a versão nova; mensagens do chat cabem no balão.
--
-- Só textos: a descrição da janela "Novidades" quando ela mostra a versão
-- que ainda vai ser instalada (whatsNew.description.upcoming) e os itens da
-- janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.description.upcoming', $json$"O JayV {version} está pronto para instalar. Veja o que ele traz."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.upcomingNotes.title', $json$"O que muda mostra só a versão nova"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.upcomingNotes.detail', $json$"O que muda, no aviso de atualização, agora abre as Novidades só com o que a versão nova traz, e com um botão para atualizar dali mesmo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatFits.title', $json$"Mensagens do chat cabem no balão"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatFits.detail', $json$"Links, caminhos e palavras compridas agora quebram dentro do balão em vez de serem cortados nas laterais, e tabelas e códigos largos rolam por dentro dele. A linha de tokens, custo e tempo de cada resposta do JayV fica à direita."$json$::jsonb),
  ('en', 'whatsNew.description.upcoming', $json$"JayV {version} is ready to install. Here is what it brings."$json$::jsonb),
  ('en', 'whatsNew.item.upcomingNotes.title', $json$"What changes shows only the new version"$json$::jsonb),
  ('en', 'whatsNew.item.upcomingNotes.detail', $json$"What changes, in the update notice, now opens What's new with only what the new version brings, and a button to update from there."$json$::jsonb),
  ('en', 'whatsNew.item.chatFits.title', $json$"Chat messages fit inside their bubble"$json$::jsonb),
  ('en', 'whatsNew.item.chatFits.detail', $json$"Long links, paths and words now wrap inside the bubble instead of being cut off at the sides, and wide tables and code scroll inside it. The tokens, cost and time line of each JayV answer sits on the right."$json$::jsonb),
  ('es', 'whatsNew.description.upcoming', $json$"JayV {version} está listo para instalar. Esto es lo que trae."$json$::jsonb),
  ('es', 'whatsNew.item.upcomingNotes.title', $json$"Qué cambia muestra solo la versión nueva"$json$::jsonb),
  ('es', 'whatsNew.item.upcomingNotes.detail', $json$"Qué cambia, en el aviso de actualización, ahora abre Novedades solo con lo que trae la versión nueva, y con un botón para actualizar desde ahí."$json$::jsonb),
  ('es', 'whatsNew.item.chatFits.title', $json$"Los mensajes del chat caben en su globo"$json$::jsonb),
  ('es', 'whatsNew.item.chatFits.detail', $json$"Los enlaces, rutas y palabras largas ahora se cortan dentro del globo en lugar de quedar ocultos a los lados, y las tablas y el código anchos se desplazan dentro de él. La línea de tokens, costo y tiempo de cada respuesta de JayV queda a la derecha."$json$::jsonb),
  ('zh-CN', 'whatsNew.description.upcoming', $json$"JayV {version} 已可安装。以下是它带来的内容。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.upcomingNotes.title', $json$"“有什么变化”只显示新版本"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.upcomingNotes.detail', $json$"更新提示中的“有什么变化”现在会打开“新功能”，只显示新版本带来的内容，并可直接在那里更新。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatFits.title', $json$"聊天消息不再超出气泡"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatFits.detail', $json$"长链接、路径和长单词现在会在气泡内换行，不再在两侧被截断；较宽的表格和代码在气泡内滚动。每条 JayV 回答的令牌、费用和耗时一行显示在右侧。"$json$::jsonb),
  ('hi', 'whatsNew.description.upcoming', $json$"JayV {version} इंस्टॉल करने के लिए तैयार है। देखें यह क्या लाता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.upcomingNotes.title', $json$"क्या बदलता है अब सिर्फ़ नया संस्करण दिखाता है"$json$::jsonb),
  ('hi', 'whatsNew.item.upcomingNotes.detail', $json$"अपडेट सूचना में क्या बदलता है अब नया क्या है खोलता है, जिसमें सिर्फ़ नए संस्करण की बातें हैं और वहीं से अपडेट करने का बटन है।"$json$::jsonb),
  ('hi', 'whatsNew.item.chatFits.title', $json$"चैट संदेश बबल के अंदर रहते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.chatFits.detail', $json$"लंबे लिंक, पथ और शब्द अब किनारों पर कटने के बजाय बबल के अंदर ही अगली पंक्ति में जाते हैं, और चौड़ी तालिकाएँ और कोड उसके अंदर स्क्रॉल होते हैं। JayV के हर जवाब की टोकन, लागत और समय वाली पंक्ति दाईं ओर रहती है।"$json$::jsonb),
  ('ar', 'whatsNew.description.upcoming', $json$"JayV {version} جاهز للتثبيت. إليك ما يحمله."$json$::jsonb),
  ('ar', 'whatsNew.item.upcomingNotes.title', $json$"ما الذي يتغير يعرض الإصدار الجديد فقط"$json$::jsonb),
  ('ar', 'whatsNew.item.upcomingNotes.detail', $json$"يفتح الآن زر ما الذي يتغير في إشعار التحديث نافذة الجديد بما يحمله الإصدار الجديد فقط، مع زر للتحديث من هناك مباشرة."$json$::jsonb),
  ('ar', 'whatsNew.item.chatFits.title', $json$"رسائل الدردشة تتسع داخل فقاعتها"$json$::jsonb),
  ('ar', 'whatsNew.item.chatFits.detail', $json$"تلتف الآن الروابط والمسارات والكلمات الطويلة داخل الفقاعة بدلًا من أن تُقص عند الجانبين، وتُمرَّر الجداول والشيفرة العريضة داخلها. ويظهر سطر الرموز والتكلفة والوقت لكل إجابة من JayV في الطرف المقابل لبدايتها."$json$::jsonb),
  ('fr', 'whatsNew.description.upcoming', $json$"JayV {version} est prêt à être installé. Voici ce qu'il apporte."$json$::jsonb),
  ('fr', 'whatsNew.item.upcomingNotes.title', $json$"Ce qui change montre seulement la nouvelle version"$json$::jsonb),
  ('fr', 'whatsNew.item.upcomingNotes.detail', $json$"Ce qui change, dans l'avis de mise à jour, ouvre désormais Nouveautés avec seulement ce qu'apporte la nouvelle version, et un bouton pour mettre à jour directement."$json$::jsonb),
  ('fr', 'whatsNew.item.chatFits.title', $json$"Les messages du chat tiennent dans leur bulle"$json$::jsonb),
  ('fr', 'whatsNew.item.chatFits.detail', $json$"Les liens, chemins et mots longs passent désormais à la ligne dans la bulle au lieu d'être coupés sur les côtés, et les tableaux et le code larges défilent à l'intérieur. La ligne de jetons, coût et durée de chaque réponse de JayV est à droite."$json$::jsonb),
  ('ru', 'whatsNew.description.upcoming', $json$"JayV {version} готов к установке. Вот что в нём нового."$json$::jsonb),
  ('ru', 'whatsNew.item.upcomingNotes.title', $json$"«Что изменится» показывает только новую версию"$json$::jsonb),
  ('ru', 'whatsNew.item.upcomingNotes.detail', $json$"Кнопка «Что изменится» в уведомлении об обновлении теперь открывает «Что нового» только с тем, что приносит новая версия, и с кнопкой, чтобы обновиться прямо оттуда."$json$::jsonb),
  ('ru', 'whatsNew.item.chatFits.title', $json$"Сообщения чата помещаются в пузырь"$json$::jsonb),
  ('ru', 'whatsNew.item.chatFits.detail', $json$"Длинные ссылки, пути и слова теперь переносятся внутри пузыря, а не обрезаются по краям, а широкие таблицы и код прокручиваются внутри него. Строка с токенами, стоимостью и временем каждого ответа JayV стоит справа."$json$::jsonb),
  ('ja', 'whatsNew.description.upcoming', $json$"JayV {version} をインストールできます。新しい内容は次のとおりです。"$json$::jsonb),
  ('ja', 'whatsNew.item.upcomingNotes.title', $json$"「変更点」は新しいバージョンだけを表示"$json$::jsonb),
  ('ja', 'whatsNew.item.upcomingNotes.detail', $json$"更新のお知らせの「変更点」は、新しいバージョンの内容だけを表示する「新機能」を開くようになり、そこから直接更新できるボタンも付きました。"$json$::jsonb),
  ('ja', 'whatsNew.item.chatFits.title', $json$"チャットのメッセージが吹き出しに収まる"$json$::jsonb),
  ('ja', 'whatsNew.item.chatFits.detail', $json$"長いリンク、パス、単語は左右で切れずに吹き出しの中で折り返され、幅の広い表やコードは吹き出しの中でスクロールします。JayV の各回答のトークン・費用・時間の行は右側に表示されます。"$json$::jsonb),
  ('de', 'whatsNew.description.upcoming', $json$"JayV {version} ist bereit zur Installation. Das bringt die Version."$json$::jsonb),
  ('de', 'whatsNew.item.upcomingNotes.title', $json$"Was sich ändert zeigt nur die neue Version"$json$::jsonb),
  ('de', 'whatsNew.item.upcomingNotes.detail', $json$"Was sich ändert im Update-Hinweis öffnet jetzt Neuigkeiten nur mit dem, was die neue Version bringt, samt Knopf, um direkt dort zu aktualisieren."$json$::jsonb),
  ('de', 'whatsNew.item.chatFits.title', $json$"Chatnachrichten passen in ihre Blase"$json$::jsonb),
  ('de', 'whatsNew.item.chatFits.detail', $json$"Lange Links, Pfade und Wörter brechen jetzt innerhalb der Blase um, statt an den Seiten abgeschnitten zu werden, und breite Tabellen und Code scrollen darin. Die Zeile mit Tokens, Kosten und Zeit jeder JayV-Antwort steht rechts."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
