-- v0.35.0: o JayV aprende com o uso.
--
-- A memória do projeto: notas curtas que o agente lê uma vez, quando a sessão
-- começa, e receitas (o passo a passo de quem usa para um tipo de pedido) que
-- vão só junto dos pedidos parecidos. As notas escritas pela pessoa têm
-- `source = 'manual'`; as que o app aprende das respostas às perguntas da
-- portaria têm `source = 'gate'` e `covers` com o critério que elas cobrem
-- (`says_where`, `says_when_done`), para a portaria não perguntar de novo.
--
-- Como as outras tabelas sincronizadas, cada linha é de um usuário
-- (`user_id`), nunca é apagada de verdade (`row_deleted_at`) e sobe e desce
-- pelo `sync_row`. A nota não é compartilhada com a organização.
--
-- Apagar o projeto apaga as notas dele: `cascade_row_deletion` ganha a aresta
-- projects → project_notes, e a nota que chega com o projeto já apagado nasce
-- apagada.
--
-- E os textos: a janela da memória, a busca nos chats, a sugestão de nível,
-- duas linhas novas no painel do Jev e os itens da janela "Novidades".

create table public.project_notes (
  id text primary key,
  project_id text not null references public.projects(id) on delete cascade,
  kind text not null check (kind in ('note', 'recipe')),
  title text not null default '',
  body text not null,
  trigger text not null default '',
  covers text not null default '',
  source text not null default 'manual' check (source in ('manual', 'gate', 'repeat')),
  created_at text not null,
  updated_at text not null,
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  row_updated_at timestamptz not null default now(),
  row_deleted_at timestamptz,
  synced_at timestamptz not null default clock_timestamp()
);

create index project_notes_user_synced on public.project_notes (user_id, synced_at);
create trigger sync_row before insert or update on public.project_notes
  for each row execute function public.sync_row();

alter table public.project_notes enable row level security;
create policy "dono lê" on public.project_notes for select to authenticated using (user_id = (select auth.uid()));
create policy "dono escreve" on public.project_notes for insert to authenticated with check (user_id = (select auth.uid()));
create policy "dono muda" on public.project_notes for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "segundo fator" on public.project_notes as restrictive to authenticated
  using ((select public.second_factor_ok())) with check ((select public.second_factor_ok()));
revoke delete, truncate on public.project_notes from anon, authenticated;
revoke all on public.project_notes from anon;

-- A mesma função de antes, com a aresta nova.
create or replace function public.cascade_row_deletion() returns trigger
language plpgsql
set search_path = ''
as $$
declare
  child record;
begin
  for child in
    select * from (values
      ('projects', 'chats', 'project_id'),
      ('projects', 'project_notes', 'project_id'),
      ('chats', 'turns', 'chat_id'),
      ('chats', 'messages', 'chat_id'),
      ('turns', 'entry_checks', 'turn_id'),
      ('turns', 'exit_checks', 'turn_id'),
      ('turns', 'turn_events', 'turn_id'),
      ('turns', 'questions', 'turn_id')
    ) as edges(parent, name, fk)
    where parent = tg_table_name
  loop
    -- `row_updated_at` nunca recua: o `sync_row` descartaria a marca como
    -- escrita atrasada.
    execute format(
      'update public.%I set row_deleted_at = $1, row_updated_at = greatest(row_updated_at, $1)
        where %I = $2 and row_deleted_at is null',
      child.name, child.fk)
    using new.row_deleted_at, new.id;
  end loop;
  return null;
end
$$;

-- Antes de `sync_row` pela ordem do nome, como nas outras tabelas filhas.
create trigger inherit_row_deletion before insert or update on public.project_notes
  for each row execute function public.inherit_row_deletion('projects', 'project_id');

insert into public.translations (locale, key, value) values
  ('pt-BR', 'memory.open', $json$"Memória do projeto"$json$::jsonb),
  ('pt-BR', 'memory.eyebrow', $json$"Memória do projeto"$json$::jsonb),
  ('pt-BR', 'memory.title', $json$"O que o JayV sabe deste projeto"$json$::jsonb),
  ('pt-BR', 'memory.description', $json$"As notas vão ao agente uma vez, quando uma sessão começa. As receitas vão só junto dos pedidos parecidos com elas. Tudo sincroniza com a sua conta."$json$::jsonb),
  ('pt-BR', 'memory.tab.notes', $json$"Notas"$json$::jsonb),
  ('pt-BR', 'memory.tab.recipes', $json$"Receitas"$json$::jsonb),
  ('pt-BR', 'memory.notes.hint', $json$"Fatos curtos que o agente teria de explorar para descobrir: como testar, onde as coisas ficam, o que não mexer. O que você responde quando a portaria cobra onde fica ou como conferir também é guardado aqui."$json$::jsonb),
  ('pt-BR', 'memory.notes.used', $json$"{used} / {limit} caracteres"$json$::jsonb),
  ('pt-BR', 'memory.notes.empty', $json$"Nenhuma nota ainda."$json$::jsonb),
  ('pt-BR', 'memory.note.text', $json$"Nota"$json$::jsonb),
  ('pt-BR', 'memory.note.placeholder', $json$"ex.: Os testes rodam com npm test; a API fica em server/api."$json$::jsonb),
  ('pt-BR', 'memory.note.add', $json$"Adicionar nota"$json$::jsonb),
  ('pt-BR', 'memory.note.learned', $json$"Aprendida da portaria"$json$::jsonb),
  ('pt-BR', 'memory.save', $json$"Salvar"$json$::jsonb),
  ('pt-BR', 'memory.edit', $json$"Editar"$json$::jsonb),
  ('pt-BR', 'memory.recipes.hint', $json$"Uma receita é o seu passo a passo para um pedido que se repete, com até {limit} caracteres. Ela vai junto só quando o pedido se parece com o gatilho dela."$json$::jsonb),
  ('pt-BR', 'memory.recipes.empty', $json$"Nenhuma receita ainda."$json$::jsonb),
  ('pt-BR', 'memory.repeated', $json$"Pedidos que se repetem"$json$::jsonb),
  ('pt-BR', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('pt-BR', 'memory.repeated.save', $json$"Virar receita"$json$::jsonb),
  ('pt-BR', 'memory.recipe.name', $json$"Nome"$json$::jsonb),
  ('pt-BR', 'memory.recipe.name.placeholder', $json$"ex.: Migração nova"$json$::jsonb),
  ('pt-BR', 'memory.recipe.trigger', $json$"Pedido gatilho"$json$::jsonb),
  ('pt-BR', 'memory.recipe.trigger.placeholder', $json$"Um pedido que esta receita atende (vazio, vale o nome)"$json$::jsonb),
  ('pt-BR', 'memory.recipe.steps', $json$"Passo a passo"$json$::jsonb),
  ('pt-BR', 'memory.recipe.steps.placeholder', $json$"ex.: 1. Crie o arquivo em migrations/ 2. Rode os testes de migração"$json$::jsonb),
  ('pt-BR', 'memory.recipe.add', $json$"Adicionar receita"$json$::jsonb),
  ('pt-BR', 'memory.recipe.when', $json$"Quando: {trigger}"$json$::jsonb),
  ('pt-BR', 'memory.empty', $json$"Escreva alguma coisa antes."$json$::jsonb),
  ('pt-BR', 'memory.secret', $json$"Isto parece um segredo (chave, token ou senha). As notas vão ao agente, então não podem guardar segredos."$json$::jsonb),
  ('pt-BR', 'memory.recipe.untitled', $json$"Dê um nome à receita."$json$::jsonb),
  ('pt-BR', 'memory.recipe.tooLong', $json$"Uma receita guarda até {limit} caracteres."$json$::jsonb),
  ('pt-BR', 'memory.full', $json$"As notas do projeto estão cheias ({limit} caracteres). Encurte ou apague uma nota antes."$json$::jsonb),
  ('pt-BR', 'memory.missing', $json$"Esta nota não existe mais."$json$::jsonb),
  ('pt-BR', 'search.label', $json$"Buscar nos chats deste projeto"$json$::jsonb),
  ('pt-BR', 'search.placeholder', $json$"Buscar o que foi dito nos chats deste projeto"$json$::jsonb),
  ('pt-BR', 'search.empty', $json$"Nada encontrado nos chats deste projeto."$json$::jsonb),
  ('pt-BR', 'expertise.suggestion', $json$"Nos últimos {days} dias, {passed} dos seus {checks} pedidos passaram pela portaria de primeira. O nível {level} combina mais com esse histórico."$json$::jsonb),
  ('pt-BR', 'expertise.suggestion.apply', $json$"Trocar para {level}"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.noteLearned', $json$"Notas aprendidas"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.answerRecalled', $json$"Respostas antigas reaproveitadas"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectNotes.title', $json$"Memória do projeto"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectNotes.detail', $json$"Na tela de chats de um projeto, o botão Memória do projeto guarda notas curtas (até 2.200 caracteres): como testar, onde as coisas ficam, o que não mexer. Elas vão ao agente uma vez, quando a sessão começa, e o poupam de explorar o projeto para descobrir de novo. Segredos são recusados, e tudo sincroniza com a sua conta."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.gateLearning.title', $json$"A portaria aprende com as suas respostas"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.gateLearning.detail', $json$"Quando a portaria cobra onde fica ou como conferir uma mudança e você responde no pedido seguinte, a frase que respondeu vira nota do projeto. Daí em diante a portaria não cobra isso de novo naquele projeto, e o agente já recebe a resposta."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.routingFeedback.title', $json$"O roteamento aprende com o que não deu certo"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.routingFeedback.detail', $json$"Uma resposta que veio inteira já não conta sempre como acerto. Se a mensagem seguinte diz que não funcionou, ou se a portaria de saída segura a resposta, o modelo que atendeu perde ponto. A nota de cada modelo também passa a valer por tipo de pedido, então a revisão e o teste podem ir a modelos diferentes."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.levelSuggestion.title', $json$"Sugestão de nível"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.levelSuggestion.detail', $json$"Em Configuração, Seu nível agora sugere subir ou descer um degrau quando o histórico da portaria dos últimos 30 dias pede (a partir de 20 pedidos): quase tudo passando de primeira, ou muito pedido segurado. A troca continua sendo sua, com um clique."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatSearch.title', $json$"Busca nas conversas"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatSearch.detail', $json$"A tela de chats de um projeto ganhou uma busca pelo que foi dito nas conversas, com o trecho achado em destaque. Ela roda no próprio computador, num índice local, sem ida à rede."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.answerRecall.title', $json$"Reaproveita respostas que o projeto já tem"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.answerRecall.detail', $json$"Quando um pedido é quase igual a outro já respondido noutro chat do mesmo projeto, a resposta de antes vai junto, curta, e o agente parte dela em vez de explorar e responder tudo de novo. As vezes em que isso acontece aparecem no painel do Jev."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.recipes.title', $json$"Receitas para pedidos que se repetem"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.recipes.detail', $json$"A Memória do projeto mostra os pedidos que você já fez três vezes ou mais e deixa transformá-los em receita: o seu passo a passo para aquele tipo de pedido. A receita vai junto só quando o pedido se parece com ela, então não pesa nos outros."$json$::jsonb),
  ('en', 'memory.open', $json$"Project memory"$json$::jsonb),
  ('en', 'memory.eyebrow', $json$"Project memory"$json$::jsonb),
  ('en', 'memory.title', $json$"What JayV knows about this project"$json$::jsonb),
  ('en', 'memory.description', $json$"Notes go to the agent once, when a session starts. Recipes go along only with requests that look like them. Everything syncs with your account."$json$::jsonb),
  ('en', 'memory.tab.notes', $json$"Notes"$json$::jsonb),
  ('en', 'memory.tab.recipes', $json$"Recipes"$json$::jsonb),
  ('en', 'memory.notes.hint', $json$"Short facts the agent would otherwise explore to find: how to test, where things live, what not to touch. What you answer when the gatehouse asks where something is or how to check it is saved here too."$json$::jsonb),
  ('en', 'memory.notes.used', $json$"{used} / {limit} characters"$json$::jsonb),
  ('en', 'memory.notes.empty', $json$"No notes yet."$json$::jsonb),
  ('en', 'memory.note.text', $json$"Note"$json$::jsonb),
  ('en', 'memory.note.placeholder', $json$"e.g. Run the tests with npm test; the API lives in server/api."$json$::jsonb),
  ('en', 'memory.note.add', $json$"Add note"$json$::jsonb),
  ('en', 'memory.note.learned', $json$"Learned from the gatehouse"$json$::jsonb),
  ('en', 'memory.save', $json$"Save"$json$::jsonb),
  ('en', 'memory.edit', $json$"Edit"$json$::jsonb),
  ('en', 'memory.recipes.hint', $json$"A recipe is your procedure for a request you repeat, up to {limit} characters. It goes along only when a request looks like its trigger."$json$::jsonb),
  ('en', 'memory.recipes.empty', $json$"No recipes yet."$json$::jsonb),
  ('en', 'memory.repeated', $json$"Requests you repeat"$json$::jsonb),
  ('en', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('en', 'memory.repeated.save', $json$"Make a recipe"$json$::jsonb),
  ('en', 'memory.recipe.name', $json$"Name"$json$::jsonb),
  ('en', 'memory.recipe.name.placeholder', $json$"e.g. New migration"$json$::jsonb),
  ('en', 'memory.recipe.trigger', $json$"Trigger request"$json$::jsonb),
  ('en', 'memory.recipe.trigger.placeholder', $json$"A request this recipe answers (the name is used if empty)"$json$::jsonb),
  ('en', 'memory.recipe.steps', $json$"Steps"$json$::jsonb),
  ('en', 'memory.recipe.steps.placeholder', $json$"e.g. 1. Create the file in migrations/ 2. Run the migration tests"$json$::jsonb),
  ('en', 'memory.recipe.add', $json$"Add recipe"$json$::jsonb),
  ('en', 'memory.recipe.when', $json$"When: {trigger}"$json$::jsonb),
  ('en', 'memory.empty', $json$"Write something first."$json$::jsonb),
  ('en', 'memory.secret', $json$"This looks like a secret (key, token or password). Notes go to the agent, so they cannot hold secrets."$json$::jsonb),
  ('en', 'memory.recipe.untitled', $json$"Give the recipe a name."$json$::jsonb),
  ('en', 'memory.recipe.tooLong', $json$"A recipe holds up to {limit} characters."$json$::jsonb),
  ('en', 'memory.full', $json$"The project notes are full ({limit} characters). Shorten or delete a note first."$json$::jsonb),
  ('en', 'memory.missing', $json$"This note no longer exists."$json$::jsonb),
  ('en', 'search.label', $json$"Search the chats of this project"$json$::jsonb),
  ('en', 'search.placeholder', $json$"Search what was said in this project's chats"$json$::jsonb),
  ('en', 'search.empty', $json$"Nothing found in this project's chats."$json$::jsonb),
  ('en', 'expertise.suggestion', $json$"In the last {days} days, {passed} of your {checks} requests got through the gatehouse at once. The {level} level fits this history better."$json$::jsonb),
  ('en', 'expertise.suggestion.apply', $json$"Switch to {level}"$json$::jsonb),
  ('en', 'usage.jev.work.noteLearned', $json$"Notes learned"$json$::jsonb),
  ('en', 'usage.jev.work.answerRecalled', $json$"Earlier answers reused"$json$::jsonb),
  ('en', 'whatsNew.item.projectNotes.title', $json$"Project memory"$json$::jsonb),
  ('en', 'whatsNew.item.projectNotes.detail', $json$"On a project's chats screen, the Project memory button keeps short notes (up to 2,200 characters): how to test, where things live, what not to touch. They go to the agent once, when the session starts, and spare it from exploring the project to find them again. Secrets are refused, and everything syncs with your account."$json$::jsonb),
  ('en', 'whatsNew.item.gateLearning.title', $json$"The gatehouse learns from your answers"$json$::jsonb),
  ('en', 'whatsNew.item.gateLearning.detail', $json$"When the gatehouse asks where something lives or how to check a change and you answer in your next request, the sentence that answered becomes a project note. From then on the gatehouse no longer asks that in the project, and the agent already gets the answer."$json$::jsonb),
  ('en', 'whatsNew.item.routingFeedback.title', $json$"Routing learns from what did not work"$json$::jsonb),
  ('en', 'whatsNew.item.routingFeedback.detail', $json$"An answer that arrived whole no longer always counts as a success. If your next message says it did not work, or the exit gate holds the answer, the model that answered loses a point. Each model's score is now also kept per kind of request, so reviews and tests can go to different models."$json$::jsonb),
  ('en', 'whatsNew.item.levelSuggestion.title', $json$"Level suggestion"$json$::jsonb),
  ('en', 'whatsNew.item.levelSuggestion.detail', $json$"In Settings, Your level now suggests moving one step up or down when the gatehouse history of the last 30 days calls for it (from 20 requests on): almost everything getting through at once, or many requests held. The switch is still yours, with one click."$json$::jsonb),
  ('en', 'whatsNew.item.chatSearch.title', $json$"Search your chats"$json$::jsonb),
  ('en', 'whatsNew.item.chatSearch.detail', $json$"A project's chats screen now has a search over what was said in its chats, with the matching passage highlighted. It runs on your computer, on a local index, without going to the network."$json$::jsonb),
  ('en', 'whatsNew.item.answerRecall.title', $json$"Reuses answers the project already has"$json$::jsonb),
  ('en', 'whatsNew.item.answerRecall.detail', $json$"When a request is nearly identical to one already answered in another chat of the same project, the earlier answer goes along, shortened, and the agent starts from it instead of exploring and answering everything again. Each time this happens shows up in the Jev panel."$json$::jsonb),
  ('en', 'whatsNew.item.recipes.title', $json$"Recipes for requests you repeat"$json$::jsonb),
  ('en', 'whatsNew.item.recipes.detail', $json$"Project memory shows the requests you have made three or more times and lets you turn them into a recipe: your procedure for that kind of request. The recipe goes along only when a request looks like it, so it adds nothing to the others."$json$::jsonb),
  ('es', 'memory.open', $json$"Memoria del proyecto"$json$::jsonb),
  ('es', 'memory.eyebrow', $json$"Memoria del proyecto"$json$::jsonb),
  ('es', 'memory.title', $json$"Lo que JayV sabe de este proyecto"$json$::jsonb),
  ('es', 'memory.description', $json$"Las notas van al agente una vez, cuando empieza una sesión. Las recetas van solo con las solicitudes que se les parecen. Todo se sincroniza con tu cuenta."$json$::jsonb),
  ('es', 'memory.tab.notes', $json$"Notas"$json$::jsonb),
  ('es', 'memory.tab.recipes', $json$"Recetas"$json$::jsonb),
  ('es', 'memory.notes.hint', $json$"Datos breves que el agente tendría que explorar para descubrir: cómo probar, dónde está cada cosa, qué no tocar. Lo que respondes cuando la portería pregunta dónde está algo o cómo comprobarlo también se guarda aquí."$json$::jsonb),
  ('es', 'memory.notes.used', $json$"{used} / {limit} caracteres"$json$::jsonb),
  ('es', 'memory.notes.empty', $json$"Todavía no hay notas."$json$::jsonb),
  ('es', 'memory.note.text', $json$"Nota"$json$::jsonb),
  ('es', 'memory.note.placeholder', $json$"p. ej.: Las pruebas se ejecutan con npm test; la API está en server/api."$json$::jsonb),
  ('es', 'memory.note.add', $json$"Añadir nota"$json$::jsonb),
  ('es', 'memory.note.learned', $json$"Aprendida de la portería"$json$::jsonb),
  ('es', 'memory.save', $json$"Guardar"$json$::jsonb),
  ('es', 'memory.edit', $json$"Editar"$json$::jsonb),
  ('es', 'memory.recipes.hint', $json$"Una receta es tu procedimiento para una solicitud que repites, de hasta {limit} caracteres. Solo va con la solicitud cuando se parece a su disparador."$json$::jsonb),
  ('es', 'memory.recipes.empty', $json$"Todavía no hay recetas."$json$::jsonb),
  ('es', 'memory.repeated', $json$"Solicitudes que repites"$json$::jsonb),
  ('es', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('es', 'memory.repeated.save', $json$"Convertir en receta"$json$::jsonb),
  ('es', 'memory.recipe.name', $json$"Nombre"$json$::jsonb),
  ('es', 'memory.recipe.name.placeholder', $json$"p. ej.: Migración nueva"$json$::jsonb),
  ('es', 'memory.recipe.trigger', $json$"Solicitud disparadora"$json$::jsonb),
  ('es', 'memory.recipe.trigger.placeholder', $json$"Una solicitud que esta receta atiende (si está vacío, vale el nombre)"$json$::jsonb),
  ('es', 'memory.recipe.steps', $json$"Pasos"$json$::jsonb),
  ('es', 'memory.recipe.steps.placeholder', $json$"p. ej.: 1. Crea el archivo en migrations/ 2. Ejecuta las pruebas de migración"$json$::jsonb),
  ('es', 'memory.recipe.add', $json$"Añadir receta"$json$::jsonb),
  ('es', 'memory.recipe.when', $json$"Cuando: {trigger}"$json$::jsonb),
  ('es', 'memory.empty', $json$"Escribe algo primero."$json$::jsonb),
  ('es', 'memory.secret', $json$"Esto parece un secreto (clave, token o contraseña). Las notas van al agente, así que no pueden guardar secretos."$json$::jsonb),
  ('es', 'memory.recipe.untitled', $json$"Ponle un nombre a la receta."$json$::jsonb),
  ('es', 'memory.recipe.tooLong', $json$"Una receta admite hasta {limit} caracteres."$json$::jsonb),
  ('es', 'memory.full', $json$"Las notas del proyecto están llenas ({limit} caracteres). Acorta o borra una nota primero."$json$::jsonb),
  ('es', 'memory.missing', $json$"Esta nota ya no existe."$json$::jsonb),
  ('es', 'search.label', $json$"Buscar en los chats de este proyecto"$json$::jsonb),
  ('es', 'search.placeholder', $json$"Busca lo que se dijo en los chats de este proyecto"$json$::jsonb),
  ('es', 'search.empty', $json$"No se encontró nada en los chats de este proyecto."$json$::jsonb),
  ('es', 'expertise.suggestion', $json$"En los últimos {days} días, {passed} de tus {checks} solicitudes pasaron la portería a la primera. El nivel {level} encaja mejor con ese historial."$json$::jsonb),
  ('es', 'expertise.suggestion.apply', $json$"Cambiar a {level}"$json$::jsonb),
  ('es', 'usage.jev.work.noteLearned', $json$"Notas aprendidas"$json$::jsonb),
  ('es', 'usage.jev.work.answerRecalled', $json$"Respuestas anteriores reutilizadas"$json$::jsonb),
  ('es', 'whatsNew.item.projectNotes.title', $json$"Memoria del proyecto"$json$::jsonb),
  ('es', 'whatsNew.item.projectNotes.detail', $json$"En la pantalla de chats de un proyecto, el botón Memoria del proyecto guarda notas breves (hasta 2.200 caracteres): cómo probar, dónde está cada cosa, qué no tocar. Van al agente una vez, cuando empieza la sesión, y le ahorran explorar el proyecto para descubrirlas otra vez. Los secretos se rechazan y todo se sincroniza con tu cuenta."$json$::jsonb),
  ('es', 'whatsNew.item.gateLearning.title', $json$"La portería aprende de tus respuestas"$json$::jsonb),
  ('es', 'whatsNew.item.gateLearning.detail', $json$"Cuando la portería pregunta dónde está algo o cómo comprobar un cambio y respondes en la siguiente solicitud, la frase que respondió se convierte en nota del proyecto. Desde entonces la portería deja de preguntarlo en ese proyecto, y el agente ya recibe la respuesta."$json$::jsonb),
  ('es', 'whatsNew.item.routingFeedback.title', $json$"El enrutamiento aprende de lo que no funcionó"$json$::jsonb),
  ('es', 'whatsNew.item.routingFeedback.detail', $json$"Una respuesta que llegó completa ya no cuenta siempre como acierto. Si tu siguiente mensaje dice que no funcionó, o si la portería de salida retiene la respuesta, el modelo que respondió pierde un punto. La nota de cada modelo ahora también se lleva por tipo de solicitud, así que la revisión y las pruebas pueden ir a modelos distintos."$json$::jsonb),
  ('es', 'whatsNew.item.levelSuggestion.title', $json$"Sugerencia de nivel"$json$::jsonb),
  ('es', 'whatsNew.item.levelSuggestion.detail', $json$"En Configuración, Tu nivel ahora sugiere subir o bajar un escalón cuando el historial de la portería de los últimos 30 días lo pide (a partir de 20 solicitudes): casi todo pasando a la primera, o muchas solicitudes retenidas. El cambio sigue siendo tuyo, con un clic."$json$::jsonb),
  ('es', 'whatsNew.item.chatSearch.title', $json$"Búsqueda en los chats"$json$::jsonb),
  ('es', 'whatsNew.item.chatSearch.detail', $json$"La pantalla de chats de un proyecto ahora tiene una búsqueda por lo que se dijo en las conversaciones, con el fragmento encontrado resaltado. Funciona en tu propio equipo, en un índice local, sin salir a la red."$json$::jsonb),
  ('es', 'whatsNew.item.answerRecall.title', $json$"Reutiliza respuestas que el proyecto ya tiene"$json$::jsonb),
  ('es', 'whatsNew.item.answerRecall.detail', $json$"Cuando una solicitud es casi igual a otra ya respondida en otro chat del mismo proyecto, la respuesta anterior va con ella, abreviada, y el agente parte de ella en lugar de explorar y responder todo de nuevo. Cada vez que ocurre aparece en el panel de Jev."$json$::jsonb),
  ('es', 'whatsNew.item.recipes.title', $json$"Recetas para solicitudes que se repiten"$json$::jsonb),
  ('es', 'whatsNew.item.recipes.detail', $json$"La Memoria del proyecto muestra las solicitudes que ya hiciste tres veces o más y te deja convertirlas en receta: tu procedimiento para ese tipo de solicitud. La receta solo va cuando la solicitud se le parece, así que no pesa en las demás."$json$::jsonb),
  ('zh-CN', 'memory.open', $json$"项目记忆"$json$::jsonb),
  ('zh-CN', 'memory.eyebrow', $json$"项目记忆"$json$::jsonb),
  ('zh-CN', 'memory.title', $json$"JayV 对这个项目的了解"$json$::jsonb),
  ('zh-CN', 'memory.description', $json$"笔记在会话开始时发给智能体一次。配方只随与之相似的请求一起发送。所有内容都会与你的账户同步。"$json$::jsonb),
  ('zh-CN', 'memory.tab.notes', $json$"笔记"$json$::jsonb),
  ('zh-CN', 'memory.tab.recipes', $json$"配方"$json$::jsonb),
  ('zh-CN', 'memory.notes.hint', $json$"智能体原本需要探索才能找到的简短事实：如何测试、东西放在哪里、什么不要动。当门卫询问某样东西在哪里或如何检查时，你的回答也会保存在这里。"$json$::jsonb),
  ('zh-CN', 'memory.notes.used', $json$"{used} / {limit} 个字符"$json$::jsonb),
  ('zh-CN', 'memory.notes.empty', $json$"还没有笔记。"$json$::jsonb),
  ('zh-CN', 'memory.note.text', $json$"笔记"$json$::jsonb),
  ('zh-CN', 'memory.note.placeholder', $json$"例如：用 npm test 运行测试；API 在 server/api。"$json$::jsonb),
  ('zh-CN', 'memory.note.add', $json$"添加笔记"$json$::jsonb),
  ('zh-CN', 'memory.note.learned', $json$"从门卫学到"$json$::jsonb),
  ('zh-CN', 'memory.save', $json$"保存"$json$::jsonb),
  ('zh-CN', 'memory.edit', $json$"编辑"$json$::jsonb),
  ('zh-CN', 'memory.recipes.hint', $json$"配方是你为重复请求写下的步骤，最多 {limit} 个字符。只有当请求与它的触发语相似时才会一起发送。"$json$::jsonb),
  ('zh-CN', 'memory.recipes.empty', $json$"还没有配方。"$json$::jsonb),
  ('zh-CN', 'memory.repeated', $json$"你重复的请求"$json$::jsonb),
  ('zh-CN', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('zh-CN', 'memory.repeated.save', $json$"做成配方"$json$::jsonb),
  ('zh-CN', 'memory.recipe.name', $json$"名称"$json$::jsonb),
  ('zh-CN', 'memory.recipe.name.placeholder', $json$"例如：新迁移"$json$::jsonb),
  ('zh-CN', 'memory.recipe.trigger', $json$"触发请求"$json$::jsonb),
  ('zh-CN', 'memory.recipe.trigger.placeholder', $json$"这个配方对应的请求（留空则使用名称）"$json$::jsonb),
  ('zh-CN', 'memory.recipe.steps', $json$"步骤"$json$::jsonb),
  ('zh-CN', 'memory.recipe.steps.placeholder', $json$"例如：1. 在 migrations/ 下创建文件 2. 运行迁移测试"$json$::jsonb),
  ('zh-CN', 'memory.recipe.add', $json$"添加配方"$json$::jsonb),
  ('zh-CN', 'memory.recipe.when', $json$"触发：{trigger}"$json$::jsonb),
  ('zh-CN', 'memory.empty', $json$"请先写点内容。"$json$::jsonb),
  ('zh-CN', 'memory.secret', $json$"这看起来像机密信息（密钥、令牌或密码）。笔记会发给智能体，因此不能保存机密。"$json$::jsonb),
  ('zh-CN', 'memory.recipe.untitled', $json$"请给配方起个名字。"$json$::jsonb),
  ('zh-CN', 'memory.recipe.tooLong', $json$"一个配方最多 {limit} 个字符。"$json$::jsonb),
  ('zh-CN', 'memory.full', $json$"项目笔记已满（{limit} 个字符）。请先缩短或删除一条笔记。"$json$::jsonb),
  ('zh-CN', 'memory.missing', $json$"这条笔记已不存在。"$json$::jsonb),
  ('zh-CN', 'search.label', $json$"搜索此项目的聊天"$json$::jsonb),
  ('zh-CN', 'search.placeholder', $json$"搜索此项目聊天中说过的内容"$json$::jsonb),
  ('zh-CN', 'search.empty', $json$"在此项目的聊天中没有找到内容。"$json$::jsonb),
  ('zh-CN', 'expertise.suggestion', $json$"在过去 {days} 天里，你的 {checks} 个请求中有 {passed} 个一次就通过了门卫。{level} 级别更符合这段记录。"$json$::jsonb),
  ('zh-CN', 'expertise.suggestion.apply', $json$"切换到{level}"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.noteLearned', $json$"学到的笔记"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.answerRecalled', $json$"复用的旧回答"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectNotes.title', $json$"项目记忆"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectNotes.detail', $json$"在项目的聊天页面，“项目记忆”按钮可以保存简短笔记（最多 2,200 个字符）：如何测试、东西在哪里、什么不要动。它们在会话开始时发给智能体一次，免得它再次探索项目去寻找。机密内容会被拒绝，所有内容都会与你的账户同步。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.gateLearning.title', $json$"门卫会从你的回答中学习"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.gateLearning.detail', $json$"当门卫询问某样东西在哪里或如何检查改动，而你在下一个请求中回答了，那句回答就会成为项目笔记。此后门卫在该项目中不再问这个问题，智能体也会直接收到答案。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.routingFeedback.title', $json$"路由会从失败中学习"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.routingFeedback.detail', $json$"完整返回的回答不再总是算作成功。如果你的下一条消息说没有成功，或者出口门卫扣下了回答，回答的模型就会被扣分。每个模型的评分现在也按请求类型记录，因此审查和测试可以交给不同的模型。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.levelSuggestion.title', $json$"级别建议"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.levelSuggestion.detail', $json$"在设置中，“你的级别”现在会在过去 30 天的门卫记录需要时（至少 20 个请求）建议升一级或降一级：几乎全部一次通过，或者很多请求被拦下。切换仍由你决定，只需一次点击。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatSearch.title', $json$"搜索聊天"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatSearch.detail', $json$"项目的聊天页面新增了对聊天内容的搜索，并高亮显示匹配的片段。搜索在你的电脑上通过本地索引完成，不需要联网。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.answerRecall.title', $json$"复用项目已有的回答"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.answerRecall.detail', $json$"当一个请求与同一项目另一个聊天中已回答过的请求几乎相同时，之前的回答会被缩短后一起发送，智能体从它出发，而不是重新探索和回答。每次发生都会显示在 Jev 面板中。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.recipes.title', $json$"为重复请求准备的配方"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.recipes.detail', $json$"项目记忆会列出你已经提出过三次或以上的请求，并可以把它们变成配方：你对这类请求的处理步骤。配方只在请求与之相似时才一起发送，不会增加其他请求的负担。"$json$::jsonb),
  ('hi', 'memory.open', $json$"प्रोजेक्ट मेमोरी"$json$::jsonb),
  ('hi', 'memory.eyebrow', $json$"प्रोजेक्ट मेमोरी"$json$::jsonb),
  ('hi', 'memory.title', $json$"JayV इस प्रोजेक्ट के बारे में क्या जानता है"$json$::jsonb),
  ('hi', 'memory.description', $json$"नोट्स सत्र शुरू होने पर एक बार एजेंट को जाते हैं। रेसिपी सिर्फ़ उनसे मिलते-जुलते अनुरोधों के साथ जाती हैं। सब कुछ आपके खाते के साथ सिंक होता है।"$json$::jsonb),
  ('hi', 'memory.tab.notes', $json$"नोट्स"$json$::jsonb),
  ('hi', 'memory.tab.recipes', $json$"रेसिपी"$json$::jsonb),
  ('hi', 'memory.notes.hint', $json$"छोटे तथ्य जिन्हें एजेंट को वरना खोजना पड़ता: कैसे टेस्ट करें, चीज़ें कहाँ हैं, किसे न छुएँ। जब द्वारपाल पूछता है कि कुछ कहाँ है या कैसे जाँचें, तो आपका जवाब भी यहीं सहेजा जाता है।"$json$::jsonb),
  ('hi', 'memory.notes.used', $json$"{used} / {limit} वर्ण"$json$::jsonb),
  ('hi', 'memory.notes.empty', $json$"अभी कोई नोट नहीं।"$json$::jsonb),
  ('hi', 'memory.note.text', $json$"नोट"$json$::jsonb),
  ('hi', 'memory.note.placeholder', $json$"उदा.: टेस्ट npm test से चलते हैं; API server/api में है।"$json$::jsonb),
  ('hi', 'memory.note.add', $json$"नोट जोड़ें"$json$::jsonb),
  ('hi', 'memory.note.learned', $json$"द्वारपाल से सीखा"$json$::jsonb),
  ('hi', 'memory.save', $json$"सहेजें"$json$::jsonb),
  ('hi', 'memory.edit', $json$"संपादित करें"$json$::jsonb),
  ('hi', 'memory.recipes.hint', $json$"रेसिपी किसी दोहराए जाने वाले अनुरोध के लिए आपकी प्रक्रिया है, अधिकतम {limit} वर्ण। यह सिर्फ़ तब साथ जाती है जब अनुरोध उसके ट्रिगर जैसा हो।"$json$::jsonb),
  ('hi', 'memory.recipes.empty', $json$"अभी कोई रेसिपी नहीं।"$json$::jsonb),
  ('hi', 'memory.repeated', $json$"आपके दोहराए जाने वाले अनुरोध"$json$::jsonb),
  ('hi', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('hi', 'memory.repeated.save', $json$"रेसिपी बनाएँ"$json$::jsonb),
  ('hi', 'memory.recipe.name', $json$"नाम"$json$::jsonb),
  ('hi', 'memory.recipe.name.placeholder', $json$"उदा.: नया माइग्रेशन"$json$::jsonb),
  ('hi', 'memory.recipe.trigger', $json$"ट्रिगर अनुरोध"$json$::jsonb),
  ('hi', 'memory.recipe.trigger.placeholder', $json$"वह अनुरोध जिसका यह रेसिपी जवाब देती है (खाली हो तो नाम लिया जाता है)"$json$::jsonb),
  ('hi', 'memory.recipe.steps', $json$"चरण"$json$::jsonb),
  ('hi', 'memory.recipe.steps.placeholder', $json$"उदा.: 1. migrations/ में फ़ाइल बनाएँ 2. माइग्रेशन टेस्ट चलाएँ"$json$::jsonb),
  ('hi', 'memory.recipe.add', $json$"रेसिपी जोड़ें"$json$::jsonb),
  ('hi', 'memory.recipe.when', $json$"कब: {trigger}"$json$::jsonb),
  ('hi', 'memory.empty', $json$"पहले कुछ लिखें।"$json$::jsonb),
  ('hi', 'memory.secret', $json$"यह कोई गोपनीय जानकारी (की, टोकन या पासवर्ड) लगती है। नोट्स एजेंट को जाते हैं, इसलिए उनमें गोपनीय जानकारी नहीं रखी जा सकती।"$json$::jsonb),
  ('hi', 'memory.recipe.untitled', $json$"रेसिपी को नाम दें।"$json$::jsonb),
  ('hi', 'memory.recipe.tooLong', $json$"एक रेसिपी में अधिकतम {limit} वर्ण होते हैं।"$json$::jsonb),
  ('hi', 'memory.full', $json$"प्रोजेक्ट नोट्स भर गए हैं ({limit} वर्ण)। पहले कोई नोट छोटा करें या हटाएँ।"$json$::jsonb),
  ('hi', 'memory.missing', $json$"यह नोट अब मौजूद नहीं है।"$json$::jsonb),
  ('hi', 'search.label', $json$"इस प्रोजेक्ट की चैट में खोजें"$json$::jsonb),
  ('hi', 'search.placeholder', $json$"इस प्रोजेक्ट की चैट में कही गई बातें खोजें"$json$::jsonb),
  ('hi', 'search.empty', $json$"इस प्रोजेक्ट की चैट में कुछ नहीं मिला।"$json$::jsonb),
  ('hi', 'expertise.suggestion', $json$"पिछले {days} दिनों में आपके {checks} अनुरोधों में से {passed} पहली बार में द्वारपाल से निकल गए। {level} स्तर इस इतिहास से बेहतर मेल खाता है।"$json$::jsonb),
  ('hi', 'expertise.suggestion.apply', $json$"{level} पर जाएँ"$json$::jsonb),
  ('hi', 'usage.jev.work.noteLearned', $json$"सीखे गए नोट्स"$json$::jsonb),
  ('hi', 'usage.jev.work.answerRecalled', $json$"दोबारा इस्तेमाल हुए पुराने उत्तर"$json$::jsonb),
  ('hi', 'whatsNew.item.projectNotes.title', $json$"प्रोजेक्ट मेमोरी"$json$::jsonb),
  ('hi', 'whatsNew.item.projectNotes.detail', $json$"किसी प्रोजेक्ट की चैट स्क्रीन पर, प्रोजेक्ट मेमोरी बटन छोटे नोट्स रखता है (अधिकतम 2,200 वर्ण): कैसे टेस्ट करें, चीज़ें कहाँ हैं, किसे न छुएँ। ये सत्र शुरू होने पर एक बार एजेंट को जाते हैं और उसे इन्हें फिर से खोजने के लिए प्रोजेक्ट छानने से बचाते हैं। गोपनीय जानकारी अस्वीकार होती है, और सब कुछ आपके खाते से सिंक होता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.gateLearning.title', $json$"द्वारपाल आपके जवाबों से सीखता है"$json$::jsonb),
  ('hi', 'whatsNew.item.gateLearning.detail', $json$"जब द्वारपाल पूछता है कि कुछ कहाँ है या बदलाव कैसे जाँचें, और आप अगले अनुरोध में जवाब देते हैं, तो जवाब वाला वाक्य प्रोजेक्ट नोट बन जाता है। उसके बाद द्वारपाल उस प्रोजेक्ट में यह दोबारा नहीं पूछता, और एजेंट को जवाब पहले से मिल जाता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.routingFeedback.title', $json$"रूटिंग नाकाम रहे काम से सीखती है"$json$::jsonb),
  ('hi', 'whatsNew.item.routingFeedback.detail', $json$"पूरा आया उत्तर अब हमेशा सफलता नहीं गिना जाता। अगर आपका अगला संदेश कहता है कि यह काम नहीं किया, या निकास द्वार उत्तर रोक लेता है, तो जवाब देने वाला मॉडल अंक खोता है। हर मॉडल का स्कोर अब अनुरोध के प्रकार के हिसाब से भी रखा जाता है, इसलिए समीक्षा और टेस्ट अलग-अलग मॉडलों को जा सकते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.levelSuggestion.title', $json$"स्तर का सुझाव"$json$::jsonb),
  ('hi', 'whatsNew.item.levelSuggestion.detail', $json$"सेटिंग्स में, आपका स्तर अब पिछले 30 दिनों का द्वारपाल इतिहास कहे तो (20 अनुरोधों से) एक कदम ऊपर या नीचे जाने का सुझाव देता है: लगभग सब कुछ पहली बार में निकल रहा हो, या बहुत से अनुरोध रोके जा रहे हों। बदलाव अब भी आपका है, एक क्लिक में।"$json$::jsonb),
  ('hi', 'whatsNew.item.chatSearch.title', $json$"चैट में खोज"$json$::jsonb),
  ('hi', 'whatsNew.item.chatSearch.detail', $json$"प्रोजेक्ट की चैट स्क्रीन में अब बातचीत में कही गई बातों की खोज है, जिसमें मिला हुआ हिस्सा हाइलाइट होता है। यह आपके कंप्यूटर पर, एक स्थानीय इंडेक्स पर, बिना नेटवर्क के चलती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.answerRecall.title', $json$"प्रोजेक्ट के मौजूदा उत्तरों का दोबारा इस्तेमाल"$json$::jsonb),
  ('hi', 'whatsNew.item.answerRecall.detail', $json$"जब कोई अनुरोध उसी प्रोजेक्ट की किसी दूसरी चैट में पहले से जवाब दिए गए अनुरोध जैसा ही होता है, तो पिछला उत्तर छोटा करके साथ जाता है, और एजेंट सब कुछ दोबारा खोजने और जवाब देने के बजाय उससे शुरू करता है। हर बार ऐसा होने पर यह Jev पैनल में दिखता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.recipes.title', $json$"दोहराए जाने वाले अनुरोधों के लिए रेसिपी"$json$::jsonb),
  ('hi', 'whatsNew.item.recipes.detail', $json$"प्रोजेक्ट मेमोरी उन अनुरोधों को दिखाती है जो आप तीन या अधिक बार कर चुके हैं, और उन्हें रेसिपी बनाने देती है: उस तरह के अनुरोध के लिए आपकी प्रक्रिया। रेसिपी सिर्फ़ तब साथ जाती है जब अनुरोध उससे मिलता हो, इसलिए बाकी अनुरोधों पर बोझ नहीं डालती।"$json$::jsonb),
  ('ar', 'memory.open', $json$"ذاكرة المشروع"$json$::jsonb),
  ('ar', 'memory.eyebrow', $json$"ذاكرة المشروع"$json$::jsonb),
  ('ar', 'memory.title', $json$"ما يعرفه JayV عن هذا المشروع"$json$::jsonb),
  ('ar', 'memory.description', $json$"تُرسل الملاحظات إلى الوكيل مرة واحدة عند بدء الجلسة. أما الوصفات فتُرسل فقط مع الطلبات المشابهة لها. كل شيء يُزامَن مع حسابك."$json$::jsonb),
  ('ar', 'memory.tab.notes', $json$"الملاحظات"$json$::jsonb),
  ('ar', 'memory.tab.recipes', $json$"الوصفات"$json$::jsonb),
  ('ar', 'memory.notes.hint', $json$"حقائق قصيرة كان على الوكيل أن يستكشف ليعرفها: كيف تختبر، وأين توجد الأشياء، وما الذي لا يجب لمسه. وما تجيب به عندما تسأل البوابة عن مكان شيء أو كيفية التحقق منه يُحفظ هنا أيضًا."$json$::jsonb),
  ('ar', 'memory.notes.used', $json$"{used} / {limit} حرفًا"$json$::jsonb),
  ('ar', 'memory.notes.empty', $json$"لا توجد ملاحظات بعد."$json$::jsonb),
  ('ar', 'memory.note.text', $json$"ملاحظة"$json$::jsonb),
  ('ar', 'memory.note.placeholder', $json$"مثال: تُشغَّل الاختبارات بـ npm test؛ والـ API في server/api."$json$::jsonb),
  ('ar', 'memory.note.add', $json$"إضافة ملاحظة"$json$::jsonb),
  ('ar', 'memory.note.learned', $json$"مُتعلَّمة من البوابة"$json$::jsonb),
  ('ar', 'memory.save', $json$"حفظ"$json$::jsonb),
  ('ar', 'memory.edit', $json$"تعديل"$json$::jsonb),
  ('ar', 'memory.recipes.hint', $json$"الوصفة هي خطواتك لطلب تكرره، حتى {limit} حرفًا. لا تُرسل إلا عندما يشبه الطلبُ مُشغِّلها."$json$::jsonb),
  ('ar', 'memory.recipes.empty', $json$"لا توجد وصفات بعد."$json$::jsonb),
  ('ar', 'memory.repeated', $json$"طلبات تكررها"$json$::jsonb),
  ('ar', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('ar', 'memory.repeated.save', $json$"حوّلها إلى وصفة"$json$::jsonb),
  ('ar', 'memory.recipe.name', $json$"الاسم"$json$::jsonb),
  ('ar', 'memory.recipe.name.placeholder', $json$"مثال: ترحيل جديد"$json$::jsonb),
  ('ar', 'memory.recipe.trigger', $json$"الطلب المُشغِّل"$json$::jsonb),
  ('ar', 'memory.recipe.trigger.placeholder', $json$"طلب تجيب عنه هذه الوصفة (إن تُرك فارغًا يُستخدم الاسم)"$json$::jsonb),
  ('ar', 'memory.recipe.steps', $json$"الخطوات"$json$::jsonb),
  ('ar', 'memory.recipe.steps.placeholder', $json$"مثال: 1. أنشئ الملف في migrations/ 2. شغّل اختبارات الترحيل"$json$::jsonb),
  ('ar', 'memory.recipe.add', $json$"إضافة وصفة"$json$::jsonb),
  ('ar', 'memory.recipe.when', $json$"عندما: {trigger}"$json$::jsonb),
  ('ar', 'memory.empty', $json$"اكتب شيئًا أولًا."$json$::jsonb),
  ('ar', 'memory.secret', $json$"يبدو هذا سرًا (مفتاحًا أو رمزًا أو كلمة مرور). تُرسل الملاحظات إلى الوكيل، لذا لا يمكنها حفظ الأسرار."$json$::jsonb),
  ('ar', 'memory.recipe.untitled', $json$"أعطِ الوصفة اسمًا."$json$::jsonb),
  ('ar', 'memory.recipe.tooLong', $json$"تتسع الوصفة لـ {limit} حرفًا كحد أقصى."$json$::jsonb),
  ('ar', 'memory.full', $json$"ملاحظات المشروع ممتلئة ({limit} حرفًا). اختصر ملاحظة أو احذفها أولًا."$json$::jsonb),
  ('ar', 'memory.missing', $json$"هذه الملاحظة لم تعد موجودة."$json$::jsonb),
  ('ar', 'search.label', $json$"البحث في محادثات هذا المشروع"$json$::jsonb),
  ('ar', 'search.placeholder', $json$"ابحث عمّا قيل في محادثات هذا المشروع"$json$::jsonb),
  ('ar', 'search.empty', $json$"لم يُعثر على شيء في محادثات هذا المشروع."$json$::jsonb),
  ('ar', 'expertise.suggestion', $json$"في آخر {days} يومًا، اجتاز {passed} من طلباتك البالغة {checks} البوابة من المرة الأولى. المستوى {level} أنسب لهذا السجل."$json$::jsonb),
  ('ar', 'expertise.suggestion.apply', $json$"التبديل إلى {level}"$json$::jsonb),
  ('ar', 'usage.jev.work.noteLearned', $json$"ملاحظات مُتعلَّمة"$json$::jsonb),
  ('ar', 'usage.jev.work.answerRecalled', $json$"إجابات سابقة أُعيد استخدامها"$json$::jsonb),
  ('ar', 'whatsNew.item.projectNotes.title', $json$"ذاكرة المشروع"$json$::jsonb),
  ('ar', 'whatsNew.item.projectNotes.detail', $json$"في شاشة محادثات المشروع، يحفظ زر ذاكرة المشروع ملاحظات قصيرة (حتى 2,200 حرف): كيف تختبر، وأين توجد الأشياء، وما الذي لا يجب لمسه. تُرسل إلى الوكيل مرة واحدة عند بدء الجلسة، فتغنيه عن استكشاف المشروع ليجدها من جديد. تُرفض الأسرار، وكل شيء يُزامَن مع حسابك."$json$::jsonb),
  ('ar', 'whatsNew.item.gateLearning.title', $json$"البوابة تتعلّم من إجاباتك"$json$::jsonb),
  ('ar', 'whatsNew.item.gateLearning.detail', $json$"عندما تسأل البوابة عن مكان شيء أو كيفية التحقق من تغيير وتجيب في طلبك التالي، تصبح الجملة التي أجابت ملاحظةً في المشروع. ومن ثم لا تسأل البوابة عن ذلك مجددًا في هذا المشروع، ويتلقى الوكيل الإجابة مسبقًا."$json$::jsonb),
  ('ar', 'whatsNew.item.routingFeedback.title', $json$"التوجيه يتعلّم مما لم ينجح"$json$::jsonb),
  ('ar', 'whatsNew.item.routingFeedback.detail', $json$"لم تعد الإجابة التي وصلت كاملة تُحتسب دائمًا نجاحًا. إذا قالت رسالتك التالية إنها لم تنجح، أو أوقفت بوابة الخروج الإجابة، يخسر النموذج الذي أجاب نقطة. كما تُحفظ درجة كل نموذج الآن حسب نوع الطلب، فيمكن أن تذهب المراجعة والاختبارات إلى نماذج مختلفة."$json$::jsonb),
  ('ar', 'whatsNew.item.levelSuggestion.title', $json$"اقتراح المستوى"$json$::jsonb),
  ('ar', 'whatsNew.item.levelSuggestion.detail', $json$"في الإعدادات، يقترح «مستواك» الآن الصعود أو النزول درجة واحدة عندما يستدعي ذلك سجل البوابة في آخر 30 يومًا (ابتداءً من 20 طلبًا): كل شيء تقريبًا يمر من المرة الأولى، أو طلبات كثيرة تُوقَف. التبديل يبقى قرارك، بنقرة واحدة."$json$::jsonb),
  ('ar', 'whatsNew.item.chatSearch.title', $json$"البحث في المحادثات"$json$::jsonb),
  ('ar', 'whatsNew.item.chatSearch.detail', $json$"أصبحت شاشة محادثات المشروع تتضمن بحثًا فيما قيل في المحادثات، مع إبراز المقطع المطابق. يعمل البحث على جهازك، في فهرس محلي، دون الاتصال بالشبكة."$json$::jsonb),
  ('ar', 'whatsNew.item.answerRecall.title', $json$"إعادة استخدام إجابات يملكها المشروع"$json$::jsonb),
  ('ar', 'whatsNew.item.answerRecall.detail', $json$"عندما يكون الطلب مطابقًا تقريبًا لطلب أُجيب عنه في محادثة أخرى من المشروع نفسه، تُرسل الإجابة السابقة معه مختصرة، فينطلق الوكيل منها بدلًا من الاستكشاف والإجابة من جديد. تظهر كل مرة يحدث فيها ذلك في لوحة Jev."$json$::jsonb),
  ('ar', 'whatsNew.item.recipes.title', $json$"وصفات للطلبات المتكررة"$json$::jsonb),
  ('ar', 'whatsNew.item.recipes.detail', $json$"تعرض ذاكرة المشروع الطلبات التي قدّمتها ثلاث مرات أو أكثر، وتتيح تحويلها إلى وصفة: خطواتك لهذا النوع من الطلبات. لا تُرسل الوصفة إلا عندما يشبهها الطلب، فلا تُثقل الطلبات الأخرى."$json$::jsonb),
  ('fr', 'memory.open', $json$"Mémoire du projet"$json$::jsonb),
  ('fr', 'memory.eyebrow', $json$"Mémoire du projet"$json$::jsonb),
  ('fr', 'memory.title', $json$"Ce que JayV sait de ce projet"$json$::jsonb),
  ('fr', 'memory.description', $json$"Les notes vont à l’agent une fois, au début d’une session. Les recettes n’accompagnent que les demandes qui leur ressemblent. Tout se synchronise avec votre compte."$json$::jsonb),
  ('fr', 'memory.tab.notes', $json$"Notes"$json$::jsonb),
  ('fr', 'memory.tab.recipes', $json$"Recettes"$json$::jsonb),
  ('fr', 'memory.notes.hint', $json$"Des faits courts que l’agent devrait sinon explorer pour trouver : comment tester, où se trouvent les choses, à quoi ne pas toucher. Ce que vous répondez quand le contrôle demande où se trouve quelque chose ou comment le vérifier est aussi enregistré ici."$json$::jsonb),
  ('fr', 'memory.notes.used', $json$"{used} / {limit} caractères"$json$::jsonb),
  ('fr', 'memory.notes.empty', $json$"Aucune note pour l’instant."$json$::jsonb),
  ('fr', 'memory.note.text', $json$"Note"$json$::jsonb),
  ('fr', 'memory.note.placeholder', $json$"ex. : Les tests se lancent avec npm test ; l’API est dans server/api."$json$::jsonb),
  ('fr', 'memory.note.add', $json$"Ajouter une note"$json$::jsonb),
  ('fr', 'memory.note.learned', $json$"Apprise du contrôle"$json$::jsonb),
  ('fr', 'memory.save', $json$"Enregistrer"$json$::jsonb),
  ('fr', 'memory.edit', $json$"Modifier"$json$::jsonb),
  ('fr', 'memory.recipes.hint', $json$"Une recette est votre procédure pour une demande que vous répétez, jusqu’à {limit} caractères. Elle n’accompagne la demande que si celle-ci ressemble à son déclencheur."$json$::jsonb),
  ('fr', 'memory.recipes.empty', $json$"Aucune recette pour l’instant."$json$::jsonb),
  ('fr', 'memory.repeated', $json$"Demandes que vous répétez"$json$::jsonb),
  ('fr', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('fr', 'memory.repeated.save', $json$"En faire une recette"$json$::jsonb),
  ('fr', 'memory.recipe.name', $json$"Nom"$json$::jsonb),
  ('fr', 'memory.recipe.name.placeholder', $json$"ex. : Nouvelle migration"$json$::jsonb),
  ('fr', 'memory.recipe.trigger', $json$"Demande déclencheur"$json$::jsonb),
  ('fr', 'memory.recipe.trigger.placeholder', $json$"Une demande à laquelle répond cette recette (vide : le nom est utilisé)"$json$::jsonb),
  ('fr', 'memory.recipe.steps', $json$"Étapes"$json$::jsonb),
  ('fr', 'memory.recipe.steps.placeholder', $json$"ex. : 1. Créez le fichier dans migrations/ 2. Lancez les tests de migration"$json$::jsonb),
  ('fr', 'memory.recipe.add', $json$"Ajouter une recette"$json$::jsonb),
  ('fr', 'memory.recipe.when', $json$"Quand : {trigger}"$json$::jsonb),
  ('fr', 'memory.empty', $json$"Écrivez d’abord quelque chose."$json$::jsonb),
  ('fr', 'memory.secret', $json$"Cela ressemble à un secret (clé, jeton ou mot de passe). Les notes vont à l’agent, elles ne peuvent donc pas contenir de secrets."$json$::jsonb),
  ('fr', 'memory.recipe.untitled', $json$"Donnez un nom à la recette."$json$::jsonb),
  ('fr', 'memory.recipe.tooLong', $json$"Une recette contient au plus {limit} caractères."$json$::jsonb),
  ('fr', 'memory.full', $json$"Les notes du projet sont pleines ({limit} caractères). Raccourcissez ou supprimez d’abord une note."$json$::jsonb),
  ('fr', 'memory.missing', $json$"Cette note n’existe plus."$json$::jsonb),
  ('fr', 'search.label', $json$"Rechercher dans les chats de ce projet"$json$::jsonb),
  ('fr', 'search.placeholder', $json$"Rechercher ce qui a été dit dans les chats de ce projet"$json$::jsonb),
  ('fr', 'search.empty', $json$"Rien trouvé dans les chats de ce projet."$json$::jsonb),
  ('fr', 'expertise.suggestion', $json$"Ces {days} derniers jours, {passed} de vos {checks} demandes ont passé le contrôle du premier coup. Le niveau {level} correspond mieux à cet historique."$json$::jsonb),
  ('fr', 'expertise.suggestion.apply', $json$"Passer à {level}"$json$::jsonb),
  ('fr', 'usage.jev.work.noteLearned', $json$"Notes apprises"$json$::jsonb),
  ('fr', 'usage.jev.work.answerRecalled', $json$"Réponses précédentes réutilisées"$json$::jsonb),
  ('fr', 'whatsNew.item.projectNotes.title', $json$"Mémoire du projet"$json$::jsonb),
  ('fr', 'whatsNew.item.projectNotes.detail', $json$"Sur l’écran des chats d’un projet, le bouton Mémoire du projet garde des notes courtes (jusqu’à 2 200 caractères) : comment tester, où se trouvent les choses, à quoi ne pas toucher. Elles vont à l’agent une fois, au début de la session, et lui évitent d’explorer le projet pour les retrouver. Les secrets sont refusés, et tout se synchronise avec votre compte."$json$::jsonb),
  ('fr', 'whatsNew.item.gateLearning.title', $json$"Le contrôle apprend de vos réponses"$json$::jsonb),
  ('fr', 'whatsNew.item.gateLearning.detail', $json$"Quand le contrôle demande où se trouve quelque chose ou comment vérifier un changement et que vous répondez dans la demande suivante, la phrase qui répondait devient une note du projet. Ensuite, le contrôle ne le redemande plus dans ce projet, et l’agent reçoit déjà la réponse."$json$::jsonb),
  ('fr', 'whatsNew.item.routingFeedback.title', $json$"Le routage apprend de ce qui n’a pas marché"$json$::jsonb),
  ('fr', 'whatsNew.item.routingFeedback.detail', $json$"Une réponse arrivée entière ne compte plus toujours comme un succès. Si votre message suivant dit que ça n’a pas marché, ou si le contrôle de sortie retient la réponse, le modèle qui a répondu perd un point. Le score de chaque modèle est aussi tenu par type de demande, donc les revues et les tests peuvent aller à des modèles différents."$json$::jsonb),
  ('fr', 'whatsNew.item.levelSuggestion.title', $json$"Suggestion de niveau"$json$::jsonb),
  ('fr', 'whatsNew.item.levelSuggestion.detail', $json$"Dans Paramètres, Votre niveau suggère maintenant de monter ou descendre d’un cran quand l’historique du contrôle des 30 derniers jours le justifie (à partir de 20 demandes) : presque tout passe du premier coup, ou beaucoup de demandes sont retenues. Le changement reste le vôtre, en un clic."$json$::jsonb),
  ('fr', 'whatsNew.item.chatSearch.title', $json$"Recherche dans les chats"$json$::jsonb),
  ('fr', 'whatsNew.item.chatSearch.detail', $json$"L’écran des chats d’un projet propose maintenant une recherche dans ce qui a été dit, avec le passage trouvé mis en évidence. Elle tourne sur votre ordinateur, dans un index local, sans passer par le réseau."$json$::jsonb),
  ('fr', 'whatsNew.item.answerRecall.title', $json$"Réutilise les réponses que le projet a déjà"$json$::jsonb),
  ('fr', 'whatsNew.item.answerRecall.detail', $json$"Quand une demande est presque identique à une autre déjà traitée dans un autre chat du même projet, la réponse précédente l’accompagne, raccourcie, et l’agent part d’elle au lieu de tout explorer et répondre à nouveau. Chaque occurrence apparaît dans le panneau Jev."$json$::jsonb),
  ('fr', 'whatsNew.item.recipes.title', $json$"Recettes pour les demandes répétées"$json$::jsonb),
  ('fr', 'whatsNew.item.recipes.detail', $json$"La Mémoire du projet affiche les demandes que vous avez faites trois fois ou plus et permet d’en faire une recette : votre procédure pour ce type de demande. La recette n’accompagne que les demandes qui lui ressemblent, elle ne pèse donc pas sur les autres."$json$::jsonb),
  ('ru', 'memory.open', $json$"Память проекта"$json$::jsonb),
  ('ru', 'memory.eyebrow', $json$"Память проекта"$json$::jsonb),
  ('ru', 'memory.title', $json$"Что JayV знает об этом проекте"$json$::jsonb),
  ('ru', 'memory.description', $json$"Заметки уходят агенту один раз, в начале сессии. Рецепты идут только с похожими на них запросами. Всё синхронизируется с вашей учётной записью."$json$::jsonb),
  ('ru', 'memory.tab.notes', $json$"Заметки"$json$::jsonb),
  ('ru', 'memory.tab.recipes', $json$"Рецепты"$json$::jsonb),
  ('ru', 'memory.notes.hint', $json$"Короткие факты, которые агенту иначе пришлось бы искать: как тестировать, где что лежит, что не трогать. Ваши ответы, когда контроль спрашивает, где что находится или как это проверить, тоже сохраняются здесь."$json$::jsonb),
  ('ru', 'memory.notes.used', $json$"{used} / {limit} символов"$json$::jsonb),
  ('ru', 'memory.notes.empty', $json$"Заметок пока нет."$json$::jsonb),
  ('ru', 'memory.note.text', $json$"Заметка"$json$::jsonb),
  ('ru', 'memory.note.placeholder', $json$"напр.: тесты запускаются через npm test; API лежит в server/api."$json$::jsonb),
  ('ru', 'memory.note.add', $json$"Добавить заметку"$json$::jsonb),
  ('ru', 'memory.note.learned', $json$"Выучено у контроля"$json$::jsonb),
  ('ru', 'memory.save', $json$"Сохранить"$json$::jsonb),
  ('ru', 'memory.edit', $json$"Изменить"$json$::jsonb),
  ('ru', 'memory.recipes.hint', $json$"Рецепт — это ваш порядок действий для повторяющегося запроса, до {limit} символов. Он отправляется, только когда запрос похож на его триггер."$json$::jsonb),
  ('ru', 'memory.recipes.empty', $json$"Рецептов пока нет."$json$::jsonb),
  ('ru', 'memory.repeated', $json$"Повторяющиеся запросы"$json$::jsonb),
  ('ru', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('ru', 'memory.repeated.save', $json$"Сделать рецептом"$json$::jsonb),
  ('ru', 'memory.recipe.name', $json$"Название"$json$::jsonb),
  ('ru', 'memory.recipe.name.placeholder', $json$"напр.: Новая миграция"$json$::jsonb),
  ('ru', 'memory.recipe.trigger', $json$"Запрос-триггер"$json$::jsonb),
  ('ru', 'memory.recipe.trigger.placeholder', $json$"Запрос, на который отвечает этот рецепт (если пусто, берётся название)"$json$::jsonb),
  ('ru', 'memory.recipe.steps', $json$"Шаги"$json$::jsonb),
  ('ru', 'memory.recipe.steps.placeholder', $json$"напр.: 1. Создайте файл в migrations/ 2. Запустите тесты миграций"$json$::jsonb),
  ('ru', 'memory.recipe.add', $json$"Добавить рецепт"$json$::jsonb),
  ('ru', 'memory.recipe.when', $json$"Когда: {trigger}"$json$::jsonb),
  ('ru', 'memory.empty', $json$"Сначала что-нибудь напишите."$json$::jsonb),
  ('ru', 'memory.secret', $json$"Похоже на секрет (ключ, токен или пароль). Заметки уходят агенту, поэтому хранить в них секреты нельзя."$json$::jsonb),
  ('ru', 'memory.recipe.untitled', $json$"Дайте рецепту название."$json$::jsonb),
  ('ru', 'memory.recipe.tooLong', $json$"Рецепт вмещает не более {limit} символов."$json$::jsonb),
  ('ru', 'memory.full', $json$"Заметки проекта заполнены ({limit} символов). Сначала сократите или удалите заметку."$json$::jsonb),
  ('ru', 'memory.missing', $json$"Этой заметки больше нет."$json$::jsonb),
  ('ru', 'search.label', $json$"Поиск по чатам проекта"$json$::jsonb),
  ('ru', 'search.placeholder', $json$"Найти сказанное в чатах проекта"$json$::jsonb),
  ('ru', 'search.empty', $json$"В чатах проекта ничего не найдено."$json$::jsonb),
  ('ru', 'expertise.suggestion', $json$"За последние {days} дней {passed} из ваших {checks} запросов прошли контроль с первого раза. Уровень «{level}» лучше подходит к этой истории."$json$::jsonb),
  ('ru', 'expertise.suggestion.apply', $json$"Перейти на «{level}»"$json$::jsonb),
  ('ru', 'usage.jev.work.noteLearned', $json$"Выученные заметки"$json$::jsonb),
  ('ru', 'usage.jev.work.answerRecalled', $json$"Повторно использованные ответы"$json$::jsonb),
  ('ru', 'whatsNew.item.projectNotes.title', $json$"Память проекта"$json$::jsonb),
  ('ru', 'whatsNew.item.projectNotes.detail', $json$"На экране чатов проекта кнопка «Память проекта» хранит короткие заметки (до 2 200 символов): как тестировать, где что лежит, что не трогать. Они уходят агенту один раз, в начале сессии, и избавляют его от повторного поиска по проекту. Секреты отклоняются, всё синхронизируется с вашей учётной записью."$json$::jsonb),
  ('ru', 'whatsNew.item.gateLearning.title', $json$"Контроль учится на ваших ответах"$json$::jsonb),
  ('ru', 'whatsNew.item.gateLearning.detail', $json$"Когда контроль спрашивает, где что находится или как проверить изменение, а вы отвечаете в следующем запросе, фраза с ответом становится заметкой проекта. После этого контроль больше не спрашивает об этом в проекте, а агент сразу получает ответ."$json$::jsonb),
  ('ru', 'whatsNew.item.routingFeedback.title', $json$"Маршрутизация учится на неудачах"$json$::jsonb),
  ('ru', 'whatsNew.item.routingFeedback.detail', $json$"Ответ, пришедший целиком, больше не всегда считается успехом. Если ваше следующее сообщение говорит, что не сработало, или выходной контроль задерживает ответ, ответившая модель теряет балл. Оценка каждой модели теперь ведётся и по типу запроса, так что ревью и тесты могут уходить разным моделям."$json$::jsonb),
  ('ru', 'whatsNew.item.levelSuggestion.title', $json$"Подсказка уровня"$json$::jsonb),
  ('ru', 'whatsNew.item.levelSuggestion.detail', $json$"В настройках «Ваш уровень» теперь предлагает подняться или опуститься на ступень, когда этого требует история контроля за последние 30 дней (от 20 запросов): почти всё проходит с первого раза или многое задерживается. Решение по-прежнему за вами, в один клик."$json$::jsonb),
  ('ru', 'whatsNew.item.chatSearch.title', $json$"Поиск по чатам"$json$::jsonb),
  ('ru', 'whatsNew.item.chatSearch.detail', $json$"На экране чатов проекта появился поиск по сказанному в переписке с подсветкой найденного фрагмента. Он работает на вашем компьютере, по локальному индексу, без обращения к сети."$json$::jsonb),
  ('ru', 'whatsNew.item.answerRecall.title', $json$"Использует ответы, которые в проекте уже есть"$json$::jsonb),
  ('ru', 'whatsNew.item.answerRecall.detail', $json$"Когда запрос почти совпадает с уже отвеченным в другом чате того же проекта, прежний ответ идёт вместе с ним в сокращённом виде, и агент отталкивается от него, а не исследует и не отвечает всё заново. Каждый такой случай отображается на панели Jev."$json$::jsonb),
  ('ru', 'whatsNew.item.recipes.title', $json$"Рецепты для повторяющихся запросов"$json$::jsonb),
  ('ru', 'whatsNew.item.recipes.detail', $json$"«Память проекта» показывает запросы, которые вы делали три раза и больше, и позволяет превратить их в рецепт — ваш порядок действий для такого запроса. Рецепт отправляется только с похожими запросами, поэтому не утяжеляет остальные."$json$::jsonb),
  ('ja', 'memory.open', $json$"プロジェクトメモリー"$json$::jsonb),
  ('ja', 'memory.eyebrow', $json$"プロジェクトメモリー"$json$::jsonb),
  ('ja', 'memory.title', $json$"JayV がこのプロジェクトについて知っていること"$json$::jsonb),
  ('ja', 'memory.description', $json$"ノートはセッション開始時に一度だけエージェントに渡されます。レシピは似たリクエストのときだけ一緒に送られます。すべてアカウントと同期されます。"$json$::jsonb),
  ('ja', 'memory.tab.notes', $json$"ノート"$json$::jsonb),
  ('ja', 'memory.tab.recipes', $json$"レシピ"$json$::jsonb),
  ('ja', 'memory.notes.hint', $json$"エージェントが本来なら探索して見つける短い事実です：テストの方法、ファイルの場所、触れてはいけないもの。ゲートが場所や確認方法を尋ねたときのあなたの答えもここに保存されます。"$json$::jsonb),
  ('ja', 'memory.notes.used', $json$"{used} / {limit} 文字"$json$::jsonb),
  ('ja', 'memory.notes.empty', $json$"まだノートはありません。"$json$::jsonb),
  ('ja', 'memory.note.text', $json$"ノート"$json$::jsonb),
  ('ja', 'memory.note.placeholder', $json$"例：テストは npm test で実行。API は server/api にある。"$json$::jsonb),
  ('ja', 'memory.note.add', $json$"ノートを追加"$json$::jsonb),
  ('ja', 'memory.note.learned', $json$"ゲートから学習"$json$::jsonb),
  ('ja', 'memory.save', $json$"保存"$json$::jsonb),
  ('ja', 'memory.edit', $json$"編集"$json$::jsonb),
  ('ja', 'memory.recipes.hint', $json$"レシピは、繰り返すリクエストのためのあなたの手順で、最大 {limit} 文字です。リクエストがトリガーに似ているときだけ一緒に送られます。"$json$::jsonb),
  ('ja', 'memory.recipes.empty', $json$"まだレシピはありません。"$json$::jsonb),
  ('ja', 'memory.repeated', $json$"繰り返しているリクエスト"$json$::jsonb),
  ('ja', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('ja', 'memory.repeated.save', $json$"レシピにする"$json$::jsonb),
  ('ja', 'memory.recipe.name', $json$"名前"$json$::jsonb),
  ('ja', 'memory.recipe.name.placeholder', $json$"例：新しいマイグレーション"$json$::jsonb),
  ('ja', 'memory.recipe.trigger', $json$"トリガーとなるリクエスト"$json$::jsonb),
  ('ja', 'memory.recipe.trigger.placeholder', $json$"このレシピが対応するリクエスト（空なら名前を使用）"$json$::jsonb),
  ('ja', 'memory.recipe.steps', $json$"手順"$json$::jsonb),
  ('ja', 'memory.recipe.steps.placeholder', $json$"例：1. migrations/ にファイルを作成 2. マイグレーションのテストを実行"$json$::jsonb),
  ('ja', 'memory.recipe.add', $json$"レシピを追加"$json$::jsonb),
  ('ja', 'memory.recipe.when', $json$"条件：{trigger}"$json$::jsonb),
  ('ja', 'memory.empty', $json$"先に内容を書いてください。"$json$::jsonb),
  ('ja', 'memory.secret', $json$"秘密情報（キー、トークン、パスワード）のようです。ノートはエージェントに渡されるため、秘密情報は保存できません。"$json$::jsonb),
  ('ja', 'memory.recipe.untitled', $json$"レシピに名前を付けてください。"$json$::jsonb),
  ('ja', 'memory.recipe.tooLong', $json$"レシピは最大 {limit} 文字です。"$json$::jsonb),
  ('ja', 'memory.full', $json$"プロジェクトのノートがいっぱいです（{limit} 文字）。先にノートを短くするか削除してください。"$json$::jsonb),
  ('ja', 'memory.missing', $json$"このノートはもう存在しません。"$json$::jsonb),
  ('ja', 'search.label', $json$"このプロジェクトのチャットを検索"$json$::jsonb),
  ('ja', 'search.placeholder', $json$"このプロジェクトのチャットで話した内容を検索"$json$::jsonb),
  ('ja', 'search.empty', $json$"このプロジェクトのチャットには見つかりませんでした。"$json$::jsonb),
  ('ja', 'expertise.suggestion', $json$"直近 {days} 日間で、{checks} 件のリクエストのうち {passed} 件が一度でゲートを通過しました。この履歴には {level} レベルの方が合っています。"$json$::jsonb),
  ('ja', 'expertise.suggestion.apply', $json$"{level} に切り替える"$json$::jsonb),
  ('ja', 'usage.jev.work.noteLearned', $json$"学習したノート"$json$::jsonb),
  ('ja', 'usage.jev.work.answerRecalled', $json$"再利用した過去の回答"$json$::jsonb),
  ('ja', 'whatsNew.item.projectNotes.title', $json$"プロジェクトメモリー"$json$::jsonb),
  ('ja', 'whatsNew.item.projectNotes.detail', $json$"プロジェクトのチャット画面にある「プロジェクトメモリー」ボタンで、短いノート（最大 2,200 文字）を保存できます：テストの方法、ファイルの場所、触れてはいけないもの。セッション開始時に一度だけエージェントに渡され、プロジェクトを探索し直す手間を省きます。秘密情報は拒否され、すべてアカウントと同期されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.gateLearning.title', $json$"ゲートがあなたの答えから学習"$json$::jsonb),
  ('ja', 'whatsNew.item.gateLearning.detail', $json$"ゲートが場所や変更の確認方法を尋ね、次のリクエストであなたが答えると、その答えの文がプロジェクトのノートになります。以降、そのプロジェクトではゲートが同じことを尋ねなくなり、エージェントは最初から答えを受け取ります。"$json$::jsonb),
  ('ja', 'whatsNew.item.routingFeedback.title', $json$"ルーティングがうまくいかなかったことから学習"$json$::jsonb),
  ('ja', 'whatsNew.item.routingFeedback.detail', $json$"完全に届いた回答が、常に成功とみなされることはなくなりました。次のメッセージでうまくいかなかったと伝えたり、出口ゲートが回答を保留したりすると、回答したモデルの評価が下がります。各モデルの評価はリクエストの種類ごとにも記録されるので、レビューとテストを別々のモデルに振り分けられます。"$json$::jsonb),
  ('ja', 'whatsNew.item.levelSuggestion.title', $json$"レベルの提案"$json$::jsonb),
  ('ja', 'whatsNew.item.levelSuggestion.detail', $json$"設定の「あなたのレベル」は、直近 30 日間のゲート履歴（20 件以上）に応じて、1 段階上げるか下げるかを提案するようになりました。ほとんどが一度で通過している場合や、多くのリクエストが止められている場合です。切り替えるかどうかは引き続きあなたが 1 クリックで決めます。"$json$::jsonb),
  ('ja', 'whatsNew.item.chatSearch.title', $json$"チャット検索"$json$::jsonb),
  ('ja', 'whatsNew.item.chatSearch.detail', $json$"プロジェクトのチャット画面に、会話の内容を検索する機能が加わり、一致した箇所が強調表示されます。検索はあなたのコンピューター上のローカル索引で行われ、ネットワークは使いません。"$json$::jsonb),
  ('ja', 'whatsNew.item.answerRecall.title', $json$"プロジェクトにある回答を再利用"$json$::jsonb),
  ('ja', 'whatsNew.item.answerRecall.detail', $json$"同じプロジェクトの別のチャットで回答済みのリクエストとほぼ同じ場合、以前の回答を短くして一緒に送り、エージェントはすべてを探索・回答し直す代わりにそこから始めます。発生した回数は Jev パネルに表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.recipes.title', $json$"繰り返すリクエストのためのレシピ"$json$::jsonb),
  ('ja', 'whatsNew.item.recipes.detail', $json$"プロジェクトメモリーには 3 回以上行ったリクエストが表示され、レシピ（その種類のリクエストに対するあなたの手順）に変えられます。レシピは似たリクエストのときだけ送られるので、ほかのリクエストの負担にはなりません。"$json$::jsonb),
  ('de', 'memory.open', $json$"Projektgedächtnis"$json$::jsonb),
  ('de', 'memory.eyebrow', $json$"Projektgedächtnis"$json$::jsonb),
  ('de', 'memory.title', $json$"Was JayV über dieses Projekt weiß"$json$::jsonb),
  ('de', 'memory.description', $json$"Notizen gehen einmal an den Agenten, wenn eine Sitzung beginnt. Rezepte gehen nur mit Anfragen mit, die ihnen ähneln. Alles wird mit deinem Konto synchronisiert."$json$::jsonb),
  ('de', 'memory.tab.notes', $json$"Notizen"$json$::jsonb),
  ('de', 'memory.tab.recipes', $json$"Rezepte"$json$::jsonb),
  ('de', 'memory.notes.hint', $json$"Kurze Fakten, die der Agent sonst erkunden müsste: wie man testet, wo was liegt, was nicht angefasst wird. Was du antwortest, wenn die Kontrolle fragt, wo etwas liegt oder wie man es prüft, wird ebenfalls hier gespeichert."$json$::jsonb),
  ('de', 'memory.notes.used', $json$"{used} / {limit} Zeichen"$json$::jsonb),
  ('de', 'memory.notes.empty', $json$"Noch keine Notizen."$json$::jsonb),
  ('de', 'memory.note.text', $json$"Notiz"$json$::jsonb),
  ('de', 'memory.note.placeholder', $json$"z. B.: Tests laufen mit npm test; die API liegt in server/api."$json$::jsonb),
  ('de', 'memory.note.add', $json$"Notiz hinzufügen"$json$::jsonb),
  ('de', 'memory.note.learned', $json$"Von der Kontrolle gelernt"$json$::jsonb),
  ('de', 'memory.save', $json$"Speichern"$json$::jsonb),
  ('de', 'memory.edit', $json$"Bearbeiten"$json$::jsonb),
  ('de', 'memory.recipes.hint', $json$"Ein Rezept ist dein Ablauf für eine wiederkehrende Anfrage, bis zu {limit} Zeichen. Es geht nur mit, wenn eine Anfrage seinem Auslöser ähnelt."$json$::jsonb),
  ('de', 'memory.recipes.empty', $json$"Noch keine Rezepte."$json$::jsonb),
  ('de', 'memory.repeated', $json$"Anfragen, die du wiederholst"$json$::jsonb),
  ('de', 'memory.repeated.count', $json$"{count}×"$json$::jsonb),
  ('de', 'memory.repeated.save', $json$"Zum Rezept machen"$json$::jsonb),
  ('de', 'memory.recipe.name', $json$"Name"$json$::jsonb),
  ('de', 'memory.recipe.name.placeholder', $json$"z. B.: Neue Migration"$json$::jsonb),
  ('de', 'memory.recipe.trigger', $json$"Auslösende Anfrage"$json$::jsonb),
  ('de', 'memory.recipe.trigger.placeholder', $json$"Eine Anfrage, die dieses Rezept beantwortet (leer: der Name zählt)"$json$::jsonb),
  ('de', 'memory.recipe.steps', $json$"Schritte"$json$::jsonb),
  ('de', 'memory.recipe.steps.placeholder', $json$"z. B.: 1. Datei in migrations/ anlegen 2. Migrationstests ausführen"$json$::jsonb),
  ('de', 'memory.recipe.add', $json$"Rezept hinzufügen"$json$::jsonb),
  ('de', 'memory.recipe.when', $json$"Wenn: {trigger}"$json$::jsonb),
  ('de', 'memory.empty', $json$"Schreib zuerst etwas."$json$::jsonb),
  ('de', 'memory.secret', $json$"Das sieht nach einem Geheimnis aus (Schlüssel, Token oder Passwort). Notizen gehen an den Agenten und dürfen daher keine Geheimnisse enthalten."$json$::jsonb),
  ('de', 'memory.recipe.untitled', $json$"Gib dem Rezept einen Namen."$json$::jsonb),
  ('de', 'memory.recipe.tooLong', $json$"Ein Rezept fasst höchstens {limit} Zeichen."$json$::jsonb),
  ('de', 'memory.full', $json$"Die Projektnotizen sind voll ({limit} Zeichen). Kürze oder lösche zuerst eine Notiz."$json$::jsonb),
  ('de', 'memory.missing', $json$"Diese Notiz gibt es nicht mehr."$json$::jsonb),
  ('de', 'search.label', $json$"In den Chats dieses Projekts suchen"$json$::jsonb),
  ('de', 'search.placeholder', $json$"Suchen, was in den Chats dieses Projekts gesagt wurde"$json$::jsonb),
  ('de', 'search.empty', $json$"In den Chats dieses Projekts wurde nichts gefunden."$json$::jsonb),
  ('de', 'expertise.suggestion', $json$"In den letzten {days} Tagen sind {passed} deiner {checks} Anfragen auf Anhieb durch die Kontrolle gekommen. Die Stufe {level} passt besser zu diesem Verlauf."$json$::jsonb),
  ('de', 'expertise.suggestion.apply', $json$"Zu {level} wechseln"$json$::jsonb),
  ('de', 'usage.jev.work.noteLearned', $json$"Gelernte Notizen"$json$::jsonb),
  ('de', 'usage.jev.work.answerRecalled', $json$"Wiederverwendete frühere Antworten"$json$::jsonb),
  ('de', 'whatsNew.item.projectNotes.title', $json$"Projektgedächtnis"$json$::jsonb),
  ('de', 'whatsNew.item.projectNotes.detail', $json$"Auf dem Chat-Bildschirm eines Projekts speichert die Schaltfläche Projektgedächtnis kurze Notizen (bis zu 2.200 Zeichen): wie man testet, wo was liegt, was nicht angefasst wird. Sie gehen einmal an den Agenten, wenn die Sitzung beginnt, und ersparen ihm, das Projekt erneut danach zu durchsuchen. Geheimnisse werden abgelehnt, und alles wird mit deinem Konto synchronisiert."$json$::jsonb),
  ('de', 'whatsNew.item.gateLearning.title', $json$"Die Kontrolle lernt aus deinen Antworten"$json$::jsonb),
  ('de', 'whatsNew.item.gateLearning.detail', $json$"Wenn die Kontrolle fragt, wo etwas liegt oder wie eine Änderung geprüft wird, und du in der nächsten Anfrage antwortest, wird der antwortende Satz zur Projektnotiz. Danach fragt die Kontrolle das in diesem Projekt nicht mehr, und der Agent bekommt die Antwort gleich mit."$json$::jsonb),
  ('de', 'whatsNew.item.routingFeedback.title', $json$"Das Routing lernt aus dem, was nicht geklappt hat"$json$::jsonb),
  ('de', 'whatsNew.item.routingFeedback.detail', $json$"Eine vollständig angekommene Antwort zählt nicht mehr automatisch als Erfolg. Sagt deine nächste Nachricht, dass es nicht geklappt hat, oder hält die Ausgangskontrolle die Antwort zurück, verliert das antwortende Modell einen Punkt. Die Bewertung jedes Modells wird jetzt auch pro Anfragetyp geführt, sodass Reviews und Tests an verschiedene Modelle gehen können."$json$::jsonb),
  ('de', 'whatsNew.item.levelSuggestion.title', $json$"Stufenvorschlag"$json$::jsonb),
  ('de', 'whatsNew.item.levelSuggestion.detail', $json$"In den Einstellungen schlägt Deine Stufe jetzt vor, eine Stufe hoch oder runter zu gehen, wenn der Kontrollverlauf der letzten 30 Tage es nahelegt (ab 20 Anfragen): fast alles kommt auf Anhieb durch, oder viele Anfragen werden aufgehalten. Der Wechsel bleibt deine Entscheidung, mit einem Klick."$json$::jsonb),
  ('de', 'whatsNew.item.chatSearch.title', $json$"Suche in den Chats"$json$::jsonb),
  ('de', 'whatsNew.item.chatSearch.detail', $json$"Der Chat-Bildschirm eines Projekts hat jetzt eine Suche über das in den Chats Gesagte, mit hervorgehobener Fundstelle. Sie läuft auf deinem Computer, über einen lokalen Index, ohne Netzwerk."$json$::jsonb),
  ('de', 'whatsNew.item.answerRecall.title', $json$"Nutzt Antworten, die das Projekt schon hat"$json$::jsonb),
  ('de', 'whatsNew.item.answerRecall.detail', $json$"Ist eine Anfrage fast gleich einer, die in einem anderen Chat desselben Projekts schon beantwortet wurde, geht die frühere Antwort gekürzt mit, und der Agent baut darauf auf, statt alles neu zu erkunden und zu beantworten. Jedes Mal erscheint im Jev-Bereich."$json$::jsonb),
  ('de', 'whatsNew.item.recipes.title', $json$"Rezepte für wiederkehrende Anfragen"$json$::jsonb),
  ('de', 'whatsNew.item.recipes.detail', $json$"Das Projektgedächtnis zeigt Anfragen, die du drei- oder mehrmals gestellt hast, und lässt dich daraus ein Rezept machen: deinen Ablauf für diese Art von Anfrage. Das Rezept geht nur mit, wenn eine Anfrage ihm ähnelt, und belastet die anderen nicht."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
