-- Janela "Novidades": o que mudou em cada versão do JayV, separado em
-- novidades e correções.
--
-- Depois de cada atualização o app abre a janela com as versões que a pessoa
-- ainda não viu neste aparelho; o botão "Novidades" em Configuração ›
-- Aplicativo › Versão a reabre com o histórico inteiro. A lista de versões e
-- dos itens de cada uma vive no app (`src/modules/changelog/releases.ts`);
-- aqui ficam só os textos: os da janela e o título e o detalhe de cada item
-- (`whatsNew.item.<id>.title` / `.detail`), da v0.23.1 à v0.33.0.
--
-- Só traduções: nenhuma tabela, coluna ou regra muda.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.title', $json$"Novidades do JayV {version}"$json$::jsonb),
  ('pt-BR', 'whatsNew.description', $json$"Tudo o que mudou em cada versão, separado em novidades e correções."$json$::jsonb),
  ('pt-BR', 'whatsNew.description.updated', $json$"O JayV foi atualizado da versão {previous} para a {version}. Veja o que mudou."$json$::jsonb),
  ('pt-BR', 'whatsNew.description.installed', $json$"Você está na versão {version} do JayV. Veja o que ela trouxe."$json$::jsonb),
  ('pt-BR', 'whatsNew.features', $json$"Novidades"$json$::jsonb),
  ('pt-BR', 'whatsNew.fixes', $json$"Correções"$json$::jsonb),
  ('pt-BR', 'whatsNew.version', $json$"Versão {version}"$json$::jsonb),
  ('pt-BR', 'whatsNew.installed', $json$"Instalada"$json$::jsonb),
  ('pt-BR', 'whatsNew.showAll', $json$"Ver versões anteriores"$json$::jsonb),
  ('pt-BR', 'whatsNew.done', $json$"Entendi"$json$::jsonb),
  ('pt-BR', 'app.whatsNew', $json$"Novidades"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.whatsNew.title', $json$"Janela de novidades"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.whatsNew.detail', $json$"Depois de cada atualização, o JayV abre esta janela com o que mudou desde a última versão que você viu neste computador, separado em novidades e correções. Ela aparece uma vez por versão e some quando você clica em Entendi."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.whatsNewHistory.title', $json$"Histórico de versões a qualquer momento"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.whatsNewHistory.detail', $json$"Em Configuração › Aplicativo › Versão, o botão Novidades reabre a janela com a versão instalada no topo e o histórico das anteriores logo abaixo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.fixedSidebar.title', $json$"Lateral e cabeçalho fixos ao rolar"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.fixedSidebar.detail', $json$"Em Projetos, Organizações, página da organização, Configurações, Perfil, Estatísticas e Sistema, a lateral subia junto com o conteúdo. Agora só o conteúdo da página rola; a lateral e o cabeçalho ficam do tamanho da janela, sempre à vista."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChat.title', $json$"Chat da organização em todos os repositórios"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChat.detail', $json$"A página da organização ganhou o botão Chat da organização, que abre um chat trabalhando em todos os repositórios dela ao mesmo tempo, usando a pasta da organização neste computador. Sem pasta escolhida, o JayV pede uma antes de abrir. O agente, o índice e a portaria enxergam todos os clones dentro dela."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChatReach.title', $json$"Saiba quais repositórios entram no chat"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChatReach.detail', $json$"Antes de abrir, uma janela mostra a pasta (com o botão Trocar) e separa os repositórios em: neste chat, de fora por estarem clonados em outra pasta e de fora por não estarem neste computador."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChatPolicy.title', $json$"A política mais rígida vale no chat da organização"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChatPolicy.detail', $json$"O chat da organização roda sob a política de LLM da organização junto com a de cada repositório dela, e vale sempre a regra mais rígida entre todas."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChatDashboard.title', $json$"Chat da organização nas Estatísticas e na Portaria"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgChatDashboard.detail', $json$"O uso do chat da organização passou a aparecer nas abas Estatísticas e Portaria da organização logo de cara, sem esperar o servidor ligar o projeto a ela."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactor.title', $json$"Autenticação de dois fatores"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactor.detail', $json$"Em Perfil › Segurança, ative um app autenticador: escaneie o QR code (ou digite a chave, mostrada em blocos de 4) e confirme com o primeiro código. O fator só passa a valer depois dessa confirmação, e Cancelar descarta um cadastro pela metade."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactorSignIn.title', $json$"Código de 6 dígitos em todo login"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactorSignIn.detail', $json$"Com o app ligado, todo login pede o código depois da senha, do GitHub, do GitLab, do Bitbucket ou do link de recuperação de senha. O banco recusa pedidos de uma sessão que ainda não passou pelo segundo fator."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactorProtect.title', $json$"Desativar a proteção pede um código"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactorProtect.detail', $json$"Para tirar o segundo fator é preciso digitar um código atual do app: uma sessão esquecida aberta não basta para remover a proteção da conta."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactorPassword.title', $json$"Troca de senha com o app ligado"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.twoFactorPassword.detail', $json$"Com o segundo fator ativo, o formulário de troca de senha pede também o código do app. Se o código falhar, o JayV pede o segundo fator de novo em vez de deixar a sessão pela metade."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.lockdown.title', $json$"App instalado fechado para inspeção"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.lockdown.detail', $json$"Na versão instalada, o menu do botão direito (fora dos campos de texto, que mantêm copiar e colar) e os atalhos de ferramentas de desenvolvedor, ver código-fonte, salvar, imprimir e recarregar a página foram desligados, e as variáveis que abririam um inspetor remoto são apagadas ao iniciar."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.safeConnections.title', $json$"Conexões mais seguras"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.safeConnections.detail', $json$"Toda requisição do JayV confia só nas autoridades de certificado embutidas e exige TLS 1.2 ou mais: um proxy que intercepta HTTPS instalando o próprio certificado no sistema é recusado, e um proxy comum continua funcionando."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.realtimeNotifications.title', $json$"Notificações em tempo real voltaram"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.realtimeNotifications.detail', $json$"A política de segurança de conteúdo barrava a conexão segura (wss) com o Supabase, e o sino não recebia notificações na hora. Ela agora é permitida, assim como as imagens embutidas usadas pelo QR code do segundo fator."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgStats.title', $json$"Aba Estatísticas na organização"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgStats.detail', $json$"Resumo, gráficos, painel do Jev e tabelas por ferramenta, modelo, projeto e chat, somando só os projetos deste computador que pertencem à organização. Há filtro de projeto, de chat e de período, e clicar numa linha das tabelas recorta a vista."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgGate.title', $json$"Aba Portaria na organização"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgGate.detail', $json$"O placar e os dois portões, de entrada e de saída, dos projetos da organização. A aba divide o filtro com Estatísticas: trocar de aba mantém o recorte, e abrir outra organização o zera."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.usernameOnce.title', $json$"Nome de usuário definido uma vez"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.usernameOnce.detail', $json$"O nome de usuário fica fixo depois do primeiro salvamento do perfil. O formulário avisa antes de salvar, e depois disso o campo fica só para leitura. Pular o passo de perfil não fixa o nome."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgPolicyDefaults.title', $json$"Organização nova já nasce com política"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgPolicyDefaults.detail', $json$"Ao criar uma organização, os campos Nunca ler e Só para modelos locais já vêm preenchidos com padrões seguros, e a aba Política abre pronta para ajustar."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentIcons.title', $json$"Ícones certos do Claude Code e do Codex"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentIcons.detail', $json$"As abas dos agentes mostravam desenhos antigos. Agora aparecem o ícone oficial do Claude Code e o ícone atual do Codex, nítidos em qualquer tamanho."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentExecutable.title', $json$"Campo Executável travado"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentExecutable.detail', $json$"Nas abas Claude, Codex, Copilot e Cursor, o JayV define o executável por conta própria: o campo fica desativado, com uma dica explicando o porquê, e o botão Verificar continua funcionando."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateBanner.title', $json$"Aviso de versão nova no topo"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateBanner.detail', $json$"Quando sai uma versão nova, uma faixa aparece no topo de qualquer tela, com O que muda (as notas da versão) e Atualizar agora. Fechar a faixa esconde o aviso só daquela versão."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateNotification.title', $json$"Versão nova também no sino"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateNotification.detail', $json$"Cada versão nova vira uma notificação no sino, uma só por versão, que leva direto à janela da atualização."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateNoAutoInstall.title', $json$"A atualização não interrompe mais o trabalho"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateNoAutoInstall.detail', $json$"Antes, o JayV achava a versão nova ao abrir e já instalava, com a janela de progresso na frente. Agora a consulta, ao abrir e a cada 30 minutos, só avisa: você escolhe a hora de atualizar. Sem rede, a consulta fica em silêncio."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgFolderRemove.title', $json$"Remover a pasta da organização"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgFolderRemove.detail', $json$"Na aba Repositórios, o botão Remover faz o JayV esquecer a pasta da organização neste computador, com confirmação. Nada é apagado do disco: os clones e os projetos continuam onde estão, e o próximo clone pergunta a pasta de novo."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectDeletion.title', $json$"Excluir um projeto apaga os chats dele em todo lugar"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectDeletion.detail', $json$"Os chats de um projeto excluído voltavam em outro computador depois da sincronização. Agora a exclusão segue também no servidor para os chats, as mensagens e as verificações do projeto."$json$::jsonb),
  ('en', 'whatsNew.title', $json$"What's new in JayV {version}"$json$::jsonb),
  ('en', 'whatsNew.description', $json$"Everything that changed in each version, split into new features and fixes."$json$::jsonb),
  ('en', 'whatsNew.description.updated', $json$"JayV was updated from version {previous} to {version}. Here is what changed."$json$::jsonb),
  ('en', 'whatsNew.description.installed', $json$"You are on JayV {version}. Here is what this version brought."$json$::jsonb),
  ('en', 'whatsNew.features', $json$"New features"$json$::jsonb),
  ('en', 'whatsNew.fixes', $json$"Fixes"$json$::jsonb),
  ('en', 'whatsNew.version', $json$"Version {version}"$json$::jsonb),
  ('en', 'whatsNew.installed', $json$"Installed"$json$::jsonb),
  ('en', 'whatsNew.showAll', $json$"See earlier versions"$json$::jsonb),
  ('en', 'whatsNew.done', $json$"Got it"$json$::jsonb),
  ('en', 'app.whatsNew', $json$"What's new"$json$::jsonb),
  ('en', 'whatsNew.item.whatsNew.title', $json$"What's new window"$json$::jsonb),
  ('en', 'whatsNew.item.whatsNew.detail', $json$"After every update, JayV opens this window with what changed since the last version you saw on this computer, split into new features and fixes. It shows once per version and goes away when you click Got it."$json$::jsonb),
  ('en', 'whatsNew.item.whatsNewHistory.title', $json$"Version history anytime"$json$::jsonb),
  ('en', 'whatsNew.item.whatsNewHistory.detail', $json$"In Settings › App › Version, the What's new button opens the window again, with the installed version on top and the history of earlier ones below it."$json$::jsonb),
  ('en', 'whatsNew.item.fixedSidebar.title', $json$"Sidebar and header stay put when scrolling"$json$::jsonb),
  ('en', 'whatsNew.item.fixedSidebar.detail', $json$"On Projects, Organizations, the organization page, Settings, Profile, Statistics and System, the sidebar scrolled away with the content. Now only the page content scrolls; the sidebar and header keep the window's height and stay in view."$json$::jsonb),
  ('en', 'whatsNew.item.orgChat.title', $json$"Organization chat across every repository"$json$::jsonb),
  ('en', 'whatsNew.item.orgChat.detail', $json$"The organization page has a new Organization chat button that opens one chat working on all of its repositories at once, using the organization folder on this computer. Without a folder, JayV asks for one first. The agent, the index and the gate see every clone inside it."$json$::jsonb),
  ('en', 'whatsNew.item.orgChatReach.title', $json$"See which repositories join the chat"$json$::jsonb),
  ('en', 'whatsNew.item.orgChatReach.detail', $json$"Before opening, a window shows the folder (with a Change button) and sorts the repositories into: in this chat, left out because they are cloned in another folder, and left out because they are not on this computer."$json$::jsonb),
  ('en', 'whatsNew.item.orgChatPolicy.title', $json$"The strictest policy applies in the organization chat"$json$::jsonb),
  ('en', 'whatsNew.item.orgChatPolicy.detail', $json$"The organization chat runs under the organization's LLM policy together with the policy of each of its repositories, and the strictest rule among them always wins."$json$::jsonb),
  ('en', 'whatsNew.item.orgChatDashboard.title', $json$"Organization chat in Statistics and Gate"$json$::jsonb),
  ('en', 'whatsNew.item.orgChatDashboard.detail', $json$"Usage from the organization chat now shows up in the organization's Statistics and Gate tabs right away, without waiting for the server to link the project to it."$json$::jsonb),
  ('en', 'whatsNew.item.twoFactor.title', $json$"Two-factor authentication"$json$::jsonb),
  ('en', 'whatsNew.item.twoFactor.detail', $json$"In Profile › Security, turn on an authenticator app: scan the QR code (or type the key, shown in blocks of 4) and confirm with the first code. The factor only counts after that confirmation, and Cancel discards a half-done setup."$json$::jsonb),
  ('en', 'whatsNew.item.twoFactorSignIn.title', $json$"A 6-digit code at every sign-in"$json$::jsonb),
  ('en', 'whatsNew.item.twoFactorSignIn.detail', $json$"With the app turned on, every sign-in asks for the code after the password, GitHub, GitLab, Bitbucket or the password recovery link. The database refuses requests from a session that has not passed the second factor yet."$json$::jsonb),
  ('en', 'whatsNew.item.twoFactorProtect.title', $json$"Turning protection off asks for a code"$json$::jsonb),
  ('en', 'whatsNew.item.twoFactorProtect.detail', $json$"Removing the second factor requires a current code from the app: a session left open is not enough to take the protection off the account."$json$::jsonb),
  ('en', 'whatsNew.item.twoFactorPassword.title', $json$"Changing the password with the app on"$json$::jsonb),
  ('en', 'whatsNew.item.twoFactorPassword.detail', $json$"With the second factor on, the change password form also asks for the app code. If the code fails, JayV asks for the second factor again instead of leaving the session half-done."$json$::jsonb),
  ('en', 'whatsNew.item.lockdown.title', $json$"Installed app closed to inspection"$json$::jsonb),
  ('en', 'whatsNew.item.lockdown.detail', $json$"In the installed app, the right-click menu (outside text fields, which keep copy and paste) and the shortcuts for developer tools, view source, save, print and reload are turned off, and the variables that would open a remote inspector are cleared at startup."$json$::jsonb),
  ('en', 'whatsNew.item.safeConnections.title', $json$"Safer connections"$json$::jsonb),
  ('en', 'whatsNew.item.safeConnections.detail', $json$"Every request JayV makes trusts only built-in certificate authorities and requires TLS 1.2 or newer: a proxy that intercepts HTTPS by installing its own certificate on the system is refused, while an ordinary proxy keeps working."$json$::jsonb),
  ('en', 'whatsNew.item.realtimeNotifications.title', $json$"Real-time notifications are back"$json$::jsonb),
  ('en', 'whatsNew.item.realtimeNotifications.detail', $json$"The content security policy blocked the secure connection (wss) to Supabase, so the bell did not get notifications as they happened. It is allowed now, along with the embedded images used by the second-factor QR code."$json$::jsonb),
  ('en', 'whatsNew.item.orgStats.title', $json$"Statistics tab in the organization"$json$::jsonb),
  ('en', 'whatsNew.item.orgStats.detail', $json$"Summary, charts, the Jev panel and tables by tool, model, project and chat, adding up only the projects on this computer that belong to the organization. There are project, chat and period filters, and clicking a table row narrows the view."$json$::jsonb),
  ('en', 'whatsNew.item.orgGate.title', $json$"Gate tab in the organization"$json$::jsonb),
  ('en', 'whatsNew.item.orgGate.detail', $json$"The scoreboard and both gates, entry and exit, for the organization's projects. The tab shares its filter with Statistics: switching tabs keeps the selection, and opening another organization resets it."$json$::jsonb),
  ('en', 'whatsNew.item.usernameOnce.title', $json$"Username set once"$json$::jsonb),
  ('en', 'whatsNew.item.usernameOnce.detail', $json$"Your username is locked after you first save your profile. The form warns you before saving, and afterwards the field is read-only. Skipping the profile step does not lock the name."$json$::jsonb),
  ('en', 'whatsNew.item.orgPolicyDefaults.title', $json$"New organizations start with a policy"$json$::jsonb),
  ('en', 'whatsNew.item.orgPolicyDefaults.detail', $json$"When you create an organization, Never read and Local models only come filled with safe defaults, and the Policy tab opens ready to adjust."$json$::jsonb),
  ('en', 'whatsNew.item.agentIcons.title', $json$"Correct Claude Code and Codex icons"$json$::jsonb),
  ('en', 'whatsNew.item.agentIcons.detail', $json$"The agent tabs showed old drawings. They now show the official Claude Code icon and the current Codex icon, sharp at any size."$json$::jsonb),
  ('en', 'whatsNew.item.agentExecutable.title', $json$"Executable field locked"$json$::jsonb),
  ('en', 'whatsNew.item.agentExecutable.detail', $json$"In the Claude, Codex, Copilot and Cursor tabs, JayV sets the executable itself: the field is disabled, with a hint explaining why, and the Verify button still works."$json$::jsonb),
  ('en', 'whatsNew.item.updateBanner.title', $json$"New version notice at the top"$json$::jsonb),
  ('en', 'whatsNew.item.updateBanner.detail', $json$"When a new version comes out, a bar appears at the top of every screen with What changes (the release notes) and Update now. Closing the bar hides the notice for that version only."$json$::jsonb),
  ('en', 'whatsNew.item.updateNotification.title', $json$"New version in the bell too"$json$::jsonb),
  ('en', 'whatsNew.item.updateNotification.detail', $json$"Each new version becomes a notification in the bell, just one per version, that takes you straight to the update window."$json$::jsonb),
  ('en', 'whatsNew.item.updateNoAutoInstall.title', $json$"Updates no longer interrupt your work"$json$::jsonb),
  ('en', 'whatsNew.item.updateNoAutoInstall.detail', $json$"JayV used to find the new version when it opened and install it right away, with the progress window in front. Now the check, at startup and every 30 minutes, only notifies you: you choose when to update. Without a network, the check stays silent."$json$::jsonb),
  ('en', 'whatsNew.item.orgFolderRemove.title', $json$"Remove the organization folder"$json$::jsonb),
  ('en', 'whatsNew.item.orgFolderRemove.detail', $json$"In the Repositories tab, the Remove button makes JayV forget the organization folder on this computer, after a confirmation. Nothing is deleted from disk: clones and projects stay where they are, and the next clone asks for a folder again."$json$::jsonb),
  ('en', 'whatsNew.item.projectDeletion.title', $json$"Deleting a project removes its chats everywhere"$json$::jsonb),
  ('en', 'whatsNew.item.projectDeletion.detail', $json$"Chats from a deleted project came back on another computer after syncing. Now the deletion also carries over on the server to the project's chats, messages and checks."$json$::jsonb),
  ('es', 'whatsNew.title', $json$"Novedades de JayV {version}"$json$::jsonb),
  ('es', 'whatsNew.description', $json$"Todo lo que cambió en cada versión, separado en novedades y correcciones."$json$::jsonb),
  ('es', 'whatsNew.description.updated', $json$"JayV se actualizó de la versión {previous} a la {version}. Esto es lo que cambió."$json$::jsonb),
  ('es', 'whatsNew.description.installed', $json$"Estás en la versión {version} de JayV. Esto es lo que trajo."$json$::jsonb),
  ('es', 'whatsNew.features', $json$"Novedades"$json$::jsonb),
  ('es', 'whatsNew.fixes', $json$"Correcciones"$json$::jsonb),
  ('es', 'whatsNew.version', $json$"Versión {version}"$json$::jsonb),
  ('es', 'whatsNew.installed', $json$"Instalada"$json$::jsonb),
  ('es', 'whatsNew.showAll', $json$"Ver versiones anteriores"$json$::jsonb),
  ('es', 'whatsNew.done', $json$"Entendido"$json$::jsonb),
  ('es', 'app.whatsNew', $json$"Novedades"$json$::jsonb),
  ('es', 'whatsNew.item.whatsNew.title', $json$"Ventana de novedades"$json$::jsonb),
  ('es', 'whatsNew.item.whatsNew.detail', $json$"Después de cada actualización, JayV abre esta ventana con lo que cambió desde la última versión que viste en este equipo, separado en novedades y correcciones. Aparece una vez por versión y se cierra al hacer clic en Entendido."$json$::jsonb),
  ('es', 'whatsNew.item.whatsNewHistory.title', $json$"Historial de versiones en cualquier momento"$json$::jsonb),
  ('es', 'whatsNew.item.whatsNewHistory.detail', $json$"En Configuración › Aplicación › Versión, el botón Novedades vuelve a abrir la ventana, con la versión instalada arriba y el historial de las anteriores debajo."$json$::jsonb),
  ('es', 'whatsNew.item.fixedSidebar.title', $json$"Barra lateral y encabezado fijos al desplazarse"$json$::jsonb),
  ('es', 'whatsNew.item.fixedSidebar.detail', $json$"En Proyectos, Organizaciones, la página de la organización, Configuración, Perfil, Estadísticas y Sistema, la barra lateral se desplazaba con el contenido. Ahora solo se desplaza el contenido; la barra lateral y el encabezado ocupan la altura de la ventana y siempre están a la vista."$json$::jsonb),
  ('es', 'whatsNew.item.orgChat.title', $json$"Chat de la organización en todos los repositorios"$json$::jsonb),
  ('es', 'whatsNew.item.orgChat.detail', $json$"La página de la organización tiene el nuevo botón Chat de la organización, que abre un chat que trabaja en todos sus repositorios a la vez, usando la carpeta de la organización en este equipo. Sin carpeta elegida, JayV pide una antes. El agente, el índice y el control ven todos los clones dentro de ella."$json$::jsonb),
  ('es', 'whatsNew.item.orgChatReach.title', $json$"Mira qué repositorios entran en el chat"$json$::jsonb),
  ('es', 'whatsNew.item.orgChatReach.detail', $json$"Antes de abrir, una ventana muestra la carpeta (con el botón Cambiar) y separa los repositorios en: en este chat, fuera por estar clonados en otra carpeta y fuera por no estar en este equipo."$json$::jsonb),
  ('es', 'whatsNew.item.orgChatPolicy.title', $json$"En el chat de la organización rige la política más estricta"$json$::jsonb),
  ('es', 'whatsNew.item.orgChatPolicy.detail', $json$"El chat de la organización funciona con la política de LLM de la organización junto con la de cada uno de sus repositorios, y siempre gana la regla más estricta."$json$::jsonb),
  ('es', 'whatsNew.item.orgChatDashboard.title', $json$"Chat de la organización en Estadísticas y Control"$json$::jsonb),
  ('es', 'whatsNew.item.orgChatDashboard.detail', $json$"El uso del chat de la organización ahora aparece de inmediato en las pestañas Estadísticas y Control de la organización, sin esperar a que el servidor vincule el proyecto."$json$::jsonb),
  ('es', 'whatsNew.item.twoFactor.title', $json$"Autenticación en dos pasos"$json$::jsonb),
  ('es', 'whatsNew.item.twoFactor.detail', $json$"En Perfil › Seguridad, activa una app de autenticación: escanea el código QR (o escribe la clave, mostrada en bloques de 4) y confirma con el primer código. El factor solo vale tras esa confirmación, y Cancelar descarta una configuración a medias."$json$::jsonb),
  ('es', 'whatsNew.item.twoFactorSignIn.title', $json$"Código de 6 dígitos en cada inicio de sesión"$json$::jsonb),
  ('es', 'whatsNew.item.twoFactorSignIn.detail', $json$"Con la app activada, cada inicio de sesión pide el código después de la contraseña, GitHub, GitLab, Bitbucket o el enlace de recuperación de contraseña. La base de datos rechaza solicitudes de una sesión que aún no pasó el segundo factor."$json$::jsonb),
  ('es', 'whatsNew.item.twoFactorProtect.title', $json$"Desactivar la protección pide un código"$json$::jsonb),
  ('es', 'whatsNew.item.twoFactorProtect.detail', $json$"Para quitar el segundo factor hay que escribir un código actual de la app: una sesión olvidada abierta no basta para quitar la protección de la cuenta."$json$::jsonb),
  ('es', 'whatsNew.item.twoFactorPassword.title', $json$"Cambio de contraseña con la app activada"$json$::jsonb),
  ('es', 'whatsNew.item.twoFactorPassword.detail', $json$"Con el segundo factor activo, el formulario de cambio de contraseña también pide el código de la app. Si el código falla, JayV vuelve a pedir el segundo factor en lugar de dejar la sesión a medias."$json$::jsonb),
  ('es', 'whatsNew.item.lockdown.title', $json$"App instalada cerrada a la inspección"$json$::jsonb),
  ('es', 'whatsNew.item.lockdown.detail', $json$"En la app instalada, el menú del botón derecho (fuera de los campos de texto, que conservan copiar y pegar) y los atajos de herramientas de desarrollo, ver código fuente, guardar, imprimir y recargar están desactivados, y las variables que abrirían un inspector remoto se borran al iniciar."$json$::jsonb),
  ('es', 'whatsNew.item.safeConnections.title', $json$"Conexiones más seguras"$json$::jsonb),
  ('es', 'whatsNew.item.safeConnections.detail', $json$"Cada solicitud de JayV confía solo en las autoridades de certificación integradas y exige TLS 1.2 o superior: se rechaza un proxy que intercepta HTTPS instalando su propio certificado en el sistema, y un proxy común sigue funcionando."$json$::jsonb),
  ('es', 'whatsNew.item.realtimeNotifications.title', $json$"Volvieron las notificaciones en tiempo real"$json$::jsonb),
  ('es', 'whatsNew.item.realtimeNotifications.detail', $json$"La política de seguridad de contenido bloqueaba la conexión segura (wss) con Supabase, y la campana no recibía las notificaciones al momento. Ahora está permitida, igual que las imágenes incrustadas que usa el código QR del segundo factor."$json$::jsonb),
  ('es', 'whatsNew.item.orgStats.title', $json$"Pestaña Estadísticas en la organización"$json$::jsonb),
  ('es', 'whatsNew.item.orgStats.detail', $json$"Resumen, gráficos, panel de Jev y tablas por herramienta, modelo, proyecto y chat, sumando solo los proyectos de este equipo que pertenecen a la organización. Hay filtros de proyecto, chat y período, y al hacer clic en una fila de las tablas se acota la vista."$json$::jsonb),
  ('es', 'whatsNew.item.orgGate.title', $json$"Pestaña Control en la organización"$json$::jsonb),
  ('es', 'whatsNew.item.orgGate.detail', $json$"El marcador y las dos puertas, de entrada y de salida, de los proyectos de la organización. La pestaña comparte el filtro con Estadísticas: cambiar de pestaña conserva la selección y abrir otra organización la reinicia."$json$::jsonb),
  ('es', 'whatsNew.item.usernameOnce.title', $json$"Nombre de usuario definido una vez"$json$::jsonb),
  ('es', 'whatsNew.item.usernameOnce.detail', $json$"El nombre de usuario queda fijo después de guardar el perfil por primera vez. El formulario avisa antes de guardar y después el campo queda solo de lectura. Saltar el paso del perfil no fija el nombre."$json$::jsonb),
  ('es', 'whatsNew.item.orgPolicyDefaults.title', $json$"Las organizaciones nuevas nacen con política"$json$::jsonb),
  ('es', 'whatsNew.item.orgPolicyDefaults.detail', $json$"Al crear una organización, los campos Nunca leer y Solo para modelos locales ya vienen con valores seguros, y la pestaña Política se abre lista para ajustar."$json$::jsonb),
  ('es', 'whatsNew.item.agentIcons.title', $json$"Iconos correctos de Claude Code y Codex"$json$::jsonb),
  ('es', 'whatsNew.item.agentIcons.detail', $json$"Las pestañas de los agentes mostraban dibujos antiguos. Ahora aparecen el icono oficial de Claude Code y el icono actual de Codex, nítidos en cualquier tamaño."$json$::jsonb),
  ('es', 'whatsNew.item.agentExecutable.title', $json$"Campo Ejecutable bloqueado"$json$::jsonb),
  ('es', 'whatsNew.item.agentExecutable.detail', $json$"En las pestañas Claude, Codex, Copilot y Cursor, JayV define el ejecutable por su cuenta: el campo queda desactivado, con una pista que explica por qué, y el botón Verificar sigue funcionando."$json$::jsonb),
  ('es', 'whatsNew.item.updateBanner.title', $json$"Aviso de versión nueva arriba"$json$::jsonb),
  ('es', 'whatsNew.item.updateBanner.detail', $json$"Cuando sale una versión nueva, aparece una franja arriba de cualquier pantalla con Qué cambia (las notas de la versión) y Actualizar ahora. Cerrar la franja oculta el aviso solo de esa versión."$json$::jsonb),
  ('es', 'whatsNew.item.updateNotification.title', $json$"Versión nueva también en la campana"$json$::jsonb),
  ('es', 'whatsNew.item.updateNotification.detail', $json$"Cada versión nueva se convierte en una notificación en la campana, una sola por versión, que lleva directo a la ventana de actualización."$json$::jsonb),
  ('es', 'whatsNew.item.updateNoAutoInstall.title', $json$"La actualización ya no interrumpe el trabajo"$json$::jsonb),
  ('es', 'whatsNew.item.updateNoAutoInstall.detail', $json$"Antes, JayV encontraba la versión nueva al abrirse y la instalaba enseguida, con la ventana de progreso delante. Ahora la consulta, al abrir y cada 30 minutos, solo avisa: tú eliges cuándo actualizar. Sin red, la consulta no dice nada."$json$::jsonb),
  ('es', 'whatsNew.item.orgFolderRemove.title', $json$"Quitar la carpeta de la organización"$json$::jsonb),
  ('es', 'whatsNew.item.orgFolderRemove.detail', $json$"En la pestaña Repositorios, el botón Quitar hace que JayV olvide la carpeta de la organización en este equipo, tras una confirmación. No se borra nada del disco: los clones y los proyectos siguen donde están, y el próximo clon vuelve a pedir la carpeta."$json$::jsonb),
  ('es', 'whatsNew.item.projectDeletion.title', $json$"Eliminar un proyecto borra sus chats en todas partes"$json$::jsonb),
  ('es', 'whatsNew.item.projectDeletion.detail', $json$"Los chats de un proyecto eliminado volvían en otro equipo después de sincronizar. Ahora la eliminación también llega en el servidor a los chats, mensajes y verificaciones del proyecto."$json$::jsonb),
  ('zh-CN', 'whatsNew.title', $json$"JayV {version} 新功能"$json$::jsonb),
  ('zh-CN', 'whatsNew.description', $json$"每个版本的全部变化，分为新功能和修复。"$json$::jsonb),
  ('zh-CN', 'whatsNew.description.updated', $json$"JayV 已从版本 {previous} 更新到 {version}。以下是变化内容。"$json$::jsonb),
  ('zh-CN', 'whatsNew.description.installed', $json$"你正在使用 JayV {version}。以下是此版本带来的内容。"$json$::jsonb),
  ('zh-CN', 'whatsNew.features', $json$"新功能"$json$::jsonb),
  ('zh-CN', 'whatsNew.fixes', $json$"修复"$json$::jsonb),
  ('zh-CN', 'whatsNew.version', $json$"版本 {version}"$json$::jsonb),
  ('zh-CN', 'whatsNew.installed', $json$"已安装"$json$::jsonb),
  ('zh-CN', 'whatsNew.showAll', $json$"查看更早的版本"$json$::jsonb),
  ('zh-CN', 'whatsNew.done', $json$"知道了"$json$::jsonb),
  ('zh-CN', 'app.whatsNew', $json$"新功能"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.whatsNew.title', $json$"新功能窗口"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.whatsNew.detail', $json$"每次更新后，JayV 都会打开此窗口，显示自你在这台电脑上看到的上一个版本以来的变化，分为新功能和修复。每个版本只显示一次，点击“知道了”即可关闭。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.whatsNewHistory.title', $json$"随时查看版本历史"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.whatsNewHistory.detail', $json$"在 设置 › 应用 › 版本 中，“新功能”按钮可以再次打开此窗口，已安装的版本在最上方，更早版本的历史在下方。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.fixedSidebar.title', $json$"滚动时侧边栏和页眉保持固定"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.fixedSidebar.detail', $json$"在“项目”“组织”、组织页面、“设置”“个人资料”“统计”和“系统”中，侧边栏原本会随内容一起滚走。现在只有页面内容滚动，侧边栏和页眉保持窗口高度，始终可见。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChat.title', $json$"覆盖所有仓库的组织聊天"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChat.detail', $json$"组织页面新增“组织聊天”按钮，可打开一个同时处理该组织所有仓库的聊天，使用这台电脑上的组织文件夹。如果还没有选择文件夹，JayV 会先请你选择。代理、索引和把关都能看到其中的所有克隆。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChatReach.title', $json$"查看哪些仓库加入聊天"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChatReach.detail', $json$"打开前会显示一个窗口，列出文件夹（带“更改”按钮），并将仓库分为：在此聊天中、因克隆在其他文件夹而排除、因不在这台电脑上而排除。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChatPolicy.title', $json$"组织聊天采用最严格的策略"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChatPolicy.detail', $json$"组织聊天同时遵循组织的 LLM 策略和其每个仓库的策略，始终以其中最严格的规则为准。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChatDashboard.title', $json$"组织聊天计入统计和把关"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgChatDashboard.detail', $json$"组织聊天的用量现在会立即显示在组织的“统计”和“把关”标签页中，无需等待服务器关联项目。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactor.title', $json$"双重身份验证"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactor.detail', $json$"在 个人资料 › 安全 中启用身份验证器应用：扫描二维码（或输入按 4 位分组显示的密钥），并用第一个验证码确认。确认后该因素才生效，“取消”会丢弃未完成的设置。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactorSignIn.title', $json$"每次登录都需要 6 位验证码"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactorSignIn.detail', $json$"启用后，每次通过密码、GitHub、GitLab、Bitbucket 或密码恢复链接登录后都会要求输入验证码。数据库会拒绝尚未通过第二因素的会话发出的请求。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactorProtect.title', $json$"关闭保护需要验证码"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactorProtect.detail', $json$"移除第二因素需要输入应用中的当前验证码：仅凭一个忘记关闭的会话无法解除账户保护。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactorPassword.title', $json$"启用应用后更改密码"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.twoFactorPassword.detail', $json$"启用第二因素后，更改密码表单也会要求输入应用验证码。如果验证码错误，JayV 会再次要求第二因素，而不会让会话停留在半完成状态。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.lockdown.title', $json$"已安装的应用禁止检查"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.lockdown.detail', $json$"在已安装的应用中，右键菜单（文本框除外，仍可复制粘贴）以及开发者工具、查看源代码、保存、打印和重新加载的快捷键均已关闭，启动时还会清除可能打开远程检查器的变量。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.safeConnections.title', $json$"更安全的连接"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.safeConnections.detail', $json$"JayV 的每个请求只信任内置的证书颁发机构，并要求 TLS 1.2 或更高版本：通过在系统中安装自有证书来拦截 HTTPS 的代理会被拒绝，普通代理仍可正常使用。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.realtimeNotifications.title', $json$"实时通知已恢复"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.realtimeNotifications.detail', $json$"内容安全策略之前阻止了与 Supabase 的安全连接（wss），铃铛无法即时收到通知。现在已允许该连接，以及第二因素二维码使用的内嵌图片。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgStats.title', $json$"组织中的“统计”标签页"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgStats.detail', $json$"摘要、图表、Jev 面板，以及按工具、模型、项目和聊天划分的表格，只统计这台电脑上属于该组织的项目。可按项目、聊天和时间段筛选，点击表格中的某一行即可缩小范围。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgGate.title', $json$"组织中的“把关”标签页"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgGate.detail', $json$"组织项目的计分板以及入口和出口两道关卡。该标签页与“统计”共用筛选：切换标签页会保留所选范围，打开其他组织则会重置。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.usernameOnce.title', $json$"用户名只能设置一次"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.usernameOnce.detail', $json$"首次保存个人资料后，用户名即被锁定。表单会在保存前提醒你，之后该字段为只读。跳过个人资料步骤不会锁定用户名。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgPolicyDefaults.title', $json$"新组织自带默认策略"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgPolicyDefaults.detail', $json$"创建组织时，“从不读取”和“仅限本地模型”会预先填入安全的默认值，“策略”标签页打开即可调整。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentIcons.title', $json$"正确的 Claude Code 和 Codex 图标"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentIcons.detail', $json$"代理标签页之前显示的是旧图标。现在显示官方的 Claude Code 图标和最新的 Codex 图标，任何尺寸都清晰。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentExecutable.title', $json$"“可执行文件”字段已锁定"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentExecutable.detail', $json$"在 Claude、Codex、Copilot 和 Cursor 标签页中，可执行文件由 JayV 自行设置：该字段已禁用并附有说明，“验证”按钮仍可使用。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateBanner.title', $json$"顶部的新版本提示"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateBanner.detail', $json$"有新版本发布时，每个界面顶部都会出现提示栏，包含“更新内容”（版本说明）和“立即更新”。关闭提示栏只会隐藏该版本的提示。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateNotification.title', $json$"铃铛中也会提示新版本"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateNotification.detail', $json$"每个新版本都会在铃铛中生成一条通知（每个版本一条），点击即可直接打开更新窗口。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateNoAutoInstall.title', $json$"更新不再打断你的工作"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateNoAutoInstall.detail', $json$"以前 JayV 打开时一发现新版本就会立即安装，并弹出进度窗口。现在启动时和每 30 分钟的检查只会提醒你，由你决定何时更新。没有网络时，检查不会打扰你。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgFolderRemove.title', $json$"移除组织文件夹"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgFolderRemove.detail', $json$"在“仓库”标签页中，“移除”按钮会在确认后让 JayV 忘记这台电脑上的组织文件夹。磁盘上的内容不会被删除：克隆和项目保持原位，下次克隆时会重新询问文件夹。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectDeletion.title', $json$"删除项目会在所有地方删除其聊天"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectDeletion.detail', $json$"已删除项目的聊天在同步后会在另一台电脑上重新出现。现在删除操作也会在服务器上同步到该项目的聊天、消息和检查。"$json$::jsonb),
  ('hi', 'whatsNew.title', $json$"JayV {version} में नया क्या है"$json$::jsonb),
  ('hi', 'whatsNew.description', $json$"हर संस्करण में जो कुछ बदला, नई सुविधाओं और सुधारों में बँटा हुआ।"$json$::jsonb),
  ('hi', 'whatsNew.description.updated', $json$"JayV संस्करण {previous} से {version} पर अपडेट हो गया है। देखें क्या बदला।"$json$::jsonb),
  ('hi', 'whatsNew.description.installed', $json$"आप JayV {version} पर हैं। देखें यह संस्करण क्या लाया।"$json$::jsonb),
  ('hi', 'whatsNew.features', $json$"नई सुविधाएँ"$json$::jsonb),
  ('hi', 'whatsNew.fixes', $json$"सुधार"$json$::jsonb),
  ('hi', 'whatsNew.version', $json$"संस्करण {version}"$json$::jsonb),
  ('hi', 'whatsNew.installed', $json$"इंस्टॉल है"$json$::jsonb),
  ('hi', 'whatsNew.showAll', $json$"पिछले संस्करण देखें"$json$::jsonb),
  ('hi', 'whatsNew.done', $json$"समझ गया"$json$::jsonb),
  ('hi', 'app.whatsNew', $json$"नया क्या है"$json$::jsonb),
  ('hi', 'whatsNew.item.whatsNew.title', $json$"नया क्या है विंडो"$json$::jsonb),
  ('hi', 'whatsNew.item.whatsNew.detail', $json$"हर अपडेट के बाद JayV यह विंडो खोलता है, जिसमें इस कंप्यूटर पर आपके देखे गए पिछले संस्करण के बाद से हुए बदलाव नई सुविधाओं और सुधारों में बँटे होते हैं। यह हर संस्करण में एक बार दिखती है और \"समझ गया\" पर क्लिक करने से बंद हो जाती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.whatsNewHistory.title', $json$"कभी भी संस्करण इतिहास"$json$::jsonb),
  ('hi', 'whatsNew.item.whatsNewHistory.detail', $json$"सेटिंग्स › ऐप › संस्करण में \"नया क्या है\" बटन यह विंडो फिर से खोलता है: सबसे ऊपर इंस्टॉल संस्करण और नीचे पिछले संस्करणों का इतिहास।"$json$::jsonb),
  ('hi', 'whatsNew.item.fixedSidebar.title', $json$"स्क्रॉल करते समय साइडबार और हेडर अपनी जगह रहते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.fixedSidebar.detail', $json$"प्रोजेक्ट, संगठन, संगठन पेज, सेटिंग्स, प्रोफ़ाइल, आँकड़े और सिस्टम में साइडबार सामग्री के साथ ऊपर खिसक जाता था। अब सिर्फ़ पेज की सामग्री स्क्रॉल होती है; साइडबार और हेडर विंडो की ऊँचाई में हमेशा दिखते रहते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChat.title', $json$"सभी रिपॉज़िटरी पर संगठन चैट"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChat.detail', $json$"संगठन पेज पर नया \"संगठन चैट\" बटन है, जो इस कंप्यूटर पर संगठन फ़ोल्डर का उपयोग करके एक साथ उसकी सभी रिपॉज़िटरी पर काम करने वाला चैट खोलता है। फ़ोल्डर न हो तो JayV पहले उसे चुनने को कहता है। एजेंट, इंडेक्स और गेट उसके अंदर के सभी क्लोन देखते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChatReach.title', $json$"देखें कौन-सी रिपॉज़िटरी चैट में आती हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChatReach.detail', $json$"खोलने से पहले एक विंडो फ़ोल्डर दिखाती है (\"बदलें\" बटन के साथ) और रिपॉज़िटरी को बाँटती है: इस चैट में, किसी दूसरे फ़ोल्डर में क्लोन होने से बाहर, और इस कंप्यूटर पर न होने से बाहर।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChatPolicy.title', $json$"संगठन चैट में सबसे सख़्त नीति लागू होती है"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChatPolicy.detail', $json$"संगठन चैट संगठन की LLM नीति और उसकी हर रिपॉज़िटरी की नीति के साथ चलता है, और उनमें से सबसे सख़्त नियम हमेशा लागू होता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChatDashboard.title', $json$"आँकड़ों और गेट में संगठन चैट"$json$::jsonb),
  ('hi', 'whatsNew.item.orgChatDashboard.detail', $json$"संगठन चैट का उपयोग अब संगठन के आँकड़े और गेट टैब में तुरंत दिखता है, सर्वर के प्रोजेक्ट को जोड़ने का इंतज़ार किए बिना।"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactor.title', $json$"दो-चरणीय प्रमाणीकरण"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactor.detail', $json$"प्रोफ़ाइल › सुरक्षा में ऑथेंटिकेटर ऐप चालू करें: QR कोड स्कैन करें (या 4-4 के समूहों में दिखाई गई कुंजी लिखें) और पहले कोड से पुष्टि करें। पुष्टि के बाद ही यह लागू होता है, और \"रद्द करें\" अधूरा सेटअप हटा देता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactorSignIn.title', $json$"हर साइन-इन पर 6 अंकों का कोड"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactorSignIn.detail', $json$"ऐप चालू होने पर पासवर्ड, GitHub, GitLab, Bitbucket या पासवर्ड रिकवरी लिंक के बाद हर साइन-इन कोड माँगता है। जो सेशन अभी दूसरा चरण पार नहीं कर पाया, डेटाबेस उसके अनुरोध अस्वीकार करता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactorProtect.title', $json$"सुरक्षा बंद करने पर कोड माँगा जाता है"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactorProtect.detail', $json$"दूसरा चरण हटाने के लिए ऐप का मौजूदा कोड डालना ज़रूरी है: खुला छूटा सेशन खाते की सुरक्षा हटाने के लिए काफ़ी नहीं है।"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactorPassword.title', $json$"ऐप चालू होने पर पासवर्ड बदलना"$json$::jsonb),
  ('hi', 'whatsNew.item.twoFactorPassword.detail', $json$"दूसरा चरण चालू होने पर पासवर्ड बदलने का फ़ॉर्म ऐप का कोड भी माँगता है। कोड गलत होने पर JayV सेशन अधूरा छोड़ने के बजाय दूसरा चरण फिर से माँगता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.lockdown.title', $json$"इंस्टॉल ऐप जाँच के लिए बंद"$json$::jsonb),
  ('hi', 'whatsNew.item.lockdown.detail', $json$"इंस्टॉल ऐप में राइट-क्लिक मेन्यू (टेक्स्ट फ़ील्ड को छोड़कर, जहाँ कॉपी-पेस्ट चलता है) और डेवलपर टूल, सोर्स देखना, सेव, प्रिंट और रीलोड के शॉर्टकट बंद हैं, और रिमोट इंस्पेक्टर खोलने वाले वेरिएबल शुरू होते ही हटा दिए जाते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.safeConnections.title', $json$"ज़्यादा सुरक्षित कनेक्शन"$json$::jsonb),
  ('hi', 'whatsNew.item.safeConnections.detail', $json$"JayV का हर अनुरोध सिर्फ़ बिल्ट-इन सर्टिफ़िकेट अथॉरिटी पर भरोसा करता है और TLS 1.2 या नया माँगता है: सिस्टम में अपना सर्टिफ़िकेट डालकर HTTPS पकड़ने वाला प्रॉक्सी अस्वीकार होता है, जबकि सामान्य प्रॉक्सी काम करता रहता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.realtimeNotifications.title', $json$"रीयल-टाइम सूचनाएँ फिर से चालू"$json$::jsonb),
  ('hi', 'whatsNew.item.realtimeNotifications.detail', $json$"कंटेंट सिक्योरिटी पॉलिसी Supabase से सुरक्षित कनेक्शन (wss) रोक रही थी, इसलिए घंटी में सूचनाएँ तुरंत नहीं आती थीं। अब इसकी अनुमति है, साथ ही दूसरे चरण के QR कोड की एम्बेडेड इमेज की भी।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgStats.title', $json$"संगठन में आँकड़े टैब"$json$::jsonb),
  ('hi', 'whatsNew.item.orgStats.detail', $json$"सारांश, चार्ट, Jev पैनल और टूल, मॉडल, प्रोजेक्ट व चैट के हिसाब से टेबल, जिनमें सिर्फ़ इस कंप्यूटर के वे प्रोजेक्ट जुड़ते हैं जो संगठन के हैं। प्रोजेक्ट, चैट और अवधि के फ़िल्टर हैं, और टेबल की किसी पंक्ति पर क्लिक करने से दृश्य सीमित हो जाता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgGate.title', $json$"संगठन में गेट टैब"$json$::jsonb),
  ('hi', 'whatsNew.item.orgGate.detail', $json$"संगठन के प्रोजेक्ट का स्कोरबोर्ड और दोनों गेट, प्रवेश और निकास। यह टैब आँकड़ों के साथ फ़िल्टर साझा करता है: टैब बदलने पर चयन बना रहता है, और दूसरा संगठन खोलने पर रीसेट हो जाता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.usernameOnce.title', $json$"यूज़रनेम एक बार तय"$json$::jsonb),
  ('hi', 'whatsNew.item.usernameOnce.detail', $json$"पहली बार प्रोफ़ाइल सेव करने के बाद यूज़रनेम लॉक हो जाता है। फ़ॉर्म सेव करने से पहले चेतावनी देता है, और उसके बाद फ़ील्ड सिर्फ़ पढ़ने के लिए रहता है। प्रोफ़ाइल चरण छोड़ने से नाम लॉक नहीं होता।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgPolicyDefaults.title', $json$"नया संगठन नीति के साथ शुरू होता है"$json$::jsonb),
  ('hi', 'whatsNew.item.orgPolicyDefaults.detail', $json$"संगठन बनाते समय \"कभी न पढ़ें\" और \"सिर्फ़ लोकल मॉडल\" सुरक्षित डिफ़ॉल्ट से भरे आते हैं, और नीति टैब बदलाव के लिए तैयार खुलता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentIcons.title', $json$"Claude Code और Codex के सही आइकन"$json$::jsonb),
  ('hi', 'whatsNew.item.agentIcons.detail', $json$"एजेंट टैब में पुराने चित्र दिखते थे। अब Claude Code का आधिकारिक आइकन और Codex का मौजूदा आइकन दिखते हैं, हर आकार में साफ़।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentExecutable.title', $json$"एक्ज़ीक्यूटेबल फ़ील्ड लॉक"$json$::jsonb),
  ('hi', 'whatsNew.item.agentExecutable.detail', $json$"Claude, Codex, Copilot और Cursor टैब में JayV खुद एक्ज़ीक्यूटेबल तय करता है: फ़ील्ड बंद रहता है, साथ में वजह बताने वाला संकेत होता है, और \"जाँचें\" बटन काम करता रहता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updateBanner.title', $json$"ऊपर नए संस्करण की सूचना"$json$::jsonb),
  ('hi', 'whatsNew.item.updateBanner.detail', $json$"नया संस्करण आने पर हर स्क्रीन के ऊपर एक पट्टी दिखती है, जिसमें \"क्या बदला है\" (रिलीज़ नोट्स) और \"अभी अपडेट करें\" होते हैं। पट्टी बंद करने से सिर्फ़ उसी संस्करण की सूचना छिपती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updateNotification.title', $json$"घंटी में भी नया संस्करण"$json$::jsonb),
  ('hi', 'whatsNew.item.updateNotification.detail', $json$"हर नया संस्करण घंटी में एक सूचना बनता है, हर संस्करण के लिए सिर्फ़ एक, जो सीधे अपडेट विंडो पर ले जाती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updateNoAutoInstall.title', $json$"अपडेट अब आपके काम में रुकावट नहीं डालते"$json$::jsonb),
  ('hi', 'whatsNew.item.updateNoAutoInstall.detail', $json$"पहले JayV खुलते ही नया संस्करण ढूँढकर तुरंत इंस्टॉल कर देता था, प्रगति विंडो सामने रखकर। अब खुलते समय और हर 30 मिनट की जाँच सिर्फ़ सूचना देती है: अपडेट का समय आप चुनते हैं। नेटवर्क न हो तो जाँच चुप रहती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgFolderRemove.title', $json$"संगठन फ़ोल्डर हटाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.orgFolderRemove.detail', $json$"रिपॉज़िटरी टैब में \"हटाएँ\" बटन पुष्टि के बाद JayV को इस कंप्यूटर पर संगठन फ़ोल्डर भुला देता है। डिस्क से कुछ नहीं मिटता: क्लोन और प्रोजेक्ट वहीं रहते हैं, और अगला क्लोन फ़ोल्डर फिर से पूछता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.projectDeletion.title', $json$"प्रोजेक्ट मिटाने पर उसके चैट हर जगह से हटते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.projectDeletion.detail', $json$"मिटाए गए प्रोजेक्ट के चैट सिंक के बाद दूसरे कंप्यूटर पर लौट आते थे। अब सर्वर पर भी प्रोजेक्ट के चैट, संदेश और जाँचें मिटती हैं।"$json$::jsonb),
  ('ar', 'whatsNew.title', $json$"الجديد في JayV {version}"$json$::jsonb),
  ('ar', 'whatsNew.description', $json$"كل ما تغيّر في كل إصدار، مقسّمًا إلى ميزات جديدة وإصلاحات."$json$::jsonb),
  ('ar', 'whatsNew.description.updated', $json$"تم تحديث JayV من الإصدار {previous} إلى {version}. إليك ما تغيّر."$json$::jsonb),
  ('ar', 'whatsNew.description.installed', $json$"أنت تستخدم JayV {version}. إليك ما جاء به هذا الإصدار."$json$::jsonb),
  ('ar', 'whatsNew.features', $json$"ميزات جديدة"$json$::jsonb),
  ('ar', 'whatsNew.fixes', $json$"إصلاحات"$json$::jsonb),
  ('ar', 'whatsNew.version', $json$"الإصدار {version}"$json$::jsonb),
  ('ar', 'whatsNew.installed', $json$"مثبّت"$json$::jsonb),
  ('ar', 'whatsNew.showAll', $json$"عرض الإصدارات السابقة"$json$::jsonb),
  ('ar', 'whatsNew.done', $json$"حسنًا"$json$::jsonb),
  ('ar', 'app.whatsNew', $json$"الجديد"$json$::jsonb),
  ('ar', 'whatsNew.item.whatsNew.title', $json$"نافذة الجديد"$json$::jsonb),
  ('ar', 'whatsNew.item.whatsNew.detail', $json$"بعد كل تحديث، يفتح JayV هذه النافذة بما تغيّر منذ آخر إصدار رأيته على هذا الحاسوب، مقسّمًا إلى ميزات جديدة وإصلاحات. تظهر مرة واحدة لكل إصدار وتُغلق عند النقر على \"حسنًا\"."$json$::jsonb),
  ('ar', 'whatsNew.item.whatsNewHistory.title', $json$"سجل الإصدارات في أي وقت"$json$::jsonb),
  ('ar', 'whatsNew.item.whatsNewHistory.detail', $json$"في الإعدادات › التطبيق › الإصدار، يعيد زر \"الجديد\" فتح النافذة، مع الإصدار المثبّت في الأعلى وسجل الإصدارات السابقة تحته."$json$::jsonb),
  ('ar', 'whatsNew.item.fixedSidebar.title', $json$"الشريط الجانبي والرأس ثابتان عند التمرير"$json$::jsonb),
  ('ar', 'whatsNew.item.fixedSidebar.detail', $json$"في المشاريع والمؤسسات وصفحة المؤسسة والإعدادات والملف الشخصي والإحصاءات والنظام، كان الشريط الجانبي يتحرك مع المحتوى. الآن يتمرّر محتوى الصفحة فقط، ويبقى الشريط الجانبي والرأس بارتفاع النافذة وظاهرين دائمًا."$json$::jsonb),
  ('ar', 'whatsNew.item.orgChat.title', $json$"دردشة المؤسسة عبر كل المستودعات"$json$::jsonb),
  ('ar', 'whatsNew.item.orgChat.detail', $json$"أصبح في صفحة المؤسسة زر \"دردشة المؤسسة\" الذي يفتح دردشة تعمل على كل مستودعاتها معًا، باستخدام مجلد المؤسسة على هذا الحاسوب. وإن لم يكن هناك مجلد، يطلب JayV اختياره أولًا. يرى الوكيل والفهرس والبوابة كل النسخ الموجودة داخله."$json$::jsonb),
  ('ar', 'whatsNew.item.orgChatReach.title', $json$"اعرف أي المستودعات تدخل الدردشة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgChatReach.detail', $json$"قبل الفتح، تعرض نافذة المجلد (مع زر \"تغيير\") وتقسّم المستودعات إلى: في هذه الدردشة، ومستبعدة لأنها منسوخة في مجلد آخر، ومستبعدة لأنها ليست على هذا الحاسوب."$json$::jsonb),
  ('ar', 'whatsNew.item.orgChatPolicy.title', $json$"تُطبَّق السياسة الأشد في دردشة المؤسسة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgChatPolicy.detail', $json$"تعمل دردشة المؤسسة وفق سياسة LLM للمؤسسة مع سياسة كل مستودع من مستودعاتها، وتسري دائمًا القاعدة الأشد بينها."$json$::jsonb),
  ('ar', 'whatsNew.item.orgChatDashboard.title', $json$"دردشة المؤسسة في الإحصاءات والبوابة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgChatDashboard.detail', $json$"يظهر استخدام دردشة المؤسسة الآن فورًا في تبويبي الإحصاءات والبوابة للمؤسسة، دون انتظار أن يربط الخادم المشروع بها."$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactor.title', $json$"المصادقة الثنائية"$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactor.detail', $json$"في الملف الشخصي › الأمان، فعّل تطبيق مصادقة: امسح رمز QR (أو اكتب المفتاح المعروض في مجموعات من 4) وأكّد بأول رمز. لا يُعتمد العامل إلا بعد هذا التأكيد، و\"إلغاء\" يحذف الإعداد غير المكتمل."$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactorSignIn.title', $json$"رمز من 6 أرقام عند كل تسجيل دخول"$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactorSignIn.detail', $json$"مع تفعيل التطبيق، يطلب كل تسجيل دخول الرمز بعد كلمة المرور أو GitHub أو GitLab أو Bitbucket أو رابط استعادة كلمة المرور. وترفض قاعدة البيانات طلبات أي جلسة لم تجتز العامل الثاني بعد."$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactorProtect.title', $json$"إيقاف الحماية يتطلب رمزًا"$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactorProtect.detail', $json$"لإزالة العامل الثاني يلزم إدخال رمز حالي من التطبيق: الجلسة المنسية المفتوحة لا تكفي لإزالة حماية الحساب."$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactorPassword.title', $json$"تغيير كلمة المرور مع تفعيل التطبيق"$json$::jsonb),
  ('ar', 'whatsNew.item.twoFactorPassword.detail', $json$"مع تفعيل العامل الثاني، يطلب نموذج تغيير كلمة المرور رمز التطبيق أيضًا. وإذا فشل الرمز، يطلب JayV العامل الثاني من جديد بدل ترك الجلسة ناقصة."$json$::jsonb),
  ('ar', 'whatsNew.item.lockdown.title', $json$"التطبيق المثبّت مغلق أمام الفحص"$json$::jsonb),
  ('ar', 'whatsNew.item.lockdown.detail', $json$"في التطبيق المثبّت، أُوقفت قائمة النقر بالزر الأيمن (خارج حقول النص التي تحتفظ بالنسخ واللصق) واختصارات أدوات المطوّر وعرض المصدر والحفظ والطباعة وإعادة التحميل، وتُمسح عند التشغيل المتغيرات التي قد تفتح أداة فحص عن بُعد."$json$::jsonb),
  ('ar', 'whatsNew.item.safeConnections.title', $json$"اتصالات أكثر أمانًا"$json$::jsonb),
  ('ar', 'whatsNew.item.safeConnections.detail', $json$"كل طلب يرسله JayV يثق فقط بسلطات الشهادات المضمّنة ويتطلب TLS 1.2 أو أحدث: يُرفض الوكيل الذي يعترض HTTPS بتثبيت شهادته الخاصة في النظام، بينما يستمر الوكيل العادي في العمل."$json$::jsonb),
  ('ar', 'whatsNew.item.realtimeNotifications.title', $json$"عادت الإشعارات الفورية"$json$::jsonb),
  ('ar', 'whatsNew.item.realtimeNotifications.detail', $json$"كانت سياسة أمان المحتوى تحظر الاتصال الآمن (wss) مع Supabase، فلم يكن الجرس يتلقى الإشعارات فورًا. أصبح مسموحًا الآن، وكذلك الصور المضمّنة التي يستخدمها رمز QR للعامل الثاني."$json$::jsonb),
  ('ar', 'whatsNew.item.orgStats.title', $json$"تبويب الإحصاءات في المؤسسة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgStats.detail', $json$"ملخص ورسوم بيانية ولوحة Jev وجداول حسب الأداة والنموذج والمشروع والدردشة، تجمع فقط مشاريع هذا الحاسوب التابعة للمؤسسة. تتوفر عوامل تصفية للمشروع والدردشة والفترة، والنقر على صف في الجداول يضيّق العرض."$json$::jsonb),
  ('ar', 'whatsNew.item.orgGate.title', $json$"تبويب البوابة في المؤسسة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgGate.detail', $json$"لوحة النتائج والبوابتان، الدخول والخروج، لمشاريع المؤسسة. يشارك التبويب عامل التصفية مع الإحصاءات: تبديل التبويب يحتفظ بالتحديد، وفتح مؤسسة أخرى يعيد ضبطه."$json$::jsonb),
  ('ar', 'whatsNew.item.usernameOnce.title', $json$"اسم المستخدم يُحدَّد مرة واحدة"$json$::jsonb),
  ('ar', 'whatsNew.item.usernameOnce.detail', $json$"يُثبَّت اسم المستخدم بعد أول حفظ للملف الشخصي. ينبّهك النموذج قبل الحفظ، وبعد ذلك يصبح الحقل للقراءة فقط. تخطي خطوة الملف الشخصي لا يثبّت الاسم."$json$::jsonb),
  ('ar', 'whatsNew.item.orgPolicyDefaults.title', $json$"المؤسسات الجديدة تبدأ بسياسة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgPolicyDefaults.detail', $json$"عند إنشاء مؤسسة، يأتي حقلا \"لا تقرأ أبدًا\" و\"للنماذج المحلية فقط\" معبّأين بقيم افتراضية آمنة، ويُفتح تبويب السياسة جاهزًا للتعديل."$json$::jsonb),
  ('ar', 'whatsNew.item.agentIcons.title', $json$"أيقونات Claude Code وCodex الصحيحة"$json$::jsonb),
  ('ar', 'whatsNew.item.agentIcons.detail', $json$"كانت تبويبات الوكلاء تعرض رسومات قديمة. الآن تظهر أيقونة Claude Code الرسمية وأيقونة Codex الحالية، واضحتين بأي حجم."$json$::jsonb),
  ('ar', 'whatsNew.item.agentExecutable.title', $json$"حقل الملف التنفيذي مقفل"$json$::jsonb),
  ('ar', 'whatsNew.item.agentExecutable.detail', $json$"في تبويبات Claude وCodex وCopilot وCursor، يحدّد JayV الملف التنفيذي بنفسه: الحقل معطّل مع تلميح يشرح السبب، ويستمر زر \"تحقق\" في العمل."$json$::jsonb),
  ('ar', 'whatsNew.item.updateBanner.title', $json$"تنبيه بالإصدار الجديد في الأعلى"$json$::jsonb),
  ('ar', 'whatsNew.item.updateBanner.detail', $json$"عند صدور إصدار جديد، يظهر شريط أعلى كل شاشة فيه \"ما الذي تغيّر\" (ملاحظات الإصدار) و\"حدّث الآن\". إغلاق الشريط يخفي التنبيه لذلك الإصدار فقط."$json$::jsonb),
  ('ar', 'whatsNew.item.updateNotification.title', $json$"الإصدار الجديد في الجرس أيضًا"$json$::jsonb),
  ('ar', 'whatsNew.item.updateNotification.detail', $json$"يصبح كل إصدار جديد إشعارًا في الجرس، واحدًا فقط لكل إصدار، يأخذك مباشرة إلى نافذة التحديث."$json$::jsonb),
  ('ar', 'whatsNew.item.updateNoAutoInstall.title', $json$"التحديثات لم تعد تقاطع عملك"$json$::jsonb),
  ('ar', 'whatsNew.item.updateNoAutoInstall.detail', $json$"كان JayV يجد الإصدار الجديد عند فتحه ويثبّته فورًا مع نافذة التقدم في الواجهة. الآن الفحص، عند الفتح وكل 30 دقيقة، ينبّهك فقط: أنت تختار وقت التحديث. وبدون شبكة يبقى الفحص صامتًا."$json$::jsonb),
  ('ar', 'whatsNew.item.orgFolderRemove.title', $json$"إزالة مجلد المؤسسة"$json$::jsonb),
  ('ar', 'whatsNew.item.orgFolderRemove.detail', $json$"في تبويب المستودعات، يجعل زر \"إزالة\" JayV ينسى مجلد المؤسسة على هذا الحاسوب بعد التأكيد. لا يُحذف شيء من القرص: تبقى النسخ والمشاريع في مكانها، ويسأل النسخ التالي عن المجلد من جديد."$json$::jsonb),
  ('ar', 'whatsNew.item.projectDeletion.title', $json$"حذف مشروع يزيل دردشاته في كل مكان"$json$::jsonb),
  ('ar', 'whatsNew.item.projectDeletion.detail', $json$"كانت دردشات المشروع المحذوف تعود على حاسوب آخر بعد المزامنة. الآن يمتد الحذف على الخادم أيضًا إلى دردشات المشروع ورسائله وفحوصه."$json$::jsonb),
  ('fr', 'whatsNew.title', $json$"Nouveautés de JayV {version}"$json$::jsonb),
  ('fr', 'whatsNew.description', $json$"Tout ce qui a changé dans chaque version, réparti entre nouveautés et correctifs."$json$::jsonb),
  ('fr', 'whatsNew.description.updated', $json$"JayV est passé de la version {previous} à la {version}. Voici ce qui a changé."$json$::jsonb),
  ('fr', 'whatsNew.description.installed', $json$"Vous utilisez JayV {version}. Voici ce que cette version apporte."$json$::jsonb),
  ('fr', 'whatsNew.features', $json$"Nouveautés"$json$::jsonb),
  ('fr', 'whatsNew.fixes', $json$"Correctifs"$json$::jsonb),
  ('fr', 'whatsNew.version', $json$"Version {version}"$json$::jsonb),
  ('fr', 'whatsNew.installed', $json$"Installée"$json$::jsonb),
  ('fr', 'whatsNew.showAll', $json$"Voir les versions précédentes"$json$::jsonb),
  ('fr', 'whatsNew.done', $json$"J’ai compris"$json$::jsonb),
  ('fr', 'app.whatsNew', $json$"Nouveautés"$json$::jsonb),
  ('fr', 'whatsNew.item.whatsNew.title', $json$"Fenêtre des nouveautés"$json$::jsonb),
  ('fr', 'whatsNew.item.whatsNew.detail', $json$"Après chaque mise à jour, JayV ouvre cette fenêtre avec ce qui a changé depuis la dernière version vue sur cet ordinateur, réparti entre nouveautés et correctifs. Elle s’affiche une fois par version et disparaît quand vous cliquez sur J’ai compris."$json$::jsonb),
  ('fr', 'whatsNew.item.whatsNewHistory.title', $json$"Historique des versions à tout moment"$json$::jsonb),
  ('fr', 'whatsNew.item.whatsNewHistory.detail', $json$"Dans Configuration › Application › Version, le bouton Nouveautés rouvre la fenêtre, avec la version installée en haut et l’historique des précédentes en dessous."$json$::jsonb),
  ('fr', 'whatsNew.item.fixedSidebar.title', $json$"Barre latérale et en-tête fixes au défilement"$json$::jsonb),
  ('fr', 'whatsNew.item.fixedSidebar.detail', $json$"Dans Projets, Organisations, la page de l’organisation, Paramètres, Profil, Statistiques et Système, la barre latérale défilait avec le contenu. Désormais seul le contenu défile ; la barre latérale et l’en-tête gardent la hauteur de la fenêtre et restent visibles."$json$::jsonb),
  ('fr', 'whatsNew.item.orgChat.title', $json$"Chat de l’organisation sur tous les dépôts"$json$::jsonb),
  ('fr', 'whatsNew.item.orgChat.detail', $json$"La page de l’organisation propose un nouveau bouton Chat de l’organisation, qui ouvre un chat travaillant sur tous ses dépôts à la fois, à partir du dossier de l’organisation sur cet ordinateur. Sans dossier, JayV en demande un d’abord. L’agent, l’index et le contrôle voient tous les clones qu’il contient."$json$::jsonb),
  ('fr', 'whatsNew.item.orgChatReach.title', $json$"Voyez quels dépôts entrent dans le chat"$json$::jsonb),
  ('fr', 'whatsNew.item.orgChatReach.detail', $json$"Avant l’ouverture, une fenêtre montre le dossier (avec un bouton Changer) et classe les dépôts : dans ce chat, exclus car clonés dans un autre dossier, et exclus car absents de cet ordinateur."$json$::jsonb),
  ('fr', 'whatsNew.item.orgChatPolicy.title', $json$"La politique la plus stricte s’applique au chat de l’organisation"$json$::jsonb),
  ('fr', 'whatsNew.item.orgChatPolicy.detail', $json$"Le chat de l’organisation suit la politique LLM de l’organisation ainsi que celle de chacun de ses dépôts, et la règle la plus stricte l’emporte toujours."$json$::jsonb),
  ('fr', 'whatsNew.item.orgChatDashboard.title', $json$"Chat de l’organisation dans Statistiques et Contrôle"$json$::jsonb),
  ('fr', 'whatsNew.item.orgChatDashboard.detail', $json$"L’utilisation du chat de l’organisation apparaît désormais tout de suite dans ses onglets Statistiques et Contrôle, sans attendre que le serveur y rattache le projet."$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactor.title', $json$"Authentification à deux facteurs"$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactor.detail', $json$"Dans Profil › Sécurité, activez une application d’authentification : scannez le QR code (ou saisissez la clé, affichée par blocs de 4) et confirmez avec le premier code. Le facteur ne compte qu’après cette confirmation, et Annuler supprime une configuration inachevée."$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactorSignIn.title', $json$"Un code à 6 chiffres à chaque connexion"$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactorSignIn.detail', $json$"Avec l’application activée, chaque connexion demande le code après le mot de passe, GitHub, GitLab, Bitbucket ou le lien de récupération du mot de passe. La base de données refuse les requêtes d’une session qui n’a pas encore passé le second facteur."$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactorProtect.title', $json$"Désactiver la protection demande un code"$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactorProtect.detail', $json$"Retirer le second facteur exige un code actuel de l’application : une session restée ouverte ne suffit pas à lever la protection du compte."$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactorPassword.title', $json$"Changer de mot de passe avec l’application activée"$json$::jsonb),
  ('fr', 'whatsNew.item.twoFactorPassword.detail', $json$"Avec le second facteur activé, le formulaire de changement de mot de passe demande aussi le code de l’application. Si le code échoue, JayV redemande le second facteur au lieu de laisser la session à moitié ouverte."$json$::jsonb),
  ('fr', 'whatsNew.item.lockdown.title', $json$"Application installée fermée à l’inspection"$json$::jsonb),
  ('fr', 'whatsNew.item.lockdown.detail', $json$"Dans l’application installée, le menu du clic droit (hors champs de texte, qui gardent copier-coller) et les raccourcis des outils de développement, du code source, de l’enregistrement, de l’impression et du rechargement sont désactivés, et les variables qui ouvriraient un inspecteur distant sont effacées au démarrage."$json$::jsonb),
  ('fr', 'whatsNew.item.safeConnections.title', $json$"Connexions plus sûres"$json$::jsonb),
  ('fr', 'whatsNew.item.safeConnections.detail', $json$"Chaque requête de JayV ne fait confiance qu’aux autorités de certification intégrées et exige TLS 1.2 ou plus : un proxy qui intercepte le HTTPS en installant son propre certificat sur le système est refusé, tandis qu’un proxy ordinaire continue de fonctionner."$json$::jsonb),
  ('fr', 'whatsNew.item.realtimeNotifications.title', $json$"Les notifications en temps réel sont de retour"$json$::jsonb),
  ('fr', 'whatsNew.item.realtimeNotifications.detail', $json$"La politique de sécurité du contenu bloquait la connexion sécurisée (wss) à Supabase, et la cloche ne recevait pas les notifications en direct. Elle est maintenant autorisée, tout comme les images intégrées du QR code du second facteur."$json$::jsonb),
  ('fr', 'whatsNew.item.orgStats.title', $json$"Onglet Statistiques dans l’organisation"$json$::jsonb),
  ('fr', 'whatsNew.item.orgStats.detail', $json$"Résumé, graphiques, panneau de Jev et tableaux par outil, modèle, projet et chat, en ne comptant que les projets de cet ordinateur qui appartiennent à l’organisation. Des filtres par projet, chat et période sont disponibles, et cliquer sur une ligne d’un tableau resserre la vue."$json$::jsonb),
  ('fr', 'whatsNew.item.orgGate.title', $json$"Onglet Contrôle dans l’organisation"$json$::jsonb),
  ('fr', 'whatsNew.item.orgGate.detail', $json$"Le tableau des scores et les deux portes, d’entrée et de sortie, pour les projets de l’organisation. L’onglet partage son filtre avec Statistiques : changer d’onglet conserve la sélection, ouvrir une autre organisation la réinitialise."$json$::jsonb),
  ('fr', 'whatsNew.item.usernameOnce.title', $json$"Nom d’utilisateur défini une seule fois"$json$::jsonb),
  ('fr', 'whatsNew.item.usernameOnce.detail', $json$"Le nom d’utilisateur est verrouillé après le premier enregistrement du profil. Le formulaire vous prévient avant, puis le champ passe en lecture seule. Passer l’étape du profil ne verrouille pas le nom."$json$::jsonb),
  ('fr', 'whatsNew.item.orgPolicyDefaults.title', $json$"Les nouvelles organisations démarrent avec une politique"$json$::jsonb),
  ('fr', 'whatsNew.item.orgPolicyDefaults.detail', $json$"À la création d’une organisation, Ne jamais lire et Modèles locaux uniquement sont déjà remplis avec des valeurs sûres, et l’onglet Politique s’ouvre prêt à être ajusté."$json$::jsonb),
  ('fr', 'whatsNew.item.agentIcons.title', $json$"Icônes correctes de Claude Code et Codex"$json$::jsonb),
  ('fr', 'whatsNew.item.agentIcons.detail', $json$"Les onglets des agents affichaient d’anciens dessins. Ils montrent maintenant l’icône officielle de Claude Code et l’icône actuelle de Codex, nettes à toutes les tailles."$json$::jsonb),
  ('fr', 'whatsNew.item.agentExecutable.title', $json$"Champ Exécutable verrouillé"$json$::jsonb),
  ('fr', 'whatsNew.item.agentExecutable.detail', $json$"Dans les onglets Claude, Codex, Copilot et Cursor, JayV définit lui-même l’exécutable : le champ est désactivé, avec une indication qui explique pourquoi, et le bouton Vérifier fonctionne toujours."$json$::jsonb),
  ('fr', 'whatsNew.item.updateBanner.title', $json$"Avis de nouvelle version en haut"$json$::jsonb),
  ('fr', 'whatsNew.item.updateBanner.detail', $json$"Quand une nouvelle version sort, une barre apparaît en haut de chaque écran avec Nouveautés (les notes de version) et Mettre à jour. Fermer la barre masque l’avis pour cette version uniquement."$json$::jsonb),
  ('fr', 'whatsNew.item.updateNotification.title', $json$"Nouvelle version aussi dans la cloche"$json$::jsonb),
  ('fr', 'whatsNew.item.updateNotification.detail', $json$"Chaque nouvelle version devient une notification dans la cloche, une seule par version, qui mène directement à la fenêtre de mise à jour."$json$::jsonb),
  ('fr', 'whatsNew.item.updateNoAutoInstall.title', $json$"Les mises à jour n’interrompent plus votre travail"$json$::jsonb),
  ('fr', 'whatsNew.item.updateNoAutoInstall.detail', $json$"Avant, JayV trouvait la nouvelle version à l’ouverture et l’installait aussitôt, avec la fenêtre de progression au premier plan. Désormais la vérification, au démarrage et toutes les 30 minutes, ne fait que prévenir : vous choisissez quand mettre à jour. Sans réseau, elle reste silencieuse."$json$::jsonb),
  ('fr', 'whatsNew.item.orgFolderRemove.title', $json$"Retirer le dossier de l’organisation"$json$::jsonb),
  ('fr', 'whatsNew.item.orgFolderRemove.detail', $json$"Dans l’onglet Dépôts, le bouton Retirer fait oublier à JayV le dossier de l’organisation sur cet ordinateur, après confirmation. Rien n’est supprimé du disque : les clones et les projets restent en place, et le prochain clone redemande un dossier."$json$::jsonb),
  ('fr', 'whatsNew.item.projectDeletion.title', $json$"Supprimer un projet efface ses chats partout"$json$::jsonb),
  ('fr', 'whatsNew.item.projectDeletion.detail', $json$"Les chats d’un projet supprimé réapparaissaient sur un autre ordinateur après la synchronisation. Désormais, la suppression s’applique aussi sur le serveur aux chats, messages et vérifications du projet."$json$::jsonb),
  ('ru', 'whatsNew.title', $json$"Что нового в JayV {version}"$json$::jsonb),
  ('ru', 'whatsNew.description', $json$"Все изменения в каждой версии: новые возможности и исправления."$json$::jsonb),
  ('ru', 'whatsNew.description.updated', $json$"JayV обновлён с версии {previous} до {version}. Вот что изменилось."$json$::jsonb),
  ('ru', 'whatsNew.description.installed', $json$"У вас JayV {version}. Вот что появилось в этой версии."$json$::jsonb),
  ('ru', 'whatsNew.features', $json$"Новые возможности"$json$::jsonb),
  ('ru', 'whatsNew.fixes', $json$"Исправления"$json$::jsonb),
  ('ru', 'whatsNew.version', $json$"Версия {version}"$json$::jsonb),
  ('ru', 'whatsNew.installed', $json$"Установлена"$json$::jsonb),
  ('ru', 'whatsNew.showAll', $json$"Показать предыдущие версии"$json$::jsonb),
  ('ru', 'whatsNew.done', $json$"Понятно"$json$::jsonb),
  ('ru', 'app.whatsNew', $json$"Что нового"$json$::jsonb),
  ('ru', 'whatsNew.item.whatsNew.title', $json$"Окно «Что нового»"$json$::jsonb),
  ('ru', 'whatsNew.item.whatsNew.detail', $json$"После каждого обновления JayV открывает это окно с изменениями со времени последней версии, которую вы видели на этом компьютере, — отдельно новые возможности и исправления. Оно показывается один раз для каждой версии и закрывается кнопкой «Понятно»."$json$::jsonb),
  ('ru', 'whatsNew.item.whatsNewHistory.title', $json$"История версий в любой момент"$json$::jsonb),
  ('ru', 'whatsNew.item.whatsNewHistory.detail', $json$"В разделе «Настройки › Приложение › Версия» кнопка «Что нового» снова открывает окно: сверху установленная версия, ниже история предыдущих."$json$::jsonb),
  ('ru', 'whatsNew.item.fixedSidebar.title', $json$"Боковая панель и заголовок не прокручиваются"$json$::jsonb),
  ('ru', 'whatsNew.item.fixedSidebar.detail', $json$"На страницах «Проекты», «Организации», странице организации, «Настройки», «Профиль», «Статистика» и «Система» боковая панель уезжала вместе с содержимым. Теперь прокручивается только содержимое страницы, а панель и заголовок занимают высоту окна и всегда на виду."$json$::jsonb),
  ('ru', 'whatsNew.item.orgChat.title', $json$"Чат организации по всем репозиториям"$json$::jsonb),
  ('ru', 'whatsNew.item.orgChat.detail', $json$"На странице организации появилась кнопка «Чат организации»: она открывает чат, который работает со всеми её репозиториями сразу, используя папку организации на этом компьютере. Если папки нет, JayV сначала попросит её выбрать. Агент, индекс и проверка видят все клоны внутри неё."$json$::jsonb),
  ('ru', 'whatsNew.item.orgChatReach.title', $json$"Видно, какие репозитории попадут в чат"$json$::jsonb),
  ('ru', 'whatsNew.item.orgChatReach.detail', $json$"Перед открытием окно показывает папку (с кнопкой «Сменить») и делит репозитории на: в этом чате, не вошедшие, потому что клонированы в другую папку, и не вошедшие, потому что их нет на этом компьютере."$json$::jsonb),
  ('ru', 'whatsNew.item.orgChatPolicy.title', $json$"В чате организации действует самая строгая политика"$json$::jsonb),
  ('ru', 'whatsNew.item.orgChatPolicy.detail', $json$"Чат организации работает по LLM-политике организации вместе с политикой каждого её репозитория, и всегда применяется самое строгое правило."$json$::jsonb),
  ('ru', 'whatsNew.item.orgChatDashboard.title', $json$"Чат организации в статистике и проверке"$json$::jsonb),
  ('ru', 'whatsNew.item.orgChatDashboard.detail', $json$"Использование чата организации теперь сразу видно на вкладках «Статистика» и «Проверка» организации, не дожидаясь, пока сервер привяжет к ней проект."$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactor.title', $json$"Двухфакторная аутентификация"$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactor.detail', $json$"В разделе «Профиль › Безопасность» включите приложение-аутентификатор: отсканируйте QR-код (или введите ключ, показанный блоками по 4 символа) и подтвердите первым кодом. Фактор начинает действовать только после подтверждения, а «Отмена» удаляет незавершённую настройку."$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactorSignIn.title', $json$"6-значный код при каждом входе"$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactorSignIn.detail', $json$"Когда приложение включено, каждый вход запрашивает код после пароля, GitHub, GitLab, Bitbucket или ссылки восстановления пароля. База данных отклоняет запросы сессии, которая ещё не прошла второй фактор."$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactorProtect.title', $json$"Для отключения защиты нужен код"$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactorProtect.detail', $json$"Чтобы убрать второй фактор, нужно ввести текущий код из приложения: забытой открытой сессии недостаточно, чтобы снять защиту с аккаунта."$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactorPassword.title', $json$"Смена пароля при включённом приложении"$json$::jsonb),
  ('ru', 'whatsNew.item.twoFactorPassword.detail', $json$"При включённом втором факторе форма смены пароля запрашивает и код из приложения. Если код не подошёл, JayV снова запрашивает второй фактор, а не оставляет сессию незавершённой."$json$::jsonb),
  ('ru', 'whatsNew.item.lockdown.title', $json$"Установленное приложение закрыто для инспекции"$json$::jsonb),
  ('ru', 'whatsNew.item.lockdown.detail', $json$"В установленном приложении отключены контекстное меню (кроме текстовых полей, где остаются копирование и вставка) и сочетания клавиш для инструментов разработчика, просмотра кода, сохранения, печати и перезагрузки страницы, а переменные, открывающие удалённый инспектор, очищаются при запуске."$json$::jsonb),
  ('ru', 'whatsNew.item.safeConnections.title', $json$"Более защищённые соединения"$json$::jsonb),
  ('ru', 'whatsNew.item.safeConnections.detail', $json$"Каждый запрос JayV доверяет только встроенным центрам сертификации и требует TLS 1.2 или новее: прокси, перехватывающий HTTPS через собственный сертификат в системе, отклоняется, а обычный прокси продолжает работать."$json$::jsonb),
  ('ru', 'whatsNew.item.realtimeNotifications.title', $json$"Уведомления в реальном времени снова работают"$json$::jsonb),
  ('ru', 'whatsNew.item.realtimeNotifications.detail', $json$"Политика безопасности контента блокировала защищённое соединение (wss) с Supabase, и колокольчик не получал уведомления сразу. Теперь оно разрешено, как и встроенные изображения для QR-кода второго фактора."$json$::jsonb),
  ('ru', 'whatsNew.item.orgStats.title', $json$"Вкладка «Статистика» в организации"$json$::jsonb),
  ('ru', 'whatsNew.item.orgStats.detail', $json$"Сводка, графики, панель Jev и таблицы по инструментам, моделям, проектам и чатам — только по проектам этого компьютера, которые принадлежат организации. Есть фильтры по проекту, чату и периоду, а клик по строке таблицы сужает обзор."$json$::jsonb),
  ('ru', 'whatsNew.item.orgGate.title', $json$"Вкладка «Проверка» в организации"$json$::jsonb),
  ('ru', 'whatsNew.item.orgGate.detail', $json$"Табло и оба шлюза — входной и выходной — для проектов организации. Вкладка использует общий фильтр со «Статистикой»: при переключении вкладок выбор сохраняется, а при открытии другой организации сбрасывается."$json$::jsonb),
  ('ru', 'whatsNew.item.usernameOnce.title', $json$"Имя пользователя задаётся один раз"$json$::jsonb),
  ('ru', 'whatsNew.item.usernameOnce.detail', $json$"Имя пользователя фиксируется после первого сохранения профиля. Форма предупреждает об этом заранее, а затем поле становится только для чтения. Если пропустить шаг профиля, имя не фиксируется."$json$::jsonb),
  ('ru', 'whatsNew.item.orgPolicyDefaults.title', $json$"Новые организации создаются с политикой"$json$::jsonb),
  ('ru', 'whatsNew.item.orgPolicyDefaults.detail', $json$"При создании организации поля «Никогда не читать» и «Только для локальных моделей» уже заполнены безопасными значениями, а вкладка «Политика» открывается готовой к настройке."$json$::jsonb),
  ('ru', 'whatsNew.item.agentIcons.title', $json$"Правильные значки Claude Code и Codex"$json$::jsonb),
  ('ru', 'whatsNew.item.agentIcons.detail', $json$"На вкладках агентов были старые рисунки. Теперь там официальный значок Claude Code и актуальный значок Codex, чёткие в любом размере."$json$::jsonb),
  ('ru', 'whatsNew.item.agentExecutable.title', $json$"Поле «Исполняемый файл» заблокировано"$json$::jsonb),
  ('ru', 'whatsNew.item.agentExecutable.detail', $json$"На вкладках Claude, Codex, Copilot и Cursor JayV сам задаёт исполняемый файл: поле отключено, рядом подсказка с объяснением, а кнопка «Проверить» по-прежнему работает."$json$::jsonb),
  ('ru', 'whatsNew.item.updateBanner.title', $json$"Уведомление о новой версии вверху"$json$::jsonb),
  ('ru', 'whatsNew.item.updateBanner.detail', $json$"Когда выходит новая версия, вверху любого экрана появляется полоса с кнопками «Что нового» (примечания к выпуску) и «Обновить сейчас». Если закрыть полосу, уведомление скроется только для этой версии."$json$::jsonb),
  ('ru', 'whatsNew.item.updateNotification.title', $json$"Новая версия и в колокольчике"$json$::jsonb),
  ('ru', 'whatsNew.item.updateNotification.detail', $json$"Каждая новая версия появляется в колокольчике одним уведомлением, которое сразу открывает окно обновления."$json$::jsonb),
  ('ru', 'whatsNew.item.updateNoAutoInstall.title', $json$"Обновления больше не прерывают работу"$json$::jsonb),
  ('ru', 'whatsNew.item.updateNoAutoInstall.detail', $json$"Раньше JayV при запуске находил новую версию и сразу её устанавливал, показывая окно прогресса поверх всего. Теперь проверка при запуске и каждые 30 минут только уведомляет — когда обновляться, решаете вы. Без сети проверка ничего не показывает."$json$::jsonb),
  ('ru', 'whatsNew.item.orgFolderRemove.title', $json$"Удаление папки организации"$json$::jsonb),
  ('ru', 'whatsNew.item.orgFolderRemove.detail', $json$"На вкладке «Репозитории» кнопка «Удалить» после подтверждения заставляет JayV забыть папку организации на этом компьютере. С диска ничего не удаляется: клоны и проекты остаются на месте, а при следующем клонировании папку спросят снова."$json$::jsonb),
  ('ru', 'whatsNew.item.projectDeletion.title', $json$"Удаление проекта удаляет его чаты везде"$json$::jsonb),
  ('ru', 'whatsNew.item.projectDeletion.detail', $json$"Чаты удалённого проекта возвращались на другом компьютере после синхронизации. Теперь удаление распространяется и на сервере — на чаты, сообщения и проверки проекта."$json$::jsonb),
  ('ja', 'whatsNew.title', $json$"JayV {version} の新機能"$json$::jsonb),
  ('ja', 'whatsNew.description', $json$"各バージョンの変更点を、新機能と修正に分けてまとめています。"$json$::jsonb),
  ('ja', 'whatsNew.description.updated', $json$"JayV はバージョン {previous} から {version} に更新されました。変更点は次のとおりです。"$json$::jsonb),
  ('ja', 'whatsNew.description.installed', $json$"JayV {version} を使用中です。このバージョンの内容は次のとおりです。"$json$::jsonb),
  ('ja', 'whatsNew.features', $json$"新機能"$json$::jsonb),
  ('ja', 'whatsNew.fixes', $json$"修正"$json$::jsonb),
  ('ja', 'whatsNew.version', $json$"バージョン {version}"$json$::jsonb),
  ('ja', 'whatsNew.installed', $json$"インストール済み"$json$::jsonb),
  ('ja', 'whatsNew.showAll', $json$"以前のバージョンを見る"$json$::jsonb),
  ('ja', 'whatsNew.done', $json$"OK"$json$::jsonb),
  ('ja', 'app.whatsNew', $json$"新機能"$json$::jsonb),
  ('ja', 'whatsNew.item.whatsNew.title', $json$"新機能ウィンドウ"$json$::jsonb),
  ('ja', 'whatsNew.item.whatsNew.detail', $json$"更新のたびに、このコンピューターで最後に見たバージョン以降の変更点を、新機能と修正に分けてこのウィンドウで表示します。各バージョンで一度だけ表示され、「OK」をクリックすると閉じます。"$json$::jsonb),
  ('ja', 'whatsNew.item.whatsNewHistory.title', $json$"いつでもバージョン履歴を表示"$json$::jsonb),
  ('ja', 'whatsNew.item.whatsNewHistory.detail', $json$"設定 › アプリ › バージョン の「新機能」ボタンで、インストール済みのバージョンを先頭に、以前のバージョンの履歴とともにウィンドウを再び開けます。"$json$::jsonb),
  ('ja', 'whatsNew.item.fixedSidebar.title', $json$"スクロールしてもサイドバーとヘッダーが固定"$json$::jsonb),
  ('ja', 'whatsNew.item.fixedSidebar.detail', $json$"プロジェクト、組織、組織ページ、設定、プロフィール、統計、システムの各画面で、サイドバーがコンテンツと一緒にスクロールしていました。現在はページの内容だけがスクロールし、サイドバーとヘッダーはウィンドウの高さで常に表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChat.title', $json$"すべてのリポジトリを対象にした組織チャット"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChat.detail', $json$"組織ページに「組織チャット」ボタンが追加され、このコンピューターの組織フォルダーを使って、組織のすべてのリポジトリを同時に扱うチャットを開けます。フォルダーが未選択なら、先に選ぶよう求めます。エージェント、インデックス、ゲートはフォルダー内のすべてのクローンを参照します。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChatReach.title', $json$"チャットに含まれるリポジトリを確認"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChatReach.detail', $json$"開く前に、フォルダー（「変更」ボタン付き）を表示し、リポジトリを「このチャットに含まれる」「別のフォルダーにクローンされているため除外」「このコンピューターにないため除外」に分けて示します。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChatPolicy.title', $json$"組織チャットでは最も厳しいポリシーを適用"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChatPolicy.detail', $json$"組織チャットは、組織の LLM ポリシーと各リポジトリのポリシーの両方に従い、常にその中で最も厳しいルールが適用されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChatDashboard.title', $json$"統計とゲートに組織チャットを反映"$json$::jsonb),
  ('ja', 'whatsNew.item.orgChatDashboard.detail', $json$"組織チャットの使用量が、サーバーによるプロジェクトの関連付けを待たずに、組織の「統計」と「ゲート」タブにすぐ表示されるようになりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactor.title', $json$"二要素認証"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactor.detail', $json$"プロフィール › セキュリティ で認証アプリを有効にします。QR コードを読み取る（または 4 文字ずつ表示されるキーを入力する）と、最初のコードで確認します。確認後に有効になり、「キャンセル」で途中の設定を破棄できます。"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactorSignIn.title', $json$"サインインごとに 6 桁のコード"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactorSignIn.detail', $json$"有効にすると、パスワード、GitHub、GitLab、Bitbucket、パスワード回復リンクのいずれでも、サインイン後にコードを求められます。第二要素を通過していないセッションからのリクエストはデータベースが拒否します。"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactorProtect.title', $json$"保護をオフにするにはコードが必要"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactorProtect.detail', $json$"第二要素を外すには、アプリの現在のコードを入力する必要があります。開いたままのセッションだけではアカウントの保護を解除できません。"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactorPassword.title', $json$"アプリ有効時のパスワード変更"$json$::jsonb),
  ('ja', 'whatsNew.item.twoFactorPassword.detail', $json$"第二要素が有効な場合、パスワード変更フォームでもアプリのコードを求めます。コードが間違っていたときは、セッションを中途半端にせず、もう一度第二要素を求めます。"$json$::jsonb),
  ('ja', 'whatsNew.item.lockdown.title', $json$"インストール版はインスペクト不可に"$json$::jsonb),
  ('ja', 'whatsNew.item.lockdown.detail', $json$"インストール版では、右クリックメニュー（コピー＆ペーストが使えるテキスト欄を除く）と、開発者ツール、ソース表示、保存、印刷、再読み込みのショートカットを無効にし、リモートインスペクターを開く変数を起動時に消去します。"$json$::jsonb),
  ('ja', 'whatsNew.item.safeConnections.title', $json$"より安全な接続"$json$::jsonb),
  ('ja', 'whatsNew.item.safeConnections.detail', $json$"JayV のすべてのリクエストは組み込みの認証局だけを信頼し、TLS 1.2 以上を必須とします。システムに独自の証明書を入れて HTTPS を傍受するプロキシは拒否され、通常のプロキシは引き続き使えます。"$json$::jsonb),
  ('ja', 'whatsNew.item.realtimeNotifications.title', $json$"リアルタイム通知が復活"$json$::jsonb),
  ('ja', 'whatsNew.item.realtimeNotifications.detail', $json$"コンテンツセキュリティポリシーが Supabase への安全な接続（wss）をブロックしていたため、ベルに通知がすぐ届きませんでした。現在は許可され、第二要素の QR コードで使う埋め込み画像も許可されています。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgStats.title', $json$"組織の「統計」タブ"$json$::jsonb),
  ('ja', 'whatsNew.item.orgStats.detail', $json$"概要、グラフ、Jev パネル、ツール・モデル・プロジェクト・チャット別の表を、このコンピューターにある組織のプロジェクトだけで集計します。プロジェクト、チャット、期間で絞り込め、表の行をクリックすると表示を絞り込めます。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgGate.title', $json$"組織の「ゲート」タブ"$json$::jsonb),
  ('ja', 'whatsNew.item.orgGate.detail', $json$"組織のプロジェクトのスコアボードと、入口・出口の 2 つのゲート。フィルターは「統計」と共通で、タブを切り替えても選択は保たれ、別の組織を開くとリセットされます。"$json$::jsonb),
  ('ja', 'whatsNew.item.usernameOnce.title', $json$"ユーザー名は一度だけ設定"$json$::jsonb),
  ('ja', 'whatsNew.item.usernameOnce.detail', $json$"ユーザー名はプロフィールを初めて保存した時点で固定されます。保存前にフォームで知らせ、その後は読み取り専用になります。プロフィールの手順をスキップしても名前は固定されません。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgPolicyDefaults.title', $json$"新しい組織はポリシー付きで作成"$json$::jsonb),
  ('ja', 'whatsNew.item.orgPolicyDefaults.detail', $json$"組織を作成すると、「読み取らない」と「ローカルモデルのみ」に安全な既定値が入り、「ポリシー」タブはすぐに調整できる状態で開きます。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentIcons.title', $json$"Claude Code と Codex の正しいアイコン"$json$::jsonb),
  ('ja', 'whatsNew.item.agentIcons.detail', $json$"エージェントのタブに古い絵が表示されていました。現在は Claude Code の公式アイコンと最新の Codex アイコンが、どのサイズでも鮮明に表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentExecutable.title', $json$"「実行ファイル」欄をロック"$json$::jsonb),
  ('ja', 'whatsNew.item.agentExecutable.detail', $json$"Claude、Codex、Copilot、Cursor の各タブでは JayV が実行ファイルを自動で設定します。欄は無効になり理由のヒントが表示されますが、「確認」ボタンは引き続き使えます。"$json$::jsonb),
  ('ja', 'whatsNew.item.updateBanner.title', $json$"上部に新バージョンのお知らせ"$json$::jsonb),
  ('ja', 'whatsNew.item.updateBanner.detail', $json$"新しいバージョンが出ると、どの画面にも上部にバーが表示され、「変更内容」（リリースノート）と「今すぐ更新」を選べます。バーを閉じると、そのバージョンの通知だけが非表示になります。"$json$::jsonb),
  ('ja', 'whatsNew.item.updateNotification.title', $json$"ベルにも新バージョンを通知"$json$::jsonb),
  ('ja', 'whatsNew.item.updateNotification.detail', $json$"新しいバージョンごとにベルへ通知が 1 件届き、そこから更新ウィンドウを直接開けます。"$json$::jsonb),
  ('ja', 'whatsNew.item.updateNoAutoInstall.title', $json$"更新で作業が中断されなくなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.updateNoAutoInstall.detail', $json$"以前は起動時に新しいバージョンを見つけるとすぐにインストールし、進行状況ウィンドウを前面に表示していました。現在は起動時と 30 分ごとの確認で知らせるだけで、更新のタイミングはあなたが選べます。ネットワークがないときは何も表示しません。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgFolderRemove.title', $json$"組織フォルダーの解除"$json$::jsonb),
  ('ja', 'whatsNew.item.orgFolderRemove.detail', $json$"「リポジトリ」タブの「削除」ボタンで、確認のうえこのコンピューターの組織フォルダーの設定を解除します。ディスクからは何も削除されず、クローンとプロジェクトはそのまま残り、次のクローン時に再びフォルダーを尋ねます。"$json$::jsonb),
  ('ja', 'whatsNew.item.projectDeletion.title', $json$"プロジェクトを削除するとチャットもすべての場所で削除"$json$::jsonb),
  ('ja', 'whatsNew.item.projectDeletion.detail', $json$"削除したプロジェクトのチャットが、同期後に別のコンピューターで復活していました。現在はサーバー上でも、プロジェクトのチャット、メッセージ、チェックまで削除が反映されます。"$json$::jsonb),
  ('de', 'whatsNew.title', $json$"Neu in JayV {version}"$json$::jsonb),
  ('de', 'whatsNew.description', $json$"Alles, was sich in jeder Version geändert hat, aufgeteilt in neue Funktionen und Fehlerbehebungen."$json$::jsonb),
  ('de', 'whatsNew.description.updated', $json$"JayV wurde von Version {previous} auf {version} aktualisiert. Das hat sich geändert."$json$::jsonb),
  ('de', 'whatsNew.description.installed', $json$"Du nutzt JayV {version}. Das bringt diese Version."$json$::jsonb),
  ('de', 'whatsNew.features', $json$"Neue Funktionen"$json$::jsonb),
  ('de', 'whatsNew.fixes', $json$"Fehlerbehebungen"$json$::jsonb),
  ('de', 'whatsNew.version', $json$"Version {version}"$json$::jsonb),
  ('de', 'whatsNew.installed', $json$"Installiert"$json$::jsonb),
  ('de', 'whatsNew.showAll', $json$"Frühere Versionen anzeigen"$json$::jsonb),
  ('de', 'whatsNew.done', $json$"Verstanden"$json$::jsonb),
  ('de', 'app.whatsNew', $json$"Neuigkeiten"$json$::jsonb),
  ('de', 'whatsNew.item.whatsNew.title', $json$"Fenster mit Neuigkeiten"$json$::jsonb),
  ('de', 'whatsNew.item.whatsNew.detail', $json$"Nach jedem Update öffnet JayV dieses Fenster mit allem, was sich seit der zuletzt auf diesem Computer gesehenen Version geändert hat, aufgeteilt in neue Funktionen und Fehlerbehebungen. Es erscheint einmal pro Version und schließt sich mit „Verstanden“."$json$::jsonb),
  ('de', 'whatsNew.item.whatsNewHistory.title', $json$"Versionsverlauf jederzeit"$json$::jsonb),
  ('de', 'whatsNew.item.whatsNewHistory.detail', $json$"Unter Einstellungen › App › Version öffnet die Schaltfläche „Neuigkeiten“ das Fenster erneut, oben die installierte Version und darunter der Verlauf der früheren."$json$::jsonb),
  ('de', 'whatsNew.item.fixedSidebar.title', $json$"Seitenleiste und Kopfzeile bleiben beim Scrollen stehen"$json$::jsonb),
  ('de', 'whatsNew.item.fixedSidebar.detail', $json$"In Projekte, Organisationen, der Organisationsseite, Einstellungen, Profil, Statistiken und System scrollte die Seitenleiste mit dem Inhalt weg. Jetzt scrollt nur noch der Seiteninhalt; Seitenleiste und Kopfzeile behalten die Fensterhöhe und bleiben sichtbar."$json$::jsonb),
  ('de', 'whatsNew.item.orgChat.title', $json$"Organisations-Chat über alle Repositorys"$json$::jsonb),
  ('de', 'whatsNew.item.orgChat.detail', $json$"Die Organisationsseite hat die neue Schaltfläche „Organisations-Chat“, die einen Chat öffnet, der mit dem Organisationsordner auf diesem Computer an allen Repositorys gleichzeitig arbeitet. Ohne Ordner fragt JayV zuerst danach. Agent, Index und Prüfung sehen alle Klone darin."$json$::jsonb),
  ('de', 'whatsNew.item.orgChatReach.title', $json$"Sehen, welche Repositorys in den Chat kommen"$json$::jsonb),
  ('de', 'whatsNew.item.orgChatReach.detail', $json$"Vor dem Öffnen zeigt ein Fenster den Ordner (mit der Schaltfläche „Ändern“) und teilt die Repositorys ein in: in diesem Chat, außen vor, weil in einem anderen Ordner geklont, und außen vor, weil nicht auf diesem Computer."$json$::jsonb),
  ('de', 'whatsNew.item.orgChatPolicy.title', $json$"Im Organisations-Chat gilt die strengste Richtlinie"$json$::jsonb),
  ('de', 'whatsNew.item.orgChatPolicy.detail', $json$"Der Organisations-Chat läuft unter der LLM-Richtlinie der Organisation zusammen mit der jedes ihrer Repositorys, und es gilt immer die strengste Regel."$json$::jsonb),
  ('de', 'whatsNew.item.orgChatDashboard.title', $json$"Organisations-Chat in Statistiken und Prüfung"$json$::jsonb),
  ('de', 'whatsNew.item.orgChatDashboard.detail', $json$"Die Nutzung des Organisations-Chats erscheint jetzt sofort in den Tabs Statistiken und Prüfung der Organisation, ohne zu warten, bis der Server das Projekt zuordnet."$json$::jsonb),
  ('de', 'whatsNew.item.twoFactor.title', $json$"Zwei-Faktor-Authentifizierung"$json$::jsonb),
  ('de', 'whatsNew.item.twoFactor.detail', $json$"Unter Profil › Sicherheit schaltest du eine Authenticator-App ein: QR-Code scannen (oder den in 4er-Blöcken angezeigten Schlüssel eintippen) und mit dem ersten Code bestätigen. Der Faktor gilt erst nach dieser Bestätigung, und „Abbrechen“ verwirft eine halbe Einrichtung."$json$::jsonb),
  ('de', 'whatsNew.item.twoFactorSignIn.title', $json$"Ein 6-stelliger Code bei jeder Anmeldung"$json$::jsonb),
  ('de', 'whatsNew.item.twoFactorSignIn.detail', $json$"Mit eingeschalteter App fragt jede Anmeldung nach Passwort, GitHub, GitLab, Bitbucket oder dem Link zur Passwortwiederherstellung nach dem Code. Die Datenbank lehnt Anfragen einer Sitzung ab, die den zweiten Faktor noch nicht bestanden hat."$json$::jsonb),
  ('de', 'whatsNew.item.twoFactorProtect.title', $json$"Zum Abschalten des Schutzes ist ein Code nötig"$json$::jsonb),
  ('de', 'whatsNew.item.twoFactorProtect.detail', $json$"Um den zweiten Faktor zu entfernen, braucht es einen aktuellen Code aus der App: Eine offen gelassene Sitzung reicht nicht, um den Schutz vom Konto zu nehmen."$json$::jsonb),
  ('de', 'whatsNew.item.twoFactorPassword.title', $json$"Passwort ändern bei eingeschalteter App"$json$::jsonb),
  ('de', 'whatsNew.item.twoFactorPassword.detail', $json$"Mit aktivem zweiten Faktor fragt das Formular zur Passwortänderung auch nach dem App-Code. Schlägt der Code fehl, fragt JayV den zweiten Faktor erneut ab, statt die Sitzung halb fertig zu lassen."$json$::jsonb),
  ('de', 'whatsNew.item.lockdown.title', $json$"Installierte App für Inspektion gesperrt"$json$::jsonb),
  ('de', 'whatsNew.item.lockdown.detail', $json$"In der installierten App sind das Rechtsklickmenü (außer in Textfeldern, die Kopieren und Einfügen behalten) und die Tastenkürzel für Entwicklertools, Quelltext, Speichern, Drucken und Neuladen abgeschaltet, und Variablen, die einen Remote-Inspektor öffnen würden, werden beim Start gelöscht."$json$::jsonb),
  ('de', 'whatsNew.item.safeConnections.title', $json$"Sicherere Verbindungen"$json$::jsonb),
  ('de', 'whatsNew.item.safeConnections.detail', $json$"Jede Anfrage von JayV vertraut nur den eingebauten Zertifizierungsstellen und verlangt TLS 1.2 oder neuer: Ein Proxy, der HTTPS mit einem eigenen, im System installierten Zertifikat abfängt, wird abgelehnt, ein gewöhnlicher Proxy funktioniert weiter."$json$::jsonb),
  ('de', 'whatsNew.item.realtimeNotifications.title', $json$"Echtzeit-Benachrichtigungen funktionieren wieder"$json$::jsonb),
  ('de', 'whatsNew.item.realtimeNotifications.detail', $json$"Die Content Security Policy blockierte die sichere Verbindung (wss) zu Supabase, sodass die Glocke Benachrichtigungen nicht sofort erhielt. Sie ist jetzt erlaubt, ebenso die eingebetteten Bilder des QR-Codes für den zweiten Faktor."$json$::jsonb),
  ('de', 'whatsNew.item.orgStats.title', $json$"Tab Statistiken in der Organisation"$json$::jsonb),
  ('de', 'whatsNew.item.orgStats.detail', $json$"Übersicht, Diagramme, das Jev-Panel und Tabellen nach Werkzeug, Modell, Projekt und Chat, nur für die Projekte auf diesem Computer, die zur Organisation gehören. Es gibt Filter für Projekt, Chat und Zeitraum, und ein Klick auf eine Tabellenzeile grenzt die Ansicht ein."$json$::jsonb),
  ('de', 'whatsNew.item.orgGate.title', $json$"Tab Prüfung in der Organisation"$json$::jsonb),
  ('de', 'whatsNew.item.orgGate.detail', $json$"Die Anzeigetafel und beide Tore, Eingang und Ausgang, für die Projekte der Organisation. Der Tab teilt seinen Filter mit Statistiken: Beim Tabwechsel bleibt die Auswahl, beim Öffnen einer anderen Organisation wird sie zurückgesetzt."$json$::jsonb),
  ('de', 'whatsNew.item.usernameOnce.title', $json$"Benutzername wird einmal festgelegt"$json$::jsonb),
  ('de', 'whatsNew.item.usernameOnce.detail', $json$"Der Benutzername wird nach dem ersten Speichern des Profils festgelegt. Das Formular weist vorher darauf hin, danach ist das Feld schreibgeschützt. Wer den Profilschritt überspringt, legt den Namen nicht fest."$json$::jsonb),
  ('de', 'whatsNew.item.orgPolicyDefaults.title', $json$"Neue Organisationen starten mit einer Richtlinie"$json$::jsonb),
  ('de', 'whatsNew.item.orgPolicyDefaults.detail', $json$"Beim Anlegen einer Organisation sind „Nie lesen“ und „Nur lokale Modelle“ bereits mit sicheren Standardwerten gefüllt, und der Tab Richtlinie öffnet sich bereit zum Anpassen."$json$::jsonb),
  ('de', 'whatsNew.item.agentIcons.title', $json$"Richtige Symbole für Claude Code und Codex"$json$::jsonb),
  ('de', 'whatsNew.item.agentIcons.detail', $json$"Die Agenten-Tabs zeigten alte Zeichnungen. Jetzt erscheinen das offizielle Claude-Code-Symbol und das aktuelle Codex-Symbol, scharf in jeder Größe."$json$::jsonb),
  ('de', 'whatsNew.item.agentExecutable.title', $json$"Feld „Programmdatei“ gesperrt"$json$::jsonb),
  ('de', 'whatsNew.item.agentExecutable.detail', $json$"In den Tabs Claude, Codex, Copilot und Cursor legt JayV die Programmdatei selbst fest: Das Feld ist deaktiviert, ein Hinweis erklärt warum, und die Schaltfläche „Prüfen“ funktioniert weiterhin."$json$::jsonb),
  ('de', 'whatsNew.item.updateBanner.title', $json$"Hinweis auf neue Version oben"$json$::jsonb),
  ('de', 'whatsNew.item.updateBanner.detail', $json$"Wenn eine neue Version erscheint, zeigt jeder Bildschirm oben eine Leiste mit „Was sich ändert“ (die Versionshinweise) und „Jetzt aktualisieren“. Schließen blendet den Hinweis nur für diese Version aus."$json$::jsonb),
  ('de', 'whatsNew.item.updateNotification.title', $json$"Neue Version auch in der Glocke"$json$::jsonb),
  ('de', 'whatsNew.item.updateNotification.detail', $json$"Jede neue Version wird zu einer Benachrichtigung in der Glocke, nur eine pro Version, die direkt zum Update-Fenster führt."$json$::jsonb),
  ('de', 'whatsNew.item.updateNoAutoInstall.title', $json$"Updates unterbrechen deine Arbeit nicht mehr"$json$::jsonb),
  ('de', 'whatsNew.item.updateNoAutoInstall.detail', $json$"Früher fand JayV die neue Version beim Öffnen und installierte sie sofort, mit dem Fortschrittsfenster im Vordergrund. Jetzt meldet die Prüfung beim Start und alle 30 Minuten nur: Du entscheidest, wann aktualisiert wird. Ohne Netzwerk bleibt die Prüfung still."$json$::jsonb),
  ('de', 'whatsNew.item.orgFolderRemove.title', $json$"Organisationsordner entfernen"$json$::jsonb),
  ('de', 'whatsNew.item.orgFolderRemove.detail', $json$"Im Tab Repositorys lässt die Schaltfläche „Entfernen“ JayV nach einer Bestätigung den Organisationsordner auf diesem Computer vergessen. Von der Festplatte wird nichts gelöscht: Klone und Projekte bleiben, wo sie sind, und der nächste Klon fragt erneut nach einem Ordner."$json$::jsonb),
  ('de', 'whatsNew.item.projectDeletion.title', $json$"Ein Projekt zu löschen entfernt seine Chats überall"$json$::jsonb),
  ('de', 'whatsNew.item.projectDeletion.detail', $json$"Chats eines gelöschten Projekts tauchten nach der Synchronisierung auf einem anderen Computer wieder auf. Jetzt greift das Löschen auch auf dem Server auf die Chats, Nachrichten und Prüfungen des Projekts über."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
