-- Limites do plano do Cursor e do Copilot no perfil, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'usage.window.auto', $json$"Modelos do Auto (mês)"$json$::jsonb),
  ('pt-BR', 'usage.window.api', $json$"Modelos escolhidos (mês)"$json$::jsonb),
  ('pt-BR', 'usage.window.premium', $json$"Requisições premium (mês)"$json$::jsonb),
  ('pt-BR', 'usage.window.chat', $json$"Chat (mês)"$json$::jsonb),
  ('pt-BR', 'usage.window.completions', $json$"Autocompletar (mês)"$json$::jsonb),
  ('pt-BR', 'usage.quota.signedOut', $json$"O {agent} não está conectado neste computador."$json$::jsonb),
  ('en', 'usage.window.auto', $json$"Auto models (month)"$json$::jsonb),
  ('en', 'usage.window.api', $json$"Named models (month)"$json$::jsonb),
  ('en', 'usage.window.premium', $json$"Premium requests (month)"$json$::jsonb),
  ('en', 'usage.window.chat', $json$"Chat (month)"$json$::jsonb),
  ('en', 'usage.window.completions', $json$"Completions (month)"$json$::jsonb),
  ('en', 'usage.quota.signedOut', $json$"{agent} is not signed in on this computer."$json$::jsonb),
  ('es', 'usage.window.auto', $json$"Modelos de Auto (mes)"$json$::jsonb),
  ('es', 'usage.window.api', $json$"Modelos elegidos (mes)"$json$::jsonb),
  ('es', 'usage.window.premium', $json$"Solicitudes premium (mes)"$json$::jsonb),
  ('es', 'usage.window.chat', $json$"Chat (mes)"$json$::jsonb),
  ('es', 'usage.window.completions', $json$"Autocompletado (mes)"$json$::jsonb),
  ('es', 'usage.quota.signedOut', $json$"{agent} no ha iniciado sesión en este equipo."$json$::jsonb),
  ('zh-CN', 'usage.window.auto', $json$"Auto 模型（本月）"$json$::jsonb),
  ('zh-CN', 'usage.window.api', $json$"指定模型（本月）"$json$::jsonb),
  ('zh-CN', 'usage.window.premium', $json$"高级请求（本月）"$json$::jsonb),
  ('zh-CN', 'usage.window.chat', $json$"聊天（本月）"$json$::jsonb),
  ('zh-CN', 'usage.window.completions', $json$"代码补全（本月）"$json$::jsonb),
  ('zh-CN', 'usage.quota.signedOut', $json$"{agent} 尚未在此电脑上登录。"$json$::jsonb),
  ('hi', 'usage.window.auto', $json$"Auto मॉडल (महीना)"$json$::jsonb),
  ('hi', 'usage.window.api', $json$"चुने गए मॉडल (महीना)"$json$::jsonb),
  ('hi', 'usage.window.premium', $json$"प्रीमियम अनुरोध (महीना)"$json$::jsonb),
  ('hi', 'usage.window.chat', $json$"चैट (महीना)"$json$::jsonb),
  ('hi', 'usage.window.completions', $json$"कम्प्लीशन (महीना)"$json$::jsonb),
  ('hi', 'usage.quota.signedOut', $json$"{agent} इस कंप्यूटर पर साइन इन नहीं है।"$json$::jsonb),
  ('ar', 'usage.window.auto', $json$"نماذج Auto (الشهر)"$json$::jsonb),
  ('ar', 'usage.window.api', $json$"النماذج المختارة (الشهر)"$json$::jsonb),
  ('ar', 'usage.window.premium', $json$"الطلبات المميزة (الشهر)"$json$::jsonb),
  ('ar', 'usage.window.chat', $json$"الدردشة (الشهر)"$json$::jsonb),
  ('ar', 'usage.window.completions', $json$"الإكمال التلقائي (الشهر)"$json$::jsonb),
  ('ar', 'usage.quota.signedOut', $json$"{agent} غير مسجَّل الدخول على هذا الحاسوب."$json$::jsonb),
  ('fr', 'usage.window.auto', $json$"Modèles Auto (mois)"$json$::jsonb),
  ('fr', 'usage.window.api', $json$"Modèles choisis (mois)"$json$::jsonb),
  ('fr', 'usage.window.premium', $json$"Requêtes premium (mois)"$json$::jsonb),
  ('fr', 'usage.window.chat', $json$"Chat (mois)"$json$::jsonb),
  ('fr', 'usage.window.completions', $json$"Complétions (mois)"$json$::jsonb),
  ('fr', 'usage.quota.signedOut', $json$"{agent} n'est pas connecté sur cet ordinateur."$json$::jsonb),
  ('ru', 'usage.window.auto', $json$"Модели Auto (месяц)"$json$::jsonb),
  ('ru', 'usage.window.api', $json$"Выбранные модели (месяц)"$json$::jsonb),
  ('ru', 'usage.window.premium', $json$"Премиум-запросы (месяц)"$json$::jsonb),
  ('ru', 'usage.window.chat', $json$"Чат (месяц)"$json$::jsonb),
  ('ru', 'usage.window.completions', $json$"Автодополнение (месяц)"$json$::jsonb),
  ('ru', 'usage.quota.signedOut', $json$"{agent} не выполнил вход на этом компьютере."$json$::jsonb),
  ('ja', 'usage.window.auto', $json$"Auto モデル（今月）"$json$::jsonb),
  ('ja', 'usage.window.api', $json$"指定モデル（今月）"$json$::jsonb),
  ('ja', 'usage.window.premium', $json$"プレミアムリクエスト（今月）"$json$::jsonb),
  ('ja', 'usage.window.chat', $json$"チャット（今月）"$json$::jsonb),
  ('ja', 'usage.window.completions', $json$"補完（今月）"$json$::jsonb),
  ('ja', 'usage.quota.signedOut', $json$"{agent} はこのコンピューターでサインインしていません。"$json$::jsonb),
  ('de', 'usage.window.auto', $json$"Auto-Modelle (Monat)"$json$::jsonb),
  ('de', 'usage.window.api', $json$"Gewählte Modelle (Monat)"$json$::jsonb),
  ('de', 'usage.window.premium', $json$"Premium-Anfragen (Monat)"$json$::jsonb),
  ('de', 'usage.window.chat', $json$"Chat (Monat)"$json$::jsonb),
  ('de', 'usage.window.completions', $json$"Vervollständigungen (Monat)"$json$::jsonb),
  ('de', 'usage.quota.signedOut', $json$"{agent} ist auf diesem Computer nicht angemeldet."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
