-- v0.38.0: organização, projetos e atualização.
--
-- Só textos: o botão "Chat da organização" vira "Agente em todos os
-- repositórios" e aparece também na página de Projetos; o filtro de Projetos
-- passa a ser Todos, Pessoais e Organizações, com uma barra de pesquisa; a
-- janela de atualização pergunta antes de instalar; a volta para as
-- organizações vira uma seta ao lado do título; e os itens da janela
-- "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'orgChat.open', $json$"Agente em todos os repositórios"$json$::jsonb),
  ('pt-BR', 'org.back', $json$"Voltar para as organizações"$json$::jsonb),
  ('pt-BR', 'update.install', $json$"Atualizar agora"$json$::jsonb),
  ('pt-BR', 'update.later', $json$"Agora não"$json$::jsonb),
  ('pt-BR', 'update.available.ask', $json$"Quer atualizar agora? Se não, a atualização fica esperando no aviso do topo e em Configurações › App até você mandar instalar."$json$::jsonb),
  ('pt-BR', 'projects.scope.organizations', $json$"Organizações"$json$::jsonb),
  ('pt-BR', 'projects.search.label', $json$"Buscar projetos por nome, pasta ou repositório"$json$::jsonb),
  ('pt-BR', 'projects.search.placeholder', $json$"Buscar projetos"$json$::jsonb),
  ('pt-BR', 'projects.search.empty', $json$"Nenhum projeto combina com a busca."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.repoAgent.title', $json$"Agente em todos os repositórios"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.repoAgent.detail', $json$"O antigo botão Chat da organização agora se chama Agente em todos os repositórios, para não parecer um chat com pessoas. Ele também aparece ao lado de cada organização na página de Projetos. Quando esse chat já existe neste computador, o botão leva direto a ele em vez de abrir outro."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectFilters.title', $json$"Filtro e busca de projetos"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.projectFilters.detail', $json$"O filtro da página de Projetos agora é Todos, Pessoais e Organizações, que mostra os projetos de todas as organizações juntos. Ao lado dele, uma barra de pesquisa acha projetos pelo nome, pela pasta ou pelo repositório."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateChoice.title', $json$"Você escolhe quando atualizar"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateChoice.detail', $json$"Procurar atualizações não instala mais a versão nova sozinho. A janela mostra o que muda e pergunta se você quer atualizar agora ou depois."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgPageTidy.title', $json$"Página da organização mais limpa"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgPageTidy.detail', $json$"As abas da organização não rolam mais de lado: Configurações virou um ícone de engrenagem ao lado do botão do agente. Voltar para a lista de organizações agora é uma seta ao lado do nome da organização."$json$::jsonb),
  ('en', 'orgChat.open', $json$"Agent in all repositories"$json$::jsonb),
  ('en', 'org.back', $json$"Back to organizations"$json$::jsonb),
  ('en', 'update.install', $json$"Update now"$json$::jsonb),
  ('en', 'update.later', $json$"Not now"$json$::jsonb),
  ('en', 'update.available.ask', $json$"Do you want to update now? If not, the update waits in the banner at the top and in Settings › App until you choose to install it."$json$::jsonb),
  ('en', 'projects.scope.organizations', $json$"Organizations"$json$::jsonb),
  ('en', 'projects.search.label', $json$"Search projects by name, folder or repository"$json$::jsonb),
  ('en', 'projects.search.placeholder', $json$"Search projects"$json$::jsonb),
  ('en', 'projects.search.empty', $json$"No project matches this search."$json$::jsonb),
  ('en', 'whatsNew.item.repoAgent.title', $json$"Agent in all repositories"$json$::jsonb),
  ('en', 'whatsNew.item.repoAgent.detail', $json$"The old Organization chat button is now called Agent in all repositories, so it no longer looks like a chat with people. It also appears next to each organization on the Projects page. When that chat already exists on this computer, the button takes you straight to it instead of opening another one."$json$::jsonb),
  ('en', 'whatsNew.item.projectFilters.title', $json$"Project filters and search"$json$::jsonb),
  ('en', 'whatsNew.item.projectFilters.detail', $json$"The Projects page filter is now All, Personal and Organizations, which shows the projects of every organization together. Next to it, a search box finds projects by name, folder or repository."$json$::jsonb),
  ('en', 'whatsNew.item.updateChoice.title', $json$"You choose when to update"$json$::jsonb),
  ('en', 'whatsNew.item.updateChoice.detail', $json$"Checking for updates no longer installs the new version on its own. The window shows what changes and asks whether you want to update now or later."$json$::jsonb),
  ('en', 'whatsNew.item.orgPageTidy.title', $json$"Tidier organization page"$json$::jsonb),
  ('en', 'whatsNew.item.orgPageTidy.detail', $json$"The organization tabs no longer scroll sideways: Settings moved to a gear icon next to the agent button. Going back to the organization list is now an arrow beside the organization name."$json$::jsonb),
  ('es', 'orgChat.open', $json$"Agente en todos los repositorios"$json$::jsonb),
  ('es', 'org.back', $json$"Volver a las organizaciones"$json$::jsonb),
  ('es', 'update.install', $json$"Actualizar ahora"$json$::jsonb),
  ('es', 'update.later', $json$"Ahora no"$json$::jsonb),
  ('es', 'update.available.ask', $json$"¿Quieres actualizar ahora? Si no, la actualización espera en el aviso de arriba y en Ajustes › App hasta que decidas instalarla."$json$::jsonb),
  ('es', 'projects.scope.organizations', $json$"Organizaciones"$json$::jsonb),
  ('es', 'projects.search.label', $json$"Buscar proyectos por nombre, carpeta o repositorio"$json$::jsonb),
  ('es', 'projects.search.placeholder', $json$"Buscar proyectos"$json$::jsonb),
  ('es', 'projects.search.empty', $json$"Ningún proyecto coincide con la búsqueda."$json$::jsonb),
  ('es', 'whatsNew.item.repoAgent.title', $json$"Agente en todos los repositorios"$json$::jsonb),
  ('es', 'whatsNew.item.repoAgent.detail', $json$"El antiguo botón Chat de la organización ahora se llama Agente en todos los repositorios, para que no parezca un chat con personas. También aparece junto a cada organización en la página de Proyectos. Si ese chat ya existe en este equipo, el botón te lleva directo a él en lugar de abrir otro."$json$::jsonb),
  ('es', 'whatsNew.item.projectFilters.title', $json$"Filtro y búsqueda de proyectos"$json$::jsonb),
  ('es', 'whatsNew.item.projectFilters.detail', $json$"El filtro de la página de Proyectos ahora es Todos, Personales y Organizaciones, que muestra juntos los proyectos de todas las organizaciones. A su lado, una barra de búsqueda encuentra proyectos por nombre, carpeta o repositorio."$json$::jsonb),
  ('es', 'whatsNew.item.updateChoice.title', $json$"Tú eliges cuándo actualizar"$json$::jsonb),
  ('es', 'whatsNew.item.updateChoice.detail', $json$"Buscar actualizaciones ya no instala la nueva versión por sí solo. La ventana muestra qué cambia y pregunta si quieres actualizar ahora o más tarde."$json$::jsonb),
  ('es', 'whatsNew.item.orgPageTidy.title', $json$"Página de la organización más ordenada"$json$::jsonb),
  ('es', 'whatsNew.item.orgPageTidy.detail', $json$"Las pestañas de la organización ya no se desplazan de lado: Ajustes pasó a un icono de engranaje junto al botón del agente. Volver a la lista de organizaciones ahora es una flecha junto al nombre de la organización."$json$::jsonb),
  ('fr', 'orgChat.open', $json$"Agent sur tous les dépôts"$json$::jsonb),
  ('fr', 'org.back', $json$"Retour aux organisations"$json$::jsonb),
  ('fr', 'update.install', $json$"Mettre à jour maintenant"$json$::jsonb),
  ('fr', 'update.later', $json$"Pas maintenant"$json$::jsonb),
  ('fr', 'update.available.ask', $json$"Voulez-vous mettre à jour maintenant ? Sinon, la mise à jour attend dans le bandeau en haut et dans Paramètres › App jusqu'à ce que vous choisissiez de l'installer."$json$::jsonb),
  ('fr', 'projects.scope.organizations', $json$"Organisations"$json$::jsonb),
  ('fr', 'projects.search.label', $json$"Rechercher des projets par nom, dossier ou dépôt"$json$::jsonb),
  ('fr', 'projects.search.placeholder', $json$"Rechercher des projets"$json$::jsonb),
  ('fr', 'projects.search.empty', $json$"Aucun projet ne correspond à cette recherche."$json$::jsonb),
  ('fr', 'whatsNew.item.repoAgent.title', $json$"Agent sur tous les dépôts"$json$::jsonb),
  ('fr', 'whatsNew.item.repoAgent.detail', $json$"L'ancien bouton Chat de l'organisation s'appelle désormais Agent sur tous les dépôts, pour ne plus ressembler à une discussion entre personnes. Il apparaît aussi à côté de chaque organisation sur la page Projets. Quand ce chat existe déjà sur cet ordinateur, le bouton vous y emmène directement au lieu d'en ouvrir un autre."$json$::jsonb),
  ('fr', 'whatsNew.item.projectFilters.title', $json$"Filtre et recherche de projets"$json$::jsonb),
  ('fr', 'whatsNew.item.projectFilters.detail', $json$"Le filtre de la page Projets est désormais Tous, Personnels et Organisations, qui affiche ensemble les projets de toutes les organisations. À côté, une barre de recherche trouve les projets par nom, dossier ou dépôt."$json$::jsonb),
  ('fr', 'whatsNew.item.updateChoice.title', $json$"Vous choisissez quand mettre à jour"$json$::jsonb),
  ('fr', 'whatsNew.item.updateChoice.detail', $json$"Rechercher des mises à jour n'installe plus la nouvelle version tout seul. La fenêtre montre ce qui change et demande si vous voulez mettre à jour maintenant ou plus tard."$json$::jsonb),
  ('fr', 'whatsNew.item.orgPageTidy.title', $json$"Page de l'organisation plus nette"$json$::jsonb),
  ('fr', 'whatsNew.item.orgPageTidy.detail', $json$"Les onglets de l'organisation ne défilent plus sur le côté : Paramètres est devenu une icône d'engrenage à côté du bouton de l'agent. Le retour à la liste des organisations est maintenant une flèche à côté du nom de l'organisation."$json$::jsonb),
  ('de', 'orgChat.open', $json$"Agent in allen Repositorys"$json$::jsonb),
  ('de', 'org.back', $json$"Zurück zu den Organisationen"$json$::jsonb),
  ('de', 'update.install', $json$"Jetzt aktualisieren"$json$::jsonb),
  ('de', 'update.later', $json$"Nicht jetzt"$json$::jsonb),
  ('de', 'update.available.ask', $json$"Möchtest du jetzt aktualisieren? Wenn nicht, wartet das Update im Hinweis oben und unter Einstellungen › App, bis du es installierst."$json$::jsonb),
  ('de', 'projects.scope.organizations', $json$"Organisationen"$json$::jsonb),
  ('de', 'projects.search.label', $json$"Projekte nach Name, Ordner oder Repository suchen"$json$::jsonb),
  ('de', 'projects.search.placeholder', $json$"Projekte suchen"$json$::jsonb),
  ('de', 'projects.search.empty', $json$"Kein Projekt passt zu dieser Suche."$json$::jsonb),
  ('de', 'whatsNew.item.repoAgent.title', $json$"Agent in allen Repositorys"$json$::jsonb),
  ('de', 'whatsNew.item.repoAgent.detail', $json$"Der frühere Knopf Organisations-Chat heißt jetzt Agent in allen Repositorys, damit er nicht wie ein Chat mit Personen wirkt. Er erscheint auch neben jeder Organisation auf der Projektseite. Wenn dieser Chat auf diesem Computer schon existiert, führt der Knopf direkt dorthin, statt einen neuen zu öffnen."$json$::jsonb),
  ('de', 'whatsNew.item.projectFilters.title', $json$"Projektfilter und Suche"$json$::jsonb),
  ('de', 'whatsNew.item.projectFilters.detail', $json$"Der Filter der Projektseite lautet jetzt Alle, Persönlich und Organisationen, das die Projekte aller Organisationen zusammen zeigt. Daneben findet eine Suchleiste Projekte nach Name, Ordner oder Repository."$json$::jsonb),
  ('de', 'whatsNew.item.updateChoice.title', $json$"Du entscheidest, wann aktualisiert wird"$json$::jsonb),
  ('de', 'whatsNew.item.updateChoice.detail', $json$"Die Suche nach Updates installiert die neue Version nicht mehr von selbst. Das Fenster zeigt, was sich ändert, und fragt, ob du jetzt oder später aktualisieren möchtest."$json$::jsonb),
  ('de', 'whatsNew.item.orgPageTidy.title', $json$"Aufgeräumtere Organisationsseite"$json$::jsonb),
  ('de', 'whatsNew.item.orgPageTidy.detail', $json$"Die Tabs der Organisation scrollen nicht mehr seitlich: Einstellungen ist jetzt ein Zahnrad neben dem Agent-Knopf. Zurück zur Organisationsliste geht es jetzt mit einem Pfeil neben dem Namen der Organisation."$json$::jsonb),
  ('ja', 'orgChat.open', $json$"すべてのリポジトリでエージェント"$json$::jsonb),
  ('ja', 'org.back', $json$"組織一覧に戻る"$json$::jsonb),
  ('ja', 'update.install', $json$"今すぐ更新"$json$::jsonb),
  ('ja', 'update.later', $json$"今はしない"$json$::jsonb),
  ('ja', 'update.available.ask', $json$"今すぐ更新しますか？しない場合、更新は上部のお知らせと 設定 › アプリ で、インストールを選ぶまで待機します。"$json$::jsonb),
  ('ja', 'projects.scope.organizations', $json$"組織"$json$::jsonb),
  ('ja', 'projects.search.label', $json$"名前、フォルダー、リポジトリでプロジェクトを検索"$json$::jsonb),
  ('ja', 'projects.search.placeholder', $json$"プロジェクトを検索"$json$::jsonb),
  ('ja', 'projects.search.empty', $json$"この検索に一致するプロジェクトはありません。"$json$::jsonb),
  ('ja', 'whatsNew.item.repoAgent.title', $json$"すべてのリポジトリでエージェント"$json$::jsonb),
  ('ja', 'whatsNew.item.repoAgent.detail', $json$"以前の「組織のチャット」ボタンは、人とのチャットに見えないよう「すべてのリポジトリでエージェント」という名前になりました。プロジェクトページの各組織の横にも表示されます。このコンピューターにそのチャットがすでにある場合は、新しく開かずにそのチャットへ直接移動します。"$json$::jsonb),
  ('ja', 'whatsNew.item.projectFilters.title', $json$"プロジェクトのフィルターと検索"$json$::jsonb),
  ('ja', 'whatsNew.item.projectFilters.detail', $json$"プロジェクトページのフィルターは「すべて」「個人」「組織」になり、「組織」ではすべての組織のプロジェクトをまとめて表示します。その横の検索バーで、名前、フォルダー、リポジトリからプロジェクトを探せます。"$json$::jsonb),
  ('ja', 'whatsNew.item.updateChoice.title', $json$"更新のタイミングを選べます"$json$::jsonb),
  ('ja', 'whatsNew.item.updateChoice.detail', $json$"更新の確認で新しいバージョンが自動的にインストールされることはなくなりました。ウィンドウに変更点が表示され、今すぐ更新するか後にするかを尋ねます。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgPageTidy.title', $json$"すっきりした組織ページ"$json$::jsonb),
  ('ja', 'whatsNew.item.orgPageTidy.detail', $json$"組織のタブが横にスクロールしなくなりました。設定はエージェントボタンの横の歯車アイコンになりました。組織一覧へ戻るには、組織名の横の矢印を使います。"$json$::jsonb),
  ('zh-CN', 'orgChat.open', $json$"在所有仓库中使用智能体"$json$::jsonb),
  ('zh-CN', 'org.back', $json$"返回组织列表"$json$::jsonb),
  ('zh-CN', 'update.install', $json$"立即更新"$json$::jsonb),
  ('zh-CN', 'update.later', $json$"暂不更新"$json$::jsonb),
  ('zh-CN', 'update.available.ask', $json$"现在要更新吗？如果不更新，更新会留在顶部提示和 设置 › 应用 中，直到你选择安装。"$json$::jsonb),
  ('zh-CN', 'projects.scope.organizations', $json$"组织"$json$::jsonb),
  ('zh-CN', 'projects.search.label', $json$"按名称、文件夹或仓库搜索项目"$json$::jsonb),
  ('zh-CN', 'projects.search.placeholder', $json$"搜索项目"$json$::jsonb),
  ('zh-CN', 'projects.search.empty', $json$"没有与此搜索匹配的项目。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.repoAgent.title', $json$"在所有仓库中使用智能体"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.repoAgent.detail', $json$"原来的“组织聊天”按钮现在叫“在所有仓库中使用智能体”，不再像是和人聊天。它也出现在项目页面每个组织的旁边。如果这台电脑上已经有这个聊天，按钮会直接带你过去，而不是再开一个。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectFilters.title', $json$"项目筛选和搜索"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.projectFilters.detail', $json$"项目页面的筛选现在是“全部”“个人”和“组织”，“组织”会把所有组织的项目一起显示。旁边的搜索栏可以按名称、文件夹或仓库查找项目。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateChoice.title', $json$"由你决定何时更新"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateChoice.detail', $json$"检查更新不会再自动安装新版本。窗口会显示变更内容，并询问你是现在更新还是稍后更新。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgPageTidy.title', $json$"更整洁的组织页面"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgPageTidy.detail', $json$"组织的标签页不再横向滚动：设置变成了智能体按钮旁的齿轮图标。返回组织列表现在是组织名称旁的箭头。"$json$::jsonb),
  ('ru', 'orgChat.open', $json$"Агент во всех репозиториях"$json$::jsonb),
  ('ru', 'org.back', $json$"Назад к организациям"$json$::jsonb),
  ('ru', 'update.install', $json$"Обновить сейчас"$json$::jsonb),
  ('ru', 'update.later', $json$"Не сейчас"$json$::jsonb),
  ('ru', 'update.available.ask', $json$"Обновить сейчас? Если нет, обновление будет ждать в баннере сверху и в Настройки › Приложение, пока вы не решите его установить."$json$::jsonb),
  ('ru', 'projects.scope.organizations', $json$"Организации"$json$::jsonb),
  ('ru', 'projects.search.label', $json$"Искать проекты по имени, папке или репозиторию"$json$::jsonb),
  ('ru', 'projects.search.placeholder', $json$"Искать проекты"$json$::jsonb),
  ('ru', 'projects.search.empty', $json$"Ни один проект не подходит под этот поиск."$json$::jsonb),
  ('ru', 'whatsNew.item.repoAgent.title', $json$"Агент во всех репозиториях"$json$::jsonb),
  ('ru', 'whatsNew.item.repoAgent.detail', $json$"Бывшая кнопка «Чат организации» теперь называется «Агент во всех репозиториях», чтобы не выглядеть как чат с людьми. Она также появилась рядом с каждой организацией на странице «Проекты». Если такой чат уже есть на этом компьютере, кнопка сразу ведёт в него, а не открывает новый."$json$::jsonb),
  ('ru', 'whatsNew.item.projectFilters.title', $json$"Фильтр и поиск проектов"$json$::jsonb),
  ('ru', 'whatsNew.item.projectFilters.detail', $json$"Фильтр на странице «Проекты» теперь: «Все», «Личные» и «Организации» — последний показывает проекты всех организаций вместе. Рядом строка поиска находит проекты по имени, папке или репозиторию."$json$::jsonb),
  ('ru', 'whatsNew.item.updateChoice.title', $json$"Вы решаете, когда обновляться"$json$::jsonb),
  ('ru', 'whatsNew.item.updateChoice.detail', $json$"Проверка обновлений больше не устанавливает новую версию сама. Окно показывает, что изменится, и спрашивает, обновиться сейчас или позже."$json$::jsonb),
  ('ru', 'whatsNew.item.orgPageTidy.title', $json$"Более аккуратная страница организации"$json$::jsonb),
  ('ru', 'whatsNew.item.orgPageTidy.detail', $json$"Вкладки организации больше не прокручиваются вбок: настройки стали значком шестерёнки рядом с кнопкой агента. Вернуться к списку организаций теперь можно стрелкой рядом с её названием."$json$::jsonb),
  ('ar', 'orgChat.open', $json$"الوكيل في كل المستودعات"$json$::jsonb),
  ('ar', 'org.back', $json$"العودة إلى المؤسسات"$json$::jsonb),
  ('ar', 'update.install', $json$"حدّث الآن"$json$::jsonb),
  ('ar', 'update.later', $json$"ليس الآن"$json$::jsonb),
  ('ar', 'update.available.ask', $json$"هل تريد التحديث الآن؟ إن لم تُرد، ينتظر التحديث في الشريط العلوي وفي الإعدادات › التطبيق حتى تختار تثبيته."$json$::jsonb),
  ('ar', 'projects.scope.organizations', $json$"المؤسسات"$json$::jsonb),
  ('ar', 'projects.search.label', $json$"ابحث عن المشاريع بالاسم أو المجلد أو المستودع"$json$::jsonb),
  ('ar', 'projects.search.placeholder', $json$"ابحث عن المشاريع"$json$::jsonb),
  ('ar', 'projects.search.empty', $json$"لا يوجد مشروع يطابق هذا البحث."$json$::jsonb),
  ('ar', 'whatsNew.item.repoAgent.title', $json$"الوكيل في كل المستودعات"$json$::jsonb),
  ('ar', 'whatsNew.item.repoAgent.detail', $json$"زر «محادثة المؤسسة» القديم أصبح اسمه «الوكيل في كل المستودعات» حتى لا يبدو محادثة مع أشخاص. ويظهر أيضًا بجانب كل مؤسسة في صفحة المشاريع. وإذا كانت هذه المحادثة موجودة على هذا الكمبيوتر، يأخذك الزر إليها مباشرة بدل فتح محادثة جديدة."$json$::jsonb),
  ('ar', 'whatsNew.item.projectFilters.title', $json$"تصفية المشاريع والبحث فيها"$json$::jsonb),
  ('ar', 'whatsNew.item.projectFilters.detail', $json$"أصبحت تصفية صفحة المشاريع: الكل، والشخصية، والمؤسسات التي تعرض مشاريع كل المؤسسات معًا. وبجانبها شريط بحث يجد المشاريع بالاسم أو المجلد أو المستودع."$json$::jsonb),
  ('ar', 'whatsNew.item.updateChoice.title', $json$"أنت تختار وقت التحديث"$json$::jsonb),
  ('ar', 'whatsNew.item.updateChoice.detail', $json$"لم يعد البحث عن التحديثات يثبّت الإصدار الجديد من تلقاء نفسه. تعرض النافذة ما الذي يتغير وتسألك إن كنت تريد التحديث الآن أو لاحقًا."$json$::jsonb),
  ('ar', 'whatsNew.item.orgPageTidy.title', $json$"صفحة مؤسسة أكثر ترتيبًا"$json$::jsonb),
  ('ar', 'whatsNew.item.orgPageTidy.detail', $json$"لم تعد علامات تبويب المؤسسة تتمرر جانبيًا: أصبحت الإعدادات أيقونة ترس بجانب زر الوكيل. والعودة إلى قائمة المؤسسات أصبحت سهمًا بجانب اسم المؤسسة."$json$::jsonb),
  ('hi', 'orgChat.open', $json$"सभी रिपॉज़िटरी में एजेंट"$json$::jsonb),
  ('hi', 'org.back', $json$"संगठनों पर वापस जाएँ"$json$::jsonb),
  ('hi', 'update.install', $json$"अभी अपडेट करें"$json$::jsonb),
  ('hi', 'update.later', $json$"अभी नहीं"$json$::jsonb),
  ('hi', 'update.available.ask', $json$"क्या आप अभी अपडेट करना चाहते हैं? नहीं तो अपडेट ऊपर की सूचना और सेटिंग्स › ऐप में तब तक इंतज़ार करेगा जब तक आप इसे इंस्टॉल करना न चुनें।"$json$::jsonb),
  ('hi', 'projects.scope.organizations', $json$"संगठन"$json$::jsonb),
  ('hi', 'projects.search.label', $json$"नाम, फ़ोल्डर या रिपॉज़िटरी से प्रोजेक्ट खोजें"$json$::jsonb),
  ('hi', 'projects.search.placeholder', $json$"प्रोजेक्ट खोजें"$json$::jsonb),
  ('hi', 'projects.search.empty', $json$"इस खोज से कोई प्रोजेक्ट मेल नहीं खाता।"$json$::jsonb),
  ('hi', 'whatsNew.item.repoAgent.title', $json$"सभी रिपॉज़िटरी में एजेंट"$json$::jsonb),
  ('hi', 'whatsNew.item.repoAgent.detail', $json$"पुराना संगठन चैट बटन अब सभी रिपॉज़िटरी में एजेंट कहलाता है, ताकि यह लोगों के साथ चैट जैसा न लगे। यह प्रोजेक्ट पेज पर हर संगठन के बगल में भी दिखता है। अगर वह चैट इस कंप्यूटर पर पहले से है, तो बटन नया खोलने के बजाय सीधे उसी पर ले जाता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.projectFilters.title', $json$"प्रोजेक्ट फ़िल्टर और खोज"$json$::jsonb),
  ('hi', 'whatsNew.item.projectFilters.detail', $json$"प्रोजेक्ट पेज का फ़िल्टर अब सभी, निजी और संगठन है, जो सभी संगठनों के प्रोजेक्ट एक साथ दिखाता है। इसके बगल में एक खोज बार नाम, फ़ोल्डर या रिपॉज़िटरी से प्रोजेक्ट ढूँढता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updateChoice.title', $json$"आप तय करते हैं कि कब अपडेट करना है"$json$::jsonb),
  ('hi', 'whatsNew.item.updateChoice.detail', $json$"अपडेट खोजने पर नया वर्ज़न अब अपने आप इंस्टॉल नहीं होता। विंडो दिखाती है कि क्या बदलेगा और पूछती है कि आप अभी अपडेट करना चाहते हैं या बाद में।"$json$::jsonb),
  ('hi', 'whatsNew.item.orgPageTidy.title', $json$"साफ़-सुथरा संगठन पेज"$json$::jsonb),
  ('hi', 'whatsNew.item.orgPageTidy.detail', $json$"संगठन के टैब अब बगल में स्क्रॉल नहीं होते: सेटिंग्स अब एजेंट बटन के बगल में गियर आइकन है। संगठनों की सूची पर वापस जाना अब संगठन के नाम के बगल में एक तीर है।"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
