-- v0.79.1: o painel Ao vivo diz o que está olhando e o botão do editor acha o VS Code fora do PATH.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'live.watching.git', $json$"Olhando {folder} (git status, uma vez por segundo)"$json$::jsonb),
  ('en', 'live.watching.git', $json$"Watching {folder} (git status, once a second)"$json$::jsonb),
  ('es', 'live.watching.git', $json$"Vigilando {folder} (git status, una vez por segundo)"$json$::jsonb),
  ('zh-CN', 'live.watching.git', $json$"正在监视 {folder}（git status，每秒一次）"$json$::jsonb),
  ('hi', 'live.watching.git', $json$"{folder} पर नज़र (git status, हर सेकंड में एक बार)"$json$::jsonb),
  ('ar', 'live.watching.git', $json$"مراقبة {folder} (git status، مرة كل ثانية)"$json$::jsonb),
  ('fr', 'live.watching.git', $json$"Surveillance de {folder} (git status, une fois par seconde)"$json$::jsonb),
  ('ru', 'live.watching.git', $json$"Слежу за {folder} (git status, раз в секунду)"$json$::jsonb),
  ('ja', 'live.watching.git', $json$"{folder} を監視中（git status、1秒に1回）"$json$::jsonb),
  ('de', 'live.watching.git', $json$"Überwacht {folder} (git status, einmal pro Sekunde)"$json$::jsonb),
  ('pt-BR', 'live.watching.folder', $json$"Olhando {folder} (sem git: arquivos alterados desde o início do pedido)"$json$::jsonb),
  ('en', 'live.watching.folder', $json$"Watching {folder} (no git: files changed since the request started)"$json$::jsonb),
  ('es', 'live.watching.folder', $json$"Vigilando {folder} (sin git: archivos cambiados desde que empezó la petición)"$json$::jsonb),
  ('zh-CN', 'live.watching.folder', $json$"正在监视 {folder}（无 git：请求开始后更改的文件）"$json$::jsonb),
  ('hi', 'live.watching.folder', $json$"{folder} पर नज़र (git नहीं: अनुरोध शुरू होने के बाद बदली फ़ाइलें)"$json$::jsonb),
  ('ar', 'live.watching.folder', $json$"مراقبة {folder} (بدون git: الملفات المتغيرة منذ بدء الطلب)"$json$::jsonb),
  ('fr', 'live.watching.folder', $json$"Surveillance de {folder} (sans git : fichiers modifiés depuis le début de la requête)"$json$::jsonb),
  ('ru', 'live.watching.folder', $json$"Слежу за {folder} (без git: файлы, изменённые с начала запроса)"$json$::jsonb),
  ('ja', 'live.watching.folder', $json$"{folder} を監視中（git なし：リクエスト開始後に変更されたファイル）"$json$::jsonb),
  ('de', 'live.watching.folder', $json$"Überwacht {folder} (ohne git: seit Anfragebeginn geänderte Dateien)"$json$::jsonb),
  ('pt-BR', 'live.notWatching', $json$"O JayV não está olhando nenhuma pasta neste pedido. Os arquivos ao vivo podem estar desligados no seu plano, ou o chat não tem pasta de projeto."$json$::jsonb),
  ('en', 'live.notWatching', $json$"JayV is not watching any folder for this request. Live files may be off in your plan, or the chat has no project folder."$json$::jsonb),
  ('es', 'live.notWatching', $json$"JayV no está vigilando ninguna carpeta en esta petición. Los archivos en vivo pueden estar desactivados en tu plan, o el chat no tiene carpeta de proyecto."$json$::jsonb),
  ('zh-CN', 'live.notWatching', $json$"JayV 没有在监视此请求的任何文件夹。你的套餐可能关闭了实时文件，或者该聊天没有项目文件夹。"$json$::jsonb),
  ('hi', 'live.notWatching', $json$"JayV इस अनुरोध के लिए कोई फ़ोल्डर नहीं देख रहा। आपके प्लान में लाइव फ़ाइलें बंद हो सकती हैं, या चैट में प्रोजेक्ट फ़ोल्डर नहीं है।"$json$::jsonb),
  ('ar', 'live.notWatching', $json$"لا يراقب JayV أي مجلد لهذا الطلب. قد تكون الملفات المباشرة معطّلة في خطتك، أو ليس للمحادثة مجلد مشروع."$json$::jsonb),
  ('fr', 'live.notWatching', $json$"JayV ne surveille aucun dossier pour cette requête. Les fichiers en direct sont peut-être désactivés dans votre forfait, ou le chat n'a pas de dossier de projet."$json$::jsonb),
  ('ru', 'live.notWatching', $json$"JayV не следит ни за одной папкой для этого запроса. Живые файлы могут быть отключены в вашем тарифе, или у чата нет папки проекта."$json$::jsonb),
  ('ja', 'live.notWatching', $json$"JayV はこのリクエストでどのフォルダも監視していません。プランでライブファイルがオフか、チャットにプロジェクトフォルダがない可能性があります。"$json$::jsonb),
  ('de', 'live.notWatching', $json$"JayV überwacht für diese Anfrage keinen Ordner. Live-Dateien sind in Ihrem Tarif möglicherweise aus, oder der Chat hat keinen Projektordner."$json$::jsonb),
  ('pt-BR', 'live.notWatched', $json$"Nada vigiado ainda: a pasta é lida a partir do próximo pedido."$json$::jsonb),
  ('en', 'live.notWatched', $json$"Nothing watched yet: the folder is read from the next request on."$json$::jsonb),
  ('es', 'live.notWatched', $json$"Nada vigilado todavía: la carpeta se lee a partir de la próxima petición."$json$::jsonb),
  ('zh-CN', 'live.notWatched', $json$"尚未监视任何内容：从下一个请求起读取该文件夹。"$json$::jsonb),
  ('hi', 'live.notWatched', $json$"अभी कुछ नहीं देखा गया: फ़ोल्डर अगले अनुरोध से पढ़ा जाएगा।"$json$::jsonb),
  ('ar', 'live.notWatched', $json$"لا شيء مراقَب بعد: تُقرأ المجلد ابتداءً من الطلب التالي."$json$::jsonb),
  ('fr', 'live.notWatched', $json$"Rien de surveillé pour l'instant : le dossier est lu à partir de la prochaine requête."$json$::jsonb),
  ('ru', 'live.notWatched', $json$"Пока ничего не отслеживается: папка читается со следующего запроса."$json$::jsonb),
  ('ja', 'live.notWatched', $json$"まだ何も監視していません。次のリクエストからフォルダを読み取ります。"$json$::jsonb),
  ('de', 'live.notWatched', $json$"Noch nichts überwacht: Der Ordner wird ab der nächsten Anfrage gelesen."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveFilesDiagnostics.title', $json$"Ao vivo diz o que está olhando"$json$::jsonb),
  ('en', 'whatsNew.item.liveFilesDiagnostics.title', $json$"Live says what it is watching"$json$::jsonb),
  ('es', 'whatsNew.item.liveFilesDiagnostics.title', $json$"En vivo dice qué está vigilando"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveFilesDiagnostics.title', $json$"实时面板会说明它在监视什么"$json$::jsonb),
  ('hi', 'whatsNew.item.liveFilesDiagnostics.title', $json$"लाइव बताता है कि वह क्या देख रहा है"$json$::jsonb),
  ('ar', 'whatsNew.item.liveFilesDiagnostics.title', $json$"المباشر يوضح ما يراقبه"$json$::jsonb),
  ('fr', 'whatsNew.item.liveFilesDiagnostics.title', $json$"En direct indique ce qu'il surveille"$json$::jsonb),
  ('ru', 'whatsNew.item.liveFilesDiagnostics.title', $json$"«Вживую» показывает, за чем следит"$json$::jsonb),
  ('ja', 'whatsNew.item.liveFilesDiagnostics.title', $json$"ライブが何を監視しているか表示"$json$::jsonb),
  ('de', 'whatsNew.item.liveFilesDiagnostics.title', $json$"Live zeigt, was es überwacht"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"A primeira linha do painel Ao vivo agora mostra qual pasta o JayV está olhando e como (git ou pasta sem git), ou avisa que não está olhando nenhuma. O painel relê o estado ao abrir, e o botão VS Code passa a achar o editor também em /snap/bin, ~/.local/bin, na pasta do VS Code no Windows e no macOS, onde o app aberto pelo menu do sistema não o enxergava."$json$::jsonb),
  ('en', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"The first line of the Live panel now shows which folder JayV is watching and how (git or a folder without git), or says it is watching none. The panel reads the state again when it opens, and the VS Code button now also finds the editor in /snap/bin, ~/.local/bin and the VS Code folders on Windows and macOS, where an app opened from the system menu could not see it."$json$::jsonb),
  ('es', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"La primera línea del panel En vivo ahora muestra qué carpeta vigila JayV y cómo (git o carpeta sin git), o avisa de que no vigila ninguna. El panel vuelve a leer el estado al abrirse, y el botón VS Code ahora también encuentra el editor en /snap/bin, ~/.local/bin y en las carpetas de VS Code de Windows y macOS, donde una app abierta desde el menú del sistema no lo veía."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"实时面板的第一行现在显示 JayV 正在监视哪个文件夹以及方式（git 或无 git 的文件夹），或提示没有监视任何文件夹。面板打开时会重新读取状态，VS Code 按钮现在也会在 /snap/bin、~/.local/bin 以及 Windows 和 macOS 的 VS Code 文件夹中查找编辑器，而从系统菜单打开的应用之前看不到这些位置。"$json$::jsonb),
  ('hi', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"लाइव पैनल की पहली पंक्ति अब बताती है कि JayV कौन-सा फ़ोल्डर और कैसे (git या बिना git का फ़ोल्डर) देख रहा है, या बताती है कि वह कुछ नहीं देख रहा। पैनल खुलते समय स्थिति फिर पढ़ता है, और VS Code बटन अब /snap/bin, ~/.local/bin तथा Windows और macOS के VS Code फ़ोल्डरों में भी एडिटर खोज लेता है, जहाँ सिस्टम मेनू से खुला ऐप उसे नहीं देख पाता था।"$json$::jsonb),
  ('ar', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"يعرض السطر الأول في لوحة المباشر الآن أي مجلد يراقبه JayV وكيف (git أو مجلد بلا git)، أو ينبّه إلى أنه لا يراقب أي مجلد. تعيد اللوحة قراءة الحالة عند فتحها، ويجد زر VS Code المحرر الآن أيضًا في /snap/bin و~/.local/bin ومجلدات VS Code في Windows وmacOS، حيث لم يكن التطبيق المفتوح من قائمة النظام يراه."$json$::jsonb),
  ('fr', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"La première ligne du panneau En direct indique désormais quel dossier JayV surveille et comment (git ou dossier sans git), ou signale qu'il n'en surveille aucun. Le panneau relit l'état à l'ouverture, et le bouton VS Code trouve aussi l'éditeur dans /snap/bin, ~/.local/bin et les dossiers de VS Code sous Windows et macOS, où une app ouverte depuis le menu du système ne le voyait pas."$json$::jsonb),
  ('ru', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"Первая строка панели «Вживую» теперь показывает, какую папку и как отслеживает JayV (git или папка без git), либо сообщает, что не отслеживает ничего. Панель заново читает состояние при открытии, а кнопка VS Code теперь находит редактор и в /snap/bin, ~/.local/bin, и в папках VS Code на Windows и macOS, где приложение, запущенное из системного меню, его не видело."$json$::jsonb),
  ('ja', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"ライブパネルの1行目に、JayV がどのフォルダをどの方法（git または git なしのフォルダ）で監視しているか、または何も監視していないことが表示されます。パネルは開くときに状態を読み直し、VS Code ボタンは /snap/bin、~/.local/bin、Windows と macOS の VS Code フォルダでもエディターを見つけるようになりました（システムメニューから開いたアプリでは見えていませんでした）。"$json$::jsonb),
  ('de', 'whatsNew.item.liveFilesDiagnostics.detail', $json$"Die erste Zeile des Live-Panels zeigt jetzt, welchen Ordner JayV überwacht und wie (git oder Ordner ohne git), oder dass er keinen überwacht. Das Panel liest den Zustand beim Öffnen neu, und die VS-Code-Schaltfläche findet den Editor jetzt auch in /snap/bin, ~/.local/bin und den VS-Code-Ordnern unter Windows und macOS, wo eine über das Systemmenü geöffnete App ihn nicht sah."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
