-- A lista de projetos separada por dono: um bloco para os pessoais e um por
-- organização, o filtro entre eles, a placa do projeto aberto e a aba "Seus
-- projetos" da organização.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'project.scope.personal', $json$"Projeto pessoal"$json$::jsonb),
  ('pt-BR', 'projects.count', $json${"one": "{count} projeto", "other": "{count} projetos"}$json$::jsonb),
  ('pt-BR', 'projects.scope.label', $json$"Mostrar projetos de"$json$::jsonb),
  ('pt-BR', 'projects.scope.all', $json$"Todos"$json$::jsonb),
  ('pt-BR', 'projects.scope.personal', $json$"Pessoais"$json$::jsonb),
  ('pt-BR', 'projects.personal.title', $json$"Projetos pessoais"$json$::jsonb),
  ('pt-BR', 'projects.personal.description', $json$"Só você trabalha neles. Um projeto passa para uma organização quando um dos remotes do git dele casa com um repositório dela."$json$::jsonb),
  ('pt-BR', 'projects.personal.empty', $json$"Nenhum projeto pessoal."$json$::jsonb),
  ('pt-BR', 'projects.org.description', $json$"Projetos deste computador cujo remote do git casa com um repositório desta organização. A política de LLM dela vale para eles."$json$::jsonb),
  ('pt-BR', 'projects.org.empty', $json$"Nenhum projeto seu entrou nesta organização ainda. Um projeto entra quando um dos remotes do git dele casa com um repositório cadastrado nela."$json$::jsonb),
  ('pt-BR', 'projects.org.open', $json$"Abrir organização"$json$::jsonb),
  ('pt-BR', 'org.tab.projects', $json$"Seus projetos"$json$::jsonb),
  ('pt-BR', 'org.projects.title', $json$"Seus projetos nesta organização"$json$::jsonb),
  ('pt-BR', 'org.projects.description', $json$"Projetos deste computador que entraram nesta organização pelo remote do git."$json$::jsonb),
  ('en', 'project.scope.personal', $json$"Personal project"$json$::jsonb),
  ('en', 'projects.count', $json${"one": "{count} project", "other": "{count} projects"}$json$::jsonb),
  ('en', 'projects.scope.label', $json$"Show projects from"$json$::jsonb),
  ('en', 'projects.scope.all', $json$"All"$json$::jsonb),
  ('en', 'projects.scope.personal', $json$"Personal"$json$::jsonb),
  ('en', 'projects.personal.title', $json$"Personal projects"$json$::jsonb),
  ('en', 'projects.personal.description', $json$"Only you work on these. A project moves to an organization when one of its git remotes matches a repository of that organization."$json$::jsonb),
  ('en', 'projects.personal.empty', $json$"No personal projects."$json$::jsonb),
  ('en', 'projects.org.description', $json$"Projects on this computer whose git remote matches a repository of this organization. Its LLM policy applies to them."$json$::jsonb),
  ('en', 'projects.org.empty', $json$"None of your projects belongs to this organization yet. A project joins it when one of its git remotes matches a repository listed in the organization."$json$::jsonb),
  ('en', 'projects.org.open', $json$"Open organization"$json$::jsonb),
  ('en', 'org.tab.projects', $json$"Your projects"$json$::jsonb),
  ('en', 'org.projects.title', $json$"Your projects in this organization"$json$::jsonb),
  ('en', 'org.projects.description', $json$"Projects on this computer that joined this organization through their git remote."$json$::jsonb),
  ('es', 'project.scope.personal', $json$"Proyecto personal"$json$::jsonb),
  ('es', 'projects.count', $json${"one": "{count} proyecto", "other": "{count} proyectos"}$json$::jsonb),
  ('es', 'projects.scope.label', $json$"Mostrar proyectos de"$json$::jsonb),
  ('es', 'projects.scope.all', $json$"Todos"$json$::jsonb),
  ('es', 'projects.scope.personal', $json$"Personales"$json$::jsonb),
  ('es', 'projects.personal.title', $json$"Proyectos personales"$json$::jsonb),
  ('es', 'projects.personal.description', $json$"Solo tú trabajas en ellos. Un proyecto pasa a una organización cuando uno de sus remotes de git coincide con un repositorio de esa organización."$json$::jsonb),
  ('es', 'projects.personal.empty', $json$"Ningún proyecto personal."$json$::jsonb),
  ('es', 'projects.org.description', $json$"Proyectos de este equipo cuyo remote de git coincide con un repositorio de esta organización. Su política de LLM se aplica a ellos."$json$::jsonb),
  ('es', 'projects.org.empty', $json$"Ninguno de tus proyectos pertenece aún a esta organización. Un proyecto entra cuando uno de sus remotes de git coincide con un repositorio registrado en ella."$json$::jsonb),
  ('es', 'projects.org.open', $json$"Abrir organización"$json$::jsonb),
  ('es', 'org.tab.projects', $json$"Tus proyectos"$json$::jsonb),
  ('es', 'org.projects.title', $json$"Tus proyectos en esta organización"$json$::jsonb),
  ('es', 'org.projects.description', $json$"Proyectos de este equipo que entraron en esta organización por su remote de git."$json$::jsonb),
  ('zh-CN', 'project.scope.personal', $json$"个人项目"$json$::jsonb),
  ('zh-CN', 'projects.count', $json${"other": "{count} 个项目"}$json$::jsonb),
  ('zh-CN', 'projects.scope.label', $json$"显示以下范围的项目"$json$::jsonb),
  ('zh-CN', 'projects.scope.all', $json$"全部"$json$::jsonb),
  ('zh-CN', 'projects.scope.personal', $json$"个人"$json$::jsonb),
  ('zh-CN', 'projects.personal.title', $json$"个人项目"$json$::jsonb),
  ('zh-CN', 'projects.personal.description', $json$"只有你在使用这些项目。当项目的某个 git 远程仓库与某个组织的仓库匹配时，该项目会归入该组织。"$json$::jsonb),
  ('zh-CN', 'projects.personal.empty', $json$"没有个人项目。"$json$::jsonb),
  ('zh-CN', 'projects.org.description', $json$"本机上 git 远程仓库与该组织某个仓库匹配的项目。组织的 LLM 策略适用于这些项目。"$json$::jsonb),
  ('zh-CN', 'projects.org.empty', $json$"你的项目尚未归入此组织。当项目的某个 git 远程仓库与组织中登记的仓库匹配时，项目就会归入该组织。"$json$::jsonb),
  ('zh-CN', 'projects.org.open', $json$"打开组织"$json$::jsonb),
  ('zh-CN', 'org.tab.projects', $json$"你的项目"$json$::jsonb),
  ('zh-CN', 'org.projects.title', $json$"你在此组织中的项目"$json$::jsonb),
  ('zh-CN', 'org.projects.description', $json$"本机上通过 git 远程仓库归入此组织的项目。"$json$::jsonb),
  ('hi', 'project.scope.personal', $json$"निजी प्रोजेक्ट"$json$::jsonb),
  ('hi', 'projects.count', $json${"one": "{count} प्रोजेक्ट", "other": "{count} प्रोजेक्ट"}$json$::jsonb),
  ('hi', 'projects.scope.label', $json$"इनके प्रोजेक्ट दिखाएँ"$json$::jsonb),
  ('hi', 'projects.scope.all', $json$"सभी"$json$::jsonb),
  ('hi', 'projects.scope.personal', $json$"निजी"$json$::jsonb),
  ('hi', 'projects.personal.title', $json$"निजी प्रोजेक्ट"$json$::jsonb),
  ('hi', 'projects.personal.description', $json$"इन पर सिर्फ़ आप काम करते हैं। जब किसी प्रोजेक्ट का कोई git remote किसी संगठन की रिपॉज़िटरी से मेल खाता है, तो वह प्रोजेक्ट उस संगठन में चला जाता है।"$json$::jsonb),
  ('hi', 'projects.personal.empty', $json$"कोई निजी प्रोजेक्ट नहीं।"$json$::jsonb),
  ('hi', 'projects.org.description', $json$"इस कंप्यूटर के वे प्रोजेक्ट जिनका git remote इस संगठन की किसी रिपॉज़िटरी से मेल खाता है। इन पर संगठन की LLM नीति लागू होती है।"$json$::jsonb),
  ('hi', 'projects.org.empty', $json$"आपका कोई प्रोजेक्ट अभी इस संगठन में नहीं है। जब किसी प्रोजेक्ट का कोई git remote संगठन में दर्ज किसी रिपॉज़िटरी से मेल खाता है, तो वह इसमें शामिल हो जाता है।"$json$::jsonb),
  ('hi', 'projects.org.open', $json$"संगठन खोलें"$json$::jsonb),
  ('hi', 'org.tab.projects', $json$"आपके प्रोजेक्ट"$json$::jsonb),
  ('hi', 'org.projects.title', $json$"इस संगठन में आपके प्रोजेक्ट"$json$::jsonb),
  ('hi', 'org.projects.description', $json$"इस कंप्यूटर के वे प्रोजेक्ट जो अपने git remote के ज़रिए इस संगठन में शामिल हुए।"$json$::jsonb),
  ('ar', 'project.scope.personal', $json$"مشروع شخصي"$json$::jsonb),
  ('ar', 'projects.count', $json${"zero": "لا مشاريع", "one": "مشروع واحد", "two": "مشروعان", "few": "{count} مشاريع", "many": "{count} مشروعًا", "other": "{count} مشروع"}$json$::jsonb),
  ('ar', 'projects.scope.label', $json$"عرض المشاريع من"$json$::jsonb),
  ('ar', 'projects.scope.all', $json$"الكل"$json$::jsonb),
  ('ar', 'projects.scope.personal', $json$"شخصية"$json$::jsonb),
  ('ar', 'projects.personal.title', $json$"المشاريع الشخصية"$json$::jsonb),
  ('ar', 'projects.personal.description', $json$"أنت وحدك من يعمل عليها. ينتقل المشروع إلى مؤسسة عندما يطابق أحد مستودعات git البعيدة الخاصة به مستودعًا لتلك المؤسسة."$json$::jsonb),
  ('ar', 'projects.personal.empty', $json$"لا توجد مشاريع شخصية."$json$::jsonb),
  ('ar', 'projects.org.description', $json$"مشاريع هذا الجهاز التي يطابق مستودع git البعيد الخاص بها مستودعًا لهذه المؤسسة. تنطبق عليها سياسة LLM الخاصة بالمؤسسة."$json$::jsonb),
  ('ar', 'projects.org.empty', $json$"لم ينضم أي من مشاريعك إلى هذه المؤسسة بعد. ينضم المشروع عندما يطابق أحد مستودعات git البعيدة الخاصة به مستودعًا مسجلًا في المؤسسة."$json$::jsonb),
  ('ar', 'projects.org.open', $json$"فتح المؤسسة"$json$::jsonb),
  ('ar', 'org.tab.projects', $json$"مشاريعك"$json$::jsonb),
  ('ar', 'org.projects.title', $json$"مشاريعك في هذه المؤسسة"$json$::jsonb),
  ('ar', 'org.projects.description', $json$"مشاريع هذا الجهاز التي انضمت إلى هذه المؤسسة عبر مستودع git البعيد."$json$::jsonb),
  ('fr', 'project.scope.personal', $json$"Projet personnel"$json$::jsonb),
  ('fr', 'projects.count', $json${"one": "{count} projet", "other": "{count} projets"}$json$::jsonb),
  ('fr', 'projects.scope.label', $json$"Afficher les projets de"$json$::jsonb),
  ('fr', 'projects.scope.all', $json$"Tous"$json$::jsonb),
  ('fr', 'projects.scope.personal', $json$"Personnels"$json$::jsonb),
  ('fr', 'projects.personal.title', $json$"Projets personnels"$json$::jsonb),
  ('fr', 'projects.personal.description', $json$"Vous seul y travaillez. Un projet passe dans une organisation lorsqu'un de ses remotes git correspond à un dépôt de cette organisation."$json$::jsonb),
  ('fr', 'projects.personal.empty', $json$"Aucun projet personnel."$json$::jsonb),
  ('fr', 'projects.org.description', $json$"Projets de cet ordinateur dont le remote git correspond à un dépôt de cette organisation. Sa politique LLM s'y applique."$json$::jsonb),
  ('fr', 'projects.org.empty', $json$"Aucun de vos projets n'appartient encore à cette organisation. Un projet y entre lorsqu'un de ses remotes git correspond à un dépôt enregistré dans l'organisation."$json$::jsonb),
  ('fr', 'projects.org.open', $json$"Ouvrir l'organisation"$json$::jsonb),
  ('fr', 'org.tab.projects', $json$"Vos projets"$json$::jsonb),
  ('fr', 'org.projects.title', $json$"Vos projets dans cette organisation"$json$::jsonb),
  ('fr', 'org.projects.description', $json$"Projets de cet ordinateur entrés dans cette organisation par leur remote git."$json$::jsonb),
  ('ru', 'project.scope.personal', $json$"Личный проект"$json$::jsonb),
  ('ru', 'projects.count', $json${"one": "{count} проект", "few": "{count} проекта", "many": "{count} проектов", "other": "{count} проекта"}$json$::jsonb),
  ('ru', 'projects.scope.label', $json$"Показать проекты"$json$::jsonb),
  ('ru', 'projects.scope.all', $json$"Все"$json$::jsonb),
  ('ru', 'projects.scope.personal', $json$"Личные"$json$::jsonb),
  ('ru', 'projects.personal.title', $json$"Личные проекты"$json$::jsonb),
  ('ru', 'projects.personal.description', $json$"Над ними работаете только вы. Проект переходит в организацию, когда один из его git-remote совпадает с репозиторием этой организации."$json$::jsonb),
  ('ru', 'projects.personal.empty', $json$"Личных проектов нет."$json$::jsonb),
  ('ru', 'projects.org.description', $json$"Проекты на этом компьютере, чей git-remote совпадает с репозиторием этой организации. К ним применяется её политика LLM."$json$::jsonb),
  ('ru', 'projects.org.empty', $json$"Ни один из ваших проектов пока не входит в эту организацию. Проект попадает в неё, когда один из его git-remote совпадает с репозиторием, добавленным в организацию."$json$::jsonb),
  ('ru', 'projects.org.open', $json$"Открыть организацию"$json$::jsonb),
  ('ru', 'org.tab.projects', $json$"Ваши проекты"$json$::jsonb),
  ('ru', 'org.projects.title', $json$"Ваши проекты в этой организации"$json$::jsonb),
  ('ru', 'org.projects.description', $json$"Проекты на этом компьютере, вошедшие в организацию через git-remote."$json$::jsonb),
  ('ja', 'project.scope.personal', $json$"個人のプロジェクト"$json$::jsonb),
  ('ja', 'projects.count', $json${"other": "プロジェクト {count} 件"}$json$::jsonb),
  ('ja', 'projects.scope.label', $json$"表示するプロジェクト"$json$::jsonb),
  ('ja', 'projects.scope.all', $json$"すべて"$json$::jsonb),
  ('ja', 'projects.scope.personal', $json$"個人"$json$::jsonb),
  ('ja', 'projects.personal.title', $json$"個人のプロジェクト"$json$::jsonb),
  ('ja', 'projects.personal.description', $json$"あなただけが作業するプロジェクトです。git リモートのいずれかが組織のリポジトリと一致すると、そのプロジェクトは組織に移ります。"$json$::jsonb),
  ('ja', 'projects.personal.empty', $json$"個人のプロジェクトはありません。"$json$::jsonb),
  ('ja', 'projects.org.description', $json$"git リモートがこの組織のリポジトリと一致する、このコンピューター上のプロジェクトです。組織の LLM ポリシーが適用されます。"$json$::jsonb),
  ('ja', 'projects.org.empty', $json$"まだこの組織に属するプロジェクトはありません。git リモートのいずれかが組織に登録されたリポジトリと一致すると、プロジェクトが加わります。"$json$::jsonb),
  ('ja', 'projects.org.open', $json$"組織を開く"$json$::jsonb),
  ('ja', 'org.tab.projects', $json$"あなたのプロジェクト"$json$::jsonb),
  ('ja', 'org.projects.title', $json$"この組織でのあなたのプロジェクト"$json$::jsonb),
  ('ja', 'org.projects.description', $json$"git リモートを通じてこの組織に加わった、このコンピューター上のプロジェクトです。"$json$::jsonb),
  ('de', 'project.scope.personal', $json$"Persönliches Projekt"$json$::jsonb),
  ('de', 'projects.count', $json${"one": "{count} Projekt", "other": "{count} Projekte"}$json$::jsonb),
  ('de', 'projects.scope.label', $json$"Projekte anzeigen von"$json$::jsonb),
  ('de', 'projects.scope.all', $json$"Alle"$json$::jsonb),
  ('de', 'projects.scope.personal', $json$"Persönlich"$json$::jsonb),
  ('de', 'projects.personal.title', $json$"Persönliche Projekte"$json$::jsonb),
  ('de', 'projects.personal.description', $json$"Nur du arbeitest daran. Ein Projekt wechselt in eine Organisation, sobald einer seiner Git-Remotes zu einem Repository dieser Organisation passt."$json$::jsonb),
  ('de', 'projects.personal.empty', $json$"Keine persönlichen Projekte."$json$::jsonb),
  ('de', 'projects.org.description', $json$"Projekte auf diesem Computer, deren Git-Remote zu einem Repository dieser Organisation passt. Ihre LLM-Richtlinie gilt für sie."$json$::jsonb),
  ('de', 'projects.org.empty', $json$"Noch keines deiner Projekte gehört zu dieser Organisation. Ein Projekt kommt hinzu, sobald einer seiner Git-Remotes zu einem in der Organisation eingetragenen Repository passt."$json$::jsonb),
  ('de', 'projects.org.open', $json$"Organisation öffnen"$json$::jsonb),
  ('de', 'org.tab.projects', $json$"Deine Projekte"$json$::jsonb),
  ('de', 'org.projects.title', $json$"Deine Projekte in dieser Organisation"$json$::jsonb),
  ('de', 'org.projects.description', $json$"Projekte auf diesem Computer, die über ihren Git-Remote dieser Organisation beigetreten sind."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
