-- v0.61.0: os textos do painel de andamento à esquerda do chat, do botão de
-- parar no lugar de enviar e do seguir no editor do Ao vivo, mais as novidades
-- da versão.

insert into public.translations (locale, key, value) values
  ('en', 'progress.title', $json$"Progress"$json$::jsonb),
  ('en', 'progress.idle', $json$"Nothing running. The steps of the next request appear here, one per line."$json$::jsonb),
  ('en', 'progress.collapse', $json$"Hide the progress panel"$json$::jsonb),
  ('en', 'progress.expand', $json$"Show the progress panel"$json$::jsonb),
  ('en', 'live.editor.armed', $json$"{editor} will open the first file the agent changes."$json$::jsonb),
  ('en', 'live.editor.missing', $json$"No VS Code, Cursor or Windsurf command found on this computer's PATH, so files can only be followed here."$json$::jsonb),
  ('en', 'whatsNew.item.progressPanel.title', $json$"Progress panel beside the chat"$json$::jsonb),
  ('en', 'whatsNew.item.progressPanel.detail', $json$"What JayV is doing now moved from above the message box to a panel on the left, next to the side menu, with each step on its own line. The repositories of an organization chat live in the same panel, so the conversation gets the full width and the bubble keeps only the answer. The panel can be collapsed to a thin strip."$json$::jsonb),
  ('en', 'whatsNew.item.stopButton.title', $json$"Stop takes the place of Send while JayV works"$json$::jsonb),
  ('en', 'whatsNew.item.stopButton.detail', $json$"While a request is actually running, the round Send button turns into a Stop button. Enter still queues a new message."$json$::jsonb),
  ('en', 'whatsNew.item.liveEditor.title', $json$"Live follow in your editor answers right away"$json$::jsonb),
  ('en', 'whatsNew.item.liveEditor.detail', $json$"Choosing VS Code, Cursor or Windsurf in the Live panel now opens the file you are looking at there at once, or says that the first changed file will open. When no editor command is found, the panel says so instead of staying silent. Errors from opening the editor are shown."$json$::jsonb),
  ('pt-BR', 'progress.title', $json$"Andamento"$json$::jsonb),
  ('pt-BR', 'progress.idle', $json$"Nada em andamento. As etapas do próximo pedido aparecem aqui, uma por linha."$json$::jsonb),
  ('pt-BR', 'progress.collapse', $json$"Esconder o painel de andamento"$json$::jsonb),
  ('pt-BR', 'progress.expand', $json$"Mostrar o painel de andamento"$json$::jsonb),
  ('pt-BR', 'live.editor.armed', $json$"O {editor} vai abrir o primeiro arquivo que o agente mudar."$json$::jsonb),
  ('pt-BR', 'live.editor.missing', $json$"Nenhum comando do VS Code, Cursor ou Windsurf foi encontrado no PATH deste computador; por isso os arquivos só podem ser acompanhados aqui."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.progressPanel.title', $json$"Painel de andamento ao lado do chat"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.progressPanel.detail', $json$"O que o JayV está fazendo saiu de cima da caixa de mensagem e foi para um painel à esquerda, junto ao menu lateral, com cada etapa em uma linha própria. Os repositórios do chat da organização ficam no mesmo painel, então a conversa ganha a largura toda e o balão guarda só a resposta. O painel pode ser recolhido numa faixa fina."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.stopButton.title', $json$"Parar toma o lugar de Enviar enquanto o JayV trabalha"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.stopButton.detail', $json$"Enquanto um pedido está de fato rodando, o botão redondo de enviar vira um botão de parar. A tecla Enter continua colocando uma nova mensagem na fila."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveEditor.title', $json$"Seguir no editor responde na hora"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveEditor.detail', $json$"Escolher VS Code, Cursor ou Windsurf no painel Ao vivo agora abre lá, na hora, o arquivo que você está vendo, ou avisa que o primeiro arquivo alterado vai abrir. Quando nenhum comando de editor é encontrado, o painel diz isso em vez de ficar em silêncio. Os erros ao abrir o editor aparecem."$json$::jsonb),
  ('es', 'progress.title', $json$"Progreso"$json$::jsonb),
  ('es', 'progress.idle', $json$"Nada en marcha. Los pasos de la próxima solicitud aparecen aquí, uno por línea."$json$::jsonb),
  ('es', 'progress.collapse', $json$"Ocultar el panel de progreso"$json$::jsonb),
  ('es', 'progress.expand', $json$"Mostrar el panel de progreso"$json$::jsonb),
  ('es', 'live.editor.armed', $json$"{editor} abrirá el primer archivo que cambie el agente."$json$::jsonb),
  ('es', 'live.editor.missing', $json$"No se encontró ningún comando de VS Code, Cursor ni Windsurf en el PATH de este equipo, así que los archivos solo se pueden seguir aquí."$json$::jsonb),
  ('es', 'whatsNew.item.progressPanel.title', $json$"Panel de progreso junto al chat"$json$::jsonb),
  ('es', 'whatsNew.item.progressPanel.detail', $json$"Lo que JayV está haciendo pasó de encima del cuadro de mensaje a un panel a la izquierda, junto al menú lateral, con cada paso en su propia línea. Los repositorios del chat de la organización viven en el mismo panel, así que la conversación gana todo el ancho y la burbuja solo guarda la respuesta. El panel se puede plegar en una franja fina."$json$::jsonb),
  ('es', 'whatsNew.item.stopButton.title', $json$"Detener ocupa el lugar de Enviar mientras JayV trabaja"$json$::jsonb),
  ('es', 'whatsNew.item.stopButton.detail', $json$"Mientras una solicitud se está ejecutando, el botón redondo de enviar se convierte en un botón de detener. Enter sigue poniendo un mensaje nuevo en la cola."$json$::jsonb),
  ('es', 'whatsNew.item.liveEditor.title', $json$"Seguir en el editor responde al instante"$json$::jsonb),
  ('es', 'whatsNew.item.liveEditor.detail', $json$"Elegir VS Code, Cursor o Windsurf en el panel En vivo ahora abre allí al instante el archivo que estás viendo, o avisa de que se abrirá el primer archivo cambiado. Si no se encuentra ningún comando de editor, el panel lo dice en lugar de callar. Los errores al abrir el editor se muestran."$json$::jsonb),
  ('fr', 'progress.title', $json$"Progression"$json$::jsonb),
  ('fr', 'progress.idle', $json$"Rien en cours. Les étapes de la prochaine demande apparaissent ici, une par ligne."$json$::jsonb),
  ('fr', 'progress.collapse', $json$"Masquer le panneau de progression"$json$::jsonb),
  ('fr', 'progress.expand', $json$"Afficher le panneau de progression"$json$::jsonb),
  ('fr', 'live.editor.armed', $json$"{editor} ouvrira le premier fichier modifié par l'agent."$json$::jsonb),
  ('fr', 'live.editor.missing', $json$"Aucune commande VS Code, Cursor ou Windsurf trouvée dans le PATH de cet ordinateur : les fichiers ne peuvent être suivis qu'ici."$json$::jsonb),
  ('fr', 'whatsNew.item.progressPanel.title', $json$"Panneau de progression à côté du chat"$json$::jsonb),
  ('fr', 'whatsNew.item.progressPanel.detail', $json$"Ce que JayV fait en ce moment a quitté le dessus de la zone de message pour un panneau à gauche, près du menu latéral, chaque étape sur sa propre ligne. Les dépôts d'un chat d'organisation vivent dans le même panneau : la conversation prend toute la largeur et la bulle ne garde que la réponse. Le panneau peut se replier en bandeau fin."$json$::jsonb),
  ('fr', 'whatsNew.item.stopButton.title', $json$"Arrêter prend la place d'Envoyer pendant que JayV travaille"$json$::jsonb),
  ('fr', 'whatsNew.item.stopButton.detail', $json$"Tant qu'une demande s'exécute vraiment, le bouton rond d'envoi devient un bouton d'arrêt. La touche Entrée met toujours un nouveau message en file."$json$::jsonb),
  ('fr', 'whatsNew.item.liveEditor.title', $json$"Le suivi dans l'éditeur répond tout de suite"$json$::jsonb),
  ('fr', 'whatsNew.item.liveEditor.detail', $json$"Choisir VS Code, Cursor ou Windsurf dans le panneau En direct ouvre maintenant aussitôt le fichier affiché, ou annonce que le premier fichier modifié s'ouvrira. Si aucune commande d'éditeur n'est trouvée, le panneau le dit au lieu de rester muet. Les erreurs d'ouverture de l'éditeur s'affichent."$json$::jsonb),
  ('de', 'progress.title', $json$"Fortschritt"$json$::jsonb),
  ('de', 'progress.idle', $json$"Nichts läuft. Die Schritte der nächsten Anfrage erscheinen hier, einer pro Zeile."$json$::jsonb),
  ('de', 'progress.collapse', $json$"Fortschrittsfenster ausblenden"$json$::jsonb),
  ('de', 'progress.expand', $json$"Fortschrittsfenster einblenden"$json$::jsonb),
  ('de', 'live.editor.armed', $json$"{editor} öffnet die erste Datei, die der Agent ändert."$json$::jsonb),
  ('de', 'live.editor.missing', $json$"Kein VS-Code-, Cursor- oder Windsurf-Befehl im PATH dieses Computers gefunden; Dateien lassen sich nur hier verfolgen."$json$::jsonb),
  ('de', 'whatsNew.item.progressPanel.title', $json$"Fortschrittsfenster neben dem Chat"$json$::jsonb),
  ('de', 'whatsNew.item.progressPanel.detail', $json$"Was JayV gerade tut, wanderte von über dem Nachrichtenfeld in ein Fenster links neben dem Seitenmenü, jeder Schritt in einer eigenen Zeile. Die Repositories eines Organisations-Chats stehen im selben Fenster, so bekommt das Gespräch die volle Breite und die Blase behält nur die Antwort. Das Fenster lässt sich zu einem schmalen Streifen einklappen."$json$::jsonb),
  ('de', 'whatsNew.item.stopButton.title', $json$"Stopp ersetzt Senden, solange JayV arbeitet"$json$::jsonb),
  ('de', 'whatsNew.item.stopButton.detail', $json$"Läuft eine Anfrage tatsächlich, wird der runde Senden-Knopf zum Stopp-Knopf. Die Eingabetaste stellt weiterhin eine neue Nachricht in die Warteschlange."$json$::jsonb),
  ('de', 'whatsNew.item.liveEditor.title', $json$"Live im Editor folgen reagiert sofort"$json$::jsonb),
  ('de', 'whatsNew.item.liveEditor.detail', $json$"Wer im Live-Fenster VS Code, Cursor oder Windsurf wählt, öffnet dort jetzt sofort die angezeigte Datei oder erfährt, dass die erste geänderte Datei geöffnet wird. Wird kein Editor-Befehl gefunden, sagt das Fenster es, statt zu schweigen. Fehler beim Öffnen des Editors werden angezeigt."$json$::jsonb),
  ('ru', 'progress.title', $json$"Ход работы"$json$::jsonb),
  ('ru', 'progress.idle', $json$"Ничего не выполняется. Шаги следующего запроса появятся здесь, по одному в строке."$json$::jsonb),
  ('ru', 'progress.collapse', $json$"Скрыть панель хода работы"$json$::jsonb),
  ('ru', 'progress.expand', $json$"Показать панель хода работы"$json$::jsonb),
  ('ru', 'live.editor.armed', $json$"{editor} откроет первый файл, который изменит агент."$json$::jsonb),
  ('ru', 'live.editor.missing', $json$"В PATH этого компьютера не найдено команд VS Code, Cursor или Windsurf, поэтому следить за файлами можно только здесь."$json$::jsonb),
  ('ru', 'whatsNew.item.progressPanel.title', $json$"Панель хода работы рядом с чатом"$json$::jsonb),
  ('ru', 'whatsNew.item.progressPanel.detail', $json$"То, что сейчас делает JayV, переехало из-над поля сообщения в панель слева, рядом с боковым меню, каждый шаг в своей строке. Репозитории чата организации находятся в той же панели, поэтому беседа получает всю ширину, а в пузыре остаётся только ответ. Панель можно свернуть в тонкую полосу."$json$::jsonb),
  ('ru', 'whatsNew.item.stopButton.title', $json$"Стоп занимает место Отправки, пока JayV работает"$json$::jsonb),
  ('ru', 'whatsNew.item.stopButton.detail', $json$"Пока запрос действительно выполняется, круглая кнопка отправки превращается в кнопку остановки. Enter по-прежнему ставит новое сообщение в очередь."$json$::jsonb),
  ('ru', 'whatsNew.item.liveEditor.title', $json$"Слежение в редакторе отвечает сразу"$json$::jsonb),
  ('ru', 'whatsNew.item.liveEditor.detail', $json$"Выбор VS Code, Cursor или Windsurf в панели «Вживую» теперь сразу открывает там просматриваемый файл или сообщает, что откроется первый изменённый файл. Если команда редактора не найдена, панель говорит об этом, а не молчит. Ошибки открытия редактора показываются."$json$::jsonb),
  ('zh-CN', 'progress.title', $json$"进度"$json$::jsonb),
  ('zh-CN', 'progress.idle', $json$"当前没有任务。下一个请求的步骤会在这里显示，每行一步。"$json$::jsonb),
  ('zh-CN', 'progress.collapse', $json$"隐藏进度面板"$json$::jsonb),
  ('zh-CN', 'progress.expand', $json$"显示进度面板"$json$::jsonb),
  ('zh-CN', 'live.editor.armed', $json$"{editor} 将打开代理修改的第一个文件。"$json$::jsonb),
  ('zh-CN', 'live.editor.missing', $json$"在这台电脑的 PATH 中没有找到 VS Code、Cursor 或 Windsurf 命令，因此只能在这里查看文件。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.progressPanel.title', $json$"聊天旁的进度面板"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.progressPanel.detail', $json$"JayV 正在做的事从消息框上方移到了左侧、侧边菜单旁的面板中，每一步各占一行。组织聊天的仓库也在同一面板里，因此对话占满整个宽度，气泡只保留回答。面板可以收起为细条。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.stopButton.title', $json$"JayV 工作时，“停止”取代“发送”"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.stopButton.detail', $json$"请求真正运行时，圆形的发送按钮会变成停止按钮。按回车仍会把新消息排入队列。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveEditor.title', $json$"在编辑器中跟随会立即响应"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveEditor.detail', $json$"在“实时”面板中选择 VS Code、Cursor 或 Windsurf 后，现在会立即在其中打开你正在查看的文件，或提示将打开第一个被修改的文件。找不到编辑器命令时，面板会说明，而不是保持沉默。打开编辑器时的错误也会显示。"$json$::jsonb),
  ('ja', 'progress.title', $json$"進行状況"$json$::jsonb),
  ('ja', 'progress.idle', $json$"実行中のものはありません。次のリクエストのステップが、1行ずつここに表示されます。"$json$::jsonb),
  ('ja', 'progress.collapse', $json$"進行状況パネルを隠す"$json$::jsonb),
  ('ja', 'progress.expand', $json$"進行状況パネルを表示"$json$::jsonb),
  ('ja', 'live.editor.armed', $json$"{editor} がエージェントの変更した最初のファイルを開きます。"$json$::jsonb),
  ('ja', 'live.editor.missing', $json$"このコンピューターの PATH に VS Code・Cursor・Windsurf のコマンドが見つからないため、ファイルはここでしか追えません。"$json$::jsonb),
  ('ja', 'whatsNew.item.progressPanel.title', $json$"チャットの横の進行状況パネル"$json$::jsonb),
  ('ja', 'whatsNew.item.progressPanel.detail', $json$"JayV がいま行っていることが、メッセージ欄の上から、サイドメニューの隣の左パネルに移り、各ステップが1行ずつ表示されます。組織チャットのリポジトリも同じパネルにあるので、会話が全幅を使え、吹き出しには回答だけが残ります。パネルは細い帯に折りたためます。"$json$::jsonb),
  ('ja', 'whatsNew.item.stopButton.title', $json$"JayV の作業中は送信の代わりに停止を表示"$json$::jsonb),
  ('ja', 'whatsNew.item.stopButton.detail', $json$"リクエストが実際に動いている間、丸い送信ボタンは停止ボタンに変わります。Enter キーは今までどおり新しいメッセージをキューに入れます。"$json$::jsonb),
  ('ja', 'whatsNew.item.liveEditor.title', $json$"エディターでの追従がすぐ反応"$json$::jsonb),
  ('ja', 'whatsNew.item.liveEditor.detail', $json$"ライブパネルで VS Code・Cursor・Windsurf を選ぶと、見ているファイルをすぐそこで開くか、最初に変更されたファイルが開くことを知らせます。エディターのコマンドが見つからない場合は、黙らずパネルがそう伝えます。エディターを開くときのエラーも表示されます。"$json$::jsonb),
  ('ar', 'progress.title', $json$"التقدّم"$json$::jsonb),
  ('ar', 'progress.idle', $json$"لا شيء قيد التنفيذ. تظهر هنا خطوات الطلب التالي، خطوة في كل سطر."$json$::jsonb),
  ('ar', 'progress.collapse', $json$"إخفاء لوحة التقدّم"$json$::jsonb),
  ('ar', 'progress.expand', $json$"إظهار لوحة التقدّم"$json$::jsonb),
  ('ar', 'live.editor.armed', $json$"سيفتح {editor} أول ملف يغيّره الوكيل."$json$::jsonb),
  ('ar', 'live.editor.missing', $json$"لم يُعثر على أمر VS Code أو Cursor أو Windsurf في PATH لهذا الحاسوب، لذا يمكن متابعة الملفات هنا فقط."$json$::jsonb),
  ('ar', 'whatsNew.item.progressPanel.title', $json$"لوحة التقدّم بجانب الدردشة"$json$::jsonb),
  ('ar', 'whatsNew.item.progressPanel.detail', $json$"انتقل ما يفعله JayV الآن من فوق مربع الرسالة إلى لوحة على اليسار بجانب القائمة الجانبية، وكل خطوة في سطر خاص بها. ومستودعات دردشة المؤسسة في اللوحة نفسها، فتأخذ المحادثة العرض كاملًا ولا تحتفظ الفقاعة إلا بالجواب. ويمكن طي اللوحة إلى شريط رفيع."$json$::jsonb),
  ('ar', 'whatsNew.item.stopButton.title', $json$"يحلّ «إيقاف» محل «إرسال» أثناء عمل JayV"$json$::jsonb),
  ('ar', 'whatsNew.item.stopButton.detail', $json$"عندما يعمل الطلب فعلًا يتحول زر الإرسال المستدير إلى زر إيقاف. ويظل مفتاح Enter يضع الرسالة الجديدة في الطابور."$json$::jsonb),
  ('ar', 'whatsNew.item.liveEditor.title', $json$"المتابعة في المحرر تستجيب فورًا"$json$::jsonb),
  ('ar', 'whatsNew.item.liveEditor.detail', $json$"اختيار VS Code أو Cursor أو Windsurf في لوحة «مباشر» يفتح الآن الملف المعروض هناك فورًا، أو يخبرك بأن أول ملف يتغير سيُفتح. وإذا لم يُعثر على أمر المحرر تقول اللوحة ذلك بدل الصمت. وتظهر أخطاء فتح المحرر."$json$::jsonb),
  ('hi', 'progress.title', $json$"प्रगति"$json$::jsonb),
  ('hi', 'progress.idle', $json$"कुछ नहीं चल रहा। अगले अनुरोध के चरण यहाँ दिखेंगे, हर पंक्ति में एक।"$json$::jsonb),
  ('hi', 'progress.collapse', $json$"प्रगति पैनल छिपाएँ"$json$::jsonb),
  ('hi', 'progress.expand', $json$"प्रगति पैनल दिखाएँ"$json$::jsonb),
  ('hi', 'live.editor.armed', $json$"{editor} एजेंट द्वारा बदली गई पहली फ़ाइल खोलेगा।"$json$::jsonb),
  ('hi', 'live.editor.missing', $json$"इस कंप्यूटर के PATH में VS Code, Cursor या Windsurf का कमांड नहीं मिला, इसलिए फ़ाइलों को केवल यहीं देखा जा सकता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.progressPanel.title', $json$"चैट के पास प्रगति पैनल"$json$::jsonb),
  ('hi', 'whatsNew.item.progressPanel.detail', $json$"JayV अभी क्या कर रहा है, यह संदेश बॉक्स के ऊपर से हटकर साइड मेनू के पास बाईं ओर के पैनल में आ गया है, हर चरण अपनी पंक्ति में। संगठन चैट के रिपॉज़िटरी भी उसी पैनल में हैं, इसलिए बातचीत को पूरी चौड़ाई मिलती है और बुलबुले में सिर्फ़ उत्तर रहता है। पैनल को पतली पट्टी में समेटा जा सकता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.stopButton.title', $json$"JayV के काम करते समय भेजें की जगह रोकें"$json$::jsonb),
  ('hi', 'whatsNew.item.stopButton.detail', $json$"जब कोई अनुरोध सचमुच चल रहा हो, गोल भेजें बटन रोकें बटन बन जाता है। Enter अब भी नया संदेश कतार में डालता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.liveEditor.title', $json$"एडिटर में फ़ॉलो करना तुरंत जवाब देता है"$json$::jsonb),
  ('hi', 'whatsNew.item.liveEditor.detail', $json$"लाइव पैनल में VS Code, Cursor या Windsurf चुनने पर अब आप जो फ़ाइल देख रहे हैं वह तुरंत वहाँ खुलती है, या बताया जाता है कि पहली बदली फ़ाइल खुलेगी। एडिटर का कमांड न मिलने पर पैनल चुप रहने के बजाय यह बताता है। एडिटर खोलने की त्रुटियाँ दिखती हैं।"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
