-- A pasta que já é de outro projeto barra o projeto novo, e o balão da
-- resposta diz quem atendeu: o agente (CLI), o modelo, o modo que o Jev
-- escolheu (planejamento ou build) e o papel do agente. A linha da rota
-- ganha chave nova, `beat.routed`, com a rota já montada em `{route}`: a
-- `beat.route` fica como está para quem ainda não atualizou o app.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'project.pathTaken', $json$"Esta pasta já pertence ao projeto “{name}”."$json$::jsonb),
  ('pt-BR', 'beat.routed', $json$"Rota: {route}"$json$::jsonb),
  ('pt-BR', 'route.mode.plan', $json$"Planejamento"$json$::jsonb),
  ('pt-BR', 'route.mode.plan.hint', $json$"Modo planejamento: o agente rodou só com leitura e respondeu com um plano, sem alterar arquivos."$json$::jsonb),
  ('pt-BR', 'route.mode.build', $json$"Build"$json$::jsonb),
  ('pt-BR', 'route.mode.build.hint', $json$"Modo build: o agente pôde alterar arquivos do projeto, dentro das permissões definidas na Configuração do LLM."$json$::jsonb),
  ('pt-BR', 'route.agent.developer', $json$"desenvolvedor"$json$::jsonb),
  ('pt-BR', 'route.agent.frontend', $json$"frontend"$json$::jsonb),
  ('pt-BR', 'route.agent.security', $json$"segurança"$json$::jsonb),
  ('pt-BR', 'route.agent.reviewer', $json$"revisor"$json$::jsonb),
  ('en', 'project.pathTaken', $json$"This folder already belongs to the project “{name}”."$json$::jsonb),
  ('en', 'beat.routed', $json$"Route: {route}"$json$::jsonb),
  ('en', 'route.mode.plan', $json$"Plan"$json$::jsonb),
  ('en', 'route.mode.plan.hint', $json$"Plan mode: the agent ran read-only and answered with a plan, without changing files."$json$::jsonb),
  ('en', 'route.mode.build', $json$"Build"$json$::jsonb),
  ('en', 'route.mode.build.hint', $json$"Build mode: the agent could change files in the project, within the permissions set in LLM settings."$json$::jsonb),
  ('en', 'route.agent.developer', $json$"developer"$json$::jsonb),
  ('en', 'route.agent.frontend', $json$"frontend"$json$::jsonb),
  ('en', 'route.agent.security', $json$"security"$json$::jsonb),
  ('en', 'route.agent.reviewer', $json$"reviewer"$json$::jsonb),
  ('es', 'project.pathTaken', $json$"Esta carpeta ya pertenece al proyecto “{name}”."$json$::jsonb),
  ('es', 'beat.routed', $json$"Ruta: {route}"$json$::jsonb),
  ('es', 'route.mode.plan', $json$"Planificación"$json$::jsonb),
  ('es', 'route.mode.plan.hint', $json$"Modo planificación: el agente se ejecutó solo con lectura y respondió con un plan, sin modificar archivos."$json$::jsonb),
  ('es', 'route.mode.build', $json$"Build"$json$::jsonb),
  ('es', 'route.mode.build.hint', $json$"Modo build: el agente pudo modificar archivos del proyecto, dentro de los permisos definidos en la Configuración del LLM."$json$::jsonb),
  ('es', 'route.agent.developer', $json$"desarrollador"$json$::jsonb),
  ('es', 'route.agent.frontend', $json$"frontend"$json$::jsonb),
  ('es', 'route.agent.security', $json$"seguridad"$json$::jsonb),
  ('es', 'route.agent.reviewer', $json$"revisor"$json$::jsonb),
  ('zh-CN', 'project.pathTaken', $json$"此文件夹已属于项目“{name}”。"$json$::jsonb),
  ('zh-CN', 'beat.routed', $json$"路由：{route}"$json$::jsonb),
  ('zh-CN', 'route.mode.plan', $json$"规划"$json$::jsonb),
  ('zh-CN', 'route.mode.plan.hint', $json$"规划模式：代理以只读方式运行，并给出计划，没有修改任何文件。"$json$::jsonb),
  ('zh-CN', 'route.mode.build', $json$"构建"$json$::jsonb),
  ('zh-CN', 'route.mode.build.hint', $json$"构建模式：代理可以在 LLM 设置所定义的权限内修改项目文件。"$json$::jsonb),
  ('zh-CN', 'route.agent.developer', $json$"开发"$json$::jsonb),
  ('zh-CN', 'route.agent.frontend', $json$"前端"$json$::jsonb),
  ('zh-CN', 'route.agent.security', $json$"安全"$json$::jsonb),
  ('zh-CN', 'route.agent.reviewer', $json$"审查"$json$::jsonb),
  ('hi', 'project.pathTaken', $json$"यह फ़ोल्डर पहले से प्रोजेक्ट “{name}” का है।"$json$::jsonb),
  ('hi', 'beat.routed', $json$"रूट: {route}"$json$::jsonb),
  ('hi', 'route.mode.plan', $json$"योजना"$json$::jsonb),
  ('hi', 'route.mode.plan.hint', $json$"योजना मोड: एजेंट केवल पढ़ने की अनुमति के साथ चला और फ़ाइलें बदले बिना एक योजना दी।"$json$::jsonb),
  ('hi', 'route.mode.build', $json$"बिल्ड"$json$::jsonb),
  ('hi', 'route.mode.build.hint', $json$"बिल्ड मोड: एजेंट LLM सेटिंग्स में तय अनुमतियों के भीतर प्रोजेक्ट की फ़ाइलें बदल सकता था।"$json$::jsonb),
  ('hi', 'route.agent.developer', $json$"डेवलपर"$json$::jsonb),
  ('hi', 'route.agent.frontend', $json$"फ्रंटएंड"$json$::jsonb),
  ('hi', 'route.agent.security', $json$"सुरक्षा"$json$::jsonb),
  ('hi', 'route.agent.reviewer', $json$"समीक्षक"$json$::jsonb),
  ('ar', 'project.pathTaken', $json$"هذا المجلد يتبع بالفعل المشروع «{name}»."$json$::jsonb),
  ('ar', 'beat.routed', $json$"المسار: {route}"$json$::jsonb),
  ('ar', 'route.mode.plan', $json$"تخطيط"$json$::jsonb),
  ('ar', 'route.mode.plan.hint', $json$"وضع التخطيط: عمل الوكيل للقراءة فقط وأجاب بخطة دون تغيير أي ملف."$json$::jsonb),
  ('ar', 'route.mode.build', $json$"تنفيذ"$json$::jsonb),
  ('ar', 'route.mode.build.hint', $json$"وضع التنفيذ: كان بإمكان الوكيل تعديل ملفات المشروع ضمن الأذونات المحددة في إعدادات النموذج اللغوي."$json$::jsonb),
  ('ar', 'route.agent.developer', $json$"مطوّر"$json$::jsonb),
  ('ar', 'route.agent.frontend', $json$"واجهة أمامية"$json$::jsonb),
  ('ar', 'route.agent.security', $json$"أمان"$json$::jsonb),
  ('ar', 'route.agent.reviewer', $json$"مراجع"$json$::jsonb),
  ('fr', 'project.pathTaken', $json$"Ce dossier appartient déjà au projet « {name} »."$json$::jsonb),
  ('fr', 'beat.routed', $json$"Route : {route}"$json$::jsonb),
  ('fr', 'route.mode.plan', $json$"Planification"$json$::jsonb),
  ('fr', 'route.mode.plan.hint', $json$"Mode planification : l’agent a tourné en lecture seule et a répondu par un plan, sans modifier de fichiers."$json$::jsonb),
  ('fr', 'route.mode.build', $json$"Build"$json$::jsonb),
  ('fr', 'route.mode.build.hint', $json$"Mode build : l’agent pouvait modifier les fichiers du projet, dans les limites des permissions définies dans les réglages du LLM."$json$::jsonb),
  ('fr', 'route.agent.developer', $json$"développeur"$json$::jsonb),
  ('fr', 'route.agent.frontend', $json$"frontend"$json$::jsonb),
  ('fr', 'route.agent.security', $json$"sécurité"$json$::jsonb),
  ('fr', 'route.agent.reviewer', $json$"relecteur"$json$::jsonb),
  ('ru', 'project.pathTaken', $json$"Эта папка уже принадлежит проекту «{name}»."$json$::jsonb),
  ('ru', 'beat.routed', $json$"Маршрут: {route}"$json$::jsonb),
  ('ru', 'route.mode.plan', $json$"Планирование"$json$::jsonb),
  ('ru', 'route.mode.plan.hint', $json$"Режим планирования: агент работал только на чтение и ответил планом, не изменяя файлы."$json$::jsonb),
  ('ru', 'route.mode.build', $json$"Сборка"$json$::jsonb),
  ('ru', 'route.mode.build.hint', $json$"Режим сборки: агент мог изменять файлы проекта в пределах разрешений, заданных в настройках LLM."$json$::jsonb),
  ('ru', 'route.agent.developer', $json$"разработчик"$json$::jsonb),
  ('ru', 'route.agent.frontend', $json$"фронтенд"$json$::jsonb),
  ('ru', 'route.agent.security', $json$"безопасность"$json$::jsonb),
  ('ru', 'route.agent.reviewer', $json$"ревьюер"$json$::jsonb),
  ('ja', 'project.pathTaken', $json$"このフォルダーはすでにプロジェクト「{name}」で使われています。"$json$::jsonb),
  ('ja', 'beat.routed', $json$"ルート：{route}"$json$::jsonb),
  ('ja', 'route.mode.plan', $json$"計画"$json$::jsonb),
  ('ja', 'route.mode.plan.hint', $json$"計画モード：エージェントは読み取り専用で動作し、ファイルを変更せずに計画を返しました。"$json$::jsonb),
  ('ja', 'route.mode.build', $json$"ビルド"$json$::jsonb),
  ('ja', 'route.mode.build.hint', $json$"ビルドモード：エージェントは LLM 設定で許可された範囲でプロジェクトのファイルを変更できました。"$json$::jsonb),
  ('ja', 'route.agent.developer', $json$"開発者"$json$::jsonb),
  ('ja', 'route.agent.frontend', $json$"フロントエンド"$json$::jsonb),
  ('ja', 'route.agent.security', $json$"セキュリティ"$json$::jsonb),
  ('ja', 'route.agent.reviewer', $json$"レビュアー"$json$::jsonb),
  ('de', 'project.pathTaken', $json$"Dieser Ordner gehört bereits zum Projekt „{name}“."$json$::jsonb),
  ('de', 'beat.routed', $json$"Route: {route}"$json$::jsonb),
  ('de', 'route.mode.plan', $json$"Planung"$json$::jsonb),
  ('de', 'route.mode.plan.hint', $json$"Planungsmodus: Der Agent lief schreibgeschützt und antwortete mit einem Plan, ohne Dateien zu ändern."$json$::jsonb),
  ('de', 'route.mode.build', $json$"Build"$json$::jsonb),
  ('de', 'route.mode.build.hint', $json$"Build-Modus: Der Agent durfte Projektdateien ändern, im Rahmen der Berechtigungen aus den LLM-Einstellungen."$json$::jsonb),
  ('de', 'route.agent.developer', $json$"Entwickler"$json$::jsonb),
  ('de', 'route.agent.frontend', $json$"Frontend"$json$::jsonb),
  ('de', 'route.agent.security', $json$"Sicherheit"$json$::jsonb),
  ('de', 'route.agent.reviewer', $json$"Reviewer"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
