-- v0.64.0: estados honestos. A resposta que a portaria de saída não segurou
-- deixa de ficar verde e aparece como não verificada (o JayV não roda teste,
-- build nem lint), e o botão "O que foi conferido" separa o que o JayV
-- observou, o que um modelo disse e o que ficou sem verificação. Inclui a
-- novidade da versão e a página answerEvidence da Documentação.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'verdict.unverified', $json$"não verificada"$json$::jsonb),
  ('pt-BR', 'verdict.unverified.hint', $json$"O JayV não rodou teste, build nem lint para esta resposta. Abra “O que foi conferido” para ver o que ele conferiu."$json$::jsonb),
  ('pt-BR', 'evidence.toggle', $json$"O que foi conferido"$json$::jsonb),
  ('pt-BR', 'evidence.loading', $json$"Lendo o que foi conferido…"$json$::jsonb),
  ('pt-BR', 'evidence.observed', $json$"Observado pelo JayV"$json$::jsonb),
  ('pt-BR', 'evidence.inferred', $json$"Dito por um modelo, sem conferência"$json$::jsonb),
  ('pt-BR', 'evidence.unverified', $json$"Não verificado"$json$::jsonb),
  ('pt-BR', 'evidence.entry', $json$"Portaria de entrada: o pedido fez {score} de 100 para um {scope} (o mínimo é {demand})."$json$::jsonb),
  ('pt-BR', 'evidence.exit.none', $json$"Portaria de saída: a resposta não citou comando para rodar nem arquivo para mudar."$json$::jsonb),
  ('pt-BR', 'evidence.exit.commands', $json${"one": "Portaria de saída: {count} comando da resposta foi conferido com as regras da casa.", "other": "Portaria de saída: {count} comandos da resposta foram conferidos com as regras da casa."}$json$::jsonb),
  ('pt-BR', 'evidence.exit.files', $json${"one": "Portaria de saída: {count} arquivo da resposta foi conferido com as regras da casa.", "other": "Portaria de saída: {count} arquivos da resposta foram conferidos com as regras da casa."}$json$::jsonb),
  ('pt-BR', 'evidence.exit.held', $json$"Segurado por {rule}: {target} ({kind})."$json$::jsonb),
  ('pt-BR', 'evidence.answer', $json$"A resposta do agente: o que ele diz ter rodado, testado ou terminado não foi conferido pelo JayV."$json$::jsonb),
  ('pt-BR', 'evidence.review', $json${"one": "Segunda opinião do {agent} ({model}) sobre {count} arquivo alterado: a leitura de outro modelo, não um teste.", "other": "Segunda opinião do {agent} ({model}) sobre {count} arquivos alterados: a leitura de outro modelo, não um teste."}$json$::jsonb),
  ('pt-BR', 'evidence.review.missing', $json$"Uma segunda opinião do {agent} foi pedida, mas não chegou."$json$::jsonb),
  ('pt-BR', 'evidence.noChecks', $json$"O JayV não rodou teste, build nem lint neste turno."$json$::jsonb),
  ('pt-BR', 'evidence.done.declared', $json$"O pedido diz como saber que ficou pronto, mas o JayV não conferiu esse critério."$json$::jsonb),
  ('pt-BR', 'evidence.done.missing', $json$"O pedido não disse como saber que ficou pronto, então não havia critério para conferir."$json$::jsonb),
  ('pt-BR', 'evidence.disclaimer', $json$"O JayV não garante que uma mudança está correta: só o que está em “Observado pelo JayV” foi conferido pelo próprio JayV."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.honestVerdicts.title', $json$"As respostas dizem o que foi conferido de verdade"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.honestVerdicts.detail', $json$"Uma resposta não fica mais verde só por ter passado pelas regras da casa. A menos que a portaria de saída tenha segurado algo, ela aparece como não verificada, porque o JayV não rodou teste, build nem lint nela. O novo botão O que foi conferido, embaixo de cada resposta, separa o que o JayV observou (as portarias de entrada e de saída), o que um modelo disse sem ninguém conferir (a resposta do agente e a segunda opinião) e o que ainda não foi verificado. No modo Desenvolvimento, o agente também é instruído a terminar dizendo o que rodou, o que supõe e o que não verificou."$json$::jsonb),
  ('pt-BR', 'docs.answerEvidence.title', $json$"O que foi conferido"$json$::jsonb),
  ('pt-BR', 'docs.answerEvidence.summary', $json$"Cada resposta mostra o que o JayV observou, o que um modelo apenas disse e o que ainda não foi verificado, em vez de uma luz verde que ninguém mediu."$json$::jsonb),
  ('pt-BR', 'docs.answerEvidence.usage', $json$"Uma resposta que a portaria de saída não segurou aparece como não verificada, porque o JayV não roda teste, build nem lint nela. Clique em O que foi conferido, embaixo da resposta, para ver a nota da portaria de entrada, os comandos e arquivos que a portaria de saída conferiu, a segunda opinião, se houve, e o que o JayV não verificou, como os testes e o próprio critério de pronto do pedido. No modo Desenvolvimento, o agente é instruído a terminar dizendo o que rodou, o que supõe e o que não verificou."$json$::jsonb),
  ('en', 'verdict.unverified', $json$"not verified"$json$::jsonb),
  ('en', 'verdict.unverified.hint', $json$"JayV ran no test, build or lint for this answer. Open “What was checked” to see what it did check."$json$::jsonb),
  ('en', 'evidence.toggle', $json$"What was checked"$json$::jsonb),
  ('en', 'evidence.loading', $json$"Reading what was checked…"$json$::jsonb),
  ('en', 'evidence.observed', $json$"Observed by JayV"$json$::jsonb),
  ('en', 'evidence.inferred', $json$"Said by a model, not checked"$json$::jsonb),
  ('en', 'evidence.unverified', $json$"Not verified"$json$::jsonb),
  ('en', 'evidence.entry', $json$"Entry gate: the request scored {score} out of 100 for a {scope} (the minimum is {demand})."$json$::jsonb),
  ('en', 'evidence.exit.none', $json$"Exit gate: the answer named no command to run and no file to change."$json$::jsonb),
  ('en', 'evidence.exit.commands', $json${"one": "Exit gate: {count} command in the answer was checked against the house rules.", "other": "Exit gate: {count} commands in the answer were checked against the house rules."}$json$::jsonb),
  ('en', 'evidence.exit.files', $json${"one": "Exit gate: {count} file in the answer was checked against the house rules.", "other": "Exit gate: {count} files in the answer were checked against the house rules."}$json$::jsonb),
  ('en', 'evidence.exit.held', $json$"Held by {rule}: {target} ({kind})."$json$::jsonb),
  ('en', 'evidence.answer', $json$"The agent's answer: whatever it says it ran, tested or finished was not checked by JayV."$json$::jsonb),
  ('en', 'evidence.review', $json${"one": "Second opinion from {agent} ({model}) on {count} changed file: another model's reading, not a test.", "other": "Second opinion from {agent} ({model}) on {count} changed files: another model's reading, not a test."}$json$::jsonb),
  ('en', 'evidence.review.missing', $json$"A second opinion from {agent} was requested but has not arrived."$json$::jsonb),
  ('en', 'evidence.noChecks', $json$"JayV ran no test, build or lint in this turn."$json$::jsonb),
  ('en', 'evidence.done.declared', $json$"The request says how to know it is done, but JayV did not check that criterion."$json$::jsonb),
  ('en', 'evidence.done.missing', $json$"The request did not say how to know it is done, so there was no criterion to check against."$json$::jsonb),
  ('en', 'evidence.disclaimer', $json$"JayV does not guarantee that a change is correct: only what is under “Observed by JayV” was checked by JayV itself."$json$::jsonb),
  ('en', 'whatsNew.item.honestVerdicts.title', $json$"Answers say what was really checked"$json$::jsonb),
  ('en', 'whatsNew.item.honestVerdicts.detail', $json$"An answer no longer turns green just because it passed the house rules. Unless the exit gate held something, it shows as not verified, because JayV ran no test, build or lint on it. The new What was checked button under each answer separates what JayV observed (the entry and exit gates), what a model said without anyone checking it (the agent's answer and the second opinion) and what is still not verified. In Development mode the agent is also asked to end with what it ran, what it assumes and what it did not verify."$json$::jsonb),
  ('en', 'docs.answerEvidence.title', $json$"What was checked"$json$::jsonb),
  ('en', 'docs.answerEvidence.summary', $json$"Each answer shows what JayV observed, what a model only said, and what is still not verified, instead of a green light that nobody measured."$json$::jsonb),
  ('en', 'docs.answerEvidence.usage', $json$"An answer the exit gate did not hold shows as not verified, because JayV runs no test, build or lint on it. Click What was checked under the answer to see the entry gate score, the commands and files the exit gate checked, the second opinion if one ran, and what JayV did not verify, such as tests and the request's own done criterion. In Development mode the agent is asked to end with what it ran, what it assumes and what it did not verify."$json$::jsonb),
  ('es', 'verdict.unverified', $json$"no verificada"$json$::jsonb),
  ('es', 'verdict.unverified.hint', $json$"JayV no ejecutó ninguna prueba, build ni lint para esta respuesta. Abre «Qué se comprobó» para ver lo que sí comprobó."$json$::jsonb),
  ('es', 'evidence.toggle', $json$"Qué se comprobó"$json$::jsonb),
  ('es', 'evidence.loading', $json$"Leyendo lo que se comprobó…"$json$::jsonb),
  ('es', 'evidence.observed', $json$"Observado por JayV"$json$::jsonb),
  ('es', 'evidence.inferred', $json$"Dicho por un modelo, sin comprobar"$json$::jsonb),
  ('es', 'evidence.unverified', $json$"No verificado"$json$::jsonb),
  ('es', 'evidence.entry', $json$"Portería de entrada: la solicitud obtuvo {score} de 100 para un {scope} (el mínimo es {demand})."$json$::jsonb),
  ('es', 'evidence.exit.none', $json$"Portería de salida: la respuesta no nombró ningún comando que ejecutar ni archivo que cambiar."$json$::jsonb),
  ('es', 'evidence.exit.commands', $json${"one": "Portería de salida: se comprobó {count} comando de la respuesta con las reglas de la casa.", "other": "Portería de salida: se comprobaron {count} comandos de la respuesta con las reglas de la casa."}$json$::jsonb),
  ('es', 'evidence.exit.files', $json${"one": "Portería de salida: se comprobó {count} archivo de la respuesta con las reglas de la casa.", "other": "Portería de salida: se comprobaron {count} archivos de la respuesta con las reglas de la casa."}$json$::jsonb),
  ('es', 'evidence.exit.held', $json$"Retenido por {rule}: {target} ({kind})."$json$::jsonb),
  ('es', 'evidence.answer', $json$"La respuesta del agente: lo que dice haber ejecutado, probado o terminado no lo comprobó JayV."$json$::jsonb),
  ('es', 'evidence.review', $json${"one": "Segunda opinión de {agent} ({model}) sobre {count} archivo modificado: la lectura de otro modelo, no una prueba.", "other": "Segunda opinión de {agent} ({model}) sobre {count} archivos modificados: la lectura de otro modelo, no una prueba."}$json$::jsonb),
  ('es', 'evidence.review.missing', $json$"Se pidió una segunda opinión de {agent}, pero no ha llegado."$json$::jsonb),
  ('es', 'evidence.noChecks', $json$"JayV no ejecutó ninguna prueba, build ni lint en este turno."$json$::jsonb),
  ('es', 'evidence.done.declared', $json$"La solicitud dice cómo saber que está lista, pero JayV no comprobó ese criterio."$json$::jsonb),
  ('es', 'evidence.done.missing', $json$"La solicitud no dijo cómo saber que está lista, así que no había criterio que comprobar."$json$::jsonb),
  ('es', 'evidence.disclaimer', $json$"JayV no garantiza que un cambio sea correcto: solo lo que está en «Observado por JayV» lo comprobó el propio JayV."$json$::jsonb),
  ('es', 'whatsNew.item.honestVerdicts.title', $json$"Las respuestas dicen lo que de verdad se comprobó"$json$::jsonb),
  ('es', 'whatsNew.item.honestVerdicts.detail', $json$"Una respuesta ya no se pone verde solo por haber pasado las reglas de la casa. Salvo que la portería de salida haya retenido algo, aparece como no verificada, porque JayV no ejecutó ninguna prueba, build ni lint sobre ella. El nuevo botón Qué se comprobó, debajo de cada respuesta, separa lo que JayV observó (las porterías de entrada y de salida), lo que un modelo dijo sin que nadie lo comprobara (la respuesta del agente y la segunda opinión) y lo que aún no está verificado. En el modo Desarrollo, además, se pide al agente que termine diciendo qué ejecutó, qué supone y qué no verificó."$json$::jsonb),
  ('es', 'docs.answerEvidence.title', $json$"Qué se comprobó"$json$::jsonb),
  ('es', 'docs.answerEvidence.summary', $json$"Cada respuesta muestra lo que JayV observó, lo que un modelo solo dijo y lo que aún no está verificado, en lugar de una luz verde que nadie midió."$json$::jsonb),
  ('es', 'docs.answerEvidence.usage', $json$"Una respuesta que la portería de salida no retuvo aparece como no verificada, porque JayV no ejecuta pruebas, build ni lint sobre ella. Haz clic en Qué se comprobó, debajo de la respuesta, para ver la puntuación de la portería de entrada, los comandos y archivos que comprobó la portería de salida, la segunda opinión si la hubo y lo que JayV no verificó, como las pruebas y el propio criterio de listo de la solicitud. En el modo Desarrollo se pide al agente que termine diciendo qué ejecutó, qué supone y qué no verificó."$json$::jsonb),
  ('zh-CN', 'verdict.unverified', $json$"未验证"$json$::jsonb),
  ('zh-CN', 'verdict.unverified.hint', $json$"JayV 没有为这个回答运行任何测试、构建或 lint。打开“核查了什么”查看它实际核查的内容。"$json$::jsonb),
  ('zh-CN', 'evidence.toggle', $json$"核查了什么"$json$::jsonb),
  ('zh-CN', 'evidence.loading', $json$"正在读取核查内容…"$json$::jsonb),
  ('zh-CN', 'evidence.observed', $json$"JayV 观察到的"$json$::jsonb),
  ('zh-CN', 'evidence.inferred', $json$"模型所说，未经核查"$json$::jsonb),
  ('zh-CN', 'evidence.unverified', $json$"未验证"$json$::jsonb),
  ('zh-CN', 'evidence.entry', $json$"入口门岗：该请求作为{scope}得分 {score}/100（最低分为 {demand}）。"$json$::jsonb),
  ('zh-CN', 'evidence.exit.none', $json$"出口门岗：回答中没有要运行的命令，也没有要修改的文件。"$json$::jsonb),
  ('zh-CN', 'evidence.exit.commands', $json${"other": "出口门岗：已按内部规则核查回答中的 {count} 条命令。"}$json$::jsonb),
  ('zh-CN', 'evidence.exit.files', $json${"other": "出口门岗：已按内部规则核查回答中的 {count} 个文件。"}$json$::jsonb),
  ('zh-CN', 'evidence.exit.held', $json$"被 {rule} 扣留：{target}（{kind}）。"$json$::jsonb),
  ('zh-CN', 'evidence.answer', $json$"代理的回答：它声称运行、测试或完成的内容都未经 JayV 核查。"$json$::jsonb),
  ('zh-CN', 'evidence.review', $json${"other": "{agent}（{model}）对 {count} 个已更改文件给出的第二意见：这是另一个模型的解读，不是测试。"}$json$::jsonb),
  ('zh-CN', 'evidence.review.missing', $json$"已请求 {agent} 给出第二意见，但尚未收到。"$json$::jsonb),
  ('zh-CN', 'evidence.noChecks', $json$"JayV 在本轮中没有运行任何测试、构建或 lint。"$json$::jsonb),
  ('zh-CN', 'evidence.done.declared', $json$"请求说明了如何判断完成，但 JayV 没有核查这一标准。"$json$::jsonb),
  ('zh-CN', 'evidence.done.missing', $json$"请求没有说明如何判断完成，因此没有可供核查的标准。"$json$::jsonb),
  ('zh-CN', 'evidence.disclaimer', $json$"JayV 不保证更改是正确的：只有“JayV 观察到的”下的内容由 JayV 亲自核查过。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.honestVerdicts.title', $json$"回答会说明真正核查了什么"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.honestVerdicts.detail', $json$"回答不再仅仅因为通过了内部规则就显示为绿色。除非出口门岗扣留了某些内容，否则它会显示为未验证，因为 JayV 没有对它运行任何测试、构建或 lint。每个回答下方新增的“核查了什么”按钮会分开显示：JayV 观察到的（入口和出口门岗）、模型所说但无人核查的（代理的回答和第二意见），以及仍未验证的内容。在开发模式下，还会要求代理在结尾说明它运行了什么、假设了什么、哪些没有验证。"$json$::jsonb),
  ('zh-CN', 'docs.answerEvidence.title', $json$"核查了什么"$json$::jsonb),
  ('zh-CN', 'docs.answerEvidence.summary', $json$"每个回答都会显示 JayV 观察到的内容、模型仅仅声称的内容以及仍未验证的内容，而不是一盏没人测量过的绿灯。"$json$::jsonb),
  ('zh-CN', 'docs.answerEvidence.usage', $json$"出口门岗未扣留的回答会显示为未验证，因为 JayV 不会对它运行测试、构建或 lint。点击回答下方的“核查了什么”，可以看到入口门岗的评分、出口门岗核查过的命令和文件、第二意见（如有），以及 JayV 没有验证的内容，例如测试和请求自身的完成标准。在开发模式下，会要求代理在结尾说明它运行了什么、假设了什么、哪些没有验证。"$json$::jsonb),
  ('hi', 'verdict.unverified', $json$"सत्यापित नहीं"$json$::jsonb),
  ('hi', 'verdict.unverified.hint', $json$"JayV ने इस जवाब के लिए कोई टेस्ट, बिल्ड या लिंट नहीं चलाया। उसने क्या जाँचा, यह देखने के लिए “क्या जाँचा गया” खोलें।"$json$::jsonb),
  ('hi', 'evidence.toggle', $json$"क्या जाँचा गया"$json$::jsonb),
  ('hi', 'evidence.loading', $json$"जाँची गई चीज़ें पढ़ी जा रही हैं…"$json$::jsonb),
  ('hi', 'evidence.observed', $json$"JayV ने देखा"$json$::jsonb),
  ('hi', 'evidence.inferred', $json$"मॉडल ने कहा, जाँचा नहीं गया"$json$::jsonb),
  ('hi', 'evidence.unverified', $json$"सत्यापित नहीं"$json$::jsonb),
  ('hi', 'evidence.entry', $json$"प्रवेश गेट: अनुरोध को {scope} के लिए 100 में से {score} मिले (न्यूनतम {demand} है)।"$json$::jsonb),
  ('hi', 'evidence.exit.none', $json$"निकास गेट: जवाब में चलाने के लिए कोई कमांड या बदलने के लिए कोई फ़ाइल नहीं थी।"$json$::jsonb),
  ('hi', 'evidence.exit.commands', $json${"one": "निकास गेट: जवाब का {count} कमांड घर के नियमों से जाँचा गया।", "other": "निकास गेट: जवाब के {count} कमांड घर के नियमों से जाँचे गए।"}$json$::jsonb),
  ('hi', 'evidence.exit.files', $json${"one": "निकास गेट: जवाब की {count} फ़ाइल घर के नियमों से जाँची गई।", "other": "निकास गेट: जवाब की {count} फ़ाइलें घर के नियमों से जाँची गईं।"}$json$::jsonb),
  ('hi', 'evidence.exit.held', $json$"{rule} ने रोका: {target} ({kind})।"$json$::jsonb),
  ('hi', 'evidence.answer', $json$"एजेंट का जवाब: उसने जो चलाने, टेस्ट करने या पूरा करने की बात कही, उसे JayV ने नहीं जाँचा।"$json$::jsonb),
  ('hi', 'evidence.review', $json${"one": "{agent} ({model}) की {count} बदली गई फ़ाइल पर दूसरी राय: दूसरे मॉडल की समझ, टेस्ट नहीं।", "other": "{agent} ({model}) की {count} बदली गई फ़ाइलों पर दूसरी राय: दूसरे मॉडल की समझ, टेस्ट नहीं।"}$json$::jsonb),
  ('hi', 'evidence.review.missing', $json$"{agent} से दूसरी राय माँगी गई, लेकिन वह नहीं आई।"$json$::jsonb),
  ('hi', 'evidence.noChecks', $json$"JayV ने इस टर्न में कोई टेस्ट, बिल्ड या लिंट नहीं चलाया।"$json$::jsonb),
  ('hi', 'evidence.done.declared', $json$"अनुरोध बताता है कि काम पूरा कैसे माना जाए, लेकिन JayV ने वह मानदंड नहीं जाँचा।"$json$::jsonb),
  ('hi', 'evidence.done.missing', $json$"अनुरोध ने नहीं बताया कि काम पूरा कैसे माना जाए, इसलिए जाँचने के लिए कोई मानदंड नहीं था।"$json$::jsonb),
  ('hi', 'evidence.disclaimer', $json$"JayV यह गारंटी नहीं देता कि बदलाव सही है: केवल “JayV ने देखा” के अंतर्गत जो है, उसे JayV ने ख़ुद जाँचा।"$json$::jsonb),
  ('hi', 'whatsNew.item.honestVerdicts.title', $json$"जवाब बताते हैं कि असल में क्या जाँचा गया"$json$::jsonb),
  ('hi', 'whatsNew.item.honestVerdicts.detail', $json$"अब कोई जवाब सिर्फ़ घर के नियमों से गुज़रने पर हरा नहीं होता। जब तक निकास गेट ने कुछ रोका न हो, वह सत्यापित नहीं के रूप में दिखता है, क्योंकि JayV ने उस पर कोई टेस्ट, बिल्ड या लिंट नहीं चलाया। हर जवाब के नीचे नया क्या जाँचा गया बटन अलग-अलग दिखाता है कि JayV ने क्या देखा (प्रवेश और निकास गेट), किसी मॉडल ने बिना जाँच के क्या कहा (एजेंट का जवाब और दूसरी राय) और क्या अभी सत्यापित नहीं है। डेवलपमेंट मोड में एजेंट से यह भी कहा जाता है कि अंत में बताए कि उसने क्या चलाया, क्या मान लिया और क्या सत्यापित नहीं किया।"$json$::jsonb),
  ('hi', 'docs.answerEvidence.title', $json$"क्या जाँचा गया"$json$::jsonb),
  ('hi', 'docs.answerEvidence.summary', $json$"हर जवाब दिखाता है कि JayV ने क्या देखा, किसी मॉडल ने सिर्फ़ क्या कहा और क्या अभी सत्यापित नहीं है, न कि ऐसी हरी बत्ती जिसे किसी ने मापा ही नहीं।"$json$::jsonb),
  ('hi', 'docs.answerEvidence.usage', $json$"जिस जवाब को निकास गेट ने नहीं रोका, वह सत्यापित नहीं के रूप में दिखता है, क्योंकि JayV उस पर कोई टेस्ट, बिल्ड या लिंट नहीं चलाता। जवाब के नीचे क्या जाँचा गया पर क्लिक करें और देखें प्रवेश गेट का स्कोर, निकास गेट द्वारा जाँचे गए कमांड और फ़ाइलें, दूसरी राय (अगर ली गई) और वह सब जो JayV ने सत्यापित नहीं किया, जैसे टेस्ट और अनुरोध का अपना पूरा होने का मानदंड। डेवलपमेंट मोड में एजेंट से कहा जाता है कि अंत में बताए कि उसने क्या चलाया, क्या मान लिया और क्या सत्यापित नहीं किया।"$json$::jsonb),
  ('ar', 'verdict.unverified', $json$"غير متحقق منها"$json$::jsonb),
  ('ar', 'verdict.unverified.hint', $json$"لم يشغّل JayV أي اختبار أو بناء أو فحص lint لهذه الإجابة. افتح «ما الذي تم فحصه» لترى ما فحصه فعلًا."$json$::jsonb),
  ('ar', 'evidence.toggle', $json$"ما الذي تم فحصه"$json$::jsonb),
  ('ar', 'evidence.loading', $json$"جارٍ قراءة ما تم فحصه…"$json$::jsonb),
  ('ar', 'evidence.observed', $json$"ما رصده JayV"$json$::jsonb),
  ('ar', 'evidence.inferred', $json$"قاله نموذج، دون فحص"$json$::jsonb),
  ('ar', 'evidence.unverified', $json$"غير متحقق منه"$json$::jsonb),
  ('ar', 'evidence.entry', $json$"بوابة الدخول: حصل الطلب على {score} من 100 بوصفه {scope} (الحد الأدنى {demand})."$json$::jsonb),
  ('ar', 'evidence.exit.none', $json$"بوابة الخروج: لم تذكر الإجابة أي أمر للتشغيل ولا أي ملف للتغيير."$json$::jsonb),
  ('ar', 'evidence.exit.commands', $json${"zero": "بوابة الخروج: لم يُفحص أي أمر من الإجابة وفق قواعد الدار.", "one": "بوابة الخروج: فُحص أمر واحد من الإجابة وفق قواعد الدار.", "two": "بوابة الخروج: فُحص أمران من الإجابة وفق قواعد الدار.", "few": "بوابة الخروج: فُحصت {count} أوامر من الإجابة وفق قواعد الدار.", "many": "بوابة الخروج: فُحص {count} أمرًا من الإجابة وفق قواعد الدار.", "other": "بوابة الخروج: فُحص {count} أمر من الإجابة وفق قواعد الدار."}$json$::jsonb),
  ('ar', 'evidence.exit.files', $json${"zero": "بوابة الخروج: لم يُفحص أي ملف من الإجابة وفق قواعد الدار.", "one": "بوابة الخروج: فُحص ملف واحد من الإجابة وفق قواعد الدار.", "two": "بوابة الخروج: فُحص ملفان من الإجابة وفق قواعد الدار.", "few": "بوابة الخروج: فُحصت {count} ملفات من الإجابة وفق قواعد الدار.", "many": "بوابة الخروج: فُحص {count} ملفًا من الإجابة وفق قواعد الدار.", "other": "بوابة الخروج: فُحص {count} ملف من الإجابة وفق قواعد الدار."}$json$::jsonb),
  ('ar', 'evidence.exit.held', $json$"احتجزته {rule}: {target} ({kind})."$json$::jsonb),
  ('ar', 'evidence.answer', $json$"إجابة الوكيل: ما يقول إنه شغّله أو اختبره أو أنهاه لم يفحصه JayV."$json$::jsonb),
  ('ar', 'evidence.review', $json${"zero": "رأي ثانٍ من {agent} ({model}) دون ملفات معدّلة: قراءة نموذج آخر، وليست اختبارًا.", "one": "رأي ثانٍ من {agent} ({model}) في ملف معدّل واحد: قراءة نموذج آخر، وليست اختبارًا.", "two": "رأي ثانٍ من {agent} ({model}) في ملفين معدّلين: قراءة نموذج آخر، وليست اختبارًا.", "few": "رأي ثانٍ من {agent} ({model}) في {count} ملفات معدّلة: قراءة نموذج آخر، وليست اختبارًا.", "many": "رأي ثانٍ من {agent} ({model}) في {count} ملفًا معدّلًا: قراءة نموذج آخر، وليست اختبارًا.", "other": "رأي ثانٍ من {agent} ({model}) في {count} ملف معدّل: قراءة نموذج آخر، وليست اختبارًا."}$json$::jsonb),
  ('ar', 'evidence.review.missing', $json$"طُلب رأي ثانٍ من {agent} لكنه لم يصل."$json$::jsonb),
  ('ar', 'evidence.noChecks', $json$"لم يشغّل JayV أي اختبار أو بناء أو فحص lint في هذه الجولة."$json$::jsonb),
  ('ar', 'evidence.done.declared', $json$"يذكر الطلب كيف يُعرف أنه أُنجز، لكن JayV لم يفحص هذا المعيار."$json$::jsonb),
  ('ar', 'evidence.done.missing', $json$"لم يذكر الطلب كيف يُعرف أنه أُنجز، فلم يكن هناك معيار للفحص."$json$::jsonb),
  ('ar', 'evidence.disclaimer', $json$"لا يضمن JayV أن التغيير صحيح: وحده ما يرد تحت «ما رصده JayV» فحصه JayV بنفسه."$json$::jsonb),
  ('ar', 'whatsNew.item.honestVerdicts.title', $json$"الإجابات تقول ما الذي فُحص فعلًا"$json$::jsonb),
  ('ar', 'whatsNew.item.honestVerdicts.detail', $json$"لم تعد الإجابة تتحول إلى الأخضر لمجرد أنها اجتازت قواعد الدار. ما لم تحتجز بوابة الخروج شيئًا، تظهر على أنها غير متحقق منها، لأن JayV لم يشغّل عليها أي اختبار أو بناء أو فحص lint. يفصل الزر الجديد ما الذي تم فحصه، أسفل كل إجابة، بين ما رصده JayV (بوابتا الدخول والخروج) وما قاله نموذج دون أن يفحصه أحد (إجابة الوكيل والرأي الثاني) وما لم يُتحقق منه بعد. وفي وضع التطوير يُطلب من الوكيل أيضًا أن يختم بما شغّله وما يفترضه وما لم يتحقق منه."$json$::jsonb),
  ('ar', 'docs.answerEvidence.title', $json$"ما الذي تم فحصه"$json$::jsonb),
  ('ar', 'docs.answerEvidence.summary', $json$"تعرض كل إجابة ما رصده JayV وما قاله نموذج فقط وما لم يُتحقق منه بعد، بدلًا من ضوء أخضر لم يقسه أحد."$json$::jsonb),
  ('ar', 'docs.answerEvidence.usage', $json$"تظهر الإجابة التي لم تحتجزها بوابة الخروج على أنها غير متحقق منها، لأن JayV لا يشغّل عليها أي اختبار أو بناء أو فحص lint. انقر ما الذي تم فحصه أسفل الإجابة لترى درجة بوابة الدخول، والأوامر والملفات التي فحصتها بوابة الخروج، والرأي الثاني إن وُجد، وما لم يتحقق منه JayV، مثل الاختبارات ومعيار الإنجاز الذي يحدده الطلب نفسه. وفي وضع التطوير يُطلب من الوكيل أن يختم بما شغّله وما يفترضه وما لم يتحقق منه."$json$::jsonb),
  ('fr', 'verdict.unverified', $json$"non vérifiée"$json$::jsonb),
  ('fr', 'verdict.unverified.hint', $json$"JayV n’a lancé aucun test, build ni lint pour cette réponse. Ouvrez « Ce qui a été vérifié » pour voir ce qu’il a vérifié."$json$::jsonb),
  ('fr', 'evidence.toggle', $json$"Ce qui a été vérifié"$json$::jsonb),
  ('fr', 'evidence.loading', $json$"Lecture de ce qui a été vérifié…"$json$::jsonb),
  ('fr', 'evidence.observed', $json$"Observé par JayV"$json$::jsonb),
  ('fr', 'evidence.inferred', $json$"Dit par un modèle, non vérifié"$json$::jsonb),
  ('fr', 'evidence.unverified', $json$"Non vérifié"$json$::jsonb),
  ('fr', 'evidence.entry', $json$"Loge d’entrée : la demande a obtenu {score} sur 100 pour {scope} (le minimum est {demand})."$json$::jsonb),
  ('fr', 'evidence.exit.none', $json$"Loge de sortie : la réponse ne cite aucune commande à lancer ni aucun fichier à modifier."$json$::jsonb),
  ('fr', 'evidence.exit.commands', $json${"one": "Loge de sortie : {count} commande de la réponse a été vérifiée selon les règles de la maison.", "other": "Loge de sortie : {count} commandes de la réponse ont été vérifiées selon les règles de la maison."}$json$::jsonb),
  ('fr', 'evidence.exit.files', $json${"one": "Loge de sortie : {count} fichier de la réponse a été vérifié selon les règles de la maison.", "other": "Loge de sortie : {count} fichiers de la réponse ont été vérifiés selon les règles de la maison."}$json$::jsonb),
  ('fr', 'evidence.exit.held', $json$"Retenu par {rule} : {target} ({kind})."$json$::jsonb),
  ('fr', 'evidence.answer', $json$"La réponse de l’agent : ce qu’il dit avoir lancé, testé ou terminé n’a pas été vérifié par JayV."$json$::jsonb),
  ('fr', 'evidence.review', $json${"one": "Deuxième avis de {agent} ({model}) sur {count} fichier modifié : la lecture d’un autre modèle, pas un test.", "other": "Deuxième avis de {agent} ({model}) sur {count} fichiers modifiés : la lecture d’un autre modèle, pas un test."}$json$::jsonb),
  ('fr', 'evidence.review.missing', $json$"Un deuxième avis de {agent} a été demandé, mais il n’est pas arrivé."$json$::jsonb),
  ('fr', 'evidence.noChecks', $json$"JayV n’a lancé aucun test, build ni lint dans ce tour."$json$::jsonb),
  ('fr', 'evidence.done.declared', $json$"La demande dit comment savoir que c’est terminé, mais JayV n’a pas vérifié ce critère."$json$::jsonb),
  ('fr', 'evidence.done.missing', $json$"La demande ne disait pas comment savoir que c’est terminé : il n’y avait donc aucun critère à vérifier."$json$::jsonb),
  ('fr', 'evidence.disclaimer', $json$"JayV ne garantit pas qu’une modification est correcte : seul ce qui figure sous « Observé par JayV » a été vérifié par JayV lui-même."$json$::jsonb),
  ('fr', 'whatsNew.item.honestVerdicts.title', $json$"Les réponses disent ce qui a vraiment été vérifié"$json$::jsonb),
  ('fr', 'whatsNew.item.honestVerdicts.detail', $json$"Une réponse ne passe plus au vert simplement parce qu’elle a respecté les règles de la maison. Sauf si la loge de sortie a retenu quelque chose, elle apparaît comme non vérifiée, car JayV n’a lancé aucun test, build ni lint dessus. Le nouveau bouton Ce qui a été vérifié, sous chaque réponse, sépare ce que JayV a observé (les loges d’entrée et de sortie), ce qu’un modèle a dit sans que personne ne le vérifie (la réponse de l’agent et le deuxième avis) et ce qui n’est pas encore vérifié. En mode Développement, l’agent doit aussi terminer en disant ce qu’il a lancé, ce qu’il suppose et ce qu’il n’a pas vérifié."$json$::jsonb),
  ('fr', 'docs.answerEvidence.title', $json$"Ce qui a été vérifié"$json$::jsonb),
  ('fr', 'docs.answerEvidence.summary', $json$"Chaque réponse montre ce que JayV a observé, ce qu’un modèle a seulement dit et ce qui n’est pas encore vérifié, au lieu d’un feu vert que personne n’a mesuré."$json$::jsonb),
  ('fr', 'docs.answerEvidence.usage', $json$"Une réponse que la loge de sortie n’a pas retenue apparaît comme non vérifiée, car JayV ne lance aucun test, build ni lint dessus. Cliquez sur Ce qui a été vérifié, sous la réponse, pour voir le score de la loge d’entrée, les commandes et fichiers vérifiés par la loge de sortie, le deuxième avis s’il y en a eu un, et ce que JayV n’a pas vérifié, comme les tests et le critère de fin donné par la demande elle-même. En mode Développement, l’agent doit terminer en disant ce qu’il a lancé, ce qu’il suppose et ce qu’il n’a pas vérifié."$json$::jsonb),
  ('ru', 'verdict.unverified', $json$"не проверено"$json$::jsonb),
  ('ru', 'verdict.unverified.hint', $json$"JayV не запускал для этого ответа ни тесты, ни сборку, ни линтер. Откройте «Что проверено», чтобы увидеть, что он проверил."$json$::jsonb),
  ('ru', 'evidence.toggle', $json$"Что проверено"$json$::jsonb),
  ('ru', 'evidence.loading', $json$"Читаю, что было проверено…"$json$::jsonb),
  ('ru', 'evidence.observed', $json$"Наблюдал JayV"$json$::jsonb),
  ('ru', 'evidence.inferred', $json$"Сказано моделью, не проверено"$json$::jsonb),
  ('ru', 'evidence.unverified', $json$"Не проверено"$json$::jsonb),
  ('ru', 'evidence.entry', $json$"Входная проходная: запрос получил {score} из 100 как «{scope}» (минимум — {demand})."$json$::jsonb),
  ('ru', 'evidence.exit.none', $json$"Выходная проходная: в ответе нет ни команд для запуска, ни файлов для изменения."$json$::jsonb),
  ('ru', 'evidence.exit.commands', $json${"one": "Выходная проходная: {count} команда из ответа сверена с правилами дома.", "few": "Выходная проходная: {count} команды из ответа сверены с правилами дома.", "many": "Выходная проходная: {count} команд из ответа сверены с правилами дома.", "other": "Выходная проходная: {count} команды из ответа сверены с правилами дома."}$json$::jsonb),
  ('ru', 'evidence.exit.files', $json${"one": "Выходная проходная: {count} файл из ответа сверен с правилами дома.", "few": "Выходная проходная: {count} файла из ответа сверены с правилами дома.", "many": "Выходная проходная: {count} файлов из ответа сверены с правилами дома.", "other": "Выходная проходная: {count} файла из ответа сверены с правилами дома."}$json$::jsonb),
  ('ru', 'evidence.exit.held', $json$"Задержано правилом {rule}: {target} ({kind})."$json$::jsonb),
  ('ru', 'evidence.answer', $json$"Ответ агента: всё, что он, по его словам, запустил, протестировал или закончил, JayV не проверял."$json$::jsonb),
  ('ru', 'evidence.review', $json${"one": "Второе мнение {agent} ({model}) по {count} изменённому файлу: прочтение другой модели, а не тест.", "few": "Второе мнение {agent} ({model}) по {count} изменённым файлам: прочтение другой модели, а не тест.", "many": "Второе мнение {agent} ({model}) по {count} изменённым файлам: прочтение другой модели, а не тест.", "other": "Второе мнение {agent} ({model}) по {count} изменённым файлам: прочтение другой модели, а не тест."}$json$::jsonb),
  ('ru', 'evidence.review.missing', $json$"Второе мнение {agent} было запрошено, но не пришло."$json$::jsonb),
  ('ru', 'evidence.noChecks', $json$"JayV не запускал в этом ходе ни тесты, ни сборку, ни линтер."$json$::jsonb),
  ('ru', 'evidence.done.declared', $json$"В запросе сказано, как понять, что работа готова, но JayV этот критерий не проверял."$json$::jsonb),
  ('ru', 'evidence.done.missing', $json$"В запросе не сказано, как понять, что работа готова, поэтому проверять было не по чему."$json$::jsonb),
  ('ru', 'evidence.disclaimer', $json$"JayV не гарантирует, что изменение верно: сам JayV проверил только то, что указано в разделе «Наблюдал JayV»."$json$::jsonb),
  ('ru', 'whatsNew.item.honestVerdicts.title', $json$"Ответы говорят, что на самом деле проверено"$json$::jsonb),
  ('ru', 'whatsNew.item.honestVerdicts.detail', $json$"Ответ больше не становится зелёным только потому, что прошёл правила дома. Если выходная проходная ничего не задержала, он помечается как не проверенный, потому что JayV не запускал для него ни тесты, ни сборку, ни линтер. Новая кнопка «Что проверено» под каждым ответом разделяет то, что наблюдал JayV (входная и выходная проходные), то, что сказала модель без всякой проверки (ответ агента и второе мнение), и то, что ещё не проверено. В режиме «Разработка» агента также просят закончить ответ тем, что он запускал, что предполагает и что не проверил."$json$::jsonb),
  ('ru', 'docs.answerEvidence.title', $json$"Что проверено"$json$::jsonb),
  ('ru', 'docs.answerEvidence.summary', $json$"Каждый ответ показывает, что наблюдал JayV, что модель только сказала и что ещё не проверено, вместо зелёного сигнала, который никто не измерял."$json$::jsonb),
  ('ru', 'docs.answerEvidence.usage', $json$"Ответ, который выходная проходная не задержала, помечается как не проверенный, потому что JayV не запускает для него ни тесты, ни сборку, ни линтер. Нажмите «Что проверено» под ответом, чтобы увидеть оценку входной проходной, команды и файлы, которые сверила выходная проходная, второе мнение, если оно было, и то, что JayV не проверял, например тесты и собственный критерий готовности из запроса. В режиме «Разработка» агента просят закончить ответ тем, что он запускал, что предполагает и что не проверил."$json$::jsonb),
  ('ja', 'verdict.unverified', $json$"未検証"$json$::jsonb),
  ('ja', 'verdict.unverified.hint', $json$"JayV はこの回答に対してテスト、ビルド、lint を実行していません。何を確認したかは「確認した内容」を開いてください。"$json$::jsonb),
  ('ja', 'evidence.toggle', $json$"確認した内容"$json$::jsonb),
  ('ja', 'evidence.loading', $json$"確認した内容を読み込んでいます…"$json$::jsonb),
  ('ja', 'evidence.observed', $json$"JayV が確認したこと"$json$::jsonb),
  ('ja', 'evidence.inferred', $json$"モデルの発言（未確認）"$json$::jsonb),
  ('ja', 'evidence.unverified', $json$"未検証"$json$::jsonb),
  ('ja', 'evidence.entry', $json$"入口ゲート：このリクエストは{scope}として100点中{score}点でした（最低点は{demand}）。"$json$::jsonb),
  ('ja', 'evidence.exit.none', $json$"出口ゲート：回答には実行するコマンドも変更するファイルもありませんでした。"$json$::jsonb),
  ('ja', 'evidence.exit.commands', $json${"other": "出口ゲート：回答内の {count} 件のコマンドをハウスルールと照合しました。"}$json$::jsonb),
  ('ja', 'evidence.exit.files', $json${"other": "出口ゲート：回答内の {count} 件のファイルをハウスルールと照合しました。"}$json$::jsonb),
  ('ja', 'evidence.exit.held', $json$"{rule} により保留：{target}（{kind}）。"$json$::jsonb),
  ('ja', 'evidence.answer', $json$"エージェントの回答：実行した・テストした・完了したという内容は JayV が確認したものではありません。"$json$::jsonb),
  ('ja', 'evidence.review', $json${"other": "{agent}（{model}）による変更ファイル {count} 件へのセカンドオピニオン：別のモデルの読み取りであり、テストではありません。"}$json$::jsonb),
  ('ja', 'evidence.review.missing', $json$"{agent} にセカンドオピニオンを依頼しましたが、まだ届いていません。"$json$::jsonb),
  ('ja', 'evidence.noChecks', $json$"JayV はこのターンでテスト、ビルド、lint を実行していません。"$json$::jsonb),
  ('ja', 'evidence.done.declared', $json$"リクエストには完了の判断方法がありますが、JayV はその基準を確認していません。"$json$::jsonb),
  ('ja', 'evidence.done.missing', $json$"リクエストに完了の判断方法がなかったため、照合する基準がありませんでした。"$json$::jsonb),
  ('ja', 'evidence.disclaimer', $json$"JayV は変更が正しいことを保証しません。JayV 自身が確認したのは「JayV が確認したこと」にある内容だけです。"$json$::jsonb),
  ('ja', 'whatsNew.item.honestVerdicts.title', $json$"回答が実際に何を確認したかを示すように"$json$::jsonb),
  ('ja', 'whatsNew.item.honestVerdicts.detail', $json$"ハウスルールを通過しただけでは、回答が緑になることはなくなりました。出口ゲートが何かを保留しない限り、回答は未検証と表示されます。JayV はその回答に対してテスト、ビルド、lint を実行していないからです。各回答の下にある新しい「確認した内容」ボタンでは、JayV が確認したこと（入口ゲートと出口ゲート）、誰も確認していないモデルの発言（エージェントの回答とセカンドオピニオン）、まだ検証されていないことが分けて表示されます。開発モードでは、エージェントに対して、実行したこと、前提としていること、検証していないことを最後に述べるよう求めます。"$json$::jsonb),
  ('ja', 'docs.answerEvidence.title', $json$"確認した内容"$json$::jsonb),
  ('ja', 'docs.answerEvidence.summary', $json$"各回答には、誰も測っていない緑のランプではなく、JayV が確認したこと、モデルが述べただけのこと、まだ検証されていないことが表示されます。"$json$::jsonb),
  ('ja', 'docs.answerEvidence.usage', $json$"出口ゲートが保留しなかった回答は未検証と表示されます。JayV はその回答に対してテスト、ビルド、lint を実行しないためです。回答の下の「確認した内容」をクリックすると、入口ゲートのスコア、出口ゲートが照合したコマンドとファイル、セカンドオピニオン（実施された場合）、そしてテストやリクエスト自体の完了基準など JayV が検証していないことを確認できます。開発モードでは、エージェントに対して、実行したこと、前提としていること、検証していないことを最後に述べるよう求めます。"$json$::jsonb),
  ('de', 'verdict.unverified', $json$"nicht geprüft"$json$::jsonb),
  ('de', 'verdict.unverified.hint', $json$"JayV hat für diese Antwort keinen Test, Build oder Lint ausgeführt. Öffne „Was geprüft wurde“, um zu sehen, was geprüft wurde."$json$::jsonb),
  ('de', 'evidence.toggle', $json$"Was geprüft wurde"$json$::jsonb),
  ('de', 'evidence.loading', $json$"Lese, was geprüft wurde…"$json$::jsonb),
  ('de', 'evidence.observed', $json$"Von JayV beobachtet"$json$::jsonb),
  ('de', 'evidence.inferred', $json$"Von einem Modell gesagt, nicht geprüft"$json$::jsonb),
  ('de', 'evidence.unverified', $json$"Nicht geprüft"$json$::jsonb),
  ('de', 'evidence.entry', $json$"Eingangspforte: Die Anfrage erhielt {score} von 100 für {scope} (das Minimum ist {demand})."$json$::jsonb),
  ('de', 'evidence.exit.none', $json$"Ausgangspforte: Die Antwort nannte keinen Befehl zum Ausführen und keine Datei zum Ändern."$json$::jsonb),
  ('de', 'evidence.exit.commands', $json${"one": "Ausgangspforte: {count} Befehl aus der Antwort wurde mit den Hausregeln abgeglichen.", "other": "Ausgangspforte: {count} Befehle aus der Antwort wurden mit den Hausregeln abgeglichen."}$json$::jsonb),
  ('de', 'evidence.exit.files', $json${"one": "Ausgangspforte: {count} Datei aus der Antwort wurde mit den Hausregeln abgeglichen.", "other": "Ausgangspforte: {count} Dateien aus der Antwort wurden mit den Hausregeln abgeglichen."}$json$::jsonb),
  ('de', 'evidence.exit.held', $json$"Zurückgehalten von {rule}: {target} ({kind})."$json$::jsonb),
  ('de', 'evidence.answer', $json$"Die Antwort des Agenten: Was er nach eigener Aussage ausgeführt, getestet oder fertiggestellt hat, hat JayV nicht geprüft."$json$::jsonb),
  ('de', 'evidence.review', $json${"one": "Zweite Meinung von {agent} ({model}) zu {count} geänderten Datei: die Lesart eines anderen Modells, kein Test.", "other": "Zweite Meinung von {agent} ({model}) zu {count} geänderten Dateien: die Lesart eines anderen Modells, kein Test."}$json$::jsonb),
  ('de', 'evidence.review.missing', $json$"Eine zweite Meinung von {agent} wurde angefordert, ist aber nicht angekommen."$json$::jsonb),
  ('de', 'evidence.noChecks', $json$"JayV hat in diesem Durchgang keinen Test, Build oder Lint ausgeführt."$json$::jsonb),
  ('de', 'evidence.done.declared', $json$"Die Anfrage sagt, woran man erkennt, dass sie erledigt ist, aber JayV hat dieses Kriterium nicht geprüft."$json$::jsonb),
  ('de', 'evidence.done.missing', $json$"Die Anfrage sagte nicht, woran man erkennt, dass sie erledigt ist, also gab es kein Kriterium zum Prüfen."$json$::jsonb),
  ('de', 'evidence.disclaimer', $json$"JayV garantiert nicht, dass eine Änderung korrekt ist: Nur was unter „Von JayV beobachtet“ steht, hat JayV selbst geprüft."$json$::jsonb),
  ('de', 'whatsNew.item.honestVerdicts.title', $json$"Antworten sagen, was wirklich geprüft wurde"$json$::jsonb),
  ('de', 'whatsNew.item.honestVerdicts.detail', $json$"Eine Antwort wird nicht mehr grün, nur weil sie die Hausregeln passiert hat. Sofern die Ausgangspforte nichts zurückgehalten hat, wird sie als nicht geprüft angezeigt, denn JayV hat für sie keinen Test, Build oder Lint ausgeführt. Die neue Schaltfläche Was geprüft wurde unter jeder Antwort trennt, was JayV beobachtet hat (Eingangs- und Ausgangspforte), was ein Modell gesagt hat, ohne dass es jemand geprüft hat (die Antwort des Agenten und die zweite Meinung), und was noch nicht geprüft ist. Im Modus Entwicklung wird der Agent außerdem gebeten, am Ende zu sagen, was er ausgeführt hat, was er annimmt und was er nicht geprüft hat."$json$::jsonb),
  ('de', 'docs.answerEvidence.title', $json$"Was geprüft wurde"$json$::jsonb),
  ('de', 'docs.answerEvidence.summary', $json$"Jede Antwort zeigt, was JayV beobachtet hat, was ein Modell nur gesagt hat und was noch nicht geprüft ist, statt eines grünen Lichts, das niemand gemessen hat."$json$::jsonb),
  ('de', 'docs.answerEvidence.usage', $json$"Eine Antwort, die die Ausgangspforte nicht zurückgehalten hat, wird als nicht geprüft angezeigt, denn JayV führt dafür keinen Test, Build oder Lint aus. Klicke unter der Antwort auf Was geprüft wurde, um die Punktzahl der Eingangspforte zu sehen, die von der Ausgangspforte abgeglichenen Befehle und Dateien, die zweite Meinung, falls es eine gab, und was JayV nicht geprüft hat, etwa Tests und das Abnahmekriterium der Anfrage selbst. Im Modus Entwicklung wird der Agent gebeten, am Ende zu sagen, was er ausgeführt hat, was er annimmt und was er nicht geprüft hat."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
