-- As recusas do servidor mostradas no chat e no projeto de cada uma, e a
-- lista de modelos de cada agente lida do /model do CLI.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'chat.refused', $json${"one": "{count} alteração deste chat recusada pelo servidor", "other": "{count} alterações deste chat recusadas pelo servidor"}$json$::jsonb),
  ('pt-BR', 'project.refused', $json${"one": "{count} alteração deste projeto recusada pelo servidor", "other": "{count} alterações deste projeto recusadas pelo servidor"}$json$::jsonb),
  ('pt-BR', 'model.refresh', $json$"Carregar do CLI"$json$::jsonb),
  ('pt-BR', 'model.refresh.running', $json$"Lendo o /model…"$json$::jsonb),
  ('pt-BR', 'model.refresh.hint', $json$"Lê a lista do comando /model do agente. Os modelos novos já vêm ligados para o Jev escolher entre eles."$json$::jsonb),
  ('pt-BR', 'model.refresh.dirty', $json$"Salve ou descarte suas alterações primeiro"$json$::jsonb),
  ('pt-BR', 'model.refresh.done', $json${"one": "{count} modelo carregado do {agent}", "other": "{count} modelos carregados do {agent}"}$json$::jsonb),
  ('pt-BR', 'model.refresh.silent', $json$"O {agent} não listou os modelos. Confira se ele está instalado e com login feito."$json$::jsonb),
  ('pt-BR', 'agent.section.models.description', $json$"Os modelos que o agente oferece no /model. O Jev escolhe entre os ligados a cada pedido."$json$::jsonb),
  ('en', 'chat.refused', $json${"one": "{count} change in this chat refused by the server", "other": "{count} changes in this chat refused by the server"}$json$::jsonb),
  ('en', 'project.refused', $json${"one": "{count} change in this project refused by the server", "other": "{count} changes in this project refused by the server"}$json$::jsonb),
  ('en', 'model.refresh', $json$"Load from the CLI"$json$::jsonb),
  ('en', 'model.refresh.running', $json$"Reading /model…"$json$::jsonb),
  ('en', 'model.refresh.hint', $json$"Reads the list from the agent's /model command. New models come enabled so Jev can choose among them."$json$::jsonb),
  ('en', 'model.refresh.dirty', $json$"Save or discard your changes first"$json$::jsonb),
  ('en', 'model.refresh.done', $json${"one": "{count} model loaded from {agent}", "other": "{count} models loaded from {agent}"}$json$::jsonb),
  ('en', 'model.refresh.silent', $json$"{agent} did not list its models. Check that it is installed and signed in."$json$::jsonb),
  ('en', 'agent.section.models.description', $json$"The models the agent offers in /model. Jev picks among the enabled ones for each request."$json$::jsonb),
  ('es', 'chat.refused', $json${"one": "{count} cambio de este chat rechazado por el servidor", "other": "{count} cambios de este chat rechazados por el servidor"}$json$::jsonb),
  ('es', 'project.refused', $json${"one": "{count} cambio de este proyecto rechazado por el servidor", "other": "{count} cambios de este proyecto rechazados por el servidor"}$json$::jsonb),
  ('es', 'model.refresh', $json$"Cargar desde la CLI"$json$::jsonb),
  ('es', 'model.refresh.running', $json$"Leyendo /model…"$json$::jsonb),
  ('es', 'model.refresh.hint', $json$"Lee la lista del comando /model del agente. Los modelos nuevos llegan activados para que Jev elija entre ellos."$json$::jsonb),
  ('es', 'model.refresh.dirty', $json$"Guarda o descarta tus cambios primero"$json$::jsonb),
  ('es', 'model.refresh.done', $json${"one": "{count} modelo cargado desde {agent}", "other": "{count} modelos cargados desde {agent}"}$json$::jsonb),
  ('es', 'model.refresh.silent', $json$"{agent} no listó sus modelos. Comprueba que esté instalado y con la sesión iniciada."$json$::jsonb),
  ('es', 'agent.section.models.description', $json$"Los modelos que el agente ofrece en /model. Jev elige entre los activados en cada solicitud."$json$::jsonb),
  ('zh-CN', 'chat.refused', $json${"other": "此聊天有 {count} 项更改被服务器拒绝"}$json$::jsonb),
  ('zh-CN', 'project.refused', $json${"other": "此项目有 {count} 项更改被服务器拒绝"}$json$::jsonb),
  ('zh-CN', 'model.refresh', $json$"从 CLI 加载"$json$::jsonb),
  ('zh-CN', 'model.refresh.running', $json$"正在读取 /model…"$json$::jsonb),
  ('zh-CN', 'model.refresh.hint', $json$"从代理的 /model 命令读取列表。新模型默认启用，供 Jev 从中选择。"$json$::jsonb),
  ('zh-CN', 'model.refresh.dirty', $json$"请先保存或放弃你的更改"$json$::jsonb),
  ('zh-CN', 'model.refresh.done', $json${"other": "已从 {agent} 加载 {count} 个模型"}$json$::jsonb),
  ('zh-CN', 'model.refresh.silent', $json$"{agent} 没有列出它的模型。请确认它已安装并已登录。"$json$::jsonb),
  ('zh-CN', 'agent.section.models.description', $json$"代理在 /model 中提供的模型。Jev 会为每个请求从已启用的模型中选择。"$json$::jsonb),
  ('hi', 'chat.refused', $json${"one": "इस चैट का {count} बदलाव सर्वर ने अस्वीकार किया", "other": "इस चैट के {count} बदलाव सर्वर ने अस्वीकार किए"}$json$::jsonb),
  ('hi', 'project.refused', $json${"one": "इस प्रोजेक्ट का {count} बदलाव सर्वर ने अस्वीकार किया", "other": "इस प्रोजेक्ट के {count} बदलाव सर्वर ने अस्वीकार किए"}$json$::jsonb),
  ('hi', 'model.refresh', $json$"CLI से लोड करें"$json$::jsonb),
  ('hi', 'model.refresh.running', $json$"/model पढ़ा जा रहा है…"$json$::jsonb),
  ('hi', 'model.refresh.hint', $json$"एजेंट के /model कमांड से सूची पढ़ता है। नए मॉडल चालू आते हैं ताकि Jev उनमें से चुन सके।"$json$::jsonb),
  ('hi', 'model.refresh.dirty', $json$"पहले अपने बदलाव सहेजें या छोड़ें"$json$::jsonb),
  ('hi', 'model.refresh.done', $json${"one": "{agent} से {count} मॉडल लोड हुआ", "other": "{agent} से {count} मॉडल लोड हुए"}$json$::jsonb),
  ('hi', 'model.refresh.silent', $json$"{agent} ने अपने मॉडल सूचीबद्ध नहीं किए। जाँचें कि वह इंस्टॉल है और साइन इन है।"$json$::jsonb),
  ('hi', 'agent.section.models.description', $json$"एजेंट /model में जो मॉडल देता है। Jev हर अनुरोध के लिए चालू मॉडलों में से चुनता है।"$json$::jsonb),
  ('ar', 'chat.refused', $json${"zero": "لم يرفض الخادم أي تغيير في هذه المحادثة", "one": "رفض الخادم تغييرًا واحدًا في هذه المحادثة", "two": "رفض الخادم تغييرين في هذه المحادثة", "few": "رفض الخادم {count} تغييرات في هذه المحادثة", "many": "رفض الخادم {count} تغييرًا في هذه المحادثة", "other": "رفض الخادم {count} تغيير في هذه المحادثة"}$json$::jsonb),
  ('ar', 'project.refused', $json${"zero": "لم يرفض الخادم أي تغيير في هذا المشروع", "one": "رفض الخادم تغييرًا واحدًا في هذا المشروع", "two": "رفض الخادم تغييرين في هذا المشروع", "few": "رفض الخادم {count} تغييرات في هذا المشروع", "many": "رفض الخادم {count} تغييرًا في هذا المشروع", "other": "رفض الخادم {count} تغيير في هذا المشروع"}$json$::jsonb),
  ('ar', 'model.refresh', $json$"التحميل من واجهة الأوامر"$json$::jsonb),
  ('ar', 'model.refresh.running', $json$"جارٍ قراءة ‎/model…"$json$::jsonb),
  ('ar', 'model.refresh.hint', $json$"يقرأ القائمة من أمر ‎/model لدى الوكيل. تأتي النماذج الجديدة مفعّلة ليختار Jev من بينها."$json$::jsonb),
  ('ar', 'model.refresh.dirty', $json$"احفظ تغييراتك أو تجاهلها أولًا"$json$::jsonb),
  ('ar', 'model.refresh.done', $json${"zero": "لم يُحمَّل أي نموذج من {agent}", "one": "تم تحميل نموذج واحد من {agent}", "two": "تم تحميل نموذجين من {agent}", "few": "تم تحميل {count} نماذج من {agent}", "many": "تم تحميل {count} نموذجًا من {agent}", "other": "تم تحميل {count} نموذج من {agent}"}$json$::jsonb),
  ('ar', 'model.refresh.silent', $json$"لم يعرض {agent} نماذجه. تأكد من أنه مثبت وأنك سجّلت الدخول."$json$::jsonb),
  ('ar', 'agent.section.models.description', $json$"النماذج التي يقدمها الوكيل في ‎/model. يختار Jev من بين المفعّلة منها لكل طلب."$json$::jsonb),
  ('fr', 'chat.refused', $json${"one": "{count} modification de ce chat refusée par le serveur", "other": "{count} modifications de ce chat refusées par le serveur"}$json$::jsonb),
  ('fr', 'project.refused', $json${"one": "{count} modification de ce projet refusée par le serveur", "other": "{count} modifications de ce projet refusées par le serveur"}$json$::jsonb),
  ('fr', 'model.refresh', $json$"Charger depuis la CLI"$json$::jsonb),
  ('fr', 'model.refresh.running', $json$"Lecture de /model…"$json$::jsonb),
  ('fr', 'model.refresh.hint', $json$"Lit la liste de la commande /model de l'agent. Les nouveaux modèles arrivent activés pour que Jev puisse choisir parmi eux."$json$::jsonb),
  ('fr', 'model.refresh.dirty', $json$"Enregistrez ou annulez d'abord vos modifications"$json$::jsonb),
  ('fr', 'model.refresh.done', $json${"one": "{count} modèle chargé depuis {agent}", "other": "{count} modèles chargés depuis {agent}"}$json$::jsonb),
  ('fr', 'model.refresh.silent', $json$"{agent} n'a pas listé ses modèles. Vérifiez qu'il est installé et connecté."$json$::jsonb),
  ('fr', 'agent.section.models.description', $json$"Les modèles que l'agent propose dans /model. Jev choisit parmi ceux activés pour chaque demande."$json$::jsonb),
  ('ru', 'chat.refused', $json${"one": "{count} изменение в этом чате отклонено сервером", "few": "{count} изменения в этом чате отклонены сервером", "many": "{count} изменений в этом чате отклонено сервером", "other": "{count} изменения в этом чате отклонено сервером"}$json$::jsonb),
  ('ru', 'project.refused', $json${"one": "{count} изменение в этом проекте отклонено сервером", "few": "{count} изменения в этом проекте отклонены сервером", "many": "{count} изменений в этом проекте отклонено сервером", "other": "{count} изменения в этом проекте отклонено сервером"}$json$::jsonb),
  ('ru', 'model.refresh', $json$"Загрузить из CLI"$json$::jsonb),
  ('ru', 'model.refresh.running', $json$"Читаем /model…"$json$::jsonb),
  ('ru', 'model.refresh.hint', $json$"Читает список из команды /model агента. Новые модели сразу включены, чтобы Jev мог выбирать среди них."$json$::jsonb),
  ('ru', 'model.refresh.dirty', $json$"Сначала сохраните или отмените изменения"$json$::jsonb),
  ('ru', 'model.refresh.done', $json${"one": "Из {agent} загружена {count} модель", "few": "Из {agent} загружено {count} модели", "many": "Из {agent} загружено {count} моделей", "other": "Из {agent} загружено {count} модели"}$json$::jsonb),
  ('ru', 'model.refresh.silent', $json$"{agent} не показал список моделей. Проверьте, что он установлен и выполнен вход."$json$::jsonb),
  ('ru', 'agent.section.models.description', $json$"Модели, которые агент предлагает в /model. Jev выбирает среди включённых для каждого запроса."$json$::jsonb),
  ('ja', 'chat.refused', $json${"other": "このチャットの変更 {count} 件がサーバーに拒否されました"}$json$::jsonb),
  ('ja', 'project.refused', $json${"other": "このプロジェクトの変更 {count} 件がサーバーに拒否されました"}$json$::jsonb),
  ('ja', 'model.refresh', $json$"CLI から読み込む"$json$::jsonb),
  ('ja', 'model.refresh.running', $json$"/model を読み込み中…"$json$::jsonb),
  ('ja', 'model.refresh.hint', $json$"エージェントの /model コマンドから一覧を読み込みます。新しいモデルは有効な状態で追加され、Jev がその中から選びます。"$json$::jsonb),
  ('ja', 'model.refresh.dirty', $json$"先に変更を保存するか破棄してください"$json$::jsonb),
  ('ja', 'model.refresh.done', $json${"other": "{agent} から {count} 個のモデルを読み込みました"}$json$::jsonb),
  ('ja', 'model.refresh.silent', $json$"{agent} がモデルを一覧表示しませんでした。インストールとサインインを確認してください。"$json$::jsonb),
  ('ja', 'agent.section.models.description', $json$"エージェントが /model で提供するモデルです。Jev はリクエストごとに有効なモデルから選びます。"$json$::jsonb),
  ('de', 'chat.refused', $json${"one": "{count} Änderung in diesem Chat vom Server abgelehnt", "other": "{count} Änderungen in diesem Chat vom Server abgelehnt"}$json$::jsonb),
  ('de', 'project.refused', $json${"one": "{count} Änderung in diesem Projekt vom Server abgelehnt", "other": "{count} Änderungen in diesem Projekt vom Server abgelehnt"}$json$::jsonb),
  ('de', 'model.refresh', $json$"Aus der CLI laden"$json$::jsonb),
  ('de', 'model.refresh.running', $json$"/model wird gelesen…"$json$::jsonb),
  ('de', 'model.refresh.hint', $json$"Liest die Liste aus dem /model-Befehl des Agenten. Neue Modelle sind gleich aktiviert, damit Jev zwischen ihnen wählen kann."$json$::jsonb),
  ('de', 'model.refresh.dirty', $json$"Speichere oder verwirf zuerst deine Änderungen"$json$::jsonb),
  ('de', 'model.refresh.done', $json${"one": "{count} Modell aus {agent} geladen", "other": "{count} Modelle aus {agent} geladen"}$json$::jsonb),
  ('de', 'model.refresh.silent', $json$"{agent} hat keine Modelle aufgelistet. Prüfe, ob er installiert und angemeldet ist."$json$::jsonb),
  ('de', 'agent.section.models.description', $json$"Die Modelle, die der Agent in /model anbietet. Jev wählt für jede Anfrage unter den aktivierten."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
