-- v0.41.0: arquivos ao vivo.
--
-- Só textos: o painel "Ao vivo" ao lado do chat (live.*), com a lista dos
-- arquivos que o pedido mudou, o diff de cada um, seguir o agente e abrir no
-- editor (VS Code, Cursor, Windsurf), os erros do núcleo live.notChanged e
-- live.editor.failed, e o item da janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'live.title', $json$"Ao vivo"$json$::jsonb),
  ('pt-BR', 'live.toggle', $json$"Ao vivo"$json$::jsonb),
  ('pt-BR', 'live.toggle.hint', $json$"Arquivos que o agente muda neste pedido, com o diff atualizando enquanto ele escreve"$json$::jsonb),
  ('pt-BR', 'live.running', $json$"agente trabalhando"$json$::jsonb),
  ('pt-BR', 'live.idle', $json$"pedido terminou"$json$::jsonb),
  ('pt-BR', 'live.follow', $json$"Seguir o agente: mostrar cada arquivo assim que ele muda"$json$::jsonb),
  ('pt-BR', 'live.close', $json$"Fechar o painel ao vivo"$json$::jsonb),
  ('pt-BR', 'live.editor', $json$"Seguir em"$json$::jsonb),
  ('pt-BR', 'live.editor.none', $json$"só aqui"$json$::jsonb),
  ('pt-BR', 'live.openIn', $json$"Abrir no {editor}"$json$::jsonb),
  ('pt-BR', 'live.waiting', $json$"Nenhum arquivo mudou neste pedido ainda. As mudanças aparecem aqui enquanto o agente escreve."$json$::jsonb),
  ('pt-BR', 'live.empty', $json$"O último pedido não mudou nenhum arquivo desta pasta."$json$::jsonb),
  ('pt-BR', 'live.kind.created', $json$"arquivo novo"$json$::jsonb),
  ('pt-BR', 'live.kind.modified', $json$"alterado"$json$::jsonb),
  ('pt-BR', 'live.kind.removed', $json$"apagado"$json$::jsonb),
  ('pt-BR', 'live.hidden', $json$"Coberto pelas regras de privacidade: só o nome aparece."$json$::jsonb),
  ('pt-BR', 'live.binary', $json$"Arquivo binário."$json$::jsonb),
  ('pt-BR', 'live.tooLarge', $json$"Grande demais para mostrar (mais de 1 MB)."$json$::jsonb),
  ('pt-BR', 'live.failed', $json$"Não foi possível ler este arquivo."$json$::jsonb),
  ('pt-BR', 'live.noBefore', $json$"Esta pasta não tem git: o JayV não tem como saber como o arquivo estava antes, então mostra o arquivo inteiro."$json$::jsonb),
  ('pt-BR', 'live.same', $json$"Igual a quando o pedido começou."$json$::jsonb),
  ('pt-BR', 'live.skipped', $json${"one": "{count} linha igual", "other": "{count} linhas iguais"}$json$::jsonb),
  ('pt-BR', 'live.notChanged', $json$"{path} não mudou no último pedido deste chat."$json$::jsonb),
  ('pt-BR', 'live.editor.failed', $json$"Não foi possível abrir o {editor}: {reason}"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveFiles.title', $json$"Veja ao vivo os arquivos que o agente muda"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.liveFiles.detail', $json$"O novo botão Ao vivo no cabeçalho do chat abre, ao lado da conversa, um painel com cada arquivo que o pedido muda, o mais recente no topo, e o diff de cada um contra como ele estava quando o pedido começou, atualizando enquanto o agente escreve. Ele abre sozinho na primeira mudança. Seguindo o agente, cada arquivo aparece assim que muda e, se o VS Code, o Cursor ou o Windsurf estiver instalado, também pode abrir lá, na linha alterada. Tudo fica neste computador, e arquivos cobertos pelas regras de privacidade mostram só o nome."$json$::jsonb),
  ('en', 'live.title', $json$"Live"$json$::jsonb),
  ('en', 'live.toggle', $json$"Live"$json$::jsonb),
  ('en', 'live.toggle.hint', $json$"Files the agent changes in this request, with the diff updating as it writes"$json$::jsonb),
  ('en', 'live.running', $json$"agent working"$json$::jsonb),
  ('en', 'live.idle', $json$"request finished"$json$::jsonb),
  ('en', 'live.follow', $json$"Follow the agent: show each file as soon as it changes"$json$::jsonb),
  ('en', 'live.close', $json$"Close the live panel"$json$::jsonb),
  ('en', 'live.editor', $json$"Follow in"$json$::jsonb),
  ('en', 'live.editor.none', $json$"only here"$json$::jsonb),
  ('en', 'live.openIn', $json$"Open in {editor}"$json$::jsonb),
  ('en', 'live.waiting', $json$"No file changed in this request yet. Changes appear here as the agent writes them."$json$::jsonb),
  ('en', 'live.empty', $json$"The last request did not change any file in this folder."$json$::jsonb),
  ('en', 'live.kind.created', $json$"new file"$json$::jsonb),
  ('en', 'live.kind.modified', $json$"changed"$json$::jsonb),
  ('en', 'live.kind.removed', $json$"deleted"$json$::jsonb),
  ('en', 'live.hidden', $json$"Covered by the privacy rules: only the name is shown."$json$::jsonb),
  ('en', 'live.binary', $json$"Binary file."$json$::jsonb),
  ('en', 'live.tooLarge', $json$"Too large to show (over 1 MB)."$json$::jsonb),
  ('en', 'live.failed', $json$"Could not read this file."$json$::jsonb),
  ('en', 'live.noBefore', $json$"This folder has no git: JayV cannot know how the file was before, so it shows the whole file."$json$::jsonb),
  ('en', 'live.same', $json$"Same as when the request started."$json$::jsonb),
  ('en', 'live.skipped', $json${"one": "{count} unchanged line", "other": "{count} unchanged lines"}$json$::jsonb),
  ('en', 'live.notChanged', $json$"{path} did not change in the last request of this chat."$json$::jsonb),
  ('en', 'live.editor.failed', $json$"Could not open {editor}: {reason}"$json$::jsonb),
  ('en', 'whatsNew.item.liveFiles.title', $json$"Watch the files the agent changes, live"$json$::jsonb),
  ('en', 'whatsNew.item.liveFiles.detail', $json$"The new Live button in the chat header opens a panel beside the conversation with every file the request changes, newest first, and the diff of each one against how it was when the request started, updating as the agent writes. It opens by itself on the first change. Following the agent shows each file as soon as it changes, and if VS Code, Cursor or Windsurf is installed, it can open each file there too, on the changed line. Everything stays on this computer, and files covered by the privacy rules show only their name."$json$::jsonb),
  ('es', 'live.title', $json$"En vivo"$json$::jsonb),
  ('es', 'live.toggle', $json$"En vivo"$json$::jsonb),
  ('es', 'live.toggle.hint', $json$"Archivos que el agente cambia en esta solicitud, con el diff actualizándose mientras escribe"$json$::jsonb),
  ('es', 'live.running', $json$"agente trabajando"$json$::jsonb),
  ('es', 'live.idle', $json$"solicitud terminada"$json$::jsonb),
  ('es', 'live.follow', $json$"Seguir al agente: mostrar cada archivo en cuanto cambia"$json$::jsonb),
  ('es', 'live.close', $json$"Cerrar el panel en vivo"$json$::jsonb),
  ('es', 'live.editor', $json$"Seguir en"$json$::jsonb),
  ('es', 'live.editor.none', $json$"solo aquí"$json$::jsonb),
  ('es', 'live.openIn', $json$"Abrir en {editor}"$json$::jsonb),
  ('es', 'live.waiting', $json$"Todavía no cambió ningún archivo en esta solicitud. Los cambios aparecen aquí mientras el agente escribe."$json$::jsonb),
  ('es', 'live.empty', $json$"La última solicitud no cambió ningún archivo de esta carpeta."$json$::jsonb),
  ('es', 'live.kind.created', $json$"archivo nuevo"$json$::jsonb),
  ('es', 'live.kind.modified', $json$"modificado"$json$::jsonb),
  ('es', 'live.kind.removed', $json$"eliminado"$json$::jsonb),
  ('es', 'live.hidden', $json$"Cubierto por las reglas de privacidad: solo se muestra el nombre."$json$::jsonb),
  ('es', 'live.binary', $json$"Archivo binario."$json$::jsonb),
  ('es', 'live.tooLarge', $json$"Demasiado grande para mostrar (más de 1 MB)."$json$::jsonb),
  ('es', 'live.failed', $json$"No se pudo leer este archivo."$json$::jsonb),
  ('es', 'live.noBefore', $json$"Esta carpeta no tiene git: JayV no puede saber cómo estaba el archivo antes, así que muestra el archivo completo."$json$::jsonb),
  ('es', 'live.same', $json$"Igual que cuando empezó la solicitud."$json$::jsonb),
  ('es', 'live.skipped', $json${"one": "{count} línea sin cambios", "other": "{count} líneas sin cambios"}$json$::jsonb),
  ('es', 'live.notChanged', $json$"{path} no cambió en la última solicitud de este chat."$json$::jsonb),
  ('es', 'live.editor.failed', $json$"No se pudo abrir {editor}: {reason}"$json$::jsonb),
  ('es', 'whatsNew.item.liveFiles.title', $json$"Mira en vivo los archivos que cambia el agente"$json$::jsonb),
  ('es', 'whatsNew.item.liveFiles.detail', $json$"El nuevo botón En vivo en la cabecera del chat abre, junto a la conversación, un panel con cada archivo que cambia la solicitud, el más reciente arriba, y el diff de cada uno frente a cómo estaba al empezar la solicitud, actualizándose mientras el agente escribe. Se abre solo con el primer cambio. Siguiendo al agente, cada archivo aparece en cuanto cambia y, si VS Code, Cursor o Windsurf está instalado, también puede abrirse allí, en la línea modificada. Todo queda en este equipo, y los archivos cubiertos por las reglas de privacidad solo muestran su nombre."$json$::jsonb),
  ('zh-CN', 'live.title', $json$"实时"$json$::jsonb),
  ('zh-CN', 'live.toggle', $json$"实时"$json$::jsonb),
  ('zh-CN', 'live.toggle.hint', $json$"智能体在此请求中修改的文件，差异随写入实时更新"$json$::jsonb),
  ('zh-CN', 'live.running', $json$"智能体工作中"$json$::jsonb),
  ('zh-CN', 'live.idle', $json$"请求已完成"$json$::jsonb),
  ('zh-CN', 'live.follow', $json$"跟随智能体：文件一变化就显示"$json$::jsonb),
  ('zh-CN', 'live.close', $json$"关闭实时面板"$json$::jsonb),
  ('zh-CN', 'live.editor', $json$"同步到"$json$::jsonb),
  ('zh-CN', 'live.editor.none', $json$"仅此处"$json$::jsonb),
  ('zh-CN', 'live.openIn', $json$"在 {editor} 中打开"$json$::jsonb),
  ('zh-CN', 'live.waiting', $json$"此请求中还没有文件被修改。智能体写入时，改动会显示在这里。"$json$::jsonb),
  ('zh-CN', 'live.empty', $json$"上一个请求没有修改此文件夹中的任何文件。"$json$::jsonb),
  ('zh-CN', 'live.kind.created', $json$"新文件"$json$::jsonb),
  ('zh-CN', 'live.kind.modified', $json$"已修改"$json$::jsonb),
  ('zh-CN', 'live.kind.removed', $json$"已删除"$json$::jsonb),
  ('zh-CN', 'live.hidden', $json$"受隐私规则保护：只显示文件名。"$json$::jsonb),
  ('zh-CN', 'live.binary', $json$"二进制文件。"$json$::jsonb),
  ('zh-CN', 'live.tooLarge', $json$"文件过大，无法显示（超过 1 MB）。"$json$::jsonb),
  ('zh-CN', 'live.failed', $json$"无法读取此文件。"$json$::jsonb),
  ('zh-CN', 'live.noBefore', $json$"此文件夹没有 git：JayV 无法得知文件之前的内容，因此显示整个文件。"$json$::jsonb),
  ('zh-CN', 'live.same', $json$"与请求开始时相同。"$json$::jsonb),
  ('zh-CN', 'live.skipped', $json${"other": "{count} 行未改动"}$json$::jsonb),
  ('zh-CN', 'live.notChanged', $json$"{path} 在此聊天的上一个请求中没有改动。"$json$::jsonb),
  ('zh-CN', 'live.editor.failed', $json$"无法打开 {editor}：{reason}"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveFiles.title', $json$"实时查看智能体修改的文件"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.liveFiles.detail', $json$"聊天顶部新增“实时”按钮，会在对话旁打开一个面板，列出本次请求修改的每个文件（最新的在最上面），并显示每个文件相对于请求开始时的差异，随智能体写入实时更新。首次有改动时会自动打开。开启“跟随智能体”后，文件一变化就会显示；如果安装了 VS Code、Cursor 或 Windsurf，还可以在其中打开该文件并定位到修改的行。所有内容都留在本机，受隐私规则保护的文件只显示名称。"$json$::jsonb),
  ('hi', 'live.title', $json$"लाइव"$json$::jsonb),
  ('hi', 'live.toggle', $json$"लाइव"$json$::jsonb),
  ('hi', 'live.toggle.hint', $json$"इस अनुरोध में एजेंट जो फ़ाइलें बदलता है, लिखते समय अपडेट होते diff के साथ"$json$::jsonb),
  ('hi', 'live.running', $json$"एजेंट काम कर रहा है"$json$::jsonb),
  ('hi', 'live.idle', $json$"अनुरोध पूरा हुआ"$json$::jsonb),
  ('hi', 'live.follow', $json$"एजेंट को फ़ॉलो करें: हर फ़ाइल बदलते ही दिखाएँ"$json$::jsonb),
  ('hi', 'live.close', $json$"लाइव पैनल बंद करें"$json$::jsonb),
  ('hi', 'live.editor', $json$"इसमें फ़ॉलो करें"$json$::jsonb),
  ('hi', 'live.editor.none', $json$"सिर्फ़ यहाँ"$json$::jsonb),
  ('hi', 'live.openIn', $json$"{editor} में खोलें"$json$::jsonb),
  ('hi', 'live.waiting', $json$"इस अनुरोध में अभी कोई फ़ाइल नहीं बदली। एजेंट के लिखते ही बदलाव यहाँ दिखेंगे।"$json$::jsonb),
  ('hi', 'live.empty', $json$"पिछले अनुरोध ने इस फ़ोल्डर की कोई फ़ाइल नहीं बदली।"$json$::jsonb),
  ('hi', 'live.kind.created', $json$"नई फ़ाइल"$json$::jsonb),
  ('hi', 'live.kind.modified', $json$"बदली गई"$json$::jsonb),
  ('hi', 'live.kind.removed', $json$"हटाई गई"$json$::jsonb),
  ('hi', 'live.hidden', $json$"गोपनीयता नियमों के तहत: सिर्फ़ नाम दिखता है।"$json$::jsonb),
  ('hi', 'live.binary', $json$"बाइनरी फ़ाइल।"$json$::jsonb),
  ('hi', 'live.tooLarge', $json$"दिखाने के लिए बहुत बड़ी (1 MB से ज़्यादा)।"$json$::jsonb),
  ('hi', 'live.failed', $json$"यह फ़ाइल पढ़ी नहीं जा सकी।"$json$::jsonb),
  ('hi', 'live.noBefore', $json$"इस फ़ोल्डर में git नहीं है: JayV नहीं जान सकता कि फ़ाइल पहले कैसी थी, इसलिए पूरी फ़ाइल दिखाता है।"$json$::jsonb),
  ('hi', 'live.same', $json$"अनुरोध शुरू होने के समय जैसी ही।"$json$::jsonb),
  ('hi', 'live.skipped', $json${"one": "{count} पंक्ति अपरिवर्तित", "other": "{count} पंक्तियाँ अपरिवर्तित"}$json$::jsonb),
  ('hi', 'live.notChanged', $json$"{path} इस चैट के पिछले अनुरोध में नहीं बदली।"$json$::jsonb),
  ('hi', 'live.editor.failed', $json$"{editor} नहीं खुल सका: {reason}"$json$::jsonb),
  ('hi', 'whatsNew.item.liveFiles.title', $json$"एजेंट जो फ़ाइलें बदलता है, उन्हें लाइव देखें"$json$::jsonb),
  ('hi', 'whatsNew.item.liveFiles.detail', $json$"चैट के हेडर में नया लाइव बटन बातचीत के बगल में एक पैनल खोलता है, जिसमें अनुरोध से बदली हर फ़ाइल (सबसे नई ऊपर) और अनुरोध शुरू होने के समय की तुलना में उसका diff होता है, जो एजेंट के लिखते ही अपडेट होता है। पहला बदलाव होते ही यह अपने आप खुलता है। एजेंट को फ़ॉलो करने पर हर फ़ाइल बदलते ही दिखती है, और VS Code, Cursor या Windsurf इंस्टॉल हो तो वह फ़ाइल वहाँ बदली गई पंक्ति पर भी खुल सकती है। सब कुछ इसी कंप्यूटर पर रहता है, और गोपनीयता नियमों के तहत आने वाली फ़ाइलों का सिर्फ़ नाम दिखता है।"$json$::jsonb),
  ('ar', 'live.title', $json$"مباشر"$json$::jsonb),
  ('ar', 'live.toggle', $json$"مباشر"$json$::jsonb),
  ('ar', 'live.toggle.hint', $json$"الملفات التي يغيّرها الوكيل في هذا الطلب، مع تحديث الفروق أثناء الكتابة"$json$::jsonb),
  ('ar', 'live.running', $json$"الوكيل يعمل"$json$::jsonb),
  ('ar', 'live.idle', $json$"انتهى الطلب"$json$::jsonb),
  ('ar', 'live.follow', $json$"تتبّع الوكيل: اعرض كل ملف فور تغيّره"$json$::jsonb),
  ('ar', 'live.close', $json$"إغلاق اللوحة المباشرة"$json$::jsonb),
  ('ar', 'live.editor', $json$"التتبع في"$json$::jsonb),
  ('ar', 'live.editor.none', $json$"هنا فقط"$json$::jsonb),
  ('ar', 'live.openIn', $json$"فتح في {editor}"$json$::jsonb),
  ('ar', 'live.waiting', $json$"لم يتغير أي ملف في هذا الطلب بعد. تظهر التغييرات هنا أثناء كتابة الوكيل."$json$::jsonb),
  ('ar', 'live.empty', $json$"لم يغيّر الطلب الأخير أي ملف في هذا المجلد."$json$::jsonb),
  ('ar', 'live.kind.created', $json$"ملف جديد"$json$::jsonb),
  ('ar', 'live.kind.modified', $json$"معدّل"$json$::jsonb),
  ('ar', 'live.kind.removed', $json$"محذوف"$json$::jsonb),
  ('ar', 'live.hidden', $json$"مشمول بقواعد الخصوصية: يظهر الاسم فقط."$json$::jsonb),
  ('ar', 'live.binary', $json$"ملف ثنائي."$json$::jsonb),
  ('ar', 'live.tooLarge', $json$"أكبر من أن يُعرض (أكثر من 1 ميغابايت)."$json$::jsonb),
  ('ar', 'live.failed', $json$"تعذّرت قراءة هذا الملف."$json$::jsonb),
  ('ar', 'live.noBefore', $json$"لا يحتوي هذا المجلد على git: لا يستطيع JayV معرفة حالة الملف سابقًا، لذا يعرض الملف كاملًا."$json$::jsonb),
  ('ar', 'live.same', $json$"كما كان عند بدء الطلب."$json$::jsonb),
  ('ar', 'live.skipped', $json${"zero": "لا أسطر دون تغيير", "one": "سطر واحد دون تغيير", "two": "سطران دون تغيير", "few": "{count} أسطر دون تغيير", "many": "{count} سطرًا دون تغيير", "other": "{count} سطر دون تغيير"}$json$::jsonb),
  ('ar', 'live.notChanged', $json$"لم يتغير {path} في آخر طلب في هذه الدردشة."$json$::jsonb),
  ('ar', 'live.editor.failed', $json$"تعذّر فتح {editor}: {reason}"$json$::jsonb),
  ('ar', 'whatsNew.item.liveFiles.title', $json$"شاهد مباشرةً الملفات التي يغيّرها الوكيل"$json$::jsonb),
  ('ar', 'whatsNew.item.liveFiles.detail', $json$"يفتح زر «مباشر» الجديد في رأس الدردشة لوحة بجانب المحادثة تعرض كل ملف يغيّره الطلب، الأحدث أولًا، مع الفروق بين حالته الآن وحالته عند بدء الطلب، وتتحدث أثناء كتابة الوكيل. تُفتح اللوحة تلقائيًا عند أول تغيير. عند تتبّع الوكيل يظهر كل ملف فور تغيّره، وإذا كان VS Code أو Cursor أو Windsurf مثبتًا يمكن فتح الملف فيه أيضًا عند السطر المعدّل. يبقى كل شيء على هذا الجهاز، والملفات المشمولة بقواعد الخصوصية يظهر اسمها فقط."$json$::jsonb),
  ('fr', 'live.title', $json$"En direct"$json$::jsonb),
  ('fr', 'live.toggle', $json$"En direct"$json$::jsonb),
  ('fr', 'live.toggle.hint', $json$"Les fichiers que l’agent modifie dans cette demande, avec le diff mis à jour pendant qu’il écrit"$json$::jsonb),
  ('fr', 'live.running', $json$"agent au travail"$json$::jsonb),
  ('fr', 'live.idle', $json$"demande terminée"$json$::jsonb),
  ('fr', 'live.follow', $json$"Suivre l’agent : afficher chaque fichier dès qu’il change"$json$::jsonb),
  ('fr', 'live.close', $json$"Fermer le panneau en direct"$json$::jsonb),
  ('fr', 'live.editor', $json$"Suivre dans"$json$::jsonb),
  ('fr', 'live.editor.none', $json$"ici seulement"$json$::jsonb),
  ('fr', 'live.openIn', $json$"Ouvrir dans {editor}"$json$::jsonb),
  ('fr', 'live.waiting', $json$"Aucun fichier n’a encore changé dans cette demande. Les modifications apparaissent ici pendant que l’agent écrit."$json$::jsonb),
  ('fr', 'live.empty', $json$"La dernière demande n’a modifié aucun fichier de ce dossier."$json$::jsonb),
  ('fr', 'live.kind.created', $json$"nouveau fichier"$json$::jsonb),
  ('fr', 'live.kind.modified', $json$"modifié"$json$::jsonb),
  ('fr', 'live.kind.removed', $json$"supprimé"$json$::jsonb),
  ('fr', 'live.hidden', $json$"Couvert par les règles de confidentialité : seul le nom est affiché."$json$::jsonb),
  ('fr', 'live.binary', $json$"Fichier binaire."$json$::jsonb),
  ('fr', 'live.tooLarge', $json$"Trop volumineux pour être affiché (plus de 1 Mo)."$json$::jsonb),
  ('fr', 'live.failed', $json$"Impossible de lire ce fichier."$json$::jsonb),
  ('fr', 'live.noBefore', $json$"Ce dossier n’a pas de git : JayV ne peut pas savoir comment était le fichier avant, il affiche donc le fichier entier."$json$::jsonb),
  ('fr', 'live.same', $json$"Identique au début de la demande."$json$::jsonb),
  ('fr', 'live.skipped', $json${"one": "{count} ligne inchangée", "other": "{count} lignes inchangées"}$json$::jsonb),
  ('fr', 'live.notChanged', $json$"{path} n’a pas changé lors de la dernière demande de ce chat."$json$::jsonb),
  ('fr', 'live.editor.failed', $json$"Impossible d’ouvrir {editor} : {reason}"$json$::jsonb),
  ('fr', 'whatsNew.item.liveFiles.title', $json$"Suivez en direct les fichiers que l’agent modifie"$json$::jsonb),
  ('fr', 'whatsNew.item.liveFiles.detail', $json$"Le nouveau bouton En direct dans l’en-tête du chat ouvre, à côté de la conversation, un panneau listant chaque fichier modifié par la demande, le plus récent en haut, avec le diff de chacun par rapport à son état au début de la demande, mis à jour pendant que l’agent écrit. Il s’ouvre tout seul au premier changement. En suivant l’agent, chaque fichier s’affiche dès qu’il change et, si VS Code, Cursor ou Windsurf est installé, il peut aussi s’ouvrir là-bas, sur la ligne modifiée. Tout reste sur cet ordinateur, et les fichiers couverts par les règles de confidentialité n’affichent que leur nom."$json$::jsonb),
  ('ru', 'live.title', $json$"В реальном времени"$json$::jsonb),
  ('ru', 'live.toggle', $json$"Вживую"$json$::jsonb),
  ('ru', 'live.toggle.hint', $json$"Файлы, которые агент меняет в этом запросе, с diff, обновляющимся по мере записи"$json$::jsonb),
  ('ru', 'live.running', $json$"агент работает"$json$::jsonb),
  ('ru', 'live.idle', $json$"запрос завершён"$json$::jsonb),
  ('ru', 'live.follow', $json$"Следить за агентом: показывать файл, как только он меняется"$json$::jsonb),
  ('ru', 'live.close', $json$"Закрыть панель"$json$::jsonb),
  ('ru', 'live.editor', $json$"Следить в"$json$::jsonb),
  ('ru', 'live.editor.none', $json$"только здесь"$json$::jsonb),
  ('ru', 'live.openIn', $json$"Открыть в {editor}"$json$::jsonb),
  ('ru', 'live.waiting', $json$"В этом запросе пока не изменено ни одного файла. Изменения появятся здесь по мере записи агентом."$json$::jsonb),
  ('ru', 'live.empty', $json$"Последний запрос не изменил ни одного файла в этой папке."$json$::jsonb),
  ('ru', 'live.kind.created', $json$"новый файл"$json$::jsonb),
  ('ru', 'live.kind.modified', $json$"изменён"$json$::jsonb),
  ('ru', 'live.kind.removed', $json$"удалён"$json$::jsonb),
  ('ru', 'live.hidden', $json$"Защищено правилами конфиденциальности: показывается только имя."$json$::jsonb),
  ('ru', 'live.binary', $json$"Двоичный файл."$json$::jsonb),
  ('ru', 'live.tooLarge', $json$"Слишком большой для показа (больше 1 МБ)."$json$::jsonb),
  ('ru', 'live.failed', $json$"Не удалось прочитать этот файл."$json$::jsonb),
  ('ru', 'live.noBefore', $json$"В этой папке нет git: JayV не может знать, каким файл был раньше, поэтому показывает его целиком."$json$::jsonb),
  ('ru', 'live.same', $json$"Так же, как в начале запроса."$json$::jsonb),
  ('ru', 'live.skipped', $json${"one": "{count} строка без изменений", "few": "{count} строки без изменений", "many": "{count} строк без изменений", "other": "{count} строки без изменений"}$json$::jsonb),
  ('ru', 'live.notChanged', $json$"{path} не менялся в последнем запросе этого чата."$json$::jsonb),
  ('ru', 'live.editor.failed', $json$"Не удалось открыть {editor}: {reason}"$json$::jsonb),
  ('ru', 'whatsNew.item.liveFiles.title', $json$"Смотрите в реальном времени, какие файлы меняет агент"$json$::jsonb),
  ('ru', 'whatsNew.item.liveFiles.detail', $json$"Новая кнопка «Вживую» в заголовке чата открывает рядом с разговором панель со всеми файлами, которые меняет запрос (новые сверху), и diff каждого относительно состояния в начале запроса; он обновляется по мере записи агентом. Панель открывается сама при первом изменении. В режиме слежения каждый файл показывается сразу после изменения, а если установлены VS Code, Cursor или Windsurf, его можно открыть и там, на изменённой строке. Всё остаётся на этом компьютере, а для файлов под правилами конфиденциальности показывается только имя."$json$::jsonb),
  ('ja', 'live.title', $json$"ライブ"$json$::jsonb),
  ('ja', 'live.toggle', $json$"ライブ"$json$::jsonb),
  ('ja', 'live.toggle.hint', $json$"このリクエストでエージェントが変更するファイル。書き込みに合わせて差分が更新されます"$json$::jsonb),
  ('ja', 'live.running', $json$"エージェント作業中"$json$::jsonb),
  ('ja', 'live.idle', $json$"リクエスト完了"$json$::jsonb),
  ('ja', 'live.follow', $json$"エージェントを追う：ファイルが変わったらすぐ表示"$json$::jsonb),
  ('ja', 'live.close', $json$"ライブパネルを閉じる"$json$::jsonb),
  ('ja', 'live.editor', $json$"追従先"$json$::jsonb),
  ('ja', 'live.editor.none', $json$"ここだけ"$json$::jsonb),
  ('ja', 'live.openIn', $json$"{editor} で開く"$json$::jsonb),
  ('ja', 'live.waiting', $json$"このリクエストではまだファイルが変更されていません。エージェントが書き込むと、ここに表示されます。"$json$::jsonb),
  ('ja', 'live.empty', $json$"直前のリクエストでは、このフォルダーのファイルは変更されませんでした。"$json$::jsonb),
  ('ja', 'live.kind.created', $json$"新規ファイル"$json$::jsonb),
  ('ja', 'live.kind.modified', $json$"変更"$json$::jsonb),
  ('ja', 'live.kind.removed', $json$"削除"$json$::jsonb),
  ('ja', 'live.hidden', $json$"プライバシールールの対象です。名前のみ表示されます。"$json$::jsonb),
  ('ja', 'live.binary', $json$"バイナリファイルです。"$json$::jsonb),
  ('ja', 'live.tooLarge', $json$"大きすぎて表示できません（1 MB 超）。"$json$::jsonb),
  ('ja', 'live.failed', $json$"このファイルを読み込めませんでした。"$json$::jsonb),
  ('ja', 'live.noBefore', $json$"このフォルダーには git がありません。変更前の状態がわからないため、ファイル全体を表示します。"$json$::jsonb),
  ('ja', 'live.same', $json$"リクエスト開始時と同じです。"$json$::jsonb),
  ('ja', 'live.skipped', $json${"other": "変更なし {count} 行"}$json$::jsonb),
  ('ja', 'live.notChanged', $json$"{path} はこのチャットの直前のリクエストで変更されていません。"$json$::jsonb),
  ('ja', 'live.editor.failed', $json$"{editor} を開けませんでした：{reason}"$json$::jsonb),
  ('ja', 'whatsNew.item.liveFiles.title', $json$"エージェントが変更するファイルをライブで確認"$json$::jsonb),
  ('ja', 'whatsNew.item.liveFiles.detail', $json$"チャットのヘッダーに追加された「ライブ」ボタンで、会話の横にパネルが開きます。リクエストで変更された各ファイルが新しい順に並び、リクエスト開始時との差分がエージェントの書き込みに合わせて更新されます。最初の変更で自動的に開きます。エージェントを追うと、変更されたファイルがすぐ表示され、VS Code・Cursor・Windsurf がインストールされていれば、変更された行でそのファイルを開くこともできます。すべてこのコンピューター内で完結し、プライバシールールの対象ファイルは名前のみ表示されます。"$json$::jsonb),
  ('de', 'live.title', $json$"Live"$json$::jsonb),
  ('de', 'live.toggle', $json$"Live"$json$::jsonb),
  ('de', 'live.toggle.hint', $json$"Dateien, die der Agent in dieser Anfrage ändert, mit einem Diff, der sich beim Schreiben aktualisiert"$json$::jsonb),
  ('de', 'live.running', $json$"Agent arbeitet"$json$::jsonb),
  ('de', 'live.idle', $json$"Anfrage beendet"$json$::jsonb),
  ('de', 'live.follow', $json$"Dem Agenten folgen: jede Datei zeigen, sobald sie sich ändert"$json$::jsonb),
  ('de', 'live.close', $json$"Live-Bereich schließen"$json$::jsonb),
  ('de', 'live.editor', $json$"Folgen in"$json$::jsonb),
  ('de', 'live.editor.none', $json$"nur hier"$json$::jsonb),
  ('de', 'live.openIn', $json$"In {editor} öffnen"$json$::jsonb),
  ('de', 'live.waiting', $json$"In dieser Anfrage hat sich noch keine Datei geändert. Änderungen erscheinen hier, während der Agent schreibt."$json$::jsonb),
  ('de', 'live.empty', $json$"Die letzte Anfrage hat keine Datei in diesem Ordner geändert."$json$::jsonb),
  ('de', 'live.kind.created', $json$"neue Datei"$json$::jsonb),
  ('de', 'live.kind.modified', $json$"geändert"$json$::jsonb),
  ('de', 'live.kind.removed', $json$"gelöscht"$json$::jsonb),
  ('de', 'live.hidden', $json$"Von den Datenschutzregeln erfasst: nur der Name wird angezeigt."$json$::jsonb),
  ('de', 'live.binary', $json$"Binärdatei."$json$::jsonb),
  ('de', 'live.tooLarge', $json$"Zu groß zum Anzeigen (über 1 MB)."$json$::jsonb),
  ('de', 'live.failed', $json$"Diese Datei konnte nicht gelesen werden."$json$::jsonb),
  ('de', 'live.noBefore', $json$"Dieser Ordner hat kein git: JayV kann nicht wissen, wie die Datei vorher war, und zeigt daher die ganze Datei."$json$::jsonb),
  ('de', 'live.same', $json$"Wie zu Beginn der Anfrage."$json$::jsonb),
  ('de', 'live.skipped', $json${"one": "{count} unveränderte Zeile", "other": "{count} unveränderte Zeilen"}$json$::jsonb),
  ('de', 'live.notChanged', $json$"{path} hat sich in der letzten Anfrage dieses Chats nicht geändert."$json$::jsonb),
  ('de', 'live.editor.failed', $json$"{editor} konnte nicht geöffnet werden: {reason}"$json$::jsonb),
  ('de', 'whatsNew.item.liveFiles.title', $json$"Live sehen, welche Dateien der Agent ändert"$json$::jsonb),
  ('de', 'whatsNew.item.liveFiles.detail', $json$"Der neue Live-Button im Chat-Kopf öffnet neben der Unterhaltung einen Bereich mit jeder Datei, die die Anfrage ändert, die neueste oben, und dem Diff jeder Datei gegenüber dem Stand zu Beginn der Anfrage, der sich beim Schreiben des Agenten aktualisiert. Er öffnet sich bei der ersten Änderung von selbst. Beim Folgen des Agenten erscheint jede Datei, sobald sie sich ändert, und wenn VS Code, Cursor oder Windsurf installiert ist, kann sie dort auch an der geänderten Zeile geöffnet werden. Alles bleibt auf diesem Computer, und Dateien unter den Datenschutzregeln zeigen nur ihren Namen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
