-- v0.40.0: chat da organização com os repositórios, intervalo das
-- atualizações e traduções que faltavam.
--
-- Textos novos: o painel de repositórios no topo do chat da organização
-- (chatRepos.*), o "procurar a cada" de Configurações › App
-- (app.updates.*) e os itens da janela "Novidades" desta versão.
-- orgChat.open muda de texto ("Agente em todos os repositórios" vira
-- "Abrir chat"); os parâmetros são os mesmos, então a chave é a mesma.
--
-- Traduções que faltavam: a janela de atualização (update.title,
-- update.checking, update.fromTo, update.description, update.step.*,
-- update.progress*, update.keepOpen, update.restarting.note, update.notes,
-- update.retry) e common.close não tinham linha em idioma nenhum, e a tela
-- caía no inglês embutido; auth.* e connection.* só tinham inglês e
-- português.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'orgChat.open', $json$"Abrir chat"$json$::jsonb),
  ('pt-BR', 'chatRepos.title', $json$"Repositórios neste chat"$json$::jsonb),
  ('pt-BR', 'chatRepos.count', $json${"one": "{count} na pasta", "other": "{count} na pasta"}$json$::jsonb),
  ('pt-BR', 'chatRepos.dirty', $json${"one": "{count} com alterações", "other": "{count} com alterações"}$json$::jsonb),
  ('pt-BR', 'chatRepos.refresh', $json$"Conferir os repositórios de novo"$json$::jsonb),
  ('pt-BR', 'chatRepos.loading', $json$"Lendo os repositórios…"$json$::jsonb),
  ('pt-BR', 'chatRepos.failed', $json$"Não foi possível ler os repositórios desta pasta."$json$::jsonb),
  ('pt-BR', 'chatRepos.empty', $json$"Ainda não há nenhum repositório dentro desta pasta."$json$::jsonb),
  ('pt-BR', 'chatRepos.outside', $json$"fora desta pasta"$json$::jsonb),
  ('pt-BR', 'chatRepos.detached', $json$"sem branch (detached)"$json$::jsonb),
  ('pt-BR', 'chatRepos.unreadable', $json$"o git não respondeu"$json$::jsonb),
  ('pt-BR', 'chatRepos.clean', $json$"limpo"$json$::jsonb),
  ('pt-BR', 'chatRepos.changed', $json${"one": "{count} alteração", "other": "{count} alterações"}$json$::jsonb),
  ('pt-BR', 'chatRepos.policy.repository', $json$"política própria"$json$::jsonb),
  ('pt-BR', 'chatRepos.policy.organization', $json$"política da organização"$json$::jsonb),
  ('pt-BR', 'chatRepos.policy.none', $json$"sem política"$json$::jsonb),
  ('pt-BR', 'chatRepos.unregistered', $json$"fora da organização"$json$::jsonb),
  ('pt-BR', 'chatRepos.policy.hint', $json$"O chat aplica as regras mais restritas da organização e de todos os repositórios dela, juntas."$json$::jsonb),
  ('pt-BR', 'app.updates.every', $json$"Procurar a cada"$json$::jsonb),
  ('pt-BR', 'app.updates.everyHint', $json$"O JayV procura versão nova ao abrir e de novo neste intervalo. Quando há uma, um aviso aparece no topo de todas as telas."$json$::jsonb),
  ('pt-BR', 'app.updates.minutes', $json${"one": "{count} minuto", "other": "{count} minutos"}$json$::jsonb),
  ('pt-BR', 'app.updates.hours', $json${"one": "{count} hora", "other": "{count} horas"}$json$::jsonb),
  ('pt-BR', 'app.updates.checkedAt', $json$"Última verificação: {at}."$json$::jsonb),
  ('pt-BR', 'app.updates.never', $json$"Ainda não verificado desde que o JayV abriu."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatRepositories.title', $json$"Repositórios dentro do chat da organização"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.chatRepositories.detail', $json$"O chat da organização agora mostra, no topo da conversa, cada repositório da pasta da organização: o branch, quanto ele está à frente ou atrás do remoto, quantos arquivos mudaram e de onde vem a política de LLM dele. Ele relê tudo quando um pedido termina. O botão na página da organização e na página Projetos agora se chama Abrir chat."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateInterval.title', $json$"Escolha de quanto em quanto tempo procurar atualizações"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updateInterval.detail', $json$"Em Configurações › App você escolhe procurar versão nova a cada 15 minutos, 30 minutos, 1 hora ou 4 horas, e vê quando foi a última verificação. A versão nova aparece no aviso do topo de todas as telas e na barra de status."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.missingTranslations.title', $json$"Textos que ainda apareciam em inglês"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.missingTranslations.detail', $json$"A janela de atualização, o botão Fechar e algumas mensagens de login e de conexão apareciam em inglês em todos os idiomas. Agora estão traduzidos."$json$::jsonb),
  ('pt-BR', 'common.close', $json$"Fechar"$json$::jsonb),
  ('pt-BR', 'update.title', $json$"Atualizando para o JayV {version}"$json$::jsonb),
  ('pt-BR', 'update.checking', $json$"Procurando atualizações"$json$::jsonb),
  ('pt-BR', 'update.fromTo', $json$"Da versão {current} para a {next}. O JayV reinicia sozinho quando terminar."$json$::jsonb),
  ('pt-BR', 'update.description', $json$"O JayV consulta o repositório de releases em busca de uma versão mais nova."$json$::jsonb),
  ('pt-BR', 'update.step.checking', $json$"Procurar versão nova"$json$::jsonb),
  ('pt-BR', 'update.step.downloading', $json$"Baixar a atualização"$json$::jsonb),
  ('pt-BR', 'update.step.installing', $json$"Instalar"$json$::jsonb),
  ('pt-BR', 'update.step.restarting', $json$"Reiniciar o JayV"$json$::jsonb),
  ('pt-BR', 'update.progress', $json$"{received} de {total} MB · {percent}%"$json$::jsonb),
  ('pt-BR', 'update.progress.unknown', $json$"{received} MB baixados"$json$::jsonb),
  ('pt-BR', 'update.keepOpen', $json$"Deixe o JayV aberto até ele reiniciar: ele está trocando os próprios arquivos."$json$::jsonb),
  ('pt-BR', 'update.restarting.note', $json$"Reiniciando… seus pedidos continuam de onde pararam."$json$::jsonb),
  ('pt-BR', 'update.notes', $json$"O que muda"$json$::jsonb),
  ('pt-BR', 'update.retry', $json$"Tentar de novo"$json$::jsonb),
  ('en', 'orgChat.open', $json$"Open chat"$json$::jsonb),
  ('en', 'chatRepos.title', $json$"Repositories in this chat"$json$::jsonb),
  ('en', 'chatRepos.count', $json${"one": "{count} in the folder", "other": "{count} in the folder"}$json$::jsonb),
  ('en', 'chatRepos.dirty', $json${"one": "{count} with changes", "other": "{count} with changes"}$json$::jsonb),
  ('en', 'chatRepos.refresh', $json$"Check the repositories again"$json$::jsonb),
  ('en', 'chatRepos.loading', $json$"Reading the repositories…"$json$::jsonb),
  ('en', 'chatRepos.failed', $json$"Could not read the repositories of this folder."$json$::jsonb),
  ('en', 'chatRepos.empty', $json$"No repository inside this folder yet."$json$::jsonb),
  ('en', 'chatRepos.outside', $json$"not in this folder"$json$::jsonb),
  ('en', 'chatRepos.detached', $json$"no branch (detached)"$json$::jsonb),
  ('en', 'chatRepos.unreadable', $json$"git did not answer"$json$::jsonb),
  ('en', 'chatRepos.clean', $json$"clean"$json$::jsonb),
  ('en', 'chatRepos.changed', $json${"one": "{count} change", "other": "{count} changes"}$json$::jsonb),
  ('en', 'chatRepos.policy.repository', $json$"own policy"$json$::jsonb),
  ('en', 'chatRepos.policy.organization', $json$"organization policy"$json$::jsonb),
  ('en', 'chatRepos.policy.none', $json$"no policy"$json$::jsonb),
  ('en', 'chatRepos.unregistered', $json$"not in the organization"$json$::jsonb),
  ('en', 'chatRepos.policy.hint', $json$"The chat applies the strictest rules of the organization and of all its repositories together."$json$::jsonb),
  ('en', 'app.updates.every', $json$"Check every"$json$::jsonb),
  ('en', 'app.updates.everyHint', $json$"JayV looks for a new version when it opens and again at this interval. When one is available, a notice appears at the top of every screen."$json$::jsonb),
  ('en', 'app.updates.minutes', $json${"one": "{count} minute", "other": "{count} minutes"}$json$::jsonb),
  ('en', 'app.updates.hours', $json${"one": "{count} hour", "other": "{count} hours"}$json$::jsonb),
  ('en', 'app.updates.checkedAt', $json$"Last checked {at}."$json$::jsonb),
  ('en', 'app.updates.never', $json$"Not checked yet since JayV opened."$json$::jsonb),
  ('en', 'whatsNew.item.chatRepositories.title', $json$"Repositories inside the organization chat"$json$::jsonb),
  ('en', 'whatsNew.item.chatRepositories.detail', $json$"The organization chat now shows, at the top of the conversation, every repository in the organization folder: its branch, how far it is ahead of or behind the remote, how many files changed and where its LLM policy comes from. It reads them again when a request finishes. The button on the organization page and on the Projects page is now called Open chat."$json$::jsonb),
  ('en', 'whatsNew.item.updateInterval.title', $json$"Choose how often to look for updates"$json$::jsonb),
  ('en', 'whatsNew.item.updateInterval.detail', $json$"In Settings › App you can choose to look for a new version every 15 minutes, 30 minutes, 1 hour or 4 hours, and see when the last check happened. A new version shows in the notice at the top of every screen and in the status bar."$json$::jsonb),
  ('en', 'whatsNew.item.missingTranslations.title', $json$"Texts that were still in English"$json$::jsonb),
  ('en', 'whatsNew.item.missingTranslations.detail', $json$"The update window, the Close button and some sign-in and connection messages appeared in English in every language. They are now translated."$json$::jsonb),
  ('en', 'common.close', $json$"Close"$json$::jsonb),
  ('en', 'update.title', $json$"Updating to JayV {version}"$json$::jsonb),
  ('en', 'update.checking', $json$"Looking for updates"$json$::jsonb),
  ('en', 'update.fromTo', $json$"From version {current} to {next}. JayV restarts on its own when it is done."$json$::jsonb),
  ('en', 'update.description', $json$"JayV checks the release repository for a newer version."$json$::jsonb),
  ('en', 'update.step.checking', $json$"Check for a new version"$json$::jsonb),
  ('en', 'update.step.downloading', $json$"Download the update"$json$::jsonb),
  ('en', 'update.step.installing', $json$"Install"$json$::jsonb),
  ('en', 'update.step.restarting', $json$"Restart JayV"$json$::jsonb),
  ('en', 'update.progress', $json$"{received} of {total} MB · {percent}%"$json$::jsonb),
  ('en', 'update.progress.unknown', $json$"{received} MB downloaded"$json$::jsonb),
  ('en', 'update.keepOpen', $json$"Keep JayV open until it restarts: it is replacing its own files."$json$::jsonb),
  ('en', 'update.restarting.note', $json$"Restarting… your requests continue where they left off."$json$::jsonb),
  ('en', 'update.notes', $json$"What changes"$json$::jsonb),
  ('en', 'update.retry', $json$"Try again"$json$::jsonb),
  ('es', 'orgChat.open', $json$"Abrir chat"$json$::jsonb),
  ('es', 'chatRepos.title', $json$"Repositorios en este chat"$json$::jsonb),
  ('es', 'chatRepos.count', $json${"one": "{count} en la carpeta", "other": "{count} en la carpeta"}$json$::jsonb),
  ('es', 'chatRepos.dirty', $json${"one": "{count} con cambios", "other": "{count} con cambios"}$json$::jsonb),
  ('es', 'chatRepos.refresh', $json$"Revisar los repositorios de nuevo"$json$::jsonb),
  ('es', 'chatRepos.loading', $json$"Leyendo los repositorios…"$json$::jsonb),
  ('es', 'chatRepos.failed', $json$"No se pudieron leer los repositorios de esta carpeta."$json$::jsonb),
  ('es', 'chatRepos.empty', $json$"Todavía no hay ningún repositorio dentro de esta carpeta."$json$::jsonb),
  ('es', 'chatRepos.outside', $json$"fuera de esta carpeta"$json$::jsonb),
  ('es', 'chatRepos.detached', $json$"sin rama (detached)"$json$::jsonb),
  ('es', 'chatRepos.unreadable', $json$"git no respondió"$json$::jsonb),
  ('es', 'chatRepos.clean', $json$"limpio"$json$::jsonb),
  ('es', 'chatRepos.changed', $json${"one": "{count} cambio", "other": "{count} cambios"}$json$::jsonb),
  ('es', 'chatRepos.policy.repository', $json$"política propia"$json$::jsonb),
  ('es', 'chatRepos.policy.organization', $json$"política de la organización"$json$::jsonb),
  ('es', 'chatRepos.policy.none', $json$"sin política"$json$::jsonb),
  ('es', 'chatRepos.unregistered', $json$"fuera de la organización"$json$::jsonb),
  ('es', 'chatRepos.policy.hint', $json$"El chat aplica juntas las reglas más estrictas de la organización y de todos sus repositorios."$json$::jsonb),
  ('es', 'app.updates.every', $json$"Buscar cada"$json$::jsonb),
  ('es', 'app.updates.everyHint', $json$"JayV busca una versión nueva al abrirse y de nuevo con este intervalo. Cuando hay una, aparece un aviso arriba en todas las pantallas."$json$::jsonb),
  ('es', 'app.updates.minutes', $json${"one": "{count} minuto", "other": "{count} minutos"}$json$::jsonb),
  ('es', 'app.updates.hours', $json${"one": "{count} hora", "other": "{count} horas"}$json$::jsonb),
  ('es', 'app.updates.checkedAt', $json$"Última comprobación: {at}."$json$::jsonb),
  ('es', 'app.updates.never', $json$"Aún no se ha comprobado desde que se abrió JayV."$json$::jsonb),
  ('es', 'whatsNew.item.chatRepositories.title', $json$"Repositorios dentro del chat de la organización"$json$::jsonb),
  ('es', 'whatsNew.item.chatRepositories.detail', $json$"El chat de la organización ahora muestra, arriba de la conversación, cada repositorio de la carpeta de la organización: su rama, cuánto va por delante o por detrás del remoto, cuántos archivos cambiaron y de dónde viene su política de LLM. Los vuelve a leer cuando termina una solicitud. El botón de la página de la organización y de la página Proyectos ahora se llama Abrir chat."$json$::jsonb),
  ('es', 'whatsNew.item.updateInterval.title', $json$"Elige cada cuánto buscar actualizaciones"$json$::jsonb),
  ('es', 'whatsNew.item.updateInterval.detail', $json$"En Configuración › App puedes elegir buscar una versión nueva cada 15 minutos, 30 minutos, 1 hora o 4 horas, y ver cuándo fue la última comprobación. La versión nueva aparece en el aviso de arriba de todas las pantallas y en la barra de estado."$json$::jsonb),
  ('es', 'whatsNew.item.missingTranslations.title', $json$"Textos que seguían en inglés"$json$::jsonb),
  ('es', 'whatsNew.item.missingTranslations.detail', $json$"La ventana de actualización, el botón Cerrar y algunos mensajes de inicio de sesión y de conexión aparecían en inglés en todos los idiomas. Ahora están traducidos."$json$::jsonb),
  ('es', 'common.close', $json$"Cerrar"$json$::jsonb),
  ('es', 'update.title', $json$"Actualizando a JayV {version}"$json$::jsonb),
  ('es', 'update.checking', $json$"Buscando actualizaciones"$json$::jsonb),
  ('es', 'update.fromTo', $json$"De la versión {current} a la {next}. JayV se reinicia solo cuando termina."$json$::jsonb),
  ('es', 'update.description', $json$"JayV consulta el repositorio de versiones en busca de una más nueva."$json$::jsonb),
  ('es', 'update.step.checking', $json$"Buscar una versión nueva"$json$::jsonb),
  ('es', 'update.step.downloading', $json$"Descargar la actualización"$json$::jsonb),
  ('es', 'update.step.installing', $json$"Instalar"$json$::jsonb),
  ('es', 'update.step.restarting', $json$"Reiniciar JayV"$json$::jsonb),
  ('es', 'update.progress', $json$"{received} de {total} MB · {percent}%"$json$::jsonb),
  ('es', 'update.progress.unknown', $json$"{received} MB descargados"$json$::jsonb),
  ('es', 'update.keepOpen', $json$"Deja JayV abierto hasta que se reinicie: está reemplazando sus propios archivos."$json$::jsonb),
  ('es', 'update.restarting.note', $json$"Reiniciando… tus solicitudes continúan donde se quedaron."$json$::jsonb),
  ('es', 'update.notes', $json$"Qué cambia"$json$::jsonb),
  ('es', 'update.retry', $json$"Intentar de nuevo"$json$::jsonb),
  ('es', 'auth.title', $json$"Inicia sesión en JayV"$json$::jsonb),
  ('es', 'auth.subtitle', $json$"Tus proyectos, chats y agentes te acompañan en cualquier equipo."$json$::jsonb),
  ('es', 'auth.email', $json$"Correo electrónico"$json$::jsonb),
  ('es', 'auth.password', $json$"Contraseña"$json$::jsonb),
  ('es', 'auth.signIn', $json$"Iniciar sesión"$json$::jsonb),
  ('es', 'auth.signUp', $json$"Crear cuenta"$json$::jsonb),
  ('es', 'auth.toSignUp', $json$"¿Aún no tienes cuenta? Crea una"$json$::jsonb),
  ('es', 'auth.toSignIn', $json$"¿Ya tienes cuenta? Inicia sesión"$json$::jsonb),
  ('es', 'auth.checkEmail', $json$"Confirma la cuenta con el correo que te enviamos y luego inicia sesión."$json$::jsonb),
  ('es', 'auth.waitingBrowser', $json$"Termina de iniciar sesión en el navegador…"$json$::jsonb),
  ('es', 'auth.signOut', $json$"Cerrar sesión"$json$::jsonb),
  ('es', 'auth.loading', $json$"Abriendo tu sesión…"$json$::jsonb),
  ('es', 'connection.offline', $json$"Sin conexión — los cambios esperan para sincronizarse"$json$::jsonb),
  ('es', 'connection.expired', $json$"Sesión vencida — renovando…"$json$::jsonb),
  ('es', 'connection.pending', $json${"one": "{count} cambio sin sincronizar", "other": "{count} cambios sin sincronizar"}$json$::jsonb),
  ('es', 'connection.failed', $json${"one": "{count} cambio rechazado por el servidor", "other": "{count} cambios rechazados por el servidor"}$json$::jsonb),
  ('zh-CN', 'orgChat.open', $json$"打开聊天"$json$::jsonb),
  ('zh-CN', 'chatRepos.title', $json$"此聊天中的仓库"$json$::jsonb),
  ('zh-CN', 'chatRepos.count', $json${"other": "文件夹中有 {count} 个"}$json$::jsonb),
  ('zh-CN', 'chatRepos.dirty', $json${"other": "{count} 个有改动"}$json$::jsonb),
  ('zh-CN', 'chatRepos.refresh', $json$"重新检查仓库"$json$::jsonb),
  ('zh-CN', 'chatRepos.loading', $json$"正在读取仓库…"$json$::jsonb),
  ('zh-CN', 'chatRepos.failed', $json$"无法读取此文件夹中的仓库。"$json$::jsonb),
  ('zh-CN', 'chatRepos.empty', $json$"此文件夹中还没有仓库。"$json$::jsonb),
  ('zh-CN', 'chatRepos.outside', $json$"不在此文件夹中"$json$::jsonb),
  ('zh-CN', 'chatRepos.detached', $json$"无分支（detached）"$json$::jsonb),
  ('zh-CN', 'chatRepos.unreadable', $json$"git 没有响应"$json$::jsonb),
  ('zh-CN', 'chatRepos.clean', $json$"无改动"$json$::jsonb),
  ('zh-CN', 'chatRepos.changed', $json${"other": "{count} 处改动"}$json$::jsonb),
  ('zh-CN', 'chatRepos.policy.repository', $json$"自有策略"$json$::jsonb),
  ('zh-CN', 'chatRepos.policy.organization', $json$"组织策略"$json$::jsonb),
  ('zh-CN', 'chatRepos.policy.none', $json$"无策略"$json$::jsonb),
  ('zh-CN', 'chatRepos.unregistered', $json$"不属于组织"$json$::jsonb),
  ('zh-CN', 'chatRepos.policy.hint', $json$"此聊天会合并应用组织及其所有仓库中最严格的规则。"$json$::jsonb),
  ('zh-CN', 'app.updates.every', $json$"检查间隔"$json$::jsonb),
  ('zh-CN', 'app.updates.everyHint', $json$"JayV 在打开时以及之后按此间隔检查新版本。有新版本时，每个页面顶部都会出现提示。"$json$::jsonb),
  ('zh-CN', 'app.updates.minutes', $json${"other": "{count} 分钟"}$json$::jsonb),
  ('zh-CN', 'app.updates.hours', $json${"other": "{count} 小时"}$json$::jsonb),
  ('zh-CN', 'app.updates.checkedAt', $json$"上次检查：{at}。"$json$::jsonb),
  ('zh-CN', 'app.updates.never', $json$"自 JayV 打开以来尚未检查。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatRepositories.title', $json$"组织聊天中显示仓库"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.chatRepositories.detail', $json$"组织聊天现在会在对话顶部显示组织文件夹中的每个仓库：所在分支、领先或落后远程多少、改动了多少文件，以及其 LLM 策略来自哪里。每次请求完成后都会重新读取。组织页面和项目页面上的按钮现在叫作“打开聊天”。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateInterval.title', $json$"自选检查更新的频率"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updateInterval.detail', $json$"在 设置 › 应用 中，可以选择每 15 分钟、30 分钟、1 小时或 4 小时检查一次新版本，并查看上次检查的时间。新版本会显示在每个页面顶部的提示和状态栏中。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.missingTranslations.title', $json$"仍显示为英文的文字"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.missingTranslations.detail', $json$"更新窗口、“关闭”按钮以及部分登录和连接消息在所有语言中都显示为英文。现在已翻译。"$json$::jsonb),
  ('zh-CN', 'common.close', $json$"关闭"$json$::jsonb),
  ('zh-CN', 'update.title', $json$"正在更新到 JayV {version}"$json$::jsonb),
  ('zh-CN', 'update.checking', $json$"正在检查更新"$json$::jsonb),
  ('zh-CN', 'update.fromTo', $json$"从 {current} 版本更新到 {next}。完成后 JayV 会自动重启。"$json$::jsonb),
  ('zh-CN', 'update.description', $json$"JayV 会在发布仓库中检查是否有更新的版本。"$json$::jsonb),
  ('zh-CN', 'update.step.checking', $json$"检查新版本"$json$::jsonb),
  ('zh-CN', 'update.step.downloading', $json$"下载更新"$json$::jsonb),
  ('zh-CN', 'update.step.installing', $json$"安装"$json$::jsonb),
  ('zh-CN', 'update.step.restarting', $json$"重启 JayV"$json$::jsonb),
  ('zh-CN', 'update.progress', $json$"{received} / {total} MB · {percent}%"$json$::jsonb),
  ('zh-CN', 'update.progress.unknown', $json$"已下载 {received} MB"$json$::jsonb),
  ('zh-CN', 'update.keepOpen', $json$"请保持 JayV 打开直到它重启：它正在替换自身的文件。"$json$::jsonb),
  ('zh-CN', 'update.restarting.note', $json$"正在重启…你的请求会从中断处继续。"$json$::jsonb),
  ('zh-CN', 'update.notes', $json$"更新内容"$json$::jsonb),
  ('zh-CN', 'update.retry', $json$"重试"$json$::jsonb),
  ('zh-CN', 'auth.title', $json$"登录 JayV"$json$::jsonb),
  ('zh-CN', 'auth.subtitle', $json$"你的项目、聊天和智能体在任何设备上都与你同在。"$json$::jsonb),
  ('zh-CN', 'auth.email', $json$"电子邮件"$json$::jsonb),
  ('zh-CN', 'auth.password', $json$"密码"$json$::jsonb),
  ('zh-CN', 'auth.signIn', $json$"登录"$json$::jsonb),
  ('zh-CN', 'auth.signUp', $json$"创建账户"$json$::jsonb),
  ('zh-CN', 'auth.toSignUp', $json$"还没有账户？创建一个"$json$::jsonb),
  ('zh-CN', 'auth.toSignIn', $json$"已有账户？登录"$json$::jsonb),
  ('zh-CN', 'auth.checkEmail', $json$"请通过我们发送的邮件确认账户，然后登录。"$json$::jsonb),
  ('zh-CN', 'auth.waitingBrowser', $json$"请在浏览器中完成登录…"$json$::jsonb),
  ('zh-CN', 'auth.signOut', $json$"退出登录"$json$::jsonb),
  ('zh-CN', 'auth.loading', $json$"正在打开你的会话…"$json$::jsonb),
  ('zh-CN', 'connection.offline', $json$"离线 — 更改将等待同步"$json$::jsonb),
  ('zh-CN', 'connection.expired', $json$"会话已过期 — 正在续期…"$json$::jsonb),
  ('zh-CN', 'connection.pending', $json${"other": "{count} 项更改未同步"}$json$::jsonb),
  ('zh-CN', 'connection.failed', $json${"other": "{count} 项更改被服务器拒绝"}$json$::jsonb),
  ('hi', 'orgChat.open', $json$"चैट खोलें"$json$::jsonb),
  ('hi', 'chatRepos.title', $json$"इस चैट में रिपॉज़िटरी"$json$::jsonb),
  ('hi', 'chatRepos.count', $json${"one": "फ़ोल्डर में {count}", "other": "फ़ोल्डर में {count}"}$json$::jsonb),
  ('hi', 'chatRepos.dirty', $json${"one": "{count} में बदलाव", "other": "{count} में बदलाव"}$json$::jsonb),
  ('hi', 'chatRepos.refresh', $json$"रिपॉज़िटरी फिर से जाँचें"$json$::jsonb),
  ('hi', 'chatRepos.loading', $json$"रिपॉज़िटरी पढ़ी जा रही हैं…"$json$::jsonb),
  ('hi', 'chatRepos.failed', $json$"इस फ़ोल्डर की रिपॉज़िटरी पढ़ी नहीं जा सकीं।"$json$::jsonb),
  ('hi', 'chatRepos.empty', $json$"इस फ़ोल्डर में अभी कोई रिपॉज़िटरी नहीं है।"$json$::jsonb),
  ('hi', 'chatRepos.outside', $json$"इस फ़ोल्डर में नहीं"$json$::jsonb),
  ('hi', 'chatRepos.detached', $json$"कोई ब्रांच नहीं (detached)"$json$::jsonb),
  ('hi', 'chatRepos.unreadable', $json$"git ने जवाब नहीं दिया"$json$::jsonb),
  ('hi', 'chatRepos.clean', $json$"साफ़"$json$::jsonb),
  ('hi', 'chatRepos.changed', $json${"one": "{count} बदलाव", "other": "{count} बदलाव"}$json$::jsonb),
  ('hi', 'chatRepos.policy.repository', $json$"अपनी नीति"$json$::jsonb),
  ('hi', 'chatRepos.policy.organization', $json$"संगठन की नीति"$json$::jsonb),
  ('hi', 'chatRepos.policy.none', $json$"कोई नीति नहीं"$json$::jsonb),
  ('hi', 'chatRepos.unregistered', $json$"संगठन में नहीं"$json$::jsonb),
  ('hi', 'chatRepos.policy.hint', $json$"चैट संगठन और उसकी सभी रिपॉज़िटरी के सबसे सख़्त नियम एक साथ लागू करती है।"$json$::jsonb),
  ('hi', 'app.updates.every', $json$"हर इतने समय में जाँचें"$json$::jsonb),
  ('hi', 'app.updates.everyHint', $json$"JayV खुलते समय और फिर इस अंतराल पर नया वर्ज़न खोजता है। जब कोई उपलब्ध हो, तो हर स्क्रीन के ऊपर सूचना दिखती है।"$json$::jsonb),
  ('hi', 'app.updates.minutes', $json${"one": "{count} मिनट", "other": "{count} मिनट"}$json$::jsonb),
  ('hi', 'app.updates.hours', $json${"one": "{count} घंटा", "other": "{count} घंटे"}$json$::jsonb),
  ('hi', 'app.updates.checkedAt', $json$"आख़िरी जाँच: {at}।"$json$::jsonb),
  ('hi', 'app.updates.never', $json$"JayV खुलने के बाद से अभी जाँच नहीं हुई।"$json$::jsonb),
  ('hi', 'whatsNew.item.chatRepositories.title', $json$"संगठन चैट के अंदर रिपॉज़िटरी"$json$::jsonb),
  ('hi', 'whatsNew.item.chatRepositories.detail', $json$"संगठन चैट अब बातचीत के ऊपर संगठन फ़ोल्डर की हर रिपॉज़िटरी दिखाती है: उसकी ब्रांच, वह रिमोट से कितना आगे या पीछे है, कितनी फ़ाइलें बदलीं और उसकी LLM नीति कहाँ से आती है। हर अनुरोध पूरा होने पर यह इन्हें फिर से पढ़ती है। संगठन पेज और प्रोजेक्ट पेज पर बटन का नाम अब चैट खोलें है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updateInterval.title', $json$"चुनें कि अपडेट कितनी बार खोजे जाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.updateInterval.detail', $json$"सेटिंग्स › ऐप में आप हर 15 मिनट, 30 मिनट, 1 घंटे या 4 घंटे में नया वर्ज़न खोजना चुन सकते हैं और देख सकते हैं कि आख़िरी जाँच कब हुई। नया वर्ज़न हर स्क्रीन के ऊपर की सूचना और स्टेटस बार में दिखता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.missingTranslations.title', $json$"जो टेक्स्ट अब तक अंग्रेज़ी में थे"$json$::jsonb),
  ('hi', 'whatsNew.item.missingTranslations.detail', $json$"अपडेट विंडो, बंद करें बटन और साइन-इन व कनेक्शन के कुछ संदेश हर भाषा में अंग्रेज़ी में दिखते थे। अब उनका अनुवाद हो गया है।"$json$::jsonb),
  ('hi', 'common.close', $json$"बंद करें"$json$::jsonb),
  ('hi', 'update.title', $json$"JayV {version} में अपडेट हो रहा है"$json$::jsonb),
  ('hi', 'update.checking', $json$"अपडेट खोजे जा रहे हैं"$json$::jsonb),
  ('hi', 'update.fromTo', $json$"वर्ज़न {current} से {next}। पूरा होने पर JayV अपने आप रीस्टार्ट होगा।"$json$::jsonb),
  ('hi', 'update.description', $json$"JayV रिलीज़ रिपॉज़िटरी में नया वर्ज़न खोजता है।"$json$::jsonb),
  ('hi', 'update.step.checking', $json$"नया वर्ज़न खोजें"$json$::jsonb),
  ('hi', 'update.step.downloading', $json$"अपडेट डाउनलोड करें"$json$::jsonb),
  ('hi', 'update.step.installing', $json$"इंस्टॉल करें"$json$::jsonb),
  ('hi', 'update.step.restarting', $json$"JayV रीस्टार्ट करें"$json$::jsonb),
  ('hi', 'update.progress', $json$"{total} में से {received} MB · {percent}%"$json$::jsonb),
  ('hi', 'update.progress.unknown', $json$"{received} MB डाउनलोड हुआ"$json$::jsonb),
  ('hi', 'update.keepOpen', $json$"JayV को रीस्टार्ट होने तक खुला रखें: यह अपनी फ़ाइलें बदल रहा है।"$json$::jsonb),
  ('hi', 'update.restarting.note', $json$"रीस्टार्ट हो रहा है… आपके अनुरोध वहीं से जारी रहेंगे जहाँ रुके थे।"$json$::jsonb),
  ('hi', 'update.notes', $json$"क्या बदलता है"$json$::jsonb),
  ('hi', 'update.retry', $json$"फिर से कोशिश करें"$json$::jsonb),
  ('hi', 'auth.title', $json$"JayV में साइन इन करें"$json$::jsonb),
  ('hi', 'auth.subtitle', $json$"आपके प्रोजेक्ट, चैट और एजेंट हर मशीन पर आपके साथ रहते हैं।"$json$::jsonb),
  ('hi', 'auth.email', $json$"ईमेल"$json$::jsonb),
  ('hi', 'auth.password', $json$"पासवर्ड"$json$::jsonb),
  ('hi', 'auth.signIn', $json$"साइन इन करें"$json$::jsonb),
  ('hi', 'auth.signUp', $json$"खाता बनाएँ"$json$::jsonb),
  ('hi', 'auth.toSignUp', $json$"अभी खाता नहीं है? एक बनाएँ"$json$::jsonb),
  ('hi', 'auth.toSignIn', $json$"पहले से खाता है? साइन इन करें"$json$::jsonb),
  ('hi', 'auth.checkEmail', $json$"हमारे भेजे ईमेल से खाते की पुष्टि करें, फिर साइन इन करें।"$json$::jsonb),
  ('hi', 'auth.waitingBrowser', $json$"ब्राउज़र में साइन इन पूरा करें…"$json$::jsonb),
  ('hi', 'auth.signOut', $json$"साइन आउट करें"$json$::jsonb),
  ('hi', 'auth.loading', $json$"आपका सत्र खुल रहा है…"$json$::jsonb),
  ('hi', 'connection.offline', $json$"ऑफ़लाइन — बदलाव सिंक होने का इंतज़ार कर रहे हैं"$json$::jsonb),
  ('hi', 'connection.expired', $json$"सत्र समाप्त — नवीनीकरण हो रहा है…"$json$::jsonb),
  ('hi', 'connection.pending', $json${"one": "{count} बदलाव सिंक नहीं हुआ", "other": "{count} बदलाव सिंक नहीं हुए"}$json$::jsonb),
  ('hi', 'connection.failed', $json${"one": "{count} बदलाव सर्वर ने अस्वीकार किया", "other": "{count} बदलाव सर्वर ने अस्वीकार किए"}$json$::jsonb),
  ('ar', 'orgChat.open', $json$"فتح الدردشة"$json$::jsonb),
  ('ar', 'chatRepos.title', $json$"المستودعات في هذه الدردشة"$json$::jsonb),
  ('ar', 'chatRepos.count', $json${"zero": "لا شيء في المجلد", "one": "واحد في المجلد", "two": "اثنان في المجلد", "few": "{count} في المجلد", "many": "{count} في المجلد", "other": "{count} في المجلد"}$json$::jsonb),
  ('ar', 'chatRepos.dirty', $json${"zero": "لا تغييرات", "one": "واحد به تغييرات", "two": "اثنان بهما تغييرات", "few": "{count} بها تغييرات", "many": "{count} بها تغييرات", "other": "{count} بها تغييرات"}$json$::jsonb),
  ('ar', 'chatRepos.refresh', $json$"تحقق من المستودعات مرة أخرى"$json$::jsonb),
  ('ar', 'chatRepos.loading', $json$"جارٍ قراءة المستودعات…"$json$::jsonb),
  ('ar', 'chatRepos.failed', $json$"تعذّرت قراءة مستودعات هذا المجلد."$json$::jsonb),
  ('ar', 'chatRepos.empty', $json$"لا يوجد أي مستودع داخل هذا المجلد بعد."$json$::jsonb),
  ('ar', 'chatRepos.outside', $json$"ليس في هذا المجلد"$json$::jsonb),
  ('ar', 'chatRepos.detached', $json$"بلا فرع (detached)"$json$::jsonb),
  ('ar', 'chatRepos.unreadable', $json$"لم يستجب git"$json$::jsonb),
  ('ar', 'chatRepos.clean', $json$"نظيف"$json$::jsonb),
  ('ar', 'chatRepos.changed', $json${"zero": "لا تغييرات", "one": "تغيير واحد", "two": "تغييران", "few": "{count} تغييرات", "many": "{count} تغييرًا", "other": "{count} تغيير"}$json$::jsonb),
  ('ar', 'chatRepos.policy.repository', $json$"سياسة خاصة"$json$::jsonb),
  ('ar', 'chatRepos.policy.organization', $json$"سياسة المؤسسة"$json$::jsonb),
  ('ar', 'chatRepos.policy.none', $json$"بلا سياسة"$json$::jsonb),
  ('ar', 'chatRepos.unregistered', $json$"ليس ضمن المؤسسة"$json$::jsonb),
  ('ar', 'chatRepos.policy.hint', $json$"تطبّق الدردشة أشد قواعد المؤسسة وجميع مستودعاتها معًا."$json$::jsonb),
  ('ar', 'app.updates.every', $json$"التحقق كل"$json$::jsonb),
  ('ar', 'app.updates.everyHint', $json$"يبحث JayV عن إصدار جديد عند فتحه ثم كل هذه المدة. عند توفر إصدار، يظهر تنبيه أعلى كل شاشة."$json$::jsonb),
  ('ar', 'app.updates.minutes', $json${"zero": "{count} دقيقة", "one": "دقيقة واحدة", "two": "دقيقتان", "few": "{count} دقائق", "many": "{count} دقيقة", "other": "{count} دقيقة"}$json$::jsonb),
  ('ar', 'app.updates.hours', $json${"zero": "{count} ساعة", "one": "ساعة واحدة", "two": "ساعتان", "few": "{count} ساعات", "many": "{count} ساعة", "other": "{count} ساعة"}$json$::jsonb),
  ('ar', 'app.updates.checkedAt', $json$"آخر تحقق: {at}."$json$::jsonb),
  ('ar', 'app.updates.never', $json$"لم يتم التحقق بعد منذ فتح JayV."$json$::jsonb),
  ('ar', 'whatsNew.item.chatRepositories.title', $json$"المستودعات داخل دردشة المؤسسة"$json$::jsonb),
  ('ar', 'whatsNew.item.chatRepositories.detail', $json$"تعرض دردشة المؤسسة الآن، أعلى المحادثة، كل مستودع في مجلد المؤسسة: فرعه، وكم يتقدم على المستودع البعيد أو يتأخر عنه، وكم ملفًا تغيّر، ومن أين تأتي سياسة LLM الخاصة به. وتعيد قراءتها عند انتهاء كل طلب. أصبح اسم الزر في صفحة المؤسسة وصفحة المشاريع فتح الدردشة."$json$::jsonb),
  ('ar', 'whatsNew.item.updateInterval.title', $json$"اختر عدد مرات البحث عن التحديثات"$json$::jsonb),
  ('ar', 'whatsNew.item.updateInterval.detail', $json$"في الإعدادات › التطبيق يمكنك اختيار البحث عن إصدار جديد كل 15 دقيقة أو 30 دقيقة أو ساعة أو 4 ساعات، ومعرفة وقت آخر تحقق. يظهر الإصدار الجديد في التنبيه أعلى كل شاشة وفي شريط الحالة."$json$::jsonb),
  ('ar', 'whatsNew.item.missingTranslations.title', $json$"نصوص كانت لا تزال بالإنجليزية"$json$::jsonb),
  ('ar', 'whatsNew.item.missingTranslations.detail', $json$"كانت نافذة التحديث وزر الإغلاق وبعض رسائل تسجيل الدخول والاتصال تظهر بالإنجليزية في كل اللغات. أصبحت مترجمة الآن."$json$::jsonb),
  ('ar', 'common.close', $json$"إغلاق"$json$::jsonb),
  ('ar', 'update.title', $json$"جارٍ التحديث إلى JayV {version}"$json$::jsonb),
  ('ar', 'update.checking', $json$"جارٍ البحث عن تحديثات"$json$::jsonb),
  ('ar', 'update.fromTo', $json$"من الإصدار {current} إلى {next}. يعيد JayV التشغيل تلقائيًا عند الانتهاء."$json$::jsonb),
  ('ar', 'update.description', $json$"يتحقق JayV من مستودع الإصدارات بحثًا عن إصدار أحدث."$json$::jsonb),
  ('ar', 'update.step.checking', $json$"البحث عن إصدار جديد"$json$::jsonb),
  ('ar', 'update.step.downloading', $json$"تنزيل التحديث"$json$::jsonb),
  ('ar', 'update.step.installing', $json$"التثبيت"$json$::jsonb),
  ('ar', 'update.step.restarting', $json$"إعادة تشغيل JayV"$json$::jsonb),
  ('ar', 'update.progress', $json$"{received} من {total} ميغابايت · {percent}%"$json$::jsonb),
  ('ar', 'update.progress.unknown', $json$"تم تنزيل {received} ميغابايت"$json$::jsonb),
  ('ar', 'update.keepOpen', $json$"أبقِ JayV مفتوحًا حتى يعيد التشغيل: فهو يستبدل ملفاته."$json$::jsonb),
  ('ar', 'update.restarting.note', $json$"جارٍ إعادة التشغيل… تستمر طلباتك من حيث توقفت."$json$::jsonb),
  ('ar', 'update.notes', $json$"ما الذي يتغير"$json$::jsonb),
  ('ar', 'update.retry', $json$"حاول مرة أخرى"$json$::jsonb),
  ('ar', 'auth.title', $json$"تسجيل الدخول إلى JayV"$json$::jsonb),
  ('ar', 'auth.subtitle', $json$"مشاريعك ودردشاتك ووكلاؤك يرافقونك على أي جهاز."$json$::jsonb),
  ('ar', 'auth.email', $json$"البريد الإلكتروني"$json$::jsonb),
  ('ar', 'auth.password', $json$"كلمة المرور"$json$::jsonb),
  ('ar', 'auth.signIn', $json$"تسجيل الدخول"$json$::jsonb),
  ('ar', 'auth.signUp', $json$"إنشاء حساب"$json$::jsonb),
  ('ar', 'auth.toSignUp', $json$"ليس لديك حساب بعد؟ أنشئ واحدًا"$json$::jsonb),
  ('ar', 'auth.toSignIn', $json$"لديك حساب بالفعل؟ سجّل الدخول"$json$::jsonb),
  ('ar', 'auth.checkEmail', $json$"أكّد الحساب عبر البريد الذي أرسلناه ثم سجّل الدخول."$json$::jsonb),
  ('ar', 'auth.waitingBrowser', $json$"أكمل تسجيل الدخول في المتصفح…"$json$::jsonb),
  ('ar', 'auth.signOut', $json$"تسجيل الخروج"$json$::jsonb),
  ('ar', 'auth.loading', $json$"جارٍ فتح جلستك…"$json$::jsonb),
  ('ar', 'connection.offline', $json$"غير متصل — التغييرات بانتظار المزامنة"$json$::jsonb),
  ('ar', 'connection.expired', $json$"انتهت الجلسة — جارٍ التجديد…"$json$::jsonb),
  ('ar', 'connection.pending', $json${"zero": "لا تغييرات غير مزامنة", "one": "تغيير واحد غير مزامن", "two": "تغييران غير مزامنين", "few": "{count} تغييرات غير مزامنة", "many": "{count} تغييرًا غير مزامن", "other": "{count} تغيير غير مزامن"}$json$::jsonb),
  ('ar', 'connection.failed', $json${"zero": "لم يرفض الخادم أي تغيير", "one": "رفض الخادم تغييرًا واحدًا", "two": "رفض الخادم تغييرين", "few": "رفض الخادم {count} تغييرات", "many": "رفض الخادم {count} تغييرًا", "other": "رفض الخادم {count} تغيير"}$json$::jsonb),
  ('fr', 'orgChat.open', $json$"Ouvrir le chat"$json$::jsonb),
  ('fr', 'chatRepos.title', $json$"Dépôts dans ce chat"$json$::jsonb),
  ('fr', 'chatRepos.count', $json${"one": "{count} dans le dossier", "other": "{count} dans le dossier"}$json$::jsonb),
  ('fr', 'chatRepos.dirty', $json${"one": "{count} avec des modifications", "other": "{count} avec des modifications"}$json$::jsonb),
  ('fr', 'chatRepos.refresh', $json$"Vérifier à nouveau les dépôts"$json$::jsonb),
  ('fr', 'chatRepos.loading', $json$"Lecture des dépôts…"$json$::jsonb),
  ('fr', 'chatRepos.failed', $json$"Impossible de lire les dépôts de ce dossier."$json$::jsonb),
  ('fr', 'chatRepos.empty', $json$"Aucun dépôt dans ce dossier pour l’instant."$json$::jsonb),
  ('fr', 'chatRepos.outside', $json$"hors de ce dossier"$json$::jsonb),
  ('fr', 'chatRepos.detached', $json$"sans branche (detached)"$json$::jsonb),
  ('fr', 'chatRepos.unreadable', $json$"git n’a pas répondu"$json$::jsonb),
  ('fr', 'chatRepos.clean', $json$"propre"$json$::jsonb),
  ('fr', 'chatRepos.changed', $json${"one": "{count} modification", "other": "{count} modifications"}$json$::jsonb),
  ('fr', 'chatRepos.policy.repository', $json$"politique propre"$json$::jsonb),
  ('fr', 'chatRepos.policy.organization', $json$"politique de l’organisation"$json$::jsonb),
  ('fr', 'chatRepos.policy.none', $json$"aucune politique"$json$::jsonb),
  ('fr', 'chatRepos.unregistered', $json$"hors de l’organisation"$json$::jsonb),
  ('fr', 'chatRepos.policy.hint', $json$"Le chat applique ensemble les règles les plus strictes de l’organisation et de tous ses dépôts."$json$::jsonb),
  ('fr', 'app.updates.every', $json$"Vérifier toutes les"$json$::jsonb),
  ('fr', 'app.updates.everyHint', $json$"JayV cherche une nouvelle version à l’ouverture puis à cet intervalle. Quand il y en a une, un avis s’affiche en haut de chaque écran."$json$::jsonb),
  ('fr', 'app.updates.minutes', $json${"one": "{count} minute", "other": "{count} minutes"}$json$::jsonb),
  ('fr', 'app.updates.hours', $json${"one": "{count} heure", "other": "{count} heures"}$json$::jsonb),
  ('fr', 'app.updates.checkedAt', $json$"Dernière vérification : {at}."$json$::jsonb),
  ('fr', 'app.updates.never', $json$"Pas encore vérifié depuis l’ouverture de JayV."$json$::jsonb),
  ('fr', 'whatsNew.item.chatRepositories.title', $json$"Les dépôts dans le chat de l’organisation"$json$::jsonb),
  ('fr', 'whatsNew.item.chatRepositories.detail', $json$"Le chat de l’organisation affiche désormais, en haut de la conversation, chaque dépôt du dossier de l’organisation : sa branche, son avance ou son retard sur le distant, le nombre de fichiers modifiés et l’origine de sa politique LLM. Il les relit à la fin de chaque demande. Le bouton de la page de l’organisation et de la page Projets s’appelle maintenant Ouvrir le chat."$json$::jsonb),
  ('fr', 'whatsNew.item.updateInterval.title', $json$"Choisissez la fréquence de recherche des mises à jour"$json$::jsonb),
  ('fr', 'whatsNew.item.updateInterval.detail', $json$"Dans Paramètres › Application, vous pouvez choisir de chercher une nouvelle version toutes les 15 minutes, 30 minutes, 1 heure ou 4 heures, et voir quand a eu lieu la dernière vérification. La nouvelle version s’affiche dans l’avis en haut de chaque écran et dans la barre d’état."$json$::jsonb),
  ('fr', 'whatsNew.item.missingTranslations.title', $json$"Des textes encore en anglais"$json$::jsonb),
  ('fr', 'whatsNew.item.missingTranslations.detail', $json$"La fenêtre de mise à jour, le bouton Fermer et certains messages de connexion apparaissaient en anglais dans toutes les langues. Ils sont maintenant traduits."$json$::jsonb),
  ('fr', 'common.close', $json$"Fermer"$json$::jsonb),
  ('fr', 'update.title', $json$"Mise à jour vers JayV {version}"$json$::jsonb),
  ('fr', 'update.checking', $json$"Recherche de mises à jour"$json$::jsonb),
  ('fr', 'update.fromTo', $json$"De la version {current} à la {next}. JayV redémarre tout seul une fois terminé."$json$::jsonb),
  ('fr', 'update.description', $json$"JayV consulte le dépôt des versions à la recherche d’une version plus récente."$json$::jsonb),
  ('fr', 'update.step.checking', $json$"Chercher une nouvelle version"$json$::jsonb),
  ('fr', 'update.step.downloading', $json$"Télécharger la mise à jour"$json$::jsonb),
  ('fr', 'update.step.installing', $json$"Installer"$json$::jsonb),
  ('fr', 'update.step.restarting', $json$"Redémarrer JayV"$json$::jsonb),
  ('fr', 'update.progress', $json$"{received} sur {total} Mo · {percent} %"$json$::jsonb),
  ('fr', 'update.progress.unknown', $json$"{received} Mo téléchargés"$json$::jsonb),
  ('fr', 'update.keepOpen', $json$"Laissez JayV ouvert jusqu’à son redémarrage : il remplace ses propres fichiers."$json$::jsonb),
  ('fr', 'update.restarting.note', $json$"Redémarrage… vos demandes reprennent là où elles s’étaient arrêtées."$json$::jsonb),
  ('fr', 'update.notes', $json$"Ce qui change"$json$::jsonb),
  ('fr', 'update.retry', $json$"Réessayer"$json$::jsonb),
  ('fr', 'auth.title', $json$"Se connecter à JayV"$json$::jsonb),
  ('fr', 'auth.subtitle', $json$"Vos projets, chats et agents vous suivent sur n’importe quelle machine."$json$::jsonb),
  ('fr', 'auth.email', $json$"E-mail"$json$::jsonb),
  ('fr', 'auth.password', $json$"Mot de passe"$json$::jsonb),
  ('fr', 'auth.signIn', $json$"Se connecter"$json$::jsonb),
  ('fr', 'auth.signUp', $json$"Créer un compte"$json$::jsonb),
  ('fr', 'auth.toSignUp', $json$"Pas encore de compte ? Créez-en un"$json$::jsonb),
  ('fr', 'auth.toSignIn', $json$"Vous avez déjà un compte ? Connectez-vous"$json$::jsonb),
  ('fr', 'auth.checkEmail', $json$"Confirmez le compte via l’e-mail envoyé, puis connectez-vous."$json$::jsonb),
  ('fr', 'auth.waitingBrowser', $json$"Terminez la connexion dans votre navigateur…"$json$::jsonb),
  ('fr', 'auth.signOut', $json$"Se déconnecter"$json$::jsonb),
  ('fr', 'auth.loading', $json$"Ouverture de votre session…"$json$::jsonb),
  ('fr', 'connection.offline', $json$"Hors ligne — les modifications attendent la synchronisation"$json$::jsonb),
  ('fr', 'connection.expired', $json$"Session expirée — renouvellement…"$json$::jsonb),
  ('fr', 'connection.pending', $json${"one": "{count} modification non synchronisée", "other": "{count} modifications non synchronisées"}$json$::jsonb),
  ('fr', 'connection.failed', $json${"one": "{count} modification refusée par le serveur", "other": "{count} modifications refusées par le serveur"}$json$::jsonb),
  ('ru', 'orgChat.open', $json$"Открыть чат"$json$::jsonb),
  ('ru', 'chatRepos.title', $json$"Репозитории в этом чате"$json$::jsonb),
  ('ru', 'chatRepos.count', $json${"one": "{count} в папке", "few": "{count} в папке", "many": "{count} в папке", "other": "{count} в папке"}$json$::jsonb),
  ('ru', 'chatRepos.dirty', $json${"one": "{count} с изменениями", "few": "{count} с изменениями", "many": "{count} с изменениями", "other": "{count} с изменениями"}$json$::jsonb),
  ('ru', 'chatRepos.refresh', $json$"Проверить репозитории снова"$json$::jsonb),
  ('ru', 'chatRepos.loading', $json$"Читаем репозитории…"$json$::jsonb),
  ('ru', 'chatRepos.failed', $json$"Не удалось прочитать репозитории этой папки."$json$::jsonb),
  ('ru', 'chatRepos.empty', $json$"В этой папке пока нет репозиториев."$json$::jsonb),
  ('ru', 'chatRepos.outside', $json$"не в этой папке"$json$::jsonb),
  ('ru', 'chatRepos.detached', $json$"без ветки (detached)"$json$::jsonb),
  ('ru', 'chatRepos.unreadable', $json$"git не ответил"$json$::jsonb),
  ('ru', 'chatRepos.clean', $json$"чисто"$json$::jsonb),
  ('ru', 'chatRepos.changed', $json${"one": "{count} изменение", "few": "{count} изменения", "many": "{count} изменений", "other": "{count} изменения"}$json$::jsonb),
  ('ru', 'chatRepos.policy.repository', $json$"своя политика"$json$::jsonb),
  ('ru', 'chatRepos.policy.organization', $json$"политика организации"$json$::jsonb),
  ('ru', 'chatRepos.policy.none', $json$"без политики"$json$::jsonb),
  ('ru', 'chatRepos.unregistered', $json$"не в организации"$json$::jsonb),
  ('ru', 'chatRepos.policy.hint', $json$"Чат применяет самые строгие правила организации и всех её репозиториев вместе."$json$::jsonb),
  ('ru', 'app.updates.every', $json$"Проверять каждые"$json$::jsonb),
  ('ru', 'app.updates.everyHint', $json$"JayV ищет новую версию при запуске и затем с этим интервалом. Когда она есть, вверху каждого экрана появляется уведомление."$json$::jsonb),
  ('ru', 'app.updates.minutes', $json${"one": "{count} минуту", "few": "{count} минуты", "many": "{count} минут", "other": "{count} минуты"}$json$::jsonb),
  ('ru', 'app.updates.hours', $json${"one": "{count} час", "few": "{count} часа", "many": "{count} часов", "other": "{count} часа"}$json$::jsonb),
  ('ru', 'app.updates.checkedAt', $json$"Последняя проверка: {at}."$json$::jsonb),
  ('ru', 'app.updates.never', $json$"С момента запуска JayV проверки ещё не было."$json$::jsonb),
  ('ru', 'whatsNew.item.chatRepositories.title', $json$"Репозитории внутри чата организации"$json$::jsonb),
  ('ru', 'whatsNew.item.chatRepositories.detail', $json$"Чат организации теперь показывает вверху разговора каждый репозиторий из папки организации: ветку, насколько он опережает удалённый или отстаёт от него, сколько файлов изменено и откуда берётся его политика LLM. Он перечитывает их после каждого запроса. Кнопка на странице организации и на странице «Проекты» теперь называется «Открыть чат»."$json$::jsonb),
  ('ru', 'whatsNew.item.updateInterval.title', $json$"Выберите, как часто искать обновления"$json$::jsonb),
  ('ru', 'whatsNew.item.updateInterval.detail', $json$"В «Настройки › Приложение» можно выбрать поиск новой версии каждые 15 минут, 30 минут, 1 час или 4 часа и увидеть время последней проверки. Новая версия показывается в уведомлении вверху каждого экрана и в строке состояния."$json$::jsonb),
  ('ru', 'whatsNew.item.missingTranslations.title', $json$"Тексты, которые оставались на английском"$json$::jsonb),
  ('ru', 'whatsNew.item.missingTranslations.detail', $json$"Окно обновления, кнопка «Закрыть» и некоторые сообщения о входе и подключении показывались на английском во всех языках. Теперь они переведены."$json$::jsonb),
  ('ru', 'common.close', $json$"Закрыть"$json$::jsonb),
  ('ru', 'update.title', $json$"Обновление до JayV {version}"$json$::jsonb),
  ('ru', 'update.checking', $json$"Поиск обновлений"$json$::jsonb),
  ('ru', 'update.fromTo', $json$"С версии {current} на {next}. JayV перезапустится сам, когда закончит."$json$::jsonb),
  ('ru', 'update.description', $json$"JayV проверяет репозиторий релизов на наличие более новой версии."$json$::jsonb),
  ('ru', 'update.step.checking', $json$"Найти новую версию"$json$::jsonb),
  ('ru', 'update.step.downloading', $json$"Скачать обновление"$json$::jsonb),
  ('ru', 'update.step.installing', $json$"Установить"$json$::jsonb),
  ('ru', 'update.step.restarting', $json$"Перезапустить JayV"$json$::jsonb),
  ('ru', 'update.progress', $json$"{received} из {total} МБ · {percent}%"$json$::jsonb),
  ('ru', 'update.progress.unknown', $json$"Скачано {received} МБ"$json$::jsonb),
  ('ru', 'update.keepOpen', $json$"Не закрывайте JayV до перезапуска: он заменяет собственные файлы."$json$::jsonb),
  ('ru', 'update.restarting.note', $json$"Перезапуск… ваши запросы продолжатся с того же места."$json$::jsonb),
  ('ru', 'update.notes', $json$"Что меняется"$json$::jsonb),
  ('ru', 'update.retry', $json$"Попробовать снова"$json$::jsonb),
  ('ru', 'auth.title', $json$"Вход в JayV"$json$::jsonb),
  ('ru', 'auth.subtitle', $json$"Ваши проекты, чаты и агенты доступны на любом компьютере."$json$::jsonb),
  ('ru', 'auth.email', $json$"Эл. почта"$json$::jsonb),
  ('ru', 'auth.password', $json$"Пароль"$json$::jsonb),
  ('ru', 'auth.signIn', $json$"Войти"$json$::jsonb),
  ('ru', 'auth.signUp', $json$"Создать аккаунт"$json$::jsonb),
  ('ru', 'auth.toSignUp', $json$"Ещё нет аккаунта? Создайте его"$json$::jsonb),
  ('ru', 'auth.toSignIn', $json$"Уже есть аккаунт? Войдите"$json$::jsonb),
  ('ru', 'auth.checkEmail', $json$"Подтвердите аккаунт по письму, которое мы отправили, затем войдите."$json$::jsonb),
  ('ru', 'auth.waitingBrowser', $json$"Завершите вход в браузере…"$json$::jsonb),
  ('ru', 'auth.signOut', $json$"Выйти"$json$::jsonb),
  ('ru', 'auth.loading', $json$"Открываем сеанс…"$json$::jsonb),
  ('ru', 'connection.offline', $json$"Нет сети — изменения ждут синхронизации"$json$::jsonb),
  ('ru', 'connection.expired', $json$"Сеанс истёк — обновляем…"$json$::jsonb),
  ('ru', 'connection.pending', $json${"one": "{count} изменение не синхронизировано", "few": "{count} изменения не синхронизированы", "many": "{count} изменений не синхронизировано", "other": "{count} изменения не синхронизированы"}$json$::jsonb),
  ('ru', 'connection.failed', $json${"one": "{count} изменение отклонено сервером", "few": "{count} изменения отклонены сервером", "many": "{count} изменений отклонено сервером", "other": "{count} изменения отклонены сервером"}$json$::jsonb),
  ('ja', 'orgChat.open', $json$"チャットを開く"$json$::jsonb),
  ('ja', 'chatRepos.title', $json$"このチャットのリポジトリ"$json$::jsonb),
  ('ja', 'chatRepos.count', $json${"other": "フォルダー内に {count} 件"}$json$::jsonb),
  ('ja', 'chatRepos.dirty', $json${"other": "変更あり {count} 件"}$json$::jsonb),
  ('ja', 'chatRepos.refresh', $json$"リポジトリをもう一度確認"$json$::jsonb),
  ('ja', 'chatRepos.loading', $json$"リポジトリを読み込んでいます…"$json$::jsonb),
  ('ja', 'chatRepos.failed', $json$"このフォルダーのリポジトリを読み込めませんでした。"$json$::jsonb),
  ('ja', 'chatRepos.empty', $json$"このフォルダーにはまだリポジトリがありません。"$json$::jsonb),
  ('ja', 'chatRepos.outside', $json$"このフォルダーの外"$json$::jsonb),
  ('ja', 'chatRepos.detached', $json$"ブランチなし（detached）"$json$::jsonb),
  ('ja', 'chatRepos.unreadable', $json$"git が応答しませんでした"$json$::jsonb),
  ('ja', 'chatRepos.clean', $json$"変更なし"$json$::jsonb),
  ('ja', 'chatRepos.changed', $json${"other": "{count} 件の変更"}$json$::jsonb),
  ('ja', 'chatRepos.policy.repository', $json$"独自のポリシー"$json$::jsonb),
  ('ja', 'chatRepos.policy.organization', $json$"組織のポリシー"$json$::jsonb),
  ('ja', 'chatRepos.policy.none', $json$"ポリシーなし"$json$::jsonb),
  ('ja', 'chatRepos.unregistered', $json$"組織外"$json$::jsonb),
  ('ja', 'chatRepos.policy.hint', $json$"このチャットは、組織とそのすべてのリポジトリのうち最も厳しいルールをまとめて適用します。"$json$::jsonb),
  ('ja', 'app.updates.every', $json$"確認する間隔"$json$::jsonb),
  ('ja', 'app.updates.everyHint', $json$"JayV は起動時と、その後この間隔で新しいバージョンを探します。見つかると、すべての画面の上部にお知らせが表示されます。"$json$::jsonb),
  ('ja', 'app.updates.minutes', $json${"other": "{count} 分"}$json$::jsonb),
  ('ja', 'app.updates.hours', $json${"other": "{count} 時間"}$json$::jsonb),
  ('ja', 'app.updates.checkedAt', $json$"最終確認：{at}。"$json$::jsonb),
  ('ja', 'app.updates.never', $json$"JayV の起動後、まだ確認していません。"$json$::jsonb),
  ('ja', 'whatsNew.item.chatRepositories.title', $json$"組織チャットにリポジトリを表示"$json$::jsonb),
  ('ja', 'whatsNew.item.chatRepositories.detail', $json$"組織チャットの会話上部に、組織フォルダー内の各リポジトリが表示されるようになりました。ブランチ、リモートより何コミット進んでいるか遅れているか、変更されたファイル数、LLM ポリシーの出どころがわかります。リクエストが終わるたびに読み直します。組織ページとプロジェクトページのボタン名は「チャットを開く」になりました。"$json$::jsonb),
  ('ja', 'whatsNew.item.updateInterval.title', $json$"アップデートを確認する頻度を選べます"$json$::jsonb),
  ('ja', 'whatsNew.item.updateInterval.detail', $json$"設定 › アプリ で、新しいバージョンを 15 分、30 分、1 時間、4 時間ごとに確認するよう選べ、最後に確認した時刻も表示されます。新しいバージョンはすべての画面上部のお知らせとステータスバーに表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.missingTranslations.title', $json$"英語のままだった文言"$json$::jsonb),
  ('ja', 'whatsNew.item.missingTranslations.detail', $json$"アップデート画面、「閉じる」ボタン、一部のサインインと接続のメッセージが、どの言語でも英語で表示されていました。翻訳されました。"$json$::jsonb),
  ('ja', 'common.close', $json$"閉じる"$json$::jsonb),
  ('ja', 'update.title', $json$"JayV {version} に更新しています"$json$::jsonb),
  ('ja', 'update.checking', $json$"アップデートを確認しています"$json$::jsonb),
  ('ja', 'update.fromTo', $json$"バージョン {current} から {next} へ。完了すると JayV は自動で再起動します。"$json$::jsonb),
  ('ja', 'update.description', $json$"JayV はリリース用リポジトリで新しいバージョンを確認します。"$json$::jsonb),
  ('ja', 'update.step.checking', $json$"新しいバージョンを確認"$json$::jsonb),
  ('ja', 'update.step.downloading', $json$"アップデートをダウンロード"$json$::jsonb),
  ('ja', 'update.step.installing', $json$"インストール"$json$::jsonb),
  ('ja', 'update.step.restarting', $json$"JayV を再起動"$json$::jsonb),
  ('ja', 'update.progress', $json$"{received} / {total} MB · {percent}%"$json$::jsonb),
  ('ja', 'update.progress.unknown', $json$"{received} MB ダウンロード済み"$json$::jsonb),
  ('ja', 'update.keepOpen', $json$"再起動するまで JayV を開いたままにしてください。自身のファイルを置き換えています。"$json$::jsonb),
  ('ja', 'update.restarting.note', $json$"再起動しています…リクエストは中断したところから続きます。"$json$::jsonb),
  ('ja', 'update.notes', $json$"変更内容"$json$::jsonb),
  ('ja', 'update.retry', $json$"もう一度試す"$json$::jsonb),
  ('ja', 'auth.title', $json$"JayV にサインイン"$json$::jsonb),
  ('ja', 'auth.subtitle', $json$"プロジェクト、チャット、エージェントはどのマシンでも使えます。"$json$::jsonb),
  ('ja', 'auth.email', $json$"メールアドレス"$json$::jsonb),
  ('ja', 'auth.password', $json$"パスワード"$json$::jsonb),
  ('ja', 'auth.signIn', $json$"サインイン"$json$::jsonb),
  ('ja', 'auth.signUp', $json$"アカウントを作成"$json$::jsonb),
  ('ja', 'auth.toSignUp', $json$"アカウントをお持ちでない方は作成"$json$::jsonb),
  ('ja', 'auth.toSignIn', $json$"アカウントをお持ちの方はサインイン"$json$::jsonb),
  ('ja', 'auth.checkEmail', $json$"送信したメールでアカウントを確認してから、サインインしてください。"$json$::jsonb),
  ('ja', 'auth.waitingBrowser', $json$"ブラウザーでサインインを完了してください…"$json$::jsonb),
  ('ja', 'auth.signOut', $json$"サインアウト"$json$::jsonb),
  ('ja', 'auth.loading', $json$"セッションを開いています…"$json$::jsonb),
  ('ja', 'connection.offline', $json$"オフライン — 変更は同期を待っています"$json$::jsonb),
  ('ja', 'connection.expired', $json$"セッションの期限切れ — 更新しています…"$json$::jsonb),
  ('ja', 'connection.pending', $json${"other": "未同期の変更 {count} 件"}$json$::jsonb),
  ('ja', 'connection.failed', $json${"other": "サーバーに拒否された変更 {count} 件"}$json$::jsonb),
  ('de', 'orgChat.open', $json$"Chat öffnen"$json$::jsonb),
  ('de', 'chatRepos.title', $json$"Repositorys in diesem Chat"$json$::jsonb),
  ('de', 'chatRepos.count', $json${"one": "{count} im Ordner", "other": "{count} im Ordner"}$json$::jsonb),
  ('de', 'chatRepos.dirty', $json${"one": "{count} mit Änderungen", "other": "{count} mit Änderungen"}$json$::jsonb),
  ('de', 'chatRepos.refresh', $json$"Repositorys erneut prüfen"$json$::jsonb),
  ('de', 'chatRepos.loading', $json$"Repositorys werden gelesen…"$json$::jsonb),
  ('de', 'chatRepos.failed', $json$"Die Repositorys dieses Ordners konnten nicht gelesen werden."$json$::jsonb),
  ('de', 'chatRepos.empty', $json$"In diesem Ordner gibt es noch kein Repository."$json$::jsonb),
  ('de', 'chatRepos.outside', $json$"nicht in diesem Ordner"$json$::jsonb),
  ('de', 'chatRepos.detached', $json$"kein Branch (detached)"$json$::jsonb),
  ('de', 'chatRepos.unreadable', $json$"git hat nicht geantwortet"$json$::jsonb),
  ('de', 'chatRepos.clean', $json$"sauber"$json$::jsonb),
  ('de', 'chatRepos.changed', $json${"one": "{count} Änderung", "other": "{count} Änderungen"}$json$::jsonb),
  ('de', 'chatRepos.policy.repository', $json$"eigene Richtlinie"$json$::jsonb),
  ('de', 'chatRepos.policy.organization', $json$"Richtlinie der Organisation"$json$::jsonb),
  ('de', 'chatRepos.policy.none', $json$"keine Richtlinie"$json$::jsonb),
  ('de', 'chatRepos.unregistered', $json$"nicht in der Organisation"$json$::jsonb),
  ('de', 'chatRepos.policy.hint', $json$"Der Chat wendet die strengsten Regeln der Organisation und aller ihrer Repositorys gemeinsam an."$json$::jsonb),
  ('de', 'app.updates.every', $json$"Prüfen alle"$json$::jsonb),
  ('de', 'app.updates.everyHint', $json$"JayV sucht beim Start und danach in diesem Abstand nach einer neuen Version. Gibt es eine, erscheint oben auf jedem Bildschirm ein Hinweis."$json$::jsonb),
  ('de', 'app.updates.minutes', $json${"one": "{count} Minute", "other": "{count} Minuten"}$json$::jsonb),
  ('de', 'app.updates.hours', $json${"one": "{count} Stunde", "other": "{count} Stunden"}$json$::jsonb),
  ('de', 'app.updates.checkedAt', $json$"Zuletzt geprüft: {at}."$json$::jsonb),
  ('de', 'app.updates.never', $json$"Seit dem Start von JayV noch nicht geprüft."$json$::jsonb),
  ('de', 'whatsNew.item.chatRepositories.title', $json$"Repositorys im Organisations-Chat"$json$::jsonb),
  ('de', 'whatsNew.item.chatRepositories.detail', $json$"Der Organisations-Chat zeigt jetzt oben in der Unterhaltung jedes Repository im Organisationsordner: seinen Branch, wie weit es dem Remote voraus oder hinterher ist, wie viele Dateien sich geändert haben und woher seine LLM-Richtlinie kommt. Nach jeder Anfrage liest er sie neu. Der Button auf der Organisationsseite und auf der Seite Projekte heißt jetzt Chat öffnen."$json$::jsonb),
  ('de', 'whatsNew.item.updateInterval.title', $json$"Wählen, wie oft nach Updates gesucht wird"$json$::jsonb),
  ('de', 'whatsNew.item.updateInterval.detail', $json$"Unter Einstellungen › App lässt sich wählen, ob alle 15 Minuten, 30 Minuten, 1 Stunde oder 4 Stunden nach einer neuen Version gesucht wird, und man sieht, wann zuletzt geprüft wurde. Eine neue Version erscheint im Hinweis oben auf jedem Bildschirm und in der Statusleiste."$json$::jsonb),
  ('de', 'whatsNew.item.missingTranslations.title', $json$"Texte, die noch auf Englisch waren"$json$::jsonb),
  ('de', 'whatsNew.item.missingTranslations.detail', $json$"Das Update-Fenster, der Schließen-Button und einige Anmelde- und Verbindungsmeldungen erschienen in jeder Sprache auf Englisch. Sie sind jetzt übersetzt."$json$::jsonb),
  ('de', 'common.close', $json$"Schließen"$json$::jsonb),
  ('de', 'update.title', $json$"Update auf JayV {version}"$json$::jsonb),
  ('de', 'update.checking', $json$"Suche nach Updates"$json$::jsonb),
  ('de', 'update.fromTo', $json$"Von Version {current} auf {next}. JayV startet von selbst neu, wenn es fertig ist."$json$::jsonb),
  ('de', 'update.description', $json$"JayV prüft das Release-Repository auf eine neuere Version."$json$::jsonb),
  ('de', 'update.step.checking', $json$"Nach neuer Version suchen"$json$::jsonb),
  ('de', 'update.step.downloading', $json$"Update herunterladen"$json$::jsonb),
  ('de', 'update.step.installing', $json$"Installieren"$json$::jsonb),
  ('de', 'update.step.restarting', $json$"JayV neu starten"$json$::jsonb),
  ('de', 'update.progress', $json$"{received} von {total} MB · {percent} %"$json$::jsonb),
  ('de', 'update.progress.unknown', $json$"{received} MB heruntergeladen"$json$::jsonb),
  ('de', 'update.keepOpen', $json$"Lass JayV geöffnet, bis es neu startet: Es ersetzt gerade seine eigenen Dateien."$json$::jsonb),
  ('de', 'update.restarting.note', $json$"Neustart… deine Anfragen laufen dort weiter, wo sie aufgehört haben."$json$::jsonb),
  ('de', 'update.notes', $json$"Was sich ändert"$json$::jsonb),
  ('de', 'update.retry', $json$"Erneut versuchen"$json$::jsonb),
  ('de', 'auth.title', $json$"Bei JayV anmelden"$json$::jsonb),
  ('de', 'auth.subtitle', $json$"Deine Projekte, Chats und Agenten begleiten dich auf jedem Rechner."$json$::jsonb),
  ('de', 'auth.email', $json$"E-Mail"$json$::jsonb),
  ('de', 'auth.password', $json$"Passwort"$json$::jsonb),
  ('de', 'auth.signIn', $json$"Anmelden"$json$::jsonb),
  ('de', 'auth.signUp', $json$"Konto erstellen"$json$::jsonb),
  ('de', 'auth.toSignUp', $json$"Noch kein Konto? Erstelle eins"$json$::jsonb),
  ('de', 'auth.toSignIn', $json$"Schon ein Konto? Melde dich an"$json$::jsonb),
  ('de', 'auth.checkEmail', $json$"Bestätige das Konto über die E-Mail, die wir gesendet haben, und melde dich dann an."$json$::jsonb),
  ('de', 'auth.waitingBrowser', $json$"Schließe die Anmeldung im Browser ab…"$json$::jsonb),
  ('de', 'auth.signOut', $json$"Abmelden"$json$::jsonb),
  ('de', 'auth.loading', $json$"Sitzung wird geöffnet…"$json$::jsonb),
  ('de', 'connection.offline', $json$"Offline — Änderungen warten auf die Synchronisierung"$json$::jsonb),
  ('de', 'connection.expired', $json$"Sitzung abgelaufen — wird erneuert…"$json$::jsonb),
  ('de', 'connection.pending', $json${"one": "{count} Änderung nicht synchronisiert", "other": "{count} Änderungen nicht synchronisiert"}$json$::jsonb),
  ('de', 'connection.failed', $json${"one": "{count} Änderung vom Server abgelehnt", "other": "{count} Änderungen vom Server abgelehnt"}$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
