-- As estatísticas de uso: o gasto de cada chamada a modelo (agentes e Jev),
-- as leituras do limite dos planos e o trabalho do Jev. Espelham o SQLite
-- (`src-tauri/src/usage/store.rs`) pela mesma fila de sync. Sem chave
-- estrangeira para chat ou projeto de propósito: apagar um chat não apaga o
-- que ele gastou. As linhas só são acrescentadas.

create table public.usage_records (
  id text primary key,
  project_id text,
  chat_id text,
  turn_id text,
  source text not null,
  model text not null,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cache_read_tokens bigint not null default 0,
  cache_write_tokens bigint not null default 0,
  cost_usd double precision,
  requests double precision,
  duration_ms bigint not null default 0,
  success bigint not null default 1,
  precision text not null,
  machine_id text not null default '',
  created_at text not null
);

create table public.quota_snapshots (
  id text primary key,
  agent text not null,
  span text not null,
  used_percent double precision,
  resets_at text,
  plan text,
  captured_at text not null,
  machine_id text not null default ''
);

create table public.jev_records (
  id text primary key,
  project_id text,
  chat_id text,
  turn_id text,
  kind text not null,
  amount double precision not null,
  precision text not null,
  created_at text not null
);

do $$
declare
  name text;
begin
  foreach name in array array['usage_records','quota_snapshots','jev_records'] loop
    execute format('alter table public.%I add column user_id uuid not null default auth.uid() references auth.users on delete cascade', name);
    execute format('alter table public.%I
      add column row_updated_at timestamptz not null default now(),
      add column row_deleted_at timestamptz,
      add column synced_at timestamptz not null default clock_timestamp()', name);
    execute format('create index %I on public.%I (user_id, synced_at)', name || '_user_synced', name);
    execute format('create trigger sync_row before insert or update on public.%I for each row execute function public.sync_row()', name);
    execute format('alter table public.%I enable row level security', name);
    execute format('create policy "dono lê" on public.%I for select to authenticated using (user_id = (select auth.uid()))', name);
    execute format('create policy "dono escreve" on public.%I for insert to authenticated with check (user_id = (select auth.uid()))', name);
    execute format('create policy "dono muda" on public.%I for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()))', name);
    execute format('revoke delete, truncate on public.%I from anon, authenticated', name);
    execute format('revoke all on public.%I from anon', name);
  end loop;
end
$$;

-- Conta a chamada e devolve quantas o usuário já fez hoje (UTC). A função
-- `jev` compara com o limite e devolve os dois números em cabeçalhos, que o
-- app mostra nas estatísticas. `jev_take_call` fica para funções antigas.
create function public.jev_count_call() returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  used int;
begin
  if (select auth.uid()) is null then
    raise exception 'sem sessão' using errcode = '28000';
  end if;
  insert into public.jev_usage (user_id, day, calls)
  values ((select auth.uid()), (now() at time zone 'utc')::date, 1)
  on conflict (user_id, day) do update set calls = public.jev_usage.calls + 1
  returning calls into used;
  return used;
end
$$;
revoke execute on function public.jev_count_call() from public, anon;
grant execute on function public.jev_count_call() to authenticated;


-- As estatísticas de uso, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'nav.stats', $json$"Estatísticas"$json$::jsonb),
  ('pt-BR', 'usage.loading', $json$"Somando o uso…"$json$::jsonb),
  ('pt-BR', 'usage.empty', $json$"Nada registrado neste período ainda."$json$::jsonb),
  ('pt-BR', 'usage.scope.project', $json$"Projeto"$json$::jsonb),
  ('pt-BR', 'usage.scope.chat', $json$"Chat"$json$::jsonb),
  ('pt-BR', 'usage.scope.global', $json$"Tudo"$json$::jsonb),
  ('pt-BR', 'usage.scope.allChats', $json$"Todos os chats"$json$::jsonb),
  ('pt-BR', 'usage.chat.removed', $json$"(chat removido)"$json$::jsonb),
  ('pt-BR', 'usage.project.removed', $json$"(projeto removido)"$json$::jsonb),
  ('pt-BR', 'usage.period', $json$"Período"$json$::jsonb),
  ('pt-BR', 'usage.period.today', $json$"Hoje"$json$::jsonb),
  ('pt-BR', 'usage.period.7d', $json$"Últimos 7 dias"$json$::jsonb),
  ('pt-BR', 'usage.period.30d', $json$"Últimos 30 dias"$json$::jsonb),
  ('pt-BR', 'usage.period.all', $json$"Desde o início"$json$::jsonb),
  ('pt-BR', 'usage.period.custom', $json$"Intervalo personalizado"$json$::jsonb),
  ('pt-BR', 'usage.period.from', $json$"De"$json$::jsonb),
  ('pt-BR', 'usage.period.to', $json$"Até"$json$::jsonb),
  ('pt-BR', 'usage.estimated.share', $json$"{share} destes tokens são estimados: a ferramenta não os informou."$json$::jsonb),
  ('pt-BR', 'usage.estimated.hint', $json$"Estimado quer dizer que o app contou caracteres ÷ 4 porque a ferramenta não informou o próprio uso. Os turnos de antes desta versão também são estimados."$json$::jsonb),
  ('pt-BR', 'usage.input', $json$"Tokens de entrada"$json$::jsonb),
  ('pt-BR', 'usage.output', $json$"Tokens de saída"$json$::jsonb),
  ('pt-BR', 'usage.cache', $json$"Cache lido / gravado"$json$::jsonb),
  ('pt-BR', 'usage.cache.hint', $json$"Tokens de entrada servidos pelo cache de prompt do provedor, e tokens gravados nele."$json$::jsonb),
  ('pt-BR', 'usage.cache.read', $json$"Cache lido"$json$::jsonb),
  ('pt-BR', 'usage.cost', $json$"Custo informado"$json$::jsonb),
  ('pt-BR', 'usage.cost.hint', $json$"Só o que as ferramentas informam. O Claude Code informa quanto a API cobraria, mesmo na assinatura. “—” quer dizer que nenhuma ferramenta informou custo."$json$::jsonb),
  ('pt-BR', 'usage.requests', $json$"Premium requests"$json$::jsonb),
  ('pt-BR', 'usage.turns', $json$"Turnos"$json$::jsonb),
  ('pt-BR', 'usage.calls', $json$"Chamadas a modelos"$json$::jsonb),
  ('pt-BR', 'usage.success', $json$"Taxa de sucesso"$json$::jsonb),
  ('pt-BR', 'usage.duration', $json$"Tempo gasto"$json$::jsonb),
  ('pt-BR', 'usage.quota.title', $json$"Limites do plano"$json$::jsonb),
  ('pt-BR', 'usage.quota.description', $json$"Quanto de cada janela do plano já foi usado. Valem para a conta inteira: incluem o uso fora do JayV e em outros computadores."$json$::jsonb),
  ('pt-BR', 'usage.quota.none', $json$"Nenhum limite de plano lido ainda."$json$::jsonb),
  ('pt-BR', 'usage.quota.refresh', $json$"Ler limites do plano"$json$::jsonb),
  ('pt-BR', 'usage.quota.refreshing', $json$"Lendo limites…"$json$::jsonb),
  ('pt-BR', 'usage.quota.readAt', $json$"Lido em {date}"$json$::jsonb),
  ('pt-BR', 'usage.quota.resets', $json$"Renova {when}"$json$::jsonb),
  ('pt-BR', 'usage.quota.notInstalled', $json$"O {agent} não foi encontrado neste computador."$json$::jsonb),
  ('pt-BR', 'usage.quota.silent', $json$"O {agent} não respondeu ao /usage a tempo."$json$::jsonb),
  ('pt-BR', 'usage.quota.unreadable', $json$"O {agent} respondeu ao /usage num formato que esta versão não lê."$json$::jsonb),
  ('pt-BR', 'usage.quota.noData', $json$"O {agent} ainda não registrou um limite de plano neste computador."$json$::jsonb),
  ('pt-BR', 'usage.quota.copilotUnreported', $json$"O Copilot CLI não informa o saldo do plano fora do modo interativo. As premium requests usadas pelo JayV são contadas acima."$json$::jsonb),
  ('pt-BR', 'usage.window.session', $json$"Sessão de 5 horas"$json$::jsonb),
  ('pt-BR', 'usage.window.week', $json$"Semana"$json$::jsonb),
  ('pt-BR', 'usage.window.weekOf', $json$"Semana ({name})"$json$::jsonb),
  ('pt-BR', 'usage.window.month', $json$"Mês"$json$::jsonb),
  ('pt-BR', 'usage.window.day', $json$"Chamadas de hoje"$json$::jsonb),
  ('pt-BR', 'usage.chart.daily', $json$"Tokens por dia"$json$::jsonb),
  ('pt-BR', 'usage.chart.models', $json$"Tokens por modelo"$json$::jsonb),
  ('pt-BR', 'usage.jev.title', $json$"Como o Jev se saiu"$json$::jsonb),
  ('pt-BR', 'usage.jev.work', $json$"O que ele fez"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.entryPass', $json$"Pedidos liberados"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.entryAsk', $json$"Pedidos devolvidos com perguntas"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.entryBlock', $json$"Pedidos barrados"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.exitCleared', $json$"Ações da resposta liberadas"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.exitHeld', $json$"Ações da resposta seguradas"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.cacheHit', $json$"Acertos do cache de contexto"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.cacheMiss', $json$"Faltas no cache de contexto"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.secretRedacted', $json$"Segredos ocultados"$json$::jsonb),
  ('pt-BR', 'usage.jev.work.fileWithheld', $json$"Arquivos retidos"$json$::jsonb),
  ('pt-BR', 'usage.jev.cost', $json$"Quanto ele custou"$json$::jsonb),
  ('pt-BR', 'usage.jev.cost.value', $json$"{calls} chamadas · {input} entrada · {output} saída · {time}"$json$::jsonb),
  ('pt-BR', 'usage.jev.stage.entry', $json$"Jev · portaria"$json$::jsonb),
  ('pt-BR', 'usage.jev.stage.routing', $json$"Jev · roteamento"$json$::jsonb),
  ('pt-BR', 'usage.jev.stage.verification', $json$"Jev · verificação"$json$::jsonb),
  ('pt-BR', 'usage.jev.stage.asking', $json$"Jev · perguntas"$json$::jsonb),
  ('pt-BR', 'usage.jev.saved', $json$"O que ele poupou (estimado)"$json$::jsonb),
  ('pt-BR', 'usage.jev.saved.hint', $json$"Estimativas, nunca somadas aos números reais: um pedido barrado é o tamanho dele mais uma resposta média; o contexto enxugado é o que o orçamento cortou."$json$::jsonb),
  ('pt-BR', 'usage.jev.saved.blocked', $json$"Pedidos barrados"$json$::jsonb),
  ('pt-BR', 'usage.jev.saved.context', $json$"Contexto enxugado"$json$::jsonb),
  ('pt-BR', 'usage.jev.saved.total', $json$"Total poupado"$json$::jsonb),
  ('pt-BR', 'usage.table.name', $json$"Nome"$json$::jsonb),
  ('pt-BR', 'usage.table.bySource', $json$"Por agente"$json$::jsonb),
  ('pt-BR', 'usage.table.byModel', $json$"Por modelo"$json$::jsonb),
  ('pt-BR', 'usage.table.byProject', $json$"Por projeto"$json$::jsonb),
  ('pt-BR', 'usage.table.byChat', $json$"Por chat"$json$::jsonb),
  ('pt-BR', 'usage.chat.open', $json$"Abrir as estatísticas deste chat"$json$::jsonb),
  ('pt-BR', 'usage.chat.tokens', $json$"Este chat: {input} entrada · {output} saída"$json$::jsonb),
  ('pt-BR', 'usage.chat.blocked', $json${"one": "Jev barrou {count}", "other": "Jev barrou {count}"}$json$::jsonb),
  ('pt-BR', 'usage.project.month', $json$"Últimos 30 dias: {tokens} tokens"$json$::jsonb),
  ('pt-BR', 'usage.turn.tokens', $json$"{input} entrada · {output} saída"$json$::jsonb),
  ('en', 'nav.stats', $json$"Statistics"$json$::jsonb),
  ('en', 'usage.loading', $json$"Adding up usage…"$json$::jsonb),
  ('en', 'usage.empty', $json$"Nothing recorded in this period yet."$json$::jsonb),
  ('en', 'usage.scope.project', $json$"Project"$json$::jsonb),
  ('en', 'usage.scope.chat', $json$"Chat"$json$::jsonb),
  ('en', 'usage.scope.global', $json$"Everything"$json$::jsonb),
  ('en', 'usage.scope.allChats', $json$"All chats"$json$::jsonb),
  ('en', 'usage.chat.removed', $json$"(chat removed)"$json$::jsonb),
  ('en', 'usage.project.removed', $json$"(project removed)"$json$::jsonb),
  ('en', 'usage.period', $json$"Period"$json$::jsonb),
  ('en', 'usage.period.today', $json$"Today"$json$::jsonb),
  ('en', 'usage.period.7d', $json$"Last 7 days"$json$::jsonb),
  ('en', 'usage.period.30d', $json$"Last 30 days"$json$::jsonb),
  ('en', 'usage.period.all', $json$"All time"$json$::jsonb),
  ('en', 'usage.period.custom', $json$"Custom range"$json$::jsonb),
  ('en', 'usage.period.from', $json$"From"$json$::jsonb),
  ('en', 'usage.period.to', $json$"To"$json$::jsonb),
  ('en', 'usage.estimated.share', $json$"{share} of these tokens are estimated: the tool did not report them."$json$::jsonb),
  ('en', 'usage.estimated.hint', $json$"Estimated means the app counted characters ÷ 4 because the tool did not report its own usage. Turns from before this version are estimated too."$json$::jsonb),
  ('en', 'usage.input', $json$"Input tokens"$json$::jsonb),
  ('en', 'usage.output', $json$"Output tokens"$json$::jsonb),
  ('en', 'usage.cache', $json$"Cache read / write"$json$::jsonb),
  ('en', 'usage.cache.hint', $json$"Input tokens served from the provider's prompt cache, and tokens written to it."$json$::jsonb),
  ('en', 'usage.cache.read', $json$"Cache read"$json$::jsonb),
  ('en', 'usage.cost', $json$"Reported cost"$json$::jsonb),
  ('en', 'usage.cost.hint', $json$"Only what the tools report. Claude Code reports what the API would charge, even on a subscription. “—” means no tool reported a cost."$json$::jsonb),
  ('en', 'usage.requests', $json$"Premium requests"$json$::jsonb),
  ('en', 'usage.turns', $json$"Turns"$json$::jsonb),
  ('en', 'usage.calls', $json$"Model calls"$json$::jsonb),
  ('en', 'usage.success', $json$"Success rate"$json$::jsonb),
  ('en', 'usage.duration', $json$"Time spent"$json$::jsonb),
  ('en', 'usage.quota.title', $json$"Plan limits"$json$::jsonb),
  ('en', 'usage.quota.description', $json$"How much of each plan window is used. These are account-wide: they include usage outside JayV and on other devices."$json$::jsonb),
  ('en', 'usage.quota.none', $json$"No plan limit read yet."$json$::jsonb),
  ('en', 'usage.quota.refresh', $json$"Read plan limits"$json$::jsonb),
  ('en', 'usage.quota.refreshing', $json$"Reading limits…"$json$::jsonb),
  ('en', 'usage.quota.readAt', $json$"Read {date}"$json$::jsonb),
  ('en', 'usage.quota.resets', $json$"Resets {when}"$json$::jsonb),
  ('en', 'usage.quota.notInstalled', $json$"{agent} was not found on this computer."$json$::jsonb),
  ('en', 'usage.quota.silent', $json$"{agent} did not answer /usage in time."$json$::jsonb),
  ('en', 'usage.quota.unreadable', $json$"{agent} answered /usage in a format this version cannot read."$json$::jsonb),
  ('en', 'usage.quota.noData', $json$"{agent} has not recorded a plan limit on this computer yet."$json$::jsonb),
  ('en', 'usage.quota.copilotUnreported', $json$"The Copilot CLI does not report the plan balance outside interactive mode. Premium requests used through JayV are counted above."$json$::jsonb),
  ('en', 'usage.window.session', $json$"5-hour session"$json$::jsonb),
  ('en', 'usage.window.week', $json$"Week"$json$::jsonb),
  ('en', 'usage.window.weekOf', $json$"Week ({name})"$json$::jsonb),
  ('en', 'usage.window.month', $json$"Month"$json$::jsonb),
  ('en', 'usage.window.day', $json$"Today's calls"$json$::jsonb),
  ('en', 'usage.chart.daily', $json$"Tokens per day"$json$::jsonb),
  ('en', 'usage.chart.models', $json$"Tokens per model"$json$::jsonb),
  ('en', 'usage.jev.title', $json$"How Jev performed"$json$::jsonb),
  ('en', 'usage.jev.work', $json$"What it did"$json$::jsonb),
  ('en', 'usage.jev.work.entryPass', $json$"Requests let through"$json$::jsonb),
  ('en', 'usage.jev.work.entryAsk', $json$"Requests sent back with questions"$json$::jsonb),
  ('en', 'usage.jev.work.entryBlock', $json$"Requests blocked"$json$::jsonb),
  ('en', 'usage.jev.work.exitCleared', $json$"Answer actions cleared"$json$::jsonb),
  ('en', 'usage.jev.work.exitHeld', $json$"Answer actions held"$json$::jsonb),
  ('en', 'usage.jev.work.cacheHit', $json$"Context cache hits"$json$::jsonb),
  ('en', 'usage.jev.work.cacheMiss', $json$"Context cache misses"$json$::jsonb),
  ('en', 'usage.jev.work.secretRedacted', $json$"Secrets redacted"$json$::jsonb),
  ('en', 'usage.jev.work.fileWithheld', $json$"Files withheld"$json$::jsonb),
  ('en', 'usage.jev.cost', $json$"What it cost"$json$::jsonb),
  ('en', 'usage.jev.cost.value', $json$"{calls} calls · {input} in · {output} out · {time}"$json$::jsonb),
  ('en', 'usage.jev.stage.entry', $json$"Jev · entry gate"$json$::jsonb),
  ('en', 'usage.jev.stage.routing', $json$"Jev · routing"$json$::jsonb),
  ('en', 'usage.jev.stage.verification', $json$"Jev · verification"$json$::jsonb),
  ('en', 'usage.jev.stage.asking', $json$"Jev · questions"$json$::jsonb),
  ('en', 'usage.jev.saved', $json$"What it saved (estimated)"$json$::jsonb),
  ('en', 'usage.jev.saved.hint', $json$"Estimates, never added to the real numbers: a blocked request is its own size plus an average answer; trimmed context is what the budget cut."$json$::jsonb),
  ('en', 'usage.jev.saved.blocked', $json$"Blocked requests"$json$::jsonb),
  ('en', 'usage.jev.saved.context', $json$"Trimmed context"$json$::jsonb),
  ('en', 'usage.jev.saved.total', $json$"Total saved"$json$::jsonb),
  ('en', 'usage.table.name', $json$"Name"$json$::jsonb),
  ('en', 'usage.table.bySource', $json$"By agent"$json$::jsonb),
  ('en', 'usage.table.byModel', $json$"By model"$json$::jsonb),
  ('en', 'usage.table.byProject', $json$"By project"$json$::jsonb),
  ('en', 'usage.table.byChat', $json$"By chat"$json$::jsonb),
  ('en', 'usage.chat.open', $json$"Open this chat's statistics"$json$::jsonb),
  ('en', 'usage.chat.tokens', $json$"This chat: {input} in · {output} out"$json$::jsonb),
  ('en', 'usage.chat.blocked', $json${"one": "Jev blocked {count}", "other": "Jev blocked {count}"}$json$::jsonb),
  ('en', 'usage.project.month', $json$"Last 30 days: {tokens} tokens"$json$::jsonb),
  ('en', 'usage.turn.tokens', $json$"{input} in · {output} out"$json$::jsonb),
  ('es', 'nav.stats', $json$"Estadísticas"$json$::jsonb),
  ('es', 'usage.loading', $json$"Sumando el uso…"$json$::jsonb),
  ('es', 'usage.empty', $json$"Aún no hay nada registrado en este periodo."$json$::jsonb),
  ('es', 'usage.scope.project', $json$"Proyecto"$json$::jsonb),
  ('es', 'usage.scope.chat', $json$"Chat"$json$::jsonb),
  ('es', 'usage.scope.global', $json$"Todo"$json$::jsonb),
  ('es', 'usage.scope.allChats', $json$"Todos los chats"$json$::jsonb),
  ('es', 'usage.chat.removed', $json$"(chat eliminado)"$json$::jsonb),
  ('es', 'usage.project.removed', $json$"(proyecto eliminado)"$json$::jsonb),
  ('es', 'usage.period', $json$"Periodo"$json$::jsonb),
  ('es', 'usage.period.today', $json$"Hoy"$json$::jsonb),
  ('es', 'usage.period.7d', $json$"Últimos 7 días"$json$::jsonb),
  ('es', 'usage.period.30d', $json$"Últimos 30 días"$json$::jsonb),
  ('es', 'usage.period.all', $json$"Desde el inicio"$json$::jsonb),
  ('es', 'usage.period.custom', $json$"Rango personalizado"$json$::jsonb),
  ('es', 'usage.period.from', $json$"Desde"$json$::jsonb),
  ('es', 'usage.period.to', $json$"Hasta"$json$::jsonb),
  ('es', 'usage.estimated.share', $json$"{share} de estos tokens son estimados: la herramienta no los informó."$json$::jsonb),
  ('es', 'usage.estimated.hint', $json$"Estimado significa que la app contó caracteres ÷ 4 porque la herramienta no informó su propio uso. Los turnos anteriores a esta versión también son estimados."$json$::jsonb),
  ('es', 'usage.input', $json$"Tokens de entrada"$json$::jsonb),
  ('es', 'usage.output', $json$"Tokens de salida"$json$::jsonb),
  ('es', 'usage.cache', $json$"Caché leída / escrita"$json$::jsonb),
  ('es', 'usage.cache.hint', $json$"Tokens de entrada servidos desde la caché de prompts del proveedor, y tokens escritos en ella."$json$::jsonb),
  ('es', 'usage.cache.read', $json$"Caché leída"$json$::jsonb),
  ('es', 'usage.cost', $json$"Costo informado"$json$::jsonb),
  ('es', 'usage.cost.hint', $json$"Solo lo que informan las herramientas. Claude Code informa lo que cobraría la API, incluso con suscripción. “—” significa que ninguna herramienta informó un costo."$json$::jsonb),
  ('es', 'usage.requests', $json$"Solicitudes premium"$json$::jsonb),
  ('es', 'usage.turns', $json$"Turnos"$json$::jsonb),
  ('es', 'usage.calls', $json$"Llamadas a modelos"$json$::jsonb),
  ('es', 'usage.success', $json$"Tasa de éxito"$json$::jsonb),
  ('es', 'usage.duration', $json$"Tiempo empleado"$json$::jsonb),
  ('es', 'usage.quota.title', $json$"Límites del plan"$json$::jsonb),
  ('es', 'usage.quota.description', $json$"Cuánto de cada ventana del plan se ha usado. Son de toda la cuenta: incluyen el uso fuera de JayV y en otros dispositivos."$json$::jsonb),
  ('es', 'usage.quota.none', $json$"Aún no se ha leído ningún límite del plan."$json$::jsonb),
  ('es', 'usage.quota.refresh', $json$"Leer límites del plan"$json$::jsonb),
  ('es', 'usage.quota.refreshing', $json$"Leyendo límites…"$json$::jsonb),
  ('es', 'usage.quota.readAt', $json$"Leído {date}"$json$::jsonb),
  ('es', 'usage.quota.resets', $json$"Se renueva {when}"$json$::jsonb),
  ('es', 'usage.quota.notInstalled', $json$"No se encontró {agent} en este equipo."$json$::jsonb),
  ('es', 'usage.quota.silent', $json$"{agent} no respondió a /usage a tiempo."$json$::jsonb),
  ('es', 'usage.quota.unreadable', $json$"{agent} respondió a /usage en un formato que esta versión no puede leer."$json$::jsonb),
  ('es', 'usage.quota.noData', $json$"{agent} aún no ha registrado un límite del plan en este equipo."$json$::jsonb),
  ('es', 'usage.quota.copilotUnreported', $json$"Copilot CLI no informa el saldo del plan fuera del modo interactivo. Las solicitudes premium usadas desde JayV se cuentan arriba."$json$::jsonb),
  ('es', 'usage.window.session', $json$"Sesión de 5 horas"$json$::jsonb),
  ('es', 'usage.window.week', $json$"Semana"$json$::jsonb),
  ('es', 'usage.window.weekOf', $json$"Semana ({name})"$json$::jsonb),
  ('es', 'usage.window.month', $json$"Mes"$json$::jsonb),
  ('es', 'usage.window.day', $json$"Llamadas de hoy"$json$::jsonb),
  ('es', 'usage.chart.daily', $json$"Tokens por día"$json$::jsonb),
  ('es', 'usage.chart.models', $json$"Tokens por modelo"$json$::jsonb),
  ('es', 'usage.jev.title', $json$"Cómo le fue a Jev"$json$::jsonb),
  ('es', 'usage.jev.work', $json$"Lo que hizo"$json$::jsonb),
  ('es', 'usage.jev.work.entryPass', $json$"Solicitudes aprobadas"$json$::jsonb),
  ('es', 'usage.jev.work.entryAsk', $json$"Solicitudes devueltas con preguntas"$json$::jsonb),
  ('es', 'usage.jev.work.entryBlock', $json$"Solicitudes bloqueadas"$json$::jsonb),
  ('es', 'usage.jev.work.exitCleared', $json$"Acciones de respuesta aprobadas"$json$::jsonb),
  ('es', 'usage.jev.work.exitHeld', $json$"Acciones de respuesta retenidas"$json$::jsonb),
  ('es', 'usage.jev.work.cacheHit', $json$"Aciertos de la caché de contexto"$json$::jsonb),
  ('es', 'usage.jev.work.cacheMiss', $json$"Fallos de la caché de contexto"$json$::jsonb),
  ('es', 'usage.jev.work.secretRedacted', $json$"Secretos ocultados"$json$::jsonb),
  ('es', 'usage.jev.work.fileWithheld', $json$"Archivos retenidos"$json$::jsonb),
  ('es', 'usage.jev.cost', $json$"Lo que costó"$json$::jsonb),
  ('es', 'usage.jev.cost.value', $json$"{calls} llamadas · {input} entrada · {output} salida · {time}"$json$::jsonb),
  ('es', 'usage.jev.stage.entry', $json$"Jev · portería"$json$::jsonb),
  ('es', 'usage.jev.stage.routing', $json$"Jev · enrutamiento"$json$::jsonb),
  ('es', 'usage.jev.stage.verification', $json$"Jev · verificación"$json$::jsonb),
  ('es', 'usage.jev.stage.asking', $json$"Jev · preguntas"$json$::jsonb),
  ('es', 'usage.jev.saved', $json$"Lo que ahorró (estimado)"$json$::jsonb),
  ('es', 'usage.jev.saved.hint', $json$"Estimaciones, nunca sumadas a los números reales: una solicitud bloqueada es su propio tamaño más una respuesta media; el contexto recortado es lo que cortó el presupuesto."$json$::jsonb),
  ('es', 'usage.jev.saved.blocked', $json$"Solicitudes bloqueadas"$json$::jsonb),
  ('es', 'usage.jev.saved.context', $json$"Contexto recortado"$json$::jsonb),
  ('es', 'usage.jev.saved.total', $json$"Total ahorrado"$json$::jsonb),
  ('es', 'usage.table.name', $json$"Nombre"$json$::jsonb),
  ('es', 'usage.table.bySource', $json$"Por agente"$json$::jsonb),
  ('es', 'usage.table.byModel', $json$"Por modelo"$json$::jsonb),
  ('es', 'usage.table.byProject', $json$"Por proyecto"$json$::jsonb),
  ('es', 'usage.table.byChat', $json$"Por chat"$json$::jsonb),
  ('es', 'usage.chat.open', $json$"Abrir las estadísticas de este chat"$json$::jsonb),
  ('es', 'usage.chat.tokens', $json$"Este chat: {input} entrada · {output} salida"$json$::jsonb),
  ('es', 'usage.chat.blocked', $json${"one": "Jev bloqueó {count}", "other": "Jev bloqueó {count}"}$json$::jsonb),
  ('es', 'usage.project.month', $json$"Últimos 30 días: {tokens} tokens"$json$::jsonb),
  ('es', 'usage.turn.tokens', $json$"{input} entrada · {output} salida"$json$::jsonb),
  ('zh-CN', 'nav.stats', $json$"统计"$json$::jsonb),
  ('zh-CN', 'usage.loading', $json$"正在汇总用量…"$json$::jsonb),
  ('zh-CN', 'usage.empty', $json$"此期间还没有任何记录。"$json$::jsonb),
  ('zh-CN', 'usage.scope.project', $json$"项目"$json$::jsonb),
  ('zh-CN', 'usage.scope.chat', $json$"聊天"$json$::jsonb),
  ('zh-CN', 'usage.scope.global', $json$"全部"$json$::jsonb),
  ('zh-CN', 'usage.scope.allChats', $json$"所有聊天"$json$::jsonb),
  ('zh-CN', 'usage.chat.removed', $json$"(已删除的聊天)"$json$::jsonb),
  ('zh-CN', 'usage.project.removed', $json$"(已删除的项目)"$json$::jsonb),
  ('zh-CN', 'usage.period', $json$"期间"$json$::jsonb),
  ('zh-CN', 'usage.period.today', $json$"今天"$json$::jsonb),
  ('zh-CN', 'usage.period.7d', $json$"最近 7 天"$json$::jsonb),
  ('zh-CN', 'usage.period.30d', $json$"最近 30 天"$json$::jsonb),
  ('zh-CN', 'usage.period.all', $json$"全部时间"$json$::jsonb),
  ('zh-CN', 'usage.period.custom', $json$"自定义范围"$json$::jsonb),
  ('zh-CN', 'usage.period.from', $json$"从"$json$::jsonb),
  ('zh-CN', 'usage.period.to', $json$"到"$json$::jsonb),
  ('zh-CN', 'usage.estimated.share', $json$"这些 token 中有 {share} 是估算的：工具没有报告它们。"$json$::jsonb),
  ('zh-CN', 'usage.estimated.hint', $json$"估算表示工具没有报告自身用量，应用按字符数 ÷ 4 计算。此版本之前的轮次也是估算值。"$json$::jsonb),
  ('zh-CN', 'usage.input', $json$"输入 token"$json$::jsonb),
  ('zh-CN', 'usage.output', $json$"输出 token"$json$::jsonb),
  ('zh-CN', 'usage.cache', $json$"缓存读取 / 写入"$json$::jsonb),
  ('zh-CN', 'usage.cache.hint', $json$"由提供方提示缓存提供的输入 token，以及写入缓存的 token。"$json$::jsonb),
  ('zh-CN', 'usage.cache.read', $json$"缓存读取"$json$::jsonb),
  ('zh-CN', 'usage.cost', $json$"报告的费用"$json$::jsonb),
  ('zh-CN', 'usage.cost.hint', $json$"仅包含工具报告的部分。即使是订阅，Claude Code 也会报告 API 会收取的费用。“—”表示没有工具报告费用。"$json$::jsonb),
  ('zh-CN', 'usage.requests', $json$"高级请求"$json$::jsonb),
  ('zh-CN', 'usage.turns', $json$"轮次"$json$::jsonb),
  ('zh-CN', 'usage.calls', $json$"模型调用"$json$::jsonb),
  ('zh-CN', 'usage.success', $json$"成功率"$json$::jsonb),
  ('zh-CN', 'usage.duration', $json$"耗时"$json$::jsonb),
  ('zh-CN', 'usage.quota.title', $json$"套餐限额"$json$::jsonb),
  ('zh-CN', 'usage.quota.description', $json$"套餐每个时间窗口已用多少。这是整个账户的数据：包括在 JayV 之外和其他设备上的使用。"$json$::jsonb),
  ('zh-CN', 'usage.quota.none', $json$"尚未读取任何套餐限额。"$json$::jsonb),
  ('zh-CN', 'usage.quota.refresh', $json$"读取套餐限额"$json$::jsonb),
  ('zh-CN', 'usage.quota.refreshing', $json$"正在读取限额…"$json$::jsonb),
  ('zh-CN', 'usage.quota.readAt', $json$"读取于 {date}"$json$::jsonb),
  ('zh-CN', 'usage.quota.resets', $json$"{when} 重置"$json$::jsonb),
  ('zh-CN', 'usage.quota.notInstalled', $json$"在这台电脑上找不到 {agent}。"$json$::jsonb),
  ('zh-CN', 'usage.quota.silent', $json$"{agent} 没有及时响应 /usage。"$json$::jsonb),
  ('zh-CN', 'usage.quota.unreadable', $json$"{agent} 以此版本无法读取的格式响应了 /usage。"$json$::jsonb),
  ('zh-CN', 'usage.quota.noData', $json$"{agent} 还没有在这台电脑上记录套餐限额。"$json$::jsonb),
  ('zh-CN', 'usage.quota.copilotUnreported', $json$"Copilot CLI 在交互模式之外不报告套餐余额。通过 JayV 使用的高级请求已在上方统计。"$json$::jsonb),
  ('zh-CN', 'usage.window.session', $json$"5 小时会话"$json$::jsonb),
  ('zh-CN', 'usage.window.week', $json$"周"$json$::jsonb),
  ('zh-CN', 'usage.window.weekOf', $json$"周（{name}）"$json$::jsonb),
  ('zh-CN', 'usage.window.month', $json$"月"$json$::jsonb),
  ('zh-CN', 'usage.window.day', $json$"今日调用"$json$::jsonb),
  ('zh-CN', 'usage.chart.daily', $json$"每日 token"$json$::jsonb),
  ('zh-CN', 'usage.chart.models', $json$"各模型 token"$json$::jsonb),
  ('zh-CN', 'usage.jev.title', $json$"Jev 的表现"$json$::jsonb),
  ('zh-CN', 'usage.jev.work', $json$"它做了什么"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.entryPass', $json$"放行的请求"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.entryAsk', $json$"带着问题退回的请求"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.entryBlock', $json$"拦截的请求"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.exitCleared', $json$"放行的回答操作"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.exitHeld', $json$"暂扣的回答操作"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.cacheHit', $json$"上下文缓存命中"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.cacheMiss', $json$"上下文缓存未命中"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.secretRedacted', $json$"已隐藏的机密"$json$::jsonb),
  ('zh-CN', 'usage.jev.work.fileWithheld', $json$"未发送的文件"$json$::jsonb),
  ('zh-CN', 'usage.jev.cost', $json$"它的花费"$json$::jsonb),
  ('zh-CN', 'usage.jev.cost.value', $json$"{calls} 次调用 · 输入 {input} · 输出 {output} · {time}"$json$::jsonb),
  ('zh-CN', 'usage.jev.stage.entry', $json$"Jev · 入口把关"$json$::jsonb),
  ('zh-CN', 'usage.jev.stage.routing', $json$"Jev · 路由"$json$::jsonb),
  ('zh-CN', 'usage.jev.stage.verification', $json$"Jev · 校验"$json$::jsonb),
  ('zh-CN', 'usage.jev.stage.asking', $json$"Jev · 提问"$json$::jsonb),
  ('zh-CN', 'usage.jev.saved', $json$"它节省了什么（估算）"$json$::jsonb),
  ('zh-CN', 'usage.jev.saved.hint', $json$"均为估算，从不计入真实数字：被拦截的请求按其自身大小加一个平均回答计算；精简的上下文是预算裁掉的部分。"$json$::jsonb),
  ('zh-CN', 'usage.jev.saved.blocked', $json$"拦截的请求"$json$::jsonb),
  ('zh-CN', 'usage.jev.saved.context', $json$"精简的上下文"$json$::jsonb),
  ('zh-CN', 'usage.jev.saved.total', $json$"共节省"$json$::jsonb),
  ('zh-CN', 'usage.table.name', $json$"名称"$json$::jsonb),
  ('zh-CN', 'usage.table.bySource', $json$"按代理"$json$::jsonb),
  ('zh-CN', 'usage.table.byModel', $json$"按模型"$json$::jsonb),
  ('zh-CN', 'usage.table.byProject', $json$"按项目"$json$::jsonb),
  ('zh-CN', 'usage.table.byChat', $json$"按聊天"$json$::jsonb),
  ('zh-CN', 'usage.chat.open', $json$"打开此聊天的统计"$json$::jsonb),
  ('zh-CN', 'usage.chat.tokens', $json$"此聊天：输入 {input} · 输出 {output}"$json$::jsonb),
  ('zh-CN', 'usage.chat.blocked', $json${"other": "Jev 拦截了 {count} 个"}$json$::jsonb),
  ('zh-CN', 'usage.project.month', $json$"最近 30 天：{tokens} token"$json$::jsonb),
  ('zh-CN', 'usage.turn.tokens', $json$"输入 {input} · 输出 {output}"$json$::jsonb),
  ('hi', 'nav.stats', $json$"आँकड़े"$json$::jsonb),
  ('hi', 'usage.loading', $json$"उपयोग जोड़ा जा रहा है…"$json$::jsonb),
  ('hi', 'usage.empty', $json$"इस अवधि में अभी कुछ दर्ज नहीं है।"$json$::jsonb),
  ('hi', 'usage.scope.project', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'usage.scope.chat', $json$"चैट"$json$::jsonb),
  ('hi', 'usage.scope.global', $json$"सब कुछ"$json$::jsonb),
  ('hi', 'usage.scope.allChats', $json$"सभी चैट"$json$::jsonb),
  ('hi', 'usage.chat.removed', $json$"(हटाई गई चैट)"$json$::jsonb),
  ('hi', 'usage.project.removed', $json$"(हटाया गया प्रोजेक्ट)"$json$::jsonb),
  ('hi', 'usage.period', $json$"अवधि"$json$::jsonb),
  ('hi', 'usage.period.today', $json$"आज"$json$::jsonb),
  ('hi', 'usage.period.7d', $json$"पिछले 7 दिन"$json$::jsonb),
  ('hi', 'usage.period.30d', $json$"पिछले 30 दिन"$json$::jsonb),
  ('hi', 'usage.period.all', $json$"शुरू से अब तक"$json$::jsonb),
  ('hi', 'usage.period.custom', $json$"अपनी अवधि"$json$::jsonb),
  ('hi', 'usage.period.from', $json$"से"$json$::jsonb),
  ('hi', 'usage.period.to', $json$"तक"$json$::jsonb),
  ('hi', 'usage.estimated.share', $json$"इन टोकन में से {share} अनुमानित हैं: टूल ने इन्हें नहीं बताया।"$json$::jsonb),
  ('hi', 'usage.estimated.hint', $json$"अनुमानित का मतलब है कि टूल ने अपना उपयोग नहीं बताया, इसलिए ऐप ने अक्षर ÷ 4 गिने। इस संस्करण से पहले के टर्न भी अनुमानित हैं।"$json$::jsonb),
  ('hi', 'usage.input', $json$"इनपुट टोकन"$json$::jsonb),
  ('hi', 'usage.output', $json$"आउटपुट टोकन"$json$::jsonb),
  ('hi', 'usage.cache', $json$"कैश पढ़ा / लिखा"$json$::jsonb),
  ('hi', 'usage.cache.hint', $json$"प्रदाता के प्रॉम्प्ट कैश से मिले इनपुट टोकन, और उसमें लिखे गए टोकन।"$json$::jsonb),
  ('hi', 'usage.cache.read', $json$"कैश पढ़ा"$json$::jsonb),
  ('hi', 'usage.cost', $json$"बताई गई लागत"$json$::jsonb),
  ('hi', 'usage.cost.hint', $json$"सिर्फ़ वही जो टूल बताते हैं। Claude Code सदस्यता में भी बताता है कि API कितना लेता। “—” का मतलब है कि किसी टूल ने लागत नहीं बताई।"$json$::jsonb),
  ('hi', 'usage.requests', $json$"प्रीमियम अनुरोध"$json$::jsonb),
  ('hi', 'usage.turns', $json$"टर्न"$json$::jsonb),
  ('hi', 'usage.calls', $json$"मॉडल कॉल"$json$::jsonb),
  ('hi', 'usage.success', $json$"सफलता दर"$json$::jsonb),
  ('hi', 'usage.duration', $json$"लगा समय"$json$::jsonb),
  ('hi', 'usage.quota.title', $json$"प्लान की सीमाएँ"$json$::jsonb),
  ('hi', 'usage.quota.description', $json$"प्लान की हर अवधि में कितना उपयोग हो चुका है। ये पूरे खाते की हैं: इनमें JayV के बाहर और दूसरे डिवाइस पर हुआ उपयोग भी शामिल है।"$json$::jsonb),
  ('hi', 'usage.quota.none', $json$"अभी तक प्लान की कोई सीमा नहीं पढ़ी गई।"$json$::jsonb),
  ('hi', 'usage.quota.refresh', $json$"प्लान की सीमाएँ पढ़ें"$json$::jsonb),
  ('hi', 'usage.quota.refreshing', $json$"सीमाएँ पढ़ी जा रही हैं…"$json$::jsonb),
  ('hi', 'usage.quota.readAt', $json$"{date} को पढ़ा गया"$json$::jsonb),
  ('hi', 'usage.quota.resets', $json$"{when} को रीसेट"$json$::jsonb),
  ('hi', 'usage.quota.notInstalled', $json$"{agent} इस कंप्यूटर पर नहीं मिला।"$json$::jsonb),
  ('hi', 'usage.quota.silent', $json$"{agent} ने समय पर /usage का जवाब नहीं दिया।"$json$::jsonb),
  ('hi', 'usage.quota.unreadable', $json$"{agent} ने /usage का जवाब ऐसे फ़ॉर्मैट में दिया जिसे यह संस्करण नहीं पढ़ सकता।"$json$::jsonb),
  ('hi', 'usage.quota.noData', $json$"{agent} ने इस कंप्यूटर पर अभी तक प्लान की कोई सीमा दर्ज नहीं की।"$json$::jsonb),
  ('hi', 'usage.quota.copilotUnreported', $json$"Copilot CLI इंटरैक्टिव मोड के बाहर प्लान का बैलेंस नहीं बताता। JayV से इस्तेमाल हुए प्रीमियम अनुरोध ऊपर गिने गए हैं।"$json$::jsonb),
  ('hi', 'usage.window.session', $json$"5 घंटे का सत्र"$json$::jsonb),
  ('hi', 'usage.window.week', $json$"सप्ताह"$json$::jsonb),
  ('hi', 'usage.window.weekOf', $json$"सप्ताह ({name})"$json$::jsonb),
  ('hi', 'usage.window.month', $json$"महीना"$json$::jsonb),
  ('hi', 'usage.window.day', $json$"आज की कॉल"$json$::jsonb),
  ('hi', 'usage.chart.daily', $json$"प्रति दिन टोकन"$json$::jsonb),
  ('hi', 'usage.chart.models', $json$"प्रति मॉडल टोकन"$json$::jsonb),
  ('hi', 'usage.jev.title', $json$"Jev ने कैसा काम किया"$json$::jsonb),
  ('hi', 'usage.jev.work', $json$"उसने क्या किया"$json$::jsonb),
  ('hi', 'usage.jev.work.entryPass', $json$"आगे भेजे गए अनुरोध"$json$::jsonb),
  ('hi', 'usage.jev.work.entryAsk', $json$"सवालों के साथ लौटाए गए अनुरोध"$json$::jsonb),
  ('hi', 'usage.jev.work.entryBlock', $json$"रोके गए अनुरोध"$json$::jsonb),
  ('hi', 'usage.jev.work.exitCleared', $json$"जवाब की स्वीकृत कार्रवाइयाँ"$json$::jsonb),
  ('hi', 'usage.jev.work.exitHeld', $json$"जवाब की रोकी गई कार्रवाइयाँ"$json$::jsonb),
  ('hi', 'usage.jev.work.cacheHit', $json$"संदर्भ कैश हिट"$json$::jsonb),
  ('hi', 'usage.jev.work.cacheMiss', $json$"संदर्भ कैश मिस"$json$::jsonb),
  ('hi', 'usage.jev.work.secretRedacted', $json$"छिपाए गए गोपनीय मान"$json$::jsonb),
  ('hi', 'usage.jev.work.fileWithheld', $json$"रोकी गई फ़ाइलें"$json$::jsonb),
  ('hi', 'usage.jev.cost', $json$"उसकी लागत"$json$::jsonb),
  ('hi', 'usage.jev.cost.value', $json$"{calls} कॉल · {input} इनपुट · {output} आउटपुट · {time}"$json$::jsonb),
  ('hi', 'usage.jev.stage.entry', $json$"Jev · प्रवेश जाँच"$json$::jsonb),
  ('hi', 'usage.jev.stage.routing', $json$"Jev · रूटिंग"$json$::jsonb),
  ('hi', 'usage.jev.stage.verification', $json$"Jev · सत्यापन"$json$::jsonb),
  ('hi', 'usage.jev.stage.asking', $json$"Jev · सवाल"$json$::jsonb),
  ('hi', 'usage.jev.saved', $json$"उसने क्या बचाया (अनुमानित)"$json$::jsonb),
  ('hi', 'usage.jev.saved.hint', $json$"अनुमान, जो असली आँकड़ों में कभी नहीं जुड़ते: रोका गया अनुरोध उसके अपने आकार और एक औसत जवाब के बराबर है; छोटा किया गया संदर्भ वह है जो बजट ने काटा।"$json$::jsonb),
  ('hi', 'usage.jev.saved.blocked', $json$"रोके गए अनुरोध"$json$::jsonb),
  ('hi', 'usage.jev.saved.context', $json$"छोटा किया गया संदर्भ"$json$::jsonb),
  ('hi', 'usage.jev.saved.total', $json$"कुल बचत"$json$::jsonb),
  ('hi', 'usage.table.name', $json$"नाम"$json$::jsonb),
  ('hi', 'usage.table.bySource', $json$"एजेंट के अनुसार"$json$::jsonb),
  ('hi', 'usage.table.byModel', $json$"मॉडल के अनुसार"$json$::jsonb),
  ('hi', 'usage.table.byProject', $json$"प्रोजेक्ट के अनुसार"$json$::jsonb),
  ('hi', 'usage.table.byChat', $json$"चैट के अनुसार"$json$::jsonb),
  ('hi', 'usage.chat.open', $json$"इस चैट के आँकड़े खोलें"$json$::jsonb),
  ('hi', 'usage.chat.tokens', $json$"यह चैट: {input} इनपुट · {output} आउटपुट"$json$::jsonb),
  ('hi', 'usage.chat.blocked', $json${"one": "Jev ने {count} रोका", "other": "Jev ने {count} रोके"}$json$::jsonb),
  ('hi', 'usage.project.month', $json$"पिछले 30 दिन: {tokens} टोकन"$json$::jsonb),
  ('hi', 'usage.turn.tokens', $json$"{input} इनपुट · {output} आउटपुट"$json$::jsonb),
  ('ar', 'nav.stats', $json$"الإحصاءات"$json$::jsonb),
  ('ar', 'usage.loading', $json$"جارٍ جمع الاستخدام…"$json$::jsonb),
  ('ar', 'usage.empty', $json$"لم يُسجَّل شيء في هذه الفترة بعد."$json$::jsonb),
  ('ar', 'usage.scope.project', $json$"المشروع"$json$::jsonb),
  ('ar', 'usage.scope.chat', $json$"المحادثة"$json$::jsonb),
  ('ar', 'usage.scope.global', $json$"الكل"$json$::jsonb),
  ('ar', 'usage.scope.allChats', $json$"كل المحادثات"$json$::jsonb),
  ('ar', 'usage.chat.removed', $json$"(محادثة محذوفة)"$json$::jsonb),
  ('ar', 'usage.project.removed', $json$"(مشروع محذوف)"$json$::jsonb),
  ('ar', 'usage.period', $json$"الفترة"$json$::jsonb),
  ('ar', 'usage.period.today', $json$"اليوم"$json$::jsonb),
  ('ar', 'usage.period.7d', $json$"آخر 7 أيام"$json$::jsonb),
  ('ar', 'usage.period.30d', $json$"آخر 30 يومًا"$json$::jsonb),
  ('ar', 'usage.period.all', $json$"منذ البداية"$json$::jsonb),
  ('ar', 'usage.period.custom', $json$"نطاق مخصص"$json$::jsonb),
  ('ar', 'usage.period.from', $json$"من"$json$::jsonb),
  ('ar', 'usage.period.to', $json$"إلى"$json$::jsonb),
  ('ar', 'usage.estimated.share', $json$"{share} من هذه الرموز تقديرية: لم تُبلغ عنها الأداة."$json$::jsonb),
  ('ar', 'usage.estimated.hint', $json$"التقديري يعني أن التطبيق عدّ الأحرف ÷ 4 لأن الأداة لم تُبلغ عن استخدامها. الأدوار السابقة لهذا الإصدار تقديرية أيضًا."$json$::jsonb),
  ('ar', 'usage.input', $json$"رموز الإدخال"$json$::jsonb),
  ('ar', 'usage.output', $json$"رموز الإخراج"$json$::jsonb),
  ('ar', 'usage.cache', $json$"الذاكرة المؤقتة: قراءة / كتابة"$json$::jsonb),
  ('ar', 'usage.cache.hint', $json$"رموز الإدخال المقدَّمة من ذاكرة الموجّهات المؤقتة لدى المزوّد، والرموز المكتوبة فيها."$json$::jsonb),
  ('ar', 'usage.cache.read', $json$"قراءة من الذاكرة المؤقتة"$json$::jsonb),
  ('ar', 'usage.cost', $json$"التكلفة المُبلَّغ عنها"$json$::jsonb),
  ('ar', 'usage.cost.hint', $json$"ما تُبلغ عنه الأدوات فقط. يُبلغ Claude Code عمّا كانت ستحتسبه الواجهة البرمجية حتى مع الاشتراك. تعني «—» أن أي أداة لم تُبلغ عن تكلفة."$json$::jsonb),
  ('ar', 'usage.requests', $json$"الطلبات المميزة"$json$::jsonb),
  ('ar', 'usage.turns', $json$"الأدوار"$json$::jsonb),
  ('ar', 'usage.calls', $json$"استدعاءات النماذج"$json$::jsonb),
  ('ar', 'usage.success', $json$"معدل النجاح"$json$::jsonb),
  ('ar', 'usage.duration', $json$"الوقت المستغرق"$json$::jsonb),
  ('ar', 'usage.quota.title', $json$"حدود الخطة"$json$::jsonb),
  ('ar', 'usage.quota.description', $json$"مقدار ما استُخدم من كل نافذة في الخطة. هذه الحدود للحساب كله: تشمل الاستخدام خارج JayV وعلى أجهزة أخرى."$json$::jsonb),
  ('ar', 'usage.quota.none', $json$"لم يُقرأ أي حد للخطة بعد."$json$::jsonb),
  ('ar', 'usage.quota.refresh', $json$"قراءة حدود الخطة"$json$::jsonb),
  ('ar', 'usage.quota.refreshing', $json$"جارٍ قراءة الحدود…"$json$::jsonb),
  ('ar', 'usage.quota.readAt', $json$"قُرئ في {date}"$json$::jsonb),
  ('ar', 'usage.quota.resets', $json$"يُعاد التعيين {when}"$json$::jsonb),
  ('ar', 'usage.quota.notInstalled', $json$"لم يُعثر على {agent} في هذا الحاسوب."$json$::jsonb),
  ('ar', 'usage.quota.silent', $json$"لم يردّ {agent} على ‎/usage في الوقت المحدد."$json$::jsonb),
  ('ar', 'usage.quota.unreadable', $json$"ردّ {agent} على ‎/usage بصيغة لا يستطيع هذا الإصدار قراءتها."$json$::jsonb),
  ('ar', 'usage.quota.noData', $json$"لم يسجّل {agent} أي حد للخطة على هذا الحاسوب بعد."$json$::jsonb),
  ('ar', 'usage.quota.copilotUnreported', $json$"لا يُبلغ Copilot CLI عن رصيد الخطة خارج الوضع التفاعلي. الطلبات المميزة المستخدمة عبر JayV محسوبة أعلاه."$json$::jsonb),
  ('ar', 'usage.window.session', $json$"جلسة 5 ساعات"$json$::jsonb),
  ('ar', 'usage.window.week', $json$"الأسبوع"$json$::jsonb),
  ('ar', 'usage.window.weekOf', $json$"الأسبوع ({name})"$json$::jsonb),
  ('ar', 'usage.window.month', $json$"الشهر"$json$::jsonb),
  ('ar', 'usage.window.day', $json$"استدعاءات اليوم"$json$::jsonb),
  ('ar', 'usage.chart.daily', $json$"الرموز يوميًا"$json$::jsonb),
  ('ar', 'usage.chart.models', $json$"الرموز لكل نموذج"$json$::jsonb),
  ('ar', 'usage.jev.title', $json$"أداء Jev"$json$::jsonb),
  ('ar', 'usage.jev.work', $json$"ما فعله"$json$::jsonb),
  ('ar', 'usage.jev.work.entryPass', $json$"طلبات سُمح بمرورها"$json$::jsonb),
  ('ar', 'usage.jev.work.entryAsk', $json$"طلبات أُعيدت مع أسئلة"$json$::jsonb),
  ('ar', 'usage.jev.work.entryBlock', $json$"طلبات محظورة"$json$::jsonb),
  ('ar', 'usage.jev.work.exitCleared', $json$"إجراءات رد مسموح بها"$json$::jsonb),
  ('ar', 'usage.jev.work.exitHeld', $json$"إجراءات رد محتجزة"$json$::jsonb),
  ('ar', 'usage.jev.work.cacheHit', $json$"إصابات ذاكرة السياق المؤقتة"$json$::jsonb),
  ('ar', 'usage.jev.work.cacheMiss', $json$"إخفاقات ذاكرة السياق المؤقتة"$json$::jsonb),
  ('ar', 'usage.jev.work.secretRedacted', $json$"أسرار محجوبة"$json$::jsonb),
  ('ar', 'usage.jev.work.fileWithheld', $json$"ملفات محجوزة"$json$::jsonb),
  ('ar', 'usage.jev.cost', $json$"ما كلّفه"$json$::jsonb),
  ('ar', 'usage.jev.cost.value', $json$"{calls} استدعاء · {input} إدخال · {output} إخراج · {time}"$json$::jsonb),
  ('ar', 'usage.jev.stage.entry', $json$"Jev · فحص الدخول"$json$::jsonb),
  ('ar', 'usage.jev.stage.routing', $json$"Jev · التوجيه"$json$::jsonb),
  ('ar', 'usage.jev.stage.verification', $json$"Jev · التحقق"$json$::jsonb),
  ('ar', 'usage.jev.stage.asking', $json$"Jev · الأسئلة"$json$::jsonb),
  ('ar', 'usage.jev.saved', $json$"ما وفّره (تقديري)"$json$::jsonb),
  ('ar', 'usage.jev.saved.hint', $json$"تقديرات لا تُضاف أبدًا إلى الأرقام الحقيقية: الطلب المحظور يساوي حجمه مع رد متوسط؛ والسياق المختصر هو ما قطعته الميزانية."$json$::jsonb),
  ('ar', 'usage.jev.saved.blocked', $json$"طلبات محظورة"$json$::jsonb),
  ('ar', 'usage.jev.saved.context', $json$"سياق مختصر"$json$::jsonb),
  ('ar', 'usage.jev.saved.total', $json$"إجمالي التوفير"$json$::jsonb),
  ('ar', 'usage.table.name', $json$"الاسم"$json$::jsonb),
  ('ar', 'usage.table.bySource', $json$"حسب الوكيل"$json$::jsonb),
  ('ar', 'usage.table.byModel', $json$"حسب النموذج"$json$::jsonb),
  ('ar', 'usage.table.byProject', $json$"حسب المشروع"$json$::jsonb),
  ('ar', 'usage.table.byChat', $json$"حسب المحادثة"$json$::jsonb),
  ('ar', 'usage.chat.open', $json$"فتح إحصاءات هذه المحادثة"$json$::jsonb),
  ('ar', 'usage.chat.tokens', $json$"هذه المحادثة: {input} إدخال · {output} إخراج"$json$::jsonb),
  ('ar', 'usage.chat.blocked', $json${"zero": "لم يحظر Jev شيئًا", "one": "حظر Jev طلبًا واحدًا", "two": "حظر Jev طلبين", "few": "حظر Jev {count} طلبات", "many": "حظر Jev {count} طلبًا", "other": "حظر Jev {count} طلب"}$json$::jsonb),
  ('ar', 'usage.project.month', $json$"آخر 30 يومًا: {tokens} رمز"$json$::jsonb),
  ('ar', 'usage.turn.tokens', $json$"{input} إدخال · {output} إخراج"$json$::jsonb),
  ('fr', 'nav.stats', $json$"Statistiques"$json$::jsonb),
  ('fr', 'usage.loading', $json$"Calcul de l’utilisation…"$json$::jsonb),
  ('fr', 'usage.empty', $json$"Rien d’enregistré sur cette période pour l’instant."$json$::jsonb),
  ('fr', 'usage.scope.project', $json$"Projet"$json$::jsonb),
  ('fr', 'usage.scope.chat', $json$"Discussion"$json$::jsonb),
  ('fr', 'usage.scope.global', $json$"Tout"$json$::jsonb),
  ('fr', 'usage.scope.allChats', $json$"Toutes les discussions"$json$::jsonb),
  ('fr', 'usage.chat.removed', $json$"(discussion supprimée)"$json$::jsonb),
  ('fr', 'usage.project.removed', $json$"(projet supprimé)"$json$::jsonb),
  ('fr', 'usage.period', $json$"Période"$json$::jsonb),
  ('fr', 'usage.period.today', $json$"Aujourd’hui"$json$::jsonb),
  ('fr', 'usage.period.7d', $json$"7 derniers jours"$json$::jsonb),
  ('fr', 'usage.period.30d', $json$"30 derniers jours"$json$::jsonb),
  ('fr', 'usage.period.all', $json$"Depuis le début"$json$::jsonb),
  ('fr', 'usage.period.custom', $json$"Plage personnalisée"$json$::jsonb),
  ('fr', 'usage.period.from', $json$"Du"$json$::jsonb),
  ('fr', 'usage.period.to', $json$"Au"$json$::jsonb),
  ('fr', 'usage.estimated.share', $json$"{share} de ces tokens sont estimés : l’outil ne les a pas indiqués."$json$::jsonb),
  ('fr', 'usage.estimated.hint', $json$"Estimé signifie que l’app a compté les caractères ÷ 4 parce que l’outil n’a pas indiqué sa propre utilisation. Les tours antérieurs à cette version sont aussi estimés."$json$::jsonb),
  ('fr', 'usage.input', $json$"Tokens en entrée"$json$::jsonb),
  ('fr', 'usage.output', $json$"Tokens en sortie"$json$::jsonb),
  ('fr', 'usage.cache', $json$"Cache lu / écrit"$json$::jsonb),
  ('fr', 'usage.cache.hint', $json$"Tokens d’entrée servis par le cache de prompts du fournisseur, et tokens écrits dedans."$json$::jsonb),
  ('fr', 'usage.cache.read', $json$"Cache lu"$json$::jsonb),
  ('fr', 'usage.cost', $json$"Coût indiqué"$json$::jsonb),
  ('fr', 'usage.cost.hint', $json$"Uniquement ce que les outils indiquent. Claude Code indique ce que facturerait l’API, même avec un abonnement. « — » signifie qu’aucun outil n’a indiqué de coût."$json$::jsonb),
  ('fr', 'usage.requests', $json$"Requêtes premium"$json$::jsonb),
  ('fr', 'usage.turns', $json$"Tours"$json$::jsonb),
  ('fr', 'usage.calls', $json$"Appels aux modèles"$json$::jsonb),
  ('fr', 'usage.success', $json$"Taux de réussite"$json$::jsonb),
  ('fr', 'usage.duration', $json$"Temps passé"$json$::jsonb),
  ('fr', 'usage.quota.title', $json$"Limites du forfait"$json$::jsonb),
  ('fr', 'usage.quota.description', $json$"La part utilisée de chaque fenêtre du forfait. Elles valent pour tout le compte : elles incluent l’usage hors de JayV et sur d’autres appareils."$json$::jsonb),
  ('fr', 'usage.quota.none', $json$"Aucune limite de forfait lue pour l’instant."$json$::jsonb),
  ('fr', 'usage.quota.refresh', $json$"Lire les limites du forfait"$json$::jsonb),
  ('fr', 'usage.quota.refreshing', $json$"Lecture des limites…"$json$::jsonb),
  ('fr', 'usage.quota.readAt', $json$"Lu le {date}"$json$::jsonb),
  ('fr', 'usage.quota.resets', $json$"Se renouvelle {when}"$json$::jsonb),
  ('fr', 'usage.quota.notInstalled', $json$"{agent} est introuvable sur cet ordinateur."$json$::jsonb),
  ('fr', 'usage.quota.silent', $json$"{agent} n’a pas répondu à /usage à temps."$json$::jsonb),
  ('fr', 'usage.quota.unreadable', $json$"{agent} a répondu à /usage dans un format que cette version ne sait pas lire."$json$::jsonb),
  ('fr', 'usage.quota.noData', $json$"{agent} n’a encore enregistré aucune limite de forfait sur cet ordinateur."$json$::jsonb),
  ('fr', 'usage.quota.copilotUnreported', $json$"Copilot CLI n’indique pas le solde du forfait hors du mode interactif. Les requêtes premium utilisées via JayV sont comptées ci-dessus."$json$::jsonb),
  ('fr', 'usage.window.session', $json$"Session de 5 heures"$json$::jsonb),
  ('fr', 'usage.window.week', $json$"Semaine"$json$::jsonb),
  ('fr', 'usage.window.weekOf', $json$"Semaine ({name})"$json$::jsonb),
  ('fr', 'usage.window.month', $json$"Mois"$json$::jsonb),
  ('fr', 'usage.window.day', $json$"Appels du jour"$json$::jsonb),
  ('fr', 'usage.chart.daily', $json$"Tokens par jour"$json$::jsonb),
  ('fr', 'usage.chart.models', $json$"Tokens par modèle"$json$::jsonb),
  ('fr', 'usage.jev.title', $json$"Les performances de Jev"$json$::jsonb),
  ('fr', 'usage.jev.work', $json$"Ce qu’il a fait"$json$::jsonb),
  ('fr', 'usage.jev.work.entryPass', $json$"Demandes acceptées"$json$::jsonb),
  ('fr', 'usage.jev.work.entryAsk', $json$"Demandes renvoyées avec des questions"$json$::jsonb),
  ('fr', 'usage.jev.work.entryBlock', $json$"Demandes bloquées"$json$::jsonb),
  ('fr', 'usage.jev.work.exitCleared', $json$"Actions de réponse autorisées"$json$::jsonb),
  ('fr', 'usage.jev.work.exitHeld', $json$"Actions de réponse retenues"$json$::jsonb),
  ('fr', 'usage.jev.work.cacheHit', $json$"Succès du cache de contexte"$json$::jsonb),
  ('fr', 'usage.jev.work.cacheMiss', $json$"Échecs du cache de contexte"$json$::jsonb),
  ('fr', 'usage.jev.work.secretRedacted', $json$"Secrets masqués"$json$::jsonb),
  ('fr', 'usage.jev.work.fileWithheld', $json$"Fichiers retenus"$json$::jsonb),
  ('fr', 'usage.jev.cost', $json$"Ce qu’il a coûté"$json$::jsonb),
  ('fr', 'usage.jev.cost.value', $json$"{calls} appels · {input} entrée · {output} sortie · {time}"$json$::jsonb),
  ('fr', 'usage.jev.stage.entry', $json$"Jev · contrôle d’entrée"$json$::jsonb),
  ('fr', 'usage.jev.stage.routing', $json$"Jev · routage"$json$::jsonb),
  ('fr', 'usage.jev.stage.verification', $json$"Jev · vérification"$json$::jsonb),
  ('fr', 'usage.jev.stage.asking', $json$"Jev · questions"$json$::jsonb),
  ('fr', 'usage.jev.saved', $json$"Ce qu’il a économisé (estimé)"$json$::jsonb),
  ('fr', 'usage.jev.saved.hint', $json$"Des estimations, jamais ajoutées aux chiffres réels : une demande bloquée vaut sa propre taille plus une réponse moyenne ; le contexte réduit est ce que le budget a coupé."$json$::jsonb),
  ('fr', 'usage.jev.saved.blocked', $json$"Demandes bloquées"$json$::jsonb),
  ('fr', 'usage.jev.saved.context', $json$"Contexte réduit"$json$::jsonb),
  ('fr', 'usage.jev.saved.total', $json$"Total économisé"$json$::jsonb),
  ('fr', 'usage.table.name', $json$"Nom"$json$::jsonb),
  ('fr', 'usage.table.bySource', $json$"Par agent"$json$::jsonb),
  ('fr', 'usage.table.byModel', $json$"Par modèle"$json$::jsonb),
  ('fr', 'usage.table.byProject', $json$"Par projet"$json$::jsonb),
  ('fr', 'usage.table.byChat', $json$"Par discussion"$json$::jsonb),
  ('fr', 'usage.chat.open', $json$"Ouvrir les statistiques de cette discussion"$json$::jsonb),
  ('fr', 'usage.chat.tokens', $json$"Cette discussion : {input} entrée · {output} sortie"$json$::jsonb),
  ('fr', 'usage.chat.blocked', $json${"one": "Jev a bloqué {count}", "other": "Jev a bloqué {count}"}$json$::jsonb),
  ('fr', 'usage.project.month', $json$"30 derniers jours : {tokens} tokens"$json$::jsonb),
  ('fr', 'usage.turn.tokens', $json$"{input} entrée · {output} sortie"$json$::jsonb),
  ('ru', 'nav.stats', $json$"Статистика"$json$::jsonb),
  ('ru', 'usage.loading', $json$"Подсчитываем использование…"$json$::jsonb),
  ('ru', 'usage.empty', $json$"За этот период пока ничего не записано."$json$::jsonb),
  ('ru', 'usage.scope.project', $json$"Проект"$json$::jsonb),
  ('ru', 'usage.scope.chat', $json$"Чат"$json$::jsonb),
  ('ru', 'usage.scope.global', $json$"Всё"$json$::jsonb),
  ('ru', 'usage.scope.allChats', $json$"Все чаты"$json$::jsonb),
  ('ru', 'usage.chat.removed', $json$"(чат удалён)"$json$::jsonb),
  ('ru', 'usage.project.removed', $json$"(проект удалён)"$json$::jsonb),
  ('ru', 'usage.period', $json$"Период"$json$::jsonb),
  ('ru', 'usage.period.today', $json$"Сегодня"$json$::jsonb),
  ('ru', 'usage.period.7d', $json$"Последние 7 дней"$json$::jsonb),
  ('ru', 'usage.period.30d', $json$"Последние 30 дней"$json$::jsonb),
  ('ru', 'usage.period.all', $json$"За всё время"$json$::jsonb),
  ('ru', 'usage.period.custom', $json$"Свой диапазон"$json$::jsonb),
  ('ru', 'usage.period.from', $json$"С"$json$::jsonb),
  ('ru', 'usage.period.to', $json$"По"$json$::jsonb),
  ('ru', 'usage.estimated.share', $json$"{share} этих токенов — оценка: инструмент их не сообщил."$json$::jsonb),
  ('ru', 'usage.estimated.hint', $json$"Оценка означает, что приложение посчитало символы ÷ 4, потому что инструмент не сообщил своё использование. Ходы до этой версии тоже оценочные."$json$::jsonb),
  ('ru', 'usage.input', $json$"Входные токены"$json$::jsonb),
  ('ru', 'usage.output', $json$"Выходные токены"$json$::jsonb),
  ('ru', 'usage.cache', $json$"Кэш: чтение / запись"$json$::jsonb),
  ('ru', 'usage.cache.hint', $json$"Входные токены из кэша промптов провайдера и токены, записанные в него."$json$::jsonb),
  ('ru', 'usage.cache.read', $json$"Чтение из кэша"$json$::jsonb),
  ('ru', 'usage.cost', $json$"Сообщённая стоимость"$json$::jsonb),
  ('ru', 'usage.cost.hint', $json$"Только то, что сообщают инструменты. Claude Code сообщает, сколько взяла бы API, даже по подписке. «—» означает, что ни один инструмент не сообщил стоимость."$json$::jsonb),
  ('ru', 'usage.requests', $json$"Премиум-запросы"$json$::jsonb),
  ('ru', 'usage.turns', $json$"Ходы"$json$::jsonb),
  ('ru', 'usage.calls', $json$"Вызовы моделей"$json$::jsonb),
  ('ru', 'usage.success', $json$"Доля успешных"$json$::jsonb),
  ('ru', 'usage.duration', $json$"Затраченное время"$json$::jsonb),
  ('ru', 'usage.quota.title', $json$"Лимиты тарифа"$json$::jsonb),
  ('ru', 'usage.quota.description', $json$"Сколько использовано в каждом окне тарифа. Лимиты общие для аккаунта: включают использование вне JayV и на других устройствах."$json$::jsonb),
  ('ru', 'usage.quota.none', $json$"Лимиты тарифа ещё не прочитаны."$json$::jsonb),
  ('ru', 'usage.quota.refresh', $json$"Прочитать лимиты тарифа"$json$::jsonb),
  ('ru', 'usage.quota.refreshing', $json$"Читаем лимиты…"$json$::jsonb),
  ('ru', 'usage.quota.readAt', $json$"Прочитано {date}"$json$::jsonb),
  ('ru', 'usage.quota.resets', $json$"Обновится {when}"$json$::jsonb),
  ('ru', 'usage.quota.notInstalled', $json$"{agent} не найден на этом компьютере."$json$::jsonb),
  ('ru', 'usage.quota.silent', $json$"{agent} не ответил на /usage вовремя."$json$::jsonb),
  ('ru', 'usage.quota.unreadable', $json$"{agent} ответил на /usage в формате, который эта версия не умеет читать."$json$::jsonb),
  ('ru', 'usage.quota.noData', $json$"{agent} пока не записал лимит тарифа на этом компьютере."$json$::jsonb),
  ('ru', 'usage.quota.copilotUnreported', $json$"Copilot CLI не сообщает остаток по тарифу вне интерактивного режима. Премиум-запросы через JayV учтены выше."$json$::jsonb),
  ('ru', 'usage.window.session', $json$"Сессия на 5 часов"$json$::jsonb),
  ('ru', 'usage.window.week', $json$"Неделя"$json$::jsonb),
  ('ru', 'usage.window.weekOf', $json$"Неделя ({name})"$json$::jsonb),
  ('ru', 'usage.window.month', $json$"Месяц"$json$::jsonb),
  ('ru', 'usage.window.day', $json$"Вызовы за сегодня"$json$::jsonb),
  ('ru', 'usage.chart.daily', $json$"Токены по дням"$json$::jsonb),
  ('ru', 'usage.chart.models', $json$"Токены по моделям"$json$::jsonb),
  ('ru', 'usage.jev.title', $json$"Как поработал Jev"$json$::jsonb),
  ('ru', 'usage.jev.work', $json$"Что он сделал"$json$::jsonb),
  ('ru', 'usage.jev.work.entryPass', $json$"Пропущенные запросы"$json$::jsonb),
  ('ru', 'usage.jev.work.entryAsk', $json$"Запросы, возвращённые с вопросами"$json$::jsonb),
  ('ru', 'usage.jev.work.entryBlock', $json$"Заблокированные запросы"$json$::jsonb),
  ('ru', 'usage.jev.work.exitCleared', $json$"Разрешённые действия из ответа"$json$::jsonb),
  ('ru', 'usage.jev.work.exitHeld', $json$"Задержанные действия из ответа"$json$::jsonb),
  ('ru', 'usage.jev.work.cacheHit', $json$"Попадания в кэш контекста"$json$::jsonb),
  ('ru', 'usage.jev.work.cacheMiss', $json$"Промахи кэша контекста"$json$::jsonb),
  ('ru', 'usage.jev.work.secretRedacted', $json$"Скрытые секреты"$json$::jsonb),
  ('ru', 'usage.jev.work.fileWithheld', $json$"Удержанные файлы"$json$::jsonb),
  ('ru', 'usage.jev.cost', $json$"Во что он обошёлся"$json$::jsonb),
  ('ru', 'usage.jev.cost.value', $json$"вызовов: {calls} · {input} вход · {output} выход · {time}"$json$::jsonb),
  ('ru', 'usage.jev.stage.entry', $json$"Jev · проверка на входе"$json$::jsonb),
  ('ru', 'usage.jev.stage.routing', $json$"Jev · маршрутизация"$json$::jsonb),
  ('ru', 'usage.jev.stage.verification', $json$"Jev · проверка ответа"$json$::jsonb),
  ('ru', 'usage.jev.stage.asking', $json$"Jev · вопросы"$json$::jsonb),
  ('ru', 'usage.jev.saved', $json$"Что он сэкономил (оценка)"$json$::jsonb),
  ('ru', 'usage.jev.saved.hint', $json$"Оценки, которые никогда не складываются с реальными цифрами: заблокированный запрос — это его размер плюс средний ответ; сокращённый контекст — то, что обрезал бюджет."$json$::jsonb),
  ('ru', 'usage.jev.saved.blocked', $json$"Заблокированные запросы"$json$::jsonb),
  ('ru', 'usage.jev.saved.context', $json$"Сокращённый контекст"$json$::jsonb),
  ('ru', 'usage.jev.saved.total', $json$"Всего сэкономлено"$json$::jsonb),
  ('ru', 'usage.table.name', $json$"Название"$json$::jsonb),
  ('ru', 'usage.table.bySource', $json$"По агентам"$json$::jsonb),
  ('ru', 'usage.table.byModel', $json$"По моделям"$json$::jsonb),
  ('ru', 'usage.table.byProject', $json$"По проектам"$json$::jsonb),
  ('ru', 'usage.table.byChat', $json$"По чатам"$json$::jsonb),
  ('ru', 'usage.chat.open', $json$"Открыть статистику этого чата"$json$::jsonb),
  ('ru', 'usage.chat.tokens', $json$"Этот чат: {input} вход · {output} выход"$json$::jsonb),
  ('ru', 'usage.chat.blocked', $json${"one": "Jev заблокировал {count}", "few": "Jev заблокировал {count}", "many": "Jev заблокировал {count}", "other": "Jev заблокировал {count}"}$json$::jsonb),
  ('ru', 'usage.project.month', $json$"Последние 30 дней: {tokens} токенов"$json$::jsonb),
  ('ru', 'usage.turn.tokens', $json$"{input} вход · {output} выход"$json$::jsonb),
  ('ja', 'nav.stats', $json$"統計"$json$::jsonb),
  ('ja', 'usage.loading', $json$"使用量を集計しています…"$json$::jsonb),
  ('ja', 'usage.empty', $json$"この期間の記録はまだありません。"$json$::jsonb),
  ('ja', 'usage.scope.project', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'usage.scope.chat', $json$"チャット"$json$::jsonb),
  ('ja', 'usage.scope.global', $json$"すべて"$json$::jsonb),
  ('ja', 'usage.scope.allChats', $json$"すべてのチャット"$json$::jsonb),
  ('ja', 'usage.chat.removed', $json$"(削除されたチャット)"$json$::jsonb),
  ('ja', 'usage.project.removed', $json$"(削除されたプロジェクト)"$json$::jsonb),
  ('ja', 'usage.period', $json$"期間"$json$::jsonb),
  ('ja', 'usage.period.today', $json$"今日"$json$::jsonb),
  ('ja', 'usage.period.7d', $json$"過去 7 日間"$json$::jsonb),
  ('ja', 'usage.period.30d', $json$"過去 30 日間"$json$::jsonb),
  ('ja', 'usage.period.all', $json$"全期間"$json$::jsonb),
  ('ja', 'usage.period.custom', $json$"カスタム期間"$json$::jsonb),
  ('ja', 'usage.period.from', $json$"開始"$json$::jsonb),
  ('ja', 'usage.period.to', $json$"終了"$json$::jsonb),
  ('ja', 'usage.estimated.share', $json$"これらのトークンのうち {share} は推定値です。ツールが報告しませんでした。"$json$::jsonb),
  ('ja', 'usage.estimated.hint', $json$"推定値とは、ツールが自身の使用量を報告しなかったため、アプリが文字数 ÷ 4 で数えたものです。このバージョンより前のターンも推定値です。"$json$::jsonb),
  ('ja', 'usage.input', $json$"入力トークン"$json$::jsonb),
  ('ja', 'usage.output', $json$"出力トークン"$json$::jsonb),
  ('ja', 'usage.cache', $json$"キャッシュ 読み取り / 書き込み"$json$::jsonb),
  ('ja', 'usage.cache.hint', $json$"プロバイダーのプロンプトキャッシュから提供された入力トークンと、キャッシュに書き込まれたトークン。"$json$::jsonb),
  ('ja', 'usage.cache.read', $json$"キャッシュ読み取り"$json$::jsonb),
  ('ja', 'usage.cost', $json$"報告されたコスト"$json$::jsonb),
  ('ja', 'usage.cost.hint', $json$"ツールが報告した分のみです。Claude Code はサブスクリプションでも API で請求される額を報告します。「—」はどのツールもコストを報告しなかったことを示します。"$json$::jsonb),
  ('ja', 'usage.requests', $json$"プレミアムリクエスト"$json$::jsonb),
  ('ja', 'usage.turns', $json$"ターン"$json$::jsonb),
  ('ja', 'usage.calls', $json$"モデル呼び出し"$json$::jsonb),
  ('ja', 'usage.success', $json$"成功率"$json$::jsonb),
  ('ja', 'usage.duration', $json$"所要時間"$json$::jsonb),
  ('ja', 'usage.quota.title', $json$"プランの上限"$json$::jsonb),
  ('ja', 'usage.quota.description', $json$"プランの各期間でどれだけ使ったか。アカウント全体の値で、JayV 以外や他のデバイスでの使用も含みます。"$json$::jsonb),
  ('ja', 'usage.quota.none', $json$"プランの上限はまだ読み取られていません。"$json$::jsonb),
  ('ja', 'usage.quota.refresh', $json$"プランの上限を読み取る"$json$::jsonb),
  ('ja', 'usage.quota.refreshing', $json$"上限を読み取っています…"$json$::jsonb),
  ('ja', 'usage.quota.readAt', $json$"{date} に読み取り"$json$::jsonb),
  ('ja', 'usage.quota.resets', $json$"{when} にリセット"$json$::jsonb),
  ('ja', 'usage.quota.notInstalled', $json$"このコンピューターに {agent} が見つかりません。"$json$::jsonb),
  ('ja', 'usage.quota.silent', $json$"{agent} が時間内に /usage に応答しませんでした。"$json$::jsonb),
  ('ja', 'usage.quota.unreadable', $json$"{agent} が、このバージョンでは読み取れない形式で /usage に応答しました。"$json$::jsonb),
  ('ja', 'usage.quota.noData', $json$"{agent} はこのコンピューターにまだプランの上限を記録していません。"$json$::jsonb),
  ('ja', 'usage.quota.copilotUnreported', $json$"Copilot CLI は対話モード以外ではプランの残量を報告しません。JayV で使ったプレミアムリクエストは上で数えています。"$json$::jsonb),
  ('ja', 'usage.window.session', $json$"5 時間セッション"$json$::jsonb),
  ('ja', 'usage.window.week', $json$"週"$json$::jsonb),
  ('ja', 'usage.window.weekOf', $json$"週 ({name})"$json$::jsonb),
  ('ja', 'usage.window.month', $json$"月"$json$::jsonb),
  ('ja', 'usage.window.day', $json$"今日の呼び出し"$json$::jsonb),
  ('ja', 'usage.chart.daily', $json$"日別トークン"$json$::jsonb),
  ('ja', 'usage.chart.models', $json$"モデル別トークン"$json$::jsonb),
  ('ja', 'usage.jev.title', $json$"Jev の働き"$json$::jsonb),
  ('ja', 'usage.jev.work', $json$"行ったこと"$json$::jsonb),
  ('ja', 'usage.jev.work.entryPass', $json$"通過したリクエスト"$json$::jsonb),
  ('ja', 'usage.jev.work.entryAsk', $json$"質問付きで差し戻したリクエスト"$json$::jsonb),
  ('ja', 'usage.jev.work.entryBlock', $json$"ブロックしたリクエスト"$json$::jsonb),
  ('ja', 'usage.jev.work.exitCleared', $json$"許可した回答内のアクション"$json$::jsonb),
  ('ja', 'usage.jev.work.exitHeld', $json$"保留した回答内のアクション"$json$::jsonb),
  ('ja', 'usage.jev.work.cacheHit', $json$"コンテキストキャッシュのヒット"$json$::jsonb),
  ('ja', 'usage.jev.work.cacheMiss', $json$"コンテキストキャッシュのミス"$json$::jsonb),
  ('ja', 'usage.jev.work.secretRedacted', $json$"伏せた秘密情報"$json$::jsonb),
  ('ja', 'usage.jev.work.fileWithheld', $json$"送らなかったファイル"$json$::jsonb),
  ('ja', 'usage.jev.cost', $json$"かかったコスト"$json$::jsonb),
  ('ja', 'usage.jev.cost.value', $json$"{calls} 回 · 入力 {input} · 出力 {output} · {time}"$json$::jsonb),
  ('ja', 'usage.jev.stage.entry', $json$"Jev · 入口チェック"$json$::jsonb),
  ('ja', 'usage.jev.stage.routing', $json$"Jev · ルーティング"$json$::jsonb),
  ('ja', 'usage.jev.stage.verification', $json$"Jev · 検証"$json$::jsonb),
  ('ja', 'usage.jev.stage.asking', $json$"Jev · 質問"$json$::jsonb),
  ('ja', 'usage.jev.saved', $json$"節約した量 (推定)"$json$::jsonb),
  ('ja', 'usage.jev.saved.hint', $json$"推定値で、実際の数値には加算しません。ブロックしたリクエストはその大きさに平均的な回答を足したもの、削ったコンテキストは予算で切り捨てた分です。"$json$::jsonb),
  ('ja', 'usage.jev.saved.blocked', $json$"ブロックしたリクエスト"$json$::jsonb),
  ('ja', 'usage.jev.saved.context', $json$"削ったコンテキスト"$json$::jsonb),
  ('ja', 'usage.jev.saved.total', $json$"節約の合計"$json$::jsonb),
  ('ja', 'usage.table.name', $json$"名前"$json$::jsonb),
  ('ja', 'usage.table.bySource', $json$"エージェント別"$json$::jsonb),
  ('ja', 'usage.table.byModel', $json$"モデル別"$json$::jsonb),
  ('ja', 'usage.table.byProject', $json$"プロジェクト別"$json$::jsonb),
  ('ja', 'usage.table.byChat', $json$"チャット別"$json$::jsonb),
  ('ja', 'usage.chat.open', $json$"このチャットの統計を開く"$json$::jsonb),
  ('ja', 'usage.chat.tokens', $json$"このチャット: 入力 {input} · 出力 {output}"$json$::jsonb),
  ('ja', 'usage.chat.blocked', $json${"other": "Jev が {count} 件ブロック"}$json$::jsonb),
  ('ja', 'usage.project.month', $json$"過去 30 日間: {tokens} トークン"$json$::jsonb),
  ('ja', 'usage.turn.tokens', $json$"入力 {input} · 出力 {output}"$json$::jsonb),
  ('de', 'nav.stats', $json$"Statistiken"$json$::jsonb),
  ('de', 'usage.loading', $json$"Nutzung wird summiert…"$json$::jsonb),
  ('de', 'usage.empty', $json$"In diesem Zeitraum ist noch nichts erfasst."$json$::jsonb),
  ('de', 'usage.scope.project', $json$"Projekt"$json$::jsonb),
  ('de', 'usage.scope.chat', $json$"Chat"$json$::jsonb),
  ('de', 'usage.scope.global', $json$"Alles"$json$::jsonb),
  ('de', 'usage.scope.allChats', $json$"Alle Chats"$json$::jsonb),
  ('de', 'usage.chat.removed', $json$"(Chat entfernt)"$json$::jsonb),
  ('de', 'usage.project.removed', $json$"(Projekt entfernt)"$json$::jsonb),
  ('de', 'usage.period', $json$"Zeitraum"$json$::jsonb),
  ('de', 'usage.period.today', $json$"Heute"$json$::jsonb),
  ('de', 'usage.period.7d', $json$"Letzte 7 Tage"$json$::jsonb),
  ('de', 'usage.period.30d', $json$"Letzte 30 Tage"$json$::jsonb),
  ('de', 'usage.period.all', $json$"Gesamter Zeitraum"$json$::jsonb),
  ('de', 'usage.period.custom', $json$"Eigener Zeitraum"$json$::jsonb),
  ('de', 'usage.period.from', $json$"Von"$json$::jsonb),
  ('de', 'usage.period.to', $json$"Bis"$json$::jsonb),
  ('de', 'usage.estimated.share', $json$"{share} dieser Tokens sind geschätzt: Das Tool hat sie nicht gemeldet."$json$::jsonb),
  ('de', 'usage.estimated.hint', $json$"Geschätzt heißt, die App hat Zeichen ÷ 4 gezählt, weil das Tool seine Nutzung nicht gemeldet hat. Turns aus der Zeit vor dieser Version sind ebenfalls geschätzt."$json$::jsonb),
  ('de', 'usage.input', $json$"Eingabe-Tokens"$json$::jsonb),
  ('de', 'usage.output', $json$"Ausgabe-Tokens"$json$::jsonb),
  ('de', 'usage.cache', $json$"Cache gelesen / geschrieben"$json$::jsonb),
  ('de', 'usage.cache.hint', $json$"Eingabe-Tokens aus dem Prompt-Cache des Anbieters und Tokens, die hineingeschrieben wurden."$json$::jsonb),
  ('de', 'usage.cache.read', $json$"Cache gelesen"$json$::jsonb),
  ('de', 'usage.cost', $json$"Gemeldete Kosten"$json$::jsonb),
  ('de', 'usage.cost.hint', $json$"Nur was die Tools melden. Claude Code meldet, was die API berechnen würde, auch im Abo. „—“ heißt, dass kein Tool Kosten gemeldet hat."$json$::jsonb),
  ('de', 'usage.requests', $json$"Premium-Anfragen"$json$::jsonb),
  ('de', 'usage.turns', $json$"Turns"$json$::jsonb),
  ('de', 'usage.calls', $json$"Modellaufrufe"$json$::jsonb),
  ('de', 'usage.success', $json$"Erfolgsquote"$json$::jsonb),
  ('de', 'usage.duration', $json$"Benötigte Zeit"$json$::jsonb),
  ('de', 'usage.quota.title', $json$"Tariflimits"$json$::jsonb),
  ('de', 'usage.quota.description', $json$"Wie viel von jedem Tarif-Zeitfenster verbraucht ist. Sie gelten für das ganze Konto: einschließlich Nutzung außerhalb von JayV und auf anderen Geräten."$json$::jsonb),
  ('de', 'usage.quota.none', $json$"Noch kein Tariflimit gelesen."$json$::jsonb),
  ('de', 'usage.quota.refresh', $json$"Tariflimits lesen"$json$::jsonb),
  ('de', 'usage.quota.refreshing', $json$"Limits werden gelesen…"$json$::jsonb),
  ('de', 'usage.quota.readAt', $json$"Gelesen {date}"$json$::jsonb),
  ('de', 'usage.quota.resets', $json$"Wird zurückgesetzt {when}"$json$::jsonb),
  ('de', 'usage.quota.notInstalled', $json$"{agent} wurde auf diesem Computer nicht gefunden."$json$::jsonb),
  ('de', 'usage.quota.silent', $json$"{agent} hat nicht rechtzeitig auf /usage geantwortet."$json$::jsonb),
  ('de', 'usage.quota.unreadable', $json$"{agent} hat auf /usage in einem Format geantwortet, das diese Version nicht lesen kann."$json$::jsonb),
  ('de', 'usage.quota.noData', $json$"{agent} hat auf diesem Computer noch kein Tariflimit gespeichert."$json$::jsonb),
  ('de', 'usage.quota.copilotUnreported', $json$"Die Copilot CLI meldet das Tarifguthaben außerhalb des interaktiven Modus nicht. Über JayV genutzte Premium-Anfragen werden oben gezählt."$json$::jsonb),
  ('de', 'usage.window.session', $json$"5-Stunden-Sitzung"$json$::jsonb),
  ('de', 'usage.window.week', $json$"Woche"$json$::jsonb),
  ('de', 'usage.window.weekOf', $json$"Woche ({name})"$json$::jsonb),
  ('de', 'usage.window.month', $json$"Monat"$json$::jsonb),
  ('de', 'usage.window.day', $json$"Heutige Aufrufe"$json$::jsonb),
  ('de', 'usage.chart.daily', $json$"Tokens pro Tag"$json$::jsonb),
  ('de', 'usage.chart.models', $json$"Tokens pro Modell"$json$::jsonb),
  ('de', 'usage.jev.title', $json$"Wie Jev abgeschnitten hat"$json$::jsonb),
  ('de', 'usage.jev.work', $json$"Was er getan hat"$json$::jsonb),
  ('de', 'usage.jev.work.entryPass', $json$"Durchgelassene Anfragen"$json$::jsonb),
  ('de', 'usage.jev.work.entryAsk', $json$"Mit Rückfragen zurückgegebene Anfragen"$json$::jsonb),
  ('de', 'usage.jev.work.entryBlock', $json$"Blockierte Anfragen"$json$::jsonb),
  ('de', 'usage.jev.work.exitCleared', $json$"Freigegebene Antwortaktionen"$json$::jsonb),
  ('de', 'usage.jev.work.exitHeld', $json$"Zurückgehaltene Antwortaktionen"$json$::jsonb),
  ('de', 'usage.jev.work.cacheHit', $json$"Treffer im Kontext-Cache"$json$::jsonb),
  ('de', 'usage.jev.work.cacheMiss', $json$"Fehlschläge im Kontext-Cache"$json$::jsonb),
  ('de', 'usage.jev.work.secretRedacted', $json$"Geschwärzte Geheimnisse"$json$::jsonb),
  ('de', 'usage.jev.work.fileWithheld', $json$"Zurückgehaltene Dateien"$json$::jsonb),
  ('de', 'usage.jev.cost', $json$"Was er gekostet hat"$json$::jsonb),
  ('de', 'usage.jev.cost.value', $json$"{calls} Aufrufe · {input} Eingabe · {output} Ausgabe · {time}"$json$::jsonb),
  ('de', 'usage.jev.stage.entry', $json$"Jev · Eingangskontrolle"$json$::jsonb),
  ('de', 'usage.jev.stage.routing', $json$"Jev · Routing"$json$::jsonb),
  ('de', 'usage.jev.stage.verification', $json$"Jev · Prüfung"$json$::jsonb),
  ('de', 'usage.jev.stage.asking', $json$"Jev · Rückfragen"$json$::jsonb),
  ('de', 'usage.jev.saved', $json$"Was er eingespart hat (geschätzt)"$json$::jsonb),
  ('de', 'usage.jev.saved.hint', $json$"Schätzungen, nie zu den echten Zahlen addiert: Eine blockierte Anfrage zählt ihre eigene Größe plus eine durchschnittliche Antwort; gekürzter Kontext ist, was das Budget abgeschnitten hat."$json$::jsonb),
  ('de', 'usage.jev.saved.blocked', $json$"Blockierte Anfragen"$json$::jsonb),
  ('de', 'usage.jev.saved.context', $json$"Gekürzter Kontext"$json$::jsonb),
  ('de', 'usage.jev.saved.total', $json$"Insgesamt eingespart"$json$::jsonb),
  ('de', 'usage.table.name', $json$"Name"$json$::jsonb),
  ('de', 'usage.table.bySource', $json$"Nach Agent"$json$::jsonb),
  ('de', 'usage.table.byModel', $json$"Nach Modell"$json$::jsonb),
  ('de', 'usage.table.byProject', $json$"Nach Projekt"$json$::jsonb),
  ('de', 'usage.table.byChat', $json$"Nach Chat"$json$::jsonb),
  ('de', 'usage.chat.open', $json$"Statistiken dieses Chats öffnen"$json$::jsonb),
  ('de', 'usage.chat.tokens', $json$"Dieser Chat: {input} Eingabe · {output} Ausgabe"$json$::jsonb),
  ('de', 'usage.chat.blocked', $json${"one": "Jev hat {count} blockiert", "other": "Jev hat {count} blockiert"}$json$::jsonb),
  ('de', 'usage.project.month', $json$"Letzte 30 Tage: {tokens} Tokens"$json$::jsonb),
  ('de', 'usage.turn.tokens', $json$"{input} Eingabe · {output} Ausgabe"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
