-- v0.83.0 (app) e v2.4.0 (site): instalar skills do skills.sh. Só textos:
-- a seção em Configurações › Skills, os erros do núcleo, o manual (que também
-- é o tutorial), o item do Novidades e a seção da aba Skills da organização.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'skills.hub.title', $json$"Instalar do skills.sh"$json$::jsonb),
  ('en', 'skills.hub.title', $json$"Install from skills.sh"$json$::jsonb),
  ('es', 'skills.hub.title', $json$"Instalar desde skills.sh"$json$::jsonb),
  ('zh-CN', 'skills.hub.title', $json$"从 skills.sh 安装"$json$::jsonb),
  ('hi', 'skills.hub.title', $json$"skills.sh से इंस्टॉल करें"$json$::jsonb),
  ('ar', 'skills.hub.title', $json$"التثبيت من skills.sh"$json$::jsonb),
  ('fr', 'skills.hub.title', $json$"Installer depuis skills.sh"$json$::jsonb),
  ('ru', 'skills.hub.title', $json$"Установить из skills.sh"$json$::jsonb),
  ('ja', 'skills.hub.title', $json$"skills.sh からインストール"$json$::jsonb),
  ('de', 'skills.hub.title', $json$"Von skills.sh installieren"$json$::jsonb),
  ('pt-BR', 'skills.hub.description', $json$"Busque no diretório aberto de skills (skills.sh) e instale uma skill com um clique. Ela vira uma skill comum neste computador: dá para desligá-la ou removê-la, e o Jev a escolhe como qualquer outra."$json$::jsonb),
  ('en', 'skills.hub.description', $json$"Search the open skills directory (skills.sh) and install a skill with one click. It becomes a regular skill on this computer: you can turn it off or remove it, and Jev picks it like any other."$json$::jsonb),
  ('es', 'skills.hub.description', $json$"Busca en el directorio abierto de skills (skills.sh) e instala una skill con un clic. Se convierte en una skill normal en este equipo: puedes desactivarla o eliminarla, y Jev la elige como cualquier otra."$json$::jsonb),
  ('zh-CN', 'skills.hub.description', $json$"在开放的技能目录（skills.sh）中搜索，一键安装技能。它会成为这台电脑上的普通技能：可以关闭或删除，Jev 会像选择其他技能一样选择它。"$json$::jsonb),
  ('hi', 'skills.hub.description', $json$"खुली स्किल डायरेक्टरी (skills.sh) में खोजें और एक क्लिक में स्किल इंस्टॉल करें। यह इस कंप्यूटर पर एक सामान्य स्किल बन जाती है: आप इसे बंद या हटा सकते हैं, और Jev इसे किसी भी अन्य की तरह चुनता है।"$json$::jsonb),
  ('ar', 'skills.hub.description', $json$"ابحث في دليل المهارات المفتوح (skills.sh) وثبّت مهارة بنقرة واحدة. تصبح مهارة عادية على هذا الكمبيوتر: يمكنك إيقافها أو إزالتها، ويختارها Jev مثل أي مهارة أخرى."$json$::jsonb),
  ('fr', 'skills.hub.description', $json$"Cherchez dans l’annuaire ouvert de skills (skills.sh) et installez une skill en un clic. Elle devient une skill ordinaire sur cet ordinateur : vous pouvez la désactiver ou la supprimer, et Jev la choisit comme les autres."$json$::jsonb),
  ('ru', 'skills.hub.description', $json$"Ищите в открытом каталоге навыков (skills.sh) и устанавливайте навык одним щелчком. Он становится обычным навыком на этом компьютере: его можно выключить или удалить, а Jev выбирает его как любой другой."$json$::jsonb),
  ('ja', 'skills.hub.description', $json$"オープンなスキルディレクトリ（skills.sh）を検索して、ワンクリックでスキルをインストールします。このコンピューター上の通常のスキルになり、オフにしたり削除したりでき、Jev は他のスキルと同じように選びます。"$json$::jsonb),
  ('de', 'skills.hub.description', $json$"Durchsuchen Sie das offene Skill-Verzeichnis (skills.sh) und installieren Sie einen Skill mit einem Klick. Er wird zu einem normalen Skill auf diesem Computer: Sie können ihn ausschalten oder entfernen, und Jev wählt ihn wie jeden anderen."$json$::jsonb),
  ('pt-BR', 'skills.hub.placeholder', $json$"Buscar skills, p. ex.: pdf, notas de versão, testes"$json$::jsonb),
  ('en', 'skills.hub.placeholder', $json$"Search skills, e.g. pdf, release notes, testing"$json$::jsonb),
  ('es', 'skills.hub.placeholder', $json$"Buscar skills, p. ej.: pdf, notas de versión, pruebas"$json$::jsonb),
  ('zh-CN', 'skills.hub.placeholder', $json$"搜索技能，例如 pdf、发布说明、测试"$json$::jsonb),
  ('hi', 'skills.hub.placeholder', $json$"स्किल खोजें, जैसे pdf, रिलीज़ नोट्स, टेस्टिंग"$json$::jsonb),
  ('ar', 'skills.hub.placeholder', $json$"ابحث عن مهارات، مثل pdf أو ملاحظات الإصدار أو الاختبار"$json$::jsonb),
  ('fr', 'skills.hub.placeholder', $json$"Rechercher des skills, p. ex. pdf, notes de version, tests"$json$::jsonb),
  ('ru', 'skills.hub.placeholder', $json$"Поиск навыков, например pdf, заметки о релизе, тесты"$json$::jsonb),
  ('ja', 'skills.hub.placeholder', $json$"スキルを検索（例: pdf、リリースノート、テスト）"$json$::jsonb),
  ('de', 'skills.hub.placeholder', $json$"Skills suchen, z. B. pdf, Release Notes, Tests"$json$::jsonb),
  ('pt-BR', 'skills.hub.search', $json$"Buscar"$json$::jsonb),
  ('en', 'skills.hub.search', $json$"Search"$json$::jsonb),
  ('es', 'skills.hub.search', $json$"Buscar"$json$::jsonb),
  ('zh-CN', 'skills.hub.search', $json$"搜索"$json$::jsonb),
  ('hi', 'skills.hub.search', $json$"खोजें"$json$::jsonb),
  ('ar', 'skills.hub.search', $json$"بحث"$json$::jsonb),
  ('fr', 'skills.hub.search', $json$"Rechercher"$json$::jsonb),
  ('ru', 'skills.hub.search', $json$"Найти"$json$::jsonb),
  ('ja', 'skills.hub.search', $json$"検索"$json$::jsonb),
  ('de', 'skills.hub.search', $json$"Suchen"$json$::jsonb),
  ('pt-BR', 'skills.hub.searching', $json$"Buscando…"$json$::jsonb),
  ('en', 'skills.hub.searching', $json$"Searching…"$json$::jsonb),
  ('es', 'skills.hub.searching', $json$"Buscando…"$json$::jsonb),
  ('zh-CN', 'skills.hub.searching', $json$"搜索中…"$json$::jsonb),
  ('hi', 'skills.hub.searching', $json$"खोज रहे हैं…"$json$::jsonb),
  ('ar', 'skills.hub.searching', $json$"جارٍ البحث…"$json$::jsonb),
  ('fr', 'skills.hub.searching', $json$"Recherche…"$json$::jsonb),
  ('ru', 'skills.hub.searching', $json$"Поиск…"$json$::jsonb),
  ('ja', 'skills.hub.searching', $json$"検索中…"$json$::jsonb),
  ('de', 'skills.hub.searching', $json$"Suche läuft…"$json$::jsonb),
  ('pt-BR', 'skills.hub.none', $json$"Nenhuma skill encontrada para essa busca."$json$::jsonb),
  ('en', 'skills.hub.none', $json$"No skill found for that search."$json$::jsonb),
  ('es', 'skills.hub.none', $json$"No se encontró ninguna skill para esa búsqueda."$json$::jsonb),
  ('zh-CN', 'skills.hub.none', $json$"没有找到符合该搜索的技能。"$json$::jsonb),
  ('hi', 'skills.hub.none', $json$"इस खोज के लिए कोई स्किल नहीं मिली।"$json$::jsonb),
  ('ar', 'skills.hub.none', $json$"لم يتم العثور على مهارة لهذا البحث."$json$::jsonb),
  ('fr', 'skills.hub.none', $json$"Aucune skill trouvée pour cette recherche."$json$::jsonb),
  ('ru', 'skills.hub.none', $json$"По этому запросу навыков не найдено."$json$::jsonb),
  ('ja', 'skills.hub.none', $json$"この検索に該当するスキルはありません。"$json$::jsonb),
  ('de', 'skills.hub.none', $json$"Für diese Suche wurde kein Skill gefunden."$json$::jsonb),
  ('pt-BR', 'skills.hub.installs', $json$"{count} instalações"$json$::jsonb),
  ('en', 'skills.hub.installs', $json$"{count} installs"$json$::jsonb),
  ('es', 'skills.hub.installs', $json$"{count} instalaciones"$json$::jsonb),
  ('zh-CN', 'skills.hub.installs', $json$"{count} 次安装"$json$::jsonb),
  ('hi', 'skills.hub.installs', $json$"{count} इंस्टॉल"$json$::jsonb),
  ('ar', 'skills.hub.installs', $json$"{count} عملية تثبيت"$json$::jsonb),
  ('fr', 'skills.hub.installs', $json$"{count} installations"$json$::jsonb),
  ('ru', 'skills.hub.installs', $json$"{count} установок"$json$::jsonb),
  ('ja', 'skills.hub.installs', $json$"{count} 件のインストール"$json$::jsonb),
  ('de', 'skills.hub.installs', $json$"{count} Installationen"$json$::jsonb),
  ('pt-BR', 'skills.hub.install', $json$"Instalar"$json$::jsonb),
  ('en', 'skills.hub.install', $json$"Install"$json$::jsonb),
  ('es', 'skills.hub.install', $json$"Instalar"$json$::jsonb),
  ('zh-CN', 'skills.hub.install', $json$"安装"$json$::jsonb),
  ('hi', 'skills.hub.install', $json$"इंस्टॉल करें"$json$::jsonb),
  ('ar', 'skills.hub.install', $json$"تثبيت"$json$::jsonb),
  ('fr', 'skills.hub.install', $json$"Installer"$json$::jsonb),
  ('ru', 'skills.hub.install', $json$"Установить"$json$::jsonb),
  ('ja', 'skills.hub.install', $json$"インストール"$json$::jsonb),
  ('de', 'skills.hub.install', $json$"Installieren"$json$::jsonb),
  ('pt-BR', 'skills.hub.reinstall', $json$"Reinstalar"$json$::jsonb),
  ('en', 'skills.hub.reinstall', $json$"Reinstall"$json$::jsonb),
  ('es', 'skills.hub.reinstall', $json$"Reinstalar"$json$::jsonb),
  ('zh-CN', 'skills.hub.reinstall', $json$"重新安装"$json$::jsonb),
  ('hi', 'skills.hub.reinstall', $json$"फिर से इंस्टॉल करें"$json$::jsonb),
  ('ar', 'skills.hub.reinstall', $json$"إعادة التثبيت"$json$::jsonb),
  ('fr', 'skills.hub.reinstall', $json$"Réinstaller"$json$::jsonb),
  ('ru', 'skills.hub.reinstall', $json$"Переустановить"$json$::jsonb),
  ('ja', 'skills.hub.reinstall', $json$"再インストール"$json$::jsonb),
  ('de', 'skills.hub.reinstall', $json$"Neu installieren"$json$::jsonb),
  ('pt-BR', 'skills.hub.installing', $json$"Instalando…"$json$::jsonb),
  ('en', 'skills.hub.installing', $json$"Installing…"$json$::jsonb),
  ('es', 'skills.hub.installing', $json$"Instalando…"$json$::jsonb),
  ('zh-CN', 'skills.hub.installing', $json$"安装中…"$json$::jsonb),
  ('hi', 'skills.hub.installing', $json$"इंस्टॉल हो रहा है…"$json$::jsonb),
  ('ar', 'skills.hub.installing', $json$"جارٍ التثبيت…"$json$::jsonb),
  ('fr', 'skills.hub.installing', $json$"Installation…"$json$::jsonb),
  ('ru', 'skills.hub.installing', $json$"Установка…"$json$::jsonb),
  ('ja', 'skills.hub.installing', $json$"インストール中…"$json$::jsonb),
  ('de', 'skills.hub.installing', $json$"Installation läuft…"$json$::jsonb),
  ('pt-BR', 'skills.hub.notes', $json$"A skill é baixada do repositório do GitHub para o qual o skills.sh aponta. Leia as instruções de uma skill antes de confiar nela: o agente vai segui-las, e os scripts dela podem rodar neste computador."$json$::jsonb),
  ('en', 'skills.hub.notes', $json$"The skill is downloaded from the GitHub repository that skills.sh points to. Read a skill’s instructions before relying on it: the agent will follow them, and its scripts can run on this computer."$json$::jsonb),
  ('es', 'skills.hub.notes', $json$"La skill se descarga del repositorio de GitHub al que apunta skills.sh. Lee las instrucciones de una skill antes de confiar en ella: el agente las seguirá y sus scripts pueden ejecutarse en este equipo."$json$::jsonb),
  ('zh-CN', 'skills.hub.notes', $json$"技能是从 skills.sh 指向的 GitHub 仓库下载的。在信任某个技能之前请先阅读它的说明：代理会遵循这些说明，它的脚本也可能在这台电脑上运行。"$json$::jsonb),
  ('hi', 'skills.hub.notes', $json$"स्किल उस GitHub रिपॉज़िटरी से डाउनलोड होती है जिसकी ओर skills.sh इशारा करता है। किसी स्किल पर भरोसा करने से पहले उसके निर्देश पढ़ें: एजेंट उनका पालन करेगा, और उसकी स्क्रिप्ट इस कंप्यूटर पर चल सकती हैं।"$json$::jsonb),
  ('ar', 'skills.hub.notes', $json$"تُنزَّل المهارة من مستودع GitHub الذي يشير إليه skills.sh. اقرأ تعليمات المهارة قبل الاعتماد عليها: سيتبعها الوكيل، وقد تعمل نصوصها البرمجية على هذا الكمبيوتر."$json$::jsonb),
  ('fr', 'skills.hub.notes', $json$"La skill est téléchargée depuis le dépôt GitHub vers lequel pointe skills.sh. Lisez les instructions d’une skill avant de vous y fier : l’agent les suivra et ses scripts peuvent s’exécuter sur cet ordinateur."$json$::jsonb),
  ('ru', 'skills.hub.notes', $json$"Навык скачивается из репозитория GitHub, на который указывает skills.sh. Прочитайте инструкции навыка, прежде чем на него полагаться: агент будет им следовать, а его скрипты могут запускаться на этом компьютере."$json$::jsonb),
  ('ja', 'skills.hub.notes', $json$"スキルは skills.sh が指す GitHub リポジトリからダウンロードされます。頼る前にスキルの指示を読んでください。エージェントはその指示に従い、スクリプトはこのコンピューターで実行されることがあります。"$json$::jsonb),
  ('de', 'skills.hub.notes', $json$"Der Skill wird aus dem GitHub-Repository heruntergeladen, auf das skills.sh verweist. Lesen Sie die Anweisungen eines Skills, bevor Sie sich darauf verlassen: Der Agent folgt ihnen, und seine Skripte können auf diesem Computer laufen."$json$::jsonb),
  ('pt-BR', 'skills.hub.network', $json$"Não foi possível acessar o skills.sh ou o GitHub ({reason})."$json$::jsonb),
  ('en', 'skills.hub.network', $json$"Could not reach skills.sh or GitHub ({reason})."$json$::jsonb),
  ('es', 'skills.hub.network', $json$"No se pudo acceder a skills.sh o a GitHub ({reason})."$json$::jsonb),
  ('zh-CN', 'skills.hub.network', $json$"无法访问 skills.sh 或 GitHub（{reason}）。"$json$::jsonb),
  ('hi', 'skills.hub.network', $json$"skills.sh या GitHub तक नहीं पहुँच सके ({reason})।"$json$::jsonb),
  ('ar', 'skills.hub.network', $json$"تعذّر الوصول إلى skills.sh أو GitHub ({reason})."$json$::jsonb),
  ('fr', 'skills.hub.network', $json$"Impossible d’atteindre skills.sh ou GitHub ({reason})."$json$::jsonb),
  ('ru', 'skills.hub.network', $json$"Не удалось связаться с skills.sh или GitHub ({reason})."$json$::jsonb),
  ('ja', 'skills.hub.network', $json$"skills.sh または GitHub に接続できませんでした（{reason}）。"$json$::jsonb),
  ('de', 'skills.hub.network', $json$"skills.sh oder GitHub ist nicht erreichbar ({reason})."$json$::jsonb),
  ('pt-BR', 'skills.hub.badSource', $json$"O endereço dessa skill não é válido."$json$::jsonb),
  ('en', 'skills.hub.badSource', $json$"That skill’s address is not valid."$json$::jsonb),
  ('es', 'skills.hub.badSource', $json$"La dirección de esa skill no es válida."$json$::jsonb),
  ('zh-CN', 'skills.hub.badSource', $json$"该技能的地址无效。"$json$::jsonb),
  ('hi', 'skills.hub.badSource', $json$"उस स्किल का पता मान्य नहीं है।"$json$::jsonb),
  ('ar', 'skills.hub.badSource', $json$"عنوان تلك المهارة غير صالح."$json$::jsonb),
  ('fr', 'skills.hub.badSource', $json$"L’adresse de cette skill n’est pas valide."$json$::jsonb),
  ('ru', 'skills.hub.badSource', $json$"Адрес этого навыка недействителен."$json$::jsonb),
  ('ja', 'skills.hub.badSource', $json$"そのスキルのアドレスが正しくありません。"$json$::jsonb),
  ('de', 'skills.hub.badSource', $json$"Die Adresse dieses Skills ist ungültig."$json$::jsonb),
  ('pt-BR', 'skills.hub.notFound', $json$"A skill {name} não foi encontrada em {source}."$json$::jsonb),
  ('en', 'skills.hub.notFound', $json$"The skill {name} was not found in {source}."$json$::jsonb),
  ('es', 'skills.hub.notFound', $json$"La skill {name} no se encontró en {source}."$json$::jsonb),
  ('zh-CN', 'skills.hub.notFound', $json$"在 {source} 中没有找到技能 {name}。"$json$::jsonb),
  ('hi', 'skills.hub.notFound', $json$"स्किल {name} {source} में नहीं मिली।"$json$::jsonb),
  ('ar', 'skills.hub.notFound', $json$"لم يتم العثور على المهارة {name} في {source}."$json$::jsonb),
  ('fr', 'skills.hub.notFound', $json$"La skill {name} est introuvable dans {source}."$json$::jsonb),
  ('ru', 'skills.hub.notFound', $json$"Навык {name} не найден в {source}."$json$::jsonb),
  ('ja', 'skills.hub.notFound', $json$"スキル {name} は {source} に見つかりませんでした。"$json$::jsonb),
  ('de', 'skills.hub.notFound', $json$"Der Skill {name} wurde in {source} nicht gefunden."$json$::jsonb),
  ('pt-BR', 'docs.skillsHub.title', $json$"Skills do skills.sh"$json$::jsonb),
  ('en', 'docs.skillsHub.title', $json$"Skills from skills.sh"$json$::jsonb),
  ('es', 'docs.skillsHub.title', $json$"Skills de skills.sh"$json$::jsonb),
  ('zh-CN', 'docs.skillsHub.title', $json$"来自 skills.sh 的技能"$json$::jsonb),
  ('hi', 'docs.skillsHub.title', $json$"skills.sh की स्किल"$json$::jsonb),
  ('ar', 'docs.skillsHub.title', $json$"مهارات من skills.sh"$json$::jsonb),
  ('fr', 'docs.skillsHub.title', $json$"Skills depuis skills.sh"$json$::jsonb),
  ('ru', 'docs.skillsHub.title', $json$"Навыки из skills.sh"$json$::jsonb),
  ('ja', 'docs.skillsHub.title', $json$"skills.sh のスキル"$json$::jsonb),
  ('de', 'docs.skillsHub.title', $json$"Skills von skills.sh"$json$::jsonb),
  ('pt-BR', 'docs.skillsHub.summary', $json$"Busque no diretório skills.sh sem sair do JayV e instale uma skill com um clique, no app ou para uma organização inteira no site."$json$::jsonb),
  ('en', 'docs.skillsHub.summary', $json$"Search the skills.sh directory from inside JayV and install a skill with one click, in the app or for a whole organization on the site."$json$::jsonb),
  ('es', 'docs.skillsHub.summary', $json$"Busca en el directorio skills.sh sin salir de JayV e instala una skill con un clic, en la app o para toda una organización en el sitio."$json$::jsonb),
  ('zh-CN', 'docs.skillsHub.summary', $json$"无需离开 JayV 即可搜索 skills.sh 目录，并一键安装技能，可在应用中安装，也可在网站上为整个组织安装。"$json$::jsonb),
  ('hi', 'docs.skillsHub.summary', $json$"JayV से बाहर गए बिना skills.sh डायरेक्टरी में खोजें और एक क्लिक में स्किल इंस्टॉल करें, ऐप में या साइट पर पूरे संगठन के लिए।"$json$::jsonb),
  ('ar', 'docs.skillsHub.summary', $json$"ابحث في دليل skills.sh من داخل JayV وثبّت مهارة بنقرة واحدة، في التطبيق أو لمؤسسة كاملة على الموقع."$json$::jsonb),
  ('fr', 'docs.skillsHub.summary', $json$"Cherchez dans l’annuaire skills.sh sans quitter JayV et installez une skill en un clic, dans l’app ou pour toute une organisation sur le site."$json$::jsonb),
  ('ru', 'docs.skillsHub.summary', $json$"Ищите в каталоге skills.sh прямо в JayV и устанавливайте навык одним щелчком — в приложении или для всей организации на сайте."$json$::jsonb),
  ('ja', 'docs.skillsHub.summary', $json$"JayV を離れずに skills.sh ディレクトリを検索し、ワンクリックでスキルをインストールできます。アプリでも、サイトで組織全体に対しても可能です。"$json$::jsonb),
  ('de', 'docs.skillsHub.summary', $json$"Durchsuchen Sie das Verzeichnis skills.sh direkt in JayV und installieren Sie einen Skill mit einem Klick, in der App oder auf der Website für eine ganze Organisation."$json$::jsonb),
  ('pt-BR', 'docs.skillsHub.usage', $json$"Abra Configurações › Skills (ou Ctrl+K › Instalar do skills.sh), digite o que você precisa e clique em Buscar; depois clique em Instalar num resultado. O JayV baixa a skill do repositório dela no GitHub e a instala como qualquer skill de uma pasta: desligue ou remova quando quiser, e o Jev a escolhe nos pedidos em que ela serve. No site, owners e maintainers fazem o mesmo na aba Skills da organização, que instala o SKILL.md da skill para todos os membros. Leia as instruções de uma skill antes de instalá-la."$json$::jsonb),
  ('en', 'docs.skillsHub.usage', $json$"Open Settings › Skills (or Ctrl+K › Install from skills.sh), type what you need and press Search, then Install on a result. JayV downloads the skill from its GitHub repository and installs it like any skill from a folder: turn it off or remove it whenever you want, and Jev picks it for the requests it fits. On the site, owners and maintainers do the same in the organization’s Skills tab, which installs the skill’s SKILL.md for every member. Read a skill’s instructions before installing it."$json$::jsonb),
  ('es', 'docs.skillsHub.usage', $json$"Abre Configuración › Skills (o Ctrl+K › Instalar desde skills.sh), escribe lo que necesitas y pulsa Buscar; luego pulsa Instalar en un resultado. JayV descarga la skill de su repositorio de GitHub y la instala como cualquier skill de una carpeta: desactívala o elimínala cuando quieras, y Jev la elige en las solicitudes a las que encaja. En el sitio, owners y maintainers hacen lo mismo en la pestaña Skills de la organización, que instala el SKILL.md de la skill para todos los miembros. Lee las instrucciones de una skill antes de instalarla."$json$::jsonb),
  ('zh-CN', 'docs.skillsHub.usage', $json$"打开“设置 › 技能”（或 Ctrl+K › 从 skills.sh 安装），输入你需要的内容并点击搜索，然后在结果上点击安装。JayV 会从技能的 GitHub 仓库下载并像文件夹中的技能一样安装：可随时关闭或删除，Jev 会在合适的请求中选用它。在网站上，所有者和维护者可在组织的“技能”标签页做同样的事，为每位成员安装该技能的 SKILL.md。安装前请先阅读技能的说明。"$json$::jsonb),
  ('hi', 'docs.skillsHub.usage', $json$"सेटिंग › स्किल खोलें (या Ctrl+K › skills.sh से इंस्टॉल करें), जो चाहिए वह लिखकर खोजें दबाएँ, फिर किसी परिणाम पर इंस्टॉल करें दबाएँ। JayV स्किल को उसकी GitHub रिपॉज़िटरी से डाउनलोड करता है और फ़ोल्डर की किसी भी स्किल की तरह इंस्टॉल करता है: जब चाहें बंद या हटाएँ, और Jev उसे उन अनुरोधों के लिए चुनता है जिनमें वह फिट बैठती है। साइट पर ओनर और मेंटेनर संगठन के स्किल टैब में यही करते हैं, जो हर सदस्य के लिए स्किल का SKILL.md इंस्टॉल करता है। इंस्टॉल करने से पहले स्किल के निर्देश पढ़ें।"$json$::jsonb),
  ('ar', 'docs.skillsHub.usage', $json$"افتح الإعدادات › المهارات (أو Ctrl+K › التثبيت من skills.sh)، واكتب ما تحتاجه واضغط بحث، ثم اضغط تثبيت على إحدى النتائج. ينزّل JayV المهارة من مستودعها على GitHub ويثبّتها كأي مهارة من مجلد: أوقفها أو أزلها متى شئت، ويختارها Jev للطلبات التي تناسبها. في الموقع يفعل المالكون والمشرفون الأمر نفسه في تبويب المهارات للمؤسسة، فيثبّت ملف SKILL.md للمهارة لجميع الأعضاء. اقرأ تعليمات المهارة قبل تثبيتها."$json$::jsonb),
  ('fr', 'docs.skillsHub.usage', $json$"Ouvrez Paramètres › Skills (ou Ctrl+K › Installer depuis skills.sh), tapez ce dont vous avez besoin et appuyez sur Rechercher, puis sur Installer pour un résultat. JayV télécharge la skill depuis son dépôt GitHub et l’installe comme toute skill d’un dossier : désactivez-la ou supprimez-la quand vous voulez, et Jev la choisit pour les demandes qui lui conviennent. Sur le site, les owners et maintainers font de même dans l’onglet Skills de l’organisation, qui installe le SKILL.md de la skill pour tous les membres. Lisez les instructions d’une skill avant de l’installer."$json$::jsonb),
  ('ru', 'docs.skillsHub.usage', $json$"Откройте «Настройки › Навыки» (или Ctrl+K › Установить из skills.sh), введите, что нужно, нажмите «Найти», затем «Установить» у результата. JayV скачивает навык из его репозитория GitHub и устанавливает как любой навык из папки: выключайте или удаляйте когда угодно, а Jev выбирает его для подходящих запросов. На сайте владельцы и мейнтейнеры делают то же на вкладке «Навыки» организации, где SKILL.md навыка устанавливается для всех участников. Прочитайте инструкции навыка перед установкой."$json$::jsonb),
  ('ja', 'docs.skillsHub.usage', $json$"設定 › スキル（または Ctrl+K › skills.sh からインストール）を開き、必要なものを入力して検索を押し、結果の「インストール」を押します。JayV はスキルを GitHub リポジトリからダウンロードし、フォルダーのスキルと同じようにインストールします。いつでもオフにしたり削除したりでき、Jev は合うリクエストで選びます。サイトでは、オーナーとメンテナーが組織の「スキル」タブで同じ操作をでき、全メンバー向けにそのスキルの SKILL.md がインストールされます。インストール前にスキルの指示を読んでください。"$json$::jsonb),
  ('de', 'docs.skillsHub.usage', $json$"Öffnen Sie Einstellungen › Skills (oder Strg+K › Von skills.sh installieren), geben Sie ein, was Sie brauchen, drücken Sie Suchen und dann bei einem Ergebnis Installieren. JayV lädt den Skill aus seinem GitHub-Repository herunter und installiert ihn wie jeden Skill aus einem Ordner: Schalten Sie ihn jederzeit aus oder entfernen Sie ihn, und Jev wählt ihn für passende Anfragen. Auf der Website tun Owner und Maintainer dasselbe im Skills-Tab der Organisation, der die SKILL.md des Skills für alle Mitglieder installiert. Lesen Sie die Anweisungen eines Skills, bevor Sie ihn installieren."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.skillsHub.title', $json$"Instale skills do skills.sh"$json$::jsonb),
  ('en', 'whatsNew.item.skillsHub.title', $json$"Install skills from skills.sh"$json$::jsonb),
  ('es', 'whatsNew.item.skillsHub.title', $json$"Instala skills de skills.sh"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.skillsHub.title', $json$"从 skills.sh 安装技能"$json$::jsonb),
  ('hi', 'whatsNew.item.skillsHub.title', $json$"skills.sh से स्किल इंस्टॉल करें"$json$::jsonb),
  ('ar', 'whatsNew.item.skillsHub.title', $json$"ثبّت مهارات من skills.sh"$json$::jsonb),
  ('fr', 'whatsNew.item.skillsHub.title', $json$"Installez des skills depuis skills.sh"$json$::jsonb),
  ('ru', 'whatsNew.item.skillsHub.title', $json$"Устанавливайте навыки из skills.sh"$json$::jsonb),
  ('ja', 'whatsNew.item.skillsHub.title', $json$"skills.sh からスキルをインストール"$json$::jsonb),
  ('de', 'whatsNew.item.skillsHub.title', $json$"Skills von skills.sh installieren"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.skillsHub.detail', $json$"Configurações › Skills (e a aba Skills da organização no site) ganharam uma seção do skills.sh: busque no diretório aberto e instale uma skill com um clique. No app ela é uma skill local comum; no site ela é entregue a todos os membros. Ctrl+K › Instalar do skills.sh leva direto à busca."$json$::jsonb),
  ('en', 'whatsNew.item.skillsHub.detail', $json$"Settings › Skills (and the organization’s Skills tab on the site) now have a skills.sh section: search the open directory and install a skill with one click. In the app it is a regular local skill; on the site it is delivered to every member. Ctrl+K › Install from skills.sh jumps to the search."$json$::jsonb),
  ('es', 'whatsNew.item.skillsHub.detail', $json$"Configuración › Skills (y la pestaña Skills de la organización en el sitio) tienen ahora una sección de skills.sh: busca en el directorio abierto e instala una skill con un clic. En la app es una skill local normal; en el sitio se entrega a todos los miembros. Ctrl+K › Instalar desde skills.sh lleva directo a la búsqueda."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.skillsHub.detail', $json$"“设置 › 技能”（以及网站上组织的“技能”标签页）新增了 skills.sh 部分：搜索开放目录并一键安装技能。在应用中它是普通的本地技能；在网站上会交付给每位成员。Ctrl+K › 从 skills.sh 安装 可直达搜索。"$json$::jsonb),
  ('hi', 'whatsNew.item.skillsHub.detail', $json$"सेटिंग › स्किल (और साइट पर संगठन के स्किल टैब) में अब skills.sh अनुभाग है: खुली डायरेक्टरी में खोजें और एक क्लिक में स्किल इंस्टॉल करें। ऐप में यह एक सामान्य लोकल स्किल है; साइट पर यह हर सदस्य को दी जाती है। Ctrl+K › skills.sh से इंस्टॉल करें सीधे खोज पर ले जाता है।"$json$::jsonb),
  ('ar', 'whatsNew.item.skillsHub.detail', $json$"أصبح في الإعدادات › المهارات (وتبويب المهارات للمؤسسة في الموقع) قسم skills.sh: ابحث في الدليل المفتوح وثبّت مهارة بنقرة واحدة. في التطبيق هي مهارة محلية عادية، وفي الموقع تُسلَّم لكل الأعضاء. يقودك Ctrl+K › التثبيت من skills.sh مباشرة إلى البحث."$json$::jsonb),
  ('fr', 'whatsNew.item.skillsHub.detail', $json$"Paramètres › Skills (et l’onglet Skills de l’organisation sur le site) ont désormais une section skills.sh : cherchez dans l’annuaire ouvert et installez une skill en un clic. Dans l’app, c’est une skill locale ordinaire ; sur le site, elle est remise à chaque membre. Ctrl+K › Installer depuis skills.sh mène directement à la recherche."$json$::jsonb),
  ('ru', 'whatsNew.item.skillsHub.detail', $json$"В «Настройки › Навыки» (и на вкладке «Навыки» организации на сайте) появился раздел skills.sh: ищите в открытом каталоге и устанавливайте навык одним щелчком. В приложении это обычный локальный навык, на сайте он выдаётся каждому участнику. Ctrl+K › Установить из skills.sh ведёт прямо к поиску."$json$::jsonb),
  ('ja', 'whatsNew.item.skillsHub.detail', $json$"設定 › スキル（とサイトの組織の「スキル」タブ）に skills.sh のセクションが加わりました。オープンなディレクトリを検索し、ワンクリックでスキルをインストールできます。アプリでは通常のローカルスキル、サイトでは全メンバーに配信されます。Ctrl+K › skills.sh からインストール で検索に直行できます。"$json$::jsonb),
  ('de', 'whatsNew.item.skillsHub.detail', $json$"Einstellungen › Skills (und der Skills-Tab der Organisation auf der Website) haben jetzt einen skills.sh-Bereich: Durchsuchen Sie das offene Verzeichnis und installieren Sie einen Skill mit einem Klick. In der App ist er ein normaler lokaler Skill, auf der Website wird er an alle Mitglieder ausgeliefert. Strg+K › Von skills.sh installieren springt direkt zur Suche."$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.title', $json$"Instalar do skills.sh"$json$::jsonb),
  ('en', 'site.org.skills.hub.title', $json$"Install from skills.sh"$json$::jsonb),
  ('es', 'site.org.skills.hub.title', $json$"Instalar desde skills.sh"$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.title', $json$"从 skills.sh 安装"$json$::jsonb),
  ('hi', 'site.org.skills.hub.title', $json$"skills.sh से इंस्टॉल करें"$json$::jsonb),
  ('ar', 'site.org.skills.hub.title', $json$"التثبيت من skills.sh"$json$::jsonb),
  ('fr', 'site.org.skills.hub.title', $json$"Installer depuis skills.sh"$json$::jsonb),
  ('ru', 'site.org.skills.hub.title', $json$"Установить из skills.sh"$json$::jsonb),
  ('ja', 'site.org.skills.hub.title', $json$"skills.sh からインストール"$json$::jsonb),
  ('de', 'site.org.skills.hub.title', $json$"Von skills.sh installieren"$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.description', $json$"Busque no diretório aberto de skills (skills.sh) e instale uma skill para a organização inteira. Ela é salva como qualquer skill da organização: os membros a recebem na próxima sincronização do app."$json$::jsonb),
  ('en', 'site.org.skills.hub.description', $json$"Search the open skills directory (skills.sh) and install a skill for the whole organization. It is saved like any organization skill: members receive it at the app’s next sync."$json$::jsonb),
  ('es', 'site.org.skills.hub.description', $json$"Busca en el directorio abierto de skills (skills.sh) e instala una skill para toda la organización. Se guarda como cualquier skill de la organización: los miembros la reciben en la próxima sincronización de la app."$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.description', $json$"在开放的技能目录（skills.sh）中搜索，并为整个组织安装技能。它与任何组织技能一样保存：成员会在应用下次同步时收到。"$json$::jsonb),
  ('hi', 'site.org.skills.hub.description', $json$"खुली स्किल डायरेक्टरी (skills.sh) में खोजें और पूरे संगठन के लिए स्किल इंस्टॉल करें। यह किसी भी संगठन स्किल की तरह सहेजी जाती है: सदस्यों को यह ऐप के अगले सिंक पर मिलती है।"$json$::jsonb),
  ('ar', 'site.org.skills.hub.description', $json$"ابحث في دليل المهارات المفتوح (skills.sh) وثبّت مهارة للمؤسسة كلها. تُحفظ كأي مهارة للمؤسسة: يستلمها الأعضاء في المزامنة التالية للتطبيق."$json$::jsonb),
  ('fr', 'site.org.skills.hub.description', $json$"Cherchez dans l’annuaire ouvert de skills (skills.sh) et installez une skill pour toute l’organisation. Elle est enregistrée comme n’importe quelle skill de l’organisation : les membres la reçoivent à la prochaine synchronisation de l’app."$json$::jsonb),
  ('ru', 'site.org.skills.hub.description', $json$"Ищите в открытом каталоге навыков (skills.sh) и устанавливайте навык для всей организации. Он сохраняется как любой навык организации: участники получат его при следующей синхронизации приложения."$json$::jsonb),
  ('ja', 'site.org.skills.hub.description', $json$"オープンなスキルディレクトリ（skills.sh）を検索し、組織全体にスキルをインストールします。通常の組織スキルと同じように保存され、メンバーはアプリの次回同期で受け取ります。"$json$::jsonb),
  ('de', 'site.org.skills.hub.description', $json$"Durchsuchen Sie das offene Skill-Verzeichnis (skills.sh) und installieren Sie einen Skill für die ganze Organisation. Er wird wie jeder Organisations-Skill gespeichert: Die Mitglieder erhalten ihn bei der nächsten Synchronisierung der App."$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.placeholder', $json$"Buscar skills, p. ex.: pdf, notas de versão, testes"$json$::jsonb),
  ('en', 'site.org.skills.hub.placeholder', $json$"Search skills, e.g. pdf, release notes, testing"$json$::jsonb),
  ('es', 'site.org.skills.hub.placeholder', $json$"Buscar skills, p. ej.: pdf, notas de versión, pruebas"$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.placeholder', $json$"搜索技能，例如 pdf、发布说明、测试"$json$::jsonb),
  ('hi', 'site.org.skills.hub.placeholder', $json$"स्किल खोजें, जैसे pdf, रिलीज़ नोट्स, टेस्टिंग"$json$::jsonb),
  ('ar', 'site.org.skills.hub.placeholder', $json$"ابحث عن مهارات، مثل pdf أو ملاحظات الإصدار أو الاختبار"$json$::jsonb),
  ('fr', 'site.org.skills.hub.placeholder', $json$"Rechercher des skills, p. ex. pdf, notes de version, tests"$json$::jsonb),
  ('ru', 'site.org.skills.hub.placeholder', $json$"Поиск навыков, например pdf, заметки о релизе, тесты"$json$::jsonb),
  ('ja', 'site.org.skills.hub.placeholder', $json$"スキルを検索（例: pdf、リリースノート、テスト）"$json$::jsonb),
  ('de', 'site.org.skills.hub.placeholder', $json$"Skills suchen, z. B. pdf, Release Notes, Tests"$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.search', $json$"Buscar"$json$::jsonb),
  ('en', 'site.org.skills.hub.search', $json$"Search"$json$::jsonb),
  ('es', 'site.org.skills.hub.search', $json$"Buscar"$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.search', $json$"搜索"$json$::jsonb),
  ('hi', 'site.org.skills.hub.search', $json$"खोजें"$json$::jsonb),
  ('ar', 'site.org.skills.hub.search', $json$"بحث"$json$::jsonb),
  ('fr', 'site.org.skills.hub.search', $json$"Rechercher"$json$::jsonb),
  ('ru', 'site.org.skills.hub.search', $json$"Найти"$json$::jsonb),
  ('ja', 'site.org.skills.hub.search', $json$"検索"$json$::jsonb),
  ('de', 'site.org.skills.hub.search', $json$"Suchen"$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.none', $json$"Nenhuma skill encontrada para essa busca."$json$::jsonb),
  ('en', 'site.org.skills.hub.none', $json$"No skill found for that search."$json$::jsonb),
  ('es', 'site.org.skills.hub.none', $json$"No se encontró ninguna skill para esa búsqueda."$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.none', $json$"没有找到符合该搜索的技能。"$json$::jsonb),
  ('hi', 'site.org.skills.hub.none', $json$"इस खोज के लिए कोई स्किल नहीं मिली।"$json$::jsonb),
  ('ar', 'site.org.skills.hub.none', $json$"لم يتم العثور على مهارة لهذا البحث."$json$::jsonb),
  ('fr', 'site.org.skills.hub.none', $json$"Aucune skill trouvée pour cette recherche."$json$::jsonb),
  ('ru', 'site.org.skills.hub.none', $json$"По этому запросу навыков не найдено."$json$::jsonb),
  ('ja', 'site.org.skills.hub.none', $json$"この検索に該当するスキルはありません。"$json$::jsonb),
  ('de', 'site.org.skills.hub.none', $json$"Für diese Suche wurde kein Skill gefunden."$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.installs', $json$"{count} instalações"$json$::jsonb),
  ('en', 'site.org.skills.hub.installs', $json$"{count} installs"$json$::jsonb),
  ('es', 'site.org.skills.hub.installs', $json$"{count} instalaciones"$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.installs', $json$"{count} 次安装"$json$::jsonb),
  ('hi', 'site.org.skills.hub.installs', $json$"{count} इंस्टॉल"$json$::jsonb),
  ('ar', 'site.org.skills.hub.installs', $json$"{count} عملية تثبيت"$json$::jsonb),
  ('fr', 'site.org.skills.hub.installs', $json$"{count} installations"$json$::jsonb),
  ('ru', 'site.org.skills.hub.installs', $json$"{count} установок"$json$::jsonb),
  ('ja', 'site.org.skills.hub.installs', $json$"{count} 件のインストール"$json$::jsonb),
  ('de', 'site.org.skills.hub.installs', $json$"{count} Installationen"$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.install', $json$"Instalar"$json$::jsonb),
  ('en', 'site.org.skills.hub.install', $json$"Install"$json$::jsonb),
  ('es', 'site.org.skills.hub.install', $json$"Instalar"$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.install', $json$"安装"$json$::jsonb),
  ('hi', 'site.org.skills.hub.install', $json$"इंस्टॉल करें"$json$::jsonb),
  ('ar', 'site.org.skills.hub.install', $json$"تثبيت"$json$::jsonb),
  ('fr', 'site.org.skills.hub.install', $json$"Installer"$json$::jsonb),
  ('ru', 'site.org.skills.hub.install', $json$"Установить"$json$::jsonb),
  ('ja', 'site.org.skills.hub.install', $json$"インストール"$json$::jsonb),
  ('de', 'site.org.skills.hub.install', $json$"Installieren"$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.reinstall', $json$"Reinstalar"$json$::jsonb),
  ('en', 'site.org.skills.hub.reinstall', $json$"Reinstall"$json$::jsonb),
  ('es', 'site.org.skills.hub.reinstall', $json$"Reinstalar"$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.reinstall', $json$"重新安装"$json$::jsonb),
  ('hi', 'site.org.skills.hub.reinstall', $json$"फिर से इंस्टॉल करें"$json$::jsonb),
  ('ar', 'site.org.skills.hub.reinstall', $json$"إعادة التثبيت"$json$::jsonb),
  ('fr', 'site.org.skills.hub.reinstall', $json$"Réinstaller"$json$::jsonb),
  ('ru', 'site.org.skills.hub.reinstall', $json$"Переустановить"$json$::jsonb),
  ('ja', 'site.org.skills.hub.reinstall', $json$"再インストール"$json$::jsonb),
  ('de', 'site.org.skills.hub.reinstall', $json$"Neu installieren"$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.installed', $json$"Skill {name} instalada. Os membros a recebem na próxima sincronização do app."$json$::jsonb),
  ('en', 'site.org.skills.hub.installed', $json$"Skill {name} installed. Members receive it at the app’s next sync."$json$::jsonb),
  ('es', 'site.org.skills.hub.installed', $json$"Skill {name} instalada. Los miembros la reciben en la próxima sincronización de la app."$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.installed', $json$"技能 {name} 已安装。成员会在应用下次同步时收到。"$json$::jsonb),
  ('hi', 'site.org.skills.hub.installed', $json$"स्किल {name} इंस्टॉल हो गई। सदस्यों को यह ऐप के अगले सिंक पर मिलेगी।"$json$::jsonb),
  ('ar', 'site.org.skills.hub.installed', $json$"تم تثبيت المهارة {name}. يستلمها الأعضاء في المزامنة التالية للتطبيق."$json$::jsonb),
  ('fr', 'site.org.skills.hub.installed', $json$"Skill {name} installée. Les membres la reçoivent à la prochaine synchronisation de l’app."$json$::jsonb),
  ('ru', 'site.org.skills.hub.installed', $json$"Навык {name} установлен. Участники получат его при следующей синхронизации приложения."$json$::jsonb),
  ('ja', 'site.org.skills.hub.installed', $json$"スキル {name} をインストールしました。メンバーはアプリの次回同期で受け取ります。"$json$::jsonb),
  ('de', 'site.org.skills.hub.installed', $json$"Skill {name} installiert. Die Mitglieder erhalten ihn bei der nächsten Synchronisierung der App."$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.notes', $json$"Só o SKILL.md é instalado: os arquivos ao lado dele (scripts, modelos) não fazem parte de uma skill da organização. Leia as instruções de uma skill antes de instalá-la, pois o agente de cada membro vai segui-las."$json$::jsonb),
  ('en', 'site.org.skills.hub.notes', $json$"Only the SKILL.md is installed: files next to it (scripts, templates) are not part of an organization skill. Read a skill’s instructions before installing it, since every member’s agent will follow them."$json$::jsonb),
  ('es', 'site.org.skills.hub.notes', $json$"Solo se instala el SKILL.md: los archivos junto a él (scripts, plantillas) no forman parte de una skill de la organización. Lee las instrucciones de una skill antes de instalarla, ya que el agente de cada miembro las seguirá."$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.notes', $json$"只安装 SKILL.md：它旁边的文件（脚本、模板）不属于组织技能。安装前请先阅读技能的说明，因为每位成员的代理都会遵循这些说明。"$json$::jsonb),
  ('hi', 'site.org.skills.hub.notes', $json$"केवल SKILL.md इंस्टॉल होती है: उसके साथ की फ़ाइलें (स्क्रिप्ट, टेम्पलेट) संगठन स्किल का हिस्सा नहीं हैं। इंस्टॉल करने से पहले स्किल के निर्देश पढ़ें, क्योंकि हर सदस्य का एजेंट उनका पालन करेगा।"$json$::jsonb),
  ('ar', 'site.org.skills.hub.notes', $json$"يُثبَّت ملف SKILL.md فقط: الملفات المجاورة له (النصوص البرمجية والقوالب) ليست جزءًا من مهارة المؤسسة. اقرأ تعليمات المهارة قبل تثبيتها لأن وكيل كل عضو سيتبعها."$json$::jsonb),
  ('fr', 'site.org.skills.hub.notes', $json$"Seul le SKILL.md est installé : les fichiers à côté (scripts, modèles) ne font pas partie d’une skill d’organisation. Lisez les instructions d’une skill avant de l’installer, car l’agent de chaque membre les suivra."$json$::jsonb),
  ('ru', 'site.org.skills.hub.notes', $json$"Устанавливается только SKILL.md: файлы рядом с ним (скрипты, шаблоны) не входят в навык организации. Прочитайте инструкции навыка перед установкой: агент каждого участника будет им следовать."$json$::jsonb),
  ('ja', 'site.org.skills.hub.notes', $json$"インストールされるのは SKILL.md だけです。隣にあるファイル（スクリプトやテンプレート）は組織スキルに含まれません。全メンバーのエージェントが従うため、インストール前にスキルの指示を読んでください。"$json$::jsonb),
  ('de', 'site.org.skills.hub.notes', $json$"Nur die SKILL.md wird installiert: Dateien daneben (Skripte, Vorlagen) gehören nicht zu einem Organisations-Skill. Lesen Sie die Anweisungen eines Skills vor der Installation, denn der Agent jedes Mitglieds folgt ihnen."$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.failed', $json$"Não foi possível acessar o skills.sh ou o GitHub. Tente de novo em instantes."$json$::jsonb),
  ('en', 'site.org.skills.hub.failed', $json$"Could not reach skills.sh or GitHub. Try again in a moment."$json$::jsonb),
  ('es', 'site.org.skills.hub.failed', $json$"No se pudo acceder a skills.sh o a GitHub. Inténtalo de nuevo en un momento."$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.failed', $json$"无法访问 skills.sh 或 GitHub。请稍后再试。"$json$::jsonb),
  ('hi', 'site.org.skills.hub.failed', $json$"skills.sh या GitHub तक नहीं पहुँच सके। थोड़ी देर बाद फिर कोशिश करें।"$json$::jsonb),
  ('ar', 'site.org.skills.hub.failed', $json$"تعذّر الوصول إلى skills.sh أو GitHub. حاول مرة أخرى بعد قليل."$json$::jsonb),
  ('fr', 'site.org.skills.hub.failed', $json$"Impossible d’atteindre skills.sh ou GitHub. Réessayez dans un instant."$json$::jsonb),
  ('ru', 'site.org.skills.hub.failed', $json$"Не удалось связаться с skills.sh или GitHub. Попробуйте ещё раз чуть позже."$json$::jsonb),
  ('ja', 'site.org.skills.hub.failed', $json$"skills.sh または GitHub に接続できませんでした。少ししてからもう一度お試しください。"$json$::jsonb),
  ('de', 'site.org.skills.hub.failed', $json$"skills.sh oder GitHub ist nicht erreichbar. Versuchen Sie es gleich noch einmal."$json$::jsonb),
  ('pt-BR', 'site.org.skills.hub.notFound', $json$"Essa skill não foi encontrada no repositório dela."$json$::jsonb),
  ('en', 'site.org.skills.hub.notFound', $json$"That skill was not found in its repository."$json$::jsonb),
  ('es', 'site.org.skills.hub.notFound', $json$"Esa skill no se encontró en su repositorio."$json$::jsonb),
  ('zh-CN', 'site.org.skills.hub.notFound', $json$"在其仓库中没有找到该技能。"$json$::jsonb),
  ('hi', 'site.org.skills.hub.notFound', $json$"वह स्किल अपनी रिपॉज़िटरी में नहीं मिली।"$json$::jsonb),
  ('ar', 'site.org.skills.hub.notFound', $json$"لم يتم العثور على تلك المهارة في مستودعها."$json$::jsonb),
  ('fr', 'site.org.skills.hub.notFound', $json$"Cette skill est introuvable dans son dépôt."$json$::jsonb),
  ('ru', 'site.org.skills.hub.notFound', $json$"Этот навык не найден в своём репозитории."$json$::jsonb),
  ('ja', 'site.org.skills.hub.notFound', $json$"そのスキルはリポジトリに見つかりませんでした。"$json$::jsonb),
  ('de', 'site.org.skills.hub.notFound', $json$"Dieser Skill wurde in seinem Repository nicht gefunden."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
