-- v0.43.0: modo de trabalho do chat.
--
-- Só textos: o seletor Auto · Planejamento · Desenvolvimento embaixo da caixa
-- de mensagem (mode.*), a dica dos comandos /plan, /build e /auto
-- (composer.key.mode), o item da paleta (palette.mode), a linha em que o Jev
-- avisa que tirou o chat do planejamento, com o Desfazer
-- (mode.switched.*, mode.undo*), e o item da janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'mode.label', $json$"Modo de trabalho"$json$::jsonb),
  ('pt-BR', 'mode.auto', $json$"Auto"$json$::jsonb),
  ('pt-BR', 'mode.plan', $json$"Planejamento"$json$::jsonb),
  ('pt-BR', 'mode.build', $json$"Desenvolvimento"$json$::jsonb),
  ('pt-BR', 'mode.auto.hint', $json$"O Jev escolhe planejamento ou desenvolvimento a cada pedido"$json$::jsonb),
  ('pt-BR', 'mode.plan.hint', $json$"O agente só lê e responde com um plano, sem mudar arquivos. Se você pedir para implementar, o Jev passa para desenvolvimento"$json$::jsonb),
  ('pt-BR', 'mode.build.hint', $json$"O agente muda arquivos do projeto, dentro das permissões definidas nas configurações de LLM"$json$::jsonb),
  ('pt-BR', 'mode.set', $json$"Este chat agora está no modo {name}."$json$::jsonb),
  ('pt-BR', 'mode.switched.asked', $json$"O Jev passou este chat para Desenvolvimento porque o pedido é para implementar."$json$::jsonb),
  ('pt-BR', 'mode.switched.repeated', $json$"O Jev passou este chat para Desenvolvimento porque você pediu para implementar de novo depois de um plano."$json$::jsonb),
  ('pt-BR', 'mode.undo', $json$"Desfazer"$json$::jsonb),
  ('pt-BR', 'mode.undo.hint', $json$"Voltar para {name}"$json$::jsonb),
  ('pt-BR', 'composer.key.mode', $json$"modo"$json$::jsonb),
  ('pt-BR', 'palette.mode', $json$"Modo de trabalho: {name}"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.workMode.title', $json$"Escolha Planejamento ou Desenvolvimento em cada chat"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.workMode.detail', $json$"Cada chat agora tem um seletor de modo de trabalho embaixo da caixa de mensagem: Auto (o Jev escolhe a cada pedido, como antes), Planejamento ou Desenvolvimento. Você também pode digitar /plan, /build ou /auto, apertar Ctrl+. (⌘. no Mac) ou usar a paleta de comandos. Se o chat estiver em Planejamento e você pedir para implementar, ou no Auto você pedir para implementar de novo depois de um plano, o Jev passa para Desenvolvimento sozinho e avisa na resposta, com um botão para desfazer."$json$::jsonb),
  ('en', 'mode.label', $json$"Work mode"$json$::jsonb),
  ('en', 'mode.auto', $json$"Auto"$json$::jsonb),
  ('en', 'mode.plan', $json$"Planning"$json$::jsonb),
  ('en', 'mode.build', $json$"Development"$json$::jsonb),
  ('en', 'mode.auto.hint', $json$"Jev picks planning or development for each request"$json$::jsonb),
  ('en', 'mode.plan.hint', $json$"The agent only reads and answers with a plan, without changing files. If you ask to implement, Jev switches to development"$json$::jsonb),
  ('en', 'mode.build.hint', $json$"The agent changes files in the project, within the permissions set in LLM settings"$json$::jsonb),
  ('en', 'mode.set', $json$"This chat is now in {name} mode."$json$::jsonb),
  ('en', 'mode.switched.asked', $json$"Jev switched this chat to Development because the request asks to implement."$json$::jsonb),
  ('en', 'mode.switched.repeated', $json$"Jev switched this chat to Development because you asked to implement again after a plan."$json$::jsonb),
  ('en', 'mode.undo', $json$"Undo"$json$::jsonb),
  ('en', 'mode.undo.hint', $json$"Go back to {name}"$json$::jsonb),
  ('en', 'composer.key.mode', $json$"mode"$json$::jsonb),
  ('en', 'palette.mode', $json$"Work mode: {name}"$json$::jsonb),
  ('en', 'whatsNew.item.workMode.title', $json$"Choose Planning or Development in each chat"$json$::jsonb),
  ('en', 'whatsNew.item.workMode.detail', $json$"Each chat now has a work mode selector under the message box: Auto (Jev picks for each request, as before), Planning or Development. You can also type /plan, /build or /auto, press Ctrl+. (⌘. on Mac) or use the command palette. If the chat is in Planning and you ask to implement, or in Auto you ask to implement again after a plan, Jev switches to Development by itself and says so in the reply, with a button to undo."$json$::jsonb),
  ('es', 'mode.label', $json$"Modo de trabajo"$json$::jsonb),
  ('es', 'mode.auto', $json$"Auto"$json$::jsonb),
  ('es', 'mode.plan', $json$"Planificación"$json$::jsonb),
  ('es', 'mode.build', $json$"Desarrollo"$json$::jsonb),
  ('es', 'mode.auto.hint', $json$"Jev elige planificación o desarrollo en cada solicitud"$json$::jsonb),
  ('es', 'mode.plan.hint', $json$"El agente solo lee y responde con un plan, sin cambiar archivos. Si pides implementar, Jev pasa a desarrollo"$json$::jsonb),
  ('es', 'mode.build.hint', $json$"El agente cambia archivos del proyecto, dentro de los permisos definidos en la configuración de LLM"$json$::jsonb),
  ('es', 'mode.set', $json$"Este chat ahora está en modo {name}."$json$::jsonb),
  ('es', 'mode.switched.asked', $json$"Jev pasó este chat a Desarrollo porque la solicitud pide implementar."$json$::jsonb),
  ('es', 'mode.switched.repeated', $json$"Jev pasó este chat a Desarrollo porque volviste a pedir implementar después de un plan."$json$::jsonb),
  ('es', 'mode.undo', $json$"Deshacer"$json$::jsonb),
  ('es', 'mode.undo.hint', $json$"Volver a {name}"$json$::jsonb),
  ('es', 'composer.key.mode', $json$"modo"$json$::jsonb),
  ('es', 'palette.mode', $json$"Modo de trabajo: {name}"$json$::jsonb),
  ('es', 'whatsNew.item.workMode.title', $json$"Elige Planificación o Desarrollo en cada chat"$json$::jsonb),
  ('es', 'whatsNew.item.workMode.detail', $json$"Cada chat tiene ahora un selector de modo de trabajo debajo del cuadro de mensaje: Auto (Jev elige en cada solicitud, como antes), Planificación o Desarrollo. También puedes escribir /plan, /build o /auto, pulsar Ctrl+. (⌘. en Mac) o usar la paleta de comandos. Si el chat está en Planificación y pides implementar, o en Auto vuelves a pedir implementar después de un plan, Jev pasa a Desarrollo por sí mismo y lo indica en la respuesta, con un botón para deshacer."$json$::jsonb),
  ('fr', 'mode.label', $json$"Mode de travail"$json$::jsonb),
  ('fr', 'mode.auto', $json$"Auto"$json$::jsonb),
  ('fr', 'mode.plan', $json$"Planification"$json$::jsonb),
  ('fr', 'mode.build', $json$"Développement"$json$::jsonb),
  ('fr', 'mode.auto.hint', $json$"Jev choisit planification ou développement à chaque demande"$json$::jsonb),
  ('fr', 'mode.plan.hint', $json$"L'agent se contente de lire et répond par un plan, sans modifier de fichiers. Si vous demandez d'implémenter, Jev passe en développement"$json$::jsonb),
  ('fr', 'mode.build.hint', $json$"L'agent modifie les fichiers du projet, dans les limites des autorisations définies dans les paramètres LLM"$json$::jsonb),
  ('fr', 'mode.set', $json$"Ce chat est maintenant en mode {name}."$json$::jsonb),
  ('fr', 'mode.switched.asked', $json$"Jev a passé ce chat en Développement car la demande consiste à implémenter."$json$::jsonb),
  ('fr', 'mode.switched.repeated', $json$"Jev a passé ce chat en Développement car vous avez de nouveau demandé d'implémenter après un plan."$json$::jsonb),
  ('fr', 'mode.undo', $json$"Annuler"$json$::jsonb),
  ('fr', 'mode.undo.hint', $json$"Revenir à {name}"$json$::jsonb),
  ('fr', 'composer.key.mode', $json$"mode"$json$::jsonb),
  ('fr', 'palette.mode', $json$"Mode de travail : {name}"$json$::jsonb),
  ('fr', 'whatsNew.item.workMode.title', $json$"Choisissez Planification ou Développement dans chaque chat"$json$::jsonb),
  ('fr', 'whatsNew.item.workMode.detail', $json$"Chaque chat dispose désormais d'un sélecteur de mode de travail sous la zone de message : Auto (Jev choisit à chaque demande, comme avant), Planification ou Développement. Vous pouvez aussi taper /plan, /build ou /auto, appuyer sur Ctrl+. (⌘. sur Mac) ou utiliser la palette de commandes. Si le chat est en Planification et que vous demandez d'implémenter, ou si en Auto vous redemandez d'implémenter après un plan, Jev passe en Développement de lui-même et l'indique dans la réponse, avec un bouton pour annuler."$json$::jsonb),
  ('zh-CN', 'mode.label', $json$"工作模式"$json$::jsonb),
  ('zh-CN', 'mode.auto', $json$"自动"$json$::jsonb),
  ('zh-CN', 'mode.plan', $json$"规划"$json$::jsonb),
  ('zh-CN', 'mode.build', $json$"开发"$json$::jsonb),
  ('zh-CN', 'mode.auto.hint', $json$"Jev 为每个请求选择规划或开发"$json$::jsonb),
  ('zh-CN', 'mode.plan.hint', $json$"智能体只读取并以计划作答，不修改文件。如果你要求实现，Jev 会切换到开发"$json$::jsonb),
  ('zh-CN', 'mode.build.hint', $json$"智能体在 LLM 设置中定义的权限范围内修改项目文件"$json$::jsonb),
  ('zh-CN', 'mode.set', $json$"此聊天现在处于{name}模式。"$json$::jsonb),
  ('zh-CN', 'mode.switched.asked', $json$"Jev 已将此聊天切换为开发，因为该请求要求实现。"$json$::jsonb),
  ('zh-CN', 'mode.switched.repeated', $json$"Jev 已将此聊天切换为开发，因为你在计划之后再次要求实现。"$json$::jsonb),
  ('zh-CN', 'mode.undo', $json$"撤销"$json$::jsonb),
  ('zh-CN', 'mode.undo.hint', $json$"返回{name}"$json$::jsonb),
  ('zh-CN', 'composer.key.mode', $json$"模式"$json$::jsonb),
  ('zh-CN', 'palette.mode', $json$"工作模式：{name}"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.workMode.title', $json$"在每个聊天中选择规划或开发"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.workMode.detail', $json$"每个聊天的消息框下方现在都有一个工作模式选择器：自动（与以前一样，由 Jev 为每个请求选择）、规划或开发。你也可以输入 /plan、/build 或 /auto，按 Ctrl+.（Mac 上为 ⌘.）或使用命令面板。如果聊天处于规划模式而你要求实现，或在自动模式下你在计划之后再次要求实现，Jev 会自行切换到开发，并在回复中说明，同时提供撤销按钮。"$json$::jsonb),
  ('ru', 'mode.label', $json$"Режим работы"$json$::jsonb),
  ('ru', 'mode.auto', $json$"Авто"$json$::jsonb),
  ('ru', 'mode.plan', $json$"Планирование"$json$::jsonb),
  ('ru', 'mode.build', $json$"Разработка"$json$::jsonb),
  ('ru', 'mode.auto.hint', $json$"Jev выбирает планирование или разработку для каждого запроса"$json$::jsonb),
  ('ru', 'mode.plan.hint', $json$"Агент только читает и отвечает планом, не меняя файлы. Если вы попросите реализовать, Jev переключится на разработку"$json$::jsonb),
  ('ru', 'mode.build.hint', $json$"Агент меняет файлы проекта в пределах разрешений, заданных в настройках LLM"$json$::jsonb),
  ('ru', 'mode.set', $json$"Этот чат теперь в режиме «{name}»."$json$::jsonb),
  ('ru', 'mode.switched.asked', $json$"Jev переключил этот чат на «Разработку», потому что запрос требует реализации."$json$::jsonb),
  ('ru', 'mode.switched.repeated', $json$"Jev переключил этот чат на «Разработку», потому что вы снова попросили реализовать после плана."$json$::jsonb),
  ('ru', 'mode.undo', $json$"Отменить"$json$::jsonb),
  ('ru', 'mode.undo.hint', $json$"Вернуться к режиму «{name}»"$json$::jsonb),
  ('ru', 'composer.key.mode', $json$"режим"$json$::jsonb),
  ('ru', 'palette.mode', $json$"Режим работы: {name}"$json$::jsonb),
  ('ru', 'whatsNew.item.workMode.title', $json$"Выбирайте планирование или разработку в каждом чате"$json$::jsonb),
  ('ru', 'whatsNew.item.workMode.detail', $json$"Теперь в каждом чате под полем сообщения есть переключатель режима работы: «Авто» (Jev выбирает для каждого запроса, как раньше), «Планирование» или «Разработка». Можно также ввести /plan, /build или /auto, нажать Ctrl+. (⌘. на Mac) или воспользоваться палитрой команд. Если чат в режиме «Планирование» и вы просите реализовать, или в режиме «Авто» вы снова просите реализовать после плана, Jev сам переключается на «Разработку» и сообщает об этом в ответе, с кнопкой отмены."$json$::jsonb),
  ('ar', 'mode.label', $json$"وضع العمل"$json$::jsonb),
  ('ar', 'mode.auto', $json$"تلقائي"$json$::jsonb),
  ('ar', 'mode.plan', $json$"التخطيط"$json$::jsonb),
  ('ar', 'mode.build', $json$"التطوير"$json$::jsonb),
  ('ar', 'mode.auto.hint', $json$"يختار Jev التخطيط أو التطوير لكل طلب"$json$::jsonb),
  ('ar', 'mode.plan.hint', $json$"يقرأ الوكيل فقط ويجيب بخطة دون تغيير الملفات. إذا طلبت التنفيذ، ينتقل Jev إلى التطوير"$json$::jsonb),
  ('ar', 'mode.build.hint', $json$"يغيّر الوكيل ملفات المشروع ضمن الأذونات المحددة في إعدادات LLM"$json$::jsonb),
  ('ar', 'mode.set', $json$"هذه المحادثة الآن في وضع {name}."$json$::jsonb),
  ('ar', 'mode.switched.asked', $json$"نقل Jev هذه المحادثة إلى التطوير لأن الطلب يطلب التنفيذ."$json$::jsonb),
  ('ar', 'mode.switched.repeated', $json$"نقل Jev هذه المحادثة إلى التطوير لأنك طلبت التنفيذ مرة أخرى بعد خطة."$json$::jsonb),
  ('ar', 'mode.undo', $json$"تراجع"$json$::jsonb),
  ('ar', 'mode.undo.hint', $json$"العودة إلى {name}"$json$::jsonb),
  ('ar', 'composer.key.mode', $json$"الوضع"$json$::jsonb),
  ('ar', 'palette.mode', $json$"وضع العمل: {name}"$json$::jsonb),
  ('ar', 'whatsNew.item.workMode.title', $json$"اختر التخطيط أو التطوير في كل محادثة"$json$::jsonb),
  ('ar', 'whatsNew.item.workMode.detail', $json$"أصبح لكل محادثة الآن محدد لوضع العمل أسفل مربع الرسالة: تلقائي (يختار Jev لكل طلب كما كان من قبل) أو التخطيط أو التطوير. يمكنك أيضًا كتابة /plan أو /build أو /auto، أو الضغط على Ctrl+. (⌘. على Mac) أو استخدام لوحة الأوامر. إذا كانت المحادثة في وضع التخطيط وطلبت التنفيذ، أو طلبت التنفيذ مرة أخرى بعد خطة في الوضع التلقائي، ينتقل Jev إلى التطوير من تلقاء نفسه ويذكر ذلك في الرد، مع زر للتراجع."$json$::jsonb),
  ('hi', 'mode.label', $json$"कार्य मोड"$json$::jsonb),
  ('hi', 'mode.auto', $json$"ऑटो"$json$::jsonb),
  ('hi', 'mode.plan', $json$"योजना"$json$::jsonb),
  ('hi', 'mode.build', $json$"डेवलपमेंट"$json$::jsonb),
  ('hi', 'mode.auto.hint', $json$"Jev हर अनुरोध के लिए योजना या डेवलपमेंट चुनता है"$json$::jsonb),
  ('hi', 'mode.plan.hint', $json$"एजेंट केवल पढ़ता है और फ़ाइलें बदले बिना योजना के साथ जवाब देता है। अगर आप लागू करने को कहते हैं, तो Jev डेवलपमेंट पर चला जाता है"$json$::jsonb),
  ('hi', 'mode.build.hint', $json$"एजेंट LLM सेटिंग्स में तय अनुमतियों के भीतर प्रोजेक्ट की फ़ाइलें बदलता है"$json$::jsonb),
  ('hi', 'mode.set', $json$"यह चैट अब {name} मोड में है।"$json$::jsonb),
  ('hi', 'mode.switched.asked', $json$"Jev ने इस चैट को डेवलपमेंट पर कर दिया क्योंकि अनुरोध लागू करने का है।"$json$::jsonb),
  ('hi', 'mode.switched.repeated', $json$"Jev ने इस चैट को डेवलपमेंट पर कर दिया क्योंकि आपने योजना के बाद फिर से लागू करने को कहा।"$json$::jsonb),
  ('hi', 'mode.undo', $json$"पूर्ववत करें"$json$::jsonb),
  ('hi', 'mode.undo.hint', $json$"{name} पर वापस जाएँ"$json$::jsonb),
  ('hi', 'composer.key.mode', $json$"मोड"$json$::jsonb),
  ('hi', 'palette.mode', $json$"कार्य मोड: {name}"$json$::jsonb),
  ('hi', 'whatsNew.item.workMode.title', $json$"हर चैट में योजना या डेवलपमेंट चुनें"$json$::jsonb),
  ('hi', 'whatsNew.item.workMode.detail', $json$"अब हर चैट में संदेश बॉक्स के नीचे कार्य मोड चुनने का विकल्प है: ऑटो (पहले की तरह Jev हर अनुरोध के लिए चुनता है), योजना या डेवलपमेंट। आप /plan, /build या /auto भी टाइप कर सकते हैं, Ctrl+. (Mac पर ⌘.) दबा सकते हैं या कमांड पैलेट का उपयोग कर सकते हैं। अगर चैट योजना मोड में है और आप लागू करने को कहते हैं, या ऑटो में योजना के बाद फिर से लागू करने को कहते हैं, तो Jev खुद डेवलपमेंट पर चला जाता है और जवाब में बताता है, साथ में पूर्ववत करने का बटन होता है।"$json$::jsonb),
  ('ja', 'mode.label', $json$"作業モード"$json$::jsonb),
  ('ja', 'mode.auto', $json$"自動"$json$::jsonb),
  ('ja', 'mode.plan', $json$"計画"$json$::jsonb),
  ('ja', 'mode.build', $json$"開発"$json$::jsonb),
  ('ja', 'mode.auto.hint', $json$"Jev がリクエストごとに計画か開発かを選びます"$json$::jsonb),
  ('ja', 'mode.plan.hint', $json$"エージェントは読み取りのみを行い、ファイルを変更せずに計画で回答します。実装を依頼すると、Jev が開発に切り替えます"$json$::jsonb),
  ('ja', 'mode.build.hint', $json$"エージェントは LLM 設定で定めた権限の範囲内でプロジェクトのファイルを変更します"$json$::jsonb),
  ('ja', 'mode.set', $json$"このチャットは{name}モードになりました。"$json$::jsonb),
  ('ja', 'mode.switched.asked', $json$"リクエストが実装を求めているため、Jev がこのチャットを開発に切り替えました。"$json$::jsonb),
  ('ja', 'mode.switched.repeated', $json$"計画の後に再び実装を依頼されたため、Jev がこのチャットを開発に切り替えました。"$json$::jsonb),
  ('ja', 'mode.undo', $json$"元に戻す"$json$::jsonb),
  ('ja', 'mode.undo.hint', $json$"{name}に戻す"$json$::jsonb),
  ('ja', 'composer.key.mode', $json$"モード"$json$::jsonb),
  ('ja', 'palette.mode', $json$"作業モード：{name}"$json$::jsonb),
  ('ja', 'whatsNew.item.workMode.title', $json$"チャットごとに計画か開発かを選択"$json$::jsonb),
  ('ja', 'whatsNew.item.workMode.detail', $json$"各チャットのメッセージ欄の下に作業モードの切り替えが追加されました：自動（これまでどおり Jev がリクエストごとに選択）、計画、開発。/plan、/build、/auto と入力するか、Ctrl+.（Mac では ⌘.）を押すか、コマンドパレットを使うこともできます。チャットが計画モードで実装を依頼した場合、または自動モードで計画の後に再び実装を依頼した場合、Jev が自動的に開発に切り替え、元に戻すボタンとともに回答の中でお知らせします。"$json$::jsonb),
  ('de', 'mode.label', $json$"Arbeitsmodus"$json$::jsonb),
  ('de', 'mode.auto', $json$"Auto"$json$::jsonb),
  ('de', 'mode.plan', $json$"Planung"$json$::jsonb),
  ('de', 'mode.build', $json$"Entwicklung"$json$::jsonb),
  ('de', 'mode.auto.hint', $json$"Jev wählt bei jeder Anfrage Planung oder Entwicklung"$json$::jsonb),
  ('de', 'mode.plan.hint', $json$"Der Agent liest nur und antwortet mit einem Plan, ohne Dateien zu ändern. Wenn Sie um eine Umsetzung bitten, wechselt Jev zur Entwicklung"$json$::jsonb),
  ('de', 'mode.build.hint', $json$"Der Agent ändert Dateien im Projekt, im Rahmen der in den LLM-Einstellungen festgelegten Berechtigungen"$json$::jsonb),
  ('de', 'mode.set', $json$"Dieser Chat ist jetzt im Modus {name}."$json$::jsonb),
  ('de', 'mode.switched.asked', $json$"Jev hat diesen Chat auf Entwicklung umgestellt, weil die Anfrage eine Umsetzung verlangt."$json$::jsonb),
  ('de', 'mode.switched.repeated', $json$"Jev hat diesen Chat auf Entwicklung umgestellt, weil Sie nach einem Plan erneut um eine Umsetzung gebeten haben."$json$::jsonb),
  ('de', 'mode.undo', $json$"Rückgängig"$json$::jsonb),
  ('de', 'mode.undo.hint', $json$"Zurück zu {name}"$json$::jsonb),
  ('de', 'composer.key.mode', $json$"Modus"$json$::jsonb),
  ('de', 'palette.mode', $json$"Arbeitsmodus: {name}"$json$::jsonb),
  ('de', 'whatsNew.item.workMode.title', $json$"Planung oder Entwicklung in jedem Chat wählen"$json$::jsonb),
  ('de', 'whatsNew.item.workMode.detail', $json$"Jeder Chat hat jetzt unter dem Nachrichtenfeld eine Auswahl für den Arbeitsmodus: Auto (Jev wählt wie bisher bei jeder Anfrage), Planung oder Entwicklung. Sie können auch /plan, /build oder /auto eingeben, Strg+. (⌘. auf dem Mac) drücken oder die Befehlspalette verwenden. Ist der Chat in Planung und Sie bitten um eine Umsetzung, oder bitten Sie in Auto nach einem Plan erneut darum, wechselt Jev von selbst zu Entwicklung und sagt es in der Antwort, mit einer Schaltfläche zum Rückgängigmachen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
