-- Site 2.11.0: a aba Projetos da organização (owner e maintainer veem os
-- repositórios que os membros têm como projeto e excluem o projeto no app de
-- todos), o erro `org.repoGone` de `delete_org_project` e a frase da página
-- Organizações, que deixa de dizer que os projetos só existem no app. Nos dez
-- idiomas. A chave antiga da frase (`site.dashboard.organizations`) fica no
-- banco, sem uso.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'org.repoGone', $json$"Este repositório não está mais na organização."$json$::jsonb),
  ('pt-BR', 'site.dashboard.organizations.intro', $json$"Crie e gerencie as suas organizações: membros e papéis, projetos, repositórios, política de LLM, permissões de comandos, servidores MCP e skills. O clone dos repositórios e os chats continuam no app do JayV."$json$::jsonb),
  ('pt-BR', 'site.org.tab.projects', $json$"Projetos"$json$::jsonb),
  ('pt-BR', 'site.org.projects.title', $json$"Projetos da organização"$json$::jsonb),
  ('pt-BR', 'site.org.projects.description', $json$"Os repositórios da organização que os membros têm como projeto no app do JayV. Cada membro tem a própria cópia, com os próprios chats. Projetos de organização só podem ser excluídos aqui, por owners e maintainers."$json$::jsonb),
  ('pt-BR', 'site.org.projects.empty', $json$"Nenhum membro tem projeto dos repositórios desta organização ainda. Os projetos aparecem aqui quando alguém clona um repositório no app do JayV."$json$::jsonb),
  ('pt-BR', 'site.org.projects.failed', $json$"Não foi possível carregar os projetos. Tente de novo daqui a pouco."$json$::jsonb),
  ('pt-BR', 'site.org.projects.chats', $json${"one": "{count} chat", "other": "{count} chats"}$json$::jsonb),
  ('pt-BR', 'site.org.projects.lastActivity', $json$"última atividade em {date}"$json$::jsonb),
  ('pt-BR', 'site.org.projects.delete.label', $json$"Excluir o projeto {repo}"$json$::jsonb),
  ('pt-BR', 'site.org.projects.delete.title', $json$"Excluir projeto"$json$::jsonb),
  ('pt-BR', 'site.org.projects.delete.description', $json$"Exclui o projeto {repo} e todos os chats dele do app do JayV de todos os membros que o têm, na próxima sincronização de cada um. Não dá para desfazer. O repositório continua na organização: os membros podem cloná-lo de novo."$json$::jsonb),
  ('pt-BR', 'site.org.projects.deleted', $json$"Projeto excluído. Ele sai do app de cada membro na próxima sincronização."$json$::jsonb),

  ('en', 'org.repoGone', $json$"This repository is no longer in the organization."$json$::jsonb),
  ('en', 'site.dashboard.organizations.intro', $json$"Create and manage your organizations: members and roles, projects, repositories, LLM policy, command permissions, MCP servers and skills. Cloning repositories and chatting stay in the JayV app."$json$::jsonb),
  ('en', 'site.org.tab.projects', $json$"Projects"$json$::jsonb),
  ('en', 'site.org.projects.title', $json$"Organization projects"$json$::jsonb),
  ('en', 'site.org.projects.description', $json$"The organization's repositories that members have as projects in the JayV app. Each member has their own copy, with their own chats. Projects of an organization can only be deleted here, by owners and maintainers."$json$::jsonb),
  ('en', 'site.org.projects.empty', $json$"No member has a project from this organization's repositories yet. They show up here once someone clones a repository in the JayV app."$json$::jsonb),
  ('en', 'site.org.projects.failed', $json$"Couldn't load the projects. Try again in a moment."$json$::jsonb),
  ('en', 'site.org.projects.chats', $json${"one": "{count} chat", "other": "{count} chats"}$json$::jsonb),
  ('en', 'site.org.projects.lastActivity', $json$"last activity {date}"$json$::jsonb),
  ('en', 'site.org.projects.delete.label', $json$"Delete the {repo} project"$json$::jsonb),
  ('en', 'site.org.projects.delete.title', $json$"Delete project"$json$::jsonb),
  ('en', 'site.org.projects.delete.description', $json$"Deletes the {repo} project and all of its chats from the JayV app of every member who has it, at their next sync. This can't be undone. The repository stays in the organization, so members can clone it again."$json$::jsonb),
  ('en', 'site.org.projects.deleted', $json$"Project deleted. It leaves each member's app at their next sync."$json$::jsonb),

  ('es', 'org.repoGone', $json$"Este repositorio ya no está en la organización."$json$::jsonb),
  ('es', 'site.dashboard.organizations.intro', $json$"Crea y gestiona tus organizaciones: miembros y roles, proyectos, repositorios, política de LLM, permisos de comandos, servidores MCP y skills. La clonación de los repositorios y los chats siguen en la app de JayV."$json$::jsonb),
  ('es', 'site.org.tab.projects', $json$"Proyectos"$json$::jsonb),
  ('es', 'site.org.projects.title', $json$"Proyectos de la organización"$json$::jsonb),
  ('es', 'site.org.projects.description', $json$"Los repositorios de la organización que los miembros tienen como proyecto en la app de JayV. Cada miembro tiene su propia copia, con sus propios chats. Los proyectos de una organización solo se eliminan aquí, por owners y maintainers."$json$::jsonb),
  ('es', 'site.org.projects.empty', $json$"Ningún miembro tiene todavía un proyecto de los repositorios de esta organización. Aparecen aquí cuando alguien clona un repositorio en la app de JayV."$json$::jsonb),
  ('es', 'site.org.projects.failed', $json$"No se pudieron cargar los proyectos. Vuelve a intentarlo en un momento."$json$::jsonb),
  ('es', 'site.org.projects.chats', $json${"one": "{count} chat", "other": "{count} chats"}$json$::jsonb),
  ('es', 'site.org.projects.lastActivity', $json$"última actividad el {date}"$json$::jsonb),
  ('es', 'site.org.projects.delete.label', $json$"Eliminar el proyecto {repo}"$json$::jsonb),
  ('es', 'site.org.projects.delete.title', $json$"Eliminar proyecto"$json$::jsonb),
  ('es', 'site.org.projects.delete.description', $json$"Elimina el proyecto {repo} y todos sus chats de la app de JayV de cada miembro que lo tiene, en su próxima sincronización. No se puede deshacer. El repositorio sigue en la organización, así que los miembros pueden volver a clonarlo."$json$::jsonb),
  ('es', 'site.org.projects.deleted', $json$"Proyecto eliminado. Sale de la app de cada miembro en su próxima sincronización."$json$::jsonb),

  ('zh-CN', 'org.repoGone', $json$"该仓库已不在此组织中。"$json$::jsonb),
  ('zh-CN', 'site.dashboard.organizations.intro', $json$"创建和管理你的组织：成员和角色、项目、仓库、LLM 策略、命令权限、MCP 服务器和技能。克隆仓库和对话仍在 JayV 应用中进行。"$json$::jsonb),
  ('zh-CN', 'site.org.tab.projects', $json$"项目"$json$::jsonb),
  ('zh-CN', 'site.org.projects.title', $json$"组织的项目"$json$::jsonb),
  ('zh-CN', 'site.org.projects.description', $json$"成员在 JayV 应用中作为项目打开的组织仓库。每个成员都有自己的副本和自己的对话。组织的项目只能在这里由 owner 和 maintainer 删除。"$json$::jsonb),
  ('zh-CN', 'site.org.projects.empty', $json$"还没有成员拥有此组织仓库的项目。有人在 JayV 应用中克隆仓库后，项目会显示在这里。"$json$::jsonb),
  ('zh-CN', 'site.org.projects.failed', $json$"无法加载项目。请稍后再试。"$json$::jsonb),
  ('zh-CN', 'site.org.projects.chats', $json${"other": "{count} 个对话"}$json$::jsonb),
  ('zh-CN', 'site.org.projects.lastActivity', $json$"最近活动于 {date}"$json$::jsonb),
  ('zh-CN', 'site.org.projects.delete.label', $json$"删除项目 {repo}"$json$::jsonb),
  ('zh-CN', 'site.org.projects.delete.title', $json$"删除项目"$json$::jsonb),
  ('zh-CN', 'site.org.projects.delete.description', $json$"将在每位拥有项目 {repo} 的成员下次同步时，从其 JayV 应用中删除该项目及其所有对话。此操作无法撤销。仓库仍保留在组织中，成员可以重新克隆。"$json$::jsonb),
  ('zh-CN', 'site.org.projects.deleted', $json$"项目已删除。每位成员下次同步时，它会从其应用中移除。"$json$::jsonb),

  ('hi', 'org.repoGone', $json$"यह रिपॉज़िटरी अब संगठन में नहीं है।"$json$::jsonb),
  ('hi', 'site.dashboard.organizations.intro', $json$"अपने संगठन बनाएँ और प्रबंधित करें: सदस्य और भूमिकाएँ, प्रोजेक्ट, रिपॉज़िटरी, LLM नीति, कमांड अनुमतियाँ, MCP सर्वर और स्किल्स। रिपॉज़िटरी क्लोन करना और चैट JayV ऐप में ही रहते हैं।"$json$::jsonb),
  ('hi', 'site.org.tab.projects', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'site.org.projects.title', $json$"संगठन के प्रोजेक्ट"$json$::jsonb),
  ('hi', 'site.org.projects.description', $json$"संगठन की वे रिपॉज़िटरी जिन्हें सदस्यों ने JayV ऐप में प्रोजेक्ट के रूप में रखा है। हर सदस्य की अपनी कॉपी होती है, अपनी चैट के साथ। संगठन का प्रोजेक्ट सिर्फ़ यहीं, owner और maintainer हटा सकते हैं।"$json$::jsonb),
  ('hi', 'site.org.projects.empty', $json$"अभी किसी सदस्य के पास इस संगठन की रिपॉज़िटरी का कोई प्रोजेक्ट नहीं है। कोई JayV ऐप में रिपॉज़िटरी क्लोन करता है, तो वे यहाँ दिखते हैं।"$json$::jsonb),
  ('hi', 'site.org.projects.failed', $json$"प्रोजेक्ट लोड नहीं हो सके। थोड़ी देर में फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'site.org.projects.chats', $json${"one": "{count} चैट", "other": "{count} चैट"}$json$::jsonb),
  ('hi', 'site.org.projects.lastActivity', $json$"आख़िरी गतिविधि {date}"$json$::jsonb),
  ('hi', 'site.org.projects.delete.label', $json$"प्रोजेक्ट {repo} हटाएँ"$json$::jsonb),
  ('hi', 'site.org.projects.delete.title', $json$"प्रोजेक्ट हटाएँ"$json$::jsonb),
  ('hi', 'site.org.projects.delete.description', $json$"प्रोजेक्ट {repo} और उसकी सारी चैट उन सभी सदस्यों के JayV ऐप से हटा देता है जिनके पास यह है, उनके अगले सिंक पर। इसे वापस नहीं लिया जा सकता। रिपॉज़िटरी संगठन में बनी रहती है, इसलिए सदस्य इसे फिर से क्लोन कर सकते हैं।"$json$::jsonb),
  ('hi', 'site.org.projects.deleted', $json$"प्रोजेक्ट हटा दिया गया। हर सदस्य के अगले सिंक पर यह उसके ऐप से निकल जाएगा।"$json$::jsonb),

  ('ar', 'org.repoGone', $json$"لم يعد هذا المستودع ضمن المؤسسة."$json$::jsonb),
  ('ar', 'site.dashboard.organizations.intro', $json$"أنشئ مؤسساتك وأدرها: الأعضاء وأدوارهم، والمشاريع، والمستودعات، وسياسة LLM، وأذونات الأوامر، وخوادم MCP، والمهارات. يبقى استنساخ المستودعات والمحادثات في تطبيق JayV."$json$::jsonb),
  ('ar', 'site.org.tab.projects', $json$"المشاريع"$json$::jsonb),
  ('ar', 'site.org.projects.title', $json$"مشاريع المؤسسة"$json$::jsonb),
  ('ar', 'site.org.projects.description', $json$"مستودعات المؤسسة التي يملكها الأعضاء كمشاريع في تطبيق JayV. لكل عضو نسخته الخاصة ومحادثاته الخاصة. لا تُحذف مشاريع المؤسسة إلا من هنا، بواسطة owner وmaintainer."$json$::jsonb),
  ('ar', 'site.org.projects.empty', $json$"لا يملك أي عضو بعد مشروعًا من مستودعات هذه المؤسسة. تظهر هنا عندما يستنسخ أحدهم مستودعًا في تطبيق JayV."$json$::jsonb),
  ('ar', 'site.org.projects.failed', $json$"تعذّر تحميل المشاريع. حاول مرة أخرى بعد قليل."$json$::jsonb),
  ('ar', 'site.org.projects.chats', $json${"zero": "لا محادثات", "one": "محادثة واحدة", "two": "محادثتان", "few": "{count} محادثات", "many": "{count} محادثة", "other": "{count} محادثة"}$json$::jsonb),
  ('ar', 'site.org.projects.lastActivity', $json$"آخر نشاط في {date}"$json$::jsonb),
  ('ar', 'site.org.projects.delete.label', $json$"حذف المشروع {repo}"$json$::jsonb),
  ('ar', 'site.org.projects.delete.title', $json$"حذف المشروع"$json$::jsonb),
  ('ar', 'site.org.projects.delete.description', $json$"يحذف المشروع {repo} وكل محادثاته من تطبيق JayV لدى كل عضو يملكه، عند المزامنة التالية لكل منهم. لا يمكن التراجع عن ذلك. يبقى المستودع في المؤسسة، فيمكن للأعضاء استنساخه من جديد."$json$::jsonb),
  ('ar', 'site.org.projects.deleted', $json$"حُذف المشروع. سيختفي من تطبيق كل عضو عند مزامنته التالية."$json$::jsonb),

  ('fr', 'org.repoGone', $json$"Ce dépôt ne fait plus partie de l'organisation."$json$::jsonb),
  ('fr', 'site.dashboard.organizations.intro', $json$"Créez et gérez vos organisations : membres et rôles, projets, dépôts, politique LLM, autorisations de commandes, serveurs MCP et skills. Le clonage des dépôts et les chats restent dans l'app JayV."$json$::jsonb),
  ('fr', 'site.org.tab.projects', $json$"Projets"$json$::jsonb),
  ('fr', 'site.org.projects.title', $json$"Projets de l'organisation"$json$::jsonb),
  ('fr', 'site.org.projects.description', $json$"Les dépôts de l'organisation que les membres ont comme projet dans l'app JayV. Chaque membre a sa propre copie, avec ses propres chats. Les projets d'une organisation ne se suppriment qu'ici, par les owners et maintainers."$json$::jsonb),
  ('fr', 'site.org.projects.empty', $json$"Aucun membre n'a encore de projet issu des dépôts de cette organisation. Ils apparaissent ici dès que quelqu'un clone un dépôt dans l'app JayV."$json$::jsonb),
  ('fr', 'site.org.projects.failed', $json$"Impossible de charger les projets. Réessayez dans un instant."$json$::jsonb),
  ('fr', 'site.org.projects.chats', $json${"one": "{count} chat", "other": "{count} chats"}$json$::jsonb),
  ('fr', 'site.org.projects.lastActivity', $json$"dernière activité le {date}"$json$::jsonb),
  ('fr', 'site.org.projects.delete.label', $json$"Supprimer le projet {repo}"$json$::jsonb),
  ('fr', 'site.org.projects.delete.title', $json$"Supprimer le projet"$json$::jsonb),
  ('fr', 'site.org.projects.delete.description', $json$"Supprime le projet {repo} et tous ses chats de l'app JayV de chaque membre qui l'a, à sa prochaine synchronisation. C'est irréversible. Le dépôt reste dans l'organisation : les membres peuvent le cloner à nouveau."$json$::jsonb),
  ('fr', 'site.org.projects.deleted', $json$"Projet supprimé. Il disparaît de l'app de chaque membre à sa prochaine synchronisation."$json$::jsonb),

  ('ru', 'org.repoGone', $json$"Этого репозитория больше нет в организации."$json$::jsonb),
  ('ru', 'site.dashboard.organizations.intro', $json$"Создавайте организации и управляйте ими: участники и роли, проекты, репозитории, политика LLM, разрешения команд, MCP-серверы и скиллы. Клонирование репозиториев и чаты остаются в приложении JayV."$json$::jsonb),
  ('ru', 'site.org.tab.projects', $json$"Проекты"$json$::jsonb),
  ('ru', 'site.org.projects.title', $json$"Проекты организации"$json$::jsonb),
  ('ru', 'site.org.projects.description', $json$"Репозитории организации, которые участники открыли как проекты в приложении JayV. У каждого участника своя копия со своими чатами. Проекты организации удаляются только здесь — owner и maintainer."$json$::jsonb),
  ('ru', 'site.org.projects.empty', $json$"Пока ни у одного участника нет проекта из репозиториев этой организации. Они появятся здесь, когда кто-нибудь клонирует репозиторий в приложении JayV."$json$::jsonb),
  ('ru', 'site.org.projects.failed', $json$"Не удалось загрузить проекты. Попробуйте ещё раз чуть позже."$json$::jsonb),
  ('ru', 'site.org.projects.chats', $json${"one": "{count} чат", "few": "{count} чата", "many": "{count} чатов", "other": "{count} чата"}$json$::jsonb),
  ('ru', 'site.org.projects.lastActivity', $json$"последняя активность {date}"$json$::jsonb),
  ('ru', 'site.org.projects.delete.label', $json$"Удалить проект {repo}"$json$::jsonb),
  ('ru', 'site.org.projects.delete.title', $json$"Удалить проект"$json$::jsonb),
  ('ru', 'site.org.projects.delete.description', $json$"Удаляет проект {repo} и все его чаты из приложения JayV у каждого участника, у которого он есть, при его следующей синхронизации. Это нельзя отменить. Репозиторий остаётся в организации, и участники могут клонировать его снова."$json$::jsonb),
  ('ru', 'site.org.projects.deleted', $json$"Проект удалён. Он исчезнет из приложения каждого участника при следующей синхронизации."$json$::jsonb),

  ('ja', 'org.repoGone', $json$"このリポジトリはもう組織にありません。"$json$::jsonb),
  ('ja', 'site.dashboard.organizations.intro', $json$"組織の作成と管理ができます：メンバーと役割、プロジェクト、リポジトリ、LLM ポリシー、コマンドの許可、MCP サーバー、スキル。リポジトリのクローンとチャットは引き続き JayV アプリで行います。"$json$::jsonb),
  ('ja', 'site.org.tab.projects', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'site.org.projects.title', $json$"組織のプロジェクト"$json$::jsonb),
  ('ja', 'site.org.projects.description', $json$"メンバーが JayV アプリでプロジェクトとして持っている組織のリポジトリです。各メンバーは自分のチャット付きで自分のコピーを持っています。組織のプロジェクトを削除できるのはここだけで、owner と maintainer のみです。"$json$::jsonb),
  ('ja', 'site.org.projects.empty', $json$"この組織のリポジトリのプロジェクトを持っているメンバーはまだいません。誰かが JayV アプリでリポジトリをクローンすると、ここに表示されます。"$json$::jsonb),
  ('ja', 'site.org.projects.failed', $json$"プロジェクトを読み込めませんでした。しばらくしてからもう一度お試しください。"$json$::jsonb),
  ('ja', 'site.org.projects.chats', $json${"other": "チャット {count} 件"}$json$::jsonb),
  ('ja', 'site.org.projects.lastActivity', $json$"最終アクティビティ {date}"$json$::jsonb),
  ('ja', 'site.org.projects.delete.label', $json$"プロジェクト {repo} を削除"$json$::jsonb),
  ('ja', 'site.org.projects.delete.title', $json$"プロジェクトを削除"$json$::jsonb),
  ('ja', 'site.org.projects.delete.description', $json$"プロジェクト {repo} とそのすべてのチャットを、それを持つ各メンバーの JayV アプリから、それぞれの次回の同期時に削除します。元に戻すことはできません。リポジトリは組織に残るため、メンバーはもう一度クローンできます。"$json$::jsonb),
  ('ja', 'site.org.projects.deleted', $json$"プロジェクトを削除しました。各メンバーの次回の同期時にアプリから消えます。"$json$::jsonb),

  ('de', 'org.repoGone', $json$"Dieses Repository gehört nicht mehr zur Organisation."$json$::jsonb),
  ('de', 'site.dashboard.organizations.intro', $json$"Erstelle und verwalte deine Organisationen: Mitglieder und Rollen, Projekte, Repositories, LLM-Richtlinie, Befehlsberechtigungen, MCP-Server und Skills. Das Klonen der Repositories und die Chats bleiben in der JayV-App."$json$::jsonb),
  ('de', 'site.org.tab.projects', $json$"Projekte"$json$::jsonb),
  ('de', 'site.org.projects.title', $json$"Projekte der Organisation"$json$::jsonb),
  ('de', 'site.org.projects.description', $json$"Die Repositories der Organisation, die Mitglieder in der JayV-App als Projekt haben. Jedes Mitglied hat seine eigene Kopie mit eigenen Chats. Projekte einer Organisation werden nur hier gelöscht, von Ownern und Maintainern."$json$::jsonb),
  ('de', 'site.org.projects.empty', $json$"Noch hat kein Mitglied ein Projekt aus den Repositories dieser Organisation. Sie erscheinen hier, sobald jemand ein Repository in der JayV-App klont."$json$::jsonb),
  ('de', 'site.org.projects.failed', $json$"Die Projekte konnten nicht geladen werden. Versuche es gleich noch einmal."$json$::jsonb),
  ('de', 'site.org.projects.chats', $json${"one": "{count} Chat", "other": "{count} Chats"}$json$::jsonb),
  ('de', 'site.org.projects.lastActivity', $json$"letzte Aktivität am {date}"$json$::jsonb),
  ('de', 'site.org.projects.delete.label', $json$"Projekt {repo} löschen"$json$::jsonb),
  ('de', 'site.org.projects.delete.title', $json$"Projekt löschen"$json$::jsonb),
  ('de', 'site.org.projects.delete.description', $json$"Löscht das Projekt {repo} und alle seine Chats aus der JayV-App jedes Mitglieds, das es hat, bei dessen nächster Synchronisierung. Das lässt sich nicht rückgängig machen. Das Repository bleibt in der Organisation, sodass die Mitglieder es erneut klonen können."$json$::jsonb),
  ('de', 'site.org.projects.deleted', $json$"Projekt gelöscht. Es verschwindet bei der nächsten Synchronisierung aus der App jedes Mitglieds."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
