-- App 0.86.0: textos dos ambientes separados (pessoal e organizações), nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'environment.personal', $json$"Pessoal"$json$::jsonb),
  ('pt-BR', 'environment.label', $json$"Ambiente"$json$::jsonb),
  ('pt-BR', 'environment.switching', $json$"Trocando de ambiente…"$json$::jsonb),
  ('pt-BR', 'environment.banner', $json$"{org} mantém seus projetos, chats, clones e uso no próprio ambiente. Troque para ele para usá-los."$json$::jsonb),
  ('pt-BR', 'environment.switchTo', $json$"Trocar para {name}"$json$::jsonb),
  ('pt-BR', 'environment.current', $json$"Ambiente: {name}"$json$::jsonb),
  ('pt-BR', 'environment.unknown', $json$"Ambiente desconhecido: {environment}"$json$::jsonb),
  ('pt-BR', 'environment.notMember', $json$"Você não é membro desta organização."$json$::jsonb),
  ('pt-BR', 'environment.listFailed', $json$"Não foi possível verificar seus ambientes: {reason}"$json$::jsonb),
  ('pt-BR', 'palette.environment', $json$"Trocar para o ambiente: {name}"$json$::jsonb),
  ('pt-BR', 'docs.environments.title', $json$"Ambientes"$json$::jsonb),
  ('pt-BR', 'docs.environments.summary', $json$"Seus projetos pessoais e cada organização vivem em ambientes separados. Cada um guarda seus próprios projetos, chats, notas, uso e configurações (agentes, modelos, servidores MCP, skills e permissões), então nada de um vaza para o outro. Seu perfil, idioma, tema, plano e login em duas etapas são os mesmos em todo lugar, assim como o limite do plano de cada agente."$json$::jsonb),
  ('pt-BR', 'docs.environments.usage', $json$"Com pelo menos uma organização, um seletor abaixo do logotipo lista Pessoal e suas organizações; ao escolher uma, a janela recarrega com os dados daquele ambiente. Um ambiente de organização novo começa com as configurações padrão e sem projetos: ligue o que precisar em Configurações e use a página da organização para abrir o chat geral ou clonar os repositórios dela. No Ctrl+K, escolha \"Trocar para o ambiente\" do que quiser. Os projetos que você já tinha de uma organização foram para o ambiente dela na primeira abertura após atualizar, e uma cópia do banco pessoal antigo fica ao lado dele."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.environments.title', $json$"Ambientes separados"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.environments.detail', $json$"Seus projetos pessoais e cada organização agora têm o próprio ambiente, com projetos, chats, notas, uso e configurações próprios. Troque entre eles abaixo do logotipo ou com Ctrl+K. Perfil, idioma, tema e plano continuam os mesmos, e o limite do plano de cada agente segue compartilhado. Os projetos que eram de uma organização foram para o ambiente dela."$json$::jsonb),
  ('en', 'environment.personal', $json$"Personal"$json$::jsonb),
  ('en', 'environment.label', $json$"Environment"$json$::jsonb),
  ('en', 'environment.switching', $json$"Switching environment…"$json$::jsonb),
  ('en', 'environment.banner', $json$"{org} keeps its projects, chats, clones and usage in its own environment. Switch to it to use them."$json$::jsonb),
  ('en', 'environment.switchTo', $json$"Switch to {name}"$json$::jsonb),
  ('en', 'environment.current', $json$"Environment: {name}"$json$::jsonb),
  ('en', 'environment.unknown', $json$"Unknown environment: {environment}"$json$::jsonb),
  ('en', 'environment.notMember', $json$"You are not a member of this organization."$json$::jsonb),
  ('en', 'environment.listFailed', $json$"Could not check your environments: {reason}"$json$::jsonb),
  ('en', 'palette.environment', $json$"Switch to environment: {name}"$json$::jsonb),
  ('en', 'docs.environments.title', $json$"Environments"$json$::jsonb),
  ('en', 'docs.environments.summary', $json$"Your personal projects and each organization live in separate environments. Each one keeps its own projects, chats, notes, usage and settings (agents, models, MCP servers, skills and permissions), so nothing from one leaks into another. Your profile, language, theme, plan and two-factor sign-in are the same everywhere, and so is the limit of each agent's plan."$json$::jsonb),
  ('en', 'docs.environments.usage', $json$"With at least one organization, a selector under the logo lists Personal and your organizations; choosing one reloads the window with that environment's data. A new organization environment starts with the default settings and no projects: turn on what you need in Settings, and use the organization's page to open its general chat or clone its repositories. In Ctrl+K, choose \"Switch to environment\" for the one you want. Projects you already had for an organization moved to its environment at the first start after updating, and a copy of the old personal database stays next to it."$json$::jsonb),
  ('en', 'whatsNew.item.environments.title', $json$"Separate environments"$json$::jsonb),
  ('en', 'whatsNew.item.environments.detail', $json$"Your personal projects and each organization now have their own environment, with their own projects, chats, notes, usage and settings. Switch between them under the logo or with Ctrl+K. Your profile, language, theme and plan stay the same, and the usage limit of each agent's plan is still shared. Projects that belonged to an organization moved to its environment."$json$::jsonb),
  ('es', 'environment.personal', $json$"Personal"$json$::jsonb),
  ('es', 'environment.label', $json$"Entorno"$json$::jsonb),
  ('es', 'environment.switching', $json$"Cambiando de entorno…"$json$::jsonb),
  ('es', 'environment.banner', $json$"{org} guarda sus proyectos, chats, clones y uso en su propio entorno. Cambia a él para usarlos."$json$::jsonb),
  ('es', 'environment.switchTo', $json$"Cambiar a {name}"$json$::jsonb),
  ('es', 'environment.current', $json$"Entorno: {name}"$json$::jsonb),
  ('es', 'environment.unknown', $json$"Entorno desconocido: {environment}"$json$::jsonb),
  ('es', 'environment.notMember', $json$"No eres miembro de esta organización."$json$::jsonb),
  ('es', 'environment.listFailed', $json$"No se pudieron comprobar tus entornos: {reason}"$json$::jsonb),
  ('es', 'palette.environment', $json$"Cambiar al entorno: {name}"$json$::jsonb),
  ('es', 'docs.environments.title', $json$"Entornos"$json$::jsonb),
  ('es', 'docs.environments.summary', $json$"Tus proyectos personales y cada organización viven en entornos separados. Cada uno guarda sus propios proyectos, chats, notas, uso y ajustes (agentes, modelos, servidores MCP, skills y permisos), así que nada de uno pasa al otro. Tu perfil, idioma, tema, plan e inicio de sesión en dos pasos son los mismos en todas partes, igual que el límite del plan de cada agente."$json$::jsonb),
  ('es', 'docs.environments.usage', $json$"Con al menos una organización, un selector bajo el logotipo lista Personal y tus organizaciones; al elegir una, la ventana se recarga con los datos de ese entorno. Un entorno de organización nuevo empieza con los ajustes predeterminados y sin proyectos: activa lo que necesites en Ajustes y usa la página de la organización para abrir su chat general o clonar sus repositorios. En Ctrl+K elige \"Cambiar al entorno\" del que quieras. Los proyectos que ya tenías de una organización pasaron a su entorno en el primer inicio tras actualizar, y una copia de la base personal anterior queda a su lado."$json$::jsonb),
  ('es', 'whatsNew.item.environments.title', $json$"Entornos separados"$json$::jsonb),
  ('es', 'whatsNew.item.environments.detail', $json$"Tus proyectos personales y cada organización ahora tienen su propio entorno, con sus proyectos, chats, notas, uso y ajustes. Cambia entre ellos bajo el logotipo o con Ctrl+K. Perfil, idioma, tema y plan siguen igual, y el límite del plan de cada agente sigue compartido. Los proyectos que eran de una organización pasaron a su entorno."$json$::jsonb),
  ('fr', 'environment.personal', $json$"Personnel"$json$::jsonb),
  ('fr', 'environment.label', $json$"Environnement"$json$::jsonb),
  ('fr', 'environment.switching', $json$"Changement d'environnement…"$json$::jsonb),
  ('fr', 'environment.banner', $json$"{org} garde ses projets, chats, clones et son usage dans son propre environnement. Basculez vers lui pour les utiliser."$json$::jsonb),
  ('fr', 'environment.switchTo', $json$"Basculer vers {name}"$json$::jsonb),
  ('fr', 'environment.current', $json$"Environnement : {name}"$json$::jsonb),
  ('fr', 'environment.unknown', $json$"Environnement inconnu : {environment}"$json$::jsonb),
  ('fr', 'environment.notMember', $json$"Vous n'êtes pas membre de cette organisation."$json$::jsonb),
  ('fr', 'environment.listFailed', $json$"Impossible de vérifier vos environnements : {reason}"$json$::jsonb),
  ('fr', 'palette.environment', $json$"Basculer vers l'environnement : {name}"$json$::jsonb),
  ('fr', 'docs.environments.title', $json$"Environnements"$json$::jsonb),
  ('fr', 'docs.environments.summary', $json$"Vos projets personnels et chaque organisation vivent dans des environnements séparés. Chacun garde ses propres projets, chats, notes, usage et réglages (agents, modèles, serveurs MCP, skills et autorisations), donc rien de l'un ne passe dans l'autre. Votre profil, langue, thème, forfait et connexion en deux étapes sont les mêmes partout, tout comme la limite du forfait de chaque agent."$json$::jsonb),
  ('fr', 'docs.environments.usage', $json$"Avec au moins une organisation, un sélecteur sous le logo liste Personnel et vos organisations ; en choisir une recharge la fenêtre avec les données de cet environnement. Un nouvel environnement d'organisation démarre avec les réglages par défaut et sans projet : activez ce qu'il vous faut dans Réglages et utilisez la page de l'organisation pour ouvrir son chat général ou cloner ses dépôts. Dans Ctrl+K, choisissez « Basculer vers l'environnement » voulu. Les projets que vous aviez déjà pour une organisation sont passés dans son environnement au premier démarrage après la mise à jour, et une copie de l'ancienne base personnelle reste à côté."$json$::jsonb),
  ('fr', 'whatsNew.item.environments.title', $json$"Environnements séparés"$json$::jsonb),
  ('fr', 'whatsNew.item.environments.detail', $json$"Vos projets personnels et chaque organisation ont maintenant leur propre environnement, avec leurs projets, chats, notes, usage et réglages. Basculez de l'un à l'autre sous le logo ou avec Ctrl+K. Profil, langue, thème et forfait restent les mêmes, et la limite du forfait de chaque agent reste partagée. Les projets qui appartenaient à une organisation sont passés dans son environnement."$json$::jsonb),
  ('de', 'environment.personal', $json$"Persönlich"$json$::jsonb),
  ('de', 'environment.label', $json$"Umgebung"$json$::jsonb),
  ('de', 'environment.switching', $json$"Umgebung wird gewechselt…"$json$::jsonb),
  ('de', 'environment.banner', $json$"{org} hält ihre Projekte, Chats, Klone und Nutzung in einer eigenen Umgebung. Wechsle zu ihr, um sie zu nutzen."$json$::jsonb),
  ('de', 'environment.switchTo', $json$"Zu {name} wechseln"$json$::jsonb),
  ('de', 'environment.current', $json$"Umgebung: {name}"$json$::jsonb),
  ('de', 'environment.unknown', $json$"Unbekannte Umgebung: {environment}"$json$::jsonb),
  ('de', 'environment.notMember', $json$"Du bist kein Mitglied dieser Organisation."$json$::jsonb),
  ('de', 'environment.listFailed', $json$"Deine Umgebungen konnten nicht geprüft werden: {reason}"$json$::jsonb),
  ('de', 'palette.environment', $json$"Zur Umgebung wechseln: {name}"$json$::jsonb),
  ('de', 'docs.environments.title', $json$"Umgebungen"$json$::jsonb),
  ('de', 'docs.environments.summary', $json$"Deine persönlichen Projekte und jede Organisation leben in getrennten Umgebungen. Jede hält ihre eigenen Projekte, Chats, Notizen, Nutzung und Einstellungen (Agenten, Modelle, MCP-Server, Skills und Berechtigungen), sodass nichts von einer in die andere gelangt. Dein Profil, deine Sprache, dein Design, dein Tarif und die Zwei-Faktor-Anmeldung sind überall gleich, ebenso das Limit des Tarifs jedes Agenten."$json$::jsonb),
  ('de', 'docs.environments.usage', $json$"Mit mindestens einer Organisation listet ein Umschalter unter dem Logo Persönlich und deine Organisationen; die Auswahl lädt das Fenster mit den Daten dieser Umgebung neu. Eine neue Organisationsumgebung startet mit den Standardeinstellungen und ohne Projekte: Schalte in den Einstellungen ein, was du brauchst, und öffne über die Seite der Organisation ihren allgemeinen Chat oder klone ihre Repositories. Wähle in Strg+K „Zur Umgebung wechseln“ für die gewünschte. Projekte, die du schon für eine Organisation hattest, sind beim ersten Start nach dem Update in deren Umgebung gewandert, und eine Kopie der alten persönlichen Datenbank bleibt daneben."$json$::jsonb),
  ('de', 'whatsNew.item.environments.title', $json$"Getrennte Umgebungen"$json$::jsonb),
  ('de', 'whatsNew.item.environments.detail', $json$"Deine persönlichen Projekte und jede Organisation haben jetzt ihre eigene Umgebung mit eigenen Projekten, Chats, Notizen, Nutzung und Einstellungen. Wechsle zwischen ihnen unter dem Logo oder mit Strg+K. Profil, Sprache, Design und Tarif bleiben gleich, und das Limit des Tarifs jedes Agenten bleibt geteilt. Projekte, die zu einer Organisation gehörten, sind in deren Umgebung gewandert."$json$::jsonb),
  ('ru', 'environment.personal', $json$"Личное"$json$::jsonb),
  ('ru', 'environment.label', $json$"Среда"$json$::jsonb),
  ('ru', 'environment.switching', $json$"Переключение среды…"$json$::jsonb),
  ('ru', 'environment.banner', $json$"{org} хранит свои проекты, чаты, клоны и расход в собственной среде. Переключитесь на неё, чтобы ими пользоваться."$json$::jsonb),
  ('ru', 'environment.switchTo', $json$"Переключиться на {name}"$json$::jsonb),
  ('ru', 'environment.current', $json$"Среда: {name}"$json$::jsonb),
  ('ru', 'environment.unknown', $json$"Неизвестная среда: {environment}"$json$::jsonb),
  ('ru', 'environment.notMember', $json$"Вы не участник этой организации."$json$::jsonb),
  ('ru', 'environment.listFailed', $json$"Не удалось проверить ваши среды: {reason}"$json$::jsonb),
  ('ru', 'palette.environment', $json$"Переключиться на среду: {name}"$json$::jsonb),
  ('ru', 'docs.environments.title', $json$"Среды"$json$::jsonb),
  ('ru', 'docs.environments.summary', $json$"Ваши личные проекты и каждая организация живут в отдельных средах. В каждой свои проекты, чаты, заметки, расход и настройки (агенты, модели, серверы MCP, skills и разрешения), поэтому ничто из одной не попадает в другую. Профиль, язык, тема, тариф и двухфакторный вход одинаковы везде, как и лимит тарифа каждого агента."$json$::jsonb),
  ('ru', 'docs.environments.usage', $json$"Если есть хотя бы одна организация, переключатель под логотипом перечисляет «Личное» и ваши организации; выбор перезагружает окно с данными этой среды. Новая среда организации начинается с настроек по умолчанию и без проектов: включите нужное в Настройках, а на странице организации откройте её общий чат или клонируйте репозитории. В Ctrl+K выберите «Переключиться на среду» нужной. Проекты, которые у вас уже были для организации, при первом запуске после обновления перешли в её среду, а копия прежней личной базы остаётся рядом."$json$::jsonb),
  ('ru', 'whatsNew.item.environments.title', $json$"Раздельные среды"$json$::jsonb),
  ('ru', 'whatsNew.item.environments.detail', $json$"У ваших личных проектов и у каждой организации теперь своя среда со своими проектами, чатами, заметками, расходом и настройками. Переключайтесь между ними под логотипом или через Ctrl+K. Профиль, язык, тема и тариф остаются прежними, а лимит тарифа каждого агента по-прежнему общий. Проекты, принадлежавшие организации, перешли в её среду."$json$::jsonb),
  ('zh-CN', 'environment.personal', $json$"个人"$json$::jsonb),
  ('zh-CN', 'environment.label', $json$"环境"$json$::jsonb),
  ('zh-CN', 'environment.switching', $json$"正在切换环境…"$json$::jsonb),
  ('zh-CN', 'environment.banner', $json$"{org} 的项目、聊天、克隆和用量都保存在它自己的环境中。切换到该环境即可使用。"$json$::jsonb),
  ('zh-CN', 'environment.switchTo', $json$"切换到 {name}"$json$::jsonb),
  ('zh-CN', 'environment.current', $json$"环境：{name}"$json$::jsonb),
  ('zh-CN', 'environment.unknown', $json$"未知环境：{environment}"$json$::jsonb),
  ('zh-CN', 'environment.notMember', $json$"你不是该组织的成员。"$json$::jsonb),
  ('zh-CN', 'environment.listFailed', $json$"无法检查你的环境：{reason}"$json$::jsonb),
  ('zh-CN', 'palette.environment', $json$"切换到环境：{name}"$json$::jsonb),
  ('zh-CN', 'docs.environments.title', $json$"环境"$json$::jsonb),
  ('zh-CN', 'docs.environments.summary', $json$"你的个人项目和每个组织都在各自独立的环境中。每个环境保存自己的项目、聊天、笔记、用量和设置（代理、模型、MCP 服务器、skills 和权限），因此互不泄漏。你的资料、语言、主题、套餐和两步验证在所有环境中相同，各代理套餐的额度也是共享的。"$json$::jsonb),
  ('zh-CN', 'docs.environments.usage', $json$"只要有至少一个组织，logo 下方的选择器就会列出“个人”和你的组织；选择其一会用该环境的数据重新加载窗口。新的组织环境以默认设置且没有项目开始：在设置中打开所需内容，并通过组织页面打开其通用聊天或克隆其仓库。在 Ctrl+K 中选择“切换到环境”即可切换。你之前属于某个组织的项目，会在更新后首次启动时移到该组织的环境，旧的个人数据库副本保留在旁边。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.environments.title', $json$"独立环境"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.environments.detail', $json$"你的个人项目和每个组织现在都有自己的环境，拥有各自的项目、聊天、笔记、用量和设置。可在 logo 下方或用 Ctrl+K 切换。资料、语言、主题和套餐保持不变，各代理套餐的额度仍然共享。原本属于某个组织的项目已移到它的环境。"$json$::jsonb),
  ('ja', 'environment.personal', $json$"個人"$json$::jsonb),
  ('ja', 'environment.label', $json$"環境"$json$::jsonb),
  ('ja', 'environment.switching', $json$"環境を切り替えています…"$json$::jsonb),
  ('ja', 'environment.banner', $json$"{org} のプロジェクト、チャット、クローン、使用量は専用の環境に保存されます。使うにはその環境に切り替えてください。"$json$::jsonb),
  ('ja', 'environment.switchTo', $json$"{name} に切り替え"$json$::jsonb),
  ('ja', 'environment.current', $json$"環境：{name}"$json$::jsonb),
  ('ja', 'environment.unknown', $json$"不明な環境：{environment}"$json$::jsonb),
  ('ja', 'environment.notMember', $json$"この組織のメンバーではありません。"$json$::jsonb),
  ('ja', 'environment.listFailed', $json$"環境を確認できませんでした：{reason}"$json$::jsonb),
  ('ja', 'palette.environment', $json$"環境に切り替え：{name}"$json$::jsonb),
  ('ja', 'docs.environments.title', $json$"環境"$json$::jsonb),
  ('ja', 'docs.environments.summary', $json$"個人のプロジェクトと各組織は別々の環境にあります。それぞれが自分のプロジェクト、チャット、ノート、使用量、設定（エージェント、モデル、MCP サーバー、スキル、権限）を持つため、互いに混ざりません。プロフィール、言語、テーマ、プラン、2 段階認証はどこでも共通で、各エージェントのプランの上限も共有されます。"$json$::jsonb),
  ('ja', 'docs.environments.usage', $json$"組織が 1 つ以上あると、ロゴの下のセレクターに「個人」と組織が並び、選ぶとその環境のデータでウィンドウが再読み込みされます。新しい組織の環境は既定の設定でプロジェクトなしから始まります。設定で必要なものをオンにし、組織ページから全体チャットを開くかリポジトリをクローンしてください。Ctrl+K で「環境に切り替え」を選ぶと目的の環境に移れます。以前から組織に属していたプロジェクトは、更新後の初回起動でその組織の環境に移り、以前の個人データベースのコピーは隣に残ります。"$json$::jsonb),
  ('ja', 'whatsNew.item.environments.title', $json$"環境の分離"$json$::jsonb),
  ('ja', 'whatsNew.item.environments.detail', $json$"個人のプロジェクトと各組織に、それぞれ専用の環境ができました。プロジェクト、チャット、ノート、使用量、設定は環境ごとです。ロゴの下または Ctrl+K で切り替えられます。プロフィール、言語、テーマ、プランは共通で、各エージェントのプランの上限も共有のままです。組織に属していたプロジェクトはその組織の環境に移りました。"$json$::jsonb),
  ('hi', 'environment.personal', $json$"व्यक्तिगत"$json$::jsonb),
  ('hi', 'environment.label', $json$"परिवेश"$json$::jsonb),
  ('hi', 'environment.switching', $json$"परिवेश बदला जा रहा है…"$json$::jsonb),
  ('hi', 'environment.banner', $json$"{org} अपने प्रोजेक्ट, चैट, क्लोन और उपयोग अपने परिवेश में रखता है। उन्हें इस्तेमाल करने के लिए उसी पर जाएँ।"$json$::jsonb),
  ('hi', 'environment.switchTo', $json$"{name} पर जाएँ"$json$::jsonb),
  ('hi', 'environment.current', $json$"परिवेश: {name}"$json$::jsonb),
  ('hi', 'environment.unknown', $json$"अज्ञात परिवेश: {environment}"$json$::jsonb),
  ('hi', 'environment.notMember', $json$"आप इस संगठन के सदस्य नहीं हैं।"$json$::jsonb),
  ('hi', 'environment.listFailed', $json$"आपके परिवेश जाँचे नहीं जा सके: {reason}"$json$::jsonb),
  ('hi', 'palette.environment', $json$"परिवेश पर जाएँ: {name}"$json$::jsonb),
  ('hi', 'docs.environments.title', $json$"परिवेश"$json$::jsonb),
  ('hi', 'docs.environments.summary', $json$"आपके व्यक्तिगत प्रोजेक्ट और हर संगठन अलग-अलग परिवेश में रहते हैं। हर परिवेश के अपने प्रोजेक्ट, चैट, नोट्स, उपयोग और सेटिंग (एजेंट, मॉडल, MCP सर्वर, स्किल और अनुमतियाँ) होते हैं, इसलिए एक की चीज़ें दूसरे में नहीं जातीं। आपकी प्रोफ़ाइल, भाषा, थीम, प्लान और दो-चरण साइन-इन हर जगह समान हैं, और हर एजेंट के प्लान की सीमा भी साझा है।"$json$::jsonb),
  ('hi', 'docs.environments.usage', $json$"कम से कम एक संगठन होने पर लोगो के नीचे का चयनकर्ता व्यक्तिगत और आपके संगठनों को सूचीबद्ध करता है; एक चुनने पर विंडो उस परिवेश के डेटा के साथ फिर से लोड होती है। नया संगठन परिवेश डिफ़ॉल्ट सेटिंग और बिना प्रोजेक्ट के शुरू होता है: सेटिंग में जो चाहिए चालू करें और संगठन के पेज से उसकी सामान्य चैट खोलें या उसकी रिपॉज़िटरी क्लोन करें। Ctrl+K में मनचाहे परिवेश के लिए \"परिवेश पर जाएँ\" चुनें। किसी संगठन के जो प्रोजेक्ट आपके पास पहले से थे, वे अपडेट के बाद पहली शुरुआत पर उसके परिवेश में चले गए, और पुराने व्यक्तिगत डेटाबेस की एक प्रति उसके बगल में रहती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.environments.title', $json$"अलग-अलग परिवेश"$json$::jsonb),
  ('hi', 'whatsNew.item.environments.detail', $json$"आपके व्यक्तिगत प्रोजेक्ट और हर संगठन का अब अपना परिवेश है, जिसमें उनके अपने प्रोजेक्ट, चैट, नोट्स, उपयोग और सेटिंग हैं। लोगो के नीचे या Ctrl+K से इनके बीच बदलें। प्रोफ़ाइल, भाषा, थीम और प्लान वही रहते हैं, और हर एजेंट के प्लान की सीमा अब भी साझा है। जो प्रोजेक्ट किसी संगठन के थे, वे उसके परिवेश में चले गए।"$json$::jsonb),
  ('ar', 'environment.personal', $json$"شخصي"$json$::jsonb),
  ('ar', 'environment.label', $json$"البيئة"$json$::jsonb),
  ('ar', 'environment.switching', $json$"جارٍ تبديل البيئة…"$json$::jsonb),
  ('ar', 'environment.banner', $json$"تحتفظ {org} بمشاريعها ومحادثاتها ونسخها واستخدامها في بيئتها الخاصة. بدّل إليها لاستخدامها."$json$::jsonb),
  ('ar', 'environment.switchTo', $json$"التبديل إلى {name}"$json$::jsonb),
  ('ar', 'environment.current', $json$"البيئة: {name}"$json$::jsonb),
  ('ar', 'environment.unknown', $json$"بيئة غير معروفة: {environment}"$json$::jsonb),
  ('ar', 'environment.notMember', $json$"لست عضوًا في هذه المؤسسة."$json$::jsonb),
  ('ar', 'environment.listFailed', $json$"تعذّر التحقق من بيئاتك: {reason}"$json$::jsonb),
  ('ar', 'palette.environment', $json$"التبديل إلى البيئة: {name}"$json$::jsonb),
  ('ar', 'docs.environments.title', $json$"البيئات"$json$::jsonb),
  ('ar', 'docs.environments.summary', $json$"مشاريعك الشخصية وكل مؤسسة تعيش في بيئات منفصلة. تحتفظ كل بيئة بمشاريعها ومحادثاتها وملاحظاتها واستخدامها وإعداداتها (الوكلاء والنماذج وخوادم MCP والمهارات والأذونات)، فلا يتسرب شيء من إحداها إلى الأخرى. ملفك الشخصي ولغتك والمظهر والخطة وتسجيل الدخول بخطوتين واحدة في كل مكان، وكذلك حد خطة كل وكيل."$json$::jsonb),
  ('ar', 'docs.environments.usage', $json$"عند وجود مؤسسة واحدة على الأقل، تعرض أداة الاختيار تحت الشعار «شخصي» ومؤسساتك؛ واختيار إحداها يعيد تحميل النافذة ببيانات تلك البيئة. تبدأ بيئة المؤسسة الجديدة بالإعدادات الافتراضية وبلا مشاريع: فعّل ما تحتاجه في الإعدادات واستخدم صفحة المؤسسة لفتح محادثتها العامة أو نسخ مستودعاتها. في Ctrl+K اختر «التبديل إلى البيئة» التي تريدها. المشاريع التي كانت لديك لمؤسسة انتقلت إلى بيئتها عند أول تشغيل بعد التحديث، وتبقى نسخة من قاعدة البيانات الشخصية القديمة بجانبها."$json$::jsonb),
  ('ar', 'whatsNew.item.environments.title', $json$"بيئات منفصلة"$json$::jsonb),
  ('ar', 'whatsNew.item.environments.detail', $json$"صار لمشاريعك الشخصية ولكل مؤسسة بيئتها الخاصة بمشاريعها ومحادثاتها وملاحظاتها واستخدامها وإعداداتها. بدّل بينها تحت الشعار أو بـ Ctrl+K. يبقى الملف الشخصي واللغة والمظهر والخطة كما هي، ويظل حد خطة كل وكيل مشتركًا. المشاريع التي كانت لمؤسسة انتقلت إلى بيئتها."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
