-- Site v1.3.0: os textos novos do site, nos dez idiomas.
--   site.nav.*            o menu da conta no cabeçalho (foto, nome, e-mail e o
--                         ponto de conectado) e o menu do celular
--   site.releases.*       a página Notas da versão (/releases)
--   site.docs.*           a página Documentação (/docs)
--   site.account.photo.*  a foto de perfil com recorte (migração profile_photo)
insert into public.translations (locale, key, value) values
  ('pt-BR', 'site.nav.docs', $json$"Documentação"$json$::jsonb),
  ('pt-BR', 'site.nav.openMenu', $json$"Abrir menu"$json$::jsonb),
  ('pt-BR', 'site.nav.closeMenu', $json$"Fechar menu"$json$::jsonb),
  ('pt-BR', 'site.nav.accountMenu', $json$"Menu da conta"$json$::jsonb),
  ('pt-BR', 'site.nav.connected', $json$"Conectado"$json$::jsonb),
  ('pt-BR', 'site.releases.eyebrow', $json$"Changelog"$json$::jsonb),
  ('pt-BR', 'site.releases.title', $json$"Notas da versão"$json$::jsonb),
  ('pt-BR', 'site.releases.description', $json$"O que cada versão do JayV trouxe, da mais nova para a mais antiga: as mesmas notas que o app mostra em Novidades depois de uma atualização."$json$::jsonb),
  ('pt-BR', 'site.releases.versions', $json$"Versões"$json$::jsonb),
  ('pt-BR', 'site.releases.version', $json$"Versão {version}"$json$::jsonb),
  ('pt-BR', 'site.releases.latest', $json$"Mais recente"$json$::jsonb),
  ('pt-BR', 'site.releases.features', $json$"Novidades"$json$::jsonb),
  ('pt-BR', 'site.releases.fixes', $json$"Correções"$json$::jsonb),
  ('pt-BR', 'site.releases.download', $json$"Baixar v{version}"$json$::jsonb),
  ('pt-BR', 'site.releases.empty', $json$"Não foi possível carregar as notas da versão agora. Tente de novo em alguns minutos."$json$::jsonb),
  ('pt-BR', 'site.docs.eyebrow', $json$"Documentação"$json$::jsonb),
  ('pt-BR', 'site.docs.title', $json$"Como usar o JayV"$json$::jsonb),
  ('pt-BR', 'site.docs.description', $json$"Cada funcionalidade do app, onde encontrá-la e como usá-la, com os comandos do chat, do teclado e do terminal. Atualizada a cada versão."$json$::jsonb),
  ('pt-BR', 'site.docs.search', $json$"Buscar na documentação"$json$::jsonb),
  ('pt-BR', 'site.docs.searchPlaceholder', $json$"Buscar funcionalidades e comandos…"$json$::jsonb),
  ('pt-BR', 'site.docs.noResults', $json$"Nada na documentação corresponde a “{query}”."$json$::jsonb),
  ('pt-BR', 'site.docs.contents', $json$"Nesta página"$json$::jsonb),
  ('pt-BR', 'site.docs.howTo', $json$"Como usar"$json$::jsonb),
  ('pt-BR', 'site.docs.plan', $json$"Depende do seu plano"$json$::jsonb),
  ('pt-BR', 'site.docs.since', $json$"Desde a v{version}"$json$::jsonb),
  ('pt-BR', 'site.docs.link', $json$"Link para {title}"$json$::jsonb),
  ('pt-BR', 'site.docs.commands', $json$"Comandos"$json$::jsonb),
  ('pt-BR', 'site.docs.commands.chat', $json$"No chat"$json$::jsonb),
  ('pt-BR', 'site.docs.commands.chat.detail', $json$"Digite no começo de uma mensagem."$json$::jsonb),
  ('pt-BR', 'site.docs.commands.shortcut', $json$"Atalhos de teclado"$json$::jsonb),
  ('pt-BR', 'site.docs.commands.shortcut.detail', $json$"Ctrl no Windows e no Linux, ⌘ no Mac."$json$::jsonb),
  ('pt-BR', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('pt-BR', 'site.docs.commands.cli', $json$"Terminal"$json$::jsonb),
  ('pt-BR', 'site.docs.commands.cli.detail', $json$"Rode na pasta do projeto ou passe a pasta com --root."$json$::jsonb),
  ('pt-BR', 'site.docs.version', $json$"Documentação do JayV v{version}."$json$::jsonb),
  ('pt-BR', 'site.docs.empty', $json$"Não foi possível carregar a documentação agora. Tente de novo em alguns minutos."$json$::jsonb),
  ('pt-BR', 'site.docs.category.start', $json$"Primeiros passos"$json$::jsonb),
  ('pt-BR', 'site.docs.category.chat', $json$"Chat"$json$::jsonb),
  ('pt-BR', 'site.docs.category.agents', $json$"Agentes e modelos"$json$::jsonb),
  ('pt-BR', 'site.docs.category.gate', $json$"Portaria"$json$::jsonb),
  ('pt-BR', 'site.docs.category.privacy', $json$"Privacidade e segurança"$json$::jsonb),
  ('pt-BR', 'site.docs.category.project', $json$"Projetos"$json$::jsonb),
  ('pt-BR', 'site.docs.category.team', $json$"Organizações"$json$::jsonb),
  ('pt-BR', 'site.docs.category.account', $json$"Conta"$json$::jsonb),
  ('pt-BR', 'site.docs.category.app', $json$"O app"$json$::jsonb),
  ('pt-BR', 'site.docs.category.other', $json$"Mais"$json$::jsonb),
  ('pt-BR', 'site.account.photo.change', $json$"Trocar foto"$json$::jsonb),
  ('pt-BR', 'site.account.photo.title', $json$"Foto de perfil"$json$::jsonb),
  ('pt-BR', 'site.account.photo.description', $json$"Escolha uma imagem e ajuste o que aparece no círculo. A foto aparece no site e no app, seja qual for a forma de login."$json$::jsonb),
  ('pt-BR', 'site.account.photo.choose', $json$"Escolher imagem"$json$::jsonb),
  ('pt-BR', 'site.account.photo.drop', $json$"Ou arraste para cá. JPG, PNG, WebP ou GIF, até 10 MB."$json$::jsonb),
  ('pt-BR', 'site.account.photo.drag', $json$"Recorte da foto: arraste para mover, use as setas para ajustar e + ou − para o zoom"$json$::jsonb),
  ('pt-BR', 'site.account.photo.hint', $json$"Arraste para posicionar. Use o controle ou a roda do mouse para o zoom."$json$::jsonb),
  ('pt-BR', 'site.account.photo.zoom', $json$"Zoom"$json$::jsonb),
  ('pt-BR', 'site.account.photo.zoomIn', $json$"Aproximar"$json$::jsonb),
  ('pt-BR', 'site.account.photo.zoomOut', $json$"Afastar"$json$::jsonb),
  ('pt-BR', 'site.account.photo.another', $json$"Outra imagem"$json$::jsonb),
  ('pt-BR', 'site.account.photo.reset', $json$"Redefinir"$json$::jsonb),
  ('pt-BR', 'site.account.photo.save', $json$"Salvar foto"$json$::jsonb),
  ('pt-BR', 'site.account.photo.remove', $json$"Remover foto"$json$::jsonb),
  ('pt-BR', 'site.account.photo.saved', $json$"Foto de perfil atualizada."$json$::jsonb),
  ('pt-BR', 'site.account.photo.removed', $json$"Foto de perfil removida. A foto da conta vinculada volta, se houver uma."$json$::jsonb),
  ('pt-BR', 'site.account.photo.invalid', $json$"Esta imagem não pode ser usada. Escolha um JPG, PNG, WebP ou GIF de até 10 MB."$json$::jsonb),
  ('en', 'site.nav.docs', $json$"Docs"$json$::jsonb),
  ('en', 'site.nav.openMenu', $json$"Open menu"$json$::jsonb),
  ('en', 'site.nav.closeMenu', $json$"Close menu"$json$::jsonb),
  ('en', 'site.nav.accountMenu', $json$"Account menu"$json$::jsonb),
  ('en', 'site.nav.connected', $json$"Connected"$json$::jsonb),
  ('en', 'site.releases.eyebrow', $json$"Changelog"$json$::jsonb),
  ('en', 'site.releases.title', $json$"Release notes"$json$::jsonb),
  ('en', 'site.releases.description', $json$"What each version of JayV brought, newest first: the same notes the app shows in What's new after an update."$json$::jsonb),
  ('en', 'site.releases.versions', $json$"Versions"$json$::jsonb),
  ('en', 'site.releases.version', $json$"Version {version}"$json$::jsonb),
  ('en', 'site.releases.latest', $json$"Latest"$json$::jsonb),
  ('en', 'site.releases.features', $json$"New"$json$::jsonb),
  ('en', 'site.releases.fixes', $json$"Fixes"$json$::jsonb),
  ('en', 'site.releases.download', $json$"Download v{version}"$json$::jsonb),
  ('en', 'site.releases.empty', $json$"The release notes could not be loaded right now. Try again in a few minutes."$json$::jsonb),
  ('en', 'site.docs.eyebrow', $json$"Documentation"$json$::jsonb),
  ('en', 'site.docs.title', $json$"How to use JayV"$json$::jsonb),
  ('en', 'site.docs.description', $json$"Every feature of the app, where to find it and how to use it, with the commands of the chat, the keyboard and the terminal. Updated with each version."$json$::jsonb),
  ('en', 'site.docs.search', $json$"Search the documentation"$json$::jsonb),
  ('en', 'site.docs.searchPlaceholder', $json$"Search features and commands…"$json$::jsonb),
  ('en', 'site.docs.noResults', $json$"Nothing in the documentation matches “{query}”."$json$::jsonb),
  ('en', 'site.docs.contents', $json$"On this page"$json$::jsonb),
  ('en', 'site.docs.howTo', $json$"How to use"$json$::jsonb),
  ('en', 'site.docs.plan', $json$"Depends on your plan"$json$::jsonb),
  ('en', 'site.docs.since', $json$"Since v{version}"$json$::jsonb),
  ('en', 'site.docs.link', $json$"Link to {title}"$json$::jsonb),
  ('en', 'site.docs.commands', $json$"Commands"$json$::jsonb),
  ('en', 'site.docs.commands.chat', $json$"In the chat"$json$::jsonb),
  ('en', 'site.docs.commands.chat.detail', $json$"Type at the start of a message."$json$::jsonb),
  ('en', 'site.docs.commands.shortcut', $json$"Keyboard shortcuts"$json$::jsonb),
  ('en', 'site.docs.commands.shortcut.detail', $json$"Ctrl on Windows and Linux, ⌘ on Mac."$json$::jsonb),
  ('en', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('en', 'site.docs.commands.cli', $json$"Terminal"$json$::jsonb),
  ('en', 'site.docs.commands.cli.detail', $json$"Run in the project folder, or pass --root with the folder."$json$::jsonb),
  ('en', 'site.docs.version', $json$"Documentation for JayV v{version}."$json$::jsonb),
  ('en', 'site.docs.empty', $json$"The documentation could not be loaded right now. Try again in a few minutes."$json$::jsonb),
  ('en', 'site.docs.category.start', $json$"Getting started"$json$::jsonb),
  ('en', 'site.docs.category.chat', $json$"Chat"$json$::jsonb),
  ('en', 'site.docs.category.agents', $json$"Agents and models"$json$::jsonb),
  ('en', 'site.docs.category.gate', $json$"Gatehouse"$json$::jsonb),
  ('en', 'site.docs.category.privacy', $json$"Privacy and security"$json$::jsonb),
  ('en', 'site.docs.category.project', $json$"Projects"$json$::jsonb),
  ('en', 'site.docs.category.team', $json$"Organizations"$json$::jsonb),
  ('en', 'site.docs.category.account', $json$"Account"$json$::jsonb),
  ('en', 'site.docs.category.app', $json$"The app"$json$::jsonb),
  ('en', 'site.docs.category.other', $json$"More"$json$::jsonb),
  ('en', 'site.account.photo.change', $json$"Change photo"$json$::jsonb),
  ('en', 'site.account.photo.title', $json$"Profile photo"$json$::jsonb),
  ('en', 'site.account.photo.description', $json$"Choose an image and adjust what shows in the circle. The photo appears on the site and in the app, whichever way you sign in."$json$::jsonb),
  ('en', 'site.account.photo.choose', $json$"Choose an image"$json$::jsonb),
  ('en', 'site.account.photo.drop', $json$"Or drag it here. JPG, PNG, WebP or GIF, up to 10 MB."$json$::jsonb),
  ('en', 'site.account.photo.drag', $json$"Photo crop: drag to move, use the arrow keys to adjust and + or − to zoom"$json$::jsonb),
  ('en', 'site.account.photo.hint', $json$"Drag to position. Zoom with the slider or the mouse wheel."$json$::jsonb),
  ('en', 'site.account.photo.zoom', $json$"Zoom"$json$::jsonb),
  ('en', 'site.account.photo.zoomIn', $json$"Zoom in"$json$::jsonb),
  ('en', 'site.account.photo.zoomOut', $json$"Zoom out"$json$::jsonb),
  ('en', 'site.account.photo.another', $json$"Another image"$json$::jsonb),
  ('en', 'site.account.photo.reset', $json$"Reset"$json$::jsonb),
  ('en', 'site.account.photo.save', $json$"Save photo"$json$::jsonb),
  ('en', 'site.account.photo.remove', $json$"Remove photo"$json$::jsonb),
  ('en', 'site.account.photo.saved', $json$"Profile photo updated."$json$::jsonb),
  ('en', 'site.account.photo.removed', $json$"Profile photo removed. The photo of your linked account is back, if there is one."$json$::jsonb),
  ('en', 'site.account.photo.invalid', $json$"This image can't be used. Choose a JPG, PNG, WebP or GIF up to 10 MB."$json$::jsonb),
  ('es', 'site.nav.docs', $json$"Documentación"$json$::jsonb),
  ('es', 'site.nav.openMenu', $json$"Abrir menú"$json$::jsonb),
  ('es', 'site.nav.closeMenu', $json$"Cerrar menú"$json$::jsonb),
  ('es', 'site.nav.accountMenu', $json$"Menú de la cuenta"$json$::jsonb),
  ('es', 'site.nav.connected', $json$"Conectado"$json$::jsonb),
  ('es', 'site.releases.eyebrow', $json$"Changelog"$json$::jsonb),
  ('es', 'site.releases.title', $json$"Notas de la versión"$json$::jsonb),
  ('es', 'site.releases.description', $json$"Lo que trajo cada versión de JayV, de la más nueva a la más antigua: las mismas notas que la app muestra en Novedades después de una actualización."$json$::jsonb),
  ('es', 'site.releases.versions', $json$"Versiones"$json$::jsonb),
  ('es', 'site.releases.version', $json$"Versión {version}"$json$::jsonb),
  ('es', 'site.releases.latest', $json$"Más reciente"$json$::jsonb),
  ('es', 'site.releases.features', $json$"Novedades"$json$::jsonb),
  ('es', 'site.releases.fixes', $json$"Correcciones"$json$::jsonb),
  ('es', 'site.releases.download', $json$"Descargar v{version}"$json$::jsonb),
  ('es', 'site.releases.empty', $json$"No se pudieron cargar las notas de la versión. Inténtalo de nuevo en unos minutos."$json$::jsonb),
  ('es', 'site.docs.eyebrow', $json$"Documentación"$json$::jsonb),
  ('es', 'site.docs.title', $json$"Cómo usar JayV"$json$::jsonb),
  ('es', 'site.docs.description', $json$"Cada función de la app, dónde encontrarla y cómo usarla, con los comandos del chat, del teclado y de la terminal. Actualizada con cada versión."$json$::jsonb),
  ('es', 'site.docs.search', $json$"Buscar en la documentación"$json$::jsonb),
  ('es', 'site.docs.searchPlaceholder', $json$"Buscar funciones y comandos…"$json$::jsonb),
  ('es', 'site.docs.noResults', $json$"Nada en la documentación coincide con “{query}”."$json$::jsonb),
  ('es', 'site.docs.contents', $json$"En esta página"$json$::jsonb),
  ('es', 'site.docs.howTo', $json$"Cómo usarla"$json$::jsonb),
  ('es', 'site.docs.plan', $json$"Depende de tu plan"$json$::jsonb),
  ('es', 'site.docs.since', $json$"Desde la v{version}"$json$::jsonb),
  ('es', 'site.docs.link', $json$"Enlace a {title}"$json$::jsonb),
  ('es', 'site.docs.commands', $json$"Comandos"$json$::jsonb),
  ('es', 'site.docs.commands.chat', $json$"En el chat"$json$::jsonb),
  ('es', 'site.docs.commands.chat.detail', $json$"Escríbelos al comienzo de un mensaje."$json$::jsonb),
  ('es', 'site.docs.commands.shortcut', $json$"Atajos de teclado"$json$::jsonb),
  ('es', 'site.docs.commands.shortcut.detail', $json$"Ctrl en Windows y Linux, ⌘ en Mac."$json$::jsonb),
  ('es', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('es', 'site.docs.commands.cli', $json$"Terminal"$json$::jsonb),
  ('es', 'site.docs.commands.cli.detail', $json$"Ejecútalos en la carpeta del proyecto o pasa la carpeta con --root."$json$::jsonb),
  ('es', 'site.docs.version', $json$"Documentación de JayV v{version}."$json$::jsonb),
  ('es', 'site.docs.empty', $json$"No se pudo cargar la documentación. Inténtalo de nuevo en unos minutos."$json$::jsonb),
  ('es', 'site.docs.category.start', $json$"Primeros pasos"$json$::jsonb),
  ('es', 'site.docs.category.chat', $json$"Chat"$json$::jsonb),
  ('es', 'site.docs.category.agents', $json$"Agentes y modelos"$json$::jsonb),
  ('es', 'site.docs.category.gate', $json$"Portería"$json$::jsonb),
  ('es', 'site.docs.category.privacy', $json$"Privacidad y seguridad"$json$::jsonb),
  ('es', 'site.docs.category.project', $json$"Proyectos"$json$::jsonb),
  ('es', 'site.docs.category.team', $json$"Organizaciones"$json$::jsonb),
  ('es', 'site.docs.category.account', $json$"Cuenta"$json$::jsonb),
  ('es', 'site.docs.category.app', $json$"La app"$json$::jsonb),
  ('es', 'site.docs.category.other', $json$"Más"$json$::jsonb),
  ('es', 'site.account.photo.change', $json$"Cambiar foto"$json$::jsonb),
  ('es', 'site.account.photo.title', $json$"Foto de perfil"$json$::jsonb),
  ('es', 'site.account.photo.description', $json$"Elige una imagen y ajusta lo que aparece en el círculo. La foto se muestra en el sitio y en la app, sea cual sea la forma en que inicies sesión."$json$::jsonb),
  ('es', 'site.account.photo.choose', $json$"Elegir imagen"$json$::jsonb),
  ('es', 'site.account.photo.drop', $json$"O arrástrala aquí. JPG, PNG, WebP o GIF, hasta 10 MB."$json$::jsonb),
  ('es', 'site.account.photo.drag', $json$"Recorte de la foto: arrastra para moverla, usa las flechas para ajustar y + o − para el zoom"$json$::jsonb),
  ('es', 'site.account.photo.hint', $json$"Arrastra para colocarla. Usa el control o la rueda del ratón para el zoom."$json$::jsonb),
  ('es', 'site.account.photo.zoom', $json$"Zoom"$json$::jsonb),
  ('es', 'site.account.photo.zoomIn', $json$"Acercar"$json$::jsonb),
  ('es', 'site.account.photo.zoomOut', $json$"Alejar"$json$::jsonb),
  ('es', 'site.account.photo.another', $json$"Otra imagen"$json$::jsonb),
  ('es', 'site.account.photo.reset', $json$"Restablecer"$json$::jsonb),
  ('es', 'site.account.photo.save', $json$"Guardar foto"$json$::jsonb),
  ('es', 'site.account.photo.remove', $json$"Quitar foto"$json$::jsonb),
  ('es', 'site.account.photo.saved', $json$"Foto de perfil actualizada."$json$::jsonb),
  ('es', 'site.account.photo.removed', $json$"Foto de perfil quitada. Vuelve la foto de tu cuenta vinculada, si la hay."$json$::jsonb),
  ('es', 'site.account.photo.invalid', $json$"No se puede usar esta imagen. Elige un JPG, PNG, WebP o GIF de hasta 10 MB."$json$::jsonb),
  ('zh-CN', 'site.nav.docs', $json$"文档"$json$::jsonb),
  ('zh-CN', 'site.nav.openMenu', $json$"打开菜单"$json$::jsonb),
  ('zh-CN', 'site.nav.closeMenu', $json$"关闭菜单"$json$::jsonb),
  ('zh-CN', 'site.nav.accountMenu', $json$"账户菜单"$json$::jsonb),
  ('zh-CN', 'site.nav.connected', $json$"已连接"$json$::jsonb),
  ('zh-CN', 'site.releases.eyebrow', $json$"更新日志"$json$::jsonb),
  ('zh-CN', 'site.releases.title', $json$"版本说明"$json$::jsonb),
  ('zh-CN', 'site.releases.description', $json$"JayV 每个版本带来的内容，从新到旧排列：与应用更新后在新功能窗口中显示的说明相同。"$json$::jsonb),
  ('zh-CN', 'site.releases.versions', $json$"版本"$json$::jsonb),
  ('zh-CN', 'site.releases.version', $json$"版本 {version}"$json$::jsonb),
  ('zh-CN', 'site.releases.latest', $json$"最新"$json$::jsonb),
  ('zh-CN', 'site.releases.features', $json$"新功能"$json$::jsonb),
  ('zh-CN', 'site.releases.fixes', $json$"修复"$json$::jsonb),
  ('zh-CN', 'site.releases.download', $json$"下载 v{version}"$json$::jsonb),
  ('zh-CN', 'site.releases.empty', $json$"暂时无法加载版本说明。请过几分钟再试。"$json$::jsonb),
  ('zh-CN', 'site.docs.eyebrow', $json$"文档"$json$::jsonb),
  ('zh-CN', 'site.docs.title', $json$"如何使用 JayV"$json$::jsonb),
  ('zh-CN', 'site.docs.description', $json$"应用的每项功能、在哪里找到以及如何使用，并附有聊天、键盘和终端中的命令。随每个版本更新。"$json$::jsonb),
  ('zh-CN', 'site.docs.search', $json$"搜索文档"$json$::jsonb),
  ('zh-CN', 'site.docs.searchPlaceholder', $json$"搜索功能和命令…"$json$::jsonb),
  ('zh-CN', 'site.docs.noResults', $json$"文档中没有与“{query}”匹配的内容。"$json$::jsonb),
  ('zh-CN', 'site.docs.contents', $json$"本页内容"$json$::jsonb),
  ('zh-CN', 'site.docs.howTo', $json$"使用方法"$json$::jsonb),
  ('zh-CN', 'site.docs.plan', $json$"取决于你的套餐"$json$::jsonb),
  ('zh-CN', 'site.docs.since', $json$"自 v{version} 起"$json$::jsonb),
  ('zh-CN', 'site.docs.link', $json$"指向 {title} 的链接"$json$::jsonb),
  ('zh-CN', 'site.docs.commands', $json$"命令"$json$::jsonb),
  ('zh-CN', 'site.docs.commands.chat', $json$"在聊天中"$json$::jsonb),
  ('zh-CN', 'site.docs.commands.chat.detail', $json$"在消息开头输入。"$json$::jsonb),
  ('zh-CN', 'site.docs.commands.shortcut', $json$"键盘快捷键"$json$::jsonb),
  ('zh-CN', 'site.docs.commands.shortcut.detail', $json$"Windows 和 Linux 上为 Ctrl，Mac 上为 ⌘。"$json$::jsonb),
  ('zh-CN', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('zh-CN', 'site.docs.commands.cli', $json$"终端"$json$::jsonb),
  ('zh-CN', 'site.docs.commands.cli.detail', $json$"在项目文件夹中运行，或用 --root 指定文件夹。"$json$::jsonb),
  ('zh-CN', 'site.docs.version', $json$"JayV v{version} 的文档。"$json$::jsonb),
  ('zh-CN', 'site.docs.empty', $json$"暂时无法加载文档。请过几分钟再试。"$json$::jsonb),
  ('zh-CN', 'site.docs.category.start', $json$"入门"$json$::jsonb),
  ('zh-CN', 'site.docs.category.chat', $json$"聊天"$json$::jsonb),
  ('zh-CN', 'site.docs.category.agents', $json$"代理和模型"$json$::jsonb),
  ('zh-CN', 'site.docs.category.gate', $json$"门岗"$json$::jsonb),
  ('zh-CN', 'site.docs.category.privacy', $json$"隐私与安全"$json$::jsonb),
  ('zh-CN', 'site.docs.category.project', $json$"项目"$json$::jsonb),
  ('zh-CN', 'site.docs.category.team', $json$"组织"$json$::jsonb),
  ('zh-CN', 'site.docs.category.account', $json$"账户"$json$::jsonb),
  ('zh-CN', 'site.docs.category.app', $json$"应用"$json$::jsonb),
  ('zh-CN', 'site.docs.category.other', $json$"更多"$json$::jsonb),
  ('zh-CN', 'site.account.photo.change', $json$"更换照片"$json$::jsonb),
  ('zh-CN', 'site.account.photo.title', $json$"个人资料照片"$json$::jsonb),
  ('zh-CN', 'site.account.photo.description', $json$"选择一张图片并调整圆形中显示的部分。无论以何种方式登录，照片都会显示在网站和应用中。"$json$::jsonb),
  ('zh-CN', 'site.account.photo.choose', $json$"选择图片"$json$::jsonb),
  ('zh-CN', 'site.account.photo.drop', $json$"或拖到这里。JPG、PNG、WebP 或 GIF，最大 10 MB。"$json$::jsonb),
  ('zh-CN', 'site.account.photo.drag', $json$"照片裁剪：拖动以移动，用方向键微调，用 + 或 − 缩放"$json$::jsonb),
  ('zh-CN', 'site.account.photo.hint', $json$"拖动以定位。用滑块或鼠标滚轮缩放。"$json$::jsonb),
  ('zh-CN', 'site.account.photo.zoom', $json$"缩放"$json$::jsonb),
  ('zh-CN', 'site.account.photo.zoomIn', $json$"放大"$json$::jsonb),
  ('zh-CN', 'site.account.photo.zoomOut', $json$"缩小"$json$::jsonb),
  ('zh-CN', 'site.account.photo.another', $json$"其他图片"$json$::jsonb),
  ('zh-CN', 'site.account.photo.reset', $json$"重置"$json$::jsonb),
  ('zh-CN', 'site.account.photo.save', $json$"保存照片"$json$::jsonb),
  ('zh-CN', 'site.account.photo.remove', $json$"移除照片"$json$::jsonb),
  ('zh-CN', 'site.account.photo.saved', $json$"个人资料照片已更新。"$json$::jsonb),
  ('zh-CN', 'site.account.photo.removed', $json$"个人资料照片已移除。如果有关联账户的照片，会改为显示它。"$json$::jsonb),
  ('zh-CN', 'site.account.photo.invalid', $json$"无法使用这张图片。请选择不超过 10 MB 的 JPG、PNG、WebP 或 GIF。"$json$::jsonb),
  ('hi', 'site.nav.docs', $json$"दस्तावेज़"$json$::jsonb),
  ('hi', 'site.nav.openMenu', $json$"मेन्यू खोलें"$json$::jsonb),
  ('hi', 'site.nav.closeMenu', $json$"मेन्यू बंद करें"$json$::jsonb),
  ('hi', 'site.nav.accountMenu', $json$"खाता मेन्यू"$json$::jsonb),
  ('hi', 'site.nav.connected', $json$"कनेक्टेड"$json$::jsonb),
  ('hi', 'site.releases.eyebrow', $json$"चेंजलॉग"$json$::jsonb),
  ('hi', 'site.releases.title', $json$"रिलीज़ नोट्स"$json$::jsonb),
  ('hi', 'site.releases.description', $json$"JayV के हर संस्करण में क्या आया, सबसे नए से पुराने तक: वही नोट्स जो अपडेट के बाद ऐप नया क्या है में दिखाता है।"$json$::jsonb),
  ('hi', 'site.releases.versions', $json$"संस्करण"$json$::jsonb),
  ('hi', 'site.releases.version', $json$"संस्करण {version}"$json$::jsonb),
  ('hi', 'site.releases.latest', $json$"नवीनतम"$json$::jsonb),
  ('hi', 'site.releases.features', $json$"नया"$json$::jsonb),
  ('hi', 'site.releases.fixes', $json$"सुधार"$json$::jsonb),
  ('hi', 'site.releases.download', $json$"v{version} डाउनलोड करें"$json$::jsonb),
  ('hi', 'site.releases.empty', $json$"अभी रिलीज़ नोट्स लोड नहीं हो सके। कुछ मिनट बाद फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'site.docs.eyebrow', $json$"दस्तावेज़"$json$::jsonb),
  ('hi', 'site.docs.title', $json$"JayV का उपयोग कैसे करें"$json$::jsonb),
  ('hi', 'site.docs.description', $json$"ऐप की हर सुविधा, उसे कहाँ पाएँ और कैसे इस्तेमाल करें, साथ में चैट, कीबोर्ड और टर्मिनल के कमांड। हर संस्करण के साथ अपडेट होता है।"$json$::jsonb),
  ('hi', 'site.docs.search', $json$"दस्तावेज़ में खोजें"$json$::jsonb),
  ('hi', 'site.docs.searchPlaceholder', $json$"सुविधाएँ और कमांड खोजें…"$json$::jsonb),
  ('hi', 'site.docs.noResults', $json$"दस्तावेज़ में “{query}” से मेल खाता कुछ नहीं मिला।"$json$::jsonb),
  ('hi', 'site.docs.contents', $json$"इस पेज पर"$json$::jsonb),
  ('hi', 'site.docs.howTo', $json$"कैसे इस्तेमाल करें"$json$::jsonb),
  ('hi', 'site.docs.plan', $json$"आपके प्लान पर निर्भर"$json$::jsonb),
  ('hi', 'site.docs.since', $json$"v{version} से"$json$::jsonb),
  ('hi', 'site.docs.link', $json$"{title} का लिंक"$json$::jsonb),
  ('hi', 'site.docs.commands', $json$"कमांड"$json$::jsonb),
  ('hi', 'site.docs.commands.chat', $json$"चैट में"$json$::jsonb),
  ('hi', 'site.docs.commands.chat.detail', $json$"संदेश की शुरुआत में टाइप करें।"$json$::jsonb),
  ('hi', 'site.docs.commands.shortcut', $json$"कीबोर्ड शॉर्टकट"$json$::jsonb),
  ('hi', 'site.docs.commands.shortcut.detail', $json$"Windows और Linux पर Ctrl, Mac पर ⌘।"$json$::jsonb),
  ('hi', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('hi', 'site.docs.commands.cli', $json$"टर्मिनल"$json$::jsonb),
  ('hi', 'site.docs.commands.cli.detail', $json$"प्रोजेक्ट फ़ोल्डर में चलाएँ, या --root से फ़ोल्डर बताएँ।"$json$::jsonb),
  ('hi', 'site.docs.version', $json$"JayV v{version} के दस्तावेज़।"$json$::jsonb),
  ('hi', 'site.docs.empty', $json$"अभी दस्तावेज़ लोड नहीं हो सके। कुछ मिनट बाद फिर कोशिश करें।"$json$::jsonb),
  ('hi', 'site.docs.category.start', $json$"शुरुआत"$json$::jsonb),
  ('hi', 'site.docs.category.chat', $json$"चैट"$json$::jsonb),
  ('hi', 'site.docs.category.agents', $json$"एजेंट और मॉडल"$json$::jsonb),
  ('hi', 'site.docs.category.gate', $json$"गेट"$json$::jsonb),
  ('hi', 'site.docs.category.privacy', $json$"गोपनीयता और सुरक्षा"$json$::jsonb),
  ('hi', 'site.docs.category.project', $json$"प्रोजेक्ट"$json$::jsonb),
  ('hi', 'site.docs.category.team', $json$"संगठन"$json$::jsonb),
  ('hi', 'site.docs.category.account', $json$"खाता"$json$::jsonb),
  ('hi', 'site.docs.category.app', $json$"ऐप"$json$::jsonb),
  ('hi', 'site.docs.category.other', $json$"और"$json$::jsonb),
  ('hi', 'site.account.photo.change', $json$"फ़ोटो बदलें"$json$::jsonb),
  ('hi', 'site.account.photo.title', $json$"प्रोफ़ाइल फ़ोटो"$json$::jsonb),
  ('hi', 'site.account.photo.description', $json$"एक इमेज चुनें और तय करें कि गोले में क्या दिखे। आप किसी भी तरीके से साइन इन करें, फ़ोटो साइट और ऐप में दिखती है।"$json$::jsonb),
  ('hi', 'site.account.photo.choose', $json$"इमेज चुनें"$json$::jsonb),
  ('hi', 'site.account.photo.drop', $json$"या उसे यहाँ खींचें। JPG, PNG, WebP या GIF, 10 MB तक।"$json$::jsonb),
  ('hi', 'site.account.photo.drag', $json$"फ़ोटो क्रॉप: खिसकाने के लिए खींचें, ठीक करने के लिए तीर कुंजियाँ और ज़ूम के लिए + या − इस्तेमाल करें"$json$::jsonb),
  ('hi', 'site.account.photo.hint', $json$"जगह तय करने के लिए खींचें। स्लाइडर या माउस व्हील से ज़ूम करें।"$json$::jsonb),
  ('hi', 'site.account.photo.zoom', $json$"ज़ूम"$json$::jsonb),
  ('hi', 'site.account.photo.zoomIn', $json$"ज़ूम इन"$json$::jsonb),
  ('hi', 'site.account.photo.zoomOut', $json$"ज़ूम आउट"$json$::jsonb),
  ('hi', 'site.account.photo.another', $json$"दूसरी इमेज"$json$::jsonb),
  ('hi', 'site.account.photo.reset', $json$"रीसेट करें"$json$::jsonb),
  ('hi', 'site.account.photo.save', $json$"फ़ोटो सहेजें"$json$::jsonb),
  ('hi', 'site.account.photo.remove', $json$"फ़ोटो हटाएँ"$json$::jsonb),
  ('hi', 'site.account.photo.saved', $json$"प्रोफ़ाइल फ़ोटो अपडेट हो गई।"$json$::jsonb),
  ('hi', 'site.account.photo.removed', $json$"प्रोफ़ाइल फ़ोटो हटा दी गई। अगर लिंक किए गए खाते की फ़ोटो है, तो वह वापस आ जाती है।"$json$::jsonb),
  ('hi', 'site.account.photo.invalid', $json$"यह इमेज इस्तेमाल नहीं हो सकती। 10 MB तक की JPG, PNG, WebP या GIF चुनें।"$json$::jsonb),
  ('ar', 'site.nav.docs', $json$"التوثيق"$json$::jsonb),
  ('ar', 'site.nav.openMenu', $json$"فتح القائمة"$json$::jsonb),
  ('ar', 'site.nav.closeMenu', $json$"إغلاق القائمة"$json$::jsonb),
  ('ar', 'site.nav.accountMenu', $json$"قائمة الحساب"$json$::jsonb),
  ('ar', 'site.nav.connected', $json$"متصل"$json$::jsonb),
  ('ar', 'site.releases.eyebrow', $json$"سجل التغييرات"$json$::jsonb),
  ('ar', 'site.releases.title', $json$"ملاحظات الإصدار"$json$::jsonb),
  ('ar', 'site.releases.description', $json$"ما جاء به كل إصدار من JayV، من الأحدث إلى الأقدم: الملاحظات نفسها التي يعرضها التطبيق في الجديد بعد التحديث."$json$::jsonb),
  ('ar', 'site.releases.versions', $json$"الإصدارات"$json$::jsonb),
  ('ar', 'site.releases.version', $json$"الإصدار {version}"$json$::jsonb),
  ('ar', 'site.releases.latest', $json$"الأحدث"$json$::jsonb),
  ('ar', 'site.releases.features', $json$"الجديد"$json$::jsonb),
  ('ar', 'site.releases.fixes', $json$"الإصلاحات"$json$::jsonb),
  ('ar', 'site.releases.download', $json$"تنزيل v{version}"$json$::jsonb),
  ('ar', 'site.releases.empty', $json$"تعذّر تحميل ملاحظات الإصدار الآن. حاول مرة أخرى بعد بضع دقائق."$json$::jsonb),
  ('ar', 'site.docs.eyebrow', $json$"التوثيق"$json$::jsonb),
  ('ar', 'site.docs.title', $json$"كيف تستخدم JayV"$json$::jsonb),
  ('ar', 'site.docs.description', $json$"كل ميزة في التطبيق، وأين تجدها وكيف تستخدمها، مع أوامر الدردشة ولوحة المفاتيح والطرفية. يُحدَّث مع كل إصدار."$json$::jsonb),
  ('ar', 'site.docs.search', $json$"البحث في التوثيق"$json$::jsonb),
  ('ar', 'site.docs.searchPlaceholder', $json$"ابحث عن الميزات والأوامر…"$json$::jsonb),
  ('ar', 'site.docs.noResults', $json$"لا شيء في التوثيق يطابق «{query}»."$json$::jsonb),
  ('ar', 'site.docs.contents', $json$"في هذه الصفحة"$json$::jsonb),
  ('ar', 'site.docs.howTo', $json$"طريقة الاستخدام"$json$::jsonb),
  ('ar', 'site.docs.plan', $json$"يعتمد على اشتراكك"$json$::jsonb),
  ('ar', 'site.docs.since', $json$"منذ v{version}"$json$::jsonb),
  ('ar', 'site.docs.link', $json$"رابط إلى {title}"$json$::jsonb),
  ('ar', 'site.docs.commands', $json$"الأوامر"$json$::jsonb),
  ('ar', 'site.docs.commands.chat', $json$"في الدردشة"$json$::jsonb),
  ('ar', 'site.docs.commands.chat.detail', $json$"اكتبها في بداية الرسالة."$json$::jsonb),
  ('ar', 'site.docs.commands.shortcut', $json$"اختصارات لوحة المفاتيح"$json$::jsonb),
  ('ar', 'site.docs.commands.shortcut.detail', $json$"Ctrl على Windows وLinux، و⌘ على Mac."$json$::jsonb),
  ('ar', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('ar', 'site.docs.commands.cli', $json$"الطرفية"$json$::jsonb),
  ('ar', 'site.docs.commands.cli.detail', $json$"شغّلها في مجلد المشروع، أو مرّر المجلد باستخدام --root."$json$::jsonb),
  ('ar', 'site.docs.version', $json$"توثيق JayV v{version}."$json$::jsonb),
  ('ar', 'site.docs.empty', $json$"تعذّر تحميل التوثيق الآن. حاول مرة أخرى بعد بضع دقائق."$json$::jsonb),
  ('ar', 'site.docs.category.start', $json$"البداية"$json$::jsonb),
  ('ar', 'site.docs.category.chat', $json$"الدردشة"$json$::jsonb),
  ('ar', 'site.docs.category.agents', $json$"الوكلاء والنماذج"$json$::jsonb),
  ('ar', 'site.docs.category.gate', $json$"البوابة"$json$::jsonb),
  ('ar', 'site.docs.category.privacy', $json$"الخصوصية والأمان"$json$::jsonb),
  ('ar', 'site.docs.category.project', $json$"المشاريع"$json$::jsonb),
  ('ar', 'site.docs.category.team', $json$"المؤسسات"$json$::jsonb),
  ('ar', 'site.docs.category.account', $json$"الحساب"$json$::jsonb),
  ('ar', 'site.docs.category.app', $json$"التطبيق"$json$::jsonb),
  ('ar', 'site.docs.category.other', $json$"المزيد"$json$::jsonb),
  ('ar', 'site.account.photo.change', $json$"تغيير الصورة"$json$::jsonb),
  ('ar', 'site.account.photo.title', $json$"صورة الملف الشخصي"$json$::jsonb),
  ('ar', 'site.account.photo.description', $json$"اختر صورة واضبط ما يظهر داخل الدائرة. تظهر الصورة في الموقع وفي التطبيق مهما كانت طريقة تسجيل دخولك."$json$::jsonb),
  ('ar', 'site.account.photo.choose', $json$"اختيار صورة"$json$::jsonb),
  ('ar', 'site.account.photo.drop', $json$"أو اسحبها إلى هنا. JPG أو PNG أو WebP أو GIF، حتى 10 ميغابايت."$json$::jsonb),
  ('ar', 'site.account.photo.drag', $json$"قص الصورة: اسحب للتحريك، واستخدم مفاتيح الأسهم للضبط، و+ أو − للتكبير والتصغير"$json$::jsonb),
  ('ar', 'site.account.photo.hint', $json$"اسحب لتحديد الموضع. كبّر أو صغّر بشريط التمرير أو بعجلة الفأرة."$json$::jsonb),
  ('ar', 'site.account.photo.zoom', $json$"التكبير"$json$::jsonb),
  ('ar', 'site.account.photo.zoomIn', $json$"تكبير"$json$::jsonb),
  ('ar', 'site.account.photo.zoomOut', $json$"تصغير"$json$::jsonb),
  ('ar', 'site.account.photo.another', $json$"صورة أخرى"$json$::jsonb),
  ('ar', 'site.account.photo.reset', $json$"إعادة الضبط"$json$::jsonb),
  ('ar', 'site.account.photo.save', $json$"حفظ الصورة"$json$::jsonb),
  ('ar', 'site.account.photo.remove', $json$"إزالة الصورة"$json$::jsonb),
  ('ar', 'site.account.photo.saved', $json$"تم تحديث صورة الملف الشخصي."$json$::jsonb),
  ('ar', 'site.account.photo.removed', $json$"تمت إزالة صورة الملف الشخصي. تعود صورة حسابك المرتبط إن وُجدت."$json$::jsonb),
  ('ar', 'site.account.photo.invalid', $json$"لا يمكن استخدام هذه الصورة. اختر ملف JPG أو PNG أو WebP أو GIF بحجم لا يتجاوز 10 ميغابايت."$json$::jsonb),
  ('fr', 'site.nav.docs', $json$"Documentation"$json$::jsonb),
  ('fr', 'site.nav.openMenu', $json$"Ouvrir le menu"$json$::jsonb),
  ('fr', 'site.nav.closeMenu', $json$"Fermer le menu"$json$::jsonb),
  ('fr', 'site.nav.accountMenu', $json$"Menu du compte"$json$::jsonb),
  ('fr', 'site.nav.connected', $json$"Connecté"$json$::jsonb),
  ('fr', 'site.releases.eyebrow', $json$"Changelog"$json$::jsonb),
  ('fr', 'site.releases.title', $json$"Notes de version"$json$::jsonb),
  ('fr', 'site.releases.description', $json$"Ce que chaque version de JayV a apporté, de la plus récente à la plus ancienne : les mêmes notes que l'application affiche dans Nouveautés après une mise à jour."$json$::jsonb),
  ('fr', 'site.releases.versions', $json$"Versions"$json$::jsonb),
  ('fr', 'site.releases.version', $json$"Version {version}"$json$::jsonb),
  ('fr', 'site.releases.latest', $json$"La plus récente"$json$::jsonb),
  ('fr', 'site.releases.features', $json$"Nouveautés"$json$::jsonb),
  ('fr', 'site.releases.fixes', $json$"Corrections"$json$::jsonb),
  ('fr', 'site.releases.download', $json$"Télécharger la v{version}"$json$::jsonb),
  ('fr', 'site.releases.empty', $json$"Impossible de charger les notes de version pour le moment. Réessayez dans quelques minutes."$json$::jsonb),
  ('fr', 'site.docs.eyebrow', $json$"Documentation"$json$::jsonb),
  ('fr', 'site.docs.title', $json$"Utiliser JayV"$json$::jsonb),
  ('fr', 'site.docs.description', $json$"Chaque fonctionnalité de l'application, où la trouver et comment l'utiliser, avec les commandes du chat, du clavier et du terminal. Mise à jour à chaque version."$json$::jsonb),
  ('fr', 'site.docs.search', $json$"Rechercher dans la documentation"$json$::jsonb),
  ('fr', 'site.docs.searchPlaceholder', $json$"Rechercher des fonctionnalités et des commandes…"$json$::jsonb),
  ('fr', 'site.docs.noResults', $json$"Rien dans la documentation ne correspond à « {query} »."$json$::jsonb),
  ('fr', 'site.docs.contents', $json$"Sur cette page"$json$::jsonb),
  ('fr', 'site.docs.howTo', $json$"Comment l'utiliser"$json$::jsonb),
  ('fr', 'site.docs.plan', $json$"Dépend de votre forfait"$json$::jsonb),
  ('fr', 'site.docs.since', $json$"Depuis la v{version}"$json$::jsonb),
  ('fr', 'site.docs.link', $json$"Lien vers {title}"$json$::jsonb),
  ('fr', 'site.docs.commands', $json$"Commandes"$json$::jsonb),
  ('fr', 'site.docs.commands.chat', $json$"Dans le chat"$json$::jsonb),
  ('fr', 'site.docs.commands.chat.detail', $json$"À taper au début d'un message."$json$::jsonb),
  ('fr', 'site.docs.commands.shortcut', $json$"Raccourcis clavier"$json$::jsonb),
  ('fr', 'site.docs.commands.shortcut.detail', $json$"Ctrl sous Windows et Linux, ⌘ sur Mac."$json$::jsonb),
  ('fr', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('fr', 'site.docs.commands.cli', $json$"Terminal"$json$::jsonb),
  ('fr', 'site.docs.commands.cli.detail', $json$"À lancer dans le dossier du projet, ou en passant le dossier avec --root."$json$::jsonb),
  ('fr', 'site.docs.version', $json$"Documentation de JayV v{version}."$json$::jsonb),
  ('fr', 'site.docs.empty', $json$"Impossible de charger la documentation pour le moment. Réessayez dans quelques minutes."$json$::jsonb),
  ('fr', 'site.docs.category.start', $json$"Premiers pas"$json$::jsonb),
  ('fr', 'site.docs.category.chat', $json$"Chat"$json$::jsonb),
  ('fr', 'site.docs.category.agents', $json$"Agents et modèles"$json$::jsonb),
  ('fr', 'site.docs.category.gate', $json$"Loge"$json$::jsonb),
  ('fr', 'site.docs.category.privacy', $json$"Confidentialité et sécurité"$json$::jsonb),
  ('fr', 'site.docs.category.project', $json$"Projets"$json$::jsonb),
  ('fr', 'site.docs.category.team', $json$"Organisations"$json$::jsonb),
  ('fr', 'site.docs.category.account', $json$"Compte"$json$::jsonb),
  ('fr', 'site.docs.category.app', $json$"L'application"$json$::jsonb),
  ('fr', 'site.docs.category.other', $json$"Plus"$json$::jsonb),
  ('fr', 'site.account.photo.change', $json$"Changer la photo"$json$::jsonb),
  ('fr', 'site.account.photo.title', $json$"Photo de profil"$json$::jsonb),
  ('fr', 'site.account.photo.description', $json$"Choisissez une image et ajustez ce qui apparaît dans le cercle. La photo s'affiche sur le site et dans l'application, quelle que soit votre façon de vous connecter."$json$::jsonb),
  ('fr', 'site.account.photo.choose', $json$"Choisir une image"$json$::jsonb),
  ('fr', 'site.account.photo.drop', $json$"Ou faites-la glisser ici. JPG, PNG, WebP ou GIF, jusqu'à 10 Mo."$json$::jsonb),
  ('fr', 'site.account.photo.drag', $json$"Recadrage de la photo : faites glisser pour déplacer, utilisez les flèches pour ajuster et + ou − pour le zoom"$json$::jsonb),
  ('fr', 'site.account.photo.hint', $json$"Faites glisser pour positionner. Zoomez avec le curseur ou la molette de la souris."$json$::jsonb),
  ('fr', 'site.account.photo.zoom', $json$"Zoom"$json$::jsonb),
  ('fr', 'site.account.photo.zoomIn', $json$"Zoom avant"$json$::jsonb),
  ('fr', 'site.account.photo.zoomOut', $json$"Zoom arrière"$json$::jsonb),
  ('fr', 'site.account.photo.another', $json$"Autre image"$json$::jsonb),
  ('fr', 'site.account.photo.reset', $json$"Réinitialiser"$json$::jsonb),
  ('fr', 'site.account.photo.save', $json$"Enregistrer la photo"$json$::jsonb),
  ('fr', 'site.account.photo.remove', $json$"Supprimer la photo"$json$::jsonb),
  ('fr', 'site.account.photo.saved', $json$"Photo de profil mise à jour."$json$::jsonb),
  ('fr', 'site.account.photo.removed', $json$"Photo de profil supprimée. La photo de votre compte associé revient, s'il y en a une."$json$::jsonb),
  ('fr', 'site.account.photo.invalid', $json$"Cette image ne peut pas être utilisée. Choisissez un JPG, PNG, WebP ou GIF de 10 Mo maximum."$json$::jsonb),
  ('ru', 'site.nav.docs', $json$"Документация"$json$::jsonb),
  ('ru', 'site.nav.openMenu', $json$"Открыть меню"$json$::jsonb),
  ('ru', 'site.nav.closeMenu', $json$"Закрыть меню"$json$::jsonb),
  ('ru', 'site.nav.accountMenu', $json$"Меню аккаунта"$json$::jsonb),
  ('ru', 'site.nav.connected', $json$"В сети"$json$::jsonb),
  ('ru', 'site.releases.eyebrow', $json$"Changelog"$json$::jsonb),
  ('ru', 'site.releases.title', $json$"Примечания к версиям"$json$::jsonb),
  ('ru', 'site.releases.description', $json$"Что принесла каждая версия JayV, от новой к старой: те же примечания, что приложение показывает в разделе «Что нового» после обновления."$json$::jsonb),
  ('ru', 'site.releases.versions', $json$"Версии"$json$::jsonb),
  ('ru', 'site.releases.version', $json$"Версия {version}"$json$::jsonb),
  ('ru', 'site.releases.latest', $json$"Последняя"$json$::jsonb),
  ('ru', 'site.releases.features', $json$"Новое"$json$::jsonb),
  ('ru', 'site.releases.fixes', $json$"Исправления"$json$::jsonb),
  ('ru', 'site.releases.download', $json$"Скачать v{version}"$json$::jsonb),
  ('ru', 'site.releases.empty', $json$"Сейчас не удалось загрузить примечания к версиям. Попробуйте через несколько минут."$json$::jsonb),
  ('ru', 'site.docs.eyebrow', $json$"Документация"$json$::jsonb),
  ('ru', 'site.docs.title', $json$"Как пользоваться JayV"$json$::jsonb),
  ('ru', 'site.docs.description', $json$"Каждая функция приложения: где её найти и как ею пользоваться, а также команды чата, клавиатуры и терминала. Обновляется с каждой версией."$json$::jsonb),
  ('ru', 'site.docs.search', $json$"Поиск по документации"$json$::jsonb),
  ('ru', 'site.docs.searchPlaceholder', $json$"Искать функции и команды…"$json$::jsonb),
  ('ru', 'site.docs.noResults', $json$"В документации нет ничего по запросу «{query}»."$json$::jsonb),
  ('ru', 'site.docs.contents', $json$"На этой странице"$json$::jsonb),
  ('ru', 'site.docs.howTo', $json$"Как пользоваться"$json$::jsonb),
  ('ru', 'site.docs.plan', $json$"Зависит от тарифа"$json$::jsonb),
  ('ru', 'site.docs.since', $json$"С v{version}"$json$::jsonb),
  ('ru', 'site.docs.link', $json$"Ссылка на «{title}»"$json$::jsonb),
  ('ru', 'site.docs.commands', $json$"Команды"$json$::jsonb),
  ('ru', 'site.docs.commands.chat', $json$"В чате"$json$::jsonb),
  ('ru', 'site.docs.commands.chat.detail', $json$"Введите в начале сообщения."$json$::jsonb),
  ('ru', 'site.docs.commands.shortcut', $json$"Сочетания клавиш"$json$::jsonb),
  ('ru', 'site.docs.commands.shortcut.detail', $json$"Ctrl в Windows и Linux, ⌘ на Mac."$json$::jsonb),
  ('ru', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('ru', 'site.docs.commands.cli', $json$"Терминал"$json$::jsonb),
  ('ru', 'site.docs.commands.cli.detail', $json$"Запускайте в папке проекта или укажите папку через --root."$json$::jsonb),
  ('ru', 'site.docs.version', $json$"Документация для JayV v{version}."$json$::jsonb),
  ('ru', 'site.docs.empty', $json$"Сейчас не удалось загрузить документацию. Попробуйте через несколько минут."$json$::jsonb),
  ('ru', 'site.docs.category.start', $json$"Начало работы"$json$::jsonb),
  ('ru', 'site.docs.category.chat', $json$"Чат"$json$::jsonb),
  ('ru', 'site.docs.category.agents', $json$"Агенты и модели"$json$::jsonb),
  ('ru', 'site.docs.category.gate', $json$"Проходная"$json$::jsonb),
  ('ru', 'site.docs.category.privacy', $json$"Конфиденциальность и безопасность"$json$::jsonb),
  ('ru', 'site.docs.category.project', $json$"Проекты"$json$::jsonb),
  ('ru', 'site.docs.category.team', $json$"Организации"$json$::jsonb),
  ('ru', 'site.docs.category.account', $json$"Аккаунт"$json$::jsonb),
  ('ru', 'site.docs.category.app', $json$"Приложение"$json$::jsonb),
  ('ru', 'site.docs.category.other', $json$"Ещё"$json$::jsonb),
  ('ru', 'site.account.photo.change', $json$"Сменить фото"$json$::jsonb),
  ('ru', 'site.account.photo.title', $json$"Фото профиля"$json$::jsonb),
  ('ru', 'site.account.photo.description', $json$"Выберите изображение и настройте, что видно в круге. Фото показывается на сайте и в приложении, как бы вы ни входили."$json$::jsonb),
  ('ru', 'site.account.photo.choose', $json$"Выбрать изображение"$json$::jsonb),
  ('ru', 'site.account.photo.drop', $json$"Или перетащите его сюда. JPG, PNG, WebP или GIF, до 10 МБ."$json$::jsonb),
  ('ru', 'site.account.photo.drag', $json$"Кадрирование фото: перетаскивайте, чтобы сдвинуть, стрелками подстраивайте, а + или − меняют масштаб"$json$::jsonb),
  ('ru', 'site.account.photo.hint', $json$"Перетащите, чтобы выбрать положение. Масштаб — ползунком или колёсиком мыши."$json$::jsonb),
  ('ru', 'site.account.photo.zoom', $json$"Масштаб"$json$::jsonb),
  ('ru', 'site.account.photo.zoomIn', $json$"Увеличить"$json$::jsonb),
  ('ru', 'site.account.photo.zoomOut', $json$"Уменьшить"$json$::jsonb),
  ('ru', 'site.account.photo.another', $json$"Другое изображение"$json$::jsonb),
  ('ru', 'site.account.photo.reset', $json$"Сбросить"$json$::jsonb),
  ('ru', 'site.account.photo.save', $json$"Сохранить фото"$json$::jsonb),
  ('ru', 'site.account.photo.remove', $json$"Удалить фото"$json$::jsonb),
  ('ru', 'site.account.photo.saved', $json$"Фото профиля обновлено."$json$::jsonb),
  ('ru', 'site.account.photo.removed', $json$"Фото профиля удалено. Вернулось фото привязанного аккаунта, если оно есть."$json$::jsonb),
  ('ru', 'site.account.photo.invalid', $json$"Это изображение нельзя использовать. Выберите JPG, PNG, WebP или GIF размером до 10 МБ."$json$::jsonb),
  ('ja', 'site.nav.docs', $json$"ドキュメント"$json$::jsonb),
  ('ja', 'site.nav.openMenu', $json$"メニューを開く"$json$::jsonb),
  ('ja', 'site.nav.closeMenu', $json$"メニューを閉じる"$json$::jsonb),
  ('ja', 'site.nav.accountMenu', $json$"アカウントメニュー"$json$::jsonb),
  ('ja', 'site.nav.connected', $json$"接続中"$json$::jsonb),
  ('ja', 'site.releases.eyebrow', $json$"変更履歴"$json$::jsonb),
  ('ja', 'site.releases.title', $json$"リリースノート"$json$::jsonb),
  ('ja', 'site.releases.description', $json$"JayV の各バージョンで追加された内容を新しい順に掲載しています。アップデート後にアプリの新機能ウィンドウに表示されるものと同じ内容です。"$json$::jsonb),
  ('ja', 'site.releases.versions', $json$"バージョン"$json$::jsonb),
  ('ja', 'site.releases.version', $json$"バージョン {version}"$json$::jsonb),
  ('ja', 'site.releases.latest', $json$"最新"$json$::jsonb),
  ('ja', 'site.releases.features', $json$"新機能"$json$::jsonb),
  ('ja', 'site.releases.fixes', $json$"修正"$json$::jsonb),
  ('ja', 'site.releases.download', $json$"v{version} をダウンロード"$json$::jsonb),
  ('ja', 'site.releases.empty', $json$"現在リリースノートを読み込めません。数分後にもう一度お試しください。"$json$::jsonb),
  ('ja', 'site.docs.eyebrow', $json$"ドキュメント"$json$::jsonb),
  ('ja', 'site.docs.title', $json$"JayV の使い方"$json$::jsonb),
  ('ja', 'site.docs.description', $json$"アプリの各機能の場所と使い方を、チャット・キーボード・ターミナルのコマンドとあわせて説明します。バージョンごとに更新されます。"$json$::jsonb),
  ('ja', 'site.docs.search', $json$"ドキュメントを検索"$json$::jsonb),
  ('ja', 'site.docs.searchPlaceholder', $json$"機能やコマンドを検索…"$json$::jsonb),
  ('ja', 'site.docs.noResults', $json$"「{query}」に一致する内容はドキュメントにありません。"$json$::jsonb),
  ('ja', 'site.docs.contents', $json$"このページの内容"$json$::jsonb),
  ('ja', 'site.docs.howTo', $json$"使い方"$json$::jsonb),
  ('ja', 'site.docs.plan', $json$"プランによって異なります"$json$::jsonb),
  ('ja', 'site.docs.since', $json$"v{version} から"$json$::jsonb),
  ('ja', 'site.docs.link', $json$"{title} へのリンク"$json$::jsonb),
  ('ja', 'site.docs.commands', $json$"コマンド"$json$::jsonb),
  ('ja', 'site.docs.commands.chat', $json$"チャット"$json$::jsonb),
  ('ja', 'site.docs.commands.chat.detail', $json$"メッセージの先頭に入力します。"$json$::jsonb),
  ('ja', 'site.docs.commands.shortcut', $json$"キーボードショートカット"$json$::jsonb),
  ('ja', 'site.docs.commands.shortcut.detail', $json$"Windows と Linux では Ctrl、Mac では ⌘。"$json$::jsonb),
  ('ja', 'site.docs.ctrl', $json$"Ctrl"$json$::jsonb),
  ('ja', 'site.docs.commands.cli', $json$"ターミナル"$json$::jsonb),
  ('ja', 'site.docs.commands.cli.detail', $json$"プロジェクトのフォルダーで実行するか、--root でフォルダーを指定します。"$json$::jsonb),
  ('ja', 'site.docs.version', $json$"JayV v{version} のドキュメント。"$json$::jsonb),
  ('ja', 'site.docs.empty', $json$"現在ドキュメントを読み込めません。数分後にもう一度お試しください。"$json$::jsonb),
  ('ja', 'site.docs.category.start', $json$"はじめに"$json$::jsonb),
  ('ja', 'site.docs.category.chat', $json$"チャット"$json$::jsonb),
  ('ja', 'site.docs.category.agents', $json$"エージェントとモデル"$json$::jsonb),
  ('ja', 'site.docs.category.gate', $json$"ゲート"$json$::jsonb),
  ('ja', 'site.docs.category.privacy', $json$"プライバシーとセキュリティ"$json$::jsonb),
  ('ja', 'site.docs.category.project', $json$"プロジェクト"$json$::jsonb),
  ('ja', 'site.docs.category.team', $json$"組織"$json$::jsonb),
  ('ja', 'site.docs.category.account', $json$"アカウント"$json$::jsonb),
  ('ja', 'site.docs.category.app', $json$"アプリ"$json$::jsonb),
  ('ja', 'site.docs.category.other', $json$"その他"$json$::jsonb),
  ('ja', 'site.account.photo.change', $json$"写真を変更"$json$::jsonb),
  ('ja', 'site.account.photo.title', $json$"プロフィール写真"$json$::jsonb),
  ('ja', 'site.account.photo.description', $json$"画像を選び、円の中に表示される範囲を調整します。写真はどの方法でサインインしても、サイトとアプリに表示されます。"$json$::jsonb),
  ('ja', 'site.account.photo.choose', $json$"画像を選択"$json$::jsonb),
  ('ja', 'site.account.photo.drop', $json$"またはここにドラッグします。JPG、PNG、WebP、GIF、10 MB まで。"$json$::jsonb),
  ('ja', 'site.account.photo.drag', $json$"写真の切り抜き：ドラッグで移動、矢印キーで調整、+ または − でズーム"$json$::jsonb),
  ('ja', 'site.account.photo.hint', $json$"ドラッグして位置を決めます。スライダーかマウスホイールでズームします。"$json$::jsonb),
  ('ja', 'site.account.photo.zoom', $json$"ズーム"$json$::jsonb),
  ('ja', 'site.account.photo.zoomIn', $json$"拡大"$json$::jsonb),
  ('ja', 'site.account.photo.zoomOut', $json$"縮小"$json$::jsonb),
  ('ja', 'site.account.photo.another', $json$"別の画像"$json$::jsonb),
  ('ja', 'site.account.photo.reset', $json$"リセット"$json$::jsonb),
  ('ja', 'site.account.photo.save', $json$"写真を保存"$json$::jsonb),
  ('ja', 'site.account.photo.remove', $json$"写真を削除"$json$::jsonb),
  ('ja', 'site.account.photo.saved', $json$"プロフィール写真を更新しました。"$json$::jsonb),
  ('ja', 'site.account.photo.removed', $json$"プロフィール写真を削除しました。連携アカウントの写真があれば、それが表示されます。"$json$::jsonb),
  ('ja', 'site.account.photo.invalid', $json$"この画像は使用できません。10 MB までの JPG、PNG、WebP、GIF を選んでください。"$json$::jsonb),
  ('de', 'site.nav.docs', $json$"Dokumentation"$json$::jsonb),
  ('de', 'site.nav.openMenu', $json$"Menü öffnen"$json$::jsonb),
  ('de', 'site.nav.closeMenu', $json$"Menü schließen"$json$::jsonb),
  ('de', 'site.nav.accountMenu', $json$"Kontomenü"$json$::jsonb),
  ('de', 'site.nav.connected', $json$"Verbunden"$json$::jsonb),
  ('de', 'site.releases.eyebrow', $json$"Changelog"$json$::jsonb),
  ('de', 'site.releases.title', $json$"Versionshinweise"$json$::jsonb),
  ('de', 'site.releases.description', $json$"Was jede Version von JayV gebracht hat, die neueste zuerst: dieselben Hinweise, die die App nach einem Update unter Neu in JayV zeigt."$json$::jsonb),
  ('de', 'site.releases.versions', $json$"Versionen"$json$::jsonb),
  ('de', 'site.releases.version', $json$"Version {version}"$json$::jsonb),
  ('de', 'site.releases.latest', $json$"Neueste"$json$::jsonb),
  ('de', 'site.releases.features', $json$"Neu"$json$::jsonb),
  ('de', 'site.releases.fixes', $json$"Korrekturen"$json$::jsonb),
  ('de', 'site.releases.download', $json$"v{version} herunterladen"$json$::jsonb),
  ('de', 'site.releases.empty', $json$"Die Versionshinweise konnten gerade nicht geladen werden. Versuche es in ein paar Minuten erneut."$json$::jsonb),
  ('de', 'site.docs.eyebrow', $json$"Dokumentation"$json$::jsonb),
  ('de', 'site.docs.title', $json$"So nutzt du JayV"$json$::jsonb),
  ('de', 'site.docs.description', $json$"Jede Funktion der App, wo du sie findest und wie du sie nutzt, mit den Befehlen für Chat, Tastatur und Terminal. Mit jeder Version aktualisiert."$json$::jsonb),
  ('de', 'site.docs.search', $json$"Dokumentation durchsuchen"$json$::jsonb),
  ('de', 'site.docs.searchPlaceholder', $json$"Funktionen und Befehle suchen…"$json$::jsonb),
  ('de', 'site.docs.noResults', $json$"Nichts in der Dokumentation passt zu „{query}“."$json$::jsonb),
  ('de', 'site.docs.contents', $json$"Auf dieser Seite"$json$::jsonb),
  ('de', 'site.docs.howTo', $json$"So geht's"$json$::jsonb),
  ('de', 'site.docs.plan', $json$"Hängt von deinem Tarif ab"$json$::jsonb),
  ('de', 'site.docs.since', $json$"Seit v{version}"$json$::jsonb),
  ('de', 'site.docs.link', $json$"Link zu {title}"$json$::jsonb),
  ('de', 'site.docs.commands', $json$"Befehle"$json$::jsonb),
  ('de', 'site.docs.commands.chat', $json$"Im Chat"$json$::jsonb),
  ('de', 'site.docs.commands.chat.detail', $json$"Am Anfang einer Nachricht eingeben."$json$::jsonb),
  ('de', 'site.docs.commands.shortcut', $json$"Tastenkürzel"$json$::jsonb),
  ('de', 'site.docs.commands.shortcut.detail', $json$"Strg unter Windows und Linux, ⌘ auf dem Mac."$json$::jsonb),
  ('de', 'site.docs.ctrl', $json$"Strg"$json$::jsonb),
  ('de', 'site.docs.commands.cli', $json$"Terminal"$json$::jsonb),
  ('de', 'site.docs.commands.cli.detail', $json$"Im Projektordner ausführen oder den Ordner mit --root angeben."$json$::jsonb),
  ('de', 'site.docs.version', $json$"Dokumentation für JayV v{version}."$json$::jsonb),
  ('de', 'site.docs.empty', $json$"Die Dokumentation konnte gerade nicht geladen werden. Versuche es in ein paar Minuten erneut."$json$::jsonb),
  ('de', 'site.docs.category.start', $json$"Erste Schritte"$json$::jsonb),
  ('de', 'site.docs.category.chat', $json$"Chat"$json$::jsonb),
  ('de', 'site.docs.category.agents', $json$"Agenten und Modelle"$json$::jsonb),
  ('de', 'site.docs.category.gate', $json$"Pforte"$json$::jsonb),
  ('de', 'site.docs.category.privacy', $json$"Datenschutz und Sicherheit"$json$::jsonb),
  ('de', 'site.docs.category.project', $json$"Projekte"$json$::jsonb),
  ('de', 'site.docs.category.team', $json$"Organisationen"$json$::jsonb),
  ('de', 'site.docs.category.account', $json$"Konto"$json$::jsonb),
  ('de', 'site.docs.category.app', $json$"Die App"$json$::jsonb),
  ('de', 'site.docs.category.other', $json$"Mehr"$json$::jsonb),
  ('de', 'site.account.photo.change', $json$"Foto ändern"$json$::jsonb),
  ('de', 'site.account.photo.title', $json$"Profilfoto"$json$::jsonb),
  ('de', 'site.account.photo.description', $json$"Wähle ein Bild und passe an, was im Kreis zu sehen ist. Das Foto erscheint auf der Website und in der App, egal wie du dich anmeldest."$json$::jsonb),
  ('de', 'site.account.photo.choose', $json$"Bild auswählen"$json$::jsonb),
  ('de', 'site.account.photo.drop', $json$"Oder hierher ziehen. JPG, PNG, WebP oder GIF, bis zu 10 MB."$json$::jsonb),
  ('de', 'site.account.photo.drag', $json$"Fotoausschnitt: ziehen zum Verschieben, Pfeiltasten zum Anpassen und + oder − zum Zoomen"$json$::jsonb),
  ('de', 'site.account.photo.hint', $json$"Zum Positionieren ziehen. Mit dem Regler oder dem Mausrad zoomen."$json$::jsonb),
  ('de', 'site.account.photo.zoom', $json$"Zoom"$json$::jsonb),
  ('de', 'site.account.photo.zoomIn', $json$"Vergrößern"$json$::jsonb),
  ('de', 'site.account.photo.zoomOut', $json$"Verkleinern"$json$::jsonb),
  ('de', 'site.account.photo.another', $json$"Anderes Bild"$json$::jsonb),
  ('de', 'site.account.photo.reset', $json$"Zurücksetzen"$json$::jsonb),
  ('de', 'site.account.photo.save', $json$"Foto speichern"$json$::jsonb),
  ('de', 'site.account.photo.remove', $json$"Foto entfernen"$json$::jsonb),
  ('de', 'site.account.photo.saved', $json$"Profilfoto aktualisiert."$json$::jsonb),
  ('de', 'site.account.photo.removed', $json$"Profilfoto entfernt. Das Foto deines verknüpften Kontos ist wieder da, falls es eines gibt."$json$::jsonb),
  ('de', 'site.account.photo.invalid', $json$"Dieses Bild kann nicht verwendet werden. Wähle ein JPG, PNG, WebP oder GIF bis 10 MB."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
