-- v0.66.0: texto da alça de redimensionar o painel de andamento e as novidades
-- da versão (painel redimensionável; plano aprovado no Automático vai ao build).

insert into public.translations (locale, key, value) values
  ('en', 'progress.resize', $json$"Drag to resize the progress panel (arrow keys too, double-click to reset)"$json$::jsonb),
  ('en', 'whatsNew.item.progressResize.title', $json$"Resize the progress panel"$json$::jsonb),
  ('en', 'whatsNew.item.progressResize.detail', $json$"Drag the right edge of the progress panel beside the chat to make it wider or narrower. The arrow keys work on the edge too, and a double-click brings back the original width. JayV remembers the width you chose."$json$::jsonb),
  ('en', 'whatsNew.item.planApprovedAuto.title', $json$"Approving a plan in Auto mode now starts the change"$json$::jsonb),
  ('en', 'whatsNew.item.planApprovedAuto.detail', $json$"In Auto mode, when you approved a plan JayV had just written (\"approved, go ahead\", \"pode implementar\"), the request could still run in planning mode and the agent answered that it was only using the read-only plan context. Now an approval of a plan from the same chat runs in Development, as long as the request passes the gate and is not destructive."$json$::jsonb),
  ('pt-BR', 'progress.resize', $json$"Arraste para redimensionar o painel de andamento (as setas também servem; clique duplo restaura)"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.progressResize.title', $json$"Redimensione o painel de andamento"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.progressResize.detail', $json$"Arraste a borda direita do painel de andamento ao lado do chat para deixá-lo mais largo ou mais estreito. As setas do teclado também funcionam na borda, e um clique duplo volta à largura original. O JayV lembra a largura que você escolheu."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planApprovedAuto.title', $json$"Aprovar um plano no modo Automático agora inicia a mudança"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planApprovedAuto.detail', $json$"No modo Automático, quando você aprovava um plano que o JayV tinha acabado de escrever (\"aprovado, pode implementar\"), o pedido ainda podia rodar em planejamento e o agente respondia que só usava o contexto de plano em somente leitura. Agora a aprovação de um plano do mesmo chat roda em Desenvolvimento, desde que o pedido passe pela portaria e não seja destrutivo."$json$::jsonb),
  ('es', 'progress.resize', $json$"Arrastra para cambiar el ancho del panel de progreso (también con las flechas; doble clic lo restablece)"$json$::jsonb),
  ('es', 'whatsNew.item.progressResize.title', $json$"Cambia el ancho del panel de progreso"$json$::jsonb),
  ('es', 'whatsNew.item.progressResize.detail', $json$"Arrastra el borde derecho del panel de progreso junto al chat para hacerlo más ancho o más estrecho. Las flechas del teclado también funcionan en el borde y un doble clic devuelve el ancho original. JayV recuerda el ancho que elegiste."$json$::jsonb),
  ('es', 'whatsNew.item.planApprovedAuto.title', $json$"Aprobar un plan en modo Automático ahora inicia el cambio"$json$::jsonb),
  ('es', 'whatsNew.item.planApprovedAuto.detail', $json$"En modo Automático, cuando aprobabas un plan que JayV acababa de escribir («aprobado, adelante»), la solicitud aún podía ejecutarse en planificación y el agente respondía que solo usaba el contexto de plan de solo lectura. Ahora la aprobación de un plan del mismo chat se ejecuta en Desarrollo, siempre que la solicitud pase por la portería y no sea destructiva."$json$::jsonb),
  ('fr', 'progress.resize', $json$"Faites glisser pour redimensionner le panneau de progression (flèches du clavier aussi ; double-clic pour rétablir)"$json$::jsonb),
  ('fr', 'whatsNew.item.progressResize.title', $json$"Redimensionner le panneau de progression"$json$::jsonb),
  ('fr', 'whatsNew.item.progressResize.detail', $json$"Faites glisser le bord droit du panneau de progression à côté du chat pour l'élargir ou le rétrécir. Les flèches du clavier fonctionnent aussi sur le bord, et un double-clic rétablit la largeur d'origine. JayV retient la largeur choisie."$json$::jsonb),
  ('fr', 'whatsNew.item.planApprovedAuto.title', $json$"Approuver un plan en mode Automatique lance désormais la modification"$json$::jsonb),
  ('fr', 'whatsNew.item.planApprovedAuto.detail', $json$"En mode Automatique, quand vous approuviez un plan que JayV venait d'écrire (« approuvé, allez-y »), la demande pouvait encore s'exécuter en planification et l'agent répondait n'utiliser que le contexte de plan en lecture seule. Désormais, l'approbation d'un plan du même chat s'exécute en Développement, tant que la demande passe la porterie et n'est pas destructive."$json$::jsonb),
  ('de', 'progress.resize', $json$"Ziehen, um das Fortschrittsfenster in der Breite zu ändern (auch mit den Pfeiltasten; Doppelklick setzt zurück)"$json$::jsonb),
  ('de', 'whatsNew.item.progressResize.title', $json$"Fortschrittsfenster in der Breite ändern"$json$::jsonb),
  ('de', 'whatsNew.item.progressResize.detail', $json$"Ziehen Sie den rechten Rand des Fortschrittsfensters neben dem Chat, um es breiter oder schmaler zu machen. Die Pfeiltasten funktionieren am Rand ebenfalls, ein Doppelklick stellt die ursprüngliche Breite wieder her. JayV merkt sich die gewählte Breite."$json$::jsonb),
  ('de', 'whatsNew.item.planApprovedAuto.title', $json$"Einen Plan im Automatikmodus zu genehmigen startet jetzt die Änderung"$json$::jsonb),
  ('de', 'whatsNew.item.planApprovedAuto.detail', $json$"Im Automatikmodus konnte die Anfrage nach der Genehmigung eines frisch von JayV geschriebenen Plans („genehmigt, leg los“) noch im Planungsmodus laufen, und der Agent antwortete, er nutze nur den schreibgeschützten Plankontext. Jetzt läuft die Genehmigung eines Plans aus demselben Chat in der Entwicklung, solange die Anfrage das Gate passiert und nicht destruktiv ist."$json$::jsonb),
  ('ru', 'progress.resize', $json$"Перетащите, чтобы изменить ширину панели хода работы (стрелки тоже работают; двойной щелчок сбрасывает)"$json$::jsonb),
  ('ru', 'whatsNew.item.progressResize.title', $json$"Изменение ширины панели хода работы"$json$::jsonb),
  ('ru', 'whatsNew.item.progressResize.detail', $json$"Перетащите правый край панели хода работы рядом с чатом, чтобы сделать её шире или уже. На краю работают и стрелки клавиатуры, а двойной щелчок возвращает исходную ширину. JayV запоминает выбранную ширину."$json$::jsonb),
  ('ru', 'whatsNew.item.planApprovedAuto.title', $json$"Одобрение плана в автоматическом режиме теперь запускает изменение"$json$::jsonb),
  ('ru', 'whatsNew.item.planApprovedAuto.detail', $json$"В автоматическом режиме, когда вы одобряли только что написанный JayV план («одобрено, приступай»), запрос мог всё равно выполняться в режиме планирования, а агент отвечал, что использует лишь контекст плана только для чтения. Теперь одобрение плана из того же чата выполняется в режиме разработки, если запрос проходит шлюз и не является разрушительным."$json$::jsonb),
  ('zh-CN', 'progress.resize', $json$"拖动以调整进度面板宽度（也可用方向键；双击恢复）"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.progressResize.title', $json$"调整进度面板宽度"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.progressResize.detail', $json$"拖动聊天旁进度面板的右边缘，可以把它拉宽或收窄。边缘上也可以用方向键，双击则恢复原始宽度。JayV 会记住你选择的宽度。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planApprovedAuto.title', $json$"在自动模式下批准计划，现在会开始修改"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planApprovedAuto.detail', $json$"在自动模式下，当你批准 JayV 刚写好的计划（“批准，开始吧”）时，请求仍可能在规划模式下运行，智能体会回答说它只在使用只读的计划上下文。现在，对同一聊天中计划的批准会在开发模式下运行，只要请求通过关卡且不具破坏性。"$json$::jsonb),
  ('ja', 'progress.resize', $json$"ドラッグして進行状況パネルの幅を変更（矢印キーも可、ダブルクリックで元に戻す）"$json$::jsonb),
  ('ja', 'whatsNew.item.progressResize.title', $json$"進行状況パネルの幅を変更"$json$::jsonb),
  ('ja', 'whatsNew.item.progressResize.detail', $json$"チャットの横にある進行状況パネルの右端をドラッグすると、幅を広げたり狭めたりできます。端では矢印キーも使え、ダブルクリックで元の幅に戻ります。JayV は選んだ幅を覚えています。"$json$::jsonb),
  ('ja', 'whatsNew.item.planApprovedAuto.title', $json$"自動モードでプランを承認すると、変更が始まるようになりました"$json$::jsonb),
  ('ja', 'whatsNew.item.planApprovedAuto.detail', $json$"自動モードで、JayV が書いたばかりのプランを承認しても（「承認、進めて」）、依頼が計画モードのまま実行され、エージェントが読み取り専用のプランコンテキストを使っているだけだと答えることがありました。今は同じチャットのプランの承認が開発モードで実行されます。依頼がゲートを通り、破壊的でない場合に限ります。"$json$::jsonb),
  ('ar', 'progress.resize', $json$"اسحب لتغيير عرض لوحة التقدّم (مفاتيح الأسهم تعمل أيضًا؛ النقر المزدوج يعيد الضبط)"$json$::jsonb),
  ('ar', 'whatsNew.item.progressResize.title', $json$"تغيير عرض لوحة التقدّم"$json$::jsonb),
  ('ar', 'whatsNew.item.progressResize.detail', $json$"اسحب الحافة اليمنى للوحة التقدّم بجانب المحادثة لجعلها أعرض أو أضيق. تعمل مفاتيح الأسهم على الحافة أيضًا، والنقر المزدوج يعيد العرض الأصلي. يتذكّر JayV العرض الذي اخترته."$json$::jsonb),
  ('ar', 'whatsNew.item.planApprovedAuto.title', $json$"الموافقة على خطة في الوضع التلقائي تبدأ التغيير الآن"$json$::jsonb),
  ('ar', 'whatsNew.item.planApprovedAuto.detail', $json$"في الوضع التلقائي، عندما كنت توافق على خطة كتبها JayV للتو («موافق، تابع»)، كان الطلب لا يزال يعمل في وضع التخطيط وكان الوكيل يجيب بأنه يستخدم فقط سياق الخطة للقراءة فقط. الآن تعمل الموافقة على خطة من المحادثة نفسها في وضع التطوير، ما دام الطلب يمرّ عبر البوابة وليس مدمّرًا."$json$::jsonb),
  ('hi', 'progress.resize', $json$"प्रगति पैनल की चौड़ाई बदलने के लिए खींचें (तीर कुंजियाँ भी चलती हैं; डबल-क्लिक से रीसेट)"$json$::jsonb),
  ('hi', 'whatsNew.item.progressResize.title', $json$"प्रगति पैनल की चौड़ाई बदलें"$json$::jsonb),
  ('hi', 'whatsNew.item.progressResize.detail', $json$"चैट के बगल वाले प्रगति पैनल के दाएँ किनारे को खींचकर उसे चौड़ा या संकरा करें। किनारे पर तीर कुंजियाँ भी काम करती हैं और डबल-क्लिक से मूल चौड़ाई लौट आती है। JayV आपकी चुनी हुई चौड़ाई याद रखता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.planApprovedAuto.title', $json$"ऑटो मोड में योजना मंज़ूर करने पर अब बदलाव शुरू होता है"$json$::jsonb),
  ('hi', 'whatsNew.item.planApprovedAuto.detail', $json$"ऑटो मोड में, जब आप JayV की अभी लिखी योजना मंज़ूर करते थे («मंज़ूर, आगे बढ़ो»), तब भी अनुरोध प्लानिंग में चल सकता था और एजेंट जवाब देता था कि वह केवल पढ़ने-भर वाले योजना संदर्भ का उपयोग कर रहा है। अब उसी चैट की योजना की मंज़ूरी डेवलपमेंट में चलती है, बशर्ते अनुरोध गेट पार करे और विनाशकारी न हो।"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
