-- v0.59.0: o `jayv bench` mede voltas até a tarefa ficar pronta e dólares por
-- lado, com cópias separadas, ordem alternada e a portaria ligada. Só textos.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.item.benchRounds.title', $json$"O jayv bench mede as voltas até ficar pronto"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.benchRounds.detail', $json$"O benchmark de linha de comando agora roda um arquivo de tarefas: cada tarefa tem o roteiro de um iniciante e um comando que diz quando ela ficou pronta. O JayV e o agente sozinho trabalham cada um numa cópia própria do projeto, em ordem alternada, com a portaria ligada para o JayV, e o resultado é quantos pedidos e quantos dólares cada lado precisou. Um exemplo com dez tarefas vem em src-tauri/bench."$json$::jsonb),
  ('en', 'whatsNew.item.benchRounds.title', $json$"jayv bench measures rounds until done"$json$::jsonb),
  ('en', 'whatsNew.item.benchRounds.detail', $json$"The command-line benchmark now runs a task file: each task has a beginner's script and a command that tells when it is done. JayV and the agent alone each work in their own copy of the project, in alternating order, with the gatehouse on for JayV, and the result is how many requests and how many dollars each side needed. An example with ten tasks comes in src-tauri/bench."$json$::jsonb),
  ('es', 'whatsNew.item.benchRounds.title', $json$"jayv bench mide las vueltas hasta que esté listo"$json$::jsonb),
  ('es', 'whatsNew.item.benchRounds.detail', $json$"El benchmark de línea de comandos ahora ejecuta un archivo de tareas: cada tarea tiene el guion de un principiante y un comando que indica cuándo está lista. JayV y el agente solo trabajan cada uno en su propia copia del proyecto, en orden alterno, con la portería activa para JayV, y el resultado es cuántas solicitudes y cuántos dólares necesitó cada lado. Un ejemplo con diez tareas viene en src-tauri/bench."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.benchRounds.title', $json$"jayv bench 统计完成任务所需的来回次数"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.benchRounds.detail', $json$"命令行基准测试现在运行一个任务文件：每个任务包含一段新手的对话脚本和一个判断任务是否完成的命令。JayV 和单独的智能体各自在项目的独立副本中工作，顺序交替，JayV 一侧开启门房，结果是每一侧需要多少个请求、花多少美元。src-tauri/bench 中附带一个包含十个任务的示例。"$json$::jsonb),
  ('hi', 'whatsNew.item.benchRounds.title', $json$"jayv bench काम पूरा होने तक के चक्कर मापता है"$json$::jsonb),
  ('hi', 'whatsNew.item.benchRounds.detail', $json$"कमांड-लाइन बेंचमार्क अब एक टास्क फ़ाइल चलाता है: हर टास्क में एक नौसिखिए की स्क्रिप्ट और एक कमांड है जो बताती है कि काम कब पूरा हुआ। JayV और अकेला एजेंट दोनों प्रोजेक्ट की अपनी-अपनी कॉपी में बारी-बारी से काम करते हैं, JayV के लिए गेटहाउस चालू रहता है, और नतीजा यह होता है कि हर पक्ष को कितने अनुरोध और कितने डॉलर लगे। दस टास्क वाला एक उदाहरण src-tauri/bench में है।"$json$::jsonb),
  ('ar', 'whatsNew.item.benchRounds.title', $json$"يقيس jayv bench الجولات حتى اكتمال المهمة"$json$::jsonb),
  ('ar', 'whatsNew.item.benchRounds.detail', $json$"صار اختبار الأداء من سطر الأوامر يشغّل ملف مهام: لكل مهمة نص مبتدئ وأمر يحدد متى اكتملت. يعمل JayV والوكيل وحده كلٌّ في نسخته الخاصة من المشروع، بترتيب متناوب، مع تفعيل البوابة لـ JayV، والنتيجة هي عدد الطلبات وعدد الدولارات التي احتاجها كل جانب. يأتي مثال بعشر مهام في src-tauri/bench."$json$::jsonb),
  ('fr', 'whatsNew.item.benchRounds.title', $json$"jayv bench mesure les allers-retours jusqu’à ce que ce soit fait"$json$::jsonb),
  ('fr', 'whatsNew.item.benchRounds.detail', $json$"Le benchmark en ligne de commande exécute désormais un fichier de tâches : chaque tâche a le scénario d’un débutant et une commande qui indique quand elle est terminée. JayV et l’agent seul travaillent chacun dans sa propre copie du projet, dans un ordre alterné, avec le poste de garde activé pour JayV, et le résultat est le nombre de demandes et de dollars qu’il a fallu à chaque côté. Un exemple avec dix tâches est fourni dans src-tauri/bench."$json$::jsonb),
  ('ru', 'whatsNew.item.benchRounds.title', $json$"jayv bench считает круги до готового результата"$json$::jsonb),
  ('ru', 'whatsNew.item.benchRounds.detail', $json$"Бенчмарк командной строки теперь запускает файл задач: у каждой задачи есть сценарий новичка и команда, которая говорит, что задача готова. JayV и агент сам по себе работают каждый в своей копии проекта, по очереди, с включённой проходной для JayV, а результат — сколько запросов и долларов понадобилось каждой стороне. Пример с десятью задачами лежит в src-tauri/bench."$json$::jsonb),
  ('ja', 'whatsNew.item.benchRounds.title', $json$"jayv bench が完了までのやり取りの回数を測ります"$json$::jsonb),
  ('ja', 'whatsNew.item.benchRounds.detail', $json$"コマンドラインのベンチマークがタスクファイルを実行するようになりました。各タスクには初心者の台本と、完了を判定するコマンドがあります。JayV と単独のエージェントはそれぞれプロジェクトの別コピーで交互に作業し、JayV 側ではゲートが有効になります。結果は、それぞれが必要としたリクエスト数と金額です。10個のタスクの例が src-tauri/bench に含まれています。"$json$::jsonb),
  ('de', 'whatsNew.item.benchRounds.title', $json$"jayv bench misst die Runden bis zur fertigen Aufgabe"$json$::jsonb),
  ('de', 'whatsNew.item.benchRounds.detail', $json$"Der Kommandozeilen-Benchmark führt jetzt eine Aufgabendatei aus: Jede Aufgabe hat das Skript eines Einsteigers und einen Befehl, der sagt, wann sie fertig ist. JayV und der Agent allein arbeiten jeweils in einer eigenen Kopie des Projekts, abwechselnd, mit eingeschaltetem Pförtnerhaus für JayV, und das Ergebnis ist, wie viele Anfragen und wie viele Dollar jede Seite brauchte. Ein Beispiel mit zehn Aufgaben liegt in src-tauri/bench."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
