-- v0.63.0: as novidades da versão — a foto de perfil escolhida no site em todo
-- login, a documentação e as notas da versão no site e as atualizações pela
-- função releases do Supabase.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.item.profilePhoto.title', $json$"A sua foto de perfil, seja qual for a forma de login"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.profilePhoto.detail', $json$"A foto que você escolhe e recorta na sua conta no site do JayV agora aparece no app, entrando com e-mail e senha ou com uma conta vinculada. Removê-la traz de volta a foto da conta vinculada."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.onlineManual.title', $json$"Documentação e notas da versão no site"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.onlineManual.detail', $json$"Cada funcionalidade e cada comando do JayV agora têm uma página na Documentação do site, e a página Notas da versão lista tudo que cada versão trouxe, atualizadas a cada release."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updatesViaServer.title', $json$"As atualizações passam pelo servidor do JayV"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.updatesViaServer.detail', $json$"O app agora procura e baixa versões novas pelo servidor do próprio JayV, em vez de ir direto ao repositório de releases."$json$::jsonb),
  ('en', 'whatsNew.item.profilePhoto.title', $json$"Your profile photo, whatever way you sign in"$json$::jsonb),
  ('en', 'whatsNew.item.profilePhoto.detail', $json$"The photo you choose and crop in your account on the JayV site now shows in the app, whether you sign in with email and password or with a linked account. Removing it brings back the photo of your linked account."$json$::jsonb),
  ('en', 'whatsNew.item.onlineManual.title', $json$"Documentation and release notes on the site"$json$::jsonb),
  ('en', 'whatsNew.item.onlineManual.detail', $json$"Every feature and command of JayV now has a page in the Documentation on the site, and the Release notes page lists everything each version brought, updated with every release."$json$::jsonb),
  ('en', 'whatsNew.item.updatesViaServer.title', $json$"Updates come through JayV's server"$json$::jsonb),
  ('en', 'whatsNew.item.updatesViaServer.detail', $json$"The app now checks for and downloads new versions through JayV's own server instead of going straight to the releases repository."$json$::jsonb),
  ('es', 'whatsNew.item.profilePhoto.title', $json$"Tu foto de perfil, sea cual sea la forma de iniciar sesión"$json$::jsonb),
  ('es', 'whatsNew.item.profilePhoto.detail', $json$"La foto que eliges y recortas en tu cuenta del sitio de JayV ahora aparece en la app, tanto si inicias sesión con correo y contraseña como con una cuenta vinculada. Quitarla trae de vuelta la foto de tu cuenta vinculada."$json$::jsonb),
  ('es', 'whatsNew.item.onlineManual.title', $json$"Documentación y notas de la versión en el sitio"$json$::jsonb),
  ('es', 'whatsNew.item.onlineManual.detail', $json$"Cada función y cada comando de JayV tienen ahora una página en la Documentación del sitio, y la página Notas de la versión enumera todo lo que trajo cada versión, actualizadas con cada release."$json$::jsonb),
  ('es', 'whatsNew.item.updatesViaServer.title', $json$"Las actualizaciones pasan por el servidor de JayV"$json$::jsonb),
  ('es', 'whatsNew.item.updatesViaServer.detail', $json$"La app ahora busca y descarga las versiones nuevas a través del propio servidor de JayV, en lugar de ir directamente al repositorio de releases."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.profilePhoto.title', $json$"无论以何种方式登录，都显示你的个人资料照片"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.profilePhoto.detail', $json$"你在 JayV 网站账户中选择并裁剪的照片现在会显示在应用中，无论你用邮箱和密码还是关联账户登录。移除后会恢复为关联账户的照片。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.onlineManual.title', $json$"网站上的文档和版本说明"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.onlineManual.detail', $json$"JayV 的每项功能和每个命令现在都在网站的文档中有自己的页面，版本说明页面列出每个版本带来的全部内容，随每次发布更新。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updatesViaServer.title', $json$"更新通过 JayV 的服务器进行"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.updatesViaServer.detail', $json$"应用现在通过 JayV 自己的服务器检查和下载新版本，而不是直接访问发布仓库。"$json$::jsonb),
  ('hi', 'whatsNew.item.profilePhoto.title', $json$"आपकी प्रोफ़ाइल फ़ोटो, आप किसी भी तरह साइन इन करें"$json$::jsonb),
  ('hi', 'whatsNew.item.profilePhoto.detail', $json$"JayV साइट पर अपने खाते में चुनी और क्रॉप की गई फ़ोटो अब ऐप में दिखती है, चाहे आप ईमेल और पासवर्ड से साइन इन करें या लिंक किए गए खाते से। उसे हटाने पर लिंक किए गए खाते की फ़ोटो वापस आ जाती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.onlineManual.title', $json$"साइट पर दस्तावेज़ और रिलीज़ नोट्स"$json$::jsonb),
  ('hi', 'whatsNew.item.onlineManual.detail', $json$"JayV की हर सुविधा और हर कमांड का अब साइट के दस्तावेज़ में अपना पेज है, और रिलीज़ नोट्स पेज पर हर संस्करण में आया सब कुछ है, जो हर रिलीज़ के साथ अपडेट होता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.updatesViaServer.title', $json$"अपडेट अब JayV के सर्वर से आते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.updatesViaServer.detail', $json$"ऐप अब नए संस्करण सीधे रिलीज़ रिपॉज़िटरी से लेने के बजाय JayV के अपने सर्वर से जाँचता और डाउनलोड करता है।"$json$::jsonb),
  ('ar', 'whatsNew.item.profilePhoto.title', $json$"صورة ملفك الشخصي، مهما كانت طريقة تسجيل الدخول"$json$::jsonb),
  ('ar', 'whatsNew.item.profilePhoto.detail', $json$"الصورة التي تختارها وتقصّها في حسابك على موقع JayV تظهر الآن في التطبيق، سواء سجّلت الدخول بالبريد الإلكتروني وكلمة المرور أو بحساب مرتبط. وإزالتها تعيد صورة حسابك المرتبط."$json$::jsonb),
  ('ar', 'whatsNew.item.onlineManual.title', $json$"التوثيق وملاحظات الإصدار على الموقع"$json$::jsonb),
  ('ar', 'whatsNew.item.onlineManual.detail', $json$"لكل ميزة وكل أمر في JayV الآن صفحة في توثيق الموقع، وتعرض صفحة ملاحظات الإصدار كل ما جاء به كل إصدار، وتُحدَّث مع كل إصدار جديد."$json$::jsonb),
  ('ar', 'whatsNew.item.updatesViaServer.title', $json$"التحديثات تمر عبر خادم JayV"$json$::jsonb),
  ('ar', 'whatsNew.item.updatesViaServer.detail', $json$"يبحث التطبيق الآن عن الإصدارات الجديدة وينزّلها عبر خادم JayV نفسه، بدل التوجه مباشرة إلى مستودع الإصدارات."$json$::jsonb),
  ('fr', 'whatsNew.item.profilePhoto.title', $json$"Votre photo de profil, quelle que soit votre façon de vous connecter"$json$::jsonb),
  ('fr', 'whatsNew.item.profilePhoto.detail', $json$"La photo que vous choisissez et recadrez dans votre compte sur le site de JayV apparaît maintenant dans l'application, que vous vous connectiez par e-mail et mot de passe ou avec un compte associé. La supprimer fait revenir la photo de votre compte associé."$json$::jsonb),
  ('fr', 'whatsNew.item.onlineManual.title', $json$"Documentation et notes de version sur le site"$json$::jsonb),
  ('fr', 'whatsNew.item.onlineManual.detail', $json$"Chaque fonctionnalité et chaque commande de JayV a désormais sa page dans la Documentation du site, et la page Notes de version liste tout ce que chaque version a apporté, mises à jour à chaque release."$json$::jsonb),
  ('fr', 'whatsNew.item.updatesViaServer.title', $json$"Les mises à jour passent par le serveur de JayV"$json$::jsonb),
  ('fr', 'whatsNew.item.updatesViaServer.detail', $json$"L'application recherche et télécharge désormais les nouvelles versions via le serveur de JayV, au lieu d'aller directement au dépôt des releases."$json$::jsonb),
  ('ru', 'whatsNew.item.profilePhoto.title', $json$"Ваше фото профиля при любом способе входа"$json$::jsonb),
  ('ru', 'whatsNew.item.profilePhoto.detail', $json$"Фото, которое вы выбираете и кадрируете в своём аккаунте на сайте JayV, теперь показывается в приложении — при входе и по почте с паролем, и через привязанный аккаунт. Если удалить его, вернётся фото привязанного аккаунта."$json$::jsonb),
  ('ru', 'whatsNew.item.onlineManual.title', $json$"Документация и примечания к версиям на сайте"$json$::jsonb),
  ('ru', 'whatsNew.item.onlineManual.detail', $json$"У каждой функции и команды JayV теперь есть страница в Документации на сайте, а на странице «Примечания к версиям» перечислено всё, что принесла каждая версия; обновляется с каждым релизом."$json$::jsonb),
  ('ru', 'whatsNew.item.updatesViaServer.title', $json$"Обновления идут через сервер JayV"$json$::jsonb),
  ('ru', 'whatsNew.item.updatesViaServer.detail', $json$"Теперь приложение проверяет и скачивает новые версии через собственный сервер JayV, а не обращается напрямую к репозиторию релизов."$json$::jsonb),
  ('ja', 'whatsNew.item.profilePhoto.title', $json$"どの方法でサインインしてもプロフィール写真が表示されます"$json$::jsonb),
  ('ja', 'whatsNew.item.profilePhoto.detail', $json$"JayV サイトのアカウントで選んで切り抜いた写真が、メールアドレスとパスワードでも連携アカウントでも、サインインするとアプリに表示されるようになりました。削除すると、連携アカウントの写真に戻ります。"$json$::jsonb),
  ('ja', 'whatsNew.item.onlineManual.title', $json$"サイトにドキュメントとリリースノート"$json$::jsonb),
  ('ja', 'whatsNew.item.onlineManual.detail', $json$"JayV のすべての機能とコマンドにサイトのドキュメントのページができ、リリースノートのページには各バージョンの内容がすべて載ります。リリースのたびに更新されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.updatesViaServer.title', $json$"アップデートは JayV のサーバー経由になりました"$json$::jsonb),
  ('ja', 'whatsNew.item.updatesViaServer.detail', $json$"アプリは新しいバージョンの確認とダウンロードを、リリースのリポジトリへ直接ではなく、JayV 自身のサーバー経由で行うようになりました。"$json$::jsonb),
  ('de', 'whatsNew.item.profilePhoto.title', $json$"Dein Profilfoto, egal wie du dich anmeldest"$json$::jsonb),
  ('de', 'whatsNew.item.profilePhoto.detail', $json$"Das Foto, das du in deinem Konto auf der JayV-Website auswählst und zuschneidest, erscheint jetzt in der App, ob du dich mit E-Mail und Passwort oder mit einem verknüpften Konto anmeldest. Entfernst du es, kommt das Foto deines verknüpften Kontos zurück."$json$::jsonb),
  ('de', 'whatsNew.item.onlineManual.title', $json$"Dokumentation und Versionshinweise auf der Website"$json$::jsonb),
  ('de', 'whatsNew.item.onlineManual.detail', $json$"Jede Funktion und jeder Befehl von JayV hat jetzt eine Seite in der Dokumentation der Website, und die Seite Versionshinweise listet alles, was jede Version gebracht hat, aktualisiert mit jedem Release."$json$::jsonb),
  ('de', 'whatsNew.item.updatesViaServer.title', $json$"Updates kommen über den JayV-Server"$json$::jsonb),
  ('de', 'whatsNew.item.updatesViaServer.detail', $json$"Die App sucht und lädt neue Versionen jetzt über den eigenen Server von JayV, statt direkt zum Release-Repository zu gehen."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
