-- v0.67.0: permissões da próxima mensagem (seletor ao lado do modo) e a
-- pergunta Executar/Negar/Sempre permitir quando o agente é bloqueado por uma
-- permissão; novidades da versão.

insert into public.translations (locale, key, value) values
  ('en', 'ask.permission.title', $json$"Permission"$json$::jsonb),
  ('en', 'ask.permission.prompt', $json${"one":"The agent was blocked and asks to run this command:","other":"The agent was blocked and asks to run these commands:"}$json$::jsonb),
  ('en', 'ask.permission.hint', $json$"Run allows it for this request only and sends the request again. Always allow also saves the start of the command for this project; you can remove it under Permissions, next to the mode. Deny keeps the answer as it is."$json$::jsonb),
  ('en', 'ask.permission.run', $json$"Run"$json$::jsonb),
  ('en', 'ask.permission.always', $json$"Always allow"$json$::jsonb),
  ('en', 'ask.permission.deny', $json$"Deny"$json$::jsonb),
  ('en', 'grants.label', $json$"Permissions"$json$::jsonb),
  ('en', 'grants.active', $json${"one":"{count} permission","other":"{count} permissions"}$json$::jsonb),
  ('en', 'grants.title', $json$"Permissions for the next message"$json$::jsonb),
  ('en', 'grants.hint', $json$"Only for the next message you send in this chat, in development mode. With nothing on, when the agent is blocked JayV asks above the message box whether to run, deny or always allow the command."$json$::jsonb),
  ('en', 'grants.shell', $json$"Run commands"$json$::jsonb),
  ('en', 'grants.shell.hint', $json$"Tests, builds and scripts without asking. Codex already runs commands inside its sandbox."$json$::jsonb),
  ('en', 'grants.git', $json$"Write to Git"$json$::jsonb),
  ('en', 'grants.git.hint', $json$"git add, commit and other commands that change .git. On Codex this opens the full sandbox for the request."$json$::jsonb),
  ('en', 'grants.network', $json$"Use the network"$json$::jsonb),
  ('en', 'grants.network.hint', $json$"Install packages and download files."$json$::jsonb),
  ('en', 'grants.always', $json$"Always allowed in this project"$json$::jsonb),
  ('en', 'grants.always.none', $json$"None yet. Use Always allow when the agent asks."$json$::jsonb),
  ('en', 'grants.always.hint', $json$"Codex has no per-command list: an always-allowed git command opens .git on every request in this project."$json$::jsonb),
  ('en', 'grants.forget', $json$"Stop always allowing {command}"$json$::jsonb),
  ('en', 'grant.once', $json$"Allowed for this request: {commands}"$json$::jsonb),
  ('en', 'grant.always', $json$"Allowed from now on in this project: {commands}"$json$::jsonb),
  ('en', 'beat.permissionDenied', $json$"Permission denied: {commands}"$json$::jsonb),
  ('en', 'source.permission', $json$"the agent's permission request"$json$::jsonb),
  ('en', 'whatsNew.item.messagePermissions.title', $json$"Permissions for the next message"$json$::jsonb),
  ('en', 'whatsNew.item.messagePermissions.detail', $json$"Next to the mode, Permissions lets you allow commands, Git writes and the network only for the next message you send. The /plan, /build and /auto hint left the message box to make room."$json$::jsonb),
  ('en', 'whatsNew.item.blockedCommandAsks.title', $json$"A blocked command now asks you"$json$::jsonb),
  ('en', 'whatsNew.item.blockedCommandAsks.detail', $json$"When the agent is blocked by a permission (Codex could not run git add because .git is read-only, for example), JayV asks above the message box whether to run the command, deny it or always allow it in the project, instead of only reporting it. Run sends the request again with that permission."$json$::jsonb),
  ('pt-BR', 'ask.permission.title', $json$"Permissão"$json$::jsonb),
  ('pt-BR', 'ask.permission.prompt', $json${"one":"O agente foi bloqueado e pede para executar este comando:","other":"O agente foi bloqueado e pede para executar estes comandos:"}$json$::jsonb),
  ('pt-BR', 'ask.permission.hint', $json$"Executar libera só para este pedido e envia o pedido de novo. Sempre permitir também guarda o começo do comando neste projeto; dá para tirar em Permissões, ao lado do modo. Negar deixa a resposta como está."$json$::jsonb),
  ('pt-BR', 'ask.permission.run', $json$"Executar"$json$::jsonb),
  ('pt-BR', 'ask.permission.always', $json$"Sempre permitir"$json$::jsonb),
  ('pt-BR', 'ask.permission.deny', $json$"Negar"$json$::jsonb),
  ('pt-BR', 'grants.label', $json$"Permissões"$json$::jsonb),
  ('pt-BR', 'grants.active', $json${"one":"{count} permissão","other":"{count} permissões"}$json$::jsonb),
  ('pt-BR', 'grants.title', $json$"Permissões da próxima mensagem"$json$::jsonb),
  ('pt-BR', 'grants.hint', $json$"Valem só para a próxima mensagem que você enviar neste chat, no modo desenvolvimento. Sem nada ligado, quando o agente for bloqueado o JayV pergunta acima da caixa de mensagem se executa, nega ou sempre permite o comando."$json$::jsonb),
  ('pt-BR', 'grants.shell', $json$"Rodar comandos"$json$::jsonb),
  ('pt-BR', 'grants.shell.hint', $json$"Testes, builds e scripts sem perguntar. O Codex já roda comandos dentro do sandbox dele."$json$::jsonb),
  ('pt-BR', 'grants.git', $json$"Escrever no Git"$json$::jsonb),
  ('pt-BR', 'grants.git.hint', $json$"git add, commit e outros comandos que mexem no .git. No Codex isto abre o sandbox inteiro para o pedido."$json$::jsonb),
  ('pt-BR', 'grants.network', $json$"Usar a rede"$json$::jsonb),
  ('pt-BR', 'grants.network.hint', $json$"Instalar pacotes e baixar arquivos."$json$::jsonb),
  ('pt-BR', 'grants.always', $json$"Sempre permitidos neste projeto"$json$::jsonb),
  ('pt-BR', 'grants.always.none', $json$"Nenhum ainda. Use Sempre permitir quando o agente perguntar."$json$::jsonb),
  ('pt-BR', 'grants.always.hint', $json$"O Codex não tem lista por comando: um comando git sempre permitido abre o .git em todo pedido deste projeto."$json$::jsonb),
  ('pt-BR', 'grants.forget', $json$"Deixar de sempre permitir {command}"$json$::jsonb),
  ('pt-BR', 'grant.once', $json$"Liberado para este pedido: {commands}"$json$::jsonb),
  ('pt-BR', 'grant.always', $json$"Liberado a partir de agora neste projeto: {commands}"$json$::jsonb),
  ('pt-BR', 'beat.permissionDenied', $json$"Permissão negada: {commands}"$json$::jsonb),
  ('pt-BR', 'source.permission', $json$"o pedido de permissão do agente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.messagePermissions.title', $json$"Permissões da próxima mensagem"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.messagePermissions.detail', $json$"Ao lado do modo, Permissões libera comandos, escrita no Git e rede só para a próxima mensagem que você enviar. A dica de /plan, /build e /auto saiu da caixa de mensagem para dar espaço."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.blockedCommandAsks.title', $json$"Comando bloqueado agora pergunta para você"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.blockedCommandAsks.detail', $json$"Quando o agente é bloqueado por uma permissão (o Codex não conseguia rodar git add porque o .git é somente leitura, por exemplo), o JayV pergunta acima da caixa de mensagem se executa o comando, nega ou sempre permite no projeto, em vez de só relatar. Executar envia o pedido de novo com essa permissão."$json$::jsonb),
  ('es', 'ask.permission.title', $json$"Permiso"$json$::jsonb),
  ('es', 'ask.permission.prompt', $json${"one":"El agente fue bloqueado y pide ejecutar este comando:","other":"El agente fue bloqueado y pide ejecutar estos comandos:"}$json$::jsonb),
  ('es', 'ask.permission.hint', $json$"Ejecutar lo permite solo para esta solicitud y la envía de nuevo. Permitir siempre también guarda el inicio del comando en este proyecto; puedes quitarlo en Permisos, junto al modo. Denegar deja la respuesta como está."$json$::jsonb),
  ('es', 'ask.permission.run', $json$"Ejecutar"$json$::jsonb),
  ('es', 'ask.permission.always', $json$"Permitir siempre"$json$::jsonb),
  ('es', 'ask.permission.deny', $json$"Denegar"$json$::jsonb),
  ('es', 'grants.label', $json$"Permisos"$json$::jsonb),
  ('es', 'grants.active', $json${"one":"{count} permiso","other":"{count} permisos"}$json$::jsonb),
  ('es', 'grants.title', $json$"Permisos del próximo mensaje"$json$::jsonb),
  ('es', 'grants.hint', $json$"Solo para el próximo mensaje que envíes en este chat, en modo desarrollo. Sin nada activado, cuando el agente se bloquea JayV pregunta encima del cuadro de mensaje si ejecutar, denegar o permitir siempre el comando."$json$::jsonb),
  ('es', 'grants.shell', $json$"Ejecutar comandos"$json$::jsonb),
  ('es', 'grants.shell.hint', $json$"Pruebas, builds y scripts sin preguntar. Codex ya ejecuta comandos dentro de su sandbox."$json$::jsonb),
  ('es', 'grants.git', $json$"Escribir en Git"$json$::jsonb),
  ('es', 'grants.git.hint', $json$"git add, commit y otros comandos que cambian .git. En Codex esto abre el sandbox completo para la solicitud."$json$::jsonb),
  ('es', 'grants.network', $json$"Usar la red"$json$::jsonb),
  ('es', 'grants.network.hint', $json$"Instalar paquetes y descargar archivos."$json$::jsonb),
  ('es', 'grants.always', $json$"Siempre permitidos en este proyecto"$json$::jsonb),
  ('es', 'grants.always.none', $json$"Ninguno todavía. Usa Permitir siempre cuando el agente pregunte."$json$::jsonb),
  ('es', 'grants.always.hint', $json$"Codex no tiene lista por comando: un comando git permitido siempre abre .git en cada solicitud de este proyecto."$json$::jsonb),
  ('es', 'grants.forget', $json$"Dejar de permitir siempre {command}"$json$::jsonb),
  ('es', 'grant.once', $json$"Permitido para esta solicitud: {commands}"$json$::jsonb),
  ('es', 'grant.always', $json$"Permitido desde ahora en este proyecto: {commands}"$json$::jsonb),
  ('es', 'beat.permissionDenied', $json$"Permiso denegado: {commands}"$json$::jsonb),
  ('es', 'source.permission', $json$"la solicitud de permiso del agente"$json$::jsonb),
  ('es', 'whatsNew.item.messagePermissions.title', $json$"Permisos del próximo mensaje"$json$::jsonb),
  ('es', 'whatsNew.item.messagePermissions.detail', $json$"Junto al modo, Permisos permite comandos, escritura en Git y red solo para el próximo mensaje que envíes. La pista de /plan, /build y /auto salió del cuadro de mensaje para dejar espacio."$json$::jsonb),
  ('es', 'whatsNew.item.blockedCommandAsks.title', $json$"Un comando bloqueado ahora te pregunta"$json$::jsonb),
  ('es', 'whatsNew.item.blockedCommandAsks.detail', $json$"Cuando el agente es bloqueado por un permiso (por ejemplo, Codex no podía ejecutar git add porque .git es de solo lectura), JayV pregunta encima del cuadro de mensaje si ejecutar el comando, denegarlo o permitirlo siempre en el proyecto, en lugar de solo informarlo. Ejecutar envía la solicitud de nuevo con ese permiso."$json$::jsonb),
  ('fr', 'ask.permission.title', $json$"Autorisation"$json$::jsonb),
  ('fr', 'ask.permission.prompt', $json${"one":"L'agent a été bloqué et demande à exécuter cette commande :","other":"L'agent a été bloqué et demande à exécuter ces commandes :"}$json$::jsonb),
  ('fr', 'ask.permission.hint', $json$"Exécuter l'autorise pour cette demande seulement et renvoie la demande. Toujours autoriser enregistre aussi le début de la commande pour ce projet ; vous pouvez le retirer dans Autorisations, à côté du mode. Refuser laisse la réponse telle quelle."$json$::jsonb),
  ('fr', 'ask.permission.run', $json$"Exécuter"$json$::jsonb),
  ('fr', 'ask.permission.always', $json$"Toujours autoriser"$json$::jsonb),
  ('fr', 'ask.permission.deny', $json$"Refuser"$json$::jsonb),
  ('fr', 'grants.label', $json$"Autorisations"$json$::jsonb),
  ('fr', 'grants.active', $json${"one":"{count} autorisation","other":"{count} autorisations"}$json$::jsonb),
  ('fr', 'grants.title', $json$"Autorisations du prochain message"$json$::jsonb),
  ('fr', 'grants.hint', $json$"Uniquement pour le prochain message envoyé dans ce chat, en mode développement. Si rien n'est activé, quand l'agent est bloqué, JayV demande au-dessus de la zone de message s'il faut exécuter, refuser ou toujours autoriser la commande."$json$::jsonb),
  ('fr', 'grants.shell', $json$"Exécuter des commandes"$json$::jsonb),
  ('fr', 'grants.shell.hint', $json$"Tests, builds et scripts sans demander. Codex exécute déjà des commandes dans son sandbox."$json$::jsonb),
  ('fr', 'grants.git', $json$"Écrire dans Git"$json$::jsonb),
  ('fr', 'grants.git.hint', $json$"git add, commit et autres commandes qui modifient .git. Avec Codex, cela ouvre tout le sandbox pour la demande."$json$::jsonb),
  ('fr', 'grants.network', $json$"Utiliser le réseau"$json$::jsonb),
  ('fr', 'grants.network.hint', $json$"Installer des paquets et télécharger des fichiers."$json$::jsonb),
  ('fr', 'grants.always', $json$"Toujours autorisées dans ce projet"$json$::jsonb),
  ('fr', 'grants.always.none', $json$"Aucune pour l'instant. Utilisez Toujours autoriser quand l'agent demande."$json$::jsonb),
  ('fr', 'grants.always.hint', $json$"Codex n'a pas de liste par commande : une commande git toujours autorisée ouvre .git à chaque demande de ce projet."$json$::jsonb),
  ('fr', 'grants.forget', $json$"Ne plus toujours autoriser {command}"$json$::jsonb),
  ('fr', 'grant.once', $json$"Autorisé pour cette demande : {commands}"$json$::jsonb),
  ('fr', 'grant.always', $json$"Autorisé désormais dans ce projet : {commands}"$json$::jsonb),
  ('fr', 'beat.permissionDenied', $json$"Autorisation refusée : {commands}"$json$::jsonb),
  ('fr', 'source.permission', $json$"la demande d'autorisation de l'agent"$json$::jsonb),
  ('fr', 'whatsNew.item.messagePermissions.title', $json$"Autorisations du prochain message"$json$::jsonb),
  ('fr', 'whatsNew.item.messagePermissions.detail', $json$"À côté du mode, Autorisations permet les commandes, l'écriture dans Git et le réseau uniquement pour le prochain message envoyé. L'aide /plan, /build et /auto a quitté la zone de message pour faire de la place."$json$::jsonb),
  ('fr', 'whatsNew.item.blockedCommandAsks.title', $json$"Une commande bloquée vous demande maintenant"$json$::jsonb),
  ('fr', 'whatsNew.item.blockedCommandAsks.detail', $json$"Quand l'agent est bloqué par une autorisation (par exemple, Codex ne pouvait pas exécuter git add car .git est en lecture seule), JayV demande au-dessus de la zone de message s'il faut exécuter la commande, la refuser ou toujours l'autoriser dans le projet, au lieu de seulement le signaler. Exécuter renvoie la demande avec cette autorisation."$json$::jsonb),
  ('de', 'ask.permission.title', $json$"Berechtigung"$json$::jsonb),
  ('de', 'ask.permission.prompt', $json${"one":"Der Agent wurde blockiert und möchte diesen Befehl ausführen:","other":"Der Agent wurde blockiert und möchte diese Befehle ausführen:"}$json$::jsonb),
  ('de', 'ask.permission.hint', $json$"Ausführen erlaubt es nur für diese Anfrage und sendet die Anfrage erneut. Immer erlauben speichert zusätzlich den Anfang des Befehls für dieses Projekt; entfernen können Sie ihn unter Berechtigungen neben dem Modus. Ablehnen lässt die Antwort, wie sie ist."$json$::jsonb),
  ('de', 'ask.permission.run', $json$"Ausführen"$json$::jsonb),
  ('de', 'ask.permission.always', $json$"Immer erlauben"$json$::jsonb),
  ('de', 'ask.permission.deny', $json$"Ablehnen"$json$::jsonb),
  ('de', 'grants.label', $json$"Berechtigungen"$json$::jsonb),
  ('de', 'grants.active', $json${"one":"{count} Berechtigung","other":"{count} Berechtigungen"}$json$::jsonb),
  ('de', 'grants.title', $json$"Berechtigungen für die nächste Nachricht"$json$::jsonb),
  ('de', 'grants.hint', $json$"Nur für die nächste Nachricht, die Sie in diesem Chat senden, im Entwicklungsmodus. Ist nichts aktiviert und der Agent wird blockiert, fragt JayV über dem Nachrichtenfeld, ob der Befehl ausgeführt, abgelehnt oder immer erlaubt werden soll."$json$::jsonb),
  ('de', 'grants.shell', $json$"Befehle ausführen"$json$::jsonb),
  ('de', 'grants.shell.hint', $json$"Tests, Builds und Skripte ohne Nachfrage. Codex führt Befehle bereits in seiner Sandbox aus."$json$::jsonb),
  ('de', 'grants.git', $json$"In Git schreiben"$json$::jsonb),
  ('de', 'grants.git.hint', $json$"git add, commit und andere Befehle, die .git ändern. Bei Codex öffnet das die ganze Sandbox für die Anfrage."$json$::jsonb),
  ('de', 'grants.network', $json$"Netzwerk nutzen"$json$::jsonb),
  ('de', 'grants.network.hint', $json$"Pakete installieren und Dateien herunterladen."$json$::jsonb),
  ('de', 'grants.always', $json$"In diesem Projekt immer erlaubt"$json$::jsonb),
  ('de', 'grants.always.none', $json$"Noch keine. Nutzen Sie Immer erlauben, wenn der Agent fragt."$json$::jsonb),
  ('de', 'grants.always.hint', $json$"Codex hat keine Liste pro Befehl: Ein immer erlaubter git-Befehl öffnet .git bei jeder Anfrage in diesem Projekt."$json$::jsonb),
  ('de', 'grants.forget', $json$"{command} nicht mehr immer erlauben"$json$::jsonb),
  ('de', 'grant.once', $json$"Für diese Anfrage erlaubt: {commands}"$json$::jsonb),
  ('de', 'grant.always', $json$"Ab jetzt in diesem Projekt erlaubt: {commands}"$json$::jsonb),
  ('de', 'beat.permissionDenied', $json$"Berechtigung abgelehnt: {commands}"$json$::jsonb),
  ('de', 'source.permission', $json$"die Berechtigungsanfrage des Agenten"$json$::jsonb),
  ('de', 'whatsNew.item.messagePermissions.title', $json$"Berechtigungen für die nächste Nachricht"$json$::jsonb),
  ('de', 'whatsNew.item.messagePermissions.detail', $json$"Neben dem Modus erlaubt Berechtigungen Befehle, Schreiben in Git und Netzwerk nur für die nächste Nachricht. Der Hinweis zu /plan, /build und /auto ist aus dem Nachrichtenfeld verschwunden, um Platz zu machen."$json$::jsonb),
  ('de', 'whatsNew.item.blockedCommandAsks.title', $json$"Ein blockierter Befehl fragt Sie jetzt"$json$::jsonb),
  ('de', 'whatsNew.item.blockedCommandAsks.detail', $json$"Wird der Agent durch eine Berechtigung blockiert (Codex konnte z. B. git add nicht ausführen, weil .git schreibgeschützt ist), fragt JayV über dem Nachrichtenfeld, ob der Befehl ausgeführt, abgelehnt oder im Projekt immer erlaubt werden soll, statt es nur zu melden. Ausführen sendet die Anfrage mit dieser Berechtigung erneut."$json$::jsonb),
  ('ru', 'ask.permission.title', $json$"Разрешение"$json$::jsonb),
  ('ru', 'ask.permission.prompt', $json${"one":"Агент заблокирован и просит выполнить команду:","other":"Агент заблокирован и просит выполнить команды:"}$json$::jsonb),
  ('ru', 'ask.permission.hint', $json$"«Выполнить» разрешает только для этого запроса и отправляет его снова. «Всегда разрешать» также сохраняет начало команды для этого проекта; убрать его можно в «Разрешениях» рядом с режимом. «Запретить» оставляет ответ как есть."$json$::jsonb),
  ('ru', 'ask.permission.run', $json$"Выполнить"$json$::jsonb),
  ('ru', 'ask.permission.always', $json$"Всегда разрешать"$json$::jsonb),
  ('ru', 'ask.permission.deny', $json$"Запретить"$json$::jsonb),
  ('ru', 'grants.label', $json$"Разрешения"$json$::jsonb),
  ('ru', 'grants.active', $json${"one":"{count} разрешение","other":"{count} разрешений"}$json$::jsonb),
  ('ru', 'grants.title', $json$"Разрешения для следующего сообщения"$json$::jsonb),
  ('ru', 'grants.hint', $json$"Только для следующего сообщения в этом чате, в режиме разработки. Если ничего не включено и агент заблокирован, JayV спрашивает над полем сообщения: выполнить, запретить или всегда разрешать команду."$json$::jsonb),
  ('ru', 'grants.shell', $json$"Выполнять команды"$json$::jsonb),
  ('ru', 'grants.shell.hint', $json$"Тесты, сборки и скрипты без вопросов. Codex и так выполняет команды в своей песочнице."$json$::jsonb),
  ('ru', 'grants.git', $json$"Запись в Git"$json$::jsonb),
  ('ru', 'grants.git.hint', $json$"git add, commit и другие команды, меняющие .git. В Codex это открывает всю песочницу для запроса."$json$::jsonb),
  ('ru', 'grants.network', $json$"Использовать сеть"$json$::jsonb),
  ('ru', 'grants.network.hint', $json$"Установка пакетов и загрузка файлов."$json$::jsonb),
  ('ru', 'grants.always', $json$"Всегда разрешено в этом проекте"$json$::jsonb),
  ('ru', 'grants.always.none', $json$"Пока ничего. Нажмите «Всегда разрешать», когда агент спросит."$json$::jsonb),
  ('ru', 'grants.always.hint', $json$"У Codex нет списка по командам: всегда разрешённая git-команда открывает .git в каждом запросе этого проекта."$json$::jsonb),
  ('ru', 'grants.forget', $json$"Больше не разрешать всегда {command}"$json$::jsonb),
  ('ru', 'grant.once', $json$"Разрешено для этого запроса: {commands}"$json$::jsonb),
  ('ru', 'grant.always', $json$"Разрешено с этого момента в проекте: {commands}"$json$::jsonb),
  ('ru', 'beat.permissionDenied', $json$"Разрешение отклонено: {commands}"$json$::jsonb),
  ('ru', 'source.permission', $json$"запрос разрешения от агента"$json$::jsonb),
  ('ru', 'whatsNew.item.messagePermissions.title', $json$"Разрешения для следующего сообщения"$json$::jsonb),
  ('ru', 'whatsNew.item.messagePermissions.detail', $json$"Рядом с режимом «Разрешения» позволяют команды, запись в Git и сеть только для следующего сообщения. Подсказка /plan, /build и /auto убрана из поля сообщения, чтобы освободить место."$json$::jsonb),
  ('ru', 'whatsNew.item.blockedCommandAsks.title', $json$"Заблокированная команда теперь спрашивает вас"$json$::jsonb),
  ('ru', 'whatsNew.item.blockedCommandAsks.detail', $json$"Когда агента блокирует разрешение (например, Codex не мог выполнить git add, потому что .git только для чтения), JayV спрашивает над полем сообщения, выполнить команду, запретить или всегда разрешать в проекте, а не просто сообщает об этом. «Выполнить» отправляет запрос снова с этим разрешением."$json$::jsonb),
  ('zh-CN', 'ask.permission.title', $json$"权限"$json$::jsonb),
  ('zh-CN', 'ask.permission.prompt', $json${"one":"代理被阻止，请求运行此命令：","other":"代理被阻止，请求运行这些命令："}$json$::jsonb),
  ('zh-CN', 'ask.permission.hint', $json$"“运行”只对本次请求允许并重新发送请求。“始终允许”还会为此项目保存命令开头；可在模式旁边的“权限”中移除。“拒绝”保留当前回答。"$json$::jsonb),
  ('zh-CN', 'ask.permission.run', $json$"运行"$json$::jsonb),
  ('zh-CN', 'ask.permission.always', $json$"始终允许"$json$::jsonb),
  ('zh-CN', 'ask.permission.deny', $json$"拒绝"$json$::jsonb),
  ('zh-CN', 'grants.label', $json$"权限"$json$::jsonb),
  ('zh-CN', 'grants.active', $json${"one":"{count} 项权限","other":"{count} 项权限"}$json$::jsonb),
  ('zh-CN', 'grants.title', $json$"下一条消息的权限"$json$::jsonb),
  ('zh-CN', 'grants.hint', $json$"仅对你在此聊天中发送的下一条消息生效，且为开发模式。若都未开启，代理被阻止时 JayV 会在消息框上方询问是运行、拒绝还是始终允许该命令。"$json$::jsonb),
  ('zh-CN', 'grants.shell', $json$"运行命令"$json$::jsonb),
  ('zh-CN', 'grants.shell.hint', $json$"无需询问即可运行测试、构建和脚本。Codex 本就在其沙盒内运行命令。"$json$::jsonb),
  ('zh-CN', 'grants.git', $json$"写入 Git"$json$::jsonb),
  ('zh-CN', 'grants.git.hint', $json$"git add、commit 等修改 .git 的命令。在 Codex 中这会为该请求开放整个沙盒。"$json$::jsonb),
  ('zh-CN', 'grants.network', $json$"使用网络"$json$::jsonb),
  ('zh-CN', 'grants.network.hint', $json$"安装软件包和下载文件。"$json$::jsonb),
  ('zh-CN', 'grants.always', $json$"此项目中始终允许"$json$::jsonb),
  ('zh-CN', 'grants.always.none', $json$"暂无。代理询问时使用“始终允许”。"$json$::jsonb),
  ('zh-CN', 'grants.always.hint', $json$"Codex 没有按命令的列表：始终允许的 git 命令会在此项目的每个请求中开放 .git。"$json$::jsonb),
  ('zh-CN', 'grants.forget', $json$"不再始终允许 {command}"$json$::jsonb),
  ('zh-CN', 'grant.once', $json$"本次请求已允许：{commands}"$json$::jsonb),
  ('zh-CN', 'grant.always', $json$"此项目从现在起已允许：{commands}"$json$::jsonb),
  ('zh-CN', 'beat.permissionDenied', $json$"权限被拒绝：{commands}"$json$::jsonb),
  ('zh-CN', 'source.permission', $json$"代理的权限请求"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.messagePermissions.title', $json$"下一条消息的权限"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.messagePermissions.detail', $json$"在模式旁边，“权限”可仅为你发送的下一条消息允许命令、Git 写入和网络。/plan、/build 和 /auto 的提示已从消息框移除以腾出空间。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.blockedCommandAsks.title', $json$"被阻止的命令现在会询问你"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.blockedCommandAsks.detail', $json$"当代理被权限阻止时（例如 Codex 因 .git 为只读而无法运行 git add），JayV 会在消息框上方询问是运行该命令、拒绝，还是在项目中始终允许，而不只是报告。“运行”会带着该权限重新发送请求。"$json$::jsonb),
  ('ja', 'ask.permission.title', $json$"許可"$json$::jsonb),
  ('ja', 'ask.permission.prompt', $json${"one":"エージェントがブロックされ、次のコマンドの実行を求めています：","other":"エージェントがブロックされ、次のコマンドの実行を求めています："}$json$::jsonb),
  ('ja', 'ask.permission.hint', $json$"「実行」はこのリクエストだけ許可してリクエストを再送します。「常に許可」はコマンドの先頭をこのプロジェクトに保存します。モードの横の「許可」から削除できます。「拒否」は回答をそのままにします。"$json$::jsonb),
  ('ja', 'ask.permission.run', $json$"実行"$json$::jsonb),
  ('ja', 'ask.permission.always', $json$"常に許可"$json$::jsonb),
  ('ja', 'ask.permission.deny', $json$"拒否"$json$::jsonb),
  ('ja', 'grants.label', $json$"許可"$json$::jsonb),
  ('ja', 'grants.active', $json${"one":"許可 {count} 件","other":"許可 {count} 件"}$json$::jsonb),
  ('ja', 'grants.title', $json$"次のメッセージの許可"$json$::jsonb),
  ('ja', 'grants.hint', $json$"このチャットで次に送るメッセージだけ、開発モードで有効です。何もオンにしていない場合、エージェントがブロックされると JayV はメッセージ欄の上で、コマンドを実行・拒否・常に許可のどれにするか尋ねます。"$json$::jsonb),
  ('ja', 'grants.shell', $json$"コマンドを実行"$json$::jsonb),
  ('ja', 'grants.shell.hint', $json$"テスト、ビルド、スクリプトを確認なしで実行します。Codex はもともとサンドボックス内でコマンドを実行します。"$json$::jsonb),
  ('ja', 'grants.git', $json$"Git に書き込む"$json$::jsonb),
  ('ja', 'grants.git.hint', $json$"git add、commit など .git を変更するコマンド。Codex ではリクエストのためにサンドボックス全体を開きます。"$json$::jsonb),
  ('ja', 'grants.network', $json$"ネットワークを使う"$json$::jsonb),
  ('ja', 'grants.network.hint', $json$"パッケージのインストールとファイルのダウンロード。"$json$::jsonb),
  ('ja', 'grants.always', $json$"このプロジェクトで常に許可"$json$::jsonb),
  ('ja', 'grants.always.none', $json$"まだありません。エージェントが尋ねたら「常に許可」を使ってください。"$json$::jsonb),
  ('ja', 'grants.always.hint', $json$"Codex にはコマンド単位のリストがありません。常に許可した git コマンドは、このプロジェクトのすべてのリクエストで .git を開きます。"$json$::jsonb),
  ('ja', 'grants.forget', $json$"{command} の常時許可をやめる"$json$::jsonb),
  ('ja', 'grant.once', $json$"このリクエストで許可：{commands}"$json$::jsonb),
  ('ja', 'grant.always', $json$"このプロジェクトで今後許可：{commands}"$json$::jsonb),
  ('ja', 'beat.permissionDenied', $json$"許可を拒否：{commands}"$json$::jsonb),
  ('ja', 'source.permission', $json$"エージェントの許可リクエスト"$json$::jsonb),
  ('ja', 'whatsNew.item.messagePermissions.title', $json$"次のメッセージの許可"$json$::jsonb),
  ('ja', 'whatsNew.item.messagePermissions.detail', $json$"モードの横の「許可」で、次に送るメッセージだけコマンド、Git への書き込み、ネットワークを許可できます。/plan、/build、/auto のヒントはスペースを空けるためにメッセージ欄から外しました。"$json$::jsonb),
  ('ja', 'whatsNew.item.blockedCommandAsks.title', $json$"ブロックされたコマンドが確認を求めるように"$json$::jsonb),
  ('ja', 'whatsNew.item.blockedCommandAsks.detail', $json$"エージェントが許可でブロックされたとき（例：.git が読み取り専用のため Codex が git add を実行できなかった場合）、JayV は報告するだけでなく、メッセージ欄の上でコマンドを実行・拒否・プロジェクトで常に許可のどれにするか尋ねます。「実行」はその許可でリクエストを再送します。"$json$::jsonb),
  ('ar', 'ask.permission.title', $json$"إذن"$json$::jsonb),
  ('ar', 'ask.permission.prompt', $json${"one":"تم حظر الوكيل ويطلب تشغيل هذا الأمر:","other":"تم حظر الوكيل ويطلب تشغيل هذه الأوامر:"}$json$::jsonb),
  ('ar', 'ask.permission.hint', $json$"«تشغيل» يسمح به لهذا الطلب فقط ويرسل الطلب من جديد. «السماح دائمًا» يحفظ أيضًا بداية الأمر لهذا المشروع، ويمكنك إزالته من «الأذونات» بجانب الوضع. «رفض» يُبقي الإجابة كما هي."$json$::jsonb),
  ('ar', 'ask.permission.run', $json$"تشغيل"$json$::jsonb),
  ('ar', 'ask.permission.always', $json$"السماح دائمًا"$json$::jsonb),
  ('ar', 'ask.permission.deny', $json$"رفض"$json$::jsonb),
  ('ar', 'grants.label', $json$"الأذونات"$json$::jsonb),
  ('ar', 'grants.active', $json${"one":"{count} إذن","other":"{count} أذونات"}$json$::jsonb),
  ('ar', 'grants.title', $json$"أذونات الرسالة التالية"$json$::jsonb),
  ('ar', 'grants.hint', $json$"للرسالة التالية فقط في هذه المحادثة، في وضع التطوير. إن لم يُفعَّل شيء وتم حظر الوكيل، يسأل JayV فوق مربع الرسالة: تشغيل الأمر أم رفضه أم السماح به دائمًا."$json$::jsonb),
  ('ar', 'grants.shell', $json$"تشغيل الأوامر"$json$::jsonb),
  ('ar', 'grants.shell.hint', $json$"الاختبارات والبناء والسكربتات دون سؤال. Codex يشغّل الأوامر داخل بيئته المعزولة أصلًا."$json$::jsonb),
  ('ar', 'grants.git', $json$"الكتابة في Git"$json$::jsonb),
  ('ar', 'grants.git.hint', $json$"git add وcommit وأوامر أخرى تغيّر .git. في Codex يفتح هذا البيئة المعزولة بالكامل للطلب."$json$::jsonb),
  ('ar', 'grants.network', $json$"استخدام الشبكة"$json$::jsonb),
  ('ar', 'grants.network.hint', $json$"تثبيت الحزم وتنزيل الملفات."$json$::jsonb),
  ('ar', 'grants.always', $json$"مسموح دائمًا في هذا المشروع"$json$::jsonb),
  ('ar', 'grants.always.none', $json$"لا شيء بعد. استخدم «السماح دائمًا» عندما يسأل الوكيل."$json$::jsonb),
  ('ar', 'grants.always.hint', $json$"لا يملك Codex قائمة لكل أمر: أمر git مسموح دائمًا يفتح .git في كل طلب في هذا المشروع."$json$::jsonb),
  ('ar', 'grants.forget', $json$"إيقاف السماح الدائم بـ {command}"$json$::jsonb),
  ('ar', 'grant.once', $json$"مسموح لهذا الطلب: {commands}"$json$::jsonb),
  ('ar', 'grant.always', $json$"مسموح من الآن في هذا المشروع: {commands}"$json$::jsonb),
  ('ar', 'beat.permissionDenied', $json$"تم رفض الإذن: {commands}"$json$::jsonb),
  ('ar', 'source.permission', $json$"طلب الإذن من الوكيل"$json$::jsonb),
  ('ar', 'whatsNew.item.messagePermissions.title', $json$"أذونات الرسالة التالية"$json$::jsonb),
  ('ar', 'whatsNew.item.messagePermissions.detail', $json$"بجانب الوضع، تتيح «الأذونات» السماح بالأوامر والكتابة في Git والشبكة للرسالة التالية فقط. أُزيلت تلميحة /plan و/build و/auto من مربع الرسالة لإفساح المجال."$json$::jsonb),
  ('ar', 'whatsNew.item.blockedCommandAsks.title', $json$"الأمر المحظور يسألك الآن"$json$::jsonb),
  ('ar', 'whatsNew.item.blockedCommandAsks.detail', $json$"عندما يُحظر الوكيل بسبب إذن (مثلًا لم يستطع Codex تشغيل git add لأن .git للقراءة فقط)، يسأل JayV فوق مربع الرسالة: تشغيل الأمر أم رفضه أم السماح به دائمًا في المشروع، بدلًا من الاكتفاء بالإبلاغ. «تشغيل» يرسل الطلب من جديد بهذا الإذن."$json$::jsonb),
  ('hi', 'ask.permission.title', $json$"अनुमति"$json$::jsonb),
  ('hi', 'ask.permission.prompt', $json${"one":"एजेंट रुका और यह कमांड चलाने की अनुमति माँग रहा है:","other":"एजेंट रुका और ये कमांड चलाने की अनुमति माँग रहा है:"}$json$::jsonb),
  ('hi', 'ask.permission.hint', $json$"चलाएँ सिर्फ़ इस अनुरोध के लिए अनुमति देता है और अनुरोध दोबारा भेजता है। हमेशा अनुमति दें इस प्रोजेक्ट के लिए कमांड की शुरुआत भी सहेजता है; इसे मोड के बगल में अनुमतियाँ में हटा सकते हैं। मना करें जवाब को वैसा ही रखता है।"$json$::jsonb),
  ('hi', 'ask.permission.run', $json$"चलाएँ"$json$::jsonb),
  ('hi', 'ask.permission.always', $json$"हमेशा अनुमति दें"$json$::jsonb),
  ('hi', 'ask.permission.deny', $json$"मना करें"$json$::jsonb),
  ('hi', 'grants.label', $json$"अनुमतियाँ"$json$::jsonb),
  ('hi', 'grants.active', $json${"one":"{count} अनुमति","other":"{count} अनुमतियाँ"}$json$::jsonb),
  ('hi', 'grants.title', $json$"अगले संदेश की अनुमतियाँ"$json$::jsonb),
  ('hi', 'grants.hint', $json$"सिर्फ़ इस चैट में भेजे जाने वाले अगले संदेश के लिए, डेवलपमेंट मोड में। कुछ भी चालू न हो और एजेंट रुके, तो JayV संदेश बॉक्स के ऊपर पूछता है कि कमांड चलाएँ, मना करें या हमेशा अनुमति दें।"$json$::jsonb),
  ('hi', 'grants.shell', $json$"कमांड चलाएँ"$json$::jsonb),
  ('hi', 'grants.shell.hint', $json$"टेस्ट, बिल्ड और स्क्रिप्ट बिना पूछे। Codex पहले से अपने सैंडबॉक्स में कमांड चलाता है।"$json$::jsonb),
  ('hi', 'grants.git', $json$"Git में लिखें"$json$::jsonb),
  ('hi', 'grants.git.hint', $json$"git add, commit और .git बदलने वाली अन्य कमांड। Codex में यह अनुरोध के लिए पूरा सैंडबॉक्स खोल देता है।"$json$::jsonb),
  ('hi', 'grants.network', $json$"नेटवर्क का उपयोग"$json$::jsonb),
  ('hi', 'grants.network.hint', $json$"पैकेज इंस्टॉल करना और फ़ाइलें डाउनलोड करना।"$json$::jsonb),
  ('hi', 'grants.always', $json$"इस प्रोजेक्ट में हमेशा अनुमत"$json$::jsonb),
  ('hi', 'grants.always.none', $json$"अभी कोई नहीं। एजेंट पूछे तो हमेशा अनुमति दें चुनें।"$json$::jsonb),
  ('hi', 'grants.always.hint', $json$"Codex में प्रति-कमांड सूची नहीं है: हमेशा अनुमत git कमांड इस प्रोजेक्ट के हर अनुरोध में .git खोल देती है।"$json$::jsonb),
  ('hi', 'grants.forget', $json$"{command} को हमेशा अनुमति देना बंद करें"$json$::jsonb),
  ('hi', 'grant.once', $json$"इस अनुरोध के लिए अनुमत: {commands}"$json$::jsonb),
  ('hi', 'grant.always', $json$"अब से इस प्रोजेक्ट में अनुमत: {commands}"$json$::jsonb),
  ('hi', 'beat.permissionDenied', $json$"अनुमति अस्वीकृत: {commands}"$json$::jsonb),
  ('hi', 'source.permission', $json$"एजेंट का अनुमति अनुरोध"$json$::jsonb),
  ('hi', 'whatsNew.item.messagePermissions.title', $json$"अगले संदेश की अनुमतियाँ"$json$::jsonb),
  ('hi', 'whatsNew.item.messagePermissions.detail', $json$"मोड के बगल में अनुमतियाँ सिर्फ़ अगले संदेश के लिए कमांड, Git में लिखना और नेटवर्क की अनुमति देती हैं। जगह बनाने के लिए /plan, /build और /auto का संकेत संदेश बॉक्स से हटा दिया गया।"$json$::jsonb),
  ('hi', 'whatsNew.item.blockedCommandAsks.title', $json$"रुकी हुई कमांड अब आपसे पूछती है"$json$::jsonb),
  ('hi', 'whatsNew.item.blockedCommandAsks.detail', $json$"जब एजेंट किसी अनुमति के कारण रुकता है (जैसे .git सिर्फ़ पढ़ने योग्य होने से Codex git add नहीं चला पाया), तो JayV सिर्फ़ बताने के बजाय संदेश बॉक्स के ऊपर पूछता है कि कमांड चलाएँ, मना करें या प्रोजेक्ट में हमेशा अनुमति दें। चलाएँ उसी अनुमति के साथ अनुरोध दोबारा भेजता है।"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
