-- v0.54.0: as perguntas do agente em etapas — uma por vez, com voltar e
-- avançar, e todas as respostas enviadas juntas na última —, o painel de
-- perguntas que se recolhe numa linha, e o acesso à rede do Codex que volta a
-- ligar com o sandbox "Somente leitura" e vale no modo Desenvolvimento.
-- Só textos.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'ask.form.step', $json$"{current} de {total}"$json$::jsonb),
  ('pt-BR', 'ask.form.previous', $json$"Voltar"$json$::jsonb),
  ('pt-BR', 'ask.form.next', $json$"Avançar"$json$::jsonb),
  ('pt-BR', 'ask.title', $json$"Pergunta"$json$::jsonb),
  ('pt-BR', 'ask.collapse', $json$"Recolher a pergunta"$json$::jsonb),
  ('pt-BR', 'ask.expand', $json$"Abrir a pergunta"$json$::jsonb),
  ('pt-BR', 'chat.answers', $json${"one":"Resposta a {count} pergunta","other":"Respostas a {count} perguntas"}$json$::jsonb),
  ('pt-BR', 'codex.network.hint', $json$"Deixa o Codex baixar pacotes e acessar a internet enquanto escreve no projeto, inclusive no modo Desenvolvimento. O modo Planejamento nunca tem rede."$json$::jsonb),
  ('pt-BR', 'codex.network.open', $json$"O acesso total já inclui a rede."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.questionSteps.title', $json$"Várias perguntas do agente, uma etapa por vez"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.questionSteps.detail', $json$"Quando o agente faz mais de uma pergunta, elas aparecem uma por etapa, com Voltar e Avançar e uma marca de onde você está (2 de 4). Tudo o que você respondeu vai junto na última etapa."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.questionFold.title', $json$"Recolha as perguntas do agente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.questionFold.detail', $json$"O painel de perguntas acima da caixa de mensagem se recolhe numa linha para você ler o chat, e abre de novo com um clique. As respostas a várias perguntas também aparecem recolhidas no chat."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.codexNetwork.title', $json$"O acesso à rede do Codex volta a ligar"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.codexNetwork.detail', $json$"Em Configurações › Agentes › Codex, a chave Acesso à rede ficava travada com o sandbox padrão \"Somente leitura\", e o modo Desenvolvimento a descartava mesmo ligada. Agora ela funciona com \"Somente leitura\" e \"Escrever no projeto\" e vale sempre que o Codex escreve; com Acesso total ela aparece ligada, porque não há sandbox."$json$::jsonb),
  ('en', 'ask.form.step', $json$"{current} of {total}"$json$::jsonb),
  ('en', 'ask.form.previous', $json$"Previous"$json$::jsonb),
  ('en', 'ask.form.next', $json$"Next"$json$::jsonb),
  ('en', 'ask.title', $json$"Question"$json$::jsonb),
  ('en', 'ask.collapse', $json$"Collapse the question"$json$::jsonb),
  ('en', 'ask.expand', $json$"Expand the question"$json$::jsonb),
  ('en', 'chat.answers', $json${"one":"Answer to {count} question","other":"Answers to {count} questions"}$json$::jsonb),
  ('en', 'codex.network.hint', $json$"Lets Codex download packages and reach the internet while it writes to the project, including in Development mode. Planning mode never has network access."$json$::jsonb),
  ('en', 'codex.network.open', $json$"Full access already includes the network."$json$::jsonb),
  ('en', 'whatsNew.item.questionSteps.title', $json$"Several questions from the agent, one step at a time"$json$::jsonb),
  ('en', 'whatsNew.item.questionSteps.detail', $json$"When the agent asks more than one question, they now come one per step, with Previous and Next and a marker showing where you are (2 of 4). Everything you answered goes together on the last step."$json$::jsonb),
  ('en', 'whatsNew.item.questionFold.title', $json$"Collapse the agent's questions"$json$::jsonb),
  ('en', 'whatsNew.item.questionFold.detail', $json$"The question panel above the message box folds into one line so you can read the chat, and opens again with a click. Answers to several questions also show folded in the chat."$json$::jsonb),
  ('en', 'whatsNew.item.codexNetwork.title', $json$"Codex network access can be turned on again"$json$::jsonb),
  ('en', 'whatsNew.item.codexNetwork.detail', $json$"In Settings › Agents › Codex the Network access switch stayed locked with the default \"Read only\" sandbox, and Development mode dropped it even when it was on. It now works with \"Read only\" and \"Write to the project\" and applies whenever Codex writes; with Full access it shows on, because there is no sandbox."$json$::jsonb),
  ('es', 'ask.form.step', $json$"{current} de {total}"$json$::jsonb),
  ('es', 'ask.form.previous', $json$"Anterior"$json$::jsonb),
  ('es', 'ask.form.next', $json$"Siguiente"$json$::jsonb),
  ('es', 'ask.title', $json$"Pregunta"$json$::jsonb),
  ('es', 'ask.collapse', $json$"Contraer la pregunta"$json$::jsonb),
  ('es', 'ask.expand', $json$"Abrir la pregunta"$json$::jsonb),
  ('es', 'chat.answers', $json${"one":"Respuesta a {count} pregunta","other":"Respuestas a {count} preguntas"}$json$::jsonb),
  ('es', 'codex.network.hint', $json$"Permite a Codex descargar paquetes y acceder a internet mientras escribe en el proyecto, también en el modo Desarrollo. El modo Planificación nunca tiene red."$json$::jsonb),
  ('es', 'codex.network.open', $json$"El acceso total ya incluye la red."$json$::jsonb),
  ('es', 'whatsNew.item.questionSteps.title', $json$"Varias preguntas del agente, un paso a la vez"$json$::jsonb),
  ('es', 'whatsNew.item.questionSteps.detail', $json$"Cuando el agente hace más de una pregunta, ahora aparecen una por paso, con Anterior y Siguiente y una marca de dónde estás (2 de 4). Todo lo que respondiste se envía junto en el último paso."$json$::jsonb),
  ('es', 'whatsNew.item.questionFold.title', $json$"Contrae las preguntas del agente"$json$::jsonb),
  ('es', 'whatsNew.item.questionFold.detail', $json$"El panel de preguntas sobre el cuadro de mensaje se contrae en una línea para que leas el chat, y se abre de nuevo con un clic. Las respuestas a varias preguntas también aparecen contraídas en el chat."$json$::jsonb),
  ('es', 'whatsNew.item.codexNetwork.title', $json$"El acceso a la red de Codex vuelve a activarse"$json$::jsonb),
  ('es', 'whatsNew.item.codexNetwork.detail', $json$"En Configuración › Agentes › Codex, el interruptor Acceso a la red quedaba bloqueado con el sandbox predeterminado \"Solo lectura\", y el modo Desarrollo lo descartaba aunque estuviera activado. Ahora funciona con \"Solo lectura\" y \"Escribir en el proyecto\" y vale siempre que Codex escribe; con Acceso total aparece activado, porque no hay sandbox."$json$::jsonb),
  ('zh-CN', 'ask.form.step', $json$"第 {current} / {total} 题"$json$::jsonb),
  ('zh-CN', 'ask.form.previous', $json$"上一步"$json$::jsonb),
  ('zh-CN', 'ask.form.next', $json$"下一步"$json$::jsonb),
  ('zh-CN', 'ask.title', $json$"问题"$json$::jsonb),
  ('zh-CN', 'ask.collapse', $json$"收起问题"$json$::jsonb),
  ('zh-CN', 'ask.expand', $json$"展开问题"$json$::jsonb),
  ('zh-CN', 'chat.answers', $json${"other":"对 {count} 个问题的回答"}$json$::jsonb),
  ('zh-CN', 'codex.network.hint', $json$"允许 Codex 在写入项目时下载软件包和访问互联网，包括开发模式。规划模式永远没有网络。"$json$::jsonb),
  ('zh-CN', 'codex.network.open', $json$"完全访问已包含网络。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.questionSteps.title', $json$"代理的多个问题，一步一个"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.questionSteps.detail', $json$"当代理提出多个问题时，现在每步显示一个，带有上一步和下一步，以及当前位置标记（第 2 / 4 题）。你的所有回答在最后一步一起发送。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.questionFold.title', $json$"收起代理的问题"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.questionFold.detail', $json$"消息框上方的问题面板可以收起成一行，方便阅读聊天，点击即可重新展开。对多个问题的回答在聊天中也默认收起。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.codexNetwork.title', $json$"Codex 的网络访问可以重新开启"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.codexNetwork.detail', $json$"在 设置 › 代理 › Codex 中，默认沙盒为“只读”时网络访问开关被锁定，而开发模式即使开启也会丢弃它。现在它在“只读”和“写入项目”下都可用，并在 Codex 写入时生效；在完全访问下显示为开启，因为没有沙盒。"$json$::jsonb),
  ('hi', 'ask.form.step', $json$"{total} में से {current}"$json$::jsonb),
  ('hi', 'ask.form.previous', $json$"पिछला"$json$::jsonb),
  ('hi', 'ask.form.next', $json$"अगला"$json$::jsonb),
  ('hi', 'ask.title', $json$"सवाल"$json$::jsonb),
  ('hi', 'ask.collapse', $json$"सवाल समेटें"$json$::jsonb),
  ('hi', 'ask.expand', $json$"सवाल खोलें"$json$::jsonb),
  ('hi', 'chat.answers', $json${"one":"{count} सवाल का जवाब","other":"{count} सवालों के जवाब"}$json$::jsonb),
  ('hi', 'codex.network.hint', $json$"प्रोजेक्ट में लिखते समय Codex को पैकेज डाउनलोड करने और इंटरनेट तक पहुँचने देता है, डेवलपमेंट मोड में भी। योजना मोड में कभी नेटवर्क नहीं होता।"$json$::jsonb),
  ('hi', 'codex.network.open', $json$"पूरी पहुँच में नेटवर्क पहले से शामिल है।"$json$::jsonb),
  ('hi', 'whatsNew.item.questionSteps.title', $json$"एजेंट के कई सवाल, एक बार में एक कदम"$json$::jsonb),
  ('hi', 'whatsNew.item.questionSteps.detail', $json$"जब एजेंट एक से ज़्यादा सवाल पूछता है, तो अब वे एक-एक कदम में आते हैं, पिछला और अगला बटन और आप कहाँ हैं इसका निशान (4 में से 2) के साथ। आपके सभी जवाब आख़िरी कदम पर एक साथ जाते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.questionFold.title', $json$"एजेंट के सवाल समेटें"$json$::jsonb),
  ('hi', 'whatsNew.item.questionFold.detail', $json$"संदेश बॉक्स के ऊपर का सवालों वाला पैनल एक लाइन में सिमट जाता है ताकि आप चैट पढ़ सकें, और एक क्लिक से फिर खुलता है। कई सवालों के जवाब भी चैट में सिमटे हुए दिखते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.codexNetwork.title', $json$"Codex की नेटवर्क पहुँच फिर से चालू हो सकती है"$json$::jsonb),
  ('hi', 'whatsNew.item.codexNetwork.detail', $json$"सेटिंग्स › एजेंट › Codex में डिफ़ॉल्ट \"सिर्फ़ पढ़ना\" सैंडबॉक्स के साथ नेटवर्क पहुँच स्विच बंद रहता था, और डेवलपमेंट मोड उसे चालू होने पर भी हटा देता था। अब यह \"सिर्फ़ पढ़ना\" और \"प्रोजेक्ट में लिखना\" दोनों के साथ काम करता है और जब भी Codex लिखता है लागू होता है; पूरी पहुँच में यह चालू दिखता है, क्योंकि कोई सैंडबॉक्स नहीं है।"$json$::jsonb),
  ('ar', 'ask.form.step', $json$"{current} من {total}"$json$::jsonb),
  ('ar', 'ask.form.previous', $json$"السابق"$json$::jsonb),
  ('ar', 'ask.form.next', $json$"التالي"$json$::jsonb),
  ('ar', 'ask.title', $json$"سؤال"$json$::jsonb),
  ('ar', 'ask.collapse', $json$"طي السؤال"$json$::jsonb),
  ('ar', 'ask.expand', $json$"فتح السؤال"$json$::jsonb),
  ('ar', 'chat.answers', $json${"zero":"إجابات عن {count} سؤال","one":"إجابة عن سؤال واحد","two":"إجابتان عن سؤالين","few":"إجابات عن {count} أسئلة","many":"إجابات عن {count} سؤالًا","other":"إجابات عن {count} سؤال"}$json$::jsonb),
  ('ar', 'codex.network.hint', $json$"يسمح لـ Codex بتنزيل الحزم والوصول إلى الإنترنت أثناء الكتابة في المشروع، بما في ذلك وضع التطوير. وضع التخطيط لا يملك الشبكة أبدًا."$json$::jsonb),
  ('ar', 'codex.network.open', $json$"الوصول الكامل يشمل الشبكة بالفعل."$json$::jsonb),
  ('ar', 'whatsNew.item.questionSteps.title', $json$"عدة أسئلة من الوكيل، خطوة في كل مرة"$json$::jsonb),
  ('ar', 'whatsNew.item.questionSteps.detail', $json$"عندما يطرح الوكيل أكثر من سؤال، تظهر الآن سؤالًا في كل خطوة، مع السابق والتالي وعلامة تبين مكانك (2 من 4). كل ما أجبت عنه يُرسل معًا في الخطوة الأخيرة."$json$::jsonb),
  ('ar', 'whatsNew.item.questionFold.title', $json$"اطوِ أسئلة الوكيل"$json$::jsonb),
  ('ar', 'whatsNew.item.questionFold.detail', $json$"لوحة الأسئلة فوق مربع الرسالة تُطوى في سطر واحد لتقرأ المحادثة، وتُفتح مجددًا بنقرة. الإجابات عن عدة أسئلة تظهر أيضًا مطوية في المحادثة."$json$::jsonb),
  ('ar', 'whatsNew.item.codexNetwork.title', $json$"يمكن تشغيل وصول Codex إلى الشبكة مجددًا"$json$::jsonb),
  ('ar', 'whatsNew.item.codexNetwork.detail', $json$"في الإعدادات › الوكلاء › Codex كان مفتاح الوصول إلى الشبكة مقفلًا مع صندوق العزل الافتراضي \"قراءة فقط\"، وكان وضع التطوير يتجاهله حتى عند تشغيله. الآن يعمل مع \"قراءة فقط\" و\"الكتابة في المشروع\" ويسري كلما كتب Codex؛ ومع الوصول الكامل يظهر مفعّلًا لعدم وجود صندوق عزل."$json$::jsonb),
  ('fr', 'ask.form.step', $json$"{current} sur {total}"$json$::jsonb),
  ('fr', 'ask.form.previous', $json$"Précédent"$json$::jsonb),
  ('fr', 'ask.form.next', $json$"Suivant"$json$::jsonb),
  ('fr', 'ask.title', $json$"Question"$json$::jsonb),
  ('fr', 'ask.collapse', $json$"Replier la question"$json$::jsonb),
  ('fr', 'ask.expand', $json$"Déplier la question"$json$::jsonb),
  ('fr', 'chat.answers', $json${"one":"Réponse à {count} question","other":"Réponses à {count} questions"}$json$::jsonb),
  ('fr', 'codex.network.hint', $json$"Permet à Codex de télécharger des paquets et d'accéder à internet quand il écrit dans le projet, y compris en mode Développement. Le mode Planification n'a jamais le réseau."$json$::jsonb),
  ('fr', 'codex.network.open', $json$"L'accès complet inclut déjà le réseau."$json$::jsonb),
  ('fr', 'whatsNew.item.questionSteps.title', $json$"Plusieurs questions de l'agent, une étape à la fois"$json$::jsonb),
  ('fr', 'whatsNew.item.questionSteps.detail', $json$"Quand l'agent pose plus d'une question, elles arrivent désormais une par étape, avec Précédent et Suivant et un repère de votre position (2 sur 4). Toutes vos réponses partent ensemble à la dernière étape."$json$::jsonb),
  ('fr', 'whatsNew.item.questionFold.title', $json$"Repliez les questions de l'agent"$json$::jsonb),
  ('fr', 'whatsNew.item.questionFold.detail', $json$"Le panneau de questions au-dessus de la zone de message se replie sur une ligne pour lire la conversation, et se rouvre d'un clic. Les réponses à plusieurs questions apparaissent aussi repliées dans la conversation."$json$::jsonb),
  ('fr', 'whatsNew.item.codexNetwork.title', $json$"L'accès réseau de Codex s'active de nouveau"$json$::jsonb),
  ('fr', 'whatsNew.item.codexNetwork.detail', $json$"Dans Paramètres › Agents › Codex, l'interrupteur Accès réseau restait bloqué avec le sandbox par défaut « Lecture seule », et le mode Développement l'ignorait même activé. Il fonctionne maintenant avec « Lecture seule » et « Écrire dans le projet » et s'applique dès que Codex écrit ; avec l'accès complet il apparaît activé, car il n'y a pas de sandbox."$json$::jsonb),
  ('ru', 'ask.form.step', $json$"{current} из {total}"$json$::jsonb),
  ('ru', 'ask.form.previous', $json$"Назад"$json$::jsonb),
  ('ru', 'ask.form.next', $json$"Далее"$json$::jsonb),
  ('ru', 'ask.title', $json$"Вопрос"$json$::jsonb),
  ('ru', 'ask.collapse', $json$"Свернуть вопрос"$json$::jsonb),
  ('ru', 'ask.expand', $json$"Развернуть вопрос"$json$::jsonb),
  ('ru', 'chat.answers', $json${"one":"Ответ на {count} вопрос","few":"Ответы на {count} вопроса","many":"Ответы на {count} вопросов","other":"Ответы на {count} вопроса"}$json$::jsonb),
  ('ru', 'codex.network.hint', $json$"Позволяет Codex загружать пакеты и выходить в интернет, когда он пишет в проект, в том числе в режиме Разработка. В режиме Планирование сети нет никогда."$json$::jsonb),
  ('ru', 'codex.network.open', $json$"Полный доступ уже включает сеть."$json$::jsonb),
  ('ru', 'whatsNew.item.questionSteps.title', $json$"Несколько вопросов агента — по одному шагу"$json$::jsonb),
  ('ru', 'whatsNew.item.questionSteps.detail', $json$"Когда агент задаёт больше одного вопроса, они теперь идут по одному на шаг, с кнопками Назад и Далее и отметкой, где вы находитесь (2 из 4). Все ваши ответы отправляются вместе на последнем шаге."$json$::jsonb),
  ('ru', 'whatsNew.item.questionFold.title', $json$"Сворачивайте вопросы агента"$json$::jsonb),
  ('ru', 'whatsNew.item.questionFold.detail', $json$"Панель вопросов над полем сообщения сворачивается в одну строку, чтобы читать чат, и снова открывается одним щелчком. Ответы на несколько вопросов тоже показываются в чате свёрнутыми."$json$::jsonb),
  ('ru', 'whatsNew.item.codexNetwork.title', $json$"Доступ Codex к сети снова включается"$json$::jsonb),
  ('ru', 'whatsNew.item.codexNetwork.detail', $json$"В Настройки › Агенты › Codex переключатель «Доступ к сети» был заблокирован при песочнице по умолчанию «Только чтение», а режим Разработка отбрасывал его, даже когда он был включён. Теперь он работает с «Только чтение» и «Запись в проект» и действует всякий раз, когда Codex пишет; при полном доступе он показан включённым, потому что песочницы нет."$json$::jsonb),
  ('ja', 'ask.form.step', $json$"{current} / {total}"$json$::jsonb),
  ('ja', 'ask.form.previous', $json$"前へ"$json$::jsonb),
  ('ja', 'ask.form.next', $json$"次へ"$json$::jsonb),
  ('ja', 'ask.title', $json$"質問"$json$::jsonb),
  ('ja', 'ask.collapse', $json$"質問を折りたたむ"$json$::jsonb),
  ('ja', 'ask.expand', $json$"質問を開く"$json$::jsonb),
  ('ja', 'chat.answers', $json${"other":"{count} 件の質問への回答"}$json$::jsonb),
  ('ja', 'codex.network.hint', $json$"Codex がプロジェクトに書き込む間、パッケージのダウンロードやインターネット接続を許可します（開発モードを含む）。計画モードでは常にネットワークなしです。"$json$::jsonb),
  ('ja', 'codex.network.open', $json$"フルアクセスにはすでにネットワークが含まれます。"$json$::jsonb),
  ('ja', 'whatsNew.item.questionSteps.title', $json$"エージェントからの複数の質問を1ステップずつ"$json$::jsonb),
  ('ja', 'whatsNew.item.questionSteps.detail', $json$"エージェントが複数の質問をすると、1ステップに1問ずつ表示されるようになりました。前へ・次へボタンと現在位置の表示（2 / 4）があります。回答はすべて最後のステップでまとめて送信されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.questionFold.title', $json$"エージェントの質問を折りたたむ"$json$::jsonb),
  ('ja', 'whatsNew.item.questionFold.detail', $json$"メッセージ欄の上の質問パネルを1行に折りたたんでチャットを読めるようになり、クリックで再び開けます。複数の質問への回答もチャットでは折りたたんで表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.codexNetwork.title', $json$"Codex のネットワークアクセスを再びオンにできます"$json$::jsonb),
  ('ja', 'whatsNew.item.codexNetwork.detail', $json$"設定 › エージェント › Codex で、既定のサンドボックス「読み取り専用」ではネットワークアクセスのスイッチがロックされ、開発モードではオンにしても無視されていました。現在は「読み取り専用」と「プロジェクトに書き込み」の両方で使え、Codex が書き込むときに有効になります。フルアクセスではサンドボックスがないため、オンとして表示されます。"$json$::jsonb),
  ('de', 'ask.form.step', $json$"{current} von {total}"$json$::jsonb),
  ('de', 'ask.form.previous', $json$"Zurück"$json$::jsonb),
  ('de', 'ask.form.next', $json$"Weiter"$json$::jsonb),
  ('de', 'ask.title', $json$"Frage"$json$::jsonb),
  ('de', 'ask.collapse', $json$"Frage einklappen"$json$::jsonb),
  ('de', 'ask.expand', $json$"Frage aufklappen"$json$::jsonb),
  ('de', 'chat.answers', $json${"one":"Antwort auf {count} Frage","other":"Antworten auf {count} Fragen"}$json$::jsonb),
  ('de', 'codex.network.hint', $json$"Lässt Codex Pakete herunterladen und ins Internet, während es im Projekt schreibt, auch im Modus Entwicklung. Der Modus Planung hat nie Netzwerk."$json$::jsonb),
  ('de', 'codex.network.open', $json$"Vollzugriff schließt das Netzwerk bereits ein."$json$::jsonb),
  ('de', 'whatsNew.item.questionSteps.title', $json$"Mehrere Fragen des Agenten, Schritt für Schritt"$json$::jsonb),
  ('de', 'whatsNew.item.questionSteps.detail', $json$"Stellt der Agent mehr als eine Frage, erscheinen sie jetzt eine pro Schritt, mit Zurück und Weiter und einer Markierung, wo du bist (2 von 4). Alle Antworten gehen im letzten Schritt gemeinsam raus."$json$::jsonb),
  ('de', 'whatsNew.item.questionFold.title', $json$"Fragen des Agenten einklappen"$json$::jsonb),
  ('de', 'whatsNew.item.questionFold.detail', $json$"Das Fragenfeld über dem Nachrichtenfeld lässt sich auf eine Zeile einklappen, damit du den Chat lesen kannst, und öffnet sich mit einem Klick wieder. Antworten auf mehrere Fragen erscheinen im Chat ebenfalls eingeklappt."$json$::jsonb),
  ('de', 'whatsNew.item.codexNetwork.title', $json$"Der Netzwerkzugriff von Codex lässt sich wieder einschalten"$json$::jsonb),
  ('de', 'whatsNew.item.codexNetwork.detail', $json$"Unter Einstellungen › Agenten › Codex war der Schalter Netzwerkzugriff mit der Standard-Sandbox „Nur lesen“ gesperrt, und der Modus Entwicklung verwarf ihn selbst eingeschaltet. Jetzt funktioniert er mit „Nur lesen“ und „Im Projekt schreiben“ und gilt immer, wenn Codex schreibt; mit Vollzugriff erscheint er eingeschaltet, weil es keine Sandbox gibt."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
