-- O nível do desenvolvedor (starter, junior, mid, senior, architect), guardado
-- na conta. `account_settings` é chave e valor por usuário, espelha o SQLite
-- (`src-tauri/src/expertise.rs`) e sobe pela mesma fila de sync.

create table public.account_settings (
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  key text not null,
  value text not null,
  updated_at text not null,
  row_updated_at timestamptz not null default now(),
  row_deleted_at timestamptz,
  synced_at timestamptz not null default clock_timestamp(),
  primary key (user_id, key)
);
create index account_settings_user_synced on public.account_settings (user_id, synced_at);
create trigger sync_row before insert or update on public.account_settings for each row execute function public.sync_row();
alter table public.account_settings enable row level security;
create policy "dono lê" on public.account_settings for select to authenticated using (user_id = (select auth.uid()));
create policy "dono escreve" on public.account_settings for insert to authenticated with check (user_id = (select auth.uid()));
create policy "dono muda" on public.account_settings for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
revoke delete, truncate on public.account_settings from anon, authenticated;
revoke all on public.account_settings from anon;

-- O seletor de nível, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'expertise.title', $json$"Seu nível"$json$::jsonb),
  ('pt-BR', 'expertise.description', $json$"Fica na sua conta. Muda o quanto a portaria pergunta antes de liberar um pedido e até onde o Jev deixa o agente construir sozinho. Nunca muda o que é barrado."$json$::jsonb),
  ('pt-BR', 'expertise.starter', $json$"Starter"$json$::jsonb),
  ('pt-BR', 'expertise.starter.hint', $json$"Mais perguntas de esclarecimento e mais planos: build só em mudanças simples."$json$::jsonb),
  ('pt-BR', 'expertise.junior', $json$"Júnior"$json$::jsonb),
  ('pt-BR', 'expertise.junior.hint', $json$"Pergunta um pouco mais que o padrão; build só em mudanças simples."$json$::jsonb),
  ('pt-BR', 'expertise.mid', $json$"Pleno"$json$::jsonb),
  ('pt-BR', 'expertise.mid.hint', $json$"Os critérios padrão: build até mudanças médias."$json$::jsonb),
  ('pt-BR', 'expertise.senior', $json$"Sênior"$json$::jsonb),
  ('pt-BR', 'expertise.senior.hint', $json$"Confia em pedidos mais curtos; build até mudanças médias, mesmo quando reescrevem código."$json$::jsonb),
  ('pt-BR', 'expertise.architect', $json$"Arquiteto"$json$::jsonb),
  ('pt-BR', 'expertise.architect.hint', $json$"Confia em pedidos enxutos; build até em trabalho do tamanho do sistema."$json$::jsonb),
  ('pt-BR', 'expertise.numbers', $json$"clareza {demand} · confiança do roteamento {confidence} · build até {build} · plano se puder apagar trabalho ≥ {destructive}"$json$::jsonb),
  ('pt-BR', 'expertise.saved', $json$"Nível trocado para {level}. Vale a partir do próximo pedido."$json$::jsonb),
  ('pt-BR', 'expertise.invalid', $json$"Nível desconhecido: {value}"$json$::jsonb),
  ('en', 'expertise.title', $json$"Your level"$json$::jsonb),
  ('en', 'expertise.description', $json$"Tied to your account. It changes how much the gatehouse asks before letting a request through and how far Jev lets the agent build on its own. It never changes what gets blocked."$json$::jsonb),
  ('en', 'expertise.starter', $json$"Starter"$json$::jsonb),
  ('en', 'expertise.starter.hint', $json$"More clarifying questions and more plans: build only for simple changes."$json$::jsonb),
  ('en', 'expertise.junior', $json$"Junior"$json$::jsonb),
  ('en', 'expertise.junior.hint', $json$"Asks a bit more than usual; build only for simple changes."$json$::jsonb),
  ('en', 'expertise.mid', $json$"Mid-level"$json$::jsonb),
  ('en', 'expertise.mid.hint', $json$"The standard criteria: build up to medium changes."$json$::jsonb),
  ('en', 'expertise.senior', $json$"Senior"$json$::jsonb),
  ('en', 'expertise.senior.hint', $json$"Trusts shorter requests; build up to medium changes, even when they rewrite code."$json$::jsonb),
  ('en', 'expertise.architect', $json$"Architect"$json$::jsonb),
  ('en', 'expertise.architect.hint', $json$"Trusts terse requests; build even for system-wide work."$json$::jsonb),
  ('en', 'expertise.numbers', $json$"clarity {demand} · routing confidence {confidence} · build up to {build} · plan if it may erase work ≥ {destructive}"$json$::jsonb),
  ('en', 'expertise.saved', $json$"Level changed to {level}. It applies from the next request."$json$::jsonb),
  ('en', 'expertise.invalid', $json$"Unknown level: {value}"$json$::jsonb),
  ('es', 'expertise.title', $json$"Tu nivel"$json$::jsonb),
  ('es', 'expertise.description', $json$"Queda en tu cuenta. Cambia cuánto pregunta la portería antes de dejar pasar una solicitud y hasta dónde Jev deja que el agente construya solo. Nunca cambia lo que se bloquea."$json$::jsonb),
  ('es', 'expertise.starter', $json$"Starter"$json$::jsonb),
  ('es', 'expertise.starter.hint', $json$"Más preguntas de aclaración y más planes: build solo en cambios simples."$json$::jsonb),
  ('es', 'expertise.junior', $json$"Junior"$json$::jsonb),
  ('es', 'expertise.junior.hint', $json$"Pregunta un poco más de lo habitual; build solo en cambios simples."$json$::jsonb),
  ('es', 'expertise.mid', $json$"Semi senior"$json$::jsonb),
  ('es', 'expertise.mid.hint', $json$"Los criterios estándar: build hasta cambios medianos."$json$::jsonb),
  ('es', 'expertise.senior', $json$"Senior"$json$::jsonb),
  ('es', 'expertise.senior.hint', $json$"Confía en solicitudes más cortas; build hasta cambios medianos, incluso si reescriben código."$json$::jsonb),
  ('es', 'expertise.architect', $json$"Arquitecto"$json$::jsonb),
  ('es', 'expertise.architect.hint', $json$"Confía en solicitudes concisas; build incluso en trabajo a nivel de sistema."$json$::jsonb),
  ('es', 'expertise.numbers', $json$"claridad {demand} · confianza del enrutamiento {confidence} · build hasta {build} · plan si puede borrar trabajo ≥ {destructive}"$json$::jsonb),
  ('es', 'expertise.saved', $json$"Nivel cambiado a {level}. Vale a partir de la próxima solicitud."$json$::jsonb),
  ('es', 'expertise.invalid', $json$"Nivel desconocido: {value}"$json$::jsonb),
  ('zh-CN', 'expertise.title', $json$"你的级别"$json$::jsonb),
  ('zh-CN', 'expertise.description', $json$"与你的账户绑定。它改变门卫在放行请求前提问的多少，以及 Jev 允许代理自行构建的范围。它从不改变被拦截的内容。"$json$::jsonb),
  ('zh-CN', 'expertise.starter', $json$"入门"$json$::jsonb),
  ('zh-CN', 'expertise.starter.hint', $json$"更多澄清问题、更多计划：只有简单改动才会构建。"$json$::jsonb),
  ('zh-CN', 'expertise.junior', $json$"初级"$json$::jsonb),
  ('zh-CN', 'expertise.junior.hint', $json$"比默认多问一些；只有简单改动才会构建。"$json$::jsonb),
  ('zh-CN', 'expertise.mid', $json$"中级"$json$::jsonb),
  ('zh-CN', 'expertise.mid.hint', $json$"标准规则：中等改动及以下会构建。"$json$::jsonb),
  ('zh-CN', 'expertise.senior', $json$"高级"$json$::jsonb),
  ('zh-CN', 'expertise.senior.hint', $json$"信任更简短的请求；中等改动及以下会构建，即使会重写代码。"$json$::jsonb),
  ('zh-CN', 'expertise.architect', $json$"架构师"$json$::jsonb),
  ('zh-CN', 'expertise.architect.hint', $json$"信任简洁的请求；即使是系统级的工作也会构建。"$json$::jsonb),
  ('zh-CN', 'expertise.numbers', $json$"清晰度 {demand} · 路由置信度 {confidence} · 构建上限 {build} · 可能抹掉工作 ≥ {destructive} 时改为计划"$json$::jsonb),
  ('zh-CN', 'expertise.saved', $json$"级别已改为 {level}，从下一个请求开始生效。"$json$::jsonb),
  ('zh-CN', 'expertise.invalid', $json$"未知级别：{value}"$json$::jsonb),
  ('hi', 'expertise.title', $json$"आपका स्तर"$json$::jsonb),
  ('hi', 'expertise.description', $json$"यह आपके खाते से जुड़ा है। यह बदलता है कि गेटहाउस अनुरोध आगे भेजने से पहले कितना पूछता है और Jev एजेंट को अपने आप कितना बनाने देता है। जो रोका जाता है, उसे यह कभी नहीं बदलता।"$json$::jsonb),
  ('hi', 'expertise.starter', $json$"स्टार्टर"$json$::jsonb),
  ('hi', 'expertise.starter.hint', $json$"अधिक स्पष्टीकरण वाले प्रश्न और अधिक योजनाएँ: बिल्ड केवल सरल बदलावों में।"$json$::jsonb),
  ('hi', 'expertise.junior', $json$"जूनियर"$json$::jsonb),
  ('hi', 'expertise.junior.hint', $json$"सामान्य से थोड़ा अधिक पूछता है; बिल्ड केवल सरल बदलावों में।"$json$::jsonb),
  ('hi', 'expertise.mid', $json$"मिड-लेवल"$json$::jsonb),
  ('hi', 'expertise.mid.hint', $json$"मानक मानदंड: मध्यम बदलावों तक बिल्ड।"$json$::jsonb),
  ('hi', 'expertise.senior', $json$"सीनियर"$json$::jsonb),
  ('hi', 'expertise.senior.hint', $json$"छोटे अनुरोधों पर भरोसा करता है; मध्यम बदलावों तक बिल्ड, भले ही वे कोड दोबारा लिखें।"$json$::jsonb),
  ('hi', 'expertise.architect', $json$"आर्किटेक्ट"$json$::jsonb),
  ('hi', 'expertise.architect.hint', $json$"संक्षिप्त अनुरोधों पर भरोसा करता है; पूरे सिस्टम के काम में भी बिल्ड।"$json$::jsonb),
  ('hi', 'expertise.numbers', $json$"स्पष्टता {demand} · रूटिंग विश्वास {confidence} · {build} तक बिल्ड · काम मिटने की संभावना ≥ {destructive} पर योजना"$json$::jsonb),
  ('hi', 'expertise.saved', $json$"स्तर {level} में बदला गया। यह अगले अनुरोध से लागू होगा।"$json$::jsonb),
  ('hi', 'expertise.invalid', $json$"अज्ञात स्तर: {value}"$json$::jsonb),
  ('ar', 'expertise.title', $json$"مستواك"$json$::jsonb),
  ('ar', 'expertise.description', $json$"مرتبط بحسابك. يغيّر مقدار ما تسأله البوابة قبل تمرير الطلب وإلى أي حد يسمح Jev للوكيل بالبناء وحده. ولا يغيّر أبدًا ما يُحظر."$json$::jsonb),
  ('ar', 'expertise.starter', $json$"مبتدئ"$json$::jsonb),
  ('ar', 'expertise.starter.hint', $json$"أسئلة توضيح أكثر وخطط أكثر: التنفيذ للتغييرات البسيطة فقط."$json$::jsonb),
  ('ar', 'expertise.junior', $json$"مبتدئ متقدم"$json$::jsonb),
  ('ar', 'expertise.junior.hint', $json$"يسأل أكثر قليلًا من المعتاد؛ التنفيذ للتغييرات البسيطة فقط."$json$::jsonb),
  ('ar', 'expertise.mid', $json$"متوسط"$json$::jsonb),
  ('ar', 'expertise.mid.hint', $json$"المعايير القياسية: التنفيذ حتى التغييرات المتوسطة."$json$::jsonb),
  ('ar', 'expertise.senior', $json$"خبير"$json$::jsonb),
  ('ar', 'expertise.senior.hint', $json$"يثق بالطلبات الأقصر؛ التنفيذ حتى التغييرات المتوسطة حتى لو أعادت كتابة الشيفرة."$json$::jsonb),
  ('ar', 'expertise.architect', $json$"معماري"$json$::jsonb),
  ('ar', 'expertise.architect.hint', $json$"يثق بالطلبات الموجزة؛ التنفيذ حتى في العمل على مستوى النظام."$json$::jsonb),
  ('ar', 'expertise.numbers', $json$"الوضوح {demand} · ثقة التوجيه {confidence} · التنفيذ حتى {build} · خطة إذا احتمل محو العمل ≥ {destructive}"$json$::jsonb),
  ('ar', 'expertise.saved', $json$"تم تغيير المستوى إلى {level}. يسري من الطلب التالي."$json$::jsonb),
  ('ar', 'expertise.invalid', $json$"مستوى غير معروف: {value}"$json$::jsonb),
  ('fr', 'expertise.title', $json$"Votre niveau"$json$::jsonb),
  ('fr', 'expertise.description', $json$"Lié à votre compte. Il change combien la loge pose de questions avant de laisser passer une demande et jusqu’où Jev laisse l’agent construire seul. Il ne change jamais ce qui est bloqué."$json$::jsonb),
  ('fr', 'expertise.starter', $json$"Débutant"$json$::jsonb),
  ('fr', 'expertise.starter.hint', $json$"Plus de questions de clarification et plus de plans : build seulement pour les changements simples."$json$::jsonb),
  ('fr', 'expertise.junior', $json$"Junior"$json$::jsonb),
  ('fr', 'expertise.junior.hint', $json$"Pose un peu plus de questions que d’habitude ; build seulement pour les changements simples."$json$::jsonb),
  ('fr', 'expertise.mid', $json$"Confirmé"$json$::jsonb),
  ('fr', 'expertise.mid.hint', $json$"Les critères standard : build jusqu’aux changements moyens."$json$::jsonb),
  ('fr', 'expertise.senior', $json$"Senior"$json$::jsonb),
  ('fr', 'expertise.senior.hint', $json$"Fait confiance aux demandes plus courtes ; build jusqu’aux changements moyens, même s’ils réécrivent du code."$json$::jsonb),
  ('fr', 'expertise.architect', $json$"Architecte"$json$::jsonb),
  ('fr', 'expertise.architect.hint', $json$"Fait confiance aux demandes concises ; build même pour un travail à l’échelle du système."$json$::jsonb),
  ('fr', 'expertise.numbers', $json$"clarté {demand} · confiance du routage {confidence} · build jusqu’à {build} · plan s’il peut effacer du travail ≥ {destructive}"$json$::jsonb),
  ('fr', 'expertise.saved', $json$"Niveau changé en {level}. Il s’applique dès la prochaine demande."$json$::jsonb),
  ('fr', 'expertise.invalid', $json$"Niveau inconnu : {value}"$json$::jsonb),
  ('ru', 'expertise.title', $json$"Ваш уровень"$json$::jsonb),
  ('ru', 'expertise.description', $json$"Привязан к вашему аккаунту. Определяет, сколько вопросов задаёт проходная, прежде чем пропустить запрос, и насколько Jev позволяет агенту строить самостоятельно. То, что блокируется, он не меняет никогда."$json$::jsonb),
  ('ru', 'expertise.starter', $json$"Начинающий"$json$::jsonb),
  ('ru', 'expertise.starter.hint', $json$"Больше уточняющих вопросов и больше планов: сборка только для простых изменений."$json$::jsonb),
  ('ru', 'expertise.junior', $json$"Джуниор"$json$::jsonb),
  ('ru', 'expertise.junior.hint', $json$"Спрашивает чуть больше обычного; сборка только для простых изменений."$json$::jsonb),
  ('ru', 'expertise.mid', $json$"Мидл"$json$::jsonb),
  ('ru', 'expertise.mid.hint', $json$"Стандартные критерии: сборка до средних изменений."$json$::jsonb),
  ('ru', 'expertise.senior', $json$"Сеньор"$json$::jsonb),
  ('ru', 'expertise.senior.hint', $json$"Доверяет более коротким запросам; сборка до средних изменений, даже если они переписывают код."$json$::jsonb),
  ('ru', 'expertise.architect', $json$"Архитектор"$json$::jsonb),
  ('ru', 'expertise.architect.hint', $json$"Доверяет лаконичным запросам; сборка даже для работы масштаба всей системы."$json$::jsonb),
  ('ru', 'expertise.numbers', $json$"ясность {demand} · уверенность маршрутизации {confidence} · сборка до {build} · план, если может стереть работу ≥ {destructive}"$json$::jsonb),
  ('ru', 'expertise.saved', $json$"Уровень изменён на {level}. Действует со следующего запроса."$json$::jsonb),
  ('ru', 'expertise.invalid', $json$"Неизвестный уровень: {value}"$json$::jsonb),
  ('ja', 'expertise.title', $json$"あなたのレベル"$json$::jsonb),
  ('ja', 'expertise.description', $json$"アカウントに紐づきます。ゲートがリクエストを通す前にどれだけ質問するか、Jev がエージェントにどこまで自力で構築させるかが変わります。ブロックされる内容は変わりません。"$json$::jsonb),
  ('ja', 'expertise.starter', $json$"スターター"$json$::jsonb),
  ('ja', 'expertise.starter.hint', $json$"確認の質問と計画が増えます。ビルドは単純な変更のみ。"$json$::jsonb),
  ('ja', 'expertise.junior', $json$"ジュニア"$json$::jsonb),
  ('ja', 'expertise.junior.hint', $json$"標準より少し多く質問します。ビルドは単純な変更のみ。"$json$::jsonb),
  ('ja', 'expertise.mid', $json$"ミドル"$json$::jsonb),
  ('ja', 'expertise.mid.hint', $json$"標準の基準。中程度の変更までビルド。"$json$::jsonb),
  ('ja', 'expertise.senior', $json$"シニア"$json$::jsonb),
  ('ja', 'expertise.senior.hint', $json$"短いリクエストを信頼します。コードを書き換える場合も中程度の変更までビルド。"$json$::jsonb),
  ('ja', 'expertise.architect', $json$"アーキテクト"$json$::jsonb),
  ('ja', 'expertise.architect.hint', $json$"簡潔なリクエストを信頼します。システム全体の作業でもビルド。"$json$::jsonb),
  ('ja', 'expertise.numbers', $json$"明確さ {demand} · ルーティング信頼度 {confidence} · {build} までビルド · 作業を消す可能性 ≥ {destructive} なら計画"$json$::jsonb),
  ('ja', 'expertise.saved', $json$"レベルを {level} に変更しました。次のリクエストから適用されます。"$json$::jsonb),
  ('ja', 'expertise.invalid', $json$"不明なレベル: {value}"$json$::jsonb),
  ('de', 'expertise.title', $json$"Ihr Level"$json$::jsonb),
  ('de', 'expertise.description', $json$"Gehört zu Ihrem Konto. Es ändert, wie viel die Pforte fragt, bevor sie eine Anfrage durchlässt, und wie weit Jev den Agenten selbst bauen lässt. Was blockiert wird, ändert es nie."$json$::jsonb),
  ('de', 'expertise.starter', $json$"Einsteiger"$json$::jsonb),
  ('de', 'expertise.starter.hint', $json$"Mehr Rückfragen und mehr Pläne: Build nur bei einfachen Änderungen."$json$::jsonb),
  ('de', 'expertise.junior', $json$"Junior"$json$::jsonb),
  ('de', 'expertise.junior.hint', $json$"Fragt etwas mehr als üblich; Build nur bei einfachen Änderungen."$json$::jsonb),
  ('de', 'expertise.mid', $json$"Mid-Level"$json$::jsonb),
  ('de', 'expertise.mid.hint', $json$"Die Standardkriterien: Build bis zu mittleren Änderungen."$json$::jsonb),
  ('de', 'expertise.senior', $json$"Senior"$json$::jsonb),
  ('de', 'expertise.senior.hint', $json$"Vertraut kürzeren Anfragen; Build bis zu mittleren Änderungen, auch wenn sie Code neu schreiben."$json$::jsonb),
  ('de', 'expertise.architect', $json$"Architekt"$json$::jsonb),
  ('de', 'expertise.architect.hint', $json$"Vertraut knappen Anfragen; Build sogar bei systemweiter Arbeit."$json$::jsonb),
  ('de', 'expertise.numbers', $json$"Klarheit {demand} · Routing-Sicherheit {confidence} · Build bis {build} · Plan, wenn Arbeit gelöscht werden könnte ≥ {destructive}"$json$::jsonb),
  ('de', 'expertise.saved', $json$"Level auf {level} geändert. Es gilt ab der nächsten Anfrage."$json$::jsonb),
  ('de', 'expertise.invalid', $json$"Unbekanntes Level: {value}"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
