-- O design system novo: tema claro, escuro ou o do sistema, escolhido nas
-- configurações do app (fica no aparelho, não no banco), e a trilha de
-- navegação do cabeçalho, que precisa de nome para leitores de tela.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'header.breadcrumb', $json$"Trilha de navegação"$json$::jsonb),
  ('pt-BR', 'app.section.theme', $json$"Tema"$json$::jsonb),
  ('pt-BR', 'app.section.theme.description', $json$"Claro, escuro ou o mesmo do sistema. A escolha fica neste dispositivo."$json$::jsonb),
  ('pt-BR', 'theme.label', $json$"Tema"$json$::jsonb),
  ('pt-BR', 'theme.system', $json$"Sistema"$json$::jsonb),
  ('pt-BR', 'theme.light', $json$"Claro"$json$::jsonb),
  ('pt-BR', 'theme.dark', $json$"Escuro"$json$::jsonb),
  ('en', 'header.breadcrumb', $json$"Breadcrumb"$json$::jsonb),
  ('en', 'app.section.theme', $json$"Theme"$json$::jsonb),
  ('en', 'app.section.theme.description', $json$"Light, dark or the same as the system. The choice stays on this device."$json$::jsonb),
  ('en', 'theme.label', $json$"Theme"$json$::jsonb),
  ('en', 'theme.system', $json$"System"$json$::jsonb),
  ('en', 'theme.light', $json$"Light"$json$::jsonb),
  ('en', 'theme.dark', $json$"Dark"$json$::jsonb),
  ('es', 'header.breadcrumb', $json$"Ruta de navegación"$json$::jsonb),
  ('es', 'app.section.theme', $json$"Tema"$json$::jsonb),
  ('es', 'app.section.theme.description', $json$"Claro, oscuro o el mismo del sistema. La elección se guarda en este dispositivo."$json$::jsonb),
  ('es', 'theme.label', $json$"Tema"$json$::jsonb),
  ('es', 'theme.system', $json$"Sistema"$json$::jsonb),
  ('es', 'theme.light', $json$"Claro"$json$::jsonb),
  ('es', 'theme.dark', $json$"Oscuro"$json$::jsonb),
  ('zh-CN', 'header.breadcrumb', $json$"导航路径"$json$::jsonb),
  ('zh-CN', 'app.section.theme', $json$"主题"$json$::jsonb),
  ('zh-CN', 'app.section.theme.description', $json$"浅色、深色或跟随系统。此选择仅保存在本设备上。"$json$::jsonb),
  ('zh-CN', 'theme.label', $json$"主题"$json$::jsonb),
  ('zh-CN', 'theme.system', $json$"跟随系统"$json$::jsonb),
  ('zh-CN', 'theme.light', $json$"浅色"$json$::jsonb),
  ('zh-CN', 'theme.dark', $json$"深色"$json$::jsonb),
  ('hi', 'header.breadcrumb', $json$"नेविगेशन पथ"$json$::jsonb),
  ('hi', 'app.section.theme', $json$"थीम"$json$::jsonb),
  ('hi', 'app.section.theme.description', $json$"हल्का, गहरा या सिस्टम के समान। यह चुनाव इसी डिवाइस पर रहता है।"$json$::jsonb),
  ('hi', 'theme.label', $json$"थीम"$json$::jsonb),
  ('hi', 'theme.system', $json$"सिस्टम"$json$::jsonb),
  ('hi', 'theme.light', $json$"हल्का"$json$::jsonb),
  ('hi', 'theme.dark', $json$"गहरा"$json$::jsonb),
  ('ar', 'header.breadcrumb', $json$"مسار التنقل"$json$::jsonb),
  ('ar', 'app.section.theme', $json$"السمة"$json$::jsonb),
  ('ar', 'app.section.theme.description', $json$"فاتح أو داكن أو مثل النظام. يبقى الاختيار على هذا الجهاز."$json$::jsonb),
  ('ar', 'theme.label', $json$"السمة"$json$::jsonb),
  ('ar', 'theme.system', $json$"النظام"$json$::jsonb),
  ('ar', 'theme.light', $json$"فاتح"$json$::jsonb),
  ('ar', 'theme.dark', $json$"داكن"$json$::jsonb),
  ('fr', 'header.breadcrumb', $json$"Fil d’Ariane"$json$::jsonb),
  ('fr', 'app.section.theme', $json$"Thème"$json$::jsonb),
  ('fr', 'app.section.theme.description', $json$"Clair, sombre ou comme le système. Le choix reste sur cet appareil."$json$::jsonb),
  ('fr', 'theme.label', $json$"Thème"$json$::jsonb),
  ('fr', 'theme.system', $json$"Système"$json$::jsonb),
  ('fr', 'theme.light', $json$"Clair"$json$::jsonb),
  ('fr', 'theme.dark', $json$"Sombre"$json$::jsonb),
  ('ru', 'header.breadcrumb', $json$"Навигационная цепочка"$json$::jsonb),
  ('ru', 'app.section.theme', $json$"Тема"$json$::jsonb),
  ('ru', 'app.section.theme.description', $json$"Светлая, тёмная или как в системе. Выбор хранится на этом устройстве."$json$::jsonb),
  ('ru', 'theme.label', $json$"Тема"$json$::jsonb),
  ('ru', 'theme.system', $json$"Системная"$json$::jsonb),
  ('ru', 'theme.light', $json$"Светлая"$json$::jsonb),
  ('ru', 'theme.dark', $json$"Тёмная"$json$::jsonb),
  ('ja', 'header.breadcrumb', $json$"パンくずリスト"$json$::jsonb),
  ('ja', 'app.section.theme', $json$"テーマ"$json$::jsonb),
  ('ja', 'app.section.theme.description', $json$"ライト、ダーク、またはシステムと同じ。選択はこのデバイスに保存されます。"$json$::jsonb),
  ('ja', 'theme.label', $json$"テーマ"$json$::jsonb),
  ('ja', 'theme.system', $json$"システム"$json$::jsonb),
  ('ja', 'theme.light', $json$"ライト"$json$::jsonb),
  ('ja', 'theme.dark', $json$"ダーク"$json$::jsonb),
  ('de', 'header.breadcrumb', $json$"Brotkrümelnavigation"$json$::jsonb),
  ('de', 'app.section.theme', $json$"Design"$json$::jsonb),
  ('de', 'app.section.theme.description', $json$"Hell, dunkel oder wie das System. Die Auswahl bleibt auf diesem Gerät."$json$::jsonb),
  ('de', 'theme.label', $json$"Design"$json$::jsonb),
  ('de', 'theme.system', $json$"System"$json$::jsonb),
  ('de', 'theme.light', $json$"Hell"$json$::jsonb),
  ('de', 'theme.dark', $json$"Dunkel"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
