-- v0.60.0: os textos dos recursos de núcleo e dos recursos novos do
-- catálogo (divididos entre o app e o site), da trava no app e do editor de
-- planos da Administração.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'feature.entryGate.title', $json$"Portaria de entrada"$json$::jsonb),
  ('pt-BR', 'feature.entryGate.detail', $json$"O Jev confere cada pedido antes de qualquer agente rodar e pede o que falta."$json$::jsonb),
  ('pt-BR', 'feature.exitGate.title', $json$"Portaria de saída"$json$::jsonb),
  ('pt-BR', 'feature.exitGate.detail', $json$"O Jev confere os comandos e os arquivos de cada resposta contra as regras do projeto."$json$::jsonb),
  ('pt-BR', 'feature.secretRedaction.title', $json$"Remoção de segredos"$json$::jsonb),
  ('pt-BR', 'feature.secretRedaction.detail', $json$"Chaves, tokens e senhas são trocados antes de qualquer arquivo chegar a um modelo."$json$::jsonb),
  ('pt-BR', 'feature.sensitiveFiles.title', $json$"Arquivos sensíveis"$json$::jsonb),
  ('pt-BR', 'feature.sensitiveFiles.detail', $json$"Arquivos como .env, chaves e certificados nunca entram no contexto."$json$::jsonb),
  ('pt-BR', 'feature.agentSessions.title', $json$"Sessões do agente"$json$::jsonb),
  ('pt-BR', 'feature.agentSessions.detail', $json$"Cada chat retoma a sessão do seu agente em vez de reler o projeto a cada pedido."$json$::jsonb),
  ('pt-BR', 'feature.contextCache.title', $json$"Cache de contexto"$json$::jsonb),
  ('pt-BR', 'feature.contextCache.detail', $json$"O contexto montado para um pedido é reaproveitado por pelo menos cinco minutos enquanto os arquivos não mudam."$json$::jsonb),
  ('pt-BR', 'feature.answerRecall.title', $json$"Respostas anteriores"$json$::jsonb),
  ('pt-BR', 'feature.answerRecall.detail', $json$"Um pedido quase igual a um já respondido em outro chat do projeto parte daquela resposta."$json$::jsonb),
  ('pt-BR', 'feature.leanCode.title', $json$"Código enxuto"$json$::jsonb),
  ('pt-BR', 'feature.leanCode.detail', $json$"No modo build o agente escreve o mínimo de código que resolve a tarefa."$json$::jsonb),
  ('pt-BR', 'feature.symbolIndex.title', $json$"Índice de símbolos para o Claude"$json$::jsonb),
  ('pt-BR', 'feature.symbolIndex.detail', $json$"O Claude Code pergunta ao índice de símbolos do JayV onde as coisas moram em vez de varrer a pasta."$json$::jsonb),
  ('pt-BR', 'plans.required', $json$"Obrigatório no seu plano"$json$::jsonb),
  ('pt-BR', 'plans.cacheFloor', $json$"Seu plano mantém o cache de contexto por pelo menos {minutes} minutos."$json$::jsonb),
  ('pt-BR', 'plans.sensitiveAlways', $json$"Seu plano também deixa sempre de fora: {patterns}."$json$::jsonb),
  ('pt-BR', 'admin.error.coreFeature', $json$"Este é um recurso de núcleo: fica ligado em todo plano e não pode ser desligado."$json$::jsonb),
  ('pt-BR', 'site.admin.feature.core', $json$"Recurso de núcleo: ligado em todo plano, não pode ser desligado"$json$::jsonb),
  ('pt-BR', 'site.admin.feature.mode.off', $json$"Fora do plano"$json$::jsonb),
  ('pt-BR', 'site.admin.feature.mode.optional', $json$"Opcional"$json$::jsonb),
  ('pt-BR', 'site.admin.feature.mode.locked', $json$"Obrigatório"$json$::jsonb),
  ('pt-BR', 'site.admin.feature.defaultOn', $json$"Ligado de partida"$json$::jsonb),
  ('pt-BR', 'site.admin.plan.limits', $json$"Limites"$json$::jsonb),
  ('pt-BR', 'site.admin.plan.jevDailyLimit', $json$"Chamadas do Jev por dia"$json$::jsonb),
  ('pt-BR', 'site.admin.plan.jevDailyLimitHint', $json$"Vazio usa o padrão do servidor."$json$::jsonb),
  ('pt-BR', 'site.admin.plan.maxConcurrentTurns', $json$"Pedidos ao mesmo tempo"$json$::jsonb),
  ('pt-BR', 'site.admin.plan.maxConcurrentTurnsHint', $json$"Quantos chats podem rodar pedidos ao mesmo tempo, de 1 a 8."$json$::jsonb),
  ('en', 'feature.entryGate.title', $json$"Entry gate"$json$::jsonb),
  ('en', 'feature.entryGate.detail', $json$"Jev checks every request before any agent runs and asks for what is missing."$json$::jsonb),
  ('en', 'feature.exitGate.title', $json$"Exit gate"$json$::jsonb),
  ('en', 'feature.exitGate.detail', $json$"Jev checks the commands and files in every answer against the project's rules."$json$::jsonb),
  ('en', 'feature.secretRedaction.title', $json$"Secret redaction"$json$::jsonb),
  ('en', 'feature.secretRedaction.detail', $json$"Keys, tokens and passwords are replaced before any file reaches a model."$json$::jsonb),
  ('en', 'feature.sensitiveFiles.title', $json$"Sensitive files"$json$::jsonb),
  ('en', 'feature.sensitiveFiles.detail', $json$"Files such as .env, keys and certificates never go into the context."$json$::jsonb),
  ('en', 'feature.agentSessions.title', $json$"Agent sessions"$json$::jsonb),
  ('en', 'feature.agentSessions.detail', $json$"Each chat resumes its agent's session instead of re-reading the project on every request."$json$::jsonb),
  ('en', 'feature.contextCache.title', $json$"Context cache"$json$::jsonb),
  ('en', 'feature.contextCache.detail', $json$"The context built for a request is reused for at least five minutes while the files stay the same."$json$::jsonb),
  ('en', 'feature.answerRecall.title', $json$"Earlier answers"$json$::jsonb),
  ('en', 'feature.answerRecall.detail', $json$"A request almost identical to one already answered in another chat of the project starts from that answer."$json$::jsonb),
  ('en', 'feature.leanCode.title', $json$"Lean code"$json$::jsonb),
  ('en', 'feature.leanCode.detail', $json$"In build mode the agent writes the least code that solves the task."$json$::jsonb),
  ('en', 'feature.symbolIndex.title', $json$"Symbol index for Claude"$json$::jsonb),
  ('en', 'feature.symbolIndex.detail', $json$"Claude Code asks JayV's symbol index where things live instead of scanning the folder."$json$::jsonb),
  ('en', 'plans.required', $json$"Required by your plan"$json$::jsonb),
  ('en', 'plans.cacheFloor', $json$"Your plan keeps the context cache for at least {minutes} minutes."$json$::jsonb),
  ('en', 'plans.sensitiveAlways', $json$"Your plan always keeps these out too: {patterns}."$json$::jsonb),
  ('en', 'admin.error.coreFeature', $json$"This is a core feature: it stays on in every plan and can't be turned off."$json$::jsonb),
  ('en', 'site.admin.feature.core', $json$"Core feature: on in every plan, can't be turned off"$json$::jsonb),
  ('en', 'site.admin.feature.mode.off', $json$"Not included"$json$::jsonb),
  ('en', 'site.admin.feature.mode.optional', $json$"Optional"$json$::jsonb),
  ('en', 'site.admin.feature.mode.locked', $json$"Required"$json$::jsonb),
  ('en', 'site.admin.feature.defaultOn', $json$"On by default"$json$::jsonb),
  ('en', 'site.admin.plan.limits', $json$"Limits"$json$::jsonb),
  ('en', 'site.admin.plan.jevDailyLimit', $json$"Jev calls per day"$json$::jsonb),
  ('en', 'site.admin.plan.jevDailyLimitHint', $json$"Empty uses the server default."$json$::jsonb),
  ('en', 'site.admin.plan.maxConcurrentTurns', $json$"Requests at the same time"$json$::jsonb),
  ('en', 'site.admin.plan.maxConcurrentTurnsHint', $json$"How many chats can run requests at once, from 1 to 8."$json$::jsonb),
  ('es', 'feature.entryGate.title', $json$"Portería de entrada"$json$::jsonb),
  ('es', 'feature.entryGate.detail', $json$"Jev revisa cada solicitud antes de que se ejecute cualquier agente y pide lo que falta."$json$::jsonb),
  ('es', 'feature.exitGate.title', $json$"Portería de salida"$json$::jsonb),
  ('es', 'feature.exitGate.detail', $json$"Jev revisa los comandos y archivos de cada respuesta frente a las reglas del proyecto."$json$::jsonb),
  ('es', 'feature.secretRedaction.title', $json$"Ocultación de secretos"$json$::jsonb),
  ('es', 'feature.secretRedaction.detail', $json$"Las claves, tokens y contraseñas se reemplazan antes de que cualquier archivo llegue a un modelo."$json$::jsonb),
  ('es', 'feature.sensitiveFiles.title', $json$"Archivos sensibles"$json$::jsonb),
  ('es', 'feature.sensitiveFiles.detail', $json$"Archivos como .env, claves y certificados nunca entran en el contexto."$json$::jsonb),
  ('es', 'feature.agentSessions.title', $json$"Sesiones del agente"$json$::jsonb),
  ('es', 'feature.agentSessions.detail', $json$"Cada chat retoma la sesión de su agente en lugar de releer el proyecto en cada solicitud."$json$::jsonb),
  ('es', 'feature.contextCache.title', $json$"Caché de contexto"$json$::jsonb),
  ('es', 'feature.contextCache.detail', $json$"El contexto armado para una solicitud se reutiliza durante al menos cinco minutos mientras los archivos no cambien."$json$::jsonb),
  ('es', 'feature.answerRecall.title', $json$"Respuestas anteriores"$json$::jsonb),
  ('es', 'feature.answerRecall.detail', $json$"Una solicitud casi idéntica a otra ya respondida en otro chat del proyecto parte de esa respuesta."$json$::jsonb),
  ('es', 'feature.leanCode.title', $json$"Código mínimo"$json$::jsonb),
  ('es', 'feature.leanCode.detail', $json$"En modo build el agente escribe el mínimo código que resuelve la tarea."$json$::jsonb),
  ('es', 'feature.symbolIndex.title', $json$"Índice de símbolos para Claude"$json$::jsonb),
  ('es', 'feature.symbolIndex.detail', $json$"Claude Code pregunta al índice de símbolos de JayV dónde está cada cosa en lugar de recorrer la carpeta."$json$::jsonb),
  ('es', 'plans.required', $json$"Obligatorio en tu plan"$json$::jsonb),
  ('es', 'plans.cacheFloor', $json$"Tu plan mantiene la caché de contexto al menos {minutes} minutos."$json$::jsonb),
  ('es', 'plans.sensitiveAlways', $json$"Tu plan también deja siempre fuera: {patterns}."$json$::jsonb),
  ('es', 'admin.error.coreFeature', $json$"Esta es una función esencial: permanece activa en todos los planes y no se puede desactivar."$json$::jsonb),
  ('es', 'site.admin.feature.core', $json$"Función esencial: activa en todos los planes, no se puede desactivar"$json$::jsonb),
  ('es', 'site.admin.feature.mode.off', $json$"No incluido"$json$::jsonb),
  ('es', 'site.admin.feature.mode.optional', $json$"Opcional"$json$::jsonb),
  ('es', 'site.admin.feature.mode.locked', $json$"Obligatorio"$json$::jsonb),
  ('es', 'site.admin.feature.defaultOn', $json$"Activado por defecto"$json$::jsonb),
  ('es', 'site.admin.plan.limits', $json$"Límites"$json$::jsonb),
  ('es', 'site.admin.plan.jevDailyLimit', $json$"Llamadas al Jev por día"$json$::jsonb),
  ('es', 'site.admin.plan.jevDailyLimitHint', $json$"Vacío usa el valor por defecto del servidor."$json$::jsonb),
  ('es', 'site.admin.plan.maxConcurrentTurns', $json$"Solicitudes simultáneas"$json$::jsonb),
  ('es', 'site.admin.plan.maxConcurrentTurnsHint', $json$"Cuántos chats pueden ejecutar solicitudes a la vez, de 1 a 8."$json$::jsonb),
  ('zh-CN', 'feature.entryGate.title', $json$"入口门卫"$json$::jsonb),
  ('zh-CN', 'feature.entryGate.detail', $json$"在任何代理运行之前，Jev 会检查每个请求并询问缺少的内容。"$json$::jsonb),
  ('zh-CN', 'feature.exitGate.title', $json$"出口门卫"$json$::jsonb),
  ('zh-CN', 'feature.exitGate.detail', $json$"Jev 会根据项目规则检查每个回答中的命令和文件。"$json$::jsonb),
  ('zh-CN', 'feature.secretRedaction.title', $json$"密钥脱敏"$json$::jsonb),
  ('zh-CN', 'feature.secretRedaction.detail', $json$"在任何文件发送给模型之前，密钥、令牌和密码都会被替换。"$json$::jsonb),
  ('zh-CN', 'feature.sensitiveFiles.title', $json$"敏感文件"$json$::jsonb),
  ('zh-CN', 'feature.sensitiveFiles.detail', $json$".env、密钥和证书等文件永远不会进入上下文。"$json$::jsonb),
  ('zh-CN', 'feature.agentSessions.title', $json$"代理会话"$json$::jsonb),
  ('zh-CN', 'feature.agentSessions.detail', $json$"每个聊天都会恢复其代理的会话，而不是在每次请求时重新读取项目。"$json$::jsonb),
  ('zh-CN', 'feature.contextCache.title', $json$"上下文缓存"$json$::jsonb),
  ('zh-CN', 'feature.contextCache.detail', $json$"只要文件没有变化，为请求构建的上下文会被复用至少五分钟。"$json$::jsonb),
  ('zh-CN', 'feature.answerRecall.title', $json$"以往的回答"$json$::jsonb),
  ('zh-CN', 'feature.answerRecall.detail', $json$"与项目中另一个聊天里已回答过的请求几乎相同的请求，会从那个回答开始。"$json$::jsonb),
  ('zh-CN', 'feature.leanCode.title', $json$"精简代码"$json$::jsonb),
  ('zh-CN', 'feature.leanCode.detail', $json$"在构建模式下，代理只写解决任务所需的最少代码。"$json$::jsonb),
  ('zh-CN', 'feature.symbolIndex.title', $json$"供 Claude 使用的符号索引"$json$::jsonb),
  ('zh-CN', 'feature.symbolIndex.detail', $json$"Claude Code 会询问 JayV 的符号索引东西在哪里，而不是扫描整个文件夹。"$json$::jsonb),
  ('zh-CN', 'plans.required', $json$"你的套餐要求启用"$json$::jsonb),
  ('zh-CN', 'plans.cacheFloor', $json$"你的套餐会至少保留上下文缓存 {minutes} 分钟。"$json$::jsonb),
  ('zh-CN', 'plans.sensitiveAlways', $json$"你的套餐还会始终排除：{patterns}。"$json$::jsonb),
  ('zh-CN', 'admin.error.coreFeature', $json$"这是核心功能：在所有套餐中都保持开启，无法关闭。"$json$::jsonb),
  ('zh-CN', 'site.admin.feature.core', $json$"核心功能：所有套餐中均开启，无法关闭"$json$::jsonb),
  ('zh-CN', 'site.admin.feature.mode.off', $json$"不包含"$json$::jsonb),
  ('zh-CN', 'site.admin.feature.mode.optional', $json$"可选"$json$::jsonb),
  ('zh-CN', 'site.admin.feature.mode.locked', $json$"必需"$json$::jsonb),
  ('zh-CN', 'site.admin.feature.defaultOn', $json$"默认开启"$json$::jsonb),
  ('zh-CN', 'site.admin.plan.limits', $json$"限制"$json$::jsonb),
  ('zh-CN', 'site.admin.plan.jevDailyLimit', $json$"每日 Jev 调用次数"$json$::jsonb),
  ('zh-CN', 'site.admin.plan.jevDailyLimitHint', $json$"留空则使用服务器默认值。"$json$::jsonb),
  ('zh-CN', 'site.admin.plan.maxConcurrentTurns', $json$"同时进行的请求"$json$::jsonb),
  ('zh-CN', 'site.admin.plan.maxConcurrentTurnsHint', $json$"可以同时运行请求的聊天数量，1 到 8。"$json$::jsonb),
  ('hi', 'feature.entryGate.title', $json$"प्रवेश गेट"$json$::jsonb),
  ('hi', 'feature.entryGate.detail', $json$"किसी भी एजेंट के चलने से पहले Jev हर अनुरोध की जाँच करता है और जो कमी है वह पूछता है।"$json$::jsonb),
  ('hi', 'feature.exitGate.title', $json$"निकास गेट"$json$::jsonb),
  ('hi', 'feature.exitGate.detail', $json$"Jev हर जवाब के कमांड और फ़ाइलों को प्रोजेक्ट के नियमों से मिलाकर जाँचता है।"$json$::jsonb),
  ('hi', 'feature.secretRedaction.title', $json$"गोपनीय जानकारी छिपाना"$json$::jsonb),
  ('hi', 'feature.secretRedaction.detail', $json$"किसी भी फ़ाइल के मॉडल तक पहुँचने से पहले कुंजियाँ, टोकन और पासवर्ड बदल दिए जाते हैं।"$json$::jsonb),
  ('hi', 'feature.sensitiveFiles.title', $json$"संवेदनशील फ़ाइलें"$json$::jsonb),
  ('hi', 'feature.sensitiveFiles.detail', $json$".env, कुंजियाँ और प्रमाणपत्र जैसी फ़ाइलें कभी संदर्भ में नहीं जातीं।"$json$::jsonb),
  ('hi', 'feature.agentSessions.title', $json$"एजेंट सत्र"$json$::jsonb),
  ('hi', 'feature.agentSessions.detail', $json$"हर चैट हर अनुरोध पर प्रोजेक्ट दोबारा पढ़ने के बजाय अपने एजेंट का सत्र फिर से शुरू करती है।"$json$::jsonb),
  ('hi', 'feature.contextCache.title', $json$"संदर्भ कैश"$json$::jsonb),
  ('hi', 'feature.contextCache.detail', $json$"जब तक फ़ाइलें नहीं बदलतीं, किसी अनुरोध के लिए बना संदर्भ कम से कम पाँच मिनट तक दोबारा इस्तेमाल होता है।"$json$::jsonb),
  ('hi', 'feature.answerRecall.title', $json$"पिछले जवाब"$json$::jsonb),
  ('hi', 'feature.answerRecall.detail', $json$"प्रोजेक्ट की किसी दूसरी चैट में पहले से जवाब दिए गए अनुरोध जैसा अनुरोध उसी जवाब से शुरू होता है।"$json$::jsonb),
  ('hi', 'feature.leanCode.title', $json$"संक्षिप्त कोड"$json$::jsonb),
  ('hi', 'feature.leanCode.detail', $json$"बिल्ड मोड में एजेंट काम हल करने के लिए कम से कम कोड लिखता है।"$json$::jsonb),
  ('hi', 'feature.symbolIndex.title', $json$"Claude के लिए सिंबल इंडेक्स"$json$::jsonb),
  ('hi', 'feature.symbolIndex.detail', $json$"Claude Code फ़ोल्डर खँगालने के बजाय JayV के सिंबल इंडेक्स से पूछता है कि चीज़ें कहाँ हैं।"$json$::jsonb),
  ('hi', 'plans.required', $json$"आपके प्लान में अनिवार्य"$json$::jsonb),
  ('hi', 'plans.cacheFloor', $json$"आपका प्लान संदर्भ कैश को कम से कम {minutes} मिनट तक रखता है।"$json$::jsonb),
  ('hi', 'plans.sensitiveAlways', $json$"आपका प्लान इन्हें भी हमेशा बाहर रखता है: {patterns}।"$json$::jsonb),
  ('hi', 'admin.error.coreFeature', $json$"यह मुख्य फ़ीचर है: यह हर प्लान में चालू रहता है और बंद नहीं किया जा सकता।"$json$::jsonb),
  ('hi', 'site.admin.feature.core', $json$"मुख्य फ़ीचर: हर प्लान में चालू, बंद नहीं किया जा सकता"$json$::jsonb),
  ('hi', 'site.admin.feature.mode.off', $json$"शामिल नहीं"$json$::jsonb),
  ('hi', 'site.admin.feature.mode.optional', $json$"वैकल्पिक"$json$::jsonb),
  ('hi', 'site.admin.feature.mode.locked', $json$"अनिवार्य"$json$::jsonb),
  ('hi', 'site.admin.feature.defaultOn', $json$"डिफ़ॉल्ट रूप से चालू"$json$::jsonb),
  ('hi', 'site.admin.plan.limits', $json$"सीमाएँ"$json$::jsonb),
  ('hi', 'site.admin.plan.jevDailyLimit', $json$"प्रति दिन Jev कॉल"$json$::jsonb),
  ('hi', 'site.admin.plan.jevDailyLimitHint', $json$"खाली छोड़ने पर सर्वर का डिफ़ॉल्ट लागू होता है।"$json$::jsonb),
  ('hi', 'site.admin.plan.maxConcurrentTurns', $json$"एक साथ अनुरोध"$json$::jsonb),
  ('hi', 'site.admin.plan.maxConcurrentTurnsHint', $json$"कितनी चैट एक साथ अनुरोध चला सकती हैं, 1 से 8 तक।"$json$::jsonb),
  ('ar', 'feature.entryGate.title', $json$"بوابة الدخول"$json$::jsonb),
  ('ar', 'feature.entryGate.detail', $json$"يفحص Jev كل طلب قبل تشغيل أي وكيل ويسأل عمّا ينقصه."$json$::jsonb),
  ('ar', 'feature.exitGate.title', $json$"بوابة الخروج"$json$::jsonb),
  ('ar', 'feature.exitGate.detail', $json$"يفحص Jev الأوامر والملفات في كل رد وفق قواعد المشروع."$json$::jsonb),
  ('ar', 'feature.secretRedaction.title', $json$"حجب الأسرار"$json$::jsonb),
  ('ar', 'feature.secretRedaction.detail', $json$"تُستبدل المفاتيح والرموز وكلمات المرور قبل وصول أي ملف إلى نموذج."$json$::jsonb),
  ('ar', 'feature.sensitiveFiles.title', $json$"الملفات الحساسة"$json$::jsonb),
  ('ar', 'feature.sensitiveFiles.detail', $json$"لا تدخل ملفات مثل .env والمفاتيح والشهادات إلى السياق أبدًا."$json$::jsonb),
  ('ar', 'feature.agentSessions.title', $json$"جلسات الوكيل"$json$::jsonb),
  ('ar', 'feature.agentSessions.detail', $json$"تستأنف كل دردشة جلسة وكيلها بدلًا من إعادة قراءة المشروع مع كل طلب."$json$::jsonb),
  ('ar', 'feature.contextCache.title', $json$"ذاكرة السياق المؤقتة"$json$::jsonb),
  ('ar', 'feature.contextCache.detail', $json$"يُعاد استخدام السياق المبني لطلب ما لمدة خمس دقائق على الأقل ما دامت الملفات لم تتغير."$json$::jsonb),
  ('ar', 'feature.answerRecall.title', $json$"الإجابات السابقة"$json$::jsonb),
  ('ar', 'feature.answerRecall.detail', $json$"الطلب المطابق تقريبًا لطلب أُجيب عنه في دردشة أخرى من المشروع يبدأ من تلك الإجابة."$json$::jsonb),
  ('ar', 'feature.leanCode.title', $json$"شيفرة مختصرة"$json$::jsonb),
  ('ar', 'feature.leanCode.detail', $json$"في وضع البناء يكتب الوكيل أقل قدر من الشيفرة يحل المهمة."$json$::jsonb),
  ('ar', 'feature.symbolIndex.title', $json$"فهرس الرموز لـ Claude"$json$::jsonb),
  ('ar', 'feature.symbolIndex.detail', $json$"يسأل Claude Code فهرس رموز JayV عن مكان الأشياء بدلًا من مسح المجلد."$json$::jsonb),
  ('ar', 'plans.required', $json$"إلزامي في خطتك"$json$::jsonb),
  ('ar', 'plans.cacheFloor', $json$"تحتفظ خطتك بذاكرة السياق المؤقتة لمدة {minutes} دقائق على الأقل."$json$::jsonb),
  ('ar', 'plans.sensitiveAlways', $json$"تستبعد خطتك هذه أيضًا دائمًا: {patterns}."$json$::jsonb),
  ('ar', 'admin.error.coreFeature', $json$"هذه ميزة أساسية: تبقى مفعّلة في كل خطة ولا يمكن إيقافها."$json$::jsonb),
  ('ar', 'site.admin.feature.core', $json$"ميزة أساسية: مفعّلة في كل خطة ولا يمكن إيقافها"$json$::jsonb),
  ('ar', 'site.admin.feature.mode.off', $json$"غير مضمّن"$json$::jsonb),
  ('ar', 'site.admin.feature.mode.optional', $json$"اختياري"$json$::jsonb),
  ('ar', 'site.admin.feature.mode.locked', $json$"إلزامي"$json$::jsonb),
  ('ar', 'site.admin.feature.defaultOn', $json$"مفعّل افتراضيًا"$json$::jsonb),
  ('ar', 'site.admin.plan.limits', $json$"الحدود"$json$::jsonb),
  ('ar', 'site.admin.plan.jevDailyLimit', $json$"استدعاءات Jev يوميًا"$json$::jsonb),
  ('ar', 'site.admin.plan.jevDailyLimitHint', $json$"إذا تُرك فارغًا يُستخدم الإعداد الافتراضي للخادم."$json$::jsonb),
  ('ar', 'site.admin.plan.maxConcurrentTurns', $json$"الطلبات في الوقت نفسه"$json$::jsonb),
  ('ar', 'site.admin.plan.maxConcurrentTurnsHint', $json$"عدد الدردشات التي يمكنها تشغيل الطلبات في الوقت نفسه، من 1 إلى 8."$json$::jsonb),
  ('fr', 'feature.entryGate.title', $json$"Contrôle d'entrée"$json$::jsonb),
  ('fr', 'feature.entryGate.detail', $json$"Jev vérifie chaque demande avant qu'un agent ne s'exécute et demande ce qui manque."$json$::jsonb),
  ('fr', 'feature.exitGate.title', $json$"Contrôle de sortie"$json$::jsonb),
  ('fr', 'feature.exitGate.detail', $json$"Jev vérifie les commandes et les fichiers de chaque réponse selon les règles du projet."$json$::jsonb),
  ('fr', 'feature.secretRedaction.title', $json$"Masquage des secrets"$json$::jsonb),
  ('fr', 'feature.secretRedaction.detail', $json$"Les clés, jetons et mots de passe sont remplacés avant qu'un fichier n'atteigne un modèle."$json$::jsonb),
  ('fr', 'feature.sensitiveFiles.title', $json$"Fichiers sensibles"$json$::jsonb),
  ('fr', 'feature.sensitiveFiles.detail', $json$"Les fichiers comme .env, les clés et les certificats n'entrent jamais dans le contexte."$json$::jsonb),
  ('fr', 'feature.agentSessions.title', $json$"Sessions de l'agent"$json$::jsonb),
  ('fr', 'feature.agentSessions.detail', $json$"Chaque chat reprend la session de son agent au lieu de relire le projet à chaque demande."$json$::jsonb),
  ('fr', 'feature.contextCache.title', $json$"Cache de contexte"$json$::jsonb),
  ('fr', 'feature.contextCache.detail', $json$"Le contexte construit pour une demande est réutilisé au moins cinq minutes tant que les fichiers ne changent pas."$json$::jsonb),
  ('fr', 'feature.answerRecall.title', $json$"Réponses précédentes"$json$::jsonb),
  ('fr', 'feature.answerRecall.detail', $json$"Une demande presque identique à une autre déjà traitée dans un autre chat du projet part de cette réponse."$json$::jsonb),
  ('fr', 'feature.leanCode.title', $json$"Code minimal"$json$::jsonb),
  ('fr', 'feature.leanCode.detail', $json$"En mode build, l'agent écrit le moins de code possible pour accomplir la tâche."$json$::jsonb),
  ('fr', 'feature.symbolIndex.title', $json$"Index des symboles pour Claude"$json$::jsonb),
  ('fr', 'feature.symbolIndex.detail', $json$"Claude Code demande à l'index des symboles de JayV où se trouvent les choses au lieu de parcourir le dossier."$json$::jsonb),
  ('fr', 'plans.required', $json$"Obligatoire dans votre forfait"$json$::jsonb),
  ('fr', 'plans.cacheFloor', $json$"Votre forfait conserve le cache de contexte au moins {minutes} minutes."$json$::jsonb),
  ('fr', 'plans.sensitiveAlways', $json$"Votre forfait exclut aussi toujours : {patterns}."$json$::jsonb),
  ('fr', 'admin.error.coreFeature', $json$"C'est une fonction essentielle : elle reste active dans tous les forfaits et ne peut pas être désactivée."$json$::jsonb),
  ('fr', 'site.admin.feature.core', $json$"Fonction essentielle : active dans tous les forfaits, impossible à désactiver"$json$::jsonb),
  ('fr', 'site.admin.feature.mode.off', $json$"Non inclus"$json$::jsonb),
  ('fr', 'site.admin.feature.mode.optional', $json$"Facultatif"$json$::jsonb),
  ('fr', 'site.admin.feature.mode.locked', $json$"Obligatoire"$json$::jsonb),
  ('fr', 'site.admin.feature.defaultOn', $json$"Activé par défaut"$json$::jsonb),
  ('fr', 'site.admin.plan.limits', $json$"Limites"$json$::jsonb),
  ('fr', 'site.admin.plan.jevDailyLimit', $json$"Appels au Jev par jour"$json$::jsonb),
  ('fr', 'site.admin.plan.jevDailyLimitHint', $json$"Vide : la valeur par défaut du serveur s'applique."$json$::jsonb),
  ('fr', 'site.admin.plan.maxConcurrentTurns', $json$"Demandes simultanées"$json$::jsonb),
  ('fr', 'site.admin.plan.maxConcurrentTurnsHint', $json$"Combien de chats peuvent exécuter des demandes en même temps, de 1 à 8."$json$::jsonb),
  ('ru', 'feature.entryGate.title', $json$"Входная проверка"$json$::jsonb),
  ('ru', 'feature.entryGate.detail', $json$"Jev проверяет каждый запрос до запуска любого агента и спрашивает, чего не хватает."$json$::jsonb),
  ('ru', 'feature.exitGate.title', $json$"Выходная проверка"$json$::jsonb),
  ('ru', 'feature.exitGate.detail', $json$"Jev сверяет команды и файлы в каждом ответе с правилами проекта."$json$::jsonb),
  ('ru', 'feature.secretRedaction.title', $json$"Скрытие секретов"$json$::jsonb),
  ('ru', 'feature.secretRedaction.detail', $json$"Ключи, токены и пароли заменяются до того, как файл попадёт к модели."$json$::jsonb),
  ('ru', 'feature.sensitiveFiles.title', $json$"Конфиденциальные файлы"$json$::jsonb),
  ('ru', 'feature.sensitiveFiles.detail', $json$"Файлы вроде .env, ключей и сертификатов никогда не попадают в контекст."$json$::jsonb),
  ('ru', 'feature.agentSessions.title', $json$"Сессии агента"$json$::jsonb),
  ('ru', 'feature.agentSessions.detail', $json$"Каждый чат продолжает сессию своего агента, а не перечитывает проект при каждом запросе."$json$::jsonb),
  ('ru', 'feature.contextCache.title', $json$"Кэш контекста"$json$::jsonb),
  ('ru', 'feature.contextCache.detail', $json$"Контекст, собранный для запроса, используется повторно не менее пяти минут, пока файлы не меняются."$json$::jsonb),
  ('ru', 'feature.answerRecall.title', $json$"Прежние ответы"$json$::jsonb),
  ('ru', 'feature.answerRecall.detail', $json$"Запрос, почти совпадающий с уже отвеченным в другом чате проекта, начинается с того ответа."$json$::jsonb),
  ('ru', 'feature.leanCode.title', $json$"Минимум кода"$json$::jsonb),
  ('ru', 'feature.leanCode.detail', $json$"В режиме сборки агент пишет минимум кода, который решает задачу."$json$::jsonb),
  ('ru', 'feature.symbolIndex.title', $json$"Индекс символов для Claude"$json$::jsonb),
  ('ru', 'feature.symbolIndex.detail', $json$"Claude Code спрашивает у индекса символов JayV, где что находится, вместо сканирования папки."$json$::jsonb),
  ('ru', 'plans.required', $json$"Обязательно в вашем тарифе"$json$::jsonb),
  ('ru', 'plans.cacheFloor', $json$"Ваш тариф хранит кэш контекста не меньше {minutes} минут."$json$::jsonb),
  ('ru', 'plans.sensitiveAlways', $json$"Ваш тариф также всегда исключает: {patterns}."$json$::jsonb),
  ('ru', 'admin.error.coreFeature', $json$"Это базовая функция: она включена во всех тарифах, и её нельзя выключить."$json$::jsonb),
  ('ru', 'site.admin.feature.core', $json$"Базовая функция: включена во всех тарифах, выключить нельзя"$json$::jsonb),
  ('ru', 'site.admin.feature.mode.off', $json$"Не входит"$json$::jsonb),
  ('ru', 'site.admin.feature.mode.optional', $json$"По выбору"$json$::jsonb),
  ('ru', 'site.admin.feature.mode.locked', $json$"Обязательно"$json$::jsonb),
  ('ru', 'site.admin.feature.defaultOn', $json$"Включено по умолчанию"$json$::jsonb),
  ('ru', 'site.admin.plan.limits', $json$"Ограничения"$json$::jsonb),
  ('ru', 'site.admin.plan.jevDailyLimit', $json$"Вызовов Jev в день"$json$::jsonb),
  ('ru', 'site.admin.plan.jevDailyLimitHint', $json$"Пусто — действует значение сервера по умолчанию."$json$::jsonb),
  ('ru', 'site.admin.plan.maxConcurrentTurns', $json$"Одновременных запросов"$json$::jsonb),
  ('ru', 'site.admin.plan.maxConcurrentTurnsHint', $json$"Сколько чатов могут выполнять запросы одновременно, от 1 до 8."$json$::jsonb),
  ('ja', 'feature.entryGate.title', $json$"入口ゲート"$json$::jsonb),
  ('ja', 'feature.entryGate.detail', $json$"Jev はエージェントが動く前にすべてのリクエストを確認し、足りない点を尋ねます。"$json$::jsonb),
  ('ja', 'feature.exitGate.title', $json$"出口ゲート"$json$::jsonb),
  ('ja', 'feature.exitGate.detail', $json$"Jev はすべての回答に含まれるコマンドとファイルをプロジェクトのルールと照らし合わせます。"$json$::jsonb),
  ('ja', 'feature.secretRedaction.title', $json$"シークレットの伏せ字化"$json$::jsonb),
  ('ja', 'feature.secretRedaction.detail', $json$"ファイルがモデルに届く前に、キー、トークン、パスワードが置き換えられます。"$json$::jsonb),
  ('ja', 'feature.sensitiveFiles.title', $json$"機密ファイル"$json$::jsonb),
  ('ja', 'feature.sensitiveFiles.detail', $json$".env、キー、証明書などのファイルはコンテキストに入りません。"$json$::jsonb),
  ('ja', 'feature.agentSessions.title', $json$"エージェントのセッション"$json$::jsonb),
  ('ja', 'feature.agentSessions.detail', $json$"各チャットはリクエストのたびにプロジェクトを読み直さず、エージェントのセッションを再開します。"$json$::jsonb),
  ('ja', 'feature.contextCache.title', $json$"コンテキストキャッシュ"$json$::jsonb),
  ('ja', 'feature.contextCache.detail', $json$"ファイルが変わらない限り、リクエスト用に組み立てたコンテキストを少なくとも 5 分間再利用します。"$json$::jsonb),
  ('ja', 'feature.answerRecall.title', $json$"以前の回答"$json$::jsonb),
  ('ja', 'feature.answerRecall.detail', $json$"プロジェクトの別のチャットで回答済みのリクエストとほぼ同じリクエストは、その回答から始めます。"$json$::jsonb),
  ('ja', 'feature.leanCode.title', $json$"最小限のコード"$json$::jsonb),
  ('ja', 'feature.leanCode.detail', $json$"ビルドモードでは、エージェントはタスクを解決する最小限のコードを書きます。"$json$::jsonb),
  ('ja', 'feature.symbolIndex.title', $json$"Claude 用のシンボルインデックス"$json$::jsonb),
  ('ja', 'feature.symbolIndex.detail', $json$"Claude Code はフォルダを走査する代わりに、JayV のシンボルインデックスに場所を尋ねます。"$json$::jsonb),
  ('ja', 'plans.required', $json$"ご利用のプランで必須"$json$::jsonb),
  ('ja', 'plans.cacheFloor', $json$"ご利用のプランでは、コンテキストキャッシュを少なくとも {minutes} 分間保持します。"$json$::jsonb),
  ('ja', 'plans.sensitiveAlways', $json$"ご利用のプランでは次も常に除外します: {patterns}。"$json$::jsonb),
  ('ja', 'admin.error.coreFeature', $json$"これはコア機能です。すべてのプランで有効のままで、オフにできません。"$json$::jsonb),
  ('ja', 'site.admin.feature.core', $json$"コア機能: すべてのプランで有効、オフにできません"$json$::jsonb),
  ('ja', 'site.admin.feature.mode.off', $json$"含まない"$json$::jsonb),
  ('ja', 'site.admin.feature.mode.optional', $json$"任意"$json$::jsonb),
  ('ja', 'site.admin.feature.mode.locked', $json$"必須"$json$::jsonb),
  ('ja', 'site.admin.feature.defaultOn', $json$"既定でオン"$json$::jsonb),
  ('ja', 'site.admin.plan.limits', $json$"上限"$json$::jsonb),
  ('ja', 'site.admin.plan.jevDailyLimit', $json$"1 日あたりの Jev 呼び出し"$json$::jsonb),
  ('ja', 'site.admin.plan.jevDailyLimitHint', $json$"空欄ならサーバーの既定値を使います。"$json$::jsonb),
  ('ja', 'site.admin.plan.maxConcurrentTurns', $json$"同時リクエスト数"$json$::jsonb),
  ('ja', 'site.admin.plan.maxConcurrentTurnsHint', $json$"同時にリクエストを実行できるチャット数（1〜8）。"$json$::jsonb),
  ('de', 'feature.entryGate.title', $json$"Eingangspforte"$json$::jsonb),
  ('de', 'feature.entryGate.detail', $json$"Jev prüft jede Anfrage, bevor ein Agent startet, und fragt nach dem, was fehlt."$json$::jsonb),
  ('de', 'feature.exitGate.title', $json$"Ausgangspforte"$json$::jsonb),
  ('de', 'feature.exitGate.detail', $json$"Jev prüft die Befehle und Dateien jeder Antwort anhand der Regeln des Projekts."$json$::jsonb),
  ('de', 'feature.secretRedaction.title', $json$"Schwärzen von Geheimnissen"$json$::jsonb),
  ('de', 'feature.secretRedaction.detail', $json$"Schlüssel, Tokens und Passwörter werden ersetzt, bevor eine Datei ein Modell erreicht."$json$::jsonb),
  ('de', 'feature.sensitiveFiles.title', $json$"Sensible Dateien"$json$::jsonb),
  ('de', 'feature.sensitiveFiles.detail', $json$"Dateien wie .env, Schlüssel und Zertifikate gelangen nie in den Kontext."$json$::jsonb),
  ('de', 'feature.agentSessions.title', $json$"Agentensitzungen"$json$::jsonb),
  ('de', 'feature.agentSessions.detail', $json$"Jeder Chat setzt die Sitzung seines Agenten fort, statt das Projekt bei jeder Anfrage neu zu lesen."$json$::jsonb),
  ('de', 'feature.contextCache.title', $json$"Kontext-Cache"$json$::jsonb),
  ('de', 'feature.contextCache.detail', $json$"Der für eine Anfrage erstellte Kontext wird mindestens fünf Minuten wiederverwendet, solange sich die Dateien nicht ändern."$json$::jsonb),
  ('de', 'feature.answerRecall.title', $json$"Frühere Antworten"$json$::jsonb),
  ('de', 'feature.answerRecall.detail', $json$"Eine Anfrage, die fast gleich einer bereits in einem anderen Chat des Projekts beantworteten ist, startet von dieser Antwort."$json$::jsonb),
  ('de', 'feature.leanCode.title', $json$"Schlanker Code"$json$::jsonb),
  ('de', 'feature.leanCode.detail', $json$"Im Build-Modus schreibt der Agent so wenig Code wie nötig, um die Aufgabe zu lösen."$json$::jsonb),
  ('de', 'feature.symbolIndex.title', $json$"Symbolindex für Claude"$json$::jsonb),
  ('de', 'feature.symbolIndex.detail', $json$"Claude Code fragt den Symbolindex von JayV, wo etwas liegt, statt den Ordner zu durchsuchen."$json$::jsonb),
  ('de', 'plans.required', $json$"In deinem Tarif verpflichtend"$json$::jsonb),
  ('de', 'plans.cacheFloor', $json$"Dein Tarif behält den Kontext-Cache mindestens {minutes} Minuten."$json$::jsonb),
  ('de', 'plans.sensitiveAlways', $json$"Dein Tarif schließt diese ebenfalls immer aus: {patterns}."$json$::jsonb),
  ('de', 'admin.error.coreFeature', $json$"Das ist eine Kernfunktion: Sie bleibt in jedem Tarif aktiv und lässt sich nicht abschalten."$json$::jsonb),
  ('de', 'site.admin.feature.core', $json$"Kernfunktion: in jedem Tarif aktiv, nicht abschaltbar"$json$::jsonb),
  ('de', 'site.admin.feature.mode.off', $json$"Nicht enthalten"$json$::jsonb),
  ('de', 'site.admin.feature.mode.optional', $json$"Optional"$json$::jsonb),
  ('de', 'site.admin.feature.mode.locked', $json$"Verpflichtend"$json$::jsonb),
  ('de', 'site.admin.feature.defaultOn', $json$"Standardmäßig an"$json$::jsonb),
  ('de', 'site.admin.plan.limits', $json$"Grenzen"$json$::jsonb),
  ('de', 'site.admin.plan.jevDailyLimit', $json$"Jev-Aufrufe pro Tag"$json$::jsonb),
  ('de', 'site.admin.plan.jevDailyLimitHint', $json$"Leer bedeutet: Standardwert des Servers."$json$::jsonb),
  ('de', 'site.admin.plan.maxConcurrentTurns', $json$"Gleichzeitige Anfragen"$json$::jsonb),
  ('de', 'site.admin.plan.maxConcurrentTurnsHint', $json$"Wie viele Chats gleichzeitig Anfragen ausführen können, von 1 bis 8."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
