-- v0.58.0: o build recebe o plano inteiro, "não funcionou" muda a nova tentativa,
-- busca em português e espanhol acha código em inglês, título sem premium request
-- e economia de bloqueio descontada no reenvio. Só textos.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'whatsNew.item.planToBuild.title', $json$"O build recebe o plano inteiro"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planToBuild.detail', $json$"Quando você planeja num chat e depois pede para implementar, o agente que constrói agora recebe o plano completo. Antes, uma sessão nova via só o começo dele, porque as respostas antigas vão encurtadas no histórico."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.betterRetry.title', $json$"\"Não funcionou\" não repete mais a mesma tentativa"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.betterRetry.detail', $json$"Uma reclamação sobre a última resposta agora pede ao agente que confira o que a mudança anterior fez e reproduza a falha antes de mudar de novo. Da segunda reclamação seguida em diante, ele também pensa um degrau a mais."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.smallCuts.title', $json$"Busca no seu idioma, títulos mais baratos e economia honesta"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.smallCuts.detail', $json$"Pedidos escritos em português ou espanhol agora acham código escrito em inglês, porque as palavras comuns de programação também são buscadas em inglês. Com só o Copilot configurado, o chat fica com o título local em vez de gastar uma premium request com ele. E um pedido barrado que você reenvia em até 15 minutos não conta mais como tokens poupados."$json$::jsonb),
  ('en', 'whatsNew.item.planToBuild.title', $json$"The build gets the whole plan"$json$::jsonb),
  ('en', 'whatsNew.item.planToBuild.detail', $json$"When you plan in a chat and then ask to implement, the agent that builds now receives the plan in full. Before, a new session only saw the start of it, because old answers are shortened in the history."$json$::jsonb),
  ('en', 'whatsNew.item.betterRetry.title', $json$"\"It didn't work\" no longer retries the same way"$json$::jsonb),
  ('en', 'whatsNew.item.betterRetry.detail', $json$"A complaint about the last answer now tells the agent to check what its previous change did and reproduce the failure before changing anything again. From the second complaint in a row, it also thinks one step harder."$json$::jsonb),
  ('en', 'whatsNew.item.smallCuts.title', $json$"Searches in your language, cheaper titles and honest savings"$json$::jsonb),
  ('en', 'whatsNew.item.smallCuts.detail', $json$"Requests written in Portuguese or Spanish now find code written in English, because common programming words are searched in English too. With only Copilot set up, chats keep the local title instead of spending a premium request on it. And a blocked request you resend within 15 minutes no longer counts as tokens saved."$json$::jsonb),
  ('es', 'whatsNew.item.planToBuild.title', $json$"El build recibe el plan completo"$json$::jsonb),
  ('es', 'whatsNew.item.planToBuild.detail', $json$"Cuando planificas en un chat y luego pides implementar, el agente que construye ahora recibe el plan completo. Antes, una sesión nueva solo veía el comienzo, porque las respuestas antiguas se acortan en el historial."$json$::jsonb),
  ('es', 'whatsNew.item.betterRetry.title', $json$"\"No funcionó\" ya no repite el mismo intento"$json$::jsonb),
  ('es', 'whatsNew.item.betterRetry.detail', $json$"Una queja sobre la última respuesta ahora pide al agente que revise lo que hizo su cambio anterior y reproduzca el fallo antes de volver a cambiar algo. A partir de la segunda queja seguida, también piensa un nivel más."$json$::jsonb),
  ('es', 'whatsNew.item.smallCuts.title', $json$"Búsquedas en tu idioma, títulos más baratos y ahorro honesto"$json$::jsonb),
  ('es', 'whatsNew.item.smallCuts.detail', $json$"Las solicitudes escritas en portugués o español ahora encuentran código escrito en inglés, porque las palabras comunes de programación también se buscan en inglés. Con solo Copilot configurado, el chat mantiene el título local en lugar de gastar una premium request en él. Y una solicitud bloqueada que reenvías en 15 minutos ya no cuenta como tokens ahorrados."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planToBuild.title', $json$"构建会收到完整的计划"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planToBuild.detail', $json$"当你在聊天中先规划、再要求实现时，负责构建的智能体现在会收到完整的计划。以前新会话只能看到计划的开头，因为历史中的旧回答会被截短。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.betterRetry.title', $json$"“没成功”不再按同样的方式重试"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.betterRetry.detail', $json$"对上一个回答的抱怨现在会让智能体先检查之前的改动做了什么、复现故障，然后再改动。从连续第二次抱怨开始，它还会多思考一个等级。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.smallCuts.title', $json$"用你的语言搜索、更省钱的标题和如实的节省统计"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.smallCuts.detail', $json$"用葡萄牙语或西班牙语写的请求现在也能找到用英语写的代码，因为常见的编程词汇也会按英语搜索。只配置了 Copilot 时，聊天会保留本地标题，而不是为它花掉一次 premium request。被拦下的请求如果在 15 分钟内重新发送，不再计为节省的 token。"$json$::jsonb),
  ('hi', 'whatsNew.item.planToBuild.title', $json$"बिल्ड को पूरी योजना मिलती है"$json$::jsonb),
  ('hi', 'whatsNew.item.planToBuild.detail', $json$"जब आप किसी चैट में योजना बनाते हैं और फिर लागू करने को कहते हैं, तो बनाने वाले एजेंट को अब पूरी योजना मिलती है। पहले नया सत्र केवल उसकी शुरुआत देखता था, क्योंकि इतिहास में पुराने जवाब छोटे कर दिए जाते हैं।"$json$::jsonb),
  ('hi', 'whatsNew.item.betterRetry.title', $json$"\"काम नहीं किया\" अब उसी तरह दोबारा कोशिश नहीं करता"$json$::jsonb),
  ('hi', 'whatsNew.item.betterRetry.detail', $json$"पिछले जवाब पर शिकायत अब एजेंट से कहती है कि दोबारा कुछ बदलने से पहले जाँचे कि पिछले बदलाव ने क्या किया और गड़बड़ी को दोहराए। लगातार दूसरी शिकायत से वह एक स्तर ज़्यादा सोचता भी है।"$json$::jsonb),
  ('hi', 'whatsNew.item.smallCuts.title', $json$"आपकी भाषा में खोज, सस्ते शीर्षक और ईमानदार बचत"$json$::jsonb),
  ('hi', 'whatsNew.item.smallCuts.detail', $json$"पुर्तगाली या स्पैनिश में लिखे अनुरोध अब अंग्रेज़ी में लिखा कोड ढूँढ लेते हैं, क्योंकि प्रोग्रामिंग के आम शब्द अंग्रेज़ी में भी खोजे जाते हैं। सिर्फ़ Copilot सेट होने पर चैट का स्थानीय शीर्षक रहता है, उस पर premium request ख़र्च नहीं होती। और रोका गया अनुरोध 15 मिनट के भीतर दोबारा भेजने पर अब बचाए गए टोकन में नहीं गिना जाता।"$json$::jsonb),
  ('ar', 'whatsNew.item.planToBuild.title', $json$"يتلقى البناء الخطة كاملة"$json$::jsonb),
  ('ar', 'whatsNew.item.planToBuild.detail', $json$"عندما تخطط في محادثة ثم تطلب التنفيذ، يتلقى الوكيل الذي يبني الآن الخطة كاملة. في السابق كانت الجلسة الجديدة ترى بدايتها فقط، لأن الإجابات القديمة تُختصر في السجل."$json$::jsonb),
  ('ar', 'whatsNew.item.betterRetry.title', $json$"\"لم ينجح\" لم يعد يكرر المحاولة نفسها"$json$::jsonb),
  ('ar', 'whatsNew.item.betterRetry.detail', $json$"الشكوى من الإجابة الأخيرة تطلب الآن من الوكيل أن يتحقق مما فعله تغييره السابق ويعيد إنتاج الخلل قبل تغيير أي شيء مرة أخرى. ومن الشكوى الثانية المتتالية، يفكر أيضًا بدرجة أعلى."$json$::jsonb),
  ('ar', 'whatsNew.item.smallCuts.title', $json$"بحث بلغتك، وعناوين أرخص، وتوفير صادق"$json$::jsonb),
  ('ar', 'whatsNew.item.smallCuts.detail', $json$"الطلبات المكتوبة بالبرتغالية أو الإسبانية تجد الآن الشيفرة المكتوبة بالإنجليزية، لأن كلمات البرمجة الشائعة يُبحث عنها بالإنجليزية أيضًا. عند إعداد Copilot وحده، تحتفظ المحادثة بالعنوان المحلي بدل إنفاق premium request عليه. والطلب الموقوف الذي تعيد إرساله خلال 15 دقيقة لم يعد يُحسب ضمن الرموز الموفّرة."$json$::jsonb),
  ('fr', 'whatsNew.item.planToBuild.title', $json$"Le build reçoit le plan entier"$json$::jsonb),
  ('fr', 'whatsNew.item.planToBuild.detail', $json$"Quand vous planifiez dans un chat puis demandez l’implémentation, l’agent qui construit reçoit désormais le plan complet. Avant, une nouvelle session n’en voyait que le début, car les anciennes réponses sont raccourcies dans l’historique."$json$::jsonb),
  ('fr', 'whatsNew.item.betterRetry.title', $json$"« Ça n’a pas marché » ne relance plus la même tentative"$json$::jsonb),
  ('fr', 'whatsNew.item.betterRetry.detail', $json$"Une plainte sur la dernière réponse demande désormais à l’agent de vérifier ce qu’a fait son changement précédent et de reproduire l’échec avant de modifier quoi que ce soit. À partir de la deuxième plainte d’affilée, il réfléchit aussi d’un cran de plus."$json$::jsonb),
  ('fr', 'whatsNew.item.smallCuts.title', $json$"Recherche dans votre langue, titres moins chers et économies honnêtes"$json$::jsonb),
  ('fr', 'whatsNew.item.smallCuts.detail', $json$"Les demandes écrites en portugais ou en espagnol trouvent désormais du code écrit en anglais, car les mots courants de programmation sont aussi cherchés en anglais. Avec seulement Copilot configuré, le chat garde le titre local au lieu de dépenser une premium request. Et une demande bloquée que vous renvoyez dans les 15 minutes ne compte plus comme des tokens économisés."$json$::jsonb),
  ('ru', 'whatsNew.item.planToBuild.title', $json$"Сборка получает план целиком"$json$::jsonb),
  ('ru', 'whatsNew.item.planToBuild.detail', $json$"Когда вы планируете в чате, а потом просите реализовать, агент, который собирает, теперь получает план целиком. Раньше новая сессия видела только его начало, потому что старые ответы в истории сокращаются."$json$::jsonb),
  ('ru', 'whatsNew.item.betterRetry.title', $json$"«Не сработало» больше не повторяет ту же попытку"$json$::jsonb),
  ('ru', 'whatsNew.item.betterRetry.detail', $json$"Жалоба на последний ответ теперь просит агента проверить, что сделало предыдущее изменение, и воспроизвести сбой, прежде чем снова что-то менять. Со второй жалобы подряд он ещё и думает на ступень больше."$json$::jsonb),
  ('ru', 'whatsNew.item.smallCuts.title', $json$"Поиск на вашем языке, дешёвые названия и честная экономия"$json$::jsonb),
  ('ru', 'whatsNew.item.smallCuts.detail', $json$"Запросы на португальском или испанском теперь находят код, написанный на английском, потому что распространённые слова программирования ищутся и по-английски. Если настроен только Copilot, чат сохраняет локальное название вместо траты premium request. А заблокированный запрос, отправленный повторно в течение 15 минут, больше не считается сэкономленными токенами."$json$::jsonb),
  ('ja', 'whatsNew.item.planToBuild.title', $json$"ビルドに計画の全文が渡ります"$json$::jsonb),
  ('ja', 'whatsNew.item.planToBuild.detail', $json$"チャットで計画してから実装を頼むと、ビルドするエージェントに計画の全文が渡るようになりました。以前は履歴の古い回答が短縮されるため、新しいセッションは計画の冒頭しか見られませんでした。"$json$::jsonb),
  ('ja', 'whatsNew.item.betterRetry.title', $json$"「うまくいかない」で同じやり方を繰り返さなくなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.betterRetry.detail', $json$"直前の回答への不満を伝えると、エージェントは何かを変える前に、前回の変更が何をしたかを確認し、失敗を再現するよう指示されます。2回続けて不満が出たら、推論も一段階強めます。"$json$::jsonb),
  ('ja', 'whatsNew.item.smallCuts.title', $json$"あなたの言語での検索、安いタイトル付け、正直な節約表示"$json$::jsonb),
  ('ja', 'whatsNew.item.smallCuts.detail', $json$"ポルトガル語やスペイン語で書いたリクエストでも、英語で書かれたコードが見つかるようになりました。一般的なプログラミング用語を英語でも検索するためです。Copilot だけを設定している場合、チャットのタイトルに premium request を使わず、ローカルのタイトルのままにします。また、ブロックされたリクエストを15分以内に再送した場合は、節約したトークンとして数えなくなりました。"$json$::jsonb),
  ('de', 'whatsNew.item.planToBuild.title', $json$"Der Build bekommt den ganzen Plan"$json$::jsonb),
  ('de', 'whatsNew.item.planToBuild.detail', $json$"Wenn du in einem Chat planst und dann die Umsetzung verlangst, bekommt der bauende Agent jetzt den vollständigen Plan. Vorher sah eine neue Sitzung nur dessen Anfang, weil alte Antworten im Verlauf gekürzt werden."$json$::jsonb),
  ('de', 'whatsNew.item.betterRetry.title', $json$"„Hat nicht funktioniert“ wiederholt nicht mehr denselben Versuch"$json$::jsonb),
  ('de', 'whatsNew.item.betterRetry.detail', $json$"Eine Beschwerde über die letzte Antwort fordert den Agenten jetzt auf, zu prüfen, was seine vorige Änderung getan hat, und den Fehler nachzustellen, bevor er erneut etwas ändert. Ab der zweiten Beschwerde in Folge denkt er außerdem eine Stufe gründlicher."$json$::jsonb),
  ('de', 'whatsNew.item.smallCuts.title', $json$"Suche in deiner Sprache, günstigere Titel und ehrliche Ersparnis"$json$::jsonb),
  ('de', 'whatsNew.item.smallCuts.detail', $json$"Anfragen auf Portugiesisch oder Spanisch finden jetzt auch auf Englisch geschriebenen Code, weil gängige Programmierwörter zusätzlich auf Englisch gesucht werden. Ist nur Copilot eingerichtet, behält der Chat den lokalen Titel, statt dafür einen Premium Request auszugeben. Und eine blockierte Anfrage, die du innerhalb von 15 Minuten erneut sendest, zählt nicht mehr als eingesparte Tokens."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
