-- App 0.88.0: carregamento da troca de ambiente e convites pendentes na aba Membros, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'org.pending.title', $json$"Aguardando resposta"$json$::jsonb),
  ('en', 'org.pending.title', $json$"Waiting for an answer"$json$::jsonb),
  ('es', 'org.pending.title', $json$"Esperando respuesta"$json$::jsonb),
  ('fr', 'org.pending.title', $json$"En attente de réponse"$json$::jsonb),
  ('de', 'org.pending.title', $json$"Wartet auf Antwort"$json$::jsonb),
  ('ru', 'org.pending.title', $json$"Ожидают ответа"$json$::jsonb),
  ('zh-CN', 'org.pending.title', $json$"等待回复"$json$::jsonb),
  ('ja', 'org.pending.title', $json$"返信待ち"$json$::jsonb),
  ('hi', 'org.pending.title', $json$"उत्तर की प्रतीक्षा में"$json$::jsonb),
  ('ar', 'org.pending.title', $json$"بانتظار الرد"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.environmentSwitchLoading.title', $json$"Trocar de ambiente mostra um carregamento"$json$::jsonb),
  ('en', 'whatsNew.item.environmentSwitchLoading.title', $json$"Switching environment shows a loading screen"$json$::jsonb),
  ('es', 'whatsNew.item.environmentSwitchLoading.title', $json$"Cambiar de entorno muestra una pantalla de carga"$json$::jsonb),
  ('fr', 'whatsNew.item.environmentSwitchLoading.title', $json$"Changer d'environnement affiche un écran de chargement"$json$::jsonb),
  ('de', 'whatsNew.item.environmentSwitchLoading.title', $json$"Der Umgebungswechsel zeigt einen Ladebildschirm"$json$::jsonb),
  ('ru', 'whatsNew.item.environmentSwitchLoading.title', $json$"Переключение среды показывает экран загрузки"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.environmentSwitchLoading.title', $json$"切换环境时显示加载界面"$json$::jsonb),
  ('ja', 'whatsNew.item.environmentSwitchLoading.title', $json$"環境の切り替え中に読み込み画面が表示されます"$json$::jsonb),
  ('hi', 'whatsNew.item.environmentSwitchLoading.title', $json$"परिवेश बदलते समय लोडिंग स्क्रीन दिखती है"$json$::jsonb),
  ('ar', 'whatsNew.item.environmentSwitchLoading.title', $json$"تبديل البيئة يعرض شاشة تحميل"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.environmentSwitchLoading.detail', $json$"Ao trocar de ambiente, o JayV não procura mais atualização: mostra um carregamento até os dados do ambiente novo chegarem."$json$::jsonb),
  ('en', 'whatsNew.item.environmentSwitchLoading.detail', $json$"When you switch environment, JayV no longer looks for updates: it shows a loading screen until the new environment's data arrives."$json$::jsonb),
  ('es', 'whatsNew.item.environmentSwitchLoading.detail', $json$"Al cambiar de entorno, JayV ya no busca actualizaciones: muestra una pantalla de carga hasta que llegan los datos del nuevo entorno."$json$::jsonb),
  ('fr', 'whatsNew.item.environmentSwitchLoading.detail', $json$"En changeant d'environnement, JayV ne cherche plus de mise à jour : il affiche un écran de chargement jusqu'à l'arrivée des données du nouvel environnement."$json$::jsonb),
  ('de', 'whatsNew.item.environmentSwitchLoading.detail', $json$"Beim Umgebungswechsel sucht JayV nicht mehr nach Updates, sondern zeigt einen Ladebildschirm, bis die Daten der neuen Umgebung da sind."$json$::jsonb),
  ('ru', 'whatsNew.item.environmentSwitchLoading.detail', $json$"При переключении среды JayV больше не ищет обновления: показывается экран загрузки, пока не придут данные новой среды."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.environmentSwitchLoading.detail', $json$"切换环境时，JayV 不再检查更新，而是显示加载界面，直到新环境的数据到达。"$json$::jsonb),
  ('ja', 'whatsNew.item.environmentSwitchLoading.detail', $json$"環境を切り替えても JayV は更新を確認せず、新しい環境のデータが届くまで読み込み画面を表示します。"$json$::jsonb),
  ('hi', 'whatsNew.item.environmentSwitchLoading.detail', $json$"परिवेश बदलने पर JayV अब अपडेट नहीं खोजता: नए परिवेश का डेटा आने तक लोडिंग स्क्रीन दिखाता है।"$json$::jsonb),
  ('ar', 'whatsNew.item.environmentSwitchLoading.detail', $json$"عند تبديل البيئة لم يعد JayV يبحث عن تحديثات، بل يعرض شاشة تحميل حتى تصل بيانات البيئة الجديدة."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgPendingInvites.title', $json$"Convites pendentes na aba Membros"$json$::jsonb),
  ('en', 'whatsNew.item.orgPendingInvites.title', $json$"Pending invites in the Members tab"$json$::jsonb),
  ('es', 'whatsNew.item.orgPendingInvites.title', $json$"Invitaciones pendientes en la pestaña Miembros"$json$::jsonb),
  ('fr', 'whatsNew.item.orgPendingInvites.title', $json$"Invitations en attente dans l'onglet Membres"$json$::jsonb),
  ('de', 'whatsNew.item.orgPendingInvites.title', $json$"Ausstehende Einladungen im Tab „Mitglieder“"$json$::jsonb),
  ('ru', 'whatsNew.item.orgPendingInvites.title', $json$"Ожидающие приглашения на вкладке «Участники»"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgPendingInvites.title', $json$"成员标签页显示待处理邀请"$json$::jsonb),
  ('ja', 'whatsNew.item.orgPendingInvites.title', $json$"メンバータブに保留中の招待を表示"$json$::jsonb),
  ('hi', 'whatsNew.item.orgPendingInvites.title', $json$"सदस्य टैब में लंबित आमंत्रण"$json$::jsonb),
  ('ar', 'whatsNew.item.orgPendingInvites.title', $json$"الدعوات المعلّقة في تبويب الأعضاء"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgPendingInvites.detail', $json$"Quem gere a organização vê no app, abaixo dos membros, os convites que ainda esperam resposta. E o site passou a listar os membros (com o owner) ao lado dos convites."$json$::jsonb),
  ('en', 'whatsNew.item.orgPendingInvites.detail', $json$"Owners and maintainers now see, below the members, the invites still waiting for an answer. The site also lists the members (owner included) next to the invites."$json$::jsonb),
  ('es', 'whatsNew.item.orgPendingInvites.detail', $json$"Quien gestiona la organización ve en la app, bajo los miembros, las invitaciones que aún esperan respuesta. Y el sitio ahora lista los miembros (con el owner) junto a las invitaciones."$json$::jsonb),
  ('fr', 'whatsNew.item.orgPendingInvites.detail', $json$"Les personnes qui gèrent l'organisation voient dans l'application, sous les membres, les invitations encore en attente. Le site liste aussi les membres (owner compris) à côté des invitations."$json$::jsonb),
  ('de', 'whatsNew.item.orgPendingInvites.detail', $json$"Wer die Organisation verwaltet, sieht in der App unter den Mitgliedern die Einladungen, die noch auf Antwort warten. Die Website listet jetzt auch die Mitglieder (samt Owner) neben den Einladungen."$json$::jsonb),
  ('ru', 'whatsNew.item.orgPendingInvites.detail', $json$"Те, кто управляет организацией, видят в приложении под участниками приглашения, ожидающие ответа. А сайт теперь показывает участников (включая owner) рядом с приглашениями."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgPendingInvites.detail', $json$"管理组织的人现在可以在应用中成员下方看到仍在等待回复的邀请；网站也在邀请旁列出成员（包括 owner）。"$json$::jsonb),
  ('ja', 'whatsNew.item.orgPendingInvites.detail', $json$"組織を管理する人は、アプリのメンバー一覧の下に、返信待ちの招待を確認できます。サイトでも、招待の横にメンバー（owner を含む）が表示されます。"$json$::jsonb),
  ('hi', 'whatsNew.item.orgPendingInvites.detail', $json$"संगठन संभालने वाले अब ऐप में सदस्यों के नीचे वे आमंत्रण देखते हैं जिनका उत्तर बाकी है। साइट भी आमंत्रणों के साथ सदस्यों (owner सहित) की सूची दिखाती है।"$json$::jsonb),
  ('ar', 'whatsNew.item.orgPendingInvites.detail', $json$"يرى من يدير المؤسسة في التطبيق، أسفل الأعضاء، الدعوات التي لا تزال تنتظر الرد. كما صار الموقع يعرض الأعضاء (بمن فيهم owner) بجانب الدعوات."$json$::jsonb),
  ('pt-BR', 'docs.organizations.usage', $json$"Crie uma organização, convide membros e associe os repositórios dela no painel do site do JayV. No app, Ctrl+2 (⌘2 no Mac) abre as suas organizações e os repositórios delas. Na aba Membros, quem gere vê também os convites que ainda esperam resposta."$json$::jsonb),
  ('en', 'docs.organizations.usage', $json$"Create an organization, invite members and link its repositories on the JayV site dashboard. In the app, Ctrl+2 (⌘2 on Mac) opens your organizations and their repositories. In the Members tab, owners and maintainers also see the invites still waiting for an answer."$json$::jsonb),
  ('es', 'docs.organizations.usage', $json$"Crea una organización, invita a miembros y asocia sus repositorios en el panel del sitio de JayV. En la app, Ctrl+2 (⌘2 en Mac) abre tus organizaciones y sus repositorios. En la pestaña Miembros, quien gestiona también ve las invitaciones que aún esperan respuesta."$json$::jsonb),
  ('fr', 'docs.organizations.usage', $json$"Créez une organisation, invitez des membres et associez ses dépôts dans le tableau de bord du site de JayV. Dans l'application, Ctrl+2 (⌘2 sur Mac) ouvre vos organisations et leurs dépôts. Dans l'onglet Membres, les gestionnaires voient aussi les invitations encore en attente."$json$::jsonb),
  ('de', 'docs.organizations.usage', $json$"Erstelle eine Organisation, lade Mitglieder ein und verknüpfe ihre Repositorys im Dashboard der JayV-Website. In der App öffnet Strg+2 (⌘2 auf dem Mac) deine Organisationen und ihre Repositorys. Im Tab „Mitglieder“ sehen Verwaltende außerdem die Einladungen, die noch auf Antwort warten."$json$::jsonb),
  ('ru', 'docs.organizations.usage', $json$"Создайте организацию, пригласите участников и привяжите её репозитории в панели сайта JayV. В приложении Ctrl+2 (⌘2 на Mac) открывает ваши организации и их репозитории. На вкладке «Участники» управляющие также видят приглашения, ожидающие ответа."$json$::jsonb),
  ('zh-CN', 'docs.organizations.usage', $json$"在 JayV 网站的控制台中创建组织、邀请成员并关联其仓库。在应用中，Ctrl+2（Mac 上为 ⌘2）打开你的组织及其仓库。在“成员”标签页中，管理者还能看到仍在等待回复的邀请。"$json$::jsonb),
  ('ja', 'docs.organizations.usage', $json$"JayV サイトのダッシュボードで組織を作成し、メンバーを招待して、リポジトリを関連付けます。アプリでは Ctrl+2（Mac では ⌘2）で組織とそのリポジトリを開けます。「メンバー」タブでは、管理者は返信待ちの招待も確認できます。"$json$::jsonb),
  ('hi', 'docs.organizations.usage', $json$"JayV साइट के डैशबोर्ड में संगठन बनाएँ, सदस्यों को आमंत्रित करें और उसकी रिपॉज़िटरी जोड़ें। ऐप में Ctrl+2 (Mac पर ⌘2) आपके संगठन और उनकी रिपॉज़िटरी खोलता है। सदस्य टैब में, प्रबंधक उन आमंत्रणों को भी देखते हैं जिनका उत्तर बाकी है।"$json$::jsonb),
  ('ar', 'docs.organizations.usage', $json$"أنشئ مؤسسة وادعُ الأعضاء واربط مستودعاتها من لوحة تحكم موقع JayV. في التطبيق، يفتح Ctrl+2 (⌘2 على Mac) مؤسساتك ومستودعاتها. في تبويب الأعضاء، يرى المديرون أيضًا الدعوات التي لا تزال تنتظر الرد."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
