-- App 0.93.0: as integrações com LLM (Claude Code, Codex, Copilot, Cursor,
-- Kilo Code, OpenRouter e LiteLLM) viram mods, com a aba Configuração › Mods
-- e o Criar mod, e os chats gerais da organização ganham uma coluna própria
-- ao lado do menu lateral. Os textos novos da tela e dos erros do núcleo, as
-- Novidades e o manual (a página nova `llmMods` e o `orgChat`, que mudou de
-- uso), nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'settings.tab.mods', $json$"Mods"$json$::jsonb),
  ('en', 'settings.tab.mods', $json$"Mods"$json$::jsonb),
  ('es', 'settings.tab.mods', $json$"Mods"$json$::jsonb),
  ('zh-CN', 'settings.tab.mods', $json$"模组"$json$::jsonb),
  ('hi', 'settings.tab.mods', $json$"मॉड"$json$::jsonb),
  ('ar', 'settings.tab.mods', $json$"الإضافات"$json$::jsonb),
  ('fr', 'settings.tab.mods', $json$"Mods"$json$::jsonb),
  ('ru', 'settings.tab.mods', $json$"Моды"$json$::jsonb),
  ('ja', 'settings.tab.mods', $json$"Mod"$json$::jsonb),
  ('de', 'settings.tab.mods', $json$"Mods"$json$::jsonb),
  ('pt-BR', 'mods.title', $json$"Mods"$json$::jsonb),
  ('en', 'mods.title', $json$"Mods"$json$::jsonb),
  ('es', 'mods.title', $json$"Mods"$json$::jsonb),
  ('zh-CN', 'mods.title', $json$"模组"$json$::jsonb),
  ('hi', 'mods.title', $json$"मॉड"$json$::jsonb),
  ('ar', 'mods.title', $json$"الإضافات"$json$::jsonb),
  ('fr', 'mods.title', $json$"Mods"$json$::jsonb),
  ('ru', 'mods.title', $json$"Моды"$json$::jsonb),
  ('ja', 'mods.title', $json$"Mod"$json$::jsonb),
  ('de', 'mods.title', $json$"Mods"$json$::jsonb),
  ('pt-BR', 'mods.description', $json$"Toda integração com modelos de LLM é um mod. Os que vêm com o app e os que você cria aparecem juntos, e cada um tem a sua aba, com a conexão, o comportamento e os modelos."$json$::jsonb),
  ('en', 'mods.description', $json$"Every integration with LLM models is a mod. The built-in ones and the ones you create are listed together, and each has its own tab with its connection, behavior and models."$json$::jsonb),
  ('es', 'mods.description', $json$"Toda integración con modelos de LLM es un mod. Los que vienen con la app y los que creas aparecen juntos, y cada uno tiene su pestaña, con la conexión, el comportamiento y los modelos."$json$::jsonb),
  ('zh-CN', 'mods.description', $json$"与 LLM 模型的每一项集成都是一个模组。应用自带的和你创建的列在一起，每个都有自己的标签页，包含连接、行为和模型。"$json$::jsonb),
  ('hi', 'mods.description', $json$"LLM मॉडलों से हर इंटीग्रेशन एक मॉड है। ऐप के साथ आने वाले और आपके बनाए मॉड साथ में दिखते हैं, और हर एक का अपना टैब है, जिसमें कनेक्शन, व्यवहार और मॉडल हैं।"$json$::jsonb),
  ('ar', 'mods.description', $json$"كل تكامل مع نماذج LLM هو إضافة. تظهر الإضافات المضمّنة في التطبيق والتي تنشئها معًا، ولكل منها تبويب خاص يضم الاتصال والسلوك والنماذج."$json$::jsonb),
  ('fr', 'mods.description', $json$"Chaque intégration avec des modèles de LLM est un mod. Ceux fournis avec l’app et ceux que vous créez apparaissent ensemble, et chacun a son onglet, avec la connexion, le comportement et les modèles."$json$::jsonb),
  ('ru', 'mods.description', $json$"Каждая интеграция с моделями LLM — это мод. Встроенные и созданные вами моды показаны вместе, и у каждого своя вкладка с подключением, поведением и моделями."$json$::jsonb),
  ('ja', 'mods.description', $json$"LLM モデルとの連携はすべて Mod です。アプリに組み込まれたものと自分で作成したものが一緒に並び、それぞれに接続・動作・モデルをまとめたタブがあります。"$json$::jsonb),
  ('de', 'mods.description', $json$"Jede Anbindung an LLM-Modelle ist ein Mod. Die mitgelieferten und die selbst erstellten stehen zusammen in der Liste, und jeder hat seinen eigenen Tab mit Verbindung, Verhalten und Modellen."$json$::jsonb),
  ('pt-BR', 'mods.create', $json$"Criar mod"$json$::jsonb),
  ('en', 'mods.create', $json$"Create mod"$json$::jsonb),
  ('es', 'mods.create', $json$"Crear mod"$json$::jsonb),
  ('zh-CN', 'mods.create', $json$"创建模组"$json$::jsonb),
  ('hi', 'mods.create', $json$"मॉड बनाएँ"$json$::jsonb),
  ('ar', 'mods.create', $json$"إنشاء إضافة"$json$::jsonb),
  ('fr', 'mods.create', $json$"Créer un mod"$json$::jsonb),
  ('ru', 'mods.create', $json$"Создать мод"$json$::jsonb),
  ('ja', 'mods.create', $json$"Mod を作成"$json$::jsonb),
  ('de', 'mods.create', $json$"Mod erstellen"$json$::jsonb),
  ('pt-BR', 'mods.create.title', $json$"Criar um mod"$json$::jsonb),
  ('en', 'mods.create.title', $json$"Create a mod"$json$::jsonb),
  ('es', 'mods.create.title', $json$"Crear un mod"$json$::jsonb),
  ('zh-CN', 'mods.create.title', $json$"创建模组"$json$::jsonb),
  ('hi', 'mods.create.title', $json$"मॉड बनाएँ"$json$::jsonb),
  ('ar', 'mods.create.title', $json$"إنشاء إضافة"$json$::jsonb),
  ('fr', 'mods.create.title', $json$"Créer un mod"$json$::jsonb),
  ('ru', 'mods.create.title', $json$"Создание мода"$json$::jsonb),
  ('ja', 'mods.create.title', $json$"Mod の作成"$json$::jsonb),
  ('de', 'mods.create.title', $json$"Einen Mod erstellen"$json$::jsonb),
  ('pt-BR', 'mods.create.description', $json$"Ligue outro LLM ao Jev: um programa de linha de comando neste computador ou um endereço de API compatível com OpenAI ou Anthropic. O mod entra na configuração já ligado, com a sua aba, e passa a valer quando você salvar."$json$::jsonb),
  ('en', 'mods.create.description', $json$"Connect another LLM to Jev: a command-line program on this computer or an API address compatible with OpenAI or Anthropic. The mod joins the settings turned on, with its own tab, and takes effect when you save."$json$::jsonb),
  ('es', 'mods.create.description', $json$"Conecta otro LLM a Jev: un programa de línea de comandos en este equipo o una dirección de API compatible con OpenAI o Anthropic. El mod entra en la configuración ya activado, con su pestaña, y se aplica cuando guardas."$json$::jsonb),
  ('zh-CN', 'mods.create.description', $json$"为 Jev 接入另一个 LLM：本机上的命令行程序，或兼容 OpenAI 或 Anthropic 的 API 地址。模组加入设置时即为开启状态，带有自己的标签页，保存后生效。"$json$::jsonb),
  ('hi', 'mods.create.description', $json$"Jev से कोई दूसरा LLM जोड़ें: इस कंप्यूटर पर कोई कमांड-लाइन प्रोग्राम या OpenAI या Anthropic के साथ संगत API पता। मॉड चालू अवस्था में, अपने टैब के साथ, सेटिंग्स में जुड़ता है और सहेजने पर लागू होता है।"$json$::jsonb),
  ('ar', 'mods.create.description', $json$"اربط نموذج LLM آخر بـ Jev: برنامج سطر أوامر على هذا الجهاز أو عنوان API متوافق مع OpenAI أو Anthropic. تنضم الإضافة إلى الإعدادات مفعّلة، مع تبويبها الخاص، وتسري عند الحفظ."$json$::jsonb),
  ('fr', 'mods.create.description', $json$"Connectez un autre LLM à Jev : un programme en ligne de commande sur cet ordinateur ou une adresse d’API compatible avec OpenAI ou Anthropic. Le mod entre dans la configuration déjà activé, avec son onglet, et s’applique quand vous enregistrez."$json$::jsonb),
  ('ru', 'mods.create.description', $json$"Подключите к Jev другую LLM: программу командной строки на этом компьютере или адрес API, совместимый с OpenAI или Anthropic. Мод попадает в настройки уже включённым, со своей вкладкой, и начинает действовать после сохранения."$json$::jsonb),
  ('ja', 'mods.create.description', $json$"別の LLM を Jev につなぎます。このコンピューター上のコマンドラインプログラムか、OpenAI または Anthropic 互換の API アドレスです。Mod はオンの状態で専用タブとともに設定に加わり、保存すると有効になります。"$json$::jsonb),
  ('de', 'mods.create.description', $json$"Binden Sie ein weiteres LLM an Jev an: ein Kommandozeilenprogramm auf diesem Computer oder eine API-Adresse, die mit OpenAI oder Anthropic kompatibel ist. Der Mod kommt eingeschaltet in die Einstellungen, mit eigenem Tab, und gilt, sobald Sie speichern."$json$::jsonb),
  ('pt-BR', 'mods.name', $json$"Nome"$json$::jsonb),
  ('en', 'mods.name', $json$"Name"$json$::jsonb),
  ('es', 'mods.name', $json$"Nombre"$json$::jsonb),
  ('zh-CN', 'mods.name', $json$"名称"$json$::jsonb),
  ('hi', 'mods.name', $json$"नाम"$json$::jsonb),
  ('ar', 'mods.name', $json$"الاسم"$json$::jsonb),
  ('fr', 'mods.name', $json$"Nom"$json$::jsonb),
  ('ru', 'mods.name', $json$"Название"$json$::jsonb),
  ('ja', 'mods.name', $json$"名前"$json$::jsonb),
  ('de', 'mods.name', $json$"Name"$json$::jsonb),
  ('pt-BR', 'mods.name.hint', $json$"Como o mod aparece nas abas, no chat e no uso."$json$::jsonb),
  ('en', 'mods.name.hint', $json$"How the mod appears in the tabs, in the chat and in usage."$json$::jsonb),
  ('es', 'mods.name.hint', $json$"Cómo aparece el mod en las pestañas, en el chat y en el uso."$json$::jsonb),
  ('zh-CN', 'mods.name.hint', $json$"模组在标签页、聊天和用量中显示的名称。"$json$::jsonb),
  ('hi', 'mods.name.hint', $json$"टैब, चैट और उपयोग में मॉड इसी नाम से दिखता है।"$json$::jsonb),
  ('ar', 'mods.name.hint', $json$"كيف تظهر الإضافة في التبويبات وفي الدردشة وفي الاستخدام."$json$::jsonb),
  ('fr', 'mods.name.hint', $json$"Comment le mod apparaît dans les onglets, dans le chat et dans l’utilisation."$json$::jsonb),
  ('ru', 'mods.name.hint', $json$"Как мод отображается во вкладках, в чате и в статистике использования."$json$::jsonb),
  ('ja', 'mods.name.hint', $json$"タブ、チャット、使用状況での Mod の表示名です。"$json$::jsonb),
  ('de', 'mods.name.hint', $json$"So erscheint der Mod in den Tabs, im Chat und in der Nutzung."$json$::jsonb),
  ('pt-BR', 'mods.name.placeholder', $json$"Meu modelo local"$json$::jsonb),
  ('en', 'mods.name.placeholder', $json$"My local model"$json$::jsonb),
  ('es', 'mods.name.placeholder', $json$"Mi modelo local"$json$::jsonb),
  ('zh-CN', 'mods.name.placeholder', $json$"我的本地模型"$json$::jsonb),
  ('hi', 'mods.name.placeholder', $json$"मेरा लोकल मॉडल"$json$::jsonb),
  ('ar', 'mods.name.placeholder', $json$"نموذجي المحلي"$json$::jsonb),
  ('fr', 'mods.name.placeholder', $json$"Mon modèle local"$json$::jsonb),
  ('ru', 'mods.name.placeholder', $json$"Моя локальная модель"$json$::jsonb),
  ('ja', 'mods.name.placeholder', $json$"ローカルモデル"$json$::jsonb),
  ('de', 'mods.name.placeholder', $json$"Mein lokales Modell"$json$::jsonb),
  ('pt-BR', 'mods.name.empty', $json$"Dê um nome ao mod."$json$::jsonb),
  ('en', 'mods.name.empty', $json$"Give the mod a name."$json$::jsonb),
  ('es', 'mods.name.empty', $json$"Ponle un nombre al mod."$json$::jsonb),
  ('zh-CN', 'mods.name.empty', $json$"请为模组命名。"$json$::jsonb),
  ('hi', 'mods.name.empty', $json$"मॉड को एक नाम दें।"$json$::jsonb),
  ('ar', 'mods.name.empty', $json$"أعطِ الإضافة اسمًا."$json$::jsonb),
  ('fr', 'mods.name.empty', $json$"Donnez un nom au mod."$json$::jsonb),
  ('ru', 'mods.name.empty', $json$"Дайте моду название."$json$::jsonb),
  ('ja', 'mods.name.empty', $json$"Mod に名前を付けてください。"$json$::jsonb),
  ('de', 'mods.name.empty', $json$"Geben Sie dem Mod einen Namen."$json$::jsonb),
  ('pt-BR', 'mods.kind', $json$"Tipo"$json$::jsonb),
  ('en', 'mods.kind', $json$"Type"$json$::jsonb),
  ('es', 'mods.kind', $json$"Tipo"$json$::jsonb),
  ('zh-CN', 'mods.kind', $json$"类型"$json$::jsonb),
  ('hi', 'mods.kind', $json$"प्रकार"$json$::jsonb),
  ('ar', 'mods.kind', $json$"النوع"$json$::jsonb),
  ('fr', 'mods.kind', $json$"Type"$json$::jsonb),
  ('ru', 'mods.kind', $json$"Тип"$json$::jsonb),
  ('ja', 'mods.kind', $json$"種類"$json$::jsonb),
  ('de', 'mods.kind', $json$"Typ"$json$::jsonb),
  ('pt-BR', 'mods.kind.cli', $json$"Linha de comando"$json$::jsonb),
  ('en', 'mods.kind.cli', $json$"Command line"$json$::jsonb),
  ('es', 'mods.kind.cli', $json$"Línea de comandos"$json$::jsonb),
  ('zh-CN', 'mods.kind.cli', $json$"命令行"$json$::jsonb),
  ('hi', 'mods.kind.cli', $json$"कमांड लाइन"$json$::jsonb),
  ('ar', 'mods.kind.cli', $json$"سطر الأوامر"$json$::jsonb),
  ('fr', 'mods.kind.cli', $json$"Ligne de commande"$json$::jsonb),
  ('ru', 'mods.kind.cli', $json$"Командная строка"$json$::jsonb),
  ('ja', 'mods.kind.cli', $json$"コマンドライン"$json$::jsonb),
  ('de', 'mods.kind.cli', $json$"Kommandozeile"$json$::jsonb),
  ('pt-BR', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('en', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('es', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('zh-CN', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('hi', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('ar', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('fr', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('ru', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('ja', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('de', 'mods.kind.api', $json$"API"$json$::jsonb),
  ('pt-BR', 'mods.kind.cli.hint', $json$"Um programa neste computador que recebe o pedido e responde com texto, como os agentes de código."$json$::jsonb),
  ('en', 'mods.kind.cli.hint', $json$"A program on this computer that receives the request and answers with text, like the coding agents."$json$::jsonb),
  ('es', 'mods.kind.cli.hint', $json$"Un programa en este equipo que recibe la solicitud y responde con texto, como los agentes de código."$json$::jsonb),
  ('zh-CN', 'mods.kind.cli.hint', $json$"本机上的程序，接收请求并以文本作答，类似编程代理。"$json$::jsonb),
  ('hi', 'mods.kind.cli.hint', $json$"इस कंप्यूटर पर एक प्रोग्राम जो अनुरोध लेता है और टेक्स्ट में जवाब देता है, कोडिंग एजेंट की तरह।"$json$::jsonb),
  ('ar', 'mods.kind.cli.hint', $json$"برنامج على هذا الجهاز يستقبل الطلب ويجيب بالنص، مثل وكلاء البرمجة."$json$::jsonb),
  ('fr', 'mods.kind.cli.hint', $json$"Un programme sur cet ordinateur qui reçoit la demande et répond par du texte, comme les agents de code."$json$::jsonb),
  ('ru', 'mods.kind.cli.hint', $json$"Программа на этом компьютере, которая получает запрос и отвечает текстом, как агенты для кода."$json$::jsonb),
  ('ja', 'mods.kind.cli.hint', $json$"リクエストを受け取ってテキストで答える、このコンピューター上のプログラムです。コーディングエージェントと同じです。"$json$::jsonb),
  ('de', 'mods.kind.cli.hint', $json$"Ein Programm auf diesem Computer, das die Anfrage erhält und mit Text antwortet, wie die Coding-Agenten."$json$::jsonb),
  ('pt-BR', 'mods.kind.api.hint', $json$"Um endereço HTTP compatível com a API da OpenAI ou da Anthropic. Responde com texto e nunca edita o projeto."$json$::jsonb),
  ('en', 'mods.kind.api.hint', $json$"An HTTP address compatible with the OpenAI or Anthropic API. It answers with text and never edits the project."$json$::jsonb),
  ('es', 'mods.kind.api.hint', $json$"Una dirección HTTP compatible con la API de OpenAI o de Anthropic. Responde con texto y nunca edita el proyecto."$json$::jsonb),
  ('zh-CN', 'mods.kind.api.hint', $json$"兼容 OpenAI 或 Anthropic API 的 HTTP 地址。它以文本作答，从不编辑项目。"$json$::jsonb),
  ('hi', 'mods.kind.api.hint', $json$"OpenAI या Anthropic API के साथ संगत एक HTTP पता। यह टेक्स्ट में जवाब देता है और प्रोजेक्ट को कभी संपादित नहीं करता।"$json$::jsonb),
  ('ar', 'mods.kind.api.hint', $json$"عنوان HTTP متوافق مع واجهة OpenAI أو Anthropic البرمجية. يجيب بالنص ولا يعدّل المشروع أبدًا."$json$::jsonb),
  ('fr', 'mods.kind.api.hint', $json$"Une adresse HTTP compatible avec l’API d’OpenAI ou d’Anthropic. Elle répond par du texte et ne modifie jamais le projet."$json$::jsonb),
  ('ru', 'mods.kind.api.hint', $json$"HTTP-адрес, совместимый с API OpenAI или Anthropic. Отвечает текстом и никогда не редактирует проект."$json$::jsonb),
  ('ja', 'mods.kind.api.hint', $json$"OpenAI または Anthropic の API と互換性のある HTTP アドレスです。テキストで答え、プロジェクトを編集することはありません。"$json$::jsonb),
  ('de', 'mods.kind.api.hint', $json$"Eine HTTP-Adresse, die mit der API von OpenAI oder Anthropic kompatibel ist. Sie antwortet mit Text und bearbeitet nie das Projekt."$json$::jsonb),
  ('pt-BR', 'mods.command', $json$"Programa"$json$::jsonb),
  ('en', 'mods.command', $json$"Program"$json$::jsonb),
  ('es', 'mods.command', $json$"Programa"$json$::jsonb),
  ('zh-CN', 'mods.command', $json$"程序"$json$::jsonb),
  ('hi', 'mods.command', $json$"प्रोग्राम"$json$::jsonb),
  ('ar', 'mods.command', $json$"البرنامج"$json$::jsonb),
  ('fr', 'mods.command', $json$"Programme"$json$::jsonb),
  ('ru', 'mods.command', $json$"Программа"$json$::jsonb),
  ('ja', 'mods.command', $json$"プログラム"$json$::jsonb),
  ('de', 'mods.command', $json$"Programm"$json$::jsonb),
  ('pt-BR', 'mods.command.hint', $json$"O nome do executável, achado no PATH, ou o caminho completo dele. Sem argumentos aqui."$json$::jsonb),
  ('en', 'mods.command.hint', $json$"The executable name, found in PATH, or its full path. No arguments here."$json$::jsonb),
  ('es', 'mods.command.hint', $json$"El nombre del ejecutable, encontrado en el PATH, o su ruta completa. Sin argumentos aquí."$json$::jsonb),
  ('zh-CN', 'mods.command.hint', $json$"可执行文件名（在 PATH 中查找）或其完整路径。此处不要填写参数。"$json$::jsonb),
  ('hi', 'mods.command.hint', $json$"निष्पादन योग्य फ़ाइल का नाम, जो PATH में मिले, या उसका पूरा पथ। यहाँ आर्ग्युमेंट नहीं।"$json$::jsonb),
  ('ar', 'mods.command.hint', $json$"اسم الملف التنفيذي كما يوجد في PATH، أو مساره الكامل. بلا وسائط هنا."$json$::jsonb),
  ('fr', 'mods.command.hint', $json$"Le nom de l’exécutable, trouvé dans le PATH, ou son chemin complet. Pas d’arguments ici."$json$::jsonb),
  ('ru', 'mods.command.hint', $json$"Имя исполняемого файла из PATH или полный путь к нему. Без аргументов."$json$::jsonb),
  ('ja', 'mods.command.hint', $json$"PATH から見つかる実行ファイル名、またはそのフルパス。ここに引数は入れません。"$json$::jsonb),
  ('de', 'mods.command.hint', $json$"Der Name der ausführbaren Datei, im PATH gefunden, oder ihr vollständiger Pfad. Hier keine Argumente."$json$::jsonb),
  ('pt-BR', 'mods.args', $json$"Linha de comando"$json$::jsonb),
  ('en', 'mods.args', $json$"Command line"$json$::jsonb),
  ('es', 'mods.args', $json$"Línea de comandos"$json$::jsonb),
  ('zh-CN', 'mods.args', $json$"命令行"$json$::jsonb),
  ('hi', 'mods.args', $json$"कमांड लाइन"$json$::jsonb),
  ('ar', 'mods.args', $json$"سطر الأوامر"$json$::jsonb),
  ('fr', 'mods.args', $json$"Ligne de commande"$json$::jsonb),
  ('ru', 'mods.args', $json$"Командная строка"$json$::jsonb),
  ('ja', 'mods.args', $json$"コマンドライン"$json$::jsonb),
  ('de', 'mods.args', $json$"Kommandozeile"$json$::jsonb),
  ('pt-BR', 'mods.args.hint', $json$"Argumentos separados por espaço (as aspas mantêm junto um argumento com espaços). {model} vira o modelo que o Jev escolheu; {prompt}, sozinho num argumento, vira o pedido — sem ele, o pedido vai pela entrada padrão."$json$::jsonb),
  ('en', 'mods.args.hint', $json$"Arguments separated by spaces (quotes keep one with spaces together). {model} becomes the model Jev picked; {prompt}, alone in an argument, becomes the request — without it, the request goes through standard input."$json$::jsonb),
  ('es', 'mods.args.hint', $json$"Argumentos separados por espacios (las comillas mantienen junto un argumento con espacios). {model} se convierte en el modelo que eligió Jev; {prompt}, solo en un argumento, se convierte en la solicitud — sin él, la solicitud va por la entrada estándar."$json$::jsonb),
  ('zh-CN', 'mods.args.hint', $json$"以空格分隔的参数（引号可让含空格的参数保持完整）。{model} 会替换为 Jev 选择的模型；{prompt} 单独作为一个参数时会替换为请求——没有它时，请求通过标准输入传入。"$json$::jsonb),
  ('hi', 'mods.args.hint', $json$"स्पेस से अलग आर्ग्युमेंट (उद्धरण चिह्न स्पेस वाले आर्ग्युमेंट को एक साथ रखते हैं)। {model} की जगह Jev का चुना मॉडल आता है; {prompt}, अकेले एक आर्ग्युमेंट में, अनुरोध बन जाता है — इसके बिना अनुरोध मानक इनपुट से जाता है।"$json$::jsonb),
  ('ar', 'mods.args.hint', $json$"وسائط مفصولة بمسافات (علامات الاقتباس تُبقي الوسيط الذي فيه مسافات مجتمعًا). يصبح {model} النموذج الذي اختاره Jev؛ ويصبح {prompt}، منفردًا في وسيط، الطلبَ — ومن دونه يُرسل الطلب عبر الإدخال القياسي."$json$::jsonb),
  ('fr', 'mods.args.hint', $json$"Arguments séparés par des espaces (les guillemets gardent ensemble un argument avec des espaces). {model} devient le modèle choisi par Jev ; {prompt}, seul dans un argument, devient la demande — sans lui, la demande passe par l’entrée standard."$json$::jsonb),
  ('ru', 'mods.args.hint', $json$"Аргументы через пробел (кавычки удерживают вместе аргумент с пробелами). {model} заменяется моделью, выбранной Jev; {prompt}, отдельным аргументом, заменяется запросом — без него запрос передаётся через стандартный ввод."$json$::jsonb),
  ('ja', 'mods.args.hint', $json$"スペース区切りの引数です（引用符で囲むとスペースを含む引数を1つにできます）。{model} は Jev が選んだモデルに、単独の引数の {prompt} はリクエストに置き換わります。これがなければ、リクエストは標準入力で渡されます。"$json$::jsonb),
  ('de', 'mods.args.hint', $json$"Durch Leerzeichen getrennte Argumente (Anführungszeichen halten ein Argument mit Leerzeichen zusammen). {model} wird zum Modell, das Jev gewählt hat; {prompt}, allein in einem Argument, wird zur Anfrage — ohne es geht die Anfrage über die Standardeingabe."$json$::jsonb),
  ('pt-BR', 'mods.args.invalid', $json$"A linha de comando tem um argumento vazio, uma quebra de linha ou um argumento longo demais."$json$::jsonb),
  ('en', 'mods.args.invalid', $json$"The command line has an empty argument, a line break or an argument that is too long."$json$::jsonb),
  ('es', 'mods.args.invalid', $json$"La línea de comandos tiene un argumento vacío, un salto de línea o un argumento demasiado largo."$json$::jsonb),
  ('zh-CN', 'mods.args.invalid', $json$"命令行中有空参数、换行或过长的参数。"$json$::jsonb),
  ('hi', 'mods.args.invalid', $json$"कमांड लाइन में कोई खाली आर्ग्युमेंट, लाइन ब्रेक या बहुत लंबा आर्ग्युमेंट है।"$json$::jsonb),
  ('ar', 'mods.args.invalid', $json$"في سطر الأوامر وسيط فارغ أو فاصل أسطر أو وسيط أطول من اللازم."$json$::jsonb),
  ('fr', 'mods.args.invalid', $json$"La ligne de commande contient un argument vide, un saut de ligne ou un argument trop long."$json$::jsonb),
  ('ru', 'mods.args.invalid', $json$"В командной строке есть пустой аргумент, перевод строки или слишком длинный аргумент."$json$::jsonb),
  ('ja', 'mods.args.invalid', $json$"コマンドラインに空の引数、改行、または長すぎる引数があります。"$json$::jsonb),
  ('de', 'mods.args.invalid', $json$"Die Kommandozeile enthält ein leeres Argument, einen Zeilenumbruch oder ein zu langes Argument."$json$::jsonb),
  ('pt-BR', 'mods.args.tooMany', $json$"A linha de comando aceita no máximo 64 argumentos."$json$::jsonb),
  ('en', 'mods.args.tooMany', $json$"The command line takes at most 64 arguments."$json$::jsonb),
  ('es', 'mods.args.tooMany', $json$"La línea de comandos admite como máximo 64 argumentos."$json$::jsonb),
  ('zh-CN', 'mods.args.tooMany', $json$"命令行最多接受 64 个参数。"$json$::jsonb),
  ('hi', 'mods.args.tooMany', $json$"कमांड लाइन में अधिकतम 64 आर्ग्युमेंट हो सकते हैं।"$json$::jsonb),
  ('ar', 'mods.args.tooMany', $json$"يقبل سطر الأوامر 64 وسيطًا على الأكثر."$json$::jsonb),
  ('fr', 'mods.args.tooMany', $json$"La ligne de commande accepte au plus 64 arguments."$json$::jsonb),
  ('ru', 'mods.args.tooMany', $json$"Командная строка принимает не более 64 аргументов."$json$::jsonb),
  ('ja', 'mods.args.tooMany', $json$"コマンドラインの引数は最大 64 個です。"$json$::jsonb),
  ('de', 'mods.args.tooMany', $json$"Die Kommandozeile nimmt höchstens 64 Argumente an."$json$::jsonb),
  ('pt-BR', 'mods.args.placeholder', $json$"Só {model} e {prompt} (sozinho num argumento) podem ser usados na linha de comando."$json$::jsonb),
  ('en', 'mods.args.placeholder', $json$"Only {model} and {prompt} (alone in an argument) can be used in the command line."$json$::jsonb),
  ('es', 'mods.args.placeholder', $json$"Solo {model} y {prompt} (solo en un argumento) se pueden usar en la línea de comandos."$json$::jsonb),
  ('zh-CN', 'mods.args.placeholder', $json$"命令行中只能使用 {model} 和 {prompt}（单独作为一个参数）。"$json$::jsonb),
  ('hi', 'mods.args.placeholder', $json$"कमांड लाइन में केवल {model} और {prompt} (अकेले एक आर्ग्युमेंट में) इस्तेमाल हो सकते हैं।"$json$::jsonb),
  ('ar', 'mods.args.placeholder', $json$"لا يُستخدم في سطر الأوامر إلا {model} و{prompt} (منفردًا في وسيط)."$json$::jsonb),
  ('fr', 'mods.args.placeholder', $json$"Seuls {model} et {prompt} (seul dans un argument) peuvent être utilisés dans la ligne de commande."$json$::jsonb),
  ('ru', 'mods.args.placeholder', $json$"В командной строке можно использовать только {model} и {prompt} (отдельным аргументом)."$json$::jsonb),
  ('ja', 'mods.args.placeholder', $json$"コマンドラインで使えるのは {model} と {prompt}（単独の引数として）だけです。"$json$::jsonb),
  ('de', 'mods.args.placeholder', $json$"In der Kommandozeile sind nur {model} und {prompt} (allein in einem Argument) erlaubt."$json$::jsonb),
  ('pt-BR', 'mods.edits', $json$"Escreve no projeto"$json$::jsonb),
  ('en', 'mods.edits', $json$"Writes to the project"$json$::jsonb),
  ('es', 'mods.edits', $json$"Escribe en el proyecto"$json$::jsonb),
  ('zh-CN', 'mods.edits', $json$"会写入项目"$json$::jsonb),
  ('hi', 'mods.edits', $json$"प्रोजेक्ट में लिखता है"$json$::jsonb),
  ('ar', 'mods.edits', $json$"يكتب في المشروع"$json$::jsonb),
  ('fr', 'mods.edits', $json$"Écrit dans le projet"$json$::jsonb),
  ('ru', 'mods.edits', $json$"Пишет в проект"$json$::jsonb),
  ('ja', 'mods.edits', $json$"プロジェクトに書き込む"$json$::jsonb),
  ('de', 'mods.edits', $json$"Schreibt ins Projekt"$json$::jsonb),
  ('pt-BR', 'mods.edits.hint', $json$"Ligue quando o programa edita arquivos ou roda comandos: os modelos dele passam a poder fazer código e usar ferramentas, e a linha de planejamento fica obrigatória."$json$::jsonb),
  ('en', 'mods.edits.hint', $json$"Turn on when the program edits files or runs commands: its models can then do code and use tools, and the planning line becomes required."$json$::jsonb),
  ('es', 'mods.edits.hint', $json$"Actívalo cuando el programa edita archivos o ejecuta comandos: sus modelos pueden entonces hacer código y usar herramientas, y la línea de planificación pasa a ser obligatoria."$json$::jsonb),
  ('zh-CN', 'mods.edits.hint', $json$"当程序会编辑文件或运行命令时开启：其模型即可编写代码和使用工具，同时规划命令行变为必填。"$json$::jsonb),
  ('hi', 'mods.edits.hint', $json$"जब प्रोग्राम फ़ाइलें संपादित करता है या कमांड चलाता है तब चालू करें: तब इसके मॉडल कोड लिख सकते हैं और टूल इस्तेमाल कर सकते हैं, और योजना वाली लाइन ज़रूरी हो जाती है।"$json$::jsonb),
  ('ar', 'mods.edits.hint', $json$"فعّله عندما يعدّل البرنامج الملفات أو يشغّل الأوامر: عندها يمكن لنماذجه كتابة الشيفرة واستخدام الأدوات، ويصبح سطر التخطيط إلزاميًا."$json$::jsonb),
  ('fr', 'mods.edits.hint', $json$"Activez-le quand le programme modifie des fichiers ou exécute des commandes : ses modèles peuvent alors faire du code et utiliser des outils, et la ligne de planification devient obligatoire."$json$::jsonb),
  ('ru', 'mods.edits.hint', $json$"Включите, если программа редактирует файлы или выполняет команды: её модели смогут писать код и пользоваться инструментами, а строка планирования станет обязательной."$json$::jsonb),
  ('ja', 'mods.edits.hint', $json$"プログラムがファイルを編集したりコマンドを実行したりする場合にオンにします。そのモデルはコードを書いたりツールを使ったりできるようになり、計画用のコマンドラインが必須になります。"$json$::jsonb),
  ('de', 'mods.edits.hint', $json$"Einschalten, wenn das Programm Dateien bearbeitet oder Befehle ausführt: Seine Modelle können dann Code schreiben und Werkzeuge nutzen, und die Planungszeile wird Pflicht."$json$::jsonb),
  ('pt-BR', 'mods.planArgs', $json$"Linha de comando do planejamento"$json$::jsonb),
  ('en', 'mods.planArgs', $json$"Planning command line"$json$::jsonb),
  ('es', 'mods.planArgs', $json$"Línea de comandos de planificación"$json$::jsonb),
  ('zh-CN', 'mods.planArgs', $json$"规划命令行"$json$::jsonb),
  ('hi', 'mods.planArgs', $json$"योजना की कमांड लाइन"$json$::jsonb),
  ('ar', 'mods.planArgs', $json$"سطر أوامر التخطيط"$json$::jsonb),
  ('fr', 'mods.planArgs', $json$"Ligne de commande de planification"$json$::jsonb),
  ('ru', 'mods.planArgs', $json$"Командная строка для планирования"$json$::jsonb),
  ('ja', 'mods.planArgs', $json$"計画用のコマンドライン"$json$::jsonb),
  ('de', 'mods.planArgs', $json$"Kommandozeile für die Planung"$json$::jsonb),
  ('pt-BR', 'mods.planArgs.hint', $json$"Opcional: a linha usada no modo Planejamento. Vazia, o mod usa a mesma linha."$json$::jsonb),
  ('en', 'mods.planArgs.hint', $json$"Optional: the line used in Planning mode. Empty, the mod uses the same line."$json$::jsonb),
  ('es', 'mods.planArgs.hint', $json$"Opcional: la línea usada en el modo Planificación. Vacía, el mod usa la misma línea."$json$::jsonb),
  ('zh-CN', 'mods.planArgs.hint', $json$"可选：规划模式下使用的命令行。留空时，模组使用同一行。"$json$::jsonb),
  ('hi', 'mods.planArgs.hint', $json$"वैकल्पिक: योजना मोड में इस्तेमाल होने वाली लाइन। खाली होने पर मॉड वही लाइन इस्तेमाल करता है।"$json$::jsonb),
  ('ar', 'mods.planArgs.hint', $json$"اختياري: السطر المستخدم في وضع التخطيط. إن كان فارغًا تستخدم الإضافة السطر نفسه."$json$::jsonb),
  ('fr', 'mods.planArgs.hint', $json$"Facultatif : la ligne utilisée en mode Planification. Vide, le mod utilise la même ligne."$json$::jsonb),
  ('ru', 'mods.planArgs.hint', $json$"Необязательно: строка для режима «Планирование». Если пусто, мод использует ту же строку."$json$::jsonb),
  ('ja', 'mods.planArgs.hint', $json$"任意：計画モードで使うコマンドライン。空の場合、Mod は同じコマンドラインを使います。"$json$::jsonb),
  ('de', 'mods.planArgs.hint', $json$"Optional: die Zeile für den Modus Planung. Leer nutzt der Mod dieselbe Zeile."$json$::jsonb),
  ('pt-BR', 'mods.planArgs.hint.required', $json$"A linha que não escreve no projeto: usada no modo Planejamento e sempre que a política de uma organização aperta os agentes."$json$::jsonb),
  ('en', 'mods.planArgs.hint.required', $json$"The line that does not write to the project: used in Planning mode and whenever an organization's policy tightens the agents."$json$::jsonb),
  ('es', 'mods.planArgs.hint.required', $json$"La línea que no escribe en el proyecto: se usa en el modo Planificación y siempre que la política de una organización restringe a los agentes."$json$::jsonb),
  ('zh-CN', 'mods.planArgs.hint.required', $json$"不写入项目的命令行：用于规划模式，以及组织策略收紧代理权限的任何时候。"$json$::jsonb),
  ('hi', 'mods.planArgs.hint.required', $json$"वह लाइन जो प्रोजेक्ट में नहीं लिखती: योजना मोड में और जब भी किसी संगठन की नीति एजेंटों को सख़्त करती है, तब इस्तेमाल होती है।"$json$::jsonb),
  ('ar', 'mods.planArgs.hint.required', $json$"السطر الذي لا يكتب في المشروع: يُستخدم في وضع التخطيط وكلما شدّدت سياسة مؤسسة القيود على الوكلاء."$json$::jsonb),
  ('fr', 'mods.planArgs.hint.required', $json$"La ligne qui n’écrit pas dans le projet : utilisée en mode Planification et chaque fois que la politique d’une organisation restreint les agents."$json$::jsonb),
  ('ru', 'mods.planArgs.hint.required', $json$"Строка, которая не пишет в проект: используется в режиме «Планирование» и всякий раз, когда политика организации ужесточает правила для агентов."$json$::jsonb),
  ('ja', 'mods.planArgs.hint.required', $json$"プロジェクトに書き込まないコマンドライン。計画モードと、組織のポリシーがエージェントを制限するときに使われます。"$json$::jsonb),
  ('de', 'mods.planArgs.hint.required', $json$"Die Zeile, die nicht ins Projekt schreibt: genutzt im Modus Planung und immer dann, wenn die Richtlinie einer Organisation die Agenten einschränkt."$json$::jsonb),
  ('pt-BR', 'mods.planArgs.required', $json$"Um mod que escreve no projeto precisa de uma linha de comando de planejamento que não escreva."$json$::jsonb),
  ('en', 'mods.planArgs.required', $json$"A mod that writes to the project needs a planning command line that does not."$json$::jsonb),
  ('es', 'mods.planArgs.required', $json$"Un mod que escribe en el proyecto necesita una línea de comandos de planificación que no escriba."$json$::jsonb),
  ('zh-CN', 'mods.planArgs.required', $json$"会写入项目的模组需要一条不写入项目的规划命令行。"$json$::jsonb),
  ('hi', 'mods.planArgs.required', $json$"जो मॉड प्रोजेक्ट में लिखता है, उसे योजना की ऐसी कमांड लाइन चाहिए जो न लिखे।"$json$::jsonb),
  ('ar', 'mods.planArgs.required', $json$"الإضافة التي تكتب في المشروع تحتاج إلى سطر أوامر للتخطيط لا يكتب فيه."$json$::jsonb),
  ('fr', 'mods.planArgs.required', $json$"Un mod qui écrit dans le projet a besoin d’une ligne de commande de planification qui n’écrit pas."$json$::jsonb),
  ('ru', 'mods.planArgs.required', $json$"Моду, который пишет в проект, нужна командная строка для планирования, которая в проект не пишет."$json$::jsonb),
  ('ja', 'mods.planArgs.required', $json$"プロジェクトに書き込む Mod には、書き込まない計画用のコマンドラインが必要です。"$json$::jsonb),
  ('de', 'mods.planArgs.required', $json$"Ein Mod, der ins Projekt schreibt, braucht eine Kommandozeile für die Planung, die das nicht tut."$json$::jsonb),
  ('pt-BR', 'mods.protocol', $json$"Protocolo"$json$::jsonb),
  ('en', 'mods.protocol', $json$"Protocol"$json$::jsonb),
  ('es', 'mods.protocol', $json$"Protocolo"$json$::jsonb),
  ('zh-CN', 'mods.protocol', $json$"协议"$json$::jsonb),
  ('hi', 'mods.protocol', $json$"प्रोटोकॉल"$json$::jsonb),
  ('ar', 'mods.protocol', $json$"البروتوكول"$json$::jsonb),
  ('fr', 'mods.protocol', $json$"Protocole"$json$::jsonb),
  ('ru', 'mods.protocol', $json$"Протокол"$json$::jsonb),
  ('ja', 'mods.protocol', $json$"プロトコル"$json$::jsonb),
  ('de', 'mods.protocol', $json$"Protokoll"$json$::jsonb),
  ('pt-BR', 'mods.protocol.hint', $json$"Compatível com OpenAI (/chat/completions e /models) ou a API Messages da Anthropic (/messages)."$json$::jsonb),
  ('en', 'mods.protocol.hint', $json$"OpenAI-compatible (/chat/completions and /models) or the Anthropic Messages API (/messages)."$json$::jsonb),
  ('es', 'mods.protocol.hint', $json$"Compatible con OpenAI (/chat/completions y /models) o la API Messages de Anthropic (/messages)."$json$::jsonb),
  ('zh-CN', 'mods.protocol.hint', $json$"兼容 OpenAI（/chat/completions 和 /models）或 Anthropic 的 Messages API（/messages）。"$json$::jsonb),
  ('hi', 'mods.protocol.hint', $json$"OpenAI-संगत (/chat/completions और /models) या Anthropic का Messages API (/messages)।"$json$::jsonb),
  ('ar', 'mods.protocol.hint', $json$"متوافق مع OpenAI (‏/chat/completions و‏/models) أو واجهة Messages من Anthropic (‏/messages)."$json$::jsonb),
  ('fr', 'mods.protocol.hint', $json$"Compatible OpenAI (/chat/completions et /models) ou l’API Messages d’Anthropic (/messages)."$json$::jsonb),
  ('ru', 'mods.protocol.hint', $json$"Совместимый с OpenAI (/chat/completions и /models) или Messages API от Anthropic (/messages)."$json$::jsonb),
  ('ja', 'mods.protocol.hint', $json$"OpenAI 互換（/chat/completions と /models）または Anthropic の Messages API（/messages）。"$json$::jsonb),
  ('de', 'mods.protocol.hint', $json$"OpenAI-kompatibel (/chat/completions und /models) oder die Messages-API von Anthropic (/messages)."$json$::jsonb),
  ('pt-BR', 'mods.protocol.openai', $json$"Compatível com OpenAI"$json$::jsonb),
  ('en', 'mods.protocol.openai', $json$"OpenAI-compatible"$json$::jsonb),
  ('es', 'mods.protocol.openai', $json$"Compatible con OpenAI"$json$::jsonb),
  ('zh-CN', 'mods.protocol.openai', $json$"兼容 OpenAI"$json$::jsonb),
  ('hi', 'mods.protocol.openai', $json$"OpenAI-संगत"$json$::jsonb),
  ('ar', 'mods.protocol.openai', $json$"متوافق مع OpenAI"$json$::jsonb),
  ('fr', 'mods.protocol.openai', $json$"Compatible OpenAI"$json$::jsonb),
  ('ru', 'mods.protocol.openai', $json$"Совместимый с OpenAI"$json$::jsonb),
  ('ja', 'mods.protocol.openai', $json$"OpenAI 互換"$json$::jsonb),
  ('de', 'mods.protocol.openai', $json$"OpenAI-kompatibel"$json$::jsonb),
  ('pt-BR', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('en', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('es', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('zh-CN', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('hi', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('ar', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('fr', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('ru', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('ja', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('de', 'mods.protocol.anthropic', $json$"Anthropic"$json$::jsonb),
  ('pt-BR', 'mods.baseUrl.hint', $json$"O endereço base da API, por exemplo http://localhost:8080/v1."$json$::jsonb),
  ('en', 'mods.baseUrl.hint', $json$"The base address of the API, for example http://localhost:8080/v1."$json$::jsonb),
  ('es', 'mods.baseUrl.hint', $json$"La dirección base de la API, por ejemplo http://localhost:8080/v1."$json$::jsonb),
  ('zh-CN', 'mods.baseUrl.hint', $json$"API 的基础地址，例如 http://localhost:8080/v1。"$json$::jsonb),
  ('hi', 'mods.baseUrl.hint', $json$"API का मूल पता, उदाहरण के लिए http://localhost:8080/v1।"$json$::jsonb),
  ('ar', 'mods.baseUrl.hint', $json$"العنوان الأساسي للواجهة البرمجية، مثل http://localhost:8080/v1."$json$::jsonb),
  ('fr', 'mods.baseUrl.hint', $json$"L’adresse de base de l’API, par exemple http://localhost:8080/v1."$json$::jsonb),
  ('ru', 'mods.baseUrl.hint', $json$"Базовый адрес API, например http://localhost:8080/v1."$json$::jsonb),
  ('ja', 'mods.baseUrl.hint', $json$"API のベースアドレス。例：http://localhost:8080/v1"$json$::jsonb),
  ('de', 'mods.baseUrl.hint', $json$"Die Basisadresse der API, zum Beispiel http://localhost:8080/v1."$json$::jsonb),
  ('pt-BR', 'mods.baseUrl.required', $json$"Informe o endereço da API."$json$::jsonb),
  ('en', 'mods.baseUrl.required', $json$"Enter the API address."$json$::jsonb),
  ('es', 'mods.baseUrl.required', $json$"Introduce la dirección de la API."$json$::jsonb),
  ('zh-CN', 'mods.baseUrl.required', $json$"请输入 API 地址。"$json$::jsonb),
  ('hi', 'mods.baseUrl.required', $json$"API का पता दर्ज करें।"$json$::jsonb),
  ('ar', 'mods.baseUrl.required', $json$"أدخل عنوان الواجهة البرمجية."$json$::jsonb),
  ('fr', 'mods.baseUrl.required', $json$"Saisissez l’adresse de l’API."$json$::jsonb),
  ('ru', 'mods.baseUrl.required', $json$"Укажите адрес API."$json$::jsonb),
  ('ja', 'mods.baseUrl.required', $json$"API のアドレスを入力してください。"$json$::jsonb),
  ('de', 'mods.baseUrl.required', $json$"Geben Sie die API-Adresse ein."$json$::jsonb),
  ('pt-BR', 'mods.apiKey.hint', $json$"Opcional quando o servidor não pede uma. Fica só neste computador: nunca é mostrada de novo nem sincronizada com a nuvem."$json$::jsonb),
  ('en', 'mods.apiKey.hint', $json$"Optional when the server does not ask for one. Stored only on this computer: never shown again and never synced to the cloud."$json$::jsonb),
  ('es', 'mods.apiKey.hint', $json$"Opcional si el servidor no la pide. Se guarda solo en este equipo: nunca se vuelve a mostrar ni se sincroniza con la nube."$json$::jsonb),
  ('zh-CN', 'mods.apiKey.hint', $json$"服务器不要求时可不填。仅保存在本机：不会再次显示，也不会同步到云端。"$json$::jsonb),
  ('hi', 'mods.apiKey.hint', $json$"सर्वर न माँगे तो वैकल्पिक। केवल इस कंप्यूटर पर सहेजी जाती है: न दोबारा दिखाई जाती है, न क्लाउड से सिंक होती है।"$json$::jsonb),
  ('ar', 'mods.apiKey.hint', $json$"اختياري حين لا يطلبه الخادم. يُحفظ على هذا الجهاز فقط: لا يُعرض مرة أخرى ولا يُزامَن مع السحابة."$json$::jsonb),
  ('fr', 'mods.apiKey.hint', $json$"Facultative si le serveur n’en demande pas. Stockée uniquement sur cet ordinateur : jamais réaffichée ni synchronisée avec le cloud."$json$::jsonb),
  ('ru', 'mods.apiKey.hint', $json$"Необязательно, если сервер его не требует. Хранится только на этом компьютере: больше не показывается и не синхронизируется с облаком."$json$::jsonb),
  ('ja', 'mods.apiKey.hint', $json$"サーバーが求めない場合は任意です。このコンピューターにのみ保存され、再表示もクラウドへの同期もされません。"$json$::jsonb),
  ('de', 'mods.apiKey.hint', $json$"Optional, wenn der Server keinen verlangt. Nur auf diesem Computer gespeichert: nie wieder angezeigt und nie mit der Cloud synchronisiert."$json$::jsonb),
  ('pt-BR', 'mods.keyRequired', $json$"Exige chave de API"$json$::jsonb),
  ('en', 'mods.keyRequired', $json$"Requires an API key"$json$::jsonb),
  ('es', 'mods.keyRequired', $json$"Requiere clave de API"$json$::jsonb),
  ('zh-CN', 'mods.keyRequired', $json$"需要 API 密钥"$json$::jsonb),
  ('hi', 'mods.keyRequired', $json$"API कुंजी ज़रूरी"$json$::jsonb),
  ('ar', 'mods.keyRequired', $json$"يتطلب مفتاح API"$json$::jsonb),
  ('fr', 'mods.keyRequired', $json$"Exige une clé d’API"$json$::jsonb),
  ('ru', 'mods.keyRequired', $json$"Требуется ключ API"$json$::jsonb),
  ('ja', 'mods.keyRequired', $json$"API キーが必要"$json$::jsonb),
  ('de', 'mods.keyRequired', $json$"Benötigt einen API-Schlüssel"$json$::jsonb),
  ('pt-BR', 'mods.keyRequired.hint', $json$"Ligado, o mod só roda com uma chave guardada neste computador."$json$::jsonb),
  ('en', 'mods.keyRequired.hint', $json$"Turned on, the mod only runs with a key saved on this computer."$json$::jsonb),
  ('es', 'mods.keyRequired.hint', $json$"Activado, el mod solo funciona con una clave guardada en este equipo."$json$::jsonb),
  ('zh-CN', 'mods.keyRequired.hint', $json$"开启后，模组只在本机保存了密钥时才运行。"$json$::jsonb),
  ('hi', 'mods.keyRequired.hint', $json$"चालू होने पर मॉड केवल इस कंप्यूटर पर सहेजी कुंजी के साथ चलता है।"$json$::jsonb),
  ('ar', 'mods.keyRequired.hint', $json$"عند تفعيله لا تعمل الإضافة إلا بمفتاح محفوظ على هذا الجهاز."$json$::jsonb),
  ('fr', 'mods.keyRequired.hint', $json$"Activé, le mod ne fonctionne qu’avec une clé enregistrée sur cet ordinateur."$json$::jsonb),
  ('ru', 'mods.keyRequired.hint', $json$"Если включено, мод работает только с ключом, сохранённым на этом компьютере."$json$::jsonb),
  ('ja', 'mods.keyRequired.hint', $json$"オンにすると、このコンピューターにキーが保存されているときだけ Mod が動作します。"$json$::jsonb),
  ('de', 'mods.keyRequired.hint', $json$"Eingeschaltet läuft der Mod nur mit einem auf diesem Computer gespeicherten Schlüssel."$json$::jsonb),
  ('pt-BR', 'mods.model', $json$"Primeiro modelo"$json$::jsonb),
  ('en', 'mods.model', $json$"First model"$json$::jsonb),
  ('es', 'mods.model', $json$"Primer modelo"$json$::jsonb),
  ('zh-CN', 'mods.model', $json$"第一个模型"$json$::jsonb),
  ('hi', 'mods.model', $json$"पहला मॉडल"$json$::jsonb),
  ('ar', 'mods.model', $json$"النموذج الأول"$json$::jsonb),
  ('fr', 'mods.model', $json$"Premier modèle"$json$::jsonb),
  ('ru', 'mods.model', $json$"Первая модель"$json$::jsonb),
  ('ja', 'mods.model', $json$"最初のモデル"$json$::jsonb),
  ('de', 'mods.model', $json$"Erstes Modell"$json$::jsonb),
  ('pt-BR', 'mods.model.hint.cli', $json$"Opcional: o id de um modelo que o programa aceita em {model}. Adicione outros na aba do mod."$json$::jsonb),
  ('en', 'mods.model.hint.cli', $json$"Optional: a model id the program accepts in {model}. Add more in the mod's tab."$json$::jsonb),
  ('es', 'mods.model.hint.cli', $json$"Opcional: el id de un modelo que el programa acepta en {model}. Añade más en la pestaña del mod."$json$::jsonb),
  ('zh-CN', 'mods.model.hint.cli', $json$"可选：程序在 {model} 中接受的模型 ID。更多模型可在模组的标签页中添加。"$json$::jsonb),
  ('hi', 'mods.model.hint.cli', $json$"वैकल्पिक: किसी मॉडल की id जिसे प्रोग्राम {model} में स्वीकार करता है। और मॉडल मॉड के टैब में जोड़ें।"$json$::jsonb),
  ('ar', 'mods.model.hint.cli', $json$"اختياري: معرّف نموذج يقبله البرنامج في {model}. أضف المزيد في تبويب الإضافة."$json$::jsonb),
  ('fr', 'mods.model.hint.cli', $json$"Facultatif : l’id d’un modèle que le programme accepte dans {model}. Ajoutez-en d’autres dans l’onglet du mod."$json$::jsonb),
  ('ru', 'mods.model.hint.cli', $json$"Необязательно: id модели, который программа принимает в {model}. Другие добавьте во вкладке мода."$json$::jsonb),
  ('ja', 'mods.model.hint.cli', $json$"任意：プログラムが {model} で受け付けるモデル ID。ほかのモデルは Mod のタブで追加します。"$json$::jsonb),
  ('de', 'mods.model.hint.cli', $json$"Optional: die ID eines Modells, das das Programm in {model} annimmt. Weitere fügen Sie im Tab des Mods hinzu."$json$::jsonb),
  ('pt-BR', 'mods.model.hint.api', $json$"Opcional: depois de salvar, a aba do mod pode carregar a lista de modelos da API."$json$::jsonb),
  ('en', 'mods.model.hint.api', $json$"Optional: after saving, the mod's tab can load the list of models from the API."$json$::jsonb),
  ('es', 'mods.model.hint.api', $json$"Opcional: después de guardar, la pestaña del mod puede cargar la lista de modelos desde la API."$json$::jsonb),
  ('zh-CN', 'mods.model.hint.api', $json$"可选：保存后，模组的标签页可以从 API 加载模型列表。"$json$::jsonb),
  ('hi', 'mods.model.hint.api', $json$"वैकल्पिक: सहेजने के बाद मॉड का टैब API से मॉडलों की सूची लोड कर सकता है।"$json$::jsonb),
  ('ar', 'mods.model.hint.api', $json$"اختياري: بعد الحفظ يمكن لتبويب الإضافة تحميل قائمة النماذج من الواجهة البرمجية."$json$::jsonb),
  ('fr', 'mods.model.hint.api', $json$"Facultatif : après l’enregistrement, l’onglet du mod peut charger la liste des modèles depuis l’API."$json$::jsonb),
  ('ru', 'mods.model.hint.api', $json$"Необязательно: после сохранения вкладка мода может загрузить список моделей из API."$json$::jsonb),
  ('ja', 'mods.model.hint.api', $json$"任意：保存後、Mod のタブで API からモデル一覧を読み込めます。"$json$::jsonb),
  ('de', 'mods.model.hint.api', $json$"Optional: Nach dem Speichern kann der Tab des Mods die Modellliste von der API laden."$json$::jsonb),
  ('pt-BR', 'mods.enabled', $json$"Ligar {name}"$json$::jsonb),
  ('en', 'mods.enabled', $json$"Turn on {name}"$json$::jsonb),
  ('es', 'mods.enabled', $json$"Activar {name}"$json$::jsonb),
  ('zh-CN', 'mods.enabled', $json$"开启 {name}"$json$::jsonb),
  ('hi', 'mods.enabled', $json$"{name} चालू करें"$json$::jsonb),
  ('ar', 'mods.enabled', $json$"تفعيل {name}"$json$::jsonb),
  ('fr', 'mods.enabled', $json$"Activer {name}"$json$::jsonb),
  ('ru', 'mods.enabled', $json$"Включить {name}"$json$::jsonb),
  ('ja', 'mods.enabled', $json$"{name} をオンにする"$json$::jsonb),
  ('de', 'mods.enabled', $json$"{name} einschalten"$json$::jsonb),
  ('pt-BR', 'mods.origin.builtIn', $json$"Do app"$json$::jsonb),
  ('en', 'mods.origin.builtIn', $json$"Built in"$json$::jsonb),
  ('es', 'mods.origin.builtIn', $json$"De la app"$json$::jsonb),
  ('zh-CN', 'mods.origin.builtIn', $json$"内置"$json$::jsonb),
  ('hi', 'mods.origin.builtIn', $json$"बिल्ट-इन"$json$::jsonb),
  ('ar', 'mods.origin.builtIn', $json$"مضمّنة"$json$::jsonb),
  ('fr', 'mods.origin.builtIn', $json$"Intégré"$json$::jsonb),
  ('ru', 'mods.origin.builtIn', $json$"Встроенный"$json$::jsonb),
  ('ja', 'mods.origin.builtIn', $json$"組み込み"$json$::jsonb),
  ('de', 'mods.origin.builtIn', $json$"Mitgeliefert"$json$::jsonb),
  ('pt-BR', 'mods.origin.custom', $json$"Seu"$json$::jsonb),
  ('en', 'mods.origin.custom', $json$"Yours"$json$::jsonb),
  ('es', 'mods.origin.custom', $json$"Tuyo"$json$::jsonb),
  ('zh-CN', 'mods.origin.custom', $json$"我的"$json$::jsonb),
  ('hi', 'mods.origin.custom', $json$"आपका"$json$::jsonb),
  ('ar', 'mods.origin.custom', $json$"خاصتك"$json$::jsonb),
  ('fr', 'mods.origin.custom', $json$"À vous"$json$::jsonb),
  ('ru', 'mods.origin.custom', $json$"Ваш"$json$::jsonb),
  ('ja', 'mods.origin.custom', $json$"自分用"$json$::jsonb),
  ('de', 'mods.origin.custom', $json$"Eigener"$json$::jsonb),
  ('pt-BR', 'mods.locked', $json$"Fora do seu plano"$json$::jsonb),
  ('en', 'mods.locked', $json$"Not in your plan"$json$::jsonb),
  ('es', 'mods.locked', $json$"No está en tu plan"$json$::jsonb),
  ('zh-CN', 'mods.locked', $json$"不在你的套餐中"$json$::jsonb),
  ('hi', 'mods.locked', $json$"आपके प्लान में नहीं"$json$::jsonb),
  ('ar', 'mods.locked', $json$"ليست ضمن خطتك"$json$::jsonb),
  ('fr', 'mods.locked', $json$"Hors de votre offre"$json$::jsonb),
  ('ru', 'mods.locked', $json$"Нет в вашем тарифе"$json$::jsonb),
  ('ja', 'mods.locked', $json$"プランに含まれていません"$json$::jsonb),
  ('de', 'mods.locked', $json$"Nicht in Ihrem Tarif"$json$::jsonb),
  ('pt-BR', 'mods.configure', $json$"Configurar"$json$::jsonb),
  ('en', 'mods.configure', $json$"Configure"$json$::jsonb),
  ('es', 'mods.configure', $json$"Configurar"$json$::jsonb),
  ('zh-CN', 'mods.configure', $json$"配置"$json$::jsonb),
  ('hi', 'mods.configure', $json$"कॉन्फ़िगर करें"$json$::jsonb),
  ('ar', 'mods.configure', $json$"إعداد"$json$::jsonb),
  ('fr', 'mods.configure', $json$"Configurer"$json$::jsonb),
  ('ru', 'mods.configure', $json$"Настроить"$json$::jsonb),
  ('ja', 'mods.configure', $json$"設定"$json$::jsonb),
  ('de', 'mods.configure', $json$"Konfigurieren"$json$::jsonb),
  ('pt-BR', 'mods.remove', $json$"Excluir mod"$json$::jsonb),
  ('en', 'mods.remove', $json$"Delete mod"$json$::jsonb),
  ('es', 'mods.remove', $json$"Eliminar mod"$json$::jsonb),
  ('zh-CN', 'mods.remove', $json$"删除模组"$json$::jsonb),
  ('hi', 'mods.remove', $json$"मॉड हटाएँ"$json$::jsonb),
  ('ar', 'mods.remove', $json$"حذف الإضافة"$json$::jsonb),
  ('fr', 'mods.remove', $json$"Supprimer le mod"$json$::jsonb),
  ('ru', 'mods.remove', $json$"Удалить мод"$json$::jsonb),
  ('ja', 'mods.remove', $json$"Mod を削除"$json$::jsonb),
  ('de', 'mods.remove', $json$"Mod löschen"$json$::jsonb),
  ('pt-BR', 'mods.remove.named', $json$"Excluir {name}"$json$::jsonb),
  ('en', 'mods.remove.named', $json$"Delete {name}"$json$::jsonb),
  ('es', 'mods.remove.named', $json$"Eliminar {name}"$json$::jsonb),
  ('zh-CN', 'mods.remove.named', $json$"删除 {name}"$json$::jsonb),
  ('hi', 'mods.remove.named', $json$"{name} हटाएँ"$json$::jsonb),
  ('ar', 'mods.remove.named', $json$"حذف {name}"$json$::jsonb),
  ('fr', 'mods.remove.named', $json$"Supprimer {name}"$json$::jsonb),
  ('ru', 'mods.remove.named', $json$"Удалить {name}"$json$::jsonb),
  ('ja', 'mods.remove.named', $json$"{name} を削除"$json$::jsonb),
  ('de', 'mods.remove.named', $json$"{name} löschen"$json$::jsonb),
  ('pt-BR', 'mods.remove.title', $json$"Excluir {name}?"$json$::jsonb),
  ('en', 'mods.remove.title', $json$"Delete {name}?"$json$::jsonb),
  ('es', 'mods.remove.title', $json$"¿Eliminar {name}?"$json$::jsonb),
  ('zh-CN', 'mods.remove.title', $json$"删除 {name}？"$json$::jsonb),
  ('hi', 'mods.remove.title', $json$"{name} हटाएँ?"$json$::jsonb),
  ('ar', 'mods.remove.title', $json$"حذف {name}؟"$json$::jsonb),
  ('fr', 'mods.remove.title', $json$"Supprimer {name} ?"$json$::jsonb),
  ('ru', 'mods.remove.title', $json$"Удалить {name}?"$json$::jsonb),
  ('ja', 'mods.remove.title', $json$"{name} を削除しますか？"$json$::jsonb),
  ('de', 'mods.remove.title', $json$"{name} löschen?"$json$::jsonb),
  ('pt-BR', 'mods.remove.description', $json$"O mod e os modelos dele saem da configuração quando você salvar, e a chave de API dele é apagada deste computador. Os chats guardam o que ele já respondeu."$json$::jsonb),
  ('en', 'mods.remove.description', $json$"The mod and its models leave the settings when you save, and its API key is erased from this computer. Chats keep what it already answered."$json$::jsonb),
  ('es', 'mods.remove.description', $json$"El mod y sus modelos salen de la configuración cuando guardas, y su clave de API se borra de este equipo. Los chats conservan lo que ya respondió."$json$::jsonb),
  ('zh-CN', 'mods.remove.description', $json$"保存后，该模组及其模型将从设置中移除，其 API 密钥也会从本机删除。聊天中保留它已给出的回答。"$json$::jsonb),
  ('hi', 'mods.remove.description', $json$"सहेजने पर मॉड और उसके मॉडल सेटिंग्स से हट जाते हैं, और उसकी API कुंजी इस कंप्यूटर से मिटा दी जाती है। चैट में उसके दिए जवाब बने रहते हैं।"$json$::jsonb),
  ('ar', 'mods.remove.description', $json$"تخرج الإضافة ونماذجها من الإعدادات عند الحفظ، ويُمسح مفتاح API الخاص بها من هذا الجهاز. تحتفظ الدردشات بما أجابت به من قبل."$json$::jsonb),
  ('fr', 'mods.remove.description', $json$"Le mod et ses modèles quittent la configuration quand vous enregistrez, et sa clé d’API est effacée de cet ordinateur. Les chats gardent ce qu’il a déjà répondu."$json$::jsonb),
  ('ru', 'mods.remove.description', $json$"Мод и его модели исчезнут из настроек после сохранения, а его ключ API будет стёрт с этого компьютера. В чатах останется то, что он уже ответил."$json$::jsonb),
  ('ja', 'mods.remove.description', $json$"保存すると Mod とそのモデルは設定から外れ、API キーはこのコンピューターから消去されます。チャットにはすでに答えた内容が残ります。"$json$::jsonb),
  ('de', 'mods.remove.description', $json$"Der Mod und seine Modelle verlassen die Einstellungen, sobald Sie speichern, und sein API-Schlüssel wird von diesem Computer gelöscht. Chats behalten, was er bereits geantwortet hat."$json$::jsonb),
  ('pt-BR', 'mods.yours', $json$"Seus mods"$json$::jsonb),
  ('en', 'mods.yours', $json$"Your mods"$json$::jsonb),
  ('es', 'mods.yours', $json$"Tus mods"$json$::jsonb),
  ('zh-CN', 'mods.yours', $json$"我的模组"$json$::jsonb),
  ('hi', 'mods.yours', $json$"आपके मॉड"$json$::jsonb),
  ('ar', 'mods.yours', $json$"إضافاتك"$json$::jsonb),
  ('fr', 'mods.yours', $json$"Vos mods"$json$::jsonb),
  ('ru', 'mods.yours', $json$"Ваши моды"$json$::jsonb),
  ('ja', 'mods.yours', $json$"自分の Mod"$json$::jsonb),
  ('de', 'mods.yours', $json$"Ihre Mods"$json$::jsonb),
  ('pt-BR', 'mods.empty', $json$"Nenhum mod seu ainda. Criar mod liga outro LLM: um programa de linha de comando ou uma API."$json$::jsonb),
  ('en', 'mods.empty', $json$"No mod of your own yet. Create mod connects another LLM: a command-line program or an API."$json$::jsonb),
  ('es', 'mods.empty', $json$"Todavía no tienes mods propios. Crear mod conecta otro LLM: un programa de línea de comandos o una API."$json$::jsonb),
  ('zh-CN', 'mods.empty', $json$"还没有自己的模组。“创建模组”可接入另一个 LLM：命令行程序或 API。"$json$::jsonb),
  ('hi', 'mods.empty', $json$"अभी आपका कोई मॉड नहीं है। मॉड बनाएँ से कोई दूसरा LLM जुड़ता है: कमांड-लाइन प्रोग्राम या API।"$json$::jsonb),
  ('ar', 'mods.empty', $json$"لا توجد إضافات خاصة بك بعد. «إنشاء إضافة» يربط نموذج LLM آخر: برنامج سطر أوامر أو واجهة API."$json$::jsonb),
  ('fr', 'mods.empty', $json$"Aucun mod à vous pour l’instant. Créer un mod connecte un autre LLM : un programme en ligne de commande ou une API."$json$::jsonb),
  ('ru', 'mods.empty', $json$"Своих модов пока нет. «Создать мод» подключает другую LLM: программу командной строки или API."$json$::jsonb),
  ('ja', 'mods.empty', $json$"自分の Mod はまだありません。「Mod を作成」で別の LLM（コマンドラインプログラムまたは API）をつなげます。"$json$::jsonb),
  ('de', 'mods.empty', $json$"Noch kein eigener Mod. Mod erstellen bindet ein weiteres LLM an: ein Kommandozeilenprogramm oder eine API."$json$::jsonb),
  ('pt-BR', 'mods.empty.locked', $json$"Criar mods não está no seu plano."$json$::jsonb),
  ('en', 'mods.empty.locked', $json$"Creating mods is not in your plan."$json$::jsonb),
  ('es', 'mods.empty.locked', $json$"Crear mods no está en tu plan."$json$::jsonb),
  ('zh-CN', 'mods.empty.locked', $json$"你的套餐不包含创建模组。"$json$::jsonb),
  ('hi', 'mods.empty.locked', $json$"मॉड बनाना आपके प्लान में नहीं है।"$json$::jsonb),
  ('ar', 'mods.empty.locked', $json$"إنشاء الإضافات ليس ضمن خطتك."$json$::jsonb),
  ('fr', 'mods.empty.locked', $json$"La création de mods n’est pas dans votre offre."$json$::jsonb),
  ('ru', 'mods.empty.locked', $json$"Создание модов не входит в ваш тариф."$json$::jsonb),
  ('ja', 'mods.empty.locked', $json$"Mod の作成はプランに含まれていません。"$json$::jsonb),
  ('de', 'mods.empty.locked', $json$"Mods erstellen ist nicht in Ihrem Tarif."$json$::jsonb),
  ('pt-BR', 'mods.full', $json$"Até {max} mods seus."$json$::jsonb),
  ('en', 'mods.full', $json$"Up to {max} mods of your own."$json$::jsonb),
  ('es', 'mods.full', $json$"Hasta {max} mods propios."$json$::jsonb),
  ('zh-CN', 'mods.full', $json$"最多 {max} 个自己的模组。"$json$::jsonb),
  ('hi', 'mods.full', $json$"आपके अधिकतम {max} मॉड।"$json$::jsonb),
  ('ar', 'mods.full', $json$"حتى {max} إضافات خاصة بك."$json$::jsonb),
  ('fr', 'mods.full', $json$"Jusqu’à {max} mods à vous."$json$::jsonb),
  ('ru', 'mods.full', $json$"До {max} своих модов."$json$::jsonb),
  ('ja', 'mods.full', $json$"自分の Mod は最大 {max} 個です。"$json$::jsonb),
  ('de', 'mods.full', $json$"Bis zu {max} eigene Mods."$json$::jsonb),
  ('pt-BR', 'mods.notes', $json$"Os mods são salvos com o resto da configuração deste ambiente e sincronizam entre os seus computadores; as chaves de API ficam neste computador. Nos projetos de uma organização, a política de LLM dela vale para todo mod: quando ela lista os agentes permitidos, os mods que você cria ficam desligados lá."$json$::jsonb),
  ('en', 'mods.notes', $json$"Mods are saved with the other settings of this environment and sync between your computers; API keys stay on this computer. In an organization's projects its LLM policy applies to every mod: when it lists the allowed agents, the mods you create stay off there."$json$::jsonb),
  ('es', 'mods.notes', $json$"Los mods se guardan con el resto de la configuración de este entorno y se sincronizan entre tus equipos; las claves de API se quedan en este equipo. En los proyectos de una organización, su política de LLM se aplica a todo mod: cuando enumera los agentes permitidos, los mods que creas quedan desactivados allí."$json$::jsonb),
  ('zh-CN', 'mods.notes', $json$"模组与此环境的其他设置一起保存，并在你的各台电脑间同步；API 密钥只保留在本机。在组织的项目中，其 LLM 策略适用于每个模组：当策略列出允许的代理时，你创建的模组在那里保持关闭。"$json$::jsonb),
  ('hi', 'mods.notes', $json$"मॉड इस परिवेश की बाकी सेटिंग्स के साथ सहेजे जाते हैं और आपके कंप्यूटरों के बीच सिंक होते हैं; API कुंजियाँ इसी कंप्यूटर पर रहती हैं। किसी संगठन के प्रोजेक्ट में उसकी LLM नीति हर मॉड पर लागू होती है: जब वह अनुमत एजेंटों की सूची देती है, तो आपके बनाए मॉड वहाँ बंद रहते हैं।"$json$::jsonb),
  ('ar', 'mods.notes', $json$"تُحفظ الإضافات مع بقية إعدادات هذه البيئة وتُزامَن بين أجهزتك؛ وتبقى مفاتيح API على هذا الجهاز. في مشاريع المؤسسة تسري سياسة LLM الخاصة بها على كل إضافة: عندما تحدد الوكلاء المسموح بهم، تبقى الإضافات التي تنشئها معطّلة هناك."$json$::jsonb),
  ('fr', 'mods.notes', $json$"Les mods sont enregistrés avec le reste de la configuration de cet environnement et se synchronisent entre vos ordinateurs ; les clés d’API restent sur cet ordinateur. Dans les projets d’une organisation, sa politique LLM s’applique à chaque mod : quand elle liste les agents autorisés, les mods que vous créez y restent désactivés."$json$::jsonb),
  ('ru', 'mods.notes', $json$"Моды сохраняются вместе с остальными настройками этой среды и синхронизируются между вашими компьютерами; ключи API остаются на этом компьютере. В проектах организации её политика LLM действует на каждый мод: если в ней перечислены разрешённые агенты, созданные вами моды там отключены."$json$::jsonb),
  ('ja', 'mods.notes', $json$"Mod はこの環境のほかの設定と一緒に保存され、お使いのコンピューター間で同期されます。API キーはこのコンピューターに残ります。組織のプロジェクトでは、その LLM ポリシーがすべての Mod に適用されます。ポリシーが許可するエージェントを列挙している場合、自分で作成した Mod はそこではオフになります。"$json$::jsonb),
  ('de', 'mods.notes', $json$"Mods werden mit den übrigen Einstellungen dieser Umgebung gespeichert und zwischen Ihren Computern synchronisiert; API-Schlüssel bleiben auf diesem Computer. In den Projekten einer Organisation gilt deren LLM-Richtlinie für jeden Mod: Wenn sie die erlaubten Agenten auflistet, bleiben Ihre eigenen Mods dort ausgeschaltet."$json$::jsonb),
  ('pt-BR', 'mods.tagline.cli', $json$"Seu mod · linha de comando"$json$::jsonb),
  ('en', 'mods.tagline.cli', $json$"Your mod · command line"$json$::jsonb),
  ('es', 'mods.tagline.cli', $json$"Tu mod · línea de comandos"$json$::jsonb),
  ('zh-CN', 'mods.tagline.cli', $json$"我的模组 · 命令行"$json$::jsonb),
  ('hi', 'mods.tagline.cli', $json$"आपका मॉड · कमांड लाइन"$json$::jsonb),
  ('ar', 'mods.tagline.cli', $json$"إضافتك · سطر الأوامر"$json$::jsonb),
  ('fr', 'mods.tagline.cli', $json$"Votre mod · ligne de commande"$json$::jsonb),
  ('ru', 'mods.tagline.cli', $json$"Ваш мод · командная строка"$json$::jsonb),
  ('ja', 'mods.tagline.cli', $json$"自分の Mod · コマンドライン"$json$::jsonb),
  ('de', 'mods.tagline.cli', $json$"Ihr Mod · Kommandozeile"$json$::jsonb),
  ('pt-BR', 'mods.tagline.api', $json$"Seu mod · API"$json$::jsonb),
  ('en', 'mods.tagline.api', $json$"Your mod · API"$json$::jsonb),
  ('es', 'mods.tagline.api', $json$"Tu mod · API"$json$::jsonb),
  ('zh-CN', 'mods.tagline.api', $json$"我的模组 · API"$json$::jsonb),
  ('hi', 'mods.tagline.api', $json$"आपका मॉड · API"$json$::jsonb),
  ('ar', 'mods.tagline.api', $json$"إضافتك · API"$json$::jsonb),
  ('fr', 'mods.tagline.api', $json$"Votre mod · API"$json$::jsonb),
  ('ru', 'mods.tagline.api', $json$"Ваш мод · API"$json$::jsonb),
  ('ja', 'mods.tagline.api', $json$"自分の Mod · API"$json$::jsonb),
  ('de', 'mods.tagline.api', $json$"Ihr Mod · API"$json$::jsonb),
  ('pt-BR', 'mods.refresh.none', $json$"Um mod de linha de comando não lista modelos: adicione os ids que ele aceita."$json$::jsonb),
  ('en', 'mods.refresh.none', $json$"A command-line mod does not list models: add the ids it accepts."$json$::jsonb),
  ('es', 'mods.refresh.none', $json$"Un mod de línea de comandos no enumera modelos: añade los ids que acepta."$json$::jsonb),
  ('zh-CN', 'mods.refresh.none', $json$"命令行模组不会列出模型：请添加它接受的模型 ID。"$json$::jsonb),
  ('hi', 'mods.refresh.none', $json$"कमांड-लाइन मॉड मॉडलों की सूची नहीं देता: वे id जोड़ें जिन्हें वह स्वीकार करता है।"$json$::jsonb),
  ('ar', 'mods.refresh.none', $json$"إضافة سطر الأوامر لا تعرض قائمة نماذج: أضف المعرّفات التي تقبلها."$json$::jsonb),
  ('fr', 'mods.refresh.none', $json$"Un mod en ligne de commande ne liste pas de modèles : ajoutez les ids qu’il accepte."$json$::jsonb),
  ('ru', 'mods.refresh.none', $json$"Мод командной строки не выдаёт список моделей: добавьте id, которые он принимает."$json$::jsonb),
  ('ja', 'mods.refresh.none', $json$"コマンドラインの Mod はモデルを一覧表示しません。受け付ける ID を追加してください。"$json$::jsonb),
  ('de', 'mods.refresh.none', $json$"Ein Kommandozeilen-Mod listet keine Modelle: Fügen Sie die IDs hinzu, die er annimmt."$json$::jsonb),
  ('pt-BR', 'mods.tooMany', $json$"Até {max} mods seus por ambiente."$json$::jsonb),
  ('en', 'mods.tooMany', $json$"Up to {max} mods of your own per environment."$json$::jsonb),
  ('es', 'mods.tooMany', $json$"Hasta {max} mods propios por entorno."$json$::jsonb),
  ('zh-CN', 'mods.tooMany', $json$"每个环境最多 {max} 个自己的模组。"$json$::jsonb),
  ('hi', 'mods.tooMany', $json$"हर परिवेश में आपके अधिकतम {max} मॉड।"$json$::jsonb),
  ('ar', 'mods.tooMany', $json$"حتى {max} إضافات خاصة بك في كل بيئة."$json$::jsonb),
  ('fr', 'mods.tooMany', $json$"Jusqu’à {max} mods à vous par environnement."$json$::jsonb),
  ('ru', 'mods.tooMany', $json$"До {max} своих модов в одной среде."$json$::jsonb),
  ('ja', 'mods.tooMany', $json$"自分の Mod は環境ごとに最大 {max} 個です。"$json$::jsonb),
  ('de', 'mods.tooMany', $json$"Bis zu {max} eigene Mods pro Umgebung."$json$::jsonb),
  ('pt-BR', 'mods.nameInvalid', $json$"Dê ao mod um nome de até {max} caracteres."$json$::jsonb),
  ('en', 'mods.nameInvalid', $json$"Give the mod a name of up to {max} characters."$json$::jsonb),
  ('es', 'mods.nameInvalid', $json$"Ponle al mod un nombre de hasta {max} caracteres."$json$::jsonb),
  ('zh-CN', 'mods.nameInvalid', $json$"请为模组取一个不超过 {max} 个字符的名称。"$json$::jsonb),
  ('hi', 'mods.nameInvalid', $json$"मॉड को अधिकतम {max} अक्षरों का नाम दें।"$json$::jsonb),
  ('ar', 'mods.nameInvalid', $json$"أعطِ الإضافة اسمًا لا يتجاوز {max} حرفًا."$json$::jsonb),
  ('fr', 'mods.nameInvalid', $json$"Donnez au mod un nom de {max} caractères au plus."$json$::jsonb),
  ('ru', 'mods.nameInvalid', $json$"Дайте моду название длиной до {max} символов."$json$::jsonb),
  ('ja', 'mods.nameInvalid', $json$"Mod には {max} 文字以内の名前を付けてください。"$json$::jsonb),
  ('de', 'mods.nameInvalid', $json$"Geben Sie dem Mod einen Namen mit höchstens {max} Zeichen."$json$::jsonb),
  ('pt-BR', 'mods.argsTooMany', $json$"A linha de comando de {name} aceita no máximo {max} argumentos."$json$::jsonb),
  ('en', 'mods.argsTooMany', $json$"The command line of {name} takes at most {max} arguments."$json$::jsonb),
  ('es', 'mods.argsTooMany', $json$"La línea de comandos de {name} admite como máximo {max} argumentos."$json$::jsonb),
  ('zh-CN', 'mods.argsTooMany', $json$"{name} 的命令行最多接受 {max} 个参数。"$json$::jsonb),
  ('hi', 'mods.argsTooMany', $json$"{name} की कमांड लाइन में अधिकतम {max} आर्ग्युमेंट हो सकते हैं।"$json$::jsonb),
  ('ar', 'mods.argsTooMany', $json$"يقبل سطر أوامر {name} ‏{max} وسيطًا على الأكثر."$json$::jsonb),
  ('fr', 'mods.argsTooMany', $json$"La ligne de commande de {name} accepte au plus {max} arguments."$json$::jsonb),
  ('ru', 'mods.argsTooMany', $json$"Командная строка {name} принимает не более {max} аргументов."$json$::jsonb),
  ('ja', 'mods.argsTooMany', $json$"{name} のコマンドラインの引数は最大 {max} 個です。"$json$::jsonb),
  ('de', 'mods.argsTooMany', $json$"Die Kommandozeile von {name} nimmt höchstens {max} Argumente an."$json$::jsonb),
  ('pt-BR', 'mods.argInvalid', $json$"A linha de comando de {name} tem um argumento vazio, uma quebra de linha ou um argumento longo demais."$json$::jsonb),
  ('en', 'mods.argInvalid', $json$"The command line of {name} has an empty argument, a line break or an argument that is too long."$json$::jsonb),
  ('es', 'mods.argInvalid', $json$"La línea de comandos de {name} tiene un argumento vacío, un salto de línea o un argumento demasiado largo."$json$::jsonb),
  ('zh-CN', 'mods.argInvalid', $json$"{name} 的命令行中有空参数、换行或过长的参数。"$json$::jsonb),
  ('hi', 'mods.argInvalid', $json$"{name} की कमांड लाइन में कोई खाली आर्ग्युमेंट, लाइन ब्रेक या बहुत लंबा आर्ग्युमेंट है।"$json$::jsonb),
  ('ar', 'mods.argInvalid', $json$"في سطر أوامر {name} وسيط فارغ أو فاصل أسطر أو وسيط أطول من اللازم."$json$::jsonb),
  ('fr', 'mods.argInvalid', $json$"La ligne de commande de {name} contient un argument vide, un saut de ligne ou un argument trop long."$json$::jsonb),
  ('ru', 'mods.argInvalid', $json$"В командной строке {name} есть пустой аргумент, перевод строки или слишком длинный аргумент."$json$::jsonb),
  ('ja', 'mods.argInvalid', $json$"{name} のコマンドラインに空の引数、改行、または長すぎる引数があります。"$json$::jsonb),
  ('de', 'mods.argInvalid', $json$"Die Kommandozeile von {name} enthält ein leeres Argument, einen Zeilenumbruch oder ein zu langes Argument."$json$::jsonb),
  ('pt-BR', 'mods.placeholder', $json$"A linha de comando de {name} usa {token}: só {model} e {prompt} (sozinho num argumento) são aceitos."$json$::jsonb),
  ('en', 'mods.placeholder', $json$"The command line of {name} uses {token}: only {model} and {prompt} (alone in an argument) are accepted."$json$::jsonb),
  ('es', 'mods.placeholder', $json$"La línea de comandos de {name} usa {token}: solo se aceptan {model} y {prompt} (solo en un argumento)."$json$::jsonb),
  ('zh-CN', 'mods.placeholder', $json$"{name} 的命令行使用了 {token}：只接受 {model} 和 {prompt}（单独作为一个参数）。"$json$::jsonb),
  ('hi', 'mods.placeholder', $json$"{name} की कमांड लाइन {token} इस्तेमाल करती है: केवल {model} और {prompt} (अकेले एक आर्ग्युमेंट में) स्वीकार हैं।"$json$::jsonb),
  ('ar', 'mods.placeholder', $json$"يستخدم سطر أوامر {name} ‏{token}: لا يُقبل إلا {model} و{prompt} (منفردًا في وسيط)."$json$::jsonb),
  ('fr', 'mods.placeholder', $json$"La ligne de commande de {name} utilise {token} : seuls {model} et {prompt} (seul dans un argument) sont acceptés."$json$::jsonb),
  ('ru', 'mods.placeholder', $json$"В командной строке {name} используется {token}: допустимы только {model} и {prompt} (отдельным аргументом)."$json$::jsonb),
  ('ja', 'mods.placeholder', $json$"{name} のコマンドラインで {token} が使われています。使えるのは {model} と {prompt}（単独の引数として）だけです。"$json$::jsonb),
  ('de', 'mods.placeholder', $json$"Die Kommandozeile von {name} verwendet {token}: Erlaubt sind nur {model} und {prompt} (allein in einem Argument)."$json$::jsonb),
  ('pt-BR', 'mods.planRequired', $json$"{name} escreve no projeto e precisa de uma linha de comando de planejamento que não escreva."$json$::jsonb),
  ('en', 'mods.planRequired', $json$"{name} writes to the project and needs a planning command line that does not."$json$::jsonb),
  ('es', 'mods.planRequired', $json$"{name} escribe en el proyecto y necesita una línea de comandos de planificación que no escriba."$json$::jsonb),
  ('zh-CN', 'mods.planRequired', $json$"{name} 会写入项目，需要一条不写入项目的规划命令行。"$json$::jsonb),
  ('hi', 'mods.planRequired', $json$"{name} प्रोजेक्ट में लिखता है और उसे योजना की ऐसी कमांड लाइन चाहिए जो न लिखे।"$json$::jsonb),
  ('ar', 'mods.planRequired', $json$"{name} يكتب في المشروع ويحتاج إلى سطر أوامر للتخطيط لا يكتب فيه."$json$::jsonb),
  ('fr', 'mods.planRequired', $json$"{name} écrit dans le projet et a besoin d’une ligne de commande de planification qui n’écrit pas."$json$::jsonb),
  ('ru', 'mods.planRequired', $json$"{name} пишет в проект, и ему нужна командная строка для планирования, которая в проект не пишет."$json$::jsonb),
  ('ja', 'mods.planRequired', $json$"{name} はプロジェクトに書き込むため、書き込まない計画用のコマンドラインが必要です。"$json$::jsonb),
  ('de', 'mods.planRequired', $json$"{name} schreibt ins Projekt und braucht eine Kommandozeile für die Planung, die das nicht tut."$json$::jsonb),
  ('pt-BR', 'mods.protocolInvalid', $json$"{name}: escolha o protocolo compatível com OpenAI ou o da Anthropic."$json$::jsonb),
  ('en', 'mods.protocolInvalid', $json$"{name}: choose the OpenAI-compatible or the Anthropic protocol."$json$::jsonb),
  ('es', 'mods.protocolInvalid', $json$"{name}: elige el protocolo compatible con OpenAI o el de Anthropic."$json$::jsonb),
  ('zh-CN', 'mods.protocolInvalid', $json$"{name}：请选择兼容 OpenAI 的协议或 Anthropic 协议。"$json$::jsonb),
  ('hi', 'mods.protocolInvalid', $json$"{name}: OpenAI-संगत या Anthropic प्रोटोकॉल चुनें।"$json$::jsonb),
  ('ar', 'mods.protocolInvalid', $json$"{name}: اختر البروتوكول المتوافق مع OpenAI أو بروتوكول Anthropic."$json$::jsonb),
  ('fr', 'mods.protocolInvalid', $json$"{name} : choisissez le protocole compatible OpenAI ou celui d’Anthropic."$json$::jsonb),
  ('ru', 'mods.protocolInvalid', $json$"{name}: выберите протокол, совместимый с OpenAI, или протокол Anthropic."$json$::jsonb),
  ('ja', 'mods.protocolInvalid', $json$"{name}：OpenAI 互換または Anthropic のプロトコルを選んでください。"$json$::jsonb),
  ('de', 'mods.protocolInvalid', $json$"{name}: Wählen Sie das OpenAI-kompatible oder das Anthropic-Protokoll."$json$::jsonb),
  ('pt-BR', 'mods.urlRequired', $json$"{name} precisa do endereço da API."$json$::jsonb),
  ('en', 'mods.urlRequired', $json$"{name} needs the API address."$json$::jsonb),
  ('es', 'mods.urlRequired', $json$"{name} necesita la dirección de la API."$json$::jsonb),
  ('zh-CN', 'mods.urlRequired', $json$"{name} 需要 API 地址。"$json$::jsonb),
  ('hi', 'mods.urlRequired', $json$"{name} को API का पता चाहिए।"$json$::jsonb),
  ('ar', 'mods.urlRequired', $json$"{name} يحتاج إلى عنوان الواجهة البرمجية."$json$::jsonb),
  ('fr', 'mods.urlRequired', $json$"{name} a besoin de l’adresse de l’API."$json$::jsonb),
  ('ru', 'mods.urlRequired', $json$"{name}: нужен адрес API."$json$::jsonb),
  ('ja', 'mods.urlRequired', $json$"{name} には API のアドレスが必要です。"$json$::jsonb),
  ('de', 'mods.urlRequired', $json$"{name} braucht die API-Adresse."$json$::jsonb),
  ('pt-BR', 'mods.kindInvalid', $json$"{name}: um mod é de linha de comando ou de API."$json$::jsonb),
  ('en', 'mods.kindInvalid', $json$"{name}: a mod is either command line or API."$json$::jsonb),
  ('es', 'mods.kindInvalid', $json$"{name}: un mod es de línea de comandos o de API."$json$::jsonb),
  ('zh-CN', 'mods.kindInvalid', $json$"{name}：模组只能是命令行或 API 之一。"$json$::jsonb),
  ('hi', 'mods.kindInvalid', $json$"{name}: मॉड या तो कमांड लाइन होता है या API।"$json$::jsonb),
  ('ar', 'mods.kindInvalid', $json$"{name}: الإضافة إما سطر أوامر وإما API."$json$::jsonb),
  ('fr', 'mods.kindInvalid', $json$"{name} : un mod est en ligne de commande ou par API."$json$::jsonb),
  ('ru', 'mods.kindInvalid', $json$"{name}: мод работает либо через командную строку, либо через API."$json$::jsonb),
  ('ja', 'mods.kindInvalid', $json$"{name}：Mod はコマンドラインか API のどちらかです。"$json$::jsonb),
  ('de', 'mods.kindInvalid', $json$"{name}: Ein Mod ist entweder Kommandozeile oder API."$json$::jsonb),
  ('pt-BR', 'generalChats.empty', $json$"Nenhum chat geral ainda. O + começa o primeiro."$json$::jsonb),
  ('en', 'generalChats.empty', $json$"No general chat yet. + starts the first one."$json$::jsonb),
  ('es', 'generalChats.empty', $json$"Todavía no hay chats generales. + empieza el primero."$json$::jsonb),
  ('zh-CN', 'generalChats.empty', $json$"还没有通用聊天。点 + 开始第一个。"$json$::jsonb),
  ('hi', 'generalChats.empty', $json$"अभी कोई सामान्य चैट नहीं। + से पहली शुरू करें।"$json$::jsonb),
  ('ar', 'generalChats.empty', $json$"لا توجد محادثات عامة بعد. + يبدأ أولاها."$json$::jsonb),
  ('fr', 'generalChats.empty', $json$"Aucun chat général pour l’instant. + lance le premier."$json$::jsonb),
  ('ru', 'generalChats.empty', $json$"Общих чатов пока нет. + начинает первый."$json$::jsonb),
  ('ja', 'generalChats.empty', $json$"総合チャットはまだありません。+ で最初のチャットを始めます。"$json$::jsonb),
  ('de', 'generalChats.empty', $json$"Noch kein allgemeiner Chat. + startet den ersten."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.llmMods.title', $json$"As integrações com LLM são mods"$json$::jsonb),
  ('en', 'whatsNew.item.llmMods.title', $json$"LLM integrations are mods"$json$::jsonb),
  ('es', 'whatsNew.item.llmMods.title', $json$"Las integraciones con LLM son mods"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.llmMods.title', $json$"LLM 集成变成了模组"$json$::jsonb),
  ('hi', 'whatsNew.item.llmMods.title', $json$"LLM इंटीग्रेशन अब मॉड हैं"$json$::jsonb),
  ('ar', 'whatsNew.item.llmMods.title', $json$"تكاملات LLM أصبحت إضافات"$json$::jsonb),
  ('fr', 'whatsNew.item.llmMods.title', $json$"Les intégrations LLM sont des mods"$json$::jsonb),
  ('ru', 'whatsNew.item.llmMods.title', $json$"Интеграции с LLM стали модами"$json$::jsonb),
  ('ja', 'whatsNew.item.llmMods.title', $json$"LLM 連携が Mod に"$json$::jsonb),
  ('de', 'whatsNew.item.llmMods.title', $json$"LLM-Anbindungen sind Mods"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter e LiteLLM agora são mods, listados na nova aba Configuração › Mods, onde Criar mod liga outro LLM: um programa de linha de comando neste computador (com {model} e {prompt} na linha de comando) ou uma API compatível com OpenAI ou Anthropic. Os seus mods ganham aba, modelos e aprovação de MCP próprios, sincronizam com a sua configuração e seguem a política de LLM da organização."$json$::jsonb),
  ('en', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter and LiteLLM are now mods, listed in the new Settings › Mods tab, where Create mod connects another LLM: a command-line program on this computer (with {model} and {prompt} in its command line) or an API compatible with OpenAI or Anthropic. Your mods get their own tab, models and MCP approval, sync with your settings and follow the organization's LLM policy."$json$::jsonb),
  ('es', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter y LiteLLM ahora son mods, enumerados en la nueva pestaña Configuración › Mods, donde Crear mod conecta otro LLM: un programa de línea de comandos en este equipo (con {model} y {prompt} en su línea de comandos) o una API compatible con OpenAI o Anthropic. Tus mods tienen su propia pestaña, sus modelos y su aprobación de MCP, se sincronizan con tu configuración y siguen la política de LLM de la organización."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.llmMods.detail', $json$"Claude Code、Codex、Copilot、Cursor、Kilo Code、OpenRouter 和 LiteLLM 现在都是模组，列在新的“设置 › 模组”标签页中，在那里“创建模组”可接入另一个 LLM：本机上的命令行程序（命令行中使用 {model} 和 {prompt}）或兼容 OpenAI 或 Anthropic 的 API。你的模组拥有自己的标签页、模型和 MCP 批准，随你的设置同步，并遵循组织的 LLM 策略。"$json$::jsonb),
  ('hi', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter और LiteLLM अब मॉड हैं, जो नए सेटिंग्स › मॉड टैब में दिखते हैं, जहाँ मॉड बनाएँ से कोई दूसरा LLM जुड़ता है: इस कंप्यूटर पर कोई कमांड-लाइन प्रोग्राम (कमांड लाइन में {model} और {prompt} के साथ) या OpenAI या Anthropic के साथ संगत API। आपके मॉड को अपना टैब, मॉडल और MCP अनुमोदन मिलता है, वे आपकी सेटिंग्स के साथ सिंक होते हैं और संगठन की LLM नीति का पालन करते हैं।"$json$::jsonb),
  ('ar', 'whatsNew.item.llmMods.detail', $json$"أصبحت Claude Code وCodex وCopilot وCursor وKilo Code وOpenRouter وLiteLLM إضافات، مدرجة في التبويب الجديد الإعدادات › الإضافات، حيث يربط «إنشاء إضافة» نموذج LLM آخر: برنامج سطر أوامر على هذا الجهاز (مع {model} و{prompt} في سطر أوامره) أو واجهة API متوافقة مع OpenAI أو Anthropic. تحصل إضافاتك على تبويبها ونماذجها وموافقة MCP الخاصة بها، وتُزامَن مع إعداداتك وتتبع سياسة LLM للمؤسسة."$json$::jsonb),
  ('fr', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter et LiteLLM sont désormais des mods, listés dans le nouvel onglet Configuration › Mods, où Créer un mod connecte un autre LLM : un programme en ligne de commande sur cet ordinateur (avec {model} et {prompt} dans sa ligne de commande) ou une API compatible avec OpenAI ou Anthropic. Vos mods ont leur propre onglet, leurs modèles et leur approbation MCP, se synchronisent avec votre configuration et suivent la politique LLM de l’organisation."$json$::jsonb),
  ('ru', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter и LiteLLM теперь моды и перечислены на новой вкладке Настройки › Моды, где «Создать мод» подключает другую LLM: программу командной строки на этом компьютере (с {model} и {prompt} в командной строке) или API, совместимый с OpenAI или Anthropic. У ваших модов своя вкладка, свои модели и своё одобрение MCP, они синхронизируются с вашими настройками и подчиняются политике LLM организации."$json$::jsonb),
  ('ja', 'whatsNew.item.llmMods.detail', $json$"Claude Code、Codex、Copilot、Cursor、Kilo Code、OpenRouter、LiteLLM は Mod になり、新しい 設定 › Mod タブに並びます。そこで「Mod を作成」から別の LLM をつなげます。このコンピューター上のコマンドラインプログラム（コマンドラインに {model} と {prompt}）か、OpenAI または Anthropic 互換の API です。自分の Mod には専用のタブ、モデル、MCP の承認があり、設定と同期され、組織の LLM ポリシーに従います。"$json$::jsonb),
  ('de', 'whatsNew.item.llmMods.detail', $json$"Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter und LiteLLM sind jetzt Mods und stehen im neuen Tab Einstellungen › Mods, wo Mod erstellen ein weiteres LLM anbindet: ein Kommandozeilenprogramm auf diesem Computer (mit {model} und {prompt} in seiner Kommandozeile) oder eine API, die mit OpenAI oder Anthropic kompatibel ist. Ihre Mods bekommen eigenen Tab, eigene Modelle und eigene MCP-Freigabe, synchronisieren sich mit Ihren Einstellungen und folgen der LLM-Richtlinie der Organisation."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.generalChatsColumn.title', $json$"Chats gerais ao lado do menu lateral"$json$::jsonb),
  ('en', 'whatsNew.item.generalChatsColumn.title', $json$"General chats beside the side menu"$json$::jsonb),
  ('es', 'whatsNew.item.generalChatsColumn.title', $json$"Chats generales junto al menú lateral"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.generalChatsColumn.title', $json$"通用聊天移到侧边菜单旁"$json$::jsonb),
  ('hi', 'whatsNew.item.generalChatsColumn.title', $json$"साइड मेनू के बगल में सामान्य चैट"$json$::jsonb),
  ('ar', 'whatsNew.item.generalChatsColumn.title', $json$"المحادثات العامة بجوار القائمة الجانبية"$json$::jsonb),
  ('fr', 'whatsNew.item.generalChatsColumn.title', $json$"Chats généraux à côté du menu latéral"$json$::jsonb),
  ('ru', 'whatsNew.item.generalChatsColumn.title', $json$"Общие чаты рядом с боковым меню"$json$::jsonb),
  ('ja', 'whatsNew.item.generalChatsColumn.title', $json$"総合チャットがサイドメニューの横に"$json$::jsonb),
  ('de', 'whatsNew.item.generalChatsColumn.title', $json$"Allgemeine Chats neben dem Seitenmenü"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.generalChatsColumn.detail', $json$"No ambiente de uma organização, os chats gerais dela agora têm uma coluna própria ao lado do menu lateral, visível em todas as telas, do mais recente para o mais antigo; o + começa outro. Eles saíram da página Projetos, que agora lista só os projetos dos repositórios."$json$::jsonb),
  ('en', 'whatsNew.item.generalChatsColumn.detail', $json$"In an organization's environment, its general chats now have their own column next to the side menu, visible on every screen, newest first; + starts another one. They left the Projects page, which now lists only the repository projects."$json$::jsonb),
  ('es', 'whatsNew.item.generalChatsColumn.detail', $json$"En el entorno de una organización, sus chats generales ahora tienen su propia columna junto al menú lateral, visible en todas las pantallas, del más reciente al más antiguo; + empieza otro. Salieron de la página Proyectos, que ahora enumera solo los proyectos de los repositorios."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.generalChatsColumn.detail', $json$"在组织的环境中，其通用聊天现在在侧边菜单旁有单独的一栏，在每个界面都可见，最新的在前；点 + 开始新的。它们已离开“项目”页面，该页面现在只列出各仓库的项目。"$json$::jsonb),
  ('hi', 'whatsNew.item.generalChatsColumn.detail', $json$"किसी संगठन के परिवेश में उसकी सामान्य चैट का अब साइड मेनू के बगल में अपना कॉलम है, जो हर स्क्रीन पर दिखता है, सबसे नई पहले; + से एक और शुरू होती है। वे प्रोजेक्ट पेज से हट गई हैं, जो अब केवल रिपॉज़िटरी के प्रोजेक्ट दिखाता है।"$json$::jsonb),
  ('ar', 'whatsNew.item.generalChatsColumn.detail', $json$"في بيئة المؤسسة، أصبح لمحادثاتها العامة عمود خاص بجوار القائمة الجانبية، ظاهر في كل الشاشات، والأحدث أولًا؛ و+ يبدأ محادثة أخرى. وقد خرجت من صفحة المشاريع التي صارت تعرض مشاريع المستودعات فقط."$json$::jsonb),
  ('fr', 'whatsNew.item.generalChatsColumn.detail', $json$"Dans l’environnement d’une organisation, ses chats généraux ont désormais leur propre colonne à côté du menu latéral, visible sur tous les écrans, du plus récent au plus ancien ; + en lance un autre. Ils ont quitté la page Projets, qui ne liste plus que les projets des dépôts."$json$::jsonb),
  ('ru', 'whatsNew.item.generalChatsColumn.detail', $json$"В среде организации её общие чаты теперь занимают отдельную колонку рядом с боковым меню, видимую на всех экранах, сначала самые новые; + начинает ещё один. Они ушли со страницы «Проекты», где теперь перечислены только проекты репозиториев."$json$::jsonb),
  ('ja', 'whatsNew.item.generalChatsColumn.detail', $json$"組織の環境では、その総合チャットがサイドメニューの横に専用の列を持つようになり、どの画面でも新しい順に表示されます。+ で新しく始められます。プロジェクトページからは外れ、そこにはリポジトリのプロジェクトだけが並びます。"$json$::jsonb),
  ('de', 'whatsNew.item.generalChatsColumn.detail', $json$"In der Umgebung einer Organisation haben ihre allgemeinen Chats jetzt eine eigene Spalte neben dem Seitenmenü, auf jedem Bildschirm sichtbar, die neuesten zuerst; + startet einen weiteren. Sie sind aus der Seite Projekte verschwunden, die jetzt nur noch die Projekte der Repositories auflistet."$json$::jsonb),
  ('pt-BR', 'docs.llmMods.title', $json$"Mods de LLM"$json$::jsonb),
  ('en', 'docs.llmMods.title', $json$"LLM mods"$json$::jsonb),
  ('es', 'docs.llmMods.title', $json$"Mods de LLM"$json$::jsonb),
  ('zh-CN', 'docs.llmMods.title', $json$"LLM 模组"$json$::jsonb),
  ('hi', 'docs.llmMods.title', $json$"LLM मॉड"$json$::jsonb),
  ('ar', 'docs.llmMods.title', $json$"إضافات LLM"$json$::jsonb),
  ('fr', 'docs.llmMods.title', $json$"Mods LLM"$json$::jsonb),
  ('ru', 'docs.llmMods.title', $json$"Моды LLM"$json$::jsonb),
  ('ja', 'docs.llmMods.title', $json$"LLM の Mod"$json$::jsonb),
  ('de', 'docs.llmMods.title', $json$"LLM-Mods"$json$::jsonb),
  ('pt-BR', 'docs.llmMods.summary', $json$"Toda integração com modelos de LLM é um mod: Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter e LiteLLM vêm com o app, e você pode criar os seus para ligar outro programa de linha de comando ou uma API compatível com OpenAI ou Anthropic. O Jev escolhe entre todos do mesmo jeito, com as mesmas portarias, o mesmo roteamento e o mesmo registro de uso."$json$::jsonb),
  ('en', 'docs.llmMods.summary', $json$"Every integration with LLM models is a mod: Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter and LiteLLM come built in, and you can create your own to connect another command-line program or an API compatible with OpenAI or Anthropic. Jev picks among all of them the same way, with the same gates, routing and usage records."$json$::jsonb),
  ('es', 'docs.llmMods.summary', $json$"Toda integración con modelos de LLM es un mod: Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter y LiteLLM vienen con la app, y puedes crear los tuyos para conectar otro programa de línea de comandos o una API compatible con OpenAI o Anthropic. Jev elige entre todos de la misma forma, con las mismas porterías, el mismo enrutamiento y el mismo registro de uso."$json$::jsonb),
  ('zh-CN', 'docs.llmMods.summary', $json$"与 LLM 模型的每一项集成都是一个模组：Claude Code、Codex、GitHub Copilot、Cursor、Kilo Code、OpenRouter 和 LiteLLM 随应用自带，你也可以创建自己的模组，接入另一个命令行程序或兼容 OpenAI 或 Anthropic 的 API。Jev 以相同的方式在所有模组中选择，使用相同的门岗、路由和用量记录。"$json$::jsonb),
  ('hi', 'docs.llmMods.summary', $json$"LLM मॉडलों से हर इंटीग्रेशन एक मॉड है: Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter और LiteLLM ऐप के साथ आते हैं, और आप कोई दूसरा कमांड-लाइन प्रोग्राम या OpenAI या Anthropic के साथ संगत API जोड़ने के लिए अपने मॉड बना सकते हैं। Jev सबमें से एक ही तरह चुनता है, उन्हीं गेट, उसी रूटिंग और उसी उपयोग रिकॉर्ड के साथ।"$json$::jsonb),
  ('ar', 'docs.llmMods.summary', $json$"كل تكامل مع نماذج LLM هو إضافة: تأتي Claude Code وCodex وGitHub Copilot وCursor وKilo Code وOpenRouter وLiteLLM مضمّنة في التطبيق، ويمكنك إنشاء إضافاتك لربط برنامج سطر أوامر آخر أو واجهة API متوافقة مع OpenAI أو Anthropic. يختار Jev بينها جميعًا بالطريقة نفسها، بالبوابات نفسها والتوجيه نفسه وسجل الاستخدام نفسه."$json$::jsonb),
  ('fr', 'docs.llmMods.summary', $json$"Chaque intégration avec des modèles de LLM est un mod : Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter et LiteLLM sont fournis avec l’app, et vous pouvez créer les vôtres pour connecter un autre programme en ligne de commande ou une API compatible avec OpenAI ou Anthropic. Jev choisit parmi eux tous de la même façon, avec les mêmes loges, le même routage et le même relevé d’utilisation."$json$::jsonb),
  ('ru', 'docs.llmMods.summary', $json$"Каждая интеграция с моделями LLM — это мод: Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter и LiteLLM встроены в приложение, а свои моды можно создать, чтобы подключить другую программу командной строки или API, совместимый с OpenAI или Anthropic. Jev выбирает среди всех одинаково, с теми же проходными, той же маршрутизацией и тем же учётом использования."$json$::jsonb),
  ('ja', 'docs.llmMods.summary', $json$"LLM モデルとの連携はすべて Mod です。Claude Code、Codex、GitHub Copilot、Cursor、Kilo Code、OpenRouter、LiteLLM がアプリに組み込まれており、自分で Mod を作成して、別のコマンドラインプログラムや OpenAI または Anthropic 互換の API をつなぐこともできます。Jev はすべての Mod から同じ方法で選び、同じゲート、ルーティング、使用状況の記録を使います。"$json$::jsonb),
  ('de', 'docs.llmMods.summary', $json$"Jede Anbindung an LLM-Modelle ist ein Mod: Claude Code, Codex, GitHub Copilot, Cursor, Kilo Code, OpenRouter und LiteLLM sind mitgeliefert, und Sie können eigene erstellen, um ein weiteres Kommandozeilenprogramm oder eine mit OpenAI oder Anthropic kompatible API anzubinden. Jev wählt unter allen auf dieselbe Weise, mit denselben Pforten, demselben Routing und derselben Nutzungserfassung."$json$::jsonb),
  ('pt-BR', 'docs.llmMods.usage', $json$"Abra Configuração › Mods (ou Ctrl+K › Criar mod) e clique em Criar mod. Num mod de linha de comando, informe o programa e a linha de comando dele: {model} vira o modelo que o Jev escolheu e {prompt}, sozinho num argumento, o pedido (sem ele, o pedido vai pela entrada padrão); se o programa escreve no projeto, informe também a linha de planejamento, que não pode escrever. Num mod de API, escolha compatível com OpenAI ou Anthropic, informe o endereço e, se ela pedir, a chave, que fica neste computador. Salve a configuração e depois adicione ou carregue os modelos na aba do mod e ligue os que o Jev pode usar. Os mods sincronizam com a configuração do ambiente. Nos projetos de uma organização, a política de LLM dela vale para todo mod: quando ela lista os agentes permitidos, os mods que você cria ficam desligados lá."$json$::jsonb),
  ('en', 'docs.llmMods.usage', $json$"Open Settings › Mods (or Ctrl+K › Create mod) and click Create mod. For a command-line mod, give the program and its command line: {model} becomes the model Jev picked and {prompt}, alone in an argument, the request (without it, the request goes through standard input); if the program writes to the project, also give the planning line, which must not. For an API mod, choose OpenAI-compatible or Anthropic, enter the address and, if it needs one, the key, which stays on this computer. Save the settings, then add or refresh the models in the mod's tab and turn on the ones Jev may use. Mods sync with the settings of the environment. In an organization's projects its LLM policy applies to every mod: when it lists the allowed agents, the mods you create stay off there."$json$::jsonb),
  ('es', 'docs.llmMods.usage', $json$"Abre Configuración › Mods (o Ctrl+K › Crear mod) y haz clic en Crear mod. En un mod de línea de comandos, indica el programa y su línea de comandos: {model} se convierte en el modelo que eligió Jev y {prompt}, solo en un argumento, en la solicitud (sin él, la solicitud va por la entrada estándar); si el programa escribe en el proyecto, indica también la línea de planificación, que no debe escribir. En un mod de API, elige compatible con OpenAI o Anthropic, introduce la dirección y, si la pide, la clave, que se queda en este equipo. Guarda la configuración y después añade o carga los modelos en la pestaña del mod y activa los que Jev puede usar. Los mods se sincronizan con la configuración del entorno. En los proyectos de una organización, su política de LLM se aplica a todo mod: cuando enumera los agentes permitidos, los mods que creas quedan desactivados allí."$json$::jsonb),
  ('zh-CN', 'docs.llmMods.usage', $json$"打开“设置 › 模组”（或 Ctrl+K › 创建模组），点击“创建模组”。对于命令行模组，填写程序及其命令行：{model} 会替换为 Jev 选择的模型，{prompt} 单独作为一个参数时替换为请求（没有它时，请求通过标准输入传入）；如果程序会写入项目，还要填写不写入项目的规划命令行。对于 API 模组，选择兼容 OpenAI 或 Anthropic，输入地址，如需要再输入密钥，密钥只保留在本机。保存设置后，在模组的标签页中添加或加载模型，并开启 Jev 可以使用的模型。模组随环境的设置同步。在组织的项目中，其 LLM 策略适用于每个模组：当策略列出允许的代理时，你创建的模组在那里保持关闭。"$json$::jsonb),
  ('hi', 'docs.llmMods.usage', $json$"सेटिंग्स › मॉड खोलें (या Ctrl+K › मॉड बनाएँ) और मॉड बनाएँ पर क्लिक करें। कमांड-लाइन मॉड के लिए प्रोग्राम और उसकी कमांड लाइन दें: {model} की जगह Jev का चुना मॉडल आता है और {prompt}, अकेले एक आर्ग्युमेंट में, अनुरोध बन जाता है (इसके बिना अनुरोध मानक इनपुट से जाता है); अगर प्रोग्राम प्रोजेक्ट में लिखता है, तो योजना की लाइन भी दें, जो नहीं लिखनी चाहिए। API मॉड के लिए OpenAI-संगत या Anthropic चुनें, पता दर्ज करें और ज़रूरत हो तो कुंजी, जो इसी कंप्यूटर पर रहती है। सेटिंग्स सहेजें, फिर मॉड के टैब में मॉडल जोड़ें या लोड करें और वे चालू करें जिन्हें Jev इस्तेमाल कर सकता है। मॉड परिवेश की सेटिंग्स के साथ सिंक होते हैं। किसी संगठन के प्रोजेक्ट में उसकी LLM नीति हर मॉड पर लागू होती है: जब वह अनुमत एजेंटों की सूची देती है, तो आपके बनाए मॉड वहाँ बंद रहते हैं।"$json$::jsonb),
  ('ar', 'docs.llmMods.usage', $json$"افتح الإعدادات › الإضافات (أو Ctrl+K › إنشاء إضافة) وانقر «إنشاء إضافة». في إضافة سطر الأوامر، أدخل البرنامج وسطر أوامره: يصبح {model} النموذج الذي اختاره Jev ويصبح {prompt}، منفردًا في وسيط، الطلبَ (ومن دونه يُرسل الطلب عبر الإدخال القياسي)؛ وإن كان البرنامج يكتب في المشروع فأدخل أيضًا سطر التخطيط، الذي يجب ألا يكتب. في إضافة API، اختر المتوافق مع OpenAI أو Anthropic، وأدخل العنوان والمفتاح إن طُلب، وهو يبقى على هذا الجهاز. احفظ الإعدادات، ثم أضف النماذج أو حمّلها في تبويب الإضافة وفعّل التي يمكن لـ Jev استخدامها. تُزامَن الإضافات مع إعدادات البيئة. في مشاريع المؤسسة تسري سياسة LLM الخاصة بها على كل إضافة: عندما تحدد الوكلاء المسموح بهم، تبقى الإضافات التي تنشئها معطّلة هناك."$json$::jsonb),
  ('fr', 'docs.llmMods.usage', $json$"Ouvrez Configuration › Mods (ou Ctrl+K › Créer un mod) et cliquez sur Créer un mod. Pour un mod en ligne de commande, indiquez le programme et sa ligne de commande : {model} devient le modèle choisi par Jev et {prompt}, seul dans un argument, la demande (sans lui, la demande passe par l’entrée standard) ; si le programme écrit dans le projet, indiquez aussi la ligne de planification, qui ne doit pas écrire. Pour un mod d’API, choisissez compatible OpenAI ou Anthropic, saisissez l’adresse et, si elle en demande une, la clé, qui reste sur cet ordinateur. Enregistrez la configuration, puis ajoutez ou chargez les modèles dans l’onglet du mod et activez ceux que Jev peut utiliser. Les mods se synchronisent avec la configuration de l’environnement. Dans les projets d’une organisation, sa politique LLM s’applique à chaque mod : quand elle liste les agents autorisés, les mods que vous créez y restent désactivés."$json$::jsonb),
  ('ru', 'docs.llmMods.usage', $json$"Откройте Настройки › Моды (или Ctrl+K › Создать мод) и нажмите «Создать мод». Для мода командной строки укажите программу и её командную строку: {model} заменяется моделью, выбранной Jev, а {prompt}, отдельным аргументом, — запросом (без него запрос передаётся через стандартный ввод); если программа пишет в проект, укажите и строку планирования, которая писать не должна. Для мода API выберите «Совместимый с OpenAI» или Anthropic, введите адрес и, если нужно, ключ — он остаётся на этом компьютере. Сохраните настройки, затем добавьте или загрузите модели во вкладке мода и включите те, которыми может пользоваться Jev. Моды синхронизируются с настройками среды. В проектах организации её политика LLM действует на каждый мод: если в ней перечислены разрешённые агенты, созданные вами моды там отключены."$json$::jsonb),
  ('ja', 'docs.llmMods.usage', $json$"設定 › Mod（または Ctrl+K › Mod を作成）を開き、「Mod を作成」をクリックします。コマンドラインの Mod では、プログラムとそのコマンドラインを入力します。{model} は Jev が選んだモデルに、単独の引数の {prompt} はリクエストに置き換わります（なければリクエストは標準入力で渡されます）。プログラムがプロジェクトに書き込む場合は、書き込まない計画用のコマンドラインも入力します。API の Mod では OpenAI 互換か Anthropic を選び、アドレスと、必要ならキーを入力します。キーはこのコンピューターに残ります。設定を保存したら、Mod のタブでモデルを追加または読み込み、Jev が使ってよいものをオンにします。Mod は環境の設定と同期されます。組織のプロジェクトでは、その LLM ポリシーがすべての Mod に適用されます。ポリシーが許可するエージェントを列挙している場合、自分で作成した Mod はそこではオフになります。"$json$::jsonb),
  ('de', 'docs.llmMods.usage', $json$"Öffnen Sie Einstellungen › Mods (oder Ctrl+K › Mod erstellen) und klicken Sie auf Mod erstellen. Bei einem Kommandozeilen-Mod geben Sie das Programm und seine Kommandozeile an: {model} wird zum Modell, das Jev gewählt hat, und {prompt}, allein in einem Argument, zur Anfrage (ohne es geht die Anfrage über die Standardeingabe); schreibt das Programm ins Projekt, geben Sie auch die Planungszeile an, die das nicht tun darf. Bei einem API-Mod wählen Sie OpenAI-kompatibel oder Anthropic, geben die Adresse und, falls verlangt, den Schlüssel ein, der auf diesem Computer bleibt. Speichern Sie die Einstellungen, fügen Sie dann im Tab des Mods die Modelle hinzu oder laden Sie sie, und schalten Sie die ein, die Jev nutzen darf. Mods synchronisieren sich mit den Einstellungen der Umgebung. In den Projekten einer Organisation gilt deren LLM-Richtlinie für jeden Mod: Wenn sie die erlaubten Agenten auflistet, bleiben Ihre eigenen Mods dort ausgeschaltet."$json$::jsonb),
  ('pt-BR', 'docs.orgChat.summary', $json$"Chats que trabalham em todos os repositórios de uma organização de uma vez, com o agente, o índice e a portaria enxergando todos eles. No ambiente da organização, eles têm uma coluna própria ao lado do menu lateral, à parte dos projetos de cada repositório."$json$::jsonb),
  ('en', 'docs.orgChat.summary', $json$"Chats that work on every repository of an organization at once, with the agent, the index and the gate seeing all of them. In the organization's environment they have their own column next to the side menu, apart from the projects of each repository."$json$::jsonb),
  ('es', 'docs.orgChat.summary', $json$"Chats que trabajan en todos los repositorios de una organización a la vez, con el agente, el índice y la portería viéndolos todos. En el entorno de la organización tienen su propia columna junto al menú lateral, aparte de los proyectos de cada repositorio."$json$::jsonb),
  ('zh-CN', 'docs.orgChat.summary', $json$"同时处理组织所有仓库的聊天，代理、索引和门岗能看到全部仓库。在组织的环境中，它们在侧边菜单旁有单独的一栏，与各仓库的项目分开。"$json$::jsonb),
  ('hi', 'docs.orgChat.summary', $json$"ऐसी चैट जो किसी संगठन की सभी रिपॉज़िटरी पर एक साथ काम करती हैं, जिनमें एजेंट, इंडेक्स और गेट सबको देखते हैं। संगठन के परिवेश में उनका साइड मेनू के बगल में अपना कॉलम है, हर रिपॉज़िटरी के प्रोजेक्ट से अलग।"$json$::jsonb),
  ('ar', 'docs.orgChat.summary', $json$"محادثات تعمل على كل مستودعات المؤسسة في آن واحد، ويرى فيها الوكيل والفهرس والبوابة المستودعات كلها. في بيئة المؤسسة لها عمود خاص بجوار القائمة الجانبية، منفصل عن مشاريع كل مستودع."$json$::jsonb),
  ('fr', 'docs.orgChat.summary', $json$"Des chats qui travaillent sur tous les dépôts d’une organisation à la fois, avec l’agent, l’index et la loge qui les voient tous. Dans l’environnement de l’organisation, ils ont leur propre colonne à côté du menu latéral, à part des projets de chaque dépôt."$json$::jsonb),
  ('ru', 'docs.orgChat.summary', $json$"Чаты, работающие сразу со всеми репозиториями организации: агент, индекс и проходная видят их все. В среде организации у них отдельная колонка рядом с боковым меню, отдельно от проектов каждого репозитория."$json$::jsonb),
  ('ja', 'docs.orgChat.summary', $json$"組織のすべてのリポジトリをまとめて扱うチャットで、エージェント、インデックス、ゲートがすべてのリポジトリを参照します。組織の環境では、各リポジトリのプロジェクトとは別に、サイドメニューの横に専用の列があります。"$json$::jsonb),
  ('de', 'docs.orgChat.summary', $json$"Chats, die an allen Repositories einer Organisation zugleich arbeiten, wobei Agent, Index und Pforte sie alle sehen. In der Umgebung der Organisation haben sie eine eigene Spalte neben dem Seitenmenü, getrennt von den Projekten der einzelnen Repositories."$json$::jsonb),
  ('pt-BR', 'docs.orgChat.usage', $json$"No ambiente da organização, a coluna Chats gerais ao lado do menu lateral os lista, do mais recente para o mais antigo, em todas as telas: clique num para continuá-lo ou no + para começar outro. O botão Abrir chat no alto de Projetos também deixa escolher ou começar um. Sem uma pasta da organização neste computador, o JayV pede uma primeiro. Também na paleta de comandos (Ctrl+K): Chats gerais."$json$::jsonb),
  ('en', 'docs.orgChat.usage', $json$"In the organization's environment, the General chats column next to the side menu lists them, newest first, on every screen: click one to continue it or + to start another. The Open chat button at the top of Projects also lets you choose or start one. Without an organization folder on this computer, JayV asks for one first. Also in the command palette (Ctrl+K): General chats."$json$::jsonb),
  ('es', 'docs.orgChat.usage', $json$"En el entorno de la organización, la columna Chats generales junto al menú lateral los enumera, del más reciente al más antiguo, en todas las pantallas: haz clic en uno para continuarlo o en + para empezar otro. El botón Abrir chat arriba de Proyectos también permite elegir o empezar uno. Sin una carpeta de la organización en este equipo, JayV pide una primero. También en la paleta de comandos (Ctrl+K): Chats generales."$json$::jsonb),
  ('zh-CN', 'docs.orgChat.usage', $json$"在组织的环境中，侧边菜单旁的“通用聊天”栏在每个界面列出它们，最新的在前：点击其中一个继续，或点 + 开始新的。“项目”顶部的“打开聊天”按钮也可以选择或开始一个。如果本机没有该组织的文件夹，JayV 会先请你指定一个。也可在命令面板（Ctrl+K）中使用：通用聊天。"$json$::jsonb),
  ('hi', 'docs.orgChat.usage', $json$"संगठन के परिवेश में साइड मेनू के बगल का सामान्य चैट कॉलम उन्हें हर स्क्रीन पर, सबसे नई पहले, दिखाता है: किसी एक पर क्लिक करके उसे जारी रखें या + से दूसरी शुरू करें। प्रोजेक्ट के ऊपर का चैट खोलें बटन भी एक चुनने या शुरू करने देता है। इस कंप्यूटर पर संगठन का फ़ोल्डर न हो तो JayV पहले एक माँगता है। कमांड पैलेट (Ctrl+K) में भी: सामान्य चैट।"$json$::jsonb),
  ('ar', 'docs.orgChat.usage', $json$"في بيئة المؤسسة، يعرضها عمود المحادثات العامة بجوار القائمة الجانبية في كل الشاشات، والأحدث أولًا: انقر إحداها لمتابعتها أو + لبدء أخرى. ويتيح زر «فتح الدردشة» أعلى المشاريع أيضًا اختيار محادثة أو بدء واحدة. إن لم يكن على هذا الجهاز مجلد للمؤسسة، يطلب JayV واحدًا أولًا. وأيضًا في لوحة الأوامر (Ctrl+K): المحادثات العامة."$json$::jsonb),
  ('fr', 'docs.orgChat.usage', $json$"Dans l’environnement de l’organisation, la colonne Chats généraux à côté du menu latéral les liste, du plus récent au plus ancien, sur tous les écrans : cliquez sur l’un pour le reprendre ou sur + pour en lancer un autre. Le bouton Ouvrir le chat en haut de Projets permet aussi d’en choisir ou d’en lancer un. Sans dossier de l’organisation sur cet ordinateur, JayV en demande un d’abord. Aussi dans la palette de commandes (Ctrl+K) : Chats généraux."$json$::jsonb),
  ('ru', 'docs.orgChat.usage', $json$"В среде организации колонка «Общие чаты» рядом с боковым меню показывает их на всех экранах, сначала самые новые: нажмите на чат, чтобы продолжить его, или на +, чтобы начать новый. Кнопка «Открыть чат» вверху страницы «Проекты» тоже позволяет выбрать или начать чат. Если на этом компьютере нет папки организации, JayV сначала попросит её указать. Также в палитре команд (Ctrl+K): «Общие чаты»."$json$::jsonb),
  ('ja', 'docs.orgChat.usage', $json$"組織の環境では、サイドメニューの横にある「総合チャット」列が、どの画面でも新しい順に一覧表示します。クリックすると続きから、+ で新しく始められます。プロジェクト上部の「チャットを開く」ボタンからも選んだり始めたりできます。このコンピューターに組織のフォルダーがない場合、JayV が先に指定を求めます。コマンドパレット（Ctrl+K）の「総合チャット」からも使えます。"$json$::jsonb),
  ('de', 'docs.orgChat.usage', $json$"In der Umgebung der Organisation listet die Spalte Allgemeine Chats neben dem Seitenmenü sie auf jedem Bildschirm auf, die neuesten zuerst: Klicken Sie auf einen, um ihn fortzusetzen, oder auf +, um einen weiteren zu starten. Auch die Schaltfläche Chat öffnen oben in Projekte lässt einen wählen oder starten. Ohne Ordner der Organisation auf diesem Computer fragt JayV zuerst nach einem. Auch in der Befehlspalette (Ctrl+K): Allgemeine Chats."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
