-- v0.80.0: "siga com o plano" vai ao desenvolvimento, trava de cota para todos os agentes, busca na conversa (Ctrl+F) e atalhos do navegador bloqueados.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'find.label', $json$"Pesquisar na conversa"$json$::jsonb),
  ('en', 'find.label', $json$"Find in the conversation"$json$::jsonb),
  ('es', 'find.label', $json$"Buscar en la conversación"$json$::jsonb),
  ('zh-CN', 'find.label', $json$"在对话中查找"$json$::jsonb),
  ('hi', 'find.label', $json$"बातचीत में खोजें"$json$::jsonb),
  ('ar', 'find.label', $json$"البحث في المحادثة"$json$::jsonb),
  ('fr', 'find.label', $json$"Rechercher dans la conversation"$json$::jsonb),
  ('ru', 'find.label', $json$"Поиск в разговоре"$json$::jsonb),
  ('ja', 'find.label', $json$"会話内を検索"$json$::jsonb),
  ('de', 'find.label', $json$"In der Unterhaltung suchen"$json$::jsonb),
  ('pt-BR', 'find.placeholder', $json$"Pesquisar nesta conversa"$json$::jsonb),
  ('en', 'find.placeholder', $json$"Find in this conversation"$json$::jsonb),
  ('es', 'find.placeholder', $json$"Buscar en esta conversación"$json$::jsonb),
  ('zh-CN', 'find.placeholder', $json$"在此对话中查找"$json$::jsonb),
  ('hi', 'find.placeholder', $json$"इस बातचीत में खोजें"$json$::jsonb),
  ('ar', 'find.placeholder', $json$"ابحث في هذه المحادثة"$json$::jsonb),
  ('fr', 'find.placeholder', $json$"Rechercher dans cette conversation"$json$::jsonb),
  ('ru', 'find.placeholder', $json$"Искать в этом разговоре"$json$::jsonb),
  ('ja', 'find.placeholder', $json$"この会話内を検索"$json$::jsonb),
  ('de', 'find.placeholder', $json$"In dieser Unterhaltung suchen"$json$::jsonb),
  ('pt-BR', 'find.count', $json$"{current} de {total}"$json$::jsonb),
  ('en', 'find.count', $json$"{current} of {total}"$json$::jsonb),
  ('es', 'find.count', $json$"{current} de {total}"$json$::jsonb),
  ('zh-CN', 'find.count', $json$"第 {current} 个，共 {total} 个"$json$::jsonb),
  ('hi', 'find.count', $json$"{total} में से {current}"$json$::jsonb),
  ('ar', 'find.count', $json$"{current} من {total}"$json$::jsonb),
  ('fr', 'find.count', $json$"{current} sur {total}"$json$::jsonb),
  ('ru', 'find.count', $json$"{current} из {total}"$json$::jsonb),
  ('ja', 'find.count', $json$"{current} / {total}"$json$::jsonb),
  ('de', 'find.count', $json$"{current} von {total}"$json$::jsonb),
  ('pt-BR', 'find.none', $json$"Nada encontrado"$json$::jsonb),
  ('en', 'find.none', $json$"No matches"$json$::jsonb),
  ('es', 'find.none', $json$"Sin resultados"$json$::jsonb),
  ('zh-CN', 'find.none', $json$"无匹配项"$json$::jsonb),
  ('hi', 'find.none', $json$"कोई परिणाम नहीं"$json$::jsonb),
  ('ar', 'find.none', $json$"لا نتائج"$json$::jsonb),
  ('fr', 'find.none', $json$"Aucun résultat"$json$::jsonb),
  ('ru', 'find.none', $json$"Ничего не найдено"$json$::jsonb),
  ('ja', 'find.none', $json$"一致なし"$json$::jsonb),
  ('de', 'find.none', $json$"Keine Treffer"$json$::jsonb),
  ('pt-BR', 'find.previous', $json$"Ocorrência anterior"$json$::jsonb),
  ('en', 'find.previous', $json$"Previous match"$json$::jsonb),
  ('es', 'find.previous', $json$"Coincidencia anterior"$json$::jsonb),
  ('zh-CN', 'find.previous', $json$"上一个匹配项"$json$::jsonb),
  ('hi', 'find.previous', $json$"पिछला परिणाम"$json$::jsonb),
  ('ar', 'find.previous', $json$"النتيجة السابقة"$json$::jsonb),
  ('fr', 'find.previous', $json$"Résultat précédent"$json$::jsonb),
  ('ru', 'find.previous', $json$"Предыдущее совпадение"$json$::jsonb),
  ('ja', 'find.previous', $json$"前の一致"$json$::jsonb),
  ('de', 'find.previous', $json$"Vorheriger Treffer"$json$::jsonb),
  ('pt-BR', 'find.next', $json$"Próxima ocorrência"$json$::jsonb),
  ('en', 'find.next', $json$"Next match"$json$::jsonb),
  ('es', 'find.next', $json$"Siguiente coincidencia"$json$::jsonb),
  ('zh-CN', 'find.next', $json$"下一个匹配项"$json$::jsonb),
  ('hi', 'find.next', $json$"अगला परिणाम"$json$::jsonb),
  ('ar', 'find.next', $json$"النتيجة التالية"$json$::jsonb),
  ('fr', 'find.next', $json$"Résultat suivant"$json$::jsonb),
  ('ru', 'find.next', $json$"Следующее совпадение"$json$::jsonb),
  ('ja', 'find.next', $json$"次の一致"$json$::jsonb),
  ('de', 'find.next', $json$"Nächster Treffer"$json$::jsonb),
  ('pt-BR', 'find.close', $json$"Fechar a busca"$json$::jsonb),
  ('en', 'find.close', $json$"Close search"$json$::jsonb),
  ('es', 'find.close', $json$"Cerrar la búsqueda"$json$::jsonb),
  ('zh-CN', 'find.close', $json$"关闭搜索"$json$::jsonb),
  ('hi', 'find.close', $json$"खोज बंद करें"$json$::jsonb),
  ('ar', 'find.close', $json$"إغلاق البحث"$json$::jsonb),
  ('fr', 'find.close', $json$"Fermer la recherche"$json$::jsonb),
  ('ru', 'find.close', $json$"Закрыть поиск"$json$::jsonb),
  ('ja', 'find.close', $json$"検索を閉じる"$json$::jsonb),
  ('de', 'find.close', $json$"Suche schließen"$json$::jsonb),
  ('pt-BR', 'guard.steps', $json$"O JayV parou esta execução após {max} passos de ferramenta para proteger a cota do seu plano. O que o agente já fez fica no projeto: envie um pedido mais restrito para continuar."$json$::jsonb),
  ('en', 'guard.steps', $json$"JayV stopped this run after {max} tool steps to protect your plan quota. What the agent already did stays in the project: send a narrower request to continue."$json$::jsonb),
  ('es', 'guard.steps', $json$"JayV detuvo esta ejecución tras {max} pasos de herramienta para proteger la cuota de tu plan. Lo que el agente ya hizo queda en el proyecto: envía una petición más acotada para continuar."$json$::jsonb),
  ('zh-CN', 'guard.steps', $json$"为保护你的套餐额度，JayV 在 {max} 个工具步骤后停止了这次运行。代理已完成的内容保留在项目中：请发送范围更小的请求以继续。"$json$::jsonb),
  ('hi', 'guard.steps', $json$"आपके प्लान का कोटा बचाने के लिए JayV ने {max} टूल स्टेप के बाद यह रन रोक दिया। एजेंट जो कर चुका है वह प्रोजेक्ट में रहता है: जारी रखने के लिए छोटा अनुरोध भेजें।"$json$::jsonb),
  ('ar', 'guard.steps', $json$"أوقف JayV هذا التشغيل بعد {max} خطوة أدوات لحماية حصة خطتك. ما أنجزه الوكيل يبقى في المشروع: أرسل طلبًا أضيق للمتابعة."$json$::jsonb),
  ('fr', 'guard.steps', $json$"JayV a arrêté cette exécution après {max} étapes d'outil pour protéger le quota de votre forfait. Ce que l'agent a déjà fait reste dans le projet : envoyez une demande plus ciblée pour continuer."$json$::jsonb),
  ('ru', 'guard.steps', $json$"JayV остановил этот запуск после {max} шагов инструментов, чтобы защитить квоту вашего тарифа. Уже сделанное агентом остаётся в проекте: отправьте более узкий запрос, чтобы продолжить."$json$::jsonb),
  ('ja', 'guard.steps', $json$"プランの使用枠を守るため、JayV はツール操作が {max} 回に達したところでこの実行を止めました。エージェントがすでに行った変更はプロジェクトに残ります。続けるには範囲を絞った依頼を送ってください。"$json$::jsonb),
  ('de', 'guard.steps', $json$"JayV hat diesen Lauf nach {max} Werkzeugschritten gestoppt, um das Kontingent Ihres Tarifs zu schützen. Was der Agent bereits getan hat, bleibt im Projekt: Senden Sie eine engere Anfrage, um fortzufahren."$json$::jsonb),
  ('pt-BR', 'guard.tokens', $json$"O JayV parou esta execução após cerca de {amount} milhão de tokens da cota do seu plano em uma única execução. O que o agente já fez fica no projeto: envie um pedido mais restrito para continuar."$json$::jsonb),
  ('en', 'guard.tokens', $json$"JayV stopped this run after about {amount} million tokens' worth of your plan quota in a single run. What the agent already did stays in the project: send a narrower request to continue."$json$::jsonb),
  ('es', 'guard.tokens', $json$"JayV detuvo esta ejecución tras cerca de {amount} millones de tokens de la cuota de tu plan en una sola ejecución. Lo que el agente ya hizo queda en el proyecto: envía una petición más acotada para continuar."$json$::jsonb),
  ('zh-CN', 'guard.tokens', $json$"单次运行已消耗约相当于 {amount} 百万 token 的套餐额度，JayV 已停止这次运行。代理已完成的内容保留在项目中：请发送范围更小的请求以继续。"$json$::jsonb),
  ('hi', 'guard.tokens', $json$"एक ही रन में आपके प्लान के कोटे का लगभग {amount} मिलियन टोकन के बराबर खर्च होने पर JayV ने यह रन रोक दिया। एजेंट जो कर चुका है वह प्रोजेक्ट में रहता है: जारी रखने के लिए छोटा अनुरोध भेजें।"$json$::jsonb),
  ('ar', 'guard.tokens', $json$"أوقف JayV هذا التشغيل بعد استهلاك ما يعادل نحو {amount} مليون رمز من حصة خطتك في تشغيل واحد. ما أنجزه الوكيل يبقى في المشروع: أرسل طلبًا أضيق للمتابعة."$json$::jsonb),
  ('fr', 'guard.tokens', $json$"JayV a arrêté cette exécution après environ {amount} million de jetons du quota de votre forfait en une seule exécution. Ce que l'agent a déjà fait reste dans le projet : envoyez une demande plus ciblée pour continuer."$json$::jsonb),
  ('ru', 'guard.tokens', $json$"JayV остановил этот запуск после расхода примерно {amount} млн токенов квоты вашего тарифа за один запуск. Уже сделанное агентом остаётся в проекте: отправьте более узкий запрос, чтобы продолжить."$json$::jsonb),
  ('ja', 'guard.tokens', $json$"1 回の実行でプランの使用枠を約 {amount} 百万トークン分使ったため、JayV はこの実行を止めました。エージェントがすでに行った変更はプロジェクトに残ります。続けるには範囲を絞った依頼を送ってください。"$json$::jsonb),
  ('de', 'guard.tokens', $json$"JayV hat diesen Lauf gestoppt, nachdem er in einem einzigen Lauf etwa {amount} Millionen Token des Kontingents Ihres Tarifs verbraucht hatte. Was der Agent bereits getan hat, bleibt im Projekt: Senden Sie eine engere Anfrage, um fortzufahren."$json$::jsonb),
  ('pt-BR', 'guard.runs', $json$"O JayV não abriu outro agente: este pedido já abriu {max} (plano, divisão, revisão e novas tentativas). Envie um pedido mais restrito."$json$::jsonb),
  ('en', 'guard.runs', $json$"JayV did not open another agent: this request already opened {max} (plan, split, review and retries). Send a narrower request."$json$::jsonb),
  ('es', 'guard.runs', $json$"JayV no abrió otro agente: esta petición ya abrió {max} (plan, división, revisión y reintentos). Envía una petición más acotada."$json$::jsonb),
  ('zh-CN', 'guard.runs', $json$"JayV 没有再启动代理：此请求已启动 {max} 个（计划、拆分、审查和重试）。请发送范围更小的请求。"$json$::jsonb),
  ('hi', 'guard.runs', $json$"JayV ने दूसरा एजेंट नहीं खोला: इस अनुरोध ने पहले ही {max} खोल लिए हैं (प्लान, विभाजन, समीक्षा और पुनः प्रयास)। छोटा अनुरोध भेजें।"$json$::jsonb),
  ('ar', 'guard.runs', $json$"لم يفتح JayV وكيلًا آخر: فتح هذا الطلب بالفعل {max} (الخطة والتقسيم والمراجعة وإعادة المحاولة). أرسل طلبًا أضيق."$json$::jsonb),
  ('fr', 'guard.runs', $json$"JayV n'a pas ouvert d'autre agent : cette demande en a déjà ouvert {max} (plan, découpage, revue et nouvelles tentatives). Envoyez une demande plus ciblée."$json$::jsonb),
  ('ru', 'guard.runs', $json$"JayV не стал открывать другого агента: этот запрос уже открыл {max} (план, разделение, проверка и повторы). Отправьте более узкий запрос."$json$::jsonb),
  ('ja', 'guard.runs', $json$"JayV は別のエージェントを起動しませんでした。この依頼ですでに {max} 回起動しています（計画、分割、レビュー、再試行）。範囲を絞った依頼を送ってください。"$json$::jsonb),
  ('de', 'guard.runs', $json$"JayV hat keinen weiteren Agenten geöffnet: Diese Anfrage hat bereits {max} geöffnet (Plan, Aufteilung, Review und Wiederholungen). Senden Sie eine engere Anfrage."$json$::jsonb),
  ('pt-BR', 'guard.quota', $json$"O JayV não abriu {agent}: o limite ({window}) está em {percent}% do seu plano e ele provavelmente pararia no meio. Espere o limite reiniciar ou ligue outro agente."$json$::jsonb),
  ('en', 'guard.quota', $json$"JayV did not open {agent}: its limit ({window}) is at {percent}% of your plan, so it would likely stop midway. Wait for the limit to reset or turn on another agent."$json$::jsonb),
  ('es', 'guard.quota', $json$"JayV no abrió {agent}: su límite ({window}) está al {percent}% de tu plan y probablemente se detendría a medias. Espera a que el límite se reinicie o activa otro agente."$json$::jsonb),
  ('zh-CN', 'guard.quota', $json$"JayV 没有启动 {agent}：其额度（{window}）已用到套餐的 {percent}%，很可能中途停止。请等待额度重置或启用其他代理。"$json$::jsonb),
  ('hi', 'guard.quota', $json$"JayV ने {agent} नहीं खोला: उसकी सीमा ({window}) आपके प्लान के {percent}% पर है और वह बीच में रुक सकता है। सीमा रीसेट होने तक प्रतीक्षा करें या दूसरा एजेंट चालू करें।"$json$::jsonb),
  ('ar', 'guard.quota', $json$"لم يفتح JayV {agent}: حدّه ({window}) عند {percent}% من خطتك وسيتوقف على الأرجح في منتصف العمل. انتظر حتى يُعاد ضبط الحد أو شغّل وكيلًا آخر."$json$::jsonb),
  ('fr', 'guard.quota', $json$"JayV n'a pas ouvert {agent} : sa limite ({window}) est à {percent} % de votre forfait et il s'arrêterait probablement en cours de route. Attendez la réinitialisation de la limite ou activez un autre agent."$json$::jsonb),
  ('ru', 'guard.quota', $json$"JayV не стал открывать {agent}: его лимит ({window}) израсходован на {percent}% вашего тарифа, и он, скорее всего, остановился бы на полпути. Дождитесь сброса лимита или включите другого агента."$json$::jsonb),
  ('ja', 'guard.quota', $json$"JayV は {agent} を起動しませんでした。上限（{window}）がプランの {percent}% に達しており、途中で止まる可能性が高いためです。上限のリセットを待つか、別のエージェントをオンにしてください。"$json$::jsonb),
  ('de', 'guard.quota', $json$"JayV hat {agent} nicht geöffnet: Das Limit ({window}) liegt bei {percent} % Ihres Tarifs und der Agent würde wohl mittendrin stoppen. Warten Sie auf das Zurücksetzen des Limits oder schalten Sie einen anderen Agenten ein."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planFollowUp.title', $json$"“Pode seguir com o plano” agora desenvolve"$json$::jsonb),
  ('en', 'whatsNew.item.planFollowUp.title', $json$"“Go ahead with the plan” now builds"$json$::jsonb),
  ('es', 'whatsNew.item.planFollowUp.title', $json$"«Sigue con el plan» ahora desarrolla"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planFollowUp.title', $json$"“按计划继续”现在会开始开发"$json$::jsonb),
  ('hi', 'whatsNew.item.planFollowUp.title', $json$"“योजना पर आगे बढ़ें” अब निर्माण करता है"$json$::jsonb),
  ('ar', 'whatsNew.item.planFollowUp.title', $json$"«تابع الخطة» يبني الآن"$json$::jsonb),
  ('fr', 'whatsNew.item.planFollowUp.title', $json$"« Poursuis avec le plan » lance maintenant le développement"$json$::jsonb),
  ('ru', 'whatsNew.item.planFollowUp.title', $json$"«Продолжай по плану» теперь запускает разработку"$json$::jsonb),
  ('ja', 'whatsNew.item.planFollowUp.title', $json$"「計画を進めて」で開発が始まるように"$json$::jsonb),
  ('de', 'whatsNew.item.planFollowUp.title', $json$"„Weiter mit dem Plan“ entwickelt jetzt"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.planFollowUp.detail', $json$"No Automático, a mensagem que pede para executar o plano que o chat já tem (“siga com o desenvolvimento”, “chega de plano”, “continue com o plano”, em qualquer idioma do app) não é mais barrada pela portaria nem mandada de novo ao planejamento: ela vai ao Desenvolvimento com o plano inteiro, mesmo depois de reabrir o app."$json$::jsonb),
  ('en', 'whatsNew.item.planFollowUp.detail', $json$"In Auto, a message that asks to carry out the plan the chat already has (“siga com o desenvolvimento”, “chega de plano”, “continue with the plan”, in any app language) is no longer held by the entry gate or sent to planning again: it goes to Development with the whole plan, even after the app was reopened."$json$::jsonb),
  ('es', 'whatsNew.item.planFollowUp.detail', $json$"En Automático, el mensaje que pide ejecutar el plan que el chat ya tiene («sigue con el desarrollo», «basta de plan», «continúa con el plan», en cualquier idioma de la app) ya no lo retiene la puerta de entrada ni vuelve a planificación: pasa a Desarrollo con el plan completo, incluso tras reabrir la app."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.planFollowUp.detail', $json$"在自动模式下，要求执行对话中已有计划的消息（“继续开发”、“别再做计划了”、“按计划继续”，任何应用语言均可）不再被入口关卡拦下，也不会再次进入规划：它会带着完整计划进入开发，即使应用重新打开过。"$json$::jsonb),
  ('hi', 'whatsNew.item.planFollowUp.detail', $json$"ऑटो में, चैट की मौजूदा योजना को लागू करने को कहने वाला संदेश (“विकास जारी रखो”, “अब योजना नहीं”, “योजना के साथ आगे बढ़ो”, ऐप की किसी भी भाषा में) अब प्रवेश द्वार से नहीं रुकता और दोबारा प्लानिंग में नहीं जाता: वह पूरी योजना के साथ डेवलपमेंट में जाता है, ऐप दोबारा खोलने के बाद भी।"$json$::jsonb),
  ('ar', 'whatsNew.item.planFollowUp.detail', $json$"في الوضع التلقائي، الرسالة التي تطلب تنفيذ الخطة الموجودة في المحادثة («تابع التطوير»، «كفى تخطيطًا»، «تابع الخطة»، بأي لغة في التطبيق) لم تعد تُحجز عند بوابة الدخول ولا تعود إلى التخطيط: تذهب إلى التطوير مع الخطة كاملة، حتى بعد إعادة فتح التطبيق."$json$::jsonb),
  ('fr', 'whatsNew.item.planFollowUp.detail', $json$"En Automatique, le message qui demande d'exécuter le plan déjà présent dans le chat (« continue le développement », « assez de plan », « poursuis avec le plan », dans n'importe quelle langue de l'app) n'est plus retenu par la porte d'entrée ni renvoyé en planification : il passe en Développement avec le plan complet, même après la réouverture de l'app."$json$::jsonb),
  ('ru', 'whatsNew.item.planFollowUp.detail', $json$"В автоматическом режиме сообщение с просьбой выполнить уже существующий в чате план («продолжай разработку», «хватит планов», «продолжай по плану», на любом языке приложения) больше не задерживается входными воротами и не возвращается к планированию: оно идёт в Разработку с полным планом, даже после перезапуска приложения."$json$::jsonb),
  ('ja', 'whatsNew.item.planFollowUp.detail', $json$"自動モードでは、チャットにすでにある計画の実行を求めるメッセージ（「開発を進めて」「もう計画はいい」「計画どおり続けて」など、アプリのどの言語でも）が入口ゲートで止められたり計画に戻されたりしなくなりました。アプリを開き直した後でも、計画全体を持って開発に進みます。"$json$::jsonb),
  ('de', 'whatsNew.item.planFollowUp.detail', $json$"Im Automatikmodus wird eine Nachricht, die den schon vorhandenen Plan des Chats ausführen lässt („mach mit der Entwicklung weiter“, „genug geplant“, „weiter mit dem Plan“, in jeder App-Sprache), nicht mehr vom Eingangstor gehalten oder erneut in die Planung geschickt: Sie geht mit dem ganzen Plan in die Entwicklung, auch nach einem Neustart der App."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.quotaGuard.title', $json$"Trava de cota para todos os agentes"$json$::jsonb),
  ('en', 'whatsNew.item.quotaGuard.title', $json$"Quota guard for every agent"$json$::jsonb),
  ('es', 'whatsNew.item.quotaGuard.title', $json$"Freno de cuota para todos los agentes"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.quotaGuard.title', $json$"适用于所有代理的额度保护"$json$::jsonb),
  ('hi', 'whatsNew.item.quotaGuard.title', $json$"सभी एजेंटों के लिए कोटा सुरक्षा"$json$::jsonb),
  ('ar', 'whatsNew.item.quotaGuard.title', $json$"حماية الحصة لكل الوكلاء"$json$::jsonb),
  ('fr', 'whatsNew.item.quotaGuard.title', $json$"Garde-fou de quota pour tous les agents"$json$::jsonb),
  ('ru', 'whatsNew.item.quotaGuard.title', $json$"Защита квоты для всех агентов"$json$::jsonb),
  ('ja', 'whatsNew.item.quotaGuard.title', $json$"すべてのエージェントの使用枠ガード"$json$::jsonb),
  ('de', 'whatsNew.item.quotaGuard.title', $json$"Kontingentschutz für alle Agenten"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.quotaGuard.detail', $json$"O JayV não abre um agente cujo limite do plano está em 95% ou mais, limita as chamadas de agente que um pedido pode abrir e para a execução que passa de 400 passos de ferramenta ou de cerca de 1,5 milhão de tokens da cota, avisando no chat. O planejamento deixa de escolher o modelo grande sozinho, e um resultado repetido do Claude não é mais contado várias vezes no uso."$json$::jsonb),
  ('en', 'whatsNew.item.quotaGuard.detail', $json$"JayV does not open an agent whose plan limit is at 95% or more, caps the agent calls one request can open, and stops a run that takes more than 400 tool steps or about 1.5 million tokens' worth of quota, saying so in the chat. Planning no longer picks the large model by itself, and a repeated Claude result is no longer counted several times in usage."$json$::jsonb),
  ('es', 'whatsNew.item.quotaGuard.detail', $json$"JayV no abre un agente cuyo límite del plan está al 95% o más, limita las llamadas de agente que una petición puede abrir y detiene la ejecución que pasa de 400 pasos de herramienta o de cerca de 1,5 millones de tokens de cuota, avisando en el chat. La planificación deja de elegir sola el modelo grande, y un resultado repetido de Claude ya no se cuenta varias veces en el uso."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.quotaGuard.detail', $json$"JayV 不会启动套餐额度已用到 95% 或以上的代理，限制一个请求可启动的代理调用次数，并在运行超过 400 个工具步骤或约 150 万 token 的额度时停止，同时在对话中说明。规划不再自行选择大模型，Claude 重复返回的结果也不再在用量中被多次计算。"$json$::jsonb),
  ('hi', 'whatsNew.item.quotaGuard.detail', $json$"JayV उस एजेंट को नहीं खोलता जिसकी प्लान सीमा 95% या अधिक है, एक अनुरोध कितनी एजेंट कॉल खोल सकता है यह सीमित करता है, और जो रन 400 टूल स्टेप या लगभग 15 लाख टोकन के कोटे से आगे जाता है उसे रोककर चैट में बताता है। प्लानिंग अब बड़ा मॉडल अपने आप नहीं चुनती, और Claude का दोहराया गया परिणाम उपयोग में कई बार नहीं गिना जाता।"$json$::jsonb),
  ('ar', 'whatsNew.item.quotaGuard.detail', $json$"لا يفتح JayV وكيلًا بلغ حدّ خطته 95% أو أكثر، ويقيّد عدد استدعاءات الوكلاء التي يفتحها الطلب الواحد، ويوقف التشغيل الذي يتجاوز 400 خطوة أدوات أو ما يعادل نحو 1.5 مليون رمز من الحصة مع إبلاغك في المحادثة. لم يعد التخطيط يختار النموذج الكبير من تلقاء نفسه، ولم تعد نتيجة Claude المكررة تُحسب عدة مرات في الاستخدام."$json$::jsonb),
  ('fr', 'whatsNew.item.quotaGuard.detail', $json$"JayV n'ouvre pas un agent dont la limite du forfait est à 95 % ou plus, plafonne les appels d'agent qu'une demande peut ouvrir et arrête l'exécution qui dépasse 400 étapes d'outil ou environ 1,5 million de jetons de quota, en le disant dans le chat. La planification ne choisit plus seule le grand modèle, et un résultat répété de Claude n'est plus compté plusieurs fois dans l'usage."$json$::jsonb),
  ('ru', 'whatsNew.item.quotaGuard.detail', $json$"JayV не открывает агента, лимит тарифа которого достиг 95% или больше, ограничивает число вызовов агентов на один запрос и останавливает запуск, который превышает 400 шагов инструментов или около 1,5 млн токенов квоты, сообщая об этом в чате. Планирование больше не выбирает большую модель само, а повторный результат Claude больше не учитывается в расходе несколько раз."$json$::jsonb),
  ('ja', 'whatsNew.item.quotaGuard.detail', $json$"JayV は、プランの上限が 95% 以上に達したエージェントを起動せず、1 つの依頼が起動できるエージェント呼び出しの数を制限し、ツール操作が 400 回、または使用枠で約 150 万トークン分を超えた実行を止めて、チャットでお知らせします。計画では大きいモデルを自動で選ばなくなり、Claude が繰り返し返した結果は使用量で何度も数えられなくなりました。"$json$::jsonb),
  ('de', 'whatsNew.item.quotaGuard.detail', $json$"JayV öffnet keinen Agenten, dessen Tariflimit bei 95 % oder mehr liegt, begrenzt die Agentenaufrufe, die eine Anfrage öffnen kann, und stoppt einen Lauf, der mehr als 400 Werkzeugschritte oder etwa 1,5 Millionen Token des Kontingents braucht, mit Hinweis im Chat. Die Planung wählt das große Modell nicht mehr von selbst, und ein wiederholtes Claude-Ergebnis wird in der Nutzung nicht mehr mehrfach gezählt."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.conversationFind.title', $json$"Pesquisar na conversa (Ctrl+F)"$json$::jsonb),
  ('en', 'whatsNew.item.conversationFind.title', $json$"Find in the conversation (Ctrl+F)"$json$::jsonb),
  ('es', 'whatsNew.item.conversationFind.title', $json$"Buscar en la conversación (Ctrl+F)"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.conversationFind.title', $json$"在对话中查找 (Ctrl+F)"$json$::jsonb),
  ('hi', 'whatsNew.item.conversationFind.title', $json$"बातचीत में खोजें (Ctrl+F)"$json$::jsonb),
  ('ar', 'whatsNew.item.conversationFind.title', $json$"البحث في المحادثة (Ctrl+F)"$json$::jsonb),
  ('fr', 'whatsNew.item.conversationFind.title', $json$"Rechercher dans la conversation (Ctrl+F)"$json$::jsonb),
  ('ru', 'whatsNew.item.conversationFind.title', $json$"Поиск в разговоре (Ctrl+F)"$json$::jsonb),
  ('ja', 'whatsNew.item.conversationFind.title', $json$"会話内を検索 (Ctrl+F)"$json$::jsonb),
  ('de', 'whatsNew.item.conversationFind.title', $json$"In der Unterhaltung suchen (Strg+F)"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F (⌘F no Mac) abre uma busca dentro do chat aberto: as ocorrências ficam destacadas, Enter e Shift+Enter vão de uma à outra e Esc fecha. Também está na paleta de comandos."$json$::jsonb),
  ('en', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F (⌘F on Mac) opens a search inside the open chat: matches are highlighted, Enter and Shift+Enter move between them and Esc closes. It is also in the command palette."$json$::jsonb),
  ('es', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F (⌘F en Mac) abre una búsqueda dentro del chat abierto: las coincidencias se resaltan, Enter y Shift+Enter pasan de una a otra y Esc cierra. También está en la paleta de comandos."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F（Mac 上为 ⌘F）会在当前聊天中打开搜索：匹配项高亮显示，Enter 和 Shift+Enter 在其间切换，Esc 关闭。命令面板中也有此项。"$json$::jsonb),
  ('hi', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F (Mac पर ⌘F) खुले चैट के भीतर खोज खोलता है: परिणाम हाइलाइट होते हैं, Enter और Shift+Enter से उनके बीच जाएँ और Esc से बंद करें। यह कमांड पैलेट में भी है।"$json$::jsonb),
  ('ar', 'whatsNew.item.conversationFind.detail', $json$"يفتح Ctrl+F (⌘F على ماك) بحثًا داخل المحادثة المفتوحة: تُميَّز النتائج، وينتقل Enter وShift+Enter بينها، ويغلق Esc البحث. وهو موجود أيضًا في لوحة الأوامر."$json$::jsonb),
  ('fr', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F (⌘F sur Mac) ouvre une recherche dans le chat ouvert : les résultats sont surlignés, Entrée et Maj+Entrée passent de l'un à l'autre et Échap ferme. C'est aussi dans la palette de commandes."$json$::jsonb),
  ('ru', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F (⌘F на Mac) открывает поиск внутри открытого чата: совпадения подсвечиваются, Enter и Shift+Enter переходят между ними, Esc закрывает. Это есть и в палитре команд."$json$::jsonb),
  ('ja', 'whatsNew.item.conversationFind.detail', $json$"Ctrl+F（Mac では ⌘F）で開いているチャット内の検索が開きます。一致箇所はハイライトされ、Enter と Shift+Enter で移動し、Esc で閉じます。コマンドパレットにもあります。"$json$::jsonb),
  ('de', 'whatsNew.item.conversationFind.detail', $json$"Strg+F (⌘F auf dem Mac) öffnet eine Suche im geöffneten Chat: Treffer werden hervorgehoben, Enter und Umschalt+Enter wechseln zwischen ihnen und Esc schließt. Sie ist auch in der Befehlspalette."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.lockedWebview.title', $json$"Atalhos do navegador bloqueados"$json$::jsonb),
  ('en', 'whatsNew.item.lockedWebview.title', $json$"Browser shortcuts are blocked"$json$::jsonb),
  ('es', 'whatsNew.item.lockedWebview.title', $json$"Atajos del navegador bloqueados"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.lockedWebview.title', $json$"浏览器快捷键已被禁用"$json$::jsonb),
  ('hi', 'whatsNew.item.lockedWebview.title', $json$"ब्राउज़र शॉर्टकट बंद"$json$::jsonb),
  ('ar', 'whatsNew.item.lockedWebview.title', $json$"اختصارات المتصفح محظورة"$json$::jsonb),
  ('fr', 'whatsNew.item.lockedWebview.title', $json$"Raccourcis du navigateur bloqués"$json$::jsonb),
  ('ru', 'whatsNew.item.lockedWebview.title', $json$"Горячие клавиши браузера заблокированы"$json$::jsonb),
  ('ja', 'whatsNew.item.lockedWebview.title', $json$"ブラウザのショートカットを無効化"$json$::jsonb),
  ('de', 'whatsNew.item.lockedWebview.title', $json$"Browser-Tastenkürzel gesperrt"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.lockedWebview.detail', $json$"No app instalado, os atalhos do motor web (recarregar, zoom, imprimir, salvar página, busca nativa, voltar e avançar, ver código-fonte, inspetor, abrir arquivos) e o menu nativo do botão direito fora dos campos de texto não fazem mais nada. Copiar, recortar, colar, selecionar tudo e desfazer continuam funcionando, assim como os atalhos do próprio JayV."$json$::jsonb),
  ('en', 'whatsNew.item.lockedWebview.detail', $json$"In the installed app, the shortcuts of the web engine (reload, zoom, print, save page, native find, back and forward, view source, inspector, opening files) and the native right-click menu outside text fields no longer do anything. Copy, cut, paste, select all and undo keep working, and so do JayV's own shortcuts."$json$::jsonb),
  ('es', 'whatsNew.item.lockedWebview.detail', $json$"En la app instalada, los atajos del motor web (recargar, zoom, imprimir, guardar página, búsqueda nativa, atrás y adelante, ver código fuente, inspector, abrir archivos) y el menú nativo del clic derecho fuera de los campos de texto ya no hacen nada. Copiar, cortar, pegar, seleccionar todo y deshacer siguen funcionando, igual que los atajos propios de JayV."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.lockedWebview.detail', $json$"在已安装的应用中，Web 引擎的快捷键（刷新、缩放、打印、保存页面、原生查找、后退和前进、查看源代码、检查器、打开文件）以及文本框之外的原生右键菜单不再起作用。复制、剪切、粘贴、全选和撤销仍可使用，JayV 自己的快捷键也一样。"$json$::jsonb),
  ('hi', 'whatsNew.item.lockedWebview.detail', $json$"इंस्टॉल किए गए ऐप में वेब इंजन के शॉर्टकट (रीलोड, ज़ूम, प्रिंट, पेज सेव, नेटिव खोज, पीछे-आगे, सोर्स देखना, इंस्पेक्टर, फ़ाइल खोलना) और टेक्स्ट फ़ील्ड के बाहर का नेटिव राइट-क्लिक मेनू अब कुछ नहीं करते। कॉपी, कट, पेस्ट, सब चुनें और पूर्ववत करें चलते रहते हैं, JayV के अपने शॉर्टकट भी।"$json$::jsonb),
  ('ar', 'whatsNew.item.lockedWebview.detail', $json$"في التطبيق المثبّت لم تعد اختصارات محرك الويب (إعادة التحميل، التكبير، الطباعة، حفظ الصفحة، البحث الأصلي، الرجوع والتقدّم، عرض المصدر، المفتّش، فتح الملفات) ولا قائمة النقر الأيمن الأصلية خارج حقول النص تفعل شيئًا. النسخ والقص واللصق وتحديد الكل والتراجع تعمل كالمعتاد، وكذلك اختصارات JayV نفسه."$json$::jsonb),
  ('fr', 'whatsNew.item.lockedWebview.detail', $json$"Dans l'app installée, les raccourcis du moteur web (recharger, zoom, imprimer, enregistrer la page, recherche native, précédent et suivant, voir la source, inspecteur, ouvrir des fichiers) et le menu natif du clic droit hors des champs de texte ne font plus rien. Copier, couper, coller, tout sélectionner et annuler continuent de fonctionner, comme les raccourcis propres à JayV."$json$::jsonb),
  ('ru', 'whatsNew.item.lockedWebview.detail', $json$"В установленном приложении горячие клавиши веб-движка (перезагрузка, масштаб, печать, сохранение страницы, встроенный поиск, назад и вперёд, исходный код, инспектор, открытие файлов) и системное контекстное меню вне текстовых полей больше ничего не делают. Копирование, вырезание, вставка, выделение всего и отмена работают, как и собственные сочетания JayV."$json$::jsonb),
  ('ja', 'whatsNew.item.lockedWebview.detail', $json$"インストール版では、Web エンジンのショートカット（再読み込み、ズーム、印刷、ページ保存、標準の検索、戻る・進む、ソース表示、インスペクタ、ファイルを開く）と、テキスト欄以外の標準の右クリックメニューは何も起こりません。コピー、切り取り、貼り付け、すべて選択、元に戻すと、JayV 独自のショートカットは引き続き使えます。"$json$::jsonb),
  ('de', 'whatsNew.item.lockedWebview.detail', $json$"In der installierten App tun die Tastenkürzel der Web-Engine (Neu laden, Zoom, Drucken, Seite speichern, native Suche, Zurück und Vor, Quelltext, Inspektor, Dateien öffnen) und das native Kontextmenü außerhalb von Textfeldern nichts mehr. Kopieren, Ausschneiden, Einfügen, Alles auswählen und Rückgängig funktionieren weiter, ebenso die eigenen Kürzel von JayV."$json$::jsonb),
  ('pt-BR', 'docs.conversationFind.title', $json$"Pesquisar na conversa"$json$::jsonb),
  ('en', 'docs.conversationFind.title', $json$"Find in the conversation"$json$::jsonb),
  ('es', 'docs.conversationFind.title', $json$"Buscar en la conversación"$json$::jsonb),
  ('zh-CN', 'docs.conversationFind.title', $json$"在对话中查找"$json$::jsonb),
  ('hi', 'docs.conversationFind.title', $json$"बातचीत में खोजें"$json$::jsonb),
  ('ar', 'docs.conversationFind.title', $json$"البحث في المحادثة"$json$::jsonb),
  ('fr', 'docs.conversationFind.title', $json$"Rechercher dans la conversation"$json$::jsonb),
  ('ru', 'docs.conversationFind.title', $json$"Поиск в разговоре"$json$::jsonb),
  ('ja', 'docs.conversationFind.title', $json$"会話内を検索"$json$::jsonb),
  ('de', 'docs.conversationFind.title', $json$"In der Unterhaltung suchen"$json$::jsonb),
  ('pt-BR', 'docs.conversationFind.summary', $json$"Pesquise as palavras da conversa aberta, com todas as ocorrências destacadas e um salto para a próxima e a anterior."$json$::jsonb),
  ('en', 'docs.conversationFind.summary', $json$"Search the words of the open conversation, with every match highlighted and a jump to the next and the previous one."$json$::jsonb),
  ('es', 'docs.conversationFind.summary', $json$"Busca las palabras de la conversación abierta, con todas las coincidencias resaltadas y un salto a la siguiente y a la anterior."$json$::jsonb),
  ('zh-CN', 'docs.conversationFind.summary', $json$"搜索当前对话中的文字，所有匹配项高亮显示，并可跳到下一个和上一个。"$json$::jsonb),
  ('hi', 'docs.conversationFind.summary', $json$"खुली बातचीत के शब्द खोजें; सभी परिणाम हाइलाइट होते हैं और अगले व पिछले पर जाया जा सकता है।"$json$::jsonb),
  ('ar', 'docs.conversationFind.summary', $json$"ابحث في كلمات المحادثة المفتوحة مع تمييز كل النتائج وانتقال إلى التالية والسابقة."$json$::jsonb),
  ('fr', 'docs.conversationFind.summary', $json$"Recherchez les mots de la conversation ouverte, avec tous les résultats surlignés et un saut vers le suivant et le précédent."$json$::jsonb),
  ('ru', 'docs.conversationFind.summary', $json$"Ищите слова в открытом разговоре: все совпадения подсвечены, можно переходить к следующему и предыдущему."$json$::jsonb),
  ('ja', 'docs.conversationFind.summary', $json$"開いている会話の語句を検索します。一致箇所はすべてハイライトされ、次・前の一致へ移動できます。"$json$::jsonb),
  ('de', 'docs.conversationFind.summary', $json$"Durchsuchen Sie die Wörter der geöffneten Unterhaltung, alle Treffer hervorgehoben, mit Sprung zum nächsten und vorherigen."$json$::jsonb),
  ('pt-BR', 'docs.conversationFind.usage', $json$"Pressione Ctrl+F (⌘F no Mac) em um chat, digite e use Enter e Shift+Enter (ou as setas) para ir de uma ocorrência à outra; Esc fecha. A mesma entrada está na paleta de comandos. Maiúsculas e acentos não importam. No app instalado, os outros atalhos do motor web (recarregar, zoom, imprimir, salvar página, busca nativa, voltar e avançar, ver código-fonte, inspetor) ficam desligados, assim como o menu nativo do botão direito fora dos campos de texto; copiar, recortar, colar, selecionar tudo e desfazer continuam funcionando."$json$::jsonb),
  ('en', 'docs.conversationFind.usage', $json$"Press Ctrl+F (⌘F on Mac) in a chat, type, and use Enter and Shift+Enter (or the arrows) to move between matches; Esc closes. The same entry is in the command palette. Case and accents do not matter. In the installed app the other shortcuts of the web engine (reload, zoom, print, save page, native find, back and forward, view source, inspector) are turned off, and so is the native right-click menu outside text fields; copy, cut, paste, select all and undo keep working."$json$::jsonb),
  ('es', 'docs.conversationFind.usage', $json$"Pulsa Ctrl+F (⌘F en Mac) en un chat, escribe y usa Enter y Shift+Enter (o las flechas) para pasar de una coincidencia a otra; Esc cierra. La misma entrada está en la paleta de comandos. Mayúsculas y acentos no importan. En la app instalada, los demás atajos del motor web (recargar, zoom, imprimir, guardar página, búsqueda nativa, atrás y adelante, ver código fuente, inspector) están desactivados, igual que el menú nativo del clic derecho fuera de los campos de texto; copiar, cortar, pegar, seleccionar todo y deshacer siguen funcionando."$json$::jsonb),
  ('zh-CN', 'docs.conversationFind.usage', $json$"在聊天中按 Ctrl+F（Mac 上为 ⌘F），输入内容，用 Enter 和 Shift+Enter（或箭头）在匹配项之间移动；Esc 关闭。命令面板中也有同样的入口。不区分大小写和重音。在已安装的应用中，Web 引擎的其他快捷键（刷新、缩放、打印、保存页面、原生查找、后退和前进、查看源代码、检查器）以及文本框之外的原生右键菜单均已关闭；复制、剪切、粘贴、全选和撤销仍然可用。"$json$::jsonb),
  ('hi', 'docs.conversationFind.usage', $json$"चैट में Ctrl+F (Mac पर ⌘F) दबाएँ, लिखें, और परिणामों के बीच जाने के लिए Enter और Shift+Enter (या तीर) इस्तेमाल करें; Esc बंद करता है। यही प्रविष्टि कमांड पैलेट में भी है। अक्षर-रूप और उच्चारण चिह्न मायने नहीं रखते। इंस्टॉल किए गए ऐप में वेब इंजन के बाकी शॉर्टकट (रीलोड, ज़ूम, प्रिंट, पेज सेव, नेटिव खोज, पीछे-आगे, सोर्स देखना, इंस्पेक्टर) और टेक्स्ट फ़ील्ड के बाहर का नेटिव राइट-क्लिक मेनू बंद हैं; कॉपी, कट, पेस्ट, सब चुनें और पूर्ववत करें चलते रहते हैं।"$json$::jsonb),
  ('ar', 'docs.conversationFind.usage', $json$"اضغط Ctrl+F (⌘F على ماك) داخل محادثة، واكتب، واستخدم Enter وShift+Enter (أو الأسهم) للتنقل بين النتائج؛ ويغلق Esc البحث. والإدخال نفسه موجود في لوحة الأوامر. لا يهم حجم الأحرف ولا علامات التشكيل. في التطبيق المثبّت تُعطَّل بقية اختصارات محرك الويب (إعادة التحميل، التكبير، الطباعة، حفظ الصفحة، البحث الأصلي، الرجوع والتقدّم، عرض المصدر، المفتّش) وكذلك قائمة النقر الأيمن الأصلية خارج حقول النص؛ ويستمر عمل النسخ والقص واللصق وتحديد الكل والتراجع."$json$::jsonb),
  ('fr', 'docs.conversationFind.usage', $json$"Appuyez sur Ctrl+F (⌘F sur Mac) dans un chat, saisissez, puis utilisez Entrée et Maj+Entrée (ou les flèches) pour passer d'un résultat à l'autre ; Échap ferme. La même entrée est dans la palette de commandes. Majuscules et accents n'ont pas d'importance. Dans l'app installée, les autres raccourcis du moteur web (recharger, zoom, imprimer, enregistrer la page, recherche native, précédent et suivant, voir la source, inspecteur) sont désactivés, ainsi que le menu natif du clic droit hors des champs de texte ; copier, couper, coller, tout sélectionner et annuler continuent de fonctionner."$json$::jsonb),
  ('ru', 'docs.conversationFind.usage', $json$"Нажмите Ctrl+F (⌘F на Mac) в чате, введите текст и переходите между совпадениями клавишами Enter и Shift+Enter (или стрелками); Esc закрывает поиск. Тот же пункт есть в палитре команд. Регистр и диакритика не важны. В установленном приложении остальные горячие клавиши веб-движка (перезагрузка, масштаб, печать, сохранение страницы, встроенный поиск, назад и вперёд, исходный код, инспектор) и системное контекстное меню вне текстовых полей отключены; копирование, вырезание, вставка, выделение всего и отмена работают."$json$::jsonb),
  ('ja', 'docs.conversationFind.usage', $json$"チャットで Ctrl+F（Mac では ⌘F）を押して入力し、Enter と Shift+Enter（または矢印）で一致箇所を移動します。Esc で閉じます。同じ項目がコマンドパレットにもあります。大文字・小文字やアクセントは区別しません。インストール版では、Web エンジンのその他のショートカット（再読み込み、ズーム、印刷、ページ保存、標準の検索、戻る・進む、ソース表示、インスペクタ）とテキスト欄以外の標準の右クリックメニューは無効で、コピー、切り取り、貼り付け、すべて選択、元に戻すは使えます。"$json$::jsonb),
  ('de', 'docs.conversationFind.usage', $json$"Drücken Sie in einem Chat Strg+F (⌘F auf dem Mac), tippen Sie und wechseln Sie mit Enter und Umschalt+Enter (oder den Pfeilen) zwischen den Treffern; Esc schließt. Derselbe Eintrag ist in der Befehlspalette. Groß-/Kleinschreibung und Akzente spielen keine Rolle. In der installierten App sind die übrigen Kürzel der Web-Engine (Neu laden, Zoom, Drucken, Seite speichern, native Suche, Zurück und Vor, Quelltext, Inspektor) und das native Kontextmenü außerhalb von Textfeldern abgeschaltet; Kopieren, Ausschneiden, Einfügen, Alles auswählen und Rückgängig funktionieren weiter."$json$::jsonb),
  ('pt-BR', 'docs.consumptionGuard.title', $json$"Trava de cota"$json$::jsonb),
  ('en', 'docs.consumptionGuard.title', $json$"Quota guard"$json$::jsonb),
  ('es', 'docs.consumptionGuard.title', $json$"Freno de cuota"$json$::jsonb),
  ('zh-CN', 'docs.consumptionGuard.title', $json$"额度保护"$json$::jsonb),
  ('hi', 'docs.consumptionGuard.title', $json$"कोटा सुरक्षा"$json$::jsonb),
  ('ar', 'docs.consumptionGuard.title', $json$"حماية الحصة"$json$::jsonb),
  ('fr', 'docs.consumptionGuard.title', $json$"Garde-fou de quota"$json$::jsonb),
  ('ru', 'docs.consumptionGuard.title', $json$"Защита квоты"$json$::jsonb),
  ('ja', 'docs.consumptionGuard.title', $json$"使用枠ガード"$json$::jsonb),
  ('de', 'docs.consumptionGuard.title', $json$"Kontingentschutz"$json$::jsonb),
  ('pt-BR', 'docs.consumptionGuard.summary', $json$"O JayV para uma execução antes de ela queimar a cota do seu plano: não abre um agente cujo limite do plano está quase todo usado, limita o que um pedido pode abrir e para a execução que dá passos ou usa tokens demais."$json$::jsonb),
  ('en', 'docs.consumptionGuard.summary', $json$"JayV stops a run before it burns the quota of your plan: it does not open an agent whose plan limit is almost used, caps what one request can open and stops a run that takes too many steps or tokens."$json$::jsonb),
  ('es', 'docs.consumptionGuard.summary', $json$"JayV detiene una ejecución antes de que queme la cuota de tu plan: no abre un agente cuyo límite del plan está casi agotado, limita lo que una petición puede abrir y detiene la ejecución que da demasiados pasos o usa demasiados tokens."$json$::jsonb),
  ('zh-CN', 'docs.consumptionGuard.summary', $json$"JayV 会在运行耗尽你的套餐额度之前将其停止：不会启动套餐额度快用完的代理，限制一个请求能启动的内容，并停止步骤或 token 过多的运行。"$json$::jsonb),
  ('hi', 'docs.consumptionGuard.summary', $json$"JayV किसी रन को आपके प्लान का कोटा जलाने से पहले रोक देता है: जिस एजेंट की प्लान सीमा लगभग पूरी हो चुकी है उसे नहीं खोलता, एक अनुरोध कितना खोल सकता है यह सीमित करता है, और बहुत अधिक स्टेप या टोकन लेने वाले रन को रोकता है।"$json$::jsonb),
  ('ar', 'docs.consumptionGuard.summary', $json$"يوقف JayV التشغيل قبل أن يستنزف حصة خطتك: لا يفتح وكيلًا استُهلك حدّ خطته تقريبًا، ويقيّد ما يمكن للطلب أن يفتحه، ويوقف التشغيل الذي يتخذ خطوات أو يستهلك رموزًا أكثر من اللازم."$json$::jsonb),
  ('fr', 'docs.consumptionGuard.summary', $json$"JayV arrête une exécution avant qu'elle ne brûle le quota de votre forfait : il n'ouvre pas un agent dont la limite du forfait est presque épuisée, plafonne ce qu'une demande peut ouvrir et arrête l'exécution qui fait trop d'étapes ou consomme trop de jetons."$json$::jsonb),
  ('ru', 'docs.consumptionGuard.summary', $json$"JayV останавливает запуск, прежде чем он сожжёт квоту вашего тарифа: не открывает агента, лимит которого почти исчерпан, ограничивает то, что может открыть один запрос, и останавливает запуск с чрезмерным числом шагов или токенов."$json$::jsonb),
  ('ja', 'docs.consumptionGuard.summary', $json$"JayV は、実行がプランの使用枠を使い切る前に止めます。プランの上限がほぼ尽きたエージェントは起動せず、1 つの依頼が起動できる数を制限し、操作やトークンが多すぎる実行を止めます。"$json$::jsonb),
  ('de', 'docs.consumptionGuard.summary', $json$"JayV stoppt einen Lauf, bevor er das Kontingent Ihres Tarifs verbrennt: Es öffnet keinen Agenten, dessen Tariflimit fast aufgebraucht ist, begrenzt, was eine Anfrage öffnen kann, und stoppt einen Lauf mit zu vielen Schritten oder Token."$json$::jsonb),
  ('pt-BR', 'docs.consumptionGuard.usage', $json$"Está sempre ligada e vale para Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter e LiteLLM. Um agente cuja janela do plano (sessão, semana ou mês) marca 95% ou mais não é aberto, e outro agente assume quando há um ligado. Um pedido abre no máximo 12 chamadas de agente (plano, divisão, revisão, novas tentativas), uma execução para após 400 passos de ferramenta ou cerca de 1,5 milhão de tokens da cota, e o planejamento não escolhe o modelo grande sozinho. Quando algo é parado, o chat diz o que e por quê, e o que o agente já fez fica. Os limites do plano estão em Estatísticas."$json$::jsonb),
  ('en', 'docs.consumptionGuard.usage', $json$"It is always on and covers Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter and LiteLLM. An agent whose plan window (session, week or month) reads 95% or more is not opened, and another agent takes over when one is on. A request opens at most 12 agent calls (plan, split, review, retries), a run stops after 400 tool steps or about 1.5 million tokens' worth of quota, and planning does not pick the large model by itself. When it stops something, the chat says what and why, and what the agent already did stays. Plan limits are in Statistics."$json$::jsonb),
  ('es', 'docs.consumptionGuard.usage', $json$"Está siempre activo y cubre Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter y LiteLLM. Un agente cuya ventana del plan (sesión, semana o mes) marca 95% o más no se abre, y otro agente toma el relevo si hay uno activo. Una petición abre como máximo 12 llamadas de agente (plan, división, revisión, reintentos), una ejecución se detiene tras 400 pasos de herramienta o cerca de 1,5 millones de tokens de cuota, y la planificación no elige sola el modelo grande. Cuando algo se detiene, el chat dice qué y por qué, y lo que el agente ya hizo se queda. Los límites del plan están en Estadísticas."$json$::jsonb),
  ('zh-CN', 'docs.consumptionGuard.usage', $json$"它始终开启，适用于 Claude Code、Codex、Copilot、Cursor、Kilo Code、OpenRouter 和 LiteLLM。套餐窗口（会话、每周或每月）达到 95% 或以上的代理不会被启动，若有其他已启用的代理则由其接手。一个请求最多启动 12 次代理调用（计划、拆分、审查、重试），一次运行在 400 个工具步骤或约 150 万 token 的额度后停止，规划也不会自行选择大模型。停止时，聊天会说明停止了什么及原因，代理已完成的内容会保留。套餐额度可在“统计”中查看。"$json$::jsonb),
  ('hi', 'docs.consumptionGuard.usage', $json$"यह हमेशा चालू रहता है और Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter और LiteLLM पर लागू होता है। जिस एजेंट की प्लान विंडो (सेशन, सप्ताह या महीना) 95% या अधिक दिखाती है उसे नहीं खोला जाता, और कोई दूसरा एजेंट चालू हो तो वह काम संभालता है। एक अनुरोध अधिकतम 12 एजेंट कॉल (प्लान, विभाजन, समीक्षा, पुनः प्रयास) खोलता है, रन 400 टूल स्टेप या लगभग 15 लाख टोकन के कोटे के बाद रुकता है, और प्लानिंग बड़ा मॉडल अपने आप नहीं चुनती। कुछ रुकने पर चैट बताता है क्या और क्यों, और एजेंट जो कर चुका है वह बना रहता है। प्लान की सीमाएँ आँकड़ों में हैं।"$json$::jsonb),
  ('ar', 'docs.consumptionGuard.usage', $json$"هي مفعّلة دائمًا وتشمل Claude Code وCodex وCopilot وCursor وKilo Code وOpenRouter وLiteLLM. لا يُفتح الوكيل الذي تُظهر نافذة خطته (الجلسة أو الأسبوع أو الشهر) 95% أو أكثر، ويتولى وكيل آخر المهمة إن كان مفعّلًا. يفتح الطلب 12 استدعاءً للوكلاء كحد أقصى (الخطة والتقسيم والمراجعة وإعادة المحاولة)، ويتوقف التشغيل بعد 400 خطوة أدوات أو ما يعادل نحو 1.5 مليون رمز من الحصة، ولا يختار التخطيط النموذج الكبير من تلقاء نفسه. عند إيقاف شيء تذكر المحادثة ماذا ولماذا، ويبقى ما أنجزه الوكيل. حدود الخطة في الإحصاءات."$json$::jsonb),
  ('fr', 'docs.consumptionGuard.usage', $json$"Il est toujours actif et couvre Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter et LiteLLM. Un agent dont la fenêtre du forfait (session, semaine ou mois) affiche 95 % ou plus n'est pas ouvert, et un autre agent prend le relais s'il y en a un d'activé. Une demande ouvre au plus 12 appels d'agent (plan, découpage, revue, nouvelles tentatives), une exécution s'arrête après 400 étapes d'outil ou environ 1,5 million de jetons de quota, et la planification ne choisit pas seule le grand modèle. Quand quelque chose est arrêté, le chat dit quoi et pourquoi, et ce que l'agent a déjà fait reste. Les limites du forfait sont dans Statistiques."$json$::jsonb),
  ('ru', 'docs.consumptionGuard.usage', $json$"Защита всегда включена и охватывает Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter и LiteLLM. Агент, окно тарифа которого (сессия, неделя или месяц) показывает 95% или больше, не открывается, и его заменяет другой включённый агент. Один запрос открывает не более 12 вызовов агентов (план, разделение, проверка, повторы), запуск останавливается после 400 шагов инструментов или около 1,5 млн токенов квоты, а планирование не выбирает большую модель само. Когда что-то остановлено, чат объясняет, что и почему, а сделанное агентом остаётся. Лимиты тарифа — в разделе «Статистика»."$json$::jsonb),
  ('ja', 'docs.consumptionGuard.usage', $json$"常にオンで、Claude Code、Codex、Copilot、Cursor、Kilo Code、OpenRouter、LiteLLM が対象です。プランの枠（セッション、週、月）が 95% 以上のエージェントは起動せず、ほかにオンのエージェントがあればそちらが引き継ぎます。1 つの依頼が起動できるエージェント呼び出しは最大 12 回（計画、分割、レビュー、再試行）で、実行はツール操作 400 回または使用枠で約 150 万トークン分に達すると止まり、計画では大きいモデルを自動で選びません。止めたときは、何をなぜ止めたかがチャットに表示され、エージェントがすでに行った内容は残ります。プランの上限は「統計」で確認できます。"$json$::jsonb),
  ('de', 'docs.consumptionGuard.usage', $json$"Der Schutz ist immer aktiv und gilt für Claude Code, Codex, Copilot, Cursor, Kilo Code, OpenRouter und LiteLLM. Ein Agent, dessen Tariffenster (Sitzung, Woche oder Monat) 95 % oder mehr anzeigt, wird nicht geöffnet; ein anderer eingeschalteter Agent übernimmt. Eine Anfrage öffnet höchstens 12 Agentenaufrufe (Plan, Aufteilung, Review, Wiederholungen), ein Lauf stoppt nach 400 Werkzeugschritten oder etwa 1,5 Millionen Token Kontingent, und die Planung wählt das große Modell nicht von selbst. Wird etwas gestoppt, sagt der Chat was und warum, und was der Agent schon getan hat, bleibt. Die Tariflimits stehen unter Statistik."$json$::jsonb),
  ('pt-BR', 'docs.command.find', $json$"Pesquisa as palavras da conversa aberta."$json$::jsonb),
  ('en', 'docs.command.find', $json$"Searches the words of the open conversation."$json$::jsonb),
  ('es', 'docs.command.find', $json$"Busca las palabras de la conversación abierta."$json$::jsonb),
  ('zh-CN', 'docs.command.find', $json$"搜索当前对话中的文字。"$json$::jsonb),
  ('hi', 'docs.command.find', $json$"खुली बातचीत के शब्द खोजता है।"$json$::jsonb),
  ('ar', 'docs.command.find', $json$"يبحث في كلمات المحادثة المفتوحة."$json$::jsonb),
  ('fr', 'docs.command.find', $json$"Recherche les mots de la conversation ouverte."$json$::jsonb),
  ('ru', 'docs.command.find', $json$"Ищет слова в открытом разговоре."$json$::jsonb),
  ('ja', 'docs.command.find', $json$"開いている会話の語句を検索します。"$json$::jsonb),
  ('de', 'docs.command.find', $json$"Durchsucht die Wörter der geöffneten Unterhaltung."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
