-- v0.50.0: um pedido grande dividido entre agentes que trabalham ao mesmo
-- tempo, cada um numa git worktree própria.
--
-- Só textos: as etapas da divisão no chat, a opção em Configuração › Jev ›
-- Roteamento e o item da janela "Novidades".

insert into public.translations (locale, key, value) values
  ('pt-BR', 'beat.split', $json$"Dividido em {count} partes feitas ao mesmo tempo: {parts}"$json$::jsonb),
  ('pt-BR', 'beat.subtask.applied', $json$"{title} ({agent}): mudanças aplicadas no projeto"$json$::jsonb),
  ('pt-BR', 'beat.subtask.empty', $json$"{title} ({agent}): terminou sem mudar arquivos"$json$::jsonb),
  ('pt-BR', 'beat.subtask.conflict', $json$"{title} ({agent}): as mudanças não encaixaram no projeto e ficaram guardadas em {patch}"$json$::jsonb),
  ('pt-BR', 'beat.subtask.failed', $json$"{title} ({agent}): o agente falhou"$json$::jsonb),
  ('pt-BR', 'jev.parallel', $json$"Dividir pedidos grandes entre agentes"$json$::jsonb),
  ('pt-BR', 'jev.parallel.hint', $json$"Num pedido complexo do modo build num projeto git, o plano divide o trabalho em partes com arquivos separados; cada parte vai a um agente diferente, numa cópia própria do projeto, ao mesmo tempo, e as mudanças voltam para o projeto. Custa uma chamada por parte, mais a divisão."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.parallelTasks.title', $json$"Pedidos grandes divididos entre agentes trabalhando ao mesmo tempo"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.parallelTasks.detail', $json$"Ligue Dividir pedidos grandes entre agentes em Configuração › Jev › Roteamento. Num pedido complexo do modo build num projeto git, um modelo de raciocínio divide o trabalho em até 4 partes que mexem em arquivos separados. Cada parte vai a um agente diferente, numa cópia própria do projeto (git worktree), todas ao mesmo tempo, e as mudanças voltam para a sua pasta. A parte cujas mudanças não encaixam mais fica guardada como patch para você aplicar com git apply."$json$::jsonb),
  ('en', 'beat.split', $json$"Split into {count} parts done at the same time: {parts}"$json$::jsonb),
  ('en', 'beat.subtask.applied', $json$"{title} ({agent}): changes applied to the project"$json$::jsonb),
  ('en', 'beat.subtask.empty', $json$"{title} ({agent}): finished without changing files"$json$::jsonb),
  ('en', 'beat.subtask.conflict', $json$"{title} ({agent}): the changes did not fit the project and were kept in {patch}"$json$::jsonb),
  ('en', 'beat.subtask.failed', $json$"{title} ({agent}): the agent failed"$json$::jsonb),
  ('en', 'jev.parallel', $json$"Split big requests between agents"$json$::jsonb),
  ('en', 'jev.parallel.hint', $json$"In a complex build request in a git project, the plan splits the work into parts with separate files; each part goes to a different agent, in its own copy of the project, at the same time, and the changes come back to the project. It costs one call per part plus the split."$json$::jsonb),
  ('en', 'whatsNew.item.parallelTasks.title', $json$"Big requests split between agents working at the same time"$json$::jsonb),
  ('en', 'whatsNew.item.parallelTasks.detail', $json$"Turn on Split big requests between agents in Settings › Jev › Routing. In a complex request in build mode in a git project, a reasoning model splits the work into up to 4 parts that touch separate files. Each part goes to a different agent, in its own copy of the project (git worktree), all at the same time, and the changes come back to your folder. A part whose changes no longer fit is kept as a patch for you to apply with git apply."$json$::jsonb),
  ('es', 'beat.split', $json$"Dividido en {count} partes hechas al mismo tiempo: {parts}"$json$::jsonb),
  ('es', 'beat.subtask.applied', $json$"{title} ({agent}): cambios aplicados al proyecto"$json$::jsonb),
  ('es', 'beat.subtask.empty', $json$"{title} ({agent}): terminó sin cambiar archivos"$json$::jsonb),
  ('es', 'beat.subtask.conflict', $json$"{title} ({agent}): los cambios no encajaron en el proyecto y se guardaron en {patch}"$json$::jsonb),
  ('es', 'beat.subtask.failed', $json$"{title} ({agent}): el agente falló"$json$::jsonb),
  ('es', 'jev.parallel', $json$"Dividir solicitudes grandes entre agentes"$json$::jsonb),
  ('es', 'jev.parallel.hint', $json$"En una solicitud compleja en modo build en un proyecto git, el plan divide el trabajo en partes con archivos separados; cada parte va a un agente distinto, en su propia copia del proyecto, al mismo tiempo, y los cambios vuelven al proyecto. Cuesta una llamada por parte más la división."$json$::jsonb),
  ('es', 'whatsNew.item.parallelTasks.title', $json$"Solicitudes grandes divididas entre agentes que trabajan a la vez"$json$::jsonb),
  ('es', 'whatsNew.item.parallelTasks.detail', $json$"Activa Dividir solicitudes grandes entre agentes en Configuración › Jev › Enrutamiento. En una solicitud compleja en modo build en un proyecto git, un modelo de razonamiento divide el trabajo en hasta 4 partes que tocan archivos separados. Cada parte va a un agente distinto, en su propia copia del proyecto (git worktree), todas a la vez, y los cambios vuelven a tu carpeta. La parte cuyos cambios ya no encajan se guarda como patch para que la apliques con git apply."$json$::jsonb),
  ('zh-CN', 'beat.split', $json$"拆分为 {count} 个同时进行的部分:{parts}"$json$::jsonb),
  ('zh-CN', 'beat.subtask.applied', $json$"{title}({agent}):更改已应用到项目"$json$::jsonb),
  ('zh-CN', 'beat.subtask.empty', $json$"{title}({agent}):已完成,未更改文件"$json$::jsonb),
  ('zh-CN', 'beat.subtask.conflict', $json$"{title}({agent}):更改无法应用到项目,已保存到 {patch}"$json$::jsonb),
  ('zh-CN', 'beat.subtask.failed', $json$"{title}({agent}):代理失败"$json$::jsonb),
  ('zh-CN', 'jev.parallel', $json$"把大请求拆分给多个代理"$json$::jsonb),
  ('zh-CN', 'jev.parallel.hint', $json$"在 git 项目中 build 模式的复杂请求里,计划会把工作拆分成文件互不重叠的部分;每个部分同时交给不同的代理,在各自的项目副本中完成,更改再回到项目中。每个部分一次调用,外加拆分的一次。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.parallelTasks.title', $json$"大请求拆分给同时工作的多个代理"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.parallelTasks.detail', $json$"在 设置 › Jev › 路由 中打开“把大请求拆分给多个代理”。在 git 项目中 build 模式的复杂请求里,推理模型会把工作拆分为最多 4 个文件互不重叠的部分。每个部分交给不同的代理,在各自的项目副本(git worktree)中同时进行,更改会回到你的文件夹。更改无法再应用的部分会保存为补丁,你可以用 git apply 应用。"$json$::jsonb),
  ('hi', 'beat.split', $json$"{count} हिस्सों में बाँटा गया, जो एक साथ चल रहे हैं: {parts}"$json$::jsonb),
  ('hi', 'beat.subtask.applied', $json$"{title} ({agent}): बदलाव प्रोजेक्ट में लागू किए गए"$json$::jsonb),
  ('hi', 'beat.subtask.empty', $json$"{title} ({agent}): फ़ाइलें बदले बिना पूरा हुआ"$json$::jsonb),
  ('hi', 'beat.subtask.conflict', $json$"{title} ({agent}): बदलाव प्रोजेक्ट में फ़िट नहीं हुए और {patch} में रखे गए"$json$::jsonb),
  ('hi', 'beat.subtask.failed', $json$"{title} ({agent}): एजेंट विफल रहा"$json$::jsonb),
  ('hi', 'jev.parallel', $json$"बड़े अनुरोध एजेंटों में बाँटें"$json$::jsonb),
  ('hi', 'jev.parallel.hint', $json$"git प्रोजेक्ट में बिल्ड मोड के जटिल अनुरोध में, योजना काम को अलग-अलग फ़ाइलों वाले हिस्सों में बाँटती है; हर हिस्सा एक साथ अलग एजेंट को, प्रोजेक्ट की उसकी अपनी कॉपी में जाता है, और बदलाव प्रोजेक्ट में लौटते हैं। हर हिस्से की एक कॉल और बँटवारे की एक कॉल लगती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.parallelTasks.title', $json$"बड़े अनुरोध एक साथ काम करने वाले एजेंटों में बँटते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.parallelTasks.detail', $json$"सेटिंग्स › Jev › रूटिंग में बड़े अनुरोध एजेंटों में बाँटें चालू करें। git प्रोजेक्ट में बिल्ड मोड के जटिल अनुरोध में, एक रीज़निंग मॉडल काम को अलग-अलग फ़ाइलों वाले अधिकतम 4 हिस्सों में बाँटता है। हर हिस्सा अलग एजेंट को, प्रोजेक्ट की उसकी अपनी कॉपी (git worktree) में, सब एक साथ जाता है, और बदलाव आपके फ़ोल्डर में लौटते हैं। जिस हिस्से के बदलाव अब फ़िट नहीं होते, वह पैच के रूप में रखा जाता है जिसे आप git apply से लागू कर सकते हैं।"$json$::jsonb),
  ('ar', 'beat.split', $json$"قُسّم إلى {count} أجزاء تُنفَّذ في الوقت نفسه: {parts}"$json$::jsonb),
  ('ar', 'beat.subtask.applied', $json$"{title} ({agent}): طُبّقت التعديلات على المشروع"$json$::jsonb),
  ('ar', 'beat.subtask.empty', $json$"{title} ({agent}): انتهى دون تعديل ملفات"$json$::jsonb),
  ('ar', 'beat.subtask.conflict', $json$"{title} ({agent}): لم تتوافق التعديلات مع المشروع وحُفظت في {patch}"$json$::jsonb),
  ('ar', 'beat.subtask.failed', $json$"{title} ({agent}): فشل الوكيل"$json$::jsonb),
  ('ar', 'jev.parallel', $json$"تقسيم الطلبات الكبيرة بين الوكلاء"$json$::jsonb),
  ('ar', 'jev.parallel.hint', $json$"في الطلب المعقّد في وضع البناء داخل مشروع git، تقسّم الخطة العمل إلى أجزاء بملفات منفصلة، ويذهب كل جزء إلى وكيل مختلف في نسخته الخاصة من المشروع في الوقت نفسه، ثم تعود التعديلات إلى المشروع. يكلّف ذلك استدعاءً لكل جزء إضافةً إلى التقسيم."$json$::jsonb),
  ('ar', 'whatsNew.item.parallelTasks.title', $json$"الطلبات الكبيرة تُقسَّم بين وكلاء يعملون في الوقت نفسه"$json$::jsonb),
  ('ar', 'whatsNew.item.parallelTasks.detail', $json$"فعّل «تقسيم الطلبات الكبيرة بين الوكلاء» في الإعدادات › Jev › التوجيه. في الطلب المعقّد في وضع البناء داخل مشروع git، يقسّم نموذج استدلال العمل إلى 4 أجزاء على الأكثر بملفات منفصلة. يذهب كل جزء إلى وكيل مختلف في نسخته الخاصة من المشروع (git worktree)، وكلها في الوقت نفسه، ثم تعود التعديلات إلى مجلدك. والجزء الذي لم تعد تعديلاته متوافقة يُحفظ كرقعة يمكنك تطبيقها بـ git apply."$json$::jsonb),
  ('fr', 'beat.split', $json$"Découpé en {count} parties faites en même temps : {parts}"$json$::jsonb),
  ('fr', 'beat.subtask.applied', $json$"{title} ({agent}) : modifications appliquées au projet"$json$::jsonb),
  ('fr', 'beat.subtask.empty', $json$"{title} ({agent}) : terminé sans modifier de fichier"$json$::jsonb),
  ('fr', 'beat.subtask.conflict', $json$"{title} ({agent}) : les modifications ne s’appliquaient plus au projet et ont été gardées dans {patch}"$json$::jsonb),
  ('fr', 'beat.subtask.failed', $json$"{title} ({agent}) : l’agent a échoué"$json$::jsonb),
  ('fr', 'jev.parallel', $json$"Répartir les grosses demandes entre agents"$json$::jsonb),
  ('fr', 'jev.parallel.hint', $json$"Pour une demande complexe en mode build dans un projet git, le plan découpe le travail en parties aux fichiers distincts ; chaque partie va à un agent différent, dans sa propre copie du projet, en même temps, et les modifications reviennent dans le projet. Cela coûte un appel par partie plus le découpage."$json$::jsonb),
  ('fr', 'whatsNew.item.parallelTasks.title', $json$"Les grosses demandes réparties entre agents qui travaillent en même temps"$json$::jsonb),
  ('fr', 'whatsNew.item.parallelTasks.detail', $json$"Activez Répartir les grosses demandes entre agents dans Configuration › Jev › Routage. Pour une demande complexe en mode build dans un projet git, un modèle de raisonnement découpe le travail en 4 parties au plus, aux fichiers distincts. Chaque partie va à un agent différent, dans sa propre copie du projet (git worktree), toutes en même temps, et les modifications reviennent dans votre dossier. Une partie dont les modifications ne s’appliquent plus est gardée comme patch à appliquer avec git apply."$json$::jsonb),
  ('ru', 'beat.split', $json$"Разделено на части, выполняемые одновременно ({count}): {parts}"$json$::jsonb),
  ('ru', 'beat.subtask.applied', $json$"{title} ({agent}): изменения применены к проекту"$json$::jsonb),
  ('ru', 'beat.subtask.empty', $json$"{title} ({agent}): завершено без изменения файлов"$json$::jsonb),
  ('ru', 'beat.subtask.conflict', $json$"{title} ({agent}): изменения не подошли к проекту и сохранены в {patch}"$json$::jsonb),
  ('ru', 'beat.subtask.failed', $json$"{title} ({agent}): агент завершился с ошибкой"$json$::jsonb),
  ('ru', 'jev.parallel', $json$"Делить большие запросы между агентами"$json$::jsonb),
  ('ru', 'jev.parallel.hint', $json$"В сложном запросе в режиме build в git-проекте план делит работу на части с разными файлами; каждая часть одновременно уходит другому агенту в отдельную копию проекта, а изменения возвращаются в проект. Это по одному вызову на часть плюс разделение."$json$::jsonb),
  ('ru', 'whatsNew.item.parallelTasks.title', $json$"Большие запросы делятся между агентами, работающими одновременно"$json$::jsonb),
  ('ru', 'whatsNew.item.parallelTasks.detail', $json$"Включите «Делить большие запросы между агентами» в Настройки › Jev › Маршрутизация. В сложном запросе в режиме build в git-проекте модель рассуждения делит работу максимум на 4 части с разными файлами. Каждая часть уходит другому агенту в отдельную копию проекта (git worktree), все одновременно, а изменения возвращаются в вашу папку. Часть, изменения которой больше не подходят, сохраняется как патч, который можно применить через git apply."$json$::jsonb),
  ('ja', 'beat.split', $json$"{count} 個のパートに分割し、同時に進めます: {parts}"$json$::jsonb),
  ('ja', 'beat.subtask.applied', $json$"{title}({agent}): 変更をプロジェクトに適用しました"$json$::jsonb),
  ('ja', 'beat.subtask.empty', $json$"{title}({agent}): ファイルを変更せずに完了しました"$json$::jsonb),
  ('ja', 'beat.subtask.conflict', $json$"{title}({agent}): 変更がプロジェクトに適用できず、{patch} に保存しました"$json$::jsonb),
  ('ja', 'beat.subtask.failed', $json$"{title}({agent}): エージェントが失敗しました"$json$::jsonb),
  ('ja', 'jev.parallel', $json$"大きな依頼をエージェントで分担"$json$::jsonb),
  ('ja', 'jev.parallel.hint', $json$"git プロジェクトでの build モードの複雑な依頼では、計画が作業をファイルの重ならないパートに分けます。各パートは別々のエージェントが、それぞれのプロジェクトのコピーで同時に進め、変更はプロジェクトに戻ります。パートごとに1回の呼び出しと分割の分がかかります。"$json$::jsonb),
  ('ja', 'whatsNew.item.parallelTasks.title', $json$"大きな依頼を同時に動く複数のエージェントで分担"$json$::jsonb),
  ('ja', 'whatsNew.item.parallelTasks.detail', $json$"設定 › Jev › ルーティングで「大きな依頼をエージェントで分担」をオンにしてください。git プロジェクトでの build モードの複雑な依頼では、推論モデルが作業をファイルの重ならない最大4つのパートに分けます。各パートは別々のエージェントが、それぞれのプロジェクトのコピー(git worktree)で同時に進め、変更はあなたのフォルダーに戻ります。変更が適用できなくなったパートはパッチとして保存され、git apply で適用できます。"$json$::jsonb),
  ('de', 'beat.split', $json$"In {count} Teile aufgeteilt, die gleichzeitig laufen: {parts}"$json$::jsonb),
  ('de', 'beat.subtask.applied', $json$"{title} ({agent}): Änderungen ins Projekt übernommen"$json$::jsonb),
  ('de', 'beat.subtask.empty', $json$"{title} ({agent}): fertig, ohne Dateien zu ändern"$json$::jsonb),
  ('de', 'beat.subtask.conflict', $json$"{title} ({agent}): Die Änderungen passten nicht mehr ins Projekt und wurden in {patch} gespeichert"$json$::jsonb),
  ('de', 'beat.subtask.failed', $json$"{title} ({agent}): Der Agent ist gescheitert"$json$::jsonb),
  ('de', 'jev.parallel', $json$"Große Anfragen auf Agenten verteilen"$json$::jsonb),
  ('de', 'jev.parallel.hint', $json$"Bei einer komplexen Anfrage im Build-Modus in einem Git-Projekt teilt der Plan die Arbeit in Teile mit getrennten Dateien; jeder Teil geht gleichzeitig an einen anderen Agenten in einer eigenen Kopie des Projekts, und die Änderungen kommen ins Projekt zurück. Das kostet einen Aufruf pro Teil plus die Aufteilung."$json$::jsonb),
  ('de', 'whatsNew.item.parallelTasks.title', $json$"Große Anfragen auf gleichzeitig arbeitende Agenten verteilt"$json$::jsonb),
  ('de', 'whatsNew.item.parallelTasks.detail', $json$"Schalte Große Anfragen auf Agenten verteilen unter Einstellungen › Jev › Routing ein. Bei einer komplexen Anfrage im Build-Modus in einem Git-Projekt teilt ein Reasoning-Modell die Arbeit in bis zu 4 Teile mit getrennten Dateien. Jeder Teil geht an einen anderen Agenten, in einer eigenen Kopie des Projekts (git worktree), alle gleichzeitig, und die Änderungen kommen in deinen Ordner zurück. Ein Teil, dessen Änderungen nicht mehr passen, wird als Patch gespeichert, den du mit git apply anwendest."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
