-- v0.76.1: o painel de andamento acompanha a etapa mais recente; botão para voltar ao fim.

insert into public.translations (locale, key, value) values
  ('en', 'progress.scrollDown', $json$"Go to the latest step"$json$::jsonb),
  ('en', 'whatsNew.item.progressAutoScroll.title', $json$"The progress panel follows the latest step"$json$::jsonb),
  ('en', 'whatsNew.item.progressAutoScroll.detail', $json$"The steps list beside the chat now scrolls to the end by itself whenever a new step arrives. If you scroll up to read an earlier step, it stays where you left it and shows a button to jump back to the latest step."$json$::jsonb),
  ('pt-BR', 'progress.scrollDown', $json$"Ir para a etapa mais recente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.progressAutoScroll.title', $json$"O painel de andamento acompanha a etapa mais recente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.progressAutoScroll.detail', $json$"A lista de etapas ao lado do chat agora rola sozinha até o fim sempre que chega uma etapa nova. Se você rolar para cima para ler uma etapa anterior, ela fica parada onde você deixou e mostra um botão para voltar à etapa mais recente."$json$::jsonb),
  ('es', 'progress.scrollDown', $json$"Ir al paso más reciente"$json$::jsonb),
  ('es', 'whatsNew.item.progressAutoScroll.title', $json$"El panel de progreso sigue el paso más reciente"$json$::jsonb),
  ('es', 'whatsNew.item.progressAutoScroll.detail', $json$"La lista de pasos junto al chat ahora se desplaza sola hasta el final cada vez que llega un paso nuevo. Si te desplazas hacia arriba para leer un paso anterior, se queda donde lo dejaste y muestra un botón para volver al paso más reciente."$json$::jsonb),
  ('fr', 'progress.scrollDown', $json$"Aller à la dernière étape"$json$::jsonb),
  ('fr', 'whatsNew.item.progressAutoScroll.title', $json$"Le panneau de progression suit la dernière étape"$json$::jsonb),
  ('fr', 'whatsNew.item.progressAutoScroll.detail', $json$"La liste des étapes à côté du chat défile désormais seule jusqu'à la fin à chaque nouvelle étape. Si vous remontez pour lire une étape précédente, elle reste où vous l'avez laissée et affiche un bouton pour revenir à la dernière étape."$json$::jsonb),
  ('de', 'progress.scrollDown', $json$"Zum neuesten Schritt"$json$::jsonb),
  ('de', 'whatsNew.item.progressAutoScroll.title', $json$"Das Fortschrittsfenster folgt dem neuesten Schritt"$json$::jsonb),
  ('de', 'whatsNew.item.progressAutoScroll.detail', $json$"Die Schrittliste neben dem Chat scrollt jetzt bei jedem neuen Schritt von selbst ans Ende. Wenn Sie nach oben scrollen, um einen früheren Schritt zu lesen, bleibt sie dort stehen und zeigt eine Schaltfläche, um zum neuesten Schritt zurückzuspringen."$json$::jsonb),
  ('ru', 'progress.scrollDown', $json$"К последнему шагу"$json$::jsonb),
  ('ru', 'whatsNew.item.progressAutoScroll.title', $json$"Панель хода работы следует за последним шагом"$json$::jsonb),
  ('ru', 'whatsNew.item.progressAutoScroll.detail', $json$"Список шагов рядом с чатом теперь сам прокручивается до конца при каждом новом шаге. Если вы прокрутите вверх, чтобы прочитать предыдущий шаг, список останется на месте и покажет кнопку возврата к последнему шагу."$json$::jsonb),
  ('zh-CN', 'progress.scrollDown', $json$"跳到最新步骤"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.progressAutoScroll.title', $json$"进度面板会跟随最新步骤"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.progressAutoScroll.detail', $json$"聊天旁的步骤列表现在每当出现新步骤时都会自动滚动到末尾。如果你向上滚动去看之前的步骤，它会停在原处，并显示一个按钮，可跳回最新步骤。"$json$::jsonb),
  ('ja', 'progress.scrollDown', $json$"最新のステップへ"$json$::jsonb),
  ('ja', 'whatsNew.item.progressAutoScroll.title', $json$"進行状況パネルが最新のステップに追従します"$json$::jsonb),
  ('ja', 'whatsNew.item.progressAutoScroll.detail', $json$"チャット横のステップ一覧は、新しいステップが届くたびに自動で末尾までスクロールします。前のステップを読むために上へスクロールすると、その位置にとどまり、最新のステップへ戻るボタンが表示されます。"$json$::jsonb),
  ('hi', 'progress.scrollDown', $json$"नवीनतम चरण पर जाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.progressAutoScroll.title', $json$"प्रगति पैनल नवीनतम चरण का अनुसरण करता है"$json$::jsonb),
  ('hi', 'whatsNew.item.progressAutoScroll.detail', $json$"चैट के बगल की चरणों की सूची अब हर नया चरण आने पर अपने आप अंत तक स्क्रॉल हो जाती है। यदि आप पिछला चरण पढ़ने के लिए ऊपर स्क्रॉल करते हैं, तो वह वहीं रुकी रहती है और नवीनतम चरण पर लौटने के लिए एक बटन दिखाती है।"$json$::jsonb),
  ('ar', 'progress.scrollDown', $json$"الانتقال إلى أحدث خطوة"$json$::jsonb),
  ('ar', 'whatsNew.item.progressAutoScroll.title', $json$"لوحة التقدّم تتابع أحدث خطوة"$json$::jsonb),
  ('ar', 'whatsNew.item.progressAutoScroll.detail', $json$"قائمة الخطوات بجوار المحادثة تنتقل الآن إلى النهاية تلقائيًا كلما وصلت خطوة جديدة. إذا مررتَ لأعلى لقراءة خطوة سابقة، تبقى القائمة حيث تركتها وتعرض زرًا للعودة إلى أحدث خطوة."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
