-- v0.60.0: os textos do app da onda 2 — parar o pedido e o teto de
-- minutos, os arquivos protegidos nas CLIs, o login dos agentes, os modos
-- novos do Claude e as novidades da versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'chat.cancelQueued', $json$"Tirar da fila"$json$::jsonb),
  ('pt-BR', 'chat.cancelQueued.title', $json$"Tira este pedido da fila antes de ele rodar"$json$::jsonb),
  ('pt-BR', 'pending.stop', $json$"Parar"$json$::jsonb),
  ('pt-BR', 'pending.stop.title', $json$"Para este pedido e fecha os agentes que ele abriu. O que já foi dito fica no chat."$json$::jsonb),
  ('pt-BR', 'pending.stopping', $json$"Parando…"$json$::jsonb),
  ('pt-BR', 'exit.kind.changed', $json$"alterado pelo agente"$json$::jsonb),
  ('pt-BR', 'claude.permission.manual', $json$"Perguntar antes de agir"$json$::jsonb),
  ('pt-BR', 'claude.permission.manual.hint', $json$"O modo padrão do Claude Code: o que precisa de aprovação é negado, porque ninguém aprova pelo chat. No modo desenvolvimento o JayV ainda deixa ele editar os arquivos do projeto."$json$::jsonb),
  ('pt-BR', 'claude.permission.dontAsk', $json$"Nunca perguntar"$json$::jsonb),
  ('pt-BR', 'claude.permission.dontAsk.hint', $json$"Nega na hora o que pediria aprovação; leituras e as ferramentas que você liberou continuam rodando. No modo desenvolvimento o JayV ainda deixa ele editar os arquivos do projeto."$json$::jsonb),
  ('pt-BR', 'claude.symbols.safeMode', $json$"O modo seguro não sobe servidor MCP, então as ferramentas de símbolos ficam desligadas"$json$::jsonb),
  ('pt-BR', 'turn.cancelled', $json$"Você parou este pedido antes de ele terminar. Reenvie para continuar."$json$::jsonb),
  ('pt-BR', 'turn.ceiling', $json$"Este pedido passou do limite de {minutes} minutos e foi parado. Aumente o limite em Configuração › Jev ou divida o pedido."$json$::jsonb),
  ('pt-BR', 'agent.loggedOut', $json$"Encontrado em {path}, mas sem login. Entre pelo terminal; até lá o JayV manda os pedidos aos outros agentes."$json$::jsonb),
  ('pt-BR', 'jev.ceiling', $json$"Tempo máximo do pedido"$json$::jsonb),
  ('pt-BR', 'jev.ceiling.hint', $json$"O pedido que passar disso para, e os agentes que ele abriu fecham junto."$json$::jsonb),
  ('pt-BR', 'app.deny.agents', $json$"O Claude Code também bloqueia as próprias leituras e edições destes arquivos. Codex, Copilot e Cursor não têm essa chave: o JayV deixa os arquivos fora do que manda a eles e segura qualquer mudança que o agente fizer neles."$json$::jsonb),
  ('pt-BR', 'core.turnCeiling', $json$"O tempo máximo do pedido vai de {min} a {max} minutos."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.requiredFeatures.title', $json$"Proteções que o seu plano mantém ligadas"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.requiredFeatures.detail', $json$"As portarias de entrada e de saída, a remoção de segredos, os arquivos protegidos, as sessões dos agentes, o cache de contexto e o roteamento adaptativo fazem parte de todo plano e não se desligam mais. O seu plano também pode travar ligado um recurso opcional, e o interruptor diz por que não muda."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.stopRequest.title', $json$"Pare um pedido"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.stopRequest.detail', $json$"O botão Parar encerra o pedido em andamento e fecha todos os processos que o agente abriu; o que ele já disse fica no chat. O pedido que espera na fila pode sair dela, e todo pedido para num tempo máximo que você define em Configuração › Jev (30 minutos por padrão)."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.protectedFiles.title', $json$"Arquivos protegidos continuam protegidos"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.protectedFiles.detail', $json$"O Claude Code não consegue mais ler nem editar os arquivos da sua lista de protegidos, e qualquer mudança que um agente fizer num deles fica segurada na portaria de saída, mesmo que a resposta não fale dele."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.backgroundReview.title', $json$"A segunda opinião chega depois da resposta"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.backgroundReview.detail', $json$"A revisão por outro agente agora roda depois que a resposta chega, só em pedidos médios e complexos, e entra no mesmo chat. O próximo pedido não espera mais por ela."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.fasterRequests.title', $json$"Os pedidos começam mais rápido"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.fasterRequests.detail', $json$"Os agentes não são mais remontados e procurados no disco antes de cada pedido, os projetos entre os quais você alterna guardam o índice e só os arquivos que mudaram são lidos de novo, e o chat que muda é relido sozinho em vez de todas as conversas."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentLogin.title', $json$"Agentes sem login ficam de fora"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentLogin.detail', $json$"Um agente sem login sai do roteamento em vez de falhar a cada pedido, e conferir um agente na Configuração mostra se ele está logado."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.offlineQueue.title', $json$"A fila anda mesmo sem o servidor"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.offlineQueue.detail', $json$"Com a sessão válida, os pedidos rodam mesmo quando o servidor do JayV não responde, com a portaria local. A sincronização espera enquanto um pedido roda, em vez de disputar com ele."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentFlags.title', $json$"Linhas de comando dos agentes que sempre funcionam"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.agentFlags.detail', $json$"O Claude Code ganha o modo Nunca perguntar e não espera mais uma aprovação que ninguém pode dar. O planejamento, a revisão e o nome dos chats não deixam mais sessões guardadas para trás, e a saída limpa do Copilot e o Codex fora do Git ficam sempre ligados."$json$::jsonb),
  ('en', 'chat.cancelQueued', $json$"Remove from queue"$json$::jsonb),
  ('en', 'chat.cancelQueued.title', $json$"Take this request out of the queue before it runs"$json$::jsonb),
  ('en', 'pending.stop', $json$"Stop"$json$::jsonb),
  ('en', 'pending.stop.title', $json$"Stop this request and close the agents it opened. What was already said stays in the chat."$json$::jsonb),
  ('en', 'pending.stopping', $json$"Stopping…"$json$::jsonb),
  ('en', 'exit.kind.changed', $json$"changed by the agent"$json$::jsonb),
  ('en', 'claude.permission.manual', $json$"Ask before acting"$json$::jsonb),
  ('en', 'claude.permission.manual.hint', $json$"Claude Code's standard mode: what needs approval is denied, since nobody approves from the chat. In Development mode JayV still lets it edit project files."$json$::jsonb),
  ('en', 'claude.permission.dontAsk', $json$"Never ask"$json$::jsonb),
  ('en', 'claude.permission.dontAsk.hint', $json$"Denies on the spot anything that would ask for approval; reads and the tools you allowed still run. In Development mode JayV still lets it edit project files."$json$::jsonb),
  ('en', 'claude.symbols.safeMode', $json$"Safe mode starts no MCP server, so the symbol tools stay off"$json$::jsonb),
  ('en', 'turn.cancelled', $json$"You stopped this request before it finished. Send it again to continue."$json$::jsonb),
  ('en', 'turn.ceiling', $json$"This request ran past its {minutes}-minute limit and was stopped. Raise the limit in Settings › Jev or split the request."$json$::jsonb),
  ('en', 'agent.loggedOut', $json$"Found at {path}, but not signed in. Sign in in the terminal; until then JayV routes requests to the other agents."$json$::jsonb),
  ('en', 'jev.ceiling', $json$"Request time limit"$json$::jsonb),
  ('en', 'jev.ceiling.hint', $json$"A request that runs longer than this stops, and the agents it opened close with it."$json$::jsonb),
  ('en', 'app.deny.agents', $json$"Claude Code also blocks its own reads and edits of these files. Codex, Copilot and Cursor have no such switch: JayV keeps the files out of what it sends them and holds any change the agent makes to them."$json$::jsonb),
  ('en', 'core.turnCeiling', $json$"The request time limit goes from {min} to {max} minutes."$json$::jsonb),
  ('en', 'whatsNew.item.requiredFeatures.title', $json$"Protections your plan keeps on"$json$::jsonb),
  ('en', 'whatsNew.item.requiredFeatures.detail', $json$"The entry and exit gates, secret redaction, protected files, agent sessions, the context cache and adaptive routing are part of every plan and no longer switch off. Your plan can also lock an optional feature on, and its switch shows why it cannot be changed."$json$::jsonb),
  ('en', 'whatsNew.item.stopRequest.title', $json$"Stop a request"$json$::jsonb),
  ('en', 'whatsNew.item.stopRequest.detail', $json$"A Stop button ends the running request and closes every process the agent opened; what it already said stays in the chat. A request waiting in the queue can be removed from it, and every request stops at a time limit you set in Settings › Jev (30 minutes by default)."$json$::jsonb),
  ('en', 'whatsNew.item.protectedFiles.title', $json$"Protected files stay protected"$json$::jsonb),
  ('en', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code can no longer read or edit the files in your protected list, and any change an agent makes to one of them is held at the exit gate, even when the answer does not mention it."$json$::jsonb),
  ('en', 'whatsNew.item.backgroundReview.title', $json$"The second opinion arrives after the answer"$json$::jsonb),
  ('en', 'whatsNew.item.backgroundReview.detail', $json$"The review by another agent now runs after the answer is in, only for medium and complex requests, and lands in the same chat. The next request no longer waits for it."$json$::jsonb),
  ('en', 'whatsNew.item.fasterRequests.title', $json$"Requests start faster"$json$::jsonb),
  ('en', 'whatsNew.item.fasterRequests.detail', $json$"Agents are no longer rebuilt and searched for on disk before every request, projects you switch between keep their index and only changed files are read again, and a chat that changes reloads alone instead of every conversation."$json$::jsonb),
  ('en', 'whatsNew.item.agentLogin.title', $json$"Signed-out agents are skipped"$json$::jsonb),
  ('en', 'whatsNew.item.agentLogin.detail', $json$"An agent that is not signed in leaves routing instead of failing each request, and checking an agent in Settings shows whether it is signed in."$json$::jsonb),
  ('en', 'whatsNew.item.offlineQueue.title', $json$"The queue keeps going without the server"$json$::jsonb),
  ('en', 'whatsNew.item.offlineQueue.detail', $json$"With a valid session, requests run even when the JayV server cannot be reached, using the local gate. Sync waits while a request is running instead of competing with it."$json$::jsonb),
  ('en', 'whatsNew.item.agentFlags.title', $json$"Agent command lines that always work"$json$::jsonb),
  ('en', 'whatsNew.item.agentFlags.detail', $json$"Claude Code gains the Never ask mode and no longer waits for an approval nobody can give. Planning, review and chat names no longer leave saved sessions behind, and Copilot's clean output and Codex outside Git are always on."$json$::jsonb),
  ('es', 'chat.cancelQueued', $json$"Quitar de la cola"$json$::jsonb),
  ('es', 'chat.cancelQueued.title', $json$"Quita esta solicitud de la cola antes de que se ejecute"$json$::jsonb),
  ('es', 'pending.stop', $json$"Detener"$json$::jsonb),
  ('es', 'pending.stop.title', $json$"Detiene esta solicitud y cierra los agentes que abrió. Lo que ya se dijo queda en el chat."$json$::jsonb),
  ('es', 'pending.stopping', $json$"Deteniendo…"$json$::jsonb),
  ('es', 'exit.kind.changed', $json$"modificado por el agente"$json$::jsonb),
  ('es', 'claude.permission.manual', $json$"Preguntar antes de actuar"$json$::jsonb),
  ('es', 'claude.permission.manual.hint', $json$"El modo estándar de Claude Code: lo que necesita aprobación se rechaza, porque nadie aprueba desde el chat. En el modo desarrollo, JayV igual le permite editar los archivos del proyecto."$json$::jsonb),
  ('es', 'claude.permission.dontAsk', $json$"Nunca preguntar"$json$::jsonb),
  ('es', 'claude.permission.dontAsk.hint', $json$"Rechaza al instante lo que pediría aprobación; las lecturas y las herramientas que permitiste siguen funcionando. En el modo desarrollo, JayV igual le permite editar los archivos del proyecto."$json$::jsonb),
  ('es', 'claude.symbols.safeMode', $json$"El modo seguro no inicia ningún servidor MCP, así que las herramientas de símbolos quedan desactivadas"$json$::jsonb),
  ('es', 'turn.cancelled', $json$"Detuviste esta solicitud antes de que terminara. Vuelve a enviarla para continuar."$json$::jsonb),
  ('es', 'turn.ceiling', $json$"Esta solicitud superó su límite de {minutes} minutos y se detuvo. Aumenta el límite en Configuración › Jev o divide la solicitud."$json$::jsonb),
  ('es', 'agent.loggedOut', $json$"Encontrado en {path}, pero sin sesión iniciada. Inicia sesión en la terminal; hasta entonces JayV envía las solicitudes a los demás agentes."$json$::jsonb),
  ('es', 'jev.ceiling', $json$"Tiempo máximo de la solicitud"$json$::jsonb),
  ('es', 'jev.ceiling.hint', $json$"La solicitud que dure más que esto se detiene, y los agentes que abrió se cierran con ella."$json$::jsonb),
  ('es', 'app.deny.agents', $json$"Claude Code también bloquea sus propias lecturas y ediciones de estos archivos. Codex, Copilot y Cursor no tienen ese interruptor: JayV deja los archivos fuera de lo que les envía y retiene cualquier cambio que el agente haga en ellos."$json$::jsonb),
  ('es', 'core.turnCeiling', $json$"El tiempo máximo de la solicitud va de {min} a {max} minutos."$json$::jsonb),
  ('es', 'whatsNew.item.requiredFeatures.title', $json$"Protecciones que tu plan mantiene activas"$json$::jsonb),
  ('es', 'whatsNew.item.requiredFeatures.detail', $json$"Las porterías de entrada y salida, la ocultación de secretos, los archivos protegidos, las sesiones de los agentes, la caché de contexto y el enrutamiento adaptativo forman parte de todo plan y ya no se desactivan. Tu plan también puede fijar activada una función opcional, y su interruptor explica por qué no cambia."$json$::jsonb),
  ('es', 'whatsNew.item.stopRequest.title', $json$"Detén una solicitud"$json$::jsonb),
  ('es', 'whatsNew.item.stopRequest.detail', $json$"El botón Detener termina la solicitud en curso y cierra todos los procesos que abrió el agente; lo que ya dijo queda en el chat. Una solicitud que espera en la cola puede quitarse de ella, y toda solicitud se detiene en un tiempo máximo que defines en Configuración › Jev (30 minutos por defecto)."$json$::jsonb),
  ('es', 'whatsNew.item.protectedFiles.title', $json$"Los archivos protegidos siguen protegidos"$json$::jsonb),
  ('es', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code ya no puede leer ni editar los archivos de tu lista de protegidos, y cualquier cambio que un agente haga en uno de ellos queda retenido en la portería de salida, aunque la respuesta no lo mencione."$json$::jsonb),
  ('es', 'whatsNew.item.backgroundReview.title', $json$"La segunda opinión llega después de la respuesta"$json$::jsonb),
  ('es', 'whatsNew.item.backgroundReview.detail', $json$"La revisión de otro agente ahora se ejecuta después de que llega la respuesta, solo en solicitudes medianas y complejas, y aparece en el mismo chat. La siguiente solicitud ya no la espera."$json$::jsonb),
  ('es', 'whatsNew.item.fasterRequests.title', $json$"Las solicitudes empiezan más rápido"$json$::jsonb),
  ('es', 'whatsNew.item.fasterRequests.detail', $json$"Los agentes ya no se reconstruyen ni se buscan en el disco antes de cada solicitud, los proyectos entre los que alternas conservan su índice y solo se vuelven a leer los archivos que cambiaron, y el chat que cambia se recarga solo en lugar de todas las conversaciones."$json$::jsonb),
  ('es', 'whatsNew.item.agentLogin.title', $json$"Los agentes sin sesión se omiten"$json$::jsonb),
  ('es', 'whatsNew.item.agentLogin.detail', $json$"Un agente sin sesión iniciada sale del enrutamiento en lugar de fallar en cada solicitud, y revisar un agente en Configuración muestra si tiene la sesión iniciada."$json$::jsonb),
  ('es', 'whatsNew.item.offlineQueue.title', $json$"La cola avanza aun sin el servidor"$json$::jsonb),
  ('es', 'whatsNew.item.offlineQueue.detail', $json$"Con una sesión válida, las solicitudes se ejecutan aunque el servidor de JayV no responda, usando la portería local. La sincronización espera mientras una solicitud se ejecuta, en lugar de competir con ella."$json$::jsonb),
  ('es', 'whatsNew.item.agentFlags.title', $json$"Líneas de comando de los agentes que siempre funcionan"$json$::jsonb),
  ('es', 'whatsNew.item.agentFlags.detail', $json$"Claude Code incorpora el modo Nunca preguntar y ya no espera una aprobación que nadie puede dar. La planificación, la revisión y los nombres de los chats ya no dejan sesiones guardadas, y la salida limpia de Copilot y Codex fuera de Git quedan siempre activados."$json$::jsonb),
  ('zh-CN', 'chat.cancelQueued', $json$"移出队列"$json$::jsonb),
  ('zh-CN', 'chat.cancelQueued.title', $json$"在运行之前将此请求移出队列"$json$::jsonb),
  ('zh-CN', 'pending.stop', $json$"停止"$json$::jsonb),
  ('zh-CN', 'pending.stop.title', $json$"停止此请求并关闭它打开的代理。已经说过的内容会保留在聊天中。"$json$::jsonb),
  ('zh-CN', 'pending.stopping', $json$"正在停止…"$json$::jsonb),
  ('zh-CN', 'exit.kind.changed', $json$"被代理修改"$json$::jsonb),
  ('zh-CN', 'claude.permission.manual', $json$"操作前询问"$json$::jsonb),
  ('zh-CN', 'claude.permission.manual.hint', $json$"Claude Code 的标准模式：需要批准的操作会被拒绝，因为没有人能在聊天中批准。在开发模式下，JayV 仍允许它编辑项目文件。"$json$::jsonb),
  ('zh-CN', 'claude.permission.dontAsk', $json$"从不询问"$json$::jsonb),
  ('zh-CN', 'claude.permission.dontAsk.hint', $json$"立即拒绝任何需要批准的操作；读取和你允许的工具仍可运行。在开发模式下，JayV 仍允许它编辑项目文件。"$json$::jsonb),
  ('zh-CN', 'claude.symbols.safeMode', $json$"安全模式不会启动任何 MCP 服务器，因此符号工具保持关闭"$json$::jsonb),
  ('zh-CN', 'turn.cancelled', $json$"你在此请求完成前停止了它。重新发送即可继续。"$json$::jsonb),
  ('zh-CN', 'turn.ceiling', $json$"此请求超过了 {minutes} 分钟的限制，已被停止。请在“设置 › Jev”中提高限制，或拆分请求。"$json$::jsonb),
  ('zh-CN', 'agent.loggedOut', $json$"已在 {path} 找到，但未登录。请在终端中登录；在此之前，JayV 会把请求交给其他代理。"$json$::jsonb),
  ('zh-CN', 'jev.ceiling', $json$"请求时间上限"$json$::jsonb),
  ('zh-CN', 'jev.ceiling.hint', $json$"运行超过此时长的请求会停止，它打开的代理也会一并关闭。"$json$::jsonb),
  ('zh-CN', 'app.deny.agents', $json$"Claude Code 也会阻止自身读取和编辑这些文件。Codex、Copilot 和 Cursor 没有这样的开关：JayV 会把这些文件排除在发送给它们的内容之外，并拦下代理对它们所做的任何更改。"$json$::jsonb),
  ('zh-CN', 'core.turnCeiling', $json$"请求时间上限为 {min} 到 {max} 分钟。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.requiredFeatures.title', $json$"套餐始终开启的保护功能"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.requiredFeatures.detail', $json$"入口和出口门卫、密钥脱敏、受保护文件、代理会话、上下文缓存和自适应路由已包含在每个套餐中，不能再关闭。你的套餐还可以将某个可选功能锁定为开启，其开关会说明为何无法更改。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.stopRequest.title', $json$"停止请求"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.stopRequest.detail', $json$"“停止”按钮会结束正在运行的请求，并关闭代理打开的所有进程；它已经说过的内容会保留在聊天中。排队中的请求可以移出队列，所有请求都会在你于“设置 › Jev”中设定的时间上限停止（默认 30 分钟）。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.protectedFiles.title', $json$"受保护文件始终受保护"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code 不再能读取或编辑你保护列表中的文件；代理对其中任何文件所做的更改都会被出口门卫拦下，即使回答中没有提到它。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.backgroundReview.title', $json$"第二意见在回答之后送达"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.backgroundReview.detail', $json$"另一个代理的审查现在会在回答到达后运行，仅针对中等和复杂的请求，并出现在同一个聊天中。下一个请求不再需要等待它。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.fasterRequests.title', $json$"请求启动更快"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.fasterRequests.detail', $json$"不再在每个请求之前重建代理并在磁盘上查找它们；你来回切换的项目会保留索引，只重新读取已更改的文件；发生变化的聊天会单独重新加载，而不是所有对话。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentLogin.title', $json$"跳过未登录的代理"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentLogin.detail', $json$"未登录的代理会退出路由，而不是让每个请求都失败；在设置中检查代理时会显示它是否已登录。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.offlineQueue.title', $json$"没有服务器时队列也会继续"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.offlineQueue.detail', $json$"只要会话有效，即使无法连接 JayV 服务器，请求也会使用本地门卫运行。请求运行期间，同步会等待，而不是与它争抢资源。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentFlags.title', $json$"始终可用的代理命令行"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.agentFlags.detail', $json$"Claude Code 新增“从不询问”模式，不再等待无人能给出的批准。规划、审查和聊天命名不再留下已保存的会话，Copilot 的简洁输出和 Codex 在 Git 之外运行始终开启。"$json$::jsonb),
  ('hi', 'chat.cancelQueued', $json$"कतार से हटाएँ"$json$::jsonb),
  ('hi', 'chat.cancelQueued.title', $json$"इस अनुरोध को चलने से पहले कतार से हटा दें"$json$::jsonb),
  ('hi', 'pending.stop', $json$"रोकें"$json$::jsonb),
  ('hi', 'pending.stop.title', $json$"इस अनुरोध को रोकता है और इसके खोले गए एजेंटों को बंद करता है। जो पहले कहा जा चुका है वह चैट में रहता है।"$json$::jsonb),
  ('hi', 'pending.stopping', $json$"रोका जा रहा है…"$json$::jsonb),
  ('hi', 'exit.kind.changed', $json$"एजेंट द्वारा बदला गया"$json$::jsonb),
  ('hi', 'claude.permission.manual', $json$"कार्य करने से पहले पूछें"$json$::jsonb),
  ('hi', 'claude.permission.manual.hint', $json$"Claude Code का मानक मोड: जिसे मंज़ूरी चाहिए उसे अस्वीकार कर दिया जाता है, क्योंकि चैट से कोई मंज़ूरी नहीं देता। डेवलपमेंट मोड में JayV फिर भी उसे प्रोजेक्ट फ़ाइलें बदलने देता है।"$json$::jsonb),
  ('hi', 'claude.permission.dontAsk', $json$"कभी न पूछें"$json$::jsonb),
  ('hi', 'claude.permission.dontAsk.hint', $json$"जिसके लिए मंज़ूरी माँगी जाती, उसे तुरंत अस्वीकार करता है; पढ़ना और आपके अनुमति दिए गए टूल चलते रहते हैं। डेवलपमेंट मोड में JayV फिर भी उसे प्रोजेक्ट फ़ाइलें बदलने देता है।"$json$::jsonb),
  ('hi', 'claude.symbols.safeMode', $json$"सेफ़ मोड कोई MCP सर्वर शुरू नहीं करता, इसलिए सिंबल टूल बंद रहते हैं"$json$::jsonb),
  ('hi', 'turn.cancelled', $json$"आपने यह अनुरोध पूरा होने से पहले रोक दिया। जारी रखने के लिए इसे फिर से भेजें।"$json$::jsonb),
  ('hi', 'turn.ceiling', $json$"यह अनुरोध {minutes} मिनट की सीमा से आगे चला गया और रोक दिया गया। सेटिंग्स › Jev में सीमा बढ़ाएँ या अनुरोध को बाँट दें।"$json$::jsonb),
  ('hi', 'agent.loggedOut', $json$"{path} पर मिला, लेकिन साइन इन नहीं है। टर्मिनल में साइन इन करें; तब तक JayV अनुरोध दूसरे एजेंटों को भेजता है।"$json$::jsonb),
  ('hi', 'jev.ceiling', $json$"अनुरोध की समय सीमा"$json$::jsonb),
  ('hi', 'jev.ceiling.hint', $json$"इससे ज़्यादा चलने वाला अनुरोध रुक जाता है, और उसके खोले गए एजेंट भी साथ में बंद हो जाते हैं।"$json$::jsonb),
  ('hi', 'app.deny.agents', $json$"Claude Code भी इन फ़ाइलों को खुद पढ़ने और बदलने से रोकता है। Codex, Copilot और Cursor में ऐसा स्विच नहीं है: JayV इन फ़ाइलों को उन्हें भेजी जाने वाली सामग्री से बाहर रखता है और एजेंट द्वारा इनमें किया गया कोई भी बदलाव रोक लेता है।"$json$::jsonb),
  ('hi', 'core.turnCeiling', $json$"अनुरोध की समय सीमा {min} से {max} मिनट तक होती है।"$json$::jsonb),
  ('hi', 'whatsNew.item.requiredFeatures.title', $json$"सुरक्षाएँ जो आपका प्लान चालू रखता है"$json$::jsonb),
  ('hi', 'whatsNew.item.requiredFeatures.detail', $json$"प्रवेश और निकास गेट, गोपनीय जानकारी छिपाना, सुरक्षित फ़ाइलें, एजेंट सत्र, संदर्भ कैश और अनुकूली रूटिंग हर प्लान का हिस्सा हैं और अब बंद नहीं होते। आपका प्लान किसी वैकल्पिक सुविधा को भी चालू लॉक कर सकता है, और उसका स्विच बताता है कि वह क्यों नहीं बदलता।"$json$::jsonb),
  ('hi', 'whatsNew.item.stopRequest.title', $json$"अनुरोध रोकें"$json$::jsonb),
  ('hi', 'whatsNew.item.stopRequest.detail', $json$"रोकें बटन चल रहे अनुरोध को समाप्त करता है और एजेंट द्वारा खोली गई हर प्रक्रिया बंद करता है; जो वह पहले कह चुका है वह चैट में रहता है। कतार में इंतज़ार कर रहा अनुरोध उससे हटाया जा सकता है, और हर अनुरोध उस समय सीमा पर रुकता है जो आप सेटिंग्स › Jev में तय करते हैं (डिफ़ॉल्ट 30 मिनट)।"$json$::jsonb),
  ('hi', 'whatsNew.item.protectedFiles.title', $json$"सुरक्षित फ़ाइलें सुरक्षित ही रहती हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code अब आपकी सुरक्षित सूची की फ़ाइलें न पढ़ सकता है न बदल सकता है, और किसी एजेंट द्वारा उनमें से किसी में किया गया कोई भी बदलाव निकास गेट पर रोक लिया जाता है, भले ही जवाब में उसका ज़िक्र न हो।"$json$::jsonb),
  ('hi', 'whatsNew.item.backgroundReview.title', $json$"दूसरी राय जवाब के बाद आती है"$json$::jsonb),
  ('hi', 'whatsNew.item.backgroundReview.detail', $json$"दूसरे एजेंट की समीक्षा अब जवाब आने के बाद चलती है, केवल मध्यम और जटिल अनुरोधों के लिए, और उसी चैट में आती है। अगला अनुरोध अब उसका इंतज़ार नहीं करता।"$json$::jsonb),
  ('hi', 'whatsNew.item.fasterRequests.title', $json$"अनुरोध तेज़ी से शुरू होते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.fasterRequests.detail', $json$"अब हर अनुरोध से पहले एजेंटों को दोबारा बनाया और डिस्क पर खोजा नहीं जाता, जिन प्रोजेक्टों के बीच आप बदलते हैं उनका इंडेक्स बना रहता है और केवल बदली हुई फ़ाइलें दोबारा पढ़ी जाती हैं, और बदली हुई चैट अकेले फिर से लोड होती है, सारी बातचीत नहीं।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentLogin.title', $json$"साइन आउट एजेंट छोड़ दिए जाते हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.agentLogin.detail', $json$"जो एजेंट साइन इन नहीं है वह हर अनुरोध पर विफल होने के बजाय रूटिंग से बाहर हो जाता है, और सेटिंग्स में एजेंट जाँचने पर दिखता है कि वह साइन इन है या नहीं।"$json$::jsonb),
  ('hi', 'whatsNew.item.offlineQueue.title', $json$"सर्वर के बिना भी कतार चलती रहती है"$json$::jsonb),
  ('hi', 'whatsNew.item.offlineQueue.detail', $json$"वैध सत्र होने पर, JayV सर्वर तक न पहुँच पाने पर भी अनुरोध स्थानीय गेट के साथ चलते हैं। जब कोई अनुरोध चल रहा होता है तो सिंक उससे होड़ करने के बजाय इंतज़ार करता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.agentFlags.title', $json$"एजेंट कमांड लाइनें जो हमेशा काम करती हैं"$json$::jsonb),
  ('hi', 'whatsNew.item.agentFlags.detail', $json$"Claude Code में कभी न पूछें मोड जुड़ गया है और अब वह ऐसी मंज़ूरी का इंतज़ार नहीं करता जो कोई नहीं दे सकता। योजना, समीक्षा और चैट के नाम अब सहेजे गए सत्र पीछे नहीं छोड़ते, और Copilot का साफ़ आउटपुट तथा Git के बाहर Codex हमेशा चालू रहते हैं।"$json$::jsonb),
  ('ar', 'chat.cancelQueued', $json$"إزالة من قائمة الانتظار"$json$::jsonb),
  ('ar', 'chat.cancelQueued.title', $json$"أزل هذا الطلب من قائمة الانتظار قبل تشغيله"$json$::jsonb),
  ('ar', 'pending.stop', $json$"إيقاف"$json$::jsonb),
  ('ar', 'pending.stop.title', $json$"يوقف هذا الطلب ويغلق الوكلاء الذين فتحهم. ما قيل بالفعل يبقى في المحادثة."$json$::jsonb),
  ('ar', 'pending.stopping', $json$"جارٍ الإيقاف…"$json$::jsonb),
  ('ar', 'exit.kind.changed', $json$"عدّله الوكيل"$json$::jsonb),
  ('ar', 'claude.permission.manual', $json$"السؤال قبل التنفيذ"$json$::jsonb),
  ('ar', 'claude.permission.manual.hint', $json$"الوضع القياسي في Claude Code: يُرفض ما يحتاج إلى موافقة، لأن لا أحد يوافق من المحادثة. في وضع التطوير يسمح له JayV مع ذلك بتعديل ملفات المشروع."$json$::jsonb),
  ('ar', 'claude.permission.dontAsk', $json$"عدم السؤال أبدًا"$json$::jsonb),
  ('ar', 'claude.permission.dontAsk.hint', $json$"يرفض فورًا كل ما قد يطلب موافقة؛ وتستمر القراءة والأدوات التي سمحت بها في العمل. في وضع التطوير يسمح له JayV مع ذلك بتعديل ملفات المشروع."$json$::jsonb),
  ('ar', 'claude.symbols.safeMode', $json$"الوضع الآمن لا يشغّل أي خادم MCP، لذا تبقى أدوات الرموز معطّلة"$json$::jsonb),
  ('ar', 'turn.cancelled', $json$"أوقفت هذا الطلب قبل أن ينتهي. أعد إرساله للمتابعة."$json$::jsonb),
  ('ar', 'turn.ceiling', $json$"تجاوز هذا الطلب حدّه البالغ {minutes} دقيقة وتم إيقافه. ارفع الحد في الإعدادات › Jev أو قسّم الطلب."$json$::jsonb),
  ('ar', 'agent.loggedOut', $json$"عُثر عليه في {path}، لكنه غير مسجّل الدخول. سجّل الدخول من الطرفية؛ وحتى ذلك الحين يوجّه JayV الطلبات إلى الوكلاء الآخرين."$json$::jsonb),
  ('ar', 'jev.ceiling', $json$"الحد الزمني للطلب"$json$::jsonb),
  ('ar', 'jev.ceiling.hint', $json$"الطلب الذي يستمر أطول من ذلك يتوقف، ويُغلق معه الوكلاء الذين فتحهم."$json$::jsonb),
  ('ar', 'app.deny.agents', $json$"يمنع Claude Code أيضًا قراءته وتعديله لهذه الملفات. أما Codex وCopilot وCursor فلا يملكون هذا الخيار: يُبقي JayV الملفات خارج ما يرسله إليهم ويحتجز أي تغيير يجريه الوكيل عليها."$json$::jsonb),
  ('ar', 'core.turnCeiling', $json$"يتراوح الحد الزمني للطلب بين {min} و{max} دقيقة."$json$::jsonb),
  ('ar', 'whatsNew.item.requiredFeatures.title', $json$"حمايات يُبقيها اشتراكك مفعّلة"$json$::jsonb),
  ('ar', 'whatsNew.item.requiredFeatures.detail', $json$"بوابتا الدخول والخروج وحجب الأسرار والملفات المحمية وجلسات الوكلاء وذاكرة السياق والتوجيه التكيّفي جزء من كل اشتراك ولم تعد تُعطَّل. ويمكن لاشتراكك أيضًا قفل ميزة اختيارية على وضع التشغيل، ويوضح مفتاحها سبب عدم تغيّره."$json$::jsonb),
  ('ar', 'whatsNew.item.stopRequest.title', $json$"أوقف طلبًا"$json$::jsonb),
  ('ar', 'whatsNew.item.stopRequest.detail', $json$"ينهي زر الإيقاف الطلب الجاري ويغلق كل العمليات التي فتحها الوكيل؛ ويبقى ما قاله بالفعل في المحادثة. ويمكن إزالة الطلب المنتظر من قائمة الانتظار، ويتوقف كل طلب عند حد زمني تحدده في الإعدادات › Jev (30 دقيقة افتراضيًا)."$json$::jsonb),
  ('ar', 'whatsNew.item.protectedFiles.title', $json$"الملفات المحمية تبقى محمية"$json$::jsonb),
  ('ar', 'whatsNew.item.protectedFiles.detail', $json$"لم يعد Claude Code قادرًا على قراءة ملفات قائمتك المحمية أو تعديلها، وأي تغيير يجريه وكيل على أحدها يُحتجز عند بوابة الخروج، حتى لو لم يذكره الرد."$json$::jsonb),
  ('ar', 'whatsNew.item.backgroundReview.title', $json$"الرأي الثاني يصل بعد الرد"$json$::jsonb),
  ('ar', 'whatsNew.item.backgroundReview.detail', $json$"أصبحت مراجعة وكيل آخر تعمل بعد وصول الرد، للطلبات المتوسطة والمعقدة فقط، وتظهر في المحادثة نفسها. ولم يعد الطلب التالي ينتظرها."$json$::jsonb),
  ('ar', 'whatsNew.item.fasterRequests.title', $json$"الطلبات تبدأ أسرع"$json$::jsonb),
  ('ar', 'whatsNew.item.fasterRequests.detail', $json$"لم يعد الوكلاء يُعاد بناؤهم ويُبحث عنهم على القرص قبل كل طلب، والمشاريع التي تتنقل بينها تحتفظ بفهرسها ولا يُعاد إلا قراءة الملفات التي تغيّرت، والمحادثة التي تتغيّر يُعاد تحميلها وحدها بدلًا من كل المحادثات."$json$::jsonb),
  ('ar', 'whatsNew.item.agentLogin.title', $json$"تخطي الوكلاء غير المسجّلين"$json$::jsonb),
  ('ar', 'whatsNew.item.agentLogin.detail', $json$"الوكيل غير المسجّل الدخول يخرج من التوجيه بدلًا من أن يفشل في كل طلب، وفحص الوكيل في الإعدادات يوضح ما إذا كان مسجّل الدخول."$json$::jsonb),
  ('ar', 'whatsNew.item.offlineQueue.title', $json$"قائمة الانتظار تستمر دون الخادم"$json$::jsonb),
  ('ar', 'whatsNew.item.offlineQueue.detail', $json$"مع جلسة صالحة، تعمل الطلبات حتى عندما يتعذر الوصول إلى خادم JayV، باستخدام البوابة المحلية. وتنتظر المزامنة أثناء تشغيل طلب بدلًا من منافسته."$json$::jsonb),
  ('ar', 'whatsNew.item.agentFlags.title', $json$"أسطر أوامر للوكلاء تعمل دائمًا"$json$::jsonb),
  ('ar', 'whatsNew.item.agentFlags.detail', $json$"يكتسب Claude Code وضع «عدم السؤال أبدًا» ولم يعد ينتظر موافقة لا يستطيع أحد منحها. ولم يعد التخطيط والمراجعة وتسمية المحادثات تترك جلسات محفوظة، ويبقى الإخراج النظيف في Copilot وتشغيل Codex خارج Git مفعّلين دائمًا."$json$::jsonb),
  ('fr', 'chat.cancelQueued', $json$"Retirer de la file"$json$::jsonb),
  ('fr', 'chat.cancelQueued.title', $json$"Retire cette demande de la file avant qu'elle ne s'exécute"$json$::jsonb),
  ('fr', 'pending.stop', $json$"Arrêter"$json$::jsonb),
  ('fr', 'pending.stop.title', $json$"Arrête cette demande et ferme les agents qu'elle a ouverts. Ce qui a déjà été dit reste dans la conversation."$json$::jsonb),
  ('fr', 'pending.stopping', $json$"Arrêt en cours…"$json$::jsonb),
  ('fr', 'exit.kind.changed', $json$"modifié par l'agent"$json$::jsonb),
  ('fr', 'claude.permission.manual', $json$"Demander avant d'agir"$json$::jsonb),
  ('fr', 'claude.permission.manual.hint', $json$"Le mode standard de Claude Code : ce qui demande une approbation est refusé, car personne n'approuve depuis la conversation. En mode développement, JayV le laisse quand même modifier les fichiers du projet."$json$::jsonb),
  ('fr', 'claude.permission.dontAsk', $json$"Ne jamais demander"$json$::jsonb),
  ('fr', 'claude.permission.dontAsk.hint', $json$"Refuse sur-le-champ tout ce qui demanderait une approbation ; les lectures et les outils que vous avez autorisés continuent de fonctionner. En mode développement, JayV le laisse quand même modifier les fichiers du projet."$json$::jsonb),
  ('fr', 'claude.symbols.safeMode', $json$"Le mode sécurisé ne démarre aucun serveur MCP : les outils de symboles restent désactivés"$json$::jsonb),
  ('fr', 'turn.cancelled', $json$"Vous avez arrêté cette demande avant la fin. Renvoyez-la pour continuer."$json$::jsonb),
  ('fr', 'turn.ceiling', $json$"Cette demande a dépassé sa limite de {minutes} minutes et a été arrêtée. Augmentez la limite dans Paramètres › Jev ou découpez la demande."$json$::jsonb),
  ('fr', 'agent.loggedOut', $json$"Trouvé dans {path}, mais non connecté. Connectez-vous dans le terminal ; d'ici là, JayV envoie les demandes aux autres agents."$json$::jsonb),
  ('fr', 'jev.ceiling', $json$"Durée maximale d'une demande"$json$::jsonb),
  ('fr', 'jev.ceiling.hint', $json$"Une demande qui dure plus longtemps s'arrête, et les agents qu'elle a ouverts se ferment avec elle."$json$::jsonb),
  ('fr', 'app.deny.agents', $json$"Claude Code bloque aussi ses propres lectures et modifications de ces fichiers. Codex, Copilot et Cursor n'ont pas ce réglage : JayV garde les fichiers hors de ce qu'il leur envoie et retient toute modification qu'un agent y apporte."$json$::jsonb),
  ('fr', 'core.turnCeiling', $json$"La durée maximale d'une demande va de {min} à {max} minutes."$json$::jsonb),
  ('fr', 'whatsNew.item.requiredFeatures.title', $json$"Des protections que votre forfait garde actives"$json$::jsonb),
  ('fr', 'whatsNew.item.requiredFeatures.detail', $json$"Les contrôles d'entrée et de sortie, le masquage des secrets, les fichiers protégés, les sessions des agents, le cache de contexte et le routage adaptatif font partie de chaque forfait et ne se désactivent plus. Votre forfait peut aussi verrouiller une fonctionnalité optionnelle sur activé, et son interrupteur indique pourquoi il ne change pas."$json$::jsonb),
  ('fr', 'whatsNew.item.stopRequest.title', $json$"Arrêter une demande"$json$::jsonb),
  ('fr', 'whatsNew.item.stopRequest.detail', $json$"Le bouton Arrêter met fin à la demande en cours et ferme tous les processus ouverts par l'agent ; ce qu'il a déjà dit reste dans la conversation. Une demande en attente peut être retirée de la file, et chaque demande s'arrête à une durée maximale que vous réglez dans Paramètres › Jev (30 minutes par défaut)."$json$::jsonb),
  ('fr', 'whatsNew.item.protectedFiles.title', $json$"Les fichiers protégés restent protégés"$json$::jsonb),
  ('fr', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code ne peut plus lire ni modifier les fichiers de votre liste protégée, et toute modification qu'un agent apporte à l'un d'eux est retenue au contrôle de sortie, même si la réponse n'en parle pas."$json$::jsonb),
  ('fr', 'whatsNew.item.backgroundReview.title', $json$"Le second avis arrive après la réponse"$json$::jsonb),
  ('fr', 'whatsNew.item.backgroundReview.detail', $json$"La revue par un autre agent s'exécute désormais après l'arrivée de la réponse, seulement pour les demandes moyennes et complexes, et s'affiche dans la même conversation. La demande suivante ne l'attend plus."$json$::jsonb),
  ('fr', 'whatsNew.item.fasterRequests.title', $json$"Les demandes démarrent plus vite"$json$::jsonb),
  ('fr', 'whatsNew.item.fasterRequests.detail', $json$"Les agents ne sont plus reconstruits ni recherchés sur le disque avant chaque demande, les projets entre lesquels vous passez gardent leur index et seuls les fichiers modifiés sont relus, et une conversation qui change est rechargée seule au lieu de toutes."$json$::jsonb),
  ('fr', 'whatsNew.item.agentLogin.title', $json$"Les agents non connectés sont ignorés"$json$::jsonb),
  ('fr', 'whatsNew.item.agentLogin.detail', $json$"Un agent non connecté sort du routage au lieu d'échouer à chaque demande, et vérifier un agent dans Paramètres indique s'il est connecté."$json$::jsonb),
  ('fr', 'whatsNew.item.offlineQueue.title', $json$"La file avance même sans le serveur"$json$::jsonb),
  ('fr', 'whatsNew.item.offlineQueue.detail', $json$"Avec une session valide, les demandes s'exécutent même quand le serveur JayV est injoignable, avec le contrôle local. La synchronisation attend pendant qu'une demande s'exécute au lieu de lui faire concurrence."$json$::jsonb),
  ('fr', 'whatsNew.item.agentFlags.title', $json$"Des lignes de commande d'agents qui fonctionnent toujours"$json$::jsonb),
  ('fr', 'whatsNew.item.agentFlags.detail', $json$"Claude Code gagne le mode Ne jamais demander et n'attend plus une approbation que personne ne peut donner. La planification, la revue et le nommage des conversations ne laissent plus de sessions enregistrées, et la sortie épurée de Copilot et Codex hors de Git sont toujours activés."$json$::jsonb),
  ('ru', 'chat.cancelQueued', $json$"Убрать из очереди"$json$::jsonb),
  ('ru', 'chat.cancelQueued.title', $json$"Убрать этот запрос из очереди до его запуска"$json$::jsonb),
  ('ru', 'pending.stop', $json$"Остановить"$json$::jsonb),
  ('ru', 'pending.stop.title', $json$"Останавливает этот запрос и закрывает открытых им агентов. Уже сказанное остаётся в чате."$json$::jsonb),
  ('ru', 'pending.stopping', $json$"Остановка…"$json$::jsonb),
  ('ru', 'exit.kind.changed', $json$"изменён агентом"$json$::jsonb),
  ('ru', 'claude.permission.manual', $json$"Спрашивать перед действием"$json$::jsonb),
  ('ru', 'claude.permission.manual.hint', $json$"Стандартный режим Claude Code: всё, что требует одобрения, отклоняется, потому что из чата никто не одобряет. В режиме разработки JayV всё равно разрешает ему править файлы проекта."$json$::jsonb),
  ('ru', 'claude.permission.dontAsk', $json$"Никогда не спрашивать"$json$::jsonb),
  ('ru', 'claude.permission.dontAsk.hint', $json$"Сразу отклоняет всё, что потребовало бы одобрения; чтение и разрешённые вами инструменты продолжают работать. В режиме разработки JayV всё равно разрешает ему править файлы проекта."$json$::jsonb),
  ('ru', 'claude.symbols.safeMode', $json$"Безопасный режим не запускает MCP-серверы, поэтому инструменты символов остаются выключенными"$json$::jsonb),
  ('ru', 'turn.cancelled', $json$"Вы остановили этот запрос до его завершения. Отправьте его снова, чтобы продолжить."$json$::jsonb),
  ('ru', 'turn.ceiling', $json$"Этот запрос превысил лимит в {minutes} мин. и был остановлен. Увеличьте лимит в «Настройки › Jev» или разделите запрос."$json$::jsonb),
  ('ru', 'agent.loggedOut', $json$"Найден в {path}, но вход не выполнен. Войдите в терминале; до тех пор JayV отправляет запросы другим агентам."$json$::jsonb),
  ('ru', 'jev.ceiling', $json$"Лимит времени запроса"$json$::jsonb),
  ('ru', 'jev.ceiling.hint', $json$"Запрос, который длится дольше, останавливается, и открытые им агенты закрываются вместе с ним."$json$::jsonb),
  ('ru', 'app.deny.agents', $json$"Claude Code также блокирует собственное чтение и изменение этих файлов. У Codex, Copilot и Cursor такого переключателя нет: JayV не включает эти файлы в то, что им отправляет, и задерживает любое изменение, которое агент в них вносит."$json$::jsonb),
  ('ru', 'core.turnCeiling', $json$"Лимит времени запроса — от {min} до {max} минут."$json$::jsonb),
  ('ru', 'whatsNew.item.requiredFeatures.title', $json$"Защиты, которые ваш тариф держит включёнными"$json$::jsonb),
  ('ru', 'whatsNew.item.requiredFeatures.detail', $json$"Входная и выходная проверки, скрытие секретов, защищённые файлы, сессии агентов, кэш контекста и адаптивная маршрутизация входят в каждый тариф и больше не отключаются. Тариф также может закрепить включённой необязательную функцию, а её переключатель объясняет, почему её нельзя изменить."$json$::jsonb),
  ('ru', 'whatsNew.item.stopRequest.title', $json$"Остановка запроса"$json$::jsonb),
  ('ru', 'whatsNew.item.stopRequest.detail', $json$"Кнопка «Остановить» завершает текущий запрос и закрывает все процессы, открытые агентом; уже сказанное остаётся в чате. Запрос в очереди можно из неё убрать, а каждый запрос останавливается по лимиту времени, который задаётся в «Настройки › Jev» (по умолчанию 30 минут)."$json$::jsonb),
  ('ru', 'whatsNew.item.protectedFiles.title', $json$"Защищённые файлы остаются защищёнными"$json$::jsonb),
  ('ru', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code больше не может читать и изменять файлы из вашего списка защищённых, а любое изменение, которое агент вносит в один из них, задерживается на выходной проверке, даже если ответ о нём не упоминает."$json$::jsonb),
  ('ru', 'whatsNew.item.backgroundReview.title', $json$"Второе мнение приходит после ответа"$json$::jsonb),
  ('ru', 'whatsNew.item.backgroundReview.detail', $json$"Проверка другим агентом теперь запускается после получения ответа, только для средних и сложных запросов, и появляется в том же чате. Следующий запрос её больше не ждёт."$json$::jsonb),
  ('ru', 'whatsNew.item.fasterRequests.title', $json$"Запросы стартуют быстрее"$json$::jsonb),
  ('ru', 'whatsNew.item.fasterRequests.detail', $json$"Агенты больше не пересобираются и не ищутся на диске перед каждым запросом, проекты, между которыми вы переключаетесь, сохраняют индекс, и заново читаются только изменённые файлы, а изменившийся чат перезагружается отдельно, а не все разговоры."$json$::jsonb),
  ('ru', 'whatsNew.item.agentLogin.title', $json$"Агенты без входа пропускаются"$json$::jsonb),
  ('ru', 'whatsNew.item.agentLogin.detail', $json$"Агент без входа исключается из маршрутизации, а не проваливает каждый запрос, а проверка агента в настройках показывает, выполнен ли вход."$json$::jsonb),
  ('ru', 'whatsNew.item.offlineQueue.title', $json$"Очередь работает и без сервера"$json$::jsonb),
  ('ru', 'whatsNew.item.offlineQueue.detail', $json$"При действующей сессии запросы выполняются даже без связи с сервером JayV, с локальной проверкой. Синхронизация ждёт, пока выполняется запрос, вместо того чтобы конкурировать с ним."$json$::jsonb),
  ('ru', 'whatsNew.item.agentFlags.title', $json$"Командные строки агентов, которые всегда работают"$json$::jsonb),
  ('ru', 'whatsNew.item.agentFlags.detail', $json$"В Claude Code появился режим «Никогда не спрашивать», и он больше не ждёт одобрения, которое некому дать. Планирование, проверка и названия чатов больше не оставляют сохранённых сессий, а чистый вывод Copilot и работа Codex вне Git всегда включены."$json$::jsonb),
  ('ja', 'chat.cancelQueued', $json$"キューから外す"$json$::jsonb),
  ('ja', 'chat.cancelQueued.title', $json$"実行される前にこのリクエストをキューから外します"$json$::jsonb),
  ('ja', 'pending.stop', $json$"停止"$json$::jsonb),
  ('ja', 'pending.stop.title', $json$"このリクエストを止め、開いたエージェントを閉じます。すでに出力された内容はチャットに残ります。"$json$::jsonb),
  ('ja', 'pending.stopping', $json$"停止中…"$json$::jsonb),
  ('ja', 'exit.kind.changed', $json$"エージェントが変更"$json$::jsonb),
  ('ja', 'claude.permission.manual', $json$"実行前に確認"$json$::jsonb),
  ('ja', 'claude.permission.manual.hint', $json$"Claude Code の標準モード: 承認が必要な操作は拒否されます。チャットからは誰も承認できないためです。開発モードでは、JayV はそれでもプロジェクトのファイル編集を許可します。"$json$::jsonb),
  ('ja', 'claude.permission.dontAsk', $json$"確認しない"$json$::jsonb),
  ('ja', 'claude.permission.dontAsk.hint', $json$"承認を求めるはずの操作はその場で拒否します。読み取りと許可したツールは引き続き動きます。開発モードでは、JayV はそれでもプロジェクトのファイル編集を許可します。"$json$::jsonb),
  ('ja', 'claude.symbols.safeMode', $json$"セーフモードでは MCP サーバーを起動しないため、シンボルツールはオフのままです"$json$::jsonb),
  ('ja', 'turn.cancelled', $json$"このリクエストは完了前に停止されました。続けるには再送信してください。"$json$::jsonb),
  ('ja', 'turn.ceiling', $json$"このリクエストは {minutes} 分の上限を超えたため停止しました。設定 › Jev で上限を上げるか、リクエストを分けてください。"$json$::jsonb),
  ('ja', 'agent.loggedOut', $json$"{path} で見つかりましたが、サインインしていません。ターミナルでサインインしてください。それまで JayV はリクエストを他のエージェントに回します。"$json$::jsonb),
  ('ja', 'jev.ceiling', $json$"リクエストの制限時間"$json$::jsonb),
  ('ja', 'jev.ceiling.hint', $json$"これより長く続くリクエストは停止し、開いたエージェントも一緒に閉じます。"$json$::jsonb),
  ('ja', 'app.deny.agents', $json$"Claude Code はこれらのファイルの読み取りと編集も自ら禁止します。Codex、Copilot、Cursor にはこの設定がないため、JayV はこれらのファイルを送信内容から外し、エージェントが加えた変更を保留します。"$json$::jsonb),
  ('ja', 'core.turnCeiling', $json$"リクエストの制限時間は {min}〜{max} 分です。"$json$::jsonb),
  ('ja', 'whatsNew.item.requiredFeatures.title', $json$"プランが常にオンにする保護機能"$json$::jsonb),
  ('ja', 'whatsNew.item.requiredFeatures.detail', $json$"入口・出口ゲート、シークレットの伏せ字化、保護ファイル、エージェントのセッション、コンテキストキャッシュ、適応ルーティングはすべてのプランに含まれ、オフにできなくなりました。プランでオプション機能をオンに固定することもでき、そのスイッチには変更できない理由が表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.stopRequest.title', $json$"リクエストを停止"$json$::jsonb),
  ('ja', 'whatsNew.item.stopRequest.detail', $json$"停止ボタンで実行中のリクエストを終了し、エージェントが開いたすべてのプロセスを閉じます。すでに出力された内容はチャットに残ります。キューで待っているリクエストは外すことができ、すべてのリクエストは設定 › Jev で決めた制限時間 (既定 30 分) で停止します。"$json$::jsonb),
  ('ja', 'whatsNew.item.protectedFiles.title', $json$"保護ファイルは保護されたまま"$json$::jsonb),
  ('ja', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code は保護リストのファイルを読み取ったり編集したりできなくなりました。エージェントがそのいずれかに加えた変更は、回答で触れていなくても出口ゲートで保留されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.backgroundReview.title', $json$"セカンドオピニオンは回答の後に届きます"$json$::jsonb),
  ('ja', 'whatsNew.item.backgroundReview.detail', $json$"別のエージェントによるレビューは、回答が届いた後に中規模・複雑なリクエストでのみ実行され、同じチャットに追加されます。次のリクエストはもう待ちません。"$json$::jsonb),
  ('ja', 'whatsNew.item.fasterRequests.title', $json$"リクエストの開始が速くなりました"$json$::jsonb),
  ('ja', 'whatsNew.item.fasterRequests.detail', $json$"リクエストごとにエージェントを再構築したりディスク上で探したりしなくなりました。切り替えて使うプロジェクトはインデックスを保持し、変更されたファイルだけを読み直します。変更があったチャットは、すべての会話ではなくそのチャットだけを再読み込みします。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentLogin.title', $json$"サインインしていないエージェントはスキップ"$json$::jsonb),
  ('ja', 'whatsNew.item.agentLogin.detail', $json$"サインインしていないエージェントは、リクエストのたびに失敗するのではなくルーティングから外れます。設定でエージェントを確認すると、サインイン状態が表示されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.offlineQueue.title', $json$"サーバーがなくてもキューが進みます"$json$::jsonb),
  ('ja', 'whatsNew.item.offlineQueue.detail', $json$"セッションが有効なら、JayV サーバーに接続できなくてもローカルゲートでリクエストが実行されます。リクエストの実行中は、同期は競合せずに待機します。"$json$::jsonb),
  ('ja', 'whatsNew.item.agentFlags.title', $json$"常に動作するエージェントのコマンドライン"$json$::jsonb),
  ('ja', 'whatsNew.item.agentFlags.detail', $json$"Claude Code に「確認しない」モードが加わり、誰も出せない承認を待たなくなりました。計画、レビュー、チャット名の生成は保存済みセッションを残さなくなり、Copilot のクリーンな出力と Git 外での Codex 実行は常にオンになります。"$json$::jsonb),
  ('de', 'chat.cancelQueued', $json$"Aus der Warteschlange nehmen"$json$::jsonb),
  ('de', 'chat.cancelQueued.title', $json$"Nimmt diese Anfrage aus der Warteschlange, bevor sie läuft"$json$::jsonb),
  ('de', 'pending.stop', $json$"Stoppen"$json$::jsonb),
  ('de', 'pending.stop.title', $json$"Stoppt diese Anfrage und schließt die Agenten, die sie geöffnet hat. Was schon gesagt wurde, bleibt im Chat."$json$::jsonb),
  ('de', 'pending.stopping', $json$"Wird gestoppt…"$json$::jsonb),
  ('de', 'exit.kind.changed', $json$"vom Agenten geändert"$json$::jsonb),
  ('de', 'claude.permission.manual', $json$"Vor dem Handeln fragen"$json$::jsonb),
  ('de', 'claude.permission.manual.hint', $json$"Der Standardmodus von Claude Code: Was eine Freigabe braucht, wird abgelehnt, da niemand im Chat freigibt. Im Entwicklungsmodus lässt JayV es trotzdem Projektdateien bearbeiten."$json$::jsonb),
  ('de', 'claude.permission.dontAsk', $json$"Nie fragen"$json$::jsonb),
  ('de', 'claude.permission.dontAsk.hint', $json$"Lehnt sofort ab, was eine Freigabe bräuchte; Lesezugriffe und die von dir erlaubten Werkzeuge laufen weiter. Im Entwicklungsmodus lässt JayV es trotzdem Projektdateien bearbeiten."$json$::jsonb),
  ('de', 'claude.symbols.safeMode', $json$"Der abgesicherte Modus startet keinen MCP-Server, daher bleiben die Symbolwerkzeuge aus"$json$::jsonb),
  ('de', 'turn.cancelled', $json$"Du hast diese Anfrage gestoppt, bevor sie fertig war. Sende sie erneut, um fortzufahren."$json$::jsonb),
  ('de', 'turn.ceiling', $json$"Diese Anfrage hat ihr Limit von {minutes} Minuten überschritten und wurde gestoppt. Erhöhe das Limit unter Einstellungen › Jev oder teile die Anfrage auf."$json$::jsonb),
  ('de', 'agent.loggedOut', $json$"Gefunden unter {path}, aber nicht angemeldet. Melde dich im Terminal an; bis dahin leitet JayV Anfragen an die anderen Agenten."$json$::jsonb),
  ('de', 'jev.ceiling', $json$"Zeitlimit pro Anfrage"$json$::jsonb),
  ('de', 'jev.ceiling.hint', $json$"Eine Anfrage, die länger läuft, wird gestoppt, und die Agenten, die sie geöffnet hat, werden mit ihr geschlossen."$json$::jsonb),
  ('de', 'app.deny.agents', $json$"Claude Code sperrt außerdem eigene Lese- und Schreibzugriffe auf diese Dateien. Codex, Copilot und Cursor haben diesen Schalter nicht: JayV hält die Dateien aus dem heraus, was es ihnen schickt, und hält jede Änderung zurück, die ein Agent daran vornimmt."$json$::jsonb),
  ('de', 'core.turnCeiling', $json$"Das Zeitlimit pro Anfrage liegt zwischen {min} und {max} Minuten."$json$::jsonb),
  ('de', 'whatsNew.item.requiredFeatures.title', $json$"Schutzfunktionen, die dein Tarif eingeschaltet lässt"$json$::jsonb),
  ('de', 'whatsNew.item.requiredFeatures.detail', $json$"Ein- und Ausgangspforte, das Schwärzen von Geheimnissen, geschützte Dateien, Agentensitzungen, der Kontext-Cache und adaptives Routing gehören zu jedem Tarif und lassen sich nicht mehr abschalten. Dein Tarif kann außerdem eine optionale Funktion fest einschalten, und ihr Schalter erklärt, warum er sich nicht ändern lässt."$json$::jsonb),
  ('de', 'whatsNew.item.stopRequest.title', $json$"Eine Anfrage stoppen"$json$::jsonb),
  ('de', 'whatsNew.item.stopRequest.detail', $json$"Die Stopp-Schaltfläche beendet die laufende Anfrage und schließt alle Prozesse, die der Agent geöffnet hat; was er schon gesagt hat, bleibt im Chat. Eine wartende Anfrage lässt sich aus der Warteschlange nehmen, und jede Anfrage stoppt an einem Zeitlimit, das du unter Einstellungen › Jev festlegst (standardmäßig 30 Minuten)."$json$::jsonb),
  ('de', 'whatsNew.item.protectedFiles.title', $json$"Geschützte Dateien bleiben geschützt"$json$::jsonb),
  ('de', 'whatsNew.item.protectedFiles.detail', $json$"Claude Code kann die Dateien deiner Schutzliste nicht mehr lesen oder bearbeiten, und jede Änderung, die ein Agent an einer davon vornimmt, wird an der Ausgangspforte zurückgehalten, auch wenn die Antwort sie nicht erwähnt."$json$::jsonb),
  ('de', 'whatsNew.item.backgroundReview.title', $json$"Die Zweitmeinung kommt nach der Antwort"$json$::jsonb),
  ('de', 'whatsNew.item.backgroundReview.detail', $json$"Die Prüfung durch einen anderen Agenten läuft jetzt, nachdem die Antwort da ist, nur bei mittleren und komplexen Anfragen, und erscheint im selben Chat. Die nächste Anfrage wartet nicht mehr darauf."$json$::jsonb),
  ('de', 'whatsNew.item.fasterRequests.title', $json$"Anfragen starten schneller"$json$::jsonb),
  ('de', 'whatsNew.item.fasterRequests.detail', $json$"Agenten werden nicht mehr vor jeder Anfrage neu aufgebaut und auf der Festplatte gesucht, Projekte, zwischen denen du wechselst, behalten ihren Index und nur geänderte Dateien werden neu gelesen, und ein geänderter Chat wird allein neu geladen statt aller Unterhaltungen."$json$::jsonb),
  ('de', 'whatsNew.item.agentLogin.title', $json$"Abgemeldete Agenten werden übersprungen"$json$::jsonb),
  ('de', 'whatsNew.item.agentLogin.detail', $json$"Ein nicht angemeldeter Agent fällt aus dem Routing, statt bei jeder Anfrage zu scheitern, und die Prüfung eines Agenten in den Einstellungen zeigt, ob er angemeldet ist."$json$::jsonb),
  ('de', 'whatsNew.item.offlineQueue.title', $json$"Die Warteschlange läuft auch ohne Server weiter"$json$::jsonb),
  ('de', 'whatsNew.item.offlineQueue.detail', $json$"Mit gültiger Sitzung laufen Anfragen auch dann, wenn der JayV-Server nicht erreichbar ist, mit der lokalen Pforte. Die Synchronisierung wartet, während eine Anfrage läuft, statt mit ihr zu konkurrieren."$json$::jsonb),
  ('de', 'whatsNew.item.agentFlags.title', $json$"Agenten-Befehlszeilen, die immer funktionieren"$json$::jsonb),
  ('de', 'whatsNew.item.agentFlags.detail', $json$"Claude Code erhält den Modus Nie fragen und wartet nicht mehr auf eine Freigabe, die niemand geben kann. Planung, Prüfung und Chat-Namen hinterlassen keine gespeicherten Sitzungen mehr, und die saubere Ausgabe von Copilot sowie Codex außerhalb von Git sind immer aktiv."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
