-- Site v1.0.0: o site do JayV (repositório JayV-Coder/site) passou a ser
-- Next.js e lê as traduções desta tabela, como o app. As chaves dele começam
-- por `site.`; as que ele divide com o app (`auth.*`, `admin.*`, `feature.*`
-- e outras) já estão aqui e não mudam.
--
-- O site lê só os grupos de chave que usa (filtro por prefixo), então o app
-- não precisa de nada novo: as chaves `site.*` chegam ao cache dele e ficam
-- sem uso. Os nomes de pacote (AppImage, Debian / Ubuntu, Fedora / RHEL) e a
-- arquitetura x86_64 não se traduzem: valem os do inglês embutido.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'site.meta.title', $json$"JayV — Agentes de IA, sob controle"$json$::jsonb),
  ('pt-BR', 'site.meta.description', $json$"Baixe o JayV para Windows, macOS ou Linux. Coordene Codex, Claude Code, GitHub Copilot e Cursor Agent com contexto, controle e rastreabilidade."$json$::jsonb),
  ('pt-BR', 'site.skip', $json$"Pular para o conteúdo"$json$::jsonb),
  ('pt-BR', 'site.nav.label', $json$"Navegação principal"$json$::jsonb),
  ('pt-BR', 'site.nav.home', $json$"JayV, início"$json$::jsonb),
  ('pt-BR', 'site.nav.features', $json$"Recursos"$json$::jsonb),
  ('pt-BR', 'site.nav.downloads', $json$"Downloads"$json$::jsonb),
  ('pt-BR', 'site.nav.how', $json$"Como funciona"$json$::jsonb),
  ('pt-BR', 'site.nav.releases', $json$"Versões"$json$::jsonb),
  ('pt-BR', 'site.nav.signIn', $json$"Entrar"$json$::jsonb),
  ('pt-BR', 'site.nav.signUp', $json$"Criar conta"$json$::jsonb),
  ('pt-BR', 'site.nav.account', $json$"Conectado como {email}"$json$::jsonb),
  ('pt-BR', 'site.hero.eyebrow', $json$"Orquestração local para desenvolvimento"$json$::jsonb),
  ('pt-BR', 'site.hero.title', $json$"Agentes de IA,"$json$::jsonb),
  ('pt-BR', 'site.hero.highlight', $json$"sob controle."$json$::jsonb),
  ('pt-BR', 'site.hero.copy', $json$"O JayV coordena Codex, Claude Code, GitHub Copilot e Cursor Agent no contexto de cada projeto. O Jev entende o pedido, escolhe a rota e verifica a resposta para manter o trabalho focado e rastreável."$json$::jsonb),
  ('pt-BR', 'site.hero.download', $json$"Baixar para o meu sistema"$json$::jsonb),
  ('pt-BR', 'site.hero.downloadFor', $json$"Baixar para {system}"$json$::jsonb),
  ('pt-BR', 'site.hero.notes', $json$"Notas da versão"$json$::jsonb),
  ('pt-BR', 'site.hero.release', $json$"Versão {version} · Windows, macOS e Linux"$json$::jsonb),
  ('pt-BR', 'site.hero.releaseUnknown', $json$"Windows, macOS e Linux"$json$::jsonb),
  ('pt-BR', 'site.hero.agents', $json$"Agentes integrados"$json$::jsonb),
  ('pt-BR', 'site.trace.label', $json$"Exemplo de uma rota analisada pelo JayV"$json$::jsonb),
  ('pt-BR', 'site.trace.request', $json$"revise o fluxo de autenticação"$json$::jsonb),
  ('pt-BR', 'site.trace.indexing', $json$"indexando o contexto do projeto…"$json$::jsonb),
  ('pt-BR', 'site.trace.entry', $json$"entrada avaliada"$json$::jsonb),
  ('pt-BR', 'site.trace.scope', $json$"escopo: alteração média"$json$::jsonb),
  ('pt-BR', 'site.trace.agent', $json$"agente"$json$::jsonb),
  ('pt-BR', 'site.trace.model', $json$"modelo"$json$::jsonb),
  ('pt-BR', 'site.trace.mode', $json$"modo"$json$::jsonb),
  ('pt-BR', 'site.trace.role', $json$"papel"$json$::jsonb),
  ('pt-BR', 'site.trace.modeValue', $json$"planejamento"$json$::jsonb),
  ('pt-BR', 'site.trace.roleValue', $json$"revisor"$json$::jsonb),
  ('pt-BR', 'site.trace.exit', $json$"saída verificada"$json$::jsonb),
  ('pt-BR', 'site.trace.saved', $json$"turno salvo · contexto preservado"$json$::jsonb),
  ('pt-BR', 'site.features.kicker', $json$"O que o JayV entrega"$json$::jsonb),
  ('pt-BR', 'site.features.title', $json$"Um espaço para coordenar todo o trabalho."$json$::jsonb),
  ('pt-BR', 'site.features.note', $json$"Projetos, conversas, rotas e consumo ficam reunidos numa interface nativa, com o detalhe técnico disponível quando você precisa dele."$json$::jsonb),
  ('pt-BR', 'site.features.agents.tag', $json$"agentes"$json$::jsonb),
  ('pt-BR', 'site.features.agents.title', $json$"Quatro agentes, uma interface"$json$::jsonb),
  ('pt-BR', 'site.features.agents.detail', $json$"Configure modelos, permissões, ferramentas, sandbox e esforço de cada agente sem editar comandos à mão."$json$::jsonb),
  ('pt-BR', 'site.features.routing.tag', $json$"roteamento"$json$::jsonb),
  ('pt-BR', 'site.features.routing.title', $json$"A rota acompanha o pedido"$json$::jsonb),
  ('pt-BR', 'site.features.routing.detail', $json$"Intenção, porte e nível do desenvolvedor ajudam o Jev a escolher agente, modelo, modo de execução e papel."$json$::jsonb),
  ('pt-BR', 'site.features.trace.tag', $json$"rastreabilidade"$json$::jsonb),
  ('pt-BR', 'site.features.trace.title', $json$"Cada turno tem história"$json$::jsonb),
  ('pt-BR', 'site.features.trace.detail', $json$"O pedido é salvo antes da execução. Códigos de turno ligam as mensagens aos vereditos das portarias de entrada e saída."$json$::jsonb),
  ('pt-BR', 'site.features.account.tag', $json$"conta"$json$::jsonb),
  ('pt-BR', 'site.features.account.title', $json$"Perfil, atividade e limites"$json$::jsonb),
  ('pt-BR', 'site.features.account.detail', $json$"Acompanhe seu nível, a atividade dos últimos 30 dias e o uso informado por cada agente em um só lugar."$json$::jsonb),
  ('pt-BR', 'site.downloads.kicker', $json$"Downloads oficiais"$json$::jsonb),
  ('pt-BR', 'site.downloads.title', $json$"Escolha seu sistema"$json$::jsonb),
  ('pt-BR', 'site.downloads.note', $json$"Os links apontam para os arquivos publicados no repositório oficial. O JayV avisa quando uma versão nova estiver disponível."$json$::jsonb),
  ('pt-BR', 'site.downloads.recommended', $json$"Seu sistema"$json$::jsonb),
  ('pt-BR', 'site.downloads.windows.arch', $json$"64 bits · Windows 10 ou superior"$json$::jsonb),
  ('pt-BR', 'site.downloads.mac.arch', $json$"Apple Silicon ou Intel"$json$::jsonb),
  ('pt-BR', 'site.downloads.exe', $json$"Instalador EXE"$json$::jsonb),
  ('pt-BR', 'site.downloads.msi', $json$"Pacote MSI"$json$::jsonb),
  ('pt-BR', 'site.downloads.dmgArm', $json$"DMG Apple Silicon"$json$::jsonb),
  ('pt-BR', 'site.downloads.dmgIntel', $json$"DMG Intel"$json$::jsonb),
  ('pt-BR', 'site.downloads.missing', $json$"Pacote ainda indisponível."$json$::jsonb),
  ('pt-BR', 'site.downloads.meta', $json$"JayV v{version} · publicado em {date}"$json$::jsonb),
  ('pt-BR', 'site.downloads.metaUnknown', $json$"Versão mais recente no GitHub"$json$::jsonb),
  ('pt-BR', 'site.how.kicker', $json$"Fluxo com contexto"$json$::jsonb),
  ('pt-BR', 'site.how.title', $json$"Do contexto à resposta, cada etapa tem uma função."$json$::jsonb),
  ('pt-BR', 'site.how.detail', $json$"O JayV aponta o índice para a pasta do projeto, preserva a conversa e registra como cada turno foi conduzido."$json$::jsonb),
  ('pt-BR', 'site.how.step1.title', $json$"Abre o contexto certo"$json$::jsonb),
  ('pt-BR', 'site.how.step1.detail', $json$"Arquivos, índice e histórico ficam isolados por projeto e por conversa."$json$::jsonb),
  ('pt-BR', 'site.how.step2.title', $json$"Registra e avalia"$json$::jsonb),
  ('pt-BR', 'site.how.step2.detail', $json$"O turno é salvo antes da execução, e a portaria de entrada avalia o pedido."$json$::jsonb),
  ('pt-BR', 'site.how.step3.title', $json$"Escolhe a rota"$json$::jsonb),
  ('pt-BR', 'site.how.step3.detail', $json$"O trabalho segue para o agente, modelo, modo e papel adequados ao escopo."$json$::jsonb),
  ('pt-BR', 'site.how.step4.title', $json$"Verifica a saída"$json$::jsonb),
  ('pt-BR', 'site.how.step4.detail', $json$"A resposta volta pela portaria de saída, com a decisão e o histórico à vista."$json$::jsonb),
  ('pt-BR', 'site.privacy.title', $json$"O contexto permanece no projeto certo."$json$::jsonb),
  ('pt-BR', 'site.privacy.detail', $json$"Projetos, conversas e configurações persistem localmente; as chaves de provedores são mascaradas depois de salvas."$json$::jsonb),
  ('pt-BR', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('pt-BR', 'site.register.title', $json$"Crie sua conta no JayV"$json$::jsonb),
  ('pt-BR', 'site.register.subtitle', $json$"A mesma conta entra no app em qualquer máquina e neste site."$json$::jsonb),
  ('pt-BR', 'site.callback.working', $json$"Terminando de entrar…"$json$::jsonb),
  ('pt-BR', 'site.callback.failed', $json$"Este link não funcionou. Peça um novo ou entre de novo."$json$::jsonb),
  ('pt-BR', 'site.session.failed', $json$"Não deu para abrir sua sessão no site. Tente de novo."$json$::jsonb),
  ('pt-BR', 'site.admin.signIn', $json$"Entre com a conta de administrador do sistema para abrir esta página."$json$::jsonb),
  ('pt-BR', 'site.notFound.title', $json$"Página não encontrada"$json$::jsonb),
  ('pt-BR', 'site.notFound.detail', $json$"Este endereço não existe no site do JayV."$json$::jsonb),
  ('pt-BR', 'site.notFound.home', $json$"Voltar ao início"$json$::jsonb),
  ('en', 'site.meta.title', $json$"JayV — AI agents, under control"$json$::jsonb),
  ('en', 'site.meta.description', $json$"Download JayV for Windows, macOS or Linux. Coordinate Codex, Claude Code, GitHub Copilot and Cursor Agent with context, control and traceability."$json$::jsonb),
  ('en', 'site.skip', $json$"Skip to content"$json$::jsonb),
  ('en', 'site.nav.label', $json$"Main navigation"$json$::jsonb),
  ('en', 'site.nav.home', $json$"JayV, home"$json$::jsonb),
  ('en', 'site.nav.features', $json$"Features"$json$::jsonb),
  ('en', 'site.nav.downloads', $json$"Downloads"$json$::jsonb),
  ('en', 'site.nav.how', $json$"How it works"$json$::jsonb),
  ('en', 'site.nav.releases', $json$"Releases"$json$::jsonb),
  ('en', 'site.nav.signIn', $json$"Sign in"$json$::jsonb),
  ('en', 'site.nav.signUp', $json$"Create account"$json$::jsonb),
  ('en', 'site.nav.account', $json$"Signed in as {email}"$json$::jsonb),
  ('en', 'site.hero.eyebrow', $json$"Local orchestration for development"$json$::jsonb),
  ('en', 'site.hero.title', $json$"AI agents,"$json$::jsonb),
  ('en', 'site.hero.highlight', $json$"under control."$json$::jsonb),
  ('en', 'site.hero.copy', $json$"JayV coordinates Codex, Claude Code, GitHub Copilot and Cursor Agent in the context of each project. Jev understands the request, picks the route and checks the answer to keep the work focused and traceable."$json$::jsonb),
  ('en', 'site.hero.download', $json$"Download for my system"$json$::jsonb),
  ('en', 'site.hero.downloadFor', $json$"Download for {system}"$json$::jsonb),
  ('en', 'site.hero.notes', $json$"Release notes"$json$::jsonb),
  ('en', 'site.hero.release', $json$"Version {version} · Windows, macOS and Linux"$json$::jsonb),
  ('en', 'site.hero.releaseUnknown', $json$"Windows, macOS and Linux"$json$::jsonb),
  ('en', 'site.hero.agents', $json$"Integrated agents"$json$::jsonb),
  ('en', 'site.trace.label', $json$"Example of a route analyzed by JayV"$json$::jsonb),
  ('en', 'site.trace.request', $json$"review the authentication flow"$json$::jsonb),
  ('en', 'site.trace.indexing', $json$"indexing project context…"$json$::jsonb),
  ('en', 'site.trace.entry', $json$"input checked"$json$::jsonb),
  ('en', 'site.trace.scope', $json$"scope: medium change"$json$::jsonb),
  ('en', 'site.trace.agent', $json$"agent"$json$::jsonb),
  ('en', 'site.trace.model', $json$"model"$json$::jsonb),
  ('en', 'site.trace.mode', $json$"mode"$json$::jsonb),
  ('en', 'site.trace.role', $json$"role"$json$::jsonb),
  ('en', 'site.trace.modeValue', $json$"plan"$json$::jsonb),
  ('en', 'site.trace.roleValue', $json$"reviewer"$json$::jsonb),
  ('en', 'site.trace.exit', $json$"output verified"$json$::jsonb),
  ('en', 'site.trace.saved', $json$"turn saved · context kept"$json$::jsonb),
  ('en', 'site.features.kicker', $json$"What JayV delivers"$json$::jsonb),
  ('en', 'site.features.title', $json$"One place to coordinate all the work."$json$::jsonb),
  ('en', 'site.features.note', $json$"Projects, chats, routes and usage live together in a native interface, with the technical detail there when you need it."$json$::jsonb),
  ('en', 'site.features.agents.tag', $json$"agents"$json$::jsonb),
  ('en', 'site.features.agents.title', $json$"Four agents, one interface"$json$::jsonb),
  ('en', 'site.features.agents.detail', $json$"Set up models, permissions, tools, sandbox and effort for each agent without editing commands by hand."$json$::jsonb),
  ('en', 'site.features.routing.tag', $json$"routing"$json$::jsonb),
  ('en', 'site.features.routing.title', $json$"The route follows the request"$json$::jsonb),
  ('en', 'site.features.routing.detail', $json$"Intent, size and the developer's level help Jev pick the agent, model, execution mode and role."$json$::jsonb),
  ('en', 'site.features.trace.tag', $json$"traceability"$json$::jsonb),
  ('en', 'site.features.trace.title', $json$"Every turn has a history"$json$::jsonb),
  ('en', 'site.features.trace.detail', $json$"The request is saved before it runs. Turn codes link the messages to the verdicts of the entry and exit gates."$json$::jsonb),
  ('en', 'site.features.account.tag', $json$"account"$json$::jsonb),
  ('en', 'site.features.account.title', $json$"Profile, activity and limits"$json$::jsonb),
  ('en', 'site.features.account.detail', $json$"Follow your level, the last 30 days of activity and the usage each agent reports, in one place."$json$::jsonb),
  ('en', 'site.downloads.kicker', $json$"Official downloads"$json$::jsonb),
  ('en', 'site.downloads.title', $json$"Choose your system"$json$::jsonb),
  ('en', 'site.downloads.note', $json$"The links point to the files published in the official repository. JayV tells you when a new version is out."$json$::jsonb),
  ('en', 'site.downloads.recommended', $json$"Your system"$json$::jsonb),
  ('en', 'site.downloads.windows.arch', $json$"64-bit · Windows 10 or later"$json$::jsonb),
  ('en', 'site.downloads.mac.arch', $json$"Apple Silicon or Intel"$json$::jsonb),
  ('en', 'site.downloads.linux.arch', $json$"x86_64"$json$::jsonb),
  ('en', 'site.downloads.exe', $json$"EXE installer"$json$::jsonb),
  ('en', 'site.downloads.msi', $json$"MSI package"$json$::jsonb),
  ('en', 'site.downloads.dmgArm', $json$"Apple Silicon DMG"$json$::jsonb),
  ('en', 'site.downloads.dmgIntel', $json$"Intel DMG"$json$::jsonb),
  ('en', 'site.downloads.appImage', $json$"AppImage"$json$::jsonb),
  ('en', 'site.downloads.deb', $json$"Debian / Ubuntu"$json$::jsonb),
  ('en', 'site.downloads.rpm', $json$"Fedora / RHEL"$json$::jsonb),
  ('en', 'site.downloads.missing', $json$"Package not available yet."$json$::jsonb),
  ('en', 'site.downloads.meta', $json$"JayV v{version} · published {date}"$json$::jsonb),
  ('en', 'site.downloads.metaUnknown', $json$"Latest version on GitHub"$json$::jsonb),
  ('en', 'site.how.kicker', $json$"Flow with context"$json$::jsonb),
  ('en', 'site.how.title', $json$"From context to answer, each step has a job."$json$::jsonb),
  ('en', 'site.how.detail', $json$"JayV points the index at the project folder, keeps the conversation and records how each turn was handled."$json$::jsonb),
  ('en', 'site.how.step1.title', $json$"Opens the right context"$json$::jsonb),
  ('en', 'site.how.step1.detail', $json$"Files, index and history are isolated per project and per chat."$json$::jsonb),
  ('en', 'site.how.step2.title', $json$"Records and checks"$json$::jsonb),
  ('en', 'site.how.step2.detail', $json$"The turn is saved before it runs, and the entry gate checks the request."$json$::jsonb),
  ('en', 'site.how.step3.title', $json$"Picks the route"$json$::jsonb),
  ('en', 'site.how.step3.detail', $json$"The work goes to the agent, model, mode and role that fit the scope."$json$::jsonb),
  ('en', 'site.how.step4.title', $json$"Verifies the output"$json$::jsonb),
  ('en', 'site.how.step4.detail', $json$"The answer comes back through the exit gate, with the decision and the history in sight."$json$::jsonb),
  ('en', 'site.privacy.title', $json$"Context stays in the right project."$json$::jsonb),
  ('en', 'site.privacy.detail', $json$"Projects, chats and settings persist locally; provider keys are masked after saving."$json$::jsonb),
  ('en', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('en', 'site.register.title', $json$"Create your JayV account"$json$::jsonb),
  ('en', 'site.register.subtitle', $json$"The same account signs in to the app on any machine and to this site."$json$::jsonb),
  ('en', 'site.callback.working', $json$"Finishing sign-in…"$json$::jsonb),
  ('en', 'site.callback.failed', $json$"This link didn't work. Request a new one or sign in again."$json$::jsonb),
  ('en', 'site.session.failed', $json$"Couldn't open your session on the site. Try again."$json$::jsonb),
  ('en', 'site.admin.signIn', $json$"Sign in with the system administrator account to open this page."$json$::jsonb),
  ('en', 'site.notFound.title', $json$"Page not found"$json$::jsonb),
  ('en', 'site.notFound.detail', $json$"This address doesn't exist on the JayV site."$json$::jsonb),
  ('en', 'site.notFound.home', $json$"Back to home"$json$::jsonb),
  ('es', 'site.meta.title', $json$"JayV — Agentes de IA, bajo control"$json$::jsonb),
  ('es', 'site.meta.description', $json$"Descarga JayV para Windows, macOS o Linux. Coordina Codex, Claude Code, GitHub Copilot y Cursor Agent con contexto, control y trazabilidad."$json$::jsonb),
  ('es', 'site.skip', $json$"Saltar al contenido"$json$::jsonb),
  ('es', 'site.nav.label', $json$"Navegación principal"$json$::jsonb),
  ('es', 'site.nav.home', $json$"JayV, inicio"$json$::jsonb),
  ('es', 'site.nav.features', $json$"Funciones"$json$::jsonb),
  ('es', 'site.nav.downloads', $json$"Descargas"$json$::jsonb),
  ('es', 'site.nav.how', $json$"Cómo funciona"$json$::jsonb),
  ('es', 'site.nav.releases', $json$"Versiones"$json$::jsonb),
  ('es', 'site.nav.signIn', $json$"Iniciar sesión"$json$::jsonb),
  ('es', 'site.nav.signUp', $json$"Crear cuenta"$json$::jsonb),
  ('es', 'site.nav.account', $json$"Sesión iniciada como {email}"$json$::jsonb),
  ('es', 'site.hero.eyebrow', $json$"Orquestación local para desarrollo"$json$::jsonb),
  ('es', 'site.hero.title', $json$"Agentes de IA,"$json$::jsonb),
  ('es', 'site.hero.highlight', $json$"bajo control."$json$::jsonb),
  ('es', 'site.hero.copy', $json$"JayV coordina Codex, Claude Code, GitHub Copilot y Cursor Agent en el contexto de cada proyecto. Jev entiende la petición, elige la ruta y verifica la respuesta para mantener el trabajo enfocado y trazable."$json$::jsonb),
  ('es', 'site.hero.download', $json$"Descargar para mi sistema"$json$::jsonb),
  ('es', 'site.hero.downloadFor', $json$"Descargar para {system}"$json$::jsonb),
  ('es', 'site.hero.notes', $json$"Notas de la versión"$json$::jsonb),
  ('es', 'site.hero.release', $json$"Versión {version} · Windows, macOS y Linux"$json$::jsonb),
  ('es', 'site.hero.releaseUnknown', $json$"Windows, macOS y Linux"$json$::jsonb),
  ('es', 'site.hero.agents', $json$"Agentes integrados"$json$::jsonb),
  ('es', 'site.trace.label', $json$"Ejemplo de una ruta analizada por JayV"$json$::jsonb),
  ('es', 'site.trace.request', $json$"revisa el flujo de autenticación"$json$::jsonb),
  ('es', 'site.trace.indexing', $json$"indexando el contexto del proyecto…"$json$::jsonb),
  ('es', 'site.trace.entry', $json$"entrada evaluada"$json$::jsonb),
  ('es', 'site.trace.scope', $json$"alcance: cambio mediano"$json$::jsonb),
  ('es', 'site.trace.agent', $json$"agente"$json$::jsonb),
  ('es', 'site.trace.model', $json$"modelo"$json$::jsonb),
  ('es', 'site.trace.mode', $json$"modo"$json$::jsonb),
  ('es', 'site.trace.role', $json$"rol"$json$::jsonb),
  ('es', 'site.trace.modeValue', $json$"planificación"$json$::jsonb),
  ('es', 'site.trace.roleValue', $json$"revisor"$json$::jsonb),
  ('es', 'site.trace.exit', $json$"salida verificada"$json$::jsonb),
  ('es', 'site.trace.saved', $json$"turno guardado · contexto conservado"$json$::jsonb),
  ('es', 'site.features.kicker', $json$"Lo que ofrece JayV"$json$::jsonb),
  ('es', 'site.features.title', $json$"Un lugar para coordinar todo el trabajo."$json$::jsonb),
  ('es', 'site.features.note', $json$"Proyectos, conversaciones, rutas y consumo reunidos en una interfaz nativa, con el detalle técnico disponible cuando lo necesitas."$json$::jsonb),
  ('es', 'site.features.agents.tag', $json$"agentes"$json$::jsonb),
  ('es', 'site.features.agents.title', $json$"Cuatro agentes, una interfaz"$json$::jsonb),
  ('es', 'site.features.agents.detail', $json$"Configura modelos, permisos, herramientas, sandbox y esfuerzo de cada agente sin editar comandos a mano."$json$::jsonb),
  ('es', 'site.features.routing.tag', $json$"enrutamiento"$json$::jsonb),
  ('es', 'site.features.routing.title', $json$"La ruta sigue a la petición"$json$::jsonb),
  ('es', 'site.features.routing.detail', $json$"La intención, el tamaño y el nivel del desarrollador ayudan a Jev a elegir agente, modelo, modo de ejecución y rol."$json$::jsonb),
  ('es', 'site.features.trace.tag', $json$"trazabilidad"$json$::jsonb),
  ('es', 'site.features.trace.title', $json$"Cada turno tiene historia"$json$::jsonb),
  ('es', 'site.features.trace.detail', $json$"La petición se guarda antes de ejecutarse. Los códigos de turno enlazan los mensajes con los veredictos de las porterías de entrada y salida."$json$::jsonb),
  ('es', 'site.features.account.tag', $json$"cuenta"$json$::jsonb),
  ('es', 'site.features.account.title', $json$"Perfil, actividad y límites"$json$::jsonb),
  ('es', 'site.features.account.detail', $json$"Sigue tu nivel, la actividad de los últimos 30 días y el uso que informa cada agente en un solo lugar."$json$::jsonb),
  ('es', 'site.downloads.kicker', $json$"Descargas oficiales"$json$::jsonb),
  ('es', 'site.downloads.title', $json$"Elige tu sistema"$json$::jsonb),
  ('es', 'site.downloads.note', $json$"Los enlaces apuntan a los archivos publicados en el repositorio oficial. JayV avisa cuando hay una versión nueva."$json$::jsonb),
  ('es', 'site.downloads.recommended', $json$"Tu sistema"$json$::jsonb),
  ('es', 'site.downloads.windows.arch', $json$"64 bits · Windows 10 o superior"$json$::jsonb),
  ('es', 'site.downloads.mac.arch', $json$"Apple Silicon o Intel"$json$::jsonb),
  ('es', 'site.downloads.exe', $json$"Instalador EXE"$json$::jsonb),
  ('es', 'site.downloads.msi', $json$"Paquete MSI"$json$::jsonb),
  ('es', 'site.downloads.dmgArm', $json$"DMG Apple Silicon"$json$::jsonb),
  ('es', 'site.downloads.dmgIntel', $json$"DMG Intel"$json$::jsonb),
  ('es', 'site.downloads.missing', $json$"Paquete aún no disponible."$json$::jsonb),
  ('es', 'site.downloads.meta', $json$"JayV v{version} · publicado el {date}"$json$::jsonb),
  ('es', 'site.downloads.metaUnknown', $json$"Última versión en GitHub"$json$::jsonb),
  ('es', 'site.how.kicker', $json$"Flujo con contexto"$json$::jsonb),
  ('es', 'site.how.title', $json$"Del contexto a la respuesta, cada paso tiene una función."$json$::jsonb),
  ('es', 'site.how.detail', $json$"JayV apunta el índice a la carpeta del proyecto, conserva la conversación y registra cómo se condujo cada turno."$json$::jsonb),
  ('es', 'site.how.step1.title', $json$"Abre el contexto correcto"$json$::jsonb),
  ('es', 'site.how.step1.detail', $json$"Archivos, índice e historial quedan aislados por proyecto y por conversación."$json$::jsonb),
  ('es', 'site.how.step2.title', $json$"Registra y evalúa"$json$::jsonb),
  ('es', 'site.how.step2.detail', $json$"El turno se guarda antes de ejecutarse, y la portería de entrada evalúa la petición."$json$::jsonb),
  ('es', 'site.how.step3.title', $json$"Elige la ruta"$json$::jsonb),
  ('es', 'site.how.step3.detail', $json$"El trabajo va al agente, modelo, modo y rol adecuados al alcance."$json$::jsonb),
  ('es', 'site.how.step4.title', $json$"Verifica la salida"$json$::jsonb),
  ('es', 'site.how.step4.detail', $json$"La respuesta vuelve por la portería de salida, con la decisión y el historial a la vista."$json$::jsonb),
  ('es', 'site.privacy.title', $json$"El contexto se queda en el proyecto correcto."$json$::jsonb),
  ('es', 'site.privacy.detail', $json$"Proyectos, conversaciones y ajustes se guardan localmente; las claves de los proveedores se ocultan después de guardarlas."$json$::jsonb),
  ('es', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('es', 'site.register.title', $json$"Crea tu cuenta de JayV"$json$::jsonb),
  ('es', 'site.register.subtitle', $json$"La misma cuenta inicia sesión en la app en cualquier equipo y en este sitio."$json$::jsonb),
  ('es', 'site.callback.working', $json$"Terminando de iniciar sesión…"$json$::jsonb),
  ('es', 'site.callback.failed', $json$"Este enlace no funcionó. Pide uno nuevo o inicia sesión de nuevo."$json$::jsonb),
  ('es', 'site.session.failed', $json$"No se pudo abrir tu sesión en el sitio. Inténtalo de nuevo."$json$::jsonb),
  ('es', 'site.admin.signIn', $json$"Inicia sesión con la cuenta de administrador del sistema para abrir esta página."$json$::jsonb),
  ('es', 'site.notFound.title', $json$"Página no encontrada"$json$::jsonb),
  ('es', 'site.notFound.detail', $json$"Esta dirección no existe en el sitio de JayV."$json$::jsonb),
  ('es', 'site.notFound.home', $json$"Volver al inicio"$json$::jsonb),
  ('zh-CN', 'site.meta.title', $json$"JayV — 让 AI 智能体尽在掌控"$json$::jsonb),
  ('zh-CN', 'site.meta.description', $json$"下载适用于 Windows、macOS 或 Linux 的 JayV。在上下文、控制和可追溯性之下协调 Codex、Claude Code、GitHub Copilot 和 Cursor Agent。"$json$::jsonb),
  ('zh-CN', 'site.skip', $json$"跳到内容"$json$::jsonb),
  ('zh-CN', 'site.nav.label', $json$"主导航"$json$::jsonb),
  ('zh-CN', 'site.nav.home', $json$"JayV 首页"$json$::jsonb),
  ('zh-CN', 'site.nav.features', $json$"功能"$json$::jsonb),
  ('zh-CN', 'site.nav.downloads', $json$"下载"$json$::jsonb),
  ('zh-CN', 'site.nav.how', $json$"工作原理"$json$::jsonb),
  ('zh-CN', 'site.nav.releases', $json$"版本"$json$::jsonb),
  ('zh-CN', 'site.nav.signIn', $json$"登录"$json$::jsonb),
  ('zh-CN', 'site.nav.signUp', $json$"创建账户"$json$::jsonb),
  ('zh-CN', 'site.nav.account', $json$"已登录：{email}"$json$::jsonb),
  ('zh-CN', 'site.hero.eyebrow', $json$"面向开发的本地编排"$json$::jsonb),
  ('zh-CN', 'site.hero.title', $json$"AI 智能体，"$json$::jsonb),
  ('zh-CN', 'site.hero.highlight', $json$"尽在掌控。"$json$::jsonb),
  ('zh-CN', 'site.hero.copy', $json$"JayV 在每个项目的上下文中协调 Codex、Claude Code、GitHub Copilot 和 Cursor Agent。Jev 理解请求、选择路线并核查回答，让工作保持专注且可追溯。"$json$::jsonb),
  ('zh-CN', 'site.hero.download', $json$"下载适合我系统的版本"$json$::jsonb),
  ('zh-CN', 'site.hero.downloadFor', $json$"下载 {system} 版"$json$::jsonb),
  ('zh-CN', 'site.hero.notes', $json$"版本说明"$json$::jsonb),
  ('zh-CN', 'site.hero.release', $json$"版本 {version} · Windows、macOS 和 Linux"$json$::jsonb),
  ('zh-CN', 'site.hero.releaseUnknown', $json$"Windows、macOS 和 Linux"$json$::jsonb),
  ('zh-CN', 'site.hero.agents', $json$"已集成的智能体"$json$::jsonb),
  ('zh-CN', 'site.trace.label', $json$"JayV 分析的一条路线示例"$json$::jsonb),
  ('zh-CN', 'site.trace.request', $json$"审查身份验证流程"$json$::jsonb),
  ('zh-CN', 'site.trace.indexing', $json$"正在索引项目上下文…"$json$::jsonb),
  ('zh-CN', 'site.trace.entry', $json$"输入已检查"$json$::jsonb),
  ('zh-CN', 'site.trace.scope', $json$"范围：中等改动"$json$::jsonb),
  ('zh-CN', 'site.trace.agent', $json$"智能体"$json$::jsonb),
  ('zh-CN', 'site.trace.model', $json$"模型"$json$::jsonb),
  ('zh-CN', 'site.trace.mode', $json$"模式"$json$::jsonb),
  ('zh-CN', 'site.trace.role', $json$"角色"$json$::jsonb),
  ('zh-CN', 'site.trace.modeValue', $json$"规划"$json$::jsonb),
  ('zh-CN', 'site.trace.roleValue', $json$"审查者"$json$::jsonb),
  ('zh-CN', 'site.trace.exit', $json$"输出已核验"$json$::jsonb),
  ('zh-CN', 'site.trace.saved', $json$"轮次已保存 · 上下文已保留"$json$::jsonb),
  ('zh-CN', 'site.features.kicker', $json$"JayV 带来什么"$json$::jsonb),
  ('zh-CN', 'site.features.title', $json$"在一个地方协调所有工作。"$json$::jsonb),
  ('zh-CN', 'site.features.note', $json$"项目、对话、路线和用量集中在一个原生界面中，需要时随时查看技术细节。"$json$::jsonb),
  ('zh-CN', 'site.features.agents.tag', $json$"智能体"$json$::jsonb),
  ('zh-CN', 'site.features.agents.title', $json$"四个智能体，一个界面"$json$::jsonb),
  ('zh-CN', 'site.features.agents.detail', $json$"无需手动编辑命令，即可为每个智能体设置模型、权限、工具、沙箱和推理强度。"$json$::jsonb),
  ('zh-CN', 'site.features.routing.tag', $json$"路由"$json$::jsonb),
  ('zh-CN', 'site.features.routing.title', $json$"路线随请求而定"$json$::jsonb),
  ('zh-CN', 'site.features.routing.detail', $json$"意图、规模和开发者的水平帮助 Jev 选择智能体、模型、执行模式和角色。"$json$::jsonb),
  ('zh-CN', 'site.features.trace.tag', $json$"可追溯性"$json$::jsonb),
  ('zh-CN', 'site.features.trace.title', $json$"每一轮都有记录"$json$::jsonb),
  ('zh-CN', 'site.features.trace.detail', $json$"请求在执行前保存。轮次代码把消息与入口和出口关卡的判定关联起来。"$json$::jsonb),
  ('zh-CN', 'site.features.account.tag', $json$"账户"$json$::jsonb),
  ('zh-CN', 'site.features.account.title', $json$"资料、活动与限额"$json$::jsonb),
  ('zh-CN', 'site.features.account.detail', $json$"在一个地方查看你的水平、最近 30 天的活动以及每个智能体报告的用量。"$json$::jsonb),
  ('zh-CN', 'site.downloads.kicker', $json$"官方下载"$json$::jsonb),
  ('zh-CN', 'site.downloads.title', $json$"选择你的系统"$json$::jsonb),
  ('zh-CN', 'site.downloads.note', $json$"链接指向官方仓库中发布的文件。有新版本时 JayV 会提醒你。"$json$::jsonb),
  ('zh-CN', 'site.downloads.recommended', $json$"你的系统"$json$::jsonb),
  ('zh-CN', 'site.downloads.windows.arch', $json$"64 位 · Windows 10 或更高版本"$json$::jsonb),
  ('zh-CN', 'site.downloads.mac.arch', $json$"Apple Silicon 或 Intel"$json$::jsonb),
  ('zh-CN', 'site.downloads.exe', $json$"EXE 安装程序"$json$::jsonb),
  ('zh-CN', 'site.downloads.msi', $json$"MSI 安装包"$json$::jsonb),
  ('zh-CN', 'site.downloads.dmgArm', $json$"Apple Silicon DMG"$json$::jsonb),
  ('zh-CN', 'site.downloads.dmgIntel', $json$"Intel DMG"$json$::jsonb),
  ('zh-CN', 'site.downloads.missing', $json$"安装包暂不可用。"$json$::jsonb),
  ('zh-CN', 'site.downloads.meta', $json$"JayV v{version} · 发布于 {date}"$json$::jsonb),
  ('zh-CN', 'site.downloads.metaUnknown', $json$"GitHub 上的最新版本"$json$::jsonb),
  ('zh-CN', 'site.how.kicker', $json$"带上下文的流程"$json$::jsonb),
  ('zh-CN', 'site.how.title', $json$"从上下文到回答，每一步各司其职。"$json$::jsonb),
  ('zh-CN', 'site.how.detail', $json$"JayV 将索引指向项目文件夹，保留对话，并记录每一轮是如何进行的。"$json$::jsonb),
  ('zh-CN', 'site.how.step1.title', $json$"打开正确的上下文"$json$::jsonb),
  ('zh-CN', 'site.how.step1.detail', $json$"文件、索引和历史按项目和对话隔离。"$json$::jsonb),
  ('zh-CN', 'site.how.step2.title', $json$"记录并检查"$json$::jsonb),
  ('zh-CN', 'site.how.step2.detail', $json$"轮次在执行前保存，入口关卡会检查请求。"$json$::jsonb),
  ('zh-CN', 'site.how.step3.title', $json$"选择路线"$json$::jsonb),
  ('zh-CN', 'site.how.step3.detail', $json$"工作交给与范围相符的智能体、模型、模式和角色。"$json$::jsonb),
  ('zh-CN', 'site.how.step4.title', $json$"核验输出"$json$::jsonb),
  ('zh-CN', 'site.how.step4.detail', $json$"回答经出口关卡返回，判定和历史一目了然。"$json$::jsonb),
  ('zh-CN', 'site.privacy.title', $json$"上下文留在正确的项目里。"$json$::jsonb),
  ('zh-CN', 'site.privacy.detail', $json$"项目、对话和设置保存在本地；提供商密钥保存后会被遮盖。"$json$::jsonb),
  ('zh-CN', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('zh-CN', 'site.register.title', $json$"创建你的 JayV 账户"$json$::jsonb),
  ('zh-CN', 'site.register.subtitle', $json$"同一个账户可在任何机器上登录应用，也可登录本网站。"$json$::jsonb),
  ('zh-CN', 'site.callback.working', $json$"正在完成登录…"$json$::jsonb),
  ('zh-CN', 'site.callback.failed', $json$"此链接无效。请重新获取链接或再次登录。"$json$::jsonb),
  ('zh-CN', 'site.session.failed', $json$"无法在网站上打开你的会话。请重试。"$json$::jsonb),
  ('zh-CN', 'site.admin.signIn', $json$"请使用系统管理员账户登录以打开此页面。"$json$::jsonb),
  ('zh-CN', 'site.notFound.title', $json$"找不到页面"$json$::jsonb),
  ('zh-CN', 'site.notFound.detail', $json$"JayV 网站上没有这个地址。"$json$::jsonb),
  ('zh-CN', 'site.notFound.home', $json$"返回首页"$json$::jsonb),
  ('hi', 'site.meta.title', $json$"JayV — AI एजेंट, आपके नियंत्रण में"$json$::jsonb),
  ('hi', 'site.meta.description', $json$"Windows, macOS या Linux के लिए JayV डाउनलोड करें। Codex, Claude Code, GitHub Copilot और Cursor Agent को संदर्भ, नियंत्रण और ट्रेसबिलिटी के साथ समन्वित करें।"$json$::jsonb),
  ('hi', 'site.skip', $json$"सामग्री पर जाएँ"$json$::jsonb),
  ('hi', 'site.nav.label', $json$"मुख्य नेविगेशन"$json$::jsonb),
  ('hi', 'site.nav.home', $json$"JayV, होम"$json$::jsonb),
  ('hi', 'site.nav.features', $json$"सुविधाएँ"$json$::jsonb),
  ('hi', 'site.nav.downloads', $json$"डाउनलोड"$json$::jsonb),
  ('hi', 'site.nav.how', $json$"यह कैसे काम करता है"$json$::jsonb),
  ('hi', 'site.nav.releases', $json$"संस्करण"$json$::jsonb),
  ('hi', 'site.nav.signIn', $json$"साइन इन"$json$::jsonb),
  ('hi', 'site.nav.signUp', $json$"खाता बनाएँ"$json$::jsonb),
  ('hi', 'site.nav.account', $json$"{email} के रूप में साइन इन"$json$::jsonb),
  ('hi', 'site.hero.eyebrow', $json$"डेवलपमेंट के लिए लोकल ऑर्केस्ट्रेशन"$json$::jsonb),
  ('hi', 'site.hero.title', $json$"AI एजेंट,"$json$::jsonb),
  ('hi', 'site.hero.highlight', $json$"आपके नियंत्रण में।"$json$::jsonb),
  ('hi', 'site.hero.copy', $json$"JayV हर प्रोजेक्ट के संदर्भ में Codex, Claude Code, GitHub Copilot और Cursor Agent को समन्वित करता है। Jev अनुरोध समझता है, रास्ता चुनता है और जवाब जाँचता है, ताकि काम केंद्रित और ट्रेस करने योग्य रहे।"$json$::jsonb),
  ('hi', 'site.hero.download', $json$"मेरे सिस्टम के लिए डाउनलोड करें"$json$::jsonb),
  ('hi', 'site.hero.downloadFor', $json$"{system} के लिए डाउनलोड करें"$json$::jsonb),
  ('hi', 'site.hero.notes', $json$"रिलीज़ नोट्स"$json$::jsonb),
  ('hi', 'site.hero.release', $json$"संस्करण {version} · Windows, macOS और Linux"$json$::jsonb),
  ('hi', 'site.hero.releaseUnknown', $json$"Windows, macOS और Linux"$json$::jsonb),
  ('hi', 'site.hero.agents', $json$"जुड़े हुए एजेंट"$json$::jsonb),
  ('hi', 'site.trace.label', $json$"JayV द्वारा विश्लेषित एक रूट का उदाहरण"$json$::jsonb),
  ('hi', 'site.trace.request', $json$"ऑथेंटिकेशन फ़्लो की समीक्षा करो"$json$::jsonb),
  ('hi', 'site.trace.indexing', $json$"प्रोजेक्ट का संदर्भ इंडेक्स हो रहा है…"$json$::jsonb),
  ('hi', 'site.trace.entry', $json$"इनपुट जाँचा गया"$json$::jsonb),
  ('hi', 'site.trace.scope', $json$"दायरा: मध्यम बदलाव"$json$::jsonb),
  ('hi', 'site.trace.agent', $json$"एजेंट"$json$::jsonb),
  ('hi', 'site.trace.model', $json$"मॉडल"$json$::jsonb),
  ('hi', 'site.trace.mode', $json$"मोड"$json$::jsonb),
  ('hi', 'site.trace.role', $json$"भूमिका"$json$::jsonb),
  ('hi', 'site.trace.modeValue', $json$"योजना"$json$::jsonb),
  ('hi', 'site.trace.roleValue', $json$"समीक्षक"$json$::jsonb),
  ('hi', 'site.trace.exit', $json$"आउटपुट सत्यापित"$json$::jsonb),
  ('hi', 'site.trace.saved', $json$"टर्न सहेजा गया · संदर्भ सुरक्षित"$json$::jsonb),
  ('hi', 'site.features.kicker', $json$"JayV क्या देता है"$json$::jsonb),
  ('hi', 'site.features.title', $json$"सारा काम समन्वित करने की एक जगह।"$json$::jsonb),
  ('hi', 'site.features.note', $json$"प्रोजेक्ट, चैट, रूट और उपयोग एक नेटिव इंटरफ़ेस में साथ रहते हैं, और ज़रूरत पड़ने पर तकनीकी विवरण भी मिलता है।"$json$::jsonb),
  ('hi', 'site.features.agents.tag', $json$"एजेंट"$json$::jsonb),
  ('hi', 'site.features.agents.title', $json$"चार एजेंट, एक इंटरफ़ेस"$json$::jsonb),
  ('hi', 'site.features.agents.detail', $json$"हर एजेंट के मॉडल, अनुमतियाँ, टूल, सैंडबॉक्स और प्रयास कमांड हाथ से बदले बिना सेट करें।"$json$::jsonb),
  ('hi', 'site.features.routing.tag', $json$"रूटिंग"$json$::jsonb),
  ('hi', 'site.features.routing.title', $json$"रूट अनुरोध के साथ चलता है"$json$::jsonb),
  ('hi', 'site.features.routing.detail', $json$"इरादा, आकार और डेवलपर का स्तर Jev को एजेंट, मॉडल, एक्ज़ीक्यूशन मोड और भूमिका चुनने में मदद करते हैं।"$json$::jsonb),
  ('hi', 'site.features.trace.tag', $json$"ट्रेसबिलिटी"$json$::jsonb),
  ('hi', 'site.features.trace.title', $json$"हर टर्न का इतिहास है"$json$::jsonb),
  ('hi', 'site.features.trace.detail', $json$"अनुरोध चलने से पहले सहेजा जाता है। टर्न कोड संदेशों को प्रवेश और निकास गेट के फ़ैसलों से जोड़ते हैं।"$json$::jsonb),
  ('hi', 'site.features.account.tag', $json$"खाता"$json$::jsonb),
  ('hi', 'site.features.account.title', $json$"प्रोफ़ाइल, गतिविधि और सीमाएँ"$json$::jsonb),
  ('hi', 'site.features.account.detail', $json$"अपना स्तर, पिछले 30 दिनों की गतिविधि और हर एजेंट द्वारा बताया गया उपयोग एक ही जगह देखें।"$json$::jsonb),
  ('hi', 'site.downloads.kicker', $json$"आधिकारिक डाउनलोड"$json$::jsonb),
  ('hi', 'site.downloads.title', $json$"अपना सिस्टम चुनें"$json$::jsonb),
  ('hi', 'site.downloads.note', $json$"लिंक आधिकारिक रिपॉज़िटरी में प्रकाशित फ़ाइलों की ओर जाते हैं। नया संस्करण आने पर JayV बताता है।"$json$::jsonb),
  ('hi', 'site.downloads.recommended', $json$"आपका सिस्टम"$json$::jsonb),
  ('hi', 'site.downloads.windows.arch', $json$"64-बिट · Windows 10 या नया"$json$::jsonb),
  ('hi', 'site.downloads.mac.arch', $json$"Apple Silicon या Intel"$json$::jsonb),
  ('hi', 'site.downloads.exe', $json$"EXE इंस्टॉलर"$json$::jsonb),
  ('hi', 'site.downloads.msi', $json$"MSI पैकेज"$json$::jsonb),
  ('hi', 'site.downloads.dmgArm', $json$"Apple Silicon DMG"$json$::jsonb),
  ('hi', 'site.downloads.dmgIntel', $json$"Intel DMG"$json$::jsonb),
  ('hi', 'site.downloads.missing', $json$"पैकेज अभी उपलब्ध नहीं है।"$json$::jsonb),
  ('hi', 'site.downloads.meta', $json$"JayV v{version} · {date} को प्रकाशित"$json$::jsonb),
  ('hi', 'site.downloads.metaUnknown', $json$"GitHub पर नवीनतम संस्करण"$json$::jsonb),
  ('hi', 'site.how.kicker', $json$"संदर्भ के साथ प्रवाह"$json$::jsonb),
  ('hi', 'site.how.title', $json$"संदर्भ से जवाब तक, हर चरण का एक काम है।"$json$::jsonb),
  ('hi', 'site.how.detail', $json$"JayV इंडेक्स को प्रोजेक्ट फ़ोल्डर पर लगाता है, बातचीत सहेजता है और दर्ज करता है कि हर टर्न कैसे चला।"$json$::jsonb),
  ('hi', 'site.how.step1.title', $json$"सही संदर्भ खोलता है"$json$::jsonb),
  ('hi', 'site.how.step1.detail', $json$"फ़ाइलें, इंडेक्स और इतिहास हर प्रोजेक्ट और हर चैट के लिए अलग रहते हैं।"$json$::jsonb),
  ('hi', 'site.how.step2.title', $json$"दर्ज करता और जाँचता है"$json$::jsonb),
  ('hi', 'site.how.step2.detail', $json$"टर्न चलने से पहले सहेजा जाता है, और प्रवेश गेट अनुरोध को जाँचता है।"$json$::jsonb),
  ('hi', 'site.how.step3.title', $json$"रूट चुनता है"$json$::jsonb),
  ('hi', 'site.how.step3.detail', $json$"काम दायरे के अनुसार सही एजेंट, मॉडल, मोड और भूमिका तक जाता है।"$json$::jsonb),
  ('hi', 'site.how.step4.title', $json$"आउटपुट सत्यापित करता है"$json$::jsonb),
  ('hi', 'site.how.step4.detail', $json$"जवाब निकास गेट से लौटता है, फ़ैसला और इतिहास सामने रहते हैं।"$json$::jsonb),
  ('hi', 'site.privacy.title', $json$"संदर्भ सही प्रोजेक्ट में रहता है।"$json$::jsonb),
  ('hi', 'site.privacy.detail', $json$"प्रोजेक्ट, चैट और सेटिंग्स लोकल रहती हैं; प्रोवाइडर कुंजियाँ सहेजने के बाद छिपा दी जाती हैं।"$json$::jsonb),
  ('hi', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('hi', 'site.register.title', $json$"अपना JayV खाता बनाएँ"$json$::jsonb),
  ('hi', 'site.register.subtitle', $json$"यही खाता किसी भी मशीन पर ऐप में और इस साइट पर साइन इन करता है।"$json$::jsonb),
  ('hi', 'site.callback.working', $json$"साइन इन पूरा हो रहा है…"$json$::jsonb),
  ('hi', 'site.callback.failed', $json$"यह लिंक काम नहीं किया। नया लिंक माँगें या फिर से साइन इन करें।"$json$::jsonb),
  ('hi', 'site.session.failed', $json$"साइट पर आपका सत्र नहीं खुल सका। फिर से कोशिश करें।"$json$::jsonb),
  ('hi', 'site.admin.signIn', $json$"यह पेज खोलने के लिए सिस्टम एडमिनिस्ट्रेटर खाते से साइन इन करें।"$json$::jsonb),
  ('hi', 'site.notFound.title', $json$"पेज नहीं मिला"$json$::jsonb),
  ('hi', 'site.notFound.detail', $json$"यह पता JayV साइट पर मौजूद नहीं है।"$json$::jsonb),
  ('hi', 'site.notFound.home', $json$"होम पर लौटें"$json$::jsonb),
  ('ar', 'site.meta.title', $json$"JayV — وكلاء الذكاء الاصطناعي تحت السيطرة"$json$::jsonb),
  ('ar', 'site.meta.description', $json$"نزّل JayV لنظام Windows أو macOS أو Linux. نسّق بين Codex وClaude Code وGitHub Copilot وCursor Agent مع السياق والتحكم وإمكانية التتبع."$json$::jsonb),
  ('ar', 'site.skip', $json$"انتقل إلى المحتوى"$json$::jsonb),
  ('ar', 'site.nav.label', $json$"التنقل الرئيسي"$json$::jsonb),
  ('ar', 'site.nav.home', $json$"JayV، الصفحة الرئيسية"$json$::jsonb),
  ('ar', 'site.nav.features', $json$"الميزات"$json$::jsonb),
  ('ar', 'site.nav.downloads', $json$"التنزيلات"$json$::jsonb),
  ('ar', 'site.nav.how', $json$"كيف يعمل"$json$::jsonb),
  ('ar', 'site.nav.releases', $json$"الإصدارات"$json$::jsonb),
  ('ar', 'site.nav.signIn', $json$"تسجيل الدخول"$json$::jsonb),
  ('ar', 'site.nav.signUp', $json$"إنشاء حساب"$json$::jsonb),
  ('ar', 'site.nav.account', $json$"مسجّل الدخول باسم {email}"$json$::jsonb),
  ('ar', 'site.hero.eyebrow', $json$"تنسيق محلي للتطوير"$json$::jsonb),
  ('ar', 'site.hero.title', $json$"وكلاء الذكاء الاصطناعي،"$json$::jsonb),
  ('ar', 'site.hero.highlight', $json$"تحت السيطرة."$json$::jsonb),
  ('ar', 'site.hero.copy', $json$"ينسّق JayV بين Codex وClaude Code وGitHub Copilot وCursor Agent في سياق كل مشروع. يفهم Jev الطلب ويختار المسار ويتحقق من الإجابة ليبقى العمل مركّزًا وقابلًا للتتبع."$json$::jsonb),
  ('ar', 'site.hero.download', $json$"نزّل لنظامي"$json$::jsonb),
  ('ar', 'site.hero.downloadFor', $json$"نزّل لـ {system}"$json$::jsonb),
  ('ar', 'site.hero.notes', $json$"ملاحظات الإصدار"$json$::jsonb),
  ('ar', 'site.hero.release', $json$"الإصدار {version} · Windows وmacOS وLinux"$json$::jsonb),
  ('ar', 'site.hero.releaseUnknown', $json$"Windows وmacOS وLinux"$json$::jsonb),
  ('ar', 'site.hero.agents', $json$"الوكلاء المدمجون"$json$::jsonb),
  ('ar', 'site.trace.label', $json$"مثال لمسار حلّله JayV"$json$::jsonb),
  ('ar', 'site.trace.request', $json$"راجع مسار المصادقة"$json$::jsonb),
  ('ar', 'site.trace.indexing', $json$"جارٍ فهرسة سياق المشروع…"$json$::jsonb),
  ('ar', 'site.trace.entry', $json$"تم فحص المدخل"$json$::jsonb),
  ('ar', 'site.trace.scope', $json$"النطاق: تغيير متوسط"$json$::jsonb),
  ('ar', 'site.trace.agent', $json$"الوكيل"$json$::jsonb),
  ('ar', 'site.trace.model', $json$"النموذج"$json$::jsonb),
  ('ar', 'site.trace.mode', $json$"الوضع"$json$::jsonb),
  ('ar', 'site.trace.role', $json$"الدور"$json$::jsonb),
  ('ar', 'site.trace.modeValue', $json$"تخطيط"$json$::jsonb),
  ('ar', 'site.trace.roleValue', $json$"مراجع"$json$::jsonb),
  ('ar', 'site.trace.exit', $json$"تم التحقق من المخرج"$json$::jsonb),
  ('ar', 'site.trace.saved', $json$"حُفظ الدور · السياق محفوظ"$json$::jsonb),
  ('ar', 'site.features.kicker', $json$"ما يقدّمه JayV"$json$::jsonb),
  ('ar', 'site.features.title', $json$"مكان واحد لتنسيق العمل كله."$json$::jsonb),
  ('ar', 'site.features.note', $json$"المشاريع والمحادثات والمسارات والاستهلاك مجتمعة في واجهة أصلية، مع التفاصيل التقنية عند حاجتك إليها."$json$::jsonb),
  ('ar', 'site.features.agents.tag', $json$"الوكلاء"$json$::jsonb),
  ('ar', 'site.features.agents.title', $json$"أربعة وكلاء، واجهة واحدة"$json$::jsonb),
  ('ar', 'site.features.agents.detail', $json$"اضبط النماذج والأذونات والأدوات وصندوق العزل ومستوى الجهد لكل وكيل دون تعديل الأوامر يدويًا."$json$::jsonb),
  ('ar', 'site.features.routing.tag', $json$"التوجيه"$json$::jsonb),
  ('ar', 'site.features.routing.title', $json$"المسار يتبع الطلب"$json$::jsonb),
  ('ar', 'site.features.routing.detail', $json$"تساعد النية والحجم ومستوى المطوّر Jev على اختيار الوكيل والنموذج ووضع التنفيذ والدور."$json$::jsonb),
  ('ar', 'site.features.trace.tag', $json$"التتبع"$json$::jsonb),
  ('ar', 'site.features.trace.title', $json$"لكل دور سجل"$json$::jsonb),
  ('ar', 'site.features.trace.detail', $json$"يُحفظ الطلب قبل تنفيذه. تربط رموز الأدوار الرسائل بقرارات بوابتي الدخول والخروج."$json$::jsonb),
  ('ar', 'site.features.account.tag', $json$"الحساب"$json$::jsonb),
  ('ar', 'site.features.account.title', $json$"الملف الشخصي والنشاط والحدود"$json$::jsonb),
  ('ar', 'site.features.account.detail', $json$"تابع مستواك ونشاط آخر 30 يومًا والاستهلاك الذي يبلغ عنه كل وكيل في مكان واحد."$json$::jsonb),
  ('ar', 'site.downloads.kicker', $json$"التنزيلات الرسمية"$json$::jsonb),
  ('ar', 'site.downloads.title', $json$"اختر نظامك"$json$::jsonb),
  ('ar', 'site.downloads.note', $json$"تشير الروابط إلى الملفات المنشورة في المستودع الرسمي. ينبهك JayV عند صدور إصدار جديد."$json$::jsonb),
  ('ar', 'site.downloads.recommended', $json$"نظامك"$json$::jsonb),
  ('ar', 'site.downloads.windows.arch', $json$"64 بت · Windows 10 أو أحدث"$json$::jsonb),
  ('ar', 'site.downloads.mac.arch', $json$"Apple Silicon أو Intel"$json$::jsonb),
  ('ar', 'site.downloads.exe', $json$"مثبّت EXE"$json$::jsonb),
  ('ar', 'site.downloads.msi', $json$"حزمة MSI"$json$::jsonb),
  ('ar', 'site.downloads.dmgArm', $json$"DMG لـ Apple Silicon"$json$::jsonb),
  ('ar', 'site.downloads.dmgIntel', $json$"DMG لـ Intel"$json$::jsonb),
  ('ar', 'site.downloads.missing', $json$"الحزمة غير متاحة بعد."$json$::jsonb),
  ('ar', 'site.downloads.meta', $json$"JayV v{version} · نُشر في {date}"$json$::jsonb),
  ('ar', 'site.downloads.metaUnknown', $json$"أحدث إصدار على GitHub"$json$::jsonb),
  ('ar', 'site.how.kicker', $json$"تدفق بسياق"$json$::jsonb),
  ('ar', 'site.how.title', $json$"من السياق إلى الإجابة، لكل خطوة وظيفة."$json$::jsonb),
  ('ar', 'site.how.detail', $json$"يوجّه JayV الفهرس إلى مجلد المشروع، ويحفظ المحادثة، ويسجّل كيف جرى كل دور."$json$::jsonb),
  ('ar', 'site.how.step1.title', $json$"يفتح السياق الصحيح"$json$::jsonb),
  ('ar', 'site.how.step1.detail', $json$"الملفات والفهرس والسجل معزولة لكل مشروع ولكل محادثة."$json$::jsonb),
  ('ar', 'site.how.step2.title', $json$"يسجّل ويفحص"$json$::jsonb),
  ('ar', 'site.how.step2.detail', $json$"يُحفظ الدور قبل تنفيذه، وتفحص بوابة الدخول الطلب."$json$::jsonb),
  ('ar', 'site.how.step3.title', $json$"يختار المسار"$json$::jsonb),
  ('ar', 'site.how.step3.detail', $json$"يذهب العمل إلى الوكيل والنموذج والوضع والدور المناسبة للنطاق."$json$::jsonb),
  ('ar', 'site.how.step4.title', $json$"يتحقق من المخرج"$json$::jsonb),
  ('ar', 'site.how.step4.detail', $json$"تعود الإجابة عبر بوابة الخروج، مع القرار والسجل أمامك."$json$::jsonb),
  ('ar', 'site.privacy.title', $json$"يبقى السياق في المشروع الصحيح."$json$::jsonb),
  ('ar', 'site.privacy.detail', $json$"تبقى المشاريع والمحادثات والإعدادات محليًا؛ وتُخفى مفاتيح المزوّدين بعد حفظها."$json$::jsonb),
  ('ar', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('ar', 'site.register.title', $json$"أنشئ حسابك في JayV"$json$::jsonb),
  ('ar', 'site.register.subtitle', $json$"الحساب نفسه يسجّل دخولك إلى التطبيق على أي جهاز وإلى هذا الموقع."$json$::jsonb),
  ('ar', 'site.callback.working', $json$"جارٍ إكمال تسجيل الدخول…"$json$::jsonb),
  ('ar', 'site.callback.failed', $json$"لم يعمل هذا الرابط. اطلب رابطًا جديدًا أو سجّل الدخول من جديد."$json$::jsonb),
  ('ar', 'site.session.failed', $json$"تعذّر فتح جلستك على الموقع. حاول مرة أخرى."$json$::jsonb),
  ('ar', 'site.admin.signIn', $json$"سجّل الدخول بحساب مسؤول النظام لفتح هذه الصفحة."$json$::jsonb),
  ('ar', 'site.notFound.title', $json$"الصفحة غير موجودة"$json$::jsonb),
  ('ar', 'site.notFound.detail', $json$"هذا العنوان غير موجود في موقع JayV."$json$::jsonb),
  ('ar', 'site.notFound.home', $json$"العودة إلى الرئيسية"$json$::jsonb),
  ('fr', 'site.meta.title', $json$"JayV — Des agents d'IA sous contrôle"$json$::jsonb),
  ('fr', 'site.meta.description', $json$"Téléchargez JayV pour Windows, macOS ou Linux. Coordonnez Codex, Claude Code, GitHub Copilot et Cursor Agent avec contexte, contrôle et traçabilité."$json$::jsonb),
  ('fr', 'site.skip', $json$"Aller au contenu"$json$::jsonb),
  ('fr', 'site.nav.label', $json$"Navigation principale"$json$::jsonb),
  ('fr', 'site.nav.home', $json$"JayV, accueil"$json$::jsonb),
  ('fr', 'site.nav.features', $json$"Fonctionnalités"$json$::jsonb),
  ('fr', 'site.nav.downloads', $json$"Téléchargements"$json$::jsonb),
  ('fr', 'site.nav.how', $json$"Fonctionnement"$json$::jsonb),
  ('fr', 'site.nav.releases', $json$"Versions"$json$::jsonb),
  ('fr', 'site.nav.signIn', $json$"Se connecter"$json$::jsonb),
  ('fr', 'site.nav.signUp', $json$"Créer un compte"$json$::jsonb),
  ('fr', 'site.nav.account', $json$"Connecté en tant que {email}"$json$::jsonb),
  ('fr', 'site.hero.eyebrow', $json$"Orchestration locale pour le développement"$json$::jsonb),
  ('fr', 'site.hero.title', $json$"Des agents d'IA,"$json$::jsonb),
  ('fr', 'site.hero.highlight', $json$"sous contrôle."$json$::jsonb),
  ('fr', 'site.hero.copy', $json$"JayV coordonne Codex, Claude Code, GitHub Copilot et Cursor Agent dans le contexte de chaque projet. Jev comprend la demande, choisit la route et vérifie la réponse pour garder le travail ciblé et traçable."$json$::jsonb),
  ('fr', 'site.hero.download', $json$"Télécharger pour mon système"$json$::jsonb),
  ('fr', 'site.hero.downloadFor', $json$"Télécharger pour {system}"$json$::jsonb),
  ('fr', 'site.hero.notes', $json$"Notes de version"$json$::jsonb),
  ('fr', 'site.hero.release', $json$"Version {version} · Windows, macOS et Linux"$json$::jsonb),
  ('fr', 'site.hero.releaseUnknown', $json$"Windows, macOS et Linux"$json$::jsonb),
  ('fr', 'site.hero.agents', $json$"Agents intégrés"$json$::jsonb),
  ('fr', 'site.trace.label', $json$"Exemple d'une route analysée par JayV"$json$::jsonb),
  ('fr', 'site.trace.request', $json$"revois le flux d'authentification"$json$::jsonb),
  ('fr', 'site.trace.indexing', $json$"indexation du contexte du projet…"$json$::jsonb),
  ('fr', 'site.trace.entry', $json$"entrée évaluée"$json$::jsonb),
  ('fr', 'site.trace.scope', $json$"portée : changement moyen"$json$::jsonb),
  ('fr', 'site.trace.agent', $json$"agent"$json$::jsonb),
  ('fr', 'site.trace.model', $json$"modèle"$json$::jsonb),
  ('fr', 'site.trace.mode', $json$"mode"$json$::jsonb),
  ('fr', 'site.trace.role', $json$"rôle"$json$::jsonb),
  ('fr', 'site.trace.modeValue', $json$"planification"$json$::jsonb),
  ('fr', 'site.trace.roleValue', $json$"relecteur"$json$::jsonb),
  ('fr', 'site.trace.exit', $json$"sortie vérifiée"$json$::jsonb),
  ('fr', 'site.trace.saved', $json$"tour enregistré · contexte conservé"$json$::jsonb),
  ('fr', 'site.features.kicker', $json$"Ce que JayV apporte"$json$::jsonb),
  ('fr', 'site.features.title', $json$"Un seul endroit pour coordonner tout le travail."$json$::jsonb),
  ('fr', 'site.features.note', $json$"Projets, conversations, routes et consommation réunis dans une interface native, avec le détail technique quand vous en avez besoin."$json$::jsonb),
  ('fr', 'site.features.agents.tag', $json$"agents"$json$::jsonb),
  ('fr', 'site.features.agents.title', $json$"Quatre agents, une interface"$json$::jsonb),
  ('fr', 'site.features.agents.detail', $json$"Configurez modèles, permissions, outils, sandbox et effort de chaque agent sans modifier les commandes à la main."$json$::jsonb),
  ('fr', 'site.features.routing.tag', $json$"routage"$json$::jsonb),
  ('fr', 'site.features.routing.title', $json$"La route suit la demande"$json$::jsonb),
  ('fr', 'site.features.routing.detail', $json$"L'intention, la taille et le niveau du développeur aident Jev à choisir l'agent, le modèle, le mode d'exécution et le rôle."$json$::jsonb),
  ('fr', 'site.features.trace.tag', $json$"traçabilité"$json$::jsonb),
  ('fr', 'site.features.trace.title', $json$"Chaque tour a une histoire"$json$::jsonb),
  ('fr', 'site.features.trace.detail', $json$"La demande est enregistrée avant l'exécution. Les codes de tour relient les messages aux verdicts des contrôles d'entrée et de sortie."$json$::jsonb),
  ('fr', 'site.features.account.tag', $json$"compte"$json$::jsonb),
  ('fr', 'site.features.account.title', $json$"Profil, activité et limites"$json$::jsonb),
  ('fr', 'site.features.account.detail', $json$"Suivez votre niveau, l'activité des 30 derniers jours et l'usage déclaré par chaque agent, au même endroit."$json$::jsonb),
  ('fr', 'site.downloads.kicker', $json$"Téléchargements officiels"$json$::jsonb),
  ('fr', 'site.downloads.title', $json$"Choisissez votre système"$json$::jsonb),
  ('fr', 'site.downloads.note', $json$"Les liens pointent vers les fichiers publiés dans le dépôt officiel. JayV vous prévient quand une nouvelle version sort."$json$::jsonb),
  ('fr', 'site.downloads.recommended', $json$"Votre système"$json$::jsonb),
  ('fr', 'site.downloads.windows.arch', $json$"64 bits · Windows 10 ou ultérieur"$json$::jsonb),
  ('fr', 'site.downloads.mac.arch', $json$"Apple Silicon ou Intel"$json$::jsonb),
  ('fr', 'site.downloads.exe', $json$"Installateur EXE"$json$::jsonb),
  ('fr', 'site.downloads.msi', $json$"Paquet MSI"$json$::jsonb),
  ('fr', 'site.downloads.dmgArm', $json$"DMG Apple Silicon"$json$::jsonb),
  ('fr', 'site.downloads.dmgIntel', $json$"DMG Intel"$json$::jsonb),
  ('fr', 'site.downloads.missing', $json$"Paquet pas encore disponible."$json$::jsonb),
  ('fr', 'site.downloads.meta', $json$"JayV v{version} · publié le {date}"$json$::jsonb),
  ('fr', 'site.downloads.metaUnknown', $json$"Dernière version sur GitHub"$json$::jsonb),
  ('fr', 'site.how.kicker', $json$"Un flux avec contexte"$json$::jsonb),
  ('fr', 'site.how.title', $json$"Du contexte à la réponse, chaque étape a un rôle."$json$::jsonb),
  ('fr', 'site.how.detail', $json$"JayV pointe l'index sur le dossier du projet, conserve la conversation et enregistre comment chaque tour a été mené."$json$::jsonb),
  ('fr', 'site.how.step1.title', $json$"Ouvre le bon contexte"$json$::jsonb),
  ('fr', 'site.how.step1.detail', $json$"Fichiers, index et historique sont isolés par projet et par conversation."$json$::jsonb),
  ('fr', 'site.how.step2.title', $json$"Enregistre et évalue"$json$::jsonb),
  ('fr', 'site.how.step2.detail', $json$"Le tour est enregistré avant l'exécution, et le contrôle d'entrée évalue la demande."$json$::jsonb),
  ('fr', 'site.how.step3.title', $json$"Choisit la route"$json$::jsonb),
  ('fr', 'site.how.step3.detail', $json$"Le travail part vers l'agent, le modèle, le mode et le rôle adaptés à la portée."$json$::jsonb),
  ('fr', 'site.how.step4.title', $json$"Vérifie la sortie"$json$::jsonb),
  ('fr', 'site.how.step4.detail', $json$"La réponse revient par le contrôle de sortie, avec la décision et l'historique visibles."$json$::jsonb),
  ('fr', 'site.privacy.title', $json$"Le contexte reste dans le bon projet."$json$::jsonb),
  ('fr', 'site.privacy.detail', $json$"Projets, conversations et réglages restent en local ; les clés des fournisseurs sont masquées après l'enregistrement."$json$::jsonb),
  ('fr', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('fr', 'site.register.title', $json$"Créez votre compte JayV"$json$::jsonb),
  ('fr', 'site.register.subtitle', $json$"Le même compte vous connecte à l'app sur n'importe quelle machine et à ce site."$json$::jsonb),
  ('fr', 'site.callback.working', $json$"Connexion en cours…"$json$::jsonb),
  ('fr', 'site.callback.failed', $json$"Ce lien n'a pas fonctionné. Demandez-en un nouveau ou reconnectez-vous."$json$::jsonb),
  ('fr', 'site.session.failed', $json$"Impossible d'ouvrir votre session sur le site. Réessayez."$json$::jsonb),
  ('fr', 'site.admin.signIn', $json$"Connectez-vous avec le compte administrateur du système pour ouvrir cette page."$json$::jsonb),
  ('fr', 'site.notFound.title', $json$"Page introuvable"$json$::jsonb),
  ('fr', 'site.notFound.detail', $json$"Cette adresse n'existe pas sur le site de JayV."$json$::jsonb),
  ('fr', 'site.notFound.home', $json$"Retour à l'accueil"$json$::jsonb),
  ('ru', 'site.meta.title', $json$"JayV — ИИ-агенты под контролем"$json$::jsonb),
  ('ru', 'site.meta.description', $json$"Скачайте JayV для Windows, macOS или Linux. Координируйте Codex, Claude Code, GitHub Copilot и Cursor Agent с контекстом, контролем и прослеживаемостью."$json$::jsonb),
  ('ru', 'site.skip', $json$"Перейти к содержимому"$json$::jsonb),
  ('ru', 'site.nav.label', $json$"Основная навигация"$json$::jsonb),
  ('ru', 'site.nav.home', $json$"JayV, главная"$json$::jsonb),
  ('ru', 'site.nav.features', $json$"Возможности"$json$::jsonb),
  ('ru', 'site.nav.downloads', $json$"Загрузки"$json$::jsonb),
  ('ru', 'site.nav.how', $json$"Как это работает"$json$::jsonb),
  ('ru', 'site.nav.releases', $json$"Версии"$json$::jsonb),
  ('ru', 'site.nav.signIn', $json$"Войти"$json$::jsonb),
  ('ru', 'site.nav.signUp', $json$"Создать аккаунт"$json$::jsonb),
  ('ru', 'site.nav.account', $json$"Вы вошли как {email}"$json$::jsonb),
  ('ru', 'site.hero.eyebrow', $json$"Локальная оркестрация для разработки"$json$::jsonb),
  ('ru', 'site.hero.title', $json$"ИИ-агенты"$json$::jsonb),
  ('ru', 'site.hero.highlight', $json$"под контролем."$json$::jsonb),
  ('ru', 'site.hero.copy', $json$"JayV координирует Codex, Claude Code, GitHub Copilot и Cursor Agent в контексте каждого проекта. Jev понимает запрос, выбирает маршрут и проверяет ответ, чтобы работа оставалась сфокусированной и прослеживаемой."$json$::jsonb),
  ('ru', 'site.hero.download', $json$"Скачать для моей системы"$json$::jsonb),
  ('ru', 'site.hero.downloadFor', $json$"Скачать для {system}"$json$::jsonb),
  ('ru', 'site.hero.notes', $json$"Примечания к версии"$json$::jsonb),
  ('ru', 'site.hero.release', $json$"Версия {version} · Windows, macOS и Linux"$json$::jsonb),
  ('ru', 'site.hero.releaseUnknown', $json$"Windows, macOS и Linux"$json$::jsonb),
  ('ru', 'site.hero.agents', $json$"Встроенные агенты"$json$::jsonb),
  ('ru', 'site.trace.label', $json$"Пример маршрута, проанализированного JayV"$json$::jsonb),
  ('ru', 'site.trace.request', $json$"проверь процесс аутентификации"$json$::jsonb),
  ('ru', 'site.trace.indexing', $json$"индексация контекста проекта…"$json$::jsonb),
  ('ru', 'site.trace.entry', $json$"вход проверен"$json$::jsonb),
  ('ru', 'site.trace.scope', $json$"объём: среднее изменение"$json$::jsonb),
  ('ru', 'site.trace.agent', $json$"агент"$json$::jsonb),
  ('ru', 'site.trace.model', $json$"модель"$json$::jsonb),
  ('ru', 'site.trace.mode', $json$"режим"$json$::jsonb),
  ('ru', 'site.trace.role', $json$"роль"$json$::jsonb),
  ('ru', 'site.trace.modeValue', $json$"планирование"$json$::jsonb),
  ('ru', 'site.trace.roleValue', $json$"ревьюер"$json$::jsonb),
  ('ru', 'site.trace.exit', $json$"выход проверен"$json$::jsonb),
  ('ru', 'site.trace.saved', $json$"ход сохранён · контекст сохранён"$json$::jsonb),
  ('ru', 'site.features.kicker', $json$"Что даёт JayV"$json$::jsonb),
  ('ru', 'site.features.title', $json$"Одно место, чтобы координировать всю работу."$json$::jsonb),
  ('ru', 'site.features.note', $json$"Проекты, чаты, маршруты и расход собраны в нативном интерфейсе, а технические детали под рукой, когда они нужны."$json$::jsonb),
  ('ru', 'site.features.agents.tag', $json$"агенты"$json$::jsonb),
  ('ru', 'site.features.agents.title', $json$"Четыре агента, один интерфейс"$json$::jsonb),
  ('ru', 'site.features.agents.detail', $json$"Настраивайте модели, разрешения, инструменты, песочницу и усилие каждого агента, не редактируя команды вручную."$json$::jsonb),
  ('ru', 'site.features.routing.tag', $json$"маршрутизация"$json$::jsonb),
  ('ru', 'site.features.routing.title', $json$"Маршрут следует за запросом"$json$::jsonb),
  ('ru', 'site.features.routing.detail', $json$"Намерение, размер задачи и уровень разработчика помогают Jev выбрать агента, модель, режим выполнения и роль."$json$::jsonb),
  ('ru', 'site.features.trace.tag', $json$"прослеживаемость"$json$::jsonb),
  ('ru', 'site.features.trace.title', $json$"У каждого хода есть история"$json$::jsonb),
  ('ru', 'site.features.trace.detail', $json$"Запрос сохраняется до выполнения. Коды ходов связывают сообщения с вердиктами входной и выходной проверки."$json$::jsonb),
  ('ru', 'site.features.account.tag', $json$"аккаунт"$json$::jsonb),
  ('ru', 'site.features.account.title', $json$"Профиль, активность и лимиты"$json$::jsonb),
  ('ru', 'site.features.account.detail', $json$"Следите за своим уровнем, активностью за последние 30 дней и расходом, о котором сообщает каждый агент, в одном месте."$json$::jsonb),
  ('ru', 'site.downloads.kicker', $json$"Официальные загрузки"$json$::jsonb),
  ('ru', 'site.downloads.title', $json$"Выберите свою систему"$json$::jsonb),
  ('ru', 'site.downloads.note', $json$"Ссылки ведут на файлы, опубликованные в официальном репозитории. JayV сообщит, когда выйдет новая версия."$json$::jsonb),
  ('ru', 'site.downloads.recommended', $json$"Ваша система"$json$::jsonb),
  ('ru', 'site.downloads.windows.arch', $json$"64 бита · Windows 10 или новее"$json$::jsonb),
  ('ru', 'site.downloads.mac.arch', $json$"Apple Silicon или Intel"$json$::jsonb),
  ('ru', 'site.downloads.exe', $json$"Установщик EXE"$json$::jsonb),
  ('ru', 'site.downloads.msi', $json$"Пакет MSI"$json$::jsonb),
  ('ru', 'site.downloads.dmgArm', $json$"DMG для Apple Silicon"$json$::jsonb),
  ('ru', 'site.downloads.dmgIntel', $json$"DMG для Intel"$json$::jsonb),
  ('ru', 'site.downloads.missing', $json$"Пакет пока недоступен."$json$::jsonb),
  ('ru', 'site.downloads.meta', $json$"JayV v{version} · опубликовано {date}"$json$::jsonb),
  ('ru', 'site.downloads.metaUnknown', $json$"Последняя версия на GitHub"$json$::jsonb),
  ('ru', 'site.how.kicker', $json$"Процесс с контекстом"$json$::jsonb),
  ('ru', 'site.how.title', $json$"От контекста до ответа у каждого шага своя задача."$json$::jsonb),
  ('ru', 'site.how.detail', $json$"JayV направляет индекс на папку проекта, сохраняет разговор и записывает, как прошёл каждый ход."$json$::jsonb),
  ('ru', 'site.how.step1.title', $json$"Открывает нужный контекст"$json$::jsonb),
  ('ru', 'site.how.step1.detail', $json$"Файлы, индекс и история изолированы по проектам и чатам."$json$::jsonb),
  ('ru', 'site.how.step2.title', $json$"Записывает и проверяет"$json$::jsonb),
  ('ru', 'site.how.step2.detail', $json$"Ход сохраняется до выполнения, а входная проверка оценивает запрос."$json$::jsonb),
  ('ru', 'site.how.step3.title', $json$"Выбирает маршрут"$json$::jsonb),
  ('ru', 'site.how.step3.detail', $json$"Работа уходит к агенту, модели, режиму и роли, подходящим к объёму."$json$::jsonb),
  ('ru', 'site.how.step4.title', $json$"Проверяет результат"$json$::jsonb),
  ('ru', 'site.how.step4.detail', $json$"Ответ возвращается через выходную проверку, с решением и историей на виду."$json$::jsonb),
  ('ru', 'site.privacy.title', $json$"Контекст остаётся в нужном проекте."$json$::jsonb),
  ('ru', 'site.privacy.detail', $json$"Проекты, чаты и настройки хранятся локально; ключи провайдеров маскируются после сохранения."$json$::jsonb),
  ('ru', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('ru', 'site.register.title', $json$"Создайте аккаунт JayV"$json$::jsonb),
  ('ru', 'site.register.subtitle', $json$"С этим же аккаунтом вы входите в приложение на любом компьютере и на этот сайт."$json$::jsonb),
  ('ru', 'site.callback.working', $json$"Завершаем вход…"$json$::jsonb),
  ('ru', 'site.callback.failed', $json$"Эта ссылка не сработала. Запросите новую или войдите снова."$json$::jsonb),
  ('ru', 'site.session.failed', $json$"Не удалось открыть сеанс на сайте. Попробуйте ещё раз."$json$::jsonb),
  ('ru', 'site.admin.signIn', $json$"Войдите с аккаунтом администратора системы, чтобы открыть эту страницу."$json$::jsonb),
  ('ru', 'site.notFound.title', $json$"Страница не найдена"$json$::jsonb),
  ('ru', 'site.notFound.detail', $json$"Такого адреса нет на сайте JayV."$json$::jsonb),
  ('ru', 'site.notFound.home', $json$"На главную"$json$::jsonb),
  ('ja', 'site.meta.title', $json$"JayV — AI エージェントを手の内に"$json$::jsonb),
  ('ja', 'site.meta.description', $json$"Windows、macOS、Linux 向けの JayV をダウンロード。Codex、Claude Code、GitHub Copilot、Cursor Agent をコンテキスト・制御・追跡性とともに連携させます。"$json$::jsonb),
  ('ja', 'site.skip', $json$"本文へスキップ"$json$::jsonb),
  ('ja', 'site.nav.label', $json$"メインナビゲーション"$json$::jsonb),
  ('ja', 'site.nav.home', $json$"JayV ホーム"$json$::jsonb),
  ('ja', 'site.nav.features', $json$"機能"$json$::jsonb),
  ('ja', 'site.nav.downloads', $json$"ダウンロード"$json$::jsonb),
  ('ja', 'site.nav.how', $json$"しくみ"$json$::jsonb),
  ('ja', 'site.nav.releases', $json$"リリース"$json$::jsonb),
  ('ja', 'site.nav.signIn', $json$"ログイン"$json$::jsonb),
  ('ja', 'site.nav.signUp', $json$"アカウント作成"$json$::jsonb),
  ('ja', 'site.nav.account', $json$"{email} でログイン中"$json$::jsonb),
  ('ja', 'site.hero.eyebrow', $json$"開発のためのローカル・オーケストレーション"$json$::jsonb),
  ('ja', 'site.hero.title', $json$"AI エージェントを、"$json$::jsonb),
  ('ja', 'site.hero.highlight', $json$"手の内に。"$json$::jsonb),
  ('ja', 'site.hero.copy', $json$"JayV は Codex、Claude Code、GitHub Copilot、Cursor Agent をプロジェクトごとのコンテキストで連携させます。Jev が依頼を理解し、ルートを選び、回答を検証して、作業を集中した追跡可能な状態に保ちます。"$json$::jsonb),
  ('ja', 'site.hero.download', $json$"お使いのシステム用にダウンロード"$json$::jsonb),
  ('ja', 'site.hero.downloadFor', $json$"{system} 用にダウンロード"$json$::jsonb),
  ('ja', 'site.hero.notes', $json$"リリースノート"$json$::jsonb),
  ('ja', 'site.hero.release', $json$"バージョン {version} · Windows、macOS、Linux"$json$::jsonb),
  ('ja', 'site.hero.releaseUnknown', $json$"Windows、macOS、Linux"$json$::jsonb),
  ('ja', 'site.hero.agents', $json$"連携しているエージェント"$json$::jsonb),
  ('ja', 'site.trace.label', $json$"JayV が分析したルートの例"$json$::jsonb),
  ('ja', 'site.trace.request', $json$"認証フローをレビューして"$json$::jsonb),
  ('ja', 'site.trace.indexing', $json$"プロジェクトのコンテキストをインデックス中…"$json$::jsonb),
  ('ja', 'site.trace.entry', $json$"入力を確認済み"$json$::jsonb),
  ('ja', 'site.trace.scope', $json$"規模: 中程度の変更"$json$::jsonb),
  ('ja', 'site.trace.agent', $json$"エージェント"$json$::jsonb),
  ('ja', 'site.trace.model', $json$"モデル"$json$::jsonb),
  ('ja', 'site.trace.mode', $json$"モード"$json$::jsonb),
  ('ja', 'site.trace.role', $json$"役割"$json$::jsonb),
  ('ja', 'site.trace.modeValue', $json$"計画"$json$::jsonb),
  ('ja', 'site.trace.roleValue', $json$"レビュアー"$json$::jsonb),
  ('ja', 'site.trace.exit', $json$"出力を検証済み"$json$::jsonb),
  ('ja', 'site.trace.saved', $json$"ターンを保存 · コンテキストを保持"$json$::jsonb),
  ('ja', 'site.features.kicker', $json$"JayV でできること"$json$::jsonb),
  ('ja', 'site.features.title', $json$"すべての作業をひとつの場所で。"$json$::jsonb),
  ('ja', 'site.features.note', $json$"プロジェクト、チャット、ルート、使用量をネイティブのインターフェースにまとめ、必要なときは技術的な詳細も確認できます。"$json$::jsonb),
  ('ja', 'site.features.agents.tag', $json$"エージェント"$json$::jsonb),
  ('ja', 'site.features.agents.title', $json$"4 つのエージェント、1 つの画面"$json$::jsonb),
  ('ja', 'site.features.agents.detail', $json$"各エージェントのモデル、権限、ツール、サンドボックス、推論の強さを、コマンドを手で書き換えずに設定できます。"$json$::jsonb),
  ('ja', 'site.features.routing.tag', $json$"ルーティング"$json$::jsonb),
  ('ja', 'site.features.routing.title', $json$"ルートは依頼に合わせて"$json$::jsonb),
  ('ja', 'site.features.routing.detail', $json$"意図、規模、開発者のレベルをもとに、Jev がエージェント、モデル、実行モード、役割を選びます。"$json$::jsonb),
  ('ja', 'site.features.trace.tag', $json$"追跡性"$json$::jsonb),
  ('ja', 'site.features.trace.title', $json$"すべてのターンに履歴"$json$::jsonb),
  ('ja', 'site.features.trace.detail', $json$"依頼は実行前に保存されます。ターンコードがメッセージと入口・出口ゲートの判定を結びつけます。"$json$::jsonb),
  ('ja', 'site.features.account.tag', $json$"アカウント"$json$::jsonb),
  ('ja', 'site.features.account.title', $json$"プロフィール、アクティビティ、上限"$json$::jsonb),
  ('ja', 'site.features.account.detail', $json$"レベル、過去 30 日間のアクティビティ、各エージェントが報告する使用量を 1 か所で確認できます。"$json$::jsonb),
  ('ja', 'site.downloads.kicker', $json$"公式ダウンロード"$json$::jsonb),
  ('ja', 'site.downloads.title', $json$"システムを選択"$json$::jsonb),
  ('ja', 'site.downloads.note', $json$"リンクは公式リポジトリで公開されたファイルを指します。新しいバージョンが出ると JayV がお知らせします。"$json$::jsonb),
  ('ja', 'site.downloads.recommended', $json$"お使いのシステム"$json$::jsonb),
  ('ja', 'site.downloads.windows.arch', $json$"64 ビット · Windows 10 以降"$json$::jsonb),
  ('ja', 'site.downloads.mac.arch', $json$"Apple Silicon または Intel"$json$::jsonb),
  ('ja', 'site.downloads.exe', $json$"EXE インストーラー"$json$::jsonb),
  ('ja', 'site.downloads.msi', $json$"MSI パッケージ"$json$::jsonb),
  ('ja', 'site.downloads.dmgArm', $json$"Apple Silicon 用 DMG"$json$::jsonb),
  ('ja', 'site.downloads.dmgIntel', $json$"Intel 用 DMG"$json$::jsonb),
  ('ja', 'site.downloads.missing', $json$"パッケージはまだありません。"$json$::jsonb),
  ('ja', 'site.downloads.meta', $json$"JayV v{version} · {date} 公開"$json$::jsonb),
  ('ja', 'site.downloads.metaUnknown', $json$"GitHub の最新バージョン"$json$::jsonb),
  ('ja', 'site.how.kicker', $json$"コンテキストのある流れ"$json$::jsonb),
  ('ja', 'site.how.title', $json$"コンテキストから回答まで、各ステップに役割があります。"$json$::jsonb),
  ('ja', 'site.how.detail', $json$"JayV はインデックスをプロジェクトのフォルダーに向け、会話を保持し、各ターンの進め方を記録します。"$json$::jsonb),
  ('ja', 'site.how.step1.title', $json$"正しいコンテキストを開く"$json$::jsonb),
  ('ja', 'site.how.step1.detail', $json$"ファイル、インデックス、履歴はプロジェクトとチャットごとに分離されます。"$json$::jsonb),
  ('ja', 'site.how.step2.title', $json$"記録して確認する"$json$::jsonb),
  ('ja', 'site.how.step2.detail', $json$"ターンは実行前に保存され、入口ゲートが依頼を確認します。"$json$::jsonb),
  ('ja', 'site.how.step3.title', $json$"ルートを選ぶ"$json$::jsonb),
  ('ja', 'site.how.step3.detail', $json$"作業は規模に合ったエージェント、モデル、モード、役割に渡されます。"$json$::jsonb),
  ('ja', 'site.how.step4.title', $json$"出力を検証する"$json$::jsonb),
  ('ja', 'site.how.step4.detail', $json$"回答は出口ゲートを通って戻り、判定と履歴を確認できます。"$json$::jsonb),
  ('ja', 'site.privacy.title', $json$"コンテキストは正しいプロジェクトに。"$json$::jsonb),
  ('ja', 'site.privacy.detail', $json$"プロジェクト、チャット、設定はローカルに保存され、プロバイダーのキーは保存後にマスクされます。"$json$::jsonb),
  ('ja', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('ja', 'site.register.title', $json$"JayV アカウントを作成"$json$::jsonb),
  ('ja', 'site.register.subtitle', $json$"同じアカウントで、どのマシンのアプリにもこのサイトにもログインできます。"$json$::jsonb),
  ('ja', 'site.callback.working', $json$"ログインを完了しています…"$json$::jsonb),
  ('ja', 'site.callback.failed', $json$"このリンクは使えませんでした。新しいリンクを受け取るか、もう一度ログインしてください。"$json$::jsonb),
  ('ja', 'site.session.failed', $json$"サイトでセッションを開けませんでした。もう一度お試しください。"$json$::jsonb),
  ('ja', 'site.admin.signIn', $json$"このページを開くには、システム管理者のアカウントでログインしてください。"$json$::jsonb),
  ('ja', 'site.notFound.title', $json$"ページが見つかりません"$json$::jsonb),
  ('ja', 'site.notFound.detail', $json$"このアドレスは JayV のサイトにありません。"$json$::jsonb),
  ('ja', 'site.notFound.home', $json$"ホームへ戻る"$json$::jsonb),
  ('de', 'site.meta.title', $json$"JayV — KI-Agenten unter Kontrolle"$json$::jsonb),
  ('de', 'site.meta.description', $json$"Lade JayV für Windows, macOS oder Linux herunter. Koordiniere Codex, Claude Code, GitHub Copilot und Cursor Agent mit Kontext, Kontrolle und Nachvollziehbarkeit."$json$::jsonb),
  ('de', 'site.skip', $json$"Zum Inhalt springen"$json$::jsonb),
  ('de', 'site.nav.label', $json$"Hauptnavigation"$json$::jsonb),
  ('de', 'site.nav.home', $json$"JayV, Startseite"$json$::jsonb),
  ('de', 'site.nav.features', $json$"Funktionen"$json$::jsonb),
  ('de', 'site.nav.downloads', $json$"Downloads"$json$::jsonb),
  ('de', 'site.nav.how', $json$"So funktioniert's"$json$::jsonb),
  ('de', 'site.nav.releases', $json$"Versionen"$json$::jsonb),
  ('de', 'site.nav.signIn', $json$"Anmelden"$json$::jsonb),
  ('de', 'site.nav.signUp', $json$"Konto erstellen"$json$::jsonb),
  ('de', 'site.nav.account', $json$"Angemeldet als {email}"$json$::jsonb),
  ('de', 'site.hero.eyebrow', $json$"Lokale Orchestrierung für die Entwicklung"$json$::jsonb),
  ('de', 'site.hero.title', $json$"KI-Agenten,"$json$::jsonb),
  ('de', 'site.hero.highlight', $json$"unter Kontrolle."$json$::jsonb),
  ('de', 'site.hero.copy', $json$"JayV koordiniert Codex, Claude Code, GitHub Copilot und Cursor Agent im Kontext jedes Projekts. Jev versteht die Anfrage, wählt die Route und prüft die Antwort, damit die Arbeit fokussiert und nachvollziehbar bleibt."$json$::jsonb),
  ('de', 'site.hero.download', $json$"Für mein System herunterladen"$json$::jsonb),
  ('de', 'site.hero.downloadFor', $json$"Für {system} herunterladen"$json$::jsonb),
  ('de', 'site.hero.notes', $json$"Versionshinweise"$json$::jsonb),
  ('de', 'site.hero.release', $json$"Version {version} · Windows, macOS und Linux"$json$::jsonb),
  ('de', 'site.hero.releaseUnknown', $json$"Windows, macOS und Linux"$json$::jsonb),
  ('de', 'site.hero.agents', $json$"Integrierte Agenten"$json$::jsonb),
  ('de', 'site.trace.label', $json$"Beispiel einer von JayV analysierten Route"$json$::jsonb),
  ('de', 'site.trace.request', $json$"prüfe den Anmeldeablauf"$json$::jsonb),
  ('de', 'site.trace.indexing', $json$"Projektkontext wird indiziert…"$json$::jsonb),
  ('de', 'site.trace.entry', $json$"Eingabe geprüft"$json$::jsonb),
  ('de', 'site.trace.scope', $json$"Umfang: mittlere Änderung"$json$::jsonb),
  ('de', 'site.trace.agent', $json$"Agent"$json$::jsonb),
  ('de', 'site.trace.model', $json$"Modell"$json$::jsonb),
  ('de', 'site.trace.mode', $json$"Modus"$json$::jsonb),
  ('de', 'site.trace.role', $json$"Rolle"$json$::jsonb),
  ('de', 'site.trace.modeValue', $json$"Planung"$json$::jsonb),
  ('de', 'site.trace.roleValue', $json$"Reviewer"$json$::jsonb),
  ('de', 'site.trace.exit', $json$"Ausgabe geprüft"$json$::jsonb),
  ('de', 'site.trace.saved', $json$"Runde gespeichert · Kontext erhalten"$json$::jsonb),
  ('de', 'site.features.kicker', $json$"Was JayV bietet"$json$::jsonb),
  ('de', 'site.features.title', $json$"Ein Ort, um die ganze Arbeit zu koordinieren."$json$::jsonb),
  ('de', 'site.features.note', $json$"Projekte, Chats, Routen und Verbrauch in einer nativen Oberfläche, mit technischen Details, wenn du sie brauchst."$json$::jsonb),
  ('de', 'site.features.agents.tag', $json$"Agenten"$json$::jsonb),
  ('de', 'site.features.agents.title', $json$"Vier Agenten, eine Oberfläche"$json$::jsonb),
  ('de', 'site.features.agents.detail', $json$"Lege Modelle, Berechtigungen, Werkzeuge, Sandbox und Aufwand jedes Agenten fest, ohne Befehle von Hand zu bearbeiten."$json$::jsonb),
  ('de', 'site.features.routing.tag', $json$"Routing"$json$::jsonb),
  ('de', 'site.features.routing.title', $json$"Die Route folgt der Anfrage"$json$::jsonb),
  ('de', 'site.features.routing.detail', $json$"Absicht, Umfang und das Niveau der Entwicklerin oder des Entwicklers helfen Jev, Agent, Modell, Ausführungsmodus und Rolle zu wählen."$json$::jsonb),
  ('de', 'site.features.trace.tag', $json$"Nachvollziehbarkeit"$json$::jsonb),
  ('de', 'site.features.trace.title', $json$"Jede Runde hat eine Geschichte"$json$::jsonb),
  ('de', 'site.features.trace.detail', $json$"Die Anfrage wird vor der Ausführung gespeichert. Rundencodes verknüpfen die Nachrichten mit den Urteilen der Eingangs- und Ausgangsprüfung."$json$::jsonb),
  ('de', 'site.features.account.tag', $json$"Konto"$json$::jsonb),
  ('de', 'site.features.account.title', $json$"Profil, Aktivität und Limits"$json$::jsonb),
  ('de', 'site.features.account.detail', $json$"Verfolge dein Niveau, die Aktivität der letzten 30 Tage und die von jedem Agenten gemeldete Nutzung an einem Ort."$json$::jsonb),
  ('de', 'site.downloads.kicker', $json$"Offizielle Downloads"$json$::jsonb),
  ('de', 'site.downloads.title', $json$"Wähle dein System"$json$::jsonb),
  ('de', 'site.downloads.note', $json$"Die Links führen zu den Dateien im offiziellen Repository. JayV meldet sich, wenn eine neue Version erscheint."$json$::jsonb),
  ('de', 'site.downloads.recommended', $json$"Dein System"$json$::jsonb),
  ('de', 'site.downloads.windows.arch', $json$"64 Bit · Windows 10 oder neuer"$json$::jsonb),
  ('de', 'site.downloads.mac.arch', $json$"Apple Silicon oder Intel"$json$::jsonb),
  ('de', 'site.downloads.exe', $json$"EXE-Installer"$json$::jsonb),
  ('de', 'site.downloads.msi', $json$"MSI-Paket"$json$::jsonb),
  ('de', 'site.downloads.dmgArm', $json$"Apple-Silicon-DMG"$json$::jsonb),
  ('de', 'site.downloads.dmgIntel', $json$"Intel-DMG"$json$::jsonb),
  ('de', 'site.downloads.missing', $json$"Paket noch nicht verfügbar."$json$::jsonb),
  ('de', 'site.downloads.meta', $json$"JayV v{version} · veröffentlicht am {date}"$json$::jsonb),
  ('de', 'site.downloads.metaUnknown', $json$"Neueste Version auf GitHub"$json$::jsonb),
  ('de', 'site.how.kicker', $json$"Ablauf mit Kontext"$json$::jsonb),
  ('de', 'site.how.title', $json$"Vom Kontext zur Antwort hat jeder Schritt eine Aufgabe."$json$::jsonb),
  ('de', 'site.how.detail', $json$"JayV richtet den Index auf den Projektordner aus, behält das Gespräch und hält fest, wie jede Runde verlief."$json$::jsonb),
  ('de', 'site.how.step1.title', $json$"Öffnet den richtigen Kontext"$json$::jsonb),
  ('de', 'site.how.step1.detail', $json$"Dateien, Index und Verlauf sind pro Projekt und pro Chat getrennt."$json$::jsonb),
  ('de', 'site.how.step2.title', $json$"Speichert und prüft"$json$::jsonb),
  ('de', 'site.how.step2.detail', $json$"Die Runde wird vor der Ausführung gespeichert, und die Eingangsprüfung bewertet die Anfrage."$json$::jsonb),
  ('de', 'site.how.step3.title', $json$"Wählt die Route"$json$::jsonb),
  ('de', 'site.how.step3.detail', $json$"Die Arbeit geht an den Agenten, das Modell, den Modus und die Rolle, die zum Umfang passen."$json$::jsonb),
  ('de', 'site.how.step4.title', $json$"Prüft die Ausgabe"$json$::jsonb),
  ('de', 'site.how.step4.detail', $json$"Die Antwort kommt durch die Ausgangsprüfung zurück, mit Entscheidung und Verlauf im Blick."$json$::jsonb),
  ('de', 'site.privacy.title', $json$"Der Kontext bleibt im richtigen Projekt."$json$::jsonb),
  ('de', 'site.privacy.detail', $json$"Projekte, Chats und Einstellungen bleiben lokal; Anbieterschlüssel werden nach dem Speichern maskiert."$json$::jsonb),
  ('de', 'site.footer.rights', $json$"© {year} JayV"$json$::jsonb),
  ('de', 'site.register.title', $json$"Erstelle dein JayV-Konto"$json$::jsonb),
  ('de', 'site.register.subtitle', $json$"Mit demselben Konto meldest du dich in der App auf jedem Rechner und auf dieser Website an."$json$::jsonb),
  ('de', 'site.callback.working', $json$"Anmeldung wird abgeschlossen…"$json$::jsonb),
  ('de', 'site.callback.failed', $json$"Dieser Link hat nicht funktioniert. Fordere einen neuen an oder melde dich erneut an."$json$::jsonb),
  ('de', 'site.session.failed', $json$"Deine Sitzung auf der Website konnte nicht geöffnet werden. Versuche es erneut."$json$::jsonb),
  ('de', 'site.admin.signIn', $json$"Melde dich mit dem Administratorkonto des Systems an, um diese Seite zu öffnen."$json$::jsonb),
  ('de', 'site.notFound.title', $json$"Seite nicht gefunden"$json$::jsonb),
  ('de', 'site.notFound.detail', $json$"Diese Adresse gibt es auf der JayV-Website nicht."$json$::jsonb),
  ('de', 'site.notFound.home', $json$"Zur Startseite"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
