-- App 0.87.0 / site 2.7.0: uso por ambiente nas Estatísticas e na Administração, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'usage.environmentNote', $json$"Gasto no ambiente {name}. O limite do plano de cada agente é compartilhado por todos os ambientes."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.environmentUsage.title', $json$"Uso por ambiente"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.environmentUsage.detail', $json$"As Estatísticas agora dizem a qual ambiente o gasto pertence, e a página Usuários do site mostra os projetos, chats e o uso de cada conta em cada ambiente."$json$::jsonb),
  ('pt-BR', 'site.users.section.environments', $json$"Por ambiente"$json$::jsonb),
  ('pt-BR', 'site.users.environmentsNote', $json$"O que a conta tem em cada ambiente: o Pessoal e um por organização. O uso é dos últimos 30 dias."$json$::jsonb),
  ('pt-BR', 'site.users.environment.personal', $json$"Pessoal"$json$::jsonb),
  ('en', 'usage.environmentNote', $json$"Spending in the {name} environment. The limit of each agent's plan is shared by all environments."$json$::jsonb),
  ('en', 'whatsNew.item.environmentUsage.title', $json$"Usage by environment"$json$::jsonb),
  ('en', 'whatsNew.item.environmentUsage.detail', $json$"Statistics now say which environment the spending belongs to, and the site's Users page shows each account's projects, chats and usage in every environment."$json$::jsonb),
  ('en', 'site.users.section.environments', $json$"By environment"$json$::jsonb),
  ('en', 'site.users.environmentsNote', $json$"What the account has in each environment: Personal and one per organization. Usage is the last 30 days."$json$::jsonb),
  ('en', 'site.users.environment.personal', $json$"Personal"$json$::jsonb),
  ('es', 'usage.environmentNote', $json$"Gasto en el entorno {name}. El límite del plan de cada agente se comparte entre todos los entornos."$json$::jsonb),
  ('es', 'whatsNew.item.environmentUsage.title', $json$"Uso por entorno"$json$::jsonb),
  ('es', 'whatsNew.item.environmentUsage.detail', $json$"Las Estadísticas ahora indican a qué entorno pertenece el gasto, y la página Usuarios del sitio muestra los proyectos, chats y el uso de cada cuenta en cada entorno."$json$::jsonb),
  ('es', 'site.users.section.environments', $json$"Por entorno"$json$::jsonb),
  ('es', 'site.users.environmentsNote', $json$"Lo que tiene la cuenta en cada entorno: el Personal y uno por organización. El uso es de los últimos 30 días."$json$::jsonb),
  ('es', 'site.users.environment.personal', $json$"Personal"$json$::jsonb),
  ('fr', 'usage.environmentNote', $json$"Dépenses dans l'environnement {name}. La limite du forfait de chaque agent est partagée par tous les environnements."$json$::jsonb),
  ('fr', 'whatsNew.item.environmentUsage.title', $json$"Usage par environnement"$json$::jsonb),
  ('fr', 'whatsNew.item.environmentUsage.detail', $json$"Les Statistiques indiquent maintenant à quel environnement appartient la dépense, et la page Utilisateurs du site montre les projets, chats et l'usage de chaque compte dans chaque environnement."$json$::jsonb),
  ('fr', 'site.users.section.environments', $json$"Par environnement"$json$::jsonb),
  ('fr', 'site.users.environmentsNote', $json$"Ce que le compte a dans chaque environnement : le Personnel et un par organisation. L'usage couvre les 30 derniers jours."$json$::jsonb),
  ('fr', 'site.users.environment.personal', $json$"Personnel"$json$::jsonb),
  ('de', 'usage.environmentNote', $json$"Ausgaben in der Umgebung {name}. Das Limit des Tarifs jedes Agenten wird von allen Umgebungen geteilt."$json$::jsonb),
  ('de', 'whatsNew.item.environmentUsage.title', $json$"Nutzung pro Umgebung"$json$::jsonb),
  ('de', 'whatsNew.item.environmentUsage.detail', $json$"Die Statistiken zeigen jetzt, zu welcher Umgebung die Ausgaben gehören, und die Seite Benutzer der Website zeigt Projekte, Chats und Nutzung jedes Kontos in jeder Umgebung."$json$::jsonb),
  ('de', 'site.users.section.environments', $json$"Pro Umgebung"$json$::jsonb),
  ('de', 'site.users.environmentsNote', $json$"Was das Konto in jeder Umgebung hat: Persönlich und eine pro Organisation. Die Nutzung gilt für die letzten 30 Tage."$json$::jsonb),
  ('de', 'site.users.environment.personal', $json$"Persönlich"$json$::jsonb),
  ('ru', 'usage.environmentNote', $json$"Расход в среде {name}. Лимит тарифа каждого агента общий для всех сред."$json$::jsonb),
  ('ru', 'whatsNew.item.environmentUsage.title', $json$"Расход по средам"$json$::jsonb),
  ('ru', 'whatsNew.item.environmentUsage.detail', $json$"Статистика теперь показывает, к какой среде относится расход, а страница «Пользователи» на сайте показывает проекты, чаты и расход каждой учётной записи в каждой среде."$json$::jsonb),
  ('ru', 'site.users.section.environments', $json$"По средам"$json$::jsonb),
  ('ru', 'site.users.environmentsNote', $json$"Что есть у учётной записи в каждой среде: «Личное» и по одной на организацию. Расход за последние 30 дней."$json$::jsonb),
  ('ru', 'site.users.environment.personal', $json$"Личное"$json$::jsonb),
  ('zh-CN', 'usage.environmentNote', $json$"{name} 环境中的花费。每个代理的套餐额度由所有环境共享。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.environmentUsage.title', $json$"按环境查看用量"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.environmentUsage.detail', $json$"统计现在会说明花费属于哪个环境，网站的“用户”页面会显示每个账户在每个环境中的项目、聊天和用量。"$json$::jsonb),
  ('zh-CN', 'site.users.section.environments', $json$"按环境"$json$::jsonb),
  ('zh-CN', 'site.users.environmentsNote', $json$"账户在每个环境中拥有的内容：个人环境和每个组织一个环境。用量为最近 30 天。"$json$::jsonb),
  ('zh-CN', 'site.users.environment.personal', $json$"个人"$json$::jsonb),
  ('ja', 'usage.environmentNote', $json$"{name} 環境での支出。各エージェントのプランの上限は、すべての環境で共有されます。"$json$::jsonb),
  ('ja', 'whatsNew.item.environmentUsage.title', $json$"環境ごとの使用量"$json$::jsonb),
  ('ja', 'whatsNew.item.environmentUsage.detail', $json$"統計に、支出がどの環境のものかが表示されるようになり、サイトのユーザーページには各アカウントのプロジェクト、チャット、使用量が環境ごとに表示されます。"$json$::jsonb),
  ('ja', 'site.users.section.environments', $json$"環境別"$json$::jsonb),
  ('ja', 'site.users.environmentsNote', $json$"アカウントが各環境に持つもの：個人と、組織ごとに 1 つ。使用量は直近 30 日です。"$json$::jsonb),
  ('ja', 'site.users.environment.personal', $json$"個人"$json$::jsonb),
  ('hi', 'usage.environmentNote', $json$"{name} परिवेश में खर्च। हर एजेंट के प्लान की सीमा सभी परिवेशों में साझा है।"$json$::jsonb),
  ('hi', 'whatsNew.item.environmentUsage.title', $json$"परिवेश के अनुसार उपयोग"$json$::jsonb),
  ('hi', 'whatsNew.item.environmentUsage.detail', $json$"आँकड़े अब बताते हैं कि खर्च किस परिवेश का है, और साइट का उपयोगकर्ता पेज हर खाते के प्रोजेक्ट, चैट और उपयोग को हर परिवेश में दिखाता है।"$json$::jsonb),
  ('hi', 'site.users.section.environments', $json$"परिवेश के अनुसार"$json$::jsonb),
  ('hi', 'site.users.environmentsNote', $json$"खाते के पास हर परिवेश में क्या है: व्यक्तिगत और हर संगठन के लिए एक। उपयोग पिछले 30 दिनों का है।"$json$::jsonb),
  ('hi', 'site.users.environment.personal', $json$"व्यक्तिगत"$json$::jsonb),
  ('ar', 'usage.environmentNote', $json$"الإنفاق في بيئة {name}. حد خطة كل وكيل مشترك بين كل البيئات."$json$::jsonb),
  ('ar', 'whatsNew.item.environmentUsage.title', $json$"الاستخدام حسب البيئة"$json$::jsonb),
  ('ar', 'whatsNew.item.environmentUsage.detail', $json$"تذكر الإحصاءات الآن البيئة التي يعود إليها الإنفاق، وتعرض صفحة المستخدمين في الموقع مشاريع كل حساب ومحادثاته واستخدامه في كل بيئة."$json$::jsonb),
  ('ar', 'site.users.section.environments', $json$"حسب البيئة"$json$::jsonb),
  ('ar', 'site.users.environmentsNote', $json$"ما لدى الحساب في كل بيئة: الشخصية وواحدة لكل مؤسسة. الاستخدام لآخر 30 يومًا."$json$::jsonb),
  ('ar', 'site.users.environment.personal', $json$"شخصي"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
