-- v0.39.0: página Sistema.
--
-- Só textos: o painel de saúde (servidor e agentes), a versão com a busca de
-- atualização, os registros do roteador, os caminhos com copiar e mostrar na
-- pasta, o total de linhas do banco, o "Copiar diagnóstico" e os itens da
-- janela "Novidades" desta versão.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'db.total', $json${"one": "{rows} linha no total", "other": "{rows} linhas no total"}$json$::jsonb),
  ('pt-BR', 'system.eyebrow', $json$"Diagnóstico"$json$::jsonb),
  ('pt-BR', 'system.description', $json$"Como o JayV está neste computador: servidor e agentes, versão, números do motor, arquivos e o banco local."$json$::jsonb),
  ('pt-BR', 'system.reload', $json$"Conferir de novo"$json$::jsonb),
  ('pt-BR', 'system.copy', $json$"Copiar diagnóstico"$json$::jsonb),
  ('pt-BR', 'system.copied', $json$"Copiado para a área de transferência."$json$::jsonb),
  ('pt-BR', 'system.health', $json$"Saúde"$json$::jsonb),
  ('pt-BR', 'system.server', $json$"Servidor"$json$::jsonb),
  ('pt-BR', 'system.link.online', $json$"conectado"$json$::jsonb),
  ('pt-BR', 'system.link.offline', $json$"sem conexão"$json$::jsonb),
  ('pt-BR', 'system.link.expired', $json$"sessão vencida"$json$::jsonb),
  ('pt-BR', 'system.link.signedOut', $json$"fora da conta"$json$::jsonb),
  ('pt-BR', 'system.agent.off', $json$"não configurado"$json$::jsonb),
  ('pt-BR', 'system.agent.missing', $json$"não encontrado"$json$::jsonb),
  ('pt-BR', 'system.agent.silent', $json$"encontrado, mas não responde"$json$::jsonb),
  ('pt-BR', 'system.agents.configure', $json$"Configurar agentes"$json$::jsonb),
  ('pt-BR', 'system.update.check', $json$"Procurar atualizações"$json$::jsonb),
  ('pt-BR', 'system.update.available', $json$"A versão {version} está disponível."$json$::jsonb),
  ('pt-BR', 'system.update.running', $json$"Atualizando…"$json$::jsonb),
  ('pt-BR', 'system.whatsNew', $json$"Novidades"$json$::jsonb),
  ('pt-BR', 'system.released', $json${"one": "Lançada em {date} com {count} mudança.", "other": "Lançada em {date} com {count} mudanças."}$json$::jsonb),
  ('pt-BR', 'system.router', $json$"Registros do roteador"$json$::jsonb),
  ('pt-BR', 'system.router.hint', $json$"Respostas com que o roteador aprendeu a escolher um modelo para cada tipo de pedido."$json$::jsonb),
  ('pt-BR', 'system.files', $json$"Arquivos"$json$::jsonb),
  ('pt-BR', 'system.files.config', $json$"Configuração"$json$::jsonb),
  ('pt-BR', 'system.files.database', $json$"Banco de dados"$json$::jsonb),
  ('pt-BR', 'system.path.copy', $json$"Copiar caminho"$json$::jsonb),
  ('pt-BR', 'system.path.reveal', $json$"Mostrar na pasta"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.systemHealth.title', $json$"Página Sistema mais clara"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.systemHealth.detail', $json$"A página Sistema agora abre com um painel de saúde: se o servidor está conectado e em dia, e se cada agente está instalado e respondendo, com a versão dele. Ao lado ficam a versão instalada, um botão para procurar atualizações e as novidades. Os números do motor incluem quantas respostas o roteador usou para aprender, e o banco local mostra cada tabela com uma barra do tamanho dela."$json$::jsonb),
  ('pt-BR', 'whatsNew.item.systemDiagnostics.title', $json$"Copiar diagnóstico"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.systemDiagnostics.detail', $json$"Copiar diagnóstico põe na área de transferência a versão, o sistema, a conexão, os agentes, os números do motor e o tamanho das tabelas, pronto para colar num pedido de ajuda. Não leva conteúdo de chat, chaves nem tokens. Os caminhos da configuração e do banco podem ser copiados ou mostrados na pasta."$json$::jsonb),
  ('en', 'db.total', $json${"one": "{rows} row in total", "other": "{rows} rows in total"}$json$::jsonb),
  ('en', 'system.eyebrow', $json$"Diagnostics"$json$::jsonb),
  ('en', 'system.description', $json$"How JayV is doing on this computer: server and agents, version, engine numbers, files and the local database."$json$::jsonb),
  ('en', 'system.reload', $json$"Check again"$json$::jsonb),
  ('en', 'system.copy', $json$"Copy diagnostics"$json$::jsonb),
  ('en', 'system.copied', $json$"Copied to the clipboard."$json$::jsonb),
  ('en', 'system.health', $json$"Health"$json$::jsonb),
  ('en', 'system.server', $json$"Server"$json$::jsonb),
  ('en', 'system.link.online', $json$"online"$json$::jsonb),
  ('en', 'system.link.offline', $json$"offline"$json$::jsonb),
  ('en', 'system.link.expired', $json$"session expired"$json$::jsonb),
  ('en', 'system.link.signedOut', $json$"signed out"$json$::jsonb),
  ('en', 'system.agent.off', $json$"not configured"$json$::jsonb),
  ('en', 'system.agent.missing', $json$"not found"$json$::jsonb),
  ('en', 'system.agent.silent', $json$"found, but it does not answer"$json$::jsonb),
  ('en', 'system.agents.configure', $json$"Configure agents"$json$::jsonb),
  ('en', 'system.update.check', $json$"Check for updates"$json$::jsonb),
  ('en', 'system.update.available', $json$"Version {version} is available."$json$::jsonb),
  ('en', 'system.update.running', $json$"Updating…"$json$::jsonb),
  ('en', 'system.whatsNew', $json$"What's new"$json$::jsonb),
  ('en', 'system.released', $json${"one": "Released on {date} with {count} change.", "other": "Released on {date} with {count} changes."}$json$::jsonb),
  ('en', 'system.router', $json$"Router records"$json$::jsonb),
  ('en', 'system.router.hint', $json$"Answers the router learned from to pick a model for each kind of request."$json$::jsonb),
  ('en', 'system.files', $json$"Files"$json$::jsonb),
  ('en', 'system.files.config', $json$"Configuration"$json$::jsonb),
  ('en', 'system.files.database', $json$"Database"$json$::jsonb),
  ('en', 'system.path.copy', $json$"Copy path"$json$::jsonb),
  ('en', 'system.path.reveal', $json$"Show in folder"$json$::jsonb),
  ('en', 'whatsNew.item.systemHealth.title', $json$"A clearer System page"$json$::jsonb),
  ('en', 'whatsNew.item.systemHealth.detail', $json$"The System page now opens with a health panel: whether the server is online and in sync, and whether each agent is installed and answering, with its version. Next to it are the installed version, a button to check for updates and the release notes. The engine numbers include how many answers the router learned from, and the local database shows every table with a bar for its size."$json$::jsonb),
  ('en', 'whatsNew.item.systemDiagnostics.title', $json$"Copy diagnostics"$json$::jsonb),
  ('en', 'whatsNew.item.systemDiagnostics.detail', $json$"Copy diagnostics puts the version, system, connection, agents, engine numbers and table sizes on the clipboard, ready to paste into a request for help. It holds no chat content, keys or tokens. The configuration and database paths can be copied or shown in their folder."$json$::jsonb),
  ('es', 'db.total', $json${"one": "{rows} fila en total", "other": "{rows} filas en total"}$json$::jsonb),
  ('es', 'system.eyebrow', $json$"Diagnóstico"$json$::jsonb),
  ('es', 'system.description', $json$"Cómo está JayV en este equipo: servidor y agentes, versión, números del motor, archivos y la base de datos local."$json$::jsonb),
  ('es', 'system.reload', $json$"Comprobar de nuevo"$json$::jsonb),
  ('es', 'system.copy', $json$"Copiar diagnóstico"$json$::jsonb),
  ('es', 'system.copied', $json$"Copiado al portapapeles."$json$::jsonb),
  ('es', 'system.health', $json$"Salud"$json$::jsonb),
  ('es', 'system.server', $json$"Servidor"$json$::jsonb),
  ('es', 'system.link.online', $json$"conectado"$json$::jsonb),
  ('es', 'system.link.offline', $json$"sin conexión"$json$::jsonb),
  ('es', 'system.link.expired', $json$"sesión vencida"$json$::jsonb),
  ('es', 'system.link.signedOut', $json$"sin sesión"$json$::jsonb),
  ('es', 'system.agent.off', $json$"no configurado"$json$::jsonb),
  ('es', 'system.agent.missing', $json$"no encontrado"$json$::jsonb),
  ('es', 'system.agent.silent', $json$"encontrado, pero no responde"$json$::jsonb),
  ('es', 'system.agents.configure', $json$"Configurar agentes"$json$::jsonb),
  ('es', 'system.update.check', $json$"Buscar actualizaciones"$json$::jsonb),
  ('es', 'system.update.available', $json$"La versión {version} está disponible."$json$::jsonb),
  ('es', 'system.update.running', $json$"Actualizando…"$json$::jsonb),
  ('es', 'system.whatsNew', $json$"Novedades"$json$::jsonb),
  ('es', 'system.released', $json${"one": "Publicada el {date} con {count} cambio.", "other": "Publicada el {date} con {count} cambios."}$json$::jsonb),
  ('es', 'system.router', $json$"Registros del enrutador"$json$::jsonb),
  ('es', 'system.router.hint', $json$"Respuestas con las que el enrutador aprendió a elegir un modelo para cada tipo de petición."$json$::jsonb),
  ('es', 'system.files', $json$"Archivos"$json$::jsonb),
  ('es', 'system.files.config', $json$"Configuración"$json$::jsonb),
  ('es', 'system.files.database', $json$"Base de datos"$json$::jsonb),
  ('es', 'system.path.copy', $json$"Copiar ruta"$json$::jsonb),
  ('es', 'system.path.reveal', $json$"Mostrar en la carpeta"$json$::jsonb),
  ('es', 'whatsNew.item.systemHealth.title', $json$"Una página Sistema más clara"$json$::jsonb),
  ('es', 'whatsNew.item.systemHealth.detail', $json$"La página Sistema ahora abre con un panel de salud: si el servidor está conectado y al día, y si cada agente está instalado y responde, con su versión. Al lado están la versión instalada, un botón para buscar actualizaciones y las novedades. Los números del motor incluyen de cuántas respuestas aprendió el enrutador, y la base de datos local muestra cada tabla con una barra de su tamaño."$json$::jsonb),
  ('es', 'whatsNew.item.systemDiagnostics.title', $json$"Copiar diagnóstico"$json$::jsonb),
  ('es', 'whatsNew.item.systemDiagnostics.detail', $json$"Copiar diagnóstico pone en el portapapeles la versión, el sistema, la conexión, los agentes, los números del motor y el tamaño de las tablas, listo para pegar en una petición de ayuda. No incluye contenido de chats, claves ni tokens. Las rutas de la configuración y de la base de datos se pueden copiar o mostrar en su carpeta."$json$::jsonb),
  ('fr', 'db.total', $json${"one": "{rows} ligne au total", "other": "{rows} lignes au total"}$json$::jsonb),
  ('fr', 'system.eyebrow', $json$"Diagnostic"$json$::jsonb),
  ('fr', 'system.description', $json$"L'état de JayV sur cet ordinateur : serveur et agents, version, chiffres du moteur, fichiers et base de données locale."$json$::jsonb),
  ('fr', 'system.reload', $json$"Vérifier à nouveau"$json$::jsonb),
  ('fr', 'system.copy', $json$"Copier le diagnostic"$json$::jsonb),
  ('fr', 'system.copied', $json$"Copié dans le presse-papiers."$json$::jsonb),
  ('fr', 'system.health', $json$"Santé"$json$::jsonb),
  ('fr', 'system.server', $json$"Serveur"$json$::jsonb),
  ('fr', 'system.link.online', $json$"connecté"$json$::jsonb),
  ('fr', 'system.link.offline', $json$"hors ligne"$json$::jsonb),
  ('fr', 'system.link.expired', $json$"session expirée"$json$::jsonb),
  ('fr', 'system.link.signedOut', $json$"déconnecté"$json$::jsonb),
  ('fr', 'system.agent.off', $json$"non configuré"$json$::jsonb),
  ('fr', 'system.agent.missing', $json$"introuvable"$json$::jsonb),
  ('fr', 'system.agent.silent', $json$"trouvé, mais ne répond pas"$json$::jsonb),
  ('fr', 'system.agents.configure', $json$"Configurer les agents"$json$::jsonb),
  ('fr', 'system.update.check', $json$"Rechercher des mises à jour"$json$::jsonb),
  ('fr', 'system.update.available', $json$"La version {version} est disponible."$json$::jsonb),
  ('fr', 'system.update.running', $json$"Mise à jour…"$json$::jsonb),
  ('fr', 'system.whatsNew', $json$"Nouveautés"$json$::jsonb),
  ('fr', 'system.released', $json${"one": "Publiée le {date} avec {count} changement.", "other": "Publiée le {date} avec {count} changements."}$json$::jsonb),
  ('fr', 'system.router', $json$"Données du routeur"$json$::jsonb),
  ('fr', 'system.router.hint', $json$"Réponses dont le routeur s'est servi pour apprendre à choisir un modèle pour chaque type de demande."$json$::jsonb),
  ('fr', 'system.files', $json$"Fichiers"$json$::jsonb),
  ('fr', 'system.files.config', $json$"Configuration"$json$::jsonb),
  ('fr', 'system.files.database', $json$"Base de données"$json$::jsonb),
  ('fr', 'system.path.copy', $json$"Copier le chemin"$json$::jsonb),
  ('fr', 'system.path.reveal', $json$"Afficher dans le dossier"$json$::jsonb),
  ('fr', 'whatsNew.item.systemHealth.title', $json$"Une page Système plus claire"$json$::jsonb),
  ('fr', 'whatsNew.item.systemHealth.detail', $json$"La page Système s'ouvre maintenant sur un panneau de santé : le serveur est-il connecté et à jour, et chaque agent est-il installé et répond-il, avec sa version. À côté se trouvent la version installée, un bouton pour rechercher des mises à jour et les nouveautés. Les chiffres du moteur indiquent de combien de réponses le routeur a appris, et la base de données locale montre chaque table avec une barre de sa taille."$json$::jsonb),
  ('fr', 'whatsNew.item.systemDiagnostics.title', $json$"Copier le diagnostic"$json$::jsonb),
  ('fr', 'whatsNew.item.systemDiagnostics.detail', $json$"Copier le diagnostic place dans le presse-papiers la version, le système, la connexion, les agents, les chiffres du moteur et la taille des tables, prêt à coller dans une demande d'aide. Il ne contient aucun contenu de chat, clé ni jeton. Les chemins de la configuration et de la base de données peuvent être copiés ou affichés dans leur dossier."$json$::jsonb),
  ('de', 'db.total', $json${"one": "{rows} Zeile insgesamt", "other": "{rows} Zeilen insgesamt"}$json$::jsonb),
  ('de', 'system.eyebrow', $json$"Diagnose"$json$::jsonb),
  ('de', 'system.description', $json$"Wie es JayV auf diesem Computer geht: Server und Agents, Version, Zahlen der Engine, Dateien und die lokale Datenbank."$json$::jsonb),
  ('de', 'system.reload', $json$"Erneut prüfen"$json$::jsonb),
  ('de', 'system.copy', $json$"Diagnose kopieren"$json$::jsonb),
  ('de', 'system.copied', $json$"In die Zwischenablage kopiert."$json$::jsonb),
  ('de', 'system.health', $json$"Zustand"$json$::jsonb),
  ('de', 'system.server', $json$"Server"$json$::jsonb),
  ('de', 'system.link.online', $json$"verbunden"$json$::jsonb),
  ('de', 'system.link.offline', $json$"offline"$json$::jsonb),
  ('de', 'system.link.expired', $json$"Sitzung abgelaufen"$json$::jsonb),
  ('de', 'system.link.signedOut', $json$"abgemeldet"$json$::jsonb),
  ('de', 'system.agent.off', $json$"nicht eingerichtet"$json$::jsonb),
  ('de', 'system.agent.missing', $json$"nicht gefunden"$json$::jsonb),
  ('de', 'system.agent.silent', $json$"gefunden, antwortet aber nicht"$json$::jsonb),
  ('de', 'system.agents.configure', $json$"Agents einrichten"$json$::jsonb),
  ('de', 'system.update.check', $json$"Nach Updates suchen"$json$::jsonb),
  ('de', 'system.update.available', $json$"Version {version} ist verfügbar."$json$::jsonb),
  ('de', 'system.update.running', $json$"Wird aktualisiert…"$json$::jsonb),
  ('de', 'system.whatsNew', $json$"Neuerungen"$json$::jsonb),
  ('de', 'system.released', $json${"one": "Veröffentlicht am {date} mit {count} Änderung.", "other": "Veröffentlicht am {date} mit {count} Änderungen."}$json$::jsonb),
  ('de', 'system.router', $json$"Router-Einträge"$json$::jsonb),
  ('de', 'system.router.hint', $json$"Antworten, aus denen der Router gelernt hat, für jede Art von Anfrage ein Modell zu wählen."$json$::jsonb),
  ('de', 'system.files', $json$"Dateien"$json$::jsonb),
  ('de', 'system.files.config', $json$"Konfiguration"$json$::jsonb),
  ('de', 'system.files.database', $json$"Datenbank"$json$::jsonb),
  ('de', 'system.path.copy', $json$"Pfad kopieren"$json$::jsonb),
  ('de', 'system.path.reveal', $json$"Im Ordner zeigen"$json$::jsonb),
  ('de', 'whatsNew.item.systemHealth.title', $json$"Eine klarere Systemseite"$json$::jsonb),
  ('de', 'whatsNew.item.systemHealth.detail', $json$"Die Systemseite beginnt jetzt mit einer Zustandsübersicht: ob der Server verbunden und synchron ist und ob jeder Agent installiert ist und antwortet, mit seiner Version. Daneben stehen die installierte Version, ein Knopf zum Suchen nach Updates und die Neuerungen. Die Zahlen der Engine zeigen, aus wie vielen Antworten der Router gelernt hat, und die lokale Datenbank zeigt jede Tabelle mit einem Balken für ihre Größe."$json$::jsonb),
  ('de', 'whatsNew.item.systemDiagnostics.title', $json$"Diagnose kopieren"$json$::jsonb),
  ('de', 'whatsNew.item.systemDiagnostics.detail', $json$"Diagnose kopieren legt Version, System, Verbindung, Agents, Zahlen der Engine und Tabellengrößen in die Zwischenablage, bereit zum Einfügen in eine Hilfeanfrage. Sie enthält keine Chatinhalte, Schlüssel oder Tokens. Die Pfade von Konfiguration und Datenbank lassen sich kopieren oder im Ordner zeigen."$json$::jsonb),
  ('ja', 'db.total', $json${"other": "合計 {rows} 行"}$json$::jsonb),
  ('ja', 'system.eyebrow', $json$"診断"$json$::jsonb),
  ('ja', 'system.description', $json$"このコンピューターでの JayV の状態：サーバーとエージェント、バージョン、エンジンの数値、ファイル、ローカルデータベース。"$json$::jsonb),
  ('ja', 'system.reload', $json$"再確認"$json$::jsonb),
  ('ja', 'system.copy', $json$"診断をコピー"$json$::jsonb),
  ('ja', 'system.copied', $json$"クリップボードにコピーしました。"$json$::jsonb),
  ('ja', 'system.health', $json$"状態"$json$::jsonb),
  ('ja', 'system.server', $json$"サーバー"$json$::jsonb),
  ('ja', 'system.link.online', $json$"接続中"$json$::jsonb),
  ('ja', 'system.link.offline', $json$"オフライン"$json$::jsonb),
  ('ja', 'system.link.expired', $json$"セッション期限切れ"$json$::jsonb),
  ('ja', 'system.link.signedOut', $json$"ログアウト中"$json$::jsonb),
  ('ja', 'system.agent.off', $json$"未設定"$json$::jsonb),
  ('ja', 'system.agent.missing', $json$"見つかりません"$json$::jsonb),
  ('ja', 'system.agent.silent', $json$"見つかりましたが応答しません"$json$::jsonb),
  ('ja', 'system.agents.configure', $json$"エージェントを設定"$json$::jsonb),
  ('ja', 'system.update.check', $json$"アップデートを確認"$json$::jsonb),
  ('ja', 'system.update.available', $json$"バージョン {version} が利用できます。"$json$::jsonb),
  ('ja', 'system.update.running', $json$"更新中…"$json$::jsonb),
  ('ja', 'system.whatsNew', $json$"新機能"$json$::jsonb),
  ('ja', 'system.released', $json${"other": "{date} に {count} 件の変更とともにリリース。"}$json$::jsonb),
  ('ja', 'system.router', $json$"ルーター記録"$json$::jsonb),
  ('ja', 'system.router.hint', $json$"ルーターが依頼の種類ごとにモデルを選ぶために学習した回答の数。"$json$::jsonb),
  ('ja', 'system.files', $json$"ファイル"$json$::jsonb),
  ('ja', 'system.files.config', $json$"設定"$json$::jsonb),
  ('ja', 'system.files.database', $json$"データベース"$json$::jsonb),
  ('ja', 'system.path.copy', $json$"パスをコピー"$json$::jsonb),
  ('ja', 'system.path.reveal', $json$"フォルダーで表示"$json$::jsonb),
  ('ja', 'whatsNew.item.systemHealth.title', $json$"わかりやすくなったシステムページ"$json$::jsonb),
  ('ja', 'whatsNew.item.systemHealth.detail', $json$"システムページは状態パネルから始まるようになりました。サーバーが接続され同期しているか、各エージェントがインストールされ応答しているかをバージョンとともに表示します。その横には、インストール済みのバージョン、アップデートを確認するボタン、新機能があります。エンジンの数値にはルーターが学習に使った回答数が加わり、ローカルデータベースは各テーブルをサイズのバーとともに表示します。"$json$::jsonb),
  ('ja', 'whatsNew.item.systemDiagnostics.title', $json$"診断をコピー"$json$::jsonb),
  ('ja', 'whatsNew.item.systemDiagnostics.detail', $json$"「診断をコピー」は、バージョン、システム、接続、エージェント、エンジンの数値、テーブルのサイズをクリップボードに入れ、サポート依頼にそのまま貼り付けられるようにします。チャットの内容、キー、トークンは含みません。設定とデータベースのパスはコピーしたり、フォルダーで表示したりできます。"$json$::jsonb),
  ('zh-CN', 'db.total', $json${"other": "共 {rows} 行"}$json$::jsonb),
  ('zh-CN', 'system.eyebrow', $json$"诊断"$json$::jsonb),
  ('zh-CN', 'system.description', $json$"JayV 在这台电脑上的情况：服务器和智能体、版本、引擎数据、文件和本地数据库。"$json$::jsonb),
  ('zh-CN', 'system.reload', $json$"重新检查"$json$::jsonb),
  ('zh-CN', 'system.copy', $json$"复制诊断信息"$json$::jsonb),
  ('zh-CN', 'system.copied', $json$"已复制到剪贴板。"$json$::jsonb),
  ('zh-CN', 'system.health', $json$"状态"$json$::jsonb),
  ('zh-CN', 'system.server', $json$"服务器"$json$::jsonb),
  ('zh-CN', 'system.link.online', $json$"已连接"$json$::jsonb),
  ('zh-CN', 'system.link.offline', $json$"离线"$json$::jsonb),
  ('zh-CN', 'system.link.expired', $json$"会话已过期"$json$::jsonb),
  ('zh-CN', 'system.link.signedOut', $json$"未登录"$json$::jsonb),
  ('zh-CN', 'system.agent.off', $json$"未配置"$json$::jsonb),
  ('zh-CN', 'system.agent.missing', $json$"未找到"$json$::jsonb),
  ('zh-CN', 'system.agent.silent', $json$"已找到，但没有响应"$json$::jsonb),
  ('zh-CN', 'system.agents.configure', $json$"配置智能体"$json$::jsonb),
  ('zh-CN', 'system.update.check', $json$"检查更新"$json$::jsonb),
  ('zh-CN', 'system.update.available', $json$"{version} 版本可用。"$json$::jsonb),
  ('zh-CN', 'system.update.running', $json$"正在更新…"$json$::jsonb),
  ('zh-CN', 'system.whatsNew', $json$"新功能"$json$::jsonb),
  ('zh-CN', 'system.released', $json${"other": "发布于 {date}，包含 {count} 项变更。"}$json$::jsonb),
  ('zh-CN', 'system.router', $json$"路由记录"$json$::jsonb),
  ('zh-CN', 'system.router.hint', $json$"路由器为每类请求选择模型时学习过的回答数量。"$json$::jsonb),
  ('zh-CN', 'system.files', $json$"文件"$json$::jsonb),
  ('zh-CN', 'system.files.config', $json$"配置"$json$::jsonb),
  ('zh-CN', 'system.files.database', $json$"数据库"$json$::jsonb),
  ('zh-CN', 'system.path.copy', $json$"复制路径"$json$::jsonb),
  ('zh-CN', 'system.path.reveal', $json$"在文件夹中显示"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.systemHealth.title', $json$"更清晰的系统页面"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.systemHealth.detail', $json$"系统页面现在以状态面板开头：服务器是否已连接并同步，每个智能体是否已安装并能响应，以及它的版本。旁边是已安装的版本、检查更新的按钮和新功能。引擎数据包括路由器学习过的回答数量，本地数据库会用条形图显示每张表的大小。"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.systemDiagnostics.title', $json$"复制诊断信息"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.systemDiagnostics.detail', $json$"“复制诊断信息”会把版本、系统、连接、智能体、引擎数据和表的大小放到剪贴板，方便粘贴到求助请求中。其中不包含聊天内容、密钥或令牌。配置和数据库的路径可以复制，也可以在文件夹中显示。"$json$::jsonb),
  ('ru', 'db.total', $json${"one": "Всего {rows} строка", "few": "Всего {rows} строки", "many": "Всего {rows} строк", "other": "Всего {rows} строки"}$json$::jsonb),
  ('ru', 'system.eyebrow', $json$"Диагностика"$json$::jsonb),
  ('ru', 'system.description', $json$"Как JayV работает на этом компьютере: сервер и агенты, версия, показатели движка, файлы и локальная база данных."$json$::jsonb),
  ('ru', 'system.reload', $json$"Проверить снова"$json$::jsonb),
  ('ru', 'system.copy', $json$"Скопировать диагностику"$json$::jsonb),
  ('ru', 'system.copied', $json$"Скопировано в буфер обмена."$json$::jsonb),
  ('ru', 'system.health', $json$"Состояние"$json$::jsonb),
  ('ru', 'system.server', $json$"Сервер"$json$::jsonb),
  ('ru', 'system.link.online', $json$"на связи"$json$::jsonb),
  ('ru', 'system.link.offline', $json$"нет связи"$json$::jsonb),
  ('ru', 'system.link.expired', $json$"сессия истекла"$json$::jsonb),
  ('ru', 'system.link.signedOut', $json$"вход не выполнен"$json$::jsonb),
  ('ru', 'system.agent.off', $json$"не настроен"$json$::jsonb),
  ('ru', 'system.agent.missing', $json$"не найден"$json$::jsonb),
  ('ru', 'system.agent.silent', $json$"найден, но не отвечает"$json$::jsonb),
  ('ru', 'system.agents.configure', $json$"Настроить агентов"$json$::jsonb),
  ('ru', 'system.update.check', $json$"Проверить обновления"$json$::jsonb),
  ('ru', 'system.update.available', $json$"Доступна версия {version}."$json$::jsonb),
  ('ru', 'system.update.running', $json$"Обновление…"$json$::jsonb),
  ('ru', 'system.whatsNew', $json$"Что нового"$json$::jsonb),
  ('ru', 'system.released', $json${"one": "Выпущена {date}, {count} изменение.", "few": "Выпущена {date}, {count} изменения.", "many": "Выпущена {date}, {count} изменений.", "other": "Выпущена {date}, {count} изменения."}$json$::jsonb),
  ('ru', 'system.router', $json$"Записи маршрутизатора"$json$::jsonb),
  ('ru', 'system.router.hint', $json$"Ответы, на которых маршрутизатор научился выбирать модель для каждого типа запроса."$json$::jsonb),
  ('ru', 'system.files', $json$"Файлы"$json$::jsonb),
  ('ru', 'system.files.config', $json$"Конфигурация"$json$::jsonb),
  ('ru', 'system.files.database', $json$"База данных"$json$::jsonb),
  ('ru', 'system.path.copy', $json$"Копировать путь"$json$::jsonb),
  ('ru', 'system.path.reveal', $json$"Показать в папке"$json$::jsonb),
  ('ru', 'whatsNew.item.systemHealth.title', $json$"Более понятная страница «Система»"$json$::jsonb),
  ('ru', 'whatsNew.item.systemHealth.detail', $json$"Страница «Система» теперь начинается с панели состояния: на связи ли сервер и всё ли синхронизировано, установлен ли каждый агент и отвечает ли он, с его версией. Рядом — установленная версия, кнопка проверки обновлений и список нового. Среди показателей движка теперь есть число ответов, на которых учился маршрутизатор, а локальная база данных показывает каждую таблицу с полосой её размера."$json$::jsonb),
  ('ru', 'whatsNew.item.systemDiagnostics.title', $json$"Скопировать диагностику"$json$::jsonb),
  ('ru', 'whatsNew.item.systemDiagnostics.detail', $json$"«Скопировать диагностику» помещает в буфер обмена версию, систему, подключение, агентов, показатели движка и размеры таблиц — готово для вставки в запрос о помощи. Содержимое чатов, ключи и токены туда не попадают. Пути к конфигурации и базе данных можно скопировать или показать в папке."$json$::jsonb),
  ('ar', 'db.total', $json${"zero": "لا صفوف", "one": "صف واحد في المجموع", "two": "صفان في المجموع", "few": "{rows} صفوف في المجموع", "many": "{rows} صفًا في المجموع", "other": "{rows} صف في المجموع"}$json$::jsonb),
  ('ar', 'system.eyebrow', $json$"التشخيص"$json$::jsonb),
  ('ar', 'system.description', $json$"حال JayV على هذا الكمبيوتر: الخادم والوكلاء، والإصدار، وأرقام المحرك، والملفات، وقاعدة البيانات المحلية."$json$::jsonb),
  ('ar', 'system.reload', $json$"تحقق مجددًا"$json$::jsonb),
  ('ar', 'system.copy', $json$"انسخ التشخيص"$json$::jsonb),
  ('ar', 'system.copied', $json$"نُسخ إلى الحافظة."$json$::jsonb),
  ('ar', 'system.health', $json$"الحالة"$json$::jsonb),
  ('ar', 'system.server', $json$"الخادم"$json$::jsonb),
  ('ar', 'system.link.online', $json$"متصل"$json$::jsonb),
  ('ar', 'system.link.offline', $json$"غير متصل"$json$::jsonb),
  ('ar', 'system.link.expired', $json$"انتهت الجلسة"$json$::jsonb),
  ('ar', 'system.link.signedOut', $json$"غير مسجّل الدخول"$json$::jsonb),
  ('ar', 'system.agent.off', $json$"غير مُعدّ"$json$::jsonb),
  ('ar', 'system.agent.missing', $json$"غير موجود"$json$::jsonb),
  ('ar', 'system.agent.silent', $json$"موجود لكنه لا يستجيب"$json$::jsonb),
  ('ar', 'system.agents.configure', $json$"إعداد الوكلاء"$json$::jsonb),
  ('ar', 'system.update.check', $json$"التحقق من التحديثات"$json$::jsonb),
  ('ar', 'system.update.available', $json$"الإصدار {version} متاح."$json$::jsonb),
  ('ar', 'system.update.running', $json$"جارٍ التحديث…"$json$::jsonb),
  ('ar', 'system.whatsNew', $json$"الجديد"$json$::jsonb),
  ('ar', 'system.released', $json${"zero": "صدر في {date} دون تغييرات.", "one": "صدر في {date} مع تغيير واحد.", "two": "صدر في {date} مع تغييرين.", "few": "صدر في {date} مع {count} تغييرات.", "many": "صدر في {date} مع {count} تغييرًا.", "other": "صدر في {date} مع {count} تغيير."}$json$::jsonb),
  ('ar', 'system.router', $json$"سجلات الموجّه"$json$::jsonb),
  ('ar', 'system.router.hint', $json$"الإجابات التي تعلّم منها الموجّه اختيار نموذج لكل نوع من الطلبات."$json$::jsonb),
  ('ar', 'system.files', $json$"الملفات"$json$::jsonb),
  ('ar', 'system.files.config', $json$"الإعدادات"$json$::jsonb),
  ('ar', 'system.files.database', $json$"قاعدة البيانات"$json$::jsonb),
  ('ar', 'system.path.copy', $json$"انسخ المسار"$json$::jsonb),
  ('ar', 'system.path.reveal', $json$"اعرض في المجلد"$json$::jsonb),
  ('ar', 'whatsNew.item.systemHealth.title', $json$"صفحة نظام أوضح"$json$::jsonb),
  ('ar', 'whatsNew.item.systemHealth.detail', $json$"تبدأ صفحة النظام الآن بلوحة الحالة: هل الخادم متصل ومتزامن، وهل كل وكيل مثبّت ويستجيب، مع إصداره. وبجانبها الإصدار المثبّت وزر للتحقق من التحديثات والجديد. وتتضمن أرقام المحرك عدد الإجابات التي تعلّم منها الموجّه، وتعرض قاعدة البيانات المحلية كل جدول مع شريط بحجمه."$json$::jsonb),
  ('ar', 'whatsNew.item.systemDiagnostics.title', $json$"انسخ التشخيص"$json$::jsonb),
  ('ar', 'whatsNew.item.systemDiagnostics.detail', $json$"يضع «انسخ التشخيص» في الحافظة الإصدار والنظام والاتصال والوكلاء وأرقام المحرك وأحجام الجداول، جاهزًا للصق في طلب مساعدة. ولا يتضمن محتوى المحادثات ولا المفاتيح ولا الرموز. ويمكن نسخ مساري الإعدادات وقاعدة البيانات أو عرضهما في المجلد."$json$::jsonb),
  ('hi', 'db.total', $json${"one": "कुल {rows} पंक्ति", "other": "कुल {rows} पंक्तियाँ"}$json$::jsonb),
  ('hi', 'system.eyebrow', $json$"निदान"$json$::jsonb),
  ('hi', 'system.description', $json$"इस कंप्यूटर पर JayV की स्थिति: सर्वर और एजेंट, वर्ज़न, इंजन के आँकड़े, फ़ाइलें और लोकल डेटाबेस।"$json$::jsonb),
  ('hi', 'system.reload', $json$"फिर से जाँचें"$json$::jsonb),
  ('hi', 'system.copy', $json$"निदान कॉपी करें"$json$::jsonb),
  ('hi', 'system.copied', $json$"क्लिपबोर्ड पर कॉपी हो गया।"$json$::jsonb),
  ('hi', 'system.health', $json$"स्थिति"$json$::jsonb),
  ('hi', 'system.server', $json$"सर्वर"$json$::jsonb),
  ('hi', 'system.link.online', $json$"कनेक्टेड"$json$::jsonb),
  ('hi', 'system.link.offline', $json$"ऑफ़लाइन"$json$::jsonb),
  ('hi', 'system.link.expired', $json$"सेशन ख़त्म"$json$::jsonb),
  ('hi', 'system.link.signedOut', $json$"साइन आउट"$json$::jsonb),
  ('hi', 'system.agent.off', $json$"कॉन्फ़िगर नहीं"$json$::jsonb),
  ('hi', 'system.agent.missing', $json$"नहीं मिला"$json$::jsonb),
  ('hi', 'system.agent.silent', $json$"मिला, पर जवाब नहीं देता"$json$::jsonb),
  ('hi', 'system.agents.configure', $json$"एजेंट कॉन्फ़िगर करें"$json$::jsonb),
  ('hi', 'system.update.check', $json$"अपडेट जाँचें"$json$::jsonb),
  ('hi', 'system.update.available', $json$"वर्ज़न {version} उपलब्ध है।"$json$::jsonb),
  ('hi', 'system.update.running', $json$"अपडेट हो रहा है…"$json$::jsonb),
  ('hi', 'system.whatsNew', $json$"नया क्या है"$json$::jsonb),
  ('hi', 'system.released', $json${"one": "{date} को {count} बदलाव के साथ जारी।", "other": "{date} को {count} बदलावों के साथ जारी।"}$json$::jsonb),
  ('hi', 'system.router', $json$"राउटर रिकॉर्ड"$json$::jsonb),
  ('hi', 'system.router.hint', $json$"वे जवाब जिनसे राउटर ने हर तरह के अनुरोध के लिए मॉडल चुनना सीखा।"$json$::jsonb),
  ('hi', 'system.files', $json$"फ़ाइलें"$json$::jsonb),
  ('hi', 'system.files.config', $json$"कॉन्फ़िगरेशन"$json$::jsonb),
  ('hi', 'system.files.database', $json$"डेटाबेस"$json$::jsonb),
  ('hi', 'system.path.copy', $json$"पाथ कॉपी करें"$json$::jsonb),
  ('hi', 'system.path.reveal', $json$"फ़ोल्डर में दिखाएँ"$json$::jsonb),
  ('hi', 'whatsNew.item.systemHealth.title', $json$"ज़्यादा साफ़ सिस्टम पेज"$json$::jsonb),
  ('hi', 'whatsNew.item.systemHealth.detail', $json$"सिस्टम पेज अब एक स्थिति पैनल से शुरू होता है: सर्वर कनेक्टेड और सिंक है या नहीं, और हर एजेंट इंस्टॉल है और जवाब देता है या नहीं, उसके वर्ज़न के साथ। बगल में इंस्टॉल किया वर्ज़न, अपडेट जाँचने का बटन और नया क्या है। इंजन के आँकड़ों में यह भी है कि राउटर ने कितने जवाबों से सीखा, और लोकल डेटाबेस हर टेबल को उसके आकार की पट्टी के साथ दिखाता है।"$json$::jsonb),
  ('hi', 'whatsNew.item.systemDiagnostics.title', $json$"निदान कॉपी करें"$json$::jsonb),
  ('hi', 'whatsNew.item.systemDiagnostics.detail', $json$"निदान कॉपी करें वर्ज़न, सिस्टम, कनेक्शन, एजेंट, इंजन के आँकड़े और टेबल का आकार क्लिपबोर्ड पर रखता है, मदद के अनुरोध में चिपकाने के लिए तैयार। इसमें चैट की सामग्री, कुंजियाँ या टोकन नहीं होते। कॉन्फ़िगरेशन और डेटाबेस के पाथ कॉपी किए जा सकते हैं या फ़ोल्डर में दिखाए जा सकते हैं।"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
