-- v0.69.0: chats gerais da organização separados dos projetos, janela do
-- Abrir chat e entradas na paleta de comandos.

insert into public.translations (locale, key, value) values
  ('pt-BR', 'orgChat.pick.title', $json$"Escolha um chat geral"$json$::jsonb),
  ('en', 'orgChat.pick.title', $json$"Choose a general chat"$json$::jsonb),
  ('es', 'orgChat.pick.title', $json$"Elige un chat general"$json$::jsonb),
  ('zh-CN', 'orgChat.pick.title', $json$"选择通用聊天"$json$::jsonb),
  ('hi', 'orgChat.pick.title', $json$"एक सामान्य चैट चुनें"$json$::jsonb),
  ('ar', 'orgChat.pick.title', $json$"اختر محادثة عامة"$json$::jsonb),
  ('fr', 'orgChat.pick.title', $json$"Choisissez un chat général"$json$::jsonb),
  ('ru', 'orgChat.pick.title', $json$"Выберите общий чат"$json$::jsonb),
  ('ja', 'orgChat.pick.title', $json$"総合チャットを選択"$json$::jsonb),
  ('de', 'orgChat.pick.title', $json$"Allgemeinen Chat wählen"$json$::jsonb),
  ('pt-BR', 'orgChat.pick.description', $json$"Os chats gerais de {org} trabalham em todos os repositórios de uma vez. Escolha um para continuar ou comece um novo."$json$::jsonb),
  ('en', 'orgChat.pick.description', $json$"General chats of {org} work on all its repositories at once. Pick one to continue or start a new one."$json$::jsonb),
  ('es', 'orgChat.pick.description', $json$"Los chats generales de {org} trabajan en todos sus repositorios a la vez. Elige uno para continuar o empieza uno nuevo."$json$::jsonb),
  ('zh-CN', 'orgChat.pick.description', $json$"{org} 的通用聊天会同时处理其所有仓库。选择一个继续，或新建一个。"$json$::jsonb),
  ('hi', 'orgChat.pick.description', $json$"{org} की सामान्य चैट उसके सभी रिपॉज़िटरी पर एक साथ काम करती हैं। जारी रखने के लिए एक चुनें या नई शुरू करें।"$json$::jsonb),
  ('ar', 'orgChat.pick.description', $json$"تعمل المحادثات العامة لـ {org} على جميع مستودعاتها دفعة واحدة. اختر واحدة للمتابعة أو ابدأ محادثة جديدة."$json$::jsonb),
  ('fr', 'orgChat.pick.description', $json$"Les chats généraux de {org} travaillent sur tous ses dépôts à la fois. Choisissez-en un pour continuer ou démarrez-en un nouveau."$json$::jsonb),
  ('ru', 'orgChat.pick.description', $json$"Общие чаты {org} работают сразу со всеми её репозиториями. Выберите чат, чтобы продолжить, или начните новый."$json$::jsonb),
  ('ja', 'orgChat.pick.description', $json$"{org} の総合チャットは、そのすべてのリポジトリを一度に扱います。続けるチャットを選ぶか、新しく始めてください。"$json$::jsonb),
  ('de', 'orgChat.pick.description', $json$"Allgemeine Chats von {org} arbeiten an allen Repositories gleichzeitig. Wähle einen zum Fortsetzen oder starte einen neuen."$json$::jsonb),
  ('pt-BR', 'orgChat.pick.new', $json$"Novo chat geral"$json$::jsonb),
  ('en', 'orgChat.pick.new', $json$"New general chat"$json$::jsonb),
  ('es', 'orgChat.pick.new', $json$"Nuevo chat general"$json$::jsonb),
  ('zh-CN', 'orgChat.pick.new', $json$"新建通用聊天"$json$::jsonb),
  ('hi', 'orgChat.pick.new', $json$"नई सामान्य चैट"$json$::jsonb),
  ('ar', 'orgChat.pick.new', $json$"محادثة عامة جديدة"$json$::jsonb),
  ('fr', 'orgChat.pick.new', $json$"Nouveau chat général"$json$::jsonb),
  ('ru', 'orgChat.pick.new', $json$"Новый общий чат"$json$::jsonb),
  ('ja', 'orgChat.pick.new', $json$"新しい総合チャット"$json$::jsonb),
  ('de', 'orgChat.pick.new', $json$"Neuer allgemeiner Chat"$json$::jsonb),
  ('pt-BR', 'projects.org.general', $json$"Chats gerais"$json$::jsonb),
  ('en', 'projects.org.general', $json$"General chats"$json$::jsonb),
  ('es', 'projects.org.general', $json$"Chats generales"$json$::jsonb),
  ('zh-CN', 'projects.org.general', $json$"通用聊天"$json$::jsonb),
  ('hi', 'projects.org.general', $json$"सामान्य चैट"$json$::jsonb),
  ('ar', 'projects.org.general', $json$"المحادثات العامة"$json$::jsonb),
  ('fr', 'projects.org.general', $json$"Chats généraux"$json$::jsonb),
  ('ru', 'projects.org.general', $json$"Общие чаты"$json$::jsonb),
  ('ja', 'projects.org.general', $json$"総合チャット"$json$::jsonb),
  ('de', 'projects.org.general', $json$"Allgemeine Chats"$json$::jsonb),
  ('pt-BR', 'projects.org.generalHint', $json$"Chats que trabalham em todos os repositórios da organização de uma vez."$json$::jsonb),
  ('en', 'projects.org.generalHint', $json$"Chats that work on all repositories of the organization at once."$json$::jsonb),
  ('es', 'projects.org.generalHint', $json$"Chats que trabajan en todos los repositorios de la organización a la vez."$json$::jsonb),
  ('zh-CN', 'projects.org.generalHint', $json$"同时处理组织所有仓库的聊天。"$json$::jsonb),
  ('hi', 'projects.org.generalHint', $json$"ऐसी चैट जो संगठन के सभी रिपॉज़िटरी पर एक साथ काम करती हैं।"$json$::jsonb),
  ('ar', 'projects.org.generalHint', $json$"محادثات تعمل على جميع مستودعات المؤسسة دفعة واحدة."$json$::jsonb),
  ('fr', 'projects.org.generalHint', $json$"Chats qui travaillent sur tous les dépôts de l’organisation à la fois."$json$::jsonb),
  ('ru', 'projects.org.generalHint', $json$"Чаты, которые работают сразу со всеми репозиториями организации."$json$::jsonb),
  ('ja', 'projects.org.generalHint', $json$"組織のすべてのリポジトリを一度に扱うチャットです。"$json$::jsonb),
  ('de', 'projects.org.generalHint', $json$"Chats, die an allen Repositories der Organisation gleichzeitig arbeiten."$json$::jsonb),
  ('pt-BR', 'projects.org.repositories', $json$"Projetos dos repositórios"$json$::jsonb),
  ('en', 'projects.org.repositories', $json$"Repository projects"$json$::jsonb),
  ('es', 'projects.org.repositories', $json$"Proyectos de los repositorios"$json$::jsonb),
  ('zh-CN', 'projects.org.repositories', $json$"仓库项目"$json$::jsonb),
  ('hi', 'projects.org.repositories', $json$"रिपॉज़िटरी प्रोजेक्ट"$json$::jsonb),
  ('ar', 'projects.org.repositories', $json$"مشاريع المستودعات"$json$::jsonb),
  ('fr', 'projects.org.repositories', $json$"Projets des dépôts"$json$::jsonb),
  ('ru', 'projects.org.repositories', $json$"Проекты репозиториев"$json$::jsonb),
  ('ja', 'projects.org.repositories', $json$"リポジトリのプロジェクト"$json$::jsonb),
  ('de', 'projects.org.repositories', $json$"Repository-Projekte"$json$::jsonb),
  ('pt-BR', 'palette.group.general', $json$"Chats gerais"$json$::jsonb),
  ('en', 'palette.group.general', $json$"General chats"$json$::jsonb),
  ('es', 'palette.group.general', $json$"Chats generales"$json$::jsonb),
  ('zh-CN', 'palette.group.general', $json$"通用聊天"$json$::jsonb),
  ('hi', 'palette.group.general', $json$"सामान्य चैट"$json$::jsonb),
  ('ar', 'palette.group.general', $json$"المحادثات العامة"$json$::jsonb),
  ('fr', 'palette.group.general', $json$"Chats généraux"$json$::jsonb),
  ('ru', 'palette.group.general', $json$"Общие чаты"$json$::jsonb),
  ('ja', 'palette.group.general', $json$"総合チャット"$json$::jsonb),
  ('de', 'palette.group.general', $json$"Allgemeine Chats"$json$::jsonb),
  ('pt-BR', 'palette.generalNew', $json$"Novo chat geral · {org}"$json$::jsonb),
  ('en', 'palette.generalNew', $json$"New general chat · {org}"$json$::jsonb),
  ('es', 'palette.generalNew', $json$"Nuevo chat general · {org}"$json$::jsonb),
  ('zh-CN', 'palette.generalNew', $json$"新建通用聊天 · {org}"$json$::jsonb),
  ('hi', 'palette.generalNew', $json$"नई सामान्य चैट · {org}"$json$::jsonb),
  ('ar', 'palette.generalNew', $json$"محادثة عامة جديدة · {org}"$json$::jsonb),
  ('fr', 'palette.generalNew', $json$"Nouveau chat général · {org}"$json$::jsonb),
  ('ru', 'palette.generalNew', $json$"Новый общий чат · {org}"$json$::jsonb),
  ('ja', 'palette.generalNew', $json$"新しい総合チャット · {org}"$json$::jsonb),
  ('de', 'palette.generalNew', $json$"Neuer allgemeiner Chat · {org}"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgGeneralChats.title', $json$"Chats gerais da organização, separados"$json$::jsonb),
  ('en', 'whatsNew.item.orgGeneralChats.title', $json$"General chats of the organization, kept apart"$json$::jsonb),
  ('es', 'whatsNew.item.orgGeneralChats.title', $json$"Chats generales de la organización, por separado"$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgGeneralChats.title', $json$"组织的通用聊天，单独列出"$json$::jsonb),
  ('hi', 'whatsNew.item.orgGeneralChats.title', $json$"संगठन की सामान्य चैट, अलग से"$json$::jsonb),
  ('ar', 'whatsNew.item.orgGeneralChats.title', $json$"المحادثات العامة للمؤسسة، منفصلة"$json$::jsonb),
  ('fr', 'whatsNew.item.orgGeneralChats.title', $json$"Chats généraux de l’organisation, à part"$json$::jsonb),
  ('ru', 'whatsNew.item.orgGeneralChats.title', $json$"Общие чаты организации — отдельно"$json$::jsonb),
  ('ja', 'whatsNew.item.orgGeneralChats.title', $json$"組織の総合チャットを分けて表示"$json$::jsonb),
  ('de', 'whatsNew.item.orgGeneralChats.title', $json$"Allgemeine Chats der Organisation, getrennt"$json$::jsonb),
  ('pt-BR', 'whatsNew.item.orgGeneralChats.detail', $json$"Na lista de projetos, os chats que trabalham em todos os repositórios de uma organização agora têm um bloco próprio, Chats gerais, separado dos projetos de cada repositório. O botão Abrir chat pergunta qual chat geral continuar, ou começa um novo, e a paleta de comandos (Ctrl+K) também os lista."$json$::jsonb),
  ('en', 'whatsNew.item.orgGeneralChats.detail', $json$"In the project list, the chats that work on all repositories of an organization now have their own General chats block, separate from the projects of each repository. The Open chat button asks which general chat to continue, or starts a new one, and the command palette (Ctrl+K) lists them too."$json$::jsonb),
  ('es', 'whatsNew.item.orgGeneralChats.detail', $json$"En la lista de proyectos, los chats que trabajan en todos los repositorios de una organización ahora tienen su propio bloque, Chats generales, separado de los proyectos de cada repositorio. El botón Abrir chat pregunta qué chat general continuar, o empieza uno nuevo, y la paleta de comandos (Ctrl+K) también los muestra."$json$::jsonb),
  ('zh-CN', 'whatsNew.item.orgGeneralChats.detail', $json$"在项目列表中，同时处理组织所有仓库的聊天现在有了独立的“通用聊天”区块，与各仓库的项目分开。“打开聊天”按钮会询问要继续哪个通用聊天，或新建一个，命令面板（Ctrl+K）中也能找到它们。"$json$::jsonb),
  ('hi', 'whatsNew.item.orgGeneralChats.detail', $json$"प्रोजेक्ट सूची में, किसी संगठन के सभी रिपॉज़िटरी पर काम करने वाली चैट का अब अपना अलग ब्लॉक, सामान्य चैट, है, जो हर रिपॉज़िटरी के प्रोजेक्ट से अलग है। चैट खोलें बटन पूछता है कि कौन-सी सामान्य चैट जारी रखनी है, या नई शुरू करता है, और कमांड पैलेट (Ctrl+K) में भी वे दिखती हैं।"$json$::jsonb),
  ('ar', 'whatsNew.item.orgGeneralChats.detail', $json$"في قائمة المشاريع، أصبح للمحادثات التي تعمل على جميع مستودعات المؤسسة قسمها الخاص، المحادثات العامة، منفصلًا عن مشاريع كل مستودع. يسأل زر فتح المحادثة عن المحادثة العامة التي تريد متابعتها، أو يبدأ محادثة جديدة، كما تعرضها لوحة الأوامر (Ctrl+K) أيضًا."$json$::jsonb),
  ('fr', 'whatsNew.item.orgGeneralChats.detail', $json$"Dans la liste des projets, les chats qui travaillent sur tous les dépôts d’une organisation ont désormais leur propre bloc, Chats généraux, séparé des projets de chaque dépôt. Le bouton Ouvrir le chat demande quel chat général poursuivre, ou en démarre un nouveau, et la palette de commandes (Ctrl+K) les liste aussi."$json$::jsonb),
  ('ru', 'whatsNew.item.orgGeneralChats.detail', $json$"В списке проектов чаты, работающие сразу со всеми репозиториями организации, теперь вынесены в отдельный блок «Общие чаты», отдельно от проектов каждого репозитория. Кнопка «Открыть чат» спрашивает, какой общий чат продолжить, или начинает новый, а палитра команд (Ctrl+K) тоже их показывает."$json$::jsonb),
  ('ja', 'whatsNew.item.orgGeneralChats.detail', $json$"プロジェクト一覧では、組織のすべてのリポジトリを扱うチャットが専用の「総合チャット」ブロックに分かれ、各リポジトリのプロジェクトと別に表示されます。「チャットを開く」ボタンは、続ける総合チャットを選ぶか新しく始めるかを尋ね、コマンドパレット（Ctrl+K）にも表示されます。"$json$::jsonb),
  ('de', 'whatsNew.item.orgGeneralChats.detail', $json$"In der Projektliste haben Chats, die an allen Repositories einer Organisation arbeiten, jetzt einen eigenen Block, Allgemeine Chats, getrennt von den Projekten der einzelnen Repositories. Die Schaltfläche Chat öffnen fragt, welcher allgemeine Chat fortgesetzt werden soll, oder startet einen neuen; auch die Befehlspalette (Ctrl+K) listet sie."$json$::jsonb),
  ('pt-BR', 'docs.orgChat.title', $json$"Chats gerais da organização"$json$::jsonb),
  ('en', 'docs.orgChat.title', $json$"Organization general chats"$json$::jsonb),
  ('es', 'docs.orgChat.title', $json$"Chats generales de la organización"$json$::jsonb),
  ('zh-CN', 'docs.orgChat.title', $json$"组织通用聊天"$json$::jsonb),
  ('hi', 'docs.orgChat.title', $json$"संगठन की सामान्य चैट"$json$::jsonb),
  ('ar', 'docs.orgChat.title', $json$"المحادثات العامة للمؤسسة"$json$::jsonb),
  ('fr', 'docs.orgChat.title', $json$"Chats généraux de l’organisation"$json$::jsonb),
  ('ru', 'docs.orgChat.title', $json$"Общие чаты организации"$json$::jsonb),
  ('ja', 'docs.orgChat.title', $json$"組織の総合チャット"$json$::jsonb),
  ('de', 'docs.orgChat.title', $json$"Allgemeine Chats der Organisation"$json$::jsonb),
  ('pt-BR', 'docs.orgChat.summary', $json$"Chats que trabalham em todos os repositórios de uma organização de uma vez, com o agente, o índice e a portaria enxergando todos. Aparecem separados dos chats de cada projeto de repositório."$json$::jsonb),
  ('en', 'docs.orgChat.summary', $json$"Chats that work on every repository of an organization at once, with the agent, the index and the gate seeing all of them. They are listed apart from the chats of each repository project."$json$::jsonb),
  ('es', 'docs.orgChat.summary', $json$"Chats que trabajan en todos los repositorios de una organización a la vez, con el agente, el índice y la portería viendo todos. Aparecen separados de los chats de cada proyecto de repositorio."$json$::jsonb),
  ('zh-CN', 'docs.orgChat.summary', $json$"同时处理组织所有仓库的聊天，代理、索引和门禁都能看到全部仓库。它们与各仓库项目的聊天分开列出。"$json$::jsonb),
  ('hi', 'docs.orgChat.summary', $json$"ऐसी चैट जो किसी संगठन के हर रिपॉज़िटरी पर एक साथ काम करती हैं; एजेंट, इंडेक्स और गेट सभी को देखते हैं। ये हर रिपॉज़िटरी प्रोजेक्ट की चैट से अलग सूचीबद्ध होती हैं।"$json$::jsonb),
  ('ar', 'docs.orgChat.summary', $json$"محادثات تعمل على كل مستودعات المؤسسة دفعة واحدة، ويرى الوكيل والفهرس والبوابة جميعها. وتُعرض منفصلة عن محادثات كل مشروع مستودع."$json$::jsonb),
  ('fr', 'docs.orgChat.summary', $json$"Chats qui travaillent sur tous les dépôts d’une organisation à la fois, l’agent, l’index et la porte les voyant tous. Ils sont listés à part des chats de chaque projet de dépôt."$json$::jsonb),
  ('ru', 'docs.orgChat.summary', $json$"Чаты, которые работают сразу со всеми репозиториями организации: агент, индекс и шлюз видят их все. Они показаны отдельно от чатов проектов отдельных репозиториев."$json$::jsonb),
  ('ja', 'docs.orgChat.summary', $json$"組織のすべてのリポジトリを一度に扱うチャットで、エージェント、インデックス、ゲートがすべてを参照します。各リポジトリのプロジェクトのチャットとは別に一覧表示されます。"$json$::jsonb),
  ('de', 'docs.orgChat.summary', $json$"Chats, die an allen Repositories einer Organisation gleichzeitig arbeiten; Agent, Index und Gate sehen alle. Sie werden getrennt von den Chats der einzelnen Repository-Projekte aufgelistet."$json$::jsonb),
  ('pt-BR', 'docs.orgChat.usage', $json$"Na página da organização ou na lista de projetos, clique em Abrir chat e escolha qual chat geral continuar ou comece um novo. Sem uma pasta da organização neste computador, o JayV pede uma primeiro. Também na paleta de comandos (Ctrl+K): Chats gerais."$json$::jsonb),
  ('en', 'docs.orgChat.usage', $json$"On the organization page or in the project list, click Open chat and choose which general chat to continue or start a new one. Without an organization folder on this computer, JayV asks for one first. Also in the command palette (Ctrl+K): General chats."$json$::jsonb),
  ('es', 'docs.orgChat.usage', $json$"En la página de la organización o en la lista de proyectos, haz clic en Abrir chat y elige qué chat general continuar o empieza uno nuevo. Sin una carpeta de la organización en este equipo, JayV pide una primero. También en la paleta de comandos (Ctrl+K): Chats generales."$json$::jsonb),
  ('zh-CN', 'docs.orgChat.usage', $json$"在组织页面或项目列表中，点击“打开聊天”，选择要继续的通用聊天或新建一个。如果此电脑上没有组织文件夹，JayV 会先请你选择。也可在命令面板（Ctrl+K）中找到：通用聊天。"$json$::jsonb),
  ('hi', 'docs.orgChat.usage', $json$"संगठन के पेज या प्रोजेक्ट सूची में चैट खोलें पर क्लिक करें और चुनें कि कौन-सी सामान्य चैट जारी रखनी है या नई शुरू करें। इस कंप्यूटर पर संगठन का फ़ोल्डर न हो तो JayV पहले एक माँगता है। कमांड पैलेट (Ctrl+K) में भी: सामान्य चैट।"$json$::jsonb),
  ('ar', 'docs.orgChat.usage', $json$"في صفحة المؤسسة أو قائمة المشاريع، انقر على فتح المحادثة واختر المحادثة العامة التي تريد متابعتها أو ابدأ محادثة جديدة. إن لم يكن لديك مجلد المؤسسة على هذا الحاسوب يطلب JayV مجلدًا أولًا. وتجدها أيضًا في لوحة الأوامر (Ctrl+K): المحادثات العامة."$json$::jsonb),
  ('fr', 'docs.orgChat.usage', $json$"Sur la page de l’organisation ou dans la liste des projets, cliquez sur Ouvrir le chat et choisissez quel chat général poursuivre, ou démarrez-en un nouveau. Sans dossier de l’organisation sur cet ordinateur, JayV en demande un d’abord. Aussi dans la palette de commandes (Ctrl+K) : Chats généraux."$json$::jsonb),
  ('ru', 'docs.orgChat.usage', $json$"На странице организации или в списке проектов нажмите «Открыть чат» и выберите общий чат, чтобы продолжить, или начните новый. Если на этом компьютере нет папки организации, JayV сначала попросит её выбрать. Также в палитре команд (Ctrl+K): «Общие чаты»."$json$::jsonb),
  ('ja', 'docs.orgChat.usage', $json$"組織のページまたはプロジェクト一覧で「チャットを開く」をクリックし、続ける総合チャットを選ぶか、新しく始めます。このコンピューターに組織のフォルダーがない場合、JayV が先に尋ねます。コマンドパレット（Ctrl+K）の「総合チャット」からも開けます。"$json$::jsonb),
  ('de', 'docs.orgChat.usage', $json$"Klicke auf der Organisationsseite oder in der Projektliste auf Chat öffnen und wähle, welcher allgemeine Chat fortgesetzt werden soll, oder starte einen neuen. Ohne Organisationsordner auf diesem Computer fragt JayV zuerst danach. Auch in der Befehlspalette (Ctrl+K): Allgemeine Chats."$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
