-- Formulário de várias perguntas na caixa de escrita, nos dez idiomas.
insert into public.translations (locale, key, value) values
  ('pt-BR', 'ask.form.send', $json$"Enviar respostas"$json$::jsonb),
  ('pt-BR', 'ask.form.other', $json$"Ou responda com suas palavras…"$json$::jsonb),
  ('pt-BR', 'ask.form.answer', $json$"Sua resposta…"$json$::jsonb),
  ('en', 'ask.form.send', $json$"Send answers"$json$::jsonb),
  ('en', 'ask.form.other', $json$"Or answer in your own words…"$json$::jsonb),
  ('en', 'ask.form.answer', $json$"Your answer…"$json$::jsonb),
  ('es', 'ask.form.send', $json$"Enviar respuestas"$json$::jsonb),
  ('es', 'ask.form.other', $json$"O responde con tus palabras…"$json$::jsonb),
  ('es', 'ask.form.answer', $json$"Tu respuesta…"$json$::jsonb),
  ('zh-CN', 'ask.form.send', $json$"发送回答"$json$::jsonb),
  ('zh-CN', 'ask.form.other', $json$"或用你自己的话回答…"$json$::jsonb),
  ('zh-CN', 'ask.form.answer', $json$"你的回答…"$json$::jsonb),
  ('hi', 'ask.form.send', $json$"जवाब भेजें"$json$::jsonb),
  ('hi', 'ask.form.other', $json$"या अपने शब्दों में जवाब दें…"$json$::jsonb),
  ('hi', 'ask.form.answer', $json$"आपका जवाब…"$json$::jsonb),
  ('ar', 'ask.form.send', $json$"إرسال الإجابات"$json$::jsonb),
  ('ar', 'ask.form.other', $json$"أو أجب بكلماتك…"$json$::jsonb),
  ('ar', 'ask.form.answer', $json$"إجابتك…"$json$::jsonb),
  ('fr', 'ask.form.send', $json$"Envoyer les réponses"$json$::jsonb),
  ('fr', 'ask.form.other', $json$"Ou répondez avec vos mots…"$json$::jsonb),
  ('fr', 'ask.form.answer', $json$"Votre réponse…"$json$::jsonb),
  ('ru', 'ask.form.send', $json$"Отправить ответы"$json$::jsonb),
  ('ru', 'ask.form.other', $json$"Или ответьте своими словами…"$json$::jsonb),
  ('ru', 'ask.form.answer', $json$"Ваш ответ…"$json$::jsonb),
  ('ja', 'ask.form.send', $json$"回答を送信"$json$::jsonb),
  ('ja', 'ask.form.other', $json$"または自分の言葉で回答…"$json$::jsonb),
  ('ja', 'ask.form.answer', $json$"あなたの回答…"$json$::jsonb),
  ('de', 'ask.form.send', $json$"Antworten senden"$json$::jsonb),
  ('de', 'ask.form.other', $json$"Oder antworte mit eigenen Worten…"$json$::jsonb),
  ('de', 'ask.form.answer', $json$"Deine Antwort…"$json$::jsonb)
on conflict (locale, key) do update set value = excluded.value;
